### ISSUE TITLE
Pin Items does not function in Linux

### ISSUE THREAD

**Issue by vbgfhfngfdtyreyt** [hluk/CopyQ#1000]
v3.5.0 tested on Debian 8 and 9 64 bit.

The copyq docs:

https://copyq.readthedocs.io/en/latest/pin-items.html

Says:

> click “Add Actions to Menu and Toolbar”,

But I see:

![copyq error](https://i.imgur.com/1K5eyLx.png)

The shortcuts are there under the shortcuts tab, and pinning does work, but that button is missing for some reason, it was just a little confusing for me.

**Comment by hluk** [comment]
I completely forgot to update documentation after it changed.
