### ISSUE TITLE
CopyQ runs with combination of tiny and huge fonts, being completely unreadable

### ISSUE THREAD

**Issue by mgorny** [hluk/CopyQ#1005]
I've just built CopyQ-3.5.0 from source, and started it from terminal. When I click the tray icon to see the main window, the fonts inside are so tiny I can't read anything. However, if I open any menu (either top menu in the window, or pop-up on tray) the fonts are huge, and the positions look wrong.

I'm attaching a screenshot of the part of the screen with the window. See the window decorations and terminal below for how other app look like on my system. I didn't have any problem like that with any GTK+ or Qt applications before.

![copyq-screen](https://user-images.githubusercontent.com/110765/45474241-852ae580-b739-11e8-909b-b8813752c590.png)

**Comment by mgorny** [comment]
Ok, I'm sorry. Now I see that this is related to this awesome feature of high-DPI support that doesn't account for people having Samsung monitors with completely useless EDID. I'm going to try to find some solution upstream. Or simply finally rid my system of Qt.

**Comment by hluk** [comment]
Yeah, I still have issues with some apps having broken UI because of my high-DPI display.

You can try to some special env variables for Qt before starting the app.

```bash
QT_SCALE_FACTOR=2 QT_AUTO_SCREEN_SCALE_FACTOR=0 copyq
```

There is also `QT_SCREEN_SCALE_FACTORS` for setting different DPI for each screen, in my case I use:

```bash
export QT_SCREEN_SCALE_FACTORS='eDP-1=1;DP-2=1;DP-2-1=1;DP-2-2=1;HDMI-2=2;'
```

**Comment by mgorny** [comment]
I've managed to fix it via overriding broken EDID. If anyone else hits it, feel free to send them over to https://blogs.gentoo.org/mgorny/2018/09/15/overriding-misreported-screen-dimensions-with-kms-backed-drivers/.
