### ISSUE TITLE
Feature request: Search CopyQ with multiple search words, terms, operators

### ISSUE THREAD

**Issue by Clemens-Ratte-Polle** [hluk/CopyQ#1008]
hi
I would love to search exactlier in CopyQ with an option to search for 2 or more terms.
And some operators like +/- would be even more helful :)
thx

**Comment by nmat** [comment]
or use regexp in the search terms? like (something|something2) etc

**Comment by hluk** [comment]
Regular expressions are supported. If you click the magnifier glass icon next to search field you can enable it.

**Comment by stefanoful** [comment]
Hi, is it possible to insert the search and display on which folder tab is the string searched?
using a popup for the tab matching? a FIND ALL .. SEARCH ALL ... 
I using more tab, and search string is  complicate

**Comment by hluk** [comment]
@stefanoful See #486.

[The command is now available in the copyq-commands repo.](https://github.com/hluk/copyq-commands/tree/master/Application#search-all-tabs)
