### ISSUE TITLE
hidpi - popout window seems render oddly

### ISSUE THREAD

**Issue by nmat** [hluk/CopyQ#1009]
This happens on a second monitor on windows 10.

You can see scaling going a bit of for icons etc.

Also noticed the same on scrollbar where it scales off strange.

![image](https://user-images.githubusercontent.com/383031/45669305-f1ce2780-bb1f-11e8-964a-dcfc21fc93b4.png)

Setup I have is:
Laptop connected to dock using USB-C with 2 external monitors. (laptop is using hidpi)

**Comment by nmat** [comment]
This does seem to affect the whole interface if hidpi is being used. Could be QT bug also.

**Comment by hluk** [comment]
I tried to fix the icons in filter field. You can try the new build [here](https://ci.appveyor.com/project/hluk/copyq/build/job/ce9afvk3xn7ocprg/artifacts) (after it's built).
