### ISSUE TITLE
Copy text automatically by selecting it with mouse....

### ISSUE THREAD

**Issue by khari3** [hluk/CopyQ#1010]
Copy text automatically by selecting it with mouse and paste it by middle click button of mouse.

**Comment by hluk** [comment]
Not sure what exactly you mean. Can you be more specific?

**Comment by khari3** [comment]
To copy text what we do -- First we select the text and then right click the mouse to copy.

And what i want is -- By selecting text with mouse,it should get automatically copied,instead of right clicking with mouse and then select copy.
And the copied text shall be pasted anywhere by clicking the middle button of a mouse.

**Comment by hluk** [comment]
If you mean selecting text in any application, that's unlikely to be implemented unless you use X11 on Linux. It would be too difficult to implement on other platforms.

**Comment by khari3** [comment]
Even clipboardmaster a windows app, has this feature.So,it's possible to add this feature

**Comment by hluk** [comment]
I'm not saying it's impossible, just it probably won't be implemented by me. If anyone wants to give it a try, I'm accepting pull requests.

**Comment by hluk** [comment]
> It's a very useful and important feature,why not implement?

It's not that important for me, since it works on X11 out-of-the-box. Also, I would need to spend some time figuring out how to do this on Windows - I don't enjoy going through WinAPI. If you want to give it a try, be my guest.

**Comment by khari3** [comment]
Sir,

Somehow add this feature i request u kindly

**Comment by hluk** [comment]
Qt GUI framework doesn't support binding mouse buttons (globally, from any application). So this would be non-trivial to implement.

You can use a specialized app to bind the mouse button to `copyq paste` command (or to Ctrl+C/Shift+Insert).

Sorry, but I'm closing this since I will be unlikely to implement this feature myself.
