### ISSUE TITLE
Keyboard shortcut for item menu

### ISSUE THREAD

**Issue by reagle** [hluk/CopyQ#1011]
I love that I can keyboard around for most everything, but when it comes to prompting the item menu (so I might select a command) I must move the mouse over to the menu bar and click `item` or alt-click on the item in the history. Is there no keyboard shortcut for this?

**Comment by hluk** [comment]
Does <kbd>Menu</kbd> key or <kbd>Alt</kbd>+<kbd>I</kbd> work?

**Comment by reagle** [comment]
I meant "keyboard around" and have fixed above. I'm not sure what the `menu` key is, but `alt+i` doesn't do anything for me on Mac.

**Comment by hluk** [comment]
How are context menu or main menu items accessed with keyboard on Mac usually?

**Comment by hluk** [comment]
<kbd>Shift</kbd>+<kbd>F10</kbd> is now default, you can change it in Shortcut configuration (search for "Open Item Context Menu").
