### ISSUE TITLE
After switching to larger resolution monitor, copyq icon becomes weird 

### ISSUE THREAD

**Issue by amosbird** [hluk/CopyQ#1014]
![image](https://user-images.githubusercontent.com/5085485/45917632-5b965a80-bead-11e8-912b-3326e7176fdc.png)

Along with all items be gigantic and main window 1.5 times larger

**Comment by hluk** [comment]
That's possibly because some DE or WM issues. You can try setting some environment variables for Qt, e.g.:

```bash
export QT_SCALE_FACTOR=1
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_SCREEN_SCALE_FACTORS=2
export GDK_SCALE=2
copyq
```

**Comment by amosbird** [comment]
It seems to work. Thanks!
