### ISSUE TITLE
Copyq no longer top window upon activation

### ISSUE THREAD

**Issue by morsedl** [hluk/CopyQ#1019]
Hi,

Ever since upgrading from CopyQ 3.4.0 to 3.5.0-1 on Ubuntu 16.04 LTS (in attempt to fix another problem), CopyQ no longer opens as the top window when I activate it with my configured shortcut key (in my case, Ctrl-Alt-C). CopyQ still appears and works fine (except for the other minor process crash annoyance), but not having it activate as the top window means having to switch to it either with the mouse or Alt-Tab before I can work with it.

Minor but ever-present annoyance, as I am keyboard power user.

Unfortunately downgrading to 3.4.0 (all from the official Ubuntu repos) to change the behavior to as it was before the update. I've also tried unchecking and then re-checking "Always on top" in the settings, but this too unfortunately does not reinstate the previous behavior of CopyQ always activating as the top window.

Thanks for making CopyQ available. It's an incredibly useful tool.

Cheers,
Doug

**Comment by hluk** [comment]
This is possibly connected to focus stealing. CopyQ is trying hard to steal window focus with various window managers, but I expect this can fail in some cases.

You can try assigning the shortcut in system instead in the app (assign to `copyq toggle`).

**Comment by morsedl** [comment]
@hluk Thanks Lukas, good to know.

Oddly, after making a quarterly backup of my workstation on Friday, which entailed a reboot, CopyQ is now again grabbing the focus properly. I don't reboot often, so this was fortuitous, and perhaps can be of help to others.
