### ISSUE TITLE
[BUG] Tray context menu partly out side of screen

### ISSUE THREAD

**Issue by huhiha** [hluk/CopyQ#1020]
As you can see:
![_2018-10-07_143647](https://user-images.githubusercontent.com/32677299/46579147-77b60200-ca3e-11e8-895b-3e7591f93f7c.png)

**Comment by nmat** [comment]
Duplicate of https://github.com/hluk/CopyQ/issues/976 this is a QT bug it seems. To verify you can try to click on the middle mouse button on the tray and it will show everything above the taskbar.

**Comment by hluk** [comment]
Closing as duplicate of #976.
