### ISSUE TITLE
[BUG] Next Tab hotkey not working in different language

### ISSUE THREAD

**Issue by huhiha** [hluk/CopyQ#1021]
When I switched language to English, WTF is that? 
![image](https://user-images.githubusercontent.com/32677299/46579186-ff037580-ca3e-11e8-8e6e-8da29be98c60.png)

And these hotkeys just don't work. 
When I switched back to Chinese, those 2 hotkeys still don't work at all.

**Comment by hluk** [comment]
Can you post steps to reproduce this?

**Comment by huhiha** [comment]
My computer language is Chinese. So after it is installed, the default language is Chinese. These words should be "Left" and "Right". 
So the problem is, you are translating something that you shouldn't be translating.

**Comment by hluk** [comment]
I cannot reproduce this, shortcuts are being saved in portable formats (shouldn't depend on OS or language). What is the CopyQ version you use?

**Comment by hluk** [comment]
Oh, nevermind, I managed to reproduce it -- though only with Chinese.

**Comment by hluk** [comment]
Fixed. The problem was that it wasn't clear for translators that the texts (Right/Left) are for shortcuts (I've added comments to clarify that).

Thanks for reporting this.
