### ISSUE TITLE
Using 'write(row, mimeType, data)' function produces empty items in clipboard when selecting text

### ISSUE THREAD

**Issue by rezmir99** [hluk/CopyQ#1023]
I want to use this command to copy clipboard conditional. Using this, only items related to 'clipboard' tab will be copied and nothing will be copied to 'Understand' tab.
Secondly this command produces \<EMPTY\> items in 'clipboard' tab when selecting a text from any app.

```ini
[Command]
Automatic=true
Command="
    bash:
    if [ -e /home/rezmir/.config/copyq/Understand ]; then
     rm -f /home/rezmir/.config/copyq/Understand
     copyq eval \"tab('Understand')
    write('application/x-copyq-item', clipboard('application/x-copyq-item'))
    \"
    else
     copyq eval \"tab('&clipboard')
    write('application/x-copyq-item', clipboard('application/x-copyq-item'))
    \"
    fi
    "
Icon=\xf15b
Input=application/x-copyq-item
Name=Conditional copy
```

**Comment by hluk** [comment]
Not sure if I understand what you want to do. From the command, it seems you store new clipboard content to different tab when a special file exists, otherwise save in the 'clipboard' tab. Is that right?

I made few changes in the command:
- Use COPYQ env variable to get path to current `copyq` executable
- Use `setData(mimeOutputTab, tabName)` in script to set tab to store the new clipboard content (it'll be stored only after all automatic commands are run)

```ini
[Command]
Automatic=true
Command="
    bash:
    if [ -e /home/rezmir/.config/copyq/Understand ]; then
     rm -f /home/rezmir/.config/copyq/Understand
     \"$COPYQ\" \"setData(mimeOutputTab, 'Understand')\"
    else
     \"$COPYQ\" \"setData(mimeOutputTab, '&clipboard')\"
    fi
    "
Icon=\xf15b
Name=Conditional copy
```

**Comment by rezmir99** [comment]
That's exactly what I want and works well.Thanks.
But when I use this new command, another problem arises: everything I copy or even select with mouse , will be copied to '&clipboard' tab, no matter it should be copied or not According to the code.
 The problem is still there even if 'setData()' part of the code is commented out.
Tested on Ubuntu 18.04.1 LTS.

**Comment by hluk** [comment]
Automatic commands are run on mouse selections also. Maybe that's the issue here.

You can check if command is run on clipboard data change with [isClipboard()](https://copyq.readthedocs.io/en/latest/scripting-api.html#bool%20isClipboard).

**Comment by rezmir99** [comment]
That solved my problem.Thanks for your help.
Basically I want to copy to a specific tab with use of keyboard shortcut. First command sets the tab to which the clipboard should be copied:

` [Command]
Command="
    bash: 
    echo 'Understand' > \"$HOME/.config/copyq/tabtocopy\"
    copyq copy
    "
GlobalShortcut=ctrl+shift+u
Icon=\xf15b
IsGlobalShortcut=true
Name=Move to \x201cUnderstand\x201d tab

`
And second command copies to the tab and sets the default tab to '&clipboard':
`[Command]
Automatic=true
Command="
    bash:
    if [ $(\"$COPYQ\" \"isClipboard()\") = 'true' ]; then
     tabtocopy=$(cat $HOME/.config/copyq/tabtocopy 2>/dev/null)
     \"$COPYQ\" \"setData(mimeOutputTab, '${tabtocopy:-&clipboard}')\"
     echo '&clipboard' > \"$HOME/.config/copyq/tabtocopy\"
    fi
    "
Icon=\xf15b
Name=Conditional copy

`
There should be better ways to do that.

**Comment by hluk** [comment]
How about following two commands? First is Script command which adds new function for copying to specific tab and second is command that calls the new function on a global shortcut.

```ini
[Commands]
1\Command="
    // Ignore the option if it was set more than X milliseconds ago.
    var copyTimeLimitMs = 1000
    
    // Option for storing [Date.now(), targetTab]
    // where targetTab is name of the tab to store next copied item.
    var copyNextItemToOption = 'copyToTab'
    
    // New global function to for copying to specific tab.
    global.copyToTab = function(tabName) {
      settings(copyNextItemToOption, [Date.now(), tabName])
      copy()
    }
    
    // Override saveData()
    var saveData_ = saveData
    global.saveData = function() {
      var value = settings(copyNextItemToOption)
      if (value) {
        settings(copyNextItemToOption, [])
    
        copyTime = value[0]
        targetTab = str(value[1])
        if (Date.now() - copyTime < 1000) {
          setData(mimeOutputTab, targetTab)
          popup('Copied to ' + targetTab + ' tab')
        }
      }
    
      // Call original saveData().
      saveData_()
    }"
1\GlobalShortcut=ctrl+shift+u
1\Icon=\xf15b
1\IsScript=true
1\Name=Save next item to Special tab
2\Command="
    copyq copyToTab Understand"
2\GlobalShortcut=ctrl+shift+u
2\Icon=\xf15b
2\IsGlobalShortcut=true
2\Name=Copy to \x201cUnderstand\x201d tab
size=2
```

**Comment by rezmir99** [comment]
Works like a charm. Also the popup is beautiful.
 I was looking for a native solution like this.
Thanks again.
