### ISSUE TITLE
Version number is wrong.

### ISSUE THREAD

**Issue by Achaean** [hluk/CopyQ#1028]
At v.3.6.1, still indicates 3.6.0.
Installed with the DEB package, at Devuan x64 KDE.

**Comment by hluk** [comment]
You mean, one of DEB packages from [here](https://github.com/hluk/CopyQ/releases/tag/v3.6.1)?

Does `copyq --version` print the wrong version?

Can you also check if the `copyq` binary is installed from package with version 3.6.1? (Usually `which copyq` should print `/usr/bin/copyq`.)

**Comment by Achaean** [comment]
> You mean, one of DEB packages from [here](https://github.com/hluk/CopyQ/releases/tag/v3.6.1)?
> 

Yes. copyq_3.6.1_Debian_9.0-1_amd64.deb, installed (as root) with gdebi.

> Does `copyq --version` print the wrong version?
> 

>copyq -v
CopyQ Clipboard Manager v3.6.0
Qt: 5.7.1
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Devuan GNU/Linux ascii
>

> Can you also check if the `copyq` binary is installed from package with version 3.6.1? (Usually `which copyq` should print `/usr/bin/copyq`.)

>which copyq
/usr/local/bin/copyq
>

However, Synaptic reports v.3.6.1-1.

**Comment by hluk** [comment]
`/usr/local/bin/copyq` look like a custom build and not installed by package manager. You may need to uninstall that version. Also check if `/usr/bin/copyq --version` gives you the correct version.

**Comment by Achaean** [comment]
Ooops!!!
My bad! ::-)

Seems like I had compile it from source at past, without removing it before installing the DEB version.
I deleted the /usr/local files and everything is OK now.
