### ISSUE TITLE
Is the Windows Plugin for Syncing still active?

### ISSUE THREAD

**Issue by mbakstars** [hluk/CopyQ#1029]
I was looking how to sync on a Windows machine and found some information in the docs, and it saying that it needs the sync plugin; but I can't find the plugin.

Is the sync plugin still being worked on/available for Windows? [At work have W10Enterprise, 1809 & at home W10 Pro Slow Insider Ring]

I am trying to find a quick easy way to offload/save my images tab, since I am not sure where on my file system they live. I have over 1,300 images that need to be moved. I'm trying to move them from my work pc to my home pc.

**Comment by hluk** [comment]
The plugin should work on Windows. If you install the app using the official installer, you have to select "Synchronize Items to Disk" during the process.

If you can see "Synchronize" under "Items" configuration tab in the app, it should be already installed.

See [the docs](https://copyq.readthedocs.io/en/latest/synchronize.html) for details on how to set it up.
