### ISSUE TITLE
How to force decrypt to ask for password ?

### ISSUE THREAD

**Issue by repsorp** [hluk/CopyQ#1034]
Considering this in "Password Protection":
"You’ll be prompt to enter password in future (you only need to enter it once in a while)"

Is there anyway to force decrypt to ask for password instead of having to wait for an unestimated amount of time ?

Thanks

**Comment by hluk** [comment]
The timeout to unload tab can be specified with "Unload tab after an interval" option in "History" config tab. The password entry agent that gpg uses usually remembers the password for a while (not sure where you can find this configuration).
