### ISSUE TITLE
Issues with tray icon background and font size

### ISSUE THREAD

**Issue by cjbassi** [hluk/CopyQ#1040]
1) The copyq icon in my polbar tray has a black square background around the icon by default, whereas no other icons in the tray have a solid color background.
2) The tooltop text when hovering over the icon is very tiny.

Pic![img_20181110_201952](https://user-images.githubusercontent.com/23287621/48309061-2a89ec00-e526-11e8-8181-1d688c1cab4f.jpg)

Mouse is hidden but it's hovered over the icon.
Thanks!

CopyQ Clipboard Manager v3.7.0
Qt: 5.11.2
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Arch Linux

Installed from the `copyq` aur package.

polybar version: 3.2.0-26-g11d66ee

**Comment by hluk** [comment]
CopyQ doesn't set the tool tip appearance. This is an issue of underlying system (either Qt, Gtk or the desktop environment) and it's quite common in Qt apps.
