### ISSUE TITLE
CopyQ 3.7.1 can use in English language only.

### ISSUE THREAD

**Issue by sicklylife-jp** [hluk/CopyQ#1043]
OS: Ubuntu 18.04, 18.10
Language: Japanese

**Screenshot**

![screenshot from 2018-11-19 20-57-33](https://user-images.githubusercontent.com/43719368/48706096-7af7fc80-ec3e-11e8-8343-e67edaffa488.png)

**Comment by hluk** [comment]
Can you try installing `qttranslations5-l10n`? Maybe translation files are installed with Qt 5 framework by default anymore.

```bash
sudo apt install qttranslations5-l10n
```

**Comment by sicklylife-jp** [comment]
> qttranslations5-l10n

Package qttranslations5-l10n is already installed on my PC since before.

I found that CopyQ 3.7.1's CMakeLists.txt has this bug.
Please downgrade CMakeLists.txt to the previous version.

**Patch**

[CMakeLists.diff.txt](https://github.com/hluk/CopyQ/files/2599483/CMakeLists.diff.txt)

**Screenshot (CopyQ version 3.7.1-0+sicklylife~ppa1)**

copyq (3.7.1-0+sicklylife~ppa1) : [https://launchpad.net/~sicklylife/+archive/ubuntu/testing/+sourcepub/9597966/+listing-archive-extra](https://launchpad.net/~sicklylife/+archive/ubuntu/testing/+sourcepub/9597966/+listing-archive-extra)

![2018-11-20_19-54](https://user-images.githubusercontent.com/43719368/48770870-16eb3c00-ed03-11e8-946e-789e8ef5ee80.png)

**Comment by hluk** [comment]
Oh, OK, now I understand what's wrong - the new paths defined in `CMakeLists.txt` are not absolute.

Fixing. Thanks for the details.
