### ISSUE TITLE
Fails to Import

### ISSUE THREAD

**Issue by mbakstars** [hluk/CopyQ#1044]
I backup up my CopyQ install & tabs ever night to a cloud drive before leaving work; should I need to use any of the text at home. I ended up having a corrupted user profile today and had to create a new one. I just tried importing from my exported backup and it errors out. Saying failed to import. The file 0KB which I hadn't noticed until now, and most of the updates for the last few months have been this size through different versions.  Windows 10 Enterprise, 1809.

Thanks for your assistance. =) Please let me know if this is user error.

**Comment by hluk** [comment]
Can you provide steps to reproduce it?

**Comment by mbakstars** [comment]
Trying now with new profile, newest version of W CopyQ, and vanilla install. I normally just go to export, chose my OneDrive (thru Uni) folder, select a previous file to get the naming, and then update a few characters.

This time I got a file, and had more that 0KB. In the past, the program would exit, which now that I think about it, was most likely a crash. 

If you would like I can try to recreate my previous setup, and see if it still does it? I had a TON of data stored. Images were syncing and going to a different tab. But still had quite a bit of data. I might a somewhat (not sure how recent, but still a good chunk of data) copy of it on my home pc (usually using at work).
