### ISSUE TITLE
automatic command is not triggered

### ISSUE THREAD

**Issue by amosbird** [hluk/CopyQ#1045]
When directly doing ` maim -s | copyq write image/png -`, this automatic command isn't get triggered

```
[Command]
Automatic=true
Command="
    copyq:
    var imageDir = Dir().homePath() + '/Pictures/Screenshots/'
    var imageFileName = 'copied-' + dateString('yyyy-MM-dd-HH_mm_ss') + '.png'
    var imagePath = imageDir + '/' + imageFileName
    
    
    if (!Dir().mkpath(imageDir)) {
      popup('Failed to create directory for images')
      abort()
    }
    
    var f = new File(imagePath)
    if (!f.openWriteOnly() || f.write(input()) == -1) {
      popup('Failed to save image', f.errorString())
      abort()
    }
    f.close()
    
    notes = [
      '[[file:' + imagePath + ']]',
      imagePath
    ]
    setData(mimeItemNotes, notes.join('\\n'))"
Icon=\xf03e
Input=image/png
Name=Save Copied Images

```

**Comment by hluk** [comment]
Automatic commands are only triggered when clipboard changes externally. Also `copyq write ...` only stores the data in the default tab.

**Comment by amosbird** [comment]
Ok, anyway I can trigger that explicitly?

**Comment by hluk** [comment]
> Ok, anyway I can trigger that explicitly? Or is there a way to put the png file directly into the clipboard?

Triggering it manually would be a bit difficult - there is no functionality that directly supports it (though you have access to all commands in CopyQ scripts).

To copy the image directly, just use `copy` instead of `write` in your command (`... | copyq copy image/png -`).

**Comment by amosbird** [comment]
`maim -s | copyq copy image/png -` doesn't work. No image shows in copyq window

**Comment by amosbird** [comment]
This works : `  maim -s | xclip -selection clipboard -t image/png`

**Comment by hluk** [comment]
`copyq copy` just copies the data without storing it. To both store and copy you can do:

```bash
maim -s | copyq 'format="image/png"; copy(format, input()); write(format, input())'
```
