### ISSUE TITLE
Pasted item not matching selected one from context menu

### ISSUE THREAD

**Issue by orschiro** [hluk/CopyQ#1046]
Hi all, 

Can anyone reproduce the problem by which CopyQ is not pasting the selected item from the context menu but a different one?

I recorded [this video](https://drive.google.com/file/d/1My0J0pZ8ZuV5aZ_XQ2iSXIAq0YyNxeG1/view) for you. 

Much appreciated!

Yours

**Comment by hluk** [comment]
Does this work in other apps or fields on web pages?

Can you try pressing Shift+Insert again (that's what CopyQ uses to paste the content)?

**Comment by orschiro** [comment]
The problem is that it doesn't always happen. I will monitor this and see if I can reliably reproduce it!

**Comment by orschiro** [comment]
OK, it just occurred again and pressing Shift while selecting an entry from the context menu causes the same problem.

**Comment by hluk** [comment]
Maybe the target app is misbehaving (web app or browser). I don't cannot reproduce this issue anywhere.

**Comment by scottkosty** [comment]
I think I have seen this before. I will try to keep an eye out for it and in what settings I see it occur and try to reproduce. It might take me a while to narrow it down though since I only see it once in a while.

@orschiro did this start happening only with recent versions of CopyQ? The issue I have in mind has been happening for a while.

**Comment by orschiro** [comment]
@scottkosty good question. Honestly I don't know. I will report back if I find any more information about this issue. Thanks for your help!

**Comment by orschiro** [comment]
Dear @scottkosty and @hluk, 

Once the bug occurs and the wrong element is pasted, I can press Ctrl + Z to undo the paste and then press Ctrl + Shift + V to paste the correct entry. 

Interesting find, right?

**Comment by hluk** [comment]
> Once the bug occurs and the wrong element is pasted, I can press Ctrl + Z to undo the paste and then press Ctrl + Shift + V to paste the correct entry.

It looks like the target application still sees the old clipboard content when CopyQ generates Shift+Insert.

You can add a delay when pasting from main window (see [this comment](https://github.com/hluk/CopyQ/issues/562#issuecomment-257385689)).

**Comment by orschiro** [comment]
@hluk thanks! Target application is Chrome, shall that matter. 

Yours
