### ISSUE TITLE
Copyq on startup does not minimize

### ISSUE THREAD

**Issue by dreamwhite** [hluk/CopyQ#1048]
Using: 

```
CopyQ Clipboard Manager v3.7.1
Qt: 5.9.5
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Ubuntu 18.04.1 LTS
```

I've added via Startup Application Copyq. The issue is that if I login, copyq does not minimize in systray. To fix that I need to close copyq via ctrl+q at the startup and then reopen it. Please fix it

**Comment by hluk** [comment]
Maybe CopyQ starts before it can minimize to tray or with window manager (there is some detection logic in the app).

See if the behavior is fixed after enabling "Hide main window" in Layout configuration tab in CopyQ (or with command `copyq config hide_main_window 1`).

**Comment by dreamwhite** [comment]
Dear @hluk, I've tried such as you suggested. It works, but I don't see the CopyQ icon in the systray. It's like that, when I've submitted this issue, CopyQ tries to load itself before the Window Manager and presents this bug. It's a little bit annoying. In any case ily the Copyq project :)

**Comment by hluk** [comment]
What's your window manager and desktop environment?

There are lot of issues with the tray icon (just search the issues). I use Qt framework to handle the icon. I should probably drop the tray support since it's so broken and every environment is handling it its own way. :(

**Comment by dreamwhite** [comment]
I'm using:

CopyQ Clipboard Manager v3.7.1
Qt: 5.9.5
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Ubuntu 18.04.1 LTS with Gnome DE


Il giorno Mer 12 Dic 2018, 12:42 PM Lukas Holecek <notifications@github.com>
ha scritto:
