### ISSUE TITLE
Clipboard window greyed out on second open - Manjaro Linux

### ISSUE THREAD

**Issue by jonpatterns** [hluk/CopyQ#1049]
I'm using Manjaro Linux with XFCE desktop.

Left-clicking on copyq opens the main clipboard window correctly; if done once.

However, if I move and close the window, then left-click on copyq for a second time the clipboard window is greyed out (the tabs show but not the clipboard area).

Note, sometimes the clipboard window can be opened and moved twice; but never a third time without becoming greyed out.

The is a new bug that did not used to happen on the previous version. Currently I'm using v3.5.0.

Thread on Manjaro forum has some additional information.

---

Quiting and restart copyq gives the same functionally (main clipboard window may only be opened once or twice before becoming greyed out).

https://forum.manjaro.org/t/copyq-3-5-0-not-working-well-after-update/52272

**Comment by hluk** [comment]
That's an old issue resolved in more recent releases.
