### ISSUE TITLE
Anyone know how I could detect Russian?

### ISSUE THREAD

**Issue by mishaxz** [hluk/CopyQ#1050]
I created a command to open text in the browser (google translate url)

I would like to be able to automate this so that it can detect any Russian pasted to the clipboard and automatically open this google translate URL.

So would anyone know how I could do the automatically detect Russian (cyrillic) part? I'm not concerned with any other Cyrillic languages so as long as the text is in Cyrillic, we can assume it is Russian.

**Comment by hluk** [comment]
Here are some helper functions:

```ini
[Command]
Automatic=true
Command="
    copyq:
    function isCyrillicCharCode(charCode) {
      return 0x0400 <= charCode && charCode <= 0x4FF
    }
    
    function isCyrillicChar(chr) {
      return isCyrillicCharCode(chr.charCodeAt(0))
    }
    
    function isCyrillicText(text) {
      return text.split('').some(isCyrillicChar)
    }
    
    var text = str(input())
    if (isCyrillicText(text)) {
      popup('Cyrillic detected')
    }"
Icon=\xf024
Input=text/plain
Name=Cyrillic Copied
```

**Comment by mishaxz** [comment]
thank you very much!
