### ISSUE TITLE
Cannot delete just one character hitting backspace in context menu

### ISSUE THREAD

**Issue by orschiro** [hluk/CopyQ#1052]
Dear all, 

Please correct me if this is intended and not a bug. 

However; I expected being able to delete a single character hitting backspace when searching from the context menu. Instead, it deletes the entire word.

Could you shed some light on this for me, please?

Much appreciated!

Yours

**Comment by hluk** [comment]
Yeah, that was done by design since Esc key won't clear the search as in main window (it closes the menu instead), I set the Backspace key to clear the search.

I'm OK with changing the behavior if it's unexpected or annoying.

**Comment by orschiro** [comment]
Dear @hluk, 

Thanks for elaborating. 

> I'm OK with changing the behavior if it's unexpected or annoying.

For me it certainly was unexpected and partially annoying. 

Can anyone else comment please and share their opinion?

Much appreciated!

Yours

**Comment by hluk** [comment]
@orschiro Fixed. To clear the search you can use Delete key (though there is no indication in UI that it can be used like that).

**Comment by orschiro** [comment]
@hluk thanks for providing this quick fix!

Much appreciated.

Yours
