### ISSUE TITLE
Dark theme not applied to context menu

### ISSUE THREAD

**Issue by orschiro** [hluk/CopyQ#1055]
Dear all, 

I applied the dark theme as you can see below but it's not being considered for the tray icon context menu. 

Is this a bug or can't the tray icon context menu not be customised?

Much appreciate your advise. 

Yours

![image](https://user-images.githubusercontent.com/170947/49578444-0d401600-f94a-11e8-8835-e2692c280a52.png)

**Comment by hluk** [comment]
Yup, the theme is not applied to tray menu. Tray menus are usually handled by the desktop environment (Gnome, Unity, KDE, OS X ...) so I don't have control over the style of the menu most of the time.

I might be implement this only for the menu which opens on global shortcut (i.e. `copyq menu` command) but the style would be inconsistent with the tray icon menu (well, it already is inconsistent, since the tray menu is missing search field).

**Comment by orschiro** [comment]
@hluk thanks! Much appreciated. 

Then I need to figure out why my chosen Xfce GTK Dark Theme (Arc-Dark) is not applied to CopyQ (since it's a Qt app).

![image](https://user-images.githubusercontent.com/170947/49581831-81cb8280-f953-11e8-982e-7f4828917b0a.png)

If anyone has an idea what I can try, much welcome. 

I guess we shall close this issue as invalid then?

Yours

**Comment by hluk** [comment]
To style Qt apps, I use `qt5ct`. Details are on [Arch Linux wiki](https://wiki.archlinux.org/index.php/Qt#Configuration_of_Qt5_apps_under_environments_other_than_KDE_Plasma).

**Comment by orschiro** [comment]
Brilliant! That mostly did it. Now I just need to find the right font configuration to fix this blurry bold font.

![image](https://user-images.githubusercontent.com/170947/49582721-35357680-f956-11e8-96d4-036feff70b9e.png)

![image](https://user-images.githubusercontent.com/170947/49582762-55fdcc00-f956-11e8-969d-48522f65661a.png)

**Comment by hluk** [comment]
You can try changing style in Style Sheets tab in `qt5ct`.

Click create button there, enter some name like "fix-disabled-menu-item-color", click Edit and enter following code (change the color code).

```css
QMenu:item:disabled { color: #ff0000 }
```

(You can use `TrayMenu` instead of `QMenu` to be more specific.)

**Comment by orschiro** [comment]
@hluk thanks but this is not really what I wanted. Your color codes changed the color to red. 

I just want to remove this blurry font for "Type to search". 

But this is just a minor issue.

I can live with it if there is no fix for that. :-)

Already much appreciate your help!

Yours
