### ISSUE TITLE
closed and reopen no items on main interface

### ISSUE THREAD

**Issue by Novite5** [hluk/CopyQ#1056]
displays as the pic:
![image](https://user-images.githubusercontent.com/16817335/49979397-cd9cae00-ff89-11e8-9ef5-da60b907cfd2.png)
exit main windows with "ESC" is OK.

And after recent update cannot change theme and translations in the setting.

My OS is archlinux with Gnome. 
CopyQ version 3.7.1

in copyq log only found this:
`
Warning [2018-12-10 10:26:07.452] <Server-888>: CopyQ server is already running.
`

**Comment by hluk** [comment]
I think this is bug in Qt. I implemented a workaround for this in #989. No idea what else to do about it.

Try updating Qt libraries and rebuilt CopyQ. You can also try changing or disabling the theme in CopyQ (Appearance configuration tab).
