### ISSUE TITLE
Possible issue with global shortcut

### ISSUE THREAD

**Issue by hetdegon** [hluk/CopyQ#1058]
OS: Ubuntu 18.10 64bit
CopyQ version: 3.7.1
Command:
```
[Command]
Command="
    dlmanager queue %1"
GlobalShortcut=meta+w
Icon=\xf218
InMenu=true
Input=text/plain
IsGlobalShortcut=true
Match=^(http|https?|ftps?|file)://
Name=dlmanager

```
I don't know if there's an issue with copyq or I am doing something wrong.
I tried setting a command to copy an URL and send it to an an external application with a keypress.
The command works fine if set as a menu action, or from adding that same command in the F5 dialog, but when invoked using a global shortcut, nothing happens. The action is marked as complete in the process manager, but the command certainly doesn't activate, and I can't seem to get any debug output to see if it's malformed input or something, and doing something like "echo mycommand myparameter %1" doesn't leave a trace in xsession-errors or anything visible by journalctl either (or stdout when invoking copyq from console).
The tray icon does respond to the key combination (meta+w, the scissors close) but nothing happens at all otherwise. Other global shortcuts work normally (like meta+q to show the main window).

**Comment by hluk** [comment]
The `%1` in the command will be empty if triggered by global shortcut. You would need to get the text from clipboard first, e.g. with `copyq clipboard`.

```ini
[Command]
Command="
    copyq:
    execute('dlmanager', 'queue', clipboard())"
GlobalShortcut=meta+w
Icon=\xf218
InMenu=true
Input=text/plain
IsGlobalShortcut=true
Match=^(http|https?|ftps?|file)://
Name=dlmanager
```

**Comment by hetdegon** [comment]
Ah, I understand, I failed to see any mention of this.
So user error it is, I'll be closing it. Thank you for the solution.
