### ISSUE TITLE
Unwanted behavior from selection monitoring and auto actions

### ISSUE THREAD

**Issue by hetdegon** [hluk/CopyQ#1059]
OS: Ubuntu 17.10 64bit
CopyQ version: 3.7.1
Related to: #1042

I've noticed that when selection processing is disabled, like this
![out5](https://user-images.githubusercontent.com/323651/50323792-b276f480-04db-11e9-866c-257f5e28f68b.png)
selecting text still fires onClipboardChanged events regardless, for example this action
```
[Command]
Automatic=true
Command="dlmanager auto \"%1\""
Icon=\xf218
Input=text/plain
Match=^\\[.dlman.\\](http|https?|ftps?|file)://
Name=autoqueue
Remove=true
```
just selecting text that matches the regex will trigger the automatic action, even if the options are set as shown in the screenshot above.

Could it be possible to disable the automatic actions on selection when selection storage is disabled? Or at least some action setting to only fire the automatic action if it actually enters a copyq tab?

For some background I'm trying to replace Firefox's old FlashGot functionality (that allowed to send a link to a download manager of choice), but this functionality was removed in FF57+, so I moved to Chromium because FF56 is already too old to use daily. So I wrote a Chrome extension to add a tag to a right-clicked link so copyq can process it and do the work instead. However, Chrome doesn't have a proper usable clipboard API, so copying a link implies a selection and then copying, so it fires the command twice, which during debugging showed this unwanted behavior (thankfully the process manager helped everything!).

**Comment by hluk** [comment]
Automatic commands are triggered on both clipboard and selection and the options in screenshot above only change additional behavior (creating new items and synchronizing clipboard/selection).

To disable running commands when selection changes you can use following command which overrides `runAutomaticCommands()` function.

```ini
[Command]
Command="
    runAutomaticCommands_ = runAutomaticCommands
    runAutomaticCommands = function() {
        return isClipboard() && runAutomaticCommands_()
    }"
Icon=\xf246
IsScript=true
Name=No Automatic Commands for Selection
```

**Comment by hetdegon** [comment]
Interesting. Would it be possible to fine-tune this? Like not running selection commands if current window is chrome/chromium, or is it an all-or-nothing approach?

**Comment by hluk** [comment]
You can use `currentWindowTitle()`. (If the command below doesn't work, try changing the regular expression `/Chromium$|Chrome$/` to match the window titles.)

```ini
[Command]
Command="
    runAutomaticCommands_ = runAutomaticCommands
    runAutomaticCommands = function() {
        if ( !isClipboard() && currentWindowTitle().match(/Chromium$|Chrome$/) )
            return false;
        return runAutomaticCommands_()
    }"
Icon=\xf246
IsScript=true
Name=No Automatic Commands for Selection
```

**Comment by hetdegon** [comment]
Thank you very much! I tested it thoroughly and everything works as expected now.
