### ISSUE TITLE
Items are blank for a little while when scrolling on macOS

### ISSUE THREAD

**Issue by RoadToDream** [hluk/CopyQ#1060]
Items are blank for a little while when scrolling on macOS. Would you consider a more aggressive strategy of cache?

**Comment by scottkosty** [comment]
@RoadToDream thanks for opening this issue. What are your CopyQ version and OS version? (these are always helpful to give when providing a bug report).

**Comment by scottkosty** [comment]
@RoadToDream Thanks! I see something similar, but the blanks only last very little time (i.e., I didn't even notice it before I looked for it). For you they last longer for some reason. However, my guess is that they are necessary: it would not be a good idea to load all of those images for your entire history. That would take up a lot of memory (and unneeded I/O). I wonder if HD/SSD speed matters for this. I'm guessing that the images are read from your file system and loaded into memory as-needed.

Just for reference, I'm on Ubuntu 18.04.

**Comment by hluk** [comment]
I'm trying to improve the way the items are cached. Unfortunately, I wasn't able to reproduce the smooth scrolling in the app.

Can you test [this pre-release](https://github.com/hluk/CopyQ/releases/tag/v3.7.2-beta-scroll-update-fix)? Let me know if it's better.

**Comment by RoadToDream** [comment]
Sorry for the late reply, I am catching the deadlines at the end of semester. 
I'll give it a try after I have finished my exams. 
Thanks for your respond!

**Comment by hluk** [comment]
> Sorry for the late reply, I am catching the deadlines at the end of semester.
> I'll give it a try after I have finished my exams.
> Thanks for your respond!

No problem. You can now use the latest version of the app to test it (no need to use the pre-release).

Good luck with your exams!

**Comment by RoadToDream** [comment]
@hluk Thank you very much.
I'll try it right now.

**Comment by RoadToDream** [comment]
@hluk The latest release perfectly fixes the problem. Thanks for that!
