### ISSUE TITLE
Clear clipboard on exit

### ISSUE THREAD

**Issue by ricardogaspar2** [hluk/CopyQ#1063]
Feature Request: create an option that allows to specify that the clipboard history has to be deleted when the program is being closed/shutdown.

**Comment by hluk** [comment]
You can keep the tab content only in memory if you set empty [synchronization path](https://copyq.readthedocs.io/en/latest/synchronize.html) for it.

One problem is that it will also get cleaned after the "unload tabs" interval specified in configuration. You can set it to 0, but it works for all tabs and it's nice to have this set if you use many items and tabs to free some memory.

![image](https://user-images.githubusercontent.com/38054/52534863-0917e680-2d47-11e9-8308-1ab14f969dea.png)

To implement this properly, I think I would need to implement tab-specific configuration with some nice UI.

**Comment by akwala** [comment]
I remember discussing this years ago. See #59 which came out of the following thread:
https://github.com/hluk/CopyQ/issues/55#issuecomment-18924890

I control the life of and access to saved clipboard items by setting a maximum limit for the number of saved items, encrypting the clipboard history tab and setting the interval after which tabs unload.

**Comment by hluk** [comment]
@akwala Thanks for reminding me about #59. I think it can be now easily implemented adding new script functions -- the new "script" commands can override them. I just hope that won't affect performance badly.

One problem is that running anything on application exit can be unreliable. The app can be killed or crash and your exit-code won't be executed.

**Comment by Gitoffthelawn** [comment]
I need this functionality as well.

I tried the workaround by @hluk (thank you!), and to help others that might try it I want to mention that the default clipboard is `&clipboard` and not `clipboard`.

IOW, you need to sync `&clipboard` with nothing for the default clipboard contents to be erased with the copyq session is terminated.

Hopefully this functionality will be integrated without needing the workaround. :)

**Comment by Gitoffthelawn** [comment]
I see this issue is now closed.  :) How is this functionality enabled without using the "empty sync path" trick?

**Comment by hluk** [comment]
@Gitoffthelawn You can now disable storing items to disk for specific tabs:

1. open configuration,
2. go to Tabs configuration tab,
3. select a tab from list,
4. disable "Store Items" checkbox,
5. apply configuration.

**Comment by Gitoffthelawn** [comment]
Thank you so much!  I had a hunch that was it, but I wasn't sure. :)

Once the "Store Items" checkbox is disabled (unchecked), can I disable syncing with an empty path?

**Comment by hluk** [comment]
> Once the "Store Items" checkbox is disabled (unchecked), can I disable syncing with an empty path?

Yup, no need for the workaround anymore.

**Comment by Gitoffthelawn** [comment]
Thank you! :)

**Comment by KaKi87** [comment]
Hello,

> go to Tabs configuration tab, select a tab from list, disable "Store Items" checkbox

Where's that setting now ?

Thanks

**Comment by hluk** [comment]
The option is still in the Tabs config tab -- but it was renamed to "Save Items".

**Comment by KaKi87** [comment]
Here are the configuration tabs I see : general, layout, history, tray, notifications, items, shortcuts, appearance.
I see no "tabs" tab
Thanks

**Comment by hluk** [comment]
@KaKi87 You need to install more recent version of CopyQ.

**Comment by KaKi87** [comment]
I'm using Linux Mint 19.3 and APT installed me version 3.2.0.1

**Comment by hluk** [comment]
@KaKi87 Maybe you can get newer version from PPA or using Flatpak?

See: https://copyq.readthedocs.io/en/latest/installation.html

**Comment by KaKi87** [comment]
It worked, thanks !
However, I've seen packages firstly requiring a PPA and then not requiring it anymore, but never the other way around.
Why did it changed ?
Thanks

**Comment by hubyhuby** [comment]
I am using 6.0.1 so unsure if the feature as been added.
I cannot make it work . Security is a big concern, you don t want a copy past password to be there ;)
So I believe it could even be the default behaviour, not to keep the information betwen sessions or when closed... 
ALso in french the wording here is unclear , where is it recorded ? rto disk to memory ? ;) ![image](https://github.com/hluk/CopyQ/assets/26340942/b6c2c1db-a9ed-45cc-b3d2-0ec46a336ff0)

Here is a screen of what I would need. Maybe it is already there and I don t understand : 
Would be nice to be able to set 10 000 minutes (a week)
![image](https://github.com/hluk/CopyQ/assets/26340942/efad88dc-4da2-4f70-9540-e21f88482236)

**Comment by luckylittle** [comment]
The highest I could get the `Unload tab after an interval in minutes` in v`7.0.0` is 480 (equals to 8 hours)

**Comment by hluk** [comment]
Items are stored unencrypted on disk by default. Recently used tabs/items are also loaded in the main memory.

Some safety features and commands you can use:
- Set the unload interval globally or for specific tabs (only drops the items data from the main memory)
- [Store encrypted items/tabs](https://copyq.readthedocs.io/en/latest/password-protection.html)
- [Avoid storing clipboard from specific apps](https://copyq.readthedocs.io/en/latest/faq.html#faq-ignore-password-manager)
- Use [Synchronization](https://copyq.readthedocs.io/en/latest/synchronize.html) but set empty Path for the tab so it is kept only in the main memory and cleared in intervals and on exit
- [Blocklisted Texts](https://github.com/hluk/copyq-commands/blob/master/Scripts/blocklisted_texts.ini) - Manually select which clipboard texts to ignore
- [Clear Clipboard After Interval](https://github.com/hluk/copyq-commands/blob/master/Scripts/clear-clipboard-after-interval.ini)
- [No Clipboard in Title and Tool Tip](https://github.com/hluk/copyq-commands/blob/master/Scripts/no-clipboard-in-title-and-tooltip.ini)
- [Copy a Secret If a Modifier Held](https://github.com/hluk/copyq-commands/blob/master/Automatic/copy-a-secret-if-modifier-held.ini)
- [KeePassXC protector](https://github.com/hluk/copyq-commands/blob/master/Automatic/keepassxc-protector.ini)

See also: https://copyq.readthedocs.io/en/latest/security.html

**Comment by Gitoffthelawn** [comment]
In addition to what @hluk just posted, people who haven't read this entire thread may find it helpful to see also:

https://github.com/hluk/CopyQ/issues/1063#issuecomment-549231239
