### ISSUE TITLE
tried to install using _deb file, failed on libqt5svg5 as it needs a 5.6.0-beta 

### ISSUE THREAD

**Issue by rharing** [hluk/CopyQ#1067]
sudo apt-get install libqt5svg5
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libqt5svg5 is already the newest version (5.5.1-2build1).
The following package was automatically installed and is no longer required:
  libqt5script5
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 35 not upgraded.

**Comment by hluk** [comment]
Which deb file do you mean? What is the distro?
