### ISSUE TITLE
CopyQ 3.7.2 failed to open UI on Fedora 29

### ISSUE THREAD

**Issue by icycandy** [hluk/CopyQ#1069]
![4](https://user-images.githubusercontent.com/724257/51095651-44c79b00-17f1-11e9-83e9-b6ec188c41dc.gif)

As you can see from the gif, CopyQ 3.7.2 failed to launch on Fedora 29, CopyQ 3.6.1 is OK.

**Comment by hluk** [comment]
Can you open the app from tray?

**Comment by gbcox** [comment]
copyq --help

copyq without any parameters will open the server and place an icon in the tray
to get the menu, either open from tray or enter copyq --menu

**Comment by icycandy** [comment]
@hluk Can't open V3.7.2 from tray. The server is started, because I can see the copyq process. But can't see the UI.
```bash
[candy@f29 ~]$ ps fx | grep copyq
 2697 tty2     Sl+    0:00      |   \_ copyq
 2724 tty2     Sl+    0:00      |       \_ /usr/bin/copyq monitorClipboard
 2797 pts/0    S+     0:00  |   |   \_ grep --color=auto copyq
```

@gbcox 
```bash
[candy@f29 ~]$ copyq --menu
NaN
```

**Comment by hluk** [comment]
Command to show the main window is `copyq show`; to show menu use `copyq menu`.

**Comment by icycandy** [comment]
> 
> 
> Command to show the main window is `copyq show`; to show menu use `copyq menu`.

I tried `copyq show` and `copyq menu` with version 3.7.2, both successfully opend the UI.
So maybe the problem is that plain `copyq` command is not invoke the sub command `copyq show`?

**Comment by gbcox** [comment]
> Command to show the main window is `copyq show`; to show menu use `copyq menu`.

oops - sorry about the typo

**Comment by gbcox** [comment]
> > Command to show the main window is `copyq show`; to show menu use `copyq menu`.
> 
> I tried `copyq show` and `copyq menu` with version 3.7.2, both successfully opend the UI.
> So maybe the problem is that plain `copyq` command is not invoke the sub command `copyq show`?

No, copyq is also designed to work in scripts, and that being the case you don't always want the UI displayed.  Review the documentation.

**Comment by wes-novack** [comment]
Similar issue here, copyq fails to display the UI or run the server.

```
$ copyq --version
CopyQ Clipboard Manager v3.9.2
Qt: 5.11.3
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Fedora 29 (Workstation Edition)
$ uname -a
Linux ps-notebook 5.2.11-100.fc29.x86_64 #1 SMP Thu Aug 29 12:52:22 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by hluk** [comment]
@icycandy Is this still an issue? If so, can you provides steps to reproduce? (BTW, the gif is too long and there is no way to skip forward -- better to use a video.)

I'll close this for now.
