### ISSUE TITLE
Resolution big sized in second screen

### ISSUE THREAD

**Issue by rafaeldev** [hluk/CopyQ#1072]
**Describe the bug**
Resolution super-sized when opened in second screen with *1920X1080*

**To Reproduce**
1. Open "settings pane on second screen"

**Expected behavior**
Which the size is much more big then first size.

**Screenshots**
Notebook Dell screen:
![image](https://user-images.githubusercontent.com/4596160/51605438-33b81180-1ef6-11e9-9e89-235c628e09a0.png)

![image](https://user-images.githubusercontent.com/4596160/51605475-52b6a380-1ef6-11e9-9357-875c3c18691e.png)

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Application Version v3.4.0
 - Deepin OS 15.9
 - Desktop environment

**Additional context**
My second screen is a _TV/Monitor LCD 24 Samsung P2470HN Full HD_

**Comment by hluk** [comment]
The monitor is probably providing wrong information about DPI/resolution. See #1005.

Try running `QT_SCREEN_SCALE_FACTORS=1 copyq` from console.

**Comment by rafaeldev** [comment]
With value `1` the size continous very big but when run with value `3` the size was very good!

**Comment by hluk** [comment]
Here are the values I use so that Qt apps on my laptop and 4k display look sane:

```
QT_AUTO_SCREEN_SCALE_FACTOR=1
QT_SCALE_FACTOR=1
QT_SCREEN_SCALE_FACTORS='eDP-1=1;DP-2=1;DP-2-1=1;DP-2-2=1;HDMI-2=2;'
```

`QT_SCREEN_SCALE_FACTORS` can contain list of factors for each display (the names can be listed with `xrandr`).
