### ISSUE TITLE
Clear search field when main window closes/hides

### ISSUE THREAD

**Issue by hluk** [hluk/CopyQ#1074]
Showing old search is unexpected when main window reopens.

**Comment by ilcasco-hectora** [comment]
As a workaround, while this new feature is implemented, in CopyQ Commands paste the following commands:

```
[Command]
Command="
  copyq:
  filter('')
  selectItems(0)
  toggle()"
GlobalShortcut=ctrl+shift+alt+v
Icon=\xf022
IsGlobalShortcut=true
Name=Show/hide main window
```

Change the _GlobalShortcut_ accordingly.

Thanks to @hluk for his kind help. Now CopyQ is even more efficient. Hoping to see this implemented soon.
Greetings.
