### ISSUE TITLE
how to filter specific tagged items like tagged important?

### ISSUE THREAD

**Issue by snowman** [hluk/CopyQ#1075]
i have thousands of different category items, i want to quick access to those tagged items like `agenda` or `contact` or `todo`

**Comment by hluk** [comment]
You can simply type the tag name to search for it.

**Comment by balalaXD** [comment]
Yeah it only work when select `Edit menu > Find` from `copyq show`, but when i run `copyq menu` type text to search tag-keyword not work.

**Comment by balalaXD** [comment]
Currently i bind `Ctrl-f` => `copyq menu`, otherwise bind keys => `copyq show` instead but may consume some screen space.
