### ISSUE TITLE
improved address copy and paste workflow

### ISSUE THREAD

**Issue by herrdeh** [hluk/CopyQ#1076]
As copyQ seems not to have a forum, I'm abusing the bug tracker for a workflow request. Apologies in advance for that.

Very often I have to copy from an email ```<prename>, <surname>, <street>, <house number>, <post code>, <name_of_city>, <country>``` and paste ```<prename>, <surname>, <street>, <house number>, <post code>, <name_of_city>, <country>``` into a web form of a parcel service.

Or I copy ```<name>, <iban>, <sum>, <bill-number>``` from an invoice to a online banking form.

Or think of contact data in an email signature, going into your PIM's address book.,

I searched copyQ docu for ideas for a workflow, but could not get a clou. 
An idea to operate this could be:

1. double-click (with some modifier key(s) pressed) the strings in the source window, copying them to copyQ's items list
2. open copyQ's saved items list manually
3. (nice-to-have): open copyQ's saved items list automatically when <modifier-double click> is received
4. switch to the target window manually
5. paste the first list entry with some keyboard shortcut into the first field and do a TAB afterwards; select the next item from the copyQ list automatically
6. do manual TAB or Shift-TAB if necessary
7. paste the next list entry with some keyboard shortcut into the next field and do a TAB afterwards; select the next item from the copy list
8. repeat step 7. till all fields are filled
9. close copyQ's copied items list

How could that be achieved? - I guess, everybody has got the tasks above regularly, so it may be useful to have a HOWTO for that. I'll be happy to write this HOWTO when I get an idea I can understand.

**Comment by hluk** [comment]
This sounds like what "Paste and copy next" command is doing (you can assign shortcut in configuration).

Issue #597 could be also related.

**Comment by herrdeh** [comment]
Thank you for your thoughts.
"Paste and copy next" indeed does quite a lot what I want when it comes to the "paste" part of the procedure. Could I save a command "paste - hit TAB and copy next" ?

I could not really understand what [https://github.com/hluk/CopyQ/issues/597](url) is all about. Neither the question, nor the solution. ): Sorry for my stupidity... 
Does it mean he wants to copy a number of items into a list (he calls it "stack") - and then paste this list's contents into an entry field?

If so - allright, that's close. 2 issues remaining:

1st: Again we have the "press TAB" issue. Should not be too difficult to add that into such a command. How could that be done?

2nd: How could the "coppy" task be improved? - In my daily life, there are various data sources - emails, text files, LibO files, pdfs. Keyboard operation is impossible in most of them, mouse selection is painful, but a double click to select works in all of them. Should I file this one - meaning "copy with _hotkey-double click_" - as a RFE?

**Comment by hluk** [comment]
> "Paste and copy next" indeed does quite a lot what I want when it comes to the "paste" part of the procedure. Could I save a command "paste - hit TAB and copy next" ?

If you go to Command dialog in CopyQ (F6 shortcut), click Add button and there are predefined command to "Copy next item" and "Copy previous item". Unfortunately it's not possible to set Tab as global shortcut (nor it is a good idea because you won't be able to use the key in other apps).

> How could the "coppy" task be improved? - In my daily life, there are various data sources - emails, text files, LibO files, pdfs. Keyboard operation is impossible in most of them, mouse selection is painful, but a double click to select works in all of them. Should I file this one - meaning "copy with _hotkey-double click_" - as a RFE?

If you cannot copy with keyboard from an application, I doubt that CopyQ will be able to help - it sends "copy" shortcut to an target app to copy (the command is `copyq copy`).

**Comment by herrdeh** [comment]
Thank you for your care - very much appreciated!

> If you go to Command dialog in CopyQ (F6 shortcut), click Add button and there are predefined command to "Copy next item" and "Copy previous item". Unfortunately it's not possible to set Tab as global shortcut (nor it is a good idea because you won't be able to use the key in other apps).

You may have got me wrong. My idea was rather to insert the equivalent of hitting the TAB key to jump to the next entry field instead of using the TAB key as a trigger (which definitely is not a good idea. The bash command  
```_echo -e ' \t ' ```
should do, but I could not find out how to get that work within the framework of copyq.

To achieve the double-click feature, we need some instance to catch double-clicks system-wide and check whether "our" special key is pressed, then trigger a "copy to clipboard" action. Should not be too difficult to achieve.

I still wonder why there seems not to be a comfortable standard solution to copy/paste all the unstructured data we get all day (in various text files) into given data fields, may it be browser, address book, calendar or other data bases. I guess, everybody has got this annoying work every day....

**Comment by hluk** [comment]
> You may have got me wrong. My idea was rather to insert the equivalent of hitting the TAB key to jump to the next entry field instead of using the TAB key as a trigger (which definitely is not a good idea, full ack). The bash command
> `echo -e ' \t ' `
> should do, but I could not find out how to get that work within the framework of copyq.

If you need to simulate Tab key press you'll have to use a different application - that's not goal of clipboard manager.

CopyQ supports just simulating "copy" and "paste" shortcuts so it may not be difficult to implement this but it's still out of scope.

On Linux/X11 (not Wayland though), there is `xdotool key Tab`, perhaps there is something similar for Windows ans OS X.

The command to "paste+Tab+copy next" could look like this (though `xdotool` doen't seem to reliably send the Tab key press):

```ini
[Command]
Command="
    copyq paste
    xdotool key Tab
    copyq next"
GlobalShortcut=meta+alt+v
Icon=\xf0ce
IsGlobalShortcut=true
Name=Paste and Tab
```

> To achieve the double-click feature, we need some instance to catch double-clicks system-wide and check whether "our" special key is pressed, then trigger a "copy to clipboard" action. Should not be too difficult to achieve. Do you have an idea where to look for that?

There is currently no easy way to listen to mouse events that happen outside of the app. So this is not trivial to implement (in fact difficult to make this work cross-platform).

**Comment by herrdeh** [comment]
Thank you very much for your time and effort.

Actually, the "copy" issue is not so serious, _double-click & ctrl-c_ is quite a nice way to handle it.

xdotool works allright for me - thanks for that hint.
But I found that I turned the order of my copied items. Normally, I would e.g. copy the sequence <prename>, <surname>, <street>, <house number>, <post code>, <name_of_city>, <country> and expect to replicate it in that order. In copyq's window, the list will appear in reverse order, so I rather need a "copy previous" instead a "copy next" feature. I tinkered around with the copyq previous() command, but could not make it work. 

Your "copy next" code has the disadvantage that the first selected issue is not pasted, but the next one. Would be nice if the command would first first paste the first selected.

Great you do accompany me with that issue!

**Comment by hluk** [comment]
I think you can use modified "stack" command from the issue #597.

```ini
[Commands]
1\Command="
    copyq:
    tab('Queue')
    copy()
    var text = clipboard()
    add(text)"
1\GlobalShortcut=ctrl+shift+c
1\Icon=\xf078
1\IsGlobalShortcut=true
1\Name=Queue Item
2\Command="
    copyq:
    tab('Queue')
    
    var i = size() - 1
    if (i < 0) {
      popup('Queue is empty')
      abort()
    }
    
    var text = read(i)
    copy(text)
    paste()
    execute('xdotool', 'key', 'Tab')
    remove(i)"
2\GlobalShortcut=ctrl+shift+v
2\Icon=\xf077
2\IsGlobalShortcut=true
2\Name=Unqueue Item
size=2
```

One shortcut is to copy item to a special tab "Queue", the other pastes item from the end of the tab, removes it and runs `xdotool key Tab`.

**Comment by herrdeh** [comment]
Hello,
thank you very much for all your patience. But I'm very much convinced that this workflow will help very many people out there... 

I tried your last suggestion in real life - having to address a parcel. Already, it's a great deal of improvement, compared to the standard procedure. Now, IMHO there is some polish which could be done.

1. copyQ's window always disappears completely if another window is clicked. This behaviour is not so handy for this task. Is there a way to keep the "queue" windows always in front, until the whole task is carried out? - An attached window to the top menu bar would be nice. Can it be achieved that it always answers to "arrow up" and "arrow down", independently which window is front ? - That would make it much more handy to select the next item to be pasted.
2. Different to copyQ's main copied items list, in the queue list the next item to be copied is not highlighted. Would be great to have that as well.
3. Queue list entries should not be deleted when pasted first. It can always happen that some paste step fail, for that case we should still have all items present. I suggest that the "clear queue" command is carried out when the next "create queue and copy" sequence is triggerd.





-- 
++++++++++++++++++++++++++++++++++++++
KomponentenKontor Berlin GmbH
Wolf Drechsel, Geschäftsführer
Soorstr. 73
D-14050 Berlin-Charlottenburg
Fernruf: 030 / 120 11 352
Funkruf: 01577 / 77 23 904
USt-ID: DE307967828
Registergericht Berlin-Charlottenburg
HRB 179667 B
++++++++++++++++++++++++++++++++++++++

**Comment by hluk** [comment]
> 1. copyQ's window always disappears completely if another window is clicked.

You can disable "Close When Unfocused" option in General configuration tab and enable "Always on Top" so the main window stays on top of other windows.

> 2. Different to copyQ's main copied items list, in the queue list the next item to be copied is not highlighted. Would be great to have that as well.

The next item is always the last one in the special tab. Maybe storing the new item to bottom of the list would help.

> 3. Queue list entries should not be deleted when pasted first. It can always happen that some paste step fail, for that case we should still have all items present. I suggest that the "clear queue" command is carried out when the next "create queue and copy" sequence is triggerd.

If the paste operation fails, the item should still be in clipboard so you can paste it manually.

**Comment by herrdeh** [comment]
Hi, I did a little testing during the last few days - till now, I'm quite happy with it. I'll carry on with testing under real work conditions and report back when I gained more experience.

**Comment by herrdeh** [comment]
I really love this workflow !
But now, it does not work as it did before with LibreOffice. I'm using 

`Version: 6.3.1.2
Build-ID: 1:6.3.1~rc2-0ubuntu0.18.04.1~lo1
CPU-Threads: 8; BS: Linux 4.15; UI-Render: Standard; VCL: gtk3; 
Gebietsschema: de-DE (de_DE.UTF-8); UI-Sprache: de-DE`

and (I guess since one of the recent updates, often the "queue" contains blank items:

![Bildschirmfoto von 2019-09-24 12-40-56](https://user-images.githubusercontent.com/7152847/65505198-f498f080-dec8-11e9-957d-8b363a7ab315.png)

"Blank" and "real" contents change randomly, I could not find any structure and order, this is how source doc looks like - just bogus characters:

![Bildschirmfoto von 2019-09-24 12-44-53](https://user-images.githubusercontent.com/7152847/65505315-34f86e80-dec9-11e9-8862-aea3f54c3c79.png)


Running copyq from console does not produce any output.
Cheers,
Wolf

**Comment by hluk** [comment]
Are there any warnings/errors in the log (F12 shortcut from CopyQ's main window)?

**Comment by herrdeh** [comment]
Am Dienstag, den 24.09.2019, 05:01 -0700 schrieb Lukas Holecek:
> Are there any warnings/errors in the log (F12 shortcut from CopyQ's
> main window)?

No, nothing.

**Comment by hluk** [comment]
It looks like waiting a bit after releasing the keyboard modifiers pressed with the shortcut helps.

(I changed only the first command "Queue Item".)

```ini
[Commands]
1\Command="
    copyq:
    tab('Queue')
    
    function isModifierPressed() {
        var modifiers = queryKeyboardModifiers()
        return modifiers.length > 0
    }
    
    while (isModifierPressed())
        sleep(20)
    sleep(100)
    
    popup('Copying to Queue')
    copy()
    
    var text = str(clipboard())
    if (text.size == 0) {
        popup('Failed to Copy to Queue', 'Clipboard is empty.')
        abort()
    }
    
    popup('Copied to Queue', text)
    add(text)"
1\GlobalShortcut=ctrl+shift+c
1\Icon=\xf078
1\IsGlobalShortcut=true
1\Name=Queue Item
2\Command="
    copyq:
    tab('Queue')
    
    var i = size() - 1
    if (i < 0) {
      popup('Queue is empty')
      abort()
    }
    
    var text = read(i)
    copy(text)
    paste()
    execute('xdotool', 'key', 'Tab')
    remove(i)"
2\GlobalShortcut=ctrl+shift+v
2\Icon=\xf077
2\IsGlobalShortcut=true
2\Name=Unqueue Item
size=2
```

**Comment by herrdeh** [comment]
Thank you very much for your work - highly appreciated.

I'm sorry having to say that the new code does not make any difference
on my machine (X3450 @ 2.67GHz × 8). I'm attaching the updated copyq-
commands.ini to make sure I didn't miscopy the new code.

I noticed that now with any copy command two notifiers pop up bottom
right at my screen - they say "copying to queue" and "copied to queue
<string>". In case nothing was copied, no <string> is displayed.

[General]
plugin_priority=itemimage, itemencrypted, itemfakevim, itemnotes, itempinned, itemsync, itemtags, itemtext, itemdata

[Options]
action_has_input=false
action_has_output=false
action_output_tab=
action_separator=\\n
activate_closes=true
activate_focuses=true
activate_pastes=true
always_on_top=true
autocompletion=true
autostart=true
check_clipboard=true
check_selection=false
clipboard_notification_lines=0
clipboard_tab=Zwis&chenablage
close_on_unfocus=false
command_history_size=100
confirm_exit=true
copy_clipboard=false
copy_selection=false
disable_tray=false
edit_ctrl_return=true
editor=gedit --standalone -- %1
expire_tab=0
hide_main_window=false
hide_tabs=false
hide_toolbar=false
hide_toolbar_labels=true
item_popup_interval=0
language=de
maxitems=200
move=true
notification_horizontal_offset=10
notification_maximum_height=100
notification_maximum_width=300
notification_position=3
notification_vertical_offset=10
open_windows_on_current_screen=false
save_filter_history=false
show_advanced_command_settings=true
show_simple_items=false
show_tab_item_count=false
tab_tree=false
tabs=Zwis&chenablage, Queue
text_wrap=true
transparency=0
transparency_focused=0
tray_commands=true
tray_images=true
tray_item_paste=true
tray_items=5
tray_tab=
tray_tab_is_current=true
vi=false

[Plugins]
itemdata\enabled=true
itemencrypted\enabled=true
itemfakevim\enabled=true
itemimage\enabled=true
itemimage\image_editor=
itemimage\max_image_height=240
itemimage\max_image_width=320
itemimage\svg_editor=
itemnotes\enabled=true
itempinned\enabled=true
itemsync\enabled=true
itemtags\enabled=true
itemtext\enabled=true

[Shortcuts]
about=shift+f1
change_tab_icon=ctrl+shift+t
commands=f6
copy_selected_items=ctrl+c
delete_item=del
edit=f2
edit_notes=shift+f2
editor=ctrl+e
exit=ctrl+q
export=ctrl+s
find_items=ctrl+g
format-next=ctrl+right
format-previous=ctrl+left
help=f1
import=ctrl+i
move_down=
move_to_bottom=ctrl+end
move_to_clipboard=
move_to_top=ctrl+home
move_up=ctrl+up
new=ctrl+n
new_tab=ctrl+t
next_tab=right
paste_selected_items=ctrl+v
preferences=ctrl+p
previous_tab=left
process_manager=ctrl+shift+z
remove_tab=ctrl+w
rename_tab=ctrl+f2
reverse_selected_items=ctrl+shift+r
show-log=f12
show_clipboard_content=
show_item_content=f4
show_item_preview=f7
sort_selected_items=ctrl+shift+s
system-run=f5
toggle_clipboard_storing=ctrl+shift+x

[Theme]
alt_bg=#f7f5f3
alt_item_css=
bg=#ffffff
css=
cur_item_css="\n    ;border: 0.1em solid ${sel_bg}"
edit_bg=#ffffff
edit_fg=#000000
edit_font=
fg=#000000
find_bg=#ff0
find_fg=#000
find_font=
font=
font_antialiasing=true
item_css=
item_spacing=
menu_bar_css="\n    ;background: ${bg}\n    ;color: ${fg}"
menu_bar_disabled_css="\n    ;color: ${bg - #666}"
menu_bar_selected_css="\n    ;background: ${sel_bg}\n    ;color: ${sel_fg}"
menu_css="\n    ;border-top: 0.08em solid ${bg + #333}\n    ;border-left: 0.08em solid ${bg + #333}\n    ;border-bottom: 0.08em solid ${bg - #333}\n    ;border-right: 0.08em solid ${bg - #333}"
notes_bg=#ffffdc
notes_css=
notes_fg=#000000
notes_font=
notification_bg=#333
notification_fg=#ddd
notification_font=
num_fg=#000000
num_font=
search_bar="\n    ;background: ${edit_bg}\n    ;color: ${edit_fg}\n    ;border: 1px solid ${alt_bg}\n    ;margin: 2px"
search_bar_focused="\n    ;border: 1px solid ${sel_bg}"
sel_bg=#308cc6
sel_fg=#ffffff
sel_item_css=
show_number=true
show_scrollbars=true
style_main_window=false
tab_bar_css="\n    ;background: ${bg - #222}"
tab_bar_item_counter="\n    ;color: ${fg - #044 + #400}\n    ;font-size: 6pt"
tab_bar_scroll_buttons_css="\n    ;background: ${bg - #222}\n    ;color: ${fg}\n    ;border: 0"
tab_bar_sel_item_counter="\n    ;color: ${sel_bg - #044 + #400}"
tab_bar_tab_selected_css="\n    ;padding: 0.5em\n    ;background: ${bg}\n    ;border: 0.05em solid ${bg}\n    ;color: ${fg}"
tab_bar_tab_unselected_css="\n    ;border: 0.05em solid ${bg}\n    ;padding: 0.5em\n    ;background: ${bg - #222}\n    ;color: ${fg - #333}"
tab_tree_css="\n    ;color: ${fg}\n    ;background-color: ${bg}"
tab_tree_item_counter="\n    ;color: ${fg - #044 + #400}\n    ;font-size: 6pt"
tab_tree_sel_item_counter="\n    ;color: ${sel_fg - #044 + #400}"
tab_tree_sel_item_css="\n    ;color: ${sel_fg}\n    ;background-color: ${sel_bg}\n    ;border-radius: 2px"
tool_bar_css="\n    ;color: ${fg}\n    ;background-color: ${bg}\n    ;border: 0"
tool_button_css="\n    ;background-color: transparent"
tool_button_selected_css="\n    ;background: ${sel_bg}\n    ;color: ${sel_fg}"
use_system_icons=false

**Comment by hluk** [comment]
Is this still a problem? This is really something that custom commands in CopyQ should handle.

**Comment by herrdeh** [comment]
I used to be really happy with this feature for years now, several updates, no problems.

But now, with update to ubuntu 26, GNOME 50, copyq 13.0.0 it no longer works:

* keyboard shortcuts do nothing
* calling the "queuing" from a menu leads to "copy to clip failed"

I'd be very glad to have it back - which additional info is needed?  copyq-commands.ini attached.

Cheers,
Wolf

[copyq-commands.ini--.txt](https://github.com/user-attachments/files/28968502/copyq-commands.ini--.txt)
