### ISSUE TITLE
System tray Icon is not shown on KDE Plasma

### ISSUE THREAD

**Issue by nemonein** [hluk/CopyQ#1078]
**Describe the bug**
Icon is empty

**To Reproduce**
On Kubuntu 18.10 and KDE Neon, there is no icon(Copyq 3.7.3) on the tray.

**Screenshots**
![copyq-3 7 3](https://user-images.githubusercontent.com/5688288/52165642-c5b9e880-2746-11e9-8ca4-3e7f37cb846a.png)
It is taken on KDE Neon.

**Version, OS and Environment**
 - Application Version 3.7.3. (Until 3.7.2, there was no problem.)
 - OS: Kubuntu 18.10, KDE Neon
 - Desktop environment : KDE Plasma

..............................

I've just installed 3.7.3 through PPA, and the icon is missing. However, CopyQ is working anyway.

**Comment by magpie514** [comment]
I got the same issue when updating to 3.7.3 from the provided release package (copyq_3.7.3_Debian_9.0-1_amd64.deb) on "base" Ubuntu 18.10 but also using Plasma 5.

**Comment by hluk** [comment]
Any errors in log? (F12 shortcut from application window)

**Comment by magpie514** [comment]
![out5](https://user-images.githubusercontent.com/323651/52167554-eff6b080-271c-11e9-8698-a5058d676d0d.png)
Nothing really relevant.

**Comment by hluk** [comment]
Fixed (adda48379077a9bff37520ee03d3c4c687fbb4a8) but not sure when I can do another release.

Looks like bug in Qt or KDE. Same icon is used in window title and there it looks OK.

**Comment by hluk** [comment]
I'm at least updating [copyq-beta PPA](https://launchpad.net/~hluk/+archive/ubuntu/copyq-beta) with the fix.

**Comment by magpie514** [comment]
Good enough, I can live with it until next release, personally. Thanks anyway!

**Comment by nemonein** [comment]
I've installed the one in beta PPA, and it works good.
Thank you very much!

**Comment by hluk** [comment]
I'll keep this open for visibility.

**Comment by gbcox** [comment]
Yeah, same issue on Fedora with 3.7.3

**Comment by hluk** [comment]
@gbcox Thanks for including the patch in packages for Fedora.

**Comment by gbcox** [comment]
No problem.  Thanks for the quick response on the patch.
