### ISSUE TITLE
Tab for storing clipboard

### ISSUE THREAD

**Issue by Migacz85** [hluk/CopyQ#1080]
**Describe the bug**
Going to file -> history -> Tab for storing clipboard
Selecting new tab for storing it. 
Apply
result:
Copy shourtcat is not working. 

Repeating the action and changing to &clipboard making apply.
Setting another tab for saving clipboards.
Result:
Finally switches the copyq to store content in new tab. And ctrl+c is working again.

**Version, OS and Environment**

 - OS manjaro i3wn
 - Desktop environment, window manager (if applicable)
CopyQ Clipboard Manager v3.7.1
Qt: 5.11.2
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Manjaro Linux

**Additional context**

**Comment by hluk** [comment]
I cannot reproduce this.

Are you trying to use a special tab, e.g. encrypted or synchronized to disk?

Can you try this with latest version?

**Comment by Migacz85** [comment]
The tab in this test was normal tab without encryption and without synchronization on the disk. I build successfully copy q from master. Also sudo make intall seems run as should. But I still get v 3.7.1 while running copyq from console.

**Comment by hluk** [comment]
If build from master it would give you something like:

```
> copyq version
CopyQ Clipboard Manager v3.7.3-4-g991214c4
```

I'm guessing you have copyq executable also installed from package manager in `/usr/bin` (`make` installs to `/usr/local` by default).

Do you see any errors/warnings in logs (F12 shortcut)?

**Comment by Migacz85** [comment]
I'm still on 3.7.1
Here is mine log: 

Warning [2019-01-17 18:30:23.427] <Server-31770>: CopyQ server is already running.
Warning [2019-01-17 18:58:54.633] <Server-22975>: CopyQ server is already running.
ERROR [2019-01-19 21:04:18.309] <Client-4583>: Cannot connect to server! Start CopyQ server first.
ERROR [2019-01-19 21:05:16.700] <Client-5918>: Cannot connect to server! Start CopyQ server first.
Warning [2019-01-19 21:08:49.262] <Server-10885>: CopyQ server is already running.
Warning [2019-01-22 00:23:59.616] <Server-9278>: CopyQ server is already running.
Warning [2019-01-23 12:29:01.096] <Server-25011>: CopyQ server is already running.
Warning [2019-01-23 12:30:20.024] <Server-26803>: CopyQ server is already running.
Warning [2019-01-23 12:31:34.696] <Server-28488>: CopyQ server is already running.
Note [2019-01-23 12:48:39.753] <Server-29455>: Failed to open desktop file "share/applications/com.github.hluk.copyq.desktop": No such file or directory
ERROR [2019-01-23 13:29:20.835] <Client-10870>: ItemEncrypt ERROR: GnuPG stderr:
ERROR [2019-01-23 13:29:20.835] <Client-10870>:    gpg: keybox '/home/migacz/.config/copyq/copyq.pub' created
ERROR [2019-01-23 13:29:20.835] <Client-10870>:    gpg: copyq: skipped: No public key
ERROR [2019-01-23 13:29:20.835] <Client-10870>:    gpg: [stdin]: encryption failed: No public key
ERROR [2019-01-23 13:29:20.835] <Client-10870>:    
Note [2019-01-23 13:29:20.835] <Client-10870>: ScriptError: Exception in command "Encrypt (needs GnuPG)": Failed to execute GPG!
Note [2019-01-23 13:29:20.835] <Client-10870>:    
Note [2019-01-23 13:29:20.835] <Client-10870>:    --- backtrace ---
Note [2019-01-23 13:29:20.835] <Client-10870>:    <eval>() at “throw 'Failed to execute GPG!'”:1
Note [2019-01-23 13:29:20.835] <Client-10870>:    <eval>() at “ plugins.itemencrypted.encryptItems()”:1
Note [2019-01-23 13:29:20.835] <Client-10870>:    --- end backtrace ---
Note [2019-01-23 13:29:20.842] <Server-29455>: Command “Encrypt (needs GnuPG)”
Note [2019-01-23 13:29:20.842] <Server-29455>:    Exit code: 4
Note [2019-01-23 13:29:20.842] <Server-29455>:    ERROR: ItemEncrypt ERROR: GnuPG stderr:
Note [2019-01-23 13:29:20.842] <Server-29455>:    ERROR:    gpg: keybox '/home/migacz/.config/copyq/copyq.pub' created
Note [2019-01-23 13:29:20.842] <Server-29455>:    ERROR:    gpg: copyq: skipped: No public key
Note [2019-01-23 13:29:20.842] <Server-29455>:    ERROR:    gpg: [stdin]: encryption failed: No public key
Note [2019-01-23 13:29:20.842] <Server-29455>:    ERROR:    
Note [2019-01-23 13:29:20.842] <Server-29455>:    ScriptError: Failed to execute GPG!
Note [2019-01-23 13:29:20.842] <Server-29455>:    
Note [2019-01-23 13:29:20.842] <Server-29455>:    --- backtrace ---
Note [2019-01-23 13:29:20.842] <Server-29455>:    <eval>() at “throw 'Failed to execute GPG!'”:1
Note [2019-01-23 13:29:20.842] <Server-29455>:    <eval>() at “ plugins.itemencrypted.encryptItems()”:1
Note [2019-01-23 13:29:20.842] <Server-29455>:    --- end backtrace ---
Note [2019-01-23 13:29:20.842] <Server-29455>:    
Note [2019-01-23 13:29:20.842] <Server-29455>:    1. copyq:  plugins.itemencrypted.encryptItems()
ERROR [2019-01-23 13:30:43.873] <Client-12782>: ItemEncrypt ERROR: GnuPG stderr:
ERROR [2019-01-23 13:30:43.873] <Client-12782>:    gpg: copyq: skipped: No public key
ERROR [2019-01-23 13:30:43.873] <Client-12782>:    gpg: [stdin]: encryption failed: No public key
ERROR [2019-01-23 13:30:43.873] <Client-12782>:    
Note [2019-01-23 13:30:43.874] <Client-12782>: ScriptError: Exception in command "Encrypt (needs GnuPG)": Failed to execute GPG!
Note [2019-01-23 13:30:43.874] <Client-12782>:    
Note [2019-01-23 13:30:43.874] <Client-12782>:    --- backtrace ---
Note [2019-01-23 13:30:43.874] <Client-12782>:    <eval>() at “throw 'Failed to execute GPG!'”:1
Note [2019-01-23 13:30:43.874] <Client-12782>:    <eval>() at “ plugins.itemencrypted.encryptItems()”:1
Note [2019-01-23 13:30:43.874] <Client-12782>:    --- end backtrace ---
ERROR [2019-01-23 13:30:45.236] <Client-12804>: ItemEncrypt ERROR: GnuPG stderr:
ERROR [2019-01-23 13:30:45.236] <Client-12804>:    gpg: copyq: skipped: No public key
ERROR [2019-01-23 13:30:45.236] <Client-12804>:    gpg: [stdin]: encryption failed: No public key
ERROR [2019-01-23 13:30:45.236] <Client-12804>:    
Note [2019-01-23 13:30:45.237] <Client-12804>: ScriptError: Exception in command "Encrypt (needs GnuPG)": Failed to execute GPG!
Note [2019-01-23 13:30:45.237] <Client-12804>:    
Note [2019-01-23 13:30:45.237] <Client-12804>:    --- backtrace ---
Note [2019-01-23 13:30:45.237] <Client-12804>:    <eval>() at “throw 'Failed to execute GPG!'”:1
Note [2019-01-23 13:30:45.237] <Client-12804>:    <eval>() at “ plugins.itemencrypted.encryptItems()”:1
Note [2019-01-23 13:30:45.237] <Client-12804>:    --- end backtrace ---
Note [2019-01-23 22:19:14.886] <Server-29455>: Command “terminator -x %1 ; delay 10”
Note [2019-01-23 22:19:14.886] <Server-29455>:    Error: execve: No such file or directory
Note [2019-01-23 22:19:14.886] <Server-29455>:    1. terminator -x sshfs 192.168.0.80:/storage/emulated/0 ~/Android -p 2222
Note [2019-01-23 22:19:14.886] <Server-29455>:    2. 
Note [2019-01-23 22:19:14.886] <Server-29455>:    3. |delay 10
Note [2019-01-23 22:27:54.060] <Server-29455>: Command “copyq provideClipboard”
Note [2019-01-23 22:27:54.060] <Server-29455>:    Error: Process crashed
Note [2019-01-23 22:27:54.060] <Server-29455>:    1. copyq provideClipboard
ERROR [2019-01-23 22:28:11.549] <monitorClipboard-27130>: Connection lost!
Warning [2019-01-23 23:41:32.623] <Server-30429>: CopyQ server is already running.
Warning [2019-01-24 19:15:52.668] <Server-32221>: CopyQ server is already running.
Note [2019-01-24 19:17:03.101] <Server-9854>: Command “copyq monitorClipboard”
Note [2019-01-24 19:17:03.101] <Server-9854>:    Error: Process crashed
Note [2019-01-24 19:17:03.101] <Server-9854>:    1. copyq monitorClipboard
ERROR [2019-01-24 19:18:40.128] <monitorClipboard-3057>: Connection lost!
Note [2019-01-24 20:12:06.332] <Server-1485>: Command “copyq monitorClipboard”
Note [2019-01-24 20:12:06.332] <Server-1485>:    Error: Process crashed
Note [2019-01-24 20:12:06.332] <Server-1485>:    1. copyq monitorClipboard
ERROR [2019-01-24 20:14:36.509] <Client-10485>: Cannot connect to server! Start CopyQ server first.
Warning [2019-02-03 22:59:42.724] <Server-13998>: CopyQ server is already running.
Warning [2019-02-03 22:59:50.768] <Server-14205>: CopyQ server is already running.
ERROR [2019-02-03 23:00:20.753] <monitorClipboard-14540>: Connection lost!
ERROR [2019-02-03 23:07:37.380] <Client-24665>: Cannot connect to server! Start CopyQ server first.
ERROR [2019-02-03 23:07:39.697] <Client-24729>: Cannot connect to server! Start CopyQ server first.

**Comment by hluk** [comment]
Looks like something wrong is with your installation of CopyQ - mixed versions of binaries or libraries.

Can you remove all the files installed with `make install`?

**Comment by Migacz85** [comment]
If there is any script/command to do this in quick way ?

**Comment by hluk** [comment]
Unfortunately, no. If you didn't install anything else into `/usr/local` - **check with `find /usr/local -type f`** - you can just remove the directory (`sudo rm -rf /usr/local`) - system packages are not installed there.

Normally I wouldn't advice using `sudo make ...` though I just noticed that it's in the README file. :( Sorry about that, if you followed the steps there. I'll remove it - you can run the built application without it.

**Comment by Migacz85** [comment]
I just went to build folder from the project tested steps on current version: v3.7.3-4-ga4fbfbe9 

- The bug is not active here  -

**Comment by hluk** [comment]
> It not thread for that but it would be nice to have shourtcat for changing where clip will be storred. :-)

Do you mean a shortcut to change the tab for automatic storing the clipboard?

**Comment by Migacz85** [comment]
yes exactly, a shourtcut to change the tab for storing the clipboard.

**Comment by hluk** [comment]
You can map a global shortcut to change the clipboard tab:

```ini
[Command]
Command="
    copyq config clipboard_tab clipboard2"
GlobalShortcut=meta+alt+t
Icon=\xf15b
IsGlobalShortcut=true
Name=Change Clipboard Tab
```

(Just change the `clipboard2` to your tab name and set shortcut.)

**Comment by hluk** [comment]
BTW, [here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them).

**Comment by Migacz85** [comment]
Oh brilliant, I felt that this can be done somwhere there. This soft is preatty great :-) I was thinking to code something simmilar - Thanks to your project I don't need to. Thanks!
