### ISSUE TITLE
Paste as auto-type the text

### ISSUE THREAD

**Issue by gsurrel** [hluk/CopyQ#1082]
This is halfway between a bug (of the documentation) and a feature request (for the software):

Is pasting the content actually sending a "Clipboard paste" event or is it typing the text? This can be useful for applications which do not support clipboard at all (or ignore it).

As an example, "Keepass XC" can fill-in forms by automatically typing the characters one by one, which is a nice workaround when clipboard is not supported (whether it's on purpose or not).

If it is already available, it would be nice to advertise this auto-type feature in the documentation and website.

**Comment by hluk** [comment]
To paste a content, CopyQ first copies it into clipboard and then just sends Shift+Insert to the target window.

Implementing text typing would be to complicated (should be cross-platform) and error-prone (unicode text, different keyboard layouts etc.) but if we really decide to do this, it could be a good idea to start with [the code in keepassxc](https://github.com/keepassxreboot/keepassxc/tree/develop/src/autotype).

Is this really a bug? Can you point out what needs to be changed in docs or ideally create a pull request?

**Comment by hluk** [comment]
It would be nice to have, but for me it's not very important.

BTW, if you're on Linux/X11, you can override Enter key with a command that executes `xdotool` to type the text (can be slow for long text).

```ini
[Command]
Command="
    xdotool type %1"
HideWindow=true
Icon=\xf15b
InMenu=true
Input=text/plain
Name=Paste
Shortcut=return
```

([Here is how to add the command to CopyQ.](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them))

**Comment by Chealer** [comment]
@gsurrel: What you want is discussed in ticket #3444.
