### ISSUE TITLE
Custom file name for synchronized clip to documents folder

### ISSUE THREAD

**Issue by cjohnsonuk** [hluk/CopyQ#1083]
Clips in the synchronized folder have names that are not very useful if you're viewing the folder not using the application.
Would it be possible to use the window title and date time stamp to create a filename that was a bit easier to work out what's  in the clip?

Instead of saving a file with a name of copyq_0001.txt

could the filename be based on variables the script has access to ?
eg {YYYY}-{MM}-{DD}_{HH}_{mm}_{SS}_{WindowTitle}.{extension}
to give a name like 

2017-10-06_16_49_19_ODBC Data Source Administrator (32-bit)

Or the notes or the tags or the tab name etc

**Comment by bitclick** [comment]
i noticed this too: tags and notes are not synchronized using the synchronize plugin. I doubt, that all this info can be encoded in the filename. Maybe an extra file for metadata should be added per item?

Meanwhile, would you recommend putting the `~/.config/copyq` folder on dropbox or syncthing for this purpose?

**Comment by hluk** [comment]
I completely forgot about this feature request. And actually, I have not realized it until now, but this is possible thanks to some recent improvements in the synchronization plugin.

Try to add following command ([here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)):

```ini
[Command]
Automatic=true
Command="
    copyq:
    var window = str(data(mimeWindowTitle))
    var mime = 'application/x-copyq-itemsync-basename'
    var time = dateString('yyyy-MM-ddhhmmss')
    setData(mime, 'copyq_' + time + window)"
Icon=\xf56f
Name=Nicer Sync Filename
```

This would work only for newly copied content.

**Comment by bitclick** [comment]
nice! thank you :slightly_smiling_face:
