### ISSUE TITLE
Empty tray list

### ISSUE THREAD

**Issue by avkarenow** [hluk/CopyQ#1084]
**Describe the bug**
Tray list of copied items disappears few times per day. I often have about 100+ items in history. After some time is back to work.

**To Reproduce**
1. Set history to 200 items on Ubuntu 18.04 with Gnome Classic.
2. Use a little time ;)

**Version, OS and Environment**
- Ubuntu 18.04 with Gnome Classic
$ copyq --version
CopyQ Clipboard Manager v3.7.3
Qt: 5.9.5
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Ubuntu 18.04.1 LTS
- Repo: deb http://ppa.launchpad.net/hluk/copyq/ubuntu bionic main

![copyq-empty](https://user-images.githubusercontent.com/14143181/52236125-4521f600-28c6-11e9-9967-690a9f47ca12.png)

**Comment by hluk** [comment]
This is probably a bug in the tray extension Gnome Classic uses.

I'm using [Topicons Plus](https://extensions.gnome.org/extension/1031/topicons/) which works fine in Gnome.

Also if you run `copyq menu` it should popup the tray menu that CopyQ creates.

**Comment by avkarenow** [comment]
It's weird, other applications have no such problems on Gnome Classic.

TopIcons Plus doesn't work with Gnome Classic, I'm using standard indicator.

`copyq menu` works and I can use it as a temporary workaround.

**Comment by hluk** [comment]
The menu in CopyQ has to be updated sometimes (when clipboard content changes and on some other occasions). I'm guessing that's the part where the integration extension in Gnome has issues.
