### ISSUE TITLE
[Feature Request] Add option to set `1` as first clipboard history entry number instead of `0`.

### ISSUE THREAD

**Issue by fmaiabatista** [hluk/CopyQ#1085]
**Is your feature request related to a problem? Please describe.**
I have CopyQ "Show the tray menu" option bound to the shortcut `Alt + '` and I paste the items with `Alt + numbers`. The problem is that I'm used to (and it's more practical) pasting the last copied item (which is the first entry in clipboard history) with key `1` (which is closest to the `'` key in a QWERTY layout) instead of key `0`.

**Describe the solution you'd like**
Have a checkbox option to set the order of clipboard history between "1 ... 9 then 0" and the default "0 ... 9".

**Describe alternatives you've considered**
The clipboard managers I use on other OSes have this setting (Ditto for Windows and Clipy for Mac). Maybe if this setting is present in CopyQ I could ditch both of them and standardize my clipboard manager :).

**Additional context**
![image](https://user-images.githubusercontent.com/1574224/52412974-67cf2d00-2ac7-11e9-8549-5a9c091e6ec0.png)

**Comment by qizhihere** [comment]
Yes, i also used to select an item with just a number key. It seems more natural to press `1` instead of `0` to select the first item. If the first item is labeled by 1, it will be more intuitive and clear.

**Comment by magpie514** [comment]
I kind of agree with this one, 0 is ideal when working with code, arrays and computer logic, but for UI it's definitely better to start with 1.

**Comment by hluk** [comment]
Just released in v4.0.0: Rows are now numbered from 1 instead of 0 by default.
