### ISSUE TITLE
Install error (CentOS) org.kde.Platform not found

### ISSUE THREAD

**Issue by chang-zhao** [hluk/CopyQ#1086]
Trying to install on CentOS 7 with Xfce. The instruction https://hluk.github.io/CopyQ/ says:

```
Other Linux Distributions

Install Flatpak and com.github.hluk.copyq from Flathub.

flatpak install --user --from https://flathub.org/repo/appstream/com.github.hluk.copyq.flatpakref
```

but running this command gives an error:

```
error: The Application com.github.hluk.copyq/x86_64/stable requires the org.kde.Platform/x86_64/5.9 which was not found
```

Do I miss something?

**Comment by hluk** [comment]
I got the same problem. Looks like the command on [CopyQ page on flathub](https://flathub.org/apps/details/com.github.hluk.copyq) is different:

    https://flathub.org/apps/details/com.github.hluk.copyq

But if I try to run it:

    error: Unable to load summary from remote flathub: GPG verification enabled, but no summary found (check that the configured URL in remote config is correct)

Reinstalling flatpak helped with both (on Fedora `sudo dnf reinstall flatpak`).

Before reinstalling I also moved the `/var/lib/flatpak`.

    sudo mv /var/lib/flatpak{,.old}

**Comment by luckylittle** [comment]
If you're interested in a different way to install CopyQ on CentOS/RHEL, check out my RPM: https://github.com/luckylittle/CopyQ-for-RHEL8
