### ISSUE TITLE
[Question] Isn't there copyq.conf in macOS?

### ISSUE THREAD

**Issue by nemonein** [hluk/CopyQ#1087]
Hello.

I'm sorry, this is neither a bug nor request. Just a simple question.
I've been using copyq in Ubuntu for a long time.
Copyq's configuration files are stored on ~/.config/copyq in Ubuntu, and copyq.conf is the main config file.

On macOS, there also is ~/.config/copyq directory and some files in it, but no copyq.conf.
I'd like to share copy settings between macOS machines. I usually do this in Ubuntu by sharing copyq.conf using Cloud service.

Where's copyq.conf in macOS? Or is some other method used in mac?

**Comment by hluk** [comment]
The config file path can be printed with `copyq info config` command.

**Comment by nemonein** [comment]
Thank you @hluk.
For the record, I left what I did.

```
$ /Applications/CopyQ.app/Contents/MacOS/copyq info config
/Users/userid/Library/Preferences/com.copyq.copyq.plist
```

com.copyq.copyq.plist is a binary file, and quite different from Linux's copyq.conf.
I wished to make the same environment(copyq) automatically on both systems(Linux and macOS), and it turns out to be impossible.

**Comment by hluk** [comment]
> com.copyq.copyq.plist is a binary file, and quite different from Linux's copyq.conf.

@nemonein Maybe it will come to the same situation as in Windows: stop storing configuration in registry and use plain text file.

You can use `COPYQ_SETTINGS_PATH` environment variable to override the settings paths, (e.g. `export COPYQ_SETTINGS_PATH=$HOME/.config/copyq`), but I don't remember if it will also force the usage of the plain text format.

**Comment by nemonein** [comment]
Thank you for your help. I really appreciate it.
I've found a work around referring to [this](https://serverfault.com/questions/111391/use-an-environment-variable-in-a-launchd-script).

1st, unselect 'Autostart' section in CopyQ preferences.
2nd, create a plist file. `~/Library/LaunchAgents/run_copyq.plist` (or anyname would be ok)
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>EnvironmentVariables</key>
	<dict>
		<key>COPYQ_SETTINGS_PATH</key>
		<string>/Users/myuserid/.config/copyq_plaintext</string>
	</dict>
	<key>Label</key>
	<string>Run.Copyq</string>
	<key>ProgramArguments</key>
	<array>
		<string>/Applications/CopyQ.app/Contents/MacOS/copyq</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
	<key>ServiceIPC</key>
	<false/>
</dict>
</plist>
```
3rd and finally, reboot.

It works great. copyq.ini is the new configuration file, which is Plain Text format.

If there's a better idea, please let me know.
I reopened the issue for others, but you might close.
