### ISSUE TITLE
CopyQ : Error deleting items

### ISSUE THREAD

**Issue by Clemens-Ratte-Polle** [hluk/CopyQ#1088]
hi.
CopyQ Error :(
When deleting items while staying on e.g. the second item, because not to delete the first item but some others beneath, CopyQ sometimes jumps one item up inexplicably o_O
It happens that i do not notice this and then it gets lost - totally lost, because it ist NOT stored in the extra tab trash to undelete it >:( 👎 
It has gone...
This is NOT funny :(

Perhaps there is a confusion conflict between some commands F6 ?
I got 3 "Addons":  
Search all Tabs
Move to trash
Undo delete

Perhaps someone has the same issues?
thx

**Comment by hluk** [comment]
I never noticed such issues with [Move to Trash](https://github.com/hluk/copyq-commands/tree/master/Application#undoable-move-to-trash).

Can you verify that the command is same as the one [here](https://github.com/hluk/copyq-commands/blob/master/Application/undoable-move-to-trash.ini)?

Can you provide steps to reproduce this (how you delete items)?

**Comment by Clemens-Ratte-Polle** [comment]
it seems the same as mine:
https://github.com/hluk/copyq-commands/blob/master/Application/undoable-move-to-trash.ini
ARE there some versions?
Why aren't they noticed there as numbers?

Reproduce?
Hm, when deleting more items such as 20 in a fast way with the keyboard DEL.
But this happens seldomly.

**Comment by hluk** [comment]
> https://github.com/hluk/copyq-commands/blob/master/Application/undoable-move-to-trash.ini
> ARE there some versions?

There are no versions for those commands. I could consider adding a version number, but there needs to be support in CopyQ - maybe I can start adding them as comments in the command.

> Hm, when deleting more items such as 20 in a fast way with the keyboard DEL.

Looks like the action is disabled for a moment when another item is selected and pressing DEL invokes the default action. I'm trying to fix that.

**Comment by Clemens-Ratte-Polle** [comment]
thx! :)
