### ISSUE TITLE
CopyQ : Error Bug Report

### ISSUE THREAD

**Issue by Clemens-Ratte-Polle** [hluk/CopyQ#1089]
hi
I want to report bugs, but when i click:
"Bug report Create a report to help us improve"
it leads to:
http://bug_report.md/
which causes ERROR :(
Waht's wrong?

**Comment by hluk** [comment]
I don't see that behavior. After clicking "Get started":

> ![image](https://user-images.githubusercontent.com/38054/52524114-c0562400-2c99-11e9-95b3-c8a745f3a97c.png)

I get to following URL in browser which allows me to fill in the bug report.

    https://github.com/hluk/CopyQ/issues/new?assignees=&labels=bug&template=bug_report.md&title=

Maybe it's some caching issues on github, I've added the `bug_report.md` template recently.

Anyway, looks like a github problem, not much I can do about this.
