### ISSUE TITLE
[feature] paste selected item on releasing keyboard shortcuts.

### ISSUE THREAD

**Issue by lengthmin** [hluk/CopyQ#1094]
**Is your feature request related to a problem? Please describe.**
 I have used a same software named "Clipdiary" before. which allowed me to do this:
1. I use the keys [Ctrl + Shift + UpArray] to select the previous clip.
2. the selected content(text, image) will display on a side.
3. It will paste the items after I release the keys. It means once I find the correct ones, and it will be paste.
---
display information I selected.
![image](https://user-images.githubusercontent.com/13938334/52944805-444f9080-33ab-11e9-81a8-20b57d7388fa.png)
---
the setting of Clipdiary
![image](https://user-images.githubusercontent.com/13938334/52944822-4fa2bc00-33ab-11e9-858b-0fed9781c18f.png)

 But I cannot find a solution for that on CopyQ.

**Describe the solution you'd like**
I use the command `popup("Selected Item：", clipboard(),TIME=3000)` to show the content.
and `paste()` for paste the item I want.

But every time I press the shortcut keys to choose the right item, it will paste every item immediately.
I want it paste when I release the keys.

**Describe alternatives you've considered**
 1. provide another command that can preview image on popup window.
2. provide the setting for  `command executed when the keyboard is pressed` and `command executed when the keyboard is released`

**Additional context**
:) thank you all for your efforts.

**Comment by hluk** [comment]
The command can wait for keyboard modifiers to be released (`queryKeyboardModifiers().length == 0`):

```ini
[Command]
Command="
    copyq:
    var waitSeconds = 3;
    var sleepMilliseconds = 100;
    
    next()
    var text = str(clipboard())
    
    for (var i = 0; i < waitSeconds * 1000; i += sleepMilliseconds) {
      if (queryKeyboardModifiers().length == 0) {
        paste()
        break
      }
    
      sleep(sleepMilliseconds)
    
      if (str(clipboard()) != text) break;
    }"
GlobalShortcut=ctrl+shift+down
Icon=\xf0ab
IsGlobalShortcut=true
Name=Quick Paste Item
```

**Comment by lengthmin** [comment]
thank u!  it works fine!

**Comment by popovserhii** [comment]
@lengthmin 
Could you please describe in detail how to configure "Preview Mode" in CopyQ like Clipdiary?

**Comment by lengthmin** [comment]
@popovserhii
the function:`popup`
```
popup("Selected Item：", clipboard(),TIME=3000)
```

**Comment by lengthmin** [comment]
![image](https://user-images.githubusercontent.com/13938334/58102408-cc943a80-7c13-11e9-91fd-bb4f037602e3.png)
```
copyq:
var waitSeconds = 3;
var sleepMilliseconds = 100;

previous()
var text = str(clipboard())
popup("Selected Item：", text,TIME=3000)
for (var i = 0; i < waitSeconds * 1000; i += sleepMilliseconds) {
  if (queryKeyboardModifiers().length == 0) {
    paste()
    break
  }

  sleep(sleepMilliseconds)

  if (str(clipboard()) != text) break;
}
```

**Comment by popovserhii** [comment]
For someone who are googling "CopyQ how to show selected item preview with shortcut", use the next instruction. Thank @lengthmin for help.

* Open CopyQ main window
* Go to **_File_** -> **_Commands/GlobalShortcuts (F6)_**
* Click **_Add +_** button and select **_New command_**
![image](https://user-images.githubusercontent.com/1991183/58225735-2ee05e80-7d2c-11e9-8a99-e02f3d6c8f16.png)
* Enter the Name: *Copy next*
Go to tab **_Command_** and paste next script
```
copyq:
var waitSeconds = 3;
var sleepMilliseconds = 1;

next()
var text = str(clipboard())
popup("Selected Item：", text, TIME=1000)
for (var i = 0; i < waitSeconds * 1000; i += sleepMilliseconds) {
  if (queryKeyboardModifiers().length == 0) {
    paste()
    break
  }

  sleep(sleepMilliseconds)

  if (str(clipboard()) != text) break;
}
```
* Go to **_Advanced_** tab and check **_Global Shortcut_**
![image](https://user-images.githubusercontent.com/1991183/58225802-8383d980-7d2c-11e9-82db-784713c507c9.png)
* The last one, you should apply shortcut command for your script.
Click on **_Global Shortcut +_** and enter shortcut which you want.
In my case it is _Meta+Alt+Up_ (where Meta = Win key on keyboard)
![image](https://user-images.githubusercontent.com/1991183/58225820-9c8c8a80-7d2c-11e9-85cf-e4b47239876e.png)
* Click **_Apply_** button and create the same script but change only **_next()_** to **_previous()_**
* Uncheck default **_Copy next item_** and **_Copy previous item_** if they are presented
* Now, with shortcut _Win+Alt+Up_ and _Win+Alt+Down_ you can browse through your clip.
