### ISSUE TITLE
Ignoring mime content copied from Office

### ISSUE THREAD

**Issue by amosbird** [hluk/CopyQ#1096]
There is a command example that ignores images when text is available

https://copyq.readthedocs.io/en/latest/command-examples.html

however it seems conflicts with this command.

```ini
[Command]
Automatic=true
Command="
    copyq:
    var imageDir = Dir().homePath() + '/Pictures/Screenshots/'
    var imageFileName = 'copied-' + dateString('yyyy-MM-dd-HH_mm_ss') + '.png'
    var imagePath = imageDir + '/' + imageFileName
    
    
    if (!Dir().mkpath(imageDir)) {
      popup('Failed to create directory for images')
      abort()
    }
    
    var f = new File(imagePath)
    if (!f.openWriteOnly() || f.write(input()) == -1) {
      popup('Failed to save image', f.errorString())
      abort()
    }
    f.close()
    
    notes = [
      '[[file:' + imagePath + ']]',
      imagePath
    ]
    setData(mimeItemNotes, notes.join('\\n'))
    copy(\"image/png\", input())"
Icon=\xf03e
Input=image/png
Name=Save Copied Images
```

How can I extend it so that the MIME content copied from Office Visio gets pasted correctly to Office PowerPoint?

**Comment by hluk** [comment]
> There is a command example that ignores images when text is available

The command shouldn't be needed, that's now handled in the application itself. I'll remove it from the documentation.

> How can I extend it so that the MIME content copied from Office Visio gets pasted correctly to Office PowerPoint?

I think you need to retrieve any special data from clipboard (`data = clipboard(mime)`) and add it to the last `copy()` call in the command (`copy('image/png', input(), mime, data)`).

**Comment by amosbird** [comment]
@hluk single `mime` isn't a thing. How can I grab all mime data and put them back?

**Comment by hluk** [comment]
What I meant is that you have to figure out which formats those application provide and require? Maybe just `mimeText` and `mimeHtml`.

You can list all MIME formats with `copyq clipboard ?`, but cloning all mime data is not very good idea - that can take a looong time (even listing the formats can be sometimes slow - depends on the app and OS).

**Comment by amosbird** [comment]
hmmm, there is no addtional MIME formats
```
 ❯ copyq clipboard '?'
TIMESTAMP
TARGETS
image/bmp
application/x-qt-image
```
however, after changing from `image/png` to `image/bmp`, pasting results in  error 925 - unable to retrieve Device Independent Bitmap data

**Comment by hluk** [comment]
Hmm, maybe you can just skip the `copy()` call when stuff is copied from Visio; something like:

```js
var windowTitle = str(data(mimeWindowTitle))
if ( !windowTitle.match(/Visio/) )
  copy(...)
```

Actually, do you need the `copy()` there at all?

**Comment by amosbird** [comment]
......... removing `copy` works
