### ISSUE TITLE
CopyQ date+texte insertion

### ISSUE THREAD

**Issue by JRAuger** [hluk/CopyQ#1097]
I am a user under W10 Flashpaste pro software. Looking for an equivalent in Linux I just found CopyQ which is available under Windows and Ubuntu. Great !
I also found the way to share the same CopyQ config file between my pc under W10 and Linux ... Super!

So I make my debut with CopyQ.
If I want to insert a signature into a text document of the following type:

xxxxxxx
My name, my name,
title
date and time (hr: min)
xxxxxxx

I know I have to use the function "F6 / Paste current date and time", but I want to use it by combining a particular text ...? I dont need a global shortcut, but simply paste de signature with some specific text...

Tank's for that great apps...

**Comment by hluk** [comment]
You can change the command if you click "Show Advanced" checkbox in the command dialog. You can also change the command type to "In Menu" so it can be triggered from tray menu (or Insert menu).

> ![image](https://user-images.githubusercontent.com/38054/53243167-54b38400-36a7-11e9-8d11-d6eabe26d8e9.png)

**Comment by hluk** [comment]
See also [Snippets command](https://github.com/hluk/copyq-commands/tree/master/Global#snippets) in commands repository which helps with pasting customized texts.

**Comment by JRAuger** [comment]
I understand that it is possible to use the "Show Advanced" option to configure a command. Then we choose between the options: Automatic, In Menu, Global Shortcut, Display. But this will remain an order to be called by the Global Shotcut ...

This does not tell me how to combine in a single action, the insertion of a text with the date and time ... A bit like the insertion of a signature where the name, date and time will be inserted. Do you have an example of a command like "Paste current date and time", but adapted to add a section of text like the name of the signatory for example?

**Comment by JRAuger** [comment]
I just added the Snippets tab and it is operational (new tabs in CopyQ). This is a different way of calling actions? or sections of texts?

But still there, how to integrate in the same command the fact of sticking of the text and the order to insert date: hr: min....

**Comment by JRAuger** [comment]
Are there any commands to start actions like this one for example:

Start Firefox, to a precise html address?

Start Window Explorer but pointing to a specific path, for example? C: \ _ temp \ bobwalch

Show an accurate pdf file in the default homepage (Acrobat reader DC) for example? C: \ temp _ \ bobwalch \ marc-1.pdf

**Comment by hluk** [comment]
> Start Firefox, to a precise html address?

You can use "Open in Browser" predefined command (select it after clicking on Add button in the Command dialog).

Similarly you could change the command to open file browser at given path.

For details see: https://copyq.readthedocs.io/en/latest/writing-commands-and-adding-functionality.html

**Comment by JRAuger** [comment]
Okay, I have not yet answered my questions, but it's my fault, I ask too many questions at the same time. I progress well in the mastery of Copyq and every day I realize its power.

In copyq I made several TABs and in each of these TAB I added several ITEMS. In each ITEM, when I put text in it, no problem, to refer to these ITEMS later to use this great paperweight to select a lot of texts ...

But if for some of these ITEMS, I would like, when I select them: paste the "text" present, but also execute some commands. How can I do it?

For example, in a TAB, I would have several ITEMS where I have already written text like for example:

- Human Anatomy
- Human Body 1
- Grocery
- ect ...

And when I select the text "Human Body 1", CopyQ will start Firefox (default) with the desired web page like:
https://en.wikipedia.org/wiki/Human_body

I understand that I will have to use the command (F6): "Open in & Browser", but how will I have to configure this command to work specifically with my existing ITEM "Human Body 1"?

Thank you for your patience...

**Comment by JRAuger** [comment]
I understand that I will have to use the command (F6): "Open in & Browser", but how will I have to configure this command to work specifically with my existing ITEM "Human Body 1"?

**Comment by hluk** [comment]
> And when I select the text "Human Body 1", CopyQ will start Firefox (default) with the desired web page like:
> https://en.wikipedia.org/wiki/Human_body

You can use following command to open the web page when you select (double-click or Enter) item "Human Body 1" from main window.

```ini
[Command]
Command="
    copyq open 'https://en.wikipedia.org/wiki/Human_body'"
Icon=\xf15b
InMenu=true
Input=text/plain
Match=^Human Body 1$
Name=Human Body 1
Shortcut=enter
```

The Content field in command dialog (Advanced tab) matches the text and activates the command in menu or toolbar only if the selected item text is the same.
