### ISSUE TITLE
Using Enter to paste into remote Windows machine fails

### ISSUE THREAD

**Issue by amosbird** [hluk/CopyQ#1098]
**Describe the bug**

Press `Enter` on a non-first item to paste into remote windows desktop fails.

**To Reproduce**
1. use freerdp to connect to a remote windows box
2. copy a file with mimeUriList
3. copy any text so the file uri becomes the second item
4. focus freerdp and show copyq menu
5. select the second item and press enter

**Expected behavior**
file is pasted correctly

**Screenshots**

https://la.wentropy.com/U1dG.webm

Using `Enter` to paste fails. Using `Ctrl-V` or `Shift-Insert` works fine.

**Version, OS and Environment**
copyq version
CopyQ Clipboard Manager v3.7.3-19-g11059cfd
Qt: 5.12.1
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Arch Linux

**Comment by hluk** [comment]
Are you running CopyQ locally or on remote machine?

The file explorer probably needs some special format in clipboard.

**Comment by amosbird** [comment]
> Are you running CopyQ locally or on remote machine?

locally.

Hmm, but it somehow works when the item is the first one in copyq menu

**Comment by hluk** [comment]
> Hmm, but it somehow works when the item is the first one in copyq menu

Maybe that means that the clipboard did not completely change and the special formats from explorer are still available. Can you try copying another item in CopyQ and then pasting the first one? Or just move another item to the top and try to paste it?

**Comment by amosbird** [comment]
> Or just move another item to the top and try to paste it?

Hmm, moving the file uri item to the top first using ctrl-v and then paste it into Windows using ctrl-v works. So it does look like an incomplete data change. What can be done?

**Comment by hluk** [comment]
I remember trying to create command for this in past but failed because CopyQ (or more precisely Qt framework) couldn't see other formats in clipboard. You can try listing the formats after copying from explorer with Ctrl+Shift+C or:

```bash
copyq clipboard '?'
```

If you find additional format to save, you can create empty automatic command with just the "Format" field set to the format/MIME name - CopyQ will start saving it next time it's copied to clipboard.

**Comment by amosbird** [comment]
>  You can try listing the formats after copying from explorer with Ctrl+Shift+C 

You mean in remote right?

![image](https://user-images.githubusercontent.com/5085485/53432579-ba986680-3a2d-11e9-8258-c34f78e377d0.png)

I'm not sure if we can generate that weird binary content...

**Comment by hluk** [comment]
Hmm, if you cannot see the formats locally, that will be be a problem. Also, it seems that Qt has some translation layer for MIME on Windows so putting the formats to clipboard with CopyQ may not work anyway. But below are the automatic commands. You can verify that an item was stored with those formats by selecting it and pressing F4 key.

```ini
[Commands]
1\Automatic=true
1\Icon=\xf15b
1\Input="application/x-qt-windows-mime;value='CanUploadToCloudClipboard'"
1\Name=Save: CanUploadToCloudClipboard
2\Automatic=true
2\Icon=\xf15b
2\Input="application/x-qt-windows-mime;value='FileGroupDescriptorW'"
2\Name=Save: FileGroupDescriptorW
3\Automatic=true
3\Icon=\xf15b
3\Input="application/x-qt-windows-mime;value='CanlncludelnClipboardHistory'"
3\Name=Save: CanlncludelnClipboardHistory
size=3
```

**Comment by amosbird** [comment]
I don't follow. Those commands seem to do nothing. btw I'm a bit worried about the interference of copyq and freerdp. As far as I know, `FileGroupDescriptorW` is generated by freerdp when seeing text/uri-list

**Comment by hluk** [comment]
Those commands should only store the formats in new item, but maybe it's only possible to do that on remote machine if the local CopyQ instance don't see those clipboard formats.

**Comment by amosbird** [comment]
It doesn't work in remote copyq either. item still only contains text/plain but the clipboard has 4 entries

**Comment by amosbird** [comment]
It still looks like an incomplete clipboard transfer issue. Can I have the `Enter` key wait for 1 second before sending `shift-insert` for given window FreeRDP ?

**Comment by hluk** [comment]
You can add the delay but I don't think local instance of CopyQ will recognize the window running remotely.

```ini
[Command]
Command="
    copyq:
    hide()
    copy(mimeItems, input())
    sleep(1000)
    paste()"
Icon=\xf0ea
InMenu=true
Input=application/x-copyq-item
Name=Paste with delay
Shortcut=enter
```

**Comment by amosbird** [comment]
> I don't think local instance of CopyQ will recognize the window running remotely.

I mean the freerdp window, not the remote window in Windows box :)

adding delay works. So how can I check if the target window for receiving the paste is named `FreeRDP` and if so running that delayed paste?

**Comment by hluk** [comment]
OK, then maybe change the `sleep(1000)` to:

```js
if (currentWindowTitle().match(/FreeRDP/))
  sleep(1000)
```

**Comment by hluk** [comment]
Actually it seems it also needs small delay after the `hide()` so that `currentWindowTitle()` is not "CopyQ".

**Comment by amosbird** [comment]
Great! Thank you.

**Comment by amosbird** [comment]
This delay paste command doesn't work for multiple selected items
```
[Command]
Command="
    copyq:
    hide()
    select(index())
    //copy(mimeItems, input())
    sleep(50)
    if (currentWindowTitle().match(/^FreeRDP/))
      sleep(200)
    paste()
    filter('')"
Icon=\xf0ea
InMenu=true
Input=application/x-copyq-item
Name=Paste with delay
Shortcut=enter
```

How can I adapt it (perhaps some loop)?

**Comment by hluk** [comment]
`select(index())` means to select (and copy) just the current item (one of the selected, usually last one). Why did you replace the `copy(mimeItems, input())`?

**Comment by amosbird** [comment]
Cool! copy and copySelection works. btw, can I have alt-1-9 to paste the 1-9 items (acting like select the item and press Enter with delayed paste) ? I don't like adding nine actions...

**Comment by hluk** [comment]
You can check which shortcut triggered the action. Example:

```ini
[Command]
Command="
    copyq:
    var n = str(data(mimeShortcut)).slice(-1)
    select(n)"
Icon=\xf0cb
InMenu=true
Name=Select Nth Item
Shortcut=alt+1, alt+2, alt+3, alt+4, alt+5, alt+6, alt+7, alt+8, alt+9
```

**Comment by amosbird** [comment]
Can I invoke the `Paste with delay` action in this action after selecting a given item?

**Comment by hluk** [comment]
Well, either assign the shortcuts to the `Paste with delay` command and handle the digit keys there (in addition to `str(data(mimeShortcut)) == 'enter'`), or you could do simulate Enter key press (but it's undocumented feature only used for tests):

```js
selectItems(n)
keys('ENTER')
```

**Comment by amosbird** [comment]
hmm, this somehow doesn't work
```
[Command]
Command="
    copyq:
    hide()
    // select(index())
    shortcut = str(data(mimeShortcut))
    if (shortcut !== \"enter\") {
        n = shortcut.slice(-1)
        select(n)
    } else {
        copy(mimeItems, input())
        copySelection(mimeItems, input())
    }
    sleep(50)
    if (currentWindowTitle().match(/^FreeRDP/))
      sleep(200)
    paste()
    filter('')"
Icon=\xf0ea
InMenu=true
Input=application/x-copyq-item
Name=Paste with delay
Shortcut=enter
, alt+1, alt+2, alt+3, alt+4, alt+5, alt+6, alt+7, alt+8, alt+9
```

**Comment by hluk** [comment]
Oh, sorry, looks like the shortcut is an empty string (instead of "enter") because the trigger is actually item-activation event (like double clicking the item).

**Comment by amosbird** [comment]
Awesome, thanks!
