### ISSUE TITLE
Missing items and do not save images

### ISSUE THREAD

**Issue by evandrocoan** [hluk/CopyQ#1099]
**Describe the bug**
![image](https://user-images.githubusercontent.com/5332158/53502322-94ee7a00-3a8c-11e9-9edb-c19880b441c6.png)

**To Reproduce**
1. Create a screenshot and copy the image to the clipboard

**Version, OS and Environment**
```
CopyQ Clipboard Manager v3.2.0 (hluk@email.cz)
Built with: Qt 5.9.3, LibQxt 0.7.0
```
 - Application Version v3.2.0
 - OS Linux Mint XFCE 19.1
 - Desktop environment, XFCE4

This is how image items are displayed, and selecting them and pasting does nothing.
![image](https://user-images.githubusercontent.com/5332158/53502245-6ffa0700-3a8c-11e9-8335-e7d290dcf4f2.png)

**Comment by hluk** [comment]
Looks like the plugins are not loaded.

How did you install the app?

Is there any error or warning in the log (F12 shortcut)?

**Comment by evandrocoan** [comment]
I had installed it with: `sudo apt install copyq`

But now I closed the application and ran:
``` 
sudo add-apt-repository ppa:hluk/copyq
sudo apt update
sudo apt install copyq
```

And when I opened it, it was working!

**Comment by hluk** [comment]
Looks like you may have to install plugins separately (not sure if or why that's the case):

```bash
sudo apt install copyq copyq-plugins
```

**Comment by evandrocoan** [comment]
The plugins are installed now, after I had added `
sudo add-apt-repository ppa:hluk/copyq` and ran `
sudo apt install copyq`
