### ISSUE TITLE
suggest publish copyQ on portableapps.com

### ISSUE THREAD

**Issue by witwall** [hluk/CopyQ#11]
portableapps.com is a very famous portable app distrubtion website.

**Comment by scottkosty** [comment]
The Windows build is fixed right? (Note that I'm not actually familiar with the website above). I suppose it would go under the "Utilities" section.

witwall are you able to add CopyQ to the list yourself or is the developer supposed to do it?

**Comment by hluk** [comment]
Windows build is fixed -- I don't really know what was the problem anymore :).

I actually sent and request to portableapps to add CopyQ few years back -- I didn't get any response.

**Comment by hluk** [comment]
I'm closing this, if anyone needs this I would appreciate some help.
