### ISSUE TITLE
Remember last position in list of items being pasted not working

### ISSUE THREAD

**Issue by JeremyWW** [hluk/CopyQ#1101]
Windows 10 x64 Pro.

New laptop with fresh install of CopyQ. Previous machine was Windows 10 Home x64.

My workflow:

Copy a long list of names from another document thus forming a long list in a CopyQ tab that I then quickpaste (double click) one by one into an invoice for each person. On the previous machine with the same CopyQ config, CopyQ would 'remember' the last name pasted and leave it highlighted so for the next new invoice I'd always know where I was. Strangely, on the new machine, it isn't doing that - when I open CopyQ (under the cursor with a keyboard shortcut) the name at the top of the list is highlighted so I need to be careful and it's slowing down a very boring repetitive job. I don't allow CopyQ to move an 'activated' item to the top of the list (and it isn't doing that) - it' just not remembering where I was and I can't work out why!

Thanks

**Comment by hluk** [comment]
This broke because of d8c5fa6a58269e4aaacce6ef7bbcbcbf89ba62f6 in v3.7.3.

But in this case, it makes sense not to reset the selection so I'm fixing it.

Thanks for feedback.

**Comment by JeremyWW** [comment]
Thank you, yes please. This is genuinely very important so if you can fix that speedily I would be eternally grateful :-)

**Comment by hluk** [comment]
> Thank you, yes please. This is genuinely very important so if you can fix that speedily I would be eternally grateful :-)

Well, it's already fixed. :)

You can get the development build (with couple of other fixes) here: https://ci.appveyor.com/project/hluk/copyq/builds/22723166/job/mp0uscltyuspam1t/artifacts (it should be relatively stable)

**Comment by JeremyWW** [comment]
Thanks! The dev build works perfectly.
