### ISSUE TITLE
Paste inserts some text string instead of picture

### ISSUE THREAD

**Issue by NolanNolan** [hluk/CopyQ#1102]
**Describe the bug**
right clicking on a picture in edge selecting copy, then inserting in eg excel inserts some text reference not the actual picture. Using chrome or firefox doesn have this bug

**To Reproduce**
1. rignt click a picture in edge eg this: https://www.msn.com/da-dk/underholdning/verdenskongelige/quiz-kender-du-etiketten-i-det-britiske-kongehus/ar-BBJkBYM
2. seect copy picture
3.insert the picture in excel office 365
4. The error is: some text string is inserted instead of the actual picture

**Expected behavior**
The picture copied should have been inserted

**Screenshots**
not relevant

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Application Version 3.7.3
 - OS Windows 10 pro v 1809
 - Desktop environment, window manager (if applicable)

**Additional context**

**Comment by hluk** [comment]
Wasn't this was resolved in #1100? Solution is to use command in [this comment](https://github.com/hluk/CopyQ/issues/1100#issuecomment-467985200).

This is not a bug in CopyQ.

**Comment by NolanNolan** [comment]
yes, that was just because i realised afterwards it should have had its own ticket, it was commented in a string with other issues. Sorry, will make this stringent for the future

thanks

Nolan

**Comment by hluk** [comment]
No problem, thanks for your input, it helped me to improve CopyQ (fixed some text encoding issue). :)
