### ISSUE TITLE
Scheduled Backup

### ISSUE THREAD

**Issue by glolsh** [hluk/CopyQ#1103]
**Is your feature request related to a problem? Please describe.**
I lost contents of one of my tabs. No way to restore it.

**Describe the solution you'd like**
I'd like a way to perform scheduled backup of settings and tab contents

**Comment by hluk** [comment]
Any idea why the data was lost?

You can use File/Export... or `copyq exportData backup.cpq` (and to import `copyq importData backup.cpq`).

Alternatively, backup the whole configuration directory (`copyq info config` to get the config path) - but exit the app first. This is how I do backup now.

**Comment by glolsh** [comment]
There was over 7k rows, so I think CopyQ couldn't handle it. One day I just opened CopyQ and saw tab with almost nothing (it filled with new content)

Yeah I know that I can backup data Manually, but I'm asking about Scheduling backup, so I don't need to pay attention to it.
Other way is to make copy of current data each day ( or at application start)

**Comment by scottkosty** [comment]
There are tools dedicated to backups. I think it is better to rely on one of them than to have CopyQ add that feature. Have you considered using `cron` or something similar?

**Comment by glolsh** [comment]
Yeah, I think it's possible to do that on *nix systems using cron. Maybe it's possible to do that on Windows via Scheduler or on Mac with (I don't know what performs scheduled actions there) something.
But you know, there are always some ways around problems. Instead of CopyQ I can use notepad (users say that when I try to convert them to CopyQ-users) or something like that. 
LibreOffice makes scheduled backups when working with documents, as well as MS Office soft. Many Android apps make backups automatically. 
This feature will make CopyQ more practical and safe, but hell yeah, why develop more features if it's fine the way it is.
I'll write outside script for that if you won't make this feature inside app.

**Comment by hluk** [comment]
In next release it will be possible to run a command automatically when application starts or exits. So to make backup at application exit you can use following command.

```ini
[Command]
Command="
    var onExitPrevious = global.onExit
    global.onExit = function() {
        onExitPrevious()
    
        var backupDir = Dir().home()
    
        backupDir.mkdir('Documents')
        backupDir.cd('Documents')
    
        backupDir.mkdir('copyq-backups')
        backupDir.cd('copyq-backups')
    
        var fileName = backupDir.absoluteFilePath(
            dateString('yyyy-MM-dd-hh-mm-ss.cpq'))
        exportData(fileName)
    }"
Icon=\xf0a0
IsScript=true
Name=Backup On Exit
```

You'll have to verify if the files are being created, AFAIK on some systems (e.g. desktop without any session management) it's possible that when shutting down, the application is just killed without being able to save its state.

Just few things additional things to implement for the command:
- verify that backup is created and is not empty,
- remove old backups (limit number of files or used space).

Note: The `onExit` handler is run even if the application is killed by a signal on *nix systems (unless it's SIGKILL).

**Comment by glolsh** [comment]
Thanks, I'll check it this week.

**Comment by hluk** [comment]
Just a note: You'll still need a dev build since the new functionality is not part of latest release (3.7.3).

**Comment by glolsh** [comment]
Oh, then I'll wait till release

**Comment by fyanchev** [comment]
using 3.8.0 - added the auto backup script on exit, but there is no copyq folder under Documents, am I looking at the wrong place or how can I select different folder on my PC to store the backups.

Is there a way to determine the number of backups - lets say to keep last 5-10 backups, or I have to delete the old once by myself?

Thank you for your reply and time taken. The app is great, just moved from Ditto and trying to figure out all the options - really appreciate your efforts and time to evolve such a wonderful app.

**Comment by hluk** [comment]
I've added the command to copyq-commands repository: https://github.com/hluk/copyq-commands/tree/master/Scripts#backup-on-exit

It now contains two variables to set the backup path and number of backups to keep.

The default path is "Documents/copyq-backups" in home directory. Not sure what is the absolute path on Windows, maybe you can access it from explorer with "%HOME%\Documents\copyq-backups".

Let me know if there is better default path.

**Comment by fyanchev** [comment]
Hi, tried the new script, did not work. Maybe I am doing something wrong. 

Created a folder copyq-backups in my Documents folder - path is D:\Documents\copyq-backups

The scripts shows Documents\copyq-backups - not aware if the / \ brake the script. 

I have changed the first line of the script to show:
var backupPath = 'D:\Documents\copyq-backups' - which did not work either - exit copyq but folder is empty. 

Sorry to bother you again and maybe its a stupid question - but I am doing something wrong. Working on a Windows and Linux mint machine, looking for a way to make everything work on both, backup both and also have access to the clipboard of both systems - some kind of synchronization. 

Thank you.

**Comment by hluk** [comment]
Use [forward slash as path separator](https://doc.qt.io/qt-5/qdir.html#details) in the script:

```js
var backupPath = 'D:/Documents/copyq-backups'
```

Do you see any errors in the log (F12 shortcut) after you start CopyQ again?

**Comment by fyanchev** [comment]
Only this errors, but they are not connected with the backup - 
Warning [2019-04-30 10:53:31.711] <Server-6368>: Failed to set global shortcut "Meta+Alt+T" for command "Paste Current Time".
Warning [2019-04-30 10:56:11.777] <Server-6368>: Failed to set global shortcut "Meta+Alt+T" for command "Paste Current Time".
Warning [2019-04-30 10:56:14.009] <Server-6368>: Failed to set global shortcut "Meta+Alt+T" for command "Paste Current Time".
Warning [2019-04-30 11:18:55.422] <Server-11868>: Failed to set global shortcut "Meta+Alt+T" for command "Paste Current Time".

**Comment by fyanchev** [comment]
Just checked again forward slash as path separator solved the problem - not the backups work - thank you for your time and solution :)

**Comment by hluk** [comment]
> Just checked again forward slash as path separator solved the problem - not the backups work - thank you for your time and solution :)

No problem. I'll add a note about the path separator the API documentation - otherwise it's really confusing.
