### ISSUE TITLE
copyq main window not showing on startup

### ISSUE THREAD

**Issue by GamerGirlandCo** [hluk/CopyQ#1106]
in a previous version of copyq, (v3.7.1) i could double click the .exe file or click the taskbar icon and voila, the main window would show. however, upon updating it to v3.7.3, the main window no longer shows up, just a weird window that says `<EMPTY>`.
does anyone know what's wrong or how to fix this?

**Comment by nmat** [comment]
can you please provide which environment you are on? Windows or linux?

Also can you test the latest version of 3.8.0?
