### ISSUE TITLE
Bug: Rendering chinese(中文) font problem & only have one language option

### ISSUE THREAD

**Issue by balalaXD** [hluk/CopyQ#1107]
**A square box rendering for chinese/中文 text.**
![2019-03-10_101703](https://user-images.githubusercontent.com/16096559/54079770-bd446700-431d-11e9-9adf-3756d431341a.png)
### And the language option only have English choice.
![2019-03-10_101418](https://user-images.githubusercontent.com/16096559/54079772-c2091b00-431d-11e9-9483-aefa0df6fa12.png)

**To Reproduce**
1. Copy 中国
2. and you got two squares

**Expected behavior**
Display as it is.

**Version, OS and Environment**
CopyQ Clipboard Manager v3.7.1
Qt: 5.11.2
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Manjaro Linux

**Comment by hluk** [comment]
Maybe the font in GUI don't support the characters. Can you see the same problem when you open main window (click Show/Hide from the menu)? Try to set different font using "Preferences..." menu item, under Appearance tab.

Apart from that, it looks like no other language is installed. It depends on system but translation files are usually installed in `/usr/share/copyq/translations/`.

**Comment by balalaXD** [comment]
main window still displays hollow box.
```
/usr/share/copyq/translations
➜ ls -1                
copyq_ar.qm
copyq_cs.qm
copyq_da.qm
copyq_de.qm
copyq_es.qm
copyq_fr.qm
copyq_hu.qm
copyq_it.qm
copyq_ja.qm
copyq_lt.qm
copyq_nb.qm
copyq_nl.qm
copyq_pl.qm
copyq_pt_BR.qm
copyq_pt_PT.qm
copyq_ru.qm
copyq_sk.qm
copyq_sv.qm
copyq_tr.qm
copyq_uk.qm
copyq_zh_CN.qm
copyq_zh_TW.qm
```

**Comment by hluk** [comment]
What does `copyq info translations` command print?

**Comment by balalaXD** [comment]
```bash
➜ copyq info translations
/usr/share/copyq/translations
```

**Comment by balalaXD** [comment]
is there an option to set `copyq menu` font, if so, i think change the font could fix the problem.

**Comment by hluk** [comment]
To fix the context menu font, I think you also have to enable option "Set colors for tabs, tool bar and menus" in the Appearance tab. But ideally use better default system font.

It's strange that the translations are not listed in GUI even though the files are in the expected location. Is there anything in the log (F12 shortcut)?

**Comment by balalaXD** [comment]
Although nothing happen by pressing `F12`, but now you mention translations then i view it again in GUI, it work by weird... maybe it's the problem of `fcitx` or `ibus`, i don't know, recently i just remove `ibus` and install `fcitx`. thanks :+1: :smile:

**Comment by balalaXD** [comment]
maybe it work by `export LC_ALL=zh_CN.UTF-8` in my `~/.profile`

**Comment by balalaXD** [comment]
G

**Comment by MarkFirewhal** [comment]
Same issue, on windows. It displays a ton of chinese text, but if you dig into it... it's the actual text that was copied. 
Still, a HUUUUUUUUUGE turn off for anyone installing. Oh hum, let me install new software. Oh, weird... it turned everything I copy to Mandarin. That doesnt look like my computer just got a nasty trojan installed by CopyQ. 

This was a fast uninstall for me, and makes this software look like a joke. Might not want to close this thread again.
