### ISSUE TITLE
can not move the picture to the clipboard with copyQ

### ISSUE THREAD

**Issue by mjchow** [hluk/CopyQ#1109]
I can not move the picture to the clipboard with copyQ
text has worked but picture not worked

my operating system is deepin-linux 15.9.2

**Comment by hluk** [comment]
Can you provide steps so I can reproduce this?

**Comment by mjchow** [comment]
> Can you provide steps so I can reproduce this?

1. i use deepin-screenshot tool to screenshot
2. and then the picture is inside my clipboard also inside copyQ. because i can see that in copy item list.
3. and then i copy text, but not use picture in clipboard. 
4. after I paste the text, I move from the picture in the copy to the clipboard. but the picture can not paste.

**Comment by hluk** [comment]
Works fine for me. Is that happening only when pasting to specific application?

**Comment by mjchow** [comment]
> Works fine for me. Is that happening only when pasting to specific application?

emmmm, sorry. i use synergy . i mean i can not pasting picture to anther pc and it worked local pc normal.

**Comment by hluk** [comment]
> > Works fine for me. Is that happening only when pasting to specific application?
> 
> emmmm, sorry. i use synergy . i mean i can not pasting picture to anther pc and it worked local pc normal.

Something like that was already mentioned in #793. Not sure if there is anything I can do about it.

Disclaimer: I don't use synergy so currently I don't care enough to get this fixed myself.

**Comment by mjchow** [comment]
> > > Works fine for me. Is that happening only when pasting to specific application?
> > 
> > 
> > emmmm, sorry. i use synergy . i mean i can not pasting picture to anther pc and it worked local pc normal.
> 
> Something like that was already mentioned in #793. Not sure if there is anything I can do about it.
> 
> Disclaimer: I don't use synergy so currently I don't care enough to get this fixed myself.

thank u.

**Comment by mjchow** [comment]
> > > Works fine for me. Is that happening only when pasting to specific application?
> > 
> > 
> > emmmm, sorry. i use synergy . i mean i can not pasting picture to anther pc and it worked local pc normal.
> 
> Something like that was already mentioned in #793. Not sure if there is anything I can do about it.
> 
> Disclaimer: I don't use synergy so currently I don't care enough to get this fixed myself.

i find a situation.
If it's a bigger picture that can not through synergy with copyQ Shear plate
but Small picture can work normal.
