### ISSUE TITLE
Is it possible to provide a bookmark label?

### ISSUE THREAD

**Issue by ghostry** [hluk/CopyQ#1110]
be like iCopy (mac app: Ashvin Ajadiya 「iCopy: Copy & Paste Text」),
There are three labels in the popup layer,{all,bookmark,top}

**Comment by hluk** [comment]
Did you try [tags](https://copyq.readthedocs.io/en/latest/tags.html)?

**Comment by ghostry** [comment]
This doesn't seem to be what I want. I found another feature [tabs](https://copyq.readthedocs.io/en/latest/tabs-and-items.html#tabs), but it can only be used in the main window, not the popup layer.

**Comment by hluk** [comment]
I don't understand the requested feature here. What you mean by "the popup layer"?

 Can you provide video or screenshots to underline the functionality?

**Comment by ghostry** [comment]
![](http://2.bp.blogspot.com/-B5kQP-TT1sU/USyU5dS9-7I/AAAAAAAAOHk/TY8ZdthwJUw/s1600/copyq.png)
I hope there are tabs to click here.

**Comment by hluk** [comment]
Oh, putting tabs in tray menu (or doing anything special with it) is not even possible in many desktop environments those menus get hijacked by the desktop environment. It's already missing the search field -- you can open the original menu using `copyq menu` command.

The menu was designed only to quickly pick an item to paste, anything more complicated can be done using the main window.

Tip: You can set a tab which is used for the menu and [pin](https://copyq.readthedocs.io/en/latest/pin-items.html) some frequent item to the top of the tab.

**Comment by ghostry** [comment]
The author of iCopy solved my problem and the issue was closed.
