### ISSUE TITLE
Can't seem to synchronize a nested tab

### ISSUE THREAD

**Issue by cpsyctc2** [hluk/CopyQ#1111]
**Describe the bug**
I'm not sure if this is a bug or me missing something.  I am converting from Windoze to Linux and am running CopyQ in Ubuntu 18.04.2 LTS which is great.  I've also got the Windoze version of CopyQ running in a VirtuaBox Windoze on the same machine and used export to export my tabs successfully and I'm now setting up synchronize to synch between the two versions.  That works fine for top level tabs but when I try to do it for nested tabs new items don't show in the Windoze CopyQ.

**To Reproduce**
1. I followed the instructions to set up the synchronization.  (I would love a "synch all" option!) and it's working fine for the top level tabs but when I put the tab name in as top_level_tabname/childname it doesn't, nor if I just put childname in without the top level name.  (My child level tab names are unique across top level tabs.)

**Expected behavior**
I had expected items to show up in the Windoze CopyQ as they do for top level tabs (brilliant feature: huge thanks) but they just don't for the child level tabs.

**Version, OS and Environment**
On Ubuntu:
 - CopyQ Clipboard Manager v3.2.0 (hluk@email.cz)
    Built with: Qt 5.9.3, LibQxt 0.7.0
 - OS Ubuntu 18.04.02 LTS
 - Gnome desktop

On Windoze:
- CopyQ v3.7.3
- OS Windows 10 Home version 1804

**Additional context**
Can't think of anything to add.  Sorry if I'm missing something obvious.

**Comment by hluk** [comment]
Maybe try to copy the full tab name to the sync config from the combo box "Tab for storing clipboard" in History config tab.

> ![image](https://user-images.githubusercontent.com/38054/54838663-71080800-4cc9-11e9-8a8e-22b44c5ed7a2.png)

I should improve the configuration UI for the sync plugin (and other plugins too).

**Comment by cpsyctc2** [comment]
Got it. I'm not sure if that's actually different from what I thought I was typing in before but this time it worked.  I guess it would be great to have a drop down selection from the tab list, and I'd reiterate my request for a "synch all" option but you seem to have solved my problem. Thanks.  Hugely impressive.
