### ISSUE TITLE
Could we have named items within tabs?

### ISSUE THREAD

**Issue by cpsyctc2** [hluk/CopyQ#1112]
**Is your feature request related to a problem? Please describe.**
Sort of.  I have come to CopyQ from ClipClip on windoze and have a lot of standard "boilerplate" type clips of many different sizes but some are quite big.  ClipClip allowed me to give them a name so that it was easy to see what was what in the list of items within a tab.

**Describe the solution you'd like**
The ability to replace the appearance of the whole of an item within a tab with a short name.  No need for this in the main copy buffer.  Would be good perhaps if the names of the named clips/items showed up in the listings in a different colour from unnamed clips to avoid any confusion.

**Describe alternatives you've considered**
I can't think of any.  Sorry.

**Additional context**
Can't think of any!

**Comment by hluk** [comment]
You can attach note to the item with Shift+F2, and you can hide the item content with [this command](https://github.com/hluk/copyq-commands/tree/master/Application#hideshow-item-content) (see [the commands repo description](https://github.com/hluk/copyq-commands/blob/master/README.md) for details).

There is also [this command](https://github.com/hluk/copyq-commands/tree/master/Application#mark-selected-items) which allows to toggle a color for selected item (though you would need to modify it to assign different colors).

**Comment by cpsyctc2** [comment]
Magic.  Exactly what I needed and works perfectly. Sorry I didn't find that.  Many thanks.
