### ISSUE TITLE
Question: what does "Auto-cleanup of translation" do?

### ISSUE THREAD

**Issue by Trost123** [hluk/CopyQ#1114]
Screenshot attached below. What does it do?
Tried searching in Google and in this repository code - this feature remains a mystery to me, please help :stuck_out_tongue_closed_eyes: 
![Screenshot](https://i.imgur.com/3un2sNU.png)

**Comment by hluk** [comment]
I have no idea where this is from. The menu doesn't look like it comes from CopyQ.

Can you provide more information?

**Comment by Trost123** [comment]
> I have no idea where this is from. The menu doesn't look like it comes from CopyQ.
> 
> Can you provide more information?

Because it doesn't come from CopyQ. It comes from QTranslate. Damn I'm stupid xD You found the bug, issue closed. :laughing:

**Comment by hluk** [comment]
No problem. I thought it could be some Qt translation tool but I couldn't find the menu in [linguist-qt5](https://download.qt.io/linguist_releases/) (the tool I'm using for translating).

BTW, you can also translate using [Weblate](https://hosted.weblate.org/projects/copyq/).

**Comment by Trost123** [comment]
Actually, QTranslate is a desktop utility, just like CopyQ, but it
specializes in giving popup translation for selected text when you double
press CTRL. They both are free, lightweight and have Q in their name so I
mixed it up. 🙂
