### ISSUE TITLE
Formatted view in CopyQ does not look like source for text copied from Word

### ISSUE THREAD

**Issue by richlux** [hluk/CopyQ#1115]
**Describe the bug**
When text is copied from Microsoft Word, the formatted text that displays in CopyQ does not look like the source

**To Reproduce**
1. Create a document in Microsoft Word with varying text formatting, including a table
2. Copy the text
3. Compare the formatted text shown in CopyQ to the text in Word

**Expected behavior**
The formatting should be the same in both CopyQ and Word.

**Screenshots**
Source text from Microsoft Word:
![image](https://user-images.githubusercontent.com/25157703/55179531-0427be80-515e-11e9-87c7-1e4476df51b6.png)

Formatted Text in CopyQ:
![image](https://user-images.githubusercontent.com/25157703/55179549-14d83480-515e-11e9-91d5-2582efa859c8.png)

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - CopyQ Version 3.7.3
 - Windows 10

**Additional context**
When I use the "Show Content" feature to view the content, all of the proper formatting is there and when I paste the clip back into Word, it looks correct.  It's simply how the text is displayed in CopyQ that is incorrect.

**Comment by hluk** [comment]
The text appearance depends on what the copied HTML contains (it's usually much simpler form, missing some default fonts styles etc.) and how well CopyQ can parse and display it (it's using the functionality from Qt).

So this is not possible for me to fix (or very difficult).

**Comment by richlux** [comment]
Thanks for the explanation.
