### ISSUE TITLE
How to save items permanently?

### ISSUE THREAD

**Issue by evandrocoan** [hluk/CopyQ#1117]
I have some stickies notes I always use. How can I save them permanently?

**Comment by hluk** [comment]
Not sure what do you mean. Adding note to an item (Shift+F2) should save the note with the item data in CopyQ.

**Comment by evandrocoan** [comment]
Now I relooked, what I want is to permanently save clipboard items.

I think I can do this by creating a new tab and dragging items into it:
![image](https://user-images.githubusercontent.com/5332158/55439656-ab9c5b00-557b-11e9-8d46-2a8487fff7c9.png)
