### ISSUE TITLE
Opening clipboard manager on Mac Mojave in full screen mode has extremely bad usability.

### ISSUE THREAD

**Issue by CrajyB** [hluk/CopyQ#1118]
**Describe the bug**
CopyQ upon window activation does not show on top of Full screen window, instead flips to the desktop space and closes. Need to re-hit hot keys for it to pop up but now since you are on a different window, you have to find your Full screen window again then paste the contents you copied to paste buffer.

**To Reproduce**
1. Use Mac Mojave OS
2. Put window into full screen spaces view with option+ctrl+f
3. Hit copyq hot key to show window to paste.

**Expected behavior**
The copyq clipboard manager window should popup on top of active full screen window.

**Screenshots**

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - 3.7.2
 - Mac Mojave OS 10.14.2

**Comment by hluk** [comment]
Isn't this duplicate of #939?

**Comment by CrajyB** [comment]
Yes appears so. We should keep tracking in #939 .
