### ISSUE TITLE
images disappear

### ISSUE THREAD

**Issue by Booya00** [hluk/CopyQ#1122]
Thank you for your good work. I run into problems. I would like to save the format text and pictures under a tab X. After I have moved the item, it will not include the image only text. Under clipboard I see the images and can copy them. Is there a solution? Thanks.

**Comment by hluk** [comment]
> After I have moved the item

Not sure what do you mean by "moved"? Can you post steps to reproduce this?

**Comment by Booya00** [comment]
I would like to save an item in the clipboard pernament under a tab. I create a new tab. Copy an item in Word. After this the item is in clipboard. I drag the item to the tab that I would like to save for the future. I restart the computer. I want to use the item again under the tab I created. I click on copy to clipboard. Paste it in Word and get to see the text and a square with a red cross, where an image should be. It contains the message "The image cannot be displayed." Thanks.

**Comment by hluk** [comment]
Check what formats the item in CopyQ contains (select item, and press F4). There should be probably `image/png` or something similar (and it should show the image after clicking on the format).

Also, after copying, see if the clipboard contains any image format (copy item, double-click or Ctrl+C, and press Ctrl+Shift+C to inspect the formats in clipboard).

Make sure you use the latest version (currently v3.7.3).

**Comment by Booya00** [comment]
If i open show content, i could see text/html and text/plain. If i copy an image, icould see the image. Is it possible to save an image and text under a item?

**Comment by hluk** [comment]
CopyQ will ignore images in clipboard if there is also plain text - there were some issues with Excel and possibly other apps.

> Is it possible to save an image and text under a item?

Maybe by creating an automatic command but it's probably not trivial.

I can improve [the condition on which the images are ignored](https://github.com/hluk/CopyQ/blob/c7a667abba7a5c26abc1ca3bb937942abb2ffe3d/src/common/common.cpp#L268) but I'm not sure how.
