### ISSUE TITLE
CMakeLists.txt should not use "${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_MANDIR}"

### ISSUE THREAD

**Issue by oniGino** [hluk/CopyQ#1123]
**Describe the bug**
Hello!, I'm your package maintainer over at Gentoo :)

Getting some complaints from higher up on your handling of 
    `set(MANPAGE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_MANDIR}/man1" CACHE PATH "Install path for manual pages")`

which should read

   ` set(MANPAGE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}/man/man1" CACHE PATH "Install path for manual pages")`
or
   ` set(MANPAGE_INSTALL_PREFIX "${CMAKE_INSTALL_MANDIR}/man1" CACHE PATH "Install path for manual pages")`

in order to be compliant with CMake guidelines here:
https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html

Users may see a /usr/usr/man directory with the current usage.

Please let me know what you think of changing this.

Thanks!

**Comment by hluk** [comment]
Fixed. Thanks for the report.
