### ISSUE TITLE
Question: How to choose between plain/rich text on the fly.

### ISSUE THREAD

**Issue by JeremyWW** [hluk/CopyQ#1124]
I've always had to compromise with this:

Most of the time I need rich text/HTML ignored when copying because I'm pasting continuously into my own pre-formatted documents with a double mouse click where I want the pasted text to adopt the target document formatting automatically (if any), but need to see/edit the items initially in CopyQ as plain text. To achieve that I uncheck the 'Save and display HTML and rich text' option in Preferences | Items | Text which works. That isn't always convenient though - if I'm doing a mailshot and need to copy/paste rich text rapidly into new emails in Outlook I need to select that option again in Preferences to avoid losing the original formatting which in this case I want. Is there a quicker way of switching between the two/converting a list of copied rich text items into plain text on the fly when needed?

Thanks.

**Comment by JeremyWW** [comment]
I found the following in another issue but it only works on single selected items. Any way to have that work on multiple selected items?

[Command]
Command="
    copyq:
    removeData(mimeHtml)"
Icon=\xf12d
InMenu=true
Input=text/html
Name=Remove HTML

**Comment by hluk** [comment]
Here is the "Remove HTML" command fixed to work with multiple items:

```ini
[Command]
Command="
    copyq:
    removeData(mimeHtml)"
Icon=\xf12d
InMenu=true
MatchCommand=copyq: if (!(mimeHtml in selectedItemData(0))) fail()
Name=Remove HTML
```

Another way could be to have special tab where only plain text is saved.

```ini
[Command]
Automatic=true
Command="
    copyq:
    if ( !isClipboard() )
      abort()
    tab('text')
    add(input())"
Icon=\xf15c
Input=text/plain
Name=Plain Text Tab
```

**Comment by JeremyWW** [comment]
These both work perfectly - thanks!
