### ISSUE TITLE
random failures when copying from shortcut script

### ISSUE THREAD

**Issue by daviddoji** [hluk/CopyQ#1127]
First of all, thanks a lot for this magnificent piece of software!

I've created a global shortcut to paste a figure environment for LaTeX code. I can choose it from the menu, but when applying it, I have to repeat the operation 2-3 times because it refuses to paste it.

I'm using the cody you have in here:
https://github.com/hluk/copyq-commands/blob/master/Global/snippets.ini

What could be the problem? Let me know how I can debug it.

**Comment by hluk** [comment]
What's your CopyQ version, OS, desktop environment?

**Comment by daviddoji** [comment]
Oops, sorry for that.
I'm using Archlinux with Plasma Desktop. CopyQ is v3.8.0

**Comment by hluk** [comment]
Does pasting with Enter key from main window work fine? (Option "Paste to current window" needs to be enabled - in "History" config tab.)

It could be caused by some delay in focusing the target window. Is it a specific application CopyQ fails to paste into?

**Comment by daviddoji** [comment]
Thanks for the fast reply!
No, pasting with Enter does not work all the time. I've tried that and the result is that it pastes not always.
I'm using the shortcut to paste code in Firefox and KDE goes back to the window which previously had the focus on. Is it possible to add a delay? Just to discard this.

**Comment by hluk** [comment]
You can try adding `sleep(100)` (wait for 100 milliseconds) before `paste()` in the command.

> I'm using the shortcut to paste code in Firefox and KDE goes back to the window which previously had the focus on.

You mean it focuses wrong window?

I should probably change how this works in CopyQ. Currently, it tries to store the last focused window by listening to various window manager events (could be unreliable) so it's able to ensure that the window is focused again before pasting the clipboard.

**Comment by daviddoji** [comment]
You can try adding sleep(100) (wait for 100 milliseconds) before paste() in the command.
