### ISSUE TITLE
ESC doesn't clear the filter string

### ISSUE THREAD

**Issue by amosbird** [hluk/CopyQ#1128]
I have this command for toggling the image filter.

```
[Command]
Command="
    copyq:
    var filter_ = '^image/.*'
    if (filter() == filter_)
      filter('')
    else
      filter(filter_)"
Icon=\xf1c5
InMenu=true
Name=Filter Images
Shortcut=ctrl+i
```

However when closing the search field via `ESC`, the filter string remains non empty. I have to press `ctrl+i` twice to toggle the filter back. Is there a way to fix this?

**Comment by hluk** [comment]
Yup, that's a bug. Nice find!

**Comment by amosbird** [comment]
hmm, are you sure it's fixed? I just tried without luck

**Comment by hluk** [comment]
The fix is not yet in any released version and I merged it into master just moments ago.

**Comment by amosbird** [comment]
yeah, it works. Thanks!

**Comment by amosbird** [comment]
Hmm, this patch introduces a different behavior. When pressing enter in a filtered main window, copyq exits and pastes that item without clearing the filter string. The next time `copyq toggle` shows the filter string again.
