### ISSUE TITLE
stdout into copyq

### ISSUE THREAD

**Issue by vlad88sv** [hluk/CopyQ#1129]
**Is your feature request related to a problem? Please describe.**
I can't store the stdout or stderr of a command to copyq

**Describe the solution you'd like**
For example:
`$ ./custom_comand.sh file1 file2 | copyq add -`

Or even more straightforward:
`$ ./custom_comand.sh file1 file2 | copyq`

**Describe alternatives you've considered**
[CopyQ CLI docs](https://copyq.readthedocs.io/en/latest/command-line.html)

**Additional context**
Please!!!

**Comment by hluk** [comment]
Works fine for me. Following command creates new item in the first tab.

```bash
echo NEW_ITEM | copyq add -
```

Do your commands print any errors?

**Comment by vlad88sv** [comment]
lol I tried several things including `copyq copy /dev/stdout` but never occurred to me trying what I was suggesting here (`copyq add -`), shame on me.

Thanks!.
