### ISSUE TITLE
3.7.3-mac release did not get fix promoted to 3.8.0-mac release

### ISSUE THREAD

**Issue by CrajyB** [hluk/CopyQ#1130]
I tested this out and the below commit does not appear to have been promoted to the 3.8.0-macosx release.

https://github.com/hluk/CopyQ/commit/d1cf88af40b1d8f2644a13279cc9e155c811d43d

I checked the source code and do not see it in the code and just to be sure I installed the 2 versions of 3.8.0 and neither of them resolve the issue of having CopyQ show on-top of fullscreen windows.

I do not want to lose this fix!

**Comment by hluk** [comment]
Oh, forgot to merge that one. Thanks for the info.

**Comment by hluk** [comment]
Hmm, looking back at the commits, d1cf88af was merged to v3.8.0 as 2d2e8c2e. The fullscreen fix is d06ffd45 (also part of the release).

If the fix did not help, please reopen #939. But make sure you test it with v3.8.0 -- the version is mentioned in the About dialog (Shift+F1).

**Comment by CrajyB** [comment]
Interesting... okay I guess I didn't look in the right place in the code? I did check the same file listed in the commit in 3.8.0 and 3.8.0-macosx and did not see it there.

I did test but let me test again. I have so many builds downloaded to my laptop that I may have just made a user error.
