### ISSUE TITLE
High CPU usage every 5 seconds

### ISSUE THREAD

**Issue by mikenakis** [hluk/CopyQ#1131]
When CopyQ is just sitting there doing nothing, and without any activity happening in the machine other than playing a video on youtube via chrome, (and certainly no clipboard activity,) CopyQ pops up at the top of the system monitor (when sorted by % CPU) once every 5 seconds.  

**To Reproduce**
1. Configure CopyQ to synchronize clipboard entries with a certain folder.  (Say, ~/tmp/clipboard)
2. Use CopyQ for a few days, so that you have of the order of 1600 files in that folder. 
3. Run some tool that shows you the most time consuming processes, refreshing automatically once a second.

**Observed behavior**
CopyQ mostly stays out of the top of the list, but it does appear at the top of the list once every 5 seconds, (very predictably so,) with about one-and-a-half core worth of CPU consumption.

**Expected behavior**
I would expect CopyQ to _**never**_ appear at the top of the list while I am not interacting with CopyQ, or with the clipboard.

**Version, OS and Environment**
CopyQ v3.8.0
Ubuntu 18.04. (Moderately hacked, but I do not expect that to make any difference.)

**Additional context**
The problem seems to be related to the number of copyq_*.txt files that I have in my synchronized clipboard folder.  I moved that folder away, and CopyQ stopped appearing at the top of the most-CPU-consuming-processes list.  I moved that folder back in its place, and CopyQ started appearing there again.

Suggestion (entering feature request territory) 

I do not know what CopyQ is doing, but it looks like it checks the folder every 5 seconds to see if something has changed.  Normally, operations of this kind are handled with some sort of filesystem notification about a change in the contents of a directory, so as to avoid polling.  Even polling as infrequently as once every 5 seconds becomes problematic when the amount of work to be carried out at the poll event is considerable.

Besides that, the clipboard sync feature is a bit of an overkill compared to what I need, which is simply the ability to have my clipboard history saved, so that I can refer to it (using a text editor) it in the rare event that I might lose an important piece of information which I know I saved to the clipboard at some point in the past.  So, a clipboard history feature (as opposed to the clipboard sync feature) would be using just one text file instead of a multitude of text files, and it would only be appending to that file, never reading from it. That would be a lot more efficient than clipboard sync for those who do not need the full functionality of sync.

Also please note that the question of how to preserve the contents of the popup menu between sessions is completely unrelated to clipboard history.  For that, you could be using a smaller text file that duplicates the last entries of the history file, and is limited to only as many entries as can fit in the popup menu.  This way you avoid having to read the entire history file during CopyQ startup only to extract the last few entries from it.  (A write-only history file allows the user to not have to worry about putting a limit to how large the history can grow, so the history file can become quite huge, so huge that you would not even want to have to read it once every time CopyQ starts up.)

**Comment by hluk** [comment]
>  Normally, operations of this kind are handled with some sort of filesystem notification about a change in the contents of a directory, so as to avoid polling.

When I started implementing the synchronization plugin I used [QFileSystemWatcher](https://doc.qt.io/qt-5/qfilesystemwatcher.html). Unfortunately, it did not work well. But this was a long time ago so perhaps it's time to try again.

So currently the directory content is polled in 5s intervals, as you figured out already.

For a start I could make the update interval configurable.

> So, a clipboard history feature (as opposed to the clipboard sync feature) would be using just one text file instead of a multitude of text files, and it would only be appending to that file, never reading from it.

I think this is possible by using an automatic command that writes to a text file (it may need to do some file locking and truncating if the file gets too big).

Not sure how having single text file for synchronization would work since CopyQ supports other data formats.

Looks like your use case is different from what synchronization plugins was designed to do -- it reads the data from synced directory back so e.g. multiple CopyQ instances can share the item list and you can actually edit the items using other apps.

**Comment by dwfreed** [comment]
I see this on Windows too (v3.8.0).  My use-case for synchronization is that I just want a history that'll persist across reboots, and I don't intend to edit it at all outside of CopyQ.

**Comment by hluk** [comment]
I'm trying to fix this so that the items are updated from disk only if you have the synced tab focused (or read the items from command line or script).

I've also increased the interval to 10s. You'll be able to change it by setting `COPYQ_SYNC_UPDATE_INTERVAL_MS` environment variable.
