### ISSUE TITLE
Icon disappears in Manjaro Gnome

### ISSUE THREAD

**Issue by tiotrom** [hluk/CopyQ#1132]
Manjaro Gnome. 

1. Open CopyQ
2. Lock your device
3. Unlock - see the icon disappears from the top panel
CopyQ is still active as you can see in the system monitor. Kill it from there, and re-open and the icon appears again.

**Comment by hluk** [comment]
Probably issue in Gnome, a Gnome extension for tray icons or even Qt framework.

I don't think there is much I can do about this. I've spent too much time trying to fix tray icon issues.

**Comment by online** [comment]
@hluk, hello. Tell me, please, how to solve this problem with icons in system tray?
![problem_with_icons](https://user-images.githubusercontent.com/722881/102660009-0710e100-4183-11eb-9523-9658dae87ca2.png)

OS: Manjaro Linux x86_64 
Kernel: 5.9.11-3-MANJARO 
Resolution: 1920x1080 
DE: GNOME 3.38.1 
WM: Mutter 
WM Theme: Matcha-dark-sea 
Theme: Matcha-sea [GTK2/3] 
Icons: Papirus-Dark-Maia [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i5-3550 (4) @ 3.700GHz 
GPU: NVIDIA GeForce GTX 660 Ti
