### ISSUE TITLE
Image editing doesn't work when text formats exist

### ISSUE THREAD

**Issue by amosbird** [hluk/CopyQ#1133]
![image](https://user-images.githubusercontent.com/5085485/56859016-40497b80-69b7-11e9-8839-7449a13d6693.png)

![image](https://user-images.githubusercontent.com/5085485/56859023-53f4e200-69b7-11e9-964b-eb11a94f2c05.png)

Can I have the edit command check image first?

**Comment by hluk** [comment]
That's currently not possible (or not easily done) unless you remove the text format.

Any reason there is a text stored with the image?

**Comment by amosbird** [comment]
> Any reason there is a text stored with the image?

Ok, I'll keep using ItemNotes then. Thanks!
