### ISSUE TITLE
external editing (F2) closes the main window

### ISSUE THREAD

**Issue by amosbird** [hluk/CopyQ#1134]
When doing external editing of current item, copyq's main window gets closed which is inconvenient to paste the edited items. https://la.wentropy.com/3aA0.webm

**Comment by hluk** [comment]
Probably caused by "Close When Unfocused".

Not sure if I can make the main window keep open when opening the external editor. Maybe re-opening when editor is closed would work better.

Workaround is to call a script that opens the editor and shows main window afterwards again. E.g.

```
#!/bin/bash
gvim -f "$1" && copyq show
```

**Comment by hluk** [comment]
Can you test the commit (58ed15758b94d35df219770ee4068523e9a4ec33)?

**Comment by amosbird** [comment]
Thanks! it works as expected

**Comment by amosbird** [comment]
@hluk Hi, I just noticed we should also disable copyq from storing clipboard changes when external editor is opened. Or else the current selected item gets nudged away.

**Comment by hluk** [comment]
> Hi, I just noticed we should also disable copyq from storing clipboard changes when external editor is opened. Or else the current selected item gets nudged away.

@amosbird True. I'm changing it so it works a bit better - after external editor is closed, the focus should return to the edited item (probably no need to disable clipboard storing).

Also, it doesn't make sense to focus main window if you finish editing clipboard (`copyq edit`).

**Comment by amosbird** [comment]
ok, lemme rebase and test.

**Comment by amosbird** [comment]
> I'm changing it 

Hmm, so it isn't landed yet? I've tested and it still focuses the first one. But I still feel that disabling makes more sense as editing the clipboard shouldn't really generate anything anymore

**Comment by hluk** [comment]
The changes are in `fix-show-after-edit` branch.
