### ISSUE TITLE
Always add to clipboard list even if duplicate item

### ISSUE THREAD

**Issue by zjgdbansd** [hluk/CopyQ#1136]
I'm using macOS and I was able to build from source. I'm trying to customize my build to always add to clipboard storage, even if the previous item is exactly the same. For example, if I do Command+C on **[1, 2, 3, 3]** then I want the CopyQ list to be **[1, 2, 3, 3]** and not **[1, 2, 3]**. Also, I am trying to make the "automatic" trigger also work any time Command+C is pressed.

I tried modifying the code but it does not work. Do you think you can point me in the right direction?

I tried using the custom script mentioned here https://github.com/hluk/CopyQ/issues/576 but it did not work, so I am trying to force it.

**Comment by amosbird** [comment]
I have similar issues related to copyq's deduplication process. Sometimes two items get combined when clipboard changes too quickly.

**Comment by hluk** [comment]
I think it's related to [this method](https://github.com/hluk/CopyQ/blob/193e3ab09c8e2dd454c876849b848fdaefb740df/src/gui/clipboardbrowser.cpp#L1644) and also to [this code](https://github.com/hluk/CopyQ/blob/193e3ab09c8e2dd454c876849b848fdaefb740df/src/app/clipboardmonitor.cpp#L98).

Following command somewhat works but it can also create too many duplicate entries:

```ini
[Command]
Command="
    var saveDataPrevious = global.saveData
    global.saveData = function() {
      var outputTab = str(data(mimeOutputTab))
      var text = str(data(mimeText))
      if (outputTab && text) {
        tab(outputTab)
        add(text)
      }
      saveDataPrevious()
    }
    
    global.onClipboardUnchanged = function() {
      onClipboardChanged()
    }"
Icon=\xf0c7
IsScript=true
Name=Always Save Clipboard
```

**Comment by zjgdbansd** [comment]
> I think it's related to [this method](https://github.com/hluk/CopyQ/blob/193e3ab09c8e2dd454c876849b848fdaefb740df/src/gui/clipboardbrowser.cpp#L1644) and also to [this code](https://github.com/hluk/CopyQ/blob/193e3ab09c8e2dd454c876849b848fdaefb740df/src/app/clipboardmonitor.cpp#L98).
> 
> Following command somewhat works but it can also create too many duplicate entries:
> 
> ```ini
> [Command]
> Command="
>     var saveDataPrevious = global.saveData
>     global.saveData = function() {
>       var outputTab = str(data(mimeOutputTab))
>       var text = str(data(mimeText))
>       if (outputTab && text) {
>         tab(outputTab)
>         add(text)
>       }
>       saveDataPrevious()
>     }
>     
>     global.onClipboardUnchanged = function() {
>       onClipboardChanged()
>     }"
> Icon=\xf0c7
> IsScript=true
> Name=Always Save Clipboard
> ```

Thanks for the tips. Have you tested that command script and have you verified that it works? I put the script in, but nothing happens when I copy the same item multiple times.

I made these changes to the code:

[clipboardmonitor.cpp](https://github.com/hluk/CopyQ/blob/193e3ab09c8e2dd454c876849b848fdaefb740df/src/app/clipboardmonitor.cpp#L98)
`
    // if ( hasSameData(data, *clipboardData) ) {
    //     COPYQ_LOG( QString("Ignoring unchanged %1")
    //                .arg(mode == ClipboardMode::Clipboard ? "clipboard" : "selection") );
    //     emit clipboardUnchanged(data);
    //     return;
    // }
`

[clipboardbrowser.cpp](https://github.com/hluk/CopyQ/blob/193e3ab09c8e2dd454c876849b848fdaefb740df/src/gui/clipboardbrowser.cpp#L1644
`
    // if ( hasSameData(data, *clipboardData) ) {
    //     COPYQ_LOG( QString("Ignoring unchanged %1")
    //                .arg(mode == ClipboardMode::Clipboard ? "clipboard" : "selection") );
    //     emit clipboardUnchanged(data);
    //     return;
    // }
`

I still could not trigger adding the same item. Do you know why these aren't working?
