### ISSUE TITLE
Clipboard storing doesn't work on wayland

### ISSUE THREAD

**Issue by fl0wsnake** [hluk/CopyQ#1140]
**Describe the bug**
`clipboardMonitor` process immediately takes down one thread. `Disable clipboard storing` solves this issue. No copied items appear on the list either way.

**To Reproduce**
Run the copyq daemon.

**Screenshots**
![image](https://user-images.githubusercontent.com/17596565/57326050-37be1700-7114-11e9-9fa7-ca3bff84f894.png)

**Version, OS and Environment**
> copyq --version
CopyQ Clipboard Manager v3.8.0
Qt: 5.11.3
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Fedora 30 (Workstation Edition)

**Comment by hluk** [comment]
I'm also on Fedora 30, but using Xorg session instead. Maybe I should switch for a while to Wayland (still need to be able to record my desktop occasionally which doesn't seem to be supported in Wayland).

Can you run following two commands to get a backtreace of the monitor process? It could point me to the misbehaving code.

```bash
pkill -ABRT -f "copyq monitorClipboard"
coredumpctl dump
```

**Comment by fl0wsnake** [comment]
Here you go:
```
> pkill -ABRT -f "copyq monitorClipboard"
> coredumpctl dump
           PID: 31872 (copyq)
           UID: 1000 (cyril)
           GID: 1000 (cyril)
        Signal: 6 (ABRT)
     Timestamp: Fri 2019-05-10 15:25:21 EEST (11s ago)
  Command Line: /usr/bin/copyq monitorClipboard
    Executable: /usr/bin/copyq
 Control Group: /user.slice/user-1000.slice/session-1.scope
          Unit: session-1.scope
         Slice: user-1000.slice
       Session: 1
     Owner UID: 1000 (cyril)
       Boot ID: f77afed41ed84397a72982be69c4455b
    Machine ID: 96bc82a80b504f2bb7e0893342d3eca1
      Hostname: localhost.localdomain
       Storage: /var/lib/systemd/coredump/core.copyq.1000.f77afed41ed84397a72982be69c4455b.31872.1557491121000000.lz4 (truncated)
       Message: Process 31872 (copyq) of user 1000 dumped core.
                
                Stack trace of thread 31872:
                #0  0x00007f96d03ec989 n/a (n/a)
Refusing to dump core to tty (use shell redirection or specify --output).
```

**Comment by hluk** [comment]
Unfortunately the trace seems cropped in your output.

I tried using Wayland yesterday but did not notice high CPU usage with CopyQ.

Are there any errors/warnings in log (F12 shortcut)?

Do you use any automatic commands? (F6 to open Command dialog.)

**Comment by fl0wsnake** [comment]
Here's erorr log:
![image](https://user-images.githubusercontent.com/17596565/57577601-4c3b4000-7483-11e9-8388-ad292942c0d1.png)
It goes on like this from the start of application.
I tried enabling and disabling all the commands and restarting Copyq with no avail.
