### ISSUE TITLE
autokey like functionality

### ISSUE THREAD

**Issue by tecan** [hluk/CopyQ#1142]
would be great to see hotkey global paste support added example press ctrl+g to paste "git clone " at the commandline with something like xclip

**Comment by Snowy556** [comment]
I believe  you can already do this:

```
[Command]
Name=New command
Command="
    copyq:
    var otext = str(clipboard())
    copy(\"git clone\")
    paste()
    copy(otext)"
IsGlobalShortcut=true
Icon=\xf15b
GlobalShortcut=ctrl+shift+g
```

The above simply inserts git clone, when you press the hotkey, and then re-copies whatever was previously in your clipboard.

You should also check out the snippets commands available on the extra commands Github:
https://github.com/hluk/copyq-commands/tree/master/Global#screenshot

**Comment by magpie514** [comment]
I have been trying to do something like this lately but I've been kinda stumped as I cannot seem to find a way to pass a string to paste to copyq, choosen with a selector such as rofi or copyq itself.
Yes, I could copy the input string as clipboard content and then "pop" the latest entry then restore as seen in Snowy's script, but I don't know if that's entirely safe to do if some edge case arrives and I'd end up losing something "important" from it (as in needing to go back to wherever I copied that text to copy it again.)

Reading the documentation I can seem to be able to run it from command line as a function with arguments, but I'm at a loss as to how to make a function accessible that way, but in theory it should allow to paste arbitrary strings without having to shuffle the clipboard/current tab around too much.

I'm sorry if this is more "discussion" than "issue" talk, but it seems apropos enough.

**Comment by Snowy556** [comment]
I think the snippets command is exactly what you are looking for.
https://github.com/hluk/copyq-commands/tree/master/Global#snippets
With Snippets, you create a new clipboard named Snippets, and add items like templates in this snippets clipboard.
You can then use the hotkey you have assigned to the snippets command to bring up a dropdown box that will allow you to select which template you want to paste.

If you are talking about the fact that CopyQ can only add text via the clipboard, I agree. Being able to directly add text without fiddling with the clipboard would be nice.

**Comment by magpie514** [comment]
Ah, yeah, talking about the later. It seems possible, I am pretty sure I saw something in the docs, but I can't remember exactly *where* so I'm at a loss as to how (or where) to declare a global function that the CLI can reach. Given that ability and coupled with a selector (rofi or dmenu, or fzf in a terminal, or even CopyQ itself if you aren't working with a huge list) to feed it text you can pretty much use a single CopyQ script to paste all the text you can remember to store.:thinking: And you can either load entries manually from a file or use CopyQ's synchronization to get a folder monitored. 

I actually tried the snippets command, it's pretty good for basic usage! But it had some issues like not liking certain characters and not allowing default values for tokens, which didn't make it super suitable for bigger code snippets, which is what prompted me to try making one to suit my personal use. 

To be perfectly honest one could in theory make everything inside CopyQ, it definitely has the power and I'm barely scratching the surface of the sheer potential, but I prefer to delegate CopyQ to just clipboard duty in this specific case so I can reuse the backend for terminal and GUI use.

**Comment by magpie514** [comment]
Ah, found out how!
All you need to do is add a new command, set it as a *script* and fill it like:

```
global.testfunc = function(_input) {
 var _clipboard = clipboard()
 copy(_input); paste(); copy(_clipboard)
}
```

then `$copyq testfunc "Hello World"` will paste "Hello World" into the currently selected window and the clipboard will be undisturbed. Of course that's useless by itself, so all that's left to do is set up keybindings or a chooser script.
For example this one-liner
`copyq testfunc "$(cat ~/.local/share/tldr/{common.txt,linux.txt} | rofi -dmenu)"`
will let me pick from a list of preformatted [tldr](https://github.com/tldr-pages/tldr) I can paste in my terminal or anywhere. Saves me from using the dirty hack around readline I was using previously to fill the prompt.
Anyway I hope this helps. With a setup like this you can paste pretty much anything and keep it all in a tiny command. I used rofi for the example but you can also use fzf or peco or your favorite picker to do it all on the terminal. At least with Konsole this approach works fine.
