### ISSUE TITLE
How to increment the date returned by dateString?

### ISSUE THREAD

**Issue by Snowy556** [hluk/CopyQ#1143]
Hi Hluk,

I love the software and the work you do on it!

My question is the following, I am trying to get a date in the future automatically.
Instead of inserting today's date with 
`dateString('yyyy-MM-dd HH:mm:ss')`

I am trying to get a date 2 days in the future. I have tried the following after reading the qt documentation, but It doesn't work. I'm assuming that this is because of the way the dateString function works.

`dateString('yyyy-MM-dd HH:mm:ss').addDays(2)`

Is there an easy way to automatically paste a date / time in the future when executing a command?

**Comment by hluk** [comment]
`dateString()` only returns string: https://copyq.readthedocs.io/en/latest/scripting-api.html#String%20dateString

There is no alternative to Qt date/time classes in the scripting engine CopyQ uses.

Maybe try `Date` js class: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

**Comment by Snowy556** [comment]
Wow, I didn't realize I could just use straight javascript, this is great!
Thank you, my working code is below for posterity:
```
copyq:
var date1 = new Date(Date.now())
date1.setDate(date1.getDate() + 2)
copy(date1.toDateString()+ '\n')
paste()
```

**Comment by hluk** [comment]
> Wow, I didn't realize I could just use straight javascript

Not JavaScript per se, it's [Qt Script](https://doc.qt.io/qt-5/qtscript-index.html). Very similar but some functionality from js is missing.
