### ISSUE TITLE
Commands in tray menu do nothing at all 

### ISSUE THREAD

**Issue by memeplex** [hluk/CopyQ#1145]
**Describe the bug**

Maybe I don't know how this is supposed to work but commands (pin, tag, etc) in the tray menu seem to have no effect (I assume they should operate on the current selection).

**To Reproduce**
1. Copy something into the clipboard
2. Open the tray menu
3. Click pin
4. Open copyq main window
5. The selection is not pinned

**Expected behavior**

Commands in the tray menu should work on the current selection, as commands in the main window toolbar.

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Application Version 3.8.0
 - Arch Linux
 - Gnome 3.32 (tested under both Xorg and Wayland)

```
~:: copyq version
CopyQ Clipboard Manager v3.8.0
Qt: 5.12.2
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Arch Linux
```

**Comment by hluk** [comment]
Yeah, this is really odd.

Commands which are marked as "In Menu" are shown in menus and tool bars. There is no way of saying that a command should be only in main window menu and not in tray.

Perhaps better way would be to show only "Global Shortcut" commands in tray.
