### ISSUE TITLE
API command to expire/unload tabs on demand

### ISSUE THREAD

**Issue by akwala** [hluk/CopyQ#1148]
**Is your feature request related to a problem? Please describe.**
There doesn't seem to be a way to expire/unload tabs on demand. This would be useful if tabs need to be made inaccessible, or encrypted, in a hurry.

**Describe the solution you'd like**
Create an API function that unloads the tabs when called -- this could then be used to create a command that can be assigned a shortcut.

**Describe alternatives you've considered**
I don't see a function in the current API that provides the ability to do this.

**Additional context**

**Comment by hluk** [comment]
Unloading an encrypted tab doesn't necessarily mean that it will ask for password next time it's opened. It depends on the GPG agent that CopyQ uses - it will usually allows to decrypt data without asking for password again for some time.

Related question: https://askubuntu.com/questions/349238/how-can-i-clear-my-cached-gpg-password

I think CopyQ would need to handle password entry and act as GPG agent to have some control over this.

With that I don't see other reason to unload tab on demand.

**Comment by akwala** [comment]
The passphrase cache of gpg-agent is cleared by doing either of the following:
`gpg-connect-agent reloadagent /bye`
`gpgconf --reload gpg-agent`

After the cache is cleared, accessing encrypted tabs requires the passphrase, regardless of gpg-agent's caching interval or CopyQ's unload interval. However, tabs that were decrypted prior to clearing the passphrase cache remain decrypted and accessible without a passphrase prompt. Unless I'm missing something, the decrypted tabs need to be unloaded before clearing the passphrase cache in order to ensure that they can't be accessed again without a passphrase prompt. 

IOW, the use case I described would entail unloading CopyQ tabs on demand, followed by clearing gpg-agent's passphrase cache on demand.

**Comment by hluk** [comment]
> IOW, the use case I described would entail unloading CopyQ tabs on demand, followed by clearing gpg-agent's passphrase cache on demand.

That could be a nice feature in the encryption plugin - maybe just clear cached passwords and unload tab after the tab is closed. But it would probably mean implementing the agent or clearing the password cache in existing agent (though this is for all signing keys/passwords on system). This could be very difficult to implement on all platforms, especially Windows.

**Comment by akwala** [comment]
> clear cached passwords ... after the tab is closed

It would be overreach for CopyQ to clear gpg-agent's passphrase cache, not a good idea. What I meant was that CopyQ would only provide a way to trigger unloading of tabs. Clearing the passphrase cache would be a separate step, outside CopyQ, which the user would do at their discretion. For instance, I could create a keyboard shortcut in Ubuntu for the following command sequence:
`copyq unload; gconf --reload gpg-agent`
where `unload()` is the API function that unloads the tabs in the running instance of CopyQ. After doing this, the next time I try to access any tab listed under Encrypted Tabs in Preferences -> Items -> Encryption, I'd be presented a passphrase prompt.

For now, `copyq exit` in place of `copyq unload` is a workaround, which is OK as long as I don't need to access any tabs that are not encrypted -- the tabs I usually need all happen to be encrypted, so the workaround isn't too inconvenient.

>... unload tab after the tab is closed

Automatically unloading tabs independently of the configured unload interval defeats the purpose of the unload interval.

**Comment by hluk** [comment]
OK, it's not difficult to add the new function.

API documentation for `unload`:

```
String[] unload([tabNames...])

   Unload tabs (i.e. items from memory).

   If no tabs are specified, unloads all tabs.

   If a tab is open and visible or has an editor open, it won't be unloaded.

   Returns list of successfully unloaded tabs.
```

Does that look OK?

**Comment by akwala** [comment]
>If a tab is open and visible or has an editor open, it won't be unloaded.

Why? Can't such a tab be rolled back to its last saved state and unloaded?

This is a security hole in this use case. The aim is to do a forced unload -- calling the function forceUnload() would make that clearer.

**Comment by hluk** [comment]
> > If a tab is open and visible or has an editor open, it won't be unloaded.
> 
> Why? Can't such a tab be rolled back to its last saved state and unloaded?
> 
> This is a security hole in this use case. The aim is to do a forced unload -- calling the function `forceUnload()` would make that clearer.

Forcefully unloading the tab would kill the editor (internal and external) with any unsaved changes made in the editor. Also, after unloading currently open tab (when window is visible) it would appear as there are no items.

**Comment by akwala** [comment]
> Forcefully unloading the tab would kill the editor (internal and external) with any unsaved changes made in the editor.

That's what I'd expect. Can't this be treated in the same way as closing the file/tab in the editor before saving changes, i.e., presenting a confirmation dialog asking whether unsaved changes should be discarded?

> after unloading currently open tab (when window is visible) it would appear as there are no items.

This is precisely the desired behavior. This happens when trying to open an encrypted tab with an invalid passphrase; the tab appears empty except for a reload button. Clicking the reload button presents the passphrase prompt; if the tab is not encrypted, clicking this button could just load the tab.

**Comment by akwala** [comment]
@hluk I tested the new script function in the unload-script-function branch. 

With a subset of my encrypted tabs decrypted, if I did `copyq unload` followed by `gpgconf --reload gpg-agent`, then all the decrypted tabs remained accessible, not just the open/visible one. A passphrase prompt appeared only when I tried to access a tab that wasn't previously decrypted. 

When I switched the order of the commands, i.e., `gpgconf --reload gpg-agent` followed by `copyq unload` then only the open/visible tab was accessible. All other encrypted tabs required a passphrase for access, including those that were previously decrypted. This is the desired behavior except for the open/visible tab remaining accessible, as I explained in my previous post.

I also found that the above behavior was the same regardless of the main window being open or hidden.

**Comment by hluk** [comment]
Works fine for me. Maybe the command to reset password cache doesn't work well.

Try updating your clone of `unload-script-function` git branch.

You can also try using `forceUnload`. This can unload any tabs and will require you to click the refresh button to reload the data.

**Comment by akwala** [comment]
> You can also try using `forceUnload`. This can unload any tabs and will require you to click the refresh button to reload the data.

Thank you! This works nicely.

My 2 (more) cents re `unload()`: 

> If a tab is open and visible or has an editor open, it won't be unloaded.

I can't think of a use case for `unload()` with this exception. I envisioned `unload()` as identical to `forceUnload()` except that `unload()` would present a confirmation dialog asking whether unsaved changes should be discarded if an item was being edited.

Regardless, a version of `forceUnload()` that presents a confirmation dialog if an editor is open would be useful.

**Comment by hluk** [comment]
> Regardless, an additional version of forceUnload() that presents a confirmation dialog if an editor is open would be useful.

I would rather avoid opening confirmation dialog (or requiring any UI interaction) when calling functions from a script. But you can use the `unload()` to check if  a tab needs `forceUnload()`:

```js
copyq:
var tab = 'secrets'
if (unload(tab).length == 0) {
    notification(
        '.title', 'Force unload?',
        '.time', 5000,
        '.button', 'Unload', 'copyq: forceUnload(input())', tab)
}
```
