### ISSUE TITLE
A dropdown to show recent items in clipboard

### ISSUE THREAD

**Issue by rampatra** [hluk/CopyQ#1149]
I have used ClipMenu on Mac and one feature I really love about it is that when you press `Ctrl+Shift+V` you get a dropdown where ever your cursor is and then you easily choose what to paste by using your arrow keys. 

A simple `Ctrl+V` just pastes the most recent item in the clipboard.

Does CopyQ have this feature?

**Comment by hluk** [comment]
You can try this: https://copyq.readthedocs.io/en/latest/faq.html#how-to-open-application-window-or-tray-menu-using-shortcut

**Comment by rampatra** [comment]
This is exactly what I wanted. Thanks a million :)
