### ISSUE TITLE
Improvements for RTL text rendering

### ISSUE THREAD

**Issue by aurora-of-earth** [hluk/CopyQ#1151]
A few small improvements for Right-to-Left text rendering in CopyQ:
- When editing an item, make CopyQ change the text direction especially the blinking cursor's alignment according to the direction of the system's current keyboard locale.

If I input a dash at the beginning of a new line and then change the keyboard locale to a RTL language, the cursor is still at the left until I input a character specific to that RTL locale.

**Comment by hluk** [comment]
This must be bug in Qt framework [1]; I don't mess around with the text direction setting (nor do I want to - better to leave this to Qt folks).

[1] https://bugreports.qt.io/secure/Dashboard.jspa

**Comment by aurora-of-earth** [comment]
@hluk I've reported the bug at <a href="https://bugreports.qt.io/browse/QTBUG-76154">here</a>.
So I close this issue.

**Comment by hluk** [comment]
Thanks for reporting the Qt bug. If you find any other inconsistencies in GUI let me know (mainly if the GUI widget ordering is unusual).
