### ISSUE TITLE
CopyQ slows down selecting text in Emacs with X forwarding

### ISSUE THREAD

**Issue by CyberShadow** [hluk/CopyQ#1152]
**Describe the bug**
When CopyQ is running, selecting text using Shift + Arrow Keys in an Emacs session running over X forwarding becomes much slower.

This is even though in settings, under "Clipboard Manipulation", the only thing that's selected is "Store clipboard", and nothing is selected on the "Items" tab. So, as far as I can see, the only thing that's changing in Emacs is the selection, which CopyQ should not care at all.

**To Reproduce**
1. Run Emacs over an SSH session with X forwarding on a remote host.
2. Note the difference in responsiveness when selecting text when CopyQ is running vs. not running.

**Version, OS and Environment**
```
CopyQ Clipboard Manager v3.8.0
Qt: 5.12.2
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Arch Linux
```
 - Desktop environment - none, window manager - i3gaps

**Comment by hluk** [comment]
Even with all the option under "Clipboard Manipulation" disabled, the X11 selection and clipboard text is still retrieved for automatic commands (and some default behavior).

I think the only way to avoid CopyQ accessing selection and clipboard is to use "File - Disable Clipboard Storing" (Ctrl+Shift+X).

You can use following command to do this automatically if you can match the remote window title. It will block clipboard monitoring on the first copy/selection operation from the window until it other window is focused.

```ini
[Command]
Command="
    var windowTitlesToIgnore = new RegExp('Emacs')
    var iconColorWhenIgnored = 'orange'
    var iconColorDefault = ''
    
    function shouldIgnoreCurrentWindow()
    {
        var windowTitle = str(currentWindowTitle())
        return windowTitlesToIgnore.test(windowTitle)
    }
    
    function disableMonitor()
    {
        ignore()
        disable()
        iconColor(iconColorWhenIgnored)
    
        while (true) {
            sleep(5000)
            if ( !shouldIgnoreCurrentWindow() )
                break
        }
    
        iconColor(iconColorDefault)
        enable()
    }
    
    var onClipboardChanged_ = onClipboardChanged
    onClipboardChanged = function() {
        if ( shouldIgnoreCurrentWindow() )
            disableMonitor()
        else
            onClipboardChanged_()
    }"
Icon=\xf05e
IsScript=true
Name=Ignore Windows
```

**Comment by CyberShadow** [comment]
Thank you for responding and for posting that workaround. I don't have any commands defined. If possible, it would be nice if CopyQ could still store newly copied text to its clipboard history, while disabling monitoring of the selection if there are no configured reasons to do so.

**Comment by hluk** [comment]
> disabling monitoring of the selection if there are no configured reasons to do so.

OK, I'm also adding new option to disable running automatic commands on selection - default is enabled - someone may depend on this.
