### ISSUE TITLE
CopyQ prompts to download loads of fonts individually

### ISSUE THREAD

**Issue by gibfahn** [hluk/CopyQ#1153]
**Describe the bug**

When I restarted my laptop, I got ~20 consecutive prompts to download and install fonts.

**To Reproduce**

1. I have CopyQ installed through brew
2. I just rebooted my machine.

**Expected behavior**

One popup with all the fonts.

**Screenshots**

<img width="419" alt="image" src="https://user-images.githubusercontent.com/15943089/58379666-a3223880-7f9e-11e9-9be3-a0d462e8c3ba.png">

(the next dialog doesn't appear until the previous one is fixed)

**Version, OS and Environment**

```console
$ copyq version
CopyQ Clipboard Manager v3.8.0-osx
Qt: 5.12.2
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: macOS Mojave (10.14)
```

**Comment by hluk** [comment]
Whoa, WTH? CopyQ doesn't require any special fonts.

Maybe it's some strange behavior on macOS when a missing font is encountered in HTML clipboard data that needs to be rendered.

...Found similar problems:
- https://apple.stackexchange.com/questions/272073/when-attempting-to-open-some-ms-word-docs-im-asked-to-download-stheiti-and-ot
- https://discussions.apple.com/thread/7795254

**Comment by gibfahn** [comment]
>Maybe it's some strange behavior on macOS when a missing font is encountered in HTML clipboard data that needs to be rendered.

That could be it, I have my clipboard history at `9999`, so there's probably all sorts of stuff in there.

I'm not quite sure why it prompted as part of updating CopyQ though...

**Comment by hluk** [comment]
I can reproduce this with following command.

```
copyq write text/html '<p style="font-family: YuMincho">TEST</p>'
```

In Qt the download font dialog is shown when calling `QTextEdit::setDocument()` with `QTextDocument` instance containing the HTML code from the command above.

Unfortunately, I cannot find a way to prevent opening the download dialog.

Here is full backtrace from CopyQ when the dialog is open:

<details>
<pre>
1  mach_msg_trap                                                                                                                                                                                                (x86_64) /usr/lib/system/libsystem_kernel.dylib                                                                                                         0x7fff7536f22a 
2  mach_msg                                                                                                                                                                                                     (x86_64) /usr/lib/system/libsystem_kernel.dylib                                                                                                         0x7fff7536f76c 
3  __CFRunLoopServiceMachPort                                                                                                                                                                                   (x86_64) /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation                                                                  0x7fff49276e6d 
4  __CFRunLoopRun                                                                                                                                                                                               (x86_64) /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation                                                                  0x7fff492763da 
5  CFRunLoopRunSpecific                                                                                                                                                                                         (x86_64) /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation                                                                  0x7fff49275b35 
6  CFMessagePortSendRequest                                                                                                                                                                                     (x86_64) /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation                                                                  0x7fff493196b2 
7  __DownloadFontsForProperties_block_invoke                                                                                                                                                                    (x86_64) /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontRegistryUI.dylib      0x7fff4793bdff 
8  _dispatch_client_callout                                                                                                                                                                                     (x86_64) /usr/lib/system/libdispatch.dylib                                                                                                              0x7fff751ed63d 
9  _dispatch_lane_barrier_sync_invoke_and_complete                                                                                                                                                              (x86_64) /usr/lib/system/libdispatch.dylib                                                                                                              0x7fff751f9129 
10 DownloadFontsForProperties                                                                                                                                                                                   (x86_64) /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontRegistryUI.dylib      0x7fff4793bcf2 
11 TDownloadableFontManager::Download()                                                                                                                                                                         (x86_64) /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontRegistry.dylib        0x7fff47909092 
12 XTCopyFontsWithProperties                                                                                                                                                                                    (x86_64) /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontRegistry.dylib        0x7fff478fb8a4 
13 TDescriptorSource::CopyDescriptorsForRequestFromXType(__CFDictionary const *, CFComparisonResult ( *)(void const *, void const *, void *), unsigned long) const                                              (x86_64) /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText                                                                              0x7fff4aed4d48 
14 TDescriptorSource::CopyDescriptorsForRequest(__CFDictionary const *, __CFSet const *, CFComparisonResult ( *)(void const *, void const *, void *), void *, unsigned long, TCFRef<__CFArray const *> *) const (x86_64) /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText                                                                              0x7fff4aed3bf2 
15 TDescriptorSource::CopyDescriptorForRequest(__CFDictionary const *, __CFSet const *, CFComparisonResult ( *)(void const *, void const *, void *), void *, unsigned long) const                               (x86_64) /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText                                                                              0x7fff4aed35a8 
16 TDescriptor::CreateMatchingDescriptorInternal(__CFSet const *, bool) const                                                                                                                                   (x86_64) /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText                                                                              0x7fff4ae8a4bf 
17 TDescriptor::InitBaseFont(bool)                                                                                                                                                                              (x86_64) /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText                                                                              0x7fff4ae9aa40 
18 TDescriptor::CreateMatchingDescriptor(__CFSet const *, double, unsigned long) const                                                                                                                          (x86_64) /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText                                                                              0x7fff4ae8a01c 
19 CTFontCreateWithFontDescriptor                                                                                                                                                                               (x86_64) /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText                                                                              0x7fff4ae90bb1 
20 ___lldb_unnamed_symbol1698$$libqcocoa.dylib                                                                                                                                                                  (x86_64) /usr/local/Cellar/qt/5.12.3/plugins/platforms/libqcocoa.dylib                                                                                  0x105be5542    
21 ___lldb_unnamed_symbol1201$$QtGui                                                                                                                                                                            (x86_64) /usr/local/opt/qt/lib/QtGui.framework/Versions/5/QtGui                                                                                         0x10122099e    
22 QFontDatabase::findFont(QFontDef const&, int)                                                                                                                                                                (x86_64) /usr/local/opt/qt/lib/QtGui.framework/Versions/5/QtGui                                                                                         0x101228501    
23 QFontDatabase::load(QFontPrivate const *, int)                                                                                                                                                               (x86_64) /usr/local/opt/qt/lib/QtGui.framework/Versions/5/QtGui                                                                                         0x10122ae26    
24 QFontPrivate::engineForScript(int) const                                                                                                                                                                     (x86_64) /usr/local/opt/qt/lib/QtGui.framework/Versions/5/QtGui                                                                                         0x10120005d    
25 QTextEngine::fontEngine(QScriptItem const&, QFixed *, QFixed *, QFixed *) const                                                                                                                              (x86_64) /usr/local/opt/qt/lib/QtGui.framework/Versions/5/QtGui                                                                                         0x1012309ff    
26 QTextEngine::shapeText(int) const                                                                                                                                                                            (x86_64) /usr/local/opt/qt/lib/QtGui.framework/Versions/5/QtGui                                                                                         0x10122f709    
27 QTextLine::layout_helper(int)                                                                                                                                                                                (x86_64) /usr/local/opt/qt/lib/QtGui.framework/Versions/5/QtGui                                                                                         0x1012487a6    
28 ___lldb_unnamed_symbol1551$$QtGui                                                                                                                                                                            (x86_64) /usr/local/opt/qt/lib/QtGui.framework/Versions/5/QtGui                                                                                         0x10128edc5    
29 ___lldb_unnamed_symbol1540$$QtGui                                                                                                                                                                            (x86_64) /usr/local/opt/qt/lib/QtGui.framework/Versions/5/QtGui                                                                                         0x1012859ff    
30 ___lldb_unnamed_symbol1550$$QtGui                                                                                                                                                                            (x86_64) /usr/local/opt/qt/lib/QtGui.framework/Versions/5/QtGui                                                                                         0x10128dec6    
31 ___lldb_unnamed_symbol1549$$QtGui                                                                                                                                                                            (x86_64) /usr/local/opt/qt/lib/QtGui.framework/Versions/5/QtGui                                                                                         0x10128d325    
32 QTextDocumentLayout::doLayout(int, int, int)                                                                                                                                                                 (x86_64) /usr/local/opt/qt/lib/QtGui.framework/Versions/5/QtGui                                                                                         0x101290f7f    
33 QTextDocumentLayout::documentChanged(int, int, int)                                                                                                                                                          (x86_64) /usr/local/opt/qt/lib/QtGui.framework/Versions/5/QtGui                                                                                         0x101290a67    
34 QTextDocument::documentLayout() const                                                                                                                                                                        (x86_64) /usr/local/opt/qt/lib/QtGui.framework/Versions/5/QtGui                                                                                         0x10125a870    
35 ___lldb_unnamed_symbol2800$$QtWidgets                                                                                                                                                                        (x86_64) /usr/local/opt/qt/lib/QtWidgets.framework/Versions/5/QtWidgets                                                                                 0x100d7f067    
36 QWidgetTextControl::setDocument(QTextDocument *)                                                                                                                                                             (x86_64) /usr/local/opt/qt/lib/QtWidgets.framework/Versions/5/QtWidgets                                                                                 0x100d81118    
37 QTextEdit::setDocument(QTextDocument *)                                                                                                                                                                      (x86_64) /usr/local/opt/qt/lib/QtWidgets.framework/Versions/5/QtWidgets                                                                                 0x100d5e01b    
38 ItemText::ItemText(QString const&, QString const&, int, int, int, QWidget *)                                                                                                                                 itemtext.cpp                                                                                                                                       166  0x10af72f1b    
39 ItemText::ItemText(QString const&, QString const&, int, int, int, QWidget *)                                                                                                                                 itemtext.cpp                                                                                                                                       116  0x10af734eb    
40 ItemTextLoader::create(QMap<QString, QVariant> const&, QWidget *, bool) const                                                                                                                                itemtext.cpp                                                                                                                                       310  0x10af74cb3    
41 ItemFactory::createItem(std::shared_ptr<ItemLoaderInterface> const&, QMap<QString, QVariant> const&, QWidget *, bool, bool, bool)                                                                            itemfactory.cpp                                                                                                                                    284  0x1001afacc    
42 ItemFactory::createItem(QMap<QString, QVariant> const&, QWidget *, bool, bool, bool)                                                                                                                         itemfactory.cpp                                                                                                                                    314  0x1001b03e5    
43 ItemDelegate::updateCache(QModelIndex const&, QMap<QString, QVariant> const&)                                                                                                                                itemdelegate.cpp                                                                                                                                   353  0x1001a3650    
44 ItemDelegate::cache(QModelIndex const&)                                                                                                                                                                      itemdelegate.cpp                                                                                                                                   147  0x1001a2ec4    
45 ItemDelegate::setItemWidgetCurrent(QModelIndex const&, bool)                                                                                                                                                 itemdelegate.cpp                                                                                                                                   262  0x1001a444f    
46 ClipboardBrowser::updateCurrent()                                                                                                                                                                            clipboardbrowser.cpp                                                                                                                               1765 0x10008f15d    
47 QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (ClipboardBrowser:: *)()>::call(void (ClipboardBrowser:: *)(), ClipboardBrowser *, void * *)                                  qobjectdefs_impl.h                                                                                                                                 152  0x1000a36fe    
48 void QtPrivate::FunctionPointer<void (ClipboardBrowser:: *)()>::call<QtPrivate::List<>, void>(void (ClipboardBrowser:: *)(), ClipboardBrowser *, void * *)                                                   qobjectdefs_impl.h                                                                                                                                 185  0x1000a3673    
49 QtPrivate::QSlotObject<void (ClipboardBrowser:: *)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase *, QObject *, void * *, bool *)                                                         qobjectdefs_impl.h                                                                                                                                 414  0x1000a35a6    
50 QMetaObject::activate(QObject *, int, int, void * *)                                                                                                                                                         (x86_64) /usr/local/opt/qt/lib/QtCore.framework/Versions/5/QtCore                                                                                       0x1018986f9    
51 QTimer::timerEvent(QTimerEvent *)                                                                                                                                                                            (x86_64) /usr/local/opt/qt/lib/QtCore.framework/Versions/5/QtCore                                                                                       0x1018a0822    
52 QObject::event(QEvent *)                                                                                                                                                                                     (x86_64) /usr/local/opt/qt/lib/QtCore.framework/Versions/5/QtCore                                                                                       0x1018911dc    
53 QApplicationPrivate::notify_helper(QObject *, QEvent *)                                                                                                                                                      (x86_64) /usr/local/opt/qt/lib/QtWidgets.framework/Versions/5/QtWidgets                                                                                 0x100b9a77f    
54 QApplication::notify(QObject *, QEvent *)                                                                                                                                                                    (x86_64) /usr/local/opt/qt/lib/QtWidgets.framework/Versions/5/QtWidgets                                                                                 0x100b9bb9c    
55 ApplicationExceptionHandler<(anonymous namespace)::ClipboardApplication>::notify(QObject *, QEvent *)                                                                                                        applicationexceptionhandler.h                                                                                                                      60   0x1001cee5e    
56 QCoreApplication::notifyInternal2(QObject *, QEvent *)                                                                                                                                                       (x86_64) /usr/local/opt/qt/lib/QtCore.framework/Versions/5/QtCore                                                                                       0x101867ab4    
57 QTimerInfoList::activateTimers()                                                                                                                                                                             (x86_64) /usr/local/opt/qt/lib/QtCore.framework/Versions/5/QtCore                                                                                       0x1018c0c4f    
58 ___lldb_unnamed_symbol609$$libqcocoa.dylib                                                                                                                                                                   (x86_64) /usr/local/Cellar/qt/5.12.3/plugins/platforms/libqcocoa.dylib                                                                                  0x105b992b2    
59 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__                                                                                                                                                   (x86_64) /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation                                                                  0x7fff49292dbb 
60 __CFRunLoopDoSource0                                                                                                                                                                                         (x86_64) /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation                                                                  0x7fff49292d61 
61 __CFRunLoopDoSources0                                                                                                                                                                                        (x86_64) /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation                                                                  0x7fff49276c6b 
62 __CFRunLoopRun                                                                                                                                                                                               (x86_64) /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation                                                                  0x7fff49276233 
63 CFRunLoopRunSpecific                                                                                                                                                                                         (x86_64) /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation                                                                  0x7fff49275b35 
64 RunCurrentEventLoopInMode                                                                                                                                                                                    (x86_64) /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox                                     0x7fff4855496b 
65 ReceiveNextEventCommon                                                                                                                                                                                       (x86_64) /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox                                     0x7fff485546a5 
66 _BlockUntilNextEventMatchingListInModeWithFilter                                                                                                                                                             (x86_64) /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox                                     0x7fff48554436 
67 _DPSNextEvent                                                                                                                                                                                                (x86_64) /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit                                                                                  0x7fff468ee987 
68 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]                                                                                                                              (x86_64) /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit                                                                                  0x7fff468ed71f 
69 -[NSApplication run]                                                                                                                                                                                         (x86_64) /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit                                                                                  0x7fff468e783c 
70 ___lldb_unnamed_symbol620$$libqcocoa.dylib                                                                                                                                                                   (x86_64) /usr/local/Cellar/qt/5.12.3/plugins/platforms/libqcocoa.dylib                                                                                  0x105b9a226    
71 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>)                                                                                                                                                      (x86_64) /usr/local/opt/qt/lib/QtCore.framework/Versions/5/QtCore                                                                                       0x10186316f    
72 QCoreApplication::exec()                                                                                                                                                                                     (x86_64) /usr/local/opt/qt/lib/QtCore.framework/Versions/5/QtCore                                                                                       0x101868122    
73 App::exec()                                                                                                                                                                                                  app.cpp                                                                                                                                            194  0x100031315    
74 (anonymous namespace)::startServer(int, char * *, QString)                                                                                                                                                   main.cpp                                                                                                                                           133  0x1001c6782    
75 (anonymous namespace)::startApplication(int, char * *)                                                                                                                                                       main.cpp                                                                                                                                           238  0x1001c5913    
76 main                                                                                                                                                                                                         main.cpp                                                                                                                                           250  0x1001c52f2    
77 start                                                                                                                                                                                                        (x86_64) /usr/lib/system/libdyld.dylib                                                                                                                  0x7fff7523a3d5 
</pre>
</details>

See also: https://stackoverflow.com/questions/41234444/prevent-prompt-to-download-font-referenced-in-webview-in-macos-application
