### ISSUE TITLE
Difference between Release 3.8.0 and 3.8.0-osx

### ISSUE THREAD

**Issue by Moulick** [hluk/CopyQ#1154]
**Describe the bug**
On the releases page there are two dmg's available for the 3.8.0 version.

Is the Release 3.8.0 different then 3.8.0-osx ?

**Comment by Moulick** [comment]
@hluk Also `brew cask install copyq` installs the v3.8.0  release, not the v3.8.0-osx

**Comment by hmijail** [comment]
FWIW, I just installed CopyQ with homebrew and the "about" window says v3.8.0-osx

**Comment by Moulick** [comment]
@hmijail true, same here. the version installed says v3.8.0-osx but the downloading url used by brew says v3.8.0, both the dmg's must be same then

**Comment by hluk** [comment]
See the tags in git. They are basically the same, except v3.8.0 can fail to build on macOS - I had to do a hot fix for the build system (e8aca166590bf4ef6a8401413a7930ee21bc8f56) after releasing the tag v3.8.0.

I should have more patience with the CI builds next time.

**Comment by Moulick** [comment]
Ah okay, No problem.
