### ISSUE TITLE
Latest version doesn't support retina display on macOS

### ISSUE THREAD

**Issue by RoadToDream** [hluk/CopyQ#1155]
**Describe the bug**
Latest version doesn't support retina display on macOS. 

**Screenshots**
Version 3.8
<img width="612" alt="CopyQ xRCsnW" src="https://user-images.githubusercontent.com/8088354/58600633-fb677c00-82b7-11e9-98ea-c3a30d11d887.png">
Version 3.7.2
<img width="612" alt="image" src="https://user-images.githubusercontent.com/8088354/58600716-484b5280-82b8-11e9-8721-9c06f0e0dd5f.png">

**Version, OS and Environment**
CopyQ Clipboard Manager v3.8.0-osx
Qt: 5.12.2
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: macOS Mojave (10.14)

**Additional context**

**Comment by hluk** [comment]
That's odd, why is even the window title pixelated?

Can you provide `copyq version` for the 3.7.2 version? Maybe it's because it uses different Qt version.

**Comment by RoadToDream** [comment]
Hi! Here is the output,
CopyQ Clipboard Manager v3.7.2
Qt: 5.12.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: macOS 10.14

Maybe Info.plist is not correctly generated?

**Comment by hluk** [comment]
> Maybe Info.plist is not correctly generated?

Can you check the differences? Maybe some libraries, plugins or other files are missing.

Note: Between versions 3.7.3 ([build log](https://api.travis-ci.org/v3/job/473844977/log.txt)) and 3.8.0 ([build log](https://api.travis-ci.org/v3/job/518319734/log.txt)) the build system was changed (from qmake to CMake+CPack).

**Comment by RoadToDream** [comment]
Seems like that there isn't anything missed, maybe qt's compatibility issues? 
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/8088354/58775273-41457c80-85f7-11e9-864a-4713f0d21f79.png">

**Comment by hluk** [comment]
Thanks for the screenshot.

It's probably unrelated, but the new libs in v3.8.0 aren't really required by CopyQ - not sure why they are included in the package.

Can you check if there are any problems in log (F12 shortcut from the main window)?

You can also try forcing the scaling with following commands.

```bash
QT_SCALE_FACTOR=1 QT_SCREEN_SCALE_FACTORS=2 copyq
# or
QT_SCALE_FACTOR=2 copyq
```

**Comment by RoadToDream** [comment]
It doesn't fix this issue, just double sized the window.
![image](https://user-images.githubusercontent.com/8088354/58869443-cc566d80-86f0-11e9-91db-1406105c4dd5.png)
That's really a weird problem, does it only occur on my computer? Seems like it's my system's fault.

**Comment by hluk** [comment]
Unfortunately, I cannot test it on macOS. It could be issue in the new Qt version but I fail to find [a similar bug](https://bugreports.qt.io/issues/?jql=text%20~%20%22retina%22%20AND%20affectedVersion%20%3E%3D%205.12).

**Comment by RoadToDream** [comment]
Thanks a a lot for your patience! I'll go back to version 3.7. Maybe a fix in QT will repair this issue.

**Comment by hluk** [comment]
I've fixed it by adding following code to `Info.plist` in the bundle.

```
       <key>NSPrincipalClass</key>
       <string>NSApplication</string>
       <key>NSHighResolutionCapable</key>
       <string>True</string>
```

Still not sure why this does not work out-of-the-box.

**Comment by hluk** [comment]
CopyQ v3.9.0, with the fix for retina displays, is available on github and via Homebrew.

**Comment by RoadToDream** [comment]
So still a plist issue, but this item is really weird, never seen it before.
Great hack!
