### ISSUE TITLE
Add an option to merge items

### ISSUE THREAD

**Issue by aurora-of-earth** [hluk/CopyQ#1158]
Currently, if I wanna merge a few items in a list, I have to select and then 'Edit' them.
But this option doesn't remove all of the selected items and create a unified one.

**Comment by hluk** [comment]
Following command adds "Merge" into menu/toolbar and shortcut to do the merge + deletion of selected items ([here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)).

```ini
[Command]
Command="
    copyq:
    add(input())"
Icon=\xf022
InMenu=true
Input=text/plain
Name=Merge and Delete
Remove=true
Shortcut=ctrl+shift+m
```

**Comment by aurora-of-earth** [comment]
@hluk Nice, but add it as a default option to CopyQ.

**Comment by hluk** [comment]
> @hluk Nice, but add it as a default option to CopyQ, as it's really useful.

What do you mean by default option exactly?

**Comment by aurora-of-earth** [comment]
> What do you mean by default option exactly?

Simply being available by default, just like the other options in the copyq menu.

**Comment by Clemens-Ratte-Polle** [comment]
Very useful for Copy&Paste :D

But merging Items can not be undone per CTRL+Z. :(
Perhaps Undo more global? :)

**Comment by hluk** [comment]
> But merging Items can not be undone per CTRL+Z. :(
> Perhaps Undo more global? :)

CopyQ doesn't support Undo out of the box. You would need to create a command for that.

**Comment by Kmfernan5** [comment]
Is it possible to merge without deleting and add this as a standard option for all who install CopyQ

**Comment by sudoshindo** [comment]
Hi, please seriously consider making this a built-in, out-of-the-box command that doesn't need to be manually added.

Merging multiple copied items is extremely useful and convenient and it sounds like a common enough use-case.
