### ISSUE TITLE
can't start copyq: QLocalServer::listen: Name error

### ISSUE THREAD

**Issue by goldylucks** [hluk/CopyQ#1163]
**Describe the bug**
running `$ copyq` from terminal doesn't load the app and logs the following:

```bash
$ copyq
ERROR: Failed to create server "": QLocalServer::listen: Name error
Warning: CopyQ server is already running.
```

**To Reproduce**
I don't know how to reproduce on another machine

**Expected behavior**
Open copyq when typing `$ copyq` in terminal

**Screenshots**
N/A

**Version, OS and Environment**
```bash
$ copyq version
CopyQ Clipboard Manager v3.8.0
Qt: 5.9.5
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Ubuntu 18.04.2 LTS
```

I'm not sure when this started happening.

some more outputs:

```bash
$ copyq show
ERROR: Cannot connect to server! Start CopyQ server first.

$ copyq tab 
ERROR: Cannot connect to server! Start CopyQ server first

$ copyq &  
[1] 11424
ERROR: Failed to create shared memory: QSharedMemory::create: already exists
Warning: CopyQ server is already running.
[1]  + 11424 done       copyq

$ sudo copyq
ERROR: Failed to create server "": QLocalServer::listen: Name error
Warning: CopyQ server is already running.
```

Any ideas?

I tried also `$ sudo apt purge copyq` and reinstalling it `$ sudo apt install copyq` with no success

**Comment by hluk** [comment]
What's the output of following commands?

`copyq info`

`ls -ld ~/.config/copyq`

`ls -l ~/.config/copyq/.copyq*`

**Comment by goldylucks** [comment]
thank you for the quick response @hluk !

```bash
$ copyq info
config: /home/goldy/.config/copyq/copyq.conf
desktop: /usr/share/applications/com.github.hluk.copyq.desktop
exe: /usr/bin/copyq
has-global-shortcuts: 1
has-mouse-selection: 1
icons: /usr/share/icons/hicolor/scalable/apps/copyq
log: /home/goldy/.local/share/copyq/copyq/copyq.log
platform: Linux/X11
plugins: /usr/lib/copyq/plugins
themes: /usr/share/copyq/themes
themes(custom): 
translations: /usr/share/copyq/translations
translations(custom): 

$ ls -ld ~/.config/copyq
drwxrwxr-x 2 goldy goldy 4096 Jun 13 11:02 /home/goldy/.config/copyq

$ ls -l ~/.config/copyq/.copyq*
srwxrwxr-x 1 goldy goldy 0 Jun 13 11:02 /home/goldy/.config/copyq/.copyq_s
```

**Comment by hluk** [comment]
How about following?

`copyq exit`

`killall copyq && sleep 5; rm ~/.config/copyq/.copyq_s`

`COPYQ_LOG_LEVEL=TRACE copyq`

**Comment by goldylucks** [comment]
That did the trick, so now I can open `copyq` from terminal and from unity. However there are some bugs which I'm not sure how to convey in text, so I made a quick loom screencast: https://www.loom.com/share/c375b24813b74f28a4f31e8253f5b9d7

Here are the bullet points:

1. the theme has inconsistent colors
1. keyboard shortcuts don't work, so I'm using the [workaround you posted here](https://github.com/hluk/CopyQ/issues/295#issuecomment-71448527): 
> Actually, as a workaround, you should be able to map any shortcut directly in Ubuntu preferences to run copyq toggle command to show/hide the application window.
1. if preferences window is open, pressing the toggle hotkey will open copyq clipboard in a "frozen" state, and clicking on entires doesn't do anything, neither does navigating with the arrow keys
1. pressing the toggle hotkey triggers a ubuntu notification "copyq is ready"
1. sometimes when copyq clipboard is open, pressing toggle hotkey doesn't close it, but "kinda" reopens it.

Like I said in the video, let me know if you prefer me to break this down to separate issues. I'm not sure what affects what and if any of it is related, I'm mostly a web dev.

Thanks again for your time and help, appreciate it a great deal.

lastly, here's the [gist with the output](https://gist.github.com/goldylucks/f439b6cd65c34dc3f875568dba04f16c) you requested

**Comment by hluk** [comment]
>  1. the theme has inconsistent colors

This is caused by HTML items. There is no way to force background and foreground colors for HTML text you copy. You could [disable storing HTML](https://copyq.readthedocs.io/en/latest/faq.html#how-to-store-only-plain-text) if that works for you.

>  2. keyboard shortcuts don't work, so I'm using the [workaround you posted here](https://github.com/hluk/CopyQ/issues/295#issuecomment-71448527):

I think you've set a shortcut that is available only when the main window is open.

There are some shortcuts that have an arrow icon right to the label. E.g. "Show/hide main window" is probably most useful:

> ![image](https://user-images.githubusercontent.com/38054/59547370-269bcd80-8f3e-11e9-9e4d-41d9a4eec420.png)

I'll try to separate the shortcuts into two lists.

---

I haven't met the other problems but you mentioned you use Unity. I thought Unity got replaced with Gnome a long time ago.

Some of the issues could be caused by the window manager but probably not the multiple instances issue.

It doesn't look like there is anything suspicious in your log output.

**Comment by hluk** [comment]
Maybe this layout works better:

![image](https://user-images.githubusercontent.com/38054/59547740-ee978900-8f43-11e9-9b43-b7a2de17c363.png)

**Comment by goldylucks** [comment]
I think a separation would make it easier to digest.
 
"Application" would mean commands available only when main window (the clipborad) is open?

about unity, that was a mistake, I am using gnome shell.

I'm using now the shortcut you mentioned and it works great.

about the html - it would be nice to see it in consistent colors, tho I don't know the limitations of ubuntu and this project, so maybe it's not possible. I do need to store html so I will keep it open.

So Im going to close this now. thanks again, keep up the good work.

**Comment by hluk** [comment]
> "Application" would mean commands available only when main window (the clipborad) is open?

Yes. I'll add a simple description in Application and Global tabs.

> about the html - it would be nice to see it in consistent colors, tho I don't know the limitations of ubuntu and this project, so maybe it's not possible. I do need to store html so I will keep it open.

This is a problem everywhere. If the copied HTML contains background or foreground colors (depends on the source app), it cannot be used everywhere and it's very difficult to override the colors.
