### ISSUE TITLE
CopyQ : donate only once?

### ISSUE THREAD

**Issue by Clemens-Ratte-Polle** [hluk/CopyQ#1165]
hi
how could i donate only once?
There are only options to pay regularly and automatically without manul control every time?
https://en.liberapay.com/CopyQ/donate
thx

**Comment by hluk** [comment]
Not sure if it helps but here is the old (still active) donation link: https://www.bountysource.com/teams/copyq

**Comment by nmat** [comment]
I think that if you do create a account at liberapay you can do a 1 time donation when you go in to donate. There are several options in there.
