### ISSUE TITLE
Seeking assistance with Copy Q

### ISSUE THREAD

**Issue by Ldxrunner** [hluk/CopyQ#1167]
I have Windows 10 64-bit with all the updates. When I right click and then click OPEN nothing happens, no action. What went wrong ?  How can I correct this ? .Thank you.

**Comment by hluk** [comment]
Not sure what do you mean. Where do you click OPEN?

If you start the CopyQ it should be available from tray.

**Comment by Ldxrunner** [comment]
I have the icon on desktop, or display screen, along with other icons.  Are you referring to the tray in lower right hand corner on the task bar ? Thank you

**Comment by hluk** [comment]
> Are you referring to the tray in lower right hand corner on the task bar ?

Yes.

![image](https://user-images.githubusercontent.com/38054/59960340-71ca5900-94c7-11e9-8f9d-f8beee83cb9a.png)

**Comment by Ldxrunner** [comment]
WOW  It is there. It was not there when I checked. Is this taking the place of  what was installed by Microsoft? Does this program work with File Zilla server? I am now onto to something.

**Comment by hluk** [comment]
> Is this taking the place of what was installed by Microsoft? Does this program work with File Zilla server?

Not sure what you mean. Can you be more specific?
