### ISSUE TITLE
Unknown characters when running CopyQ

### ISSUE THREAD

**Issue by online** [hluk/CopyQ#1169]
**Describe the bug**
When I run CopyQ, I see some unknown characters in Tab tree. If I delete this tab, after restarting CopyQ it reappears 😐

**To Reproduce**
I do not know how to reproduce it.

**Expected behavior**
The tab should not appear after deletion.

**Screenshots**
![image](https://user-images.githubusercontent.com/722881/60395288-0cffa600-9b3a-11e9-9fd8-1c084355f951.png)

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - CopyQ v3.9.0
 - OS Windows 10, v1903

**Log file**
[copyq.log](https://github.com/hluk/CopyQ/files/3342767/copyq.log)

**Comment by hluk** [comment]
An error in log says:

```
Failed to move items from "D:/Dropbox/Soft/Portable/CopyQ/config/copyq/copyq_tab_0KXQvtGA0L7RiNC+0L8vUlUv0JTQtdC0Lu+-vS-vv70u.dat" 
```

Maybe there is permission problem with the file or some other application keeps the file open.

Probably better to do [regular backups](https://github.com/hluk/copyq-commands/tree/master/Scripts#backup-on-exit) instead of sharing the configuration folder with Dropbox.

**Comment by online** [comment]
@hluk, thanks for your reply. Where do I need to put this `backup-on-exit.ini` file?

**Comment by hluk** [comment]
> Where do I need to put this `backup-on-exit.ini` file?

Please read the description in [README](https://github.com/hluk/copyq-commands/blob/master/README.md) file in the repo.

**Comment by online** [comment]
@hluk, I can’t get rid of it ([screenshot](https://user-images.githubusercontent.com/722881/60395288-0cffa600-9b3a-11e9-9fd8-1c084355f951.png)).

**Comment by hluk** [comment]
Can you just delete the file mentioned in the error [1]? (You'll need to quit CopyQ first.)

[1] `D:/Dropbox/Soft/Portable/CopyQ/config/copyq/copyq_tab_0KXQvtGA0L7RiNC+0L8vUlUv0JTQtdC0Lu+-vS-vv70u.dat`

**Comment by online** [comment]
@hluk, the fact is that I can not find this file.

**Comment by hluk** [comment]
OK, I might have a fix for this. You can download the fixed binaries for Windows here: https://ci.appveyor.com/project/hluk/copyq/build/job/0x3go6dxa80cgh99/artifacts

**Comment by online** [comment]
@hluk, sorry, but I don't see the download button.
![image](https://user-images.githubusercontent.com/722881/60643441-bc3ec480-9e3b-11e9-9a21-ceee1c0e22d4.png)

**Comment by hluk** [comment]
Sorry, bad link (not sure why it changed): https://ci.appveyor.com/project/hluk/copyq/builds/25727974/job/0x3go6dxa80cgh99/artifacts

**Comment by online** [comment]
@hluk, thanks. It helped me 👍
