### ISSUE TITLE
copyq starts with boot, but no indicator in tray

### ISSUE THREAD

**Issue by mjt33** [hluk/CopyQ#1174]
**Describe the bug**
Copyq is set to start with Xubuntu 19.04 and it does, but the indicator icon does not appear in the panel tray. When I open the task manager and kill copyq and then restart it from the menu entry, the indicator appears.

**To Reproduce**
1. In copyq's settings, click on "Autostart."
2. Log out and back in.

**Expected behavior**
The indicator icon will appear in the tray along with copyq's start at boot.

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Application Version - 3.9.0
 - OS - Xubuntu 19.04
 - Desktop environment - xfce4, compiz

**Comment by hluk** [comment]
Any errors/warnings in the log (F12 shortcut)?

**Comment by mjt33** [comment]
Only this: 
Warning [2019-07-12 20:53:46.820] <monitorClipboard-19218>: Clipboard data expired, refusing to access old data

**Comment by mjt33** [comment]
BTW, I've tried a number of ways to configure the startup entry because clearly something is going wrong when the computer starts/reboots, but nothing seems to work.

**Comment by hluk** [comment]
I can only reproduce this when copyq icon is created in a different panel (like `latte-dock`), kill the panel and launch `xfce4-panel`. The icon won't appear again.

Looks like some problem with X11 and Qt (after destroying one panel, [QSystemTrayIcon::isSystemTrayAvailable()](https://doc.qt.io/qt-5/qsystemtrayicon.html#isSystemTrayAvailable) returns always `false`).

You can try adding [short delay before starting copyq](https://github.com/hluk/CopyQ/issues/431#issuecomment-267915807).

**Comment by mjt33** [comment]
That did the trick! Thanks!
