### ISSUE TITLE
Multiple commands in tray menu

### ISSUE THREAD

**Issue by SmartFinn** [hluk/CopyQ#1175]
**Describe the bug**
Every time when I save the CopyQ configuration, the list of commands in the tray menu is duplicated.

**To Reproduce**
1. Open <kbd>Preferences...</kbd>
2. Click on <kbd>OK</kbd>
3. Open the tray menu
4. See duplicate commands

**Expected behavior**
One copy of each command.

**Screenshots**
![Screenshot from 2019-07-15 20-14-50](https://user-images.githubusercontent.com/819186/61235139-6ae8dc00-a73d-11e9-8398-f433e0d16de0.png)

**Version, OS and Environment**
```
CopyQ Clipboard Manager v3.9.0
Qt: 5.12.1
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Fedora 30 (Workstation Edition)
```

**Comment by hluk** [comment]
Can you check if there are duplicate commands in the Command dialog? (Open main window and press F6 shortcut.) If so remove them.

This is probably caused by some strange issue after pressing OK/Apply in Preferences dialog. I'll try to fix that (I haven't been able to reproduce the issue though).

**Comment by SmartFinn** [comment]
There are no duplicate commands in the CopyQ Commands window:

![image](https://user-images.githubusercontent.com/819186/61274796-2e58c700-a7b5-11e9-86af-70e2e6018e81.png)

I even tried to disable all commands except `Edit clipboard` and `Show the tray menu`, but that didn't help.

**Comment by hluk** [comment]
Oh, then it's quite possible that this is caused by the Qt tray menu integration layer for Gnome.

Can you run `copyq menu` to see if it's the same? (This menu should be Qt native and contain also search bar at top.) If there are duplicate items then it's probably caused by some bad code in CopyQ.

**Comment by SmartFinn** [comment]
Yes, the native Qt menu shows the same:

![copyq_scr](https://user-images.githubusercontent.com/819186/61276638-171bd880-a7b9-11e9-98ef-335b8a2f53f6.png)

**Comment by hluk** [comment]
Oh, found the problem and getting it fixes.

**Comment by orschiro** [comment]
Thanks for the fix! Which release will this enter?

**Comment by hluk** [comment]
> Thanks for the fix! Which release will this enter?

Next release (whatever is after 3.9.0).

**Comment by orschiro** [comment]
Thanks :)

-
Regards

**Comment by orschiro** [comment]
New automation Expert Talks, free e-book, live Covid-19 impact tracking template in Google Sheets and product updates.

logo-white-background (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbjZY32W5Z9Hx46jRFnWW6byjDy5TT8tvW5bb2875rBHWQf1HVPN203 )

Staying connected while staying apart

Dear users, partners and friends,

The Sheetgo community extends across the globe and we know that many of you are facing unexpected challenges and immense upheaval right now.

On behalf of our (remote) team, I wanted to let you know that we're here to support you and we're taking extra measures to help you keep your business running as smoothly as possible. You've been telling us that you need automation solutions more than ever.

Here's what we're doing:

SUPPORT

- Expert Talks every week to help you automate and manage data remotely. Register (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbjZY32W5Z9Hx46jRFnWW6byjDy5TT8tvW5bb2875rBHWQf1HVPN213 ) for our next talk: Automation for SMEs. April 7th.
- New business automation specialist. We have expanded our Customer Success team to give you extra support across US and European time zones.
- Server power. Sheetgo runs on Google and Amazon servers — the most secure and reliable cloud infrastructures in the world — and we will now be boosting that with Microsoft servers to deliver the best performance.
- Resources. We've created a template (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbjZY32W5Z9Hx46jRFnWW6byjDy5TT8tvW5bb2875rBHWQf1HVPN223 ) to help you analyze the regional impact of coronavius and we're sharing a new e-book (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbjZY32W5Z9Hx46jRFnWW6byjDy5TT8tvW5bb2875rBHWQf1HVPN233 ) to help you prepare your data for automated processes.

LEARNING

E-book

Collaborating and sharing data when working remotely requires a bit of forward planning. Learn how to automate and scale your business with the Sheetgo process design method.

Get the e-book (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbjZY32W5Z9Hx46jRFnWW6byjDy5TT8tvW5bb2875rBHWQf1HVPN243 )

Tips for remote teams

Has your team been thrown into disarray by working from home? Read our tips on how to stay productive and connected, no matter where you're located.

Read more (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbjZY32W5Z9Hx46jRFnWW6byjDy5TT8tvW5bb2875rBHWQf1HVPN253 )

TEMPLATE

Covid-19 impact tracking

We have developed a template that pulls live data from the COVID-19 database at John Hopkins University, allowing you to measure the impact of the coronavirus outbreak on your KPIs, region by region.

Get the template (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbjZY32W5Z9Hx46jRFnWW6byjDy5TT8tvW5bb2875rBHWQf1HVPN263 )

PRODUCT

Duplicate workflow

If you develop a solution and want to replicate it for another department or client, you can now copy the entire workflow — every connection and spreadsheet — without having to build the system from scratch. In the Sheetgo web app, find the option in the menu bar (⋮).

Open Sheetgo (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbjZY32W5Z9Hx46jRFnWW6byjDy5TT8tvW5bb2875rBHWQf1HVPN273 )

I'd love to hear if there are any other ways we can help and support you right now. If you need training for your staff or project consultation get in touch with our experts (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbjZY32W5Z9Hx46jRFnWW6byjDy5TT8tvW5bb2875rBHWQf1HVPN283 ) .

Please feel free to reply to this email with any suggestions, requests or comments.

As always, thank you. And stay safe.

Yours,

LinkedIn (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbjZY32W5Z9Hx46jRFnWW6byjDy5TT8tvW5bb2875rBHWQf1HVPN293 )

YouTube (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbjZY32W5Z9Hx46jRFnWW6byjDy5TT8tvW5bb2875rBHWQf1HVPN2b3 )

Twitter (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbjZY32W5Z9Hx46jRFnWW6byjDy5TT8tvW5bb2875rBHWQf1HVPN2c3 )

Need help using Sheetgo? Contact us here. (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbjZY32W5Z9Hx46jRFnWW6byjDy5TT8tvW5bb2875rBHWQf1HVPN2d3 )

Sheetgo, 601 Van Ness Ave, Ste E, San Francisco, California 94102, USA, +1 (612) 470-5696

Unsubscribe (https://hs-5756448.s.hubspotemail.net/hs/manage-preferences/unsubscribe-all?d=VnBg006k4PD4W2p76LK3-1rCSW3z7ZJq47WCpwW3LGyn047RZzrW3H4ss61V20lBW3M1rw63KbsvFW3R0gmz1Ssgv1W47szjy45RlhdW3P28X24hCPvhW43T2NR5mwb30W17f7hv5BjmrdW7jgvY86WXK4DW59B4HC5wrgnKV28XY47s6tqqMGKd_P20N7yW2C67Gq4Bv6KdW4lqZcf2YxnKq4pVxt1&v=3&_hsenc=p2ANqtz-_lx_WbtiKDHw0gIavIj1DnQWIHoMaRJMoMx0GttWzfjvd9qMRISa9DeKJ3GW8Y741-9bKjjnp-KHXkxtNedFFCp5JJOxsN7Nr0oUfghe1Jb8Mxqg6TdoPWFLuoGY09yD4LxtPfHoL_75nr2G4HMlPkopUa5g&_hsmi=85605929 )

Manage preferences (https://hs-5756448.s.hubspotemail.net/hs/manage-preferences/unsubscribe?d=VnBg006k4PD4W2p76LK3-1rCSW3z7ZJq47WCpwW3LGyn047RZzrW3H4ss61V20lBW3M1rw63KbsvFW3R0gmz1Ssgv1W47szjy45RlhdW3P28X24hCPvhW43T2NR5mwb30W17f7hv5BjmrdW7jgvY86WXK4DW59B4HC5wrgnKV28XY47s6tqqMGKd_P20N7yW2C67Gq4Bv6KdW4lqZcf2YxnKq4pVxt1&v=3&_hsenc=p2ANqtz-_lx_WbtiKDHw0gIavIj1DnQWIHoMaRJMoMx0GttWzfjvd9qMRISa9DeKJ3GW8Y741-9bKjjnp-KHXkxtNedFFCp5JJOxsN7Nr0oUfghe1Jb8Mxqg6TdoPWFLuoGY09yD4LxtPfHoL_75nr2G4HMlPkopUa5g&_hsmi=85605929 )

**Comment by orschiro** [comment]
Product updates, connect Google classroom, remote work & Covid-19 solutions. Smart spreadsheet experts needed!

logo-white-background (https://i7.t.hubspotemail.net/e2t/sc2/MmZ-8yk48tzW6Fr3QJ4SHj0CW8sRkjZ6-hNCgVpWfTL8tdj5WdBzP8M04 )

What's new in Sheetgo?

Global lockdowns and remote working mean many of you have reached out to us looking for new automation solutions — read on for ideas on how to manage your data and collaborate more smoothly in a changing environment. We've made some product updates based on your feedback and we've got a big annoucement too!

PRODUCT UPDATES

Sliding sidebar

You told us that you needed a way to collapse the sidebar, so we have adjusted the spreadsheet editor. Just click on the blue arrow to switch between the full spreadsheet view and the workflow editor panel on the right.

Workflow menu

The floating workflow menu lets you schedule automatic updates, add a new connection and run or share your workflow while you're working in your spreadsheets. Click and drag to move the menu bar around your screen.

Open Sheetgo (https://i7.t.hubspotemail.net/e2t/sc2/MmZ-8yk48tzW6Fr3QJ4SHj0CW8sRkjZ6-hNCgVpWfTL8tdj5WdBzP8N04 )

COMPANY NEWS

New partnership

Sheetgo is now an official Dropbox technology partner! We're working on some exciting projects to enable even more spreadsheet users to connect and automate. Watch this space!

CRISIS & REMOTE SOLUTIONS

Manage urgent deliveries

Covid-19 meant HMG Healthcare needed a way to manage orders and deliveries of personal protective equipment to care staff at their nursing facilities — as quickly as possible. They used Sheetgo to create a dynamic PPE inventory system.

Read more (https://i7.t.hubspotemail.net/e2t/sc2/MmZ-8yk48tzW6Fr3QJ4SHj0CW8sRkjZ6-hNCgVpWfTL8tdj5WdBzP8P04 )

Templates for remote

Are more of your business departments and processes moving online? From project management to cash flow monitoring, check out our range of Google Sheets-based templates to help remote teams collaborate more productively.

Find a template (https://i7.t.hubspotemail.net/e2t/sc2/MmZ-8yk48tzW6Fr3QJ4SHj0CW8sRkjZ6-hNCgVpWfTL8tdj5WdBzP8Q04 )

COMMUNITY PARTNERS

Spreadsheet masters: we want to meet you!

Looking to leverage your spreadsheet skills to generate an additional source of income? If you're interested in implementing no-code automation solutions for local businesses in your network, please get in touch with us.

I'm interested (https://i7.t.hubspotemail.net/e2t/sc2/MmZ-8yk48tzW6Fr3QJ4SHj0CW8sRkjZ6-hNCgVpWfTL8tdj5WdBzP8R04 )

SHEETGO FOR EDUCATION

Connect Google Classroom data

Teachers told us they were looking for a way to register student attendance via Google Classroom. Here's how to create your own automated system, using Google Sheets, Sheetgo templates and Forms.

Learn how (https://i7.t.hubspotemail.net/e2t/sc2/MmZ-8yk48tzW6Fr3QJ4SHj0CW8sRkjZ6-hNCgVpWfTL8tdj5WdBzP8S04 )

LinkedIn (https://i7.t.hubspotemail.net/e2t/sc2/MmZ-8yk48tzW6Fr3QJ4SHj0CW8sRkjZ6-hNCgVpWfTL8tdj5WdBzP8T04 )

YouTube (https://i7.t.hubspotemail.net/e2t/sc2/MmZ-8yk48tzW6Fr3QJ4SHj0CW8sRkjZ6-hNCgVpWfTL8tdj5WdBzP8V04 )

Twitter (https://i7.t.hubspotemail.net/e2t/sc2/MmZ-8yk48tzW6Fr3QJ4SHj0CW8sRkjZ6-hNCgVpWfTL8tdj5WdBzP8W04 )

Got comments or feedback? Just reply to this email!

Need help using Sheetgo? Contact our support team (https://i7.t.hubspotemail.net/e2t/sc2/MmZ-8yk48tzW6Fr3QJ4SHj0CW8sRkjZ6-hNCgVpWfTL8tdj5WdBzP8X04 ) .

Sheetgo, 601 Van Ness Ave, Ste E, San Francisco, California 94102, USA, +1 (612) 470-5696

Unsubscribe (https://hs-5756448.s.hubspotemail.net/hs/manage-preferences/unsubscribe-all?d=VnzSxn6k4PD4W2p76LK3-1rCSW3z7ZJq47WCpwW3LGyn047RZzrW3H4ss61V20lBW3M1rw63KbsvFW3R0gmz1Ssgv1W47szjy45RlhdW3P28X24hCPvhW43T2NR5mwb30W15gBJz66SdbkW68JYf65QLk0cW4Y0yCb6H6g79VWB9XJ6TbS6PMXk_7Qbw0_BW5wfdV03-Mw7TW2HZxcJ2X3JLx3j662&v=3&_hsenc=p2ANqtz-8SBmXkN-T-gP6AzuTpHnMlJqbqn_8pXe466WJ_-UULWywmWj2PYevrzr4Rwa_6BMKLIZwNCwsOaqFjaSqn1rGTU7TjxCaz_FSB8OJEpXa3Sz9O5ZleOSKpetIwTJBjm5MWXXzmu_22i4Laoy2MN56CcX3o4w&_hsmi=87730606 )

Manage preferences (https://hs-5756448.s.hubspotemail.net/hs/manage-preferences/unsubscribe?d=VnzSxn6k4PD4W2p76LK3-1rCSW3z7ZJq47WCpwW3LGyn047RZzrW3H4ss61V20lBW3M1rw63KbsvFW3R0gmz1Ssgv1W47szjy45RlhdW3P28X24hCPvhW43T2NR5mwb30W15gBJz66SdbkW68JYf65QLk0cW4Y0yCb6H6g79VWB9XJ6TbS6PMXk_7Qbw0_BW5wfdV03-Mw7TW2HZxcJ2X3JLx3j662&v=3&_hsenc=p2ANqtz-8SBmXkN-T-gP6AzuTpHnMlJqbqn_8pXe466WJ_-UULWywmWj2PYevrzr4Rwa_6BMKLIZwNCwsOaqFjaSqn1rGTU7TjxCaz_FSB8OJEpXa3Sz9O5ZleOSKpetIwTJBjm5MWXXzmu_22i4Laoy2MN56CcX3o4w&_hsmi=87730606 )
