### ISSUE TITLE
Triggering command based on primary selection only

### ISSUE THREAD

**Issue by ngirard** [hluk/CopyQ#1178]
On Linux, I wish an action to be triggered based on the contents of the PRIMARY selection only, not the CLIPBOARD selection.

Is it currently possible ?

**Comment by hluk** [comment]
You can check `application/x-copyq-clipboard-mode` format in automatic commands.

E.g. if you set input format of a command it would be only executed on X11 selection change:

```ini
[Command]
Automatic=true
Command="
    copyq:
    popup(input())"
Input=application/x-copyq-clipboard-mode
Name=Executed only on X11 selection change
```

Otherwise you can check it in command:

```ini
[Command]
Automatic=true
Command="
    copyq:
    if (str(data(mimeClipboardMode)) == 'selection')
      popup('selection changed')
    else
      popup('clipboard changed')"
Name=Show clipboard/selection change
```

**Comment by ngirard** [comment]
Thanks very much for your feedback !

I just created a PR that adds this to the FAQ.
