### ISSUE TITLE
Icon is cramped on Linux Mint 19.1, reducing functionality

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [hluk/CopyQ#1179]
**Describe the bug**
The tray icon is cramped on Linux Mint 19.1 Cinnamon. This problem _might_ owe to Mint. It is not just an aesthetic matter: the cramped nature of the icon means it is too easy for the tray menu to disappear (when one moves the pointer slightly horizontally, when, vertically, the pointer is aligned with the icon,

Fiddling with Cinnamon's icon scaling settings did not help.

**To Reproduce**
1. Add PPA and install.
2. Run.

**Expected behavior**
The icon should not be cramped.

**Screenshots**

![image](https://user-images.githubusercontent.com/47056543/61985866-3f9aa280-b003-11e9-9744-c3ba92446444.png)

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Application Version [e.g. 3.7.2]
CopyQ Clipboard Manager v3.9.0
Qt: 5.9.5
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Linux Mint 19.1
Cinnamon

**Additional context**
Actually, I am running the beta of Mint Cinnamon 19.1 (but these problems are common on Mint - or Linux generally?) so I suspect that is not the problem. However, that the beta ends soon means that if I am to file a bug report against Mint - rather than you - then it would be good were I able to do so _soon_.

**Comment by hluk** [comment]
Sorry, I don't have any way to fix this. Looks like a bug in Qt or the tray/notification area provider.

Note: There is already Qt 5.12 out, maybe it's fixed there.

**Comment by LinuxOnTheDesktop** [comment]
Thanks for the response. The problem does not owe to lack of padding - horizontal vertical space - in the icon, then? (I have not looked in the actual icon file.)

**Comment by hluk** [comment]
The app icon has some margins. From your screenshot it seems that the other icons even overlap CopyQ icon. No idea what i can do about this. Increasing the margin would make the icon smaller in other desktop environments.

You can try setting [different session/icon color](https://copyq.readthedocs.io/en/latest/sessions.html#icon-color), which makes Qt to provide the icon a bit differently.

```bash
COPYQ_SESSION_COLOR=white copyq
```

**Comment by LinuxOnTheDesktop** [comment]
Thanks, but that did not seem to change anything except the colour of the icon.

**Comment by scottkosty** [comment]
@LinuxOnTheDesktop do you still see this? I wonder if it's related to https://github.com/hluk/CopyQ/issues/1054

**Comment by LinuxOnTheDesktop** [comment]
@scottkosty 

I believe I was using a Hi-DPI screen; I should have reported whether or not I was. (I have two Linux laptops, one Hi-DPI, the other not.) I cannot say whether I still see the problem (cannot say easily anyway) since I no longer use CopyQ. (Perhaps I should be willing to test again. On the other hand, I did report the bug a long time ago.)

**Comment by scottkosty** [comment]
@LinuxOnTheDesktop 
 
> I believe I was using a Hi-DPI screen; I should have reported whether or not I was. (I have two Linux laptops, one Hi-DPI, the other not.) I cannot say whether I still see the problem (cannot say easily anyway) since I no longer use CopyQ. (Perhaps I should be willing to test again. On the other hand, I did report the bug a long time ago.)

No need to test, thanks for the reply!
