### ISSUE TITLE
can't use Chinese input  method

### ISSUE THREAD

**Issue by imaojun** [hluk/CopyQ#1181]
**Describe the bug**
Chinese input method cannot be entered when searching for clipboard contents.

**To Reproduce**
1. show manin window under mouse cursor（I bound a shortcut (<kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>q</kbd>)）and used vi mode)
2. used vi mode(type<kbd>/</kbd>) to search history
3. Enter keywords（can not use Chinese input metod)

**Expected behavior**
Can switch to Chinese input method for searching Chinese keywords.

**Screenshots**
![Peek 2019-07-28 14-24](https://user-images.githubusercontent.com/28778042/62003075-78da2c00-b143-11e9-98f4-900f1942cace.gif)

**Version, OS and Environment**
CopyQ Clipboard Manager v3.9.0
Qt: 5.12.4
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Manjaro Linux
 - Desktop environment, window manager (if applicable)
Bspwm

**Comment by hluk** [comment]
Did you set `QT_IM_MODULE` environment variable to `ibus`?

```
QT_IM_MODULE=ibus copyq
```

**Comment by imaojun** [comment]
solved.In addition to the following configuration：
```sh
export XMODIFIERS=@im=fcitx
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
```

Need additional installation of the fcitx-qt module.Add the fcitx-qt5 module method in archlinux:
```sh
$ sudo pacman -S fcitx-qt5
```

Restart the fcitx input tool and copyq after installation. Then try Chinese input. success.

**Comment by hunghw** [comment]
I'm using macOS and I encounter the same problem while search history. How to set the configuration in macOS.
