### ISSUE TITLE
No output in the terminal

### ISSUE THREAD

**Issue by javad94** [hluk/CopyQ#1182]
**Describe the bug**
Thanks for a great application. When I use copyq command line it's gives me no output at all. 

**To Reproduce**
1. open cmd.exe in copq installation folder.
2. type copyq help

**Expected behavior**
showing copyq help result in the terminal.

**Screenshots**
<img width="780" alt="cmd_2019-07-29_06-34-06" src="https://user-images.githubusercontent.com/7765309/62017324-6f94a200-b1cb-11e9-9c4c-9d44d3649d8f.png">

**Version, OS and Environment**
 - Copyq 3.9.0
 - Windows 10 x64 build 1903

**Comment by hluk** [comment]
Ah, yes, this can be annoying, but there doesn't seem to be a simple way to fix this. I really don't want to spend more time on this.

See #499.
