### ISSUE TITLE
Clipboard owner is not updated

### ISSUE THREAD

**Issue by hluk** [hluk/CopyQ#1183]
On macOS (tested on Mojave 10.14.5) native event handlers in the clipboard monitor process are not called when current window changes.

This means that clipboard owner will be incorrect.

**Comment by leooangeloo** [comment]
Hey hluk, I was the one that emailed you about this issue. How would I go about getting this bug fix into my version of copy?

**Comment by hluk** [comment]
@leooangeloo It will be in the next release but not yet sure when I'll be able to do it.

You can add following command to CopyQ to work around this issue.

```ini
[Command]
Command="
    var onClipboardChanged_ = onClipboardChanged
    onClipboardChanged = function() {
        setData(mimeWindowTitle, currentWindowTitle())
    }"
Icon=\xf2d0
IsScript=true
Name=Set Current Window
```

Alternative is to [build it from source](https://github.com/hluk/CopyQ#build-from-source-code).

**Comment by kurtmckee** [comment]
@hluk Should this ticket remain pinned?
