### ISSUE TITLE
Blank Items

### ISSUE THREAD

**Issue by stephenaustin** [hluk/CopyQ#1184]
Just installed CopyQ on LInux Mint on a Samsung NC10. The 'items' tab shows the following. 

![Screenshot_2019-08-05_16-05-56](https://user-images.githubusercontent.com/33739991/62449283-6e034500-b79c-11e9-91f8-e09cdf85204a.png)

Thanks.

**Comment by hluk** [comment]
Looks like CopyQ plugins are not installed (sometimes there is a separate package for that) or are installed in incompatible version.

**Comment by stephenaustin** [comment]
Thanks Lukas. THat's all i need to go on.
