### ISSUE TITLE
ctrl+[ shortcut not registering on system start

### ISSUE THREAD

**Issue by laur89** [hluk/CopyQ#1185]
**Describe the bug**
Having following global shortcut (`ctrl+[`) fails to register on system bootup. Opening & closing preferences/shortcuts tab will make it work:

    [Commands]
    1\Command=copyq: toggle()
    1\GlobalShortcut=ctrl+\xfc

Note in virtualbox guest it's even worse - all ctrl+<key> combos are captured globally, and nothing works until either copyq is closed or the same workaround described above is executed.

**To Reproduce**
1. configure global shortcut as above
1. reboot system
1. toggle said shortcut

**Expected behavior**
copyq window launches; actual behaviour - nothing happens.

**Version, OS and Environment**
    CopyQ Clipboard Manager v3.7.3 (also repros with 3.9.0)
    Qt: 5.11.3
    Compiler: GCC
    Arch: x86_64-little_endian-lp64
    OS: Debian GNU/Linux buster/sid
    window manager: i3 (without a DE)

**Additional context**
Not sure if relevant, but I have both ee & us keymaps configured, reproduces with either being active.

**Comment by fabiodocit123** [comment]
yes nothing happens and nth command doesnt work .. only with "copyq window open"... need change this to background window or something like that to use on macros.. please

**Comment by hluk** [comment]
I briefly tried this on KDE and it seems to work even with keymap switching.

I remember there were some issues with global shortcuts (either on i3 or gnome) when the app window was not yet shown.

If you still have issues with global shortcuts in CopyQ, use whatever your window manager or DE supports. The command with `copyq: toggle()` basically translates to `copyq toggle` command line.

**Comment by laur89** [comment]
Yup, that seems to do the trick.
For others binding this on i3, I recommend binding by keycode instead:
```
# keycode 34 is bracketleft on us keymap
bindcode Control+34 exec --no-startup-id copyq toggle
```

@hluk, should this issue be closed, or would this be revisited at one point? I'd imagine this to be extremely low in priority list.

**Comment by hluk** [comment]
Great. I'm closing this for now, maybe some day I'll have same issue and will be able to fix it. :)

Thanks for sharing the solution.
