### ISSUE TITLE
CopyQ not starting when Ubuntu (18.04) restarts [SOLVED] documentation?

### ISSUE THREAD

**Issue by cpsyctc2** [hluk/CopyQ#1188]
I've solved this just as I was about to post this as a bug.  I had failed to find this solution in the internet so I'm posting this here so others might find it and I guess if it's really a suggestion for putting this somewhere in your documentation.

**Describe the bug**
I definitely have CopyQ ticked in gnome session startup application preferences but if I restart Ubuntu CopyQ doesn't start automatically and I only ever notice too late.

**To Reproduce**
Reboot system: CopyQ never starts (and sadly I almost always forget this and almost always realise, too late, after I've deleted something some time back and I reach for CopyQ to rescue it!)

**Expected behavior**
CopyQ should start and appear in the top bar.

**Screenshots**
I can screenshot the startup applications if you want but it's there!

**Version, OS and Environment**
 - Application Version 3.8.0
 - OS Linux Ubuntu 18.04.3 LTS
 - Desktop environment, window manager (if applicable) gnome, I don't know more than that.

**Additional context**
I discovered that the solution is to put CopyQ in the Startup programs section of "tweaks" which I think is a gnome component but one I think I may have had to add, ah yes,
`sudo apt-get install gnome-tweak-tool`
I don't know why having CopyQ as a startup program in the main Ubuntu settings isn't working whereas putting it in this gnome tweaks option does but I guess that's more a bug with Ubuntu/gnome than with CopyQ and I'm happy just to have solved this. Thanks for a tremendous program.

**Comment by hluk** [comment]
Can you please share content of `~/.config/autostart/copyq.desktop`? I could try to verify if it's the same as the one CopyQ uses for autostart.
