### ISSUE TITLE
empty clipboard list - circle arrow inside

### ISSUE THREAD

**Issue by herrdeh** [hluk/CopyQ#1189]
**Describe the bug**
My clipboard list is and remains empty, whatever I do. Instead, I see a circle with an arrow.

**To Reproduce**
1. boot the system
2. copy some items
3. look at the copyq window

**Expected behavior**
List of copied items

**Screenshots**
![Bildschirmfoto von 2019-08-08 10-27-21](https://user-images.githubusercontent.com/7152847/62687509-33c9bb80-b9c7-11e9-99c7-680fa4a9ec21.png)

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Application Version 3.2.0
 - OS ubuntu 18.04 GNOME 
 - GNOME, wayland

**Additional context**
Clicking the arrow does not do anything.
"elements" menu items do not open (I'm not sure whether they do contain anything).

**Comment by hluk** [comment]
Are there any errors in log (F12 shortcut)?

**Comment by herrdeh** [comment]
Thanks for your time! - No, only very old entries, nearly a month ago.

**Comment by hluk** [comment]
That's odd, maybe file permission for configuration and log file are incorrect.

Can you try exiting CopyQ and starting it in terminal with following command? It could log something on standard output in terminal.

```bash
COPYQ_LOG_LEVEL=DEBUG copyq
```

BTW, the version you use is very old, there is 3.9.0 already. Can you update?

**Comment by herrdeh** [comment]
That's what I get on terminal - HTH:
`COPYQ_LOG_LEVEL=DEBUG copyq
DEBUG: Server "/home/wd/.config/copyq/.copyq_s" started.
DEBUG: Geometry: Window "ProcessManagerDialog": New geometry for "Options/ProcessManagerDialog_geometry_global_1680x1050_1280x1024"
DEBUG: Geometry: Window "MainWindow": Restore geometry "Options/MainWindow_geometry_global": 645x421,0,0 -> 448x837,520,104
DEBUG: Loading configuration
DEBUG: Tab "Zwis&chenablage": Loading items
DEBUG: QtWarning: qUncompress: Input data is corrupted (:0, )
DEBUG: Configuration loaded
DEBUG: Starting monitor
DEBUG: Executing: copyq monitorClipboard
DEBUG: Got save state request from session manager.
DEBUG: Executing: Command "Zeige/Verstecke Haupt-Fenster"
DEBUG: Geometry: Window "MainWindow": Restore geometry "Options/MainWindow_geometry_global": 448x837,520,104 -> 448x837,520,104
DEBUG: Executing: Command "Zeige/Verstecke Haupt-Fenster"
DEBUG: Executing: Command "Zeige/Verstecke Haupt-Fenster"
DEBUG: Geometry: Window "MainWindow": Restore geometry "Options/MainWindow_geometry_global": 448x837,520,104 -> 448x837,520,134
DEBUG: Executing: Command "Zeige/Verstecke Haupt-Fenster"
`

**Comment by herrdeh** [comment]
Updated to 3.9, problem persists.

**Comment by herrdeh** [comment]
Bthw: This is a really great utility! - Makes life so much easier.
Thank you for your work.

**Comment by hluk** [comment]
Looks like this is the issue:

```
DEBUG: QtWarning: qUncompress: Input data is corrupted
```

Can you check the output of `ls -l /home/wd/.config/copyq`? I think there should be file `copyq_tab_WndpcyZjaGVuYWJsYWdl.dat` with the tab data.

Are you using some other apps that could have write access to the same file?

**Comment by herrdeh** [comment]
Yes the file is in place.

> Are you using some other apps that could have write access to the same file?
I'm not aware of such. Could it have to do with my very special implementation:
[https://github.com/hluk/CopyQ/issues/1076](url)
BTHW: I really love it - would be great to implement it generically into copyQ !

**Comment by hluk** [comment]
Unfortunately, The file might be really corrupted. The data format has not changed in a long time.

Is there `copyq_tab_WndpcyZjaGVuYWJsYWdl.dat.tmp` file? Are any of those files empty?

Normally all data for a tab are first saved in `.tmp` file and then the original file is replaced (assuming the file system move operation is somewhat atomic).

I could try to inspect the file in my development environment, if you don't have any sensitive data in it.

**Comment by herrdeh** [comment]
No, I do not have the ~dat.tmp file.
I killedalll, renamed the copyq_tab_WndpcyZjaGVuYWJsYWdl.dat and restarted - then it worked normally.

How can I know whether the .dat file contains sensitive data? - Can I look into it?

**Comment by hluk** [comment]
> How can I know whether the .dat file contains sensitive data? - Can I look into it?

Not that easy unless you can figure out what it contains from raw data.

```
xxd copyq_tab_WndpcyZjaGVuYWJsYWdl.dat | less
```

Or perhaps with `strings` but it will skip over some data.

```
strings copyq_tab_WndpcyZjaGVuYWJsYWdl.dat | less
```
```

**Comment by konfuzius** [comment]
Same issue after updating from 3.8 to 3.9.1.

**Comment by hluk** [comment]
What does the log say (F12 shortcut)? I've added more detailed error messages in v3.9.1.

**Comment by herrdeh** [comment]
I threw out copyq_tab_WndpcyZjaGVuYWJsYWdl.dat  and restarted copyq, things are looking nice again. Let's see what will happen now.

**Comment by hluk** [comment]
Sorry if you lost any important data. You can use [Backup On Exit](https://github.com/hluk/copyq-commands/tree/master/Scripts#backup-on-exit) command to avoid losing data in future (it makes backup of all data and configuration in `~/Documents/copyq-backups/` when application exits).
