### ISSUE TITLE
Ignore clipboard entries from specific applications

### ISSUE THREAD

**Issue by kapsh** [hluk/CopyQ#1190]
**Is your feature request related to a problem? Please describe.**
Storing everything is insecure when working with password managers which use clipboard (like KeepassXC). The latter has "Clear clipboard after N seconds" option, but it doesn't work when CopyQ is active. 

**Describe the solution you'd like**
CopyQ has customisable list of always ignored applications and never store anything copied from them.

**Describe alternatives you've considered**
I was also thinking to script something like `if (currentWindowTitle() == ignored))...` but can't see how to run Action on every item automatically. 

**Additional context**
Perhaps this feature already implemented but I couldn't find it (please tell me if so).

**Comment by m4r71n** [comment]
Please see [here](https://copyq.readthedocs.io/en/latest/faq.html#how-to-omit-storing-text-copied-from-specific-windows-like-a-password-manager)

**Comment by kapsh** [comment]
@m4r71n thanks! I knew this should be done already. 

Though there are no such command (copyq v3.9.0), but it could be an issue with my build. I will close the issue and sort this out later.

![image](https://user-images.githubusercontent.com/144717/62786619-a6bc5a80-bacb-11e9-85aa-a3d289ef3e8a.png)
