### ISSUE TITLE
CopyQ doesnt' work on ultra wide monitors

### ISSUE THREAD

**Issue by dmitryme** [hluk/CopyQ#1191]
Doens't work on ultra wide monitors (5120x1440). It suck at start with 100% CPU utilization.

**Version, OS and Environment**
- Linux home 5.0.0-23-generic #24-Ubuntu SMP Mon Jul 29 15:36:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Ubuntu 19.04, Linux Mint 19.1(2)

**Comment by hluk** [comment]
I have no idea how to test this (with 4k display + laptop). I tried creating X server with following script but I don't see any increased CPU (but it's also different distro and versions of apps/libraries).

```
Xephyr :9 -ac -br -reset -terminate +iglx +extension Composite -screen 5120x1440 &
export DISPLAY=9
sleep 1
openbox &
copyq
```

Maybe it's unrelated to the resolution.

Is there any error/warning in log (F12 shortcut in main window)?

**Comment by dmitryme** [comment]
Hello, I've found, what 159 line in (common/config.cpp) never ended

157             // Adjust window size to current screen and move to center again.
158             const auto idealSize = w->size();
159             w->adjustSize();     // <--- program hangs here
160             const auto size = w->size().expandedTo(idealSize);

**Comment by hluk** [comment]
OK, thanks for the debug info!

Looks like a Qt bug.

I'll try to remove the line; the code is pretty old, perhaps related to Qt 4 which no longer unsupported.

**Comment by dmitryme** [comment]
Yes, just comment out this line works for me.
