### ISSUE TITLE
Copying from windows explorer

### ISSUE THREAD

**Issue by jffoleyiv** [hluk/CopyQ#1192]
I love your interface and features, but the lack of compatibility to copy from windows explorer (except file paths) is a deal-breaker. Most clipboard manager programs do have this feature. I will continue to check back and see if it is implemented.

I believe I read somewhere that the way windows handles copying from explorer is strange and problematic, but other developers seem to have overcome that issue.

am I missing something?

**Comment by nmat** [comment]
Can you elaborate a bit more on what exactly is not working for you when you use copy/paste with copyq?

I have used copyq for a long time in all sort of applications locally and to remote hosts without any issues from what I have seen.

So it would help to get some more information on what exactly is not working so that it can be reproduced.

**Comment by jffoleyiv** [comment]
First, thank you for any advice or assistance you can give. I love the
interface of CopyQ, but this issue makes it difficult to choose as my
clipboard manager.

To explain further, I have been evaluation various clipboard/copy utilities
for Windows 10 over the past month.

With CopyQ (version copyq-v3.9.0), I have found that when I copy a file
from the Windows Explorer (file manager) application, be it an image,
.xlsx, .docx, or anything, CopyQ preserves the file path instead of the
file. If I attempt to paste it into another windows folder, nothing
happens. If I paste into a text field or editor, I get the file path.
Copying images from the internet works fine.

Conversely, in other clipboard managers, like ClipAngel (version 1.83),
which I am currently evaluating, the actual file copied is preserved, so I
can paste it back into explorer or into a document. ClipAngel also has an
option to paste the path.

I have tried running CopyQ as an administrator, using an alternate file
explorer (Free Commander), reinstalling, and rebooting. Nothing has changed
this behavior. I cannot find a setting to change it.

I am running Microsoft Windows 10 Home, Version 10.0.17763 Build 17763.

All the other clipboard managers I have tried have no problems with this
issue, but I still like CopyQ and its interface better.

Attached are screenshots from running ClipAngel and CopyQ simultaneously.
Item 1 is a jpeg from file explorer, item 2 is an excel file from windows
file explorer, and item 3 is the same jpeg from Chrome. CopyQ only
succeeded with item 3.

John Foley
[image: clipangel.png]
[image: CopyQ.png]

**Comment by nmat** [comment]
This does seem like a strange setting somewhere that is set because I have tested it on 2 machines and it copies files instead of paths in file explorer.

This is 2 win 10 machines and both of them work as intended. even version 1903.

**Comment by hluk** [comment]
You probably just need to tell CopyQ to store additional `text/uri-list` format with following command ([here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)).

```ini
[Command]
Automatic=true
Icon=\xf0c1
Input=text/uri-list
Name=Copy Files/URIs
```
