### ISSUE TITLE
Lastpass extension update beats Ignore Password command

### ISSUE THREAD

**Issue by yetanotheronegithub** [hluk/CopyQ#1194]
Hi, just letting you know that Lastpass extension doesn't seem to work with the Ignore "Password" window command any more. The previous version worked very well.

Lastpass has been rolling out an updated extension with "improved" UX. You now have to click on a down arrow to copy passwords. I'm not sure if this is where the problem lies.

Also, even if you Select All and delete, the CopyQ tray icon will display the last copied item (ie your password) if you hover your mouse over it! 
<img width="144" alt="2019-08-14 (1)" src="https://user-images.githubusercontent.com/54104136/63016715-4f800680-be8c-11e9-8b8b-01108252d2cc.png">
<img width="130" alt="2019-08-14" src="https://user-images.githubusercontent.com/54104136/63016716-4f800680-be8c-11e9-9227-90869f6e2101.png">

**Comment by hluk** [comment]
You can inspect window title by using following command. Then use update the window title in the Ignore command.

```ini
[Command]
Command="
    function clipboardNotification(owns, hidden) {
        var id = isClipboard() ? 'clipboard' : 'selection'
        var icon = isClipboard() ? '\\uf0ea' : '\\uf246'
        var owner = owns ? 'CopyQ' : str(data(mimeWindowTitle))
        var title = id + ' - ' + owner
        var message = hidden ? '<HIDDEN>' : data(mimeText).left(100)
        notification(
          '.id', id,
          '.title', title,
          '.message', message,
          '.icon', icon
        )
    }
    
    onClipboardChanged_ = onClipboardChanged
    onClipboardChanged = function() {
        clipboardNotification(false, false)
        onClipboardChanged_()
    }
    
    onOwnClipboardChanged_ = onOwnClipboardChanged
    onOwnClipboardChanged = function() {
        clipboardNotification(true, false)
        onOwnClipboardChanged_()
    }
    
    onHiddenClipboardChanged_ = onHiddenClipboardChanged
    onHiddenClipboardChanged = function() {
        clipboardNotification(true, true)
        onHiddenClipboardChanged_()
    }"
Icon=\xf075
IsScript=true
Name=Clipboard Notification
```

You can use `^$` if the title is empty but it could interfere with other applications.

**Comment by yetanotheronegithub** [comment]
Thanks hluk, I gave it a go but it reported failed to start. I'll keep trying. Appreciate your help and if I get it working I'll reply here again.

**Comment by hluk** [comment]
Just for completeness: [here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them).

**Comment by yetanotheronegithub** [comment]
Thanks again, what I needed to do was restart CopyQ and then the infotool command started working perfectly and the clipboard command started working to an extent. It works fine if I copy some text off a webpage - here's what I see if I lift the word "fine" off this post: 
![image](https://user-images.githubusercontent.com/54104136/63112269-b1716680-bf87-11e9-8824-8be6f0aa9466.png)

However, there's still no info on the name of the Lastpass window. Here's what I see if I copy my Github user name from the Lastpass extension: 
![image](https://user-images.githubusercontent.com/54104136/63112161-70795200-bf87-11e9-821c-6d9e6a7dfd9b.png)

I'll try the ^$ suggestion - do I need to paste it into the Ignore command or insert it into the code somewhere?

Once again, thanks for your help - much appreciated.

**Comment by hluk** [comment]
Try adding this command:

```ini
[Command]
Automatic=true
Command="
    copyq ignore"
Icon=\xf069
Name=Ignore *\"Password\"* window
Remove=true
Window=^$
```

**Comment by yetanotheronegithub** [comment]
Yes! That seems to be working! I can see the scissors snipping but nothing appears in the CopyQ pane. However, when I copy a word from this webpage it does appear. So this, plus the infotool command means that Lastpass users should be able to copy passwords without it appearing in CopyQ or displaying as most recent clipped item in the infobar. Great work hluk!
