### ISSUE TITLE
CopyQ displays last copied item in system tray even after all items are deleted

### ISSUE THREAD

**Issue by yetanotheronegithub** [hluk/CopyQ#1195]
**Describe the bug**
The CopyQ system tray displays the last copied item if you hover your mouse over it, even if you have tried Select All, Delete to clear the clipboard history. This is a particular issue for users of the new Lastpass extension, which no longer seems to work with the Ignore "Password" window rule. For them, clearing the clipboard history can still leave the password visible.

**To Reproduce**
1. Copy a short piece of text to the clipboard
2. Open CopyQ
3. Select All (CTRL-A)
4. Press Delete to clear the clipboard history
5. Hover your mouse over the system tray icon
6. The last copied text displays in the info balloon followed by the word "CopyQ"

**Expected behavior**
When you delete the clipboard history, the info balloon should only display the word "CopyQ"

**Screenshots**
Attached. <img width="130" alt="2019-08-14" src="https://user-images.githubusercontent.com/54104136/63017181-90c4e600-be8d-11e9-8410-e6b34ea7b216.png">

**Version, OS and Environment**
 - Application Version 3.8.0
 - OS Windows 10 Pro
 - Standard laptop

**Additional context**
See also item #1194 relating to the new Lastpass extension.

**Comment by hluk** [comment]
The tooltip shows current clipboard content, not the last saved item. This is expected.

You can use following command to hide clipboard in GUI (thought new items will still be created).

```ini
[Command]
Command="
    // Empty tray tooltip and window title.
    global.updateTitle = function(){}
    
    // No clipboard notification.
    global.showDataNotification = function(){}
    
    // Empty clipboard text in tray menu.
    global.setClipboardData = function(){}"
Icon=\xf070
IsScript=true
Name=Hide Clipboard
```
