### ISSUE TITLE
Character lost in copying

### ISSUE THREAD

**Issue by NightMachinary** [hluk/CopyQ#1198]
```
$ copyq copy ' \(ᵔᵕᵔ)/' ; pbpaste
true
 (ᵔᵕᵔ)/
```

**Version, OS and Environment**
CopyQ Clipboard Manager v3.9.0
Qt: 5.12.3
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: macOS Mojave (10.14)

**Comment by hluk** [comment]
Escape sequence `\(` passed as argument is treated as `(`.

To ignore escape sequences, use one of:

```bash
copyq copy -- $DATA
copyq copy <<< $DATA
echo -n $DATA | copyq copy -
cat $FILE | copyq copy -
```

**Comment by NightMachinary** [comment]
I suggest adding `--` to the examples ... It's not at all intuitive. Thanks!

**Comment by hluk** [comment]
> I suggest adding `--` to the examples ... It's not at all intuitive.

Done, I've updated the REAME.md and [the landing page](https://hluk.github.io/CopyQ/).
