### ISSUE TITLE
Add entry deletion prompt when delete multiple items 

### ISSUE THREAD

**Issue by corona-nova** [hluk/CopyQ#1199]
**request related to a problem? Please describe.**
frustrated when cleaning clipboard history of clutter
of the many times i delete, the shift-key got stuck and instead deleted much more than one entry with no easy straightforward undo

**Describe the solution you'd like**
a yes/no prompt for large deletions both(text-length and number entries)

**Describe alternatives you've considered**

- wiki page for adding trash-can redirect, finally got it working today,
but whether it should be a built-in option
because finding the config.ini, or navigating the interface for the first time
isn't that straight-forward

**Additional context**
maybe something similar to  the exit dialog,
but maybe make it a timed deletion (5 seconds grace-period, auto-close&delete)
to make dialogs less annoying
![image](https://user-images.githubusercontent.com/54251501/63232392-81c79600-c1f5-11e9-9cd1-64f982da4b57.png)

i do appreciate the program and use it a lot

**Comment by hluk** [comment]
> of the many times i delete, the shift-key got stuck and instead deleted much more than one entry with no easy straightforward undo

Isn't the issue somewhere else then? What does "shift-key got stuck" mean?

> but maybe make it a timed deletion (5 seconds grace-period, auto-close&delete)

This doesn't sound like a good UI practice. I would find it more annoying to have the countdown.

I could add "Prompt Before Deleting" simple option if that would help but anything more complex would be better to handle using a custom command.

**Comment by heywolf15** [comment]
> I could add "Prompt Before Deleting" simple option if that would help but anything more complex would be better to handle using a custom command.

@hluk  Pls add "Prompt Before Deleting" or history of what has been deleted
