### ISSUE TITLE
Very slow using 3000 Items as Historic.

### ISSUE THREAD

**Issue by luapfr** [hluk/CopyQ#1202]
If I enable Preview it is a long time searching, I currently have a Core I7 8750H with 32Gb of Ram memory.

I did a test using for a month to get the same history items with CopyQ and ClipAngel 1.8.3
and ClipAngel is much faster to search through items and do research with the preview

**Comment by hluk** [comment]
No idea what to do here. I am always trying to improve the performance. The way CopyQ stores and loads items is not ideal but changing it would require larger code changes.

If you can limit the number of items in tab to 1000 and use automatic commands to move related items to other tab.

**Comment by luapfr** [comment]
so I use the clipboard a lot, and 1000 items is very little, in ClipAngel 1.83 I set the history to 8000 and it doesn't slow down, it already filled the 8000 items and it's super fast,
however clipAngel does not have all CopyQ functionality
I believe an optimization in CopyQ would be very interesting.

Thankful.

**Comment by hluk** [comment]
I've added a fix so that the preview is not updated so often when searching (and in other cases).

Windows build: https://ci.appveyor.com/project/hluk/copyq/builds/26943455/job/9jlo3usj9w3563sk/artifacts

**Comment by luapfr** [comment]
Unfortunately it didn't work out, if I hit F3 to do a search and scroll the scroll bar is horribly slow.

See I have 2000 Items to save in CopyQ, and ClipAngel has 9000 Items

Watch this video on the link
[](https://mega.nz/#!xvhC3CzY!RTPCOfWZDN9Y0HKD78Lsky8D0oM_vZbT0gabXgoCwxk)

**Comment by luapfr** [comment]
[https://mega.nz/#!xvhC3CzY!RTPCOfWZDN9Y0HKD78Lsky8D0oM_vZbT0gabXgoCwxk](url)

**Comment by hluk** [comment]
Thanks for sharing the video.

GUI representations of the items are created dynamically when needed (when visible in the viewport) that's why it's slow.

You can have simpler items in the list (with a bit faster rendering) by enabling "Show simple items" in History config tab.

I'll see if I can improve it somehow but no promises. :)

**Comment by luapfr** [comment]
Hello I enabled to show the simple items however the performance remains slow equal.
