### ISSUE TITLE
Fixing corrupted data file "Failed to set model data"

### ISSUE THREAD

**Issue by ivdimitro** [hluk/CopyQ#1203]
**Describe the bug**
The clipboard content is not loading in the default clipboard tab. The issue persists restart. 
The export functionality is also not working, resulting in 0b file. 
The log files show error "ERROR [2019-08-23 23:43:49.560] <Server-1053>: Failed to set model data"
New entries are being added to the clipboard and paste is working as well. 
I have 2 other tabs which display their content correctly

**To Reproduce**
Not sure. I have upgraded to version 3.9.1 recently and I had to do a few hard resets which could have caused the corruption. 

**Expected behavior**
The clipboard entries are shown in the list 

**Screenshots**
[link](https://drive.google.com/file/d/1atbSM-m5R8V4T1cHdItQo2QdOS8Wq8gJ/view?usp=sharing )

**Version, OS and Environment**
Arch with KDE, X11 - latest

**Additional context**
Is there a possibility to fix the DB or open it manually to remove the wrong entry? From the code it seems the error is thrown when parsing individual lines.

**Comment by hluk** [comment]
Sorry about this. It should be already fixed (6f16ffc4e42fa5b75ab3aaeb28bf40ac68a2fcc1).

There is no data corruption, CopyQ just mistakenly refuses to load an empty item and assumes that something is wrong with the whole file.

I am releasing new version just now.

**Comment by GuyKroizman** [comment]
I got the same error. I am using the latest version provided by the latest ubunut which is 3.9.1. 
I installed it via the "ubuntu software center".

I understand this was fixed. 
But I would much rather not have to build this from code. Is it possible to reset my db somehow?
Or maybe some other easy solution?

**Comment by hluk** [comment]
The fixed version is available on PPA. See: https://github.com/hluk/CopyQ#ubuntu-ppa
