### ISSUE TITLE
Add to tray menu no longer working?

### ISSUE THREAD

**Issue by orschiro** [hluk/CopyQ#1204]
Hi guys, 

I am doing something incorrectly?

Please see below. 

How can I add this custom action back to the tray menu?

This used to work in the past. 

Thank you!!

![image](https://user-images.githubusercontent.com/170947/63830642-f1afec00-c96c-11e9-8c0e-61fbfa6edbe7.png)

**Comment by hluk** [comment]
You now need to enable "Global Shortcut" option to add the command to tray menu (you should probably disable the other checkboxes). Tray menu doesn't make sense for other command types in most cases.

**Comment by orschiro** [comment]
Thanks @hluk!

However, now I am receiving this weird issue:

https://drive.google.com/file/d/1ozmysYkOtNEful8LqE5yKCc6XKJE2meG/view

**Comment by hluk** [comment]
Is your "Paste Date" command marked as "Automatic"? From the screenshot above it seems to be true. I think it should be marked only as "Global Shortcut" ("In Menu" is probably not needed either because it means that the command is available from context or Item menu in CopyQ window).

**Comment by orschiro** [comment]
Ah yes, that's why. Thanks for all your help, Lukas!

-
Regards

**Comment by orschiro** [comment]
New automation Expert Talks, free e-book, live Covid-19 impact tracking template in Google Sheets and product updates.

logo-white-background (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbkJ8gbW6-nQtX59jyZbW8d_Yq57K750VW6rgDd-6Ww6zBf1HVPN203 )

Staying connected while staying apart

Dear users, partners and friends,

The Sheetgo community extends across the globe and we know that many of you are facing unexpected challenges and immense upheaval right now.

On behalf of our (remote) team, I wanted to let you know that we're here to support you and we're taking extra measures to help you keep your business running as smoothly as possible. You've been telling us that you need automation solutions more than ever.

Here's what we're doing:

SUPPORT

- Expert Talks every week to help you automate and manage data remotely. Register (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbkJ8gbW6-nQtX59jyZbW8d_Yq57K750VW6rgDd-6Ww6zBf1HVPN213 ) for our next talk: Automation for SMEs. April 7th.
- New business automation specialist. We have expanded our Customer Success team to give you extra support across US and European time zones.
- Server power. Sheetgo runs on Google and Amazon servers — the most secure and reliable cloud infrastructures in the world — and we will now be boosting that with Microsoft servers to deliver the best performance.
- Resources. We've created a template (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbkJ8gbW6-nQtX59jyZbW8d_Yq57K750VW6rgDd-6Ww6zBf1HVPN223 ) to help you analyze the regional impact of coronavius and we're sharing a new e-book (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbkJ8gbW6-nQtX59jyZbW8d_Yq57K750VW6rgDd-6Ww6zBf1HVPN233 ) to help you prepare your data for automated processes.

LEARNING

E-book

Collaborating and sharing data when working remotely requires a bit of forward planning. Learn how to automate and scale your business with the Sheetgo process design method.

Get the e-book (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbkJ8gbW6-nQtX59jyZbW8d_Yq57K750VW6rgDd-6Ww6zBf1HVPN243 )

Tips for remote teams

Has your team been thrown into disarray by working from home? Read our tips on how to stay productive and connected, no matter where you're located.

Read more (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbkJ8gbW6-nQtX59jyZbW8d_Yq57K750VW6rgDd-6Ww6zBf1HVPN253 )

TEMPLATE

Covid-19 impact tracking

We have developed a template that pulls live data from the COVID-19 database at John Hopkins University, allowing you to measure the impact of the coronavirus outbreak on your KPIs, region by region.

Get the template (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbkJ8gbW6-nQtX59jyZbW8d_Yq57K750VW6rgDd-6Ww6zBf1HVPN263 )

PRODUCT

Duplicate workflow

If you develop a solution and want to replicate it for another department or client, you can now copy the entire workflow — every connection and spreadsheet — without having to build the system from scratch. In the Sheetgo web app, find the option in the menu bar (⋮).

Open Sheetgo (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbkJ8gbW6-nQtX59jyZbW8d_Yq57K750VW6rgDd-6Ww6zBf1HVPN273 )

I'd love to hear if there are any other ways we can help and support you right now. If you need training for your staff or project consultation get in touch with our experts (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbkJ8gbW6-nQtX59jyZbW8d_Yq57K750VW6rgDd-6Ww6zBf1HVPN283 ) .

Please feel free to reply to this email with any suggestions, requests or comments.

As always, thank you. And stay safe.

Yours,

LinkedIn (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbkJ8gbW6-nQtX59jyZbW8d_Yq57K750VW6rgDd-6Ww6zBf1HVPN293 )

YouTube (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbkJ8gbW6-nQtX59jyZbW8d_Yq57K750VW6rgDd-6Ww6zBf1HVPN2b3 )

Twitter (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbkJ8gbW6-nQtX59jyZbW8d_Yq57K750VW6rgDd-6Ww6zBf1HVPN2c3 )

Need help using Sheetgo? Contact us here. (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbkJ8gbW6-nQtX59jyZbW8d_Yq57K750VW6rgDd-6Ww6zBf1HVPN2d3 )

Sheetgo, 601 Van Ness Ave, Ste E, San Francisco, California 94102, USA, +1 (612) 470-5696

Unsubscribe (https://hs-5756448.s.hubspotemail.net/hs/manage-preferences/unsubscribe-all?d=VnBg006k4PD4W2p76LK3-1rCSW3z7ZJq47m79wW41rvvp4mDkgfW3BPc4m45S35SW43SHGn3KbsvFW3R0gmC1_tFmHW3JP0gk45RlhdW3P28X24hCPvhW43T2NR5mwb30W17f7hv91gdhHW75_b3w5d8zZ7W50dGgY8sQtRxV28Q0j7q7XXdMGKd_P20N4xW6Jz_1_2z7p9gW4JhM__95Fv2q4B0Xv1&v=3&_hsenc=p2ANqtz--PQpJmd-8JcqOQKYIp3PTtu5FTDn0OkwTvza_g-YuKhwnX7o215ZhojzCZH4dsR2GN62Wu9WBYExzAJmae7KXPDtq12fkssZNS55dmJYrWZzDCwCuzaTpKWIEvBGsFUCNEWvE2hXPAZRD91KGoNHWsM-L_nQ&_hsmi=85605929 )

Manage preferences (https://hs-5756448.s.hubspotemail.net/hs/manage-preferences/unsubscribe?d=VnBg006k4PD4W2p76LK3-1rCSW3z7ZJq47m79wW41rvvp4mDkgfW3BPc4m45S35SW43SHGn3KbsvFW3R0gmC1_tFmHW3JP0gk45RlhdW3P28X24hCPvhW43T2NR5mwb30W17f7hv91gdhHW75_b3w5d8zZ7W50dGgY8sQtRxV28Q0j7q7XXdMGKd_P20N4xW6Jz_1_2z7p9gW4JhM__95Fv2q4B0Xv1&v=3&_hsenc=p2ANqtz--PQpJmd-8JcqOQKYIp3PTtu5FTDn0OkwTvza_g-YuKhwnX7o215ZhojzCZH4dsR2GN62Wu9WBYExzAJmae7KXPDtq12fkssZNS55dmJYrWZzDCwCuzaTpKWIEvBGsFUCNEWvE2hXPAZRD91KGoNHWsM-L_nQ&_hsmi=85605929 )

**Comment by orschiro** [comment]
Product updates, connect Google classroom, remote work & Covid-19 solutions. Smart spreadsheet experts needed!

logo-white-background (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbkrmVgW549GZD7DMWlnW7kLSdh87X2VLW65wJKy8pD7XKf1HVPN203 )

What's new in Sheetgo?

Global lockdowns and remote working mean many of you have reached out to us looking for new automation solutions — read on for ideas on how to manage your data and collaborate more smoothly in a changing environment. We've made some product updates based on your feedback and we've got a big annoucement too!

PRODUCT UPDATES

Sliding sidebar

You told us that you needed a way to collapse the sidebar, so we have adjusted the spreadsheet editor. Just click on the blue arrow to switch between the full spreadsheet view and the workflow editor panel on the right.

Workflow menu

The floating workflow menu lets you schedule automatic updates, add a new connection and run or share your workflow while you're working in your spreadsheets. Click and drag to move the menu bar around your screen.

Open Sheetgo (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbkrmVgW549GZD7DMWlnW7kLSdh87X2VLW65wJKy8pD7XKf1HVPN213 )

COMPANY NEWS

New partnership

Sheetgo is now an official Dropbox technology partner! We're working on some exciting projects to enable even more spreadsheet users to connect and automate. Watch this space!

CRISIS & REMOTE SOLUTIONS

Manage urgent deliveries

Covid-19 meant HMG Healthcare needed a way to manage orders and deliveries of personal protective equipment to care staff at their nursing facilities — as quickly as possible. They used Sheetgo to create a dynamic PPE inventory system.

Read more (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbkrmVgW549GZD7DMWlnW7kLSdh87X2VLW65wJKy8pD7XKf1HVPN223 )

Templates for remote

Are more of your business departments and processes moving online? From project management to cash flow monitoring, check out our range of Google Sheets-based templates to help remote teams collaborate more productively.

Find a template (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbkrmVgW549GZD7DMWlnW7kLSdh87X2VLW65wJKy8pD7XKf1HVPN233 )

COMMUNITY PARTNERS

Spreadsheet masters: we want to meet you!

Looking to leverage your spreadsheet skills to generate an additional source of income? If you're interested in implementing no-code automation solutions for local businesses in your network, please get in touch with us.

I'm interested (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbkrmVgW549GZD7DMWlnW7kLSdh87X2VLW65wJKy8pD7XKf1HVPN243 )

SHEETGO FOR EDUCATION

Connect Google Classroom data

Teachers told us they were looking for a way to register student attendance via Google Classroom. Here's how to create your own automated system, using Google Sheets, Sheetgo templates and Forms.

Learn how (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbkrmVgW549GZD7DMWlnW7kLSdh87X2VLW65wJKy8pD7XKf1HVPN253 )

LinkedIn (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbkrmVgW549GZD7DMWlnW7kLSdh87X2VLW65wJKy8pD7XKf1HVPN263 )

YouTube (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbkrmVgW549GZD7DMWlnW7kLSdh87X2VLW65wJKy8pD7XKf1HVPN273 )

Twitter (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbkrmVgW549GZD7DMWlnW7kLSdh87X2VLW65wJKy8pD7XKf1HVPN283 )

Got comments or feedback? Just reply to this email!

Need help using Sheetgo? Contact our support team (https://i7.t.hubspotemail.net/e2t/sc2/Mm-nFbkrmVgW549GZD7DMWlnW7kLSdh87X2VLW65wJKy8pD7XKf1HVPN293 ) .

Sheetgo, 601 Van Ness Ave, Ste E, San Francisco, California 94102, USA, +1 (612) 470-5696

Unsubscribe (https://hs-5756448.s.hubspotemail.net/hs/manage-preferences/unsubscribe-all?d=VnBg006k4PD4W2p76LK3-1rCSW3z7ZJq47m79wW41rvvp4mDkgfW3BPc4m45S35SW43SHGn3KbsvFW3R0gmC1_tFmHW3JP0gk45RlhdW3P28X24hCPvhW43T2NR5mwb30W17f7hv7QXh3HW8-RGC46rgCyPW5k6PJM8YqZpyV28R8J8rfMCKMGKd_P20N5vW1w-L9X8DS1psW40WSDC2WKjBd51xYVK1&v=3&_hsenc=p2ANqtz-86U15klbg8FRgoQrvj0W9GFE0UOUaxCpgZKPiFsl665oDkiGdY_w5fT69z7NnK3fSVN77NAYdmfneC1pGEEJ0YDkr36Owqri_yPjY5Z39K35LNpQZCn9xBwqsHUU8Wrl7xgmwueas0cSZUE_xV_TUyGaRWgQ&_hsmi=87730606 )

Manage preferences (https://hs-5756448.s.hubspotemail.net/hs/manage-preferences/unsubscribe?d=VnBg006k4PD4W2p76LK3-1rCSW3z7ZJq47m79wW41rvvp4mDkgfW3BPc4m45S35SW43SHGn3KbsvFW3R0gmC1_tFmHW3JP0gk45RlhdW3P28X24hCPvhW43T2NR5mwb30W17f7hv7QXh3HW8-RGC46rgCyPW5k6PJM8YqZpyV28R8J8rfMCKMGKd_P20N5vW1w-L9X8DS1psW40WSDC2WKjBd51xYVK1&v=3&_hsenc=p2ANqtz-86U15klbg8FRgoQrvj0W9GFE0UOUaxCpgZKPiFsl665oDkiGdY_w5fT69z7NnK3fSVN77NAYdmfneC1pGEEJ0YDkr36Owqri_yPjY5Z39K35LNpQZCn9xBwqsHUU8Wrl7xgmwueas0cSZUE_xV_TUyGaRWgQ&_hsmi=87730606 )

**Comment by hluk** [comment]
@orschiro I received some spam messages from your account again on couple of issues.

**Comment by orschiro** [comment]
I am sorry! Let me check what's generating those comments.

**Comment by hluk** [comment]
BTW, looks like the spam comments are created using mail.

**Comment by orschiro** [comment]
I fixed it. Can you let me know please if you still see any of my unwanted
comments and I will delete them.

Thanks!

**Comment by hluk** [comment]
> I fixed it. Can you let me know please if you still see any of my unwanted
> comments and I will delete them.

Thanks, will do.
