### ISSUE TITLE
Global menu does not always work on Linux.

### ISSUE THREAD

**Issue by ripefig** [hluk/CopyQ#1206]
**Describe the bug**

**To Reproduce**
1. Run CopyQ in the background with Global Menu enabled on a system like KDE
2. Launch it a few times over the course of a day.
3. Eventually the global menu will stop being exported to the system global menu and appear only inside the application.

**Expected behavior**
Menubar should be reliably exported by QT to the system global menu and hidden within the app.

**Version, OS and Environment**
Operating System: Kubuntu 19.04
KDE Plasma Version: 5.16.4
KDE Frameworks Version: 5.61.0
Qt Version: 5.12.2
Kernel Version: 5.0.0-26-generic
OS Type: 64-bit

Clipboard Manager
v3.8.0

**Additional context**
This is not a KDE-specific bug. The application will have the same problem with any Unity-based global menu implementation.

**Comment by hluk** [comment]
Some sub-menus in the menu bar are generated dynamically (e.g. when selecting items and tabs) but everything is handled by Qt and the libraries and components responsible for the global menu. There is probably common component in KDE and Unity that is misbehaving.

I really have no idea how to fix this in CopyQ. To mitigate the problem I could try to update the menus less often.

This could be also related to #1201.

**Comment by ripefig** [comment]
You could ask these guys https://gitlab.com/vala-panel-project/vala-panel-appmenu
They might know what to do.

**Comment by hluk** [comment]
> You could ask these guys https://gitlab.com/vala-panel-project/vala-panel-appmenu
> They might know what to do.

Well, yes, that was [my response](https://github.com/hluk/CopyQ/issues/1201#issuecomment-524272276) in #1201. :)
