### ISSUE TITLE
Explain how "Copy as Json" and "Paste as Json" works

### ISSUE THREAD

**Issue by glolsh** [hluk/CopyQ#1207]
https://github.com/hluk/copyq-commands/blob/master/Application/copy-paste-items-as-json.ini

I thought that it should paste unformatted json as formatted in text editor, but it seems it works different. Can you explain - extend command description?

![image](https://user-images.githubusercontent.com/14776737/63992585-b7824e00-cb16-11e9-8ba1-e3cb4907790a.png)

**Comment by hluk** [comment]
The [description](https://github.com/hluk/copyq-commands/tree/master/Application#copy-and-paste-items-in-json-format) says:

> Allows to easily share items in readable text format.

The "items" here mean all the data of selected entries in the current CopyQ tab. So the command only works from the main application window.

**Comment by glolsh** [comment]
So "paste" right (via shortcut) to the text app is not possible. Kk
