### ISSUE TITLE
How to get available mimeType from command line or ECMAScript?

### ISSUE THREAD

**Issue by unmem** [hluk/CopyQ#1210]
In the [Scripting API documentation](https://copyq.readthedocs.io/en/latest/scripting-api.html), i have not found the function return all available mimeTypes for sepecific item row like `text/plain text/html`.

<img width="949" alt="Screen Shot 2019-09-05 at 1 17 28 PM" src="https://user-images.githubusercontent.com/16096559/64313870-a1293600-cfdf-11e9-9d83-ab6d773b34b2.png">

**Comment by hluk** [comment]
It's mentioned in description for `read()` function (thought a bit hard to find).

```
copyq read '?' 0
```
