### ISSUE TITLE
How to get user-defined formats from command line?

### ISSUE THREAD

**Issue by unmem** [hluk/CopyQ#1212]
```
[Command]
Automatic=true
Command="
    copyq:
    var windowTitle = data(mimeWindowTitle)
    settings('clipboard-window-title', windowTitle)
    setData('application/x-copyq-clipboard-window-title', windowTitle)"
Icon=\xf022
Name=Store Window Title for Clipboard
```

Steps
1. Copy this issue title 

2. Showing content for current clipboard first item
<img width="949" alt="Screen Shot 2019-09-05 at 2 12 39 PM" src="https://user-images.githubusercontent.com/16096559/64316464-7d69ee00-cfe7-11e9-97a4-f1c0501ecbc4.png">

3. Run command `copyq read application/x-copyq-clipboard-window-title` return nothing.

4. Run command `copyq read text/plain` return `How to get user-defined formats from command line? #1212`

**Comment by hluk** [comment]
You need to specify row index otherwise `read()` returns clipboard data and `application/x-copyq-*` formats are usually not stored in clipboard (unless you copy the item from CopyQ).

```
copyq read application/x-copyq-clipboard-window-title 0
```
