### ISSUE TITLE
shortcut key for opening command window?

### ISSUE THREAD

**Issue by reagle** [hluk/CopyQ#1213]
I apologize, this seems like a simple question -- and I fear I've asked it before -- but is there a keyboard shortcut that opens up the command menu? (So I don't have to alt-click via a mouse?)

**Comment by hluk** [comment]
Do you mean "Show the tray menu" shortcut?

![image](https://user-images.githubusercontent.com/38054/64427750-3694fa80-d0b2-11e9-9c67-9bf217f5b014.png)

**Comment by reagle** [comment]
I mean the menu with commands (i.e., beginning with "Search Google" and ending with "Move to Bottom."

<img width="653" alt="Screen Shot 2019-09-06 at 8 30 53 AM" src="https://user-images.githubusercontent.com/596814/64428339-7ee7f480-d081-11e9-9097-de0f13ef534d.png">

**Comment by hluk** [comment]
Isn't there a standard shortcut to open context menu on macOS? (I usually use the `Menu` key.)

Otherwise it's possible to use the Item menu (opens with Alt+I on Windows and most desktop environments on Linux).

**Comment by reagle** [comment]
Don't know, and I'm using a Kinesis Keyboard on my Mac. It'd be nice if there was a configurable key.

**Comment by hluk** [comment]
Oh, this is already implemented (#1011). I completely forgot about this. :)

The default shortcut is Shift+F10.

![image](https://user-images.githubusercontent.com/38054/65368941-50ecdd80-dc47-11e9-916c-06a078de6916.png)

**Comment by reagle** [comment]
Thank you. I was still at 3.1.2 because of #884 but that long since been fixed and appeared in homebrew, so now I'm following the latest brew and things seems to be working well.
