### ISSUE TITLE
Changing theme from command line.

### ISSUE THREAD

**Issue by Migacz85** [hluk/CopyQ#1214]
Hi, 
I'm using i3wm, and pretty often I switch from nigth to day theme. So I have script where I put all programs that I can switch to night/day mode externally from bash. Is it possible to run some small command that will change theme of CopyQ externally ? Thanks

**Comment by hluk** [comment]
Currently it's not possible. I'm adding `loadTheme` script function:

```
copyq loadTheme /path/to/theme.ini
```

**Comment by Migacz85** [comment]
Thats brilliant :-) Thank you
