### ISSUE TITLE
Main window off the screen

### ISSUE THREAD

**Issue by Ragista** [hluk/CopyQ#1216]
I use a hotkey on Windows 10 to open CopyQ's main window. Since version 3.9.2, the CopyQ window appears strictly at the mouse position and is often off the screen. (Sorry Google Translate this)

**Comment by hluk** [comment]
No sure what you mean by "at the mouse position".

Try clearing geometry/position configuration for CopyQ windows/dialogs:

1. Open File Explorer,
2. go to `%APPDATA%\copyq` folder,
3. delete `copyq_geometry.ini`.

**Comment by pezzage** [comment]
I have the same problem and deleting the file does not help.
When I press the shortcut to show the main window, it's upper edge is at the mouse level so if the mouse was at the bottom of the screen then the whole window is basically off the screen.

**Comment by jcwing01** [comment]
Hi Lukas,  same issue here.  I believe it started with the update to 3.9.3 for me.  Deleting the geometry file did not fix the issue.  Thanks

**Comment by kasumiru** [comment]
Same bug! Deleting the file does not fix this problem!

**Comment by jcwing01** [comment]
Hi, has anyone found an easily solution?  I tried deleting the geometry file and reinstalling to a new folder and importing settings and neither worked.

**Comment by hluk** [comment]
Can you explain the problem more in detail?

Do you use "Show/hide main window" shortcut to open the main window?

Can you reproduce it by clicking on the tray icon?

Is "Open windows on current screen" option enabled (in General config tab)?

**Comment by jcwing01** [comment]
Hi Lukas,
To be clear this is purely from the shortcut 'show main window under mouse cursor', which as you know aligns the top left corner of the main window with the position of the mouse cursor.  This used to adjust for the edges of the monitor so that no part of the main window would be offscreen, however after one of the recent updates, or something I did, it no longer does this.  Thanks.

**Comment by kasumiru** [comment]
> Hi, has anyone found an easily solution? I tried deleting the geometry file and reinstalling to a new folder and importing settings and neither worked.

Solution - install 3.9.0.

**Comment by hluk** [comment]
@jcwing01 Thanks for the clarification. It looks like Qt GUI framework (or window manager) moves the window to another screen if its lower right corner is out of current screen. Fixing this.

**Comment by kasumiru** [comment]
v3.12.0 bug was here! windows 10, screen 1366x768

**Comment by kasumiru** [comment]
up

**Comment by kasumiru** [comment]
Copyq v3.13.0, latest version, on Oct 16, 2020. 
Windows 10 and another windows 10 in virtualbox have this bug, just tested. 
Two or three strings was hidden.. *crying emoticon*.


![image](https://user-images.githubusercontent.com/25246740/104126612-a5e9c100-536e-11eb-9dab-e421efcfff63.png)
if manual moving window:
![image](https://user-images.githubusercontent.com/25246740/104126620-b1d58300-536e-11eb-8c41-7207b8a696e1.png)

And another:
![image](https://user-images.githubusercontent.com/25246740/104127098-3fb26d80-5371-11eb-8f06-a1049942a840.png)
if manual moving window:
![image](https://user-images.githubusercontent.com/25246740/104127104-46d97b80-5371-11eb-9287-f3c61b97c8ec.png)

Please help me.
