### ISSUE TITLE
The icon is in on the top left corner  in Ubuntu 14.04

### ISSUE THREAD

**Issue by tirengarfio** [hluk/CopyQ#1217]
The icon is in on the top left corner.

I expected on the top right corner.

![Screenshot from 2019-09-16 10:03:22](https://user-images.githubusercontent.com/54537264/64945784-3f7f8c00-d869-11e9-91ab-39cdf49233ca.png)

Ubuntu 14.04 
CopyQ Clipboard Manager v3.9.2
Qt: 5.2.1
Compiler: GCC

**Comment by hluk** [comment]
That's very old bug in some external component CopyQ uses. I thought it was already fixed. Anyway, CopyQ itself doesn't have any control over where the icon is displayed.

See also: https://stackoverflow.com/questions/24732652/qsystemtrayicon-not-showing-in-notification-area-on-ubuntu-14-04
