### ISSUE TITLE
Nonstop crashing when trying to search.

### ISSUE THREAD

**Issue by GUILKEYDILLIONC** [hluk/CopyQ#1218]
Whenever I open the window and type a query, it types the first 1 or 2 letters and then freezes, and then ultimately crashes. It's been like this since 2 years ago.

**Comment by hluk** [comment]
What's the CopyQ version, OS and desktop environment? Anything in the log?

**Comment by scottkosty** [comment]
@GUILKEYDILLIONC just wanted to make sure you saw the questions. Can you see if you can reproduce with the CopyQ version just released a couple of days ago, 3.9.3?
