### ISSUE TITLE
Is it typo?

### ISSUE THREAD

**Issue by libreajans** [hluk/CopyQ#1219]
I came across this sentence on the Weblete. 

> Note: This is not **be** supported on all systems.

As Haaninjo said before:

> Here is one word too many, the "be" can be removed. "This is not supported..."

https://hosted.weblate.org/translate/copyq/master/tr/?type=comments&offset=3

**Comment by hluk** [comment]
Hmm, the text was already removed from UI. It shouldn't show up in Weblate at all - it's marked as "vanished" in the source `xml` files.

Let me try updating the translation sources.

**Comment by hluk** [comment]
Looks like it's related to this: https://github.com/WeblateOrg/weblate/issues/2821

Sorry, if you had to translate some old texts, I didn't realize they still show up in Weblate.

I've removed the old texts and changed the update script so it removes them automatically in future.

Thanks for pointing this out! Feel free to let me know if you find out other inconsistencies.
