### ISSUE TITLE
How to increase font size of main window?

### ISSUE THREAD

**Issue by kayanco1** [hluk/CopyQ#1224]
Hi,

How can I increase the front/text size in the main window please?
See screenshot please.

![2019-10-01 11_07_27](https://user-images.githubusercontent.com/45769255/65979992-e7857f80-e43b-11e9-89fa-ca560b16645f.jpg)

Thanks.

**Comment by hluk** [comment]
You can change font in Appearance configuration tab. But for it to work in the menu you also need to enable "Set colors for tabs, tool bar and menus" checkbox in the tab.

**Comment by kayanco1** [comment]
> 
> 
> You can change font in Appearance configuration tab. But for it to work in the menu you also need to enable "Set colors for tabs, tool bar and menus" checkbox in the tab.

Hi, I did that (I enabled "Set colors for tabs, tool bar and menus" checkbox), but it doesn't affect the menu font. I tried all these:
https://i.imgur.com/rKgOExi.jpg
![2019-10-02 21_51_00](https://user-images.githubusercontent.com/45769255/66096003-23fdcc00-e55f-11e9-8d30-cf49c244bcb8.jpg)

**Comment by hluk** [comment]
Looks like the solution is similar to [this one](https://github.com/hluk/CopyQ/issues/1225#issuecomment-537565096), except you need to add `font-size` to `menu_bar_css`. E.g.:

```ini
menu_bar_css="
    ;font-size: 10pt
    ;background: ${bg}
    ;color: ${fg + #444}"
```

**Comment by pato7** [comment]
How can I increase the font size in search input?

![image](https://user-images.githubusercontent.com/35065725/73591336-a8e8fa00-44ed-11ea-9043-af9fb8f47c24.png)

**Comment by hluk** [comment]
> How can I increase the font size in search input?

Same as my previous comment but modify `search_bar`, e.g.:

```ini
search_bar="
    ;font-size: 14pt
    ;background: ${edit_bg}
    ;color: ${edit_fg}
    ;border: 1px solid ${alt_bg}
    ;margin: 2px"
```

**Comment by waseemv** [comment]
Hi hluk,

How to increase the font for menu text (highlighted in red). Thank you :)

![gAUPS6a](https://user-images.githubusercontent.com/45769255/201502756-1676d791-a07a-4045-9642-cd4aeff23b48.jpg)

**Comment by GBT55** [comment]
> ```ini
> ;font-size: 14pt
> ```

Does not work for me
