### ISSUE TITLE
How to change Tab bar font size ?

### ISSUE THREAD

**Issue by HaxorGaruda** [hluk/CopyQ#1225]
**Is your feature request related to a problem? Please describe.**
Font size on tab bar copyq it too big..  
**Describe the solution you'd like**
need to change font as normaly

![toobig](https://user-images.githubusercontent.com/5996055/66012725-6d640200-e4f2-11e9-98c9-2b6dd42c9582.png)

**Comment by hluk** [comment]
You'll have to edit the theme file manually:
1. Open app configuration (Ctrl+P),
2. go to Appearance tab,
3. enable checkbox "Set colors for tabs, tool bar and menus" (from your screenshot I assume it's already enabled),
4. click "Edit Theme" button,
5. set `font-size` for `tab_bar_css`, e.g.:

```ini
tab_bar_css="
    ;font-size: 7pt
    ;background: ${bg - #222}"
```

6. save file and apply configuration.

---

![image](https://user-images.githubusercontent.com/38054/66061151-28b28800-e53f-11e9-9d06-2011e3da4ad5.png)

**Comment by HaxorGaruda** [comment]
Thanks..   you are my hero.. hehe..
