### ISSUE TITLE
Dedicated shortcuts for tabs

### ISSUE THREAD

**Issue by Senepiaur** [hluk/CopyQ#1229]
Currently pressing ctrl+c copies stuff to tab1.
Is there a way to create shortcut to copy stuff to tab2.

So basically to automatically organize all related snippets in same location.

**Comment by hluk** [comment]
A simple way (but may not work in all apps) is to defined global shortcut to send Ctrl+C and then store the clipboard text in the specified tab. Command below stores the copied text in "work" tab ([here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)).

```ini
[Command]
Command="
    copyq:
    tab('work')
    try {
        copy()
        add(clipboard())
    } catch (e) {
        popup('Failed to Copy')
    }"
GlobalShortcut=ctrl+shift+c
Icon=\xf0c5
IsGlobalShortcut=true
Name=Copy Text to work Tab
```

Another way is to have a global shortcut that configures tab currently used for storing clipboard.

Here is a command with multiple shortcuts assigned. It will set clipboard tab depending on the digit key in the shortcut (e.g. Meta+Alt+1 sets the first tab).

```ini
[Command]
Command="
    copyq:
    var shortcut = str(data(mimeShortcut))
    var shortcutKey = shortcut.split('+').slice(-1)[0]
    var tabIndex = shortcutKey - 1
    var tabName = tab()[tabIndex]
    popup('Setting Clipboard Tab', tabName)
    config('clipboard_tab', tabName)"
GlobalShortcut=meta+alt+1, meta+alt+2, meta+alt+3, meta+alt+4, meta+alt+5
Icon=\xf15b
IsGlobalShortcut=true
Name=Set Clipboard Tab
```

I use similar command to switch current clipboard tab but it works automatically -- setting different tab for clipboard depending on content in some external configuration file.

**Comment by Senepiaur** [comment]
Seems to have solved the problems, thanks big time!
