### ISSUE TITLE
Bug Need Cmd + V to paste the item

### ISSUE THREAD

**Issue by elcolie** [hluk/CopyQ#1230]
**Describe the bug**
OSX 10.15 need `Cmd + v` to paste after select the item from CopyQ window

**To Reproduce**
1. Upgrade from OSX Mojave to Catalina 10.15
2. Install `CopyQ`
3. Select the item in the clipboard
4. Select the item

**Expected behavior**
Item will be pasted according to the focused windows or cursor

**Screenshots**
![image](https://user-images.githubusercontent.com/18206728/66711581-bcdee380-edb8-11e9-96df-5e4a0ea24f37.png)

**Version, OS and Environment**
 - Application Version `3.9.2`
 - OSX 10.15

**Additional context**
It just happen in  the latest OSX version

**Comment by elcolie** [comment]
Unable to reproduce after reboot!

**Comment by hluk** [comment]
I have been expecting some issues with Catalina. Hope everything goes well in the end.
