### ISSUE TITLE
CopyQ ignore a bit wide screenshot image.

### ISSUE THREAD

**Issue by zw963** [hluk/CopyQ#1232]
**Describe the bug**
When i use a snapshot app (deepin-screenshot) with CopyQ, it not worked always well
when current screenshot is a little wide, a little bigger.

Following is an not working screenshot image, when copy this image content, we never
see  image preview when open copyq, and there is no way to repaste this image when need.

**Expected behavior**
if show preview is not possible, maybe we can show a default preview, that way, we can paste this image when need.

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Application Version:  3.9.2-1
 - OS:  Arch
 - Desktop environment, window manager: budgie-desktop(Gnome3)

**Additional context**
Following is a not working screenshot file
![DeepinScreenshot_select-area_20191013212531.png](http://zw963.github.io/images/20984380721627.png)

Thank you.

**Comment by hluk** [comment]
For me the "Copy to clipboard" action in `deepin-screenshot` doesn't work at all. After clicking the clipboard button, the clipboard is empty. Looks like the `deepin-screenshot` itself is broken.

Can you exit CopyQ, take a new screenshot, and try pasting it from clipboard?

**Comment by zw963** [comment]
> Can you exit CopyQ, take a new screenshot, and try pasting it from clipboard?

Sorry, i don't know how to "pasting it from clipboard", but, for current issue,
deepin-screenshot is working with a more NOT wider image, e.g.

![image](https://user-images.githubusercontent.com/549126/66799485-dd877480-ef43-11e9-870f-df5d784c8614.png)

**Comment by hluk** [comment]
So wider screenshots from deepin-screenshot don't show up in CopyQ at all? Is anything in CopyQ logs (F12 shortcut from main window)?

**Comment by zw963** [comment]
![image](https://user-images.githubusercontent.com/549126/66856263-6e4b6800-efb7-11e9-8a3b-fce4dc5dff9a.png)

Please check, thank you.

BTW:  i guess one image not copied into copyQ only if this image is large enough, for the last one,
is a 424 KB image.

![image](https://user-images.githubusercontent.com/549126/66856489-e44fcf00-efb7-11e9-94e9-359eddcbeda4.png)

**Comment by hluk** [comment]
That is a bug with Qt framework or rather inability to fetch bigger clipboard data in X11 with Qt -- it will give up after 5 seconds.

But I thought this is only problem with data that are larger size (more than 50 MiB or so). Looks like the png screenshot in clipboard to be much smaller. Maybe CopyQ or the clipboard provider (deepin-screenshot) is slow for some reason.

Can you try following commands after copying the screenshot?

```bash
# list data formats in clipboard
copyq clipboard "?"

# get size of the PNG screenshot in clipboard
time copyq clipboard image/png > /tmp/screenshot.png
ls -lh /tmp/screenshot.png
identify /tmp/screenshot.png
rm -f /tmp/screenshot.png
```

**Comment by zw963** [comment]
> # list data formats in clipboard
> copyq clipboard "?"

Sometimes get following content:
```
image/xpm
TARGETS
TIMESTAMP
application/x-qt-image
```
 in some cases, output nothing, i found out it seem like not relative to size, 
just missing clipboard randomly.

Following is when output image/xpm result:

```
╭─ 00:00  zw963 ⮀ ~/Airhost/airhost_ror ⮀ ⭠ (b6dccab67) production $%  ➦ ruby-2.6.1@airhost_ror 
 ╰─ $ copyq clipboard "?"
image/xpm
TARGETS
TIMESTAMP
application/x-qt-image

 ╭─ 00:00  zw963 ⮀ ~/Airhost/airhost_ror ⮀ ⭠ (b6dccab67) production $%  ➦ ruby-2.6.1@airhost_ror 
 ╰─ $ time copyq clipboard image/xpm > /tmp/screenshot.png

real    0m0.121s
user    0m0.010s
sys     0m0.010s

 ╭─ 00:00  zw963 ⮀ ~/Airhost/airhost_ror ⮀ ⭠ (b6dccab67) production $%  ➦ ruby-2.6.1@airhost_ror 
 ╰─ $ ls -alh /tmp/screenshot.png 
-rw-r--r-- 1 zw963 zw963 0 2019-10-18 00:00 /tmp/screenshot.png

 ╭─ 00:00  zw963 ⮀ ~/Airhost/airhost_ror ⮀ ⭠ (b6dccab67) production $%  ➦ ruby-2.6.1@airhost_ror 
 ╰─ $ identify /tmp/screenshot.png 
identify: improper image header `/tmp/screenshot.png' @ error/png.c/ReadPNGImage/4294.
```

i try both image/xpm and image/png, all get a 0 type file.

**Comment by hluk** [comment]
Looks like deepin-screenshot provides only `image/xpm` in clipboard, which I believe doesn't support compression (so it could be much bigger than PNG). CopyQ tries to retrieve it and convert it as PNG. It fails retrieving the data, most probably because it's too large, but it's strange that it exits so fast while retrieving.

I am guessing the bug is in Qt framework (used by CopyQ) or deepin-screenshot.

You may be able to reproduce it with following Python script which uses just Qt to get clipboard data. You need to have PyQt5 installed.

```python
#!/usr/bin/env python3
import sys

from PyQt5 import QtCore
from PyQt5 import QtGui
from PyQt5 import QtWidgets

app = QtWidgets.QApplication(sys.argv)


def update_format_list(combo):
    combo.clear()
    data = app.clipboard().mimeData()
    for mime in data.formats():
        combo.addItem(mime)


def get_format(combo, label):
    mime = combo.currentText()
    data = app.clipboard().mimeData().data(mime)
    if mime.startswith('image'):
        image = QtGui.QImage.fromData(data)
        pixmap = QtGui.QPixmap.fromImage(image)
        label.setPixmap(pixmap)
    else:
        text = data.data().decode()
        label.setText(text)


combo = QtWidgets.QComboBox()
update_format_list(combo)

label = QtWidgets.QLabel()
label.setAlignment(QtCore.Qt.AlignCenter)

get_button = QtWidgets.QPushButton('&Get')
get_button.clicked.connect(lambda: get_format(combo, label))

update_button = QtWidgets.QPushButton('&Update')
update_button.clicked.connect(lambda: update_format_list(combo))

hlayout = QtWidgets.QHBoxLayout()
hlayout.addWidget(combo, stretch=1)
hlayout.addWidget(get_button)
hlayout.addWidget(update_button)

vlayout = QtWidgets.QVBoxLayout()
vlayout.addLayout(hlayout)
vlayout.addWidget(label)

window = QtWidgets.QWidget()
window.setLayout(vlayout)

window.show()
app.exec_()
```

**Comment by zw963** [comment]
Hi, i recent switch to use flameshot, it working quite well with copyQ, so, i think this is not a copyq issue, thank you very much!
