### ISSUE TITLE
CopyQ crashes editing clips when set to sync with Google drive folder

### ISSUE THREAD

**Issue by richlux** [hluk/CopyQ#1235]
**Describe the bug**
I have my tabs set to sync with a Google drive folder, but when I try to Edit a clip or execute a command such as removing the HTML, CopyQ crashes.

**To Reproduce**
Steps to reproduce the behavior with "Edit":
1. Setup syncing with a shared folder (e.g. Google Drive)
2. Right-mouse click over a clip and select "Edit" (F2) and CopyQ crashes

Steps to reproduce the behavior with removing HTML:
1. Add a command called "Remove HTML":
copyq:
removeData(mimeHtml)
2. Right-mouse click over a clip and select "Remove HTML" and CopyQ crashes

**Expected behavior**
CopyQ should allow me to edit the clip or remove HTML

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Version 3.9.2
 - Windows 10

**Comment by hluk** [comment]
> I have my tabs set to sync with a Google drive folder

How does that work? Do you use some application to map google drive to a virtual disk?

I'm not using gdrive (and currently not even Windows), but I tried modifying (and also removing) a synced file just before (and while) editing it and CopyQ is stable.

Can you also check if CopyQ plugins are correctly installed? The plugin directory in your installation should list only following files:

```
libitemencrypted.dll
libitemfakevim.dll
libitemimage.dll 
libitemnotes.dll 
libitempinned.dll
libitemsync.dll
libitemtags.dll
libitemtext.dll
```

**Comment by richlux** [comment]
Using "Google Backup and Sync", a Google Drive mapping is placed in Windows.  I also just tested with Dropbox and CopyQ crashes with that also.  I can see that files for each clip are being created in my Dropbox folder, so it's syncing correctly, but when I try to Edit an entry, CopyQ crashes.  I'm using Windows 10 version 1809.

I checked and those files are the exact ones I have in my plugin folder.

Rich

**Comment by richlux** [comment]
I switched to using pCloud to see if that would help.  Syncing works, but it still crashes when I Edit the clips.  I can duplicate this on each computer that is running CopyQ and synching.  They are all running windows 10.  Is there any debugging I can do to see what is causing this?

Rich

**Comment by hluk** [comment]
You can try starting CopyQ with `COPYQ_LOG_LEVEL` environment variable set to `trace` and see what is the last thing in the log.

```
COPYQ_LOG_LEVEL=trace copyq
copyq logs
```

You can also try one of the new builds, they contain debug symbols, but I don't know how Windows can handle them.

- [MinGW build](https://ci.appveyor.com/project/hluk/copyq/build/job/8fego4o09j3j4wlo/artifacts)
- [Visual Studio build](https://ci.appveyor.com/project/hluk/copyq/build/job/4f4sxaoiayuoxw29/artifacts)

**Comment by richlux** [comment]
I set the environment variable, but I can't figure out where the log files are stored.  running "copyq logs" doesn't return anything.

Rich

**Comment by richlux** [comment]
Unfortunately, there doesn't appear to be anything unusual in the logs.  Just stuff like this:

DEBUG [2019-10-31 09:51:14.148] <monitorClipboard-62540>: cls: "Qt5QWindowIcon"
DEBUG [2019-10-31 09:51:14.180] <Server-97504>: cls: "Qt5QWindowIcon"
DEBUG [2019-10-31 09:51:14.242] <Server-97504>: cls: "Qt5QWindowIcon"
DEBUG [2019-10-31 09:51:14.307] <Server-97504>: cls: "Qt5QWindowIcon"
DEBUG [2019-10-31 09:51:14.352] <monitorClipboard-62540>: cls: "Qt5QWindowIcon"
DEBUG [2019-10-31 09:51:14.367] <Server-97504>: cls: "Qt5QWindowIcon"

Rich

**Comment by richlux** [comment]
Lukas,

Is there anything you recommend that I try or can you duplicate the issue?  I've tried it on multiple different computers, so I don't think it's specific to my environment.

Rich

**Comment by hluk** [comment]
I cannot reproduce this on Window 10 (Pro v1709).

Can you try disabling any commands in Command dialog (F6 shortcut)? Maybe one of them is causing this.

**Comment by richlux** [comment]
I just narrowed down the issue.  If I use the Toolbar to execute a command (Edit, Copy to Clipboard, Remove HTML, etc.) it WORKS, but if I use a right-mouse click on an item to do the same thing, it Crashes.  It also Crashes if I click a command under the "Items" menu.  Hopefully this will help you diagnose the issue.

Rich

**Comment by hluk** [comment]
I've been trying to get CopyQ print some crash reports (branch `stacktrace`) but I fail to get it working on Windows.

**Comment by richlux** [comment]
I wish I could help :-(   Hopefully you'll get it working, so you can debug this issue.

Thanks for all your work,
Rich

**Comment by hluk** [comment]
I think I have a fix for the crash: https://github.com/hluk/CopyQ/pull/1274

Looks like the crash is caused by clearing context/Item menu for synced tab after selecting an action.

**Comment by richlux** [comment]
Awesome. I'll try it out as soon as it's available.

Rich

**Comment by hluk** [comment]
Is this still an issue? Is this related to #1311?

**Comment by richlux** [comment]
Sorry, it's no longer an issue. I will close the issue, but it's not related to 1311. CopyQ still crashes randomly a number of times throughout the day.  I will add more info to that issue.

Thanks, 
Rich
