### ISSUE TITLE
Snippets Commands: Multiple placeholders doesn't work

### ISSUE THREAD

**Issue by thenitai** [hluk/CopyQ#1237]
**Describe the bug**

I took the latest snippets.ini and imported it. All is working, except using several placeholders.

According to the conversation over at https://github.com/hluk/CopyQ/issues/845 I should be able to use something like:

${Weekday} ${Day}th ${Month}

While the popup window accepts the value, I receive an error message right after with:

![image](https://user-images.githubusercontent.com/372121/67046456-3ac72580-f0fe-11e9-99d2-29b1aa97426b.png)

Adding just ${Weekday} works.

I've already removed the "snippets" tab and re-added it. Tried it with copy & paste and with importing from the .ini file. Same result.

**Version, OS and Environment**
CopyQ Clipboard Manager v3.9.2
Qt: 5.12.2
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Pop!_OS 19.04

Any help appreciated. Thank you

**Comment by hluk** [comment]
Fixed: https://github.com/hluk/copyq-commands/commit/b3c7352685967c1265dac29ab3b21f0cd6bb9a71

Thanks for the report!

**Comment by thenitai** [comment]
Thank you for fixing it so quickly. Much appreciated.
