### ISSUE TITLE
No history after upgrade to Ubuntu 19.10

### ISSUE THREAD

**Issue by lbudzynowski** [hluk/CopyQ#1240]
**Describe the bug**
Empty history window.

**To Reproduce**
Click Show/hide from menu gives empty window.

![Screenshot from 2019-10-23 15-16-01](https://user-images.githubusercontent.com/37274983/67396550-165cc480-f5a8-11e9-93f9-00566a414cb1.png)

**Version, OS and Environment**
CopyQ Clipboard Manager v3.9.1
Qt: 5.12.4
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Ubuntu 19.10
Gnome

Please help. All my copy history should be there!!!

**Comment by hluk** [comment]
Can you please update to v3.9.2? There was some bug which causes CopyQ to refuse load the tab if there is an empty item.

> Please help. All my copy history should be there!!!

CopyQ tries hard not to lose any data, but definitely consider backing up the data.

You can use a command that does backup after exit: https://copyq.readthedocs.io/en/latest/backup.html

See also: https://copyq.readthedocs.io/en/latest/backup.html

**Comment by lbudzynowski** [comment]
Thought so. You mean using binary package because there is no ubuntu 19.10 version?

**Comment by hluk** [comment]
You can use PPA if the package is not available in Ubuntu repositories yet.

I've just updated the PPA for Ubuntu 19.10: https://launchpad.net/~hluk/+archive/ubuntu/copyq

**Comment by lbudzynowski** [comment]
Thank you very much! That did the trick!!!
