### ISSUE TITLE
Note [2019-10-26 21:58:41.496] <Server-8116>: No plugins loaded

### ISSUE THREAD

**Issue by evandrocoan** [hluk/CopyQ#1242]
I do not understand this. When I look into the log (F12) key, I see this:
```
Warning [2019-10-22 00:50:36.472] <monitorClipboard-20808>: ELAPSED 850 ms acessing "text/plain"
Warning [2019-10-22 00:50:36.669] <monitorClipboard-20808>: ELAPSED 1070 ms acessing "UTF8:text/plain"
Warning [2019-10-22 22:38:26.185] <monitorClipboard-20808>: ELAPSED 724 ms acessing "text/plain"
Warning [2019-10-22 22:38:26.200] <monitorClipboard-20808>: ELAPSED 738 ms acessing "UTF8:text/plain"
Warning [2019-10-25 02:50:06.149] <monitorClipboard-20808>: ELAPSED 646 ms acessing "text/plain"
Warning [2019-10-25 02:50:06.163] <monitorClipboard-20808>: ELAPSED 660 ms acessing "UTF8:text/plain"
Note [2019-10-26 21:58:41.496] <Server-8116>: No plugins loaded
```
![image](https://user-images.githubusercontent.com/5332158/67627984-dfeba780-f83c-11e9-8a92-9873009f0939.png)

This message `No plugins loaded` shows up even when I keep all plugins on the `plugins` directory. What it means? As far as I can see my plugins are working:

![image](https://user-images.githubusercontent.com/5332158/67628013-4bce1000-f83d-11e9-8276-e0dc4affc393.png)

![image](https://user-images.githubusercontent.com/5332158/67628016-5e484980-f83d-11e9-94c6-d83275fe9779.png)

**Comment by hluk** [comment]
The dialog shows log messages from previous runs too -- looks like this message doesn't come the current CopyQ run.

**Comment by evandrocoan** [comment]
Thanks! I should have paid attention on the timestamps.
