### ISSUE TITLE
Paste entry from history to current window on MacOS 10.15 Catallina not working

### ISSUE THREAD

**Issue by gflex** [hluk/CopyQ#1245]
**Describe the bug**
Pasting selected record from history in current application window is not working.

**To Reproduce**
CopyQ is with enabled cipboard sharing. copy text to clipboard. Try to retrieve object and paste to another program window (whichever it is). Select from history and either press enter or double click. Nothing happens. Text is not pasted.
Though, selected Item is added to clipboard. So consecutive "Command-V" pastes the selected entry.

**Expected behavior**

**Screenshots**
Selected options in History tab:
<img width="466" alt="image" src="https://user-images.githubusercontent.com/11692649/67984967-887c7b80-fc30-11e9-9f85-47fb15ee2441.png">

**Version, OS and Environment**
CopyQ version is 3.9.2 installed through brew cask
OS: MacOS Catalina 10.15.1

**Comment by hluk** [comment]
Please check if [FAQ](https://copyq.readthedocs.io/en/latest/faq.html#why-can-i-no-longer-paste-from-the-application-on-macos) or #1030 help.

**Comment by gflex** [comment]
Thanks for the reference! Actually that helped me to work the issue around.
1. brew cask remove copyq
2. reboot machine
3. brew cask install
4. start copyq.
5. Accept to run the app from "unknown source"
6. when asked , do allow CopyQ access to Accessibility in "security and privacy"

My case was similar to https://github.com/hluk/CopyQ/issues/1030#issuecomment-496096481 
Migrated from old computer to the current. So I suppose something happened during migration and the proper rights were not assigned.

Obviously not CopyQ but mac issue (whoorray!)
Thanks a lot and sorry for bothering :)

**Comment by ajorpheus** [comment]
For me, with the same issue, I had to remove and add CopyQ again in Accessibility and the auto-paste functionality was restored.
(I began having this issue after upgrading to Catalina)

**Comment by gibfahn** [comment]
I believe that all you need to do to fix the issue is to untick and retick CopyQ in the Accessibility preferences, see https://github.com/hluk/CopyQ/issues/1030#issuecomment-633205588.

**Comment by marcosdemelo** [comment]
> For me, with the same issue, I had to remove and add CopyQ again in Accessibility and the auto-paste functionality was restored.
> (I began having this issue after upgrading to Catalina)

Resolve for me. Thanks!
