### ISSUE TITLE
Copy/Move Lines

### ISSUE THREAD

**Issue by darwin4ever** [hluk/CopyQ#1246]
A Clipboard line can be dragged to another tab.

1) When a line is dragged, a "->" is shown while dragging which lets assume a "move" will be done, but next to a new line in the destination tab, the original line is NOT removed

2) When a line is [CTRL]-dragged, a "+" is shown while dragging which lets assume a "add" will be done. Actually it results in exactly as 1)

**Comment by hluk** [comment]
> but next to a new line in the destination tab

I don't understand this part.

If I understand correctly, the problem is that if you drag an item from a tab to a different tab without holding Ctrl (or any other modifier), the dragged item is not removed. Is that right?

Can you post which version of CopyQ are you using, what is your OS and ideally steps to reproduce this?

**Comment by darwin4ever** [comment]
Sorry, my comment got messed up. And for some reason I can't edit it.

So correctly it should have been :
1. When a line is dragged, a "->" is shown while dragging which lets assume a "move" will be done to the destination tab. Actually a new line in the destination tab is added, the original line is NOT removed

So yes : the dragged item is not removed

I'm using v3.9.2 on Win10 32-bit.

Reproducing :
1. create TestTab1
2. create entry in TestTab1
3. create TestTab2
4. drag entry from TestTab1 to TestTab2

**Comment by hluk** [comment]
I currently cannot test it on Windows, but I don't see any "->" when dragging items (though this probably just depends on platform).

Is there any chance the item is pinned (it should have a gray bar on the right side)?

Is anything in the logs (F12 shortcut)?

**Comment by darwin4ever** [comment]
The "->" and "+" are shown on the left side of the dragging-box. No way to include it in a screenshot.

The item is NOT pinned and there is nothing in the log after dragging the line is completed

**Comment by trysten** [comment]
OP is confusing. I've attached an image of the arrow (which doesn't seem to be relevant). When dragging, the item is copied to the correct tab and remains on the original tab. My desired behavior is to *move* the item to the destination tab such that it is no longer on the original tab. I haven't found any way to do this by dragging with or without modifiers and resorted to creating custom commands to move items to tabs. I recall that previous versions behaved differently for me on Windows 10.

It doesn't seem like this is the intended behavior. Either way, a checkbox settings to set move/copy in preferences might make sense. I would look into patching after some direction from @hluk.
![image](https://user-images.githubusercontent.com/4760903/215684774-2bb6aff4-3496-4ba0-804e-aeadf3da6938.png)

**Comment by hluk** [comment]
Can you test with the latest version and provide steps to reproduce?

**Comment by trysten** [comment]
I've isolated the bug. Items are copied (not moved) when option "Tab Tree" is unchecked. When "Tab Tree" is checked items are moved (not copied). Occurs in version 6.4.0 on Windows and Debian. I think *move* behavior should be the default. You should be able to reproduce by unchecking "Tab Tree" then drag-and-dropping items to a different tab.

Thank you for your time and effort.

**Comment by hluk** [comment]
@trysten Thanks for finding the cause!

Pull request #2261 fixes the issue.
