### ISSUE TITLE
Paste plain text: global shortcuts not working in KDE?

### ISSUE THREAD

**Issue by MountainX** [hluk/CopyQ#1248]
CopyQ looks fantastic! Thanks for working on this application. I just installed it and want to learn how to use it. I cannot get global shortcuts to work. It's probably user error.

I'm running Copy Q 3.9.2 on Arch Linux KDE (plasmashell 5.16.5).

My first goal is to use CTRL-J as a global shortcut to paste as plain text. I plan to use the "Paste clipboard as plain text" command. I followed the steps here: https://copyq.readthedocs.io/en/latest/faq.html#how-to-paste-as-plain-text

I can't get that to work. To troubleshoot, I tried the "Paste Current Date and Time" with global shortcut Win+Alt+T as mentioned here: 
https://github.com/hluk/copyq-commands/tree/master/Global#quickly-show-current-clipboard-content

Win+Alt+T doesn't do anything except emit a "t" on my system. So it appears that global shortcuts are not working for me. Therefore, to resolve this, I believe there are two steps:

1. get global shortcuts working
2. get the global shortcut for "Paste clipboard as plain text" working

**Expected behavior**
I would like to have CTRL-j paste the clipboard as plain text into the currently focused window at the text cursor position. It should work just like CTRL-v but isntead of pasting formatted clipboard contents, it should paste plain text. It should work even when the CopyQ main window is hidden or minimized (and not focused).

**Screenshots**

![Screenshot_20191103_153250](https://user-images.githubusercontent.com/48405/68091655-344fe200-fe50-11e9-8b0d-c59a97ca72a6.png)

**Comment by hluk** [comment]
If you use **Wayland** session instead of X11, you'll have to define the global shortcuts in KDE configuration. I don't think there is a simple way to fix this currently (compositor handles global shortcuts in Wayland).

I could make it easier to call the global shortcut command using scripting or allow registering shortcuts using custom command.

**Comment by opensource-assist** [comment]
@hluk I use copyq on a Plasma Wayland session and I have the same issue with shortcuts.

**Comment by hluk** [comment]
Implementing global shortcuts is part of #27 but Wayland by itself doesn't support this (probably because of security concerns to avoid key loggers).
