### ISSUE TITLE
"execvp: No such file or directory" error on trying to edit with editor

### ISSUE THREAD

**Issue by RafaelLinux** [hluk/CopyQ#1250]
**Describe the bug**
When trying to "Edit with editor", CopyQ shows a notification like this
"Editor command: execvp: No such file or directory"

**To Reproduce**
1. Select an element
2. Press "Ctrl + E"
4. Plasma shows a notification "Editor command: execvp: No such file or directory"

**Expected behavior**
To edit with Kate (or other editor)

**Screenshots**
![image](https://user-images.githubusercontent.com/13048959/68478211-ab5def80-022f-11ea-89ad-4c167073bfc1.png)

**Version, OS and Environment**
(Get details from `copyq version` --> I add AWESOME idea. I wish all developers make this info collection so easy)
CopyQ Clipboard Manager v3.9.2
Qt: 5.9.7
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: openSUSE Leap 15.0

**Comment by hluk** [comment]
Looks like CopyQ cannot find the executable for the editor command.

What's your editor command (i.e. output of `copyq config editor`)?

**Comment by RafaelLinux** [comment]
Thank you for your quick reply!!! 
The result of the command is `gedit --standalone -- %1`

So I understand the RPM was compiled for Gnome desktops, not Plasma desktops (Plasma).

I have another question, cause copyq is not in official OpenSUSE repositories ... under what kind of license is copyQ distributed?

**Comment by hluk** [comment]
> So I understand the RPM was compiled for Gnome desktops, not Plasma desktops (Plasma).

You can change the command in configuration -- "External editor command" option under History configuration tab or command line `copyq config editor <EDITOR_COMMAND>`.

To use Kate editor, run:

```
copyq config editor kate
```

AFAIK `gedit` is just the most common user-friendly editor installed on most Linux distributions. Well, most distros are gnome-based these days ... but I also still prefer Plasma/KDE.

> I have another question, cause copyq is not in official OpenSUSE repositories ... under what kind of license is copyQ distributed?

CopyQ license is [here](https://github.com/hluk/CopyQ/blob/master/LICENSE).

BTW, you can also install and keep the app up-to-date using [flatpak](https://en.opensuse.org/Flatpak).

```
flatpak install flathub com.github.hluk.copyq
flatpak run com.github.hluk.copyq
```

**Comment by RafaelLinux** [comment]
You answered all my doubts. I change gedit for kate as editor. I think the info about license should be in the program too, in "About" or similar IMHO  ;)
Thank you for suggest using flatpak, but really I adopted AppImage as my preferred way to have programs that are not available in main OpenSUSE repositories, cause I can control much better what and where files of each program are stored.
Great job!!!

**Comment by dglent** [comment]
or 'xdg-open %1' ?
