### ISSUE TITLE
Let intranet users share clipboard as notes

### ISSUE THREAD

**Issue by RafaelLinux** [hluk/CopyQ#1251]
**Is your feature request related to a problem? Please describe.**
I usually use Knotes to have notes with info about a lot of things, mainly programming code, links, steps to configure, phones, etc. Knotes is a great program, and compatible with a very old Windows note program called ATnotes (still working in Windows, fortunately). The fact is that way Linux (with Knotes) and Windows (with ATNotes) users can send each other notes, cause both programs uses same port.

However, Knotes have serious bugs, even losing temporary notes, and developers have not a real feedback with users about bugs or feature request, so I'm looking for a multiOS application to improve productivity with notes. For example, is a headache to send notes to other users cause Knotes have not a way to associate IPs to users, so I need always to see the user IP before send any note. At this point, as I begin to use CopyQ and is really very powerful and useful, being a possible "Note taking" replace for KNotes, cause when we send notes, we need to "copy" to clipboard the note, click on KNotes, open a new note, paste the clipboard content, select the user and click  "Send". So this is my feature request  suggestion...

**Describe the solution you'd like**
Could be possible for CopyQ developers to consider work in intranet using port 24837 to receive/send notes in the same simple way that Knotes, but even simplier?

**Describe alternatives you've considered**
- User select an element from CopyQ
- Click on a tab called "Send" element
- Appears a list (empty first time) of possible users. In this list user could add/remote a list with only two fields: Username and IP
- User select the user(s) and click "Accept" 

Done
Obviosly, this could be better if once received the element, it show who and when note was sent. But I know it's too much to ask for  ;)

I know there are a little percentage of users (corporative or teams intranets) interested in this feature, but I think that if you implement that functionality, will be adopted by more people.

Thank you and excellent job!!!

**Comment by hluk** [comment]
There are a few other issues/feature-requests about synchronization.

I don't plan to add this functionality to CopyQ. You will have to use another app to handle synchronization on multiple machines. But you can use CopyQ to synchronize a tab to a shared folder on disk: https://copyq.readthedocs.io/en/latest/synchronize.html

**Comment by RafaelLinux** [comment]
Syncrhonization is a very useful, but unfortunately doesn't avoid to still use Knotes/ATnotes to send info. Anyway, CopyQ is really a "must have" for any one that need a tool for productivity.
