### ISSUE TITLE
CopyQ main window showing up everytime I copy something.

### ISSUE THREAD

**Issue by aureri** [hluk/CopyQ#1252]
Everytime I copy something, copyq main window shows up. Is it an intended feature? If it is then is there a setting to disable it?

CopyQ on Linux Mint 19.2 Cinnamon

**Comment by hluk** [comment]
No, main window shouldn't show up when copying to clipboard.

Maybe you have an automatic command that does that. Can you share your `~/.config/copyq/copyq-commands.ini`?

**Comment by aureri** [comment]
> No, main window shouldn't show up when copying to clipboard.
> 
> Maybe you have an automatic command that does that. Can you share your `~/.config/copyq/copyq-commands.ini`?

You're right. I unchecked the "Display" action of "Show Window" on Global Shortcuts and it's not popping up anymore.



![](https://i.imgur.com/1uSFERR.png)
