### ISSUE TITLE
Qt5Script not found.

### ISSUE THREAD

**Issue by Achaean** [hluk/CopyQ#1256]
Trying to build it (at a Debian oldstable based distribution), cmake aborted with the message:
```
CMake Error at src/CMakeLists.txt:104 (find_package):
By not providing "FindQt5Script.cmake" in CMAKE_MODULE_PATH this project
has asked CMake to find a package configuration file provided by
"Qt5Script", but CMake did not find one.
```
although Qt5Script (and its headers) are already installed.

**Comment by hluk** [comment]
Package `qtscript5-dev` must be installed.

Also, check if you don't override `CMAKE_MODULE_PATH` (cmake arguments or environment variable).

(BTW, I just released new version of CopyQ without any issues on Debian based distros.)

**Comment by Achaean** [comment]
I tried with the last version and qtscript5-dev is already installed.
I launched cmake with the default arguments (cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local).

**Comment by hluk** [comment]
What's the version of the Qt libraries you have installed?

What's the version of CopyQ you're trying to build?

**Comment by Achaean** [comment]
CopyQ v.3.9.3.
Libqt5scripttools5 v.5.7.1~20161021+dfsg-2.

**Comment by hluk** [comment]
Can you double-check version of `qtscript5-dev` and verify following files are installed?

```
/usr/lib/x86_64-linux-gnu/cmake/Qt5Script/Qt5ScriptConfig.cmake
/usr/lib/x86_64-linux-gnu/cmake/Qt5Script/Qt5ScriptConfigVersion.cmake
```

You can find log file from installing packages and running cmake for the v3.9.3 build for Debian 9.0 [here](https://build.opensuse.org/build/home:lukho:copyq/Debian_9.0/i586/CopyQ-Qt5/_log).

**Comment by Achaean** [comment]
No! There were not there.

So...something went wrong with dependencies installation.
I purged all the dependencies, rebooted and installed them again.
Now...these files are indeed there!!!

Of course this time CopyQ compiled and installed as expected.
It was dependencies installation bug, NOT CopyQ's one.

Oh well...I suppose there's a reason that oldstable called OLD.  :-)
Some day I have to move on to an up to day version.
THANKS for your help and SORRY for wasting your time, with unrelated to CopyQ bugs.  :-)
Bye!!!

**Comment by hluk** [comment]
:tada: Great, glad it worked. :)
