### ISSUE TITLE
Windows 10 Notification Area Icon

### ISSUE THREAD

**Issue by JeremyWW** [hluk/CopyQ#1258]
Just curious if anyone else has experienced this - Just installed 3.9.3 on Windows 10 Pro (fully updated) and, despite having the taskbar icon set to show, every restart of copyq results in the setting turning itself off.

**Comment by JeremyWW** [comment]
Windows issue, apparently now solved. Apologies.

**Comment by JeremyWW** [comment]
Hmm... sorry, I was wrong. I have to reopen this as it's only come to light with this version and after restarting the laptop the issue is back. Haven't got a clue what's going on with this.

**Comment by JeremyWW** [comment]
If it helps and to ensure that this is not a Windows issue I did the following:

1) Reset Notification Area Icons (https://www.tenforums.com/tutorials/5662-reset-notification-area-icons-windows-10-a.html)

2) According to the now refreshed list of notification icons in Windows, copyq.exe is the only one without a 'name'. Is this something that is now causing an issue in some way? Hopefully I've attached a screenshot. Notification icon was showing until I restarted, whereupon it was mysteriously turned off.

![image](https://user-images.githubusercontent.com/544340/69163618-72066900-0ae6-11ea-8ea3-d98f315b4ea3.png)

**Comment by hluk** [comment]
Probably a Qt bug. I moved from using old **Qt 5.6** to latest LTS version **Qt 5.12.5** for Windows.

(I could try to reproduce and debug it later when I have access to Windows.)

**Comment by JeremyWW** [comment]
OK thanks. I'll be dropping back to 3.9.2 in the meantime as a visible icon is essential for me.

**Comment by Dominiquini** [comment]
It's probably related: 

After I upgraded to version 3.9.3, every time I restart the PC (or restart CopyQ), the position I set for the taskbar icon is lost, and I have to readjust!

APP Version: 3.9.3
OS: Windows 10 (64)

**Comment by hluk** [comment]
I don't see this issue with CopyQ 3.9.3 (installed using Chocolatey) on Windows 10 Pro (version 1709; 64-bit).

I'm trying to install the latest system updates (looks like it takes forever to download those).

**Comment by JeremyWW** [comment]
Latest build for W10 Pro is 1909. I've tried with 3.9.3, fresh installs, probably 3 or 4 times and it's the same behaviour on every occasion. 3.9.2. is fine.

**Comment by Dominiquini** [comment]
Version 3.9.2 is working fine for me, too!

**Comment by hluk** [comment]
After system update (which took forever) I still see the tray icon - but I think I ended up with somewhat broken system because it currently fails to re-activate and I cannot change notification area settings.

Anyway, this seems like either Qt or Windows issue.

**Comment by JeremyWW** [comment]
Confused as to how it can be a Windows issue if 3.9.2 behaves and all other app notification icons work. Anything to do with Windows security? (Long shot but Smartscreen complains when you install copyq - you have to override Windows blocking the installation. And then there's no 'name' or description in the notification list for copyq. Just wondering if Windows is getting finicky).

**Comment by hluk** [comment]
> Confused as to how it can be a Windows issue if 3.9.2 behaves and all other app notification icons work.

I don't know where the configuration for notification area is stored -- maybe the system is confused with previous configuration for copyq.

Or maybe the problem is that Windows fails to figure out the app name. But I have no idea if there is way to set this in Qt or when building Windows app with CMake (no idea where to look).

**Comment by JeremyWW** [comment]
> I don't know where the configuration for notification area is stored -- maybe the system is confused with previous configuration for copyq.

I manually removed any obvious traces of copyq before reinstalling. There might be something buried elsewhere but as I completely cleared the cache for the notification area I don't think this is the problem.

> Or maybe the problem is that Windows fails to figure out the app name. But I have no idea if there is way to set this in Qt or when building Windows app with CMake (no idea where to look).

I certainly don't. I'm not a developer. All I can see is some evidence that Windows isn't happy with the signing of the app in some way which presumably is why it tries to block it. TBH Windows has been flagging the copyq installation for some time now but with no ongoing issues - now we have an additional problem which might be a 'red herring' but it makes me suspicious that Windows has tightened it's security / requirements around third party app installation.

**Comment by hluk** [comment]
> All I can see is some evidence that Windows isn't happy with the signing of the app in some way which presumably is why it tries to block it.

The app is not signed, but that shouldn't be an issue since this worked well with Qt 5.6.

I've built the app with older Qt versions:
- [with Qt 5.9](https://ci.appveyor.com/project/hluk/copyq/builds/29051061/job/1f203cday1d2kx5w/artifacts)
- [with Qt 5.6](https://ci.appveyor.com/project/hluk/copyq/builds/29051061/job/mapu87wq6keejhk0/artifacts)

Can you try those?

**Comment by JeremyWW** [comment]
Both work fine with visible taskbar icons, however Windows attempts to block installation for both which it has for some time. 

I tried the released version of 3.9.3 again and the taskbar icon fails to stay visible as before. Interestingly though, the installation for the 3.9.3 release isn't blocked. Another oddity in the 3.9.3 release is in the tab label behaviour - I'm using the Tab Tree option and if I click on the clipboard tab label at the top, then click the other tab labels one by one, the selected tab label flashes dark blue. Very distracting compared to the subtle label colour changes in previous versions. The tab tree itself also has a slightly different appearance with an additional horizontal line at the top which is a bit odd.

**Comment by JeremyWW** [comment]
Just to clarify - I'm running with your Qt 5.9 version at the moment which exhibits none of the issues above except the installation block which I can live with. Nice if that could be corrected though.

**Comment by Gitoffthelawn** [comment]
I can confirm this issue on Win7 with CopyQ v3.9.3.

Sometimes Windows will no longer show the CopyQ icon in the system tray, instead relegating it to the overflow menu.  This only happens with CopyQ, and not other applications I tested.

I have a _**hypothesis**_ as to why this might be happening: CopyQ changes it's window title (and system tray tooltip) to reflect the contents of the clipboard.  Windows might then be seeing it as a different application, because the title is different.

Note that this also _could possibly_ result in privacy and security issues because when Windows stores the application name in the registry (for the system tray icon settings) it _may_ also be storing the contents of the clipboard in the registry (since it's part of the application title).  If that's not bad enough, in Windows 10, it's possible that such information could possibly be transmitted to Microsoft as part of their aggressive telemetry campaign.  Ugh.

Note also that, by default, Windows 7, 8, 8.1, and 10 automatically run different maintenance tasks on various schedules.  It's possible that one of those tasks (possibly `Windows Maintenance Troubleshooter` / `System Maintenance Troubleshooter`) is thinking that CopyQ no longer exists, and so deletes its system tray settings.

I have a hunch that modifying _something_ in CopyQ relating to application title, window naming, or tooltip contents will fix this issue.

**Comment by hluk** [comment]
> I have a _**hypothesis**_ as to why this might be happening: CopyQ changes it's window title (and system tray tooltip) to reflect the contents of the clipboard. Windows might then be seeing it as a different application, because the title is different.

@Gitoffthelawn Hmm, if that's true, it's probably a Qt bug (it should identify the app using something else). But you can try using [command "No Clipboard in Title and Tool Tip"](https://github.com/hluk/copyq-commands/tree/master/Scripts#no-clipboard-in-title-and-tool-tip) so CopyQ stops setting window title and tool tip (it will take effect after restarting the app).

**Comment by Gitoffthelawn** [comment]
@hluk Ah, thank you.  I was searching for the setting to do that, and I couldn't find it.  Now at least I know I didn't just miss it in the UI.  I wonder if it would be good to add a setting for it to the UI.

I might give it a try.  But, for the most part, I find it useful to see the current clipboard contents in the tooltip.

Would it be possible to show the current clipboard contents in the tooltip, but not change the window title?

**Comment by hluk** [comment]
> Would it be possible to show the current clipboard contents in the tooltip, but not change the window title?

Nope, only setting both the title and tool tip is supported.

**Comment by Gitoffthelawn** [comment]
> Nope, only setting both the title and tool tip is supported.

Interesting.  Is that a Qt thing or a Windows thing?

**Comment by hluk** [comment]
> > Nope, only setting both the title and tool tip is supported.
> 
> Interesting. Is that a Qt thing or a Windows thing?

No, it's just the current implementation -- more detailed control over tool tip and window title was never required.

It's probably easy to implement but I don't think it would fix the problem with the hidden tray icon.

**Comment by Gitoffthelawn** [comment]
I'm going to keep a little log of when the CopyQ system tray icon gets tossed into the overflow popup.  By doing so, I'm hoping to determine what is actually causing the issue.

It hasn't happened in a few days, so I'm guessing it's a scheduled Windows maintenance task that it causing it.

**Comment by Columbus1000** [comment]
I use CopyQ throughout multiple family member's PCs, and my own also, so easy replication is important to me. Hence I always use the  .ZIP version and (after CONFIG backing up etc)  simply overwrite the existing installations. No need to run installers etc. So I can't comment on Windows 10 blocking installations or not; I have no such issue with the ZIP method anyway.

I **thoroughly tested both the .ZIPs above** (from hluk back up this page on Nov 22 https://github.com/hluk/CopyQ/issues/1258#issuecomment-557550234.) and I **can confirm**, after multiple restarts and reboots that **both these versions solve the disappearing icon problem completely**. And re-trying the release version of copyq-v3.9.3.zip confirmed the problem returned. So well done on that ... the older QT versions both work fine, as you predicted.

Thanks again for a great program!

**Comment by Gitoffthelawn** [comment]
@Columbus1000 Interesting.  That implies it's likely a Qt issue - something they changed between Qt v5.9 and v5.12.5.  Assuming that's the only change between those compiled versions.

**Comment by hluk** [comment]
BTW, the latest development version is built with Qt 5.12.6 (but I'm skeptical that it fixes this issue).

You can find the latest build here: https://ci.appveyor.com/project/hluk/copyq/builds/30207841/job/8jkowjx6vp08y45x/artifacts

**Comment by JeremyWW** [comment]
I was hoping 3.10.0 would include a fix for this but clearly not. No taskbar icon after machine restart. I'll go back to copyq-v3.9.3-1-gc3f095ce-setup which is fine as above.

**Comment by hluk** [comment]
> I was hoping 3.10.0 would include a fix for this but clearly not. No taskbar icon after machine restart. I'll go back to copyq-v3.9.3-1-gc3f095ce-setup which is fine as above.

@JeremyWW I no longer build CopyQ with old version of Qt (official support for Qt 5.9 ends in May 2020). I don't want to be stuck on an old version.

Not sure if it helps but here are builds for Qt 5.13.2:

- [32bit](https://ci.appveyor.com/project/hluk/copyq/builds/30533145/job/1o8b67498yax87lh/artifacts)
- [64bit](https://ci.appveyor.com/project/hluk/copyq/builds/30533145/job/760cnh9080btuy4x/artifacts)

**Comment by Gitoffthelawn** [comment]
While investigating an issue with another application, I noticed that CopyQ has no Program Name or Description in [WinLister (NirSoft)](https://www.nirsoft.net/utils/winlister.html).

Could this missing data possibly be the cause of the notification icon issue in Windows?  Perhaps just adding a Program Name and Description to the window(s) will fix the issue.

**Comment by JeremyWW** [comment]
You can see that in the Windows list of icons that show or don't in the taskbar. It was one of my early suggestions as it's a glaring difference.

**Comment by JeremyWW** [comment]
> > I was hoping 3.10.0 would include a fix for this but clearly not. No taskbar icon after machine restart. I'll go back to copyq-v3.9.3-1-gc3f095ce-setup which is fine as above.
> 
> @JeremyWW I no longer build CopyQ with old version of Qt (official support for Qt 5.9 ends in May 2020). I don't want to be stuck on an old version.
> 
> Not sure if it helps but here are builds for Qt 5.13.2:
> 
> * [32bit](https://ci.appveyor.com/project/hluk/copyq/builds/30533145/job/1o8b67498yax87lh/artifacts)
> * [64bit](https://ci.appveyor.com/project/hluk/copyq/builds/30533145/job/760cnh9080btuy4x/artifacts)

Those latest builds have the same issue unfortunately. Strange colour highlighting when clicking the tab names and the taskbar icon still disappears after restart. I really hope that this is resolvable as the later versions since v3.9.3-1-gc3f095ce are really not usable. I'll need to stick with v3.9.3-1-gc3f095ce for the time being.

**Comment by hluk** [comment]
Here is a new CopyQ build with Qt 5.9: https://ci.appveyor.com/project/hluk/copyq/builds/30554651/job/bi7n6lpdjvqy4e5x/artifacts

**Comment by JeremyWW** [comment]
> Here is a new CopyQ build with Qt 5.9: https://ci.appveyor.com/project/hluk/copyq/builds/30554651/job/bi7n6lpdjvqy4e5x/artifacts

Thanks. That one works fine.

**Comment by garynsw** [comment]
Thanks for the link and update, this version "copyq-v3.10.0-7-gca7c54f4" appears to have fixed the issue when restarting windows.
It was an annoying problem and I had to revert back to "copyq-v3.9.2" from the newer versions because the icon would not remain on the taskbar when windows restarted, and would go back to being hidden despite the windows setting "Select which icons appear on the taskbar".
CopyQ is certainly the best clipboard manager that I have used.
Thanks

**Comment by Gitoffthelawn** [comment]
I spent a couple hours looking into this.  I was able to determine where Windows stores the notification area data and decrypt it (it's actually encrypted, but uses weak encryption).

I wrote a [CyberChef](https://gchq.github.io/CyberChef/) routine to automate the process.

I'm not sure, but I think this issue may have to do with CopyQ changing its tooltip.  There is a *chance* that having CopyQ change its tooltip to null (or just `CopyQ`) before it exits will resolve this issue.  I give it a 20% chance.

**Comment by hluk** [comment]
> I spent a couple hours looking into this.

Wow, thanks.

> I'm not sure, but I think this issue may have to do with CopyQ changing its tooltip. There is a chance that having CopyQ change its tooltip to null (or just CopyQ) before it exits will resolve this issue. I give it a 20% chance.

It's worth a try: #1355

I'll provide new Windows binaries when the build finishes

**Comment by hluk** [comment]
Here is a build (using Qt 5.13) with fix that resets the tray tooltip (to "CopyQ") on exit: https://ci.appveyor.com/project/hluk/copyq/builds/32256212/job/0n6mtkwtbn269mlo/artifacts

To test:
1. Launch the new version.
2. Set the tray icon in Windows as visible.
3. Exit CopyQ.
4. Launch the new version again.
5. The tray icon should be visible (if the fixed worked).

**Comment by JeremyWW** [comment]
Doesn't work for me. Tried a few times, including a reboot.

**Comment by Gitoffthelawn** [comment]
@hluk You're welcome, and thank you for the update.  I'll give it a try soon.

@JeremyWW Thanks for trying it on Win10.  Here's a couple things you can try:

  1. Before closing CopyQ, hover over its notification area icon to view the tooltip.
  2. If step 1 doesn't help, perform step 1, and then wait 10 minutes before exiting CopyQ.

I give step 1 by itself about a 2% chance of working.  When adding step 2, i give it another 15%.

It's so bizarre that CopyQ is the only application having this issue.  I'm trying to think of what it is doing differently that is causing this issue.  I'm also trying to think of an automated way to work around it if it can't be resolved.

**Comment by hluk** [comment]
> It's so bizarre that CopyQ is the only application having this issue.

It could be because of the newer Qt version [1] and possibly also the way the app initializes or uses the tray icon.

[1] It works fine in Qt 5.9, but it's difficult to tell what change broke it because there are too many changes between minor Qt releases.

**Comment by Gitoffthelawn** [comment]
I guess you could file an issue report with Qt, if you haven't already.  They could use CopyQ as a test app to quickly replicate the issue.

**Comment by tanrak** [comment]
Hi, in v3.11.0 the problem still exists. Also no tooltip is displayed anymore when i hover over the tray icon after a restart of CopyQ. Can you please build a temporary version with Qt 5.9 as for v3.10.0?
Thanks in advance.

**Comment by hluk** [comment]
CopyQ 3.11.0 - Qt 5.9 build: https://ci.appveyor.com/project/hluk/copyq/builds/32599707/artifacts

**Comment by tanrak** [comment]
Thanks. This works as expected. I hope that problem is someday eliminated by Qt-Developers.

**Comment by Gitoffthelawn** [comment]
@hluk Is Qt aware of this issue?

**Comment by JeremyWW** [comment]
I concur with the above. Qt 5.9 build seems to work fine.

**Comment by hluk** [comment]
@Gitoffthelawn Not sure if there is a Qt bug report for this. I currently have no means to test or reproduce this. But feel free to create a bug report.

**Comment by hluk** [comment]
I found only this Qt bug that could be related: https://bugreports.qt.io/browse/QTBUG-77653

There are many code changes for the tray icon between [Qt 5.9.9 and 5.12.5](http://mergely.com/ndPPPtGW/).

**Comment by Dominiquini** [comment]
I am also having problems with the official versions with regard to the icon in the notification area, but the versions published using QT 5.9 work well.
Wouldn't it be better to go back to using QT 5.9 for the official versions until this bug has been fixed?

**Comment by hluk** [comment]
New version built with Qt 5.9 is here: https://ci.appveyor.com/project/hluk/copyq/builds/32745642/artifacts

> Wouldn't it be better to go back to using QT 5.9 for the official versions until this bug has been fixed?

I might do that in the end, but I really don't want to be stuck on old version of Qt (there should be much better high DPI support on newer versions).

**Comment by tukanos** [comment]
Sigh, I thought this was a Windows bug.   It is really annoying bug.  I have noticed this hiding of CopyQ but did not have time to address it.  I was thinking that I'll just do some powershell hack to do a temp fix.  I'm glad in the end it was a QT's bug, because that might get fixed.  Did you report it in the QT upstream?

From the comparision change log the bug may reside here:

```
static void setIconVisibility(NOTIFYICONDATA &tnd, bool v)
{
    tnd.uFlags |= NIF_STATE;
    tnd.dwStateMask = NIS_HIDDEN;
    tnd.dwState = v ? 0 : NIS_HIDDEN;
}

**Comment by tukanos** [comment]
@hluk I have created a PR (https://github.com/qt/qtbase/pull/38) for QT.  I hope it correct and gets merged soon.

**Comment by Gitoffthelawn** [comment]
@tukanos Thanks. Did you submit it elsewhere?

**Comment by tukanos** [comment]
@Gitoffthelawn You are welcome.  I suffer from this too.  I'm trying to setup the env.  It is not that easy the [QT Contribution Guidelines](https://wiki.qt.io/Qt_Contribution_Guidelines).

**Comment by tukanos** [comment]
After the long fight I have managed to push the changes to QT's gerrit repository.  I hope they will intercorporate the change soon.

[Initial icon visibility](https://codereview.qt-project.org/c/qt/qtbase/+/302953)

**Comment by hluk** [comment]
@tukanos Thanks for fixing Qt! :tada: 

I'm looking at the code and trying to figure out if it's possible to have workaround in CopyQ (other than using old Qt) until your patch is merged, released and the fixed version of [Qt available on AppVeyor](https://www.appveyor.com/docs/windows-images-software/#qt) (it could take a long time). Let me know if you have any ideas ... and thanks again. :)

**Comment by Gitoffthelawn** [comment]
I have not had this issue lately, even though I haven't intentionally done anything to fix it.

The only thing I've changed is that I added a dynamic (frequently changing) system tray icon immediately to the right of CopyQ.

**Comment by fmaiabatista** [comment]
Hey guys I was about to notify this issue but this thread seems to address it properly.

I see you have discussed a ton already and I'd like to reinforce the suspicion that what causes this issue with the tray icon is the "subtitle" of CopyQ in Windows as it changes with every new item in the clipboard.

![image](https://user-images.githubusercontent.com/1574224/85329226-7a71b880-b4a8-11ea-8499-a07d42178e3a.png)

That being said, what I believe happens is Windows registers this instance "copyq.exe - _with editing and scripting features_" as the visible icon but then whenever I restart my system there'll be a different "program" registered (which could be "copyq.exe - _empty_" or anything else really ("copyq.exe - _current clipboard content_") and then Windows was never told to "always show" that icon in the tray.

![image](https://user-images.githubusercontent.com/1574224/85329672-595d9780-b4a9-11ea-9b18-535c99fe2264.png)

(Now it might be registered as "another program" and even though it says "active" [because I didn't restart my system and this info doesn't refresh live], it will be hidden if I restart my system)

**Comment by Gitoffthelawn** [comment]
Quick update: This issue came back, but it is less frequent than before.  I have made no changes that should affect it. Weird.

**Comment by tukanos** [comment]
I still have the issue.

**Comment by hluk** [comment]
If CopyQ v3.12.0 still doesn't work (there are few additional libraries included that may have fixed this issue), here is a new build with Qt 5.9: https://ci.appveyor.com/project/hluk/copyq/builds/34048008/artifacts

**Comment by glolsh** [comment]
Hello! Can't reproduce that bug on several PC's on 3.12!

**Comment by Columbus1000** [comment]
Hi Lukas, I'm delighted to report that version 3.12.0 seems to have licked
the system tray problem on Windows 10!

I downloaded The QT 5.9 (34048008) version you so thoughtfully created but
it doesn't seem to be necessary and I haven't even tried it.

I've moved the CopyQ icon out of and back to the system tray and it behaves
beautifully. I don't know if that's the QT people or something clever
you've done, but well done on fixing it, cheers

**Comment by hluk** [comment]
Great, I actually did not expect this to work. My guess is that it was fixed by including `styles/qwindowsvistastyle.dll` in the installation (#1427).

**Comment by JeremyWW** [comment]
All good here also. Well behaved since yesterday. Thanks.

**Comment by garynsw** [comment]
I also have no problems after updating CopyQ to version 3.12.0, everything works well with the system tray icon after restarting or reboot. Thanks.

**Comment by tanrak** [comment]
Also here all fine. I think we can close now this issue...

**Comment by hluk** [comment]
Glad to hear it works now!

**Comment by tukanos** [comment]
Yes, it works now!  So I will ditch my patch to the QT project.  Thank you @hluk.
