### ISSUE TITLE
TypeError: Result of expression 'plugins.itemtags' [undefined] is not an object.

### ISSUE THREAD

**Issue by sl5net** [hluk/CopyQ#1262]
**Describe the bug**
I got:
"TypeError: Result of expression 'plugins.itemtags' [undefined] is not an..."
an i think it means maybe:
"TypeError: Result of expression 'plugins.itemtags' [undefined] is not an object."
I record a video: https://youtu.be/A-S0T_qFSUM
and let some details here: https://forum.manjaro.org/t/message-several-times-a-day-at-bottom-right/112232

**To Reproduce**
it happen all the time. but is easier to reproduce if you do this: https://youtu.be/A-S0T_qFSUM

**Expected behavior**
no message.

**Screenshots**
here are Screenshots:
https://forum.manjaro.org/t/message-several-times-a-day-at-bottom-right/112232
and here is a video:
https://youtu.be/A-S0T_qFSUM

**Version, OS and Environment**
CopyQ
Clipboard Manager
v3.9.2
Kernel: 5.3.11-1-MANJARO x86_64 bits: 64 compiler: gcc 
  v: 9.2.0 Desktop: Xfce 4.14.1 tk: Gtk 3.24.12 info: xfce4-panel wm: xfwm4 
  dm: LightDM 1.30.0 Distro: Manjaro Linux 
Machine:

**Comment by sl5net** [comment]
my workaround: i simply configured notification window with maximal height/width of 1pixel

**Comment by amosbird** [comment]
I just pulled the latest master and encountered this as well

**Comment by hluk** [comment]
Hmm, it should have been fixed in v3.9.3 (#1222).

It's caused by a command that uses `plugins.itemtags` -- you can search (for `plugins.itemtags`) and disable these commands manually in Command dialog (F6 shortcuts).

**Comment by mrkskwsnck** [comment]
I encountered this exact notification error upon every start of `copyq` v3.10.0 after upgrading my system to Linux Mint 20. As soon as I realized it was a plugin related issue, I installed the additional package `copyq-plugins` and the problem was gone.

**Comment by zzapper** [comment]
yep linuxmint 20  needs (thanks https://github.com/mrkskwsnck)
apt-get install copyq-plugins

**Comment by hluk** [comment]
I have a better error/notification message planned for a future release. The fix is included in branch `qt5-scripting-3` (it's mainly to support new scripting framework and Qt 6).
