### ISSUE TITLE
How can I remove the blank of tabtree

### ISSUE THREAD

**Issue by Antisunny** [hluk/CopyQ#1264]
<img width="232" alt="Capture2019-11-2221 17 16" src="https://user-images.githubusercontent.com/2398514/69429021-94f67e80-0d6d-11ea-85e7-d4a5e4351213.png">

**Comment by hluk** [comment]
No idea. I tried to modify some examples [here](https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qtreeview) without any luck. It may depend on the original system theme.
