### ISSUE TITLE
Is it possible to have the tray show only the first line of something I have copied?

### ISSUE THREAD

**Issue by seredes** [hluk/CopyQ#1266]
**Is your feature request related to a problem? Please describe.**
I am using a lot of pinned items. I would like to have as many as possible visible in the tray, but some of them contain long text that takes up all the space.

**Describe the solution you'd like**
I would like it to be possible to have the tray show only the first line of an item.

**Describe alternatives you've considered**
N/A

**Additional context**
Actually I am not sure if this is a feature request or not... I thought something on these lines was maybe already possible. I checked the documentation but could not find anything related.

**Comment by royharoush** [comment]
is this what you're looking for ? 
![image](https://user-images.githubusercontent.com/8113056/69590039-d0f04480-0ff6-11ea-85d4-fd46a03d2416.png)

**Comment by royharoush** [comment]
@seredes  did you look at the above suggestion ?

**Comment by seredes** [comment]
Yes it worked , thank you!

**Comment by hluk** [comment]
Glad it works for you.

@royharoush Thanks for helping!
