### ISSUE TITLE
Issues with images when syncing is enabled (Windows)

### ISSUE THREAD

**Issue by richlux** [hluk/CopyQ#1270]
On Windows, when syncing is enabled, image clips moved to the clipboard aren't treated the same way as they are when syncing is not enabled.  When a clip in CopyQ that is an image is copied to the clipboard using "Move to clipboard", the following behavior occurs:

**When syncing _is NOT_ enabled:**
- The CopyQ window title says `<IMAGE>`
- Clicking the "Edit with editor" does nothing (because it's an image)
- Pasting the clip into other programs pastes the image properly

**When syncing _IS_ enabled:**
- The CopyQ window title shows the filename (e.g. P:/CopyQ/Images/copyq_0001.png)
- Clicking the "Edit with editor" opens the editor and puts the name of the file (P:/CopyQ/Images/copyq_0001.png) into the editor
- Pasting the clip into other programs that allow text (such as notepad), will paste the filename. Similarly, pasting into an Outlook email will paste the image as an attachment pointing to the file (P:/CopyQ/Images/copyq_0001.png) instead of embedding the image into the email message.

**Expected behavior**
When syncing is enabled, images should be treated the same as they are when syncing is not enabled.  The filename should not be used as the information pasted.

**Screenshots**
Header when syncing is NOT enabled:
![image](https://user-images.githubusercontent.com/25157703/70094601-dd752e00-15f0-11ea-8646-84dc64d61782.png)

Header when syncing IS enabled:
![image](https://user-images.githubusercontent.com/25157703/70094586-cfbfa880-15f0-11ea-96e9-8385715abba9.png)

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Application Version 3.9.3
 - OS Windows 10

**Comment by hluk** [comment]
What formats does the item contain? (You can list the formats by selecting the item and pressing F4.)

**Comment by richlux** [comment]
It has the following:

image/png
application/x-copyq-itemsync-basename
application/x-copyq-itemsync-mime-to-extension-map

**Comment by hluk** [comment]
Oh, it's because the image editor is not set so the plugin falls back to text editor because the sync plugin also provides text for each item (which is the file path).

Fixing.
