### ISSUE TITLE
Customizing number of lines displayed per item

### ISSUE THREAD

**Issue by volt4ire** [hluk/CopyQ#1271]
Is there a way to set the maximum number of lines displayed per copied item in the main window's list view? For example, if I copy multiple items of text that are many paragraphs long, I would like only 3 or 4 lines at most for each copied item to be displayed so that more items simultaneously fit in the list view. I couldn't find any way to do this in the documentation or settings menu, but would you consider adding this feature? Thanks!

**Comment by hluk** [comment]
The configuration is under Items tab in Preferences dialog.

![image](https://user-images.githubusercontent.com/38054/70378482-15e27800-1921-11ea-9329-64ff4aa800a0.png)

**Comment by volt4ire** [comment]
Thanks so much I didn't think to look there!
