### ISSUE TITLE
Select candidate from CopyQ on Konsole, get output strange charactor, e.g. (2~)

### ISSUE THREAD

**Issue by zw963** [hluk/CopyQ#1272]
*** Reproduce

1. Active cursor on Konsole 

2. Use hotkey active copyQ window.

3. Select pasted content

4. get following outout:

```sh
 ╭─ 11:36  zw963 ⮀ ~/Airhost/airhost_ror ⮀ ⭠ (df3ef6e72) billy-81 *+$%  ➦ ruby-2.6.1@airhost_ror 
 ╰─ $ 2~
```

**Comment by hluk** [comment]
Does it also happen if you paste to Konsole with Shift+Insert? That's the shortcut CopyQ tries to send to the target window. It can fail with some keyboard layout or input method configurations in the desktop environment.

**Comment by zw963** [comment]
> Does it also happen if you paste to Konsole with Shift+Insert?

Yes, when i press "Shift+Insert" on Konsole, i see "**2~**" now.

my current system is arch linux.

```
 ╰─ $ echo $DESKTOP_SESSION
budgie-desktop

 ╭─ 10:29  zw963 ⮀ ~/Dropbox/common/functions ⮀ ⭠ (75036c901) test *$%  ➦  
 ╰─ $ uname -a
Linux lggram 5.3.13-arch1-1 #1 SMP PREEMPT Sun, 24 Nov 2019 10:15:50 +0000 x86_64 GNU/Linux
```

**Comment by hluk** [comment]
Might be caused by some Konsole configuration. Probably nothing I can do in CopyQ if the target app is not using standard shortcuts for pasting. You could define custom command for pasting in CopyQ but it would be much easier to fix the behavior in Konsole.

**Comment by zw963** [comment]
@hluk , thank you very much for help, it resolved now after change konsole config.

![image](https://user-images.githubusercontent.com/549126/70403153-f8bcbf00-1a70-11ea-9fd8-245ca2e6cc46.png)

**Comment by zw963** [comment]
Hi, change the Konsole default key mapping is not easy, which cause another new issue, so, it maybe Konsole bug, but, anyway, i revert it after i try it two days.

At the mean time, i test on another similar package, named:  `Parcellite`,  1.2.1, if i use it to paste on konsole, never insert those strange "2~" character, it work as expected, so, maybe it use another more better way to handle this? 

Thank you.

**Comment by hluk** [comment]
So what shortcut do you use to paste to console? If it's Ctrl+V, you can use: https://github.com/hluk/CopyQ/issues/334#issuecomment-105001542

Otherwise, you can use `xdotool` to [simulate a shortcut for pasting](https://github.com/hluk/CopyQ/issues/562#issuecomment-257086056) or let it [type the text instead](https://github.com/hluk/CopyQ/issues/1082#issuecomment-460338893).

**Comment by hluk** [comment]
Looks like Parcellite uses `xdotool` to send Ctrl+V ([code](https://github.com/rickyrockrat/parcellite/blob/fa54161d0ea83357d817d3d16b6ef3f503bafc09/src/main.c#L1650)) or simulate middle mouse click (but this is not a good idea in this case, since mouse may not be over terminal).

**Comment by zw963** [comment]
> So what shortcut do you use to paste to console?

C-y,  i think i can solve this by `xdotool`,  but, i think maybe parcellite solution better, if you don't think so, that is ok, just need delete two char after i paste from copyq, i am very familiar this for now.

**Comment by zw963** [comment]
@hluk , Just let you know, this issue was fixed on konsole in recently version, thank you.
