### ISSUE TITLE
How to disable autocomplete when searching on the clipboard history?

### ISSUE THREAD

**Issue by evandrocoan** [hluk/CopyQ#1273]
That autocomplete pop up frequently shows up and it is quite annoying. I never want to autocomplete anything and it is hiding behind it my clipboards items.

If in some cause I would like to autocomplete, I could call some keybind as `Ctrl+Space`, then only then, it would show up.

![image](https://user-images.githubusercontent.com/5332158/70355730-9fc31000-1851-11ea-8897-24df3007c4b0.png)

![image](https://user-images.githubusercontent.com/5332158/70355447-e5330d80-1850-11ea-9174-62cd98c00d9e.png)

**Comment by hluk** [comment]
Disable "Save Filter History" option in General config tab.

![image](https://user-images.githubusercontent.com/38054/70378552-00ba1900-1922-11ea-92f1-3a9d01c3ac10.png)

**Comment by evandrocoan** [comment]
Thanks!
