### ISSUE TITLE
Selected Text

### ISSUE THREAD

**Issue by andrehtgti2** [hluk/CopyQ#1279]
Is there a option to do not put the mouse or keyboard selected text in the copied list ?

**Comment by hluk** [comment]
It's in the General config tab:

![image](https://user-images.githubusercontent.com/38054/70864151-b81ce400-1f4f-11ea-8093-07da12013d42.png)

Hover mouse over each option to see details.

**Comment by haizaar** [comment]
I have selected "Store text selected using mouse" and when I select text, CopyQ still doesn't catch it. I'm using copyq-3.12.0 on Ubuntu 20.04. Installed through deb file on the GH release page.

Should I open a new issue?

**Comment by hluk** [comment]
> Installed through deb file on the GH release page.

Please use [the packages for your distro](https://copyq.readthedocs.io/en/latest/installation.html). Debian package use libraries that differ from the ones on Ubuntu.

**Comment by haizaar** [comment]
Actually I started with official Ubuntu packages for 20.04 - it behaved the same (ignoring mouse selection) and hence I tried to latest release from here.

**Comment by hluk** [comment]
@haizaar My guess is that it's either related to running Wayland (instead of X11) or the app where you do the text selection doesn't support mouse selections. You can try checking the current X11 primary selection buffer with `xclip -o` or `copyq selection`.

(Probably better if you open a separate issue if you want to discuss it further.)

**Comment by haizaar** [comment]
(Last attempt before opening new issue)
1. I'm running X11. The selection doesn't work neither in Chromium, Firefox, no Gnome Terminal.
2. Selected word "Start" in the terminal:
```console
$ xclip -o; echo
Start
$ copyq selection; echo
Start
```
and yet "Start" does not show up in CopyQ popup:

![image](https://user-images.githubusercontent.com/58201/89778963-c14b6880-db51-11ea-9e0d-29206aa811d7.png)

**Comment by hluk** [comment]
It could be a command that stops the new selection to be stored in CopyQ or a tab for storing the clipboard/selection is not set (`copyq config clipboard_tab` should print the tab name).

**Comment by haizaar** [comment]
I'm not sure what you mean:
```console
$ copyq config clipboard_tab
&clipboard
```
![image](https://user-images.githubusercontent.com/58201/89780399-ba722500-db54-11ea-98b0-5938e00255d8.png)
