### ISSUE TITLE
[Feature Request] Let select candidate keybinding(up/down arraow) can be configurable.

### ISSUE THREAD

**Issue by zw963** [hluk/CopyQ#1284]
Thank you for this awesome paste tools, when i want paste the previous clipboard content, i have to move my finger to down arrow or use mouse click item i need, is there any chance make me use 
can config to use emacs keybinding (Ctrl+N move to next previous item, Ctrl+P reverse).

Thank you.

**Comment by hluk** [comment]
There are a couple of predefined commands (e.g. "Copy next item", "Paste and copy next") that may come in handy ([here is how to add a predefined command](https://copyq.readthedocs.io/en/latest/faq.html#how-to-paste-as-plain-text)).

**Comment by zw963** [comment]
Hi, @hluk , sorry for this very bad issue, i will try to describe more clearly.

1. When i open copyq select cadidate page to paste page.

![image](https://user-images.githubusercontent.com/549126/77180900-9494a700-6b05-11ea-9120-5158443d7c94.png)

2. If i want paste `44444` instead `33333', i have to press keyboard `down arrow key` to select it before i press `RET`.

3.  Current feature request: Can i change `down arrow key`, `up arrow key`'s binding to other key?
e.g. `Ctrl+p` => move up, `Ctrl+n` => move down.

Thank you.

**Comment by hluk** [comment]
> Can i change down arrow key, up arrow key's binding to other key? e.g. Ctrl+p => move up, Ctrl+n => move down.

You can add a custom commands to override the up/down arrow key functionality: [Next/Previous](https://github.com/hluk/copyq-commands/tree/master/Application#nextprevious)

(To add the commands, read [the guidelines](https://github.com/hluk/copyq-commands/blob/master/README.md#add-a-command-to-copyq).)

**Comment by zw963** [comment]
Thank you, do you consider add a app keybinding for this? anyway, i think it should be a useful settings.

**Comment by hluk** [comment]
> do you consider add a app keybinding for this?

No, since there is a way to do this with commands. I would rather like the app to be more easy to extend using commands.

**Comment by zw963** [comment]
Thank you!

**Comment by zw963** [comment]
> You can add a custom commands to override the up/down arrow key functionality: [Next/Previous](https://github.com/hluk/copyq-commands/tree/master/Application#nextprevious)
> 
> (To add the commands, read [the guidelines](https://github.com/hluk/copyq-commands/blob/master/README.md#add-a-command-to-copyq).)

```
[Commands]
1\Command="
    copyq:
    selectItems(currentItem() + 1)"
1\Icon=\xf0ab
1\InMenu=true
1\MatchCommand=copyq: currentItem() + 1 < size() || fail()
1\Name=Next
1\Shortcut=ctrl+n
2\Command="
    copyq:
    selectItems(currentItem() - 1)"
2\Icon=\xf0aa
2\InMenu=true
2\MatchCommand=copyq: currentItem() > 0 || fail()
2\Name=Previous
2\Shortcut=ctrl+p
size=2
```
Hi, @hluk , sorry for late, because i use a global keybinding transformater, so,
I never really try this for now, today, i remove global keybinding, and what to
try this, but "Ctrl+P", because it conflict with menu shortcut.

When i press "Ctrl+P", following page is raised.

![image](https://user-images.githubusercontent.com/549126/79839820-a8267c80-83e7-11ea-8108-65aef9c75a41.png)

But, it so wired, Ctrl+N is working, we can see those two keybinding marked as a warn icon, but C-n working, C-p not working, so, maybe here exist some issue? thank you!

![image](https://user-images.githubusercontent.com/549126/79840026-ea4fbe00-83e7-11ea-8a2b-cdbb345f7635.png)

**Comment by hluk** [comment]
It looks like the shortcut commands are sometimes not updated correctly. Workaround for now is to remove the Filter/MatchCommand expression:

```ini
[Commands]
1\Command="
    copyq:
    selectItems(currentItem() + 1)"
1\Icon=\xf0ab
1\InMenu=true
1\Name=Next
1\Shortcut=ctrl+n
2\Command="
    copyq:
    selectItems(currentItem() - 1)"
2\Icon=\xf0aa
2\InMenu=true
2\Name=Previous
2\Shortcut=ctrl+p
size=2
```

The filter expression is not really needed in this case - it's to disable the action/shortcut in some cases - e.g. Previous command is disabled at the top of the list, Next is disabled at the bottom.

**Comment by zw963** [comment]
Thank you, it working! 

BTW: i create a PR for fix two commands, please check.

https://github.com/hluk/copyq-commands/pull/21
