### ISSUE TITLE
CopyQ eats gigabytes of memory when started with a second screen present

### ISSUE THREAD

**Issue by tanius** [hluk/CopyQ#1286]
When starting CopyQ **when a second screen is present**, it will eat 7-8 GiB of main memory within a few seconds, unless killed in time.

Here, the issue happened with CopyQ versions 3.7.1 and 3.9.3 under Ubuntu Linux 19.04 with the LXQt desktop environment. But the issue seems related to issue #1024 (where the report remained incomplete) where it happened with an earlier version and in a different Linux distribution (Manjaro) and desktop environment (Deepin).

**To Reproduce**

1. Create a fresh installation of `copyq` with fresh configuration files:

    ```
    sudo apt purge copyq; sudo apt install copyq;
    ```

2. Use `arandr` or similar to configure an extended desktop that covers both the internal display and the external monitor. My external monitor is an old Fujitsu Siemens CTM5010 model with a max. resolution of 1024×768.

3. Now start `copyq`. (It's important to do this with a second display present. Otherwise, everything will work normally.)

4. With CopyQ version 3.9.3, you can now observe how your memory gets eaten at a rate of about 1 GiB/s. It's advisable to have `killall -9 copyq` command ready to prevent the computer from becoming unresponsive. With CopyQ 3.7.1, the same behavior appears, but only after trying to open the main window. The main window may even open eventually after about 7-8 GiB of memory have been consumed, and the program seems to behave "normal" then.

**Expected behavior**

Not eating so much memory :-)

**Version, OS and Environment**

```
# copyq version
CopyQ Clipboard Manager v3.9.3
Qt: 5.12.2
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Ubuntu 19.04
```
For desktop environment and window manager see above.

**Additional context**

I don't know about the earliest version where this issue is present – it could have been present for a long time, but the default was for my computer to start CopyQ first and then I'd manually set up the second display. Now the second display starts in mirror mode right from boot time, triggering the issue as described above.

There is one strange behaviour of CopyQ with this external display (and possibly all external displays, I don't know) that may be connected to the issue here: something about the display's DPI settings or CopyQ's way of handling them seems to be messed up, leading to super large UI elements in the main window and tray icon menu. Since this kind of behaviour does not happen with any other applications on my system, including other Qt applications, it is probably something that can be fixed in CopyQ.

To see that issue, compare the following two screenshots of CopyQ 3.9.3, the first taken on my internal display and the second after moving that window to the external display:

![MainWindow InternalScreen](https://user-images.githubusercontent.com/843907/71905726-072df180-3169-11ea-81ad-88f2629850fe.png)

![MainWindow ExternalScreen](https://user-images.githubusercontent.com/843907/71905725-072df180-3169-11ea-9981-d585494bd757.png)

**Workaround**

Start `copyq` first, with only the internal display present. Only afterwards configure the external display to get an extended desktop setup.

**Comment by hluk** [comment]
This is a Qt bug (or a bug in some system that provides scaling). I don't think I can do anything in the app itself.

You can try setting Qt environment variables before starting CopyQ as workaround:

```
export QT_SCREEN_SCALE_FACTORS=1
copyq
```

**Comment by tanius** [comment]
Indeed, like @hluk said, the root of this bug was not in the application.

## Workaround

First, what helped was starting `copyq` as follows:

```
QT_SCREEN_SCALE_FACTORS="1;0.15" copyq
```

## Cause

This will rescale the UI to with factor 1 (no scaling) on the first monitor and factor 0.15 on the second monitor. See the [documentation](https://doc.qt.io/qt-5/highdpi.html). You'll have to play around with the order of values and the scaling value itself to find something that work (and without artifacts).

About the reason: the documentation linked above says:

> The environment variable is mainly useful for debugging, or to work around monitors with wrong EDID information (Extended Display Identification Data).

And indeed my external monitor provided wrong (way too high) DPI information, as can be seen with this command:

```
sudo apt install edid-decode
cat /sys/class/drm/card0-VGA-1/edid | edid-decode
```

The output contained:

```
EDID version: 1.1
Manufacturer: BMM Model 238 Serial Number 48774
Analog display, Input voltage level: 0.7/0.3 V
Sync: Separate 
Maximum image size: 30 cm x 24 cm
[…]
Established timings supported: […]
Standard timings supported:
Detailed mode: Clock 78.750 MHz, 30 mm x 22 mm
```

The error is `Detailed mode: […] 30 mm x 22 mm`, which should be "300 mm x 240 mm" according to the "Maximum image size:" line. Qt will convert this to a very high DPI setting and tell that to `copy`, which in turn will paint a very large UI and exhaust the main memory doing so.

## Where to put a real fix?

So far only `copyq` showed the behavior of an oversized user interface on this external monitor with its wrong EDID information. This includes recent Qt5 applications, for example [`tom-ui`](https://github.com/jansorg/tom-ui). I don't know what the difference is … that is, if `copy` or the other applications use the legacy approach to High-DPI displays? See the Qt documentation about High-DPI displays in section "[Migrate Existing Applications](https://doc.qt.io/qt-5/highdpi.html#migrate-existing-applications)". Obviously, if `copyq` is already following the most recent Qt instructions for High-DPI displays, there is nothing that could be done here to fix things …

**Comment by hluk** [comment]
@tanius Thanks for the detailed description!

I've just replaced some deprecated Qt code and the app now uses more precise scaling (only available with Qt 5.6 and greater). Fixes are merged to master branch in this repo.

Using fractional scaling less than 1 for me always produces bad artifacts -- this really looks like some issue in Qt -- tested with Qt 5.13.2 but it's possibly fixed in Qt 5.14 (they provide at least more control over the scaling - e.g. rounding policy).

**Comment by tanius** [comment]
@hluk Thank you very much for caring about this issue! Didn't try the new version yet but will report back when I do.

CopyQ is the best clipboard I ever had under Linux (and I tried quite a few), so I'm especially happy that it is well maintained :slightly_smiling_face: (Just saw that [CopyQ has LiberaPay](https://liberapay.com/CopyQ/) and added a donation there.)

**Comment by hluk** [comment]
@tanius Thanks for your support!

I also hope that the high DPI support gets better -- I use lower DPI laptop screen with 4K external monitor -- but I'm experiencing fewer issues with recent Qt versions.
