### ISSUE TITLE
Tray shows many extra sections

### ISSUE THREAD

**Issue by Wylbur** [hluk/CopyQ#1289]
**Describe the bug**
As I use copyq, each time a new items is added, a blank section is added in the tray between the "Clipboard" and "Show/Hide" items.

Sections continue to be added until I close and restart copyq.  Each new item adds a new section. 

**To Reproduce**
1. Start copyq
2. Add an item
3. Click on system tray
4. Blank sections are added with each item

**Expected behavior**
No sections should be added

**Screenshots**
![Screenshot_2020-01-13_11-44-37](https://user-images.githubusercontent.com/238274/72280814-d59ca680-35fe-11ea-90d6-c481ff993ebd.png)

**Version, OS and Environment**
CopyQ Clipboard Manager v3.9.3
Qt: 5.9.5
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Linux Mint 19.3

**Comment by hluk** [comment]
Fixed (the fix will be in upcoming release). Thanks for the report.

**Comment by Wylbur** [comment]
Thanks so much I really appreciate all your efforts, this is a great project!
