### ISSUE TITLE
Launch on startup with main window open?

### ISSUE THREAD

**Issue by orschiro** [hluk/CopyQ#1292]
By main window I mean this one below:

![image](https://user-images.githubusercontent.com/170947/72622557-bcb82c00-3943-11ea-9ba1-dadd8125a08f.png)

Would be a great enhancement!

**Comment by hluk** [comment]
You can call `show()` in `onStart()` function (called after the app starts). Here is the command:

```ini
[Command]
Command="
    var onStartPrevious = global.onStart
    global.onStart = function() {
        onStartPrevious()
        show()
    }"
Icon=\xf2d0
IsScript=true
Name=Show On Start
```

**Comment by orschiro** [comment]
Thank you very much Lukas. :-)

**Comment by hluk** [comment]
No problem, glad to help. :)

BTW, I've added [the command to copyq-commands repository](https://github.com/hluk/copyq-commands/tree/master/Scripts#show-on-start).
