### ISSUE TITLE
Linux: CopyQ notification shows <EMPTY> (but it's really not empty).

### ISSUE THREAD

**Issue by tnilzon** [hluk/CopyQ#1293]
CopyQ resets the clipboard to last content if it is emptied (this happens if the application which sets the clipboard is closed). A desired behavior, and it works very well. But the CopyQ notification which displays the clipboard content shifts from showing the content to "EMPTY" when an application that has been copied from is closed (although the content resides in the clipboard).

So, the _behavior of CopyQ_ is correct, but the notification is wrong.

>My System:
Host: Kernel: 5.3.18-1-MANJARO x86_64 bits: 64 
Desktop: Gnome 3.34.3 Distro: Manjaro Linux
CopyQ version: 3.9.3

**Comment by hluk** [comment]
For me the notification correctly changes to `<HIDDEN>` after the content is reset. I use following command to reset empty clipboard/selection.

```ini
[Command]
Command="
    var timeoutMilliseconds = 500;
    
    function reset(key, getFn, setFn) {
      if (hasData()) {
        settings(key, [data(mimeText), Date.now()])
      } else {
        var last = settings(key)
        if (!last)
            return;
    
        afterMilliseconds(timeoutMilliseconds, function() {
          if (!str(getFn()) && last[1] == settings(key)[1]) {
            serverLog('Reset from ' + key)
            setFn(mimeText, last[0], mimeHidden, 1)
          }
        })
      }
    }
    
    function resetClipboard() {
      reset('lastClipboard', clipboard, copy)
    }
    
    function resetSelection() {
      reset('lastSelection', selection, copySelection)
    }
    
    var onClipboardChanged_ = onClipboardChanged
    onClipboardChanged = function() {
      onClipboardChanged_()
    
      isClipboard() ? resetClipboard() : resetSelection()
    
      if (!hasData())
        sleep(2 * timeoutMilliseconds)
    }"
Icon=\xf246
IsScript=true
Name=Reset Empty Clipboard/Selection
```

**Comment by tnilzon** [comment]
If I remember correctly the notification kept showing the clipboard content (and not "HIDDEN" or "EMPTY") if it had been reset. Has this been changed in some earlier version? Anyway I sure prefer to have  the notification to show the content instead of something else (what is the point to change it?).

**Comment by hluk** [comment]
I've omitted showing the old content to avoid accidentally showing any previously copied passwords (which could've been ignored by other command).

To show the reset content, change line

```js
setFn(mimeText, last[0], mimeHidden, 1)
```

to

```js
setFn(mimeText, last[0])
```

**Comment by tnilzon** [comment]
OK, thanks for info. But still I get "EMPTY" instead of "HIDDEN", and I can't find the origin of the "command to reset empty clipboard/selection"? Could you please advice where the file should be, thanks?

**Comment by hluk** [comment]
Maybe some other command affects the notification.

The command is [here](https://github.com/hluk/copyq-commands/tree/master/Scripts#reset-empty-clipboardselection). I normally fix the commands in the repo if I find an issue.

**Comment by tnilzon** [comment]
OK, where do I copy the `reset-empty-clipboard.ini` file on my computer (Linux)?

**Comment by tnilzon** [comment]
An idea: Could you consider adding an option in the Notification settings to either show "HIDDEN" or the clipboard content?

**Comment by hluk** [comment]
> OK, where do I copy the reset-empty-clipboard.ini file on my computer (Linux)?

You can copy the content of the file directly to the Command dialog (use the Paste button). Details are in the [README.md](https://github.com/hluk/copyq-commands/blob/master/README.md) file.

> An idea: Could you consider adding an option in the Notification settings to either show "HIDDEN" or the clipboard content on clipboard reset?

Resetting clipboard content is only provided by the command -- it's not part of the application functionality. That's why you cannot change the behavior in configuration, but only by modifying the command.

**Comment by tnilzon** [comment]
OK, thanks (still confused why it shows "EMPTY" instead of "HIDDEN" though).

**Comment by tnilzon** [comment]
Tested it now. It works, but the notification first show "EMPTY" for about one second, then shifts to "HIDDEN" (or clipboard content, with the modified script).
