### ISSUE TITLE
Command dialog in CopyQ F6 shortcut does not work

### ISSUE THREAD

**Issue by pacid** [hluk/CopyQ#1294]
**Describe the bug**
Command dialog in CopyQ (F6 shortcut) - this doesn't work for me. I see it in all docs, but whether CopyQ is focused or not it won't work. 

**To Reproduce**
1. Just press F6 - does not work - when Chrome is in focus it does sth there

1. Open CopyQ  (Ubuntu 18.04)
![image](https://user-images.githubusercontent.com/1618052/73073933-59347e00-3eb0-11ea-94eb-4c1747a7aff1.png)

2. Press F6 - nothing

**Version, OS and Environment**
- OS: Ubuntu 18.04
- Version: CopyQ Clipboard Manager v3.2.0 (hluk@email.cz)
   Built with: Qt 5.9.3, LibQxt 0.7.0
- Desktop

I must be missing something basic here as "show main window under mouse coursor" works and I have added a shortcut for it CTRL+SHIFT+V

**Comment by pacid** [comment]
Oh, ok, stand corrected.
![image](https://user-images.githubusercontent.com/1618052/73118135-11f9cc00-3f48-11ea-9af3-d798b5816b08.png)

You just need to click "Show/Hide" from the tray menu. That's the only way for me to see the main menu as it does not load in the side panel (maybe I turned it off?). 

Anyways, when I open the main window with the "File" menu and then do F6 it works.

**Comment by hluk** [comment]
> You just need to click "Show/Hide" from the tray menu.

Yeah, I can see it can be confusing. I was just replying with the same.

The menu behavior is handled by desktop environment, the app doesn't have complete control over it.

> That's the only way for me to see the main menu as it does not load in the side panel (maybe I turned it off?).

Preferred way to show the main window is to assign global shortcut.

![image](https://user-images.githubusercontent.com/38054/73118205-5b9ae480-3f51-11ea-91aa-c8d564221525.png)

**Comment by pacid** [comment]
Thanks!! I wouldn't even think of first assigning a shortcut in order to open the main menu. I would just go to see the docs or give up (I wouldn't click on random "Show/Hide" - don't know what it means in this context). In this case, since I know what Github is :) I was able to get your help this way.

Maybe then "Show/Hide" in the tray menu could be "Show/Hide Main Menu" ?
