### ISSUE TITLE
Lost any icon

### ISSUE THREAD

**Issue by andreamoro-git** [hluk/CopyQ#1295]
I installed copyQ on  mac os and I have lost any way to interface with the application. In the preferences I clicked on an option to remove the tray icon, and while the app is running (it's visible on activity monitor) there is no toolbar icon nor  menu bar icon. I have tried to delete an reinstall, to restart the computer multiple times.

**Comment by andreamoro-git** [comment]
if you you have an ideas where settings are stored, I can try delete them and reinstall

**Comment by andreamoro-git** [comment]
I found a way to delete preferences in 
~/Library/Preference

I filed a more appropriate bug in https://github.com/hluk/CopyQ/issues/1296

**Comment by hluk** [comment]
It's possible to show main window from command line with `copyq show` or re-enable the tray icon with `copyq config disable_tray false`.
