### ISSUE TITLE
[Request]: System tray icon to appear dark on a bright shell theme.

### ISSUE THREAD

**Issue by tnilzon** [hluk/CopyQ#1297]
The CopyQ tray icon is only appearing with a bright (white) color. This is fine when the tray background is dark, but with a shell theme that has a tray with a bright background the CopyQ icon is almost invisible.
It would be desirable to have the icon to shift to dark if the background is bright, or with some color that works for both. See screen shots below (compare CopyQ tray icon with some of the other icons that shifts between bright and dark depending on the tray background).

My System:
>Kernel: 5.3.18-1-MANJARO x86_64 bits: 64 
  Desktop: Gnome 3.34.3 Distro: Manjaro Linux
 CopyQ v3.9.3

Dark shell theme:
![dark](https://user-images.githubusercontent.com/6920015/73119258-7ecc9080-3f5f-11ea-9bb0-9ba0275425f4.png)

Bright shell theme:
![bright](https://user-images.githubusercontent.com/6920015/73119261-85f39e80-3f5f-11ea-8c09-cf8e6b646f7b.png)

**Comment by hluk** [comment]
That's icon from an icon theme (not sure which one) -- it's not the official app icon. Maybe it's a bug in the icon theme.

**Comment by tnilzon** [comment]
> That's icon from an icon theme (not sure which one)

This is the icon theme: `ARC-icon-theme`
<https://github.com/horst3180/arc-icon-theme>

**Comment by hluk** [comment]
> > That's icon from an icon theme (not sure which one)
> 
> This is the icon theme: `ARC-icon-theme`
> https://github.com/horst3180/arc-icon-theme

I cannot find "copyq" in the repo. Also, it was not updated in 3 years.

You can normally find icons with following command.

```
find /usr/share/icons/ -name 'copyq.png'
```

**Comment by tnilzon** [comment]
After trying numerous of icon themes I learned this:
I am never getting any other tray icon but the white scissor icon (as in my screen shot in my first post). It seems that chosen icon theme has no impact on the CopyQ tray icon (it is always the same). At least in gnome desktop.

**Comment by hluk** [comment]
Hmm, I wonder if CopyQ is really interfering with the icon somehow.

You can list icon files the app is trying to open if you restart CopyQ with `strace`:

```bash
strace copyq |& grep /usr/share/icons/
```

Or try overriding [icon color with environment variable](https://copyq.readthedocs.io/en/latest/sessions.html#icon-color):

```bash
COPYQ_SESSION_COLOR=yellow copyq
```

**Comment by tnilzon** [comment]
`strace copyq |& grep /usr/share/icons/` list of output is here <https://file.io/2KUrng>
`COPYQ_SESSION_COLOR=yellow copyq` made no difference to the tray icon (no matter what input).

**Comment by hluk** [comment]
Looks like the icon comes from [Papirus icon theme](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme).

I can set icon theme to light or dark variation in Gnome (with `gnome-tweaks`). But I don't know if the icon changes color if depending on the panel.

**Comment by hluk** [comment]
I'm changing this so you can use `COPYQ_DEFAULT_ICON=1` to avoid using the app icon from icon theme. Would it work for you?

```
COPYQ_DEFAULT_ICON=1 copyq
```

**Comment by tnilzon** [comment]
> I'm changing this so you can use `COPYQ_DEFAULT_ICON=1`

Yes, that could be a good idea, thanks!

**Comment by tnilzon** [comment]
Have now tried the new version (CopyQ-master). It now shows the default icon in the system tray regardless of system icon theme, and it is clearly visible in both dark and bright tray backgrounds. Great, much better!

![dark](https://user-images.githubusercontent.com/6920015/73463850-3efe1280-437e-11ea-81eb-74b9ca6c122e.png)

![bright](https://user-images.githubusercontent.com/6920015/73463861-445b5d00-437e-11ea-9348-ef6b1700a53c.png)
