### ISSUE TITLE
CopyX slows down Chrome and tab switching

### ISSUE THREAD

**Issue by dabesa** [hluk/CopyQ#1302]
Hi guys,
CopyX is slowing down dramatically my Chrome browser.
When CTRL+C some text, changing to a different browser tab takes ~5 seconds.

I read this bug https://github.com/hluk/CopyQ/issues/1152 and disabled the File - Disable Clipboard Storing" (Ctrl+Shift+X).
But this defeats the purpose of CopyX.

Is there a solution?

Thanks
D

**Comment by tupadr3** [comment]
On my machine it only happens after a while (~1h). A restart of copyq fixes the issue temporarily

**Comment by nmat** [comment]
hmmm I do not have this problem. Can you inform what version you are using?

**Comment by hluk** [comment]
Is this still an issue?
