### ISSUE TITLE
Global shortcut not working on Wayland

### ISSUE THREAD

**Issue by PEG71** [hluk/CopyQ#1303]
I did configure ctrl-alt-c as the global key to hide/unhide the main window. After loading the Copyq this error shows up in the logs:
Failed to set global shortcut "Ctrl+Alt+C" for  "Show/hide main window".

 - Application Version:  v3.9.3
 - OS: Fedora 31
 - Desktop environment, window manage: Gnome 3.34.3

**Comment by hluk** [comment]
It's not a bug. Wayland doesn't support this. See #27.

**Comment by hluk** [comment]
See [possible workaround](https://github.com/hluk/CopyQ/issues/27#issuecomment-549766568).
