### ISSUE TITLE
CopyQ 3.10.0 - Accented letters wrong in installer strings

### ISSUE THREAD

**Issue by bovirus** [hluk/CopyQ#1305]
@hluk 

There is a problem regarding accented letetrs in strings (ex. sarà) for Italian language.

Please check the screenshot.

![CopyQ](https://user-images.githubusercontent.com/1262554/73646721-512bc980-467a-11ea-8153-728bf0d9e2c6.jpg)

Where are located the fiel with strings for the installer?

**Comment by hluk** [comment]
I cannot find the string in [shared/copyq.iss](https://github.com/hluk/CopyQ/blob/v3.10.0/shared/copyq.iss). It looks like it comes from Inno Setup itself.

My guess is that some translation files from Inno Setup are incorrectly encoded.

[Inno Setup 6.0.3 was installed using Chocolatey](https://ci.appveyor.com/project/hluk/copyq/builds/30517462/job/ox949tlqcq43jh2f#L880) on the build system to create the setup binary.

**Comment by bovirus** [comment]
@hluk 

Please check that all .ISL language files for inno Setup are coded as UTF-8 and accenetd letters are OK.

You can get the right .ISL files here

Language files - https://www.jrsoftware.org/files/istrans/

Italian language file - https://raw.github.com/jrsoftware/issrc/master/Files/Languages/Italian.isl

**Comment by hluk** [comment]
> Please check that all .ISL language files for inno Setup are coded as UTF-8 and accenetd letters are OK.

Unfortunately, I currently don't have access to a Windows machine (and I don't want to spend a lot of time figuring this using Appveyor).

It looks like the binary for Inno Setup may have been silently updated without bumping the version so now the Chocolatey package is outdated (different checksum). I've [commented in the discussion](https://chocolatey.org/packages/InnoSetup#comment-4781727625).

**Comment by bovirus** [comment]
You don't need a Windows machine.

You can get the language files that I mentioned and updated your installation.

**Comment by hluk** [comment]
> You don't need a Windows machine.
> 
> You can get the language files that I mentioned and updated your installation.

The problem is that the file installed by `innosetup-6.0.3.exe` could be different. The string in the file you linked seems to be correctly UTF-8 encoded.
