### ISSUE TITLE
Translation strings alignment vs. different language

### ISSUE THREAD

**Issue by bovirus** [hluk/CopyQ#1306]
@hluk 

To help the translators I propose to make some changes to language files library,.

Currently the language files not have a master template (English one with strings empty).

Different language files has different status and not all languages includes string not translated and translator doesn't know if their language is complete or not.
Ex. DE language has 636 strings and IT has 609 strings.
But in Italian language I didn't see 27 strings missing to complete.

**Proposal** 

Create an english master template ts file with strings to translate empty

Use this mater template to align ALL other language to fillin them and have all number of strings for ALL language fiels (queal to amster template).

Then any transltor can open .ts file and check if all tranmslated.

You can do this job with QT SDK tools.

**Comment by hluk** [comment]
> You can do this job with QT SDK tools.

Can you post details?

I use [a script to call `lupdate`](https://github.com/hluk/CopyQ/blob/bc620e1e3a9054ebe127488685503bbfc606585b/utils/lupdate.sh) to update the translations but don't I run it as frequently as I should. I need to keep the translations synced with [Weblate](https://hosted.weblate.org/projects/copyq/) and sometimes it has conflicts I need to resolve with some updates in master branch (there is a Python utility to handle that but I haven't got time to look more into it).

BTW, Weblate includes the source English strings (read-only): https://hosted.weblate.org/translate/copyq/master/en/

**Comment by bovirus** [comment]
@hluk 

Italian translation completed (100%)
Please check that here
https://hosted.weblate.org/projects/copyq/master/it/
there re three strings marked with failed controls.
Are equal as English (it's right) but Weblate program mark as errors.
Please check and fix.

**Comment by hluk** [comment]
I've updated the translations with `lupdate`.

**Comment by bovirus** [comment]
@hluk 

Thanks. Updated translation in Weblate. You added a new string.
Please re-run lupdate.

If you want I can post a dos batch that make the same job for lupdate.sh (Linux) but for DOS/Windows.
Then anyone can check and update strings based on source.

Plese re-run lupdate.sh every time that you make some changes to source.
