### ISSUE TITLE
Pressing a number key to select item not work

### ISSUE THREAD

**Issue by Kzinux** [hluk/CopyQ#1308]
**Describe the bug**
Using a number key to activate tray menu item failes when the language is Simple Chinese(简体中文). 

**To Reproduce**
1. Open the copyq setting window then change the language to Simple Chinese, restart copyq.
2. Using the shortcut to open the copyq tray menu.
3. Pressing a number key to select a item.
4. Nothing happens.

**Expected behavior**
Pressing a number key to select a item.

**Version, OS and Environment**
CopyQ Clipboard Manager v3.10.0
Qt: 5.14.1
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Arch Linux

**Additional context**
Changing the language to English then the number key works well.

**Comment by hluk** [comment]
> Pressing a number key to select a item.

Can you type a number with a number key?

If the keys are used to type different symbols (in current layout), I would prefer the CopyQ to start filtering the items (at least that's the case for Czech keyboard layout).

**Comment by Kzinux** [comment]
Yes, I can.
After i changed the language in the CopyQ setting window, I have tried 正體中文, 日本語 and English, Number key works well.

**Comment by hluk** [comment]
Oh, it's caused by incorrect translation for the menu item format.

Fixing.

Thanks for the report!

**Comment by Kzinux** [comment]
Thank you, I appreciate your work.
