### ISSUE TITLE
Still having Issue with images when syncing is enabled (Windows)

### ISSUE THREAD

**Issue by richlux** [hluk/CopyQ#1309]
I just installed the latest version and I'm still having the problem that is referenced here: https://github.com/hluk/CopyQ/issues/1270

Thanks,
Rich

**Comment by hluk** [comment]
Hmm, I cannot reproduce the issue anymore with 3.10.0.

Can you double-check that the versions is up-to-date in GUI (Shift+F1 from main window should show About dialog with the version)?

**Comment by richlux** [comment]
It's the latest version.  This only happens if you move an image from the clipboard hsitory into the clipboard. If you copy an image and it is already in the clipboard, it will paste properly.

![image](https://user-images.githubusercontent.com/25157703/74069790-3dab9600-49cd-11ea-8e3f-d6ddf8fddae1.png)

**Comment by hluk** [comment]
Oh, I thought the problem was editing the image in an editor.

I'll try to fix the pasting issue by avoiding adding `plain/text` format when copying to clipboard. It may help, but there is still `text/uri-list` copied so the content can be also handled as a file and I'm not sure various apps interpret it.

**Comment by richlux** [comment]
It looks like this issue still exists. The original issue doesn’t say it, but this happens with URLs also. If I move a previously copied URL into the clipboard, when I paste it, I don’t get the URL text, I get file attachments instead. I’ve tested with both Microsoft Word and Outlook emails. See the examples below. (FYI, Images moved to the clipboard seem to paste correctly in Microsoft Word, but still create attachments in Outlook emails)

Given these URLs in the clipboard list:
![image](https://user-images.githubusercontent.com/25157703/78999514-d0c19300-7b18-11ea-8d72-40715c49f40c.png)

Moving **URL 1** above into the clipboard and then pasting into Microsoft Word or Outlook, I get this embedded file below instead of the URL text:
 
![image](https://user-images.githubusercontent.com/25157703/78999524-d5864700-7b18-11ea-93e3-36ff285f1e11.png)


Moving **URL 5** above into the clipboard and then pasting into Microsoft Word or Outlook, I get the 3 embedded files below instead of the URL text. Probably because URL 5 has and Icon and Notes:
 
![image](https://user-images.githubusercontent.com/25157703/78999532-d8813780-7b18-11ea-9318-fb25b1f080f3.png)


Thanks,
Rich

**Comment by hluk** [comment]
The best solution is probably not to set the URI list in copied data.

Fixed development version: https://ci.appveyor.com/project/hluk/copyq/builds/32097432/job/a46bfedl2nheldjn/artifacts

**Comment by richlux** [comment]
Thank you! Thank you! Thank you!  This appears to fix the problem.  (it was driving me crazy because I constantly paste into Outlook and Word)

Rich
