### ISSUE TITLE
Notifications: need option to completely disable keyboard interaction and hovering focus

### ISSUE THREAD

**Issue by amerlyq** [hluk/CopyQ#1310]
**Is your feature request related to a problem? Please describe.**
1) When I use tiling window manager (keyboard-only) I move mouse away from screen, often in the top-right corner.
But when I copy some data by shortcuts, notifications often appear directly under mouse cursor and will never hide away, until I move mouse from it.
2) When I actually use mouse for browsing, I often rapidly select something on screen, simultaneously move mouse to "close tab" button, press `Ctrl-C` and immediately press that "close tab" button. But as you already can guess, notification appears directly over that button, and I click on notification instead of tab.
So, I lose notification to verify what I had copied, and I must press close-tab twice. BUT! if I delay between clicks is ~2 seconds (time of notification) my habitual two clicks will now close two tabs.

It's rather irritating over years :(

**Describe the solution you'd like**
Option to use totally ephemeral notification.
No keyboard interaction. No mouse interaction. No focusing. No hovering.
Simply show me my notification for 2 seconds and disappear away.
And if I somehow click on it -- click must directly fallthrough to underlying window.

**Describe alternatives you've considered**
Disable notifications completely.
But after half a year of such experience, I started much rately use shortctus of "copy-previous-item-from-history", etc. which are almost useless without visual feedback from notification.

**Comment by hluk** [comment]
Setting the display interval in Notification config tab to 0 should disable these notifications.

**Comment by amerlyq** [comment]
I already mentioned this suggestion in section "alternative solutions which
I tried", and stated my reasons why I don't want to lose the notifications
completely. Therefore I still deem uninteractible notifications useful -
after all I use copyq 7+ years already on both linux and windows.

**Comment by hluk** [comment]
OK, let's try a proper fix - notification won't pop up under mouse cursor.
