### ISSUE TITLE
Custom underline tray menu Actions shortcuts

### ISSUE THREAD

**Issue by elig0n** [hluk/CopyQ#1312]
It will be very nice if we can assign underline letter shortcuts to custom actions in the tray menu this way using global shortcut to menu and then some letter will execute an action.

**Comment by hluk** [comment]
It should work if you use `&` in the custom action name (e.g. you can trigger `&Open` with Alt+O or similar). It may not work for native tray menus in some desktop environments (nothing I can do about that).
