### ISSUE TITLE
Command to Delete / Clear selected clipboard item

### ISSUE THREAD

**Issue by elig0n** [hluk/CopyQ#1313]
I was searching for some, very basic IMO, functionality to delete/remove/clear current clipboard selection in the Add Commands dialog but I couldn't find it. But then weird things like "Paste current time" or "Take screenshot" do exist. ¯\\\_(ツ)\_/¯

I've seen #308 but adding a new entry is not what I would rather have, but replace the current with \<EMPTY\> or delete it and use the next clipboard entry as the selected one instead.

**Comment by hluk** [comment]
> I've seen #308 but adding a new entry is not what I would rather have, but replace the current with <EMPTY> or delete it and use the next clipboard entry as the selected one instead.

I don't understand what you mean by "adding a new entry". Can you explain more in detail the functionality you need?

**Comment by elig0n** [comment]
> 
> 
> > I've seen #308 but adding a new entry is not what I would rather have, but replace the current with  or delete it and use the next clipboard entry as the selected one instead.
> 
> I don't understand what you mean by "adding a new entry". Can you explain more in detail the functionality you need?

As I said in the title, I would like to have my current clipboard content cleared, preferably similar to Remove.

**Comment by hluk** [comment]
> As I said in the title, I would like to have my current clipboard content cleared, preferably similar to Remove.

But that's exactly what [the command](https://github.com/hluk/CopyQ/issues/308#issuecomment-69774233) in #308 does.

The title mentions "selected clipboard item" by which I guess you mean an item stored in CopyQ. Removing item in CopyQ can be done by opening the main window and pressing Delete key.

Note: There is little relation between items stored in CopyQ and the current clipboard content. The app only stores the content (to designated tab/history/list) when it changes (sometimes it may ignore it).

**Comment by dgulinobw** [comment]
I think having a single command and shortcut to clear all of CopyQ's Clipboard would be handy.  Sometimes I've mistakenly copied passwords, etc and just want to quickly remove everything.

**Comment by hluk** [comment]
I believe this can be done with a command. But I'm still unsure what are the exact requirements here.

**Comment by elig0n** [comment]
@hluk  command from #308 replaces the text in the clipboard.

I eventually managed to get what I wanted with this command:

    copyq:
    copy(mimeText, "")
    setData(mimeText, "")
    remove(currentItem())`

which sets my clipboard <EMPTY> and also removes item from the list.

**Comment by Ace-Cassidy** [comment]
This should really just be a button somewhere. It's a security risk to not be able to easily clear your clipboard manager.
