### ISSUE TITLE
Display picture when hovering tray icon

### ISSUE THREAD

**Issue by AntoineTurmel** [hluk/CopyQ#1314]
**Is your feature request related to a problem? Please describe.**
Currently when a picture is inside the clipboard, CopyQ only display the path of it when hovering the tray icon

**Describe the solution you'd like**
It would be nice to have a thumbnail of the picture instead.

**Describe alternatives you've considered**
Right-clicking on the icon display the picture, but it's really small... 16x16

**Additional context**
eg.
![image](https://user-images.githubusercontent.com/119288/74291420-1e966680-4d35-11ea-812b-221a9668a295.png)

**Comment by hluk** [comment]
That's not supported by Qt out of the box. It would require me to implement custom tooltips and it would still not work in many desktop environments.

Also, I don't find tooltips useful at all and I usually don't work with images anyway.

In all, I don't have any interest to implement this.

But you can use following command that shows a current clipboard on a global shortcut ([here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)).

```ini
[Command]
Command="
    copyq:
    // Shows notification with current clipboard content.
    var timeout = 8000
    
    function showImage(mime, suffix) {
        var image = clipboard(mime)
        if (image.size() == 0)
            return false
    
        var fileTemplate = Dir().temp().absoluteFilePath(
            'copyq-XXXXXX.' + suffix)
        var file = new TemporaryFile()
        file.setFileTemplate(fileTemplate)
        file.openWriteOnly()
        file.write(image)
        file.close()
    
        var filePath = file.fileName()
        notification(
            '.icon', filePath,
            '.time', timeout
        )
        sleep(timeout)
        return true
    }
    
    function showText() {
        var text = clipboard()
        notification(
            '.message', text,
            '.time', timeout
        )
        sleep(timeout)
        return true
    }
    
    showImage('image/png', 'png') ||
      showImage('image/bmp', 'bmp') ||
        showText()
    "
GlobalShortcut=ctrl+shift+q
Icon=\xf27a
IsGlobalShortcut=true
Name=Show Clipboard
```

**Comment by Gitoffthelawn** [comment]
@hluk That's a very useful piece of code.  What do you think about adding it to: https://github.com/hluk/copyq-commands/tree/master/Application ?

**Comment by hluk** [comment]
> @hluk That's a very useful piece of code. What do you think about adding it to: https://github.com/hluk/copyq-commands/tree/master/Application ?

It's already in the copyq-commands repo, just in a different category: https://github.com/hluk/copyq-commands/tree/master/Global#show-clipboard

**Comment by Gitoffthelawn** [comment]
@hluk  Got it. Thanks!
