### ISSUE TITLE
Typing Korean characters does not trigger quick search mode

### ISSUE THREAD

**Issue by mysticfall** [hluk/CopyQ#1316]
**Describe the bug**
After opening up the context menu from CopyQ's status icon, typing Korean characters does not trigger the application to enter the quick search mode as it would with English characters.

When I enter Korean characters from the context menu, it opens the application window. But it does not show the search entry which, however, can be brought up by switching the input method and typing in any English character.

**To Reproduce**
1. Open CopyQ's context menu from its status icon (tested on KDE Plasma 5).
2. Switch to Korean input method (tested with Fcitx).
3. Type some Korean characters.

**Expected behavior**
CopyQ should enter into quick search mode, as it would be the case with typing English characters.

**Version, OS and Environment**
```
CopyQ Clipboard Manager v3.10.0
Qt: 5.14.1
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Manjaro Linux (KDE)
```

**Comment by hluk** [comment]
Interesting. I have a fix, but the solution may feel a bit unnatural, especially in the menu, since the characters are only rendered when complete.
