### ISSUE TITLE
Search numbers in tray 

### ISSUE THREAD

**Issue by RonaldShum** [hluk/CopyQ#1319]
When i try to search numbers in the tray, it selected the nth item instead. 

I saw issue #882 already addressed this but i cannot find the option to search number in tray as the screenshot in #882 (in history tab). 

Is the option being moved to other tabs or is this feature is one completely from copyq?

![image](https://user-images.githubusercontent.com/21473784/74813831-eabcd180-5330-11ea-9bbb-23bbacc37867.png)

**Comment by hluk** [comment]
That looks like an old version, you should update to the latest release.

**Comment by RonaldShum** [comment]
After reinstall copyq from apt install instead of the software center of ubuntu. 
The copyq version is now 3.10 and the search number option is available in history tab.

Thank you for the help.
