### ISSUE TITLE
doesn't store last items

### ISSUE THREAD

**Issue by erqan** [hluk/CopyQ#1320]
**Describe the bug**
If you logout or shutdown or force to kill copyq, it doesn't store items which are copied in last ~30 seconds.

**To Reproduce**
1. Copy any item
2. Logout or shutdown or force to kill copyq in 30 seconds
3. Re-login / restart copyq
4. See the stored items...

**Expected behavior**
I didn't look well into the code, maybe this is by design.. But I expect to store the copied items immediately.

**Screenshots**

**Version, OS and Environment**
CopyQ Clipboard Manager v3.10.0
Qt: 5.14.1
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Arch Linux

**Additional context**

**Comment by hluk** [comment]
> If you logout or shutdown or force to kill copyq, it doesn't store items which are copied in last ~30 seconds.

The application uses session management to flush data to disk before shutdown if the system gives it a chance.

If you don't run a session manager this won't work.

**Comment by erqan** [comment]
ok, thanks for the explanation..
