### ISSUE TITLE
CopyQ : Merge Clipboard items

### ISSUE THREAD

**Issue by Clemens-Ratte-Polle** [hluk/CopyQ#1321]
Hi.
OK, you can edit 2 items by F2 and then save to fuse them.
But perhaps merging per right click on some selected items would be fine :)
thx

**Comment by hluk** [comment]
See https://github.com/hluk/CopyQ/issues/1158#issuecomment-498276994.

**Comment by Clemens-Ratte-Polle** [comment]
Command merge&delete
thank you :)
