### ISSUE TITLE
Does not save emojis from Emoji Selector Gnome extension

### ISSUE THREAD

**Issue by forteller** [hluk/CopyQ#1324]
**Describe the bug**
Thanks for an amazing tool!

Unfortunately it never catches emojis from the [Emoji Selector Gnome extension](https://extensions.gnome.org/extension/1162/emoji-selector/).

It did before, but not in the latest few months of releases. Or at least not for me. The change happened not with an update, but after installing CopyQ on my new PC. I've not been able to start my old PC to update CopyQ there and see if I have the same issue there, unfortunately.

**To Reproduce**
1. Install Emoji Selector
2. Use it to copy an emoji
3. Notice that you can paste this emoji normally
4. Open the CopyQ main window and notice that the emoji is not there.

**Expected behavior**
The emoji should be captured and saved in the same way everything else you copy should.

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
CopyQ Clipboard Manager v3.10.0
Qt: 5.11.3
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Ubuntu 19.10

Thanks!

**Comment by hluk** [comment]
Looks the extension sets `text/plain;charset=utf-8` format and CopyQ somehow fails to recognize it as text.

You can fix it by adding following command ([here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)).

```ini
[Command]
Automatic=true
Command="
    copyq:
    setData(mimeText, input())"
Icon=\xf15c
Input="text/plain;charset=utf-8"
Name=Fix Copying UTF-8 Text
```

**Comment by forteller** [comment]
It worked!

Thank you for the workaround, and for committing a bugfix so fast!
