### ISSUE TITLE
Meta timestamps 

### ISSUE THREAD

**Issue by elig0n** [hluk/CopyQ#1325]
I wish CopyQ could save "meta" timestamps for each copy so that then I could filter through the history list via date and time or just get a clue how old that copy is.

**Comment by m4r71n** [comment]
This is already possible. Please take a look at https://copyq.readthedocs.io/en/latest/command-examples.html#show-copy-time

**Comment by elig0n** [comment]
Since this is a clipboard **manager** I believe this should become an embedded feature just like "Tags", "Pins", "Numbers" and "Notes".

**Comment by hluk** [comment]
Probably won't be implemented since it's possible to add time stamps using commands.
