### ISSUE TITLE
Copy specific line from preview pane

### ISSUE THREAD

**Issue by royharoush** [hluk/CopyQ#1326]
Though i thought it was possible, it doesn't seem like it's possible to copy a specific line\text from the preview pane. the use of SHIFT was mentioned in an earlier issue but it doesn't work or i didn't understand how to use it. 

the feature is to able to copy the marked line (shown in the screenshot), from the preview pane.
![image](https://user-images.githubusercontent.com/8113056/76153022-f77e4b00-60ce-11ea-841a-426afae147ff.png)

**Comment by royharoush** [comment]
can you direct me towards the nightly builds so i can test this feature before the next release ?

**Comment by hluk** [comment]
> can you direct me towards the nightly builds so i can test this feature before the next release ?

https://ci.appveyor.com/project/hluk/copyq/builds/31344283/job/3niymeovu6h50cm5/artifacts

**Comment by royharoush** [comment]
the nightly guild works. 
just one suggestion .. 
also tie ctrl+c to copying the content from the preview, and not just right click and copy. 

since copyq is aware of the context (when moving from the item to the preview the color of the item changes), it will be a great add.

**Comment by hluk** [comment]
> also tie ctrl+c to copying the content from the preview, and not just right click and copy.

It looks like the preview panel focus is a bit strange -- it doesn't receive the shortcuts (Ctrl+C/Ctrl+A) when you select the text.

**Comment by hluk** [comment]
Got the fix for Ctrl+C in the preview: https://ci.appveyor.com/project/hluk/copyq/builds/31477570/job/xoy0d9ew805qn7h8/artifacts

**Comment by royharoush** [comment]
awesome ! also liked that you added the keyboard navigation !
