### ISSUE TITLE
"CopyQ.app" cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by SimeonVSimeonov** [hluk/CopyQ#1331]
I'm using MacOS Catalina on MacBook Pro 2015 After install copyQ with this command "brew cask install copyq", I receive this error 
“CopyQ.app” cannot be opened because the developer cannot be verified.
macOS cannot verify that this app is free from malware.

![Image 16 03 20 at 13 13](https://user-images.githubusercontent.com/37142690/76751530-16907300-6788-11ea-98b2-bb7a44e50530.jpeg)

**Comment by SimeonVSimeonov** [comment]
I forgot to update permission in security settings. Works like a charm. Thanks

**Comment by anandchakru** [comment]
System Preferences -> Security & Privacy -> General (tab) -> You should see a warning that CopyQ was blocked, override it here and you should be good.

**Comment by barnabasszabo** [comment]
I am using bigSur 11.3.1 macOS, but unfortunately there is such option in security & Privacy section :(

can u release a verified version?

**Comment by AndreyRavkov** [comment]
get this error on Monterey 12.6.1
can u release a verified version?

**Comment by hluk** [comment]
> can u release a verified version?

Probably not, unless there is a way to handle this without macOS and an Apple account.

**Comment by AndreyRavkov** [comment]
:(

**Comment by AndreyRavkov** [comment]
looks liker i found how to enable it.
Apple System Preferenses -> Security & Privacy -> General -> Allow app downloaded from  -> click allow

**Comment by anandchakru** [comment]
> > can u release a verified version?
> 
> Probably not, unless there is a way to handle this without macOS and an Apple account.

I happen to have both, and I'm happy to help. Let me know what needs to be done.

**Comment by HugoDL** [comment]
[This](https://github.com/hluk/CopyQ/issues/1377#issuecomment-2020682321) is how I solved it

**Comment by XhstormR** [comment]
fix the issues:
```
xattr -d com.apple.quarantine /Applications/CopyQ.app
codesign --force --deep --sign - /Applications/CopyQ.app
```
