### ISSUE TITLE
"Remove tag important" is not working?

### ISSUE THREAD

**Issue by zw963** [hluk/CopyQ#1332]
**Describe the bug**
I mark a copied item as import, but i can't unmark it.

**Expected behavior**
unmark can be click.

**Screenshots**

![image](https://user-images.githubusercontent.com/549126/76874527-45066f00-68aa-11ea-81f8-ab187ae37bc5.png)

**Version, OS and Environment**
CopyQ Clipboard Manager v3.10.0
Qt: 5.14.1
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Arch Linux

**Additional context**

**Comment by hluk** [comment]
Nice find. Fixing. Thank for the report.
