### ISSUE TITLE
Shortcuts not working in some programs

### ISSUE THREAD

**Issue by amoksito** [hluk/CopyQ#1333]
I configured a shortcut to show copyq, but it seems to work only in some programs (like Chrome) but not in others (Gedt, Gnome-Terminal, etc). 

I'm using Manjaro. 

1. Set a shortcut.
2. Try to use it.

CopyQ Clipboard Manager v3.10.0
Qt: 5.14.1
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Manjaro Linux

**Comment by hluk** [comment]
Sounds like Wayland issue (global shortcut probably works only if an X11 app is focused). The big task is #27.

I suggest to use shortcut capability in you desktop environment (see [FAQ](https://copyq.readthedocs.io/en/latest/faq.html#why-global-shortcuts-don-t-work)).
