### ISSUE TITLE
[Feature Request] merge sequential copied content into one shot

### ISSUE THREAD

**Issue by zw963** [hluk/CopyQ#1334]
**Is your feature request related to a problem? Please describe.**

Maybe this is a issue ?

copyq provided to as a feature, named:  "Paste and copy next".
But i don't think this is a useful feature for me.

We try to reproduce a useful example:

![image](https://user-images.githubusercontent.com/549126/76975814-0fc35500-696e-11ea-9009-599b3ca78d46.png)

In this case, we can get copy history as this;

![image](https://user-images.githubusercontent.com/549126/76974705-7e071800-696c-11ea-98b6-b29df27481a4.png)

In fact, in most cases, i copy those "number" from different place, but i want paste those content
into one place, as original order (345126), as follow:

```
33333
44444
55555
11111
22222
66666
```

But i don't know how to do this, and i bind `Paste and copy next` to a hotkey, when i run those hotkey sequently, it was not worked as expected,  it get the original content reverse order.

So, i thought maybe we can add one of feature as describe in following screenshot.

![image](https://user-images.githubusercontent.com/549126/76976720-54032500-696f-11ea-86bd-795ed390f739.png)

Thank you!

**Comment by hluk** [comment]
Not sure if it's exactly what you need but you can reverse order of selected items from menu bar "Edit - Reverse Selected Items".

Or you can add commands to copy/paste from/to special Queue tab.

```ini
[Commands]
1\Command="
    copyq:
    tab('Queue')
    copy()
    var text = clipboard()
    add(text)"
1\GlobalShortcut=ctrl+shift+c
1\Icon=\xf078
1\IsGlobalShortcut=true
1\Name=Queue Item
2\Command="
    copyq:
    tab('Queue')
    
    var i = size() - 1
    if (i < 0) {
      popup('Queue is empty')
      abort()
    }
    
    var text = read(i)
    copy(text)
    paste()
    remove(i)"
2\GlobalShortcut=ctrl+shift+v
2\Icon=\xf077
2\IsGlobalShortcut=true
2\Name=Unqueue Item
size=2
```

**Comment by zw963** [comment]
> Not sure if it's exactly what you need but you can reverse order of selected items from menu bar "Edit - Reverse Selected Items".

Yes, this is exactly what i want, thank you!
