### ISSUE TITLE
Pasted text prepends "Version:1.0 StartHTML:" and more before the text copied

### ISSUE THREAD

**Issue by cpsyctc2** [hluk/CopyQ#1335]
**Describe the bug**
I have CopyQ running in Ubuntu 18.04 and in Windoze 10 in a VM and mostly copyQ synchs between the two fine.  However, sometimes when I copy text in Windoze it pastes in in Ubuntu starting with a bit like this: 
Version:1.0 StartHTML:0000000224 EndHTML:0000039719 StartFragment:0000039206 EndFragment:0000039679 and the file name of the file from which the copy was taken.  (In M$ Wurd in Windoze, not sure it's only from there though.)

**To Reproduce**
1. Copy some text in Wurd in Windoze in VM
2. Go to Firefox (for my Emailer) in Ubuntu and paste into HTML format Email
3. Pasted text is prepended with that extra text.

**Expected behavior**
Expect just to get the text I copied.

**Screenshots**
Don't think they'd help.

**Version, OS and Environment**
$ copyq version
CopyQ Clipboard Manager v3.8.0
Qt: 5.9.5
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Ubuntu 18.04.4 LTS

and
v3.7.3 in Windoze 10 Home version 1909 build 18363.752 running in VirtualBox 5.2.34_Ubuntu_133883 (Qt 5.9.5 apparently)

**Additional context**
Just a brilliant program and hope I'm not missing something obvious.  Many thanks.

**Comment by hluk** [comment]
Can you try using the latest version? Anyway, this sounds like an issue with VM software or some compatibility layer in system.

Maybe checking the clipboard content in both systems from CopyQ (Ctrl+Shift+C) can help.

(BTW, changing names of Microsoft products makes your description difficult to read.)

**Comment by cpsyctc2** [comment]
Sorry about the mocking names, you're the first person ever to comment on them.  I will remember to add the usual names if this turns into a "SOLVED" but I think you're correct that it will be something outside of CopyQ.  I hadn't realised that I wasn't receiving any alerts about being out of date.  Updated on Windows (grrr!) without any problems but updating on Ubuntu (18.04.4 LTS) has done something I've never seen before:

`
# dpkg -i copyq_3.10.0_Debian_10-1_amd64.deb 
Selecting previously unselected package copyq.
(Reading database ... 415415 files and directories currently installed.)
Preparing to unpack copyq_3.10.0_Debian_10-1_amd64.deb ...
Unpacking copyq (3.10.0-1) ...
dpkg: dependency problems prevent configuration of copyq:
 copyq depends on libqt5core5a (>= 5.11.0~rc1); however:
  Version of libqt5core5a:amd64 on system is 5.9.5+dfsg-0ubuntu2.5.
 copyq depends on libqt5gui5 (>= 5.11.0~rc1); however:
  Version of libqt5gui5:amd64 on system is 5.9.5+dfsg-0ubuntu2.5.
 copyq depends on libqt5widgets5 (>= 5.11.0~rc1); however:
  Version of libqt5widgets5:amd64 on system is 5.9.5+dfsg-0ubuntu2.5.

dpkg: error processing package copyq (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.13.3-11ubuntu1.1) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu3.18.04.2) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Errors were encountered while processing:
 copyq
`

I'm used to seeing dpkg back out cleanly in that situation but it didn't and now the system says I have a broken CopyQ installation.  The old version is running:
`# copyq version
CopyQ Clipboard Manager v3.8.0
Qt: 5.9.5
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Ubuntu 18.04.4 LTS
`

But I assume that if I have to restart my session or reboot, the broken version will fail to start.  I have done an export of "all" but would like your advice about backing of this.  I guess I can do a purge uninstall of CopyQ using dpkg and find and download 3.8.0 and install that and then import the data again.  Is that the safest way to get back up and robust to reboots?  Maybe this will teach me to change the names of programs I don't like having to use (not CopyQ)!

**Comment by cpsyctc2** [comment]
Sorry about the mocking names, you're the first person ever to comment on them. I will remember to add the usual names if this turns into a "SOLVED" but I think you're correct that it will be something outside of CopyQ. I hadn't realised that I wasn't receiving any alerts about being out of date. Updated on Windows (grrr!) without any problems but updating on Ubuntu (18.04.4 LTS) has done something I've never seen before:

`dpkg -i copyq_3.10.0_Debian_10-1_amd64.deb`

`Selecting previously unselected package copyq.`
`(Reading database ... 415415 files and directories currently installed.)`
`Preparing to unpack copyq_3.10.0_Debian_10-1_amd64.deb ...`
`Unpacking copyq (3.10.0-1) ...`
`dpkg: dependency problems prevent configuration of copyq:`
`copyq depends on libqt5core5a (>= 5.11.0rc1); however:`
`Version of libqt5core5a:amd64 on system is 5.9.5+dfsg-0ubuntu2.5.`
`copyq depends on libqt5gui5 (>= 5.11.0rc1); however:`
`Version of libqt5gui5:amd64 on system is 5.9.5+dfsg-0ubuntu2.5.`
`copyq depends on libqt5widgets5 (>= 5.11.0~rc1); however:`
`Version of libqt5widgets5:amd64 on system is 5.9.5+dfsg-0ubuntu2.5.`

`dpkg: error processing package copyq (--install):`
`dependency problems - leaving unconfigured`
`Processing triggers for gnome-menus (3.13.3-11ubuntu1.1) ...`
`Processing triggers for desktop-file-utils (0.23-1ubuntu3.18.04.2) ...`
`Processing triggers for mime-support (3.60ubuntu1) ...`
`Processing triggers for hicolor-icon-theme (0.17-2) ...`
`Processing triggers for man-db (2.8.3-2ubuntu0.1) ...`
`Errors were encountered while processing:`
`copyq`

I'm surprised by the "leaving unconfigured", I'm used to seeing dpkg back out cleanly in that situation but it didn't and now the system of course says I have a broken CopyQ installation. The old version is running:
`# copyq version `
`CopyQ Clipboard Manager v3.8.0 `
`Qt: 5.9.5 `
`Compiler: GCC `
`Arch: x86_64-little_endian-lp64 OS: Ubuntu 18.04.4 LTS`

But I assume that if I have to restart my session or reboot, the broken version will fail to start. I have done an export of "all" but would like your advice about backing of this. I guess I can do a purge uninstall of CopyQ using dpkg and find and download 3.8.0 and install that and then import the data again. Is that the safest way to get back up and robust to reboots? Maybe this will teach me to change the names of programs I don't like having to use (not CopyQ)!

**Comment by hluk** [comment]
Ideally, use installation instructions specific for Ubuntu (if an official package is not up-to-date): https://github.com/hluk/copyq/blob/master/README.md#ubuntu-ppa

Usually, it's enough to restart CopyQ after an update (Ctrl+Q from main window and start `copyq` again).

**Comment by cpsyctc2** [comment]
Frustrating: I was following the download link from your sourceforge for that deb.  I now as you say but my Linux version stays on 3.8.0:

`# add-apt-repository ppa:hluk/copyq`
 `CopyQ is advanced clipboard manager with editing and scripting features.`
` More info: https://launchpad.net/~hluk/+archive/ubuntu/copyq`
`Press [ENTER] to continue or Ctrl-c to cancel adding it.`

No error messages.  Did the apt-get update.  No error messages. Then:

# apt install copyq
Reading package lists... Done
Building dependency tree       
Reading state information... Done
copyq is already the newest version (3.10.0-1).
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies.
 copyq : Depends: libqt5core5a (>= 5.11.0~rc1) but 5.9.5+dfsg-0ubuntu2.5 is to be installed
         Depends: libqt5gui5 (>= 5.11.0~rc1) but 5.9.5+dfsg-0ubuntu2.5 is to be installed
         Depends: libqt5widgets5 (>= 5.11.0~rc1) but 5.9.5+dfsg-0ubuntu2.5 is to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
root@chris-Aether: Sat Mar 28 09:25:54 :/home/chris/Downloads
# apt --fix-broken install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following packages will be REMOVED
  copyq
0 to upgrade, 0 to newly install, 1 to remove and 0 not to upgrade.
1 not fully installed or removed.
After this operation, 7,452 kB disk space will be freed.
Do you want to continue? [Y/n] 
(Reading database ... 415487 files and directories currently installed.)
Removing copyq (3.10.0-1) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu3.18.04.2) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Processing triggers for gnome-menus (3.13.3-11ubuntu1.1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for mime-support (3.60ubuntu1) ...
root@chris-Aether: Sat Mar 28 09:26:38 :/home/chris/Downloads
# apt install copyq
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed
  copyq
0 to upgrade, 1 to newly install, 0 to remove and 0 not to upgrade.
Need to get 1,700 kB of archives.
After this operation, 6,984 kB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/hluk/copyq/ubuntu bionic/main amd64 copyq amd64 3.10.0~bionic [1,700 kB]
Fetched 1,700 kB in 1s (1,690 kB/s)
Selecting previously unselected package copyq.
(Reading database ... 415415 files and directories currently installed.)
Preparing to unpack .../copyq_3.10.0~bionic_amd64.deb ...
Unpacking copyq (3.10.0~bionic) ...
Setting up copyq (3.10.0~bionic) ...
Processing triggers for gnome-menus (3.13.3-11ubuntu1.1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu3.18.04.2) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
root@chris-Aether: Sat Mar 28 09:26:52 :/home/chris/Downloads
# copyq version
CopyQ Clipboard Manager v3.8.0
Qt: 5.9.5
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Ubuntu 18.04.4 LTS

I admit defeat.  The original issue wasn't serious and this failure to upgrade wasn't but getting left with a broken install was.  I've learned my lesson.

**Comment by cpsyctc2** [comment]
Oh, and, no, I wasn't going to comment every single line of that last copy and paste.  I am sure anyone who needs to can understand that despite all the formatting.  I'm sure someone can work out why for me the inline quoting of code seems to have to be imposed on every single line but probably neither that person nor I have the time!  I love FLOSS but I am learning that sometimes it's best to remember I paid nothing and walk away.  Sadly, things like the quoting do make me more reluctant to contribute by reporting issues.

**Comment by hluk** [comment]
Hmm, I think `apt` is still not installing the version from PPA because the log says:

```
copyq : Depends: libqt5core5a (>= 5.11.0~rc1) but 5.9.5+dfsg-0ubuntu2.5 is to be installed
```

The package from PPA uses the Qt version available from official repos (i.e. `5.9.5...`).

Unfortunately, I don't know how to tell `apt` not to install the incompatible version -- maybe there is some `clean` command.

**Comment by cpsyctc2** [comment]
Thanks Lukas.  If it's beyond your knowledge it's light years beyond mine.  I appreciate you trying to help.  Very best.  Chris

**Comment by hluk** [comment]
You can also try installing Flatpak package: https://github.com/hluk/copyq/blob/master/README.md#other-linux-distributions

Anyway, since this is issue with installing an incorrect package, I'm closing this.
