### ISSUE TITLE
CopyQ Icon not showing on windows 10 taskbar.

### ISSUE THREAD

**Issue by Hsam11** [hluk/CopyQ#1336]
CopyQ Icon not showing on taskbar. All other icons showing except CopQ. 

I am using windows 10

Tried everything but failed.  Is there any other way to go to options?

Thanks in advance

**Comment by hluk** [comment]
Is this same issue as in #1258? Is the app running at all?

**Comment by drwinchell** [comment]
I am seeing this issue as well (Windows 10 version 3.11.1). 
It's more of annoyance since I can go into Toolbar settings and turn it on to show it. Until it disappears again.

**Comment by hughh** [comment]
Same issue.

**Comment by hluk** [comment]
I believe this was already fixed in #1258. Please install latest CopyQ version.
