### ISSUE TITLE
CopyQ v3.10.0 : Icon rearrange when applying any strings in clipboard after PC rebooting

### ISSUE THREAD

**Issue by x69toki** [hluk/CopyQ#1337]
**Describe the bug**
CopyQ v3.10.0's icon wiil re-arrange its original position of the right-buttom Windows' state bar when applying any strings in clipboard after PC rebooting.

**To Reproduce**
1. Drag the CopyQ icon on the right-buttom Windows' state bar to the right end.
2. Go to 'CopyQ'.
3. Apply any coping  strings. (make sure it's copied)
4. Paste the string to any doc, and reboot the PC.
5. You will find the original position of CopyQ on the right-buttom Windows' state bar is CHANGED, it will always move to the left end of the Windows' state bar.
6. However, the previous version of CopyQ and the other apps' icons won't have the same problem. (Their positions are always FIXED)

**Expected behavior**
Please make the icon of CopyQ on the right-buttom Windows' state bar FIXED, not moving around.

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Application Version [v3.10.0]
 - OS [Windows 10 Pro]
- Environment [RAM: 16G, CPU: Intel i7-7770, AGP: AMD HD-8550, SSD: 256 GB]

**Comment by hluk** [comment]
I don't understand which icon do you mean. Can you provide a screenshot?

I don't think CopyQ has control over any icon order in the system.

**Comment by x69toki** [comment]
Hi Lukas,

Thanks for the reply.

I will use my cellphone to record the screen for your reference.

It will be musch better to understand my issue.  :-)

Please wait a moment, thanks in advance.

Andy



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
20/03/27
上午06:25:14

Lukas Holecek <notifications@github.com> 於 2020年3月27日 週五 上午2:30寫道：

**Comment by x69toki** [comment]
Hi Lukas,

I had sent the video via WeTransfer platform, please check it.

*Download link:*
https://wetransfer.com/downloads/ffdb8f992840984f96873a441054110220200404164519/1222f64151e0e0ac13e6a1a9b587918920200404164519/4b8f93

File Name: VID_20200405_004101.mp4

You may find the position of CopyQ's icon is no fixed like others.

Thanks in advance.

Andy




[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
20/04/05
上午01:46:02

陳Andy <x69toki@gmail.com> 於 2020年3月27日 週五 上午6:25寫道：

**Comment by hluk** [comment]
Thanks for sharing. I didn't even know you could change position of tray icons.

It's probably related to #1258 - that issue is about Windows not remembering previously set show/hide status for the tray icon.

It looks like when using new Qt libraries to build the app, some identifier/property is not correctly configured for the tray.

You can try using a binary built with older Qt version: https://ci.appveyor.com/project/hluk/copyq/builds/30554651/job/bi7n6lpdjvqy4e5x/artifacts

**Comment by x69toki** [comment]
Hi

By the way, I found the previous version (v3.9) do NOT have this problem.

The position of previous version (v3.9) is fixed, CopyQ v3.9 will remember
its previously set show/hide status for the tray icon.

Therefore, is it the NEW bug in the latest version? Will it be fixed in
next version?

Thanks for the updates, and I really appreciate for your hard working.  :-)

Andy








[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
20/04/05
下午09:34:44

Lukas Holecek <notifications@github.com> 於 2020年4月5日 週日 下午1:43寫道：

**Comment by hluk** [comment]
As I mentioned before, the app itself doesn't have any direct control over the icon position in the tray area. It's probably an issue with Qt framework -- newer versions of the app use different, more recent Qt versions.

**Comment by glolsh** [comment]
I have the same issue. I'll try app built with older Qt. Can you send bugreport to them?

**Comment by glolsh** [comment]
For now - several reboots, and it works fine. Icon is fixed!

**Comment by glolsh** [comment]
@hluk can you provide this version in your future releases? or this is one-time release with old QT?

**Comment by hluk** [comment]
I will release new versions of CopyQ with one version of Qt. But I might be able to provide builds with older Qt version if requested.

**Comment by glolsh** [comment]
Oh okay then. I need to make new issue if 3.11 gonna have this problem?

**Comment by hluk** [comment]
Just comment or reopen this one, please.

**Comment by glolsh** [comment]
3.11 same behavior. Please compile with old QT

**Comment by hluk** [comment]
> 3.11 same behavior. Please compile with old QT

Already built. See #1258. I'm closing this as duplicate.

**Comment by x69toki** [comment]
The same bug still insists in CopyQ v3.11.1

May I know how difficult it is to fix the icon's position bug?

Such bug insists in  v3.9, and still alive in v3.11.1

It's really annoying to adjust the icon position  of CopyQ after rebooting PC every time.

**Comment by hluk** [comment]
@x69toki Can you check if the build mentioned in #1258 fixes the issue?

It's not possible for me to fix this here (it's a Qt bug). I could only start building the app again with an old version of Qt.

**Comment by tukanos** [comment]
@hluk I noticed after the reboot the CopyQ position in taskbar gets inactivated and moves to the hidden items (you have to access it via the 'V' arrow.   You have to manually move it back to the visible part of the taskbar.  Is that the same bug or different one?  Did you report it to the QT upstream?
