### ISSUE TITLE
[Help on script] Save current/previous clipboard into two file, and run an (diff) command, pass those two file as arguments

### ISSUE THREAD

**Issue by zw963** [hluk/CopyQ#1338]
**Is your feature request related to a problem? Please describe.**
No, this is not a issue, i am now use copyQ a lot, day and day.
I hope copyQ can improve on some frequently use case for me.

e.g. i often need to compare two snippet code with in a diff tools.

we assume following is two successive clipboard content copy from different place.

![image](https://user-images.githubusercontent.com/549126/77676138-db344680-6fc8-11ea-953b-ae2b46bd532c.png)

For now my own naive process is:

1. copy `clipboard 1 content` into clipboard, and save as config1.json
2. copy `clipboard 2 content` into clipboard, and save as config2.json
3. assume i have a diff tool named bcomp, then run following command in command line
    
```sh
$: bcomp  config1.json config2.json
```

I guess this process can be improve a lot if combine with copyQ, following is my imagination.

1. copy `clipboard 1 content` as usual
2. copy `clipboard 2 content` as usual too
3. write a copyQ command, retrieve `clipboard 1 content` save to /tmp/copy1.txt, retrive `clipboard 2 content` save to /tmp/copy2.txt, and finally, run `bcomp /tmp/copy1.txt /tmp/copy2.txt`.

Following is my attempt.

```
[Command]
Name=Play Sound on Copy
Command="
    # How to get current() and previous() clipboard content and save to file?
     bash:
     bcomp /tmp/copy1.txt /tmp/copy2.txt"
Automatic=false
GlobalShortcut=ctrl+shift+v
Icon=\xf028
```

I spent hours for study how to use command, but still not following, following is my issue:

1.  My command is happen even on highlight on linux terminal, but i only want it happen when i press Ctrl+Shift+C(copy content into clipboard for konsole)

![image](https://user-images.githubusercontent.com/549126/77678607-6236ee00-6fcc-11ea-9df8-fc7579aa6737.png)

2. command should not effect the normally copyQ working flow, it should only happen when i press
a global hotkey. e.g. GlobalShortcut=ctrl+shift+v

3. It don't working on output clipboard content into file.

Can you help me on this? anyway, thank you in advance for patient.

**Comment by hluk** [comment]
Perhaps following command can help a bit. It stores last two items (from clipboard tab in CopyQ) in temporary files and compares them (in this case using Neovim editor).

```ini
[Command]
Command="
    copyq:
    var item1 = read(0)
    var item2 = read(1)
    
    function tempFile(content) {
        var file = new TemporaryFile()
        file.openWriteOnly()
        file.write(content)
        file.close()
        return file
    }
    
    var f1 = tempFile(item1)
    var f2 = tempFile(item2)
    var name1 = f1.fileName()
    var name2 = f2.fileName()
    execute('gnome-terminal', '--', 'nvim', '-d', name1, name2)
    
    // Wait few seconds before exiting script and deleting temporary files,
    // because the command may be executed in background.
    sleep(5000)"
GlobalShortcut=meta+alt+d
Icon=\xf0db
IsGlobalShortcut=true
Name=Diff latest items
```

**Comment by zw963** [comment]
Thank you very much for you patient help, it working like a charm!

In fact, do you consider add this a as a default command cadidation?

Same too for the awesome `C-n => down arrow`, `C-p => up arrow`.

Anyway, many users like not so expect on write own command like this,
anyway, we need more sample to familiar with it.

Following is my working example for use bcompare as diff tools, it is a property software(Window, Linux, OSX), which i use daily too. https://www.scootersoftware.com/download.php

```
[Command]
Command="
    copyq:
    var item1 = read(0)
    var item2 = read(1)

    function tempFile(content) {
        var file = new TemporaryFile()
        file.openWriteOnly()
        file.write(content)
        file.close()
        return file
    }

    var f1 = tempFile(item1)
    var f2 = tempFile(item2)
    var name1 = f1.fileName()
    var name2 = f2.fileName()
    execute('bcompare', name1, name2)

    // Wait few seconds before exiting script and deleting temporary files,
    // because the command may be executed in background.
    sleep(5000)"
GlobalShortcut=meta+alt+d
Icon=\xf0db
IsGlobalShortcut=true
Name=Diff latest items use bcompare
```

**Comment by hluk** [comment]
Nice, glad it works for you.

> In fact, do you consider add this a as a default command cadidation?

If you mean, add it as predefined command that is available in clean installation of CopyQ, then no. It's very specific and probably useful for smaller user group.

But you can create a pull request to https://github.com/hluk/copyq-commands repo if you want.

**Comment by zw963** [comment]
Hi, @hluk , i create a PR, please check. https://github.com/hluk/copyq-commands/pull/18/files

But, i have another idea after i create this PR, maybe we can support same function on UI, which make this command more useful then just select the last one, right?

![image](https://user-images.githubusercontent.com/549126/77848487-b07c0500-71f7-11ea-92bd-fc0e74224946.png)

**Comment by hluk** [comment]
> But, i still have no idea on how to get both selected items instead of the last one, can you please help improve it again? ^_^

You can use `selectedItemData(0)[mimeText]` and `selectedItemData(1)[mimeText]` to get text from first two selected items. If the first value is `undefined`, the selected item either doesn't contain text or the command is run as global shortcut. The second value can be also `undefined` if only one item is selected.

**Comment by zw963** [comment]
Hi, @hluk , it's seem like not working, following is my code.

```js
var selectedItem1 = selectedItemData(0)[mimeText]
var selectedItem2 = selectedItemData(1)[mimeText]

var item1 = null
var item2 = null

if (selectedItem1 == undefined) {
    // the selected item either doesn't contain text
    // or the command is run as global shortcut.
    // select the last two clipboard in this case.
    item1 = read(0)
    item2 = read(1)
} else {
    item1 = selectedItem1
    item2 = selectedItem2
}

function tempFile(content) {
    var file = new TemporaryFile()
    file.openWriteOnly()
    file.write(content)
    file.close()
    return file
}

var f1 = tempFile(item1)
var f2 = tempFile(item2)
var name1 = f1.fileName()
var name2 = f2.fileName()
execute('bcompare', name1, name2)

// Wait few seconds before exiting script and deleting temporary files,
// because the command may be executed in background.
sleep(5000)
```
it get following error:

![image](https://user-images.githubusercontent.com/549126/77855227-a242de80-7221-11ea-948d-97cc15d727ee.png)

i change to use `var selectedItem1 = selectedItemData(0)["text/plain"]`, it not working too, could you please check?

And another question: is there a way to alert a message to this command user, for told them some things wrong?

thank you.

**Comment by hluk** [comment]
The `execve` error looks like the `bcompare` was not found. You can check details of the error in logs (F12 shortcut from main window).

BTW, if you use the global shortcut, it will always diff the first two items.

The following command works for me.

```ini
[Command]
Command="
    copyq:
    var selectedItem1 = selectedItemData(0)[mimeText]
    var selectedItem2 = selectedItemData(1)[mimeText]
    
    var item1 = null
    var item2 = null
    
    if (selectedItem1 == undefined) {
        // the selected item either doesn't contain text
        // or the command is run as global shortcut.
        // select the last two clipboard in this case.
        item1 = read(0)
        item2 = read(1)
    } else {
        item1 = selectedItem1
        item2 = selectedItem2
    }
    
    function tempFile(content) {
        var file = new TemporaryFile()
        file.openWriteOnly()
        file.write(content)
        file.close()
        return file
    }
    
    var f1 = tempFile(item1)
    var f2 = tempFile(item2)
    var name1 = f1.fileName()
    var name2 = f2.fileName()
    execute('gnome-terminal', '--', 'nvim', '-d', name1, name2)
    
    // Wait few seconds before exiting script and deleting temporary files,
    // because the command may be executed in background.
    sleep(5000)"
GlobalShortcut=meta+alt+d
Icon=\xf0db
InMenu=true
IsGlobalShortcut=true
Name=Diff latest items
Shortcut=ctrl+d
```

**Comment by zw963** [comment]
Okay, after copy yours' code it working, but, if i edit only command part directly in copyQ command editor, it's seem like not working, anyway, great!

I update my PR, thank you. 

https://github.com/hluk/copyq-commands/pull/18/files

**Comment by brainexcerpts** [comment]
> 
> ```
> [Command]
> Command="
>     copyq:
>     var item1 = read(0)
>     var item2 = read(1)
> 
>     function tempFile(content) {
>         var file = new TemporaryFile()
>         file.openWriteOnly()
>         file.write(content)
>         file.close()
>         return file
>     }
> 
>     var f1 = tempFile(item1)
>     var f2 = tempFile(item2)
>     var name1 = f1.fileName()
>     var name2 = f2.fileName()
>     execute('bcompare', name1, name2)
> 
>     // Wait few seconds before exiting script and deleting temporary files,
>     // because the command may be executed in background.
>     sleep(5000)"
> GlobalShortcut=meta+alt+d
> Icon=\xf0db
> IsGlobalShortcut=true
> Name=Diff latest items use bcompare
> ```
> 







The above solution is great and compares the latest entries in the clipboard. Now to compare selected items you would do:





      // Get selected items
      var selected = selectedItems()
      if (selected.length !== 2) {
        popup("Please select exactly 2 items", "Error")
        abort()
      }
      
      // Read the content of selected items
      var item1 = read(selected[0])
      var item2 = read(selected[1])
      
      function tempFile(content) {
        var file = new TemporaryFile()
        file.openWriteOnly()
        file.write(content)
        file.close()
        return file
      }
      
      var f1 = tempFile(item1)
      var f2 = tempFile(item2)
      var name1 = f1.fileName()
      var name2 = f2.fileName()
      
      // Use Beyond Compare instead of nvim
      execute('bcompare', '-fv=Text Compare', name1, name2)
      
      // Wait before cleanup
      sleep(5000)

**Comment by zw963** [comment]
My solution support selected items too.
