### ISSUE TITLE
Duplicate items in sequence

### ISSUE THREAD

**Issue by JeremyWW** [hluk/CopyQ#1339]
I can't see how to allow this. Is it possible? Copying entries in a financial statement which I then need to total.

**Comment by hluk** [comment]
If you really need to make sure that the item was added to CopyQ, use a customized copy command, e.g. copy on a global shortcut to a special "Copied" tab:

```ini
[Command]
Command="
    copyq:
    try {
        tab('Copied')
        copy()
        var text = clipboard()
        add(text)
        popup('Copied', text)
    } catch(e) {
        popup('Failed to copy', e)
    }"
GlobalShortcut=meta+alt+c
Icon=\xf0ea
IsGlobalShortcut=true
Name=Copy to Tab
```

([Here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them).)

**Comment by JeremyWW** [comment]
Thanks, that works. I've just modified it as that command will place repeated copies into the text only tab that I have already. Modified code below just with the 'tab('Copied')' line removed. Look OK to you?

copyq:
try {
    copy()
    var text = clipboard()
    add(text)
    popup('Copied', text)
} catch(e) {
    popup('Failed to copy', e)
}

**Comment by hluk** [comment]
> Look OK to you?

Good with me if it works for you. :)
