### ISSUE TITLE
Text preview/editor tab size

### ISSUE THREAD

**Issue by magpie514** [hluk/CopyQ#1341]
**Is your feature request related to a problem? Please describe.**
When handling code snippets from tab-indented langs, the results can be a bit complicated to read with the default tab size.
The situation is similar in the text editor, as well.
I mostly noticed when rearranging a bunch of functions in GDScript, a python-like language with tab indentation. Since I use hard tabs (*...d-don't judge me...*), the result is a bit too stretched out. In the example it's a very simple function but more complex things with higher indentation levels are just gone from the screen. (I use 2-3 space wide hardtabs in text editors to make it nice and compact)

**Describe the solution you'd like**
An option to change hardtab size for both the preview and text editor would be pretty good. I know it's not intended to be a fully featured text editor, but when handling certain languages for a quick modification it can be a bit non-optimal.

**Describe alternatives you've considered**
*I am too old to change my habits! It's the computer's job to allow me to be lazy!*
Jokes aside, I've looked around in case there was some setting or something I could use, but there doesn't seem to be one.
Text can be filtered to make it more readable but then it'd lose the original formatting to be pasted back.

**Additional context**
Screenshot of a simple snippet I was working with.
![ksnip_20200405-203816](https://user-images.githubusercontent.com/323651/78506934-a82e4780-776c-11ea-9ffc-375e761c449d.png)
Trying to edit it, despite being a simple one, already makes things go weird with wrapping:
![ksnip_20200405-205211](https://user-images.githubusercontent.com/323651/78507253-92ba1d00-776e-11ea-8f79-5cd1d840c12b.png)

**Comment by hluk** [comment]
It looks like in Qt framework the tab size is fixed to 80 pixels:

> 
![image](https://user-images.githubusercontent.com/38054/78588462-f90e7080-783e-11ea-8ef9-de6d905dd27f.png)

I'm changing it so it's configurable, by default 8 spaces:

> 
![image](https://user-images.githubusercontent.com/38054/78588487-07f52300-783f-11ea-8c61-e520bfc2cd93.png)
