### ISSUE TITLE
Empty 'currentWindowTitle()' on Gentoo

### ISSUE THREAD

**Issue by mrozigor** [hluk/CopyQ#1342]
**Describe the bug**
I couldn't get 'Ignore password window' command to work. I found out that calling `currentWindowTitle()` returns nothing.

**To Reproduce**
Just copy something.

**Expected behavior**
`currentWindowTitle()` returns window name

**Version, OS and Environment**
CopyQ Clipboard Manager v3.10.0
Qt: 5.14.1
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Gentoo/Linux, X11, XMonad

**Comment by mrozigor** [comment]
`_NET_WM_NAME` is set correctly to `DBname.kdbx - KeePassXC` (checked it with `xprop` command).

**Comment by hluk** [comment]
It looks like this is the problem: https://unix.stackexchange.com/questions/395613/why-is-xprop-root-not-returning-net-active-window

**Comment by mrozigor** [comment]
Thank you very much. Didn't know in what direction search for answer. XMonad implements EWMH via extensions (`xmonad-contrib`). Then you have to add proper entries to config file (`~/.xmonad/xmonad.hs`):

```
import XMonad.Hooks.EwmhDesktops

(...)

main = do
  xmonad $ ewmh def
    {
(...)
```

**Comment by hluk** [comment]
Cool, thanks for posting the solution.
