### ISSUE TITLE
Is there a way to paste the second item with shortcut?

### ISSUE THREAD

**Issue by ooker777** [hluk/CopyQ#1345]
Perhaps this is doable, but I haven't found a way to do so. If it's possible, please guide me. Thank you

**Comment by hluk** [comment]
Yes, it's possible with following command ([here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)):
```ini
[Command]
Command="
    copyq:
    copy(read(1))
    paste()"
GlobalShortcut=ctrl+shift+@
Icon=\xf0ea
IsGlobalShortcut=true
Name=Paste second item
```

**Comment by ooker777** [comment]
Many thanks. Maybe you want to make it as a built-in command
