### ISSUE TITLE
Disabling opening of window at current mouse cursor location?

### ISSUE THREAD

**Issue by mishaxz** [hluk/CopyQ#1346]
Anyone know how to disable opening of the window at the current mouse cursor location?

This makes CopyQ extremely annoying to use since half the window is often off-screen.

**Comment by hluk** [comment]
Can you unset a shortcut for "Show main window under cursor" and set "Show/hide main window" instead?

![image](https://user-images.githubusercontent.com/38054/78990599-1ee58f00-7b37-11ea-86ee-e04b1b2e3911.png)

Or maybe you mean "Open windows on current screen" option (in General config tab)?

**Comment by mishaxz** [comment]
great that worked, thanks
