### ISSUE TITLE
FR: Clear clipboard contents when deleting all items from CopyQ's clipboard tab

### ISSUE THREAD

**Issue by Gitoffthelawn** [hluk/CopyQ#1348]
I would find it useful to have an option to delete the contents of the Windows clipboard when deleting all items from CopyQ's clipboard tab.

**Comment by hluk** [comment]
There is [Clear Clipboard Tab](https://github.com/hluk/copyq-commands/tree/master/Application#clear-clipboard-tab) command to clear the tab content. Append `copy("")` line to the script to clear system clipboard.

**Comment by Gitoffthelawn** [comment]
Thank you.  I created a new command, with these instructions:

> clearClipboardData; copy("")

When I select the menu item for it, I get the error:

```
Error: Process failed to start: The system cannot find the file specified.
1. clearClipboardData
2. |copy()
```

What am I doing wrong?

Also, is there a way to assign a keyboard shortcut to it for within CopyQ, but not have it be system global?

**Comment by hluk** [comment]
The full command is:

```ini
[Command]
Command="
    copyq:
    copy('')
    tab(config('clipboard_tab'))
    items = Array
      .apply(0, Array(size()))
      .map(function(x,i){return i})
    remove.apply(this, items)"
Icon=\xf2ed
InMenu=true
Name=Clear Clipboard And History
```

... and [here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them).

**Comment by Gitoffthelawn** [comment]
Thanks.  I thought it was a built-in command like "version".  I'll try adding the code.

**Comment by Gitoffthelawn** [comment]
That worked a treat.  Thank you.

So commands aren't really internal commands, but are actually very useful pre-written code snippets.  Do I have that correct?

**Comment by hluk** [comment]
> So commands aren't really internal commands, but are actually very useful pre-written code snippets. Do I have that correct?

These are basically [user scripts](https://copyq.readthedocs.io/en/latest/writing-commands-and-adding-functionality.html). There are few predefined commands in CopyQ (ready to be added when you click Add button in Command dialog F6) and some more advanced commands in [copyq-command repo](https://github.com/hluk/copyq-commands).

**Comment by Gitoffthelawn** [comment]
Makes sense.  Thank you.
