### ISSUE TITLE
FR: Add ability to delete all items from CopyQ's clipboard tab

### ISSUE THREAD

**Issue by Gitoffthelawn** [hluk/CopyQ#1349]
I would find it very useful if CopyQ had the option to delete all items from it's clipboard tab (and clear the clipboard as mentioned in https://github.com/hluk/CopyQ/issues/1348).

Right now, I have to click on the Remove button 50 times to accomplish this task.

Perhaps have Shift+Click on the Remove button remove everything.

**Comment by hluk** [comment]
There is shortcut to select all and delete selected: <kbd>Ctrl</kbd>+<kbd>A</kbd>, <kbd>Delete</kbd>

Otherwise, you can use the command mentined in https://github.com/hluk/CopyQ/issues/1348#issuecomment-614821306.

**Comment by Gitoffthelawn** [comment]
LOL! Thank you.  I wasn't aware `Select All` worked in that window.
