### ISSUE TITLE
UX/UI: Item Content window needs a tweak

### ISSUE THREAD

**Issue by Gitoffthelawn** [hluk/CopyQ#1352]
When the user opens the Item Content window, it always says "0 bytes".  This is because no formats are selected by default.  I recommend simply selecting the first format by default.  This way, the erroneous size will not be reported, data is always displayed, and the user is saved at least one click.

**Comment by hluk** [comment]
The first item is not selected because there could be a lot of data in clipboard. In some cases this slowed down showing up the dialog unnecessarily.

**Comment by hluk** [comment]
Also, it's not possible to get the size of data in clipboard without fetching the data first - that would solve many headaches.

**Comment by Gitoffthelawn** [comment]
> The first item is not selected because there could be a lot of data in clipboard. In some cases this slowed down showing up the dialog unnecessarily.

Hmmm... interesting.  Can you read the first x MB, and then show a "More..." indicator?  I get the sense from your next comment that this may not currently be possible.

Also, how about not showing any size indicator when no format is selected?

**Comment by hluk** [comment]
> Can you read the first x MB, and then show a "More..." indicator?

Nope, Qt allows me only to read the whole data for a format.

> Also, how about not showing any size indicator when no format is selected?

I will do that.

**Comment by Gitoffthelawn** [comment]
Ya, that's what it sounded like.

I guess another thing you can do is open the Content Window with just a "Loading content..." message, and then start populating the window (and select the first format) one format at a time as you get the data.

I think this would handle most cases better, although there are one or two edge cases that might be slower.

**Comment by hluk** [comment]
> I guess another thing you can do is open the Content Window with just a "Loading content..." message

That would be too difficult to implement because Qt fetches the clipboard content in GUI thread (another annoying thing) so it would block UI rendering anyway. GTK+ seems to have better clipboard access and allows to do this in non-blocking manner.
