### ISSUE TITLE
Appearance configuration UI: Matching search strings not highlighted

### ISSUE THREAD

**Issue by Gitoffthelawn** [hluk/CopyQ#1354]
In CopyQ Configuration -> Appearance, the matching search strings are not highlighted.

**Comment by hluk** [comment]
Yup, I fixed that recently (3d84d5e0f2f9e5b8be073741564bd0c80f22cd9d). Thanks for the report -- you have a good eye :).

**Comment by Gitoffthelawn** [comment]
You're welcome.  Still have 2 of them! :)
