### ISSUE TITLE
not storing url in the history 

### ISSUE THREAD

**Issue by mohitWrangler** [hluk/CopyQ#1356]
**Describe the bug**
URL copied from the Google Chrome browser address bar is not stored in the clipboard history.

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - CopyQ version -- v3.10.0
 - OS -- Linux Mint 19.1 Cinnamon
 

**Additional context**
after copying the URL exists in the clipboard (ctrl+v) works, but the URL is not stored in the clipboard history

**Comment by hluk** [comment]
Can you check if `text/plain` format is in clipboard (Ctrl+Shift+C from main window)?

Any chance you are using a custom command that would disable storing URLs or even files in the app? Or maybe a command that moves URL to different tab? (You can check command list in Command dialog with F6 shortcut from the main window.)

**Comment by mohitWrangler** [comment]
Yes, text/plain format is in the clipboard. 
All my custom commands are to open custom clipboard, there is no script to detect/manipulate URL.

Please Let me know if you need additional details.

**Comment by hluk** [comment]
Can you try launching CopyQ with `env COPYQ_LOG_LEVEL=DEBUG copyq` and checking logs after copying from Chrome? You can list all the logs with F12 shortcut from main window.

**Comment by mohitWrangler** [comment]
Hi hluk,

Thanks for following up.

Here is the log 
--- red lines --  I copied URLs (tried two times on different URLs) -- does not appear in the clipboard history
-- green lines -- when I copied some text which appears in the clipboard history

![Selection_279](https://user-images.githubusercontent.com/5771169/79990767-7234d700-847f-11ea-91c4-a73c5262c28a.png)

**Comment by hluk** [comment]
Can you share logs from Log dialog from main window (F12 shortcut)? There is usually more information from all processes.

**Comment by mohitWrangler** [comment]
Here you go,

I copied URL three times before copying the "Coronavirus: US health official warns of dangerous second wave" text

`DEBUG [2020-04-22 11:45:24.093] <Server-20049>: Server "/home/mohit/.config/copyq/.copyq_s" started.
DEBUG [2020-04-22 11:45:24.122] <Server-20049>: QtDebug: D-Bus global menu: no (:0, )
DEBUG [2020-04-22 11:45:24.127] <Server-20049>: Geometry: Window "MainWindow": Restore geometry "Options/MainWindow_geometry": --- -> ---
DEBUG [2020-04-22 11:45:24.128] <Server-20049>: Focus window is "1: mohit: env COPYQ_LOG_LEVEL=DEBUG copyq:Tilix: Default"
DEBUG [2020-04-22 11:45:24.132] <Server-20049>: Loading configuration
DEBUG [2020-04-22 11:45:24.227] <Server-20049>: QtDebug: D-Bus system tray: no (:0, )
DEBUG [2020-04-22 11:45:24.281] <Server-20049>: Configuration loaded
DEBUG [2020-04-22 11:45:24.282] <Server-20049>: Starting monitor
DEBUG [2020-04-22 11:45:24.282] <Server-20049>: Executing: copyq --clipboard-access monitorClipboard
DEBUG [2020-04-22 11:45:24.283] <Server-20049>: Starting callback: onStart
DEBUG [2020-04-22 11:45:24.283] <Server-20049>: Executing: copyq onStart
DEBUG [2020-04-22 11:45:24.285] <Server-20049>: Got save state request from session manager.
DEBUG [2020-04-22 11:45:24.334] <monitorClipboard-20059>: Clipboard formats to save: image/svg+xml, image/png, image/gif, application/x-copyq-encrypted, application/x-copyq-item-notes, application/x-copyq-item-icon, application/x-copyq-item-pinned, application/x-copyq-tags, text/plain, text/html, text/richtext, application/x-copyq-item
DEBUG [2020-04-22 11:45:24.347] <Server-20049>: Updating tray menu
DEBUG [2020-04-22 11:45:24.348] <Server-20049>: Tab "&clipboard": Loading items
DEBUG [2020-04-22 11:45:24.362] <Server-20049>: Tab "&clipboard": 1000 items loaded
DEBUG [2020-04-22 11:45:24.569] <Server-20049>: Executing: copyq eval -- runMenuCommandFilters()
DEBUG [2020-04-22 11:45:24.571] <Server-20049>: Updating tray menu
DEBUG [2020-04-22 11:45:24.595] <monitorClipboard-20059>: Ignoring unchanged selection
DEBUG [2020-04-22 11:45:24.596] <monitorClipboard-20059>: Ignoring unchanged clipboard
DEBUG [2020-04-22 11:45:30.829] <monitorClipboard-20059>: New selection owner: "Google - Google Chrome"
DEBUG [2020-04-22 11:45:30.988] <monitorClipboard-20059>: Clipboard unchanged, selection *CHANGED*. Test again in 0ms.
DEBUG [2020-04-22 11:45:30.989] <monitorClipboard-20059>: Postponing fast selection change
DEBUG [2020-04-22 11:45:30.989] <monitorClipboard-20059>: Postponing fast selection change
DEBUG [2020-04-22 11:45:30.989] <monitorClipboard-20059>: Postponing fast selection change
DEBUG [2020-04-22 11:45:30.990] <monitorClipboard-20059>: Selection changed, owner is ""
DEBUG [2020-04-22 11:45:30.990] <monitorClipboard-20059>: onMonitorClipboardChanged: foreign selection, owner is ""
DEBUG [2020-04-22 11:45:30.991] <Server-20049>: Executing: copyq onClipboardChanged
DEBUG [2020-04-22 11:45:31.145] <monitorClipboard-20059>: Clipboard unchanged, selection unchanged. Test again in 50ms.
DEBUG [2020-04-22 11:45:31.299] <monitorClipboard-20059>: Clipboard unchanged, selection unchanged. Test again in 150ms.
DEBUG [2020-04-22 11:45:31.548] <monitorClipboard-20059>: Clipboard unchanged, selection unchanged. Test again in 350ms.
DEBUG [2020-04-22 11:45:31.993] <monitorClipboard-20059>: Clipboard unchanged, selection unchanged.
DEBUG [2020-04-22 11:45:32.396] <monitorClipboard-20059>: New clipboard owner: "Google - Google Chrome"
DEBUG [2020-04-22 11:45:32.607] <monitorClipboard-20059>: Aborting getting clipboard, the data changed again
DEBUG [2020-04-22 11:45:32.609] <monitorClipboard-20059>: Clipboard unchanged, selection unchanged. Test again in 0ms.
DEBUG [2020-04-22 11:45:32.869] <monitorClipboard-20059>: Clipboard unchanged, selection *CHANGED*. Test again in 50ms.
DEBUG [2020-04-22 11:45:32.869] <monitorClipboard-20059>: Ignoring unchanged selection
DEBUG [2020-04-22 11:45:32.869] <Server-20049>: Executing: copyq onClipboardUnchanged
DEBUG [2020-04-22 11:45:33.025] <monitorClipboard-20059>: Clipboard unchanged, selection unchanged. Test again in 150ms.
DEBUG [2020-04-22 11:45:33.290] <monitorClipboard-20059>: Clipboard unchanged, selection unchanged. Test again in 350ms.
DEBUG [2020-04-22 11:45:33.743] <monitorClipboard-20059>: Clipboard unchanged, selection unchanged.
DEBUG [2020-04-22 11:45:41.381] <monitorClipboard-20059>: New clipboard owner: "My Drive - Google Drive - Google Chrome"
DEBUG [2020-04-22 11:45:41.597] <monitorClipboard-20059>: New selection owner: "My Drive - Google Drive - Google Chrome"
DEBUG [2020-04-22 11:45:41.598] <monitorClipboard-20059>: Aborting getting clipboard, the data changed again
DEBUG [2020-04-22 11:45:41.598] <monitorClipboard-20059>: Clipboard unchanged, selection unchanged. Test again in 0ms.
DEBUG [2020-04-22 11:45:41.862] <monitorClipboard-20059>: Clipboard unchanged, selection *CHANGED*. Test again in 50ms.
DEBUG [2020-04-22 11:45:41.863] <monitorClipboard-20059>: Selection changed, owner is ""
DEBUG [2020-04-22 11:45:41.863] <monitorClipboard-20059>: onMonitorClipboardChanged: foreign selection, owner is ""
DEBUG [2020-04-22 11:45:41.863] <Server-20049>: Executing: copyq onClipboardChanged
DEBUG [2020-04-22 11:45:42.018] <monitorClipboard-20059>: Clipboard unchanged, selection unchanged. Test again in 150ms.
DEBUG [2020-04-22 11:45:42.280] <monitorClipboard-20059>: Clipboard unchanged, selection unchanged. Test again in 350ms.
DEBUG [2020-04-22 11:45:42.743] <monitorClipboard-20059>: Clipboard unchanged, selection unchanged.
DEBUG [2020-04-22 11:45:47.590] <monitorClipboard-20059>: New clipboard owner: "Coronavirus: US health official warns of dangerous second wave - BBC News - Google Chrome"
DEBUG [2020-04-22 11:45:47.802] <monitorClipboard-20059>: New selection owner: "Coronavirus: US health official warns of dangerous second wave - BBC News - Google Chrome"
DEBUG [2020-04-22 11:45:47.802] <monitorClipboard-20059>: Aborting getting clipboard, the data changed again
DEBUG [2020-04-22 11:45:47.803] <monitorClipboard-20059>: Clipboard unchanged, selection unchanged. Test again in 0ms.
DEBUG [2020-04-22 11:45:48.064] <monitorClipboard-20059>: Clipboard unchanged, selection *CHANGED*. Test again in 50ms.
DEBUG [2020-04-22 11:45:48.064] <monitorClipboard-20059>: Selection changed, owner is ""
DEBUG [2020-04-22 11:45:48.064] <monitorClipboard-20059>: onMonitorClipboardChanged: foreign selection, owner is ""
DEBUG [2020-04-22 11:45:48.065] <Server-20049>: Executing: copyq onClipboardChanged
DEBUG [2020-04-22 11:45:48.222] <monitorClipboard-20059>: Clipboard unchanged, selection unchanged. Test again in 150ms.
DEBUG [2020-04-22 11:45:48.486] <monitorClipboard-20059>: Clipboard unchanged, selection unchanged. Test again in 350ms.
DEBUG [2020-04-22 11:45:48.945] <monitorClipboard-20059>: Clipboard unchanged, selection unchanged.
DEBUG [2020-04-22 11:45:50.511] <monitorClipboard-20059>: Selection is incomplete
DEBUG [2020-04-22 11:45:50.528] <monitorClipboard-20059>: Postponing fast selection change
DEBUG [2020-04-22 11:45:50.561] <monitorClipboard-20059>: Postponing fast selection change
DEBUG [2020-04-22 11:45:50.694] <monitorClipboard-20059>: Postponing fast selection change
DEBUG [2020-04-22 11:45:50.712] <monitorClipboard-20059>: Postponing fast selection change
DEBUG [2020-04-22 11:45:50.729] <monitorClipboard-20059>: Postponing fast selection change
DEBUG [2020-04-22 11:45:50.777] <monitorClipboard-20059>: Postponing fast selection change
DEBUG [2020-04-22 11:45:50.844] <monitorClipboard-20059>: Postponing fast selection change
DEBUG [2020-04-22 11:45:50.943] <monitorClipboard-20059>: Postponing fast selection change
DEBUG [2020-04-22 11:45:51.027] <monitorClipboard-20059>: Postponing fast selection change
DEBUG [2020-04-22 11:45:51.058] <monitorClipboard-20059>: Postponing fast selection change
DEBUG [2020-04-22 11:45:51.328] <monitorClipboard-20059>: Postponing fast selection change
DEBUG [2020-04-22 11:45:51.899] <monitorClipboard-20059>: Clipboard unchanged, selection *CHANGED*. Test again in 150ms.
DEBUG [2020-04-22 11:45:51.900] <monitorClipboard-20059>: Selection changed, owner is ""
DEBUG [2020-04-22 11:45:51.900] <monitorClipboard-20059>: onMonitorClipboardChanged: foreign selection, owner is ""
DEBUG [2020-04-22 11:45:51.901] <Server-20049>: Executing: copyq onClipboardChanged
DEBUG [2020-04-22 11:45:52.148] <monitorClipboard-20059>: Clipboard unchanged, selection unchanged. Test again in 350ms.
DEBUG [2020-04-22 11:45:52.593] <monitorClipboard-20059>: Clipboard unchanged, selection unchanged.
DEBUG [2020-04-22 11:45:53.119] <monitorClipboard-20059>: Clipboard *CHANGED*, selection unchanged. Test again in 0ms.
DEBUG [2020-04-22 11:45:53.120] <monitorClipboard-20059>: Clipboard changed, owner is ""
DEBUG [2020-04-22 11:45:53.224] <Server-20049>: Executing: copyq --clipboard-access synchronizeToSelection
DEBUG [2020-04-22 11:45:53.380] <monitorClipboard-20059>: Clipboard unchanged, selection *CHANGED*. Test again in 50ms.
DEBUG [2020-04-22 11:45:53.380] <monitorClipboard-20059>: onMonitorClipboardChanged: foreign clipboard, owner is ""
DEBUG [2020-04-22 11:45:53.381] <monitorClipboard-20059>: Ignoring unchanged selection
DEBUG [2020-04-22 11:45:53.381] <Server-20049>: Executing: copyq onClipboardChanged
DEBUG [2020-04-22 11:45:53.387] <Server-20049>: Executing: copyq onClipboardUnchanged
DEBUG [2020-04-22 11:45:53.420] <Server-20049>: New item: Moving existing to top
DEBUG [2020-04-22 11:45:53.516] <Server-20049>: Updating tray menu
DEBUG [2020-04-22 11:45:53.536] <monitorClipboard-20059>: Clipboard unchanged, selection unchanged. Test again in 150ms.
DEBUG [2020-04-22 11:45:53.546] <synchronizeToSelection-20149>: Synchronizing to selection: Cancelled (target is same as source)
DEBUG [2020-04-22 11:45:53.791] <monitorClipboard-20059>: Clipboard unchanged, selection unchanged. Test again in 350ms.
DEBUG [2020-04-22 11:45:54.243] <monitorClipboard-20059>: Clipboard unchanged, selection unchanged.
DEBUG [2020-04-22 11:45:59.378] <Server-20049>: Focus window is "Coronavirus: US health official warns of dangerous second wave - BBC News - Google Chrome"
DEBUG [2020-04-22 11:45:59.380] <Server-20049>: Geometry: Window "MainWindow": Restore geometry "Options/MainWindow_geometry": --- -> ---
DEBUG [2020-04-22 11:45:59.427] <Server-20049>: Raising window "Coronavirus: US health off…s of dangerous second wave - CopyQ"
DEBUG [2020-04-22 11:45:59.430] <Server-20049>: Geometry: Window "MainWindow": Restore geometry "Options/MainWindow_geometry": --- -> ---`

**Comment by hluk** [comment]
I haven't been able to reproduce it but I think I found what could cause this.

**Comment by mohitWrangler** [comment]
Thanks for looking up. 
Should I wait for the new release? Can I do something until then?

**Comment by hluk** [comment]
Probably wait for new release.

I've built [development/beta packages for Ubuntu](https://launchpad.net/~hluk/+archive/ubuntu/copyq-beta) - not sure if you can use them.
