### ISSUE TITLE
summary, shortcuts

### ISSUE THREAD

**Issue by sunberrysolar** [hluk/CopyQ#1357]
**Is your feature request related to a problem? Please describe.**
1. for long text, it is frustrating to scroll down to find the good text to paste.
2. no keyboard shortcuts to paste ?

**Describe the solution you'd like**
1. show only a summary for long text (ie 3 first lines of long text) 
2. possibility to add a shortcut for each text, and use it to paste

**Comment by hluk** [comment]
Ad 1. This is already configurable:

![image](https://user-images.githubusercontent.com/38054/79772471-68508e00-8330-11ea-962b-77cf48e6a26e.png)

Ad 2. Possible with custom commands -- see #1345, #246.

**Comment by sunberrysolar** [comment]
Ohoh! great! Thank your for this usefull soft ;)
