### ISSUE TITLE
[Request]: New command "Paste text using keystrokes"

### ISSUE THREAD

**Issue by tnilzon** [hluk/CopyQ#1359]
I think it would be useful with a command (configurable with a hotkey) to be able to paste text from CopyQ using keystrokes (simulating keyboard input). Some applications simply does not allow paste from clipboard (Ctrl+V), but keystrokes works. One example is the multimedia application "KODI" [https://kodi.tv/](url) , there paste with Ctrl+V does not work, but paste with keystrokes work.

For now I am using the autotext-application "Autokey" [https://github.com/autokey/autokey](url) which has an option to paste with keystrokes, but Autokey has no connection with the clipboard.

Operating System: Manjaro Linux 
KDE Plasma Version: 5.18.4
KDE Frameworks Version: 5.69.0
Qt Version: 5.14.2
Kernel Version: 5.6.6-1-MANJARO
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-9700K CPU @ 3.60GHz
Memory: 31,2 GiB of RAM

CopyQ version 3.10.0

**Comment by hluk** [comment]
I'm using [Decrypt and Type](https://github.com/hluk/copyq-commands/tree/master/Application#decrypt-and-type) command (presumably safer than putting password in clipboard and pasting). It works only on X11 on Linux and requires `xdotool`. I assume there could be some corner cases and characters which won't be possible to type this way.

I think `xdotool` also allowed me to paste into VM in case clipboard sharing did not work (I haven't used it in a while):

```ini
[Command]
Command="
    copyq:
    var maxChars = 16
    var delayBeetweenKeystrokesMs = 50
    
    function isModifierPressed() {
        var modifiers = queryKeyboardModifiers()
        return modifiers.length > 0
    }
    
    function typeText(slice) {
        if (isModifierPressed())
            throw 'Typing interrupted'
    
        var result = execute(
            'xdotool',
            'type',
            '--delay',
            delayBeetweenKeystrokesMs,
            slice)
    
        if (!result)
            throw 'Failed to type text'
    
        else if (result.exit_code != 0)
            throw 'Failed to type text: ' + result.stderr
    }
    
    sleep(200)
    while (isModifierPressed())
        sleep(20)
    
    var text = str(input())
    try {
        for (var i = 0; i < text.length; i += maxChars)
            typeText( text.slice(i, i + maxChars) )
    } catch (e) {
        popup(e)
    }"
HideWindow=true
Icon=\xf11c
InMenu=true
Input=text/plain
Name=Type-Paste
Shortcut=ctrl+shift+return
```

**Comment by tnilzon** [comment]
Yes, that would probably work for me.
Thanks!
