### ISSUE TITLE
Windows 10: Doesn't Auto Paste Into Admin Applications

### ISSUE THREAD

**Issue by ctsstc** [hluk/CopyQ#1361]
**Describe the bug**
The auto paste doesn't seem to work for applications that are running as administrator I've noticed.

**To Reproduce**
1. Go to start menu
2. Type in Notepad
3. Right click > Run as administrator
4. Try selecting an item to have it auto paste

**Expected behavior**
It should auto paste into the application.
Maybe an error if it knows it's trying to paste into a privileged window. Of course there would need to be an option to turn this off.

**Screenshots**
None

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - v3.7.3
 - Windows 10

**Additional context**
Running CopyQ as administrator allows it to paste into windows that are also running as administrator.

It could be nice if it had this as a startup option.
I'm not sure how to get around it nagging you at windows startup if you would like to run it, maybe it would have to be a service or something 🤮🤢

Maybe this case just needs to be added to the readme somewhere or the FAQ, but it would be nice to handle it.

**Comment by hluk** [comment]
It probably won't help here, but try updating to the latest version of CopyQ first.

> Running CopyQ as administrator allows it to paste into windows that are also running as administrator.
>
> It could be nice if it had this as a startup option.

Running CopyQ as admin is probably not a good idea.

Workaround could be to override paste action (Enter/Return shortcut) from CopyQ to invoke `copyq paste` as admin (in specific cases) -- I don't know how to do this in Windows.

> Maybe this case just needs to be added to the readme somewhere or the FAQ, but it would be nice to handle it.

This is actually the first time I hear about this - not sure if anyone else has this issue.

**Comment by ctsstc** [comment]
For quite a while I kept thinking, "I wish this had auto paste functionality like a different program I use on my Mac" Then I noticed it was pasting but only in specific windows. I was able to conclude with my basic test on notepad that if I ran notepad as admin it would not be able to auto paste, which seems like a security/sandbox issue.

**Comment by ctsstc** [comment]
I just updated to `v3.11.0` and it seems to be working now :) 🎉
