### ISSUE TITLE
Floating Clipboard Window

### ISSUE THREAD

**Issue by wada3n** [hluk/CopyQ#1362]
Hello
I hope to add a feature to opening Floating Clipboard Window without the Title Bar, and other stuff in the main window of copQ. with a search option and default value (first item) then chose the one you want to paste.
i mean something like Alfred clipboard in mac by invoking a shortcut appear just a like this:  

![App-Launcher-1 resized](https://user-images.githubusercontent.com/13304792/80317896-65591000-87fe-11ea-9b96-693ab62240c4.png)
or
![clipboard-filter](https://user-images.githubusercontent.com/13304792/80317908-786be000-87fe-11ea-840b-4a76e5878bbc.png)
Clipped elementary does this well:
![image-1_orig](https://user-images.githubusercontent.com/13304792/80319606-372cfd80-8809-11ea-8061-801510249d6c.png)

And thank you very much for this most amazing project.

**Comment by hluk** [comment]
I believe that's exactly that `copyq menu` command does.

**Comment by wada3n** [comment]
Hi @hluk 
thank you for the reply, it's fantastic, Even better than the others.
my appreciation and respect to you.

**Comment by hluk** [comment]
The menu supports only fixed number of items (specified in preferences). If you search in the menu it will search all items but again limit the number of found items.

If you need to show all items, you have to open the main window (`copyq show`).

**Comment by wada3n** [comment]
OK, thank you very much for your continued support.
