### ISSUE TITLE
CopyQ: setup.exe with hint when updating

### ISSUE THREAD

**Issue by Clemens-Ratte-Polle** [hluk/CopyQ#1363]
Hi.
To be sure not to lose all data when installing
copyq-v3.10.0-setup.exe
it would be fine if CQ would show when it recognizes its old installation and updates it without loss :)
Optionally with an installation there could be an option to perform a backup before.
thx :)

**Comment by hluk** [comment]
Handling this during installation would be probably too complicated if not impossible.

It's much easier and safer just to use [Backup On Exit](https://github.com/hluk/copyq-commands/tree/master/Scripts#backup-on-exit) command.
