### ISSUE TITLE
script command for Move to Top

### ISSUE THREAD

**Issue by harriott** [hluk/CopyQ#1364]
**Is your feature request related to a problem? Please describe.**
In `F6 Command/Global Shortcuts...` I've copied the default command `Paste as Plain Text` to a new command `ready for Pasting` from which I removed the last line `paste()`, and bound that new command to `Alt+Return`. This allows me to prepare a clipping for pasting into `gVim` in Arch Linux, (necessary because if I use a simple `Return` on a `CopyQ` selection, as I would with any other target program, it gets thrown randomly somewhere else in the `gVim` buffer - I don't know why, and that's not issue here). I'd like that prepared clipping to be also moved to the top, so that I can find it quicker next time.

**Describe the solution you'd like**
I'd like `Move to Top` (by default bound to `Ctrl+Home`) to be exposed as a script command that can be added at will.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by hluk** [comment]
I need to add a new function (`move()`) without it moving items is too complicated. So you will be able to use `move(0)` to move selected item to the top.
