### ISSUE TITLE
Search for the selected item in specific websites like google

### ISSUE THREAD

**Issue by wada3n** [hluk/CopyQ#1365]
Hi,
I am thinking of a way to create a command to search item selected in copyQ on websites such as Google, YouTube etc , by opening floating tray from the menu or by shortcut and choose the website then opens directly in the browser with the text selected.
like translate-to-english command but in first let me choose the website before opening.
This is a prototype picture of what I want
![Menu_004](https://user-images.githubusercontent.com/13304792/80432200-661ba000-88eb-11ea-9da7-4cd4774ab937.png)

Thanks again

**Comment by hluk** [comment]
Not sure how I can help, but you can use following code to let user pick from a list:

```js
var choice = dialog('.list:Search Engine', ['A', 'B', 'C'])
popup(choice)
```

See the API documentation for [dialog()](https://copyq.readthedocs.io/en/latest/scripting-api.html#Value%20dialog).

**Comment by wada3n** [comment]
Yes that is good but I want the list without borders and without the Title bar just a pop up like copyq tray menu.

**Comment by hluk** [comment]
You can use `copyq menu TAB_NAME` to open a menu for specific tab. But it's not possible to override the action on item activation (it's "paste" by default).

**Comment by wada3n** [comment]
Good, thank you.
Once again, @hluk  you deserves great praise and appreciation.

**Comment by hluk** [comment]
Actually, I'm thinking about new script function to create such custom menus. I'll try to come up with something, it should be relatively easy since most of the pieces are already in place (mainly the menu widget that supports search).

**Comment by wada3n** [comment]
Nice, I hope you do this soon. Searching through the clipboard on the internet is a great feature.
thank you very much.

**Comment by hluk** [comment]
With CopyQ v3.11.0, you can use `menuItems()` function to create simple menus.

Example command to search selected text item in the main window ([here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)):

```ini
[Command]
Command="
    copyq:
    var searchEngines = [
        {
            'name': 'Stackoverflow',
            'url': 'https://stackoverflow.com/search?q=%s',
            'icon': '\xf16c',
        },
        {
            'name': 'Github',
            'url': 'https://github.com/search?q=%s',
            'icon': '\xf09b',
        },
        {
            'name': 'DuckDuckGo',
            'url': 'https://duckduckgo.com/?q=%s',
        },
    ]
    
    var items = []
    for (var i in searchEngines) {
        var engine = searchEngines[i]
        var item = {}
        item[mimeText] = engine['name']
        item[mimeIcon] = engine['icon']
        items.push(item)
    }
    
    var i = menuItems(items)
    if (i == -1)
        abort()
    
    var text = encodeURIComponent(str(input()))
    var urlTemplate = searchEngines[i]
    var url = urlTemplate['url'].replace('%s', text)
    open(url)"
Icon=\xf002
InMenu=true
Input=text/plain
Name=Search Web
```

**Comment by wada3n** [comment]
You are a genius, Really you are a genius, great job!
I have one last request, please:
How can I open this menu just by selecting the text anywhere, and requesting this `menuItems` popup? without copying the text. 
I tried to add Global Shortcuts but it does not appear to me when requested through other programs. 
And thank you again.

**Comment by hluk** [comment]
Maybe something like following command which copies the selected text for you. The copy operation might not work in all apps, alternative would be just remove `copy()` from the command and just get the current clipboard content.

```ini
[Command]
Command="
    copyq:
    var searchEngines = [
        {
            'name': 'Stackoverflow',
            'url': 'https://stackoverflow.com/search?q=%s',
            'icon': '\xf16c',
        },
        {
            'name': 'Github',
            'url': 'https://github.com/search?q=%s',
            'icon': '\xf09b',
        },
        {
            'name': 'DuckDuckGo',
            'url': 'https://duckduckgo.com/?q=%s',
        },
    ]
    
    // Copy selected text.
    copy()
    var text = str(clipboard())
    if (!text)
        abort()
    popup('Search Text', text)
    
    var items = []
    for (var i in searchEngines) {
        var engine = searchEngines[i]
        var item = {}
        item[mimeText] = engine['name']
        item[mimeIcon] = engine['icon']
        items.push(item)
    }
    
    var i = menuItems(items)
    if (i == -1)
        abort()
    
    text = encodeURIComponent(text)
    var urlTemplate = searchEngines[i]
    var url = urlTemplate['url'].replace('%s', text)
    open(url)"
GlobalShortcut=meta+shift+f
Icon=\xf002
Input=text/plain
IsGlobalShortcut=true
Name=Search Web
```

**Comment by wada3n** [comment]
Yes, yes, this is it.
You do not know how happy I am with this work,  I wish you all the best.
you are such a great person.
Thank you very much and have a good day.

**Comment by hluk** [comment]
I'm glad I could help. :)

Thanks for the idea. Having the custom menu will be useful for future commands and it can probably improve some existing ones (like [snippets](https://github.com/hluk/copyq-commands/blob/master/Global/snippets.ini)).

**Comment by wada3n** [comment]
Yes of course.
Especially for research, or perhaps for opening other programs such as Zeal Offline Documentation, And do a search directly inside it with the copied text.
choose from email list, to send email maybe with default email client, And much more.
Thank you again.

**Comment by zz0rk** [comment]
@hluk Thank you so much! This is brilliant.
