### ISSUE TITLE
Show/Hide main window with holding mouse|touchpad right click.

### ISSUE THREAD

**Issue by haykokalipsis** [hluk/CopyQ#1367]
I found this feature in windows utility called arsClip, and i can't imagine any workflow without it. Most of the time it's a lot more natural and handy to strigger how/hide window with right click, then it is with shortcut. Especially for people on laptops, who dont have mouses with middle click. And its very natural when using mouse||touchpad with index finger and clicking on the field||textbox to not move your hand to click the keyboard shortcut, but instead just move your thumb a little and hold right touchpad button. I apologise for my English.

**Comment by hluk** [comment]
I don't think it's possible to do with Qt framework which CopyQ uses. Implementation would be probably too complex on multiple platforms.

There are probably utilities on some systems which allow to run a user command when you hold the right mouse button. In case of CopyQ you can run `copyq show` to popup main window.
