### ISSUE TITLE
Feature Request: Hide system tray and taskbar icon (Windows)

### ISSUE THREAD

**Issue by acicovic** [hluk/CopyQ#1368]
**Is your feature request related to a problem? Please describe.**
On Windows, when hiding CopyQ's tray icon it appears instead in the taskbar. I would like to be able to hide the icon from both locations as I only use CopyQ with the keyboard.

**Describe the solution you'd like**
Add an option to hide both tray icon and program taskbar icon.

Thanks! :)

**Comment by hluk** [comment]
It's already supported, but the option is not visible in UI since some users may lose control over the app.

To enable the option execute following command (you can do it using Action dialog -- F5 shortcut):

```
copyq config hide_main_window_in_task_bar true
```

**Comment by fxdave** [comment]
It seems like it is not working. I'm not using a tray (Arch + BSPWM), and I cannot SIGTERM the main window because it cannot find the tray (obviously). I have to SIGKILL it which is not so comfortable to do.

**Comment by hluk** [comment]
> It seems like it is not working. I'm not using a tray (Arch + BSPWM), and I cannot close the main window because it cannot find the tray (obviously). I have to kill it which is not so comfortable to do.

I think you can use `copyq config hide_main_window true` instead - or enable the "Hide main window" option in Layout tab in Preferences.

**Comment by fxdave** [comment]
Thanks, I tried this, but this hides the window instantly. It just flashes. I want to be able to use it but I also want to close it. I'm not sure whether this is the expected behavior.

**Comment by hluk** [comment]
> Thanks, I tried this, but this hides the window instantly. It just flashes. I want to be able to use it but I also want to close it. I'm not sure whether this is the expected behavior.

Maybe it's an issue with the "Close When Unfocused" option. You can disable that with `copyq config close_on_unfocus false`.

**Comment by fxdave** [comment]
Thanks @hluk !
With these options it worked:
copyq config hide_main_window true
copyq config close_on_unfocus false
