### ISSUE TITLE
Items' content may scroll a little when selected. 

### ISSUE THREAD

**Issue by RoadToDream** [hluk/CopyQ#1371]
**Describe the bug**
Text with more than one line is scrollable a bit in the item box, which make it a little hard to scroll the entire list. 

**To Reproduce**
1. copy 2 paragraphs 
2. scroll in the list

**Expected behavior**
Text in the item box should not be scrollable. 

**Screenshots**
![Screen Recording 2020-05-02 at 10 58 15 AM](https://user-images.githubusercontent.com/8088354/80872000-0f53f480-8c64-11ea-8af6-717e9798131c.gif)

**Version, OS and Environment**
CopyQ Clipboard Manager v3.11.0
Qt: 5.13.2
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: macOS 10.15

**Additional context**

**Comment by hluk** [comment]
The item size is not calculated correctly. There was a workaround for guessing the correct text size but it doesn't seem to be needed with newer Qt versions -- let me try to remove that.

Thanks for the report.
