### ISSUE TITLE
Portable CopyQ Installation Update - data lost

### ISSUE THREAD

**Issue by HyperCriSiS** [hluk/CopyQ#1376]
**Expected behavior**
After I updated my portable CopyQ Installation from v2.8.3 to v3.11.0 I lost my actual data.
Tabs, Clipboard data, Global commands, just everything is set back to a very old status. (Many month ago)

**Version, OS and Environment**
- Windows 10 Enterprise 1909
- CopyQ v3.11.0

Thanks,
Hyper

**Comment by hluk** [comment]
How did you update the app?

**Comment by HyperCriSiS** [comment]
I just extract all files from the archive into the CopyQ folder.
Doing this for a long time and never got any issues.

**Comment by hluk** [comment]
> I just extract all files from the archive into the CopyQ folder.

This is not a good idea. Some old files could be overwritten, but if a file was removed or renamed in the new version, it will be left in the folder. In case of libraries which could have been removed or renamed this can cause issues.

> Doing this for a long time and never got any issues.

Version 2.8.3 is very old (over 3 years) but I try to keep versions backwards compatible.

My guess is that the data is being pulled from different location for some reason.

What you can try: Backup `config` subfolder first, and unpack the new version to clean folder and copy `config` there.

Do you have "unins000.exe" file in your portable folder?

Can you share logs (F12 from the main window)?

**Comment by HyperCriSiS** [comment]
If 2.8.3 is 3 years old, I must have had a newer version because I updated regularly.

Dunno how this happend but the config folder got splittet. I consolidated all data now and everything is back.

Thanks!!
