### ISSUE TITLE
'After item is activated > Paste to current window' is not working

### ISSUE THREAD

**Issue by Shakil-Shahadat** [hluk/CopyQ#1378]
This was okay in 3.10. I'm on windows 8.1.

Thank you.

**Comment by hluk** [comment]
Please share logs (F12 shortcut from main window).

**Comment by Shakil-Shahadat** [comment]
On further testing, it works sometimes, doesn't work most of the time.

[copyq.log](https://github.com/hluk/CopyQ/files/4596130/copyq.log)

**Comment by Shakil-Shahadat** [comment]
I think the problem is another software here. It's called 'Comfort Keys'. Closing the issue for now.
