### ISSUE TITLE
Make clipboard contents in caption bar optional

### ISSUE THREAD

**Issue by Ralkniv** [hluk/CopyQ#1379]
I'd like to suggest that you make showing the clipboard contents (or <Empty> - if it is empty) in the caption bar optional that can be enabled/disabled in the Preferences. I also suggest that you make optional animation of the icon in the system tray to suit particular user preferences.

**Comment by hluk** [comment]
You can use [No Clipboard in Title and Tool Tip](https://github.com/hluk/copyq-commands/tree/master/Scripts#no-clipboard-in-title-and-tool-tip) command (see [README](https://github.com/hluk/copyq-commands/blob/master/README.md) for information how to use install the command).

**Comment by Ralkniv** [comment]
Many thanks Lukas, this solves it :-). But I just wonder, wouldn't it be
easier to add a simple checkbox to Preferences, for those less skilled in
how to proceed, instead of creating a separate INI file? Just a
suggestion...

Also, is there any way to stop the icon in the systray from animating?

Thanks and best regards,
David Vinklar

**Comment by hluk** [comment]
Instead of adding and option, I would rather make the app extensible through scripting and make it easier for any user to install the scripts/commands.

**Comment by hluk** [comment]
> Also, is there any way to stop the icon in the systray from animating?

I'll probably remove the feature because it's difficult to maintain and causes other issues.

See: https://github.com/hluk/CopyQ/issues/1382#issuecomment-629369861
