### ISSUE TITLE
SHOW PREVIEW button is missing in recent versions

### ISSUE THREAD

**Issue by Columbus1000** [hluk/CopyQ#1380]
I've noticed in several recent versions that the **SHOW PREVIEW button has disappeared** from the row of buttons where it formerly lived. The **F7 shortcut still works fine**, so it's not a drastic problem but unless it's been deliberately removed for some reason, I felt I should report it.

I don't know if it's a clue or even related, but the position of the Show Preview entry in **Preferences > Shortcuts > Application** has changed position by a considerable amount.

If all this is by design, or is an already reported issue, please forgive me for raising it again; I couldn't find an existing report of it and I did search for one.

As far as I can tell, one of the last versions that DID have the button intact was **v3.9.3-1-gc3f095ce** and it has disappeared at some point since that version. I will now attempt to attach **some screencaps demonstrating this** which is something I haven't tried on Github before, so I hope it works.

As always, Lukas, thanks for a fabulous and constantly improving application!

![1 Show Preview button missing in app](https://user-images.githubusercontent.com/60309420/81474193-5169d100-9236-11ea-8276-7cc1b98700ba.jpg)
![2 Show Preview button NOT missing in app](https://user-images.githubusercontent.com/60309420/81474200-5dee2980-9236-11ea-9c5d-57b9cd63cc64.jpg)
![3 Show Preview button missing](https://user-images.githubusercontent.com/60309420/81474215-6cd4dc00-9236-11ea-8304-055dd7833d6d.jpg)
![4 Show Preview button NOT missing](https://user-images.githubusercontent.com/60309420/81474223-79593480-9236-11ea-8520-0bafdfa9514f.jpg)

**Comment by hluk** [comment]
Oh, this is a side effect of moving the "Show Preview" action from Item menu to File menu. But now it's only possible to enable it using a shortcut or from the File menu.

I'll add a script function to toggle the preview - this way it would also be possible to reorder the action in the toolbar.
