### ISSUE TITLE
copyq quits when starting from command line using nohup

### ISSUE THREAD

**Issue by dln949** [hluk/CopyQ#1383]
Ubuntu 18.04.4, gnome shell 3.28.4, copyq 3.2.0

When I start copyq from the terminal with this command:  

nohup copyq

copyq starts, and the icon appears in the tray, as expected.  But, when I then close the terminal, copyq also ends.  

In addition, the command /usr/bin/copyq in the startup application does not start copyq when Ubuntu starts.  

If I manually start copyq from the gnome shell/Ubuntu application menu, copyq starts and runs fine.

**Comment by hluk** [comment]
Oh, it's handling SIGHUP the same way as SIGINT and SIGTERM ... I guess that's not correct.

> In addition, the command /usr/bin/copyq in the startup application does not start copyq when Ubuntu starts.

How is CopyQ started? Having `~/.config/autostart/copyq.desktop` with `Hidden=False` and `X-GNOME-Autostart-enabled=true` usually works.

Any error/warning in logs (F12 shortcut from main window or `copyq logs`)?

**Comment by dln949** [comment]
copyq logs produces this error message:  

ERROR: Cannot connect to server! Start CopyQ server first.


I also attach a screenshot of the startup command, which is this:  
![Screenshot from 2020-05-14 14-47-49](https://user-images.githubusercontent.com/8601150/81979313-5cd04a00-95f2-11ea-8797-386d603b2c37.jpeg)

**Comment by hluk** [comment]
That error could mean that it's trying to pass some arguments that CopyQ doesn't understand.

Is there `~/.config/autostart/copyq.desktop` file? If so, what does it contain?

**Comment by dln949** [comment]
Here is the contents of the .desktop file:  

[Desktop Entry]
Name=CopyQ
Exec=sh -c "sleep 75 && /usr/bin/copyq"
Icon=copyq
GenericName=Clipboard Manager
# The rest is taken from Klipper application.
Type=Application
Terminal=false
X-KDE-autostart-after=panel
X-KDE-StartupNotify=false
X-KDE-UniqueApplet=true
Categories=Qt;KDE;Utility;
GenericName[af]=Klipbord Program
GenericName[x-test]=xxClipboard Toolxx
Comment=A cut & paste history utility

Hidden=False
X-GNOME-Autostart-enabled=true
Name[en_US]=CopyQ


(Note:  I did not copy into this all the GenericName and Comment lines that are in many, many different languages.)

**Comment by hluk** [comment]
Why do you use `sleep 75`? (75 seconds delay before starting copyq.)

**Comment by dln949** [comment]
While having to work from home, there is a gnome shell extension I use to help me.  But, that extension takes a long time to start.  (The maintainer said he fixed the problem for a newer version of gnome shell that I do not have, once I migrate to Ubuntu 20.04 then I won't face this problem.)  Because of this, if I let other programs - like copyq, but not only copyq - start too soon, then gnome shell crashes.  So, for copyq (and other programs at startup) I put in a delay.  

P.S.:  The past couple days copyq has been consistently starting with no problem.  I do not know why/what has changed.  But, it still has the problem of not continuing to run if started from the command line with nohup.

**Comment by hluk** [comment]
I'm fixing the `nohup` issue. Thanks, for the report.
