### ISSUE TITLE
I lose all the item on the Clipboard

### ISSUE THREAD

**Issue by heywolf15** [hluk/CopyQ#1384]
I crash the OS, it's restarting and all the item gone when I check it

 - Application Version 3.11.1
 - OS Windows 10

Can I restore it?

**Comment by hluk** [comment]
Can you first back up the configuration and data? See: [Where to find saved items and configuration?](https://copyq.readthedocs.io/en/latest/faq.html#where-to-find-saved-items-and-configuration)

Check if there are any non-empty data files (`*.dat`).

Check if there are any non-empty temporary data files (`*.tmp`). These are used during saving.

See application logs for any errors or warning after start (F12 shortcut from main application window).

Also, verify if plugins are loaded correctly -- you should see them enabled in Item configuration tab.

**Comment by heywolf15** [comment]
I'm already using it for new items 
I forgot to report that my other tabs are safe, only the clipboard tab gone
theres .ini.CR448 with empty data and others null
I see many warning and errors

**Comment by hluk** [comment]
That looks like some corrupted data, maybe other applications access the files or some other data corruption happened.

I don't think I can do anything about that. CopyQ tries to be careful when storing and restoring its data.

But definitely check out the documentation about backups: https://copyq.readthedocs.io/en/latest/backup.html

**Comment by heywolf15** [comment]
Thank you
