### ISSUE TITLE
command-line to selection ?

### ISSUE THREAD

**Issue by mckellyln** [hluk/CopyQ#1389]
Hi,
Thank you foe awesome copyq!
This is really a QUESTION, not an issue or a feature request (yet).
I'm on ubuntu 18.04
I use copyq copy on the command line to copy data to the clipboard, works great.
Is there a way, either through configuration or a plugin or however, to also copy/sync that data to the X11 selection ?  I think it goes the other way automatically ?
thx again,
-m

**Comment by hluk** [comment]
See the "Clipboard Manipulation" checkboxes in Configuration dialog. I think you want to enable "Paste clipboard with mouse".

**Comment by mckellyln** [comment]
Hi,
Thanks.  I have it enabled.  Here is what I mean:
```
% echo "selection" | xsel -i -p
% copyq clipboard
selection
% copyq selection
selection

% echo "clipboard" | xsel -i -b
% copyq clipboard
clipboard
% copyq selection
clipboard
```
That looks good, but then -
```
% echo "foo" | xsel -i -p  <- just to reset it to something else ...

% echo "selection" | copyq copy -
% copyq clipboard
selection
% copyq selection
foo
```
So in this case a copyq command-line copy only copies to the clipboard.
Is there any way to use copyq command-line to sync the selection ?
thx again,
-m

**Comment by hluk** [comment]
Ah, yeah, `copyq copy ...` won't do anything extra, only copy the text to clipboard. You need to call `copyq copySelection ...` to copy to X11 selection. Or use something like:

```bash
echo "selection" | copyq "copy(input()); copySelection(input())"
```

**Comment by mckellyln** [comment]
Awesome!
@hluk thank you so much.
Closing.
