### ISSUE TITLE
global shortcuts not working on Fedora 32

### ISSUE THREAD

**Issue by bkedryna** [hluk/CopyQ#1390]
Hi. I've been using copyq for a couple of years using Fedora on vbox. It was mostly working great (a few months ago some issue with copied text on windows not getting into copyq manifested, but it wasn't a huge deal and everything else worked fine). Today I upgraded from Fedora 30 to Fedora 32 and now I can't open copyq with a shortcut anymore. When I run "copyq show", it opens, but when I use my shortcuts, nothing happens. Also this is printed to the console when I try to set different shortcuts:
Warning: Failed to set global shortcut "Ctrl+`" for command "Show/hide main window".
Warning: Failed to set global shortcut "Ctrl+F1" for command "Show main window under mouse cursor".

**To Reproduce**
1. Type "copyq show"
2. Click File->Preferences->Shortcuts
3. Set a shortcut for "Show/hide main window" to Ctrl+`
4. See error on the console. Switch windows, then press ctrl and `. Main window doesn't pop up like it used to in Fedora 30

**Version, OS and Environment**
CopyQ Clipboard Manager v3.11.1
Qt: 5.13.2
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Fedora 32 (Workstation Edition)

**Comment by hluk** [comment]
It's because global shortcuts (among other things) are not supported by Wayland. See: https://github.com/hluk/CopyQ/issues/27#issuecomment-549766568
