### ISSUE TITLE
Prevent Empty Clipboard?

### ISSUE THREAD

**Issue by metal450** [hluk/CopyQ#1391]
Apparently there's an issue in FreeDesktop (Linux) where in many apps, if you copy something to the clipboard, then quit that app without pasting, the clipboard contents are lost.  See:

https://wiki.ubuntu.com/ClipboardPersistence
https://bugs.launchpad.net/ubuntu/+bug/11334

The given workaround is to use a clipboard manger like klipper, which has an option "prevent empty clipboard." Is there a similar way to emulate this behavior in CopyQ?

Specifically, when I copy something from one of these offending apps & then quit, the Linux clipboard is empty but CopyQ does have the item available as its first entry; that makes it available, but rather than discovering the Linux clipboard is empty, then re-copying it manually from CopyQ, it would be great if there were a way to ensure that CopyQ's first item remains in the system's clipboard - in other words, "prevent empty clipboard," like in klipper :)

**Comment by hluk** [comment]
You can use [Reset Empty Clipboard/Selection command](https://github.com/hluk/copyq-commands/tree/master/Scripts#reset-empty-clipboardselection) (it works pretty well for me). Read the [README](https://github.com/hluk/copyq-commands/blob/master/README.md) file in the repo on how to install the command.

**Comment by metal450** [comment]
Perfect! Thanks :)
