### ISSUE TITLE
Notification font sizes no longer respected

### ISSUE THREAD

**Issue by Jessamynn** [hluk/CopyQ#1393]
Hi, the notifications that appear when copying text no longer will show at the font size I've selected in theme manager.

I just updated from an old version of CopyQ (v. 3.9.1) to the latest (v. 3.11.1) and immediately noticed that notifications will now only show at the default font size (I believe 8 pt), instead of whatever size I choose (I typically set it at 10 or 12 to make it easier to quickly read).

The theme manager will respect other changes, such as colors and backgrounds etc, but it won't respect font size changes for some reason. I've tried a handful of different fonts, default system fonts, no change.

I don't believe any other settings have changed, and I've fiddled around but no luck. Any ideas?

**Comment by hluk** [comment]
Fixing. This is caused by a misconfiguration in the new style sheets.

You can fix it by replacing `fontString` to `notification_font` in `themes/notification.css` in your CopyQ installation.
