### ISSUE TITLE
Clipboard content from cmdline shown in item list ?

### ISSUE THREAD

**Issue by mckellyln** [hluk/CopyQ#1394]
Hi,

Thanks for great CopyQ.
This is a QUESTION, not a problem.  I didn't seem to find it in the doc/faq.
I have Tab for storing clipboard set to &clipboard.  I am on Ubuntu 18.04
Everything 'works' - but is there a way to have cmdline clipboard content shown in the item list ?
For example if I select some text in a browser with the mouse the content shows up in the item list.
But if I copyq copy <some text> - it does not show up in the item list - it does show up as the title of the item list window - but not in the item list itself.
Is there a way to get this form of saving to the clipboard to show in the item list ?

thx,
-m

**Comment by mckellyln** [comment]
These do not show in the item list:
```
echo fooo | copyq copy -
echo baar | copyq copySelection -
```
But these do -
```
echo fooo | xsel -i -p
echo baar | xsel -i -b
```
Is there a way to use copyq cmdline to save content and have it show in item list ?
Something like -
```
copyq "copy(input()); ???)"
```
I'll keep reading the docs.
thx,
-m

**Comment by mckellyln** [comment]
ok, I think add() does it -
```
copyq "copy(input()); add(input());"
```
thx again for Copyq :-)
-m

**Comment by mckellyln** [comment]
@hluk one quick ques if you can, is there a way to add a application shortcut (not global) to be like Return, say Ctrl-C so that it moves to the top, copies it to the clipboard and hides the window ?
Return is great and Ctrl-C + Esc are ok but a left-handed way to do it with 1 key would be awesome.
The more I use and learn about CopyQ the more awesome it is!.
thx so much,
-m

**Comment by hluk** [comment]
I think that's normal behavior of the app - or at least, it can be configured (in History config tab).

![image](https://user-images.githubusercontent.com/38054/83104740-a8d2c280-a0b9-11ea-98fa-241e5890aad7.png)

If you need a command to do that:

```ini
[Command]
Command="
    copyq:
    var text = input()
    copy(text)
    copySelection(text)
    move(0)"
HideWindow=true
Icon=\xf102
InMenu=true
Input=text/plain
Name=Move to Top and Copy
Shortcut=return
```

Feel free to open new issue on github for these request - it would be easier to find this for others.

Thanks. :)

**Comment by mckellyln** [comment]
Thanks so much, will do.
-m
