### ISSUE TITLE
Remove all items also remove from clipboard and selection ?

### ISSUE THREAD

**Issue by mckellyln** [hluk/CopyQ#1397]
Hi,
Thank you for CopyQ, I use it 100s of times each day.
Just a question really -
If use \<Del\> to remove all items from the main window item list I still find some data in the X11 clipboard and selection.
Is there a way to have it be removed from the X11 clipboard and selection when removing everything from the CopyQ item list ?  I think I could edit/change/replace the \<Del\> Application shortcut with a new one that ensures the data is wiped from the X11 clipboard and selection ?
thx,
-m

**Comment by hluk** [comment]
Here is slightly modified [Clear Clipboard Tab](https://github.com/hluk/copyq-commands/tree/master/Application#clear-clipboard-tab) to handle clearing clipboard, selection and clipboard history tab:

```ini
[Command]
Command="
    copyq:
    copy('')
    copySelection('')
    tab(config('clipboard_tab'))
    items = Array
      .apply(0, Array(size()))
      .map(function(x,i){return i})
    remove.apply(this, items)"
Icon=\xf2ed
InMenu=true
MatchCommand=copyq: size() || fail()
Name=Clear Clipboard Tab
```

**Comment by mckellyln** [comment]
Thanks.  I will set about learning more copyq scripting!
I will try to make a Remove be Remove until there is one item left and them Remove is this above.
take care,
-m

**Comment by hluk** [comment]
> I will try to make a Remove be Remove until there is one item left and them Remove is this above.

I think you just need to change `0` to `1` to avoid deleting the first item (index `0`).

**Comment by mckellyln** [comment]
Hi,
I think this works well, if it's correct -
```
copyq:
if (size() == 0) {
    toggle()
} else {
    remove()
    if (size() == 0) {
        copy('')
        copySelection('')
        tab(config('clipboard_tab'))
        toggle()
    }
}
```
CopyQ is so cool!
take care,
-m
