### ISSUE TITLE
copyq add(input()) but only if not already in list ?

### ISSUE THREAD

**Issue by mckellyln** [hluk/CopyQ#1402]
Hi,
Thanks for awesome CopyQ
Not a problem but just a question.
I am looking through the copyq-commands to try and find something similar.
Is there an AddUnique() function or a way to check if text is already (as an exact match) in the list of items before calling add(input()) ?
I just want to avoid duplicates in the item list.
thx,
-m

**Comment by hluk** [comment]
One solution is to look through existing items.

You can add new function with this script command:

```ini
[Command]
Command="
    addUnique = function(textData) {
        var text = str(textData)
        for (var i = 0; i < size(); ++i) {
            if ( str(read(i)) == text )
                return;
        }
        add(textData);
    }"
Icon=\xf067
IsScript=true
Name=Add Unique
```

You can use it as `addUnique(input())`.

It could be slow depending on the number of items in the tab.

**Comment by mckellyln** [comment]
@hluk thanks so much.
-m
