### ISSUE TITLE
Unable to open main window

### ISSUE THREAD

**Issue by woobhurk** [hluk/CopyQ#1408]
Hello, I just try CopyQ and want to enjoy its features. But I CANNOT open its main window after installation. The steps I followed:

1. Install CopyQ on D:\xxx
2. Open CopyQ and it shows an icon on the tray
3. Click, double click and right click on the icon, but nothing happens

Then I uninstall CopyQ and try the portable version (.zip). Well, I'm able to see its main window, then I open its settings, and it has no response until I kill it. I'm sad and open it again, then the magic things happened as above.

My OS info: Windows 10 Education 1803 (build 17134.1550)

**Comment by hluk** [comment]
Can you execute following command from terminal? It should show main window near mouse pointer.

```
copyq showAt
```

**Comment by Woobhurk** [comment]
> Can you execute following command from terminal? It should show main window near mouse pointer.
> 
> ```
> copyq showAt
> ```

Oh, nice. It works! But this method is a little complex. And when I open settings or other dialog, it's still not respoding for a long time. I don't whether it is because of my slooow computer. I'll try on my own computer this weekend.
Thanks!

**Comment by hluk** [comment]
Can you check if there are any errors in log (F12 shortcut from the main window)?

I wonder if main window is opening outside of visible screen area when you click the tray icon - there is some code that should handle this but maybe it's misbehaving.

**Comment by Woobhurk** [comment]
The problem that it doesn't show main window disappears today. But it still runs with no responds. Almost all the operations which opens a dialog will cause CopyQ not responding. I don't know why.

Here is the log, all the log content repeats the following:

```
ERROR [2020-06-18 09:05:04.942] :    gpg: error opening lockfile '/c/Users/wbh/.gnupg/C:\Users\wbh\AppData\Roaming\copyq\copyq.pub.lock': No such file or directory
ERROR [2020-06-18 09:05:04.942] :    gpg: lockfile disappeared
```

Regards. 😊

**Comment by woobhurk** [comment]
Well! I found the cause of this problem! It's caused by my System Variable. I added all executable paths of git to `Path`, such as `%GIT%/bin`, `%GIT%/usr/bin`, etc. And then I removed all of them except the basic items, and CopyQ works perfectly.

Thanks very much. I love this tool ; )
