### ISSUE TITLE
Notification text is broken before LF (line feed) or CRLF (carriage return, line feed)

### ISSUE THREAD

**Issue by Gitoffthelawn** [hluk/CopyQ#1409]
This is on the borderline between a bug report and a feature request.

Currently, in the CopyQ notification, when it displays the contents of the clipboard, lines are broken at characters such as dashes instead of using all the available width (as specified in the settings).

I'm guessing a simple CSS ruleset will improve this for everyone (if it is also desired by @hluk and others).

Is there any consensus for making this change?  If not, would it be best to be an option? In the meantime, can a line of CSS code can be added to change this (and to where would the code be added)?

**Comment by hluk** [comment]
CopyQ relies on Qt framework to break/wrap the lines in widgets (and notifications). I don't think it can be easily fixed by using a style sheet ([the subset that Qt uses is very limited](https://doc.qt.io/qt-5/stylesheet-reference.html)).

**Comment by Gitoffthelawn** [comment]
Hmmm... I was hoping for something like the CSS `white-space` property (https://developer.mozilla.org/docs/Web/CSS/white-space).

I see QT has `spacing`, but I somehow doubt that will help.

What about `min-width`?

**Comment by hluk** [comment]
Oh, you meant that the line should not be broken at all?

The `min-width` would work but it will use unnecessary screen space.

Changing [the code that adjust the size](https://github.com/hluk/CopyQ/blob/638366af14686f842948ddc7a464689bd6a03a4a/src/gui/notificationdaemon.cpp#L140) would probably help. But I tried few changes and still have no idea if I'm missing some method call or the call order is wrong. Possibly a Qt bug.

**Comment by Gitoffthelawn** [comment]
Yes. Likely over 50% of what I cut and paste are URLs.  I have the CopyQ notification set to be sufficiently wide to handle displaying most URLs in one line, but CopyQ breaks them up into small multi-line fragments that are difficult to read/recognize.

Thanks for your efforts on this.

**Comment by Gitoffthelawn** [comment]
I just tried a quick example.  I copied the link to this issue to the clipboard via CopyQ:

`https://github.com/hluk/CopyQ/issues/1409`

The entire URL is just 40 characters, but CopyQ broke it up into 3 lines in its notification. :(

**Comment by hluk** [comment]
If you are on Windows, can you try [this build](https://ci.appveyor.com/project/hluk/copyq/builds/33534124/job/ic7csgbu6klgttg2/artifacts)? You can retry to open the notification with opening Action dialog (F5 shortcut), entering `copyq popup https://github.com/hluk/CopyQ/issues/1409` and pressing OK (or Apply).

Automatic line wrapping in Qt label widgets is definitely not good in some cases. The new build disables the feature if the text would fit the maximum width.

**Comment by Gitoffthelawn** [comment]
Yes, I will test that build for you.  Thanks for creating it.  I promised to perform testing on some other projects first, but I will get to this as soon as I possibly can.

**Comment by Gitoffthelawn** [comment]
Do you still need this tested, or just test the new release when you publish it?

I will hopefully have some time this weekend or at the end of next week.

**Comment by hluk** [comment]
I've tested this with some synthetic texts. Feel free to test it and report back if you have time.

(Not sure when I'll be able to make a new release.)

**Comment by Gitoffthelawn** [comment]
Thanks. I'll try it this weekend if I can make the time.  This week was, let's just understate it and say, *challenging*.
