### ISSUE TITLE
Right hand modifier key interference

### ISSUE THREAD

**Issue by beefeater7** [hluk/CopyQ#1412]
**Describe the bug**
Using modifier keys for certain tasks may prevent the command from functioning.

**To Reproduce**
1. Use Windows
2. Add "paste as plain text" to your commands
3. Bind it to control+v
4. Open text editor
4. First, enter the shortcut quickly: control+v, release immediately. Works
5. Then, do a "lazy paste": hold down control and v, or just control.
    * Now it gets interesting
    b. If you used left control: Works
    c. Right control: doesn't paste

If you bind to Alt+v instead and use that, the same problem occurs. This behavior means trouble for windows machines with AltGr modifier (which internally means LCtrl + RAlt).  AltGr will indeed suffer from this issue.

**Expected behavior**
It took some time to figure this one out. You clearly have accounted for this problem already, so just extend the key-up behavior from left side to the right. 

**Version, OS and Environment**
CopyQ Clipboard Manager v3.11.1
Qt: 5.13.2
Compiler: GCC
Arch: i386-little_endian-ilp32
OS: Windows 10 (10.0)

**Comment by hluk** [comment]
On Windows, CopyQ sends key release for the modifier keys (related to #178):

https://github.com/hluk/CopyQ/blob/497a8894d45d0b69081b84c6b5eb9a19f8eed549/src/platform/win/winplatformwindow.cpp#L166-L176

On Linux/X11, it waits instead for the keys to be release:

https://github.com/hluk/CopyQ/blob/497a8894d45d0b69081b84c6b5eb9a19f8eed549/src/platform/x11/x11platformwindow.cpp#L95-L104

Maybe the second way would work better on Windows.

**Comment by hluk** [comment]
Can you test the behavior with [this build](https://ci.appveyor.com/project/hluk/copyq/builds/33620678/job/oasr69bo2loumw44/artifacts)?

**Comment by beefeater7** [comment]
It works well. Chalk it up to a QT bug?

**Comment by hluk** [comment]
It's not related to Qt. It's just different behavior - the new build will wait for the key modifiers to be released - releasing keys automatically is probably not a good idea.
