### ISSUE TITLE
[Menu] as modifier

### ISSUE THREAD

**Issue by beefeater7** [hluk/CopyQ#1414]
**Is your feature request related to a problem? Please describe.**
When I first dug into the keymaps to figure out a workflow, I tried to set the tray menu to Win+V and override the OS clipboard manager, however Win10 doesn't seem to let through that keystroke. My next thought was: Menu+V, because Menu works like Win: You get context menu only on key-up, permitting its use as a hotkey. The semantics are fitting and more modifiers are always nice.

However Menu couldn't be bound as combo key in the Shortcuts dialog. 

**Describe the solution you'd like**
Treat Menu like Win/Meta key: As a modifier.

**Comment by hluk** [comment]
[Qt doesn't recognize Menu key as modifier](https://doc.qt.io/qt-5/qt.html#Modifier-enum) so this would be difficult to implement.

I don't have any need to implement this, but if anyone wants to give it a try, the code would ideally go first into https://github.com/hluk/qxtglobalshortcut first.
