### ISSUE TITLE
suggestion: separate options for theme color effects

### ISSUE THREAD

**Issue by elig0n** [hluk/CopyQ#1420]
currently setting colors for tabs, tool bar and menus appear under one selectable option in Appearance configuration.

**Comment by hluk** [comment]
Please use style sheets if you want to have more control over the styling. I would like to make the Appearance configuration simpler, not more complex.

The style sheets (`.css` files) are installed with the app. You can override them by creating same files under `themes` sub-directory in [config directory](https://copyq.readthedocs.io/en/latest/faq.html#where-to-find-saved-items-and-configuration).
