### ISSUE TITLE
latest 3.2.0 - use ppa or ubuntu repo ?

### ISSUE THREAD

**Issue by mckellyln** [hluk/CopyQ#1422]
Hi,
Just a QUESTION -
I'm on Ubuntu 18.04 and I've been using your ppa:
ppa:hluk/copyq
but then just noticed the 3.2.0 version is out and not (yet?) in the ppa,
and that it seems perhaps now the copyq pkg is available for Ubuntu 18.04 without your ppa ?
Is that correct ?  Should I remove the ppa and use the standard repo going forward ?
thanks so much for copyq, I use it everyday and it is awesome,
-m
PS I plan to start looking into a plugin to run the c++filt command on selected item before storing it in list.

**Comment by hluk** [comment]
Version 3.11.1 is the latest one ([3.2.0 is from Feb 18, 2018](https://github.com/hluk/CopyQ/releases/tag/v3.2.0)). See: https://github.com/hluk/CopyQ/releases

**Comment by mckellyln** [comment]
@hluk - ok, thanks - I just saw it and thought 20, not 2, sorry!
