### ISSUE TITLE
copyq pipe no longer works

### ISSUE THREAD

**Issue by reagle** [hluk/CopyQ#1423]
```
╰─➤  copyq --version
CopyQ Clipboard Manager v3.11.1
Qt: 5.13.2
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: macOS 10.15
```

Typing the command you suggest in #1057 does not place anything into the copyq stack/buffer.

```
─➤  echo "Some text" | copyq copy -
true
```

**Comment by hluk** [comment]
`copyq` only copies a text into clipboard.

If you want to add something to the tab, you can run:

```
echo "text" | copyq add -
```
