### ISSUE TITLE
Shortcuts claim screen estate in Commands dialog

### ISSUE THREAD

**Issue by beefeater7** [hluk/CopyQ#1425]
**Describe the bug**
Minimum width expands to accommodate shortcut UI elements. It can get unwieldy:
![Annotation 2020-07-01 180129](https://user-images.githubusercontent.com/10468970/86266520-a0dcd580-bbc5-11ea-960f-cd28d0ce4a11.png)

**To Reproduce**
1. Go to Commands
2. Paste this: 
```
[Command]
Name=Screen Eater
IsGlobalShortcut=true
Icon=\xf15b
GlobalShortcut=a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,x,y,z
```
3. Enjoy

**Expected behavior**
Horizontal scrollbar?

**Version, OS and Environment**
```
CopyQ Clipboard Manager v3.11.1-73-gbb504f4b
Qt: 5.13.2
Compiler: GCC
Arch: i386-little_endian-ilp32
OS: Windows 10 (10.0)
```

**Comment by hluk** [comment]
I'm trying to add the scrollbar, but layouts in Qt are sometimes very difficult.

I might end up creating some dynamic grid layout for this instead.

**Comment by hluk** [comment]
Interestingly, toolbar widget works quite nicely:

![image](https://user-images.githubusercontent.com/38054/86488367-129d5680-bd61-11ea-842e-ba344958e765.png)
