### ISSUE TITLE
CRLF in INI messes up import

### ISSUE THREAD

**Issue by beefeater7** [hluk/CopyQ#1426]
**Describe the bug**
Loading INI scripts does not trim whitespace if body code uses CRLF for end of line.

Happens only on file loading, not by way of paste.

**To Reproduce**
1. Using Git for Windows
2. Pull repo 'copyq-commands'
3. Try using [Load Commands...] in Commands dialog:
![file-load](https://user-images.githubusercontent.com/10468970/86390567-963f4080-bc98-11ea-9ec6-022ff4a2fff5.png)
4. Result:
![crlf](https://user-images.githubusercontent.com/10468970/86390381-3d6fa800-bc98-11ea-8913-a72b514eef98.png)

**Expected behavior**
Pasting gives this, also using Unix linebreaks.
![expected](https://user-images.githubusercontent.com/10468970/86390747-edddac00-bc98-11ea-81a8-85e38b67c6f0.png)

**Version, OS and Environment**
```
CopyQ Clipboard Manager v3.11.1-73-gbb504f4b
Qt: 5.13.2
Compiler: GCC
Arch: i386-little_endian-ilp32
OS: Windows 10 (10.0)
```

**P.S.**
Exporting to INI produces mixed-EOL file, CRLF in INI part LF in code. This imports fine

**Comment by hluk** [comment]
Fixing. Thanks for the report!
