### ISSUE TITLE
qwindowsvistastyle.dll missing on Windows installed client

### ISSUE THREAD

**Issue by beefeater7** [hluk/CopyQ#1427]
**Describe the bug**
Installed vs Portable
![image](https://user-images.githubusercontent.com/10468970/86481517-78351700-bd50-11ea-9f27-5864dcb881a7.png)

**To Reproduce**
1. Install CopyQ, open it
2. Exit, open portable version
3. Compare

**Expected behavior**
Right side looks pretty much native. I had no idea CopyQ or Qt could look this good.

**Version, OS and Environment**
Installed
```
CopyQ Clipboard Manager v3.11.1-73-gbb504f4b
Qt: 5.13.2
Compiler: GCC
Arch: i386-little_endian-ilp32
OS: Windows 10 (10.0)
```
Portable
```
CopyQ Clipboard Manager v3.11.1
Qt: 5.13.2
Compiler: GCC
Arch: i386-little_endian-ilp32
OS: Windows 10 (10.0)
```

**Comment by hluk** [comment]
Looks like the installed version is a development one - taken from [AppVeyor](https://ci.appveyor.com/project/hluk/copyq/history)?

Can you check if some files are missing in the installed version?

You can try uninstalling the app, removing the CopyQ folder in "Program Files", and installing again. Maybe there are some leftover conflicting libraries (thought this should be handled by the installer).

**Comment by beefeater7** [comment]
The UI always looked like that. I just reinstalled the stable and it looks the same as left side.

I'll look into the files.

**Comment by beefeater7** [comment]
Alright, I found the problem!
>You can try uninstalling the app, removing the CopyQ folder in "Program Files", and installing again. Maybe there are some leftover conflicting libraries (thought this should be handled by the installer).
No, I tried that now and the bad UI remained. However, with some detective work the `C:/Program Files (x86)/CopyQ/styles/qwindowsvistastyle.dll` was missing. I just dropped in the folder and it displays right now.

**Comment by hluk** [comment]
Thanks for finding the problem.

Fixed version: https://ci.appveyor.com/project/hluk/copyq/builds/33959112/job/5w1fh6x2j0pfpast/artifacts
