### ISSUE TITLE
move() doesn't work

### ISSUE THREAD

**Issue by beefeater7** [hluk/CopyQ#1428]
**Describe the bug**

**To Reproduce**
1. Using the following:
```
[Command]
Name=Scratchpad
Command="
    copyq:
    tab('foobar')
    if (count() == 0) { add('a', 'b', 'c') }
    selectItems(0)
    move(1)
    popup(read(0, 1, 2))"
IsGlobalShortcut=true
Icon=\xf15b
Shortcut=shift+f4
GlobalShortcut=shift+f4
```
2. Try it. Run as many times as you like, same output:
```
c
b
a
```
Selected items don't move.

**Expected behavior**
```
b
c
a
```
then
```
c
b
a
```
and back again.

**Version, OS and Environment**
```
CopyQ Clipboard Manager v3.11.1-73-gbb504f4b
Qt: 5.13.2
Compiler: GCC
Arch: i386-little_endian-ilp32
OS: Windows 10 (10.0)
```

**Additional context**
I also tried this in portable to have a clean environment, but even run through Sandboxie it seems to use resources from the installed version. Anyway, same issue.

**Comment by hluk** [comment]
This is not a bug. `move()` works with selected items, so it's intended to work only from the app (not with a global shortcut).

See: https://copyq.readthedocs.io/en/latest/scripting-api.html#selected-items

**Comment by beefeater7** [comment]
I question this decision. `selectItems` works fine when the window is unfocused, so why not `move`? I'd like to control my tab without opening it. 

Anyway, I can't get it to work in the application either.

```
[Command]
Name=Move in Application
Command="
    copyq:
    tab('foobar')
    show('foobar')
    if (count() == 0) { add('a', 'b', 'c') }
    selectItems(2)
    move(0)"
Input=text/plain
InMenu=true
Icon=\xf15b
Shortcut=shift+f4
```
Result...
![image](https://user-images.githubusercontent.com/10468970/86581962-29ba8f00-bf81-11ea-9b5e-f24eea061bcb.png)

Expected: b, a, c

Note also that move() actually works when you select the items **manually.**

**Comment by hluk** [comment]
There was no reason to provide selected items since with global shortcuts the window is probably not visible anyway.

This list of selected items was meant to be static so it keeps the selection at the time a command was launched and avoids modifying it even if user or a command selects different items.

I can change it so that `selectItems()` in the command changes the list of selected items. This would be useful for other commands that work with selection.

**Comment by beefeater7** [comment]
Interesting. Yeah, that would make sense I think. 

If we are proceeding with the assumption:
* Either window is open, or it's not
* Item "selection" is just an interface thing
    - Not available if window not open
...then disable `selectItems` for global context also, to avoid confusion?

As far as `move` goes, I guess a global equivalent would be nice. That veers into "feature" territory...
