### ISSUE TITLE
backslashes "\" disappear when joining iteams

### ISSUE THREAD

**Issue by royharoush** [hluk/CopyQ#1429]
When using the join command shown here
https://copyq.readthedocs.io/en/latest/command-examples.html
![image](https://user-images.githubusercontent.com/8113056/86495265-4c7e5500-bd81-11ea-96e7-6712f94fcabf.png)

items with backslashes have their backslashes stripped away. 
This is frustrating when joining items with backslashes like windows folders or Base64 that can contain this character.

![image](https://user-images.githubusercontent.com/8113056/86495310-864f5b80-bd81-11ea-8a08-5f916f5d1ca9.png)

**To Reproduce**
import the command from the url.
select 2 items that have backslahes in them and use the command (typically space).
watch the backslashes go into the void.

**Expected behavior**
not sending the backslashes into the void :)

**Version, OS and Environment**
Windows 10 64bit
Copqy version v3.10.0-53-g1139102d 
But this has been happening for years over multiple versions, I just got upset enough now to report it.

As always, thank you ! without copyq i'd be lost in space of text and forgotten memories.

**Comment by hluk** [comment]
Fixed. Thanks for the report.

CopyQ is interpreting the backslash as part of an escape sequence (e.g. `\n`, `\t`) unless it appears after `--` the argument list.
