### ISSUE TITLE
CopyQ 3.12 not building on F33

### ISSUE THREAD

**Issue by gbcox** [hluk/CopyQ#1436]
The build information is here:
https://koji.fedoraproject.org/koji/taskinfo?taskID=47072691

Build for F32 is fine, but I need to get F33 fixed before I can push.  I noticed python3 error in build log (below) and I know that Fedora is switching to python3.9 for F33, so perhaps there is some incompatibility.  Here is the Python3.9 announcement:
https://fedoraproject.org/wiki/Changes/Python3.9

End of build log shows:
make[1]: Leaving directory '/builddir/build/BUILD/CopyQ-3.12.0'
make: *** [Makefile:152: all] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.Q6eAkb (%build)
RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.Q6eAkb (%build)
Child return code was: 1
EXCEPTION: [Error()]
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.8/site-packages/mockbuild/util.py", line 776, in do_with_status
    raise exception.Error("Command failed: \n # %s\n%s" % (command, output), child.returncode)
mockbuild.exception.Error: Command failed: 
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/copyq.spec

**Comment by hluk** [comment]
Oh, it's due to this error:

```
[ 63%] Linking CXX shared module ../libitemtext.so
cd /builddir/build/BUILD/CopyQ-3.12.0/plugins/itemtext && /usr/bin/cmake -E cmake_link_script CMakeFiles/itemtext.dir/link.txt --verbose=1
/usr/bin/c++ -fPIC -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wno-long-long -DNDEBUG -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -shared  -o ../libitemtext.so CMakeFiles/itemtext.dir/itemtext_autogen/mocs_compilation.cpp.o CMakeFiles/itemtext.dir/__/__/src/common/mimetypes.cpp.o CMakeFiles/itemtext.dir/__/__/src/common/sanitize_text_document.cpp.o CMakeFiles/itemtext.dir/__/__/src/common/textdata.cpp.o CMakeFiles/itemtext.dir/__/__/src/item/itemwidget.cpp.o CMakeFiles/itemtext.dir/itemtext.cpp.o  /usr/lib64/libQt5Widgets.so.5.14.2 /usr/lib64/libQt5Test.so.5.14.2 /usr/lib64/libQt5Gui.so.5.14.2 /usr/lib64/libQt5Core.so.5.14.2 
/builddir/build/BUILD/CopyQ-3.12.0/qxt/qxtglobalshortcut_x11.cpp:36:13: fatal error: qpa/qplatformnativeinterface.h: No such file or directory
   36 | #   include <qpa/qplatformnativeinterface.h>
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/copyq.dir/build.make:347: src/CMakeFiles/copyq.dir/__/qxt/qxtglobalshortcut_x11.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

**Comment by gbcox** [comment]
Thanks!  I was going to send you a message letting you know that this was a Fedora Land issue, because it dawned on me to try the previous release with F33, and it failed also.  qpa/qplatformnativeinface was moved from qt5-qtbase-devel to qt5-qtbase-private-devel for F33.  I'm going to see if there is a list or something I can subscribe to for notifications of stuff like this.  It should have been flagged when F33 was staged - maybe it was and I missed it.

**Comment by hluk** [comment]
>  qpa/qplatformnativeinface was moved from qt5-qtbase-devel to qt5-qtbase-private-devel for F33.

Ah, good to know - I couldn't figure out which package contains the file now.
