### ISSUE TITLE
Copying re-selected Windows files

### ISSUE THREAD

**Issue by elig0n** [hluk/CopyQ#1439]
If I copy a windows file I can immediately go to some folder and paste it.
But if I select another entry from the clipboard (for example with next() or previous() action scripts global shortcuts) but then get back to selecting the file (which appears as file:// link) then windows will no longer recognize it is a file and will not paste it.

**Comment by hluk** [comment]
I believe this is explained in FAQ: [How to reuse file paths copied from a file manager?](https://copyq.readthedocs.io/en/latest/faq.html#how-to-reuse-file-paths-copied-from-a-file-manager)
