### ISSUE TITLE
Paste pinned items without opening main window

### ISSUE THREAD

**Issue by ahtutejlo** [hluk/CopyQ#1441]
Is it possible to add a global hotkey for pasting pinned items? For example, one of the first 9 items can be pasted by ctrl+option+command+1..9

**Comment by hluk** [comment]
You can use [Select Nth Item command](https://github.com/hluk/copyq-commands/tree/master/Global#select-nth-item).

**Comment by ahtutejlo** [comment]
Thank you. I just added paste() in the and that was what I looked for.
