### ISSUE TITLE
Unable to upgrade to 3.12 due to plugin dependency / plugins do not appear to be updated

### ISSUE THREAD

**Issue by robertstrom** [hluk/CopyQ#1442]
Hello,

I noticed that there was a newer version than the Mint Software manager offered so I tried to install the Flatpak version and the GUI would not start (it seems that may already be a known issue) so I reverted back to the standard apt install from the Software Manager (v 3.10.0).

I am running Linux Mint Cinnamon 20,04 so then I added the copyq repository

sudo add-apt-repository ppa:hluk/copyq

and then ran sudo apt update and sudo apt uprgade and I am unable to do so due to what I believe to be an issue with the copyq plugins.

I am getting this message when I attempt to update

(base) rstrom@rstrom-XPS-15-9550:~$ sudo apt-get --with-new-pkgs upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  copyq
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

Please let me know if there is anything that I can do at this time or when I might be able to update to the lastest version.

Thanks,

Robert

**Comment by hluk** [comment]
The PPA contains only `copyq` package which already contains plugins. You have to uninstall `copyq-plugins` to avoid conflicts.

**Comment by robertstrom** [comment]
That did the trick!

Thank you very much / really like the program. I have been using Clipmate on Windows since the mid-1990's. That is a pretty awesome program but it is not maintained any more (still works though). This is by far the closest thing that I have found to be a potential replacement for that program and it is cross platform (I use Windows, Mac, and Linux).

Thanks for a very nice program!

Robert
