### ISSUE TITLE
[Feature] Clean history list

### ISSUE THREAD

**Issue by LLKoder** [hluk/CopyQ#1443]
First of all, let me say thanks to the author. Your app is the best. :)

I have not found where I can do that and 'cause I suggest a feature. To make Checkbox for cleaning the history list (on closing, PC sleeping, idle time, etc).

It needs for personal security - let say user copy important information. Information will show in the history list and will stay there to clipboard limit. It is not safe.

**Comment by hluk** [comment]
There are some suggestions in https://github.com/hluk/CopyQ/issues/1063. Does that help?

**Comment by LLKoder** [comment]
It looks like this is what I needed - Save Items. Thanks.
I have not found information about this function in the manual. Also, there is not a hint.
What does this function do? It saves items into the file to disk when uncheck - to memory. Am I right?

**Comment by hluk** [comment]
If "Store Items" is uncheck, items in the tab will be kept only in memory. So unloading the tab or exiting the app will basically remove all the items.

**Comment by LLKoder** [comment]
Thanks a lot again. :)
