### ISSUE TITLE
Emoji display issue

### ISSUE THREAD

**Issue by wada3n** [hluk/CopyQ#1446]
Hello, Hello, thank you for this masterpiece again.

**Describe the bug**

As for the emoji display, there is a small issue the main copyq window, they appear as symbols and sometimes only squares, while through the Tray icon, emojis appear fine as in the Screenshot.

The same issue for copyq menu, they appears symbols without colors or just squares.

**Screenshots**
![2020-07-22_13-41](https://user-images.githubusercontent.com/13304792/88178762-c9834880-cc22-11ea-95ca-0ce69031455e.png)
![Tooltip_006](https://user-images.githubusercontent.com/13304792/88178765-cab47580-cc22-11ea-8540-45b170f6c07b.png)

**Version, OS and Environment**
 - Application Version: v3.12.0
 - OS: Ubuntu 20.04
 - Desktop environment: Gnome
 - WM: Mutter

**Comment by hluk** [comment]
I believe this depends on support for those characters in the default font the application uses.

**Comment by wada3n** [comment]
Hi @hluk.
Strangely, it works in Tray while in the main window it does not work!
Are they not calling the same font?

**Comment by hluk** [comment]
Hmm, then it is probably a bug in Qt (there are [quite a few](https://bugreports.qt.io/browse/QTBUG-70750?jql=project%20%3D%20QTBUG%20AND%20text%20~%20%22emoji%20font%22)) - not sure if I can do anything this in the app.

**Comment by hluk** [comment]
I can fix it locally (in Fedora) after using following in `~/.config/fontconfig/fonts.conf`:

```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
 <match target="pattern">
    <edit name="family" mode="prepend_first">
      <string>Noto Color Emoji</string>
    </edit>
  </match>
</fontconfig>
```

The above uses "Noto Color Emoji" font. You need to restart the app after the change and perhaps even the desktop environment.

**Comment by wada3n** [comment]
Very cool, now it works fine.
I just have a question: does this change not affect entire fonts in the system?

**Comment by hluk** [comment]
It should affect most of the apps, but I'm not sure what other means Gnome or Gtk apps use.

You can add something like the following (under the `match` element) so the configuration applies only to CopyQ:

```xml
  <test name="prgname">
    <string>copyq</string>
  </test>
```

**Comment by wada3n** [comment]
Aha!
meaning that effect especially Qt apps, but GTK apps deals with system customization!?

Every time I come to something and I learn many other things from you, thank you my friend
