### ISSUE TITLE
Tray window position + Search

### ISSUE THREAD

**Issue by lkrnac** [hluk/CopyQ#145]
Hi,

first of all I have to say that this is the best clipboard manager for
linux I tried so far.

But I was using Ditto few years under widows and I am missing few features
even in CopyQ.

```
1. Tray window appears on mouse position. It would be better to appear on
text cursor position (configurable?).
2. Ditto's search feature is very handy, when you start typing text in tray
window.
```

Thanks much for good work.
sitko

**Comment by hluk** [comment]
Implementation for searching in menu is in branch `search_tray`.

Top of the menu now looks like this:
![image](https://cloud.githubusercontent.com/assets/38054/22022349/e03536dc-dcc1-11e6-9994-195ccd7d3a8f.png)

and if you start typing some text:
![image](https://cloud.githubusercontent.com/assets/38054/22022357/eb1f49de-dcc1-11e6-9a87-447945b4f1e1.png)

(<kbd>Backspace</kbd> or <kbd>Delete</kbd> to clear the search.)

The only problem is that the key hints (underlined letters in menu, e.g. 0, 1, 2 etc. for items) can be only activated if you hold <kbd>Alt</kbd> or <kbd>Ctrl</kbd> key. So to select third item you have to use <kbd>Alt</kbd>+<kbd>2</kbd>.

You can test it on [Windows](https://ci.appveyor.com/project/hluk/copyq/build/job/wofo74s4pc65f7mq/artifacts).

**Comment by lkrnac** [comment]
Is there also Linux build available

**Comment by hluk** [comment]
@lkrnac Packages for Linux are [here](http://download.opensuse.org/repositories/home:/lukho:/copyq/) -- pick package with version "2.8.2.r21.gf5a0d987".

**Comment by Jiehong** [comment]
Hi,

What about the 1. of this issue?

Are we still in the same state in 2017 compared to 2014 as to detect the current cursor position on screen?

How do ibus/fcitx know where the current cursor is to display the window of candidates when one writes in Japanese for example?
Perhaps this could work without accessibility being correctly implemented everywhere?

**Comment by hluk** [comment]
I think it would require to install some libraries and set up input method to be able to get text cursor position from. I don't see how it can work on all supported platforms.

I updated the `menu()` script function so it's possible to pass it coordinates where the menu should pop up. So you can implement it yourself using a command. For example following command uses Python to get mouse cursor position and show CopyQ menu at that position.

```ini
[Command]
Command="
    python:
    tab = 'clipboard'
    numberOfItems = 10
    
    from os import environ
    from subprocess import call
    from tkinter import Tk
    
    position = Tk().winfo_pointerxy()
    copyq = environ['COPYQ']
    call([copyq, 'menu', tab, str(numberOfItems), str(position[0]), str(position[1])])
    "
GlobalShortcut=ctrl+shift+e
Icon=\xf016
Name=Show Menu Under Mouse Cursor
```

**Comment by Jiehong** [comment]
Thanks for this information!

**Comment by hluk** [comment]
Here is crazy command to open menu at text cursor location.

It relies on the fact that in most apps cursor disappears or changes shape if the editor is unfocused. Unfortunately this **doesn't work for all apps** and OSes (e.g. Chromium web browser).

It requires CopyQ 3.0.0 and [ImageMagick](https://www.imagemagick.org/script/download.php) to find text cursor on screen.

```ini
[Command]
Command="
    copyq:
    tab = 'clipboard'
    numberOfItems = 10
    
    menuOffset = [4, 10]
    waitForDifference = 20
    threshold = 50
    imageFormat = 'bmp'
    
    function executeOrAbort(name) {
      var result = execute.apply(this, arguments)
      if (!result || result.exit_code != 0) {
        popup('Failed to run \\'' + name + '\\' utility',
              result ? result.stderr : '')
        abort()
      }
      return result.stdout
    }
    
    function toggleMenuAndTakeScreenshot() {
      menu(tab, 1, 9999, 9999)
      sleep(waitForDifference)
    
      var imageData = screenshot(imageFormat)
    
      var tempFile = new TemporaryFile()
      tempFile.open()
      tempFile.write(imageData)
      tempFile.close()
    
      return tempFile
    }
    
    var f1 = toggleMenuAndTakeScreenshot()
    var f2 = toggleMenuAndTakeScreenshot()
    
    var output = executeOrAbort(
        'convert',
        imageFormat + ':' + f1.fileName(),
        imageFormat + ':' + f2.fileName(),
        '-compose', 'difference',
        '-composite',
    
        // Apply some filters on difference to find text cursor.
        '-threshold', threshold + '%',
        '-morphology', 'Erode', 'rectangle 1,15',
    
        '-format', '%@',
        'info:')
    
    var trimBox = str(output).split('+')
    var x = Number(trimBox[1]) + menuOffset[0]
    var y = Number(trimBox[2]) + menuOffset[1]
    menu(tab, numberOfItems, x, y)"
GlobalShortcut=ctrl+shift+e
Icon=\xf016
Name=Show Menu Under Text Caret
```
