### ISSUE TITLE
Inkscape copy warning message bug

### ISSUE THREAD

**Issue by jonpatterns** [hluk/CopyQ#1451]
**Describe the bug**
Copying in Inkscape causes Inkscape to open warning message.

**To Reproduce**
1. Open Inkscape document, or open new and create object
2. Copy object - either using ctrl-c or menu
3. Warning message shown by Inkscape (object is correctly added to the clipboard)

**Expected behavior**
Object copied to clipboard without triggering Inkscape message.  Disabling clipboard storing in CopyQ is a workaround solution (no message in Inkscape, but also object (obv.) not copied to clipboard).

**Screenshots**

![Inkscape error warning](https://user-images.githubusercontent.com/525951/89164115-8e600e00-d56e-11ea-9723-f0b1229e8528.png)

```
Traceback (most recent call last):
  File "ink2canvas.py", line 72, in <module>
    Html5Canvas().run()
  File "/usr/share/inkscape/extensions/inkex/base.py", line 123, in run
    self.save_raw(self.effect())
  File "/usr/share/inkscape/extensions/inkex/base.py", line 146, in save_raw
    self.save(self.options.output)
  File "ink2canvas.py", line 36, in save
    self.walk_tree(svg_root, canvas) bug
  File "ink2canvas.py", line 58, in walk_tree
    class_name = node.TAG.capitalize()
  File "/usr/share/inkscape/extensions/inkex/elements/_base.py", line 96, in TAG
    assert self.tag_name
AssertionError
```
**Version, OS and Environment**
CopyQ Clipboard Manager v3.11.1
Qt: 5.14.2
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Manjaro Linux XFCE

Inkscape 1.0 (4035a4fb49, 2020-05-01)
Pango version: 1.44.7

**Comment by hluk** [comment]
That's a bug in Inkscape - probably triggered when a client is requesting a clipboard data (looks like Inkscape is doing some conversion to a different image format).

You might be able to reproduce it with xclip, something like:

```
xclip -selection clipboard -t image/png -o > /dev/null
xclip -selection clipboard -t text/html -o > /dev/null
```
