### ISSUE TITLE
[vi mode] starting search with / places character in the search bar

### ISSUE THREAD

**Issue by laur89** [hluk/CopyQ#1458]
**Describe the bug**
When vi mode is enabled, then slash key (`/`) focuses the search bar; but as it currently stands, it also places the slash character as the input, which is incorrect behavior as user would then need to backspace to delete it.

**To Reproduce**
1. Go to preferences->General
2. Enable vi style navigation
3. Show your clipboard
4. Press `/` to activate search

**Expected behavior**
Search input field is activated. If nothing had been searched before, then the input field should simply be active, no character placed in it.
If something is already typed in search box, then the result is unclear. Either
a) same as before, ie input field activated and cleared; or
b) input field activated with previous input as-is; think this makes the most sense.

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Application Version v3.12.0
 - Linux
 - i3 wm

**Additional context**
Think we should seek some consistency between vi & regular modes.
In regular mode, if we
a) search something
b) Esc to clear
c) ctrl+f again

then note the previously searched pattern is placed in the input field. Maybe vi mode should replicate this behavior, so if user has searched something beforehand, cleared it (by Esc), and enters search again via `/` then maybe previous pattern should be preset in the input field.

**Comment by hluk** [comment]
Fixing. Thanks for the report!
