### ISSUE TITLE
CopyQ dissapears after wake up

### ISSUE THREAD

**Issue by lkrnac** [hluk/CopyQ#146]
After wake up from hibernate/sleep, CopyQ disappears from system tray. I have to start it again.
OS: Linux Mint Maya
CopyQ version: 1.9.3

Is there any log file to troubleshoot the crash?

**Comment by scottkosty** [comment]
lkrnac, can you reproduce with the latest version of CopyQ?

**Comment by lkrnac** [comment]
Can confirm that I didn't observe this problem for a while. My current version is v2.1.0. (Using automatic updates via PPA repository).
