### ISSUE TITLE
Crashing 3.12.0 bad_alloc

### ISSUE THREAD

**Issue by mbakstars** [hluk/CopyQ#1462]
Crashes on export. Must restart program.

**To Reproduce**
1. Go to 'File'
2. Click on 'Export'
3. Select All or just tabs
4. Crashes

**Expected behavior**
Doesn't crash, creates export file.

**Version, OS and Environment**
 - Application Version 3.12.0
 - Windows 10 Enterprise

**Additional context**
Log: 
ERROR [2020-08-19 10:31:25.564] <Server-36136>: Exception: std::bad_alloc
ERROR [2020-08-19 10:32:26.394] <Server-42100>: Exception: std::bad_alloc
ERROR [2020-08-19 10:33:11.128] <Server-24156>: Exception: std::bad_alloc

All commands save "Ignore items with no....." have been turned off for now, try different tabs still crashes. Did a ton of importing and exporting over time. Work pc to home pc. Was trying to move to the standalone [usb drive] to prevent having to do this every day. Log attached.
[fdsfds.txt](https://github.com/hluk/CopyQ/files/5098605/fdsfds.txt)

**Comment by Trung0246** [comment]
Can confirm, crashed while exporting with the same error 
![image](https://user-images.githubusercontent.com/11626920/90697187-ad2ef780-e232-11ea-8fe1-3facdf92020f.png)

**Comment by hluk** [comment]
Does CopyQ crashes when you click on the checkbox "All" in Export dialog?

**Comment by hluk** [comment]
Changing options in the export dialog shouldn't cause the crash.

Is this happening **after** you click OK in the export dialog and select the file name for the export? In such case `std::bad_alloc` makes sense, since it indicates that there is not enough memory to load all the tabs for export.

I should revise the export function to export data gradually and unload exported tabs from memory.

**Comment by mbakstars** [comment]
It happens after you click okay. 

My use case is for data, templates for email, data formatting, screenshots for fiscal, contacts, random 2nd brain for the day, and kids school info. With COVID changes. 

I am trying to use a thumb drive, to prevent syncing issues/cleanup. Is there a way to run the program on my pcs, and TO the thumb drive so that I can move data right now? (Drag drop). I am using Windows 10 Enterprise on all. With a 4gb thumb drive.

Many thanks. I do have a ton saved in there. The text duplicates did help slim that down a bit =) . I started a new job and haven't had the time to weed out stuff, but will do, via exporting older tabs for now.

**Comment by hluk** [comment]
> It happens after you click okay.

Just to be clear: Does this happen when you click OK but before you select the file name for export? (Having clear idea about when exactly this happens helps me a lot.)

That would point to an issue with the file selection dialog (bug in Qt).

You also export everything without opening the file dialog with following:
1. Open Action dialog (F5 shortcut).
2. Enter `copyq exportData -- c:/path/to/export.cpq` command.
3. Click OK button.

**Comment by Trung0246** [comment]
> > It happens after you click okay.
> 
> Just to be clear: Does this happen when you click OK but before you select the file name for export? (Having clear idea about when exactly this happens helps me a lot.)
> 
> That would point to an issue with the file selection dialog (bug in Qt).
> 
> You also export everything without opening the file dialog with following:
> 
> 1. Open Action dialog (F5 shortcut).
> 2. Enter `copyq exportData -- c:/path/to/export.cpq` command.
> 3. Click OK button.

Seems like doing will will crash CopyQ for my side too, unfortunately.

**Comment by hluk** [comment]
Thanks for the info.

I will fix it so the file is written gradually and exported tabs and data are unloaded from memory as soon as they are not needed.

**Comment by mbakstars** [comment]
> Thanks for the info.
> 
> I will fix it so the file is written gradually and exported tabs and data are unloaded from memory as soon as they are not needed.

Thank you!

(Sorry for delay, this was happening hitting okay, almost like it was trying to accomplish the job, and hiccupped | stopped)

**Comment by hluk** [comment]
Can you test this in [the latest development build](https://ci.appveyor.com/project/hluk/copyq/builds/34928562/job/6orapgne8slojwii/artifacts)? The build uses new export file format so it won't be possible to import it in older version, but it should use much less memory on export and import.

**Comment by mbakstars** [comment]
Many thanks. Will test now, is it portable friendly? =)

**Comment by mbakstars** [comment]
I am running into an issue where I am trying to drag items from one tab to another. The item moves to the tab, but also stays on the clipboard tab I am dragging from. Which it hadn't done for me in previous releases. So far no crashing on backup, seems snappy too. File is currently 2k kb. Please note I did import some commands, but don't have my "Tried & true" setup as before.

Many thanks!

**Comment by mbakstars** [comment]
@hluk Is this still listed as open? I ran into a new issue with the fix.

**Comment by hluk** [comment]
> Is this still listed as open? I ran into a new issue with the fix.

@mbakstars Please open a new issue if it's unrelated to this issue - don't forget to mention that you are using the development build.
