### ISSUE TITLE
Clear clipboard after X sec/mins and keep history

### ISSUE THREAD

**Issue by lazyletucce** [hluk/CopyQ#1465]
Hello, i have searched in the others issues but i cannot find if it's somehow possible, it look like no.

It is possible to clear the OS clipboard after eg. 60sec  but to keep the history in CopyQ?

that would be nice, thanks

**Comment by hluk** [comment]
There is [Clear Clipboard After Interval command](https://github.com/hluk/copyq-commands/tree/master/Scripts#clear-clipboard-after-interval) ([here is how to add the command to CopyQ](https://github.com/hluk/copyq-commands/blob/master/README.md)).

**Comment by lazyletucce** [comment]
thanks, i added it successfully but for some reason it don't clean the OS clipboard, using windows10

**Comment by hluk** [comment]
Are you using the latest CopyQ release?

Any error/warning in logs (F12 shortcut from the main window)?

**Comment by lazyletucce** [comment]
yea i have v3.12.0 and logs are empty

**Comment by hluk** [comment]
Oh, sorry, the way these scripts (called from clipboard monitor) work changed recently.

The command is updated now. Can you copy the command again?

Thanks for testing this!

**Comment by lazyletucce** [comment]
thanks!
