### ISSUE TITLE
Large unmodifiable fonts after upgrade to 3.12.0

### ISSUE THREAD

**Issue by elig0n** [hluk/CopyQ#1466]
**Describe the bug**
After upgrading to 3.12.0 my theme selection was reset. While this can be changed back easily I did not succeed changing the items list font which has gotten too big to read properly. Under Appearance settings all fonts are less than size 10 and yet the fonts are humungous.

**Version, OS and Environment**
Windows 10

**Comment by hluk** [comment]
That could be an issue with style sheets. Specifically, the second line in `themes/items.css` (in installation folder) sets the font. You can try manually change `;${font}` to `;font-size: 8pt` and restart the app to see if it changed (going to configuration dialog and clicking OK button should also apply the style sheet changes).

Otherwise it could be a scaling issue in Qt.

**Comment by elig0n** [comment]
Apparently I had a custom font-size setting under items.css in AppData\Roaming\copyq\themes which used to work fine.
But of now any font-size larger than 9 gets 'cut' because it's higher than the line that displays it.

**Comment by HeRo002** [comment]
I don't know if this is the same bug?: 
I just installed Ubuntu 20.04 on a new partition, then I installed CopyQ v3.10.0 and configured a few things. Then suddenly the font size seemed VERY small. I am not 100% sure if it had actually changed, but I think so. So in Preferences under Appearance I started pressing the 'Abc'-buttons and changing the font size, but my changes were ignored by CopyQ, whether I checked "Set colors for tabs, tool bar and menus" or not.

**Comment by hluk** [comment]
Can you check if CSS files are properly installed and not overridden?

The *.css files are usually installed in `/usr/share/copyq/themes` and overridden in `~/.config/copyq/themes/` (initially, this directory doesn't contain any *.css files).

See: https://copyq.readthedocs.io/en/latest/theme.html#style-sheets

**Comment by HeRo002** [comment]
Hi hluk!
This forum seems to be unstructured/unthreaded, so I don't know if you are talking to me. But here is my answer: 
/usr/share/copyq/themes contains 8 *.ini files. 
~/.config/copyq/themes/ contains nothing.

**Comment by HeRo002** [comment]
Hi hluk!

This forum seems to be unstructured/unthreaded, so I don't know if you are talking to me. But here is my answer: 

/usr/share/copyq/themes contains 8 *.ini files. 
~/.config/copyq/themes/ contains nothing.

**Comment by sfd99** [comment]
> I don't know if this is the same bug?:
> I just installed Ubuntu 20.04 on a new partition, then I installed CopyQ v3.10.0 and configured a few things. Then suddenly the font size seemed VERY small. I am not 100% sure if it had actually changed, but I think so. So in Preferences under Appearance I started pressing the 'Abc'-buttons and changing the font size, but my changes were ignored by CopyQ, whether I checked "Set colors for tabs, tool bar and menus" or not.

THIS IS EXACTLY my Problem w/ latest CopyQ,
under UBUNTU 20.04.4...

Suddenly, 
all the font sizes (CopyQ UI menus and copied items f/clipboard),
have become tiny.
Just like the above User,
I tried increasing the Font Sizes
in the [abc] buttons under Appearances.

But none of my new (larger) font sizes "takes".
ie:
   -  as soon as I click [OK] and then [Apply],
my font size size setting are forgotten
and the old, original font sizes reappear...

I think CopyQ is a WONDERFUL program.
But isn't there a simple way to set the font sizes
of the UI and the copied items?.

Checked the Manual 
and the Q&As, but none work for me.

HELP! Can't increase the font sizes, 
they are too small to read... :-(

SFd99
SF
Ubuntu Linux 20.04.4
latest Chromium browser

**Comment by hluk** [comment]
@HeRo002 @sfd99 The original issue is about CopyQ 3.12.0 on Windows. You problem seems to be different. Please open a new issue.

**Comment by hluk** [comment]
> Apparently I had a custom font-size setting under items.css in AppData\Roaming\copyq\themes which used to work fine.
> But of now any font-size larger than 9 gets 'cut' because it's higher than the line that displays it.

@elig0n Not sure if other change in css files can cause this. It could be caused by couple of things:
- "Maximum height in pixels" option for Text plugin in Item configuration tab.
- Items are HTML-formatted with some line-height limit (to inspect formats, select an item and press F4 key).
- Some `max-height` or other property in css files.

**Comment by elig0n** [comment]
It looks to me that it was font-size in items.css (the one in AppData).
