### ISSUE TITLE
Semi-transparent main window

### ISSUE THREAD

**Issue by thetha** [hluk/CopyQ#1467]
I have the newest IOS version
I have the newest CopyQ version
Bugs: after double click the CopyQ gets transparent, but not fully. Then you have to click on show copyq twice to see it again
![image](https://user-images.githubusercontent.com/13396762/91707329-edba3980-eb7f-11ea-8c8b-874aa130e4e8.png)
Its super annoying.

**Comment by hluk** [comment]
Can you try [this development version](https://github.com/hluk/CopyQ/releases/tag/macos-window)? I haven't tested this properly, but it's one of the things that could fix the problem.

**Comment by hluk** [comment]
BTW, supported macOS versions in CopyQ 3.12.0 are **10.12, 10.13, 10.14**.

Those are versions that Qt 5.13 supports: https://doc.qt.io/archives/qt-5.13/supported-platforms.html

I can update to Qt 5.15.0 which supports [macOS 10.13, 10.14, 10.15](https://doc.qt.io/qt-5.15/macos.html).

**Comment by uberkelium** [comment]
> Can you try [this development version](https://github.com/hluk/CopyQ/releases/tag/macos-window)? I haven't tested this properly, but it's one of the things that could fix the problem.

I think issue still persists, not sure if this is the same thing as @thetha described

Before:
![1](https://user-images.githubusercontent.com/22272118/93722413-698a1f00-fb4b-11ea-86f0-6331f720898b.gif)

After:
![2 mov](https://user-images.githubusercontent.com/22272118/93722428-7dce1c00-fb4b-11ea-8792-0f761865a6a7.gif)

**Comment by hluk** [comment]
Can you try the [development version](https://github.com/hluk/CopyQ/releases/tag/macos-window)? It's build with Qt 5.15.1 now.

**Comment by uberkelium** [comment]
@hluk How do you mean? The GIFs in my previous post were created using the development version. Also, I apologize—I think the "before" GIF was a mistaken upload. Should have shown the working version.

**Comment by hluk** [comment]
@uberkelium I meant to say "can you try the development version again" because I've rebuilt it with newer version of Qt.

**Comment by pgreda** [comment]
@hluk After short testing, it looks like development version is ok but maybe it takes some time for the bug to manifest. 
Brew version (3.13.0) is affected.

**Comment by hi-usui** [comment]
@thetha Seems to be fixed as of CopyQ v4.1.0, tested on Big Sur 11.4
