### ISSUE TITLE
3000 records slow

### ISSUE THREAD

**Issue by luapfr** [hluk/CopyQ#1469]
Those 3000 thousand records have many photos and when I run on the scrollbar or even do a search even my machine with a Core I7 8750H with 32 GB of memory with 1TB SSD I consider it very slow.

A suggestion for this limitation would be to have a database like SQLite would be much faster, an example of which is ClipAngel which uses SQLite.
[](https://sourceforge.net/projects/clip-angel/)

Thankful.

**Comment by hluk** [comment]
Related to #510. But it's a big change that probably not going to happen any time soon.
