### ISSUE TITLE
Feature request: Allow automatically storing all screenshots made with printscreen in clipboard history

### ISSUE THREAD

**Issue by AlexFolland** [hluk/CopyQ#1470]
**Is your feature request related to a problem? Please describe.**
Hello.  I recently started using Manjaro with XFCE4 after migrating from Windows 7.  On Windows 7, I have been using Ditto Clipboard Manager for years to manage my clipboard history.  It had no flaws for me, as it always saved whatever was in my clipboard, up to the limits I specified, in total bytes or history index count, whichever limit reached.  This included storing screenshots, which I do often in my daily work.

I had 16 GB of RAM until recently, when I got 32 GB and then even more recently, 64 GB of RAM, for working with multiple large Google Sheets and bloated web interfaces for various quality assurance apps like Asana in my daily work.  In Windows, I tended to have more than 25 GB of RAM free, even with Ditto set to store up to 200 clipboard entries or 16 GB of entries and Firefox taking around 20-25 GB of RAM on its own.  Obviously 200 history entries or 16 GB of history entries is overkill, but since I have overkill RAM, I figured I might as well set overkill settings until I have an issue, then dial it down from there.

**Describe the solution you'd like**
I would like to be able to do similar in Linux.  I have tried several clipboard managers now, including clipman which comes with XFCE4, ClipIt, and CopyQ.  None of these clipboard managers have the functionality I want, but CopyQ seems the closest to being able to have it implemented.

Specifically, I'd like CopyQ to be able to automatically save to the clipboard history when copying via the printscreen key (or alt+printscreen, or other screenshot keyboard combination), and have/check a limit for how much data it is allowed to store, in both number of entries and byte size.  An example of the expected behavior is to be able to press printscreen twice and see 2 images become present in the history immediately.

If a hashing algorithm checked for identical images in the history, that'd be a cool optimization, but it would have to at least bring that identical image to the top of the history.  This part isn't officially part of my feature request, but it'd definitely be badass.

The data size check wouldn't have to be configurable, and in my case with 64 GB of RAM, it could be unlimited and I'd be happy since even 200 history entries are unlikely to break even a 16GB limit, even if I filled the history with 200 full multi-monitor desktop screenshots.  Configurability of the max history size in bytes would be nice though.

Obviously if an image or giant text selection made the history reach the max size, the oldest stuff would be purged from the history until under the max.  If more than the max history byte size was copied at once, that would be the only time the history saving would be rejected, with a message.

**Describe alternatives you've considered**
I have researched as many clipboard managers as are available within XFCE4 or GTK3+ reach.  I'm not willing to try the Wayland clipboard manager right now, as I wish to stick with XFCE for now, which doesn't support Wayland.  I'm not sure if that one even has this functionality though.

**Additional context**
I'm extremely grateful that clipboard managers like Ditto exist, since I often copy a whole bunch of things for a bug report in my job, crop images, paste the cropped versions, paste the original again to crop something else, paste a session log URL, paste a crash log URL, etc.  Having all the images that I've copied stored automatically to a history list is extremely valuable, and I wish it was available in this new OS environment that I'm learning.

Also, I'd like to mention that Ditto has a feature allowing you to choose the permanent storage device path for storing its history, so you can choose the drive on which this larger history with multiple screenshots is stored.  That feature would be great to be able to configure in the CopyQ settings GUI, but could be achieved with a symbolic link instead, which is why I didn't mention it as part of the solution I requested.

CopyQ is cool, free open-source software is cool, and clipboard managers are cool.  I'm happy no matter what's done with this request.  Thanks for programming!

**Comment by hluk** [comment]
I haven't got any issues storing screenshots in CopyQ via PrtScn key, external app or using "Take screenshot" predefined command in CopyQ.

There is also a command to store images or large data in a separate tab.

```ini
[Command]
Command="
    copyq:
    sleep(1000)
    tab('Screenshots')
    var imageData = screenshotSelect()
    write('image/png', imageData)
    copy('image/png', imageData)
GlobalShortcut=meta+ctrl+s
Icon=\xf083
IsGlobalShortcut=true
Name=Take a Screenshot
```

([Here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them).)

You can limit the number of items in tabs (see Tabs in Configuration dialog).

**Comment by ElijahLynn** [comment]
I use Flameshot on Arch and it works great to auto-copy to clipboard. I don't have mine mapped to PrtScn but it could easily be done to do so. I have been through many screenshotting tools on Linux and Flameshot is my favorite so far, fwiw. 

https://flameshot.js.org

**Comment by AlexFolland** [comment]
The functionality I described and requested in the first post here is working completely now, with the latest version of CopyQ.  Thanks!
