### ISSUE TITLE
Preview does not show the entire text.

### ISSUE THREAD

**Issue by luapfr** [hluk/CopyQ#1472]
In the last version I realized that in some situations the preview does not show all the text by placing a small scroll bar beside it.
  
   Do you have any option to increase this scroll bar of the preview? and something else as the text is large would not need the scroll bar if it did not cut the text.

See in the items the scroll bar is normally large.

See attached image
https://ibb.co/25vp5kk

**Comment by hluk** [comment]
Ah, it might be due to the text size limits set in configuration. Is it fixed if you set `0` for both "Maximum..." options?

![image](https://user-images.githubusercontent.com/38054/92243790-5415c380-eec2-11ea-9c22-566c6edde786.png)

**Comment by hluk** [comment]
Actually, I just tested it and that's already handled. Looks like issue in UI layout. I'm trying to fix it.

**Comment by luapfr** [comment]
you created a correction code but I don't know how to put that code in CopyQ;

   Are you going to release an upcoming CopyQ version 3.13 with this built-in fix?

**Comment by hluk** [comment]
> Are you going to release an upcoming CopyQ version 3.13 with this built-in fix?

Yes, it will be fixed in next release.

**Comment by luapfr** [comment]
Hello good day.
Any predictions for the release of Version 3.13?

Thankful.
