### ISSUE TITLE
Unable to style the tray menu since the 3.12.0

### ISSUE THREAD

**Issue by pku888** [hluk/CopyQ#1474]
Hi, 

Since the 3.12.0 version, I am unable to use the styled tray menu.
I was able to style it with the menu_bar_css option in the copyq.conf file.
The styling was possible with the 3.11.1 version.

I've been using the tray shortcut to paste items from clipboard instead of the main window, since I feel that it's slightly faster to work this way. With the styling option no longer working, the items in the tray menu have too small font size for me to comfortably read them.

My system: Linux Mint 19.3

I am attaching my copyq.conf file, feel free to compare it with  3.11.1 against 3.12.0

[copyq.txt](https://github.com/hluk/CopyQ/files/5176873/copyq.txt)

**Comment by hluk** [comment]
Option `menu_bar_css` is for styling the menu bar in the main window. I believe, you need to change `menu_css`.

Newly, there are separate `css` files installed with the app -- on macOS it's in `Contents/Resources/themes` subdirectory. So if you need to fix some styling issue with the menu try overriding `menu.css` file. See: https://copyq.readthedocs.io/en/latest/theme.html
