### ISSUE TITLE
Download for Windows portable v3.12 ?

### ISSUE THREAD

**Issue by bawldiggle** [hluk/CopyQ#1477]
I cannot find the Windows download for Portable v3.12 ?
Am I going nuts ?

I am not the only one who cannot find it ...
by "Guest" (Aug-2020) on https://alternativeto.net/software/copyq/reviews/

**Comment by wetware05** [comment]
https://sourceforge.net/projects/copyq/files/latest/download

**Comment by bawldiggle** [comment]
@ wetware05 
Thank you.
As wife reminds me I was having a "boy" look
With adblocker disabled I was distracted looking for the Project "tabs" ... Files.
Adblocker enabled; and found what I was looking for

https://sourceforge.net/projects/copyq/files/
