### ISSUE TITLE
Just a question about the program I cannot find the answer in the documents

### ISSUE THREAD

**Issue by whytte** [hluk/CopyQ#1479]
1) When I clicked on the CopyQ in the task bar, the screen comes up shows copied text font size small, How can I increase it please?
2) is it possible to copy all the copied items into 1 text file? if so how?
3) Alternatively can the  the scripting side of the program  be set to copy all the files from clipboard  to a text file continuously, so that I get 1 text file at the end of the day?

**Comment by hluk** [comment]
ad 1. The item font can be increased in Appearance configuration tab.
ad 2. Do you mean something like Ctrl+A, Ctrl+C and paste into file?
ad 3. With scripting can write a content to a file. See:
- [API reference](https://copyq.readthedocs.io/en/latest/scripting-api.html)
- [Command repository](https://github.com/hluk/copyq-commands) - there could be some already that do something similar (`File` is the class to manipulate files)
- [Smaller command examples](https://copyq.readthedocs.io/en/latest/command-examples.html)

**Comment by JoshWZ** [comment]
2.  Let's say I have collected 50 clips at the end of the day, is it possible to paste all 
into one text file, not one by one, "all at once" to "one and only text file"?

**Comment by JoshWZ** [comment]
ideally I want all the clipboard collections, to be written onto 1 text file continuously, not into separate sections.
Let's say copyQ collects the clips continuously into 1 text file only automatically, not in part by part, 
if that is not possible, can we copy all the collection and paste all into 1 text file, not one by one

**Comment by hluk** [comment]
I just added [Write Clipboard to File](https://github.com/hluk/copyq-commands/tree/master/Scripts#write-clipboard-to-file) command (on how to add it, read [README](https://github.com/hluk/copyq-commands/blob/master/README.md) file).

**Comment by JoshWZ** [comment]
Wonderful. thank you indeed. 
I'll start testing it 
all the best

**Comment by whytte** [comment]
Works great. Thank you.

A different question:
I see image holders in the copied version of a website , not the image. 
I'm not sure about the settings in my program. 
if there's one please let me know for copying a webpage including images please
thank you in advance

**Comment by hluk** [comment]
CopyQ won't make any remote requests to show HTML. This is supported by obsolete Web plugin (I want to get rid of it soon) which is not available on Windows.

So CopyQ won't show images referred in the copied HTML (e.g. `<img src="...">`) unless the source is local file or base64-encoded data.

**Comment by whytte** [comment]
Thank you. 
You have been very helpful
Please take care
