### ISSUE TITLE
Vi style search doesn't work in tray

### ISSUE THREAD

**Issue by navennn** [hluk/CopyQ#1480]
**Describe the bug**
Vi style search doesn't work in tray. It does work in the main window though.
I have another installation, on mint 19.3 where it works just fine.
I tried following the bug workaround described in docs
'env QT_QPA_PLATFORM=xcb copyq'
It makes no difference.

**To Reproduce**
1. Set vi-style navigation to enabled
2. Right-click tray icon and attempt to search using '/'

**Expected behavior**
Numbers 0-9 shouldn't be visible, instead using '/' should allow me to search. Nothing happens when I use the slash.

**Screenshots**

![Skärmbild från 2020-09-20 12-07-55](https://user-images.githubusercontent.com/26810830/93708902-430fb800-fb3a-11ea-9500-0dadb444dd6f.png)

![Skärmbild från 2020-09-20 12-06-19](https://user-images.githubusercontent.com/26810830/93708979-01334180-fb3b-11ea-8b9f-60b2d6a1ac21.png)

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
naven@naven-GV72-8RC ~ $ copyq version
CopyQ Clipboard Manager v3.10.0
Qt: 5.12.5
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Linux Mint 20
cinnamon --version
Cinnamon 4.6.7

**Additional context**

**Comment by hluk** [comment]
Right clicking on tray icon shows menu that some desktop environments override with their native version. I have no control over that menu.

I don't think I can do anything about this.

To show the menu that CopyQ controls, you can run `copyq menu` command -- this menu supports searching items (just start typing).
