### ISSUE TITLE
Week number

### ISSUE THREAD

**Issue by viharm** [hluk/CopyQ#1482]
**Is your feature request related to a problem? Please describe.**
I have custom commands to paste current date and time as per the _CopyQ_ documentation; However am trying to paste the current week number in ISO format, e.g., `2020W39`.

**Describe the solution you'd like**
Is there an existing format string which can be used with the `dateString` function? Is there a code snippet which can be used to extract the current week number and concatenate with `dateString('yyyy')`?

**Describe alternatives you've considered**
I have looked at the _CopyQ_ docs, the reference _ECMAScript_ sections in the _Qt_ docs, but couldn't find any references to week formatting.

**Additional context**
There is a `weeknumber()` function (https://doc.qt.io/qt-5/qdate.html#weekNumber) but I don't know how to use it.

Please help.

**Comment by hluk** [comment]
`QDate` Qt class or its methods are not accessible from scripts.

Looks like this is not trivial in JavaScript either: https://stackoverflow.com/questions/6117814/get-week-of-year-in-javascript-like-in-php

If you are on Linux, you could call `date` from the script (it would add some small overhead):

```
var isoWeek = str(execute('date', '-u', '+%GW%V').stdout);
```

**Comment by viharm** [comment]
@hluk ,

Thanks for your response. I use _CopyQ_ on both _Linux_ and _Windows_, but will try out your suggestion on my _Linux_ box.

I wasn't sure how to run _Javascript_ code within _CopyQ_ commands. Since I run _CopyQ_ on both _Linux_ and _Windows_, I need something compatible with both. How can I do this?

**Comment by hluk** [comment]
Scripting in CopyQ is basically JavaScript ([Qt version of ECMAScript](https://doc.qt.io/qt-5/qtscript-index.html)). The scripting language is the same for all supported platforms.

See: https://copyq.readthedocs.io/en/latest/scripting.html

More details and API reference: https://copyq.readthedocs.io/en/latest/scripting-api.html

**Comment by viharm** [comment]
Thanks. Just tried both on my _Linux_ PC and it just works. I love _CopyQ_.

I'll try it on my _Windows_ PC tomorrow and let you know if there are any issues.

@hluk , Thanks for making and maintaining _CopyQ_. And thanks very much for your support, much appreciated.
