### ISSUE TITLE
iOS / App / Keyboard?

### ISSUE THREAD

**Issue by squirrelboot** [hluk/CopyQ#1483]
With CopyQ able to have multiple Tabs, syncing between devices is a massive benefit. I would really like to be able to access through my iOS device, synced tab items in a clipboard. Allowing me to copy from anywhere, and paste from anywhere (Win laptop / MacOS / Debian / Mobile device). Currently the only item missing in this end-to-end workflow is the mobile integration. 

How nice to be able to copy a link to a recipe you get from a colleague at work (sync with CopyQ), and paste it in my phone's browser when I'm at the grocery store.

**Comment by hluk** [comment]
Similar to #449, currently, I don't have much reason to support mobile devices.
