### ISSUE TITLE
How to change font-size of item?

### ISSUE THREAD

**Issue by snowman** [hluk/CopyQ#1484]
![1601048885](https://user-images.githubusercontent.com/16096559/94288198-baee4000-ff89-11ea-9e5b-2f95edeed4ef.png)

Here is my `$HOME/.config/copyq/copyq.conf`, even though i have set all the `css` to <code>"\n&nbsp;&nbsp;&nbsp;&nbsp;;font-size:&nbsp;32pt"</code>, but the list-item `font-size` does not change at all.
```conf
[Theme]
alt_item_css="\n    ;font-size: 32pt"
css="\n    ;font-size: 32pt"
cur_item_css="\n    ;font-size: 32pt"
item_css="\n    ;font-size: 32pt"
menu_bar_css="\n    ;font-size: 32pt"
menu_bar_disabled_css="\n    ;font-size: 32pt"
menu_bar_selected_css="\n    ;font-size: 32pt"
menu_css="\n    ;font-size: 32pt"
notes_css="\n    ;font-size: 32pt"
sel_item_css="\n    ;font-size: 32pt"
tab_bar_css="\n    ;font-size: 32pt"
tab_bar_scroll_buttons_css="\n    ;font-size: 32pt"
tab_bar_tab_selected_css="\n    ;font-size: 32pt"
tab_bar_tab_unselected_css="\n    ;font-size: 32pt"
tab_tree_css="\n    ;font-size: 32pt"
tab_tree_sel_item_css="\n    ;font-size: 32pt"
tool_bar_css="\n    ;font-size: 32pt"
tool_button_css="\n    ;font-size: 32pt"
tool_button_pressed_css="\n    ;font-size: 32pt"
tool_button_selected_css="\n    ;font-size: 32pt"
```

**Comment by hluk** [comment]
The `font` theme option changes the font size. If you want more control over the styling, see [Theme](https://copyq.readthedocs.io/en/latest/theme.html) documentation.

**Comment by snowman** [comment]
Okay, finally get it work.

![1601123195](https://user-images.githubusercontent.com/16096559/94340753-a9af3d00-0036-11eb-9106-0b706cd1b877.png)

---

According to [Theme](https://copyq.readthedocs.io/en/latest/theme.html) documentation,
```bash
$ cp $(copyq info themes)/items.css $(copyq info config | xargs dirname)/themes
$ $EDITOR $(copyq info config | xargs dirname)/themes/items.css
```

But that's not needed... :) 

If you open file `$(copyq info themes)/items.css`, you would see:
```CSS
#ClipboardBrowser,#item,#item_child{
    ;${font}
    ;color: ${fg}
    ;background: ${bg}
}
```

i guess ${font} here is using variable from `copyq.conf` file, because i see `font=` over there.

It's actually seem equivalent to following: (maybe i'm wrong, thinking it as variant of CSS, if not, then why ${font} without `font` propery working? )
```CSS
#ClipboardBrowser, #item, #item_child{
    font       : ${font};
    color      : ${fg};
    background : ${bg};
}
```

Anyway, run this do the job
```bash
# set  font="Ubuntu Condensed,20,-1,5,50,0,0,0,0,0"  in config.conf file
$ sed -i 's/^font=.*$/font="Ubuntu Condensed,20,-1,5,50,0,0,0,0,0"/' $(copyq info config)
```

Actually, the font is copied from (ommited some values here)
```bash
$ find $(copyq info themes) -type f | xargs grep -h font= | head -n5
edit_font="Sans,9,-1,5,50,0,0,0,0,0"
find_font="Ubuntu,9,-1,5,50,0,1,0,0,0"
font="Sans,9,-1,5,50,0,0,0,0,0"
notes_font="Sans,10,-1,5,50,0,0,0,0,0"
num_font="Sans,7,-1,5,25,0,0,0,0,0"
```

**Comment by hluk** [comment]
Using `${font}` (and other `*_font` options) in the stylesheets expands to following:

```
; font-family: "FAMILY NAME"
; font: {italic|oblique|normal} [bold] {SIZE}
; text-decoration: [line-through] [underline] [overline]
; font-weight: {WEIGHT}
;
```

Source: https://github.com/hluk/CopyQ/blob/65978f4770dfe74edf8244a945e059a3bd46255f/src/gui/theme.cpp#L137-L172

**Comment by snowman** [comment]
Thanks for your help :) :+1:
