### ISSUE TITLE
Very small fonts cannot be changed

### ISSUE THREAD

**Issue by HeRo002** [hluk/CopyQ#1489]
I posted the following as a comment to https://github.com/hluk/CopyQ/issues/1466 but someone determined that this is another bug: 

I just installed Ubuntu 20.04 on a new partition, then I installed CopyQ v3.10.0 and configured a few things. Then suddenly the font size seemed VERY small. I am not 100% sure if it had actually changed, but I think so. So in Preferences under Appearance I started pressing the 'Abc'-buttons and changing the font size, but my changes were ignored by CopyQ, whether I checked "Set colors for tabs, tool bar and menus" or not.

**Screenshots**

![Screenshot CopyQ-2 2020-09-29](https://user-images.githubusercontent.com/22969436/94556866-12c4c980-025e-11eb-814a-c7a7544491d0.png)

**Version, OS and Environment**

~$ copyq version
CopyQ Clipboard Manager v3.10.0
Qt: 5.12.5
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Ubuntu 20.04.1 LTS
~$ 

GNOME: 3.36.3 
Windowing system: X11

**Comment by hluk** [comment]
It's quite possible this has been already fixed in some recent CopyQ version -- version 3.10.0 is too old.

Can you try using the newest version using the PPA repository (see details [here](https://copyq.readthedocs.io/en/latest/installation.html))?

**Comment by HeRo002** [comment]
Yes. Upgrading to 3.12.0 helped. Now it is only the menus and preferences window that have very small fonts.

**Comment by hluk** [comment]
> Yes. Upgrading to 3.12.0 helped. Now it is only the menus and preferences window that have very small fonts.

Did you enable option "Set colors for tabs, tool bar and menus" in Appearance settings? The option name is a bit incomplete since it also changes font.

This does not affect font in the preferences though. You will have to change the font in the system or maybe install some better Qt integration tools/libraries/themes.

**Comment by HeRo002** [comment]
Yes. That one is enabled. 

My Ubuntu Settings -> Universal Access -> Seeing -> Large Text = 'On' - but that seems to have a limited effect. CopyQ is not the only place where it doesn't seem to take effect.

**Comment by hluk** [comment]
Looks like Ubuntu doesn't support changing this for Qt.

Alternative solutions:
- set environment variable `QT_SCREEN_SCALE_FACTORS=2` before launching CopyQ
- [qt5ct](https://sourceforge.net/projects/qt5ct/) utility to change appearance of Qt apps

**Comment by HeRo002** [comment]
Well... As long as I can change font size in the list of clips, I am OK! Thank you for solving that!
There are so many worse problems in Ubuntu!... For instance I can't use my scanner. I have to start up Ubuntu 18.04 to use it...

**Comment by ElijahLynn** [comment]
Thanks for this thread! I installed CopyQ for an Ubuntu Thinkpad I ordered and it came with Ubuntu 20.04 and didn't think much of the repo source. But I was having issues with small fonts for weeks and just did a `copyq --version` and saw 3.10.0. I followed your instructions and now I have 7.0.0 and it is fixed!!! Yay!

```
 ~/p/csp [main] copyq --version
CopyQ Clipboard Manager 7.0.0~focal
Qt: 5.12.8
KNotifications: 5.68.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Ubuntu 20.04.5 LTS
```

> It's quite possible this has been already fixed in some recent CopyQ version -- version 3.10.0 is too old.
> 
> Can you try using the newest version using the PPA repository (see details [here](https://copyq.readthedocs.io/en/latest/installation.html))?
