### ISSUE TITLE
MacOS CopyQ Search all tabs plugin pop up window is not properly displayed

### ISSUE THREAD

**Issue by smetroid** [hluk/CopyQ#1490]
Before creating a new issue, see list of [known
issues](https://copyq.readthedocs.io/en/latest/known-issues.html).

**Describe the bug**
When trying to use the search all tabs plugin the popup to search is too small to do anything with on MacOS Mojave version 10.14.6 

**To Reproduce**
1. Go to 'File > Commands Global Shortcuts > '
2. Click on 'Add > New Command'
3. Copy and paste the 'Search All Tabs' plugin
4. Open up Main window
5. Open up Search All Tabs plugin shortcut

**Expected behavior**
The 'Search All Tabs' pop up window should have a visible field to enter a search string

**Screenshots**
![Screen Shot 2020-10-03 at 11 28 2
![Screen Shot 2020-10-03 at 11 35 59 AM](https://user-images.githubusercontent.com/1909699/94996862-bb2fa200-056c-11eb-9187-bbe4e3d8c152.png)
0 AM](https://user-images.githubusercontent.com/1909699/94996802-40668700-056c-11eb-955b-fddf5615faf4.png)

**Version, OS and Environment**
 - Application Version: 
 - OS: MacOS Mojave

**Comment by hluk** [comment]
That looks like a Qt bug. Can you try it with [the development version](https://github.com/hluk/CopyQ/releases/tag/macos-window)? It uses newer version of Qt.

As a workaround, you can try changing `var match = dialog("Search")` to `var match = dialog("Search", ".height", 1000)` in the command.

**Comment by smetroid** [comment]
Well, not sure what fixed it, but it seems like the issue mentioned in here is no longer an issue.
