### ISSUE TITLE
Copy/Cut/Paste - add preview for files

### ISSUE THREAD

**Issue by pawlosck** [hluk/CopyQ#1491]
I would like to see preview for images when I want move files using copy/cut/paste. If possible, preview for other formats would be great feature too.
Of course in popup should be link to source file.

This feature is in KDE clipboard and is great.

**Comment by ElijahLynn** [comment]
I see preview working for copied images to the clipboard when pressing F7, on latest stable version (3.12.0) now.

**Comment by pawlosck** [comment]
Maybe I use other words and write example.
1. Open file manager (dolphin, double commander etc)
2. Mark few files (images) and press Ctrl+C
3. Open CopyQ -> You will see paths only, not previews of files.

**Comment by hluk** [comment]
There is [Preview Image Files](https://github.com/hluk/copyq-commands/tree/master/Display#preview-image-files) command (see [README](https://github.com/hluk/copyq-commands/blob/master/README.md) file on how to install the command).

**Comment by sequencerr** [comment]
> There is [Preview Image Files](https://github.com/hluk/copyq-commands/tree/master/Display#preview-image-files) command (see [README](https://github.com/hluk/copyq-commands/blob/master/README.md) file on how to install the command).

It's only for images. What about all other files? (docs, code files, videos, etc.)

**Comment by hluk** [comment]
> > There is [Preview Image Files](https://github.com/hluk/copyq-commands/tree/master/Display#preview-image-files) command (see [README](https://github.com/hluk/copyq-commands/blob/master/README.md) file on how to install the command).
> 
> It's only for images. What about all other files? (docs, code files, videos, etc.) Okay, of course I don't need preview for every file, but I even can't copy/paste files. Just getting "file:///D:/Downloads/Pics/4Kj3.gif". Perfect. Isn't It? roll_eyes

This depends on your file manager and desktop environment. You may need to add some special data formats to clipboard so the file manager understands what to do with the URI.

NOTE: If you copy something, check with clipboard content and formats with Ctrl+Shift+C from CopyQ. See also: [FAQ: How to reuse file paths copied from a file manager?](https://copyq.readthedocs.io/en/latest/faq.html#how-to-reuse-file-paths-copied-from-a-file-manager)
