### ISSUE TITLE
CopyQ Flathub version, not working on Linux Mint 20

### ISSUE THREAD

**Issue by ardhill** [hluk/CopyQ#1492]
I know there is another issue similar to this, but not the same. I have even less functionality than others in the Pop OS Issue: https://github.com/hluk/CopyQ/issues/1432

**System:** 
Stock Linux Mint 20 Cinnamon edition
Kernel: 5.4.0-48-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 4.6.7  wm: muffin dm: LightDM Distro: Linux Mint 20 Ulyana base: Ubuntu 20.04 focal 

**Problem:**
CopyQ installed from flathub. It is in the Menu, but that is the only visible evidence that it exists.
- Launching the GUI from the menu appears to do nothing
- There is no tray Icon 
- copyq command in terminal no use:
```
$ copyq --version
bash: copyq: command not found
```
There are a few process running called copyq, which appear to be 'sleeping'

![copyq-processes-1](https://user-images.githubusercontent.com/59650081/95447505-ba768180-0959-11eb-8cb4-864d8ed00556.png)

![copyq-processes-2](https://user-images.githubusercontent.com/59650081/95447508-bba7ae80-0959-11eb-8bd0-5b78de800a46.png)

NOTES: 
- I guess, the vivaldi-bin process is because I have copyq github open in vivaldi browser. 
- The version of copyq in Mint's software repository works, though it is v3.10.0

**Comment by hluk** [comment]
It should be possible to show UI using following command:

```bash
flatpak run com.github.hluk.copyq show
```

Normally, when tray is not available, the app should be minimized in task bar instead. Not sure why in this case it doesn't work - could be bug in Qt or the desktop environment.

To be able to use the tray icon for CopyQ (and other Qt apps), you need to install special extension in Gnome (and perhaps other desktop environments).

**Comment by ardhill** [comment]
> To be able to use the tray icon for CopyQ (and other Qt apps), you need to install special extension in Gnome (and perhaps other desktop environments).

The DE is Cinnamon, though Mint does have a lot of Gnome components. It also has QT5 working. The tray icon shows up just fine when I install CopyQ from the Mint Software repository, as do other Icons. I do have a tray icon from a Snap package, but don't have any flatpak packages that use an icon in the tray, so can't confirm or deny other tray icons within flatpak installs (if that even is something that matters).

**Comment by hluk** [comment]
@ardhill Can you try the flatpak from [here](https://github.com/flathub/com.github.hluk.copyq/pull/25)? I found a similar issue and patch that could fix it.

**Comment by hluk** [comment]
Any update on this?

**Comment by vanphong1310** [comment]
> @ardhill Can you try the flatpak from [here](https://github.com/flathub/com.github.hluk.copyq/pull/25)? I found a similar issue and patch that could fix it.

The error is still exist. I can't try this suggestion beacause the link to flatpakref file is 404.
Deb installation works fine!

**Comment by hluk** [comment]
You can test this build: https://github.com/flathub/com.github.hluk.copyq/pull/29

The build will be automatically removed after few days/weeks.

**Comment by vanphong1310** [comment]
This build works fine, tray icon is back. Thank you :heart:

**Comment by hluk** [comment]
@vanphong1310 Thanks for verification! I'll merge the fix and close this.
