### ISSUE TITLE
[SOLVED] CopyQ ctrl-c (copy) from within any app causes app to crash (linux mint 20)

### ISSUE THREAD

**Issue by tethragon** [hluk/CopyQ#1493]
**Describe the bug**
When CopyQ runs in the background, copying an image from within any app, causes app to crash

**To Reproduce**
1. Open an app (i.e. gimp)
2. Open an image
3. Copy the image (either using ctr-c or from edit/copy menu)
4. App closes without any warning

**Expected behavior**
App should stay open and the copied image should be added in the clipboard for further use

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Application Version 

CopyQ Clipboard Manager v3.10.0
Qt: 5.12.5
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Linux Mint 20

 - Desktop environment, window manager (if applicable)

System:    Kernel: 5.4.0-48-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 4.6.7 
           wm: muffin dm: LightDM Distro: Linux Mint 20 Ulyana base: Ubuntu 20.04 focal

**Comment by hluk** [comment]
How did you install CopyQ?

**Comment by tethragon** [comment]
> How did you install CopyQ?

I think from official mint repository

**Comment by hluk** [comment]
> > How did you install CopyQ?
> 
> I think from official mint repository

Do you have a link to it? I cannot find it in http://packages.linuxmint.com/.

I'm asking because it sounds like the problem could be that the app is build with a different set of libraries than those available in the system.

Probably better if you can install newer version because a lot of issues may have been fixed in the latest version. E.g. you can use the flatpak package (see the [documentation](https://copyq.readthedocs.io/en/latest/installation.html)).

**Comment by tethragon** [comment]
> > > How did you install CopyQ?
> > 
> > 
> > I think from official mint repository
> 
> Do you have a link to it? I cannot find it in http://packages.linuxmint.com/.
> 
> I'm asking because it sounds like the problem could be that the app is build with a different set of libraries than those available in the system.
> 
> Probably better if you can install newer version because a lot of issues may have been fixed in the latest version. E.g. you can use the flatpak package (see the [documentation](https://copyq.readthedocs.io/en/latest/installation.html)).

I installed from software manager within Linux Mint, so I have no link.

I don't want to use flatpak because of the unnecessary overhead. Any other options?

**Comment by hluk** [comment]
> I don't want to use flatpak because of the unnecessary overhead. Any other options?

[Build the app manually](https://copyq.readthedocs.io/en/latest/build-source-code.html). Not sure if there are other options for Linux Mint (e.g. some unofficial package repository).

Can you provide a core-dump from the crash (e.g. `coredumpctl dump copyq`)?

**Comment by tethragon** [comment]
Update. 

I uninstalled the copyQ from software manager.

Then added official copyQ PPA

sudo add-apt-repository ppa:hluk/copyq

Then Installed copyQ version 3.12 (previously installed version from Linux Mint's Software Manager was 3.10)

Everything works fine now.

**Comment by hluk** [comment]
Glad to hear it worked. :)
