### ISSUE TITLE
What is the cli command to print and clear all items in clipboard history ? ( Help Needed ) 

### ISSUE THREAD

**Issue by xd003** [hluk/CopyQ#1494]
https://copyq.readthedocs.io/en/latest/command-line.html i did had a look here but couldn't really find what i am looking for . Do note that i am not talking about printing stored items in a note , i am talking about clipboard itself ( default where a copied text gets stored ) .

i am using windows 10 , so i need the relevant commands which i can use in Powershell /Cmd or Git Bash to do the following :
1) Print all the items stored in clipboard history ( each item on a new line with the latest stored item at bottom of list )
2) Clear all the items stored in clipboard history
3) Disable clipboard storing & Enable clipboard storing

Thanks in advance

**Comment by hluk** [comment]
> 1. Print all the items stored in clipboard history ( each item on a new line with the latest stored item at bottom of list )

```sh
copyq 'tab(config("clipboard_tab")); for (var i = size() - 1; i >= 0; --i) { print(read(i)); print("\\n"); }'
```

> 2. Clear all the items stored in clipboard history

```sh
copyq 'tab(config("clipboard_tab")); var xs = Array.apply(0, Array(size())).map(function(x,i){return i}); remove.apply(this, xs);'
```

> 3. Disable clipboard storing & Enable clipboard storing

```sh
copyq disable
copyq enable
```

More details in [Scripting API](https://copyq.readthedocs.io/en/latest/scripting-api.html).

**Comment by xd003** [comment]
@hluk thanks a lot for responding , just a last question , do i need to run these commands  necessarily in git bash ?
Because in cmd prompt &  Powershell , they return the following error respectively
```
'copyq' is not recognized as an internal or external command,
operable program or batch file.
```
```
copyq : The term 'copyq' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ copyq 'tab(config("clipboard_tab")); for (var i = size() - 1; i >= 0; ...
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (copyq:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by hluk** [comment]
To use `copyq` or `copyq.exe` on command line, the path to the folder containing the executable needs to be in your `PATH` environment variable.

Alternatively, you can run the commands using Action dialog in CopyQ (F5 shortcut).

**Comment by xd003** [comment]
@hluk 
i have added it to path properly , now no more no recognized as command errors but when i run this - ```copyq 'tab(config("clipboard_tab")); for (var i = size() - 1; i >= 0; --i) { print(read(i)); print("\\n"); }'```  it doesnt ouputs anything

```
PS C:\Users\xd003> copyq 'tab(config("clipboard_tab")); for (var i = size() - 1; i >= 0; --i) { print(read(i)); print("\\n"); }'
PS C:\Users\xd003> copyq 'tab(config("clipboard_tab")); for (var i = size() - 1; i >= 0; --i) { print(read(i)); print("\\n"); }'
PS C:\Users\xd003> copyq 'tab(config("clipboard_tab")); for (var i = size() - 1; i >= 0; --i) { print(read(i)); print("\\n"); }'
PS C:\Users\xd003>
```

While in Copyq GUI its storing items correctly but doesnt reflect anything in powershell/cli

**Comment by hluk** [comment]
This is a bit messy on Windows. You need to append `| Write-Output` or `| cat` to see the output in terminal (see [Command Line](https://copyq.readthedocs.io/en/latest/command-line.html)).

**Comment by xd003** [comment]
@hluk 
Even after appending ```| Write-Output``` or ```| cat``` copyq is not outputting anything in terminal while the GUI has many items stored

```
PS C:\Users\xd003\rclone> copyq 'tab(config("clipboard_tab")); for (var i = size() - 1; i >= 0; --i) { print(read(i)); print("\\n"); }' | Write-Output
PS C:\Users\xd003\rclone> copyq 'tab(config("clipboard_tab")); for (var i = size() - 1; i >= 0; --i) { print(read(i)); print("\\n"); }' | cat
PS C:\Users\xd003\rclone> copyq 'tab(config("clipboard_tab")); for (var i = size() - 1; i >= 0; --i) { print(read(i)); print("\\n"); }' | Write-Output
PS C:\Users\xd003\rclone> copyq 'tab(config("clipboard_tab")); for (var i = size() - 1; i >= 0; --i) { print(read(i)); print("\\n"); }' | cat
```

**Comment by hluk** [comment]
Hmm, not sure what is happening. Unfortunately, I don't have a way to test this.

**Comment by xd003** [comment]
Edit - it seemed to worked well when i tried it in git bash .it seems powershell is having issues even with the cat  or write-output workaround , might wanna confirm working status with powershell with someone else too . Anyways closing this one as the original question was already answered
