### ISSUE TITLE
Show item's dates

### ISSUE THREAD

**Issue by LucioMenci** [hluk/CopyQ#1496]
There is the way to show the creation date of the items?
I think the items should have 3 dates: First creation, last creation (if I copy something that the content is identical to one already present), and last use. They are to be known to the application, but the end user cannot see them into the sheets

**Comment by hluk** [comment]
There's [this command](https://github.com/hluk/copyq-commands/tree/master/Automatic#store-copy-time) to set item creation time (for details, see [README in the same repo](https://github.com/hluk/copyq-commands/blob/master/README.md)).

But to show the first/last creation time, the command would need to be modified to search item list for same data.

To set and show last use time you could use following two commands; one overrides Enter key (and mouse click) for item activation and the other displays the time:

```ini
[Commands]
1\Command="
    copyq:
    var mime = 'application/x-copyq-last-use-time'
    var time = dateString('yyyy-MM-dd hh:mm:ss')
    var items = selectedItemsData()
    for (var i in items) {
        items[i][mime] = time
    }
    setSelectedItemsData(items)
    
    var copyData = {}
    var formats = dataFormats()
    for (var i in formats) {
        var format = formats[i]
        copyData[format] = data(format)
    }
    copy(mimeItems, pack(copyData))
    copySelection(data(mimeText))
    
    if (config('move')) move(0);
    if (config('activate_closes')) hide();
    if (config('activate_focuses')) focusPrevious();
    if (config('activate_pastes')) paste();"
1\Icon=\xf1da
1\InMenu=true
1\Name=Activate and Set Last Use Time
1\Shortcut=return
2\Command="
    copyq:
    var mime = 'application/x-copyq-last-use-time'
    var mimeTags = 'application/x-copyq-tags'
    
    var time = str(data(mime))
    if (time) {
        var tags = str(data(mimeTags))
        setData(mimeTags, tags + ',\xf1da:' + time)
    }"
2\Display=true
2\Icon=\xf1da
2\Name=Show Last Use Time
size=2
```
