### ISSUE TITLE
Consolidate CopyQ existing sites

### ISSUE THREAD

**Issue by sschuberth** [hluk/CopyQ#150]
The CopyQ project is currently spread across:

* GitHub (main web site, source code, issues)
* SourceForge (downloads, wiki)
* Google Code (deprecated project page, mailing list)

It would be nice if at least some of these "entry points" could be consolidated. For example, SF downloads could be moved to [GH releases](https://github.com/blog/1547-release-your-software), and the SF wiki to the GH wiki. The mailing list is not really tied to Google Code, so if the above moving of things was done, the SourceForce and Google Code project pages could go away completely, making it much more clear where the project is hosted and where the latest version could be found.

**Comment by SamHasler** [comment]
You're hosting downloads on SF and GitHub now, but the homepage still points at SF.

**Comment by hluk** [comment]
SF shouldn't be mentioned anywhere now (though the releases are still uploaded there).
