### ISSUE TITLE
Copyq randomly stops saving clipboard

### ISSUE THREAD

**Issue by arbach** [hluk/CopyQ#1500]
**the bug**
copyq starts and works properly on ubuntu, randomly after a day or two without restarting, maybe after suspend, copyq stops saving the clipboard entries. 
The issue is only resolved after restart. Stopping and starting copyq doesn't resloved it. even if the configuration folder is cleared. 

**To Reproduce**

1. start copyq on ubuntu
2. wait few days without restarting
3. Copy anything to clipboard, using any tools, mouse, keyboard or xclip
4. The item is not saved in copyq

**Screenshots**
Debug log
http://screenshot.studio/Oct10MjliN2.png

Everything in the log seems normal, except nothing happen when copying to clipboard. 

**Version, OS and Environment**
Ubuntu 20.04 LTS

**Additional context**
Tried disable and enabled "Clipbaoard storing" did not help 

Debug logo

`DEBUG: Geometry: Window "MainWindow": Restore geometry "Options/MainWindow_geometry": 645x421,673,343 -> 645x421,267,301
DEBUG: Focus window is " _hh_ "
DEBUG: Loading configuration
DEBUG: Configuration loaded
DEBUG: Starting monitor
DEBUG: Executing: copyq --clipboard-access monitorClipboard
DEBUG: Starting callback: onStart
DEBUG: Executing: copyq onStart
DEBUG: Got save state request from session manager.
DEBUG: Focus window is " _hh_ "
DEBUG: Updating tray menu
DEBUG: Tab "&clipboard": Loading items
DEBUG: Tab "&clipboard": 2338 items loaded
DEBUG: Executing: copyq eval -- runMenuCommandFilters()
DEBUG: Updating tray menu
DEBUG: Focus window is "copyq not saving clipboard - Google Search - Brave"
DEBUG: Geometry: Window "ConfigurationManager": Restore geometry "Options/ConfigurationManager_geometry": 679x621,656,243 -> 1049x621,327,211
DEBUG: Focus window is "Configuration — CopyQ"
DEBUG: Focus window is "copyq not saving clipboard - Google Search - Brave"
DEBUG: Terminating monitor
DEBUG: Executing: copyq eval -- setTitle(); showDataNotification()
DEBUG: Clipboard monitoring disabled.
DEBUG: Monitor finished
DEBUG: Raising window "copyq not saving clipboard - Google Search - Brave"
DEBUG: Focus window is "copyq not saving clipboard - Google Search - Brave"
DEBUG: Focus window is "copyq not saving clipboard - Google Search - Brave"
DEBUG: Starting monitor
DEBUG: Executing: copyq --clipboard-access monitorClipboard
DEBUG: Clipboard monitoring enabled.
DEBUG: Raising window "copyq not saving clipboard - Google Search - Brave"
DEBUG: Focus window is "copyq not saving clipboard - Google Search - Brave"
DEBUG: Executing: Command "Show/hide main window"
DEBUG: Focus window is " _hh_ "
DEBUG: Raising window "CopyQ"
DEBUG: Geometry: Window "MainWindow": Restore geometry "Options/MainWindow_geometry": 645x421,673,343 -> 645x421,267,301
DEBUG: Saving items on application state change (2)
DEBUG: Focus window is " _hh_ "
DEBUG: Focus window is "New Issue · hluk/CopyQ - Brave"
DEBUG: Raising window "New Issue · hluk/CopyQ - Brave"

`

**Comment by hluk** [comment]
Can you check the logs from the main window (F12 shortcut)? (Or using `copyq logs` command.) It contains information from all processes, especially the clipboard monitor.

**Comment by arbach** [comment]
When I start copyq from the command line, the log seems fine, although it still doesn't store copied item. 

copyq logs:

`
CopyQ DEBUG [2020-10-26 12:30:29.178] <Server-401208>: Server "/home/xxx/.config/copyq/.copyq_s" started.
CopyQ DEBUG [2020-10-26 12:30:29.239] <Server-401208>: Geometry: Window "MainWindow": Restore geometry "Options/MainWindow_geometry": 645x421,673,343 -> 645x421,267,301
CopyQ DEBUG [2020-10-26 12:30:29.250] <Server-401208>: Focus window is " _hh_ "
CopyQ DEBUG [2020-10-26 12:30:29.253] <Server-401208>: Loading configuration
CopyQ DEBUG [2020-10-26 12:30:29.296] <Server-401208>: Configuration loaded
CopyQ DEBUG [2020-10-26 12:30:29.296] <Server-401208>: Starting monitor
CopyQ DEBUG [2020-10-26 12:30:29.296] <Server-401208>: Executing: copyq --clipboard-access monitorClipboard
CopyQ DEBUG [2020-10-26 12:30:29.297] <Server-401208>: Starting callback: onStart
CopyQ DEBUG [2020-10-26 12:30:29.298] <Server-401208>: Executing: copyq onStart
CopyQ DEBUG [2020-10-26 12:30:29.300] <Server-401208>: Got save state request from session manager.
CopyQ DEBUG [2020-10-26 12:30:29.306] <Server-401208>: Focus window is " _hh_ "
CopyQ DEBUG [2020-10-26 12:30:29.321] <monitorClipboard-401220>: Clipboard formats to save: image/svg+xml, image/png, image/gif, application/x-copyq-encrypted, application/x-copyq-item-notes, application/x-copyq-item-icon, application/x-copyq-item-pinned, application/x-copyq-tags, text/plain, text/html, text/richtext, application/x-copyq-item
CopyQ DEBUG [2020-10-26 12:30:29.322] <monitorClipboard-401220>: Ignoring unchanged selection
CopyQ DEBUG [2020-10-26 12:30:29.322] <monitorClipboard-401220>: Ignoring unchanged clipboard
CopyQ DEBUG [2020-10-26 12:30:29.374] <Server-401208>: Updating tray menu
CopyQ DEBUG [2020-10-26 12:30:29.375] <Server-401208>: Tab "&clipboard": Loading items
CopyQ DEBUG [2020-10-26 12:30:29.381] <Server-401208>: Tab "&clipboard": 2379 items loaded
CopyQ DEBUG [2020-10-26 12:30:29.386] <Server-401208>: Executing: copyq eval -- runMenuCommandFilters()
CopyQ DEBUG [2020-10-26 12:30:29.401] <Server-401208>: Focus window is " _hh_ "
CopyQ DEBUG [2020-10-26 12:30:29.487] <Server-401208>: Updating tray menu
`



Howe ever when I start it from UI, I get the following:


CopyQ DEBUG [2020-10-26 12:32:05.247] <Server-401208>: Executing: copyq --clipboard-access monitorClipboard
CopyQ DEBUG [2020-10-26 12:32:05.273] <Server-401208>: Callback finished
CopyQ DEBUG [2020-10-26 12:32:05.286] <monitorClipboard-401275>: Waiting for server to start
CopyQ DEBUG [2020-10-26 12:32:05.286] <monitorClipboard-401275>: Terminating application on signal.
CopyQ ERROR [2020-10-26 12:32:06.286] <monitorClipboard-401275>: Cannot connect to server! Start CopyQ server first.
CopyQ DEBUG [2020-10-26 12:32:06.289] <Server-401208>: Monitor finished



Either way it doesn't work

**Comment by arbach** [comment]
Some more useful information. When watch the logs, I got the following when I clip "ctl+c"

 <monitorClipboard-401933>: Clipboard unchanged, selection unchanged. Test again in 0ms.

**Comment by arbach** [comment]
closed
