### ISSUE TITLE
v3.13.0 can't import old .cpq files

### ISSUE THREAD

**Issue by piatgithub** [hluk/CopyQ#1501]
**Describe the bug**

since v3.13.0 I can't import my old saved .cpq files

**To Reproduce**

execute:
copyq importData  foo.cpq

See error
ScriptError: Datei „foo.cpq“ kann nicht importiert werden!

**Version, OS and Environment**
% copyq version
CopyQ Clipboard Manager v3.13.0
Qt: 5.15.1
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Arch Linux

**Additional context**

% copyq logs
CopyQ Note [2020-10-27 05:30:38.778] <Client-25177>: ScriptError: Exception in command: Datei „foo.cpq“ kann nicht importiert werden!

I can import new (withv3.13.0) exported tabs without any problems.

Workaround: 
1. I downgrad to v3.12.0
2. start copyq
3. import the old cpq files
4. quit copyq 
4. upgrade to  v3.13.0
5. start copyq
6. export all tabs

**Comment by hluk** [comment]
Oops, I didn't test the backwards compatibility properly in this case. Fixing.

Thanks for the report!
