### ISSUE TITLE
How to paste as plain text for certain programs?

### ISSUE THREAD

**Issue by ooker777** [hluk/CopyQ#1508]
Copied texts from OneNote contains htlm. When pasting them to Google Keep, it doesn't recognize that and thus process the texts as image. Is there a way to tell CopyQ to only paste as plain text if the received programs contain some keywords in their titles?

**Comment by laur89** [comment]
I believe this is the feature usually triggered by `Ctrl+Shift+V`, ie 'paste as plaintext'

**Comment by ooker777** [comment]
I know, but I want to automate this in certain programs

**Comment by hluk** [comment]
Could be done with a modified "Paste clipboard as plain text" command:

```ini
[Command]
Command="
    copyq: 
    var plainTextWindows = [
        'Google Keep',
        'Mozilla Firefox',
    ]
    
    function appNeedsPlainText() {
        var currentTitle = currentWindowTitle()
        for (var i in plainTextWindows) {
            var title = plainTextWindows[i]
            if ( currentTitle.indexOf(title) )
                return true
        }
        return false
    }
    
    focusPrevious()
    if ( appNeedsPlainText() ) {
        var text = clipboard()
        copy(text)
        copySelection(text)
    }
    paste()"
GlobalShortcut=ctrl+shift+v
Icon=\xf0ea
IsGlobalShortcut=true
Name=Paste clipboard as plain text to some apps
```

**Comment by ooker777** [comment]
It has error:

```
Note [2020-11-25 00:09:57.078] <Client-8272>: ScriptError: Exception in command "Paste clipboard as plain text to some apps": ReferenceError: Can't find variable: focusPrevious
Note [2020-11-25 00:09:57.078] <Client-8272>:    
Note [2020-11-25 00:09:57.078] <Client-8272>:    --- backtrace ---
Note [2020-11-25 00:09:57.078] <Client-8272>:    <eval>() at “ ...”:17
Note [2020-11-25 00:09:57.078] <Client-8272>:    --- end backtrace ---
Note [2020-11-25 00:09:57.098] <Server-3548>: Command “Paste clipboard as plain text to some apps”
Note [2020-11-25 00:09:57.098] <Server-3548>:    Exit code: 4
Note [2020-11-25 00:09:57.098] <Server-3548>:     1. copyq:  
Note [2020-11-25 00:09:57.098] <Server-3548>:     2. var plainTextWindows = [
Note [2020-11-25 00:09:57.098] <Server-3548>:     3.     'Google Keep',
Note [2020-11-25 00:09:57.098] <Server-3548>:     4.     'Mozilla Firefox',
```

![image](https://user-images.githubusercontent.com/6695517/100128209-942d8680-2eb2-11eb-8897-d1458758ffdc.png)

**Comment by hluk** [comment]
You need to update your CopyQ installation.

**Comment by Chealer** [comment]
@ooker777: HTML should not paste to Google Keep as an image.

But this is an ITS, so please use [the mailing list](https://groups.google.com/g/copyq) or [GitHub discussions](https://github.com/hluk/CopyQ/discussions) instead. In any case, you should indicate the version you use.

**Comment by ooker777** [comment]
What does ITS mean? https://www.abbreviations.com/ITS

**Comment by Chealer** [comment]
Wow, that's a long list! Sorry, for me it just means an issue tracker (a database of reports of bugs and other software issues): https://en.wiktionary.org/wiki/ITS#Noun
