### ISSUE TITLE
Shortcut for paste as plain text from item list

### ISSUE THREAD

**Issue by m4r71n** [hluk/CopyQ#151]
I saw https://github.com/hluk/CopyQ/issues/35 but instead of a global shortcut I would like to have an application shortcut to paste HTML/rich text as plain text. 
For instance "Ditto clipboard manager" uses shift + enter as shortcut.

**Comment by orschiro** [comment]
> Should be possible with the **following command** which actually **doesn't always work** because `copyq copy` does't wait for the clipboard to be set so the `copyq paste` can possibly paste previous clipboard content.
> 
> If you want to try this out, create new command in Configuration/Commands tab (using "Add" button), set "Format" to `text/plain`, check "In Menu" checkbox, set "Command" to `copyq copy - | copyq hide | copyq paste` and set a "Shortcut" to `Shift+Enter`.
> 
> You can use other command to set the clipboard -- e.g. `xclip -selection clipboard | copyq hide | copyq paste` (which seems to work well).
> 
> This would be pretty useful, so I'll add it as a new sample command after it works properly.

Dear @hluk 

I tried your outlined solution but it's not exactly what I am looking for (I think). Let me outline my process: 

1. I have set up Ctrl + V to open the list menu (the same which is opened from the tray icon)
2. From there I am selecting one of the values from 0 to 4 to paste into the currently focused input field

I do like that it keeps the formatting when pasting. However, sometimes I want to paste one of those values as plain text. Is there a solution to address this?

Solution would be: From the same menu being able to choose to paste with formatting or as plain text. 

Looking forward. 

Yours

**Comment by hluk** [comment]
@orschiro I've just changed the behavior (6e01ef0ee97eca631578f979c0bc847f800957da) so that holding <kbd>Shift</kbd> when selecting an item from menu (or using<kbd>Shift</kbd>+<kbd>Enter</kbd>) will copy/paste only plain text.

**Comment by orschiro** [comment]
@hluk very nice! Thank you so much. Will be released in v3.6.2? :-) 

Yours

**Comment by hluk** [comment]
> Will be released in v3.6.2?

Yup, either that one or 3.7.0 (whatever the next version will be).
