### ISSUE TITLE
CopyQ sticks in dashtopanel when pasting

### ISSUE THREAD

**Issue by aindriu80** [hluk/CopyQ#1515]
Before creating a new issue, see list of [known
issues]
(https://copyq.readthedocs.io/en/latest/known-issues.html).
seen

**Describe the bug**
CopyQ won't stay hidden when I paste text from its clipboard memory.  CopyQ won't remove itself from Panel when I right click on it and click 'Quit' (taskbar for Ubuntu).  

**To Reproduce**
1. Have some text copied (Highlight text with CTRL C in Ubuntu 20.10)
2. Paste the text somewhere else (Using CTRL SHIFT V hotkey in Ubuntu 20.10)
3. Functionality is working but CopyQ appears in Dash To Panel ( https://extensions.gnome.org/extension/1160/dash-to-panel/ ) which is not something I wanted.
4. Can't get CopyQ closed from the Panel, I have to go to File then select exit to remove it then start it up again.

**Expected behavior**
CopyQ to remain hidden at all times unless I specifically load CopyQ to make preference changes.

**Screenshots**
![2020-11-06_21-20](https://user-images.githubusercontent.com/8885837/98415824-e595e300-2075-11eb-8926-5983114d7cc8.png)

**Version, OS and Environment**
CopyQ
Clipboard Manager

 - Application Version -  v3.12.0
 - OS  - Ubuntu 20.10
 - Ubuntu desktop, using Dash To Panel and Arc Menu.

**Additional context**

**Comment by hluk** [comment]
Do you have "Hide main window" option enabled (in "Layout" configuration tab)? You can enable it from command line:

```bash
copyq config hide_main_window 1
```

If it's not enabled and tray icon is not available, the main window will be only minimized when closed.

**Comment by aindriu80** [comment]
> Do you have "Hide main window" option enabled (in "Layout" configuration tab)? You can enable it from command line:
> 
> ```shell
> copyq config hide_main_window 1
> ```
> 
> If it's not enabled and tray icon is not available, the main window will be only minimized when closed.

![2020-11-16_22-12](https://user-images.githubusercontent.com/8885837/99314357-e63e2e80-2858-11eb-811f-3822f7095a50.png)
Hide main window had a tick box, I removed tick box & then re-enabled.  That worked! thanks
