### ISSUE TITLE
How to change tab tag with a shortcut?

### ISSUE THREAD

**Issue by pikaboo** [hluk/CopyQ#1518]
**Is your feature request related to a problem? Please describe.**
I am keeping data in stored tabs, however, when the data has been used, i want to keep it stored but mark it sued

**Describe the solution you'd like**
Select tab, click shortcut on keyboard, add tag "used" to the tab

**Describe alternatives you've considered**
Doing it manually, but it's too daunting

**Comment by hluk** [comment]
Not sure if I understand correctly. Do you want to add a tag to an item stored in a tab?

You can set a shortcut to add/remove a tag -- see [tags documentation](https://copyq.readthedocs.io/en/latest/tags.html).

**Comment by pikaboo** [comment]
no i want to add a tag to the tab, not any of the items in the tab

**Comment by hluk** [comment]
What did you mean by "Doing it manually, but it's too daunting"?

Tags on tabs are not supported. The closes thing is changing an icon or renaming a tab:

```
# The icon symbol is copied from icon-selection-dialog (Ctrl+Shift+T in CopyQ).
# This can be also a path to an image.
copyq tabIcon "Some Tab" ""

copyq renameTab "Some Tab" "Some Tab [used]"
# Adding an icon symbol may also work in some cases.
copyq renameTab "Some Tab" "Some Tab "
```

Here is command to toggle a tag in tab name ([here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)):

```ini
[Command]
Command="
    copyq:
    var tag = '\xf058'
    var tabName = selectedTab();
    
    var i = tabName.indexOf(tag)
    if (i == -1) {
        renameTab(tabName, tabName + tag);
    } else {
        renameTab(tabName, tabName.slice(0, i) + tabName.slice(i + tag.length));
    }
    "
Icon=\xf02b
InMenu=true
Name=Toggle Tab Tag
Shortcut=ctrl+u
```
