### ISSUE TITLE
paste success may depend on whether program where text was copied from is still open

### ISSUE THREAD

**Issue by laur89** [hluk/CopyQ#1520]
**Describe the bug**
Unsure if it's copyq or the program's issue. Whenever text is copied from [meld](https://meldmerge.org/) (a python-based diff viewer), then text can be pasted as expected, but _only_ if meld is still open/running at the time of pasting.

**To Reproduce**
1. open meld (eg `meld  .  .` to diff current dir against itself)
2. copy text from meld
3. paste the text somewhere, eg into terminal - success
4. close meld
5. repeat # 3 - failure - nothing is pasted
6. toggle copyq and press `Enter` (to select the text you copied from meld)
7. repeat # 3 - success

**Expected behavior**
Selection should be pasted regardless of the state of other processes.

**Version, OS and Environment**
    CopyQ Clipboard Manager v3.13.0
    Qt: 5.14.2
    Compiler: GCC
    Arch: x86_64-little_endian-lp64
    OS: Debian GNU/Linux bullseye/sid
    WM: i3

**Comment by hluk** [comment]
This is specific X11 behavior. The app from which you last copied from provides the clipboard content. So if the app is closed, the clipboard is empty.

You can use following command as workaround -- this resets the clipboard to recent content whenever the clipboard owner app is closed ([here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)):

```ini
[Command]
Command="
    var timeoutMilliseconds = 500;
    
    function reset(key, getFn, setFn) {
      if (hasData()) {
        settings(key, [data(mimeText), Date.now()])
      } else {
        var last = settings(key)
        if (!last)
            return;
    
        afterMilliseconds(timeoutMilliseconds, function() {
          if (!str(getFn()) && last[1] == settings(key)[1]) {
            serverLog('Reset from ' + key)
            setFn(mimeText, last[0], mimeHidden, 1)
          }
        })
      }
    }
    
    function resetClipboard() {
      reset('lastClipboard', clipboard, copy)
    }
    
    function resetSelection() {
      reset('lastSelection', selection, copySelection)
    }
    
    var onClipboardChanged_ = onClipboardChanged
    onClipboardChanged = function() {
      onClipboardChanged_()
    
      isClipboard() ? resetClipboard() : resetSelection()
    
      if (!hasData())
        sleep(2 * timeoutMilliseconds)
    }"
Icon=\xf246
IsScript=true
Name=Reset Empty Clipboard/Selection
```
