### ISSUE TITLE
[Feature request]remove all no-pin items

### ISSUE THREAD

**Issue by Vixb1122** [hluk/CopyQ#1522]
**Is your feature request related to a problem? Please describe.**
It's troublesome to remove all no-pin items.

**Describe the solution you'd like**
Provider a button to do it.

**Describe alternatives you've considered**
Ctrl+A, and view all items to deselect pin item.

**Comment by hluk** [comment]
Could be done with the following command ([here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)). It removes all not-pinned items from current tab.
```ini
[Command]
Command="
    copyq:
    var items = Array
        .apply(0, Array(size()))
        .map(function(_, i){ return i; })
        .filter(function(row){ return !plugins.itempinned.isPinned(row) })
    
    if (items.length > 0) {
        remove.apply(this, items)
    }
    
    popup('Remove All Unpinned', 'Removed ' + items.length + ' items')"
Icon=\xf2ed
InMenu=true
MatchCommand="copyq:\nmenuItem['color'] = '#ddd'\nmenuItem['tag'] = '\xf08d'"
Name=Remove All Unpinned
```

**Comment by rod-stuchi** [comment]
Hi @hluk 
_Thank you very much for this project!_ 

why the the popup doesn't trigger?

I've changed your example to remove items with no tags.

```c++
copyq:

var items = Array
    .apply(0, Array(size()))
    .map(function(_, i){ return i; })
    .filter(function(row){ return plugins.itemtags.tags(row) == 0 })

popup('Remove All No Tags', 'Removed ' + items.length + ' items')

if (items.length > 0) {
    remove.apply(this, items)
}
```
