### ISSUE TITLE
Lost Important tag

### ISSUE THREAD

**Issue by Nikit** [hluk/CopyQ#1525]
After sometime some of CPs with Important tag are lost.
Why or how to prevent loosing these?

v.3.12.0
Windows 7 64bit.

**Comment by hluk** [comment]
Do you mean some items no loger show a previously visible tag?

**Comment by Nikit** [comment]
@hluk yes, tagged will autoremoved.

I found that "Pin" item willn't removed.
But any tagged item (even **Important**) will removed after sometime.

**Comment by hluk** [comment]
Tagging only adds a small label to items. Pinning an item, makes sure that it's not removed accidentally and it keeps the item at same row.

There are still cases when pinned item can be removed, e.g. changing tab item limit in some cases or when the "Pinned Items" plugin is not loaded.

**Comment by Nikit** [comment]
But I want to store tagged items. 
"Pin" - it's pinned item in the top of list. So then I have 15 pinned items - it will take all my list place in copyq popup - so I need each time scroll or enter chars.

**Comment by hluk** [comment]
OK, I can see that "locking" tagged items can be handy. I'm adding the support to configure this for specific tags:

![image](https://user-images.githubusercontent.com/38054/100495582-37013180-314d-11eb-8a06-a7a8d6b8f5d1.png)
