### ISSUE TITLE
Copyq autostarts without tray icon

### ISSUE THREAD

**Issue by ShrirajHegde** [hluk/CopyQ#1526]
Before creating a new issue, see list of [known
issues](https://copyq.readthedocs.io/en/latest/known-issues.html).

**Describe the bug**
The tray icon is missing on autostart but copyq is running (shortcuts and clipboard recording keep working)

**To Reproduce**
1. Go to add copy q to startup (gnome)
2. Restart
**Expected behavior**
Tray icon just like when copyq is started normally

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 CopyQ Clipboard Manager v3.13.0
Qt: 5.15.1
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Arch Linux

**Additional context**
Just killing the process and relaunching it solves the problem (tray icon reappears)

**UPDATE** : This bug isn't present in  v3.10.0

**Comment by ricir** [comment]
Similar to [https://github.com/hluk/CopyQ/issues/1517](url)

I have the same problem in Ubuntu 2010 and found a [workaround](https://github.com/hluk/CopyQ/issues/1517#issuecomment-728865342) by adding a delay before start of copyQ.

**Comment by ShrirajHegde** [comment]
> I have the same problem in Ubuntu 2010 and found a [workaround](https://github.com/hluk/CopyQ/issues/1517#issuecomment-728865342) by adding a delay before start of copyQ in Autostart.

I have tried `sleep 10 && copyq` still no results

**Comment by giancarloGiuffra** [comment]
> I have tried `sleep 10 && copyq` still no results

Indeed, writing the command directly on the startup application definition does not work.

I had to create a script with the suggested workaround by @ricir :
```bash
sleep 5
copyq
```
and then call the script in the startup application definition.

**Comment by ShrirajHegde** [comment]
I am using a different aproach to kill and then relaunch copyq

```
killall copyq
sleep 3
copyq &
```

**Comment by ShrirajHegde** [comment]
This bug isn't absent in v3.10.0

**Comment by hluk** [comment]
Hmm, CopyQ already waits for tray to be available. My guess is that it's either a Qt bug ( `QSystemTrayIcon::isSystemTrayAvailable()` returns wrong status) or some bug in the desktop environment.

You can try adding following command that resets the tray icon automatically after the app start ([here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)):

```ini
[Command]
Command="
    /* Workaround for showing tray icon in some desktops environments.
     * Temporarily toggles tray icon few seconds after start.
     */
    var resetAfterSeconds = 1;
    
    var disableTray = 'disable_tray';
    var hideWindow = 'hide_main_window';
    
    var onStart_ = global.onStart;
    global.onStart = function() {
        onStart_();
        if (config(disableTray) == 'false') {
            afterMilliseconds(resetAfterSeconds * 1000, function(){
                // Enable also hide_main_window option temporarily
                // to avoid showing main window after tray is disabled.
                var hideWindowPrevious = config(hideWindow);
                config(
                    hideWindow, true,
                    disableTray, true,
                );
                config(
                    hideWindow, hideWindowPrevious,
                    disableTray, false,
                );
                abort()
            })
            sleep((resetAfterSeconds + 5) * 1000);
        }
    }"
Icon=\xf079
IsScript=true
Name=Reset Tray Icon On Start
```

**Comment by krishna-kushwaha** [comment]
> Similar to [https://github.com/hluk/CopyQ/issues/1517](url)
> 
> I have the same problem in Ubuntu 20.10 and found a [workaround](https://github.com/hluk/CopyQ/issues/1517#issuecomment-728865342) by adding a delay before start of copyQ in Autostart.

Thanks @ricir,  I edited startup command with delay `sh -c "sleep 10; copyq"` and it worked.
I am using Ubuntu 20.10.

**Comment by pwntr** [comment]
Also stumbled on this with a fresh Ubuntu 20.04.1 install + the ppa version 3.13 of copyq installed. Tried [this](https://github.com/hluk/CopyQ/issues/1526#issuecomment-738757967) but then copyq wouldn't even start anymore at all (syntax errors).

I tried the other recommendation with the delayed start, and with a small script in place, it works just fine again. See below in case anyone else tries to figure out the precise steps necessary:

1. created a small script in `/home/USERNAME/.config/copyq/delayed_start_workaround.sh`, with content `sleep 3; /usr/bin/copyq` and made it executable
2. edited `/home/USERNAME/.config/autostart/copyq.desktop` and inserted the full path of the workaround script under `Exec=`, like `Exec="/home/USERNAME/.config/copyq/delayed_start_workaround.sh"`. One might get also away by using the `~` shortcut for their home dir, too.

As mentioned [here](https://github.com/hluk/CopyQ/issues/1526#issuecomment-735995846), just adding the sleep delay under `Exec=` didn't yield any result.

Btw: thx a ton for this great tool :)!

**Comment by AdamPS** [comment]
Many programs are seeing this bug recently, for example see [this issue](https://github.com/keepassxreboot/keepassxc/issues/5691) for keepassxc.  The fix there looks good - edit .config/autostart/copyq.desktop and add a delay:

`X-GNOME-Autostart-Delay=3`

**Comment by asyks** [comment]
> Many programs are seeing this bug recently, for example see [this issue](https://github.com/keepassxreboot/keepassxc/issues/5691) for keepassxc. The fix there looks good - edit .config/autostart/copyq.desktop and add a delay:
> 
> `X-GNOME-Autostart-Delay=3`

This worked for me in ubuntu 20.04

**Comment by pwntr** [comment]
> > Many programs are seeing this bug recently, for example see [this issue](https://github.com/keepassxreboot/keepassxc/issues/5691) for keepassxc. The fix there looks good - edit .config/autostart/copyq.desktop and add a delay:
> > `X-GNOME-Autostart-Delay=3`
> 
> This worked for me in ubuntu 20.04

+1, much easier than the full-script workaround. Seems to be used by more and more projects and closed source apps, too. [Insync](https://www.insynchq.com/) uses this for their desktop file as well.

**Comment by danielsanfr** [comment]
I tried here, but it didn't work.

![2021-01-15_21-57](https://user-images.githubusercontent.com/3621711/104792290-a625fa00-577c-11eb-8602-4a51dd461469.png)

But I haven't tested it yet, disabling all the extensions I use.

**Comment by AdamPS** [comment]
Great thanks

**Comment by sans-clue** [comment]
For us noobs who installed the package on Ubuntu 20.04 via `apt`, how can we update to `v3.13.0`?

We only seem to have `3.10.0-1` available.

**Comment by pwntr** [comment]
> For us noobs who installed the package on Ubuntu 20.04 via `apt`, how can we update to `v3.13.0`?
> 
> We only seem to have `3.10.0-1` available.

[Adding the CopyQ Ubuntu PPA](https://github.com/hluk/CopyQ#ubuntu-ppa) and running an upgrade or reinstall of copyq should be enough to get the latest version. Works fine for me on Ubuntu 20.4.2:

```
$ copyq --version
CopyQ Clipboard Manager v3.13.0
Qt: 5.12.8
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Ubuntu 20.04.2 LTS
```

After that, just add the workaround / fix described above to get the tray working again when autostart is enabled.

**Comment by sirianni** [comment]
I am running Gnome 3.38.4 on Manjaro.  Using `X-GNOME-Autostart-Delay` does not fix the issue for me.

**Comment by ShrirajHegde** [comment]
> I am running copyq `3.13.0-1` on Gnome 3.38.4 on Manjaro. Using `X-GNOME-Autostart-Delay` does not fix the issue for me.

execute `killall copyq && sleep 7 && copyq` on startup

**Comment by Vichman67** [comment]
Dear hluk,

I'm not compiling copyq, just installing the version available from your repo (http://ppa.launchpad.net/hluk/copyq/ubuntu), so I don't know:

1. If my version is compiled with WITH_NATIVE_NOTIFICATIONS.
2. How to use preferably native tray icon (if this is accomplished by 'CopyQ > Preferences > Notifications > Use native notifications' check box, I've tried both checking and unchecking it, without success).

Thanks!

**Comment by Vichman67** [comment]
Great,

I've solved the problem by installing the Gnome extension '[AppIndicator and KStatusNotifierItem Support](https://extensions.gnome.org/extension/615/appindicator-support/)'. But if you install it, please restart your system inmediately after that, cause otherwise it may freeze your desktop.

Now my tray icon is visible and responsive to left or right click:

![image](https://user-images.githubusercontent.com/12735950/140813914-ad639edc-72c1-4c4b-be0b-dc4320b962d4.png)

Thanks for your support!

**Comment by martin-greentrax** [comment]
I'm using i3wm + polybar as a desktop environment and also face the problem. Will see if a sleep delay will help.

**Comment by ipatch** [comment]
> I'm using i3wm + polybar as a desktop environment and also face the problem. Will see if a sleep delay will help.

same boat as you. this seems to be working for me at the moment.

https://github.com/ipatch/dotfiles/blob/6b605af148dfe56df96110bded9a374ac048862d/config/i3/config#L31-L32

**Comment by martin-greentrax** [comment]
Good luck, I have switched to Parcellite by now as copyq wasn't reliably available per autostart. 
(I stole flameshot from your config :+1: )
