### ISSUE TITLE
Failed import exported file (.cpq)

### ISSUE THREAD

**Issue by ramisedhom** [hluk/CopyQ#1527]
**Describe the bug**
Failed import exported file (.cpq)

**To Reproduce**
1. In version 3.12.0
2. Go to 'File -> Export'
3. Click on 'All' > 'Ok', save the file to 'backup.cpq'
4. In version 3.13.0
5. Go to 'File' > 'Import', select 'backup.cpq' and click 'Open'
6. See error: 'Failed to import file'

**Expected behavior**
Expected that file imported successfully or meaningful reason for failing.

**Screenshots**
![image](https://user-images.githubusercontent.com/1517228/99794641-26d8c900-2b33-11eb-9bbf-96b6084a3ce4.png)

**Version, OS and Environment**
 - Application Version [3.13.0]
 - OS [Windows 10]

**Comment by Raialbe** [comment]
Can confirm this also happens on Linux

**Comment by hluk** [comment]
Already fixed in #1501.

Unfortunately, until it's released, you may need to use previous version to import older `*.cpq` files.
