### ISSUE TITLE
ALTERNATIVE DONATION METHODS

### ISSUE THREAD

**Issue by G-i-o** [hluk/CopyQ#1528]
It seems that currently the only way to donate to this project is to use Liberapay, which is certainly a great alternative to other proprietary, profit oriented platforms like Patreon etc.

However, Lp still replies on centralized services which cause them to charge considerable fees. Moreover, one prospect donor has to register and then commit to recursive donations, albeit those can be cancelled at any time. This can keep some donors who would be otherwise happy to make a donation, or more, away from doing it.

May I suggest to add some other options? Here's the why, how and where:

WHY

* Avoid high fees
* Avoid chargebacks
* Increase marketing
* Fight unethical practices of big companies such Paypal.
* Saveguard privacy

HOW

* Directly by creating a crypto address and giving that away (ask for help if needed). Free but requires a bit of maintenance.
* Using a payment gateway (see list below). Usual charges are in the range of 05-1% and automatic conversion, invoices and other merchant tools are also available.

WHERE

* Nowpayments.io
* Cryptocurrencycheckout.com
* Coingate.com
* Coinpayments.com
* Vendible.org
* Plisio.net
* Bitpay.com
* Spicepay.com 

Thank YOU.

**Comment by hluk** [comment]
I moved to Liberapay relatively recently. There is still active account on [Bountysource](https://www.bountysource.com/teams/copyq).

It seems that there are too many alternatives and each has its own issues.

I will probably wait before creating new account on another service.
