### ISSUE TITLE
Not able to use  copyq when terminal is active in debian 10 with VGA cards AMD/ATI or i915(HP)

### ISSUE THREAD

**Issue by jaaved** [hluk/CopyQ#1529]
I use debian 10 from three difference devices or machine. In one of the machine VGA drivers are of NVidia  copyq works as expected. However, when I use machine that has VGA card of either AMD/ATI or i915(HP), the behavior of copyq is weird and annoying:

[copyq][3]:
When terminal is active, using copyq shortcut does not activate it. When I switch to another windows(anything that is not tilix or terminal or terminal, e.g. chrome), it works.

This behavior is annoying, how can I fix this problem?

  [3]: https://hluk.github.io/CopyQ/

**Comment by hluk** [comment]
That is strange and it doesn't look like an issue in CopyQ. Any chance you are using Wayland instead of X11?

What's the terminal app, desktop environment and window manager?

Can you check logs for any errors/warnings (F12 from main window or `copyq logs`)?

**Comment by jaaved** [comment]
I changed the desktop environment to GNOME Classic and Copyq is working fine. I was using GNOME before. I tested this on two machines and switching to  GNOME Classic  helped @hluk .
