### ISSUE TITLE
Select item with given id does not work

### ISSUE THREAD

**Issue by m4r71n** [hluk/CopyQ#153]
"Type any number to select item with given id." as mentioned in the README.md does not work for me with Windows 7 x64 and CopyQ 2.0.0. Instead the search/filter is shown.

**Comment by sl5net** [comment]
My hit list is numbered. How can I select a match by number?

**Comment by sl5net** [comment]
woraround with [autoKey](https://github.com/autokey/autokey)

if i inside copyQ i use shortcut Ctrl+g to start this python.
it copys numer to clipboard and sends it. 
```
winTitle = window.get_active_title()
ok, text = dialog.input_dialog("Line ", "Choose line number ", default='10')
time.sleep(.1)
if winTitle != "AutoKey":   
    myCmd = 'copyq select ' + text # works :) 
    os.system(myCmd)
    keyboard.send_keys("<ctrl>+v")
    quit()
```
