### ISSUE TITLE
request add color feature to copyq

### ISSUE THREAD

**Issue by ikinugrihi** [hluk/CopyQ#1530]
**Is your feature request related to a problem? Please describe.**
can't search the required list grouped by color

**Describe the solution you'd like**
added a feature about coloring the clipboard list in our tab to make it easier to group the clipboard list and it would be easier if you use right-click and then the coloring menu appears, and it would be easier if you could sort by color

maybe like attachment, and thanks about feedback

![Screenshot_20201202_120902](https://user-images.githubusercontent.com/43973450/100831180-cc772b00-3497-11eb-862b-9bb677011f01.png)

**Comment by hluk** [comment]
You can use [Mark Selected Items](https://github.com/hluk/copyq-commands/tree/master/Application#mark-selected-items) command (see [README](https://github.com/hluk/copyq-commands/blob/master/README.md) file on how to install the command).

It should be possible to modify the command to use a different color, choose one from a dialog or cycle through predefined colors.
