### ISSUE TITLE
Paste then re-select row in tray is skipping paste behavior

### ISSUE THREAD

**Issue by Izaya-San** [hluk/CopyQ#1531]
I'm using this script which is working as expected (paste the Nth Item): 

> copyq:
> var shortcut = str(data("application/x-copyq-shortcut"))  // Get name of the shortcut, for example: ctrl+num+4
> var number = shortcut.match(/[0-9]/g);  // Get the digit in the shortcut
> copy("application/x-copyq-item", pack(getItem(number)))  // Copy the content of the number's row
> paste()

But if I add a last row in this script to trigger the 0th Item

> select(0)

it triggers well the 0th item but it doesn't paste nothing. Is it a bug? Or is it my code?

**Comment by hluk** [comment]
[select()](https://copyq.readthedocs.io/en/latest/scripting-api.html#select) doesn't paste items. You need to call `paste()` after it.

**Comment by Izaya-San** [comment]
Yes but that's not what I'm searching for. I was unclear sorry I'll explain it deeper:

Let's say my clipboard contains:

> 0: abc
> 1: def
> 2: ghi

If I press the key: `ctrl+num+1` I would like that copyq to:
- trigger 1
- paste the content of 1 (here: def)
- trigger 0 (I don't want to paste it, just trigger it)

So if I press `ctrl+num+1` it pastes the content of 1. Then if I press `ctrl+v` just after, I would like copyq to paste the content of 0 (abc).

My current script is doing well the two firsts points of my example but not triggering 0 at the end. So if I press `ctrl+v` after `ctrl+num+1`, it pastes the content of 1, not 0. 

Is it possible to do that?  I thought `select()` was doing the job but it's perhaps not the good way to do it.

**Comment by hluk** [comment]
> So if I press `ctrl+num+1` it pastes the content of 1. Then if I press `ctrl+v` just after, I would like copyq to paste the content of 0 (abc).

You can use similar `copy()` call as in the command, i.e. to copy the first item: `copy(mimeItems, pack(getItem(0)))`

I'm not sure why `select(0)` doesn't work for you. Does the order of items change after you trigger the command? What is your CopyQ version?

**Comment by Izaya-San** [comment]
CopyQ version:

> CopyQ Clipboard Manager v3.10.0
> Qt: 5.12.5
> Compiler: GCC
> Arch: x86_64-little_endian-lp64
> OS: Ubuntu 20.04.1 LTS

Adding this line at the end of my code: 

> select(0)

Or this one:

> copy("application/x-copyq-item", pack(getItem(0)))

Does the same thing: If I press `ctrl+num+1` it pastes the content of 0, not 1. But it's well triggering 0 at the end. 

I don't understand what is happening. It seems `paste()` is executed after the `select(0)` (or `copy(...)`).

**Comment by hluk** [comment]
Can you share the whole command? Use "Copy Selected" button in the Command dialog (the copied command should start with `[Command]`).

**Comment by Izaya-San** [comment]
The command (without last line discussed before) is: 

> [Command]
> Command="
>     copyq:
>     var shortcut = str(data(\"application/x-copyq-shortcut\"))  // Get name of the shortcut, for example: ctrl+num+4
>     var number = shortcut.match(/[0-9]/g);  // Get the digit in the shortcut
>     copy(\"application/x-copyq-item\", pack(getItem(number)))  // Copy the content of the number's row
>     paste()"
> GlobalShortcut=ctrl+num+1, ctrl+num+2, ctrl+num+3, ctrl+num+4, ctrl+num+5, ctrl+num+6, ctrl+num+7, ctrl+num+8, ctrl+num+9, ctrl+num+0
> Icon=\xf15b
> IsGlobalShortcut=true
> Name=Copy Nth Item

**Comment by hluk** [comment]
Hmm, try adding `sleep(1000)` after `paste()` (before the next `copy()`) - looks like pasting the item needs some more time.

**Comment by Izaya-San** [comment]
Ho yes, obviously it works! It works with `select(0)` and with 'copy(...)`. So it was only a pasting latency issue. 

So it's not linked to copyq right? That's the os taking more time to execute the paste command than copyq execute the next one.

Thanks a lot for your help and your time!
