### ISSUE TITLE
Paste to current window not working in Mac Big Sur

### ISSUE THREAD

**Issue by ninad-thakur** [hluk/CopyQ#1532]
After upgrading to MacOS Big Sur, Paste to Current Window does not work anymore.

**Comment by hluk** [comment]
Did you try [this workaround](https://copyq.readthedocs.io/en/latest/known-issues.html#known-issue-macos-paste-after-install)?

**Comment by scytalezero** [comment]
The workaround fixes it for me, thank you!

**Comment by ninad-thakur** [comment]
Worked for me! Thanks.
