### ISSUE TITLE
Tray not showing after clicking menu bar icon on macOS Big Sur

### ISSUE THREAD

**Issue by GingerPapa** [hluk/CopyQ#1533]
**Describe the bug**
When I click the CopyQ menu bar icon, instead of showing the tray, CopyQ shows the main window instead. I have tried disabling + re-enabling the tray, creating custom keyboard shortcuts to show the tray, restarting my Mac, and reinstalling CopyQ, but it still doesn't show. This is the first time I've come across this problem after using CopyQ for many months.

**Screenshots**
_What should show after clickling the menu bar icon:_
![How life should be](https://user-images.githubusercontent.com/65316470/101234561-6c130400-36b8-11eb-8a0f-a47f74b8ae67.png)
_What CopyQ shows instead:_
![Screen Recording 2020-12-05 at 13 03 01](https://user-images.githubusercontent.com/65316470/101234538-1c343d00-36b8-11eb-918d-40d235d796d1.gif)

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Application Version [e.g. 3.7.2]: 3.13.0
 - OS [e.g. Windows]: macOS Big Sur

**Comment by hluk** [comment]
This has been changed in 3.13.0. See [the release notes](https://github.com/hluk/CopyQ/releases/tag/v3.13.0).

To re-enable the old behavior: `copyq config tray_menu_open_on_left_click true`

**Comment by david101-hunter** [comment]
after I run `copyq config tray_menu_open_on_left_click true`, it raise a error:  segmentation fault on macbook pro m3. anyone can resolve it?
