### ISSUE TITLE
Bkav+ on virustotal.com

### ISSUE THREAD

**Issue by dtlmednet** [hluk/CopyQ#1537]
Is this a false positive?

[copyq-v3.13.0-setup
](https://github.com/hluk/CopyQ/releases/download/v3.13.0/copyq-v3.13.0-setup.exe)

![image](https://user-images.githubusercontent.com/58869709/102022539-5f3b8380-3d3c-11eb-9ed5-ebfc87711d29.png)

**Comment by dtlmednet** [comment]
![image](https://user-images.githubusercontent.com/58869709/102022648-0ddfc400-3d3d-11eb-9797-5d396ea47f83.png)

**Comment by hluk** [comment]
It's most probably a false positive, unless there is an issue with getting the installer software (installed using from chocolatey package manager) or Qt libraries (available on AppVeyor build servers).

Is this also an issue with the zip file? https://github.com/hluk/CopyQ/releases/download/v3.13.0/copyq-v3.13.0.zip

**Comment by dtlmednet** [comment]
> It's most probably a false positive, unless there is an issue with getting the installer software (installed using from chocolatey package manager) or Qt libraries (available on AppVeyor build servers).
> 
> Is this also an issue with the zip file? https://github.com/hluk/CopyQ/releases/download/v3.13.0/copyq-v3.13.0.zip

Nope.
