### ISSUE TITLE
I estimate that perhaps 20% of the time when I press `Ctrl + v` to paste nothing is pasted

### ISSUE THREAD

**Issue by Yekutiel** [hluk/CopyQ#1539]
I searched on CopyQ Github for [closed and open issues containing the word zero.](https://github.com/hluk/CopyQ/issues?q=zero+)

I looked at the list of [known issues](https://copyq.readthedocs.io/en/latest/known-issues.html).

**Describe the bug**
I estimate that perhaps 20% of the time when I press `Ctrl + v` to paste, nothing is actually pasted.

**To Reproduce**
1. I press `Ctrl + v` 
2. About one time out of five nothing is pasted.
3. About four times out of five my clipboard is pasted.

**Expected behavior**
I expect 100% of the time, that when I press `Ctrl + v` my clipboard will be pasted.

**Version, OS and Environment**
- Lubuntu 20.04 LTS
- CopyQ 3.10.0

**Additional context**
As a workaround when I press `Ctrl + v`, yet nothing is pasted...

1. I open CopyQ and
2. then I press `Enter`

When I open CopyQ and then I press **`Enter`** my clipboard is always pasted properly.

Finally, I copied and pasted my CopyQ log to [Pastebin](https://pastebin.com/SAPDFd6s)

**Comment by hluk** [comment]
Definitely update to a newer version of the app -- 3.10.0 is very old.

**Comment by Yekutiel** [comment]
Thanks for letting me know. I appreciate that.

I just installed CopyQ using...

```
sudo add-apt-repository ppa:hluk/copyq
sudo apt update
sudo apt install copyq
```

I hope that will solve the problem I was having.
