### ISSUE TITLE
Preview Window Cuts off after 2.5 lines?

### ISSUE THREAD

**Issue by squirrelboot** [hluk/CopyQ#1540]
**Describe the bug**
When trying to view preview of my text, and placing it in the top of the copyq pane, it cuts off text.
I am unable to see the remaining items.

Press F7 to show preview pane. Move preview pane around. 

**Expected behavior**
I expect it to resize, and display all items possible within the size of the preview window, or at least scroll.
It now cuts everything off. 

**Screenshots**
https://i.imgur.com/0cCeNJK.png

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Application Version v3.12.0
 - Windows 10 x64

**Additional context**
Even when taking the preview pane out of the main window:
https://i.imgur.com/f8MRKvz.png

Or on the side as well:
https://i.imgur.com/YTl04Q7.png

I do not see (maybe I am blind, it's possible) some way to adjust this behavior from within the settings of CopyQ. I can change the theme, but not other things.

**Comment by hluk** [comment]
Already fixed in #1472.

Please update to a newer version if possible.
