### ISSUE TITLE
This is primarily a copy of Issue: Bug report #1539- I estimate that perhaps 20% of the time when I press `Ctrl + v` to paste nothing is pasted

### ISSUE THREAD

**Issue by Yekutiel** [hluk/CopyQ#1541]
The following is primarily copied and pasted from Bug report #1539.

I searched on CopyQ Github for [closed and open issues containing the word zero.](https://github.com/hluk/CopyQ/issues?q=zero+)

I looked at the list of [known issues](https://copyq.readthedocs.io/en/latest/known-issues.html).

**Describe the bug**
I estimate that perhaps 20% of the time when I press `Ctrl + v` to paste, nothing is actually pasted.

**To Reproduce**
1. I press `Ctrl + v` 
2. About one time out of five nothing is pasted.
3. About four times out of five my clipboard is pasted.

**Expected behavior**
I expect 100% of the time, that when I press `Ctrl + v` my clipboard will be pasted.

**Version, OS and Environment**
- Lubuntu 20.04 LTS
- CopyQ  3.13.0 (I upgraded earlier today from an older version)

**Additional context**
As a workaround when I press `Ctrl + v`, yet nothing is pasted...

1. I open CopyQ and
2. then I press `Enter`

When I open CopyQ and then I press **`Enter`** my clipboard is always pasted properly.

I copied and pasted my CopyQ log to [Pastebin](https://pastebin.com/inZjMfCJ)

Finally, I don't know if it is relevant, but I followed the advice of @hluk listed https://github.com/hluk/CopyQ/issues/485#issuecomment-708899500 which starts with, 

> Another solution could be to mask font style defined in HTML

**Comment by hluk** [comment]
Is CopyQ overriding Ctrl+V shortcut?

Can you check the clipboard and selection formats when this happens? E.g. with `copyq clipboard "?"; copyq selection "?"` command in terminal.

Does it happen even when CopyQ is not running?

BTW, you posted log from the previous issue (from version 3.10.0).

**Comment by Yekutiel** [comment]
Thanks for taking the time to respond to me. Also, thanks for your help.

> Is CopyQ overriding Ctrl+V shortcut?

I don't know. How would I find out the answer to that question?


> Can you check the clipboard and selection formats when this happens? E.g. with copyq clipboard "?"; copyq selection "?" command in terminal.

Although I did not have a problem at the moment, as a test I just ran...
> copyq selection "?"

and

> copyq clipboard "?";

in a terminal.

In response to both commands I received the following...

```
TIMESTAMP
TARGETS
SAVE_TARGETS
MULTIPLE
text/plain
```

> Does it happen even when CopyQ is not running?

I don't know because CopyQ is almost always running.


> BTW, you posted log from the previous issue (from version 3.10.0).

I'm sorry about that. I just copied and pasted the [log for version 3.13 in pastebin]( https://pastebin.com/gU89bZF0)

**Comment by hluk** [comment]
From the logs it seems everything is slow, including clipboard access.

What is your desktop environment and window manager?

Can you share the commands in CopyQ? This is basically content of `~/.config/copyq/copyq-commands.ini` file.

**Comment by Yekutiel** [comment]
> From the logs it seems everything is slow, including clipboard access.

Thanks for letting me know. 


> What is your desktop environment and window manager?

My desktop environment is **LXQt**.
My window manager is **Openbox**.

I'm using Lubuntu 20.04.1 LTS.


> Can you share the commands in CopyQ? This is basically content of ~/.config/copyq/copyq-commands.ini file.

Yes.

I just uploaded the contents of [copyq-commands.ini](https://pastebin.com/JXUbrvAx) to Pastebin.com

**Comment by hluk** [comment]
Thanks for sharing the commands.

I don't see anything wrong with the commands. But the logs say that the "MatchCommand" entries in commands take too long to execute (e.g. "Menu item filters: Finished in 500 ms") or straight up loses connection to the server ("Connection lost!").

Maybe there is a bigger issue when starting the application. You can try checking the debug output in terminal (and logs):
1. Exit the application (`copyq exit`).
2. Run in terminal: `env COPYQ_LOG_LEVEL=DEBUG copyq`
3. Check logs from the app with F12 shortcut.

You can also try disabling "Add tag ..." and "Remove tag ..." commands (uncheck the commands in the left pane in the Command dialog). This could improve things a bit.

**Comment by Yekutiel** [comment]
> Thanks for sharing the commands.

Thanks for reading them.


> I don't see anything wrong with the commands. 

I see.


> But the logs say that the "MatchCommand" entries in commands take too long to execute (e.g. "Menu item filters: Finished in 500 ms") or straight up loses connection to the server ("Connection lost!").

That seems like a problem.


> Maybe there is a bigger issue when starting the application.

Perhaps.


> You can try checking the debug output in terminal (and logs):

```
Exit the application (copyq exit).
Run in terminal: env COPYQ_LOG_LEVEL=DEBUG copyq
```
[My results from running... env COPYQ_LOG_LEVEL=DEBUG copyq](https://pastebin.com/5n1Yvhj5)


> Check logs from the app with F12 shortcut.

There's nothing new in the log file. The last update was 3 November 2020. Should the log file update frequently (perhaps, for example, every few days)?


You can also try disabling "Add tag ..." and "Remove tag ..." commands (uncheck the commands in the left pane in the Command dialog). This could improve things a bit.`

I did not see how to disabe "Add tag ..." and "Remove tag ..." , but [I did uncheck this box](https://i.imgur.com/uFZOlCl.png)

**Comment by hluk** [comment]
Oh, I missed that the logs were still very old. They should update immediately, showing the same lines as on output of the `COPYQ_LOG_LEVEL=DEBUG copyq` command with more information from other processes.

Can you check output of `copyq logs`?

To verify that the log file is OK (in bash):

```bash
ls -l "$(copyq info log)"
```

**Comment by Yekutiel** [comment]
When I just ran `ls -l "$(copyq info log)"` it a terminal the output was...

```
y@y-peppy:~$ ls -l "$(copyq info log)"
-rw-rw-r-- 1 y y 110740 Dec 20 15:14 /home/y/.local/share/copyq/copyq/copyq.log

```
Because I was curious, I just navigated to...

`/home/y/.local/share/copyq/copyq/copyq.log`

You can see [the contents the log file I copied from... /home/y/.local/share/copyq/copyq/copyq.log](https://pastebin.com/j4TGWF0B)

That log file is **different** from the log file I obtained when I went to `CopyQ–>Help–> Show Log`

**Comment by hluk** [comment]
Can you check which file the Log dialog uses? There is label with the path next to the check boxes below the log output.

![image](https://user-images.githubusercontent.com/38054/102745965-8c4fed80-435d-11eb-8c4d-feebd9b07cac.png)

**Comment by Yekutiel** [comment]
![Screenshot at 22-31 on Sunday 20 Dec 2020](https://user-images.githubusercontent.com/16394972/102746421-19218980-4313-11eb-9eec-c448d3c5d047.png)

My point in the penultimate message—which I should have indicated explicitly—was that, strangely, the contents of...

`/home/y/.local/share/copyq/copyq/copyq.log`

are in fact **different** from that what is shown from the log file I obtained when I went to `CopyQ–>Help–> Show Log`

**Comment by hluk** [comment]
I'll check later why the log is incomplete in the GUI (could be some file buffering or just that only part of the file read due to a limited number of lines).

Good thing is that there are no errors or warnings from CopyQ now.

One problem with pasting in X11 on Linux is that if the current owner of the clipboard is closed (usually the last application where you copied content from), the clipboard is cleared. So it usually not possible to open an app, copy text from it, close it, and paste it elsewhere (at this point the clipboard is empty again because the clipboard owner/provider is closed).

To avoid this you can use [Reset Empty Clipboard/Selection](https://github.com/hluk/copyq-commands/tree/master/Scripts#reset-empty-clipboardselection) command.

I'm not sure if that is what's happening because `copyq clipboard "?"` shows that there is some text (`plain/text`). The issue could be simply in the target or source apps of the copy/paste operations.

**Comment by Yekutiel** [comment]
> I'll check later why the log is incomplete in the GUI (could be some file buffering or just that only part of the file read due to a limited number of lines).

Thanks for letting me know. I appreciate that.

 
> Good thing is that there are no errors or warnings from CopyQ now.

I agree.

 
> One problem with pasting in X11 on Linux is that if the current owner of the clipboard is closed (usually the last application where you copied content from), the clipboard is cleared. So it usually not possible to open an app, copy text from it, close it, and paste it elsewhere (at this point the clipboard is empty again because the clipboard owner/provider is closed).
 
> To avoid this you can use [Reset Empty Clipboard/Selection](https://github.com/hluk/copyq-commands/tree/master/Scripts#reset-empty-clipboardselection) command.

I have not experienced that problem.

The I have experienced a problem that is **similar** yet different.

Normally, the text I have copied using `Ctrl + x` or `Ctrl + c` is in CopyQ. In other words, I can see the text I have copied listed as item 0 in CopyQ. However, about 20% of the time that I press `Ctrl + v` to paste instead of the text in  item 0 being pasted, **nothing is pasted** whatsoever. As a workaround I open CopyQ and the press `Enter`. In other words, by opening CopyQ and pressing enter, I am able to **always** (100% of the time) able to paste item 0 listed in CopyQ.

I'm going to essentially repeat the previous paragraph to be sure you understand me clearly. I am mildly annoyed because approximately 4 out of 5 (80% of the time) I press `Ctrl + v` to paste and the text is pasted successfully. However, approximately 1 out of 5 (20% of the time) I press `Ctrl + v` to paste and nothing is pasted. As a result, in these approximately 1 out of 5 cases I need to open CopyQ and press `Enter` to paste the text.

![Screenshot at 14-55 on Monday 21 Dec 2020](https://user-images.githubusercontent.com/16394972/102829850-d3a99e80-439c-11eb-9fef-009e4457db17.png)


> I'm not sure if that is what's happening because `copyq clipboard "?"` shows that there is some text (`plain/text`). The issue could be simply in the target or source apps of the copy/paste operations.

I explicitly set up a shortcut in CopyQ to paste plain text because I often paste plain text. Perhaps that is what you have noticed.

**Comment by hluk** [comment]
Thanks for taking the time to clear this up.

It still sounds like either an issue with the current clipboard owner---which is not CopyQ unless you specifically copy something from it---or the app where you paste.

> I explicitly set up a shortcut in CopyQ to paste plain text because I often paste plain text. Perhaps that is what you have noticed.

I noticed, but there are no Ctrl+V global shortcuts so I don't see any issue here.

By default, CopyQ only reads/requests the new clipboard content automatically but doesn't change the clipboard so I don't see how it would affect pasting.

**Comment by Yekutiel** [comment]
> I noticed, but there are no Ctrl+V global shortcuts so I don't see any issue here.

After I read that sentence I realized I can bind `Ctrl+V` to a Python script which will act as a global shortcut in the following manner...

1. I will press `Ctrl+V`
2. My Python script will then open CopyQ, and then
3. Copy item 0 (the first item) in CopyQ, and then
4. Paste that item

Sure, I suppose it's a little kludgy yet it seems like it will actually be an elegant solution.

Thanks for your help! Please feel free to close this issue.

**Comment by hluk** [comment]
You can override the Ctrl+V with CopyQ with following command ([here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)):

```ini
[Command]
Command="
    copyq:
    var text = read(0)
    copy(text)
    copySelection(text)
    paste()"
GlobalShortcut=ctrl+v
Icon=\xf0ea
IsGlobalShortcut=true
Name=Paste the First Item
```

If you want to paste other formats than plain text, replace the script in the command with:

```js
copyq:
var item = read(mimeItems, 0)
copy(mimeItems, item)
copySelection(mimeItems, item)
paste()
```
