### ISSUE TITLE
Running on M1 Mac OSX Big Sur, no command line option

### ISSUE THREAD

**Issue by cjohnsonuk** [hluk/CopyQ#1542]
**Describe the bug**
When trying to run 

`copyq config tray_menu_open_on_left_click true`

on my M1 Mac Mini with Big sur I get 

`zsh: command not found: copyq`

It works on my old mac mini with Catalina.  Using the same command

From using `locate`on the old intel Mac it appears that it may have been installed with brew but IIRC there is not yet a M1 version of Homebrew

**To Reproduce**
1. install app from .dmg downloaded from github
2. drag app to applications folder
3. run app and confirm its working fine
4. open terminal
5. run `copyq config tray_menu_open_on_left_click true`
6. see error `zsh: command not found: copyq`

**Expected behavior**
expected to be able to run copyq command line

**Screenshots**

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Application Version  3.13
 - OS Mac OSX
 - Big Sur / zsh

**Comment by hluk** [comment]
Looks like `copyq` is not in `PATH`. Please add the directory containing the executable to `PATH` environment variable or use full path (or an alias in `zsh`).

I don't know if there is a better way to handle this in the `dmg` file, or if perhaps installing via `brew` handles this.

Please let me know if you find a suitable solution.

**Comment by cjohnsonuk** [comment]
I checked the path.  
On the Intel mac copyq is installed in /usr/local/bin
On the M1 mac this directory doesn't exist and I've run locate to try and find the binary for the command line but I can only find the desktop app.  I've opened the .dmg package and the only executable I can find is the desktop app: CopyQ, no copyq for the command line.  I'm pretty sure from other files on my Intel mac that CopyQ was installed through Homebrew.  Homebrew on Github says that compatibility with M1 Apple silicon is not expected for a few months

**Comment by hluk** [comment]
You can find the executable path from CopyQ:

1. Open the main window.
2. Open the Action dialog (<kbd>F5</kbd> key).
3. Enter command: `copyq info exe | copyq copy -`
4. Press OK and **the path will be copied to the clipboard**.

**Comment by cjohnsonuk** [comment]
@hluk Lucas, thats great, thank you!  I think I've got so used to seeing case sensitive commands that when I saw it was capitalised (ie CopyQ instead of copyq ) I'd incorrectly assumed that this was just the desktop app and that it wouldn't accept the scripting arguments.  I thought I had tried it but obviously not as this works great!  Thank you! :-)
