### ISSUE TITLE
Show notifications on display/monitor with focused window

### ISSUE THREAD

**Issue by gsingh93** [hluk/CopyQ#1554]
**Describe the bug**

I'm using the `notification()` function to display a notification (the full code is exactly what's shown here: https://github.com/hluk/CopyQ/issues/729#issuecomment-324406061. I have my laptop (Macbook Pro) connected to an external monitor, and when I press the hotkey to trigger the command, the notification shows up in the bottom right corner of my laptop, regardless of where the focused window I'm pasting in is. I'd expect that the notification be shown on the display where the focused window is (this is the behavior of Flycut).

**To Reproduce**

1. Connect a laptop with a second monitor
1. Create a new command using the code here: https://copyq.readthedocs.io/en/latest/known-issues.html
2. Open a text editor, move the window to the second monitor, and keep this window selected
2. Press Ctrl+Shift+V. You'll see the notification in the bottom right of the laptop display.

**Expected behavior**
The notification should show up on the display that contains the focused window. If there are use cases where you may not want this, it should be configurable.

**Version, OS and Environment**
CopyQ Clipboard Manager v3.13.0
Qt: 5.13.2
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: macOS 10.15

**Comment by hluk** [comment]
CopyQ 4.0.0 now uses system notifications instead of its own implementation.
