### ISSUE TITLE
Maintain order of clips when syncing between computers

### ISSUE THREAD

**Issue by richlux** [hluk/CopyQ#1558]
**Is your feature request related to a problem? Please describe.**
When syncing CopyQ between computers using a shared drive, often the order of the clips in the list don't match.  Sometimes when I do a copy on one machine (so it's the top clip), on the other machine, the clip is in a random position in the list.  This seems to happen more often the more clips I have in CopyQ.

**Describe the solution you'd like**
It would be nice if the order of the clips was the same on all computers being synced.

**Describe alternatives you've considered**
Sometimes I can search for the clip on the second computer, but this only works if I remember some of the text in the copied clip.

Thanks,
Rich

**Comment by hluk** [comment]
For me everything works quite well until a tab size limit is reached and there are sometimes more files then items. Then items are not added until you remove some - but in that case some old items are suddenly added to top.

I really should think about making the order more stable. But I'm not sure if I should go as far as keeping order of items same in all instances. This would probably require some kind of special index file.

This is how it works now:

- If you set up a synced tab in CopyQ for the first time, the files are loaded in alphabetical order and the list of loaded items is stored in tab data file.
- If you load an already synced tab, CopyQ first loads all files stored in the tab data file and then loads any other files (in alphabetical order).
- The item list is updated when needed and new files (read in alphabetical order) are added to the top of the item list if there is space.
- If a new item is created in CopyQ and it's not yet stored in a file, it will be assigned first available file with base name `copyq_0000`, `copyq_0001` etc.

**Comment by richlux** [comment]
Thanks for the reply.  The issue might be the size limit.  The tab is always at its size limit because I just let things roll off the bottom as new items are copied and added to the top.  Are you saying that when this happens, the synced computers don't do the same thing?  If they did, would that solve the problem?  Having to keep track of the size limit and clear entries every time the limit is reached to make sure syncing continues to work isn't really feasible.

I can't think of any reason why a user would not want to keep the order the same in all instances.  (Isn't that what syncing means? :smile:).  It would make the syncing feature much more useful, so I hope you consider this enhancement.

Thanks,
Rich

**Comment by hluk** [comment]
> Are you saying that when this happens, the synced computers don't do the same thing? If they did, would that solve the problem?

Synchronized tabs do the same things but at different times and with potentially different configuration (tab size, handled file types). Also, adding an item to a tab other than the top or moving items won't be reflected in other synced tabs.

> I can't think of any reason why a user would not want to keep the order the same in all instances. (Isn't that what syncing means? smile).

The initial goal was only to synchronize item content to disk and try to show new files at the top when there is space so as the new clipboard content can be easily shared.

Maybe it would help if CopyQ always reads own files (`copyq_*`) first from the newest one and drop any other/older items that would not fit the tab. This way there would be no need to keep additional index file.

**Comment by richlux** [comment]
> Maybe it would help if CopyQ always reads own files (copyq_*) first from the newest one and drop any other/older items that would not fit the tab. This way there would be no need to keep additional index file.

That sounds like a good idea.  Is this something you can do?

Rich

**Comment by hluk** [comment]
> > Maybe it would help if CopyQ always reads own files (copyq_*) first from the newest one and drop any other/older items that would not fit the tab. This way there would be no need to keep additional index file.
> 
> That sounds like a good idea. Is this something you can do?

Already working on it. ;-)

If possible, please test the development build:
- [Windows](https://ci.appveyor.com/project/hluk/copyq/builds/37418003/artifacts)
- [macOS](https://github.com/hluk/CopyQ/actions/runs/507243768#artifacts)

**Comment by richlux** [comment]
Thanks.  I'm running the development build now.  When it first loaded, the clips were not in the same order on each computer, but it was adding new clips to the top and dropping off the old ones.  I wanted to test how the order will be, so I cleared out my clipboard and started fresh.  I'm not at the limit yet (100), but so far things are staying in order.  I'll let you know as I use it more.

Thanks,
Rich

**Comment by richlux** [comment]
I've done a little more testing and the order is better, but it can still get out of sync in the following situation:  I have CopyQ set to "move item to the top" when I activate it (double click). If I do this on one computer, the item doesn't move in the list on the other computer causing the list order to get out of sync.  The more I do this, the more the list order gets worse.

Rich

**Comment by hluk** [comment]
Keeping order the same in both synced instances was not the goal with the recent changes. It might be possible to make it work for the special case when you move an own item (`copyq_*` file) to the top, but probably difficult otherwise without an index file.

**Comment by hluk** [comment]
I'm adding some fixes so that item positions are also synchronized (in synced tabs) for most common cases (like moving item to the top).

**Comment by richlux** [comment]
That's great! Thanks for continuing to work on this.

Rich
