### ISSUE TITLE
Copyq doesn't apply dark theme in pop_os 20.10

### ISSUE THREAD

**Issue by Racle** [hluk/CopyQ#1559]
Before creating a new issue, see list of [known
issues](https://copyq.readthedocs.io/en/latest/known-issues.html).

**Describe the bug**

**To Reproduce**
1. Open Preferences
2. Change to "dark" in Appereance page
3. Preview is in dark theme, copyq main ui and "menu()" stays in light theme.

**Expected behavior**
Copyq main UI and "menu()" should be black.
This was working before I upgraded to from pop_os 20.04 => 20.10 (should be pretty much same as ubuntu 20.10)

**Screenshot**
"menu()" 
![image](https://user-images.githubusercontent.com/759091/103982645-8abf5b80-518c-11eb-92b6-0b4c072e12d2.png)

**Version, OS and Environment**
CopyQ Clipboard Manager v3.13.0
Qt: 5.14.2
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Pop!_OS 20.10 (Gnome3)
Theme: pop-dark for main and shell theme

**Additional information**
Tried also install qt5ct. Changed dark theme from that and it also did nothing.

**Comment by hluk** [comment]
Looks like it was broken in https://github.com/hluk/CopyQ/commit/2ea08bc5 commit. Fixing.

---

BTW, if desktop environment doesn't do this, you have to tell Qt framework to use specific theme or engine.

For `qt5ct`, set `QT_QPA_PLATFORMTHEME` environment variable (you may need to select theme with `qt5ct` utility):

```
env QT_QPA_PLATFORMTHEME=qt5ct copyq
```

Similar with Kvantum rendering engine:

```
env QT_STYLE_OVERRIDE=kvantum copyq
```
