### ISSUE TITLE
Tray icon of Copyq is missing on Ubuntu 20.04  

### ISSUE THREAD

**Issue by FANN1980** [hluk/CopyQ#1560]
Hi! 
CopyQ is installed on my machine and works perfectly as well as the tray icon. 

However when I enable the "autostart" option, after a rebooting the program initiates normally but without the tray icon. To enable the tray I have to kill the CopyQ process and restart the program manually, everything works fine again up to the next reboot.   

CopyQ Clipboard Manager v3.13.0
Qt: 5.12.8
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Ubuntu 20.04.1 LTS

I will be thankful if someone can help me!

**Comment by raubel** [comment]
See [issue 126](https://github.com/hluk/CopyQ/issues/1526).
