### ISSUE TITLE
How to ignore too short copies such as a character?

### ISSUE THREAD

**Issue by c02y** [hluk/CopyQ#1561]
**Is your feature request related to a problem? Please describe.**
I noticed that there are a lot of copies in my copyq list only contain one character, it might be caused by my vim, so is it able to ignore those copies containing only one character or limited length characters(set in the Preference), I remembered that some clipboard manager can do that.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hluk** [comment]
There is predefined command "Ignore items with no or single character" for this purpose (you can add it from Command dialog - F6 key).

**Comment by c02y** [comment]
If I understand it correctly, command is a command, you need to trigger it, right?

What I mean, is a setting.

**Comment by hluk** [comment]
> I tried it, it is not working, I have to know how copyq is designed and its deep API?
> 
> If I understand it correctly, command is a command, you need to trigger it, right?

The command is triggered automatically when clipboard content changes before new item is created (and it would block creating the item when the text contains just a single character).

**Comment by c02y** [comment]
OK, it is working now. Thanks.
