### ISSUE TITLE
CopyQ does not see consecutive clipboard changes from VirtualboxVMs 

### ISSUE THREAD

**Issue by cmprmsd** [hluk/CopyQ#1565]
**Describe the bug**
When I copy text from a virtual machine in VirtualBox where the clipboard is shared CopyQ will update with the correct text only once. Consecutive copying within the vm will not update the clipboard history.
I see this working for gpaste and other alternatives, but CopyQ has the best image preview and great handling.

**To Reproduce**
1. Go into a virtual machine, open any editor
2. write some lines of gargabe
3. Open CopyQ on the host
4. Copy some text within the VM (CopyQ will show the new value)
5. Copy some other text within the VM (CopyQ will not track the new value)
6. You can paste the text on the host, as the clipboard itself did update

**Expected behavior**
Each consecutive copy should update the clipboard.

**Screenshots**
![](https://user-images.githubusercontent.com/73472903/105040594-4ec8a800-5a62-11eb-85cc-ee1bbed31b8f.gif)

![](https://user-images.githubusercontent.com/73472903/105041440-4b81ec00-5a63-11eb-8a24-371fe663546e.gif)

**Version, OS and Environment**
CopyQ Clipboard Manager v3.13.0
Qt: 5.15.1
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Arch Linux, i3wm

VirtualMachine: Arch Linux, i3wm

**Comment by hluk** [comment]
In recent versions, CopyQ started relying on TIMESTAMP in X11 clipboard. Can you check if it changes when copying stuff from VirtualBox? It should be possible to check from console with something like: `copyq clipboard; copyq clipboard TIMESTAMP | xxd`

**Comment by cmprmsd** [comment]
And we have a winner! (it seems)
Sorry for taking several days to get back to you.

When I copy from the VM it seems the timestamp is non existent:
`abc00000000: 0000 0000`

vs
`00000000: 5cc0 0400`
for stuff that is copied on the host.

**Comment by stevium** [comment]
I have the same issue. @cmprmsd did you manage to find any workaround? I mainly use Windows on VirtualBox on Ubuntu for my full time work, and only this thing is preventing me from unlocking full potential of this amazing tool.

**Comment by cmprmsd** [comment]
I did not find a workaround but switched to Wayland and VMware Workstation. That's quite a serious workaround and CopyQ currently can only see the clipboard change, when I move the cursor through the host xwayland application of  vmware workstation. 

I think that's an issue of workstation though, as it would not update the host clipboard when I flick to a Wayland window to fast after copying content in a virtual machine.

But for your problem, I guess downgrading or asking @hluk to fix it might be a better idea than my "workaround" :D

**Comment by hluk** [comment]
I'm adding a fix to ignore timestamp with incorrect format or if it's `0`.

**Comment by stevium** [comment]
I've just built it from source, and can confirm on Windows 10 Vbox on Ubuntu clipboard now updates as expected, every time a different text or image is copied. Thank you very much for a quick fix!

**Comment by cmprmsd** [comment]
Thank you so much! :) 
I'll close this issue :+1:
