### ISSUE TITLE
chording keyboard

### ISSUE THREAD

**Issue by netpipe** [hluk/CopyQ#1568]
would be neat to be able to use the numberpad for a chording keyboard somehow. (they sell pocket versions with just the numberpad and usb cable) with raspberrypi zero and eink 1/2 watt computer is very close for wearable computing

**Comment by hluk** [comment]
I have no idea how this works or how to test this. CopyQ is user space app and it doesn't handle HW, only input events (with help of Qt framework).

This seems more like [a feature request for Qt](https://bugreports.qt.io/issues/?jql=text%20~%20%22chorded%22).
