### ISSUE TITLE
Search multiple words in any order

### ISSUE THREAD

**Issue by guettli** [hluk/CopyQ#1569]
**Is your feature request related to a problem? Please describe.**

If I search for "foo bar", I don't get snippets which contain "bar foo".

**Describe the solution you'd like**

If I search for "foo bar" I would like to see all snippets which contain "foo AND bar.".

I think a space character in the search should be used to split words. 

**Describe alternatives you've considered**

I use CopyQ to remember git branch names, since I often need to switch.

A better search would help me to find the matching line faster.

**Comment by hluk** [comment]
This is good idea, I remember needing this few times.

I will make this behaviour default, disabling the regular expression search.

Any chance regular expression (or wildcard) matching can be needed in combination with this or maybe something like "match two words separated by space"? I'm probably going to figure this out when I need it. :)
