### ISSUE TITLE
Partial poor quality appearance on 4K monitors

### ISSUE THREAD

**Issue by drwinchell** [hluk/CopyQ#1572]
I recently started using 4K monitors on my Windows 10 desktop.  The left part of windows such as clipboard history and tabs and the configuration window are crisp and clear. The right side of those windows is very grainy.

<img width="680" alt="2021-02-02 16_37_42-Configuration - CopyQ" src="https://user-images.githubusercontent.com/66954912/106667034-616cd200-6576-11eb-8fe4-370b4861277d.png">

Screenshot attached.
Version v3.13.0

**Comment by fade2gray** [comment]
Must be your monitor - looks fine to me.

**Comment by hluk** [comment]
Can you change the font?

**Comment by drwinchell** [comment]
Thanks for the suggestion Lukáš. It took a little while to find where to change the font but eventually I figured it out. I changed it from MS Shell Dig 2 to Calibri and it looks much, much better now.

**Comment by hluk** [comment]
Not sure why the default font changed - looks like it could be a Qt bug.
