### ISSUE TITLE
python command: Argument list too long

### ISSUE THREAD

**Issue by maricn** [hluk/CopyQ#1573]
I'm trying to write a command that would paste an image as base64 data (for use in embedding images to HTML/markdown/etc). So far I got to something like this:

```python
python:
import base64
import subprocess, os

exe = os.environ['COPYQ']
def copyq(*args):
  return subprocess.Popen([exe] + list(args), stdout=subprocess.PIPE).communicate()[0]

item = copyq('read', 'image/png')

encoded_item = 'data:image/png;base64,' + str(base64.b64encode(item))

copyq('write', '0', 'text/plain', encoded_item)
```

However, since the images are generally very big, invoking processes with large arguments throws `Argument list too long` (in `copyq('write',...)` step).

Any ideas to how to deal with that limitation? I hope there's a simpler way than to process it in batches...

**Comment by hluk** [comment]
There is a limit on command argument list (+ environment variables) size in Linux. You should always pass a larger data on standard input or using a temporary file.

Similar command I've been using (using CopyQ scripting instread of Python):

```ini
[Command]
Command="
    copyq:
    var html = ''
    var items = selectedItemsData()

    for (var i in items) {
      var item = items[i]
      html += '<p>'
      if (mimeHtml in item) {
        html += htmlPart[mimeHtml]
      } else if (mimeText in item) {
        html += item[mimeText]
      } else if ('image/png' in item) {
        html += '<img src=\"data:image/png;base64,' + toBase64(item['image/png']) + '\" />'
      }
      html += '</p>'
    }

    copy(mimeHtml, html)"
Icon=\xf0ea
InMenu=true
Name=Copy as HTML
```

([Here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them).)

**Comment by maricn** [comment]
Thank you @hluk. For the reference, I simplified your command into my use case:
```ini
[Command]
Command="
    copyq:
    var html = ''
    var items = selectedItemsData()
    
    for (var i in items) {
      var item = items[i]
      html += '<img src=\"data:image/png;base64,' + toBase64(item['image/png']) + '\" />'
    }
    
    write(0, mimeText, html)"
Icon=\xf0ea
InMenu=true
Input=image/png
Name=Image to HTML (data:base64)
Output=text/plain
OutputTab=&clipboard
Tab=&clipboard
```
