### ISSUE TITLE
"Paste and copy previous/next" actions do instead "Copy previous/next and paste"

### ISSUE THREAD

**Issue by sitaktif** [hluk/CopyQ#1577]
**Describe the bug**

When using the "Paste and copy next" shortcut, what actually happens is that "Copy next" happens first and _then_ the contents are pasted.

**To Reproduce**

1. Assign a shortcut to "Paste and copy next"
2. Copy the string "one" then "two" then "three". The clipboard will contain "three" "two" "one" in that order (as expected).
3. Hit the "Paste and copy next" shortcut.
3. Hit the "Paste and copy next" shortcut again.
4. Notice that the pasted text is "twoone".

**Expected behavior**

The screen should show "threetwo":
- first action should "Paste (three) and copy next (two)"
- second action should "Paste (two) and copy next (one)"

**Note about use case**

This is the behaviour I would expect  from that command, and that is the one that I believe makes most sense for common use cases: the idea is to copy a list of strings (in the reverse order) and then to repeatedly hit "Paste and copy next" to paste each item quickly but moving around between each time.

For example, say you have the following text:

```
Jack
Keanu
Glenn
Meryl

Nicholson
Reeves
Close
Stripp
```

The idea is that one can quickly cut "Stripp" "Close" "Reeves" and "Nicholson" then "paste and select next" them 4 times to end up with the final text:

```
Jack Nicholson
Keanu Reeves
Glenn Close
Meryl Stripp
```

**Screenshots**

**Version, OS and Environment**

Version: v3.13.0
OS: MacOS Big Sur (11.1)

**Additional context**

I think this issue has been around since the introduction of the "Paste and copy next/previous" feature.

**Comment by sitaktif** [comment]
The `Paste and copy next` command is mapped to `copyq: paste(); next()`. If I change this to `copyq: paste(); sleep(250); next()` then it works as expected (as long as one waits long enough between actions).

So it seems that it is a race condition whereby the `paste()` command takes too long to actually trigger, but in the meantime the `next()` function gets applied, so the text that ends up being pasted is the following one on the line.

The `sleep()` workaround is not that great though as it prevents from quickly using the command multiple times in succession (if you do, everything gets mixed up because the actions start overlapping with each other).

Also, the amount of sleep one needs might vary from one computer/OS to another. For example, sleeping for 100ms seemed to work only some of the time for me.

**Comment by hluk** [comment]
There is some implicit `sleep` on Windows and Linux platforms set to 150ms, but none for macOS. Maybe I can change this to be 250ms by default on all platform and let advanced user configure the value.

**Comment by sitaktif** [comment]
Lovely, thanks!
