### ISSUE TITLE
How does copyq eliminate line breaks in copied text when copying PDF documents?

### ISSUE THREAD

**Issue by ovmonk** [hluk/CopyQ#1580]
As mentioned in the title, I am a medical researcher and I need to read and organize many papers every day. Most of these papers are presented in PDF format. But when I copy the content in the pdf, I found that the copied text has **line breaks**, so when I paste it into Word or other text editors, the format will become a mess. I remember that the clipboard manager "Ditto" has the function of deleting line breaks when pasting, but I haven't found it after looking for it in CopyQ for a long time. Does this function need to be realized with commands? Because I use the linuxmint system and I like CopyQ **very much**, I did not consider using Ditto back. :-)
PS: My current solution is to edit the text on the clipboard with a local text editor, and then use the replace function to replace all "\s" with spaces (I used regular expressions).
Sorry for my English.

**Comment by hluk** [comment]
That can be done automatically (replace when copied from a window), with a global shortcut to paste the fixed text or by selecting the text/item in CopyQ and pressing a shortcut:

```ini
[Command]
Command="
    copyq:
    focusPrevious()
    var text = str(input())
    text = text.replace(/\\s+/g, ' ')
    copy(text)
    paste()"
Icon=\xf039
InMenu=true
Input=text/plain
Name=Paste Normalized Text
Shortcut=shift+return
```

**Comment by ovmonk** [comment]
> That can be done automatically (replace when copied from a window), with a global shortcut to paste the fixed text or by selecting the text/item in CopyQ and pressing a shortcut:
> 
> ```ini
> [Command]
> Command="
>     copyq:
>     focusPrevious()
>     var text = str(input())
>     text = text.replace(/\\s+/g, ' ')
>     copy(text)
>     paste()"
> Icon=\xf039
> InMenu=true
> Input=text/plain
> Name=Paste Normalized Text
> Shortcut=shift+return
> ```

Thanks for your answer! But I tried many operations, I couldn't use this command. How should I use your command in CopyQ?

**Comment by hluk** [comment]
> But I tried many operations, I couldn't use this command. How should I use your command in CopyQ?

[Here is how to add the command to CopyQ.](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)

After installing the command, when you select an item from the main window, you should be able to use the shortcut (Shift+Enter) to copy and paste the fixed text.

**Comment by ovmonk** [comment]
> > But I tried many operations, I couldn't use this command. How should I use your command in CopyQ?
> 
> [Here is how to add the command to CopyQ.](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)
> 
> After installing the command, when you select an item from the main window, you should be able to use the shortcut (Shift+Enter) to copy and paste the fixed text.

Thanks again for your help! But I've run into this problem:
```
ReferenceError:Can't find variable:focusPrevious
```

**Comment by hluk** [comment]
> Thanks again for your help! But I've run into this problem:
> 
> ```
> ReferenceError:Can't find variable:focusPrevious
> ```

You have to update CopyQ to the latest version or perhaps replace `focusPrevious()` with `hide()`.

**Comment by ovmonk** [comment]
> > Thanks again for your help! But I've run into this problem:
> > ```
> > ReferenceError:Can't find variable:focusPrevious
> > ```
> 
> You have to update CopyQ to the latest version or perhaps replace `focusPrevious()` with `hide()`.

Thank you very much for your help! The problem is solved!
