### ISSUE TITLE
New release with proper version information on macOS

### ISSUE THREAD

**Issue by vitorgalvao** [hluk/CopyQ#1584]
**Is your feature request related to a problem? Please describe.**
As https://github.com/hluk/CopyQ/issues/1552 noted, the macOS version was missing proper version information. This has been resolved by https://github.com/hluk/CopyQ/commit/270b48633a4d8de641907a2053099eeb9fb246a1, but no release with that fix is out yet.

Without proper version information in the app, checking for updates from third-party solutions becomes impractical.

**Describe the solution you'd like**
[A new release](https://github.com/hluk/CopyQ/releases) for macOS, with proper version information in `Info.plist`.

**Describe alternatives you've considered**
None

**Additional context**
N/A

**Comment by hluk** [comment]
Yeah, I don't know when I'll be able to make new release.

In the meantime, you can grab a [development build](https://github.com/hluk/CopyQ/actions/runs/552717285#artifacts).
