### ISSUE TITLE
Thumbnail previews for Vivaldi html images

### ISSUE THREAD

**Issue by echometerain** [hluk/CopyQ#1591]
**Describe the bug**
In Vivaldi (and chromium I believe), the "copy image" function does not copy the actual image but an instead copies an html file embedding the image.

For example, the image `https://cdn.pixabay.com/photo/2018/03/19/15/04/wet-3240211_1280.jpg` will copy as `<meta http-equiv="content-type" content="text/html; charset=utf-8"><img src="https://cdn.pixabay.com/photo/2018/03/19/15/04/wet-3240211_1280.jpg"/>` instead, which most applications (including github) accepts. But for these "images", copyq doesn't generate thumbnail previews

**To Reproduce**
1. Copy an image on Vivaldi

**Expected behavior**
copyq could either download the image component of the html file and store it, or copyq could continue its current behaviour but with generating and storing thumbnail previews.

**Screenshots**
![image](https://user-images.githubusercontent.com/70437021/108266477-2226af80-7138-11eb-959e-1f7d4db12fd4.png)
![image](https://user-images.githubusercontent.com/70437021/108266489-25ba3680-7138-11eb-9418-a258bbd5c716.png)

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Copyq v3.13.0
 - Manjaro GNU/Linux 
 - KDE Plasma with kwin

**Comment by hluk** [comment]
This is not a bug. CopyQ won't fetch any remote content unless you specify such action with a custom command. So if the web browser does not provide an image format, you won't see the image in CopyQ.

I'm against adding such feature due to security and performance concerns, and TBH I don't need such behavior because most of I use copy images to clipboard properly.

**Comment by SMSourov** [comment]
@hluk Ok! 

> This is not a bug. CopyQ won't fetch any remote content unless you specify such action with a custom command. So if the web browser does not provide an image format, you won't see the image in CopyQ.
> 
> I'm against adding such feature due to security and performance concerns, and TBH I don't need such behavior because most of I use copy images to clipboard properly.

By this comment, I'm guessing that you won't add this feature. Can you show an example to set a custom command? I do need this feature.

**Comment by hluk** [comment]
> By this comment, I'm guessing that you won't add this feature. Can you show an example to set a custom command? I do need this feature. No matter which browser I use, It shows only the metadata.

Check what formats the clipboard provides after copying an image (with Ctrl+Shift+C in the main window in CopyQ) and then create a new automated command in CopyQ to download image data. Example (untested):

```js
copyq:
// Change the input format (from clipboard)
var imageUrl = str(data('text/plain'))
if (!imageUrl.startsWith('https://') || !imageUrl.includes('.png'))
    abort()

var reply = networkGet(imageUrl)
var imageData = str(reply.data)
if (reply.status != 200) {
    throw 'Failed to fetch image data.'
        + '\nStatus code: ' + reply.status
        + '\nError: ' + reply.error
}

// Change the output format
copy('image/png', imageData)
```

BTW, Firefox provides copied images properly in the clipboard.

**Comment by NA0341** [comment]
@hluk said:

> This is not a bug. CopyQ won't fetch any remote content unless you specify such action with a custom command. So if the web browser does not provide an image format, you won't see the image in CopyQ.

> BTW, Firefox provides copied images properly in the clipboard.

I totally agree that CopyQ shouldn't automatically fetch stuff from the web by default.

But the issue is not the WebBrowser!
I've [added info](https://github.com/hluk/CopyQ/issues/2084#issuecomment-1618911741) to this issue #2084 which shows that Vivaldi (in this case) provides the image data necessary to store the image - but CopyQ does not store it!

**Comment by rod-stuchi** [comment]
I've changed a little what @hluk did above, and its working for me


```toml
[Command]
Automatic=true
Command="
    copyq:
    var imageUrl = str(data('text/plain'))
    serverLog(\"info:: url: \" + imageUrl)

    if (!imageUrl.startsWith('https://')) {
        abort()
    }

    var reply = networkGet(imageUrl)
    if (reply.status != 200) {
        throw 'Failed to fetch image data.'
            + '\\nStatus code: ' + reply.status
            + '\\nError: ' + reply.error
    }

    serverLog(\"info:: status: \" + reply.status)
    setData('image/png', reply.data)"
Icon=\xf15b
Name=Fetch Image

```

**Comment by Bobs-unique-username** [comment]
> I've changed a little what [@hluk](https://github.com/hluk) did above, and its working for me
> 
> [Command]
> Automatic=true
> Command="
>     copyq:
>     var imageUrl = str(data('text/plain'))
>     serverLog(\"info:: url: \" + imageUrl)
> 
>     if (!imageUrl.startsWith('https://')) {
>         abort()
>     }
> 
>     var reply = networkGet(imageUrl)
>     if (reply.status != 200) {
>         throw 'Failed to fetch image data.'
>             + '\\nStatus code: ' + reply.status
>             + '\\nError: ' + reply.error
>     }
> 
>     serverLog(\"info:: status: \" + reply.status)
>     setData('image/png', reply.data)"
> Icon=\xf15b
> Name=Fetch Image

Thanks, Rod.  That's the only command I've found so far that will retrieve images properly in Facebook.
