### ISSUE TITLE
Slugify function (change "это ссылка" to "eto-ssylka")

### ISSUE THREAD

**Issue by d2boy** [hluk/CopyQ#1592]
I'd like to suggest adding an action for a converter for non-latin alphabet.

For example (я → ya, ю → yu, б → b). It would save a lot of time when renaming file names.

Also change spaces to underscore (_)

**Comment by hluk** [comment]
This is out of scope for the application itself, but it should be possible to use the commands/scripting for this.

For inspiration, see command templates: https://github.com/hluk/copyq-commands/tree/master/Templates
