### ISSUE TITLE
copyq/.copyq_s: Can't transfer non file/directory

### ISSUE THREAD

**Issue by orschiro** [hluk/CopyQ#1594]
Hi guys!

Quick question: 

I am using rclone for a backup of my home folder and this message came up.

What kind of file is `.copyq_s` and what is it used for?

Thank you!

**Comment by hluk** [comment]
It is a unix socket file for communication with server part of the application and to ensure that only single instance of the app is using the configuration/data directory.

It is also not recommended to backup the directory while CopyQ is using it.

**Comment by orschiro** [comment]
All I needed to know, thanks Lukas!
