### ISSUE TITLE
OSX command to install CopyQ

### ISSUE THREAD

**Issue by ravi-bytes** [hluk/CopyQ#1597]
Hi - your document says to install CopyQ on OSX using homebrew as
`brew cask install copyq`

This resulted in errors for me and I used the below command to get things to work:
`brew install --cask copyq`

I'm on macOS Catalina V10.15.7

**Comment by hluk** [comment]
Can you please point me to the documentation with `brew cask install copyq`?

Both [Installation documentation](https://copyq.readthedocs.io/en/latest/installation.html) and [README.md](https://github.com/hluk/CopyQ/blob/master/README.md) says `brew install --cask copyq`.

**Comment by ravi-bytes** [comment]
https://hluk.github.io/CopyQ/

[cid:8d4f0870-c7c0-4eb1-aa40-a03c0f253beb]

The troubles when you have a copy of the same information in multiple places 🙂

- Ravi


________________________________

**Comment by hluk** [comment]
Ah, yeah, that's generated from the README.md file, but it still needs to be done manually.

Updated. Thanks for the heads up.

**Comment by ravi-bytes** [comment]
Thanks for the great product.

- Ravi


________________________________
