### ISSUE TITLE
Using CopyQ as a stopwatch 

### ISSUE THREAD

**Issue by CleverClogs** [hluk/CopyQ#1602]
**Introduction**
The paste time and date feature in CopyQ is very useful. I know how to adjust the datestring format to get just the current time, but would it also be possible to use CopyQ as a stopwatch?

**How this would work**
So, instead of pasting, say: 11:43:27pm on pressing the associated global keyboard shortcut, we'd get something like 0:00:13, if the stopwatch was started 13 seconds ago. The next time we press the same global keyboard shortcut, of course the timer would have gone up. 

**Required options**
We'd need a command to start/reset the stopwatch, one to pause/stop it, and of course one to paste the current time on the stopwatch. 

Would this be feasible in CopyQ? Thank you so much for reading and considering.

**Comment by hluk** [comment]
To get seconds you can use following command. To improve the elapsed time format you will need to use [some more code](https://stackoverflow.com/questions/1210701/compute-elapsed-time).

```ini
[Command]
Command="
    copyq:
    var now = Date.now();
    var optionName = 'stopwatchLastTime';

    var lastTime = Number(settings(optionName));
    if (lastTime) {
        var seconds = (now - lastTime) / 1000
        popup('Elapsed time', seconds + ' seconds')
        copy(seconds)
    }

    settings(optionName, now)"
GlobalShortcut=meta+return
Icon=\xf2f2
IsGlobalShortcut=true
Name=Stopwatch
```

**Comment by CleverClogs** [comment]
Thank you for responding so quickly, like you always do, Lukas. CopyQ has been the #1 tool I install on all machines I work with and it's such an incredible time saver for me. 

I'm glad to read that a stopwatch command should be possible in CopyQ. It seems I'll need to start to learn how to use the QT programming language and integrate it in CopyQ to fine-tune the string formatting into the desired hh:mm:ss layout.
Thank you again.

**Comment by hluk** [comment]
> It seems I'll need to start to learn how to use the QT programming language and integrate it in CopyQ to fine-tune the string formatting into the desired hh:mm:ss layout.

It's not Qt, but their scripting language basically same as Javascript. So you could use some of the code from the stackowerflow link I posted ([this answer might help](https://stackoverflow.com/a/1210726/454171)).

**Comment by hluk** [comment]
Here is the updated command using the HH:MM:SS format:

```ini
[Command]
Command="
    copyq:
    var now = Date.now();
    var optionName = 'stopwatchLastTime';

    function padWithZero(n) {
        if (n < 10)
            return '0' + n;
        return n;
    }

    function millisecondsToTimeString(milliseconds) {
        var seconds = Math.floor(milliseconds / 1000);
        var s = seconds % 60;
        var minutes = Math.floor(seconds / 60);
        var m = minutes % 60;
        var hours = Math.floor(minutes / 60);
        return padWithZero(hours) + ':' + padWithZero(m) + ':' + padWithZero(s);
    }

    var lastTime = Number(settings(optionName));
    if (lastTime) {
        var time = millisecondsToTimeString(now - lastTime);
        popup('Elapsed time', time);
        copy(time);
    }

    settings(optionName, now);"
GlobalShortcut=meta+return
Icon=\xf2f2
IsGlobalShortcut=true
Name=Stopwatch
```

**Comment by CleverClogs** [comment]
Yay! This is such phenomenal help. Thank you, Lukas.
I was able to slightly change your script so that it only saves the settings the first time the script runs. This allows me to keep the stopwatch running while intermittently pasting the current stopwatch counter value to my page. 

 `[Command]
Name=Stopwatch
Command="
    copyq:
    
    var now = Date.now();
    var optionName = 'stopwatchLastTime';
    
    function padWithZero(n) {
        if (n < 10)
            return '0' + n;
        return n;
    }
    
    function millisecondsToTimeString(milliseconds) {
        var seconds = Math.floor(milliseconds / 1000);
        var s = seconds % 60;
        var minutes = Math.floor(seconds / 60);
        var m = minutes % 60;
        var hours = Math.floor(minutes / 60);
        return hours + ':' + padWithZero(m) + ':' + padWithZero(s) + ' ';
    }
    
    var lastTime = Number(settings(optionName));
    if (lastTime) {
        var time = millisecondsToTimeString(now - lastTime);
    // popup('Elapsed time', time);
        copy(time);
        paste(time)
    }
    else 
    settings(optionName, now);"
IsGlobalShortcut=true
Icon=\xf2f2
GlobalShortcut=alt+shift+t`

In addition, I added another command that resets the stopwatch: 
`[Command]
Name=Reset stopwatch
Command="
    copyq:
    var now = Date.now();
    var optionName = 'stopwatchLastTime';
    settings(optionName, now)
    popup('Stopwatch reset to 0:00:00');"
IsGlobalShortcut=true
Icon=\xf2f2
GlobalShortcut=alt+shift+y`

**Comment by CleverClogs** [comment]
Sorry for messing the code up, not sure what happened with the formatting.

**Comment by hluk** [comment]
> Sorry for messing the code up, not sure what happened with the formatting.

Np, I've fixed that. :)

BTW, for these commands it's better to enclose them in triple backticks and add a syntax specifier for `ini` format:

    ```ini
    [Command]
    ...
    ```

I've added the command to the copyq-commands repo: https://github.com/hluk/copyq-commands/tree/master/Global#stopwatch
