### ISSUE TITLE
How to send network Post request in copyq

### ISSUE THREAD

**Issue by pikaboo** [hluk/CopyQ#1603]
Before creating a new issue, see list of [known
issues](https://copyq.readthedocs.io/en/latest/known-issues.html).

**Describe the bug**
I want to send a networkPost after something is copied

**To Reproduce**
Here is my script
copyq:
   var text = str(clipboard());
   var content = '{\"text\":\"'+text+'\"}';
   var result = networkPost("mySlackChannelHookUrl", content);

and the result is always NetworkReply(name="")
**Expected behavior**
a slack message to arrive

**Actual behavior**
nothing happens

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Application Version [e.g. 3.13.0]
 - OS MacOS 11.2.2

**Comment by hluk** [comment]
That's expected: the return type is `NetworkReply`. To get the response body, use `result.data`.

See: https://copyq.readthedocs.io/en/latest/scripting-api.html#NetworkReply

**Comment by pikaboo** [comment]
The response body should be empty, the request sends a slack message

**Comment by hluk** [comment]
Hmm, I think the bug is that you need to call `result.data` so the request is properly sent and reply received.

You can try:

```js
copyq:
var text = str(clipboard());
var content = '{"text":"'+text+'"}';
var result = networkPost("mySlackChannelHookUrl", content);
result.data; // wait for the reply
if (result.error)
    popup('Error', result.error);
if (result.status >= 300)
    popup('Status', result.status);
```

**Comment by pikaboo** [comment]
You are correct. The documentation is not clear that i need to invoke result.data to actually send the request. I thought that invoking networkPost does it

**Comment by hluk** [comment]
I will probably add `networkPostAsync()` that will behave like the current implementation and change the existing `networkPost()` to synchronously make the request. It's a bit safer and easier to understand.
