### ISSUE TITLE
Fresh CopyQ Snapstore Installation Non-Functional

### ISSUE THREAD

**Issue by ml48603** [hluk/CopyQ#1604]
Before creating a new issue, see list of [known
issues](https://copyq.readthedocs.io/en/latest/known-issues.html).

**Describe the bug**
UI window graphics corrupt / copied text is not posted to list of clips / non-functional / At installation

**To Reproduce**
1. Go to Snapstore App
2. Install CopyQ
3. Start Program
4. See error, pic attached
5. NOTE copied text is not posted to list of clips

**Expected behavior**
Non striped display, copied text clips added to clip list in sequence

**Screenshots**
Screenshot attached
![CopyQ-Issue-3 10 0-1-Fresh-Install-From-Snap-Store-on-MATE20-2021-03-16](https://user-images.githubusercontent.com/17936105/111355500-6a60c100-8655-11eb-9691-06c729d46bf6.png)

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
$ copyq version
CopyQ Clipboard Manager v3.10.0
Qt: 5.12.5
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Ubuntu 20.04.2 LTS

**Additional context**

**Comment by hluk** [comment]
That looks like an old Qt issue. Some time ago, I remember having similar issues on 4k screen.

You can try using latest flatpak version of CopyQ (contains newer Qt).

For details see: https://copyq.readthedocs.io/en/latest/installation.html
