### ISSUE TITLE
Map show/hide main window shortcut to alt + c

### ISSUE THREAD

**Issue by kennethkth** [hluk/CopyQ#1608]
I am trying to map the show/hide main window shortcut to alt + c. This however, is cancelling the operation

**Comment by hluk** [comment]
What do you mean "cancelling the operation"? Which OS/desktop-enviroment are you using?

**Comment by nmat** [comment]
Alt+C seems to work on windows 10 at least here and copyq 3.13.0

**Comment by kennethkth** [comment]
@hluk ubuntu 18.04

**Comment by hluk** [comment]
Closing, since I don't think this works in recent Ubuntu versions anymore: https://copyq.readthedocs.io/en/latest/faq.html#why-do-global-shortcuts-not-work
