### ISSUE TITLE
Sometiems, while in the background, CopyQ starts consuming 100% CPU for unlimited time until killed

### ISSUE THREAD

**Issue by michaelyaakoby** [hluk/CopyQ#1609]
Sometimes, when not used, CopyQ would start using 100% of my machine's CPU for unlimited time until I have notice this and kill it.
This isn't triggered by me copying or pasting anything.

**To Reproduce**
I wish I could tell how to reproduce this - it happens occasionally, sometimes when I'm on a "teams" or "zoom" call.

**Expected behavior**
Leave the CPU alone, especially when not in use.

**Screenshots**
N/A

**Version, OS and Environment**
CopyQ Clipboard Manager v3.10.0
Qt: 5.12.5
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Ubuntu 20.04.2 LTS

Besides its a great tool, thanks you!

**Comment by hluk** [comment]
Can you check full command line argument of the process that eats the CPU? E.g. with `top -c` on command line.

**Comment by michaelyaakoby** [comment]
Sure, next time it happens I will.
Now I see the "process manager" option, it only shows today's processes - next time it happens i'll look there too.
Thanks

**Comment by michaelyaakoby** [comment]
Just happened again.
Here are running processes:
![image](https://user-images.githubusercontent.com/5503849/112498637-650b2100-8d8f-11eb-8dc6-84868093d99a.png)

Could it be triggered by ms-teams in anyway? 
The last two times happened when I was on a teams-call and sharing my screen.

**Comment by michaelyaakoby** [comment]
I upgraded to v3.13.0 and will see if this is reproduced.

**Comment by hluk** [comment]
Unfortunately, the Process Manager in CopyQ doesn't show CPU utilization and doens't capture the server/GUI process.

If it happens again please check output of `top -c` or a process manager in your desktop environment but see if it can provide full command line argument (not just process name).

**Comment by michaelyaakoby** [comment]
You are correct, my bad :-(
Will get CPU utilization as you suggested if this happens again.

**Comment by michaelyaakoby** [comment]
Doesn't reproduce anymore.
Closing.
Thanks for responding, and thanks for developing this - its really great.
