### ISSUE TITLE
Color theme does not always match current system theme

### ISSUE THREAD

**Issue by tiosgz** [hluk/CopyQ#1613]
**Is your feature request related to a problem? Please describe.**
I switch my Kvantum theme quite often & every time I do that, I have to open CopyQ settings & reset the theme to again match with everything else.

**Describe the solution you'd like**
The best solution for me would be if CopyQ didn’t use its own theme at all.

**Describe alternatives you've considered**
An option to reset the theme automatically (e.g. via a command) would also be fine, since I do everything from a script. If CQ reacted immediately (I haven’t tried if it does) & I wouldn’t have to save all my configuration in the theme file (which seems to be how it is now, though its main purpose is of course config, not theme), symlinking or overwriting files is also okay.

**Comment by hluk** [comment]
Do you mean the colors of the item list are broken when switching to a different Kvantum theme or even menu bar, toolbar, tabs, menus etc? Do you have "Set colors for tabs, tool bar and menus" option enabled (in Appearance config tab)?

**Comment by tiosgz** [comment]
No colours are broken, they only don’t match my Kvantum theme (until I reset them with the button in appearance config). I have as much as possible controlled by the system theme, i.e. only the list is inconsistent with the rest of my screen; the option you mentioned is disabled.

**Comment by hluk** [comment]
I've fixed it so that instead of colors a placeholders like `default_bg` can be used in configuration. With the change you will have to do last "Reset Theme" and then the colors should always match current system theme.

Unfortunately, I haven't found a functionality in Qt that updates colors when Kvantum theme changes. It looks like Qt apps need to be restarted if this happens.

**Comment by tiosgz** [comment]
Seems to work great, thanks!

> Unfortunately, I haven't found a functionality in Qt that updates colors when Kvantum theme changes. It looks like Qt apps need to be restarted if this happens.

Hmm, restarting CopyQ is not *perfect*, but is pretty much *enough* for me. (For the widgets themed by QT_QPA_PLATFORMTHEME (for me qt5ct) I use [qt5ct-refresh].)

[qt5ct-refresh]:https://gitlab.com/zetaPRIME/qt5ct-refresh/

**Comment by hluk** [comment]
With qt5ct I can use some undocumented Qt event to find when theme changes (`QEvent::ThemeChange`), so application theme can be automatically updated.

But with Kvantum the app doesn't receive any events/notifications. The only thing that worked was recreating the style object manually:

```c++
QApplication::setStyle(QStyleFactory::create("kvantum"));
```

For those cases where theme cannot be updated automatically, I'm adding some functionality to handle setting/updating theme in CopyQ:

```
❯ copyq config style kvantum

❯ copyq config style kvantum-dark

❯ copyq styles
Adwaita-Dark
Adwaita
Breeze
kvantum-dark
kvantum
qt5ct-style
Windows
Fusion
```

**Comment by tiosgz** [comment]
Oooh! I didn’t expect that you would bother with me further after I could achieve what I wanted, but this improves it a lot. Thank you!

**Comment by hluk** [comment]
It has been bothering me for a while actually. :)

I hope this improves in the future so that the theme updates are fully automatic. :crossed_fingers:
