### ISSUE TITLE
Running or matching an action from another action

### ISSUE THREAD

**Issue by elig0n** [hluk/CopyQ#1618]
I have one action where upon a match commands are run, at the end string is put into clipboard via copy().
If that string matches another action's match it does not run, I have to paste it and recopy it for the other action to run on it.
Is there a way to either invoke manually from the first action the second action ? or to have the second action run for copy() clipboard changes ?

**Comment by hluk** [comment]
Automatic commands are not invoked on stuff copied from CopyQ itself to avoid invoking the commands in an infinite loop.

If you want to make additional operation on the copied string, you need to explicitly call the functions/command after `copy()` operation.
