### ISSUE TITLE
Themes not working v4.0.0.

### ISSUE THREAD

**Issue by fosam** [hluk/CopyQ#1621]
Before creating a new issue, see list of [known
issues](https://copyq.readthedocs.io/en/latest/known-issues.html).

**Describe the bug**
Unable to set theme, after theme is selected, CopyQ closes immediately.

**To Reproduce**
Preferences--->Appearance--->Theme

**Expected behavior**
Theme applied.

**Screenshots**

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Application Version [v4.0.0]
 - OS [Windows 10, 2004]
 - Desktop environment, window manager (if applicable)

**Additional context**

**Comment by hluk** [comment]
Anything in logs (F12 shortcut in the main window)?

Which theme are you using? If it's a custom one, can you Save Theme and share it here?

Do you use any custom CSS files?

**Comment by hluk** [comment]
Oh, I can reproduce this when selecting Forest theme in the app on Windows. I will try to fix this later.

**Comment by fosam** [comment]
It regards all the included themes, works fine on versions before v4.0.0

**Comment by hluk** [comment]
Looks like a bug in Qt - with the default `windowsvista` style.

Following fixes the issue for me:

1. Open Action dialog (F5 from the main window).
2. Enter command: `copyq config style Fusion` (or `copyq config style windows`)
3. Click OK.

Style of widgets should change slightly.

**Comment by hluk** [comment]
Fixed. I've re-uploaded the setup.exe and portable zip for Windows: https://github.com/hluk/CopyQ/releases/tag/v4.0.0

**Comment by fosam** [comment]
Works. 👍
