### ISSUE TITLE
copyq upgrade requires 53 new packages ?

### ISSUE THREAD

**Issue by mckellygit** [hluk/CopyQ#1622]
Hi,

Thank you for CopyQ - it is so awesome.
I noticed today my system can upgrade copyq, but it also shows I need 53 new pkgs, are these all for the new version of copyq ?  Does that seem correct ?

I am currently on:
CopyQ Clipboard Manager v3.13.0
Qt: 5.9.5
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Ubuntu 18.04.5 LTS

apt-get upgrade shows me:
The following NEW packages will be installed:
  kwayland-data kwayland-integration liba52-0.7.4 libaribb24-0 libbasicusageenvironment1 libcddb2 libdbusmenu-qt5-2 libdvbpsi10 libebml4v5 libfam0 libgroupsock8
  libkf5codecs-data libkf5codecs5 libkf5config-bin libkf5config-data libkf5configcore5 libkf5coreaddons-data libkf5coreaddons5 libkf5idletime5
  libkf5notifications-data libkf5notifications5 libkf5waylandclient5 libkf5windowsystem-data libkf5windowsystem5 liblivemedia62 libmad0 libmatroska6v5
  libmicrodns0 libmpeg2-4 libnfs11 libopenmpt-modplug1 libphonon4qt5-4 libplacebo4 libprotobuf-lite10 libproxy-tools libqt5texttospeech5 libqt5waylandclient5
  libqt5waylandcompositor5 libresid-builder0c2a libsdl-image1.2 libsidplay2 libupnp6 libusageenvironment3 libva-wayland2 libvlc-bin libvlc5 libvlccore9 phonon4qt5
  phonon4qt5-backend-vlc qtwayland5 vlc-data vlc-plugin-base vlc-plugin-video-output
The following packages will be upgraded:
  copyq

thx always for everything,
-m

**Comment by hluk** [comment]
CopyQ 4.0.0 now needs KNotifications (KDE Frameworks) and libraries for Wayland support.
