### ISSUE TITLE
Error on Win7 when copying text to clipboard (v4.0.0)

### ISSUE THREAD

**Issue by Gitoffthelawn** [hluk/CopyQ#1623]
**Describe the bug**
When the user copies text to the clipboard in Win7, the following error is encountered:

```
***snoretoast.exe - System Error***

The program can't start because api-ms-win-core-winrt-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem. 
```

After this happens, CopyQ will crash when the user closes CopyQ.

**To Reproduce**
1. Copy CopyQ portable v4.0.0 to a folder
2. Launch CopyQ
3. Select text in any app
4. Try to copy the text to the clipboard
5. Notice the system error
6. Try to close CopyQ
7. Notice CopyQ will crash

**Expected behavior**
No error.  Work like in previous versions.

**Screenshots**
N/A

**Version, OS and Environment**
 - CopyQ v4.0.0 portable
 - Win7 64-bit

**Comment by hluk** [comment]
Oh, wow, looks like bug in the notifications.

Workaround, is to remove `snoretoast.exe` from the installed/unzipped folder. But this also disables notifications. :(

**Comment by Gitoffthelawn** [comment]
@hluk I think the answer is "yes", but I want to double-check: Do notifications include the momentary popup that displays the selection when it is copied to the clipboard?

If so, that's one of my favorite features of CopyQ. :)

**Comment by hluk** [comment]
BTW, snoretoast binary is otherwise linked statically (https://invent.kde.org/libraries/snoretoast/-/blob/v0.7.0/CMakeLists.txt#L27).

**Comment by hluk** [comment]
Oh, well it's snoretoast itself that does not support Windows (https://invent.kde.org/libraries/snoretoast/-/blob/v0.7.0/README.md):

> A command line application capable of creating Windows Toast notifications on Windows 8 or later.

**Comment by Gitoffthelawn** [comment]
I expected Microsoft to try to manufacture unnecessary incompatibility to force people onto Windows 10, but KDE?  😱

**Comment by Gitoffthelawn** [comment]
I guess there are 4 choices:

1. Choose a different toast library (boo snoretoast!).
2. Support the new toast library as well as system notifications (at least for Windows).
3. Ask snoretoast to add Windows 7 support.
4. Remove support for Windows 7 (in which case I'll never talk to you again, so that's not an option 😆 😆 😆).

**Comment by hluk** [comment]
Interestingly, KDE Frameworks seems to be the only viable option to have cross-platform notifications. They support Windows and macOS but it's definitely not as battle-tested as the support for Linux.

BTW, notifications are also **difficult to test** (currently, it's a manual check). To help with this, one idea was to [take a screenshot after build](https://github.com/hluk/CopyQ/blob/968d9d88e8f6c939cbc942eade31ceddfa2024a1/utils/appveyor/after_build.sh#L68) and compare to a template. For example, see [screenshot.png in this build](https://ci.appveyor.com/project/hluk/copyq/builds/38676074/artifacts) - but there is no notification visible - I think it would require an arbitrary delay after opening the notification (e.g. `copyq sleep 5000`).

**Comment by Gitoffthelawn** [comment]
I'm not sure if this will help, but I know WebChangeMonitor has notifications and is cross-platform.  It's been a while since I read all the code, but it is available here: https://sourceforge.net/projects/webchangemon/ (just like CopyQ, it's great project with a great primary developer).

Yes, testing notifications can certainly be challenging.  Even with screenshots, they can be a challenge if you don't have stable test environments for each OS.  Like you mentioned, an arbitrary delay of sufficient length after opening the notification is often helpful when testing them.

CopyQ is one of the few programs that really requires notifications for many of its useful functions.  Notifications are also one of CopyQ's primary differentiating features that the hundreds of other clipboard enhancement tools do not have.  Personally, I find the notifications paramount in determining if important content was successfully copied to the clipboard.

I need to re-read the reasons why you decided to switch away from system notifications.  At least in Windows 7, they seemed to work.  They did have a couple minor issues (https://github.com/hluk/CopyQ/issues/1620#issuecomment-818296266 and https://github.com/hluk/CopyQ/issues/1615), but overall they worked reasonably well.

**Comment by hluk** [comment]
> WebChangeMonitor has notifications and is cross-platform.

Looks like it uses wxWidgets GUI library which has support for notifications, but they also mention only [support for Windows 8 and up](https://docs.wxwidgets.org/trunk/classwx_notification_message.html).

> I need to re-read the reasons why you decided to switch away from system notifications.

Maybe there is a misunderstanding. CopyQ is now **using system notifications** instead of a custom implementation which basically showed dummy undecorated windows (using Qt framework).

**Comment by Gitoffthelawn** [comment]
> Looks like it uses wxWidgets GUI library which has support for notifications, but they also mention only support for Windows 8 and up.

Interesting.  I'm using it on Win7 without any difficulties with the notifications.  Martin (the primary developer) had to recently make separate releases for Win7 and Win10, I think due to a dependency issue (IIRC).  I'm not sure if that had anything to do with notifications or wxWidgets.

I just read the wxWidgets page you referenced, and unfortunately it's not written very clearly.  I get the sense they are trying to say some things can work differently as of Win8, and maybe a couple functions are either required for Win8-Win10, or only work on those versions.  But I think they are saying wxWidgets overall works on Win7. 

When I look at the [wxWidgets requirements page](https://docs.wxwidgets.org/trunk/page_introduction.html#page_introduction_requirements), it states that the project supports WinXP-Win10, inclusive.

> Maybe there is a misunderstanding. CopyQ is now using system notifications instead of a custom implementation which basically showed dummy undecorated windows (using Qt framework).

Ya, I had only read the release notes once at that point and I needed to re-read them.  But what I didn't know until now is how you were doing the notifications before (which may possibly explain a couple minor quirks).  Thanks for the details.  Why not use the Windows API to show Windows system notifications?  It would require a check of the underlying OS (since that API isn't x-platform), but that's an easy task.

**Comment by hluk** [comment]
Here is a development version where you can disable native notifications (it's disabled by default on Windows 7): https://ci.appveyor.com/project/hluk/copyq/builds/38686827/artifacts

**Comment by hluk** [comment]
> Why not use the Windows API to show Windows system notifications?

Maintaining platform-specific code is very time-consuming. I currently use only Linux actively (for work and otherwise) so the support there is much better than on other platforms. Having a cross-platform library really helps a lot (most of the stuff is already handled in Qt).

**Comment by Gitoffthelawn** [comment]
> Here is a development version where you can disable native notifications (it's disabled by default on Windows 7)...

Thanks.  Is it using Qt for the notifications like v3.x?

> Maintaining platform-specific code is very time-consuming. I currently use only Linux actively (for work and otherwise) so the support there is much better than on other platforms. Having a cross-platform library really helps a lot (most of the stuff is already handled in Qt).

I agree 100%. :)

BTW, I aspire to only use Linux actively, but that's a discussion for another place. :)  It's actually one big reason I chose CopyQ... because when I eventually achieve that goal, I'll already be familiar with a great clipboard enhancement tool.

In this case, though, would it literally be something as simple as this pseudo-code?:

```
IF OS = WIN7 THEN
      windowsNotificationAPI(notification)
   ELSE
      snoretoast(notification)
```

**Comment by hluk** [comment]
>  Is it using Qt for the notifications like v3.x?

Yes. Windows 7, it should work as in the older CopyQ versions.

**Comment by hluk** [comment]
I will try to release a fixed version soon.

**Comment by Domyras** [comment]
Bump @hluk 
any updates? :D
