### ISSUE TITLE
Problems with 2 monitors and moving app to second monitor

### ISSUE THREAD

**Issue by GreyCrowned** [hluk/CopyQ#1624]
**Describe the bug**
When working with 2 monitors using the Start+ArrowKey to move the application to the other window Copy Q window shakes as though it is trying to move but does not. When trying to move the window with the mouse to the other monitor the window gets stuck in between the two monitors and shakes.

**To Reproduce**
With two monitors open Copy Q
Highlight Copy Q to be active window
Use the Start+Right Arrow to move to other monitor

**Expected behavior**
Expect the CopyQ window to move to other monitor

**Screenshots**
NA

**Version, OS and Environment**
Version 4.0.0
Windows 10

**Additional context**
NA

**Comment by hluk** [comment]
Can you test if [this development build](https://ci.appveyor.com/project/hluk/copyq/builds/38666252/artifacts) fixes the issue?

**Comment by GreyCrowned** [comment]
Lukas,
   This build corrected the problem. Can I continue to use this build since the problem is corrected.
Awesome app thanks much


Best Regards,
Thomas Zaprzalka


On April 12, 2021 at 2:07 PM, Lukas Holecek ***@***.***> wrote:






Can you test if this development build fixes the issue?

**Comment by hluk** [comment]
The development version should be safe to use. It contains other patches for Windows. I'll probably do another release soon, or upload fixed Windows binaries for v4.0.0 release.

**Comment by www-apius** [comment]
Lukas, Same thing happens on macOS. Could you release 4.1 for Mac?

**Comment by hluk** [comment]
> Lukas, Same thing happens on macOS. Could you release 4.1 for Mac?

@www-apius There was some issue with the build system (GitHub Actions). It's working now. I'll hopefully upload macOS build in a few minutes.
