### ISSUE TITLE
Paste as plain text not working since upgraded to 4.0.0

### ISSUE THREAD

**Issue by macgyverski** [hluk/CopyQ#1627]
Hi hluk :)
First of all, thank you very much for this piece of amazing software that I'm using on daily basis, make me save a lot of time and is one of the first software I do install on my config !
I upgraded to v4.0.0 yesterday ( via your ppa) and since then I do have a issue with "copy as plain text"
The feature stopped working since the "Format "text/plain;charset=utf-8" is now preferred to "text/plain"." was introduced.
I can reproduce the issue on my Ubuntu Mate 20.04 US and 20.04 FR configs.

**Describe the bug**
Long time ago, I have set-up 1 extra shortcuts. I use : 
Ctrl+V to paste text from the clipboard as formatted text
Ctrl+Shift+V to paste formatted text as plain text loosing formatting

This second shortcut do not paste any output since upgraded to 4.0.0

**To Reproduce**
1 Go to File > Preferences > Shortcuts
2 Configure a shortcut to paste text as plain text
3 Copy formatted or unformatted text to your clipboard
4 Insure CopyQ have it in the clipboard
5 Paste the wanted text without formatting with the new configured shortcut,

**Expected behavior**
Before the update, the Copy as plain text was working. Nothing happens now after the function is called with the shortcut.

**Version, OS and Environment**
dpkg -l | grep copyq
ii  copyq                                       4.0.0~focal                         amd64        Advanced clipboard manager with editing and scripting features

uname -a
Linux apbook02u 5.8.0-050800-generic #202008022230 SMP Sun Aug 2 22:33:21 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

ubuntu-mate-desktop 1.263

Once again thanks a lot for this amazing software !

**Comment by hluk** [comment]
Anything in the logs (F12 shortcut from the main window)?

Can you also check output of `copyq clipboard "?"` and `copyq clipboard`?

**Comment by macgyverski** [comment]
Thanks for your answer :)

Here comes results of those commands : 

```
$ copyq clipboard "?"
text/plain
application/x-copyq-owner

```
```
$ copyq clipboard
copyq clipboard "?"
text/plain
application/x-copyq-owner
```

I don't see any error inside logs now that I manipulate the clipboard, but saw this that match the copyq auto start after boot time : 

```
Warning [2021-04-13 09:16:53.634] <monitorClipboard-1899>: ELAPSED 1345 ms acessing "text/plain"
Warning [2021-04-13 09:16:53.641] <monitorClipboard-1899>: ELAPSED 1352 ms acessing "UTF8:text/plain"
```

**Comment by hluk** [comment]
Is your desktop based on Wayland and not X11? If so see: https://copyq.readthedocs.io/en/latest/known-issues.html#on-linux-global-shortcuts-and-pasting-doesn-t-work

**Comment by macgyverski** [comment]
Hi hluk, thanks for your answer. I'm running on x.org and not wayland.
This feature was perfectly working for me before upgrading to 4.0

**Comment by macgyverski** [comment]
I found a workaround : 
From copyq window, strike F6
Click "Add" to add new feature
Search for "Paste as plain text"
Add a keyboard shortcut

It's working this way :)

**Comment by macgyverski** [comment]
I was digging long time to find a working workaround. I created new function : 

```
copyq:
var encoding = 'utf8'
var textData = clipboard()
var text = toUnicode(textData, encoding)
setData(mimeText, text)
copy(text)
paste(text)

```
Need to hold my shortcut for 3 seconds to paste my text.
I then duplicated the paste() instruction : 

```
copyq:
var encoding = 'utf8'
var textData = clipboard()
var text = toUnicode(textData, encoding)
setData(mimeText, text)
copy(text)
paste(text)
paste(text)

```
My text is pasted as expected.
Maybe it is a problem on my configuration only.

**Comment by hluk** [comment]
There are new options you can use to fix some intervals/delays:

```
window_key_press_time_ms
window_wait_after_raised_ms
window_wait_before_raise_ms
window_wait_for_modifiers_released_ms
window_wait_raised_ms
```

But the default value for `window_wait_for_modifiers_released_ms` seem to be **incorrect** now. You can revert it to the original delay with following command:

```
copyq config window_wait_for_modifiers_released_ms 2000
```

**Comment by macgyverski** [comment]
Thanks hluk :)
Confirming, that fixes the issue.
Thank you for this amazing software !
