### ISSUE TITLE
When moving program to different monitor screens it freaks out!

### ISSUE THREAD

**Issue by jojo7085** [hluk/CopyQ#1632]
Just updated to the new release.  Now I have problems.  I use 3 monitors and I was able to move the copyq window to any of the screens before to use depending on what I had up on each monitor.  I like to always keep the window open because I go back and forth copying and pasting a lot.  Now when I move it to one of the NOT primary monitors it starts flashing like crazy and freaks outs!  I would even gladly pay to use this program and if this continues I will now have to seek another source.  I just started using 2 months ago and have been happy until the release.  Please advise.  Thank you. 

Using Windows 10 latest release

Before creating a new issue, see list of [known
issues](https://copyq.readthedocs.io/en/latest/known-issues.html).

**Describe the bug**

**To Reproduce**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Application Version [e.g. 3.7.2]
 - OS [e.g. Windows]
 - Desktop environment, window manager (if applicable)

**Additional context**

**Comment by hluk** [comment]
I think this is fixed in #1624. Development build with the fix: https://ci.appveyor.com/project/hluk/copyq/builds/38666252/artifacts

**Comment by jojo7085** [comment]
Ok, I went to the link you provided above and downloaded the exe file from there and now it is working.  I believe that is the most recent build version? 
Thank you.

**Comment by hluk** [comment]
Recent builds are listed here: https://ci.appveyor.com/project/hluk/copyq/history (but I advice to pick only passed/green ones from "master" which should be relatively stable)
