### ISSUE TITLE
copyq doesn't start minimized to tray

### ISSUE THREAD

**Issue by cristianmtr** [hluk/CopyQ#1635]
Before creating a new issue, see list of [known
issues](https://copyq.readthedocs.io/en/latest/known-issues.html).

**Describe the bug**

Copyq used to start minimized into the tray. Now it starts as a window in the task bar.

**To Reproduce**

Added it to the startup applications in Ubuntu 20.04 as `/usr/bin/copyq`

**Expected behavior**

It should start minimized to the tray

**Screenshots**

![image](https://user-images.githubusercontent.com/8330330/114712260-30580d00-9d30-11eb-865e-bd7dd7ce7c99.png)

**Version, OS and Environment**

```
CopyQ Clipboard Manager v3.10.0
Qt: 5.12.5
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Ubuntu 20.04.2 LTS
```

**Additional context**

If I kill CopyQ and start it again, it now starts minimized to the tray.

![image](https://user-images.githubusercontent.com/8330330/114712450-65645f80-9d30-11eb-80c3-ea68de5023c1.png)

**Comment by hluk** [comment]
Try refreshing the autostart entry:

```
rm -f ~/.config/autostart/copyq.desktop
copyq config autostart true
```

You can check if it's correct (it should contain `X-GNOME-Autostart-Delay`):

```
❯ grep -vE 'GenericName|Comment' ~/.config/autostart/copyq.desktop
[Desktop Entry]
Name=CopyQ
Icon=copyq
# Workaround / fix for issue #1526 that prevents a proper autostart of the tray icon in GNOME
X-GNOME-Autostart-Delay=3
# The rest is taken from Klipper application.
Type=Application
Terminal=false
X-KDE-autostart-after=panel
X-KDE-StartupNotify=false
X-KDE-UniqueApplet=true
Categories=Qt;KDE;Utility;
Exec="/home/lholecek/dev/build/copyq/release/copyq"
Hidden=false
X-GNOME-Autostart-enabled=true
```

**Comment by cristianmtr** [comment]
Hey! Thanks for the quick reply.

Unfortunately my desktop entry looks different

```
$ grep -vE 'GenericName|Comment' ~/.config/autostart/copyq.desktop
[Desktop Entry]
Name=CopyQ
Icon=copyq
# The rest is taken from Klipper application.
Type=Application
Terminal=false
X-KDE-autostart-after=panel
X-KDE-StartupNotify=false
X-KDE-UniqueApplet=true
Categories=Qt;KDE;Utility;

Exec="/usr/bin/copyq"
Hidden=False
X-GNOME-Autostart-enabled=true
```

**Comment by hluk** [comment]
> Should I just add `X-GNOME-Autostart-Delay=3`?

Yes. Though that should have been fixed by the refresh commands I mentioned before.

**Comment by cristianmtr** [comment]
It didn't, but adding it myself fixed the problem on the next restart :+1:
