### ISSUE TITLE
cmake warning on Raspberry Pi 4 

### ISSUE THREAD

**Issue by cpsyctc** [hluk/CopyQ#1636]
Before creating a new issue, see list of [known
issues](https://copyq.readthedocs.io/en/latest/known-issues.html).
I couldn't find this there

**Describe the bug**
It's a warning not a bug but as I'm not sure how many people will compile CopyQ on a Pi I thought I should report it.

**To Reproduce**
I couldn't see a binary for the Pi (uname -a
Linux raspberrypi 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l GNU/Linux)
so I opted to compile it following your very clear instructions and I got this warning:

CMake Warning (dev) in src/platform/x11/systemclipboard/CMakeLists.txt:
  Policy CMP0071 is not set: Let AUTOMOC and AUTOUIC process GENERATED files.
  Run "cmake --help-policy CMP0071" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  For compatibility, CMake is excluding the GENERATED source file(s):

    "/home/pi/CopyQ/src/platform/x11/systemclipboard/wayland-wlr-data-control-unstable-v1-protocol.c"
    "/home/pi/CopyQ/src/platform/x11/systemclipboard/qwayland-wlr-data-control-unstable-v1.cpp"
    "/home/pi/CopyQ/src/platform/x11/systemclipboard/qwayland-wlr-data-control-unstable-v1.h"

  from processing by AUTOMOC.  If any of the files should be processed, set
  CMP0071 to NEW.  If any of the files should not be processed, explicitly
  exclude them by setting the source file property SKIP_AUTOMOC:

    set_property(SOURCE file.h PROPERTY SKIP_AUTOMOC ON)

This warning is for project developers.  Use -Wno-dev to suppress it.

**Expected behavior**
I think that's self-explanatory.  As far as I can see, CopyQ has installed fine but I haven't used it much yet.

**Version, OS and Environment**
CopyQ Clipboard Manager v4.0.0-17-gf276fd70
Qt: 5.11.3
KNotifications: 5.54.0
Compiler: GCC
Arch: arm-little_endian-ilp32-eabi-hardfloat
OS: Raspbian GNU/Linux 10 (buster)

**Additional context**
Just continuing huge gratitude to you for CopyQ, I use it on two Ubuntu laptops, Windows in a VM and on a standalone machine, and will now use it on the Pi as well. Saved me days, probably weeks, of my life.

**Comment by hluk** [comment]
I think I had problems with AUTOMOC before, that's why it's disabled. Maybe it was because I had to support older cmake or Qt.

**Comment by hluk** [comment]
Oh, actually, AUTOMOC is enabled. It's only disabled in the `systemclipboard` part which is taken from Klipper.

**Comment by hluk** [comment]
I don't see the warning with cmake 3.19.7, even when using `-Werror=dev -Wdeprecated -Wdev`.

**Comment by cpsyctc** [comment]
Maybe I am just creating noise.  My cmake was 3.16.3 so way behind yours.  I pulled the latest cmake source and compiled that and now have 3.20.1 and now I get this:

root@raspberrypi:/home/pi/CopyQ# cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local .
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building CopyQ version v4.0.0-17-gf276fd70.
CMake Warning (dev) at /usr/local/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args`
  (KF5Notifications) does not match the name of the calling package (KF5).
  This can lead to problems in calling code that expects `find_package`
  result variables (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /usr/share/ECM/find-modules/FindKF5.cmake:78 (find_package_handle_standard_args)
  src/notifications.cmake:9 (find_package)
  src/CMakeLists.txt:24 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Building for X11 window system.
CMake Warning (dev) at /usr/local/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args`
  (Wayland_Client) does not match the name of the calling package (Wayland).
  This can lead to problems in calling code that expects `find_package`
  result variables (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /usr/share/ECM/modules/ECMFindModuleHelpers.cmake:248 (find_package_handle_standard_args)
  /usr/share/ECM/find-modules/FindWayland.cmake:101 (ecm_find_package_handle_library_components)
  src/platform/x11/systemclipboard/CMakeLists.txt:3 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
CMake Warning (dev) in src/platform/x11/systemclipboard/CMakeLists.txt:
  Policy CMP0071 is not set: Let AUTOMOC and AUTOUIC process GENERATED files.
  Run "cmake --help-policy CMP0071" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  For compatibility, CMake is excluding the GENERATED source file(s):

    "/home/pi/CopyQ/src/platform/x11/systemclipboard/wayland-wlr-data-control-unstable-v1-protocol.c"
    "/home/pi/CopyQ/src/platform/x11/systemclipboard/qwayland-wlr-data-control-unstable-v1.cpp"
    "/home/pi/CopyQ/src/platform/x11/systemclipboard/qwayland-wlr-data-control-unstable-v1.h"

  from processing by AUTOMOC.  If any of the files should be processed, set
  CMP0071 to NEW.  If any of the files should not be processed, explicitly
  exclude them by setting the source file property SKIP_AUTOMOC:

    set_property(SOURCE file.h PROPERTY SKIP_AUTOMOC ON)

This warning is for project developers.  Use -Wno-dev to suppress it.

That means absolutely nothing to me beyond suggesting that this was not just about an outdated cmake.  Maybe it means more to you!  As I get some experience with using CopyQ on the Pi I will report if I hit problems but it looks as if this is just a warning if I don't need those wayland files.  You will know about that much better than I do as it means essentially zero to me! Very best,  Chris

**Comment by hluk** [comment]
Feel free to submit a patch but I'm not going to fix this myself unless I start seeing those in my development environment.

If there are any other problems building the app or running it, let me know.
