### ISSUE TITLE
Automatically copy the entry that was just created

### ISSUE THREAD

**Issue by p-himik** [hluk/CopyQ#1637]
**Is your feature request related to a problem? Please describe.**
With Xorg, when you copy something from an app and then close that app, the copied item will not be available anymore.
Even if the item is stored by CopyQ, the clipboard will be empty.

**Describe the solution you'd like**
I'd like to have an option that makes CopyQ the owner of an item that was just copied.
So this sequence of commands would work just as is:
- Ctrl+C something from an app
- Close that app
- Ctrl+V that something somewhere else, without interacting with CopyQ at all

**Describe alternatives you've considered**
Perhaps, `xbindkeys` could be used to replace Ctrl+C with a sequence that copies something and then activates that something with `copyq`. But it sounds like an unreliable ad-hoc solution.

**Comment by hluk** [comment]
This is handled by [Reset Empty Clipboard/Selection](https://github.com/hluk/copyq-commands/tree/master/Scripts#reset-empty-clipboardselection) (see [README.md](https://github.com/hluk/copyq-commands/blob/master/README.md) for details on how to add the command).

**Comment by p-himik** [comment]
Thanks. But there are still problems:
- It works only with text
- If the original app is not closed but hangs up somewhere in between Ctrl+C and Ctrl+V, the custom command won't work

**Comment by hluk** [comment]
> Thanks. But there are still problems:
> 
>   * It works only with text

I never needed this with anything else than text, but the command can be expanded to store other formats.

> 
>   * If the original app is not closed but hangs up somewhere in between Ctrl+C and Ctrl+V, the custom command won't work

Why would this happen? I don't think there is an easy way to detect that current clipboard owner is frozen.

**Comment by p-himik** [comment]
> I never needed this with anything else than text, but the command can be expanded to store other formats.

Yeah, I'll probably try to do that, just have to go through the commands API.

> Why would this happen?

Due to some bug. I acknowledge that it's very rare, but it's definitely a possibility.

> I don't think there is an easy way to detect that current clipboard owner is frozen.

And that's exactly why my initial post suggests moving the clipboard to CopyQ, not when it's empty, but right when it's changed.
Perhaps, this could also be achieved with a custom command.

**Comment by hluk** [comment]
> And that's exactly why my initial post suggests moving the clipboard to CopyQ, not when it's empty, but right when it's changed.
Perhaps, this could also be achieved with a custom command.

Taking over clipboard when it changes breaks some applications. This could be simply because an app expects to be the clipboard owner or expect some special formats in clipboard. If CopyQ sets clipboard it would also need to set the special formats - iterating over all clipboard data can be expensive and it would still break some apps.

If you still want to try it out, here is the command:

```ini
[Command]
Automatic=true
Command="
    copyq:
    var formats = str(clipboard('?')).split('\\n');
    var toCopy = []
    for (var i in formats) {
        var format = formats[i];
        var c = format[0];
        if ('a' <= c && c <= 'z') {
            toCopy.push(format);
            toCopy.push(clipboard(format));
        }
    }
    copy.apply(this, toCopy);"
Icon=\xf521
Name=Take Over Clipboard
```

**Comment by p-himik** [comment]
Oh, I see. Thanks!
