### ISSUE TITLE
New snoretoast notification system in v4.0.0 breaks portability

### ISSUE THREAD

**Issue by Gitoffthelawn** [hluk/CopyQ#1638]
**Describe the bug**
CopyQ v4.0.0 is no longer portable due to the snoretoast notification system.

It creates the following file outside of the CopyQ folder:
`..\AppData\Local\knotifications5\copyq.notifyrc`

**To Reproduce**
1. Download the Windows portable release of CopyQ from GitHub
2. Extract the release
3. Place the extracted files into a folder
4. Launch CopyQ
5. Notice the folder `..\AppData\Local\knotifications5\` is created as well as the file `..\AppData\Local\knotifications5\copyq.notifyrc`.  Both are created outside of the expected folder.

**Expected behavior**
No files created outside of the CopyQ folder and its subfolders

**Version, OS and Environment**
 - CopyQ v4.0.0 portable
 - Win7 64-bit

**Comment by hluk** [comment]
Fixed here: https://ci.appveyor.com/project/hluk/copyq/builds/38772525/artifacts

**Comment by Gitoffthelawn** [comment]
@hluk Thanks.  No rush... do you have an ETA for the next release?  I have some admin stuff to do, and I'll include the latest CopyQ if you're planning a release soon.

**Comment by hluk** [comment]
No ETA, I'll make the release when I have the time - hopefully soon.

**Comment by Gitoffthelawn** [comment]
Sounds good... no rush and no pressure at all.  :)
