### ISSUE TITLE
Can no longer "copy next item" and "copy previous item" using shortcut keys 

### ISSUE THREAD

**Issue by JackDinn** [hluk/CopyQ#1640]
After update to version 4 I can no longer use the keyboard to go back and forward through the history of clipboard. I think is it kinda working, but it's a problem with the new pop-up it fails to show the new history item as you go through them, so you don't know what you're selecting.

You can repeat by setting a hotkey for "copy next item" and "copy previous item". Then try using these hotkeys to go backwards/forwards through the history, you will see the popup stops responding (mostly). It will often move 1 or 2 history items and then the notification popup will "freeze" the text it is showing and not change again until you allow the pop-up to naturally disappear.

After testing for a while it seems to be intermittent, sometimes it works but mostly not.

EDIT:- O, and it also steals the focus away from some input fields that you may have been working in at the time. Example:- you may be filling out the search input field in duckduckgo, you may use the shortcut keys to scroll back in history a couple of selections. Then you hit Ctrl V and find that the input field you were working in is no longer in focus, so you have to click on it again before you can paste into it.

Linux Manjaro KDE (X11)

**Comment by hluk** [comment]
There will be an option in next version to disable native notifications/popups.

> EDIT:- O, and it also steals the focus away from some input fields that you may have been working in at the time. Example:- you may be filling out the search input field in duckduckgo, you may use the shortcut keys to scroll back in history a couple of selections. Then you hit Ctrl V and find that the input field you were working in is no longer in focus, so you have to click on it again before you can paste into it.

I think X11 behaves this way. It looks like the focus goes away from current app so CopyQ can trigger the global shortcut event handler (no idea how to fix this). Workaround could be to assign `copyq next` and `copyq previous` shortcuts in KDE instead.

**Comment by JackDinn** [comment]
> There will be an option in next version to disable native notifications/popups.

That sounds like it'll fix it.

> I think X11 behaves this way. It looks like the focus goes away from current app so CopyQ can trigger the global shortcut event handler (no idea how to fix this). Workaround could be to assign `copyq next` and `copyq previous` shortcuts in KDE instead.

I didn't think it did steal focus before the new pop-up was implemented, you have me questioning my memory of using copyq now. I shall have a tinker and see what i can find.

Cheers :+1:
