### ISSUE TITLE
Shaky behaviour of CopyQ

### ISSUE THREAD

**Issue by popovserhii** [hluk/CopyQ#1642]
**Describe the bug**
When I open CopyQ it's just go crazy and start shaking through all items. I thought it tries to sort the items but not, it just jumping. I cannot scroll down to previous items, it just doesn't allow me. I don't know if it's  a bug, but it behaviour is really annoying and I don't know how to fix.

**Expected behaviour**
I can open CopyQ, scroll through all items without that "shaky effect".

**Screenshots**
I recorded the [video](https://youtu.be/ny-VWlXaeaI) of this behaviour.

**Version, OS and Environment**
 - Application Version **4.0.0**
 - OS **Linux Mint**
 - Desktop environment.

**Comment by hluk** [comment]
Thanks for the video!

I have not seen this happen yet (not was it reported).

Are you using some commands (listed in Command dialog - F6 shortcut)?

Is that tab synchronized with a directory (i.e. it's using the [Synchronization](https://copyq.readthedocs.io/en/latest/synchronize.html) plugin)?

**Comment by popovserhii** [comment]
Hi @hluk 

> Are you using some commands (listed in Command dialog - F6 shortcut)?

Yes, I have those [two custom commands](https://github.com/hluk/CopyQ/issues/1094#issuecomment-495063707), _Copy next_ and _Copy previous_, that show a preview of the selected item, I have had these commands for 2 years, but I began to see this problem approximately 1-2 months ago. 

Here is how my Command dialogue looks like:
![copyq-commands](https://user-images.githubusercontent.com/1991183/115955289-4b7c0700-a4fe-11eb-8f91-cdcc6f57faa3.png)

Despite I tried to disable these two commands, there was no effect. Even more, I tried to Reset the configuration do default, but nothing changed.

> Is that tab synchronized with a directory (i.e. it's using the Synchronization plugin)?

No, I haven't

**Comment by hluk** [comment]
You can try to get debug logs: https://copyq.readthedocs.io/en/latest/faq.html#how-to-enable-logging

Even more logs can be enabled with (before launching the app from the same terminal):

```bash
export QT_LOGGING_RULES='*.info=true'
# ...or following which can be very verbose
export QT_LOGGING_RULES='*.debug=true'
```

**Comment by hluk** [comment]
Couple of ideas:
- Disable the preview dock (F7)
- Reset window states and geometries by removing `~/.config/copyq/copyq_geometry.ini`

**Comment by popovserhii** [comment]
Hi @hluk
> Disable the preview dock (F7)
Yes it helps me to overcome the issue, but it's as a temporary solution

> Reset window states and geometries by removing `~/.config/copyq/copyq_geometry.ini`
I haven't this file

**Comment by popovserhii** [comment]
I'm using flatpak. So I run the next commands:
```bash
$ export COPYQ_LOG_LEVEL='DEBUG'
$ flatpak run com.github.hluk.copyq

Gtk-Message: 07:48:06.021: Failed to load module "xapp-gtk3-module"
DEBUG: [default] QtWarning: Qt: Session management error: Could not open network socket
DEBUG: Server "/home/popov/.var/app/com.github.hluk.copyq/config/copyq/.copyq_s" started.
DEBUG: Geometry: Window "MainWindow": Move window: 821, 31
DEBUG: Geometry: Window "MainWindow": Restore geometry "Options/MainWindow_geometry_1920x1080": 645x421,637,312 -> 870x1013,821,31
DEBUG: Focus window is "popov@G7: ~"
DEBUG: Loading configuration
DEBUG: Configuration loaded
DEBUG: Starting monitor
DEBUG: Executing: copyq --clipboard-access monitorClipboard
DEBUG: Starting callback: onStart
DEBUG: Executing: copyq onStart
DEBUG: Executing: Command "Show/hide main window"
DEBUG: Focus window is "popov@G7: ~"
DEBUG: Tab "&clipboard": Loading items
DEBUG: Tab "&clipboard": 738 items loaded
DEBUG: Raising window "CopyQ"
DEBUG: Geometry: Window "MainWindow": Move window: 821, 31
DEBUG: Geometry: Window "MainWindow": Restore geometry "Options/MainWindow_geometry_1920x1080": 870x1013,525,16 -> 870x1013,821,31
DEBUG: Executing: copyq eval -- runDisplayCommands()
DEBUG: Executing: copyq eval -- runMenuCommandFilters()
DEBUG: [default] QtWarning: QXcbClipboard: SelectionRequest too old
DEBUG: [default] QtWarning: QXcbClipboard: SelectionRequest too old
...
DEBUG: Executing: copyq onOwnClipboardChanged
DEBUG: Executing: copyq onOwnClipboardChanged
DEBUG: Saving items on application state change (2)
DEBUG: Focus window is "popov@G7: ~"
DEBUG: Auto-hiding unfocused main window
DEBUG: Geometry: Window "MainWindow": Restore geometry "Options/MainWindow_geometry_1920x1080": 870x1013,525,40 -> 870x1013,821,43
DEBUG: Geometry: Window "LogDialog": Restore geometry "Options/LogDialog_geometry_1920x1080": 585x680,667,183 -> 1091x680,667,183
DEBUG: Focus window is "Log — CopyQ"
DEBUG: Focus window is "Log — CopyQ"
...
DEBUG: Saving items on application state change (2)
DEBUG: Focus window is "Log — CopyQ"
DEBUG: Geometry: Window "LogDialog": Save geometry "Options/LogDialog_geometry_1920x1080": 1091x680,59,211
DEBUG: Focus window is "Log — CopyQ"
DEBUG: Saving items on application state change (2)
DEBUG: Focus window is "popov@G7: ~"
DEBUG: Auto-hiding unfocused main window
DEBUG: Focus window is "popov@G7: ~"
DEBUG: Auto-hiding unfocused main window
DEBUG: Executing: copyq onClipboardChanged
DEBUG: Executing: copyq onClipboardChanged
DEBUG: New item: Adding
DEBUG: Focus window is "FAQ - Frequently Asked Questions — CopyQ documentation — Mozilla Firefox"
DEBUG: Executing: copyq onClipboardUnchanged
DEBUG: Executing: copyq onClipboardUnchanged
DEBUG: Auto-hiding unfocused main window
DEBUG: Executing: copyq onClipboardChanged
DEBUG: Executing: copyq onClipboardChanged
DEBUG: New item: Adding
DEBUG: Executing: copyq onClipboardUnchanged
DEBUG: Executing: copyq onClipboardUnchanged
DEBUG: Focus window is "popov@G7: ~"
DEBUG: Executing: copyq onClipboardChanged
DEBUG: Auto-hiding unfocused main window
DEBUG: Focus window is "popov@G7: ~"
DEBUG: Auto-hiding unfocused main window
DEBUG: Geometry: Window "MainWindow": Restore geometry "Options/MainWindow_geometry_1920x1080": 870x1013,525,40 -> 870x1013,821,43
DEBUG: [default] QtWarning: QXcbClipboard: SelectionRequest too old
...
DEBUG: Executing: copyq onOwnClipboardChanged
DEBUG: Executing: copyq onClipboardUnchanged
DEBUG: Executing: copyq onOwnClipboardChanged
DEBUG: Executing: copyq onClipboardUnchanged
DEBUG: Executing: copyq onClipboardUnchanged
DEBUG: Executing: copyq onOwnClipboardChanged
DEBUG: [default] QtWarning: QXcbClipboard: SelectionRequest too old
DEBUG: Executing: copyq onOwnClipboardChanged
DEBUG: Executing: copyq onOwnClipboardChanged
DEBUG: Executing: copyq onOwnClipboardChanged
DEBUG: [default] QtWarning: QXcbClipboard: SelectionRequest too old
DEBUG: Executing: copyq onClipboardUnchanged
DEBUG: Executing: copyq onClipboardUnchanged
DEBUG: Geometry: Window "LogDialog": Restore geometry "Options/LogDialog_geometry_1920x1080": 585x680,667,183 -> 1091x680,59,211
DEBUG: Focus window is "Log — CopyQ"
DEBUG: Focus window is "Log — CopyQ"
...
DEBUG: Executing: copyq onClipboardChanged
DEBUG: New item: Adding
DEBUG: Executing: copyq onOwnClipboardChanged
DEBUG: [default] QtWarning: QXcbClipboard: SelectionRequest too old
...
DEBUG: Executing: copyq onOwnClipboardChanged
DEBUG: Executing: copyq onClipboardChanged
DEBUG: Executing: copyq onOwnClipboardChanged
DEBUG: Focus window is "Log — CopyQ"
DEBUG: Focus window is "Log — CopyQ"
DEBUG: Focus window is "Log — CopyQ"
DEBUG: Focus window is "Log — CopyQ"
DEBUG: Saving items on application state change (2)
DEBUG: Tab "&clipboard": Saving 741 items
DEBUG: Tab "&clipboard": Items saved
DEBUG: Executing: copyq onClipboardChanged
DEBUG: Executing: copyq onClipboardChanged
DEBUG: New item: Adding
DEBUG: [default] QtWarning: QXcbClipboard: SelectionRequest too old
DEBUG: Executing: copyq onClipboardUnchanged
DEBUG: Executing: copyq onClipboardUnchanged
...
```

**Comment by hluk** [comment]
> > Reset window states and geometries by removing `~/.config/copyq/copyq_geometry.ini`
> 
> I haven't this file

For the flatpak the file is `~/.var/app/com.github.hluk.copyq/config/copyq/copyq_geometry.ini`.

Also, try updating to the newer version (4.1.0 - released few days ago).

**Comment by popovserhii** [comment]
@hluk Sorry for the long response. 
I removed `copyq_geometry.ini`, but It hasn't helped.

![image](https://user-images.githubusercontent.com/1991183/120916497-9fa80880-c6b2-11eb-9911-98d5124b8e1a.png)

**Comment by hluk** [comment]
Can you try changing the indexing so it starts from 0 with command `config row_index_from_one false`? (You can revert it with `config row_index_from_one true`.)

If it does not help try disabling plugins in Preferences dialog in Item tab.

**Comment by popovserhii** [comment]
@hluk, Hi

> `copyq config row_index_from_one false`

This command didn't help.

----
> If it does not help try disabling plugins in Preferences dialog in Item tab.

I go _File - Preferences_ but I don't see anything related to Plugins.
Also, I checked _Item_ (tab), there is no Preferences there.

![image](https://user-images.githubusercontent.com/1991183/121836970-3d1bc180-ccdd-11eb-8e2f-eaa8a96bc289.png)
![image](https://user-images.githubusercontent.com/1991183/121837252-cb904300-ccdd-11eb-8441-4ff4d07172f9.png)
