### ISSUE TITLE
Color contrast on not-simple items

### ISSUE THREAD

**Issue by madprops** [hluk/CopyQ#1645]
I'm using v3.10.0

I've been using simple items but I realized it would be better to see the multiple lines of a clipboard item to be sure of the one I need. So I disabled simple items, and the advanced mode is indeed nice. The problem is that some items simply don't have a good contrast. 

For instance see this image:

![2021-04-26_20-47](https://user-images.githubusercontent.com/206498/116177237-b2e9b080-a6d0-11eb-8810-3c4271a21280.png)

I'm wondering, first if there's an option to have the same kind of advanced items but without the coloring. And if not, if there's a way to avoid the bad contrast. I tried tweaking the theme with the options at the top but I wasn't sure if it made any effect at all.

**Comment by hluk** [comment]
I think it's related to #1464.
