### ISSUE TITLE
Pasting as plain text very rarely works in 4.0.0

### ISSUE THREAD

**Issue by Kzer-Za** [hluk/CopyQ#1648]
```
CopyQ Clipboard Manager v4.0.0
Qt: 5.15.2
KNotifications: 5.81.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Manjaro Linux
```

The problem is specific to version 4.0.0: it appeared after I updated to to version 4.0.0 from 3.13.0. It disappeared after I downgraded back to 3.13.0 without changing anything else.

The issue:

Any action that should result in pasting the item as plain text is executed only sometimes, about one time out of 3--20 tries.

By actions I mean:

1. Pasting with global shortcut: I press the global hotkeys for "Paste as Plain Text" and nothing happens. I have to press them several times and at a random next attempt the text is pasted.
2. Pasting with application shortcut from the CopyQ window: I open CopyQ window, select the item, press the hotkeys, and the CopyQ window gets closed, but the item is not pasted. As far as I can tell, this method never works.
3. Pasting with the context menu from the CopyQ window: I open CopyQ window, right-click the item, and in the context menu I left-click "Paste as Plain Text". There is no reaction to that: the item is not pasted, the window is not closed, and even the context menu remains open. Like with global shortcut, this is observed several times, then on a random next attempt the window is closed and the text is pasted. Actually, with this way there are periods when everything works as it should on each attempt. But then again comes the period of the described behavior.

This behavior does not depend on the exact keys used for a shortcut: I tried assigning different keys.

**Comment by hluk** [comment]
This has been fixed in the new version (4.1.0): #1627
