### ISSUE TITLE
v4.1.0 won't open

### ISSUE THREAD

**Issue by tbird301** [hluk/CopyQ#1649]
Downloaded v 4.1.0.  The system requirements show that OS 10.9 is needed.  When I tried to launch CopyQ I got this message below.   Have the System requirements be updated?

"Check with the developer to make sure CopyQ works with this version of OS X"

**Comment by hluk** [comment]
I think docs are a bit outdated. The minimum macOS version changes mainly with the Qt framework version CopyQ uses.

I'm not entirely sure where to find the supported platforms, maybe: https://doc.qt.io/qt-5/macos.html
