### ISSUE TITLE
Preserve order of copied items on copy or pasting multiple items

### ISSUE THREAD

**Issue by m4r71n** [hluk/CopyQ#165]
1. Copy `a` then `b` and then `c` to clipboard
2. Open main window, select the three items `c`, `b`, and `a` and copy or paste
3. The content is now (3 lines) with `cba` and not `abc`

**Comment by papazonga** [comment]
Hi. Can you provide comand to reverse all data in clipboard? Like this one: https://github.com/hluk/CopyQ/issues/1031#issuecomment-434036500

it would be realy helpfull
