### ISSUE TITLE
CopyQ : Microsoft Defender SmartScreen Alert: "Windows protected your PC."

### ISSUE THREAD

**Issue by Clemens-Ratte-Polle** [hluk/CopyQ#1651]
Wanted to update CopyQ with:
copyq-v4.1.0-setup.exe
But Windows 10 x64 alerts: 
"Windows protected your PC."
Microsoft Defender SmartScreen 

Shall i therefore copy the portable version OVER the old version 3.10.0 ?
thx

**Comment by hluk** [comment]
I don't know what "Windows protected your PC" means. :)

The installer is not signed or anything, but it should be basically the same as the portable zip -- it's just a different format for distributing the app.

**Comment by Clemens-Ratte-Polle** [comment]
it is MS Windows' Antimalware that "protects" my PC.
Solution: Copy portable files over it.
