### ISSUE TITLE
Files being read repetitively

### ISSUE THREAD

**Issue by Gitoffthelawn** [hluk/CopyQ#1654]
**Describe the bug**
I was investigating some performance issues with CopyQ, and noticed something interesting: Every time the user copy text to the clipboard, the following files are read in their entirety:

```
copyq-bak.ini	
qt_en.qm
```

(of course, the second file will be language-dependent)

Also, part of `copyq.exe` is read every time as well.

At least for the first two files mentioned, perhaps reading them on each clipboard copy could be avoided to improve performance.

You can confirm this behaviour using NirSoft's FileActivityWatch (available for free from the author here: https://www.nirsoft.net/utils/file_activity_watch.html).

**Version, OS and Environment**
CopyQ Clipboard Manager v4.1.0
Qt: 5.15.2
KNotifications: 5.81.0
Compiler: MSVC
Arch: x86_64-little_endian-llp64
OS: Windows 7 Version 6.1 (Build 7601: SP 1)

**Comment by hluk** [comment]
Those files are read by a new process which launches automatic commands when clipboard changes.

I believe, at least on Linux this is not an issue because the files are cached (kept in memory by the system).

How much time does it take to read those files?

**Comment by Gitoffthelawn** [comment]
> Those files are read by a new process which launches automatic commands when clipboard changes.

Ah! I learn another new detail! Yea knowledge! :)

> I believe, at least on Linux this is not an issue because the files are cached (kept in memory by the system).

Hmmm... I need to think about how Windows really handles this internally.  Windows caches things too, but like most caches, data will get overwritten in the cache as it fills with new data.  I'm thinking about how I can determine if the file is in a cache, and I'm surprised I don't instantly know the answer.  If you ***or others know***, please jog my memory of how to determine that detail.

> How much time does it take to read those files?

I was looking at a bigger performance issue when I stumbled on this, so I didn't measure.  But given the small size of the files, the amount of time should be under 250ms on reasonable hardware.  Of course, if there are many read/write operations being performed by other processes (or, gasp, the files are located on a network resource), CopyQ's behaviour may slow down both CopyQ and the other processes.  If you then add in the overhead of anti-malware software, the impact will likely be greater.

Overall, if your response was "oops... it shouldn't be doing that", then I would recommend fixing it.  But because it sound like it is "by design", I think it's probably not worth much time looking at it, as there may be nothing you can reasonably do.

BTW, since English is a fairly common language in the computing world, would it be possible to somehow eliminate `qt_en.qm` or include it directly within an executable or library?

**Comment by hluk** [comment]
> Overall, if your response was "oops... it shouldn't be doing that", then I would recommend fixing it.

Unless there is a big performance hit, I'm not fixing this.

Of course, if I can figure out how to make the app start faster with some simpler code refactoring, I would implement the changes. In fact, I occasionally check the performance profile and do minor adjustments where it would help - though I do this only on Linux.

> BTW, since English is a fairly common language in the computing world, would it be possible to somehow eliminate qt_en.qm or include it directly within an executable or library?

This translation file is coming from Qt I believe, and having the translation strings moved to the executable would not solve much (the executable would get bigger).

**Comment by Gitoffthelawn** [comment]
> Unless there is a big performance hit, I'm not fixing this.

I agree.  Not worth the time spent unless you happen to stumble on the fix.

> Of course, if I can figure out how to make the app start faster with some simpler code refactoring...

I find the app starts plenty fast.  Using it can sometimes be slow.  For example, when copying a large amount of text, it's slow to respond (I created an issue for that a while back).  Also, bringing up the `Commands` dialog box and working within it can be a bit slow, but it's not a big deal as you don't tend to do that every day.

> This translation file is coming from Qt I believe, and having the translation strings moved to the executable would not solve much (the executable would get bigger).

I was thinking that it may be good to just do it for English, as the English file is tiny (33 bytes).  Having to re-read it all the time vs. just adding 33 bytes or so to the executable seems like a good tradeoff.  (I agree doing it for all languages would be too much bloat, as they are all much larger than 33 bytes!)

**Comment by hluk** [comment]
I dropped some old code to migrate configuration to portable app. That could help. Dev build is here: https://ci.appveyor.com/project/hluk/copyq/builds/39073622/job/7to6o3vxyddywkd9/artifacts

I don't see any benefit changing the way how Qt/app handles reading the translations files now. It would be nice to postpone reading the translations files when needed but I did not find a good solution for this.

**Comment by Gitoffthelawn** [comment]
@hluk Thanks!
