### ISSUE TITLE
CopyQ window is opening on the wrong KDE Activity

### ISSUE THREAD

**Issue by bmgandre** [hluk/CopyQ#1667]
**Description**
I'm running KDE with multiple [activities](https://docs.kde.org/trunk5/en/plasma-desktop/plasma-desktop/activities-interface.html). On the main _activity_, Copy window shows up correctly either by clicking on the tray icon or by using a global shortcut. But, switching to a secondary _activity_, when I invoke the CopyQ window it shows up on the main _activity_.

**To Reproduce**
1. KDE System Settings > Workspace Behavior > Activities: Create a secondary activity
2. Switch to the secondary activity (Meta+Tab)
3. One of:
   a. Click on the CopyQ icon tray
   b. Invoke CopyQ using a global shortcut
4. The window is not shown on the secondary _activity_
5. Switch back to the main _activity_
6. The window is shown on the primary _activity_

**Expected behavior**
The CopyQ window should show on the current KDE _activity_ 

**Version, OS and Environment**
CopyQ Clipboard Manager v4.1.0
Qt: 5.15.2
KNotifications: 5.81.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Arch Linux

https://user-images.githubusercontent.com/11844640/119243219-239eb400-bb3b-11eb-98e8-1d74ae190d1e.mp4

**Comment by hluk** [comment]
I don't think the app itself can change where it opens in this case. I could not find any functionality for this in Qt GUI framework.

BTW, CopyQ already uses a workaround to [re-open on a visible virtual desktop](https://github.com/hluk/CopyQ/blob/0d4de7c611ded7ae705098edbe0131e3353dc180/src/common/config.cpp#L289).

I don't how KDE activities work.

**Comment by bmgandre** [comment]
It seems that It can be done via KActivities API:

> Most applications that wish to be activity-aware will want to use KActivities::Consumer to keep track of the user's current activity, and KActivities::ResourceInstance to notify the activity manager of resources the user has accessed. -- [KActivities](https://api.kde.org/frameworks/kactivities/html/index.html)

Another way to solve the problem, and it actually solves the problem for me, is to create a _Window Rule_.
![Screenshot_20210523_114427](https://user-images.githubusercontent.com/11844640/119265429-175b3b00-bbbd-11eb-8bb5-9c696bbce103.png)

**Comment by hluk** [comment]
Nice, thanks for sharing the solution. :+1:
