### ISSUE TITLE
My whole clipboard tab got wiped up

### ISSUE THREAD

**Issue by axonasif** [hluk/CopyQ#1670]
**Describe the bug**
As the title says, my main `clipboard` tab is missing all of the items it had.
I am noticing this today morning as I boot into my linux distro.
I have several other tabs too but they are intact.

**Screenshots**
![image](https://user-images.githubusercontent.com/39482679/119292215-c35e5e00-bc71-11eb-8805-ae7ac6f2e72f.png)

**Version, OS and Environment**
```bash
CopyQ Clipboard Manager v4.1.0~focal
Qt: 5.12.8
KNotifications: 5.68.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: KDE neon User Edition 5.21
```

**Additional context**
If I remember correctly, a power cutoff took place but it's nothing unusual for me.
Been using copyq for like a month.

**Comment by hluk** [comment]
Can you share logs (F12 shortcut or `copyq logs`)?

**Comment by axonasif** [comment]
> Can you share logs (F12 shortcut or `copyq logs`)?

[copyq.log](https://github.com/hluk/CopyQ/files/6530578/copyq.log)

**Comment by hluk** [comment]
I don't see any errors or warnings in the log.

Does CopyQ save items to the tab normally again? Usually, if the tab file cannot be loaded (is corrupted or has wrong permissions) the tab would show a lock icon and logs would indicate the error.

If you restart CopyQ are the items restored?

**Comment by axonasif** [comment]
> Does CopyQ save items to the tab normally again? Usually, if the tab file cannot be loaded (is corrupted or has wrong permissions) the tab would show a lock icon and logs would indicate the error.

Yes, it's still working fine.

> If you restart CopyQ are the items restored?

Nope, I tried a bunch of times.

I have started to track `$HOME/.config/copyq/` with `git` now to avoid such data loss again since the reason seems unknown still :laughing:

**Comment by hluk** [comment]
There is handy command that automatically creates backup on exit: https://github.com/hluk/copyq-commands/tree/master/Scripts#backup-on-exit

But no backup will be created if the application crashes or is terminated (with SIGKILL signal). Maybe the command can be improved so it additionally triggers after an interval.

**Comment by axonasif** [comment]
> There is handy command that automatically creates backup on exit: https://github.com/hluk/copyq-commands/tree/master/Scripts#backup-on-exit
> 
> But no backup will be created if the application crashes or is terminated (with SIGKILL signal). Maybe the command can be improved so it additionally triggers after an interval.

O.o thanks!
I was thinking about creating a systemd service to auto commit and push every time I boot in.
Guess I will just modify your referenced command and use copyq `onExit` event to achieve this :smile:

**Comment by hluk** [comment]
> I was thinking about creating a systemd service to auto commit and push every time I boot in.

:+1: Cool. I've updated [the backup command](https://github.com/hluk/copyq-commands/tree/master/Scripts#backup-on-exit) so it can be triggered from command line or script with:

```
copyq backup
```

**Comment by axonasif** [comment]
Hello again @hluk ,
This just happened again but thankfully I had `git` to the rescue this time.
Here is a video of what's happening. It was fine yesterday.
Please let me know if anything else is necessary.

https://user-images.githubusercontent.com/39482679/127324241-a51f8740-0d50-4266-94dd-e5bd8a06749a.mp4

**Comment by hluk** [comment]
@axonasif Interesting. I don't know what could be cleaning the logs from `~/.local/share/copyq` and data files from `~/.config/copyq/`.

Looks like CopyQ cannot exit because `copyq onStart` is still running. Can you check if you redefine the `onStart()` function in any command? (Open Command dialog - F6 shortcut - and enter `onStart` in "Find" field at the bottom of the dialog.)

**Comment by axonasif** [comment]
Just wanted to let you know that I'm no longer facing this issue after updating to the most recent release of copyq. Before my tab would get wiped up after a certain amount of clipboard items.
Thanks ;)
