### ISSUE TITLE
History unload and maximum number of items not working.

### ISSUE THREAD

**Issue by ezxpro** [hluk/CopyQ#1671]
Before creating a new issue, see list of [known
issues](https://copyq.readthedocs.io/en/latest/known-issues.html).

**Describe the bug**
I set a maximum number of items in history and a time limit for the history to unload under preferences > history, but that doesn't work.

**To Reproduce**
1. Right click CopyQ tray icon
2. Go to Preferences > History
3. Set a given a maximum # of items and a time interval for unload
4. Copy as many items as I set in the history (and more)
5. Wait the amount of time I set
6. Check that it neither one of the settings take effect

**Expected behavior**
Upon setting those limits, CopyQ should NOT register any entries past the number I set and it also should clean itself after the time limit I set.

**Version, OS and Environment**
 - CopyQ 4.1.0
 - Windows 10 x64 build 2004

**Comment by hluk** [comment]
The "unload interval" only unloads items from memory, but the data are kept on disk. If you don't want to save items disable "Save Items" option for specific tabs in Tabs configuration.

**Comment by ezxpro** [comment]
@hluk Ah, thanks for the clarification. I'm closing this issue, thanks.
