### ISSUE TITLE
Copying a file to your clipboard using CLI

### ISSUE THREAD

**Issue by archiif** [hluk/CopyQ#1680]
Is there any way to copy a file to your clipboard using the provided path in the command line?
e.g. `copyq copy D:\path\to\file`
Looked over the documentation, but the CLI explanations are very sparse and unclear.

**Comment by hluk** [comment]
Not sure how to do it in Windows, maybe:

```
copyq copy - < D:\path\to\file
```

Similar command is mentioned in the [README](https://github.com/hluk/CopyQ/blob/master/README.md#command-line) file.

**Comment by archiif** [comment]
Yeah but I was looking for a solution without redirection. But I figured it out anyways:
`copyq copy text/uri-list file:///D:/path/to/file`
