### ISSUE TITLE
Export/Import to JSON or other text format

### ISSUE THREAD

**Issue by blorgbeard** [hluk/CopyQ#1700]
**Is your feature request related to a problem? Please describe.**
The current "export" feature only exports to a binary .cpq format. It's useful as a backup tool, but not so much as an export, since the format is binary. I can't easily export, tweak the content, and reimport for example.

The task that prompted this request: I want to generate a large list of pastes, applying several tags to each, and import them into a tab. Doing this manually through the GUI is tedious. I could use a text editor and/or external scripts to generate a JSON file for import. Generating a CopyQ file would be more difficult.

**Describe the solution you'd like**
When exporting, allow me to choose JSON format instead of CopyQ format. When importing, accept (properly formatted) JSON files as well as CopyQ files.

**Comment by hluk** [comment]
This can be done using [Copy and Paste Items in JSON Format](https://github.com/hluk/copyq-commands/tree/master/Application#copy-and-paste-items-in-json-format) (see [README.md](https://github.com/hluk/copyq-commands/blob/master/README.md) for details on how to add the command).

I have no plans to implement the support for other formats in the app itself.

**Comment by jonpatterns** [comment]
How is export in JSON achieved? Also Export as formatted and readable format (such as .odt) would be good.
