### ISSUE TITLE
Sometimes, but not always, when I press alt + tab to switch from one window to another I notice that CopyQ is listed as one of the applications that is currently open

### ISSUE THREAD

**Issue by Raytle** [hluk/CopyQ#1714]
### Is this a known issue?
I did not see an issue similar to this issue in the list of [known issues](https://copyq.readthedocs.io/en/latest/known-issues.html).

### Describe the bug

Previously when I used an older version of CopyQ (I think it was 3.x) I never had the following problem. I just upgraded to CopyQ  v4.1.0~focal. 

Now, sometimes but not always, when I press `alt + tab` to switch from one window to another I notice that CopyQ is listed as one of the applications that is currently open. I don't want to see CopyQ as one of my open applications. Seeing CopyQ as one of my open applications looks like clutter to me. I have `show/hide main menu` bound to a hotkey (F1). When I want to bring CopyQ to the foreground I press F1. 

Here's a screenshot of my preferences...

![Image 1](https://user-images.githubusercontent.com/81956552/125908956-30fa5d02-954d-4d39-a334-342ff11c3bbe.png)

### Version, OS and Environment**
CopyQ Clipboard Manager v4.1.0~focal
Qt: 5.12.8
KNotifications: 5.68.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Lubuntu 20.04.2 LTS

**Comment by hluk** [comment]
I do not have much control over how window managers see the application.

Is the main window just minimized to the panel in desktop environment? This is usually the case if tray icon is disabled or tray is not available. You can force hiding main window instead of minimizing by enabling "Hide main window" option in Layout tab in Preferences.

**Comment by Raytle** [comment]
Your assertions not withstanding, this problem never occurred until immediately after I upgraded CopyQ therefore it is reasonable to presume changes were made to CopyQ that caused this.

I intend to downgrade CopyQ. Then I presume this problem will cease.

**Comment by Raytle** [comment]
I want to thank you again for spending your time to help me out. I appreciate that very much.

I think I just figured out the cause of the problem. In LXQt no option exists to prevent it's panel (task bar) from popping up when it is hidden. I found this annoying because when working on my computer, dozens of times each day I would frequently inadvertently cause the hidden task bar to pop up. Therefore, I recently began running `killall lxqt-panel` from a hotkey to prevent this behavior. When I need the LXQt panel I load it by pressing another hotkey to run `lxqt-panel`. I dislike such kludges but sometimes I find they are necessary.

Nonetheless, another utility I run named [autokey](https://github.com/autokey/autokey) which is buggy and barely actively does not exhibit this behavior. That is, `autokey` does not appear when I press `Alt + Tab` yet `autokey` immediately pops up on my screen when I press the hotkey which I have bound to it.

Personally I don't need nor do I care about the CopyQ icon that appears in the LXQt panel because I don't use it. To use CopyQ I simply press a hotkey to launch CopyQ. Therefore, if there were some way to—for example—remove CopyQ from the LXQt panel to prevent seeing CopyQ when I press `Alt+Tab` I would be glad to know how to do that.

For example—the following is merely a guess—if I could run a command (in a terminal) such as: `copyq --not_shown_in_panel` to prevent such behavior that would be ideal.

**Comment by hluk** [comment]
Is the main window just minimized to the panel in desktop environment?

Did you enable "Hide main window" option?

If the previous version of CopyQ works, please provide `copyq --version` output.

**Comment by Raytle** [comment]
Thanks for replying quickly to me.

As I indicated in https://github.com/hluk/CopyQ/issues/1714#issuecomment-885237998 "I think I just figured out the cause of the problem...."

> Is the main window just minimized to the panel in desktop environment?

I think this is moot (irrelevant) based on https://github.com/hluk/CopyQ/issues/1714#issuecomment-885237998.
 
> Did you enable "Hide main window" option?

I think this is also moot based on https://github.com/hluk/CopyQ/issues/1714#issuecomment-885237998.

> If the previous version of CopyQ works, please provide `copyq --version` output.

Finally, I think this is also moot based on https://github.com/hluk/CopyQ/issues/1714#issuecomment-885237998.*

**Comment by hluk** [comment]
OK, so if I understand correctly, it seems to be some issue with how LXQt handles windows. In such case I am closing this because there is not much I can do about it.

To **clarify** my previous comment: Usually, CopyQ window is hidden and should not show up in Alt+Tab window switcher. One exception is if tray icon is not available. In such case CopyQ window is minimized by default so user can recall the window in some way (it might depend on window manager and desktop environment).

**Comment by Raytle** [comment]
> OK, so if I understand correctly, it seems to be some issue with how LXQt handles windows. 

I am unsure but I believe that assertion is probably **false**.


> In such case I am closing this because there is not much I can do about it.

As you can see, I have reopened this issue.



> To **clarify** my previous comment: Usually, CopyQ window is hidden and should not show up in Alt+Tab window switcher. 

I understood your previous comment and, of course, I understand your reiteration (repeating of that comment).


> One exception is if tray icon is not available. In such case CopyQ window is minimized by default so user can recall the window in some way (it might depend on window manager and desktop environment).

**This seems to be the root of the matter**. 

1. I choose `killall lxqt-panel`.
2. As a result the LXQt panel disappears.
2. I run `CopyQ`.
3. Then I see `CopyQ` when I press `Alt + Tab`.

This feature of `CopyQ` which is designed to allow the user recall the window does **not** help me. I find this feature of `CopyQ` very mildly annoying. Why? Because I have bound `CopyQ` to `F1`, therefore it is trivial for me to recall `CopyQ` whenever I would like. Sure. I know that choosing `killall lxqt-panel` is a kludge (a wonky solution). See,  LXQt is relatively new; therefore unsurprisingly, LXQt lacks some common features that more mature desktop environment's possess.  As I indicated above...

>> In LXQt no option exists to prevent its panel (its task bar) from popping up when it is hidden. I found this annoying because when working on my computer, dozens of times each day I would frequently inadvertently cause the hidden task bar to pop up. Therefore, I recently began running `killall lxqt-panel` from a hotkey to prevent this behavior. When I need the LXQt panel I load it by pressing another hotkey to run `lxqt-panel`.

That's a gross oversight on the part of the LXQt developers because all GUI operating systems I have used previously (on Linux, Windows, and Macintosh) all had an option to keep the task bar hidden unless the user were to press a hotkey to popup the task bar (to display the task bar).

Therefore, because of my kludge—which is my method of preventing the LXQt task bar for popping up inadvertently—I have created an [edge case](https://en.wikipedia.org/wiki/Edge_case). In other words, I have created an extremely unusual problem. 

Nonetheless, is it possible for me to never, ever, under any circumstances whatsoever, see `CopyQ` when I press `Alt + Tab`?

To be sure you understand me, I have included the following screenshot (which I edited with [flameshot](https://github.com/flameshot-org/flameshot))...

![Image 1](https://user-images.githubusercontent.com/81956552/126772848-a173e3b5-0b70-4ee1-852d-36998f82ecc0.png)
