### ISSUE TITLE
add/get without duplicates 

### ISSUE THREAD

**Issue by sl5net** [hluk/CopyQ#1717]
**problem**

i adding items and have duplicates

**Additional context**

i copy all  tab-names to a tab namen tabs every some minutes, because i want all existing tabs into tabs.txt
and add all out of tabs.ext into the tab tabs.

die idear is to habe allways actuall tab-names's in the tab tabs.

https://stackoverflow.com/questions/68412750/copy-all-copyq-tab-names-to-a-tab-namen-tabs

in this way i got more and more duplicates. thats the problem

**Comment by hluk** [comment]
In your specific case, probably the best solution is to use `removeTab` before adding the tabs.

**Comment by jdholtz** [comment]
I have a similar issue to this where I want to use add, but by also removing duplicates. The current command I have in my bash script to do this is:
```bash
echo -n $@ | copyq "copy(input()); copySelection(input()); add(input()); paste();"
```

How can I add this input(), but also not have any duplicates? I've thought about just looping through my entire history every time, but that seems pretty slow to me and may slow down if I get a large history.

**Comment by hluk** [comment]
> How can I add this input(), but also not have any duplicates?

Instead of `add(input())` try using the following:

```js
setData(mimeText, input());
setData(mimeOutputTab, tab()[0]);
saveData();
```

**Comment by jdholtz** [comment]
> Instead of add(input()) try using the following:

That works great, thank you!
