### ISSUE TITLE
Duplicate insert in Chrome

### ISSUE THREAD

**Issue by guettli** [hluk/CopyQ#1722]
**Describe the bug**

In Chrome (Chromium | 92.0.4515.107 (Offizieller Build) snap (64-Bit), Ubuntu 20.04) the insert from the menu gets done twice.

This happens in the old version of copyq (3.10) and in the new (v4.1.0~focal).

**To Reproduce**
1. Copy some text
2. use shortcut to open the copy+paste menu. I use ctrl-alt-v
3. Choose an item. Hit enter
4. Text gets inserted twice into Chrome. Fails for textareas, URL addressbar, ....: 

Example: I copy `v4.1.0~focal` but `v4.1.0~focalv4.1.0~focal` gets inserted.

**Version, OS and Environment**

CopyQ Clipboard Manager v4.1.0~focal
Qt: 5.12.8
KNotifications: 5.68.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Ubuntu 20.04.2 LTS

I use CopyQ since several months and it always worked fine.

**Comment by Gelmo** [comment]
I am also able to reproduce this, on 21.04, with 3.x and 4.x

**Comment by tomoe** [comment]
+1 with CopyQ `v3.13.0` on Chrome: `Version 92.0.4515.107 (Official Build) (64-bit)` on Linux

**Comment by s-surineni** [comment]
I have the same issue 
Chrome: Version 92.0.4515.107 (Official Build) (64-bit)
CopyQ Clipboard Manager v4.1.0~bionic
On Ubuntu

**Comment by hluk** [comment]
I fail to reproduce this, but I'm not using Ubuntu and use Chromium 92.0.4515.107 installed from Flatpak/Flathub.

There are couple of options in CopyQ v4.1.0 changing the paste behavior and basically how Shift+Insert is send to target window (mainly wait times and intervals between key presses).

What could help is setting `window_key_press_time_ms` option to 0 (default is 50 on Linux).

```
copyq config window_key_press_time_ms 0
```

**Comment by panzelva** [comment]
Same issue here - setting `window_key_press_time_ms` did not help.

```
$ copyq --version
CopyQ Clipboard Manager v4.1.0~hirsute
Qt: 5.15.2
KNotifications: 5.80.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Ubuntu 21.04
```

Chrome version: `Version 92.0.4515.107 (Official Build) (64-bit)`

**Comment by sctice** [comment]
@hluk — Is there anything that those of us experiencing this behavior can do to help track down the cause? It seems to be isolated to Chrome, and I believe it started happening relatively recently. I think I first noticed it after upgrading Chrome for the first time in a couple months.

**Comment by sctice** [comment]
It looks like a [Chrome update](https://chromium.googlesource.com/chromium/src/+log/92.0.4515.107..92.0.4515.131?pretty=fuller&n=10000) may have resolved this! Just an uninformed guess after a little searching through the change log, but maybe [this commit](https://chromium.googlesource.com/chromium/src/+/7b7932975668e4d97ad6a3666a8fe9e9bca6e958)?

After updating Chrome to 92.0.4515.131 and re-launching it, I'm no longer seeing the duplicate insert behavior with CopyQ v3.13.0.

**Comment by Gelmo** [comment]
I can confirm that the latest Chrome update has resolved the issue for me, as well.

**Comment by Gelmo** [comment]
@guettli You may want to test and close this

**Comment by guettli** [comment]
Yes, I can confirm. Ubuntu does automatically install the new version, and after restarting chrome the bug is gone.

```
guettli@yoga15:~$ LANG=C snap info chromium
name:      chromium
summary:   Chromium web browser, open-source version of Chrome
publisher: Canonical*
store-url: https://snapcraft.io/chromium
contact:   https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bugs?field.tag=snap
license:   unset
description: |
  An open-source browser project that aims to build a safer, faster, and more stable way for all
  Internet users to experience the web.
commands:
  - chromium.chromedriver
  - chromium
snap-id:      XKEcBqPM06H1Z7zGOdG5fbICuf8NWK5R
tracking:     latest/stable
refresh-date: today at 08:48 CEST
channels:
  latest/stable:    92.0.4515.131 2021-08-04 (1691) 148MB -
  latest/candidate: 92.0.4515.131 2021-08-03 (1691) 148MB -
  latest/beta:      93.0.4577.42  2021-08-13 (1699) 149MB -
  latest/edge:      94.0.4603.0   2021-08-14 (1700) 153MB -
installed:          92.0.4515.131            (1691) 148MB -
```
