### ISSUE TITLE
CopyQ doesn't recognize alternative keyboard layouts, e.g. dvorak 

### ISSUE THREAD

**Issue by whudwl** [hluk/CopyQ#1733]
I'm using dvorak keyboard layout on Mac Big Sur. 
CopyQ version is the latest one as of 2021-08-18. 

After double clicking an item in CopyQ while using the `textedit` application, instead of the item getting pasted into `textedit`, I'm getting the `link description` dialog, which means CopyQ has sent `Command+K` instead of `Command+V` to `textedit`. (on dvorak keyboard, the K key is where the V key is on a QWERTY keyboard).

**Comment by hluk** [comment]
Can you test the behavior with [this development build](https://github.com/hluk/CopyQ/actions/runs/1179051078#artifacts)?

**Comment by whudwl** [comment]
> Can you test the behavior with [this development build](https://github.com/hluk/CopyQ/actions/runs/1179051078#artifacts)?

Will test this later today and report back.

**Comment by whudwl** [comment]
> Can you test the behavior with [this development build](https://github.com/hluk/CopyQ/actions/runs/1179051078#artifacts)?

This version of CopyQ works fine based on my testing. 
Thanks for the hard work
