### ISSUE TITLE
CopyQ : Command Search All Tabs causes Error Exitcode 4 

### ISSUE THREAD

**Issue by Clemens-Ratte-Polle** [hluk/CopyQ#1734]
CopyQ Command "Search All Tabs" causes Error Exitcode: 4.
What should i do?
thx

Search All Tabs Command Source:
https://github.com/hluk/copyq-commands/blob/master/Application/search-all-tabs.ini

**Comment by hluk** [comment]
Can provide the full error from logs (F12 shortcut)?

**Comment by Clemens-Ratte-Polle** [comment]
"It does not exist a tab with given name".

Note [2021-08-29 23:31:39.685] <Server-6024>:    
Note [2021-08-29 23:31:39.685] <Server-6024>:    --- backtrace ---
Note [2021-08-29 23:31:39.685] <Server-6024>:    %entry@eval code:19
Note [2021-08-29 23:31:39.685] <Server-6024>:    eval:// Name for tab for storing m...
Note [2021-08-29 23:31:39.685] <Server-6024>:    eval
Note [2021-08-29 23:31:39.685] <Server-6024>:    --- end backtrace ---
Note [2021-08-29 23:35:33.579] <Server-6024>: Exception in command "Search All Tabs": ScriptError: Es existiert kein Reiter mit dem angegebenen Namen!
Note [2021-08-29 23:35:33.579] <Server-6024>:

**Comment by hluk** [comment]
That has been already fixed in the command (there is new `try { ... } catch` block). Can you try adding it again?
