### ISSUE TITLE
Function to "de-hex" an HREF URL

### ISSUE THREAD

**Issue by cpsyctc2** [hluk/CopyQ#1743]
**Not related to a problem with CopyQ: a problem with some URLs**
I often copy URLs from an HREF link where they have been hex encoded, e.g.
https://doi.org/10.1177%2F25152459211035109
what I wanted there was the DOI which is 10.1177/25152459211035109
I realise it's a niche desire but a function in CopyQ that would "de-hex" that would be brilliant.

**Describe the solution you'd like**
The option to paste a de-hexed copy of an item, typically the latest item in the clipboard buffer in CopyQ.

**Describe alternatives you've considered**
It occurred to me that I might be able to write a shiny appt that would do this for me but I'm really no programmer: 
realistically I can't see me finding time or doing it and it would still be clumsy.

**Additional context**
For what it's worth, desire comes from copying DOIs for papers from web sites so I can paste them into Zotero.
I've suggested to Zotero that they might add de-hexing (they already strip the "https://doi.org/" bit when seeing
something like my example).  However, they don't sound likely to do this and perhaps the wish is there for other
contexts.

TIA, Chris

P.S. CopyQ is one of my favourite programs: has saved me weeks over the years I've been using it: thanks 
yet again.

**Comment by hluk** [comment]
Here is command that would automatically extract the DOI when matching URL is copied to clipboad ([here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)):

```ini
[Command]
Automatic=true
Command="
    copyq:
    var url = str(input());
    var i = url.lastIndexOf('/');
    var doi = decodeURIComponent(url.slice(i + 1));
    copy(doi);
    popup('DOI Copied', doi)

    // don't run other automatic commands and
    // don't add the original URL to CopyQ
    ignore();"
Icon=\xf13d
Input=text/plain
Match=^https://doi.org/.
Name=Copy DOI from URL
```

**Comment by cpsyctc2** [comment]
Brilliant. Sorry to be slow responding.  As ever, I'm impressed and very grateful.
