### ISSUE TITLE
Paste not always works

### ISSUE THREAD

**Issue by RitaSghe** [hluk/CopyQ#1748]
**Describe the bug**
50 percent of the time function paste don't works, but if I open the history I have the string saved .....
I use Ctrl+C or Copy by menù, it is indifferent .....

**Version, OS and Environment**
v3.10.0
Kubuntu 20.04

**Additional context**

**Comment by hluk** [comment]
Please update to the latest version of CopyQ.

**Comment by RitaSghe** [comment]
OK ...
