### ISSUE TITLE
Freeze on Windows 7 while openning Preferences

### ISSUE THREAD

**Issue by Qussayyon** [hluk/CopyQ#1750]
**Describe the bug**
In windows 7:
Any time I try to open Preferences via menu or shortcut the application freezs for around 60-120 seconds.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Application via pressing on tray.
2. Click on File->Preferences 
3. See error: the whole app freeze.

**Expected behaviour**
supposed to show Preferences dialog.

**Screenshots**
[Screenshot](https://user-images.githubusercontent.com/13088819/132308182-9a09babb-0856-4ed2-af9e-563c6cbd49a2.png)

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
```copyq.exe version```
CopyQ Clipboard Manager v4.1.0
Qt: 5.15.2
KNotifications: 5.81.0
Compiler: MSVC
Arch: x86_64-little_endian-llp64
OS: Windows 7 Version 6.1 (Build 7601: SP 1)

**Additional context**

**Comment by hluk** [comment]
Can you share logs (F12 shortcut from the main window)?

**Comment by Qussayyon** [comment]
yes, here you go:

```
ERROR [2021-09-08 21:53:26.394] :    gpg: error opening lockfile '/c/Users/rwd/.gnupg/C:\Users\rwd\AppData\Roaming\copyq\copyq.pub.lock': No such file or directory
ERROR [2021-09-08 21:53:26.394] :    gpg: lockfile disappeared
ERROR [2021-09-08 21:53:26.394] :    gpg: error opening lockfile '/c/Users/rwd/.gnupg/C:\Users\rwd\AppData\Roaming\copyq\copyq.pub.lock': No such file or directory
ERROR [2021-09-08 21:53:26.394] :    gpg: lockfile disappeared
ERROR [2021-09-08 21:53:26.394] :    gpg: error opening lockfile '/c/Users/rwd/.gnupg/C:\Users\rwd\AppData\Roaming\copyq\copyq.pub.lock': No such file or directory
ERROR [2021-09-08 21:53:26.394] :    gpg: lockfile disappeared
ERROR [2021-09-08 21:53:26.394] :    gpg: error opening lockfile '/c/Users/rwd/.gnupg/C:\Users\rwd\AppData\Roaming\copyq\copyq.pub.lock': No such file or directory
ERROR [2021-09-08 21:53:26.394] :    gpg: lockfile disappeared
ERROR [2021-09-08 21:53:26.394] :    gpg: error opening lockfile '/c/Users/rwd/.gnupg/C:\Users\rwd\AppData\Roaming\copyq\copyq.pub.lock': No such file or directory
ERROR [2021-09-08 21:53:26.394] :    gpg: lockfile disappeared
ERROR [2021-09-08 21:53:26.394] :    gpg: error opening lockfile '/c/Users/rwd/.gnupg/C:\Users\rwd\AppData\Roaming\copyq\copyq.pub.lock': No such file or directory
ERROR [2021-09-08 21:53:26.394] :    gpg: lockfile disappeared
ERROR [2021-09-08 21:53:26.394] :    
```

**Comment by hluk** [comment]
Do the errors appear when opening preferences?

Can you also try enabling [debug logging](https://copyq.readthedocs.io/en/latest/faq.html#how-to-enable-logging)?

**Comment by Qussayyon** [comment]
@hluk 
Hi there,
I'm sorry for not sending the debug info.
the issue disappeared after v5.0

kind regards and keep up great works.
