### ISSUE TITLE
No tooltip when hovering over the icon in tray/taskbar.

### ISSUE THREAD

**Issue by RDKRACZ** [hluk/CopyQ#1756]
**To Reproduce**
Hover over the CopyQ icon

**Screenshots**
Tooltips aren't visible on screenshots / can't do a screenshot when tooltip is displayed.

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
CopyQ Clipboard Manager v4.1.0
Qt: 5.15.2
KNotifications: 5.81.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: EndeavourOS
Desktop environment, window manager (if applicable): Cinnamon 5.0.5, Mutter.

**Comment by RDKRACZ** [comment]
Not sure what causes it but now it displays a clipboard content - even tho I have many things copied into CopyQ it wasn't displaying anything before.

**Comment by hluk** [comment]
This is a bug in the tray area (panel) app or Qt.
