### ISSUE TITLE
Linkify not working

### ISSUE THREAD

**Issue by reagle** [hluk/CopyQ#1758]
I ultimately want to create a simple command that automatically removes "mailto:" from addresses such as "mailto:test@example.com" yielding "example.com" for pasting into an email client. 

I thought I'd start with [linkify](https://github.com/hluk/copyq-commands/blob/master/Automatic/linkify.ini) as a template, but I can't get it to work. I have installed it (screenshot) and presume that:

1. when I copy a URL (e.g., http://example.com)
2. I will see it appear at the top of the clipboard (it does)
3. the command will be automatically triggered on match (I don't think it is)
4. then the top of the clipboard will be replaced with a URL with `<a href="http://example.com">http://example.com</a>`
5. which is then available for pasting.

<img width="914" alt="Screen Shot 2021-09-16 at 16 38 53" src="https://user-images.githubusercontent.com/596814/133682840-fc15f8c6-cf1f-4b5a-a90d-29a5f09749ec.png">

CopyQ v4.1.0-g2f223292-v4.1.0 on macOS 11.6 20G165 arm64 (under Rosetta).

**Comment by hluk** [comment]
You don't think that step 3 happens? Can you add `popup("OK")` to the command to test if it's triggered?

You can also inspect item data (specifically `text/html` format) by selecting the item and pressing F4 shortcut.

**Comment by reagle** [comment]
I haven't been able to get the popups to work either...

<img width="1021" alt="Screen Shot 2021-09-20 at 08 57 43" src="https://user-images.githubusercontent.com/596814/134006102-954f0112-578d-4ab3-a30d-58142654ac44.png">

**Comment by reagle** [comment]
Just deleted the last comment because I didn't have the command checked; I enabled and the popup worked.

Okay, and I do see there is a text/html entry, but how do I make that the default think I paste?


<img width="607" alt="Screen Shot 2021-09-20 at 09 01 19" src="https://user-images.githubusercontent.com/596814/134006579-92859558-348c-4053-9920-3d35f9a2a740.png">

**Comment by hluk** [comment]
> Okay, and I do see there is a text/html entry, but how do I make that the default thing I paste?

Adding the following code at the end of the script should do the job:

```js
copy(mimeText, url, mimeHtml, html)
```

**Comment by reagle** [comment]
Okay, I've installed the monospace dev version from the other issue, and tried this again. The popup is working, and I added the copy command but it doesn't seem to be having an effect. I'm starting with linkify, but I want to copy something, and have a transformed version be pasted on ctrl/cmd-v.

**Comment by hluk** [comment]
Can you check if clipboard contains correct `text/html` data (select File - Show Clipboard Content from menu bar)? Maybe target app expects different html format.

**Comment by reagle** [comment]
Yes, the text/html does look correct in the Content pane. I'm pasting into Sublime Text 4 and am expecting to see the actual content of the text/html content pane in the text editor. However, your last comment makes me suspect that the transformed paste will only work if I'm pasting into a rich-text type editor? If so, I suppose I want the linkify recipe to paste the transformed text as simple text/plain...?
