### ISSUE TITLE
Linux: After selecting text to drag, after you let go, it still wants to drag.

### ISSUE THREAD

**Issue by DUOLabs333** [hluk/CopyQ#1761]
I'm on the latest version, with Arch. I have the problem where, if I want to eg., drag item 1 to the search bar on Chrome, then I let go, when I go back to CopyQ and hover over item 1, it still shows the dragging UI (with the little preview rectangle next to the cursor). The only way to solve this is double-clicking on the item. Maybe there should be a way to disable dragging?

**Comment by hluk** [comment]
I think this is similar to #1692. I don't think I can do anything about this in the app if there are missing input events (either bug in Qt or window manager).
