### ISSUE TITLE
Regular expression searches

### ISSUE THREAD

**Issue by mdentremont** [hluk/CopyQ#1763]
I was trying to search for an order number in my clipboard this morning, and I tried "^R" but nothing matched - searching R leads to loads of noise matches.

It would be nice if we could do something like `\r^R` or `/^R/` to search using a regex, that could be very powerful!

**Comment by hluk** [comment]
This is already supported. You can select "Regular Expression" option by clicking on the magnifying glass icon in the search field.

![image](https://user-images.githubusercontent.com/38054/135741699-b57f74c7-f457-4bd8-88e1-ebc50c49087e.png)
