### ISSUE TITLE
Could you please release a version?

### ISSUE THREAD

**Issue by r-darwish** [hluk/CopyQ#1764]
It's been a while since the last version has been released, and since then important fixes for MacOS and Windows were commited to the main branch. Could you please release a new version of CopyQ?

**Comment by hluk** [comment]
Unfortunately, even though I planned if for a while, I did not have time to make a new release recently. Releasing an application on multiple platforms is not a simple process.

Let me try to make a release today or this week.

**Comment by hluk** [comment]
I've just released [version 5.0.0](https://github.com/hluk/CopyQ/releases/tag/v5.0.0)!
