### ISSUE TITLE
How to remove trailing and leading whitespaces?

### ISSUE THREAD

**Issue by ixarls** [hluk/CopyQ#1775]
What is the command for removing trailing and leading whitespaces from (rich) text?

**Comment by hluk** [comment]
This can be done with a command depending on how do you expect this to work and where you want to remove the whitespace (clipboard, selected text in an editor or stored items). Some templates for text modification are here: https://github.com/hluk/copyq-commands/tree/master/Templates

**Comment by hluk** [comment]
The following command removes whitespace automatically from plain text in clipboard ([here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)):

```ini
[Command]
Automatic=true
Command="
    copyq:
    var text = str(input())
    var newText = text.trim()
    if (newText != text) {
        copy(newText)
        setData(mimeText, text)
        removeData(mimeHtml)
    }"
Icon=\xf0c4
Input=text/plain
Match=^\\s+|\\s+$
Name=Trim Whitespace
```

But removing spaces from rich text (HTML) is be much more complex.

**Comment by hluk** [comment]
> The only issue is: this command won't let you copy multiple files. It copies filenames instead.

I don't understand. Can you explain in more detail?

**Comment by hluk** [comment]
> > if text/uri-list is included:
> 
> How do i do this?

Replace the previosly added command "Trim Whitespaces" in Command dialog with the new one I posted in my last comment.

**Comment by c02y** [comment]
Any update? I am annoyed for quite some time when I try to copy/paste plain text but it contains leading/trailing whitespace/line.

**Comment by hluk** [comment]
Do you use [the first command](https://github.com/hluk/CopyQ/issues/1775#issuecomment-939411101)?

What are formats and content in the system clipboard (there should be "text/plain" with the text)? You can inspect it from CopyQ by selecting "Show Clipboard Content" from File menu (Ctrl+Shift+C).

**Comment by c02y** [comment]
@hluk Tried both of the two code snippets, neither of them works.

It's `"text/plain"` from `Show Content...`, I can simply copy the one paragraph and the spaces before the first word of the the next paragraph, it always contains the empty blank line in the clipboard.

**Comment by hluk** [comment]
Not sure what could be the problem. If you are on Linux, you may also need `copySelection(newText)` (after `copy(newText)`).

**Comment by c02y** [comment]
I'm on Linux, sorry, it doesn't work.

**Comment by hluk** [comment]
My bad, the `hasData(mimeUriList)` does not work, because `hasData()` function does not take any arguments (I did this mistake before - I need to change the API).

The command should be:

```ini
[Command]
Automatic=true
Command="
    copyq:
    if ( dataFormats().indexOf(mimeUriList) != -1 )
        abort()

    var text = str(input())
    var newText = text.trim()
    if (newText != text) {
        copy(newText)
        setData(mimeText, newText)
        removeData(mimeHtml)
    }"
Icon=\xf0c4
Input=text/plain
Match=^\\s+|\\s+$
Name=Trim Whitespace
```

**EDIT:** Fixed the command above. Thanks, @hedgieinsocks!

**Comment by c02y** [comment]
> My bad, the `hasData(mimeUriList)` does not work, because `hasData()` function does not take any arguments (I did this mistake before - I need to change the API).
> 
> The command should be:
> 
> [Command]
> Automatic=true
> Command="
>     copyq:
>     if ( dataFormats().indexOf(mimeUriList) != -1 )
>         abort()
> 
>     var text = str(input())
>     var newText = text.trim()
>     if (newText != text) {
>         copy(newText)
>         setData(mimeText, text)
>         removeData(mimeHtml)
>     }"
> Icon=\xf0c4
> Input=text/plain
> Match=^\\s+|\\s+$
> Name=Trim Whitespace

Not work.

**Comment by hedgieinsocks** [comment]
It works for me, but it does not edit/trim the original text in the history. Is there a way to trim it in place for good?

Update: Ah, got it!

```
setData(mimeText, text) => setData(mimeText, newText)
```

**Comment by c02y** [comment]
> It works for me, but it does not edit/trim the original text in the history. Is there a way to trim it in place for good?
> 
> Update: Ah, got it!
> 
> ```
> setData(mimeText, text) => setData(mimeText, newText)
> ```

Thanks, it works.

**Comment by H5820121** [comment]
@hluk 
The problem with this script is that when there is a space and the script is run, it deletes the item that was copied before it from the history, and the new item goes into the history instead of the item that was copied before it.
Is there any way to solve this?
