### ISSUE TITLE
How can I copy many pieces of data and paste them one by one in order by command+V, and the pasted data will be deleted automatically?

### ISSUE THREAD

**Issue by banduoba** [hluk/CopyQ#1776]
**Is your feature request related to a problem? Please describe.**
When I have a batch of data, and need to query the information one by one, you need to copy one by one, and then paste one by one, the process needs to be repeated several times. So I would like to have a program that can copy multiple pieces of data at once and automatically paste one piece of information in the order it was copied each time by using the shortcut command+V.

**Describe the solution you'd like**

I want to be able to copy multiple pieces of data at once, and paste one piece of data at a time in order by using custom shortcuts.

**Describe alternatives you've considered**
Currently in use a tool named [paste queue](https://apps.apple.com/us/app/paste-queue-multi-clipboard/id1380017883?mt=12), can achieve similar functions, the shortcomings of this function is not synchronized in the local area network clipboard use, but also does not support the sharing of copied information through the network.

**Additional context**

**Comment by hluk** [comment]
Perhaps the command in #597 can help.
