### ISSUE TITLE
Change icon

### ISSUE THREAD

**Issue by alabotski** [hluk/CopyQ#1786]
Hi I use dark theme on my mac
Can you add support change icon in statusbar?

It will be good if you would add white icon CopyQ...

<img width="550" alt="Screenshot at Oct 20 09-22-30" src="https://user-images.githubusercontent.com/439337/138039289-c7e0a161-ddd1-40f3-8dfb-168dd65d5891.png">

**Comment by alabotski** [comment]
@hluk can you give example? I cannot configure on Mac =(

**Comment by hluk** [comment]
So alternatively, you can add the following command to CopyQ ([here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)):

```ini
[Command]
Command="
    var onStart_ = onStart;
    global.onStart = function() {
        iconColor('white');
        onStart_();
    }"
Icon=\xf0c4
IsScript=true
Name=Monochrome Tray Icon
```

**Comment by alabotski** [comment]
@hluk Thank you =)
