### ISSUE TITLE
Copy and paste suddenly doesn't work. 

### ISSUE THREAD

**Issue by elicec** [hluk/CopyQ#1791]
Copy and paste suddenly doesn't work. I'm in the process manager of copyq. You turn off the monitoring process, and it takes 30 seconds to return to normal.

The log is below

Warning [2021-10-27 11:06:25.124] <monitorClipboard-10608>: ELAPSED 843 ms acessing "UTF8:text/plain"
Warning [2021-10-27 11:06:32.566] <monitorClipboard-10608>: ELAPSED 4101 ms acessing "text/plain"
Warning [2021-10-27 11:06:32.636] <monitorClipboard-10608>: ELAPSED 4296 ms acessing "UTF8:text/plain"
Warning [2021-10-27 11:06:32.725] <monitorClipboard-10608>: Clipboard data expired, refusing to access old data
ERROR [2021-10-27 11:06:34.268] <Server-16900>: [] QtCritical: OleSetClipboard: Failed to set mime data (application/x-copyq-tags, application/x-copyq-user-copy-time, text/plain, application/x-copyq-owner) on clipboard: COM error 0xffffffff800401d0  (Unknown error 0x0800401d0) (参数错误。)
Warning [2021-10-27 11:06:35.592] <monitorClipboard-10608>: ELAPSED 561 ms acessing "text"
Warning [2021-10-27 11:06:35.714] <monitorClipboard-10608>: ELAPSED 870 ms acessing "UTF8:text/plain"
Warning [2021-10-27 11:06:41.064] <monitorClipboard-10608>: ELAPSED 3946 ms acessing "imageData"
Warning [2021-10-27 11:06:43.933] <monitorClipboard-10608>: ELAPSED 562 ms acessing "text"
Warning [2021-10-27 11:06:44.035] <monitorClipboard-10608>: ELAPSED 852 ms acessing "UTF8:text/plain"
Warning [2021-10-27 11:06:49.388] <monitorClipboard-10608>: ELAPSED 3927 ms acessing "imageData"
Warning [2021-10-27 11:06:52.257] <monitorClipboard-10608>: ELAPSED 562 ms acessing "text"
Warning [2021-10-27 11:06:52.346] <monitorClipboard-10608>: ELAPSED 839 ms acessing "UTF8:text/plain"
Warning [2021-10-27 11:06:57.685] <monitorClipboard-10608>: ELAPSED 3930 ms acessing "imageData"
Warning [2021-10-27 11:07:00.573] <monitorClipboard-10608>: ELAPSED 562 ms acessing "text"
Warning [2021-10-27 11:07:00.680] <monitorClipboard-10608>: ELAPSED 857 ms acessing "UTF8:text/plain"
Warning [2021-10-27 11:07:04.643] <monitorClipboard-10608>: ELAPSED 560 ms acessing "text"
Warning [2021-10-27 11:07:04.736] <monitorClipboard-10608>: ELAPSED 840 ms acessing "UTF8:text/plain"
ERROR [2021-10-27 11:07:05.346] <Server-16900>: [] QtCritical: OleSetClipboard: Failed to set mime data (text/plain, text/html, application/vnd.oasis.opendocument.text) on clipboard: COM error 0xffffffff800401d0  (Unknown error 0x0800401d0) (参数错误。)
ERROR [2021-10-27 11:07:05.767] <Server-16900>: [] QtCritical: OleSetClipboard: Failed to set mime data (text/plain, text/html, application/vnd.oasis.opendocument.text) on clipboard: COM error 0xffffffff800401d0  (Unknown error 0x0800401d0) (参数错误。)
ERROR [2021-10-27 11:07:06.204] <Server-16900>: [] QtCritical: OleSetClipboard: Failed to set mime data (text/plain, text/html, application/vnd.oasis.opendocument.text) on clipboard: COM error 0xffffffff800401d0  (Unknown error 0x0800401d0) (参数错误。)
Warning [2021-10-27 11:07:09.120] <monitorClipboard-10608>: ELAPSED 561 ms acessing "text"
Warning [2021-10-27 11:07:09.202] <monitorClipboard-10608>: ELAPSED 832 ms acessing "UTF8:text/plain"
Warning [2021-10-27 11:07:14.515] <monitorClipboard-10608>: ELAPSED 3929 ms acessing "imageData"
Warning [2021-10-27 11:07:17.431] <monitorClipboard-10608>: ELAPSED 561 ms acessing "text"
Warning [2021-10-27 11:07:17.493] <monitorClipboard-10608>: ELAPSED 811 ms acessing "UTF8:text/plain"
Warning [2021-10-27 11:07:22.807] <monitorClipboard-10608>: ELAPSED 3940 ms acessing "imageData"
ERROR [2021-10-27 11:07:25.556] <Server-16900>: [] QtCritical: OleSetClipboard: Failed to set mime data (application/x-copyq-tags, application/x-copyq-user-copy-time, text/plain, application/x-copyq-owner) on clipboard: COM error 0xffffffff800401d0  (Unknown error 0x0800401d0) (参数错误。)
Warning [2021-10-27 11:07:25.556] <monitorClipboard-10608>: ELAPSED 562 ms acessing "text"
Warning [2021-10-27 11:07:25.805] <monitorClipboard-10608>: ELAPSED 999 ms acessing "UTF8:text/plain"
Warning [2021-10-27 11:07:31.185] <monitorClipboard-10608>: ELAPSED 3931 ms acessing "imageData"
Warning [2021-10-27 11:07:34.117] <monitorClipboard-10608>: ELAPSED 577 ms acessing "text"
Warning [2021-10-27 11:07:34.205] <monitorClipboard-10608>: ELAPSED 852 ms acessing "UTF8:text/plain"
Warning [2021-10-27 11:07:39.352] <monitorClipboard-10608>: ELAPSED 3938 ms acessing "imageData"
Warning [2021-10-27 11:07:42.222] <monitorClipboard-10608>: ELAPSED 576 ms acessing "text"
Warning [2021-10-27 11:07:42.316] <monitorClipboard-10608>: ELAPSED 858 ms acessing "UTF8:text/plain"
Warning [2021-10-27 11:07:47.460] <monitorClipboard-10608>: ELAPSED 3940 ms acessing "imageData"
Warning [2021-10-27 11:07:50.348] <monitorClipboard-10608>: ELAPSED 562 ms acessing "text"
Warning [2021-10-27 11:07:50.428] <monitorClipboard-10608>: ELAPSED 829 ms acessing "UTF8:text/plain"
Warning [2021-10-27 11:07:55.560] <monitorClipboard-10608>: ELAPSED 3930 ms acessing "imageData"
Note [2021-10-27 11:08:00.929] <Server-16900>: 命令 “copyq --clipboard-access monitorClipboard”
Note [2021-10-27 11:08:00.929] <Server-16900>:    错误：Process crashed
Note [2021-10-27 11:08:00.929] <Server-16900>:    1. copyq --clipboard-access monitorClipboard
Warning [2021-10-27 11:08:04.180] <monitorClipboard-28664>: ELAPSED 561 ms acessing "text"
Warning [2021-10-27 11:08:04.284] <monitorClipboard-28664>: ELAPSED 851 ms acessing "UTF8:text/plain"
Warning [2021-10-27 11:08:09.621] <monitorClipboard-28664>: ELAPSED 3942 ms acessing "imageData"
Warning [2021-10-27 11:08:09.709] <monitorClipboard-28664>: Clipboard data expired, refusing to access old data
Warning [2021-10-27 11:08:09.797] <monitorClipboard-28664>: ELAPSED 8237 ms acessing "UTF8:image/svg+xml"
Warning [2021-10-27 11:08:12.506] <monitorClipboard-28664>: ELAPSED 562 ms acessing "text"
Warning [2021-10-27 11:08:12.587] <monitorClipboard-28664>: ELAPSED 831 ms acessing "UTF8:text/plain"
ERROR [2021-10-27 11:08:17.465] <Server-16900>: [] QtCritical: OleSetClipboard: Failed to set mime data (application/x-copyq-tags, application/x-copyq-user-copy-time, text/plain, application/x-copyq-owner) on clipboard: COM error 0xffffffff800401d0  (Unknown error 0x0800401d0) (参数错误。)
Warning [2021-10-27 11:08:17.916] <monitorClipboard-28664>: ELAPSED 3928 ms acessing "imageData"
Warning [2021-10-27 11:08:20.859] <monitorClipboard-28664>: ELAPSED 559 ms acessing "text"
Warning [2021-10-27 11:08:20.954] <monitorClipboard-28664>: ELAPSED 841 ms acessing "UTF8:text/plain"
Warning [2021-10-27 11:08:26.411] <monitorClipboard-28664>: ELAPSED 4095 ms acessing "text/plain"
Warning [2021-10-27 11:08:26.510] <monitorClipboard-28664>: ELAPSED 4194 ms acessing "UTF8:text/plain"
Warning [2021-10-27 11:08:27.347] <monitorClipboard-28664>: Clipboard data expired, refusing to access old data
Warning [2021-10-27 11:08:30.248] <monitorClipboard-28664>: ELAPSED 562 ms acessing "text"
Warning [2021-10-27 11:08:30.343] <monitorClipboard-28664>: ELAPSED 860 ms acessing "UTF8:text/plain"
Warning [2021-10-27 11:08:35.692] <monitorClipboard-28664>: ELAPSED 3947 ms acessing "imageData"
Warning [2021-10-27 11:08:38.577] <monitorClipboard-28664>: ELAPSED 561 ms acessing "text"
Warning [2021-10-27 11:08:38.666] <monitorClipboard-28664>: ELAPSED 839 ms acessing "UTF8:text/plain"

**Comment by elicec** [comment]
ok i will  try.thank your time-------- 原始邮件 --------发件人： Lukas Holecek ***@***.***>日期： 2021年10月29日周五 21:18收件人： hluk/CopyQ ***@***.***>抄送： elicec ***@***.***>, Author ***@***.***>主    题： Re: [hluk/CopyQ] Copy and paste suddenly doesn't work.  (Issue #1791)
It might be cause some other application that currently provides clipboard (perhaps a large data).
You can try disabling Image plugin in CopyQ to see if that helps. You can do that using following steps:
Go to preferences - Ctrl+P.Open Items tab.Uncheck "Images" in the list.Click OK.

**Comment by elicec** [comment]
I think this is caused by the operating system, because I have the same problem with using ditto, so I started using CopyQ. 
Unexpectedly, the problem of using CopyQ still exists.

**Comment by hluk** [comment]
Related issues in Qt:
- https://bugreports.qt.io/browse/QTBUG-68493
- https://bugreports.qt.io/browse/QTBUG-27097

Both should be fixed in the Qt version bundled with CopyQ 5.0.0.

Not sure why it is still an issue. I guess some application is blocking clipboard access.

**Comment by elicec** [comment]
> Related issues in Qt:
> - https://bugreports.qt.io/browse/QTBUG-68493
> - https://bugreports.qt.io/browse/QTBUG-27097
> 
> Both should be fixed in the Qt version bundled with CopyQ 5.0.0.
> 
> Not sure why it is still an issue. I guess some application is blocking clipboard access.


You mean ditto was also developed using qt? If so, it would explain.
