### ISSUE TITLE
Installs in the 32 bit 'Program Files (x86)' directory

### ISSUE THREAD

**Issue by Shakil-Shahadat** [hluk/CopyQ#1792]
'Windows: Builds are now 64bit' from 'https://github.com/hluk/CopyQ/releases/tag/v4.0.0' but installs to 'C:\Program Files (x86)\CopyQ' by default. Not a major issue but it is a bit confusing.

**Comment by hluk** [comment]
It seems Inno Setup cannot figure by itself if the installed app is 64bit even though all bundled dlls and exe are 64bit.

**Comment by hluk** [comment]
Any chance you can **test** this with [new development build](https://ci.appveyor.com/project/hluk/copyq/builds/41343728/job/rijpou7rtp1c554v/artifacts)? Specifically, I would like to know **if the old installation directory will be removed** completely because there were issues in past with old dlls not being removed after an update.

**Comment by Shakil-Shahadat** [comment]
I have tested the build you referred. It installs in the correct directory but doesn't remove the older directory.

**Comment by hluk** [comment]
> I have tested the build you referred. It installs in the correct directory but doesn't remove the older directory.

Was anything removed from the old directory by the new installer?

Or maybe it's treated as a different app. Can you find duplicate entries to uninstall CopyQ in Windows?

**Comment by Shakil-Shahadat** [comment]
> Was anything removed from the old directory by the new installer?

Nothing was removed from the old directory by the new installer.

**Comment by Shakil-Shahadat** [comment]
> Can you find duplicate entries to uninstall CopyQ in Windows?

Yes.

![image](https://user-images.githubusercontent.com/8978625/139609001-038f287e-6304-408e-bca8-9bdd6dad372e.png)

**Comment by hluk** [comment]
Not sure if it is OK to just ignore the old installation or somehow notify user about this. User would need to remove it manually.

**Comment by Shakil-Shahadat** [comment]
The new installer is supposed to call the old uninstaller but somehow fails to do so, that's how every other installer works. I think asking the user to manually remove it would be the worst-case scenario. I'm pretty sure you will find a solution if you give some thought to it.

**Comment by hluk** [comment]
> The new installer is supposed to call the old uninstaller but somehow fails to do so, that's how every other installer works. I think asking the user to manually remove it would be the worst-case scenario. I'm pretty sure you will find a solution if you give some thought to it.

Sorry, I don't have a solution for this. I don't think Inno Setup supports this use case (i.e. uninstalling old version with different architecture).

See also: https://stackoverflow.com/questions/22533348/inno-setup-changing-from-32bit-to-64bit-how-to-move-delete-unregister-old-fil

**Comment by Shakil-Shahadat** [comment]
The comments in the link you shared suggested running the uninstaller. Inno Setup supports silent uninstallation without removing user settings. Besides, the question is more than 7 years old.

I'm thinking of learning to write Inno Setup script and maybe make a post in the Inno Setup [forum](https://groups.google.com/g/innosetup?pli=1) to help you solve this issue.

**Comment by Shakil-Shahadat** [comment]
The script in the first answer should work https://stackoverflow.com/questions/2000296/inno-setup-how-to-automatically-uninstall-previous-installed-version

**Comment by hluk** [comment]
> The script in the first answer should work https://stackoverflow.com/questions/2000296/inno-setup-how-to-automatically-uninstall-previous-installed-version

I'm not sure if that would work or if it's safe (after reading the comments). It might not work because 64bit version would use different registry key - mentioned here: https://jrsoftware.org/ishelp/index.php?topic=32vs64bitinstalls

I would rather avoid doing anything special during installation unless it's supported by Inno Setup.

**Comment by Shakil-Shahadat** [comment]
CopyQ 6.0.0 still installs in the 'C:\Program Files (x86)\CopyQ' whether installed on top of an older version or freshly installed.
