### ISSUE TITLE
Installer can't close copyq instance

### ISSUE THREAD

**Issue by Shakil-Shahadat** [hluk/CopyQ#1793]
While upgrading/uninstalling, the installer can't close copyq instance automatically on Windows. In case of uninstallation, it just leaves most of the files in the installation folder.

**Comment by hluk** [comment]
> While upgrading/uninstalling, the installer can't close copyq instance automatically on Windows.

This feature has been dropped due to some bug in Inno Setup or Qt: https://github.com/hluk/CopyQ/commit/1ed18f6fc99d5cde2680363f0ca3f0ec69afe078

I could try enabling it again.

> In case of uninstallation, it just leaves most of the files in the installation folder.

Can you list the files that were not uninstalled?

**Comment by hluk** [comment]
Can you test if the new installer [here](https://ci.appveyor.com/project/hluk/copyq/builds/41350336/job/hsqtn7il01gl86ot/artifacts) closes the app? I cannot test it properly but I think it still won't work.

**Comment by Shakil-Shahadat** [comment]
Sure I'll test and let you know the result. Just me couple of hours.

**Comment by hluk** [comment]
> Can you test if the new installer [here](https://ci.appveyor.com/project/hluk/copyq/builds/41350336/job/hsqtn7il01gl86ot/artifacts) closes the app? I cannot test it properly but I think it still won't work.

I just tested it in Windows 10 (in VM) and the new installer is also unable to close the app, but I managed to get it working with the configuration I used previously - the bug **now seems to be fixed** either in Qt or Inno Setup. I will fix it in the next app release.

**Comment by Shakil-Shahadat** [comment]
'copyq-5.0.0.51-setup.exe' tries to close the app but fails.
