### ISSUE TITLE
Unable to set the window size for the popup window for list in i3wm

### ISSUE THREAD

**Issue by c02y** [hluk/CopyQ#1798]
**Is your feature request related to a problem? Please describe.**
I use a key binding to `Show main window under mouse cursor` which lists all the history. But I'm using i3 wm, `xprop _NET_WM_WINDOW_TYPE` for the `Preference` window of CopyQ is `dialog`, so I manage to set window size for this window, but the window type for the `Show main window under mouse cursor`  is `normal`, I cannot set the window size for this specific window, if I set `WM_CLASS="copyq"` as a floating window, I have default window size for the floating window which is too big for the Copyq history window.

**Describe the solution you'd like**

Would you please to set the window type (`xprop _NET_WM_WINDOW_TYPE`) for the specific `Show main window under mouse cursor`  window? According to the i3wm userguide webpage, the available values are `normal, dialog, utility, toolbar, splash, menu, dropdown_menu, popup_menu, tooltip and notification.` You can pick one such as `dropdown_menu` or `popup_menu`. Thank you.

**Describe alternatives you've considered**

**Additional context**

**Comment by hluk** [comment]
I'm not sure if I understand the issue. What does window type have to do with the size?

Could it be related to https://github.com/hluk/CopyQ/issues/1595#issuecomment-958774791?

BTW, I do not set X window properties - that is handled by Qt framework.

**Comment by c02y** [comment]
My configuration is:
```
for_window [class="copyq"] floating enable
for_window [window_type="dialog"] resize set 35 ppt 40 ppt, move position center
```
The window type for the `Show main window under mouse cursor` (AKA list popup window) window is `_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL` which is like most programs, the preference window is `_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DIALOG, _NET_WM_WINDOW_TYPE_NORMAL`, 

You see, the preference window type is `dialog` but the list popup window is `normal`, so I failed to control the window size of the list popup window, and the size of if is big.

An easy way to do this is to make the window type of list popup window the same as the preference window.

Qt framework handle setting X window properties, you call Qt API.

There is a function called `setWindowFlag()` in `https://github.com/hluk/CopyQ/blob/master/src/gui/mainwindow.cpp`, this is the function to set the `Qt::WindowType` which is listed in https://doc.qt.io/archives/qtjambi-4.5.2_01/com/trolltech/qt/core/Qt.WindowType.html

I see you set `Qt::Tool` and `Qt::WindowStaysOnTopHint`, I didn't dig into the Qt or CopyQ code, but I'm guessing when I'm using `xprop _NET_WM_WINDOW_TYPE` for list popup window and preference window, one is `normal` window type, and one is `dialog` window type, all you need to do is set them the same so the windows are both dialog windows.

**Comment by hluk** [comment]
Window flag **Qt::Tool** is set only when you use the following command in case you want to hide the main window in panel/task-bar:

```bash
copyq config hide_main_window_in_task_bar true
````

From the documentation (https://doc.qt.io/qt-5/qt.html#WindowType-enum) I see that it would also set **Qt:Dialog** flag on the window. Can you **try using the command** and **restarting** the app?

Otherwise, I would be really careful changing the default flags because they affect the behavior in unexpected ways and also depend on interpretation by various window managers and OSes.

**Comment by c02y** [comment]
It seems now the list popup window type is now:
```
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_UTILITY, _NET_WM_WINDOW_TYPE_NORMAL
```

And I can set 
```
for_window [window_type="utility"] resize set 35 ppt 80 ppt, move right 50ppt
```

It works great, thank you.
