### ISSUE TITLE
When clipboard storing is disabled, change the tray icon color (e.g. to red or orange) for easier/faster identification

### ISSUE THREAD

**Issue by carloscadux** [hluk/CopyQ#1800]
**Is your feature request related to a problem? Please describe.**
=>Currently, when clipboard storing is disabled CopyQ tray icon becomes greyed out.
Nonetheless, in my daily use, I need to really focus my sight to confirm the icon is greyed out.

**Describe the solution you'd like**
=> Change the tray icon color from green to red, orange or any color that contrasts green (screenshot attached) when clipboard is disabled.
If the tray icon had a different color (instead of just the greyed out shade), I think that glance I'd realize immediately the clipboard is disabled.

![CopyQ EPnZSL](https://user-images.githubusercontent.com/7339389/139735962-ce6c4319-9976-49a0-a999-d3278f32584c.png)

**Comment by hluk** [comment]
Icon colors are reserved for different app sessions.

But if you need this, you can create custom command (though the icon transparency will still change; [here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)):

```ini
[Command]
Command="
    copyq:
    var disabledColor = 'orange';
    var enabledColor = '';

    if (monitoring()) {
        disable();
        iconColor(disabledColor);
    } else {
        enable();
        iconColor(enabledColor);
    }"
Icon=\xf205
InMenu=true
Name=Disable/Enable
Shortcut=ctrl+shift+x
```

**Comment by carloscadux** [comment]
Thanks for sharing the command @hluk 
What incredible flexibility CopyQ commands provides!
