### ISSUE TITLE
Snap package installs version 3.13 and not 5.X

### ISSUE THREAD

**Issue by 1oglop1** [hluk/CopyQ#1804]
**Describe the bug**
I opened the ubuntu software center and found out that CopyQ version was 3.13.

**Expected behavior**
I expected the latest version to be present.

**Screenshots**
![image](https://user-images.githubusercontent.com/7480694/140318947-214a9f25-cc9d-4d80-8594-5a83a3d7b69c.png)
The `updated` field - means when the software was last installed. 

**Version, OS and Environment**
- ubuntu 21.10

**Comment by hluk** [comment]
I don't maintain the snap package. But there is up-to-date Flatpak version of the app: https://copyq.readthedocs.io/en/latest/installation.html
