### ISSUE TITLE
moving item regression

### ISSUE THREAD

**Issue by puchu** [hluk/CopyQ#1809]
**Describe the bug**
after moving an item on copyq, and moving the mouse again after the item is dropped, it grabs the selected item again

**To Reproduce**
1. Open the clipboard
2. Click on item + hold left mouse button
3. move the item to a new place + release mouse button
4. move the mouse (inside the window)
5. the selected item gets grabbed again (although no mouse button is pressed)

**Alternative way to Reproduce**
1. Open the clipboard
2. Click on item + hold left mouse button
3. press ESC (item gets released)
3. move the mouse (inside the window)
5. the selected item gets grabbed again (although no mouse button is pressed)
6. press ESC multiple times (without moving the mouse)
7. window gets closed
8. re-open the clipboard
9. move the mouse (inside the window)
10. the selected item again gets grabbed (although no mouse button is pressed)

**Expected behavior**
after moving and dropping the item, it shouldn't grab a new item again if the mouse pointer gets moved

**Version, OS and Environment**
CopyQ Clipboard Manager v5.0.0
Qt: 5.15.2
KNotifications: 5.87.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Linux

**Comment by hluk** [comment]
Looks like the drag operation was triggered multiple times. Fixed.
