### ISSUE TITLE
Command as Item

### ISSUE THREAD

**Issue by FreeHarry** [hluk/CopyQ#1822]
Would be very convenient to have an additional Command type: "As item".

In this way you could assign a Command as an Item and make it visible within a selected Tab. So you could easily perform the command when double clicking on the Item.

This would allow a more complex snippet library, because a snippet may contain specific operations, before e.g. you paste it in the current window. Or the snippet just perform a defined task, whatsoever ...

Also it enables to have commands/snippets directly accessible in the main window with one click. And you can arrange it in a tree-like structure (via tabs).

**Comment by hluk** [comment]
A simple solution is to add the following command ([here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)) so you can execute items containing a text starting with `copyq:`.

```ini
[Command]
Command="
    copyq:
    var script = str(input())
    eval(script)"
Icon=\xf120
InMenu=true
Input=text/plain
Match=^copyq:
Name=Run CopyQ Script
Shortcut=enter, return
```

Example item: `copyq: popup('TEST')`

**Comment by FreeHarry** [comment]
Thanks! It works. 👍
But I changed your approach a little bit according my needs.
