### ISSUE TITLE
Command Duplicate

### ISSUE THREAD

**Issue by alabotski** [hluk/CopyQ#1825]
For some reason, I have duplicate commands

*Пометить как "Важный"*
*Удалить метку "Важный"*
and english

*Tag as "Important"*
*Remove tag "Important"*

I tried to remove the English names, but for some reason they still return

![image](https://user-images.githubusercontent.com/439337/141959799-eb3744ae-6a2a-4411-9606-1f044ab1d615.png)

**Comment by hluk** [comment]
Thanks for the report. This will be fixed in the next version - unfortunately, you will still need to remove the old commands manually. See: 6f307d7

**Comment by alabotski** [comment]
Hi
Mac CopyQ Clipboard Manager 6.0.1-gf4773644-v6.0.1
The problem is there.

green arrows - it's russian caption
red arrows - it's english caption and I can't remove them =(

![image](https://user-images.githubusercontent.com/439337/148033713-cc6984e2-32b6-45f6-b29a-360cbd994acc.png)
