### ISSUE TITLE
Shift-click selects from old pasting item instead of current.

### ISSUE THREAD

**Issue by amosbird** [hluk/CopyQ#1828]
**Describe the bug**

The focused item in copyq menu diverges between visible highlighted item and shift-click beginning item.

**To Reproduce**

1. active an item and paste it by selecting from the copyq menu and double clicking.
2. copy some other stuff (generating some more new items)
3. open copyq menu, now the visible highlighted item should be the newly copied one.
4. shift-clicking the second item, the selection goes from the second item to the previously pasted item.

**Expected behavior**
The first and second items get selected.

**Version, OS and Environment**
CopyQ Clipboard Manager v2.7.1-2875-g7b9a28c8
Qt: 5.15.2
KNotifications: 5.88.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Arch Linux

**Additional context**
It's a forked build but should be reproduceable in official release too.

**Comment by hluk** [comment]
Nice find! Thanks for providing clear steps to reproduce the behavior.

Looks like it happens because [a workaround](https://github.com/hluk/CopyQ/blob/6f50e3ba7ce198adc04290841e5855b0ec423fb9/src/gui/clipboardbrowser.cpp#L738-L740) for setting current item in the list. It's an old workaround, I'll try to remove it.

**Comment by amosbird** [comment]
I just tried out the `read-log-bytes` and it does have the selection fixed. However, it leads to other issues. I cannot paste a single item anymore (always with other items stick together). I have `ctrl-j/k` to move down and up. Now it's like always shift-moving...

**Comment by hluk** [comment]
> I just tried out the `read-log-bytes` and it does have the selection fixed. However, it leads to other issues. I cannot paste a single item anymore (always with other items stick together). I have `ctrl-j/k` to move down and up. Now it's like always shift-moving...

Interesting, it has been fixed for me. Can you check `copyq version`?

**Comment by amosbird** [comment]
> > I just tried out the `read-log-bytes` and it does have the selection fixed. However, it leads to other issues. I cannot paste a single item anymore (always with other items stick together). I have `ctrl-j/k` to move down and up. Now it's like always shift-moving...
> 
> Interesting, it has been fixed for me. Can you check `copyq version`?

I've revised my fork and it's indeed properly fixed. Thanks!
