### ISSUE TITLE
Possible to search globally from the tray or wherever (ignoring tab selection)?

### ISSUE THREAD

**Issue by carloscadux** [hluk/CopyQ#1831]
Hi,
 
I'd appreciate your help.
Is it possible to search globally from the tray or from wherever (ignoring tab selection)?
Id like to search at once all content I have stored under several different tabs.
In "Preferences >Tray" I unchecked "Show current tab in menu" and left blank the "choose other tab" drop-down, expecting it could work as a global search from the tray.
However nothing check in "Preferences >Tray" is the same as "&clipboard" had been chosen.
Also it would work if I could select a parent tab, and the content of all children tab would be included in the search, but it seems the tabs hierarchy is just visual, and for search just the selected tab in the hierarchy is considered. 
 
Thank you!
Carlos

**Comment by hluk** [comment]
Search is only supported in single tab. Applying it globally would require large changes in the app architecture. That probably won't happen any time soon.

One workaround is to gather found items in a separate temporary tab with [Search All Tabs](https://github.com/hluk/copyq-commands/tree/master/Application#search-all-tabs) command (see [README.md](https://github.com/hluk/copyq-commands/blob/master/README.md) for details on how to add the command).

**Comment by carloscadux** [comment]
Many thanks for information. The [Search All Tabs](https://github.com/hluk/copyq-commands/tree/master/Application#search-all-tabs) command is really handy! 

a) Have developers already thought about including it in the in-built CopyQ installation? 
Many new users could start using it out of the box...

b) I searched by tag names, but the "Search All Tabs" output didn't list items with them. Could you please confirm tags aren't indeed searchable?
Whether tags aren't searchable through "Search All Tabs", could the command be improved to include tags in the search output?

**Comment by hluk** [comment]
> a) Have developers already thought about including it in the in-built CopyQ installation? Many new users could start using it out of the box...

It's not going to be included in the app itself.

> b) I searched by tag names, but the "Search All Tabs" output didn't list items with them. Could you please confirm tags aren't indeed searchable? Whether tags aren't searchable, could the command be improved to include tags in the search output?

You would need to change the command to search also tags, i.e. modify the function `item_matches` like this:

```js
function item_matches(item_index, re)
{
    var item = getitem(j)
    var note = str(item[mimeItemNotes])
    var text = str(item[mimeText])
    var tags = str(item['application/x-copyq-tags'])
    return text && (re.test(text) || re.test(note) || re.test(tags))
}
```
