### ISSUE TITLE
Keep focus of search bar when doing Up/Down navigation

### ISSUE THREAD

**Issue by amosbird** [hluk/CopyQ#1834]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when searching candidates, up/down arrow unfocused the search bar and doesn't start moving right away.

**Describe the solution you'd like**

Let Up/Down arrow key navigate through candidates while keeping the focus of the search bar.

**Comment by hluk** [comment]
To change that, you can override Up/Down keys with following command ([here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)):

```ini
[Command]
Command="
    copyq:
    var shortcut = str(data(mimeShortcut))
    if (shortcut === 'down')
        selectItems(currentItem() + 1)
    else
        selectItems(currentItem() - 1)"
Icon=\xf15b
InMenu=true
Name=Override Down/Up (doesn't unfocus search bar)
Shortcut=down, up
```

**Comment by amosbird** [comment]
@hluk  I used to have that command for years and it's buggy (I cannot remember exactly what might go wrong)

https://github.com/hluk/CopyQ/issues/695

So instead I maintain a fork of copyq to add these hotkeys  https://github.com/amosbird/CopyQ/commit/7d4ab0435f96c928815789bee56812aef010d2df#diff-bf0edb6dab60d2dc3c5ffc86ccffd857eef2c3e573d868f8505a4b092f1d8010R1420-R1436

**Comment by hluk** [comment]
I think what always confused me was that pressing Down key does not select next item - so I usually copied wrong item when I quickly pressed Down followed by Enter key.

Let me try your suggestion.

**Comment by hluk** [comment]
Merged to master. Works nicely. Thanks for the suggestion. :+1:
