### ISSUE TITLE
CopyQ sync to NAS

### ISSUE THREAD

**Issue by robertstrom** [hluk/CopyQ#1836]
Before creating a new issue, see list of [known
issues](https://copyq.readthedocs.io/en/latest/known-issues.html).

**Describe the bug**
Synchronization to NAS is really, really slow.

I created a directory on my NAS named CopyQSync and configured CopyQ to sync to that directory on my NAS via SMB. Ito took about 7 minutes for the program to sync and then I closed it and then relaunched it. The program now takes forever to load and displays the message "CopyQ is not responding" or a black screen.

![image](https://user-images.githubusercontent.com/3240205/143663519-71410b06-ef1a-4824-ae42-ea4316928b99.png)

This is what my configuration looked like

![image](https://user-images.githubusercontent.com/3240205/143664234-ffb8ceeb-63bf-4daa-8998-64f719387f96.png)

I was able to finally somewhat regain control of CopyQ by editing the Synchronization out of the config file but then when i got into CopyQ the entire root &clipboard contents was gone (the one thing in there right now is the previous screenshot).

![image](https://user-images.githubusercontent.com/3240205/143664274-79ccc7f2-b795-4509-86ef-3983d35ae738.png)

I have several recent backups and tried restoring from two. One, the most recent, was made as CopyQ was doing it's initial sync to the NAS. I tried to do a complete restore and nothing was restored to the root &clipboard folder.

Using another backup from a few hours earlier, I tried to just restore the &clipboard root folder and that did nothing either.

I've finally fixed it by looking at the Sync settings in another installation of CopyQ and mimicking the Sync settings from that file. Then I restored from a backup and then had two &clipboard folders (one with all my entries and one with just a few). I deleted the one with just a few and renamed the one with all my entries. So I am good to go now, but without any synchronization.

So how does one go about setting up sync to a local NAS? And how will it work if I am not on the network that has the sync location?

Thanks,

Robert

**To Reproduce**
1. Setup sync to a NAS with an SMB destination in the format of smb://<NAS name>/<sync folder>
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**
Sync quickly and easily without application lockup

**Screenshots**
Screenshots above

**Version, OS and Environment**

 - Application Version
- ❯ copyq --version
CopyQ Clipboard Manager v5.0.0
Qt: 5.15.2
KNotifications: 5.78.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Pop!_OS 21.04

 - OS = Linux
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
  
 - Desktop environment, window manager (if applicable)

**Additional context**

**Comment by hluk** [comment]
Can you provide logs (F12 shortcut from the main window)? CopyQ should log a message when synchronization takes too long (more than 100ms per operation).

**Comment by robertstrom** [comment]
This is the only log message for today

`Note [2022-01-16 06:08:15.214] <Server-45930>: ItemSync: Files listed in 177466 ms`

Then I copied that text from the log and copyq froze, my computers fan came on, chrome frozen, and it took approximately a minute for me to get access to chrome and for this actually  to paste. I am currently unable to switch from one tab to another. CopyQ is locked up.

The sync took approximately 30 minutes

![copyq_sync_6](https://user-images.githubusercontent.com/3240205/149661683-19425560-c351-403f-9a64-20f8c7e3fae1.png)

I just copied the text above and CopyQ is frozen. Totally unusable for minutes (approximately 6 minutues).

Here are all the logs that exist after I went through the initial sync and then disconnecting from the sync since CopyQ was unusable.

```
Note [2022-01-16 06:08:15.214] <Server-45930>: ItemSync: Files listed in 177466 ms
Warning [2022-01-16 06:13:46.068] <monitorClipboard-350485>: ELAPSED 5000 ms acessing "text/plain"
Warning [2022-01-16 06:13:46.083] <monitorClipboard-350485>: ELAPSED 5015 ms acessing "UTF8:text/plain"
Warning [2022-01-16 06:13:46.089] <monitorClipboard-350485>: Clipboard data expired, refusing to access old data
Warning [2022-01-16 06:13:56.100] <monitorClipboard-350485>: ELAPSED 5001 ms acessing "text/plain"
Warning [2022-01-16 06:13:56.114] <monitorClipboard-350485>: ELAPSED 5015 ms acessing "UTF8:text/plain"
Warning [2022-01-16 06:13:56.120] <monitorClipboard-350485>: Clipboard data expired, refusing to access old data
Warning [2022-01-16 06:14:06.340] <monitorClipboard-350485>: ELAPSED 5000 ms acessing "text/plain"
Warning [2022-01-16 06:14:06.354] <monitorClipboard-350485>: ELAPSED 5014 ms acessing "UTF8:text/plain"
Warning [2022-01-16 06:14:06.360] <monitorClipboard-350485>: Clipboard data expired, refusing to access old data
Warning [2022-01-16 06:14:16.368] <monitorClipboard-350485>: ELAPSED 5000 ms acessing "text/plain"
Warning [2022-01-16 06:14:16.383] <monitorClipboard-350485>: ELAPSED 5014 ms acessing "UTF8:text/plain"
Warning [2022-01-16 06:14:16.388] <monitorClipboard-350485>: Clipboard data expired, refusing to access old data
Warning [2022-01-16 06:14:26.552] <monitorClipboard-350485>: ELAPSED 5000 ms acessing "text/plain"
Warning [2022-01-16 06:14:26.567] <monitorClipboard-350485>: ELAPSED 5015 ms acessing "UTF8:text/plain"
Warning [2022-01-16 06:14:26.573] <monitorClipboard-350485>: Clipboard data expired, refusing to access old data
Warning [2022-01-16 06:14:36.582] <monitorClipboard-350485>: ELAPSED 5001 ms acessing "text/plain"
Warning [2022-01-16 06:14:36.596] <monitorClipboard-350485>: ELAPSED 5015 ms acessing "UTF8:text/plain"
Warning [2022-01-16 06:14:36.602] <monitorClipboard-350485>: Clipboard data expired, refusing to access old data
Warning [2022-01-16 06:14:46.955] <monitorClipboard-350485>: ELAPSED 5001 ms acessing "text/plain"
Warning [2022-01-16 06:14:46.969] <monitorClipboard-350485>: ELAPSED 5015 ms acessing "UTF8:text/plain"
Warning [2022-01-16 06:14:46.975] <monitorClipboard-350485>: Clipboard data expired, refusing to access old data
Warning [2022-01-16 06:14:56.984] <monitorClipboard-350485>: ELAPSED 5000 ms acessing "text/plain"
Warning [2022-01-16 06:14:56.990] <monitorClipboard-350485>: ELAPSED 5006 ms acessing "UTF8:text/plain"
Warning [2022-01-16 06:14:56.996] <monitorClipboard-350485>: Clipboard data expired, refusing to access old data
Warning [2022-01-16 06:15:56.861] <monitorClipboard-350485>: ELAPSED 5000 ms acessing "text/plain"
Warning [2022-01-16 06:15:56.875] <monitorClipboard-350485>: ELAPSED 5014 ms acessing "UTF8:text/plain"
Warning [2022-01-16 06:15:56.881] <monitorClipboard-350485>: Clipboard data expired, refusing to access old data
Warning [2022-01-16 06:16:06.944] <monitorClipboard-350485>: ELAPSED 5000 ms acessing "text/plain"
Warning [2022-01-16 06:16:06.958] <monitorClipboard-350485>: ELAPSED 5014 ms acessing "UTF8:text/plain"
Warning [2022-01-16 06:16:06.964] <monitorClipboard-350485>: Clipboard data expired, refusing to access old data
Warning [2022-01-16 06:16:15.512] <monitorClipboard-350485>: ELAPSED 3379 ms acessing "text/plain"
Warning [2022-01-16 06:16:15.526] <monitorClipboard-350485>: ELAPSED 3393 ms acessing "UTF8:text/plain"
Warning [2022-01-16 06:16:25.907] <monitorClipboard-350485>: ELAPSED 5000 ms acessing "text/plain"
Warning [2022-01-16 06:16:25.922] <monitorClipboard-350485>: ELAPSED 5015 ms acessing "UTF8:text/plain"
Warning [2022-01-16 06:16:25.928] <monitorClipboard-350485>: Clipboard data expired, refusing to access old data
Warning [2022-01-16 06:16:36.481] <monitorClipboard-350485>: ELAPSED 5001 ms acessing "text/plain"
Warning [2022-01-16 06:16:36.496] <monitorClipboard-350485>: ELAPSED 5015 ms acessing "UTF8:text/plain"
Warning [2022-01-16 06:16:36.502] <monitorClipboard-350485>: Clipboard data expired, refusing to access old data
Warning [2022-01-16 06:19:18.657] <monitorClipboard-350485>: ELAPSED 5001 ms acessing "text/plain"
Warning [2022-01-16 06:19:18.678] <monitorClipboard-350485>: ELAPSED 5021 ms acessing "UTF8:text/plain"
Warning [2022-01-16 06:19:18.684] <monitorClipboard-350485>: Clipboard data expired, refusing to access old data
Warning [2022-01-16 06:19:28.751] <monitorClipboard-350485>: ELAPSED 5000 ms acessing "text/plain"
Warning [2022-01-16 06:19:28.758] <monitorClipboard-350485>: ELAPSED 5007 ms acessing "UTF8:text/plain"
Warning [2022-01-16 06:19:28.764] <monitorClipboard-350485>: Clipboard data expired, refusing to access old data
Warning [2022-01-16 06:19:38.938] <monitorClipboard-350485>: ELAPSED 5001 ms acessing "text/plain"
Warning [2022-01-16 06:19:38.944] <monitorClipboard-350485>: ELAPSED 5007 ms acessing "UTF8:text/plain"
Warning [2022-01-16 06:19:38.951] <monitorClipboard-350485>: Clipboard data expired, refusing to access old data
Warning [2022-01-16 06:19:49.305] <monitorClipboard-350485>: ELAPSED 5000 ms acessing "text/plain"
Warning [2022-01-16 06:19:49.321] <monitorClipboard-350485>: ELAPSED 5016 ms acessing "UTF8:text/plain"
Warning [2022-01-16 06:19:49.327] <monitorClipboard-350485>: Clipboard data expired, refusing to access old data
Warning [2022-01-16 06:22:37.554] <monitorClipboard-350485>: ELAPSED 5000 ms acessing "text/plain"
Warning [2022-01-16 06:22:37.569] <monitorClipboard-350485>: ELAPSED 5014 ms acessing "UTF8:text/plain"
Warning [2022-01-16 06:22:37.574] <monitorClipboard-350485>: Clipboard data expired, refusing to access old data
Warning [2022-01-16 06:22:47.950] <monitorClipboard-350485>: ELAPSED 5000 ms acessing "text/plain"
Warning [2022-01-16 06:22:47.965] <monitorClipboard-350485>: ELAPSED 5014 ms acessing "UTF8:text/plain"
Warning [2022-01-16 06:22:47.971] <monitorClipboard-350485>: Clipboard data expired, refusing to access old data
Warning [2022-01-16 06:29:41.319] <Client-352888>: Command "Store Copy Time": Finished in 237808 ms
Warning [2022-01-16 06:29:41.399] <Client-352889>: Command "Store Copy Time": Finished in 237888 ms
Warning [2022-01-16 06:29:56.501] <monitorClipboard-350485>: ELAPSED 10003 ms acessing "hasText"
Warning [2022-01-16 06:29:56.516] <monitorClipboard-350485>: Clipboard data expired, refusing to access old data
Warning [2022-01-16 06:30:12.456] <monitorClipboard-350485>: ELAPSED 10002 ms acessing "hasText"
Warning [2022-01-16 06:30:12.471] <monitorClipboard-350485>: Clipboard data expired, refusing to access old data
Warning [2022-01-16 06:30:27.483] <monitorClipboard-350485>: ELAPSED 10002 ms acessing "hasText"
Warning [2022-01-16 06:30:27.498] <monitorClipboard-350485>: Clipboard data expired, refusing to access old data
Warning [2022-01-16 06:30:42.653] <monitorClipboard-350485>: ELAPSED 10001 ms acessing "hasText"
Warning [2022-01-16 06:30:42.660] <monitorClipboard-350485>: Clipboard data expired, refusing to access old data
Warning [2022-01-16 06:30:57.671] <monitorClipboard-350485>: ELAPSED 10001 ms acessing "hasText"
Warning [2022-01-16 06:30:57.685] <monitorClipboard-350485>: Clipboard data expired, refusing to access old data
Warning [2022-01-16 06:31:13.053] <monitorClipboard-350485>: ELAPSED 10002 ms acessing "hasText"
Warning [2022-01-16 06:31:13.068] <monitorClipboard-350485>: Clipboard data expired, refusing to access old data
Warning [2022-01-16 06:31:28.079] <monitorClipboard-350485>: ELAPSED 10002 ms acessing "hasText"
Warning [2022-01-16 06:31:28.094] <monitorClipboard-350485>: Clipboard data expired, refusing to access old data
Warning [2022-01-16 06:33:39.665] <Client-353318>: Command "Store Copy Time": Finished in 238260 ms
```

**Comment by robertstrom** [comment]
I setup a Dropbox sync and there is zero noticeable lag, not CopyQ lockup, etc.. The CopyQ sync to Dropbox appears to work great. I have setup the &clipboard tab to sync. Is this really only going to sync the clipboard tab? Do I actually need to sertup a sync for each and every tab?

I just did a quick count and I have over 100 tabs. I really don't want to setup 100 different syncs. Is the a way of just telling CopyQ that I want to sync everything?

Hopefully ... if not, definite feature request.

Thanks,

Robert

**Comment by hluk** [comment]
Looks like a possible bug in Qt (specifically [QDir::entryInfoList](https://doc.qt.io/qt-5/qdir.html#entryInfoList-1)) or file system access being very slow for some reason (CopyQ only need filename and read/write attribute for each file which is normally fast).

> I just did a quick count and I have over 100 tabs. I really don't want to setup 100 different syncs. Is the a way of just telling CopyQ that I want to sync everything?

No, unfortunately, the configuration allow only to specify tab names to sync.

There is an old task #952 to change the default storage format for items which would probably solve this, but I haven't got enough drive to implement it.

It's possible to sync current tabs if you change the app config file manually or with a script (the app should be exited first). The list of tabs and their directories is stored under `[Plugins]` section in `itemsync\sync_tabs` (you can get the list of tabs with `copyq tab` command).

**Comment by robertstrom** [comment]
So I now have 2 systems pointed to the same CopyQ_Sync directory @ Dropbox and I do not see that they are synced and things are not in date order. Here's a screenshot of one.  NOTE: Today's date, today's date and then 11/26/2021

![image](https://user-images.githubusercontent.com/3240205/149667717-9959d20c-83fc-499b-a49e-2b6b3fef0f5f.png)

NOTE: 11/28 under 11/27

![image](https://user-images.githubusercontent.com/3240205/149667819-413e85f0-9e49-4e45-8a73-be80db18f3e3.png)

An entry with today's date and an entry from 1/11 above it

![image](https://user-images.githubusercontent.com/3240205/149668329-b97f3b83-d87d-4ea6-b469-e60ff6d9e753.png)

Shouldn't a sync  keep things in date order?

I have edited the config file manually before but I want to be sure about what's going on with the behavior that I described above before I go adding any of the other tabs. The Clipboard tab is just the tab where everything initially lands. All the other tabs are for things that I want to store long term. I do not want them to get messed up, but they are also the ones that I am most interested in syncing between systems.

**Comment by robertstrom** [comment]
This is everything in the logs post what I already sent you:

```
Note [2022-01-16 06:51:49.971] <Server-354298>: ItemSync: Files listed in 105 ms
Note [2022-01-16 06:51:59.864] <Server-354298>: ItemSync: Files listed in 104 ms
Note [2022-01-16 06:52:03.737] <Server-354298>: ItemSync: Files listed in 108 ms
Note [2022-01-16 06:52:35.381] <Server-354298>: ItemSync: Files listed in 107 ms
Note [2022-01-16 07:52:42.863] <Server-359650>: ItemSync: Items created in 1125 ms
Warning [2022-01-16 07:57:58.264] <Server-359650>: [default] QtWarning: QFont::setPixelSize: Pixel size <= 0 (0)
Warning [2022-01-16 07:57:58.278] <Server-359650>: [default] QtWarning: QFont::setPixelSize: Pixel size <= 0 (0)
Warning [2022-01-16 09:17:52.567] <Server-359650>: [default] QtWarning: QFont::setPixelSize: Pixel size <= 0 (0)
Warning [2022-01-16 09:23:50.447] <Server-359650>: [default] QtWarning: QFont::setPixelSize: Pixel size <= 0 (0)
```

**Comment by robertstrom** [comment]
a peek into the files that exist in the Dropbox folder

![image](https://user-images.githubusercontent.com/3240205/149669060-3825fb34-c41f-4d56-9279-b0a9737d01fc.png)

**Comment by robertstrom** [comment]
> Looks like a possible bug in Qt (specifically [QDir::entryInfoList](https://doc.qt.io/qt-5/qdir.html#entryInfoList-1)) or file system access being very slow for some reason (CopyQ only need filename and read/write attribute for each file which is normally fast).
> 
> > I just did a quick count and I have over 100 tabs. I really don't want to setup 100 different syncs. Is the a way of just telling CopyQ that I want to sync everything?
> 
> No, unfortunately, the configuration allow only to specify tab names to sync.
> 
> There is an old task #952 to change the default storage format for items which would probably solve this, but I haven't got enough drive to implement it.
> 
> It's possible to sync current tabs if you change the app config file manually or with a script (the app should be exited first). The list of tabs and their directories is stored under `[Plugins]` section in `itemsync\sync_tabs` (you can get the list of tabs with `copyq tab` command).

If I add other tabs do they need to point to a separate directory @ Dropbox or can all of the tabs just be pointed to the same directory @ Dropbox?

**Comment by hluk** [comment]
New own files are usually added to the top of the list. The items are not necesarily in date/time order since they can be moved/reordered manually (or by selecting an item to copy if the action is also configured to move the item to the top).

Make sure you are using the latest version of the app - there were some improvements for the item order and synchronization behavior and performance.

> If I add other tabs do they need to point to a separate directory @ Dropbox or can all of the tabs just be pointed to the same directory @ Dropbox?

If you set same path for multiple tabs, these tabs will contains same items. Not sure if that is what you want.

**Comment by robertstrom** [comment]
This is the initial sync for two systems so they both have different data. I do not move or reorder any clips except for whenever I move something into a tab for long term storage.

I am seeing new clips sync properly (at least how I would expect sync to work). To me, sync is make them both the same. This sync does not appear to be doing that, at least not with the initial sync.

> If you set same path for multiple tabs, these tabs will contains same items. Not sure if that is what you want.

Nooooooooooooooooooooooooo

So I have to setup a sync for each tab and sync it to a separate directory up in Dropbox. Good to know / very glad that I have only tested one other small tab.

How are things going top behave if I sync CopyQ running on Linux, Mac, and Windows? When O originally thought of this question I was thinking of the forward slashes vs. the backslashes, but now I am thinking that this is not going to be an issue as long as they are pointed to the same directory @ Dropbox. Just looking for validation.

Thanks!

**Comment by hluk** [comment]
> How are things going top behave if I sync CopyQ running on Linux, Mac, and Windows?

Shouldn't be a problem.

Ideally paths in configuration should be separated with forward slashes `/` otherwise sometimes there is confusion with escape characters (like `\n`). I believe this should work on Windows in most cases (except in some native command line arguments).
