### ISSUE TITLE
Separating merged items with an empty line [Feature request]

### ISSUE THREAD

**Issue by KitezhGrad** [hluk/CopyQ#1838]
When I merge items, I want them to be separated by an empty line in the final unified text.
Can you please add this option?
Thank you for considering my request.

**Comment by hluk** [comment]
This can be done using the following command - [here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them) - it will be available in **menu** or via a **shortcut**, default **space** key:

```ini
[Command]
Command="
    copyq:
    var selection = ItemSelection().current();
    var items = selection.itemsFormat(mimeText);
    var text = '';
    for (var itemText of items.values()) {
        if (itemText) {
            if (text) {
                text += '\\n\\n';
            }
            text += itemText;
        }
    }
    add(text);
    selectItems(0)"
Icon=\xf066
InMenu=true
Input=text/plain
Name=Join Selected Items
Shortcut=space
```
