### ISSUE TITLE
Can't set shortcut to toggle main window

### ISSUE THREAD

**Issue by DUOLabs333** [hluk/CopyQ#1840]
Before creating a new issue, see list of [known
issues](https://copyq.readthedocs.io/en/latest/known-issues.html).

**Describe the bug**
If I set a keyboard shortcut for "Show/hide main window", when I press it, nothing happens (the right side of the screen does flicker though).

**To Reproduce**
1. Set keyboard shortcut for "Show/Hide main window"
2. Press it
3. See error

**Expected behavior**
The main window will show.

**Screenshots**

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Application Version: from git
 - OS Arch Linux
 - Desktop environment, window manager KDE, KWin

**Additional context**

**Comment by hluk** [comment]
Can you provide output of `copyq version`?

Can you see if there are any errors in logs (with `copyq logs` command)?

Also, try to show the window with specific size and position: `copyq showAt 0 0 400 400`

**Comment by DUOLabs333** [comment]
`copyq version`:
```
CopyQ Clipboard Manager 5.0.0-98-g344e1ba0
Qt: 5.15.2
KNotifications: 5.88.0
Compiler: GCC
Arch: arm64-little_endian-lp64
OS: Arch Linux ARM
```

Interestingly, there's no logs when I press the shortcut.

`copyq showAt 0 0 400 400` does work.

**Comment by hluk** [comment]
I'm testing some minor window geometry fixes. If you can, please checkout the git branch **fix-geometry** and tests.

CopyQ makes sure the window shows up on screen, not outside it. But I'm still not quite sure why it does not work in some cases - maybe the window manager does some magic which breaks the functionality.

https://github.com/hluk/CopyQ/blob/344e1ba0805f02d47f9949b6e0fc9a0f9e73244f/src/common/config.cpp#L132

Alternatively, try removing `~/.config/copyq/copyq_geometry.ini` (make sure you exit the app first).

**Comment by DUOLabs333** [comment]
`fix-geometry` does not fix my problem, neither does deleting `~/.config/copyq/copyq_geometry.ini`

**Comment by hluk** [comment]
Does the main window show up on `copyq show`?

**Comment by DUOLabs333** [comment]
Yes.

**Comment by hluk** [comment]
Hmm, so does the `copyq toggle` command just cause the flicker?

**Comment by DUOLabs333** [comment]
`copyq toggle` shows the window, but if I do it again, it doesn't hide it.

**Comment by hluk** [comment]
> `copyq toggle` shows the window, but if I do it again, it doesn't hide it.

Maybe the desktop environment or window manager is somehow interfering.

The workaround could be to set the shortcut in the desktop environment settings instead (map a shortcut to command `copyq toggle`).

**Comment by DUOLabs333** [comment]
It works, so this is good enough.

**Comment by hluk** [comment]
Oh, perhaps it's related to this issue: #1368

I'll try to bump the timer that checks if window has focus after activation.

https://github.com/hluk/CopyQ/blob/0f41a58545d47f0a996c624283b7557ab0f6c3bf/src/gui/mainwindow.cpp#L2373
