### ISSUE TITLE
Wayland: Main window does not open, unless invoked when X-Wayland app focussed

### ISSUE THREAD

**Issue by olivergondza** [hluk/CopyQ#1843]
**Describe the bug**

On Wayland (tested with Gnome and Enlightenment), `copyq` main window does not open upon shortcut, unless invoked from app running with X-Wayland*. For native Wayland apps (tested with `kitty-term`, `sublime-text`, or empty workspace), it simply does nothing. For X-Wayland apps (tested with `fiefox`, `thunderbird`, java UI apps), this opens/closes correctly.

Possible causes I ruled out:

- It does not even toggle the window on an inactive workspace, so it is not a window placement problem.
- This manifest on a workspace with no apps that could possibly steal the keybinding.
- The `copyq` window is not open on the workspace at all, not a problem with bringing to the top.

*) Identified with `xlsclients`

Switching to X11 with no other change gets `copyq` to correctly open and close no matter what window is focussed, if any. Verified in both Gnome and Enlightenment.

**To Reproduce**

1. Navigate to empty workspace
2. `ctrl+alt+h`
3. Nothing happens
---
1. Navigate to workspace with focussed native Wayland app
2. `ctrl+alt+h`
3. Nothing happens
---
1. Navigate to workspace with focussed X-Wayland app
2. `ctrl+alt+h`
3. Main window toggles as expected

Configuring "Open window on current screen" or "Close when unfocussed" had no effect.

**Expected behavior**

Using `ctrl+alt+h` to toggle main window will open and close on every workspace, over every app.

**Screenshots**
N/A

**Version, OS and Environment**
```
CopyQ Clipboard Manager v5.0.0
Qt: 5.15.2
KNotifications: 5.86.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Arch Linux
```

**Additional context**

```
yay -Q | grep wayland
qt5-wayland 5.15.2+kde+r36-1
wayland 1.19.0-2
wayland-protocols 1.24-1
xorg-xwayland 21.1.3-1
```

**Comment by hluk** [comment]
Wayland does not support defining custom global shortcut in applications. I'm guessing you run the app in X11 compatibility mode (XWayland) - that's probably why the global shortcuts work but only from other X11 apps.

Solution is to map shortcuts in your desktop environment instead (e.g. `copyq toggle` command is to show/hide the main window).

See also: #27
