### ISSUE TITLE
Styling for Template literals doesn't work properly

### ISSUE THREAD

**Issue by FreeHarry** [hluk/CopyQ#1845]
The styling for Template literals doesn't work properly in the Command-Edit-Dialog.
But using it works flawless. The problem only concerns the styling in the dialog.

**Screenshot**
<img width="683" alt="2021-12-08_10-57-10--copyq" src="https://user-images.githubusercontent.com/24735031/145189093-083178d0-d3c5-415b-99df-68bd421496a9.png">

**Version, OS and Environment**
CopyQ 5.0
Windows 10

**Comment by hluk** [comment]
Fixing. Thanks for the report. The syntax highlighting implementation is still quite simple and naive.
