### ISSUE TITLE
Fix for "Change Copied Text to Title Case"

### ISSUE THREAD

**Issue by sohail-bakhtiari** [hluk/CopyQ#1846]
On the [Command Examples](https://copyq.readthedocs.io/en/latest/command-examples.html) page, the example for changing text to title-case does not work. It does nothing.

I believe there is some problem with `input()` in this line:
`copy(toTitleCase(str(input())))`

To make it work I used the previous example titled "Change Upper/Lower Case of Selected Text" to copy the selected text and paste the modified string instead:

```
  copyq:
    function toTitleCase(str) {
      return str.replace(
        /\w+/g,
        function(txt) {
          return txt.charAt(0).toUpperCase() + txt.substr(1).toLowerCase();
        }
      );
    }

    if (!copy())
      abort()

    var text = str(clipboard())

    copy(toTitleCase(text))
    paste()
```

I also changed the regex from `/\w\S*/g` to `/\w+/g` to better process multipart words (words with dash or slash)

I'm not sure if it is OK to post this here, sorry if it is out of context.

**Comment by hluk** [comment]
Can you create pull request? The documentation page source code is here: https://github.com/hluk/CopyQ/blob/master/docs/command-examples.rst

**Comment by Kmfernan5** [comment]
This title case command is not working

https://github.com/hluk/CopyQ/blob/master/docs/command-examples.rst

Note [2022-04-25 19:09:27.250] <Server-15816>: Exception in command "Title Case": ScriptError: SyntaxError: Unterminated regular expression literal
Note [2022-04-25 19:09:27.250] <Server-15816>:    
Note [2022-04-25 19:09:27.250] <Server-15816>:    --- backtrace ---
Note [2022-04-25 19:09:27.250] <Server-15816>:    @eval code:4
Note [2022-04-25 19:09:27.250] <Server-15816>:    eval:function toTitleCase(str)...
Note [2022-04-25 19:09:27.250] <Server-15816>:    eval
Note [2022-04-25 19:09:27.250] <Server-15816>:    --- end backtrace ---
Note [2022-04-25 19:10:45.403] <Server-15816>: Exception in command "Title Case": ScriptError: SyntaxError: Unterminated regular expression literal
Note [2022-04-25 19:10:45.403] <Server-15816>:    
Note [2022-04-25 19:10:45.403] <Server-15816>:    --- backtrace ---
Note [2022-04-25 19:10:45.403] <Server-15816>:    @eval code:4
Note [2022-04-25 19:10:45.403] <Server-15816>:    eval:function toTitleCase(str)...
Note [2022-04-25 19:10:45.403] <Server-15816>:    eval
Note [2022-04-25 19:10:45.403] <Server-15816>:    --- end backtrace ---
Note [2022-04-25 19:11:04.441] <Server-15816>: Exception in command "Title Case": ScriptError: SyntaxError: Unterminated regular expression literal
Note [2022-04-25 19:11:04.441] <Server-15816>:    
Note [2022-04-25 19:11:04.441] <Server-15816>:    --- backtrace ---
Note [2022-04-25 19:11:04.441] <Server-15816>:    @eval code:4
Note [2022-04-25 19:11:04.441] <Server-15816>:    eval:function toTitleCase(str)...
Note [2022-04-25 19:11:04.441] <Server-15816>:    eval
Note [2022-04-25 19:11:04.441] <Server-15816>:    --- end backtrace ---

**Comment by hluk** [comment]
@viharm Can you please check? The command has been added in #1759.

**Comment by hluk** [comment]
> @hluk, this was the snippet I’ve been using for pasting as title case. How/what would you like me to check?

@viharm It seems the command was not copied properly to the documentation. The following should work (but does not):
1. Go to https://github.com/hluk/CopyQ/blob/master/docs/command-examples.rst#change-copied-text-to-title-case
2. Copy the code for "Change Copied Text to Title Case"
3. Open **Command dialog** in CopyQ (F6 shortcut from the main window)
4. Click **Paste Commands** button (check that the command is pasted)
5. Click OK
6. Copy a text and trigger the command from tray menu or with the global shortcut
7. The transformed text should be copied to clipboard and pasted (this does not work and error pops up - you can see the full error in Log dialog - F12 shortcut from the main window)

If it worked for you before and you still have the command available, please copy the working command from the Command dialog with **Copy Selected** button and create PR.

**Comment by viharm** [comment]
@hluk , I've checked the command snippet you've linked above. The one I'm using successfully is the same as in this snippet. However when I paste as a new command using the "Paste Commands" button, line 6 changes from `/\w\S*/g,` to `/*/g,`. It appears that the action associated with the "Paste Commands" button transforms this text and does not paste it as literal.

If you could point me to the relevant syntax used by the "Paste Commands" action, I can try to escape `\w\S` appropriately.

**Comment by hluk** [comment]
> @hluk , I've checked the command snippet you've linked above. The one I'm using successfully is the same as in this snippet. However when I paste as a new command using the "Paste Commands" button, line 6 changes from `/\w\S*/g,` to `/*/g,`. It appears that the action associated with the "Paste Commands" button transforms this text and does not paste it as literal.
> 
> If you could point me to the relevant syntax used by the "Paste Commands" action, I can try to escape `\w\S` appropriately.

Paste Commands uses INI format (whatever implementation Qt framework has).

I did not manage to get the command working even after replacing the regexp. It always results in an empty string.

@viharm Can you please use Copy Selected button to copy back the correct working command and create PR?

**Comment by viharm** [comment]
Testing here....

```
[Command]
Name=Paste as title case
Command="
    copyq: 
    function toTitleCase(str) {
      return str.replace(
        /\\w\\S*/g,
        function(txt) {
          return txt.charAt(0).toUpperCase() + txt.substr(1).toLowerCase();
        }
      );
    }
    copy(toTitleCase(str(input())))
           paste()
    "
Input=text/plain
IsGlobalShortcut=true
HideWindow=true
Icon=\xf15b
GlobalShortcut=ctrl+alt+shift+e
```

The above snippet shows what seems like escaping of the backslashes :-)

**Comment by hluk** [comment]
Thanks for the fix. :+1:

**Comment by viharm** [comment]
Note the double backslash before “w” & “S”.

It depends on whether you are editing directly within the CopyQ interface or in the configuration file.

I suggest try a couple of variations until it works.
