### ISSUE TITLE
Suggestion: add a tab page content import and export function

### ISSUE THREAD

**Issue by PennHui666** [hluk/CopyQ#1848]
I often store frequently used text content in copyq for my daily use. However, once I reinstall the system or the disk is damaged, the content I stored in the past is gone. Therefore, I hope that the author can see this demand and develop an import and export function to facilitate backup in the later stage.

**Comment by hluk** [comment]
Import and Export is already available (from File menu). See also: https://copyq.readthedocs.io/en/latest/backup.html
