### ISSUE TITLE
close CopyQ from root script

### ISSUE THREAD

**Issue by DoctorSubtilis** [hluk/CopyQ#1849]
I noticed that, while from a single terminal command I can exit from CopyQ, (/quit), from a script I didn't manage to leave CopyQ (even usign the same terminal command, that is `copyq exit`, or `copyq exit -yes`, and even disabling the confirm to exit).  
What should I do?

EDIT
I have KDE Neon, and the code in the KDE menu to start copyq is `env QT_QPA_PLATFORM=xcb copyq`

**Comment by DoctorSubtilis** [comment]
I think that this code should work:  
`#!/bin/bash
#to quit
export QT_QPA_PLATFORM=copyq 
copyq exit
#to start
env QT_QPA_PLATFORM=xcb copyq`

**Comment by DoctorSubtilis** [comment]
I have forgotten to say a crucial thing: my script is a _root_ script.  
And I think that this is the problem: a no-root script works, an hybrid (root and no-root) script is a mess.

**Comment by hluk** [comment]
`QT_QPA_PLATFORM` is usually `xcb` or `wayland` (`copyq` is not valid value).

You also need to have same environment variables for overriding config paths when starting the app and when running the `copyq exit` command. These variables are: `XDG_CONFIG_HOME`, `XDG_CONFIG_DIRS`, `COPYQ_SESSION_NAME`, `COPYQ_SETTINGS_PATH`

The same goes for current **user** that runs the commands. For root you would need something like:

```bash
su - $your_user -c 'copyq exit'
```
