### ISSUE TITLE
Feature Request: remove the "Text Copied" title from the non-native notification window

### ISSUE THREAD

**Issue by qualitybydesign** [hluk/CopyQ#1850]
Environment:
CopyQ v5.0.0-gb37afea3-v5.0.0
MacOs Big Sur 11.6.1

**Is your feature request related to a problem? Please describe.**
I use the non-native notification feature to display what's on the clipboard.  The window in which the clipboard content is displayed has a large font title that reads "Text Copied".  This makes the window larger than needed and takes up screen real estate, blocking content in other windows.  Older versions of CopyQ just displayed the content of the clipboard without the title and I preferred that.

**Describe the solution you'd like**
I would like an option to hide everything but the clipboard content in the notification window.

**Describe alternatives you've considered**
We could also always skip the title, but I expect some people like it.
Could also let us pick the font size for the title, so I could pick one that is very tiny. copy glyph would scale with font size.

**Additional context**
![image](https://user-images.githubusercontent.com/64216865/146053556-ba620a6a-347e-4a1c-85cd-0795fb88db33.png)

**Comment by hluk** [comment]
You can change the notification appearance and behavior with the following command ([here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)):

```ini
[Command]
Command="
    const TIMEOUT = 4000;
    const ICON = '\xf46c';
    const MAX_LENGTH = 80;

    global.showDataNotification = function() {
        const text = str(data(mimeText));
        var label = text.trim().replace(/\\n.*/, '\x2026');
        if (label.length > MAX_LENGTH) {
            label = label.substring(0, MAX_LENGTH) + '\x2026';
        }
        notification(
            '.id', 'copyq_clipboard',
            '.title', label,
            '.time', TIMEOUT,
            '.icon', ICON,
        );
    }"
Icon=\xf46c
IsScript=true
Name=Simpler Notification
```
