### ISSUE TITLE
KeePassXC passwords copied when command is set to ignore them

### ISSUE THREAD

**Issue by AdrianSkar** [hluk/CopyQ#1851]
**Describe the bug**
On Win10, KeePassXC passwords are copied to CopyQ when KeePassXC is set to minimize windows after copying one.

**To Reproduce**
1. Open CopyQ and KeePassXC
2. Set KeePassXC to _Hide window when copying to clipboard/Minimize_
3. [Set CopyQ command to ignore the KeePassXC window.](https://github.com/hluk/CopyQ/wiki/FAQ#how-to-omit-storing-text-copied-from-specific-windows-like-a-password-manager) 
4. Select an entry on KeePassXC and click on copy password.

**Expected behavior**
Password is copied but not reflected on CopyQ

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Application Version v5.0.0
 - OS Windows 10 Home 21H2
 - KeePassXC 2.6.6

**Comment by hluk** [comment]
I hope this will help: https://github.com/hluk/CopyQ/issues/1744#issuecomment-912284482

Otherwise it's probably not possible to ignore reliably content by window title if the window hides immediately (there are already some workarounds to make the behavior more reliable). Unfortunately, there is also no way to get a "clipboard owner".

**Comment by AdrianSkar** [comment]
Thank you for the quick reply. I understand the issue. From that comment 

> ...it looks like CopyQ thinks that the source window is the previous one focused because password manager has focus for only a very short time when password is copied.

I'm not savvy in app/C programming but, as an idea, could it be possible to somehow add a rule for specific programs to make CopyQ "think" that previous last windows were the password manager ones by doubling/overwritting history?
Meaning something like:
```
if (password manager)
  window[current] = password manager 
  window[last] = password manager
```

**Comment by hluk** [comment]
> I'm not savvy in app/C programming but, as an idea, could it be possible to somehow add a rule for specific programs to make CopyQ "think" that previous last windows were the password manager ones by doubling/overwritting history?

CopyQ internally already handles the case when a clipboard changes shortly after current window closes/switches: https://github.com/hluk/CopyQ/blob/3bffab72f5fe2ae51dbb28c5d48d132a0b90c727/src/app/clipboardownermonitor.cpp#L31-L39

I can maker the interval configurable (it's currently 50 ms) but I don't want to provide previously focused window in script engine (CopyQ is not a window manager).

If you can, please use the command from https://github.com/hluk/CopyQ/issues/1744#issuecomment-912284482 - it should be much safer than checking window title.
