### ISSUE TITLE
Filter for icons

### ISSUE THREAD

**Issue by alabotski** [hluk/CopyQ#1852]
Can you add search (filter) for tab icons
Now it's very hard to find anything

![image](https://user-images.githubusercontent.com/439337/146640487-7f8bef30-7916-4b20-9557-410f7fd825de.png)

**Comment by hluk** [comment]
Did you try **typing some text** after you open the dialog? It should trigger the filter (english terms only, based on the names and aliases in the icon font). You are right, it very handy.
