### ISSUE TITLE
Assign shortcut to paste specific item from specific Tab

### ISSUE THREAD

**Issue by Valerybm** [hluk/CopyQ#1854]
Hello!

I am searching for a way to assign shortcut to specific item in the clipboard (TAB) so that I can paste it with keyboard shortcut, instead of selecting it with the mouse.

Does such option exists? And how can I implement it.

Best Regards!
Valeri

**Comment by hluk** [comment]
There is [Select Nth Item](https://github.com/hluk/copyq-commands/tree/master/Global#select-nth-item) command (see [README.md](https://github.com/hluk/copyq-commands/blob/master/README.md) for details on how to add the command).

**Comment by niksfirefly** [comment]
How can I do it for any or specific TAB not clipboard?

**Comment by hluk** [comment]
> How can I do it for any or specific TAB not clipboard?

Add `tab("some other tab")` to the command, for example:

```ini
[Command]
Command="
    copyq:
    tab('work')
    var n = str(data(mimeShortcut)).slice(-1)
    select(n)"
GlobalShortcut=ctrl+shift+0, ctrl+shift+1, ctrl+shift+2, ctrl+shift+3, ctrl+shift+4, ctrl+shift+5, ctrl+shift+6, ctrl+shift+7, ctrl+shift+8, ctrl+shift+9
Icon=\xf0cb
IsGlobalShortcut=true
Name=Select Nth Item from work tab
```
