### ISSUE TITLE
CopyQ searching - ability to search entire contents, not just current tab

### ISSUE THREAD

**Issue by robertstrom** [hluk/CopyQ#1855]
**Is your feature request related to a problem? Please describe.**
I was reading an article today and determined that I wanted to copy a specific command and store it away in CopyQ (stored in a tab related to the subject). Before I did that I typed in a keyword related to the command to see if I had stored the information already. So I typed in the keyword and CopyQ found nothing. I copied the command and then dragged it into the appropriate tab (I display my tabs as a tree so I view it as a folder structure). Once I did this I saw that I had already copied a similar command previously.

**Describe the solution you'd like**
I would like to see CopyQ make it possible to search all of the tab (folder, container) structure of the CopyQ stored clips for the search term defined. 

**Describe alternatives you've considered**
On Windows I have used a similar program called Clipmate since the mid to late 1990's (The program still works but it has not been developed for years now and it only works on Windows. I use Windows, Mac, and Linux ... hence CopyQ). When you perform a search using that program it searches the entire contents of all folders, containers, or whatever you want to call them so I guess that I assumed that CopyQ did the same thing. Today I believe I discovered that it does not.

**Additional context**

**Comment by gabbymouth** [comment]
That was an important feature to me and ditto-cp would search everywhere. You should try this Command script: https://github.com/hluk/copyq-commands/blob/master/Application/search-all-tabs.ini. It works great.

**Comment by robertstrom** [comment]
@gabbymouth - I added the script and will play around with using it. At first basic testing it does seem to work. I'll just have to get used to using CTRL + SHIT + F instead of just CTRL + F.

Thanks,
Robert

**Comment by gabbymouth** [comment]
> @gabbymouth -  I'll just have to get used to using CTRL + SHIT + F instead of just CTRL + F.

I use the Menu button to launch it.

**Comment by hluk** [comment]
Searching all tabs in CopyQ would require changing the way items are stored in the app. That would be a lot of effort and I don't find it so useful myself. The search-all-tabs command will have to do for now.

**Comment by gabbymouth** [comment]
Just a note that when using the current search method, if you click each tab it will auto-search for that word/string...which is ok if you don't have a LOT of tabs...
