### ISSUE TITLE
Be able to change hyperlink color (for easier visibility in dark themes)

### ISSUE THREAD

**Issue by KeronCyst** [hluk/CopyQ#1859]
**Is your feature request related to a problem? Please describe.**
When in a dark theme, I can't easily read hyperlink text because of its darker-blue color

**Describe the solution you'd like**
Be able to edit the color of hyperlink text

**Describe alternatives you've considered**
Or just make it default to a brighter color if the background is dark

**Additional context**
For example, I find it difficult to read the hyperlink entry here without highlighting it by click or arrow keys:
![image](https://user-images.githubusercontent.com/13827055/147856478-d3b7726a-31e2-45ab-b105-2d9b59093347.png)

**Comment by hluk** [comment]
It will be configurable using a custom stylesheet in configuration in the next version.

It's also available in this development build: https://ci.appveyor.com/project/hluk/copyq/builds/42156405/artifacts

![image](https://user-images.githubusercontent.com/38054/148991822-2e2c29e6-389d-4243-9712-d886c6e84aff.png)

**Comment by vincentroue** [comment]
Here’s a polished and improved English translation of your message:

---

Hello, and a big thank you for all the work you've done and for this excellent tool, which has become absolutely indispensable for me!

I was wondering if it’s possible to modify something other than the color in the HTML stylesheet of the "text" plugin? Specifically, I’d like to adjust the display of the titles of the clips rendered in HTML (for example, reducing their size).  
![](https://i.imgur.com/gRkfBRb.png)  

I couldn’t find any documentation about this, and I tried the following:  

```css
h1 {
    font-size: 16px !important;
}
```

But nothing happens. Perhaps it’s not possible?  

Thank you so much for your feedback!  
Vincent

**Comment by vincentroue** [comment]
Thank you very much for the feedback! It already improves the appearance (level 1 headings were too large for me).  

I did some tests, and the font adjusts well with:  
`large`, `x-large`, `xx-large`, `medium`, `small`,  
but not with `x-small` or `xx-small`, nor with `underline` or `underlined`.  

I haven’t found how to underline the text, though.  

Here’s an example that successfully modifies the appearance:  

```css
h1 {
    font: bold x-large;
}

h2 {
    font: bold large;
}

h3 {
    font: italic bold small;
}
```

**Comment by vincentroue** [comment]
ok its good for underline
h1 {
    font: bold x-large
;
    text-decoration: underline;
    color: red;
    line-height: 0.3;
    text-transform: uppercase
}
h2 {
    font: bold large;
    color: blue
}

h3 {
    font: italic bold small
}
