### ISSUE TITLE
Shortcut to show/hide main window doesn't work anymore

### ISSUE THREAD

**Issue by moritzdietz** [hluk/CopyQ#1860]
Before creating a new issue, see list of [known
issues](https://copyq.readthedocs.io/en/latest/known-issues.html).

**Describe the bug**
After updating to the latest version `6.0.0~focal` using Linux Mint I noticed that my keyboard shortcut to show/hide the main window doesn't work anymore. It's not just the combination, but any shortcut I enter there doesn't trigger anything.

**To Reproduce**
1. Change a shortcut in the preferences and save it
2. Try to invoke the shortcut

**Expected behavior**
In the case where you set the shortcut for "Show/hide main window" it won't show or hide the main window

**Screenshots**
N/A

**Version, OS and Environment**
```
$ copyq version
CopyQ Clipboard Manager 6.0.0~focal
Qt: 5.12.8
KNotifications: 5.68.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Linux Mint 20.2
```
```
cat /etc/os-release
NAME="Linux Mint"
VERSION="20.2 (Uma)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20.2"
VERSION_ID="20.2"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=uma
UBUNTU_CODENAME=focal
```

**Comment by moritzdietz** [comment]
I tried to downgrade the package but I couldn't find the old package in the PPA repo somehow. Will try later/tomorrow.

**Comment by in-in** [comment]
It looks like they removed the shortcuts for the "Show/hide main window" :disappointed: 
https://github.com/hluk/CopyQ/releases/tag/v6.0.0
![220011641070421](https://user-images.githubusercontent.com/8797432/147860103-2fb6272f-3cc2-4148-9b8e-fc65bb387305.png)

**Comment by moritzdietz** [comment]
> It looks like they removed the shortcuts for the "Show/hide main window" disappointed https://github.com/hluk/CopyQ/releases/tag/v6.0.0 ![220011641070421](https://user-images.githubusercontent.com/8797432/147860103-2fb6272f-3cc2-4148-9b8e-fc65bb387305.png)

I think what they are referring to this is to use CopyQ commands that invoke such things - for example here are commands which are offfered that make use of APIs to the main application. https://github.com/hluk/copyq-commands

What I am referring to though, is the main application behavior instead :)

**Comment by koplo199** [comment]
I got the same issue after updating to 6.0.0 using the PPA, any combination won't work.
Latest working build was [5.0.0](https://launchpad.net/~hluk/+archive/ubuntu/copyq/+build/22235192),  any subsequent build has the same issue, beginning from [5.0.0.117](https://launchpad.net/~hluk/+archive/ubuntu/copyq/+build/23007348).

Ubuntu 21.10 on X.org

**Comment by moritzdietz** [comment]
> PS: @moritzdietz you can download 5.0.0~focal [here](https://launchpad.net/~hluk/+archive/ubuntu/copyq/+build/22235190).

Cheers! That worked flawlessly.

**Comment by hluk** [comment]
> It looks like they removed the shortcuts for the "Show/hide main window"

**All existing old commands should work fine**. The entry in changelog refers to fixed updating of internal commands/shortcuts.

Does `copyq toggle` command show/hide the main window?

Are there any errors in logs?

Can you find the global shortcut command "Show/hide main window" with correct shortcut in Command dialog (opens with F6 shortcut from main window)?

Unfortunately, I've been using Wayland for a long time and the global shortcuts don't work there (which is expected).

**Comment by erenseymen** [comment]
Same issue here. Ubuntu 20.04 Gnome 3.36.8 X11. None of the global shortcuts are working with copyq v6.

> Does `copyq toggle` command show/hide the main window?
Yes. It works.

> Can you find the global shortcut command "Show/hide main window" with correct shortcut in Command dialog (opens with F6 shortcut from main window)?
![image](https://user-images.githubusercontent.com/27849007/147869595-539cab1d-5277-4ac0-9305-b493eb554a7a.png)
Yes, global shortcut is defined correctly but it's not working anymore.

> Are there any errors in logs?
There are no logs in Help>"Show Log" . There are no logs when I launch copyq from the commandline. I guess because copyq cannot catch my global shortcut presses, it can't log it.

**Comment by hluk** [comment]
Thanks for a quick reply. Looks like it could be an issue with recently added support for Qt 6. I'm trying to figure out where it went wrong and fix it.

**Comment by erenseymen** [comment]
Another thing is that I cannot assign a keyboard shortcut in Gnome settings if it's already defined as a global shortcut in copyq. copyq prevents me to use that keyboard shortcut. So it seems like copyq catches global shortcuts but can't use them.

**Comment by hluk** [comment]
> Another thing is that I cannot assign a keyboard shortcut in Gnome settings if it's already defined as a global shortcut in copyq. copyq prevents me to use that keyboard shortcut. So it seems like copyq catches global shortcuts but can't use them.

This is probably not something I can fix and I don't see it as something that should be fixed in the app itself.

**Comment by erenseymen** [comment]
> This is probably not something I can fix and I don't see it as something that should be fixed in the app itself.

Yes, it is not a separate issue. I just wanted to state that copyq is able to catch those shortcuts, but currently (v6) cannot use them. Disabling the command entirely gives me the ability to use the shortcut in Gnome settings.

**Comment by hluk** [comment]
I figured out the problem. I will release a bugfix version now.

Later, I will also try to write a test for global shortcuts (using `xdotool` utility to send the key presses).

**Comment by hluk** [comment]
Version 6.0.1 is now available in the [PPA](https://launchpad.net/~hluk/+archive/ubuntu/copyq).

Thanks for fast bug report and all the quick responses! :+1:

**Comment by erenseymen** [comment]
Tested 6.0.1. It works OK. Thanks for the quick fix.

**Comment by moritzdietz** [comment]
Thanks for the quick fix on a Sunday + on January 2nd! Much appreciated.

**Comment by koplo199** [comment]
Wow that was quick! Thanks a lot.

**Comment by eldadpuzach** [comment]
Thank You!🙏

**Comment by realchrisolin** [comment]
This issue ended up being used to generate AI assisted step-by-step instructions on how to accomplish this. Decided to leave a link to the instructions for posterity.

> To add a hotkey or shortcut to show/hide the CopyQ main window, you can follow these steps:
> 
> 1. Open the CopyQ Preferences by selecting "File - Preferences" in the menu[1].
> 
> 2. In the Preferences window, select the "Shortcuts" tab[1].
> 
> 3. Click the button next to the "Show/hide main window" action[1].
> 
> 4. Press the desired shortcut key combination on your keyboard to assign it to the "Show/hide main window" action[1].
> 
> 5. Click "OK" to save the shortcut[1].
> 
> Alternatively, if the "Show/hide main window" action is missing from the Shortcuts tab, you can add it using the Commands/Global Shortcuts dialog[1][4]:
> 
> 1. Open the Commands/Global Shortcuts dialog by selecting "File - Commands/Global Shortcuts..." in the menu[4].
> 
> 2. Click the "Add" button to create a new command[4].
> 
> 3. Select the "Show/hide main window" command from the list[4].
> 
> 4. Press the desired shortcut key combination on your keyboard to assign it to the command[4].
> 
> 5. Click "OK" to save the command and shortcut[4].
> 
> After following these steps, the assigned shortcut key combination will toggle the visibility of the CopyQ main window whenever pressed, even if CopyQ is not the currently focused application[4].
> 
> Citations:
> [1] https://copyq.readthedocs.io/en/latest/keyboard.html
> [2] https://github.com/hluk/CopyQ/issues/1860
> [3] https://www.reddit.com/r/vscode/comments/rnbg1g/show_popuptooltip_on_demand_only/
> [4] https://copyq.readthedocs.io/en/latest/writing-commands-and-adding-functionality.html
> [5] https://support.ptc.com/help/wrr/r12.0.0.0/en/wrr/ReferenceGuide/basics/show_hiding_tooltips_shortcut_key_assignments.html

https://www.perplexity.ai/search/add-application-hotkeyshortcut-kQ00l00zRyyoxK3_ACS2mQ
