### ISSUE TITLE
System tray icon tooltip no longer shows current clipboard content

### ISSUE THREAD

**Issue by Gitoffthelawn** [hluk/CopyQ#1864]
**Describe the bug**
Perhaps I'm just not remembering correctly, but I thought CopyQ normally showed the current clipboard contents in it's system tray icon's tooltip.  As of 6.0.0, CopyQ no longer seems to be doing this.

**To Reproduce**
1. Copy text to the clipboard.
2. Hover over the CopyQ icon in the system tray.
3. Notice the tooltip is just "CopyQ", and not the current clipboard contents.

**Expected behavior**
Showing clipboard contents in the tooltip.

**Version, OS and Environment**
 - Application Version 6.0.1
 - Win7

**Additional context**
If I'm simply not remembering correctly, perhaps this can be turned into an FR.

**Comment by hluk** [comment]
Works fine for me. Do you perhaps have a command that overrides `updateTitle` function? I use this to avoid showing clipboard content in UI (window title + tray icon tooltip):

```ini
[Command]
Command="
    global.updateTitle = function(){}"
Icon=\xf05e
IsScript=true
Name=No Window Title
```

**Comment by Gitoffthelawn** [comment]
> 

Hmmm.... the CopyQ window title is correct, but the tooltip is now just "CopyQ" when using v6.0.1.

I did have this command to show as much of the clipboard string as possible, but I disabled it during testing:  
```
global.updateTitle = function() {
  var text = str(data(mimeText))
  setTitle(text)
}
```

Although it shouldn't affect the tooltip, the only other possibly related command I have enabled is this one, which changes the system tray icon's color:  
```
var onStart_ = global.onStart;
global.onStart = function() {
  iconColor('#ee0');
  onStart_();
}
```

(As an aside, I just noticed that my first command above does not have semicolons at the end of each line.  Are they needed, or do `newlines` work just as well?)

**Comment by hluk** [comment]
CopyQ uses new tray icon library since 6.0.0 to fix some issues on Linux. The same library is used for Windows and it looks like there is a bug in their code ("subtitle" is not set in the tooltip): https://github.com/KDE/knotifications/blob/6fc3fa7eaf7b4310fa09b401ac279fa8dea9c01d/src/kstatusnotifieritem.cpp#L317

**Comment by hluk** [comment]
Can you test [this development build](https://ci.appveyor.com/project/hluk/copyq/builds/42089021/artifacts)?

**Comment by Gitoffthelawn** [comment]
@hluk Yes, I can test it if you would still like me to.  If you can, let me know within a few minutes (if you happen to be online) if there is still a testing need.

**Comment by Gitoffthelawn** [comment]
@hluk I tested it.  It worked great.  Thank you.  Is that development build suitable for use as a daily driver?

**Comment by hluk** [comment]
> @hluk I tested it. It worked great. Thank you. Is that development build suitable for use as a daily driver?

Yup, it should be stable - except this small fix there are no other changes since the recent release.

**Comment by Gitoffthelawn** [comment]
> > @hluk I tested it. It worked great. Thank you. Is that development build suitable for use as a daily driver?
> 
> Yup, it should be stable - except this small fix there are no other changes since the recent release.

Thanks.  Do you know why all the DLLs are also changed since the recent release?

**Comment by hluk** [comment]
> > > @hluk I tested it. It worked great. Thank you. Is that development build suitable for use as a daily driver?
> > 
> > 
> > Yup, it should be stable - except this small fix there are no other changes since the recent release.
> 
> Thanks. Do you know why all the DLLs are also changed since the recent release?

What do you mean changed? Perhaps new Qt release (you can check with `copyq version` command)?

**Comment by Gitoffthelawn** [comment]
> What do you mean changed? Perhaps new Qt release (you can check with `copyq version` command)?

Before overwriting v6.0.1 with v6.0.3 dev build, I compared all files in each download.  The main executable was different, but also all the DLLs in one subfolder (sorry, I forgot "in one subfolder" in my post above).  I would have to perform the download again and run the comparison once more to see which folder it was.  I'm on an incredibly slow internet connection at the moment, so not a good time to try that... probably faster on your end.

Here is the relevant part of the `copyq version` output:  
```
CopyQ Clipboard Manager 6.0.1-3-g57a38270
Qt: 5.15.2
KNotifications: 5.87.0
Compiler: MSVC
Arch: x86_64-little_endian-llp64
```
