### ISSUE TITLE
macOS 11.6 or later required in recent version.

### ISSUE THREAD

**Issue by diimdeep** [hluk/CopyQ#1866]
I've decided to try this app, but couldn't.  
README mentions OS X 10.13+ support.
Trying latest release https://github.com/hluk/CopyQ/releases/tag/v6.0.1 while using macOS 10.15.7
Get this error
![Screenshot 2022-01-05 at 12 35 40](https://user-images.githubusercontent.com/485713/148196073-2bbc1b1f-1b3e-4ad7-ad2a-8f35e119795f.png)

Meanwhile, using v5(no problem)

**Comment by hluk** [comment]
Not sure if this can be easily fixed. I rely on whatever is supported by the compiler/linker and libraries installed in the build machine (using [utils/github/install-macos.sh](https://github.com/hluk/CopyQ/blob/c5f7119c1dae7e8be4587904e0033574348c4589/utils/github/install-macos.sh) and GitHub Actions).

**Comment by hluk** [comment]
This is probably due to [the build running on macOS 11](https://github.com/hluk/CopyQ/runs/4683648920?check_suite_focus=true) (GitHub actions must have silently updated macos-latest build image).

I will try to build the bundle on macOS 10.15.

**Comment by hluk** [comment]
Can you verify the newly built [CopyQ.dmg](https://github.com/hluk/CopyQ/actions/runs/1722362062#artifacts)?

**Comment by diimdeep** [comment]
It work now in 10.15, thanks!
