### ISSUE TITLE
copyq: error while loading shared libraries: libKF5Notifications.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by robertstrom** [hluk/CopyQ#1874]
Before creating a new issue, see list of [known
issues](https://copyq.readthedocs.io/en/latest/known-issues.html).

**Describe the bug**
Attempting to run copyq after initial installation on new build of Nali Linux

**To Reproduce**
- Install copyq (I have tried both v5.0.0 and v6.0.1)
- Attempt to launch copyq - nothing happens
- Launch from command line and get this error
`copyq: error while loading shared libraries: libKF5Notifications.so.5: cannot open shared object file: No such file or directory`

**Expected behavior**
Start the program

**Screenshots**

**Version, OS and Environment**
- Copyq version is either v5.0.0 or v6.0.1
- Operating System
```
└─# cat /etc/os-release 
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2021.4"
VERSION_ID="2021.4"
VERSION_CODENAME="kali-rolling"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"
```

Window Manager
```
└─# wmctrl -m                                                                                                                                            127 ⨯
Name: Xfwm4
Class: xfwm4
PID: 994
Window manager's "showing the desktop" mode: N/A
```

**Additional context**
I have installed Copyq on a number of other Kali instances without issue but have done a number of additional tweaks to this install, mostly done via pimpmykali - https://github.com/Dewalt-arch/pimpmykali

**Comment by robertstrom** [comment]
I was able to get it installed. Kind of a fluke though.

I went on with my configuration and installed the Dolphin file manager and happened to notice that the out put of the install included what looks like the library complained about in the copyq install error.

![image](https://user-images.githubusercontent.com/3240205/149155836-438348a2-9b24-4808-8b40-63c96c4045bd.png)

So I tried the install again and it worked.

**Comment by hluk** [comment]
That looks like a bug in the package (which I'm not maintaining).

**Comment by robertstrom** [comment]
I think it may have been that it just did not exist until I installed the Dolphin file manager. It looks like CopyQ wants **libKF5Notifications.so.5** to be there and the error was No such file or directory. Yes? No?

**Comment by hluk** [comment]
Yes, CopyQ requires KF5Notifications.
