### ISSUE TITLE
Can not paste a screenshot come from flameshot directly into Virtualbox win7 client from linux host.

### ISSUE THREAD

**Issue by zw963** [hluk/CopyQ#1878]
Before creating a new issue, see list of [known
issues](https://copyq.readthedocs.io/en/latest/known-issues.html).

**Describe the bug**
To be honest, this maybe not a issue of copyq. i just curious why this happen, and  can help locate the issue come from which 
software, copyq? or flameshot or virutalbox?

My usage is: take a screenshot from my host system. (arch linux), after do screeshot success,
i can always paste this screenshot into e.g. github issue here successful.

But, when i want to paste this image to my virtualbox guest win7(with guest additions installed) immediately 
after do screenshot success,  it not success. (in this case, the clipboard in guest win7 keep the previous copied text
no changed).

The only way to fix this is, i try paste it from copyQ once on my host system, even on the not support paste image
content place, e.g. my terminal, or a readonly file buffer, than try to paste on my win7 guest again,  win7 clipboard get
the image content now.

**To Reproduce**
1. Use flameshot create a screenshot, copy it to system clipboard. now, we can see this image item in copyq clipboard list.
2.  try to paste it in virtualbox,  not work, because system clipboard in client win7 is previous text content.
3.  try paste this image on my host linux.
4. Try paste again in guest virtualbox, it successful now.

**Expected behavior**
I can paste image in virtualbox immeeidately after i create screenshot success.

as normal when i copy text content into copyQ, i can always paste it immediately in virtualbox.

**Version, OS and Environment**
CopyQ Clipboard Manager 6.0.1
Qt: 5.15.2
KNotifications: 5.89.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Arch Linux

 ╰─ $ flameshot --version
Flameshot v0.10.2
Compiled with Qt 5.15.2

VirtualBox 6.1.30

**Comment by zw963** [comment]
BTW:

after i disable CopyQ,  then copy screenshot into system clipboard use flameshot, i can reproduce this issue that can't paste image content directly within my VirtualBox win7 client.

so, that maybe not a copyQ issue? anyway, is there exists a way to simulate paste this image on somewhere, to make my
paste image on VirtualBox can successful?

Thank you.

**Comment by hluk** [comment]
Probably bug in clipboard sharing/sync in VirtualBox.

Some time ago, I had to use simulated key presses to enter a text from host clipboard into VM - but apparently this won't work with images.
