### ISSUE TITLE
Encryption fails on CopyQ flatpak

### ISSUE THREAD

**Issue by pesader** [hluk/CopyQ#1879]
**Describe the bug**
When trying to enable the encryption feature on CopyQ, the user must click "Generate New Keys...". Upon doing so, the following error is reported by the app itself:

![image](https://user-images.githubusercontent.com/65264536/149852102-8c0b0cb3-ee7e-4b95-9bf9-38e8a47ac3f8.png)

**To Reproduce**
1. Install CopyQ flatpak package from Flathub remote
2. Open CopyQ
3. Go to "Preferences"
4. Click on "Items", then "Encryption"
5. Click on "Generate New Keys..."

**Expected behavior**
The keys should be generated, enabling the usage of the encryption feature.

**Screenshots**
Already posted above.

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Application Version: 6.0.1
 - OS: Fedora Silverblue 35
 - Desktop environment: GNOME 41.3

**Additional context**
`gpg` is installed by default in Fedora Silverblue 35.

**Comment by hluk** [comment]
`pinentry` is not available in the flatpak. I'm trying to fix that in https://github.com/flathub/com.github.hluk.copyq/pull/38 but getting various other errors.

**Comment by hluk** [comment]
I couldn't get this to work. I think some support from Flatpak will be needed: https://github.com/flatpak/flatpak/issues/2301

**Comment by asandikci** [comment]
I have the same problem with @pesader and also it seems flatpak fixed this issue in https://github.com/flatpak/flatpak/issues/2301. Is it now possible to fix @hluk ?

**Comment by hluk** [comment]
Thanks for the heads up, @asandikci.

Fixed in https://github.com/flathub/com.github.hluk.copyq/pull/52.
