### ISSUE TITLE
CI for Windows builds

### ISSUE THREAD

**Issue by m4r71n** [hluk/CopyQ#188]
Yesterday I have installed the free TeamCity Professional version on a Windows XP Pro SP3 Virtualbox which also acts as build agent. I have also installed CMake 2.8.12, Qt 4.8.5, MinGW 4.4 and Qt 5.2.1 (with MinGW 4.8).
I have set up two builds against `master` with Qt 4.8.5 and Qt 5.2.1 and two builds against `win8-fixes` also with Qt 4.8.5 and Qt 5.2.1.
Because I have some experience with TeamCity it was not much work.

If you will provide me a Windows VM with remote access I offer to you to do the inital setup.
I know a VM is not a live CI Server but it is better then nothing.

**Comment by hluk** [comment]
I've set up automated builds on [AppVeyor](https://ci.appveyor.com/project/hluk/copyq) (#347).

Only Qt 5 builds are available there.

Unfortunately tests doesn't seem to run on Windows at all (#349).
