### ISSUE TITLE
Hotkey for Pasting Last Copied Entries

### ISSUE THREAD

**Issue by moses-bowman** [hluk/CopyQ#1885]
**Is your feature request related to a problem? Please describe.**
[Ditto](https://github.com/sabrogden/Ditto) has a feature wherein you can paste the last 10 clipboard entries through custom hotkeys. Mine is set to `Ctrl` + `Numpad-N`. If CopyQ already has this, I would like to be enlightened on how to enable it. Otherwise, let this be a feature request.

**Describe the solution you'd like**
It would be nice if the limit of 10 entries would be surpassed.

**Describe alternatives you've considered**

**Additional context**

**Comment by hluk** [comment]
Try using [Select Nth Item](https://github.com/hluk/copyq-commands/tree/master/Global#select-nth-item) command (see [README.md](https://github.com/hluk/copyq-commands/blob/master/README.md) for details on how to add the command).
