### ISSUE TITLE
Dont auto paste the content after select in main panel

### ISSUE THREAD

**Issue by woshichuanqilz** [hluk/CopyQ#1889]
After select item in the main panel, copyq will auto paste the content to the current window. I dont need the autopaste, just to save to clipboard will be enough for me. Is there a way to make it? 
![image](https://user-images.githubusercontent.com/11295355/150924914-24645a3b-2268-41b8-ad4c-bd5f4e958566.png)

I already check the options in the  preference but not found related settings.

**Comment by hluk** [comment]
Disable "Paste to current window" option in Preferences (History config tab).
