### ISSUE TITLE
Image Editor Command not working

### ISSUE THREAD

**Issue by Gitoffthelawn** [hluk/CopyQ#1894]
**Describe the bug**
Setting the `Image editor command` does not result in the specified image editor loading with the selected image item when selecting "Edit" from the CopyQ toolbar.

**To Reproduce**
1. Go to Preferences > Items > Images and set `Image editor command` to a valid command (see below).
2. Click OK.
3. Notice that all the CopyQ clipboard data is deleted... has this already been reported?
4. Click the "Edit" button in the CopyQ toolbar.
5. Receive the error `Editor command failed (see logs)`.
6. Look in the logs.
7. Notice the log has a new entry: `Editor command error: Process failed to start: The system cannot find the file specified.`

**Expected behavior**
The image editor to open the selected image item.

**Version, OS and Environment**
CopyQ Clipboard Manager 6.0.1-3-g57a38270
Qt: 5.15.2
KNotifications: 5.87.0
Compiler: MSVC
Arch: x86_64-little_endian-llp64
OS: Windows 7 64-bit

**Additional context**
Here are some examples I tried for the `Image editor command`.  Because CopyQ deletes all the item content after changing any preference, this got a bit tedious.  Could that be fixed?  (If it hasn't been reported, I can write up an issue report for you to help document the issue.)

```
C:\TestForLukas\XnViewMP\xnviewmp.exe "%1"
C:\TestForLukas\XnViewMP\xnviewmp.exe %1
C:\TestForLukas\XnViewMP\xnviewmp.exe
```

I also tried several other image editors and viewers (using the same syntax), and experienced identical results.

**Comment by hluk** [comment]
Qt complains that it cannot find the executable itself (not the file to edit). It's probably problem with the `\` separators again. Can you try replacing them with `/` or `\\`?

I will try add some workaround for this that would be backwards compatible.

**Comment by hluk** [comment]
Fix for the Windows path separators is in a new development build: https://ci.appveyor.com/project/hluk/copyq/builds/42468311/artifacts

**Comment by Gitoffthelawn** [comment]
> Fix for the Windows path separators is in a new development build: https://ci.appveyor.com/project/hluk/copyq/builds/42468424/artifacts **Edit:** I had to update the patch and the dev build link.

Thank you!  Is that dev build good to use on a production box?  I'm currently using dev build v6.0.1.3, BTW.

**Comment by hluk** [comment]
> > Fix for the Windows path separators is in a new development build: https://ci.appveyor.com/project/hluk/copyq/builds/42468424/artifacts **Edit:** I had to update the patch and the dev build link.
> 
> Thank you! Is that dev build good to use on a production box? I'm currently using dev build v6.0.1.3, BTW.

The dev builds should be currently stable. If there are any problems, please open new issue.

**Comment by Gitoffthelawn** [comment]
> The dev builds should be currently stable. If there are any problems, please open new issue.

Thank you!
