### ISSUE TITLE
Text color is not inverted in tray menu

### ISSUE THREAD

**Issue by CrendKing** [hluk/CopyQ#1896]
**Describe the bug**
The text color in tray menu is black, similar to the default blue system highlight color, making text hard to read.

**To Reproduce**
1. Assign a shortcut key for tray menu
2. Press that key to bring up tray menu
3. See problem

**Expected behavior**
Like the main menu in the app, text color should invert to make text more readable.

**Screenshots**
![CopyQ 1](https://user-images.githubusercontent.com/975235/151898501-e9a1d7c7-9dea-4895-885a-b7f5c03a041f.jpg)
![CopyQ 2](https://user-images.githubusercontent.com/975235/151898504-68dcad3e-93df-4759-9ce0-c28e9e7978e9.jpg)

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Application Version: 6.0.1
 - OS: Windows 11 build 22000.438
 - Desktop environment, window manager (if applicable): N/A

**Additional context**
Tried to change the color in preference. It seems the tray menu is some standard Qt menu that uses system color instead. It seems to use the new "fixed" desktop color, which is not changeable through registry HKEY_CURRENT_USER\Control Panel\Colors.

The only thing that alters the behavior is to use one of the contrast themes, which, as expected, affects even the explorer's context menu.

**Comment by hluk** [comment]
> It seems the tray menu is some standard Qt menu that uses system color instead.

Looks like that's the case. Did you enable "Set colors for tabs, tool bar and menus" option in Appearance config tab in Preferences dialog?

**Comment by CrendKing** [comment]
It seems that option only affects the main menu in the application, to make it look like the bottom screenshot (my preference has the right text color selected). Once I disable it, the main menu becomes the same as tray menu, with problematic colors.

Is there a way to apply that option to the tray menu as well?

**Comment by hluk** [comment]
Hmm, interesting, `copyq menu` is not styled properly, but `copyq menu clipboard` (or with other tab name) seems to have the style overridden properly.

**Comment by CrendKing** [comment]
@hluk Hi. Sorry to bother. Is there any update on this issue? Thanks!

**Comment by hluk** [comment]
I managed to fix it by setting the style sheet to the menu directly. You can test it in this development version: https://ci.appveyor.com/project/hluk/copyq/builds/43701481/artifacts

**Comment by CrendKing** [comment]
It works! Thanks so much.
