### ISSUE TITLE
"Activate Items" sometimes deletes item from clipboard list

### ISSUE THREAD

**Issue by richlux** [hluk/CopyQ#1897]
**Describe the bug**
Right mouse clicking an item besides the first one in the clipboard list and selecting "Activate Items" causes the item to be removed from the list when it is copied to the clipboard. In my case, I have multiple tabs and am using the sync option in case that makes a difference. 

**To Reproduce**
1. Click on the CopyQ icon in the system tray
2. Right mouse click an item in the list and select "Activate Items"
3. The list flashes for a moment as if the item is being moved to the top, but it disappears from the list instead. The item is however,  copied to the clipboard 

**Expected behavior**
The item should move to the top of the list as well as get copied to the clipboard.

**Version, OS and Environment**
CopyQ Clipboard Manager 6.0.1
Qt: 5.15.2
KNotifications: 5.87.0
Compiler: MSVC
Arch: x86_64-little_endian-llp64
OS: Windows 10 Version 2009

**Additional context**

**Comment by hluk** [comment]
Items in CopyQ are ordered by default by file name so positions are synchronized between other app sessions. If you activate and item, it is moved to the top and filename of related files should be updated to `copyq_<current_date_time_in_utc>` so it is ordered at top.

Can you check the files in the synced folder? I.e. check if the latest modified/created file has expected content and filename.

**Comment by richlux** [comment]
I did some more testing today and it doesn’t happen all the time.  I can’t figure out a pattern to when it works and when it deletes the item.  Attached is a screen capture of what’s happening.  The first item I “Activate” works fine, but the second one never goes to the top and you can see that the item is deleted from the file system.

Thanks,
Rich

**Comment by hluk** [comment]
Oh, I can actually reproduce the behavior using the Activate Items **menu** entry - I have tested it before using just Enter and double-click and it works fine.
