### ISSUE TITLE
Hotkey to move up and down to select item

### ISSUE THREAD

**Issue by goldylucks** [hluk/CopyQ#1898]
**Is your feature request related to a problem? Please describe.**
I need to move my hand to the arrow keys to go up and down the list and select and item

**Describe the solution you'd like**
I'd like to bind a hotkey like command + j/k to move up and down the list while the main window is open

**Describe alternatives you've considered**
I'm new to mac so maybe there's a way to bind this shortcut through keyboard > shortcuts > applications, if there are available as menu commands?

**Additional context**
N/A

**Comment by hluk** [comment]
There is [Next/Previous command](https://github.com/hluk/copyq-commands/tree/master/Application#nextprevious) (see [README.md](https://github.com/hluk/copyq-commands/blob/master/README.md) for details on how to add the command).

**Comment by goldylucks** [comment]
AMAZING thank you!!

and thanks for the amazing project!!

it's awesome you keep it OS, it beats all the other tools, even the paid ones ❤️
