### ISSUE TITLE
Allow to disable CopyQ window's ability to position itself

### ISSUE THREAD

**Issue by bew** [hluk/CopyQ#1901]
**Is your feature request related to a problem? Please describe.**
On Linux, when using `herbstluftwm` (a manual tiling window manager), I configured it to manage the copyq window and center it on the screen.
When I open the main copyq window, the window flickers and mostly appear at the last known position, more often than not it just breaks (the bug may be in herbstluftwm), the window becomes unmanaged and appears at (0, 0).

**Describe the solution you'd like**
I'd like to disable the part of the code that tries hard to position the application window at a specific position and let my window manager handle this.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by hluk** [comment]
Already implemented. To disable restoring window geometry use command: `copyq config restore_geometry false`
