### ISSUE TITLE
Show main window shortcut doesn't work in Firefox/terminal

### ISSUE THREAD

**Issue by peroxy** [hluk/CopyQ#1905]
**Describe the bug**
Show main window shortcut doesn't work in Firefox (97.0 (64-bit)) or terminal (Ubuntu 21.10). It works everywhere else (Chrome, desktop, IDE, discord etc..). In terminal it works if I use the `copyq show` command, but not the shortcut.

**To Reproduce**
1. Open Firefox
2. Use shortcut Ctrl+` (I've also tried setting other keys for shortcuts but it makes no difference)
3. Clipboard window does not open

**Expected behavior**
Clipboard window should have been opened and clipboard contents displayed

**Version, OS and Environment**
CopyQ Clipboard Manager v3.13.0
Qt: 5.14.2
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Ubuntu 21.10

**Additional context**
Worked OK on Ubuntu 20.04, after I upgraded do 21.10 this issue started happening...

**Comment by hluk** [comment]
I assume this is issue with Wayland: https://copyq.readthedocs.io/en/latest/known-issues.html#on-linux-global-shortcuts-and-pasting-doesn-t-work (#27)

**Comment by peroxy** [comment]
No, I actually tried using the fix described there and it doesn't work.

**Comment by hluk** [comment]
The commands in the docs make the app run in XWayland mode, but AFAIK the global shortcuts still won't work unless you trigger them from other app that runs in XWayland.
