### ISSUE TITLE
popup() message position follow the cursor and show image

### ISSUE THREAD

**Issue by AdachiQ** [hluk/CopyQ#1906]
The issue below implements a feat similar to clipdiary, but the popup() message position is fixed. Can the message position be changed to follow the cursor (especially in the case of multiple screens).
>https://github.com/hluk/CopyQ/issues/1094

p.s. the native notifications doesn't work on my PC

popup() only shows text, how to show image?

**Comment by hluk** [comment]
The old builtin notification system is really there only to support few corner cases where the native notifications cannot be used. I'm not planning to extend the old notifications, it would be best if you can install a notification daemon.
