### ISSUE TITLE
Unload encrypted items from memory for main tab

### ISSUE THREAD

**Issue by koplo199** [hluk/CopyQ#1908]
**Is your feature request related to a problem? Please describe.**

After a reboot, I usually make use of the encrypted items feature. But these items stays in memory (as my password isn't asked) even after a long period of time.

**Describe the solution you'd like**

I would like the main tab to unload encrypted items form memory after a certain amount of time (same as unload interval?).

**Describe alternatives you've considered**

Currently, I would have to use a second tab for these encrypted items, and set the unload tab interval accordingly. It would be handier to be able to do the same for encrypted items residing in the main tab.

**Comment by hluk** [comment]
The password timeout is handled by gpg-agent, not by CopyQ. See also: https://superuser.com/questions/1172804/how-to-prevent-gpg-agent-from-timing-out-during-passphrase-collection

I haven't tested it but it should be possible to set the timeout in `~/.gnupg/gpg-agent.conf` file using `pinentry-timeout` option.

**Comment by koplo199** [comment]
It worked, thank you @hluk
