### ISSUE TITLE
Is there way to prevent chain reaction?

### ISSUE THREAD

**Issue by nemonein** [hluk/CopyQ#1909]
CopyQ : 6.0.1
OS : ArchLinux(kernel 5.16.8-arch1-1), KDE Plasma(5.24.0)

I'm a Dvorak keyboard user, and I'd like to change the short cut key to QWERTY way, which is just like macOS's Dvorak-Qwerty keyboard.

For example, I made a global hotkey ctrl + o to to send ctrl + s, and it works fine.

```
[Command]
Command="
    sh:
    xdotool keyup ctrl+o
    xdotool key ctrl+s
    exit 0"
GlobalShortcut=ctrl+o
Icon=\xf15b
IsGlobalShortcut=true
Name=ctrl s Replacement
```
If I press ctrl + o on Dvorak keyboard, CopyQ hooks the ctrl+o and changes it to ctrl + s.

I made another one, global hotkey ctrl + r to send ctrl + o.

```
[Command]
Command="
    sh:   
    xdotool keyup \"ctrl+r\"
    xdotool key \"ctrl+o\"
    exit 0"
GlobalShortcut=ctrl+r
Icon=\xf15b
IsGlobalShortcut=true
Name=ctrl o Replacement
```

This time, so called 'chain reaction' occurs.
When ctrl + r is pressed, CopyQ hooks it and send ctrl+o by xdotool. And then, CopyQ hooks ctrl+o again, then changes it to ctrl+s.
Finally, ctrl+r becomes ctrl+s.
`Ctrl+r(by keyboard press) --> Ctrl+o (by CopyQ/xdotool) --> Ctrl+s (by CopyQ/xdotool)`

I'd like to know that there could be a workaround this chain reaction. A way to distinguish between the real keypress and xdotool signal?
Thanks in advance.

**Comment by hluk** [comment]
That is not something CopyQ is supposed to handle. You can probably write a value to a temporary file and check it in the other command to stop the chain.
