### ISSUE TITLE
Can't install on standard user

### ISSUE THREAD

**Issue by xmha97** [hluk/CopyQ#1912]
Hi, I can't install this app on the standard user.

![image](https://user-images.githubusercontent.com/23485114/153858502-41629b13-81d0-43e5-8485-242c72c3ae59.png)

Please make an installation for the current user/all users.
![image](https://user-images.githubusercontent.com/23485114/149637898-eb52337d-afc2-41f5-951d-4ffd8514e329.png)
![image](https://user-images.githubusercontent.com/23485114/149637918-a791a190-0516-4a8e-8ccf-ccb6742d96b4.png)
Thanks.

**Comment by hluk** [comment]
The screenshot seems to be from a different app. Also, if Windows require admin permission to install the app to specific location, I cannot do anything about it. You can try using the portable zip file instead of installation.

**Comment by xmha97** [comment]
Please reopen this issue.
Now I realize that the problem is not solved.
When the program is to be installed only for the current user, it should not be installed in "Program Files".
![image](https://github.com/hluk/CopyQ/assets/23485114/cae28a50-cfe6-4ec0-8631-3562188da2f9)

**Comment by hluk** [comment]
> When the program is to be installed only for the current user, it should not be installed in "Program Files".

I'm not sure if I understand. Is it not possible to change the installation path?

If the default path should be different, it should be set by [Inno Setup](https://jrsoftware.org), not CopyQ itself.

**Comment by xmha97** [comment]
> > When the program is to be installed only for the current user, it should not be installed in "Program Files".
> 
> I'm not sure if I understand. Is it not possible to change the installation path?
> 
> If the default path should be different, it should be set by [Inno Setup](https://jrsoftware.org), not CopyQ itself.

The default path must be set somewhere.
I don't know but I want you to open this Ishwara so that someone else can fix it.
