### ISSUE TITLE
Copy and store part of the text from the preview item

### ISSUE THREAD

**Issue by fralbert** [hluk/CopyQ#1913]
It seems it's not possible to copy a part of the text seen in the preview part of the main window.
In fact it is copied in the Windows clipboard but not stored in the CopyQ items.

Sometimes this simple feature would be great !

![CopyQ](https://user-images.githubusercontent.com/22766601/154221695-b74c0e3d-fdfd-4d0a-b6a3-ca81df424dba.jpg)

**Comment by hluk** [comment]
That is by design: Stuff copied in CopyQ won't be added back into the app unless you explicitly paste it into the list.
