### ISSUE TITLE
Fedora 35 Gnome

### ISSUE THREAD

**Issue by jcruzs** [hluk/CopyQ#1918]
Hi!

Copyq is not working on Fedora 35, installed the RPM version and the flatpak package but not luck in any way. Moreover, thinking is was a problem of Gnome Wayland, I tried in Arch, opensuse and Copyq worked as expected.

Is there any additional steps to make copyq work in Fedora 35?

Thank you for any help in this regard. 

+ OS: Fedora 35 Gnome with Wayland

**Comment by hluk** [comment]
Not much info to go on. What does `copyq` do if you launch it from a terminal?

**Comment by jcruzs** [comment]
Yes... sorry I forgot to launch with terminal. Here is the output 

Warning: [default] QtWarning: QSocketNotifier: Can only be used with threads started with QThread
Warning: [default] QtWarning: Activating Wayland clipboard took 5000 ms
ERROR: [default] QtCritical: Failed to activate Wayland clipboard

I tried to launch by using copyq --platform xcb but definitely didn't work out. Moreover, I add

 env QT_QPA_PLATFORM="xcb" copyq 

Taking into account that works under suse, arch on wayland I believe the problem is probably with Fedora.

Thank you again

**Comment by jcruzs** [comment]
This is the log from Copyq

Warning [2022-02-23 13:18:55.686] <monitorClipboard-17072>: [default] QtWarning: Activating Wayland clipboard took 5000 ms
ERROR [2022-02-23 13:18:55.688] <monitorClipboard-17072>: [default] QtCritical: Failed to activate Wayland clipboard
Warning [2022-02-23 13:18:57.279] <Server-17053>: [qt.qpa.wayland] QtWarning: Wayland does not support QWindow::requestActivate()
Warning [2022-02-23 13:18:57.286] <Server-17053>: [qt.qpa.wayland] QtWarning: Wayland does not support QWindow::requestActivate()
Warning [2022-02-23 13:19:01.695] <Server-17053>: [qt.qpa.wayland] QtWarning: Wayland does not support QWindow::requestActivate()
Warning [2022-02-23 13:19:01.698] <Server-17053>: [qt.qpa.wayland] QtWarning: Wayland does not support QWindow::requestActivate()
Warning [2022-02-23 13:19:01.845] <Server-17053>: [qt.qpa.wayland] QtWarning: Wayland does not support QWindow::requestActivate()
Warning [2022-02-23 13:19:01.854] <Server-17053>: [qt.qpa.wayland] QtWarning: Wayland does not support QWindow::requestActivate()
Warning [2022-02-23 13:19:02.145] <Server-17053>: [qt.qpa.wayland] QtWarning: Wayland does not support QWindow::requestActivate()
Warning [2022-02-23 13:19:02.151] <Server-17053>: [qt.qpa.wayland] QtWarning: Wayland does not support QWindow::requestActivate()
Warning [2022-02-23 13:19:02.546] <Server-17053>: [qt.qpa.wayland] QtWarning: Wayland does not support QWindow::requestActivate()
Warning [2022-02-23 13:19:02.551] <Server-17053>: [qt.qpa.wayland] QtWarning: Wayland does not support QWindow::requestActivate()

**Comment by hluk** [comment]
I haven't seen any issues with CopyQ on Wayland on Fedora 35, but I'm not using Gnome.

Perhaps some additional packages related to Wayland protocols are required. But on my system, I see only `gnome-session-wayland-session` that could be related to this.

Can you try launching `env COPYQ_LOG_LEVEL=DEBUG copyq` to see debug log?

**Comment by jcruzs** [comment]
Here is the log (I tried to copy a text after running the command):

Warning: [default] QtWarning: QSocketNotifier: Can only be used with threads started with QThread
DEBUG: Server "/home/javier/.config/copyq/.copyq_s" started.
DEBUG: [default] QtInfo: Using Wayland clipboard access
Warning: [default] QtWarning: Activating Wayland clipboard took 5000 ms
ERROR: [default] QtCritical: Failed to activate Wayland clipboard
DEBUG: Geometry: Window "MainWindow": Move window: 984, 479
DEBUG: Geometry: Window "MainWindow": Restore geometry "Options/MainWindow_geometry": 645x421,0,0 -> 935x600,984,479
DEBUG: Loading configuration
Warning: Failed to set global shortcut "Meta+Ctrl+Alt+V" for command "Show/hide main window".
DEBUG: Configuration loaded
DEBUG: Starting monitor
DEBUG: Executing: copyq --clipboard-access monitorClipboard
DEBUG: Starting callback: onStart
DEBUG: Executing: copyq onStart
DEBUG: Tab "&clipboard": Loading items
DEBUG: Tab "&clipboard": 161 items loaded
DEBUG: Executing: copyq eval -- runMenuCommandFilters()
DEBUG: Updating tray menu
Warning: [qt.qpa.wayland] QtWarning: Wayland does not support QWindow::requestActivate()
Warning: [default] QtWarning: This plugin does not support setting window opacity
DEBUG: Geometry: Window "MainWindow": Move window: 982, 440
DEBUG: Geometry: Window "MainWindow": Restore geometry "Options/MainWindow_geometry": 935x600,984,479 -> 935x600,983,478
DEBUG: Got main window close event.
DEBUG: Saving items on application state change (2)

**Comment by hluk** [comment]
I'm not sure now the clipboard should be working at all when running the app in Wayland mode on Gnome (`env QT_QPA_PLATFORM="wayland" copyq`).

Here is the Gnome issue: https://gitlab.gnome.org/GNOME/mutter/-/issues/1602 ("Third-party clipboard managers support on wayland")

BTW, the clipboard should work when launched with `QT_QPA_PLATFORM="xcb"` but it is possible that it won't notice clipboard changes from Wayland native apps.

**Comment by hluk** [comment]
Yup, it looks like the clipboard protocol is not implemented on Gnome.

Tested in nested Gnome session:

```
❯ gnome-shell --nested
```

Now if you run wl-paste in watch mode in another terminal, it prints an error:

```
❯ env WAYLAND_DISPLAY=wayland-0 wl-paste --type text/plain --watch echo
Watch mode requires a compositor that supports wlroots data-control protocol
```

**Comment by jcruzs** [comment]
Thank you for the answer. I really like Fedora but copyq has been with me for a long time. I will move to opensuse or endeavour where is working without a problem and I will try again when fedora 36 is release.

Have a nice day!
