### ISSUE TITLE
Clean moved images from other formats

### ISSUE THREAD

**Issue by HyperCriSiS** [hluk/CopyQ#1920]
Hi,

I use the builtin command to move images to another tab.
This works very well but some images contain additional formats, for example when you copy an image from Outlook.
It is not possible to paste this image to some applications with this additional formats.
![grafik](https://user-images.githubusercontent.com/11708192/156028258-79a48416-1e27-495d-909e-50eb88864de2.png)

How can I change the command to remove them?

Thanks and regards,
Hyper

**Comment by hluk** [comment]
To store images without the HTML you can add following command (it should probably go at the top of command list):

```ini
[Command]
Automatic=true
Command="
    copyq:
    function hasImage(formats) {
        for (var format of formats.values()) {
            if (format.startsWith('image/'))
                return true
        }
        return false
    }

    if ( hasImage(dataFormats()) ) {
        popup('Dropping HTML image format')
        removeData(mimeHtml)
    }"
Icon=\xf03e
Input=text/html
Name=Remove HTML from images
```

([Here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them).)

**Comment by HyperCriSiS** [comment]
Thank you, works perfectly!
