### ISSUE TITLE
Possible to use VSCode as external editor (Ctrl+E) on Windows?

### ISSUE THREAD

**Issue by carloscadux** [hluk/CopyQ#1921]
Hi,

I'd appreciate you help.

I fount the command `code --wait %1` in CopyQ FAQ and thought it refers to VSCode:
[Why does my external editor fail to edit items?](https://copyq.readthedocs.io/en/latest/faq.html?highlight=external%20editor#why-does-my-external-editor-fail-to-edit-items)

However, setting up `code --wait %1` in 'Preferences>History>External editor command' didn't run VSCode.

a) Is it possible to use VSCode as external editor (Ctrl+E) on Windows?

b) Is there any way to set CopyQ external editor to run VSCode portable, instead of the installed version?
Actually I just installed VSCode to test if it would work with CopyQ using the mentioned command, but I use the portable version instead.

Thank you!

**Comment by hluk** [comment]
What does the CopyQ log say (F12 key from the main window)? Maybe `code` executable is not found.

**Comment by nmat** [comment]
It seems the file is not found when using Ctrl+E in that way.

I have tested:

"C:\Users\user\AppData\Local\Programs\Microsoft VS Code\Code.exe" "%1"

code --wait %1

code %1

code "%1"

but the results are the same. It can't find the file. And I can't seem to get a verbose output on how it tries to send the command.

I also tested to run cmd and with:

code filename

and that works. So I think something strange is going on when it tries to render the file path to the %1 variable.

**Comment by carloscadux** [comment]
a) Since VSCode has tree possibilities for installing (listed below), is CopyQ expected to work just with one of them? Or despite the path, will CopyQ look for 'Code.exe' entry that is in the registry?

b) If CopyQ is expected to work just with a certain path of VSCode, can I manually edit a CopyQ setting to force it to work, for instance, with my portable installation? 

User installer
C:\Users\user\AppData\Local\Programs\Microsoft VS Code\Code.exe

System installer
C:\Program Files\Microsoft VS Code\Code.exe

Portable installer (my path)
Z:\VSCode\Code.exe

![image](https://user-images.githubusercontent.com/7339389/156882497-16d5bded-a248-4620-8a15-1d647c28646b.png)

**Comment by hluk** [comment]
Can you test it with the following editor command?

```
"C:/Users/user/AppData/Local/Programs/Microsoft VS Code/Code.exe" --wait
```

**Comment by nmat** [comment]
> Can you test it with the following editor command?
> 
> ```
> "C:/Users/user/AppData/Local/Programs/Microsoft VS Code/Code.exe" --wait
> ```

I get the following: 

| Unexpected token 'wait' in expression or statement.

**Comment by ty-lab** [comment]
> Can you test it with the following editor command?
> 
> ```
> "C:/Users/user/AppData/Local/Programs/Microsoft VS Code/Code.exe" --wait
> ```

This command can be executed
The above problem does not occur
> ```
> "E:/VSCode/Code.exe" --wait
> ```

**Comment by carloscadux** [comment]
> > Can you test it with the following editor command?
> > ```
> > "C:/Users/user/AppData/Local/Programs/Microsoft VS Code/Code.exe" --wait
> > ```
> 

**=> The command above didn't work.**


> This command can be executed The above problem does not occur
> 
> > ```
> > "E:/VSCode/Code.exe" --wait
> > ```

**=> The command above worked.** 👍

Just to double-check, I'm using the commands in Preferences>History>Editor:

![image](https://user-images.githubusercontent.com/7339389/157417661-b6b9dff3-0a07-4b2c-85bd-0632ee8824d8.png)

**Comment by ty-lab** [comment]
> "C:/Users/~~your own username~~/AppData/Local/Programs/Microsoft VS Code/Code.exe" --wait

It is wrong to copy the command directly, you need to change the command of the second 'user' (the part indicated by the strikethrough) to your own username

**Comment by carloscadux** [comment]
> > "C:/Users/~your own username~/AppData/Local/Programs/Microsoft VS Code/Code.exe" --wait
> 
> It is wrong to copy the command directly, you need to change the command of the second 'user' (the part indicated by the strikethrough) to your own username

Sure thing. Thanks. Now it works 👍
