### ISSUE TITLE
Tab not clearing after specified amount of time

### ISSUE THREAD

**Issue by reggiiie** [hluk/CopyQ#1922]
**To Reproduce**
1. Go to history in preferences
2. Set the 'unload after an interval' to 5
3. tab doesn't get cleared after the interval, or at any point except for copyq exitting, tab also gets cleared whenever I press ok in the preferences, whether I changed anything or not

**Expected behavior**
Setting the interval, waiting 5 minutes and any entries that were there before that time period should have been cleared.

**Screenshots**
screenshot of my settings:
![image](https://user-images.githubusercontent.com/81920698/156662413-8f99bf83-aaf8-475a-8bf6-69db4bac12bf.png)

**Version, OS and Environment**
output of copyq -v:
```
CopyQ Clipboard Manager 6.0.1
Qt: 5.15.2
KNotifications: 5.91.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Arch Linux
```

**Comment by hluk** [comment]
"Unload tab after an interval in minutes" option only indicates when to unload the tab data/items from main memory on inactivity; it does not clear/remove the stored items on disk.

**Comment by reggiiie** [comment]
> 

oh my bad, is there an option to clear the clipboard after certain amount of time then?

**Comment by hluk** [comment]
> oh my bad, is there an option to clear the clipboard after certain amount of time then?

One way to do this is to set the Unload interval option and also set the tab to synchronize to an empty path:

![image](https://user-images.githubusercontent.com/38054/157039587-24b36431-1cef-4ac5-adb6-c073f4f7e562.png)

That way the items will be kept only in main memory and not saved on disk. The data will be lost the tab is unloaded from memory - this will also happen when the app restarts or configuration changes.
