### ISSUE TITLE
CopyQ too high RAM consumption

### ISSUE THREAD

**Issue by Clemens-Ratte-Polle** [hluk/CopyQ#1928]
Version : CopyQ 6.0.1 (will install 6.1 hereafter)
After a week 127 MB and also too much HD usage.
After Exit and restart only 24 MB.
What happened?

**Comment by hluk** [comment]
Possibly multiple tabs are loaded? You can try opening Preferences and clicking OK - this should cause the tabs to unload from memory (except the current tab).

BTW, there is a very cool and easy-to-use GUI app [GammaRay](https://github.com/KDAB/GammaRay#readme) that can inspect loaded objects in Qt apps like CopyQ. It can pinpoint some issues like unallocated old menu items (this happened before).

**Comment by Clemens-Ratte-Polle** [comment]
no effect clicking OK in preferences.
Still 120 MB now.
After CopyQ restart 33MB.
I delete every graphic, image, photo imediately every time, so nothing of this in memory.

GammaRay? I have to "build" it?
No experience.

**Comment by Clemens-Ratte-Polle** [comment]
my Harddisk is heavy working as shown in Process Manager, not space using.

CQ is growing by time and my usage. I copy, paste and delete text very much: hundreds a day.
Perhaps the real inner program delete from memory does not work properly?

**Comment by hluk** [comment]
> my Harddisk is heavy working as shown in Process Manager, not space using.

The app should only write data to disk after a longer interval (e.g. ~5 minutes after adding new item to tab) or when the application is deactivated (the main window loses focus). [Enable debug logs](https://copyq.readthedocs.io/en/latest/faq.html#how-to-enable-logging) to see when CopyQ saves the data to disk (F12 from main window to show the logs).

You can also change the intervals for saving and disable saving on app deactivation. For example, to disable saving on deactivation run the following command:

```
copyq config save_on_app_deactivated false
```

Here are the internal options you can change (the delays are in milliseconds):

```
save_delay_ms_on_item_added
  Tab save delay after an item is added to the tab
save_delay_ms_on_item_edited
  Tab save delay after an item is edited in the tab
save_delay_ms_on_item_modified
  Tab save delay after an item is modified in the tab
save_delay_ms_on_item_moved
  Tab save delay after an item is moved in the tab
save_delay_ms_on_item_removed
  Tab save delay after an item is removed from the tab
save_filter_history
  Save and restore history of item filters
save_on_app_deactivated
  Save unsaved tabs immediately after the app is deactivated (main window loses focus)
```

> CQ is growing by time and my usage. I copy, paste and delete text very much: hundreds a day. Perhaps the real inner program delete from memory does not work properly?

Most of the places where memory is allocated for the app are properly sanitized in the code. It is still possible that there are some memory leaks - Qt memory management/ownership is sometimes difficult to understand.

**Comment by reagle** [comment]
On my M1 Mac Mini, CopyQ can grow to hundreds of MB in a day. I quit and relaunched this morning (~50MB), and 7 hours later its at 600MiB in Activity Monitory. CopyQ 6.1.0 is one of my last Rosetta apps I'm running on this machine  (the other is DavMail) and they do tend to leak memory on this machine. (Less so on my M1 AirBook.)

macOS 12.3.1 21E258 arm64

<img width="980" alt="Screen Shot 2022-04-25 at 15 25 50" src="https://user-images.githubusercontent.com/596814/165159944-c8867750-c341-44b3-8cbb-79ce7461ab70.png">

**Comment by hluk** [comment]
Is this just on macOS? The code for that platform is written in Objective C and uses lots of OS-specific functions. Unfortunately, I'm not familiar with this and don't have proper way to test things.

**Comment by hluk** [comment]
Just checked with **GammaRay** and it seems the tool bar is leaking memory:

![image](https://user-images.githubusercontent.com/38054/165369919-c9baa546-02d3-48de-8bd2-000e8fec80bd.png)

Qt bug: https://bugreports.qt.io/browse/QTBUG-87774

I will try to implement a workaround and check other places.

**Comment by hluk** [comment]
> Just checked with **GammaRay** and it seems the tool bar is leaking memory

Perhaps I'm misinterpreting the number. The number grows only if GammaRay is monitoring the app. There is no problem if I connect GammaRay later.

**Comment by reagle** [comment]
#1873 speaks to an M1/universal build, and I have found that Rosetta apps *tend* (not completely, though) to be the ones that [leak memory since Big Sur and Monterey](https://www.macworld.com/article/549755/m1-macbook-app-memory-leaks-macos.html).

**Comment by reagle** [comment]
BTW: I created a script that runs in the morning and restarts copyq, because at the end of the days it's 500MB.

	echo "killing copyq"
	/opt/homebrew/bin/copyq exit
	sleep 2
	open /Applications/CopyQ.app

<img width="537" alt="Screen Shot 2022-06-22 at 16 52 51" src="https://user-images.githubusercontent.com/596814/175134326-edeecdfa-a0e9-4039-8178-c0588483d331.png">

**Comment by hluk** [comment]
Is this still a problem in recent versions?

**Comment by reagle** [comment]
I'll stop killing/restarting copyq every morning and see what happens over a few days.

**Comment by reagle** [comment]
I've stayed on 7.1.0-g42c02f2d-master because of #2637, but I'll grab the latest and see; if I'm able to run it, give me a few days.

**Comment by reagle** [comment]
On the morning of the 21st I grabbed 9.1.0 and when run show 3 processes. Clearly, the startup footprint is above ~50MB from the start of this thread. (Exporting/saving my clipboard yields a 573K cpq file; is 250MB of memory apt for that?) On the plus, side, my memory isn't growing by ten times over the course of a day.

| morning | cq1       | cq2        | cq3       |
| ------- | ------- | -------- | ------- |
| 21st    | 59.0 MB | 243.0 MB | 27.5 MB |
| 22nd    | 86.9 MB | 277.3 MB | 73.5 MB |
| 23rd    | 89.9 MB | 282.3 MB | 74.3 MB |

**Comment by reagle** [comment]
cq2 was above 300MB at the end of the day 2024-10-23 . I just restarted it and it is at 109MB fresh. (Of course, I don't know anything about Mac memory management or reporting, so I don't know if this good, bad, or otherwise.)

**Comment by hluk** [comment]
For me, the memory footprint is:
- ~28 MiB right after starting the app
- ~47 MiB after opening the main window
- ~80 MiB after browsing through tabs and items
- ~100 MiB after opening and browsing through Preferences
- opening Commands dialog needs about another 40 MiBs (I have over 200 commands for testing and experimenting) but that goes back down to the previous value after closing the window

It does not get much higher than that after a few days use. But I think I would notice only if there is a serious leak.

**Comment by reagle** [comment]
I'm curious, how big is your cpq export for those sizes?

**Comment by hluk** [comment]
> I'm curious, how big is your cpq export for those sizes?

I don't use that functionality, but I recently cleared my tabs (to back up the whole config and data directory), so I have less than 1000 items per tab (2 tabs with ~700 items, others with much less). Exporting everything results in ~28 MiB file.

BTW, item count affects the memory requirements much less in the recent CopyQ versions, since larger item data are loaded when needed (by default).

**Comment by reagle** [comment]
I don't either, I just thought it's a good way to index the relative sizes of data to how different OSs might report memory use. My cpq file is fraction the size of yours (573K to 28MiB) but I'm using much more memory apparently. I wonder what other MacOS users might report.

**Comment by Bellavene** [comment]
~170 MB even after relaunch. It looks for me a bit high.
Is there a possibility to turn off the built-in GUI and some other stuff that might be unneded? I use a FZF script instead anyway.

**Comment by hluk** [comment]
> Is there a possibility to turn off the built-in GUI and some other stuff that might be unneeded?

Try disabling any plugins you don't use in Item config tab:

![Image](https://github.com/user-attachments/assets/1928bd81-9920-462b-b325-2a7870bc5938)

Not sure if there is anything else that could help to reduce the memory usage noticeably.

**Comment by Bellavene** [comment]
Thank you. But is there a solution to entirely disable the GUI part?

**Comment by hluk** [comment]
> But is there a solution to entirely disable the GUI part?

Unfortunately, no.

**Comment by Bellavene** [comment]
Disabled those items, but it reduced only 5 MB of RAM usage...
It is almost perfect, but the QT UI and minor memory leaks are making me sad : (

**Comment by WaveLong** [comment]
this problem appears on windows too. it's more serious than macos

<img width="1326" height="157" alt="Image" src="https://github.com/user-attachments/assets/cf1a6305-ab11-4985-a3a0-106e935327eb" />

**Comment by lisansas** [comment]
> this problem appears on windows too. it's more serious than macos
> <img alt="Image" width="1326" height="157" src="https://private-user-images.githubusercontent.com/31360595/505623562-cf1a6305-ab11-4985-a3a0-106e935327eb.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjE0NTQ0MjQsIm5iZiI6MTc2MTQ1NDEyNCwicGF0aCI6Ii8zMTM2MDU5NS81MDU2MjM1NjItY2YxYTYzMDUtYWIxMS00OTg1LWEzYTAtMTA2ZTkzNTMyN2ViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDI2VDA0NDg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwOTEyMDk0OWFjYzc5MGY2N2MzZWJiNDhjMGUzYmVmYTU0ZGM1OTRiZjVkY2MxMjIzNzlkZDk5ZWNlYzk3YjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uB5oiHxBCV2OOlwL1lUaCB1-MOYhKNhSahJtYHw1LJ0">

me too.

Memory usage keeps climbing. Since I never shut down my computer, it once hit over 8GB.

For reference, when the program  started, this number was 100MB.
