### ISSUE TITLE
Couldn't make "Edit using bitmap application" work. Help please.

### ISSUE THREAD

**Issue by carloscadux** [hluk/CopyQ#1936]
Hi. I'd appreciate your help.

Following this [[CopyQ documentation](https://copyq.readthedocs.io/en/latest/images.html#editor)](https://copyq.readthedocs.io/en/latest/images.html#editor) I tried to set a bitmap Editor, but didn't have success.

I added the bitmap application in `Items > Images > Image editor command` then I triggered the command `Edit with Editor (Ctrl+E)`, as shown in the screenshot. I double-checked it was an image file (F4).

Tried several command combinations:

`"K:\ksnip\ksnip.exe"`

`"K:\ksnip\ksnip.exe" %1`

`"K:\ksnip\ksnip.exe" --wait %1`

`"K:\ksnip\ksnip.exe" --wait`

Although in the examples above I'm showing the app ksnip: [[ksnip/ksnip (github.com)](https://github.com/ksnip/ksnip/releases)](https://github.com/ksnip/ksnip/releases), I tried other apps as well without success.

=> Am I doing something wrong? What else could I try?

Thank you,

Carlos

![image](https://user-images.githubusercontent.com/7339389/159015447-4d688f29-5288-47a0-914b-b78919ebaabd.png)

**Comment by hluk** [comment]
Please use `/` instead of `\` in file/executable paths.

**Comment by carloscadux** [comment]
> Please use `/` instead of `\` in file/executable paths.

Thanks, it worked! 
Just added the simple path having `/` changed. 
It wasn't necessary to use neither `--wait` or `%1`

**Comment by hluk** [comment]
This should improve in the next release - I've implemented some workaround so that `\` can be used when command starts with a Windows path.

**Comment by jonathan-f-silva** [comment]
Another detail: besides using `/` instead `\`, the path must not have spaces on it.
