### ISSUE TITLE
CopyQ : Context delete to trash missing?

### ISSUE THREAD

**Issue by Clemens-Ratte-Polle** [hluk/CopyQ#1943]
CopyQ 6.1.0 
Right click on marked items in CQ shows 2 functions to delete:
- Move to trash (undoable) Del
- Remove (? in German Entfernen) with no Shortcut.
https://i.ibb.co/YXCRgFZ/2022-03-26-171734.png

I used the last and all deleted items were totally lost and NOT in the trash tab. o_O
WTF?!
There should be a Warning by the last option to delete in the context menu!
Yes, then i realized that the first option was the right but with a wrong description: it is undoable!

How could i get back my deleted items?
thx

**Comment by hluk** [comment]
> How could i get back my deleted items?

If the items are deleted, then there is no way to get them back. CopyQ does not back up data by itself.

I'm assuming the Remove menu action is the default and the Move to Trash is the custom action created from a command.

Sorry for the confusion. It would be better if the commands can customize the item deletion but there is currently no way to do this. Related to very old issue #59.

**Comment by Clemens-Ratte-Polle** [comment]
thx
