### ISSUE TITLE
Flickering / odd placement

### ISSUE THREAD

**Issue by nPHYN1T3** [hluk/CopyQ#1946]
**Describe the bug**
When calling copyq toggle on my top left most screen it will "snap" to the inside (right) edge of that screen but then flicker on the screen next to it.

If I launch on the top center screen it will snap to the left side where it flickers if I've launched it on the left screen.

If I launch on the top right screen it centers itself.

If I launch from the bottom left it randomly pops up on the right side of the top left screen or the left of the top center screen and some times will jump back and forth.

If I launch from the bottom right screen it centers on the top right screen.

**To Reproduce**
Have copyq running then call copyq toggle.

**Expected behavior**
For the menu to center on the screen with the mouse or pop up where the mouse is...and not flicker jitter and jump around.

**Screenshots**

**Version, OS and Environment**
CopyQ Clipboard Manager 6.1.0
Qt: 5.15.2
KNotifications: 5.91.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Garuda Linux
No DE / CTWM
nVidia 510.54
GTX 1060
GTX 1660
X11

**Additional context**
I've tried with and without picom and "Open Windows on Current Screen." Neither affects the behavior.
As for opening on the correct screen as denoted by the mouse. copyq is locked to the XScreen the terminal that launched it on. If I launch from XScreen :0.0 from left to right calling copyq toggle it will center on the bottom left screen, snap to the left edge of the bottom center screen and center again on the bottom right screen. - No flickering occurs when running on XScreen 0.0 though it will still jump occasionally from the left/center screens but never the right most.

**Comment by hluk** [comment]
You might get better behavior on some window managers if you completely disable the application-side window geometry restoring with the following command:

```
copyq config restore_geometry
```

**Comment by nPHYN1T3** [comment]
Just tried that and it actually made it worse. Rather than flicker on one screen with a "normal" window on the other now it draws almost completely normal on two screens edge to edge with artifacts all over.

**Comment by hluk** [comment]
Sorry, I pasted incomplete command in my previous comment:

```
copyq config restore_geometry false
```

You need to restart the app for the change to take effect.

I think the flicker is caused by some new code that is trying to restore window geometry when window manager decides to move the window to a different screen. I will try to add some safe guard so it is not called recursively.

**Comment by hluk** [comment]
I managed to reproduce and fix the behavior on kwin (KDE window manager) when moving to a border between screens and triggering show/hide. It is quite possible that the behavior broke somewhat on other window managers - specifically `sway` - I do not have the time to verify and fix it again there.

The window management is a mess, perhaps it would be better to just drop all the custom implementation from the app. :disappointed:

**Comment by nPHYN1T3** [comment]
Unfortunately video setups become a crazy topic fast. With CTWM because it's old and lacks all the fancy features common DE WM's have. There is no "screen" delineation really. So for example under XFCE if I go fullscreen on something it only uses a single panel because it "knows" each panel is a separate screen. Under CTWM fullscreen is the whole XScreen so for the two primary XScreens that means 5760x1080. So depending on how CopyQ is trying to figure out where to place itself it might end up with very different results and or confuse itself.

This is a tad unrelated but still related but I've noticed over the years a lot of games will for example Query window size in one poll but later for something else query total screen size. This causes some really broken behaviors.

**Comment by hluk** [comment]
I moved fully to Wayland (used KWin and Sway) without many issues - KWin no longer crashes, screen sharing finally works and high DPI scaling is better than on X11. Of course some apps still don't work that well, even when using the XWayland (the X11 app "emulation" on Wayland). E.g. mouse in games gets stuck - thankfully, I can still play some games with gamepad. :video_game:
