### ISSUE TITLE
CopyQ does not paste on MacOS Moneterey 12.2.1

### ISSUE THREAD

**Issue by B1T3X** [hluk/CopyQ#1949]
Before creating a new issue, see list of [known
issues](https://copyq.readthedocs.io/en/latest/known-issues.html).

**Describe the bug**
I am unable to paste using the tray.
I have mapped Option+v to open the tray menu, the tray menu does open but when I select an item and press Enter, the item is not pasted. I then have to press Cmd+v to paste the item, which is a bit annoying.
Relevant settings:
"Paste to current window" is ticked
Accessibility permissions have been granted (unticked/reticked & uninstalled/reinstalled multiple times as outlined by the solution proposed in #1030)

**To Reproduce**
1. Open the tray menu
2. Select an item either by click on it or by pressing Enter
3. Expect the value to be pasted but be disappointed :(

**Expected behavior**
When pressing enter on a tray menu item, it should be pasted to the window

**Version, OS and Environment**
CopyQ Clipboard Manager 6.1.0-gf6684d39-v6.1.0
Qt: 5.15.2
KNotifications: 5.87.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: macOS 12.2

Note: Installed using Homebrew

**Comment by konstantin83** [comment]
Same here on Monterey. Neither Enter, nor double click on item do not paste anything to active input or textarea.

CopyQ has both:
- Full rights in system settings -> universal access
- Active checkbox to Paste selected item in CopyQ settings.

But none of it helps.

Please provide some kind of advice on how to fix this

**Comment by robertstrom** [comment]
Same here.  I have an Intel Mac Pro and an Apple Silicon MacBook Pro. I am willing to do testing, etc.

**Comment by konstantin83** [comment]
Any progress?

**Comment by konstantin83** [comment]
> @ajorpheus Thanks for the fix.
> The fixed development build is here: https://github.com/hluk/CopyQ/actions/runs/2448721990#artifacts

Downloaded it, then tested it and still nothing. Maybe I'm doing something wrong?Downloaded Downloaded 
Here is the video of my problem - https://take.ms/i9rF8

PS: Also as you can see there is a serious problem with closing CopyQ window after editing settings.

**Comment by hluk** [comment]
Thanks for the recording. Let me reopen this. :shrug:

**Comment by ajorpheus** [comment]
@hluk , do you want me to reinstate the log statements so that, at the very least, we can check if the fix is actually being used or whether it is something specific to @konstantin83 ?

Could @B1T3X try to check if the dev build linked above fixes the issue?

**Comment by konstantin83** [comment]
@ajorpheus thank you very much! It halped but from the second time. First I didn't have CopyQ in "Preferences -> Security and Privacy -> Privacy -> Accessibility" menu at all. So there was nothing to delete.
So I removed CopyQ from Applications folder and then reinstalled it. After that I tried to paste with click or enter, and still nothing happened.

Then I manually added CopyQ to Accessibility list. Still nothing.

Then I unchecked it in list and after that deleted it. Then again deleted CopyQ app from Applications folder. And reinstalled in again.

After the third installation it asked me to enable Accessibility for CopyQ after the first attempt to paste with keyboard. I did and it works now. Thank you!

**Comment by ajorpheus** [comment]
@konstantin83  That is awesome ! :)

Glad it is working for you now! Accessiblity can be a bit messy in macOS :( 

Here is hoping they did things better in Ventura!

**Comment by ajorpheus** [comment]
@Udist-next , it would be great to get some more evidence that the fix is working. Would you mind testing the development build please?

**Comment by Udist-next** [comment]
> @konstantin83 May I please ask if you removed CopyQ from Accessibility after instaling the development build?
> 
> Here are the steps I had to follow when I was testing the fix with new versions of CopyQ:
> 
> 1. Delete old CopyQ from Applications
> 2. Delete CopyQ from Preferences -> Security and Privacy -> Privacy -> Accessibility   like so:
>    ![image](https://user-images.githubusercontent.com/1554671/172330622-925430a9-8cef-429a-b702-d5ea720438d2.png)
> 3. Install and open the new version of CopyQ.
> 4. Start CopyQ, select item and press enter.   This should then prompt you to enable Accessiblity for CopyQ.
> 5. Enable Accessiblity for CopyQ, then quit and relaunch CopyQ.
> 6. Try step 4 again. Profit !! (Hopefully!)
> 
> ( I think these steps are somewhere on the FAQ itself).

@ajorpheus Nice, it works! Thanks!

**Comment by ajorpheus** [comment]
@hluk : With my fix, at least 3 users have reported the issue as resolved (@ajorpheus , @Udist-next  and @konstantin83 ).

Would you be happy to close the issue based on this?

**Comment by itairaz1** [comment]
Still happened to me on 6.2, tried to remove and add permission back and restart.
Rolling back to 6.0 solves the issue

**Comment by maxwxyz** [comment]
I am having this problem with 10.0.0 on Intel MBP macOS Ventura 13.7.6 (22H625)
I've repeated the steps mentioned here: https://github.com/hluk/CopyQ/issues/1949#issuecomment-1148348106 but it does not fix the issue. When pasting from the tray menu or main window (or at least trying to paste) the CopyQ icon briefly shows up in the dock and closes nothing more happens. 
The selected menu entry is moved to the top, so a normal cmd+v pastes it, but it is not pasted from CopyQ although set in the settings.
Can this issue be reopened?

**Comment by romanskorobagatko** [comment]
@maxwxyz Deleting CopyQ from Preferences -> Security and Privacy -> Privacy -> Accessibility and adding it again fixed it for me on macOS Sequoia 15.7.
