### ISSUE TITLE
Better deletion

### ISSUE THREAD

**Issue by Raihan2387468** [hluk/CopyQ#1950]
I thought it would've been better if there was another delete option that deletes everything, except for pinned stuff. It would not warn about pinned stuff and then not do anything. It would straight up ignore pinned stuff and delete everything else. It could also be implemented as a toggle in settings so that `CTRL + A` and the existing delete option do that.

**Comment by gabbymouth** [comment]
Just in case you don't know, There's ItemSelection(tabName).selectRemovable().removeAll();
Which I used today and is covered in the Copyq Scripting API doc.

**Comment by hluk** [comment]
There is "Clear Current Tab" predefined command (menu item and toolbar action). To add it:
1. Open Commands dialog (F6 shortcut)
2. Click Add button
3. Select "Clear Current Tab" and click OK
4. Click OK button to save changes in Commands dialog
