### ISSUE TITLE
Snoretoast.exe detected as malicious by virustotal !

### ISSUE THREAD

**Issue by Eddcapone** [hluk/CopyQ#1957]
I uploaded the file "snoretoast.exe" from the project into virustotal and I get 100% Malicious by Cynet.

2/67 flagged it as a virus.

**Comment by Eddcapone** [comment]
I downloaded the file from this github repository.

**Comment by hluk** [comment]
This is very likely a false positive.

Try the latest development version - Snoretoast there has been updated to v0.8.0: https://ci.appveyor.com/project/hluk/copyq/builds/43166128/artifacts
