### ISSUE TITLE
Provide multiple TARGETS for new clip automatically

### ISSUE THREAD

**Issue by mviereck** [hluk/CopyQ#1960]
**Is your feature request related to a problem? Please describe.**
If sending a clip with `xclip`, I can only declare one target. (A limitation of xclip.)
It appears in already running CopyQ.
But if I check TARGETS, only one, e.g. `STRING` is available.
I need to either manually choose the clip in CopyQ dialogbox or use `copyq select 0` to get more TARGETS.
```
$ xclip -in -selection clipboard -t STRING <<< "hello world"

$ xclip -out -selection clipboard -t TARGETS
TARGETS
STRING

$ copyq select 0

$ xclip -out -selection clipboard -t TARGETS
text/plain
UTF8_STRING
STRING
TEXT
application/x-copyq-owner
TARGETS
MULTIPLE
TIMESTAMP
SAVE_TARGETS
```

**Describe the solution you'd like**
It would be nice if CopyQ would provide multiple TARGETS automatically if it receives a new clip without needing further interaction.

**Comment by hluk** [comment]
CopyQ by default does not change clipboard/selection, only monitors it. Overriding clipboard when change proved to be not very good idea - it can confuse some applications (basically drops any internal data an app can have).

Also, I'm not sure what is the goal here.
