### ISSUE TITLE
PASTE AND FORGET 2022

### ISSUE THREAD

**Issue by elmaure** [hluk/CopyQ#1962]
Hi, im constantly copying and pasting and sometimes i need only to use the item once, so went to de docs and see "paste and forget" script but it looks like its outdated or something. Someone can provide a working code please? thanks

**Comment by hluk** [comment]
I assume you mean [this command](https://copyq.readthedocs.io/en/latest/command-examples.html?highlight=paste%20and%20forget#paste-and-forget). Just tested and the script seem to work.

Can you describe more in detail how did you use it and what failed?

**Comment by elmaure** [comment]
Hello Lukas, thanks for your answer. Yes that command indeed. Maybe i dont fully understand what is should do. 

I pressed ctrl + alt + v to pop up copyq.
I selected the item which i need to past.
I pressed the shortcut to "paste and forget" (in mi case ctrl + alt + back)

The result was, the item was correctly pasted but not deleted from mi clipboard. I attach some screenshots of the issue. Thanks you.
![1](https://user-images.githubusercontent.com/46298088/163453552-1ce322b1-07b6-4d7e-92e0-b2fbb55b04c7.png)
![2](https://user-images.githubusercontent.com/46298088/163453561-9974d303-184c-48ec-95e1-fa2d117b0bd4.png)
![3](https://user-images.githubusercontent.com/46298088/163453562-c386da5d-cb34-4edc-8c2c-047255191a34.png)

**Comment by hluk** [comment]
> The result was, the item was correctly pasted but not deleted from mi clipboard. I attach some screenshots of the issue. Thanks you.

The "Forget" part just means that the system clipboard itself is cleared is it is not possible to paste the content again.

If you want to delete the item from the list in CopyQ, you need to add `remove(currentItem())` after `paste()` in the command.

**Comment by elmaure** [comment]
Thanks lukas! Now it works perfectly!
