### ISSUE TITLE
Can't get CopyQ to launch on macOS no matter what I do

### ISSUE THREAD

**Issue by yllekz** [hluk/CopyQ#1963]
Before creating a new issue, see list of [known
issues](https://copyq.readthedocs.io/en/latest/known-issues.html).

**Describe the bug**
After diving into GitHub issues, reading the documentation (including above link), reinstalling, removing/re-adding the app from Security & Privacy->Accessibility, and trying as many command line tricks as I possibly can, I can't get CopyQ to open on macOS no matter what. If I click the icon, it bounces and then immediately closes with no error or visual indication of what happened. If I invoke it from command line, I either get ``Warning: CopyQ server is already running`` (when it isn't), or ``ERROR: Cannot connect to server! Start CopyQ server first.`` Both of these errors contradict each other so I'm not sure which one it truly is. When I run ``ps`` or ``htop`` I don't see it running.

**To Reproduce**
1. Launch CopyQ via the app icon = Icon bounces, nothing happens.
2. Run ``copyq`` in Terminal = "ERROR: Failed to lock file: /Users/me/.config/copyq/copyq.lock" / "ERROR: Cannot connect to server! Start CopyQ server first."
3. Run ``copyq config disable_tray false`` in Terminal = "ERROR: Cannot connect to server! Start CopyQ server first."
4. Run ``/Applications/CopyQ.app/Contents/MacOS/CopyQ`` in Terminal = "ERROR: Failed to lock file: /Users/me/.config/copyq/copyq.lock" / "ERROR: Cannot connect to server! Start CopyQ server first."

**Expected behavior**
The app should open.

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Application Version [e.g. 3.7.2]: 5.15.2
 - OS [e.g. Windows]: MacOS 12.3 on M1

**Comment by dbareis** [comment]
I don't know much about MACs but on Windows, the interface doesn't open when started, it minimises to the tray and then you can open it from there....

**Comment by yllekz** [comment]
Right, I have CopyQ running in Linux and I'm familiar with its "system tray first" core behavior, but on macOS it's not even getting to that point, the daemon/server fails to start.

**Comment by yllekz** [comment]
I got it working, and I highly suggest this be added to the documentation via a PR (Someone smarter than me please :) ):

* CopyQ Fails to open if you do not pre-create ``~/.config/copyq`` otherwise the app throws ``ERROR: Failed to lock file: /Users/me/.config/copyq/copyq.lock`` and quits.
* To fix this, I did a few things: ``chmod +rwx ~/.config/`` and ``mkdir ~/.config/copyq`` as these aren't done for you automatically.
* Re-launch the app afterwards and it should show up.
