### ISSUE TITLE
settings() alternatives allowing specification of INI filenames

### ISSUE THREAD

**Issue by dbareis** [hluk/CopyQ#1964]
**Is your feature request related to a problem? Please describe.**
Without too much exaggeration I have billions of INI file values in many groups.  It is getting annoying that I can't put each group into it's own INI file. 

**Describe the solution you'd like**
Either a New "INI() function which takes a filename or a way to tell "settings()" that it should use another.  Filename should be absolute (put it exactly where specified) or relative (and maybe "" to use scripts.ini).

**Describe alternatives you've considered**
Writing my own INI functions, Using my own text files.

**Additional context**

**Comment by hluk** [comment]
Good idea.

I'm adding new type/class that acts as wrapper for the existing Qt class for handling the configuration: https://doc.qt.io/qt-5/qsettings.html

This is more powerful and probably a bit easier to manage than with a simple function.

Script example:

```js
// Open INI file
var configPath = Dir().homePath() + '/copyq.ini'
var settings = new Settings(configPath)

// Save an option
settings.setValue('option1', 'test')

// Store changes to the config file now instead of at the end of
// executing the script
settings.sync()

// Read the option value
var value = settings.value('option1')
```
