### ISSUE TITLE
Import One or More Exported Commands from the COMMAND LINE?

### ISSUE THREAD

**Issue by dbareis** [hluk/CopyQ#1965]
RE: https://groups.google.com/g/copyq/c/H12kQeEEDWA

**Is your feature request related to a problem? Please describe.**
I am trying to automate the setup of copyq and other stuff (with SOME of my commands/macros) for other users who would like access to the features I have provided (a free Geneology group I lead in U3A). I am creating a Windows Installer and currently, I'm forced to clobber any settings they have, as they can't be imported.

**Describe the solution you'd like**
I'd like to be able to import "commands" automatically without user intervention.  Either import a directory containing many command definitions or one by one (former preferred).

**Describe alternatives you've considered**
I am currently setting up my own instance but none of these people will have any other, I am copying "copyq-commands.ini" into that instance.
I have also considered updating this file myself but the current format is horrible and unnecessarily complex (why could not each command be a group, no need to number anything...).

**Additional context**
Ideally, I'd also be able to automate the export of commands so I don't have to remember to export commands as I make changes to them (to keep them in sync).

_Not directly related but surely renaming the configuration files is unnecessary, confusing and makes it hard to find files ("config\copyq-DBAREIS-TOOLS\copyq-DBAREIS-TOOLS-scripts.ini" vs "config\copyq-DBAREIS-TOOLS\scripts.ini"). And why is "copyq-" prepended to the profile name (it certainly doesn't add any more context)_

**Comment by hluk** [comment]
There are functions available to manage the commands and import/export: https://copyq.readthedocs.io/en/latest/scripting-api.html#setCommands

Importing from file can be handled like this:

```js
const fileName = str(arguments[1])

var f = File(fileName);
if (!f.openReadOnly()) {
    throw 'Failed to open file ' + fileName;
}

var newCmds = importCommands(f.readAll());
if (!newCmds) {
    throw 'Failed to load any commands';
}

// Open Command dialog to confirm new commands.
//addCommands(newCmds);

// Add commands without user interaction.
var cmds = commands();
setCommands(newCmds.concat(cmds));
```

You can run the above script with: `copyq eval - commands.ini < script.js`

**Comment by dbareis** [comment]
@hluk 
I'm trying to use "[exportCommands()](https://copyq.readthedocs.io/en/latest/scripting-api.html#:~:text=exportCommands(Command%5B%5D))", the documentation doesn't say what the parameter should be but I eventually worked out that this works:

```
copyq:
var Rc = exportCommands(["U3A Stuff"])
popup("exportCommands()", Rc)
```

However what is exported doesn't appear to be something that I can import as it doesn't include attributes such as "in Menu", "Global Shortcut" etc  

Ideally, I'd be able to get a list of all commands by name, do something like the above to each command and that output would install all attributes (like "save selected" INI files do) which could then be imported.

**Comment by dbareis** [comment]
@hluk 
I've solved the import duplication by adding this code:
```
var L4 = "Text to HTML (escape) - {SHIFT+CTRL+H} ".trim()
for (i=0; i < cmds.length; i++)
    {
        var cmd = cmds[i]
        if (L4 == cmd.name.trim())
        {
            //--- Remove this item (only expect it ONCE) ---
            cmds.splice(i, 1)
             break;
        }
    }

```

I'm back to exporting, I tried "Exported = exportCommands(cmds[2])" but that doesn't work either.  I want to do a "Save Selected" export on a single command to create one ini per command (I now know that the commands object looks like....).

**Comment by dbareis** [comment]
@hluk
> You can run the above script with: `copyq eval - commands.ini < script.js`

In the above what is "commands.ini", I can't get anything to work, some of my attempts:

- copyq.exe eval "* = invalid js;" | more
- copyq.exe eval "source('db$/xxxImport_INI_Files.js');" | more
- copyq.exe eval "source('db$/xxxImport_INI_Files.js'); ImportIniFiles('d:/tmp', '*.ini');" | more
- copyq.exe eval - "d:\\tmp" "*.ini" <  "db$\\Import_INI_Files.js" > ###.txt & type ###.txt

None of the documentation about functions makes sense either, are these inbuilt functions?  I'm trying to call a function in my ".js" file and pass 2 parameters.

**Comment by dbareis** [comment]
I've worked it out (import & export), I have [posted the export code here](https://github.com/hluk/CopyQ/discussions/2004)
