### ISSUE TITLE
copyq clears clipboard if source (google-chrome) is closed

### ISSUE THREAD

**Issue by JohnML1** [hluk/CopyQ#1972]
Before creating a new issue, see list of [known
issues](https://copyq.readthedocs.io/en/latest/known-issues.html).

**Describe the bug**
I use copyq on Manjaro Linux (Arch) XFCE and i really like it!

Is there an option of copyq to prevent clearing of clipboard if source application is closed? 

Example: if i copied something from google-chrome-stable and close google-chrome what i just copied is gone :-(

Just reactivate last item in copyq history would be the solution?

Googled for that but couldn't find a simple solution besides reactivating just copied item in copyq history myself.

Sorry, i'm pretty shure that this question is really  common ?!!

**To Reproduce**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Application Version [e.g. 3.7.2]
 - OS [e.g. Windows]
 - Desktop environment, window manager (if applicable)

**Additional context**

**Comment by hluk** [comment]
See: https://groups.google.com/g/copyq/c/0ih4pO8h9d0
