### ISSUE TITLE
can't copy multiple pictures to clipboard

### ISSUE THREAD

**Issue by Jason-Libra** [hluk/CopyQ#1978]
sometimes i need to copy many piece of text, it's perfectly working since it can copy entries to the clipboard according to the order, but when i want to active multiple picture items (i choose many picture items by `ctrl` and then press ctrl+c), it's not working, i got nothing when i press ctrl+v on the other place.

**Comment by hluk** [comment]
This is not a bug. Copying multiple images to another application requires understanding how the app works, specifically which formats they require in clipboard.

For example a **file manager** would require **storing the images to files** prior to * as a specific file format that the file manager understands (possibly `text/uri-list`).
