### ISSUE TITLE
mouse unable to directly scroll the items if there is search candidates available

### ISSUE THREAD

**Issue by VierSNV** [hluk/CopyQ#1980]
1.(Changed 6.0.0)

>While search bar is focused, pressing Down or PageDown key now selects next
>item without focusing the item list (https://github.com/hluk/CopyQ/issues/1834). 

This fix cause mouse unable to directly scroll the items if there are search candidates available
Mouse should scroll items even if the focus is lost , I think and expect

2.How can I change the Delay for copyq to close its main window when it is not in focus , the delay has noticeable increased after upgraded from v5.0 to v6.1

**Comment by hluk** [comment]
> 1.(Changed 6.0.0)
> 
> > While search bar is focused, pressing Down or PageDown key now selects next
> > item without focusing the item list (#1834).
> 
> This fix cause mouse unable to directly scroll the items if there are search candidates available Mouse should scroll items even if the focus is lost , I think and expect

I cannot reproduce this - maybe I'm misunderstanding the problem. The change should not have affected mouse behaviour.

Can you share a recording?

> 2.How can I change the Delay for copyq to close its main window when it is not in focus , the delay has noticeable increased after upgraded from v5.0 to v6.1

For example, set 100 milliseconds to close the window after unfocused:

```bash
copyq config close_on_unfocus_delay_ms 100
```

**Comment by VierSNV** [comment]
For Issue 1:
A record can't represent the mouse behavior, So I  briefly describe how to reproduce:
1. Open copyQ and search "abs", this step just leave "abs" as a search candidates
2.Close Copyq
3.Open copyQ and search "ab", here the candidates should appear
4.Now keep mouse hovering on Copyq Main Window, and Scroll the mouse wheel, I expect to scroll main window searched results and find what I needed, but CopyQ will not scroll the main window, until I click it or input additional words to make the search candidates disappear

I found his issue after upgraded from v5.0 to v6.1 
My OS: Windows 10
![CopyQ-220516-024509](https://user-images.githubusercontent.com/78007725/168490038-af376a8b-c9f9-44bc-9d4e-1833cb9d9949.png)

https://user-images.githubusercontent.com/78007725/168490040-ca53095f-4306-48e1-b875-ec0e9b0168ef.mp4

**Comment by hluk** [comment]
Thanks for the recording. :+1: 

Interesting, looks like that is specific Qt framework behavior for popup menus. Not sure if I can easily override it.

**Comment by hluk** [comment]
I've implemented workaround that closes the popup menu if you scroll with mouse wheel and the mouse pointer is outside the menu.

You can test it with the following development build: https://ci.appveyor.com/project/hluk/copyq/builds/43556816/artifacts

**Comment by VierSNV** [comment]
Greate,Thanks lots for you replies and works to solve the issues...
