### ISSUE TITLE
Tray menu displays underscores in copied text under next character

### ISSUE THREAD

**Issue by laniakea64** [hluk/CopyQ#1981]
Before creating a new issue, see list of [known
issues](https://copyq.readthedocs.io/en/latest/known-issues.html).

**Describe the bug**
When copying text containing underscores in the middle, CopyQ tray menu displays the underscores under the following character.  For example, copying `Testing_abc_def` gets displayed as "Testingabcdef" with the a and d underlined.

Selecting this item in the tray menu copies the correct text.

Main window does not have this problem.

**To Reproduce**
Copy any text with underscores, for example `Testing_abc_def`

**Expected behavior**
The tray menu should display it as Testing_abc_def

**Screenshots**

**Version, OS and Environment**
Xubuntu 22.04
 ```
$ copyq version
CopyQ Clipboard Manager 6.0.1
Qt: 5.15.2
KNotifications: 5.89.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Ubuntu 22.04 LTS
```

This issue also occurs with official PPA version of copyq.

**Additional context**

**Comment by hluk** [comment]
This looks like a problem in the specific plugin/integration that enables tray. In KDE and with native Qt menu (open with `copyq menu`) all looks good.

In Qt the character that defines the shortcut key is `&` and AFAIK it works only with the first occurrence (https://doc.qt.io/qt-5/qkeysequence.html#mnemonic).
