### ISSUE TITLE
"Show main window under mouse cursor" doesn't show the main window at the current mouse pointer position when executed the first time

### ISSUE THREAD

**Issue by puchu** [hluk/CopyQ#1982]
**Describe the bug**
when using the shortcut "Show main window under mouse cursor" to place copyq at the current mouse pointer position, copyq opens at a random point, pressing the shortcut a second time, puts copyq at the current mouse pointer position

**To Reproduce**
1. execute "Show main window under mouse cursor"
2. main window opens at a random point
3. pressing the shortcut a second time, opens the main window at the current mouse pointer position

**Expected behavior**
the main window opens at the current mouse pointer position

**Version, OS and Environment**
CopyQ Clipboard Manager 6.1.0
Qt: 5.15.2
KNotifications: 5.92.0
Compiler: GCC
Arch: x86_64-little_endian-lp64

**Comment by hluk** [comment]
I assume this happens under **Wayland** which **does not support** custom window positioning and getting mouse pointer position.

**Comment by puchu** [comment]
No, this happens under X11

**Comment by hluk** [comment]
What's you window manager? I briefly tested this in openbox without seeing any issue.

**Comment by puchu** [comment]
kde

**Comment by puchu** [comment]
it doesnt work when i do this:

* open one app
* left click inside the app (active it as active window)
* mode the mouse somewhere else one the screen
* press the defined copyq shortcut to show it below the mouse pointer
* window is opened somewhere
* press the shortcut again - now it's below the mouse pointer

**Comment by hluk** [comment]
It could be related to some problems with window geometry and multiple screens - which is fixed but not yet released.

**Comment by puchu** [comment]
which commit fixes the bug? i can backport it and try it

**Comment by hluk** [comment]
Commits 3bd6f29, 0774563 and b0dd430. Easier if you try building from latest master.

**Comment by puchu** [comment]
i applied the patches and it doesnt fix the bug

**Comment by hluk** [comment]
I've tested this in Xnest session and it looks like kwin itself restores the window position after it is shown again.

**Comment by koorya** [comment]
Same issue, 

```
~$ copyq -v
CopyQ Clipboard Manager 6.1.0
Qt: 5.15.2
KNotifications: 5.78.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Debian GNU/Linux 11 (bullseye)
```

**Comment by puchu** [comment]
fixed in the lastest version
