### ISSUE TITLE
How do I load the image plugin? 

### ISSUE THREAD

**Issue by zhl111** [hluk/CopyQ#1986]
How do I load the image plugin? I finished the installation and the plugin is shown in the plugin, but I read the manual and I can't see how to use this command to edit images
![image](https://user-images.githubusercontent.com/29135984/168208094-da2ade5d-1310-49ec-afd9-bb2d25145b2e.png)

**Comment by hluk** [comment]
You need to install an image editor and set the command (ideally path to the executable format `C:/...`).
