### ISSUE TITLE
Abbreviated Entry List w/ Entry Preview

### ISSUE THREAD

**Issue by PaltryProgrammer** [hluk/CopyQ#1991]
Thank You for providing CopyQ I often copy a large entry even an entire file of hundreds of lines. In this event the list of entries would be easier to navigate if an abbreviated view were presented preferably w/ preview by some means perhaps per hovering Thank You Kindy - Cheerio - Best

**Comment by hluk** [comment]
You can either enable "Show simple items" (in History config tab) or change size of text items in Item config tab.

Press F7 to open item preview dock.
