### ISSUE TITLE
"Empty" Theme Not Displayed Upon Selection

### ISSUE THREAD

**Issue by PaltryProgrammer** [hluk/CopyQ#1993]
Please see attached GIF demonstrates "Empty" theme is not displayed upon re/selection via Preferences Thank You Kindly
!['Empty' Theme Not Displayed Upon Selection](https://user-images.githubusercontent.com/48535920/168485323-07abbc4f-0f83-4472-961f-e94e0cb70de0.gif)

**Comment by hluk** [comment]
Please use Reset Theme button instead. This does not seem like something worth fixing (there is not meaning in the empty theme entry actually except to indicate that initially no theme is selected).
