### ISSUE TITLE
Show simple items - make multiline

### ISSUE THREAD

**Issue by alabotski** [hluk/CopyQ#1995]
CopyQ Clipboard Manager 6.1.0-gf6684d39-v6.1.0 Mac

I have checked "Show simple items"
And how to set up that the elements were shown in full, or the first N characters
Now they have been converted to simple ones (without formatting) and are displayed in one line, which is not very convenient... =(

<img width="589" alt="image" src="https://user-images.githubusercontent.com/439337/168765279-060542f4-3b7f-49d9-810a-f6ba50654007.png">

<img width="365" alt="image" src="https://user-images.githubusercontent.com/439337/168765757-adbfba31-09b0-4447-b8c5-f4c3ed09a6f3.png">

**Comment by hluk** [comment]
If you need more specific text item setting don't use the "simple items" option, rather configure the Item plugin (disable the HTML option to show plain text only):
![image](https://user-images.githubusercontent.com/38054/170968724-065bd1e0-7fad-479c-a95f-437bbbe6678e.png)
