### ISSUE TITLE
Tags/Notes Preferences & Tooltip

### ISSUE THREAD

**Issue by dbareis** [hluk/CopyQ#1997]
**Is your feature request related to a problem? Please describe.**
I can barely read the tags so allowing me to set the font would be great as would displaying a tooltip when I hover the mouse over it (as happens for "notes"). 

**Describe the solution you'd like**
I can't change the appearance of "notes" and only the color of "tags" (because it uses the number's color).  I want to be able to set the font and color of both of these to make them stand out more.

If the font I select is too big to fit an item then where possible the font should be reduced before truncating in the middle with "...".

I'm currently using "tags" more of like a "note" since it is out of the way (and color can be changed) making it easier to see the text in the clipboard, I may change back to notes if it was configurable.

**Comment by hluk** [comment]
The appearance configuration for tag is currently not user-friendly.

To change style of all tags in the Tags configuration:

![image](https://user-images.githubusercontent.com/38054/171479891-fb4b7412-661c-4e48-9a97-87542f81702a.png)

Specifically set the following table values:

1. Tag Name: `\1`
2. Match: `(.*)`
3. Style Sheet: `font-size: 12px; color: black`

**Comment by dbareis** [comment]
Thanks, line 3 does it for me :-)

The color in the style overrides the color in the color column, so that doesn't make sense unless I'm missing some reason to do it that way.

**Comment by hluk** [comment]
> The color in the style overrides the color in the color column, so that doesn't make sense unless I'm missing some reason to do it that way.

True, the button is better to set the text color. The style sheet is handy to set `background` and other attributes.

> Also I tried "Lock" which stopped items being added to the clipboard, it is NOT documented at: https://copyq.readthedocs.io/en/latest/tags.html

Oh, there is tooltip explaining it, but it is well hidden - shows up only if you hover over the column header. I will fix it and add to documentation.

**Comment by dbareis** [comment]
RE: Lock, it looked like it was pinned and from that tooltip it sounds like the same thing, if it is then the column should say "Pin" and not "Lock".

Also if I manually pin an item it doesn't prevent the clipboard (at least for other tabs) being added to, the "Lock" stopped all clipboard text being added to it.
