### ISSUE TITLE
Preventing auto-copy

### ISSUE THREAD

**Issue by dasher** [hluk/CopyQ#20]
Is there a way to prevent auto-copying of selected content?

I'm having an issue with some things - like google search - where I copy some content in one window (select & ctrl C) - goto an existing browser window with a google search. I select the current google search to delete it - and when I paste - I get back the search I just deleted.

My workflow is more:
select something - then CTRL C or CTRL X
goto another window - select some content I want to replace
paste to overwrite the content

I'm running Mint 14 with Cinnamon

**Comment by marcosanchotene** [comment]
Is there any way to prevent the auto-copy by pressing a key? I usually need to copy something to the clipboard by selecting it and then double click on something else to paste the copied item on top of it, i.e. deleting the newly selected item. But for that to work I would need to disable the auto-copy by selection temporarily. Auto Copy is a Chrome extension that does that. You can set it to temporarily ignore the auto-copy by pressing ctrl or something else. If it's currently not possible, would be a nice feature to have!
