### ISSUE TITLE
place cursor inside copied "text"

### ISSUE THREAD

**Issue by daviddoji** [hluk/CopyQ#2006]
Probably it's already implemented/achievable, but I couldn't find in the documentation the example I'm trying to look for.

Suppose I have an item in a tab named "code" which paste the following text in an editor:

\```python
>blank line here just for illustration

\```

If I have a shortcut for pasting that, I'd like the cursor to be placed in the blank line between what I've pasted in order to not waste time while coding.

Up to now, every time I paste that, I have to replace the cursor because it is moved to the end of the pasted text, i.e., after the last single quote. 

Is there a proper way to achieve this?

**Comment by dbareis** [comment]
I don't know the answer but my workaround would be to paste the middle in from the clipboard (either from selection or clipboard).
