### ISSUE TITLE
Shortcut option to paste the second item

### ISSUE THREAD

**Issue by mailsanchu** [hluk/CopyQ#2014]
I want to paste the second item using the shortcut key. I only see the copy option and I have to paste it again manually. It would be nice if you provide an option to paste it directly

**Comment by hluk** [comment]
[This comment](https://github.com/hluk/CopyQ/issues/1586#issuecomment-780458090) could help.

**Comment by mailsanchu** [comment]
I added the command and when I press ctrl + 3 .. Nothing is pasting. What could be wrong?

**Comment by hluk** [comment]
> Is there an option to NOT on copy q window and still paste the nth item?

How about the following command? Win+Ctrl+2 would copy the second item.

```ini
[Command]
Command="
    copyq:
    var shortcut = str(data(mimeShortcut))
    var number = shortcut ? shortcut.replace(/^\\D+/g, '') : currentItem();
    selectItems(number - 1)
    copy(mimeItems, pack(getItem(number - 1)))
    hide()
    paste()"
GlobalShortcut=meta+ctrl+1, meta+ctrl+2, meta+ctrl+3, meta+ctrl+4, meta+ctrl+5, meta+ctrl+6, meta+ctrl+7, meta+ctrl+8, meta+ctrl+9
Icon=\xf0cb
IsGlobalShortcut=true
Name=Copy Nth Item
```

**Comment by mailsanchu** [comment]
No these are special keys in Ubuntu. So not working. We need some other keys like ctrl + alt + shift + 1
BTW Name should be paste Nth item right?

**Comment by mailsanchu** [comment]
```
[Command]
Command="
    copyq:
    var shortcut = str(data(mimeShortcut))
    var number = shortcut ? shortcut.replace(/^\\D+/g, '') : currentItem();
    selectItems(number - 1)
    copy(mimeItems, pack(getItem(number - 1)))
    hide()
    paste()"
GlobalShortcut=alt+ctrl+shift+1, alt+ctrl+shift+2, alt+ctrl+shift+3, alt+ctrl+shift+4, alt+ctrl+shift+5, alt+ctrl+shift+6, alt+ctrl+shift+7, alt+ctrl+shift+8, alt+ctrl+shift+9
Icon=\xf0cb
IsGlobalShortcut=true
Name=Paste Nth Item
```


This worked for me

**Comment by mailsanchu** [comment]
Just FYI, I noticed this shortcut won't work on a bash terminal window. Always print the first entry. But it works on a gedit, vs code editor
