### ISSUE TITLE
Exclude certain string patterns from being recorded in the clipboard history

### ISSUE THREAD

**Issue by darkmagic13** [hluk/CopyQ#2026]

**Comment by hluk** [comment]
1. Open Command dialog (F6 key).
2. Click Add button.
3. Select "Ignore items with no or single character".
4. Enable "Show Advanced" checkbox.
5. Change the regular expression in Content field.
6. Update name of the command and click OK button to save.
7. Next time you copy something to clipboard it will be ignored it the regular expression matches the clipboard text.

**Comment by darkmagic13** [comment]
@hluk 
Turns out every feature I think of is already implemented.
Thanks!
