### ISSUE TITLE
Release source tarball

### ISSUE THREAD

**Issue by nunotexbsd** [hluk/CopyQ#2027]
Hello,

Could this project provide a release source tarball, e.g, [copyq-6.1.0.tar.gz](https://github.com/hluk/CopyQ/releases/download/v6.1.0/copyq-6.1.0.tar.gz) to be included toguether with Release Assets?

This have the advantage to download source code from a fixed tarball instead of an auto-generated one: https://github.com/hluk/CopyQ/archive/refs/tags/v6.1.0.tar.gz.

Since I'm maintaining FreeBSD CopyQ [port](https://www.freshports.org/deskutils/copyq/), instead of using github account name/project to get auto-generated source tarball, I could simply use a simple command to fetch from a static url:

from:
```
PORTNAME=       copyq
DISTVERSIONPREFIX=      v
DISTVERSION=    6.1.0

USE_GITHUB=     yes
GH_ACCOUNT=     hluk
GH_PROJECT=     CopyQ

distinfo:
SHA256 (hluk-CopyQ-v6.1.0_GH0.tar.gz) = ###
SIZE (hluk-CopyQ-v6.1.0_GH0.tar.gz) = ###

```
to:
```
PORTNAME=       copyq
DISTVERSION=    6.1.0
MASTER_SITES= https://github.com/hluk/CopyQ/releases/download/v${DISTVERSION}/

distinfo:
SHA256 (copyq-6.1.0.tar.gz) = ###
SIZE (copyq-6.1.0.tar.gz) = ###
```
IMO, all packaging systems that needs fetching and compiling from source will beneficit with this static tarball.

Thanks,

Nuno Eduardo Teixeira
eduardo@FreeBSD.org

**Comment by hluk** [comment]
Not sure if I understand correctly. Is the problem that the auto-generated tarball may change over time (i.e. its checksum changes)? I expected once the archive is downloaded for the first time, it is cached forever so that checksums can be verified in the future.

**Comment by nunotexbsd** [comment]
Nothing to do with checksums, but with auto-generated archives.
See for example: https://github.com/glfw/glfw/releases/tag/3.3.7 , they have a static 
glfw-3.3.7.zip similar to a tarball tar.gz. When you download zip file ( https://github.com/glfw/glfw/releases/download/3.3.7/glfw-3.3.7.zip ) you just take download bandwith, but "source code.zip" and "source code.tar.gz" are auto-generated in the instant and thats why they need github account and project name. Like I've said this is very usefull for packaging automation systems.

**Comment by hluk** [comment]
I still don't see how this would help anything. I see it would be just a different URL.

Is there some noticeable delay with the auto-generated archive? Is this perhaps mentioned in some best practices?

It is not a big deal, but it would add one small step to my release checklist to upload the tar to github releases and it could be a bit confusing to see same archives in releases (unless GitHub would hide the auto-generated link).

**Comment by nunotexbsd** [comment]
ok, I have that confusing example:

https://github.com/jordansissel/xdotool/releases

Could you take a look?

Thanks

**Comment by hluk** [comment]
> ok, I have that confusing example:
> 
> https://github.com/jordansissel/xdotool/releases
> 
> Could you take a look?

That's probably OK, but still not sure what would it solve exactly.

**Comment by nunotexbsd** [comment]
@hluk 

https://github.blog/2023-02-21-update-on-the-future-stability-of-source-code-archives-and-hashes/

**Comment by hluk** [comment]
I've uploaded source tag.gz archives for 6.0.0 up until the latest release. I need to update the release checklist (RELEASE.md) to do that - or better have a script to handle this.

**Comment by nunotexbsd** [comment]
Thanks!
