### ISSUE TITLE
Commands are run automatically on a selection even though they are set not to be - Ubuntu

### ISSUE THREAD

**Issue by elpraga** [hluk/CopyQ#2030]
Before creating a new issue, see list of [known
issues](https://copyq.readthedocs.io/en/latest/known-issues.html).

**Describe the bug**
I have created simple scripts to copy n-th item from the list to the clipboard using a keyboard shortcut (I use it for symbols that are hard to even type search). Even though they are not set to run automatically, they are.  

**To Reproduce**
1. Go to 'Commands, global shortcuts'
2. Create a new command 'Copy 6th item' with the command being `copyq: select(5)`
3. Assign a shortcut 'Alt+6'
4. Uncheck type: Automatic (the icon changes and it has a little eye in the left bottom corner now)
5. Even though it should not, when I copy an item, I end up with the item I want in the CopyQ list, but with the 6th item from the list in my clipboard.

**Expected behavior**
The command gets executed **only** when I press the shortcut (Alt+6 in my case)

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Application Version [6.1.0~focal]
 - OS [Ubuntu 20.04]
 - Desktop environment, window manager (Wayland)

**Comment by hluk** [comment]
Are you saying that selecting a text in an app (i.e. copying to X11 selection buffer) triggers the command?

Can you share the command code here? (Use the Copy Selected button in Command dialog.)

**Comment by elpraga** [comment]
I am at my work computer now @hluk 
I've updated CopyQ to version `6.2.0~focal` and I cannot reproduce the bug, and I believe I have discovered what was happening.

I've added a screenshot of my **Commands/Global Shortcuts** screen. 

This time, I've made sure to have **only** the **In menu** entry activated (as you can see in the screenshot, it is almost impossible to distinguish in the dark theme. (I've noticed the little overlay icons when using CopyQ in a light theme on my RaspberryPi) 

With **only** the **In menu** entry activated, commands work, as expected. If I activate **Display**, they are run automatically every time I copy something into my clipboard. Is this the expected behaviour? 

BTW, I've compiled a `.deb` file for my Ubuntu 20.04 on my RPi 4B. Would you be interested in me sending it to you? (I am not good enough though to verify if the `.deb` file meets all standards, I've just used `checkinstall`).

  



![image](https://user-images.githubusercontent.com/13814570/177978721-d32fd1b6-eda8-4a24-a30d-85338938baf0.png)

**Comment by hluk** [comment]
"Display" command type means that the command is run any time an item is displayed - it is used to modify the item appearance.

I will close this issue then.

**Comment by elpraga** [comment]
Thank you for your help!
