### ISSUE TITLE
"Show main window under mouse cursor" Dual Screen not going on 2nd monitor

### ISSUE THREAD

**Issue by rbooth84** [hluk/CopyQ#2038]
**Describe the bug**
When "Show main window under mouse cursor" is enabled when pressing the shortcut key the window will only popup on the last screen that it appeared on at the edge of the other screen. Also when "Close When Unfocused" is enable it will only close when focus is changed to another app that is on the same screen

**Steps to reproduce the behavior**
1. Enable "Show main window under mouse cursor"
2. Enable Close When Unfocused
3. Press the shortcut key on different screens.
4. When the window is displayed click on another app on the opposite screen as the window

**Expected behavior**
Should show at the mouse cursor regardless of what screen the cursor is on

**Version, OS and Environment**
 - Application Version: 6.2.0
 - OS: XeroLinux, Fedora KDE Spin
 - Desktop environment: X11 and KDE

**Additional context**
When using Zorin OS 16.1 which is based on Ubuntu 20.04 the issue does not exist.

**Comment by presianbg** [comment]
Hi,

Same behavior in:
- Application Version: 6.2.0 , 6.1.0
- OS: Solus
- DE: X11 and Budgie

Cheers!

**Comment by thennothinghappened** [comment]
I'm using a shortcut for "Show the Tray Menu" and it seems to have really weird inconsistent behaviour, sometimes it only goes on monitor 1, and other times only on monitor 2.
```
CopyQ Clipboard Manager 6.2.0
Qt: 5.15.5
KNotifications: 5.97.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Arch Linux
```
