### ISSUE TITLE
Problem with copying an image from Chrome/Firefox/Edge via browser context menu

### ISSUE THREAD

**Issue by WRPSoft** [hluk/CopyQ#2046]
Hi to all,

When I try to copy an embedded image by the browser's context menu (Chrome, Firefox, Edge), in most cases CopyQ does not catch the image -> only an empty item will be shown in the clipboard list.

Steps (please take a look at the attached screenshots):

1.) Open https://hluk.github.io/CopyQ/ for example
2.) Select the first image with the mouse, press right mouse button and choose Copy Image at the browser's context menu
3.) CopyQ shows now an empty entry at the clipboard view.

F4 properties:
text/plain: https://hluk.github.io/CopyQ/images/application.png
text/html: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta name="qrichtext" content="1" /><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">https://hluk.github.io/CopyQ/images/application.png</p></body></html>

4.) But if I display the image at an own new tab via context menu point 'Open a new tab' first - before copying -, CopyQ is able to 'catch' the image as image type correctly.

F4 properties:
text/html: <html>
<body>
<... src="https://hluk.github.io/CopyQ/images/application.png"/>
</body>
</html>
img/png: The copied image is shown

IfranView image viewer for example is able to show the copied image, after pasting the copied image to IfranView image viewer -> so the image must be copied in a valid format to the windows clipboard, but CopyQ can not handle it.

Used OS: Windows 10 home 64 bit
Used CopyQ Version: 6.2.0

![CopyQ_Img_01](https://user-images.githubusercontent.com/78589032/180295036-a35b5f11-fb8e-426b-a5d9-05f8f1c01491.png)
![CopyQ_Img_02](https://user-images.githubusercontent.com/78589032/180295071-91f58666-0422-40ce-9e56-dcf7578eb6e9.png)
![CopyQ_Img_03](https://user-images.githubusercontent.com/78589032/180295100-8d5f6cea-1074-41fb-886a-864cf03f7963.png)
![CopyQ_Img_04](https://user-images.githubusercontent.com/78589032/180295131-886280b8-d9ad-4255-a02d-d9a0d88516a9.png)

But this is working (opening image within a new tab at the browser and copy it then via the copy context menu):

![CopyQ_Img_05](https://user-images.githubusercontent.com/78589032/180295164-5c43582b-fc7c-4543-a131-c2482a1221f1.png)
![CopyQ_Img_06](https://user-images.githubusercontent.com/78589032/180296397-6faabb56-e689-4b49-8451-f7d121bbe0fc.png)
![CopyQ_Img_07](https://user-images.githubusercontent.com/78589032/180296408-afac7754-73c5-494a-9473-387b60be7161.png)
![CopyQ_Img_08](https://user-images.githubusercontent.com/78589032/180298134-0aefddc3-55c3-4889-b830-d8c7c5de90db.png)

Maybe worth to take a deeper look at

Besides many thanks for this awesome clipboard manager.
I used Ditto before, but have now switched to CopyQ and made the functions I was missing like switching tabs via a context menu accessible via scripts as far as possible -> https://wrpsoft.blogspot.com/2022/07/some-useful-scripts-for-copyq-clipboard.html

Ralph

**Comment by hluk** [comment]
CopyQ does not fetch any remote files for displaying HTML items, so unless the image data itself is copied (for example `image/png` instead of `text/html`) CopyQ won't be able to show the image.

**Comment by WRPSoft** [comment]
Dear Lukas,

> CopyQ does not fetch any remote files for displaying HTML items, so unless the image data itself is copied (for example `image/png` instead of `text/html`) CopyQ won't be able to show the image.

Thank you for your feedback.

I have slightly modified the script named **Tab for URLs with title and icon** from the official repository so that I can capture (download) most of the images directly. I typed the code quickly, and I'm not that big of a regex expert either, but it seems to be working fine for my use case now. This script works with Chrome but not Firefox, at least at my Windows 10 PC!

It's a little weird to me that every browser behaves a bit differently. These clipboard functionality seems very complex to me, especially when it comes to the desired platform independence.
Thanks again for this great clipboard manager, there is a lot of development time in there. Great Work!

Maybe someone can do something with it, one version based on RegEx and another version doing it the easy way :-) The scripts must be renamed to *.ini. 

[CatchImage_RegEx.txt](https://github.com/hluk/CopyQ/files/9187703/CatchImage_RegEx.txt)
[CatchImage.txt](https://github.com/hluk/CopyQ/files/9187708/CatchImage.txt)

`[Command]
Name=CatchImage
Match=https?://
Command="
    copyq:

    function lower(data) {
        return str(data).toLowerCase()
    }
    function findHeader(reply, headerName) {
        reply.data  // fetches data and headers
        var headers = reply.headers
        for (var i in headers) {
            var header = headers[i]
            if (lower(header[0]) === headerName)
               return header[1]
        }
        return ''
    }
    function fetchContent(url, maxRedirects) {
        if (maxRedirects === undefined)
            maxRedirects = 4
        serverLog('Fetching: ' + url)
        var reply = networkGet(url)
        if (maxRedirects == 0)
            return reply
        var header = findHeader(reply, 'location')
        if (header)
            return fetchContent(header, maxRedirects - 1)
        return reply
    }
    function isImage(url) {
       var image = \"<img.+src\\\\=(?:\\\\\\\"|\\\\\\')(.+?)(?:\\\\\\\"|\\\\\\')(?:.+?)\\\\>\"
       var img = url.match(image)
       return img
    }
    function getImage(url){
       var image = \"https?:\\\\\\/\\\\\\/(www\\\\.)?[-a-zA-Z0-9@:%._\\\\+~#=]{1,256}\\\\.[a-zA-Z0-9()]{1,6}\\\\b([-a-zA-Z0-9()@:%_\\\\+.~#?&\\/\\/=]*)\"
       var img= url.match(image)[0]
       if (!img) 
         return ''
        // popup(\"\", img, 4000)
        var url_low = lower(img)
        if (url_low.endsWith(\".png\") || url_low.indexOf('=png') !=-1) {
            popup(\"\", \"PNG image fetched\", 4000)
            var ipos = img.indexOf('&')
            if (ipos != -1) 
              img = img.substring(0, ipos);
            var image = loadImage(img)
            setData('image/png',image)
            removeData('text/html')
            removeData('text/plain')
        }
        else
        if (url_low.endsWith(\".jpg\") || url_low.indexOf('=jpg') !=-1) {
            popup(\"\", \"JPG image fetched\", 4000)
            var ipos = img.indexOf('&')
            if (ipos != -1) 
              img = img.substring(0, ipos);
            var image = loadImage(img)
            setData('image/jpeg',image)
            removeData('text/html')
            removeData('text/plain')
        }
        else
        if (url_low.endsWith(\".bmp\") || url_low.indexOf('=bmp') !=-1) {
            popup(\"\", \"BMP image fetched\", 4000)
            var image = loadImage(img)
            setData('image/bmp',image)
            removeData('text/html')
            removeData('text/plain')
        }
        else
        if (url_low.endsWith(\".gif\") || url_low.indexOf('=gif') !=-1) {
            popup(\"\", \"GIF image fetched\", 4000)
            var image = loadImage(img)
            setData('image/gif',image)
            removeData('text/html')
            removeData('text/plain')
        }
    }
    function loadImage(url) {
        var icon = url
        if (!icon)
          return ''
        // Icon path can be complete URL.
        if (icon.indexOf('://') != -1)
          return fetchContent(icon).data
        // Icon path can be missing protocol.
        if (icon.substr(0, 2) === '//') {
          var i = url.search(/\\/\\//)
          var protocol = (i == -1) ? 'http:' : url.substr(0, i)
          return fetchContent(protocol + icon).data
        }
        // Icon path can be relative to host URL.
        if (icon[0] === '/') {
          var baseUrl = url.substr(0, url.search(/[^\\/:](\\/|$)/) + 1)
          return fetchContent(baseUrl + icon).data
        }
        // Icon path can be relative to current URL.
        var baseUrl = url.substr(0, url.lastIndexOf('/') + 1)
        return fetchContent(baseUrl + icon).data
    }
    var url = str(input()).trim()
    serverLog('Fetching image: ' + url)
    // URL already added? (Just check the top of the list.)
    if (url === str(read(0)))
        abort()
    var reply = isImage(url)
    if (!reply)
        abort()
    if (!getImage(reply[1]))
        abort()
     

    "
Input=text/html
Automatic=true
InMenu=true
Icon=\xf030`
