### ISSUE TITLE
Tray is displayed at the top of screen.

### ISSUE THREAD

**Issue by HagunKim** [hluk/CopyQ#2049]
Before creating a new issue, see list of [known
issues](https://copyq.readthedocs.io/en/latest/known-issues.html).

**Describe the bug**
With Ubuntu 22.04 and dash-to-panel extension, CopyQ tray is displayed at the top of screen.
I'm using 2 monitors. So tray is displayed at the top of the screen across two monitors.

**To Reproduce**
1. Show CopyQ Tray with Ubuntu 22.04 and dash-to-panel extension environment.

**Expected behavior**
The tray should be displayed normally, as it is when the dash-to-panel extension is disabled.

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Application Version : CopyQ Clipboard Manager 6.0.1
 - OS : Ubuntu 22.04
 - Ubuntu extension : Dash to Panel

**Comment by hluk** [comment]
Most likely a problem with the tray extension. I do not have much control over the tray icon. [KNotifications](https://api.kde.org/frameworks/knotifications/html/index.html) is used to set up the icon.

Try updating to the latest version of CopyQ from PPA: https://copyq.readthedocs.io/en/latest/installation.html

**Comment by HagunKim** [comment]
It's okay with CopyQ 6.2.0 !
Thanks for your suggestion about update.
