### ISSUE TITLE
Triple click does not paste

### ISSUE THREAD

**Issue by sebmottese** [hluk/CopyQ#2050]
With default settings, (i.e. paste with double click) it happens that after an (unwanted) triple click, the content is not pasted.
This causes content not pasted and missing data in documents.
It would be great to be tolerant to triple clicks as if they were double clicks.

**Comment by hluk** [comment]
This is not something I would like to handle in the application itself. Probably better to file an issue for Qt GUI framework (https://bugreports.qt.io).
