### ISSUE TITLE
CopyQ not working on Fedora 36 Gnome 

### ISSUE THREAD

**Issue by thorrrr** [hluk/CopyQ#2051]
HI Guys

Been using CQ for months on Zorin was really good no major issues. But moved over to Fedora 36 and nothing work no copies being stored  no shortcuts to make panel show working. I used same settings as before i get a different panel with zero in it.

I can manually show it but after a few seconds shoots tot op left and disappears 

I get no right click options like screen shot 

Fedora 36 Gnome Version fully updated as off today

**Comment by thorrrr** [comment]
This is after 10 attempts to copy 

![image](https://user-images.githubusercontent.com/8170673/182580174-161228c3-68c5-450c-89fb-97207925495f.png)

**Comment by hluk** [comment]
Unfortunately, **Gnome Wayland session does not support clipboard monitoring** for native clipboard clients.

Try running the app in X11-compatibility mode. See: https://copyq.readthedocs.io/en/latest/known-issues.html#on-linux-global-shortcuts-pasting-or-clipboard-monitoring-does-not-work

**Comment by thorrrr** [comment]
HI 
I got it all setup as documented its very weird in Fedora  Gnome to use compared to Zorin. I was thinking of trying Fedora KDE would it run better in there?
Also i cannot get the paste by hitting the number to work i have ctrl alt v to bring up window i used to hit the number of the paste i wanted and it worked but now it just goes to search?  I guess i am missing a setting

**Comment by hluk** [comment]
I'm using Fedora 36 with KDE - Wayland session - where CopyQ (and clipboard monitoring) works but Wayland still requires some additional functionality to be included using a special command: [Wayland Support](https://github.com/hluk/copyq-commands/tree/master/Scripts#wayland-support) (mentioned in the [Known Issues](https://copyq.readthedocs.io/en/latest/known-issues.html#on-linux-global-shortcuts-pasting-or-clipboard-monitoring-does-not-work)).

Global shortcuts need to be set up in the desktop environment itself - for example a shortcut can be mapped to `copyq toggle` to show/hide the main window; or use `copyq triggerGlobalShortcut "{COMMAND_NAME}"` to trigger a command with a specific name.

**Comment by hluk** [comment]
BTW, you will probably get the best support on Fedora 36 KDE+Wayland since I'm using it also. :wink:
