### ISSUE TITLE
Additional CSS/Sizing Options

### ISSUE THREAD

**Issue by kevjustice** [hluk/CopyQ#2053]
I'm really used to using Ditto but it just doesn't have the functions that CopyQ has.  However the HUGE window when you paste is just too much.  I've tried styling but the style files have their limits.

Requests:
1. Give me the ability to set an initial clip window size in the app (so I can set it smaller).
2. Make the ${scale = 0.5} directive work for HTML as well.  It seems to only scale non-html which is useless if you show mixed content.
3. I figured out how to limit what is seen for the clip item if it's multiple lines which helps, but on hover can you show a tooltip of the complete paste item (unformatted).
4. To minimize the clip window size, can you hide the menu by default?  Maybe a hamburger icon to bring it back?
5. on all clip items, there is a LOT of margin/padding that I can't seem to get rid of via css.
6. Why does html have a black background? Shouldn't it follow the settings for items?

**Comment by hluk** [comment]
> Give me the ability to set an initial clip window size in the app (so I can set it smaller).

Not sure if I understand. Doesn't resizing the main window work?

> I figured out how to limit what is seen for the clip item if it's multiple lines which helps, but on hover can you show a tooltip of the complete paste item (unformatted).

There is Item Preview for this purpose (in menu bar: File - Show Preview [F7]). I'm not a fan of large tool tips - they are actually shown for item notes but I find them a bit annoying.

> To minimize the clip window size, can you hide the menu by default? Maybe a hamburger icon to bring it back?

See: [How to hide the menu bar in the main CopyQ window?](https://copyq.readthedocs.io/en/latest/faq.html#how-to-hide-the-menu-bar-in-the-main-copyq-window)

> on all clip items, there is a LOT of margin/padding that I can't seem to get rid of via css.

If you use Edit Theme in Appearance tab it could be couple of options in the config file:

```
item_css=padding: 0
item_spacing=0
```

Depends on where the additional padding/margins is. Probably not everything is not configurable using style sheets.

> Make the ${scale = 0.5} directive work for HTML as well. It seems to only scale non-html which is useless if you show mixed content.

> Why does html have a black background? Shouldn't it follow the settings for items?

Changing copied HTML is usually very difficult and it would require CopyQ to use some tools to do this. It is out of the scope for the app - though it is possible to change appearance of items using Display commands.

See also: #1464
