### ISSUE TITLE
Empower Filtering with an "AND" Operator

### ISSUE THREAD

**Issue by Lonniebiz** [hluk/CopyQ#2054]
CopyQ Clipboard Manager v3.13.0
Qt: 5.14.2
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Debian GNU/Linux 11 (bullseye)

First, I'd like to complement this development team for the fine job that has been done in the creation of CopyQ.

This is a feature enhancement request pertaining to the already existing feature of "Filtering through clipboard entries by merely typing". This is a great feature, yet (after being spoiled with it) I find myself wishing I could enter a comma as an "and" operator during searches.

Out of hundreds of entries, CopyQ quickly filters down to only the entries that contain the exact text I've typed, but when there are multiple entries that are almost identical, and only differ at the very end of the string, it would be very nice to immediately input an "and" operator (with a comma preferably) and have CopyQ do a second filter on the remaining items. This would allow me to only type what is different between the remaining items to filter down to a single entry (without using arrow keys or clicking with the mouse).

Logically, it would just be a way for me to tell CopyQ, show me all entries that have this string inside the entry, but also another string as well.

I've written filters like this in my own applications, and I used a comma as an "and" operator and that worked conveniently. However, I'd appreciate **any** and-operators you'd be willing to offer.

**Comment by dbareis** [comment]
Great idea

**Comment by hluk** [comment]
Maybe I'm missing something but in the default search (non-regular-expression) **space is treated as the AND operator**.

**Comment by Lonniebiz** [comment]
@hluk A space is **not** treated as an AND operator.

For example,
I had a clipboard entry that was:
`sudo passwd root`
and typing:
`sudo root`
didn't match it.
What I'm proposing is that:
`sudo,root` should match `sudo pssswd root` because it contains both `sudo` **and** `root`. In this case, a comma is used as an AND operator.

Currently, there is no AND operator. A space it treated like any other character (as should be). You could use `&` for an AND operator, but I find `,` (a comma) to be more convenient due to the fact that it requires only one key press and it is a key that is close to the home keys on a keyboard. Plus, in English, a comma is used as a proper way list multiple things in a sentence.

I think a comma is a good fit. However, you could certainly allow the users to set their own AND operator preference instead. I propose comma by default. But, my primary purpose here is to gain **any** AND operator in CopyQ. There currently isn't one.

**Comment by hluk** [comment]
> For example,
> I had a clipboard entry that was:
> `sudo passwd root`
> and typing:
> `sudo root`
> didn't match it.
> What I'm proposing is that:
> `sudo,root` should match `sudo pssswd root` because it contains both `sudo` **and** `root`. In this case, a comma is used as an AND operator.

The entry is found if I enter `sudo root` or even `root sudo`.

Can you install latest version of CopyQ? I have not noticed the version you mention in the description before but 3.13.0 is very old.

**Comment by Lonniebiz** [comment]
In Debian Stable, I was able to upgrade to CopyQ v3.13.0 to v6.20 using this command:
`sudo apt install copyq/bullseye-backports`

Still, the behavior you're describing is not present.

For example, I had this clipboard entry:
`192.168.0.1`
and I typed:
`168 192`
and it did not match it, even though my entry contains both of those values.

What version do I need to upgrade to in order to enjoy what you're talking about? And, if you happen to know, what's the best way to install that version in Debian Stable? Lastly, since Debian doesn't seem to consider any version later than 3.13 "stable", I'd like to know if you consider the version you're using stable. @hluk

**Comment by hluk** [comment]
The feature is available only for non-regular-expression search:
![image](https://user-images.githubusercontent.com/38054/186468754-09b7bda2-bfa5-4fc1-8207-83a4ea588024.png)

**Comment by hluk** [comment]
Best way to install the app would really be from the distro but I'm not sure why in some cases the version is so old.

BTW, I would not release a new version if I think it is unstable.

**Comment by Lonniebiz** [comment]
Thanks for making the "toggling off of Regular Expression" so clear. You had mentioned it earlier, but I assumed I didn't have that on, but I actually  did.

With v6.20, and the settings you show, it does indeed work exactly as you described.

Out of curiously, I tried these same settings in v3.13.0, but that version was indeed older than when this feature arrived.

I believe you about the stability. I'm not sure why debian stable hasn't provided later versions yet. The fact that I'm able to get v6.20 from backports may be a good sign that Debian 12 stable will have a later version.

Great job on copyQ. The more I learn about it the more I like it.
