### ISSUE TITLE
Remove a Contiguous Block of Items

### ISSUE THREAD

**Issue by PaltryProgrammer** [hluk/CopyQ#2056]
Greetings Kind Regards I was not able to find a means to remove a block of items. If not currently provided I request same or instructions if otherwise.

**Comment by PaltryProgrammer** [comment]
Greetings Kind Regards I was not able to find a means to remove a block of items. If not currently provided I request same or instructions if otherwise.

**Comment by dbareis** [comment]
I think you better show a picture or provide a better explanation of what you mean.  If you mean multiple clipboard items then that is just selection and the delete key or any number of variations of that.

**Comment by PaltryProgrammer** [comment]
I merely wish to remove a contiguous block of entries. I know how to remove a single entry i.e. to wit in particular to be specific right click -> Remove/Del but e.g. if one-hundred contiguous entries how are they all selected as a block so that a single Del is all that is necessary - Kind Regards

**Comment by dbareis** [comment]
> I merely wish to remove a contiguous block of entries. I know how to remove a single entry i.e. to wit in particular to be specific right click -> Remove/Del but e.g. if one-hundred contiguous entries how are they all selected as a block so that a single Del is all that is necessary - Kind Regards

That is [standard selection for the OS](https://www.businessinsider.com/how-to-select-multiple-files-windows-10), on Windows with mouse:

1. Select start/end (mouse click)
2. Shift Click on opposite end
3. Delete

**Comment by PaltryProgrammer** [comment]
The difficulty I am having and the reason for my post is the standard OS method for block selection results in a paste operation upon step 1. Of course I wish to avoid same. I should have stated this at outset. Thank You Kindly

**Comment by dbareis** [comment]
> The difficulty I am having and the reason for my post is the standard OS method for block selection results in a paste operation upon step 1. Of course I wish to avoid same. I should have stated this at outset. Thank You Kindly

Well that doesn't happen here on Windows 11 & copyq 6.0.1

**Comment by PaltryProgrammer** [comment]
How can it not happen as mouse click is all that is necessary to paste. As for the truncated subject line that was a typing error which I do not know how to correct. The James Bond reference I do not understand. - Cheerio

**Comment by fade2gray** [comment]
@PaltryProgrammer 

> As for the truncated subject line that was a typing error which I do not know how to correct.

FYI: To the right of the subject line is an `Edit` button.

The reference to James Bond probably infers that you are being 'secretive'. ¯\\_(ツ)_/¯

**Comment by hluk** [comment]
> The difficulty I am having and the reason for my post is the standard OS method for block selection results in a paste operation upon step 1.

Did you enable "Activate item with single click" option (in History tab in Preferences dialog)? That could be the problem.

**Comment by dbareis** [comment]
> > The difficulty I am having and the reason for my post is the standard OS method for block selection results in a paste operation upon step 1.
> 
> Did you enable "Activate item with single click" option (in History tab in Preferences dialog)? That could be the problem.

@hluk 
Surely that would be a bug if it doesn't detect the modifier keys?

**Comment by hluk** [comment]
> Surely that would be a bug if it doesn't detect the modifier keys?

Fixing (#2061).

**Comment by PaltryProgrammer** [comment]
Thank You for your kind assistance. Yes single-click-activate was enabled. I prefer single-click as I hate double-clicking. It would be nice if selection for deletion can be performed via right-click. Also I noticed the "single-click-activate" check box can be set to three states i.e. to wit in particular to be specific as indicated by [0] empty box [1] check mark [2] solid black square. May I please inquire the meaning of [2] i.e. to wit solid black square. Thank You Kindly - Cheerio

**Comment by hluk** [comment]
> Yes single-click-activate was enabled. I prefer single-click as I hate double-clicking. It would be nice if selection for deletion can be performed via right-click.

I have fixed it so multiple items can be always selected with Shift/Ctrl. Right click is reserved for context menu.

> Also I noticed the "single-click-activate" check box can be set to three states i.e. to wit in particular to be specific as indicated by [0] empty box [1] check mark [2] solid black square.

I have also fixed this - the checkbox should have only two states.

**Comment by PaltryProgrammer** [comment]
Thank You for your Kind response Perhaps I should have elaborated i.e. to wit my meaning re/ selection via right-click is "Select" would appear in the Context Menu. Further may I please inquire the meaning of Shift/Ctrl as stated above i.e. to wit does it mean (Shift+left-click and Ctrl+left-click) or Shift+Ctrl+left-click - Thank You Kindly

**Comment by hluk** [comment]
> Perhaps I should have elaborated i.e. to wit my meaning re/ selection via right-click is "Select" would appear in the Context Menu.

This is not going to happen. I prefer supporting a more standard way of selecting items.

> Further may I please inquire the meaning of Shift/Ctrl as stated above i.e. to wit does it mean (Shift+left-click and Ctrl+left-click) or Shift+Ctrl+left-click

Yes, if you hold Shift or Ctrl the left mouse button should select items without activating/pasting them.
