### ISSUE TITLE
`copyq toggle` only opens the window in the workspace where it first opened

### ISSUE THREAD

**Issue by RayZ0rr** [hluk/CopyQ#2064]
Before creating a new issue, see list of [known
issues](https://copyq.readthedocs.io/en/latest/known-issues.html).

**Describe the bug**
`copyq toggle` only opens the window in the workspace that the command first opened the window on. Not on the currently focused workspace(different from the one on which first instance had opened). Also, changing the workspace when the window is opened in a particular workspace doesn't close the window (it should as it loses focus).
Using a keybinding in [sxhkd](https://github.com/baskerville/sxhkd) to open copyq. 
```bash
#Clipboard manager
control + alt + y
  copyq toggle
  # copyq menu
```
Opening `copyq menu` works perfectly.
1) It opens in the currently focused workspace.
2) It closes when workspace is changed.

**To Reproduce**
1. Go to workspace 1
2. Open copyq with `CTRL+ALT+y` (`copyq toggle`)
3. Close it
4. Change workspace ( workspace 2 )
5. Open copyq window `CTRL+ALT+y` (`copyq toggle`)
6. copyq opened in workspace 1.

**Expected behavior**

1) It opens in the currently focused workspace.
2) It closes when workspace is changed.

**Screenshots**

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Application Version :- 
```
CopyQ Clipboard Manager 6.2.0
Qt: 5.15.5
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Arch Linux
```
 - Desktop environment, window manager
```
herbstluftwm 0.9.5
Copyright (c) 2011-2021 Thorsten Wißmann
Released under the Simplified BSD License
xrandr support: on
xinerama support: on
```

**Comment by hluk** [comment]
I tested it on Fedora 36 with herbstluftwm 0.9.4 and CopyQ 6.2.0. For me CopyQ reopens on current workspace.

Could it be caused by a configuration in herbstluftwm?

**Comment by RayZ0rr** [comment]
Could you share your herbstluftwm config? I will compare it with mine

**Comment by RayZ0rr** [comment]
Also, since you can't reproduce it, I will close this issue.

**Comment by RayZ0rr** [comment]
Temporarily reopening this issue.

**Comment by hluk** [comment]
> Could you share your herbstluftwm config?

I do not use the WM. I only installed it for the test on Fedora 36. So it used the out-of-the-box config.
