### ISSUE TITLE
Copying inline image from outlook results in truncated/cropped picture

### ISSUE THREAD

**Issue by dartrax** [hluk/CopyQ#2068]
**Describe the bug**
You've got an email with inline image in Win Outlook. Copy that image. Sometimes you get the full image showing up in CopyQ, sometimes it is truncated on all four edges.

**To Reproduce**
1. Send yourself a big image inline, like a screenshot of your desktop
2. In Outlook, select the image (dotted border appears) and hit CTRL+V
3. In CopyQ, the Image appears. If you can see the full image, repeat step 2 a few times.
4. The image will be truncated.

**Expected behavior**
The image should appear without cropped edges, like it does when you paste it into MS Paint.

**Screenshots**
![image](https://user-images.githubusercontent.com/15105943/188111625-3031a586-d85c-4357-9dad-441a2c318f9d.png)

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Application Version 6.2.0
 - OS Windows 10
 - Outlook Home and Business 2016 Version 2207

**Additional context**
For me it is strange behavior. If you copy an image in MS Outlook:
- it will appear uncropped in MS Paint always
- it will appear cropped in CopyQ sometimes
- it will appear cropped when pasting to a website in Google Chrome or MS Edge to a website that supports this (like Github) without CopyQ being involved at all.
It may be the fault of Outlook, but since it works sometimes with CopyQ and some apps like MS Paint can always read the full image, I hope the devs can find something to improve here or just give an insight of what's happening here behind the UI.

**Comment by hluk** [comment]
Can you post contents of the clipboard when the cropped image is copied? You can inspect the clipboard from CopyQ with Ctrl+Shift+C.

It could be that some image formats provided by Outlook are cropped versions of the image. Or perhaps there is an issue in handling these images in clipboard via Qt framework (that CopyQ uses).

**Comment by dartrax** [comment]
Hi @hluk, thanks for looking into it.
I did not know about the inspect function, I thought clicking the (i) Icon on the right reveals all that CopyQ know about it.

Here it is. Is there a way to figure out the pixel size of those entries?

![image](https://user-images.githubusercontent.com/15105943/189604578-dd64528e-0eae-4474-bc12-3edbcc5cd940.png)

**Comment by dartrax** [comment]
Yes, I've tried every format, I hope I've done it right, for example for GIF I used this setting:
![image](https://user-images.githubusercontent.com/15105943/189721545-acf86502-28d1-4dc1-be05-55093fb035f5.png)

Those formats that are able to display an image in CopyQ's list, all displayed the cropped image.
With those formats not displaying an image (like "Object Descriptor" for example), i'm not sure how to test this.

**Comment by hluk** [comment]
> In Chrome there is the same cropping effect.

That sounds like a problem in Windows - or perhaps with Qt not understanding the clipboard data and providing cropped images instead for some reason.

I found a similar issue though very old: https://answers.microsoft.com/en-us/windows/forum/all/clipboard-is-cropping-images-since-upgrading-to-81/25a4f97e-c4b8-4274-8176-6bf24f2dbf6a (Clipboard is cropping images since upgrading to 8.1)

**Comment by hluk** [comment]
Actually, since you mentioned in the issue description:

> it will appear cropped when pasting to a website in Google Chrome or MS Edge to a website that supports this (like Github) without CopyQ being involved at all.

.. it would mean this is some strange but intended behavior and perhaps other apps like MS Paint get the full image through some other means than clipboard.

TBH, I probably won't be able to do anything about this in CopyQ.
