### ISSUE TITLE
add non-activate mode

### ISSUE THREAD

**Issue by iamqiz** [hluk/CopyQ#2075]
**Is your feature request related to a problem? Please describe.**

 in windows explorer, press F2 to rename file (see pic below), i want to paste string from copyQ,but when copyQ popup, the file name input loss focus
so i can not rename file from copyQ,
![Snipaste_2022-09-06_07-42-58](https://user-images.githubusercontent.com/48077521/188521131-30bceb3f-8ff7-4065-adbb-840c8c3755b8.png)

how to resolve it?
if the  copyQ window popup but does not activate  ,keeping explorer.exe activated, the problem will be resolved,
so i hope copyQ can add non-activate mode, 
see extended-window-styles WS_EX_NOACTIVATE: 
https://docs.microsoft.com/en-us/windows/win32/winmsg/extended-window-styles#:~:text=MDI%20child%20window.-,WS_EX_NOACTIVATE,-0x08000000L

thanks!

**Describe the solution you'd like**
add non-activate mode 
**Describe alternatives you've considered**

**Additional context**

**Comment by hluk** [comment]
There is "Copy next item" that helps to copy an item from CopyQ to the clipboard. A global shortcut can be assigned to it in Preferences dialog, Shortcuts tab.

**Comment by Inirdin** [comment]
Copy next item is not really appropriate solution. For example: What if the item I need to paste is further down in history? Am I meant to cycle through copy next item until I stumble upon the one I need? Or should I memorize the order in which I copy items into clipboard? It can be really bothersome when you are chaining multiple items consecutively.
This issue #1468 is same thing. CopyQ is taking focus from some text fields on Windows.
