### ISSUE TITLE
copyq fails to create a tray icon on startup

### ISSUE THREAD

**Issue by martinpelikan** [hluk/CopyQ#2087]
**Describe the bug**
copyq fails to create a tray icon on startup via .xprofile but works with delayed start via sleep or manual CLI invocation

**To Reproduce**
1) echo "copyq &" >> ~/.xprofile
2) restart X session / reboot
3) observe no tray icon

**Expected behavior**
Have a tray icon

**Version, OS and Environment**
CopyQ Clipboard Manager 6.2.0
Qt: 5.15.5
KNotifications: 5.97.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Arch Linux
i3 version 4.20.1 (2021-11-03) © 2009 Michael Stapelberg and contributors
i3status-rs 0.30.0 (commit 0b6edb42 2022-08-25)

**Additional context**
I've encountered this issue before with an update, had it resolved via a subsequent update, and I'm seeing the issue show up with the latest update again.
Related issue: https://github.com/hluk/CopyQ/issues/1526
Workaround: (sleep 2; copyq )& in .xprofile

**Comment by hluk** [comment]
This is a known issue with all the tray/notification areas. Unfortunately, I do not have a proper workaround I could add to the app (previously, the app tried to detect tray area after started but it did not work either).

**Comment by amosbird** [comment]
I'm also seeing the same issue. The `sleep` workaround doesn't work. But I have to start `stalonetray` before `copyq` to get the tray icon. IIRC, this is not required in previous versions. Other applications such as fcitx, telegram-desktop don't require `stalonetray` running either.

**Comment by martinpelikan** [comment]
Unfortunately I can't comment on the situation with stalonetray since I use i3's default tray, but can confirm that after an update the sleep hack/workaround continues to work. I also found it strange that other applications don't run into this issue though.
