### ISSUE TITLE
"Show main window under mouse cursor" never shows the main window at the current mouse pointer position anymore

### ISSUE THREAD

**Issue by jazzzz** [hluk/CopyQ#2088]
Before creating a new issue, see list of [known
issues](https://copyq.readthedocs.io/en/latest/known-issues.html).

**Describe the bug**

"Show main window under mouse cursor" does not work anymore on Gnome 42.4 with X11 since commit 5517c6dfba3da516f0bc20d7f1b6e348c33d49c5.

**To Reproduce**
1. Use a keyboard shortcut to trigger "Show main window under mouse cursor"
2. The window always displays at the same place

**Expected behavior**
The window should display next to the mouse cursor.

**Screenshots**

**Version, OS and Environment**
 - Application Version 6.0.1 and 6.2.0
 - OS: Ubuntu 22.04
 - Desktop environment, window manager: Gnome 42.4

**Additional context**
I found by bisecting that it is broken since commit 5517c6dfba3da516f0bc20d7f1b6e348c33d49c5, any revision before this (like 3b6d9bd340d85bf77988b875dcfe87a9423d4b12 that is the commit just before, or 5.0.0) works correctly.

**Comment by jazzzz** [comment]
> Does it work if you build on [5517c6d](https://github.com/hluk/CopyQ/commit/5517c6dfba3da516f0bc20d7f1b6e348c33d49c5) but with `cmake -DWITH_NATIVE_NOTIFICATIONS=OFF ...`?

Yes it works with this define, and also on master.

**Comment by hluk** [comment]
> > Does it work if you build on [5517c6d](https://github.com/hluk/CopyQ/commit/5517c6dfba3da516f0bc20d7f1b6e348c33d49c5) but with `cmake -DWITH_NATIVE_NOTIFICATIONS=OFF ...`?
> 
> Yes it works with this define, and also on master.

I guess linking KNotification library or its dependencies (possibly KWindowSystem) breaks things. :thinking:

**Comment by hluk** [comment]
I think the culprit is calling `KStatusNotifierItem::setAssociatedWidget()`, it messes with the main windows a lot: https://invent.kde.org/frameworks/knotifications/-/blob/v5.98.0/src/kstatusnotifieritem.cpp#L481

Can remove [this line](https://github.com/hluk/CopyQ/blob/v6.2.0/src/gui/mainwindow.cpp#L482) and build with `cmake -DWITH_NATIVE_NOTIFICATIONS=ON` (or without the option since this is the default)?

**Comment by jazzzz** [comment]
I also tried without `-DWITH_NATIVE_NOTIFICATIONS=OFF` and just commenting out the `SystemTrayIcon` class that inherits from `KStatusNotifierItem` (replacing `#ifdef WITH_NATIVE_NOTIFICATIONS` above the class definition with `#ifdef FOO`) and it still works, so I don't think linking with KNotification library is the issue.

**Comment by jazzzz** [comment]
> Can remove [this line](https://github.com/hluk/CopyQ/blob/v6.2.0/src/gui/mainwindow.cpp#L482) and build with `cmake -DWITH_NATIVE_NOTIFICATIONS=ON` (or without the option since this is the default)?

It still doesn't work without `setAssociatedWidget(parent)`.

**Comment by hluk** [comment]
Oh, the `setAssociatedWidget()` is also called from constructor. Can you also remove `parent` from the constructor call?

```c++
    explicit SystemTrayIcon(QWidget *parent = nullptr)
        : KStatusNotifierItem(QCoreApplication::applicationName()/*, parent */)
```

**Comment by jazzzz** [comment]
When I remove both `parent` from the super constructor and `setAssociatedWidget` it works!

**Comment by hluk** [comment]
> When I remove both `parent` from the super constructor and `setAssociatedWidget` it works!

Thanks for testing this so fast!

The question if the `setAssociatedWidget()` is needed in some cases. For example, clicking on tray/notification icon may not show the main window depending on the desktop environment.

**Comment by jazzzz** [comment]
> The question if the `setAssociatedWidget()` is needed in some cases. For example, clicking on tray/notification icon may not show the main window depending on the desktop environment.

I don't know, but at least on Gnome, clicking on the tray icon and native notifications still work.

**Comment by hluk** [comment]
Fix merged to master branch. Thanks again for the investigation and testing. :+1:

**Comment by hluk** [comment]
> Thanks for the hard work and your great software! When do you expect a new release?

No exact plan. I will try to make a new release when I have the time.
