### ISSUE TITLE
can not see any text on copyq

### ISSUE THREAD

**Issue by jsrdzhk** [hluk/CopyQ#2094]
![image](https://user-images.githubusercontent.com/31811412/191147558-e2ecb125-7b49-4e23-9d4a-280be07f3e02.png)
after upgrade from 6.2 to 6.3,I cannot see text on copyq window.I tried to restart the copyq but the text disappear after a few nimutes

**Comment by jsrdzhk** [comment]
My operating system is windows 11,os version:22000.978

**Comment by online** [comment]
I have the same problem with the latest version of the program. My OS: Ubuntu 22.04.1 LTS, 5.15.0-47-generic

**Comment by zdzqianmu** [comment]
same problem

**Comment by tharfy** [comment]
Same thing here. Started since upgrade from Chocolatey on Windows yesterday.

At start it works, then after a few copy/paste, new elements are blank, older ones are still there.
When stopping / restarting the application, everything is there again, until it starts again to go blank.

**Comment by online** [comment]
As a temporary solution for not to restart the application, you can press F2 on any problematic note and quit editing immediately.

**Comment by mckellygit** [comment]
I have the same issue with 6.3, Ubuntu 20.04.

**Comment by innerfly** [comment]
Same issue on Ubuntu 22.10, CopyQ 6.3.0~jammy

**Comment by kunalagra** [comment]
Facing Same issue since the New Update on W10 21H2.

Workaround I have found is basically resizing the window, which then displays the text.

**Comment by hluk** [comment]
I'm going to close this in favor of: #1728

Please follow there.
