### ISSUE TITLE
Borders for pop up window looks disbalanced

### ISSUE THREAD

**Issue by AlexGrok** [hluk/CopyQ#2095]
Before creating a new issue, see list of [known
issues](https://copyq.readthedocs.io/en/latest/known-issues.html).

**Describe the bug**
Text located too close to right part, while a lot of space on the left 

**To Reproduce**
1. Open pop up windows with any applicable action. in my case with keyboard

**Expected behavior**
Laft part should be smaller, while right one - greater

**Screenshots**
![2022 09 20-10 10 11-Screenshot](https://user-images.githubusercontent.com/32612853/191191403-21d8c949-5d2b-4b0f-92e7-cab11a459229.jpg)

**Version, OS and Environment**
(Get details from `copyq version` command if possible.) Copyq version command doesnt work:
![2022 09 20-10 14 26-Screenshot](https://user-images.githubusercontent.com/32612853/191191762-e35c74a7-6eaf-43c4-bf96-2894638a7e26.jpg)
 - Application Version 6.3.0 (just updated from 6.2.0)
 - OS Windows 10

**Comment by hluk** [comment]
This is mostly how Qt renders the menu. The borders look good on my side.

You can try adding some margins or padding in style sheet files.
See: https://copyq.readthedocs.io/en/latest/theme.html#style-sheets

> Copyq version command doesnt work

Yeah, unfortunately, it is not possible (or very hard) to create GUI application on Windows that also acts well on command line.
