### ISSUE TITLE
Blank items in v6.3.0

### ISSUE THREAD

**Issue by majkinetor** [hluk/CopyQ#2105]
**Describe the bug**

I have blank items since v 6.3.0 that start showing up when I invoke search.

**Screenshots**

![copyq](https://user-images.githubusercontent.com/85767/192148986-e4b11d16-fccb-4187-ba2e-0f53c1f0ceae.gif)

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Application Version 6.3.0
 - OS Windows Enterprise 10.7.2021.

**Comment by hluk** [comment]
Please install 6.3.1 released yesterday (see #1728, #2093).
