### ISSUE TITLE
WITH_QT6 depends on kf5-notifications

### ISSUE THREAD

**Issue by nunotexbsd** [hluk/CopyQ#2106]
**Describe the bug**

WITH_QT6 depends on kf5-notifications to build and it fails if not installed:
```
-- Building for X11 window system.
CMake Error at src/platform/x11/x11platform.cmake:37 (find_package):
  Could not find a package configuration file provided by "ECM" with any of
  the following names:

    ECMConfig.cmake
    ecm-config.cmake

  Add the installation prefix of "ECM" to CMAKE_PREFIX_PATH or set "ECM_DIR"
  to a directory containing one of the above files.  If "ECM" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  src/platform/platform.cmake:13 (include)
  src/CMakeLists.txt:25 (include)
```

From src/notifications.cmake:
```
OPTION(WITH_NATIVE_NOTIFICATIONS "Build with native notification support" ON)

if (WITH_NATIVE_NOTIFICATIONS AND WITH_QT6)
    message(WARNING "Native notifications are not supported with Qt 6")
elseif (WITH_NATIVE_NOTIFICATIONS)
    set(KF5_MIN_VERSION "5.18.0")
```
Is there a way to build it without kf5-notification installed since it doesn't link to libKF5Notifications.so.5?

**To Reproduce**

Build WITH_QT6=ON without kf5-notification installed

**Version, OS and Environment**

 - Application Version 6.3.1
 - OS FreeBSD

**Comment by hluk** [comment]
The CMake error is related to missing **Extra CMake Modules** (ECM) which is needed to build the Wayland support.

https://github.com/hluk/CopyQ/blob/4b81a53b4778b7d5eb68d098c2cb2ad3bd9ea746/src/platform/x11/x11platform.cmake#L36-L37

**Comment by nunotexbsd** [comment]
FreeBSD port flavorize: add Qt6
https://cgit.freebsd.org/ports/commit/?id=a179d4cf80185bcb3cf47e260121562dff1371f1

Thanks

**Comment by hluk** [comment]
> FreeBSD port flavorize: add Qt6 https://cgit.freebsd.org/ports/commit/?id=a179d4cf80185bcb3cf47e260121562dff1371f1

Nice, thanks for sharing.

The Qt 6 build is not extensively tested. A GitHub Action is missing to cover building and testing it.

Also, KNotifications should support Qt 6 soon (if it already does not support it).
