### ISSUE TITLE
CopyQ main window shows blank entries on MacOS 12.6 if content was copied while main window was closed.

### ISSUE THREAD

**Issue by cpagravel** [hluk/CopyQ#2108]
**Describe the bug**
- After copying new content while the main window is closed and then opening the main window, CopyQ will display a blank entry.
- The blank entry contains content and can be pasted, but the entry will remain blank until the window is resized (using the window edge arrows).
- This behavior does not occur if new content is copied while the main window is already open.

**To Reproduce**
Steps:
1. Ensure the main window is closed.
2. Select some text and copy it to the clipboard.
3. Open the CopyQ main window and see a blank entry.

Noteworthy points:
- The entry can be pasted despite being blank.
- The entry will "fix" itself if the CopyQ main window is resized.
- The behavior does not occur if the CopyQ main window was opened at the time of copying to the clipboard.

**Expected behavior**
It is expected that entries will show the text that they contain if text is copied to the clipboard while the CopyQ main window is not open.

**Screenshots**
- Before copying
<img width="616" alt="image" src="https://user-images.githubusercontent.com/9516565/192173369-920b0631-ad77-4828-b30e-1013e800928b.png">
- After closing the main window, copying a few items to clipboard, and then opening the main window
<img width="607" alt="image" src="https://user-images.githubusercontent.com/9516565/192173540-e9e87118-c930-4c9e-aef7-f0f504e1d27b.png">
- After resizing the window.
<img width="638" alt="image" src="https://user-images.githubusercontent.com/9516565/192173580-204fb48c-3c98-4afe-af3c-3bc8711597f1.png">

**Version, OS and Environment**
- Details from `copyq version`:
```
CopyQ Clipboard Manager 6.3.0-gbf2d498e-v6.3.0
Qt: 5.15.5
KNotifications: 5.87.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: macOS 12.6
```

**Additional details**
- Processor - I'm using a Apple M1 Pro processor: `machdep.cpu.brand_string: Apple M1 Pro`
- I installed CopyQ by using Homebrew: `brew install copyq`

**Comment by hluk** [comment]
Please install 6.3.1 released yesterday (see #1728, #2093).
