### ISSUE TITLE
random blanking out of first tab

### ISSUE THREAD

**Issue by harriott** [hluk/CopyQ#2109]
## Describe the bug
Clippings in first tab are now occasionally blanked out.

## To Reproduce
Arch linux > Openbox > CopyQ

## Expected behavior
clippings in first tab should be visible

## Screenshots
[CopyQclipboardBlanks.jpg](https://www.dropbox.com/s/qj8d71bksp2k3iv/CopyQclipboardBlanks.jpg)

## Version, OS and Environment
CopyQ Clipboard Manager 6.3.0
Qt: 5.15.6
KNotifications: 5.98.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Arch Linux

## Additional context
As this began sometime while `copyq 6.2.0-2` was installed, I'm guessing it's an interaction with something else that changed on my system, maybe [qt5-svg](https://archlinux.org/packages/extra/x86_64/qt5-svg/) or [qt5-wayland](https://archlinux.org/packages/extra/x86_64/qt5-wayland/).

My workaround is to bind a key in `Openbox` to do this:
```bash
pkill copyq; copyq &
sleep 1; copyq show
```

**Comment by hluk** [comment]
Please install 6.3.1 released yesterday (see #1728, #2093).

**Comment by harriott** [comment]
Yes, that appears to be working, thanks.
