### ISSUE TITLE
Copying text without formatting

### ISSUE THREAD

**Issue by interduo** [hluk/CopyQ#2111]
**Is your feature request related to a problem? Please describe.**
Many of us are copying from one place to another without formatting because it do a mess.

**Describe the solution you'd like**
CTRL+SHIFT+V - paste text from clipboard without formatting

**Describe alternatives you've considered**
As a workaround now I do:
- paste clipboard content to notepad++,
- copy again content to clipboard,
- paste to destination place

This should be simple.

**Comment by hluk** [comment]
See: https://copyq.readthedocs.io/en/latest/faq.html#how-to-paste-as-plain-text

**Comment by interduo** [comment]
Awesome!! 

Maybe some main keyboard binding should be added by default? 
- open windows: F6,
- paste as text: ctlr+shift+v

**Comment by hluk** [comment]
To be clear, the instructions in the FAQ are to install a command that can be triggered with a single custom global shortcut (set in the step number 4).
