### ISSUE TITLE
Text format gets lost when copyq is used to copy text from google doc

### ISSUE THREAD

**Issue by amosbird** [hluk/CopyQ#2119]
Before creating a new issue, see list of [known
issues](https://copyq.readthedocs.io/en/latest/known-issues.html).

**Describe the bug**
Text format gets lost when copyq is used to copy text from google doc.

**To Reproduce**
1. Go to [this doc](https://docs.google.com/document/d/1N2389PC9Ri3XXKWUk008KUx4dzxQOKUAdS92cmPVuFc/edit?usp=sharing)
2. Select all context and do ctrl-c copy
4. Open another empty google doc and paste from copyq

**Expected behavior**
Content format remains the same of the original copy.

**Screenshots**
There is no need to provide screenshots. It's easy to reproduce.

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
CopyQ Clipboard Manager 6.3.2
Qt: 5.15.6
KNotifications: 5.98.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Arch Linux

**Additional context**
None

**Comment by hluk** [comment]
Well, it works for me. Can you check if the item in CopyQ contains `text/html` (with F4 shortcut)?

**Comment by amosbird** [comment]
> Well, it works for me. Can you check if the item in CopyQ contains text/html (with F4 shortcut)?

It's `text/plain`.

**Comment by hluk** [comment]
Do you have HTML enabled in preferences?
![image](https://user-images.githubusercontent.com/38054/193268720-51280a9f-d8c0-41f2-9fa0-992a67775f03.png)

Also, check if clipboard contains text/html after copying from the document (Ctrl+Shift+C to list clipobard formats in CopyQ).

**Comment by amosbird** [comment]
> Do you have HTML enabled in preferences?

Aha, that's the root cause. Thank you!
