### ISSUE TITLE
Text Font akward in dark mode in Linux Mint 20.03

### ISSUE THREAD

**Issue by kameshkotwani** [hluk/CopyQ#2122]
When changing the theme of copyq to dark in Linux Mint 20.3 the font changes and it becomes blurry and not visible properly

**To Reproduce**
1. Go to 'Preferences -> Appearance'
2. Click on 'dark in Theme dropdown'
4. You will see the font changes abruptly which it should not.

**Expected behavior**
The font should be normal as it is in other themes.

**Screenshots**

## Font in dark theme (blurry and awkward)
![Appearance Page](https://user-images.githubusercontent.com/36355951/193417732-0e8d49ae-5be3-4bdb-ae61-48ae85dbb965.jpg)

![Dark Themed Clipboard Page with blurry and bad font](https://user-images.githubusercontent.com/36355951/193417775-672e8397-1da2-429b-b7d5-7789af875803.jpg)

## Font in Light and Other themes (Clear and Crisp)
![Light Theme Page](https://user-images.githubusercontent.com/36355951/193417863-76678774-9768-430f-8184-809a0ab84acc.jpg)

![Light Theme clipboard page](https://user-images.githubusercontent.com/36355951/193417905-0fe3e1b3-71a9-4b9b-8965-9eab609766ca.jpg)

## About Page
![About Page](https://user-images.githubusercontent.com/36355951/193418011-3213757e-db29-488a-83f4-0fcf45d4c175.jpg)

Copyq version output
```bash

CopyQ Clipboard Manager 6.1.0
Qt: 5.11.3
KNotifications: 5.54.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Linux Mint 20.3

```

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Application Version 6.1.0
 - OS Linux Mint 20.3

**Comment by hluk** [comment]
All the screenshots look blurry to me on my screen.

CopyQ uses Qt framework to render text. Qt should use the system configuration. I don't think I can fix this in the application.

Try turning off the "Antialias" option - though I would expect the text would get less nice jagged edges.

**Comment by hluk** [comment]
I've changed the font from Ubuntu Condensed to the system default sans-serif: https://github.com/hluk/CopyQ/commit/cca529ac559b1d286c737981a5e851269d0a248d
