### ISSUE TITLE
order of items wrong when selected down-up

### ISSUE THREAD

**Issue by ritmation** [hluk/CopyQ#2124]
A bug has been introduced in version 6.3.1:
When selecting items down up, the first selected item is placed on top, then the rest of the items are simply appended in the order they appear in a copyq tab.
Top down selection works fine.

For example, let's assume I have 10 items in a tab:

item 1
item 2
item 3
item 4
item 5
item 6
item 7
item 8
item 9
item 10

If I select items starting from Item 10 and continuing to Item 1 and copy the selection to the clipboard, the items will be copied to the clipboard in the following order:

item 10
item 1
item 2
item 3
item 4
item 5
item 6
item 7
item 8
item 9

The same thing happens regardless of where in the tab the selection starts. Using the example above, selecting items from 7 to 3 will copy the items in the following order:

item 7
item 3
item 4
item 5
item 6

Up to version 6.3.0, the items were always copied in the order they were selected.

Selecting the items in top-down (Item 1 - Item 10) direction works fine.

Copyq version 6.3.2
Windows 10 1809 LTSC

**Comment by hluk** [comment]
I started relying on Qt framework again to handle the key press events. But it seems to reorder items in the selection so I will have to revert to the old code.
