### ISSUE TITLE
copyq doesn't always restore the last window size

### ISSUE THREAD

**Issue by puchu** [hluk/CopyQ#2125]
**Describe the bug**
copyq doesn't always restore the last window size

**To Reproduce**
1. assign a shortcut to - "Show/hide main window"
2. move the mouse while pressing the shortcut multiple times
3. window gets resized to minimum size after multiple restores

**Expected behavior**
the window size gets restored

**Version, OS and Environment**
CopyQ Clipboard Manager 6.3.2
Qt: 5.15.5
KNotifications: 5.98.0
Compiler: GCC
Arch: x86_64-little_endian-lp64

**Additional context**

**Comment by puchu** [comment]
![image](https://user-images.githubusercontent.com/3678296/193786373-0695edc9-5cb0-4c2e-beca-cba77b6295b6.png)

**Comment by hluk** [comment]
That is a known problem with some window managers and frame size - Qt fails to get/restore correct window size. I don't think I can fix that in the application.

Possible workaround is to map a shortcut to `copyq showAt X Y` where X Y is fixed position on screen.
