### ISSUE TITLE
paste not working on void linux

### ISSUE THREAD

**Issue by eqn-grp** [hluk/CopyQ#2130]
Paste not working on void linux, on sway (wayland).
I tried pasting using  ```Ctrl + V``` 

didn't work.

**Comment by laur89** [comment]
whilst in terminal, try
```
 copyq add test && copyq select 0 && copyq paste
```
Is `test` pasted into the window?

**Comment by laur89** [comment]
Try these scenarios:

**A**
- make sure copyq is not running (`$ killall copyq`)
- copy text in say a browser window via ctrl+c, and try to paste it onto address bar via ctrl-v
 
**B**
- make sure copyq _is_ running
- same as last point in scenario A

Do A & B have different outcomes?

**Comment by hluk** [comment]
Wayland requires some workarounds for clipboard access to work, see: https://copyq.readthedocs.io/en/latest/known-issues.html#on-linux-global-shortcuts-pasting-or-clipboard-monitoring-does-not-work
