### ISSUE TITLE
Qt6: Could NOT find QtWaylandScanner

### ISSUE THREAD

**Issue by algent-al** [hluk/CopyQ#2131]
**Describe the bug**
```
CMake Error at /usr/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find QtWaylandScanner (missing: QtWaylandScanner_EXECUTABLE)
Call Stack (most recent call first):
  /usr/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/ECM/find-modules/FindQtWaylandScanner.cmake:87 (find_package_handle_standard_args)
  src/platform/x11/systemclipboard/CMakeLists.txt:1 (find_package)
```
CMake expect to find `QtWaylandScanner_EXECUTABLE` in `/usr/bin/qtwaylandscanner` but it is in `/usr/lib64/qt6/qtwaylandscanner` instead for `qt6-wayland`.

**To Reproduce**
1. Build with `-DWITH_QT6:BOOL=ON` flag.

**Expected behavior**
Building it from source code should work as it is working with Qt5.
I made a symbolic link of `/usr/lib64/qt6/qtwaylandscanner` to `/usr/bin/qtwaylandscanner`. To test if the build succeeds and it worked, but this is a problem because `/usr/bin/qtwaylandscanner` belongs to `qt5-wayland`

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Application Version: 6.3.2
 - OS: Solus
 - Desktop environment: Budgie

**Comment by algent-al** [comment]
Fixed with this flag `-DQtWaylandScanner_EXECUTABLE:FILEPATH=/usr/lib64/qt6/qtwaylandscanner`.

**Comment by hluk** [comment]
Yeah, I need to override it manually also with a different path on Fedora 36: `/usr/lib64/qt6/libexec/qtwaylandscanner`

Any ideas how to fix that properly? I failed find a nicer solution.

**Comment by hluk** [comment]
I think I found the solution (#2133).
