### ISSUE TITLE
Ability to display the content to be pasted under the cursor

### ISSUE THREAD

**Issue by DoctorSigma** [hluk/CopyQ#2132]
**Describe the solution you'd like**
  Before your program, I used Clipdiary, but there was a need for cross-platform functionality.
  So I chose your program, I like everything very much, but there is one problem.
  It consists in the fact that in the previous program, you could select recently copied elements by pressing certain keys and pressing the up or down arrow. That is, by pressing a certain key and the up arrow, you copied the previous item in the list, and when you unpressed all the keys, the selected item is inserted into the window. It is very convenient.
  Unfortunately, I did not notice this possibility in your program.
  I tried to use the possibilities and write a script that would select the next/previous items in the list when a key is pressed. However, I could not:
- find a function, or something else, that would wait for me to release the hotkey, thereby inserting the text I selected.
- find the ability in the popups() function to specify that this window appears at certain coordinates, or best of all, under the mouse cursor, thus I would display the selected element under the cursor, as it was in Clipdiary.
- I don't know if the popups() command will be able to show the image I selected in this window.

**Comment by hluk** [comment]
This has been requested before in #1948, see: https://github.com/hluk/copyq-commands/tree/master/Global#cycle-items

**Comment by DoctorSigma** [comment]
However, it is described there, judging by what I read, the script that causes the main window, that is, the show() function is used, and the window can open almost the entire screen and it does not open under the cursor. This is a little inconvenient, especially as two monitors and the window will open on another. And I asked about the script using the popups() function, which would simply show a small, neat window without unnecessary buttons and tabs.

**Comment by hluk** [comment]
You can try the following modified command which shows just the popup instead of the main window:

```ini
[Command]
Command="
    copyq:
    const selectedRowOption = 'cycleItemsSelectedRow'
    const activeOption = 'cycleItemsActive'

    if (settings(activeOption) == 1) {
        const row = settings(selectedRowOption) + 1;
        settings(selectedRowOption, row)
        popup(read(row));
    } else {
        settings(activeOption, 1)
        settings(selectedRowOption, 0)
        popup(read(0));

        // Wait for shortcut modifiers to be released.
        while (queryKeyboardModifiers().length > 0) {
            sleep(20);
        }
        
        settings(activeOption, 0)
        const row = settings(selectedRowOption)
        if (row != -1) {
            select(row)
            paste()
        }
    }"
GlobalShortcut="ctrl+;"
Icon=\xf1b8
IsGlobalShortcut=true
Name=Cycle Items
```

**Comment by DoctorSigma** [comment]
It works strange, skips some items. And can I remove this window from the Popups () team on certain coordinates, and a certain maximum size, saw the command showat(X, Y, Width, Height, Tabname), but there are unnecessary buttons and tabs that mix? Then there may be an analogue of popups(), but there are no extra buttons or tabs, such as in the photo below.

![image](https://user-images.githubusercontent.com/93322905/194889344-43c10e8c-75b9-43b7-af33-9d5439a25c40.png)

**Comment by hluk** [comment]
I've updated the command: https://github.com/hluk/copyq-commands/tree/master/Global#cycle-items---quick

Which items does it skip? BTW, the command would need some work to show images.

You can remove the toolbar and scrollbars in Preferences (Layout and Appearance tabs).

To remove the menu bar see: [How to hide the menu bar in the main CopyQ window?](https://copyq.readthedocs.io/en/latest/faq.html#how-to-hide-the-menu-bar-in-the-main-copyq-window)

**Comment by DoctorSigma** [comment]
Oh, if you can hide those elements that I marked in the screenshot, that's great.
It missed some elements that I copied, let's say I copied the numbers from 1 to 9 separately and used this script, and some numbers were not displayed, they were skipped.
And another question: is it possible to find out the number of lines in the selected element, let's say this is a word, then it is one line, what if it is a larger text, for example, like 1 element on the screenshot where there are 4 lines?

**Comment by hluk** [comment]
> And another question: is it possible to find out the number of lines in the selected element, let's say this is a word, then it is one line, what if it is a larger text, for example, like 1 element on the screenshot where there are 4 lines?

It should be possible with [Display commands](https://copyq.readthedocs.io/en/latest/commands-display.html) and some scripting to show number of lines near the items.
