### ISSUE TITLE
one shot text input command

### ISSUE THREAD

**Issue by amosbird** [hluk/CopyQ#2134]
**Is your feature request related to a problem? Please describe.**
It's a common case to mimic user input with some script, such as auto-fill text box, password, etc.

Directly generate keyboard events for this purpose does not always work. And it's somehow slow. Using clipboard instead would be better.

**Describe the solution you'd like**
Build a copyq command that accepts a string, puts it into current clipboard, pastes it and then restore current clipboard with previous content.

**Comment by hluk** [comment]
Something like [this](https://github.com/hluk/copyq-commands/tree/master/Global#paste-current-date-and-time)?

**Comment by amosbird** [comment]
But it doesn't contain the logic of restoring the previous clipboard content.

**Comment by hluk** [comment]
If you need to restore just the text you can modify the command:

```js
copyq:
const oldText = clipboard();
copy('Some text');
paste();
sleep(1000);
copy(oldText);
```

**Comment by amosbird** [comment]
Thanks!
