### ISSUE TITLE
current clipboard content in the tray icon 

### ISSUE THREAD

**Issue by joihn** [hluk/CopyQ#2135]
I would like to have the current text content of my clipboard always displayed in the taskbard , next to the try icon 

The alternative software "clipboard indicator" already does it

**Comment by hluk** [comment]
By default, depending on your platform, the clipboard content should be displayed as tray icon tooltip (if you hover over icon). It is also visible in main window title.

**Comment by joihn** [comment]
yes (I'm on ubuntu 20), but I would prefet not to have to hover or click the icon (= always on diplay)

**Comment by hluk** [comment]
If you disable the tray icon, the main window should minimize by default and at least in some task bars the window title (with the current clipboard content) should be visible.

I don't think I can fix this specifically for Ubuntu.
