### ISSUE TITLE
CopyQ with Vim/Nvim

### ISSUE THREAD

**Issue by nocibambi** [hluk/CopyQ#2138]
**Is your feature request related to a problem? Please describe.**
I want to use copyq with vim/nvim (on Ubuntu).

**Describe the solution you'd like**
1. Copy text outside vim and paste in vim
2. Yank text in vim and paste outside vim.

**Describe alternatives you've considered**
I found this implementation: https://vi.stackexchange.com/questions/31805/how-to-set-copyq-to-handle-clipboard.

It manages to add text from vim to copyq list. Issues:
- Yanking in vim does not add the text to the system clipboard automatically (I have `set clipboard=unnamedplus` enabled).
- Selecting an item in copyq from vim moves the focus to another window (e.g. my browser) and pastes the text there not into vim.

**Comment by nocibambi** [comment]
I found a solution [here](https://vi.stackexchange.com/questions/15212/neovim-clipboard-selection?rq=1) that works with `xclip`:

```vim
let g:clipboard = {
  \   'name': 'xclip-xfce4-clipman',
  \   'copy': {
  \      '+': 'xclip -selection clipboard',
  \      '*': 'xclip -selection clipboard',
  \    },
  \   'paste': {
  \      '+': 'xclip -selection clipboard -o',
  \      '*': 'xclip -selection clipboard -o',
  \   },
  \   'cache_enabled': 1,
  \ }
```

**Comment by hluk** [comment]
This seems to be a problem outside CopyQ.

I have been using `set clipboard=unnamed,unnamedplus` in NeoVim (and `set clipboard=unnamedplus` previously in Vim) for a long time without any issue.
