### ISSUE TITLE
Toolbar/Mini Mode

### ISSUE THREAD

**Issue by kidimbwi** [hluk/CopyQ#2148]
**Is your feature request related to a problem? Please describe.**
we currently have the "Show main window under mouse cursor" option which enables us to access the clipboard history quickly but sometimes you want to see, at a glance, the current content of the clipboard without using any keyboard shortcuts.

**Describe the solution you'd like**
ClipMate(now discontinued) had the ClipBar that resided on the taskbar(i'm using CopyQ on Windows) 

![clipbar_dropdown](https://user-images.githubusercontent.com/65897337/197168136-5ea44a58-0c7e-4ca3-9630-4633f114e811.gif)

that enabled a user to see the latest clip in the clipboard and on a mouse click, the rest of the clipboard contents. with the release of Windows 11. the ClipBar no longer works which brings me to CopyQ. would it be possible to have a toolbar mode for the program where it would be dockable anywhere on a users desktop. be it just above the taskbar like we see with JetAudio's toolbar mode

![screenshot_03](https://user-images.githubusercontent.com/65897337/197169026-96648bdd-3641-40c8-b694-b2f9d090a71f.jpg)

or Password Depot's Top Bar visible in this screenshot above the web browser

![TopBarMode_](https://user-images.githubusercontent.com/65897337/197169790-3271354e-fdb4-4f2b-8d9b-c88b269ac729.png)

if such a mode existed, we would be able to quickly view the latest clipboard entry by looking at CopyQ when it was in that mode.

**Describe alternatives you've considered**
ClipMate with its ClipBar was my clipboard manager of choice but with its discontinuation in 2015, lack of unicode support and now the ClipBar not working in Windows 11, the time has come to move on to an actively developed clipboard manager.

**Additional context**

**Comment by hluk** [comment]
Unfortunately, this is something that would work only on Windows and would be difficult to implement and maintain on other platforms (impossible on some).

**Comment by kidimbwi** [comment]
Understood. Thank you for giving an explanation as to why it is not possible to implement this feature i appreciate it.

cheers.
