### ISSUE TITLE
[help wanted] This regex failed to execute

### ISSUE THREAD

**Issue by 7peanuts** [hluk/CopyQ#2149]
**Describe the bug**
Hi, I have a problem.
This regular expression: `/^(?:(?<!https:\/\/).)*?([a-zA-Z]+)\/video\/(\w+)\/?$/` ➡️ `$1_$2`
I'm tested here and it can execute replacement.
https://regex101.com/r/xBFAL9/1
But the replacement is not performed in CopyQ.
eg: `https://www.abc123.com/abc/video/abc123/`

![20221022144639](https://user-images.githubusercontent.com/82173614/197325283-cfabccec-627d-4ba4-989e-e2f96cbb07e3.jpg)

Here is my CopyQ command
```js
copyq:
// Replace this regexp ...
var replaceWhat = /^(?:(?<!https:\/\/).)*?([a-zA-Z]+)\/video\/(\w+)\/?$/
// .. with this text.
var replaceWith = '$1_$2'

var text = str(input())
if ( text.match(replaceWhat) ) {
  var newText = text.replace(replaceWhat, replaceWith)

  // Copy replaced text back to clipboard.
  copy(newText)

  // Change data to save in item list.
  setData(mimeText, newText)
  removeData(mimeHtml)
}
```
If I remove the first part of the regular expression it will execute.
`.*?([a-zA-Z]+)\/video\/(\w+)\/?` ➡️ `$1_$2`

**Version, OS and Environment**

 - Application Version [6.3.2]
 - OS [Windows 11 22H2 22621.675]

**Comment by hluk** [comment]
It it should work, it is most likely a bug in Qt or some related library.

Not sure how to read the the regex itself - the non-capturing group with the negative look-behind looks strange. How about this one: `/^(?:https:\/\/)?.*?([a-zA-Z]+)\/video\/(\w+)\/?$/`  (https://regex101.com/r/xBFAL9/3)

**Comment by 7peanuts** [comment]
> the non-capturing group with the negative look-behind looks strange.

The purpose of the negative lookbehind is to not match replace when copying the entire URL containing `https://`, and to replace when copying the second half of the URL.
I don't know if there is another way to write it.

**Comment by fade2gray** [comment]
![Capture3](https://user-images.githubusercontent.com/1332009/197643939-309ca73a-9152-4bde-844e-8c184d7edc44.PNG)

**Comment by 7peanuts** [comment]
> ![Capture3](https://user-images.githubusercontent.com/1332009/197643939-309ca73a-9152-4bde-844e-8c184d7edc44.PNG)

What your browser?
I don't have this message on Firefox or Chromium 107.0.5304.67 & 86.0.4240.198, not sure if it's related to system components.

**Comment by hluk** [comment]
> The purpose of the negative lookbehind is to not match replace when copying the entire URL containing `https://`, and to replace when copying the second half of the URL.

How about adding `!text.startsWith("https://")` to the condition in the code instead of having a complex regex?

I also see the warning "This construct may not be supported in all browsers" in Firefox 105.0.2. BTW, make sure you switch the regex flavor in side bar to **ECMAScript**.

**Comment by 7peanuts** [comment]
> I also see the warning "This construct may not be supported in all browsers" in Firefox 105.0.2. BTW, make sure you switch the regex flavor in side bar to **ECMAScript**.
> 
Ah, I saw this warning.

> How about adding `!text.startsWith("https://")` to the condition in the code instead of having a complex regex?
> 
So how should I change this command? Sorry, I'm not familiar with the code.
