### ISSUE TITLE
copyq fails to create a tray icon from a root script

### ISSUE THREAD

**Issue by DoctorSubtilis** [hluk/CopyQ#2155]
**Describe the bug**
I have the correct icon tray starting copyq as user, but starting copyq as user from a root script (sudo -u myuser ...) I cannot get the icon tray (even the server starts).

**To Reproduce**
1. Exit from copyq
2. Start copyq with the command 'sudo -u myuser env QT_QPA_PLATFORM=xcb copyq --start-server show'
3. You get the server working and the main window shown, but no tray icon

**Expected behavior**
Tray icon visible

**Screenshots**

**Version, OS and Environment**
copyq --version
CopyQ Clipboard Manager 6.0.1
Qt: 5.15.2
KNotifications: 5.89.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: KDE neon 5.26

**Additional context**

**Comment by DoctorSubtilis** [comment]
Updating to the last release (6.3.2) not fixed the icon tray problem

**Comment by hluk** [comment]
I think KDE may hide icons by default. Can you configure visibility by right clicking on tray area and selecting "Configure System Tray..."?

![image](https://user-images.githubusercontent.com/38054/199087268-887f2cc8-56a7-4046-8845-4cefc5727579.png)

![image](https://user-images.githubusercontent.com/38054/199087503-f3edc85e-be8b-450d-9530-7ef3da194cdd.png)

**Comment by DoctorSubtilis** [comment]
I had already tried this, but nothing to do. As I have said, the tray icon is correctly shown when I start copyq **as user**. The problem raises only when I start copyq **from a root script**. And this is why I have opened a new thread.  
Thank you.

**Comment by hluk** [comment]
I don't know what is the difference between `sudo -u USER` and running app without sudo - possibly some missing env variables.

Anyway, in this case the problems is not in the application itself but in the non-standard way it's being started. Not sure how much I can help here.

**Comment by hluk** [comment]
Please see the real value for `DBUS_SESSION_BUS_ADDRESS` in your desktop environment. It is possibly something like `unix:path=/run/user/1000/bus`.

**Comment by DoctorSubtilis** [comment]
It works! Thank you. Some few other attempts and I will put resolved!
