### ISSUE TITLE
Can not paste to firefox when firefox start with MOZ_ENABLE_WAYLAND=1 env set.

### ISSUE THREAD

**Issue by zw963** [hluk/CopyQ#2156]
Because some long not fix issue, please check discuss on arch linux bbs https://bbs.archlinux.org/viewtopic.php?id=279607.

I have to start my firefox with use wayland mode. (set environment variable MOZ_ENABLE_WAYLAND=1)

But, after that, i can not active my copyq when current active window is firefox, then i fixed it use https://github.com/hluk/CopyQ/issues/1843#issuecomment-991863745, copyq can raise the window now(copyq toggle), but after i select a text to paste, copyq always paste those content into my konsole (i guess it is the Xorg compatible which start before firefox?)

I don't sure if some issue need to be fix for copyq or firefox? or just copyq not support wayland?

Thank you.

**Comment by hluk** [comment]
Unfortunately, pasting on shortcut or Enter key from CopyQ does not work in Wayland apps (passing a shortcut to paste is not supported by Wayland compositors).

See: https://copyq.readthedocs.io/en/latest/known-issues.html#known-issue-wayland

I have been prototyping a simple clipboard manager in Python which uses a different way to paste text to apps: https://github.com/hluk/infinitecopy

But again not all apps supports it though it seems to work in Firefox on Wayland.

**Comment by zw963** [comment]
Hi, can i know how to use it with CopyQ?

And, i following the README in that repo, not work.

**Comment by hluk** [comment]
> Hi, can i know how to use it with CopyQ?

It is separate app - a completely different clipboard manager - and unfortunately a lot simpler one.
