### ISSUE TITLE
In other words, I want to select entry 1, 2, 3, ....N.

### ISSUE THREAD

**Issue by Hela-Girl** [hluk/CopyQ#2160]
I've been using your program for a long time and I think it's the best!
I just wanted to clarify one thing, how to assign keys to select entries from the list 1, 2, 3, ....N.
In other words, I want to select entry 1, 2, 3, ....N.
It's possible.?

**Comment by hluk** [comment]
Not sure if I understand. Can you use Shift+Down shortcut or mouse click with Shift or Ctrl?

**Comment by hluk** [comment]
By default (with the 'Search for numbers' disabled) if you enter a number, CopyQ will filter items containing the number but also directly select an item in corresponding row (if there is such a row). So if you enter 100 and press enter, item in row 100 should be copied.

There are also some command that allow the items to be pasted with a global shortcut. See: https://github.com/hluk/copyq-commands/tree/master/Global#select-nth-item (see [README.md](https://github.com/hluk/copyq-commands/blob/master/README.md) for details on how to add the command)
