### ISSUE TITLE
Undo/Redo data in CopyQ history (feature)

### ISSUE THREAD

**Issue by IT-Tool** [hluk/CopyQ#2162]
It's a pity that now there is no function to undo the last action(s) if something was deleted by accident in the CopyQ history for example.

It would be very helpful. This increases the reliability of stored data in CopyQ (for user).

Maybe this will be useful https://github.com/d-led/undoredo-cpp

**Comment by hluk** [comment]
The functionality can be added through commands: https://github.com/hluk/copyq-commands/tree/master/Application#undoable-move-to-trash (see [README.md](https://github.com/hluk/copyq-commands/blob/master/README.md) for details on how to add the command).

**Comment by LeChatNoir666** [comment]
That's a great workaround!
The "Delete" option in the Context Menu next to edit is sometime a pain if miss-clicked!
Is there a way to edit the Context Menu entries so I could put "Delete" to the bottom?

Anyway great tool, hluk! :)

**Comment by hluk** [comment]
> Is there a way to edit the Context Menu entries so I could put "Delete" to the bottom?

Move the command in the list in the Command dialog. The order in menu and toolbar follows this order.

**Comment by Korb** [comment]
> Undo/Redo data in CopyQ history (feature)

/dup #187?
