### ISSUE TITLE
Suggestions for CopyQ moving forward.

### ISSUE THREAD

**Issue by MQuigg** [hluk/CopyQ#2165]
This is a great program, maybe the best clipboard manager around. Been using it for a couple years and have a feature suggestion... Expand the search feature so it will search either sub-folders or the entire folder tree for notes. If you could do that, then we could simply store clips into sub-folders (or same-level folders) accordingly, and then find them with the search quickly and easily regardless of where they were located in the tree. Using multiple folders means we could work around the program's data storage limitations without an need for a major re-write, and also use sessions if we run out of space with a single session.

Thanks for maintaining this awesome program. Much appreciated!

Mark

**Comment by hluk** [comment]
Not sure if you have the same thing in mind, but for some time I was thinking about changing the default data format to store items similarly to the [Sync plugin](https://copyq.readthedocs.io/en/latest/synchronize.html) (each CopyQ item is stored in one or more files) with couple of improvements.

This has many advantages:
- deprecates the complex Sync plugin
- would be probably simpler have a better performance then using sqlite database (single file)
- decrease memory usage by a lot
- faster app start, loading tabs and saving items
- in case of data file corruption, usually not all items would be affected
- tabs could include a lot more items

The downsides are:
- it is a big change
- the app would need to migrate the old data files
- search could be slower (but it would be possible to search through all files from command line or in a file manager)

Unfortunately, it is a big change and I'm not planning to spend too much time on the app anytime soon.

BTW, there is a prototype of simple clipboard manager written in Python that uses sqlite database: https://github.com/hluk/infinitecopy - it would be much easier to apply these ideas there.

**Comment by MQuigg** [comment]
Sounds like a major re-write. I've found that CopyQ works perfectly if many tabs and sub-tabs are created, particularly with images but I'm sure with any data type once there are many items. Only thing I can't do is search for something if it's in another tab.
