### ISSUE TITLE
CopyQ changes \n to \r\n (LF to CRLF) in clipboard because of commits related to Wayland synchronizing UTF-8 

### ISSUE THREAD

**Issue by hwalinga** [hluk/CopyQ#2168]
**Describe the bug**
CopyQ changes newlines (\n) to Microsoft Windows newlines (\r\n). This happens sometimes, but it is reliable reproducible when you switch between applications.

**To Reproduce**
1. `echo -e 'test\ntest' | xclip`
2. Switch applications (alt-tab, alt-tab)
3. `xclip -o | od -bc`
4. See \r\n in output

**Expected behavior**
Don't change newlines in clipboard. (Or just keep them unix.)

**Version, OS and Environment**
 - MX Linux 21.2.1
 - Debian 11.5
 - Xfce 4.16.0
 - X11
 - Qt: 5.15.2
 - KNotifications: 5.78.0
 - Compiler: GCC
 - Arch: x86_64-little_endian-lp64

**Additional context**
I did some debugging for you as I might expect this to be hard to reproduce as it probably depends a lot on the environment, but I hope you manage to reproduce it as well. 

I discovered that when I interactively rebased the codebase and dropped the changes made by c5745458 and af195147 (Wayland: Fix synchronizing UTF-8 texts) the bug disappeared. I suspect some of that code makes some calls that cause the line endings to change. I hope you can figure this out, or maybe just add compatibility code that checks if CopyQ is ran on Wayland or X11 and use the old code if ran on X11.

**Comment by hwalinga** [comment]
If you Google you find some stuff that describes similar issues. Don't know if related: 

https://gitlab.gnome.org/GNOME/gtk/-/issues/2307

https://bugzilla.mozilla.org/show_bug.cgi?id=1547595

**Comment by hluk** [comment]
I tested this only briefly, but I could not reproduce it in KDE/Wayland and Openbox (running under Xephyr) - possibly the XWayland is interfering somehow.

I have been using Wayland for a while and I don't have any reason to switch back to X11.

Any chance you can post a fix for this?

Is this bug in GTK or CopyQ?

**Comment by hwalinga** [comment]
Could not reproduce anymore on my new machine. 

```
CopyQ Clipboard Manager 7.0.0
Qt: 5.15.8
KNotifications: 5.103.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Debian GNU/Linux 12 (bookworm)
```
