### ISSUE TITLE
Smooth scrolling

### ISSUE THREAD

**Issue by k650dg4d2** [hluk/CopyQ#2169]
希望可以添加平滑滚动的功能，类似谷歌浏览器的Chrome://flags/#enable-smooth-scrolling。这样滚动的时候会更舒服。
还有，希望可以用win+v的快捷键替代win10原本的剪切板增强工具。

Hope to add a smooth rolling function, similar to the Chrome: // Flags/#ENABLE-SMOOTH-Scrolling of the Google browser.It will be more comfortable when rolling.

Also, I hope to replace Win10's original shear enhancement tools with the shortcut keys of Win+V.

**Comment by hluk** [comment]
This is probably not going to happen. I see little to no advantage.
