### ISSUE TITLE
Search by note

### ISSUE THREAD

**Issue by cal4** [hluk/CopyQ#2170]
**Is your feature request related to a problem? Please describe.**
Often I have to recall a certain password, which is stored in clipboard history. The problem is that the password is sufficiently random that I can't remember the text within it, so I can't search for it in clipboard history.

**Describe the solution you'd like**
I'd like to be able to add a note to the hard-to-remember item with an easier to remember name. Say "git password" for example. Rather than memorize the random password, then I could search the tray menu for the note and the hard-to-remember item is found.

**Describe alternatives you've considered**
Rather than adding a note, tags could work. One downside is that tags aren't displayed in the tray menu from what I can tell.

**Additional context**
For example, if I typed "git password", the item below would be included in the search:
![image](https://user-images.githubusercontent.com/9409256/200947984-7f006e2d-10dd-4e63-917c-4911c08acd77.png)

**Comment by hluk** [comment]
That is a good idea and would be consistent with the search in the main window.

I've added the feature in this development build: https://ci.appveyor.com/project/hluk/copyq/builds/45431153/artifacts

Feel free to test it.
