### ISSUE TITLE
copyQ don't work well in source insight

### ISSUE THREAD

**Issue by actg** [hluk/CopyQ#2173]
copyQ don't paste content correct in source insight project

show clipboard list with hotkey,and move up or down direction keyboard,select any item,and Press Enter,the hight light content item could not paste correctly.

**Comment by hluk** [comment]
What is "source insight"?

What is the OS, CopyQ version?

Any warning or error in logs?

**Comment by actg** [comment]
windows 10 platform, copyQ 6.3.2 version,
about wiki[source insight](https://en.wikipedia.org/wiki/Source_Insight)

**Comment by hluk** [comment]
Is the correct text field or editor correctly focused after Enter key?

Does the app support pasting with Shift+Insert?

**Comment by actg** [comment]
> Is the correct text field or editor correctly focused after Enter key?
> 
> Does the app support pasting with Shift+Insert?

Yes, source insight editor support shit+insert paste text content.
You can reproduction issue in source insight file editor.

**Comment by hluk** [comment]
I don't have a host with Windows available anymore so I cannot test this. I don't know if I will be able to help.

Try increasing some wait/timeout options for the paste action in CopyQ. You can modify them by opening Action dialog (F5), entering and changing the command below and pressing Enter. These are the default values in milliseconds:

```js
copyq config window_wait_raised_ms 150
copyq config window_wait_after_raised_ms 150
copyq config window_key_press_time_ms 0
```
