### ISSUE TITLE
Ubuntu 22.10: please add "kinetic" to your PPA

### ISSUE THREAD

**Issue by Smurffson** [hluk/CopyQ#2174]
Adding your PPA on (K)Ubuntu 22.10 throws a 404 error:
> https://ppa.launchpadcontent.net/hluk/copyq/ubuntu kinetic Release - 404  Not Found

Could you please add "Kintetic" to your sources? The official Ubuntu repo ist still stuck on 6.2.0

BTW: Many thanks for providing us with this nice little tool. Coming from Windows using ClipCache Pro, it's not easy to find a replacement which is capable of at least of a subset of all the many features CC has available. CopyQ seems the so far the best available option.

**Comment by hluk** [comment]
Added. :+1:

**Comment by Smurffson** [comment]
Wow!Thanks! That was fast... :+1:
