### ISSUE TITLE
6.3.2 not preserving html or rich text formatting

### ISSUE THREAD

**Issue by paul1149** [hluk/CopyQ#2181]
**Describe the bug**
No text formatting is captured or pasted.
This is true whether CopyQ is enabled or disabled.
If I Quit CopyQ, however, text formatting is captured and pasted by the inherent linux clipboard.

I'm on MX Linux 21, with KDE desktop environment. 
I'm using CopyQ 6.3.2.
I have "Save and display HTML and rich text" enabled at Items/Text.
Copying text from either Vivaldi or Brave, into either Libreoffice or Google Docs, produces only plain text. 
Even copying text from within a LO document loses the formatting.

**Comment by hluk** [comment]
Maybe clipboard and mouse selection synchronization is somehow interfering?

Can you test it with "Paste clipboard with mouse" and "Paste mouse selection with keyboard" options disabled (in General config tab)?

![image](https://user-images.githubusercontent.com/38054/204609500-e659c160-c2c8-4c96-8ec1-285acdefeeec.png)

**Comment by paul1149** [comment]
Actually those two were already unchecked. I enabled them, with no difference. Thanks.

**Comment by paul1149** [comment]
I think I found the problem. The KDE desktop has a built-in clipboard manager that resides in the tray. I had it hidden but not disabled. Now that it's disabled copy-q seems to be preserving formatting well.

Thanks! Will close issue.

**Comment by hluk** [comment]
@paul1149 Good to know. Thanks for sharing the solution! :+1:

I don't recall having this specific issue but I remember having to disable the clipboard manager (I believe it is Klipper) in KDE in tray area every time I reset/re-created the KDE panel.
