### ISSUE TITLE
v6.3.2 - unable to run installer: Windows Defender SmartScreen error (corporate machine)

### ISSUE THREAD

**Issue by oryz** [hluk/CopyQ#2183]
On a new (corporate) laptop, I downloaded the installer but when trying to run I get the following error:
![image](https://user-images.githubusercontent.com/20960028/202641778-b59f492d-4042-440b-9bb7-3abc1c670580.png)

**To Reproduce**
1. Download installer
2. Run it

**Expected behavior**
Windows Defender does not detect the installer as suspicious

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Application Version: 6.3.2
 - OS: Windows 10

**Comment by oryz** [comment]
I'm not getting it with the older installer I have on my machine  - v4.1.0

**Comment by hluk** [comment]
CopyQ binaries are not signed in any way that's probably cause of the error. I think there might be a workaround to install the app anyway but I don't remember what it was - maybe some stricter settings do not allow it.

Try to use the portable zip version instead.

**Comment by oryz** [comment]
This works as a workaround: https://www.thewindowsclub.com/microsoft-defender-smartscreen-prevented-an-unrecognized-app-from-starting
