### ISSUE TITLE
Keeping images as JPEG (not BMP)

### ISSUE THREAD

**Issue by flommmm** [hluk/CopyQ#2185]
### Discussed in https://github.com/hluk/CopyQ/discussions/2184

<div type='discussions-op-text'>

<sup>Originally posted by **flommmm** November 18, 2022</sup>
Hey, 

when I copy a JPEG image and paste it, CopyQ delivers JPEG. When I then add e.g. some text into the clipboard, open CopyQ and doubleclick my image again to get it back into clipboard, it will be pasted as BMP and no more as JPEG. Any idea on this?

Best regards
flommmm</div>

**Comment by hluk** [comment]
Answered in #2184.
