### ISSUE TITLE
Import data by google sheet 

### ISSUE THREAD

**Issue by ILG2021** [hluk/CopyQ#2188]
CopyQ is powerful, but the input is not so that convenient. If you can import data by google sheet, it will be much fast. I have realize a restful api by appsscript to CRUD google sheet, you can operate google sheet just by a network request.

**Comment by javathehunt** [comment]
I just came here to ask about importing/exporting into a spreadsheet. Looks like it isnt possible. If anyone knows of a work around please post.

**Comment by ILG2021** [comment]
> I just came here to ask about importing/exporting into a spreadsheet. Looks like it isnt possible. If anyone knows of a work around please post.

It is very easy, just need the developer to add the feature.
