### ISSUE TITLE
Delete all item except pined item

### ISSUE THREAD

**Issue by Hell0Pe0ple** [hluk/CopyQ#2193]
Hello :)

When we want clean the clipboard with some pined items, we Ctrl+A to select home item, but we need to deselect one by one all pined item we want keep before Delete, otherwise we get the message: "unpin item first before remove them".

Its can be good to be enable to remove all unpined item more easily.

Best regard.

**Comment by koloved** [comment]
Command for menu to clear clipboard (keep pinned)

```
copyq:
tab(config('clipboard_tab'))
var count = size()
if (count) {
  for (var i = count - 1; i >= 0; i--) {
    if (!plugins.itempinned.isPinned(i)) {
      remove(i)
    }
  }
}
popup('Clipboard Tab Cleared (Pinned Items Preserved)')
```
