### ISSUE TITLE
How to stop copying file paths in copyq?

### ISSUE THREAD

**Issue by taswsz** [hluk/CopyQ#2196]
Guys, I wonder how to stop copying files' paths? 
As you can see in the screenshot, the path of chrome was copied.
![微信截图_20221130102021](https://user-images.githubusercontent.com/32477259/204691784-23c432d5-0f21-4bb9-a56e-b8932db3e2b1.png)

**Comment by CrendKing** [comment]
An imperfect solution is to set up a command where
```
Command: copyq ignore
In Advanced -> Match Items -> Content: ^file:///
```
This makes CopyQ ignore all text content that starts with `file:///`, which a copied file is coerced to. However, it also ignores any text that happens to be matching the pattern (thus the "imperfect" part).

**Comment by taswsz** [comment]
> An imperfect solution is to set up a command where
> 
> * Command: `copyq ignore`
> * In Advanced -> Match Items -> Content: `^file:///`
> 
> This makes CopyQ ignore all text content that starts with `file:///`, which a copied file is coerced to. However, it also ignores any text that happens to be matching the pattern (thus the "imperfect" part).

gotta try it, thanks anyway
