### ISSUE TITLE
[help wanted]  how to make the main window always on top ?

### ISSUE THREAD

**Issue by iamqiz** [hluk/CopyQ#2202]
thank you very much for developing the useful tool,
i want to make main window always on top, how to do it ?
i use third-party tool to set it always on top, but when the main window lose focus ,it will be closed and disappear from task bar of microsoft windows,
help me pls , thanks !

**Comment by Kvcd12** [comment]
Try this:

Preferences

General

    Enable:  Always on Top

    Disable:  Close When Unfocused

Layout

    Layout and Transparency

        adjust transparency levels

**Comment by iamqiz** [comment]
> ```
> Disable:  Close When Unfocused
> ```
@Kvcd12 
wow, it work! just disable "Close When Unfocused" then third-party tool can make it always on top when needed,     
it is so kind of you ! thank you very much! ❤😘
