### ISSUE TITLE
There is no project file

### ISSUE THREAD

**Issue by SacredTravis** [hluk/CopyQ#2218]
I downloaded the source code to challenge myself but there is no .sln to open the project in visual studio. Maybe the project got created in another software but where is the file that I can open all the project from?

**Comment by fade2gray** [comment]
Here's a starting point https://github.com/hluk/CopyQ#readme

**Comment by hluk** [comment]
I don't use Visual Studio. If the IDE supports it, try to import `CMakeLists.txt` file.
