### ISSUE TITLE
[Sway] copyq going into a copy paste loop and freezing my DE

### ISSUE THREAD

**Issue by ToxicMushroom** [hluk/CopyQ#2224]
**Describe the bug**
Copyq (I assume) goes rogue and spam transfers the image/text I was trying to paste.

**To Reproduce**
1. I can't :/ happens rarely but only when pasting.
sway logs: https://gist.github.com/ToxicMushroom/74795a600eca0b457560c30f7b6d56ff

**Expected behavior**
1. This should never occur

**Screenshots**
N/A

**Version, OS and Environment**
CopyQ Clipboard Manager 6.3.2
Qt: 5.15.6
KNotifications: 5.98.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Arch Linux
DE: Sway 1.8

**Additional context**
I previously discussed this with some sway users on the sway irc and had them look at the log, they told me to use a clipboard manager that supports wayland but to my understanding copyq does ? 
I am launching with: `QT_QPA_PLATFORM=xcb copyq`
The only other clipboard thing I have installed is `wl-clipboard` afaik

**Comment by hluk** [comment]
Does this happen when CopyQ owns the clipboard?

Does it happen only if you paste to a specific app?

I haven't seen this issue, but I'm still using Sway 1.7 (on Fedora 37).

**Comment by hluk** [comment]
Oh, if you use `QT_QPA_PLATFORM=xcb copyq` you effectively disable the Wayland support in which case the app runs in X11 mode and the clipboard is handled somehow by the XWayland integration.

Use `QT_QPA_PLATFORM=wayland copyq` to get proper Wayland support.
