### ISSUE TITLE
Duplicate clipboard items in synchronized tab

### ISSUE THREAD

**Issue by marlarius** [hluk/CopyQ#2228]
CopyQ has become my favorite clipboard manager after trying at least 10 different during the last few years. It's really cool :)

One thing I miss though is automation deduplication. The other clipboard managers don't add a new clip if it already exists, it only moves it to the top. CopyQ only ignores a clip if it is already at the top, but otherwise it is duplicated.

For example, if you copy "one", "two", "one" in sequence, the stack will show

one
two
one

Is there a setting I have missed?

If not, I would love to see it in a coming version :)

**Comment by hluk** [comment]
Item containing same data is not added again. But if, for example, new clipboard text is same as some item but the item contains additional data not in the clipboard (e.g. previous copy timestamp) it won't be replaced.

You may need a custom command to get rid of the duplicates. See: #1431

**Comment by marlarius** [comment]
I am bit confused.

If I add to the clipboard in sequence _one two one_, isn't the second _one_ the same data as the first?

**Comment by hluk** [comment]
You can check the other data formats by selecting an item and pressing F4. Sometimes the difference is only that there is an additional html format.

**Comment by marlarius** [comment]
There are no differences except for the auto generated attributes like the basename.

See below how it looks.
![image](https://user-images.githubusercontent.com/2758118/213153676-f277feb3-4ec1-456f-a172-30857577fbca.png)

**Comment by hluk** [comment]
Oh, OK then it is probably the "basename" internal format causing the problem.

**Comment by marlarius** [comment]
Thanks, it's fixed now :)
