### ISSUE TITLE
Quotes missinterpreted

### ISSUE THREAD

**Issue by FreeHarry** [hluk/CopyQ#2229]
I have the following script. It should open a file with its default app on Windows. For that I use the shell command `start`.

```
copyq:
var path = str(input())
var command = `start "${path}"`
var args = ["cmd", "/c", command]
execute.apply(this, args)
```
But I got the following message:

<img width="419" alt="2023-01-13_15-23-27--copyq" src="https://user-images.githubusercontent.com/24735031/212342752-4a3e5b1d-9817-4983-9b78-1f15c420b674.png">

The quotes for the path will have a backslash before it, what leads to the error for the shell command.
How can I format the string to have the quotes correctly given to the command?

Without quotes it works, but only for paths without spaces within. So I need the quotes.

**Version, OS and Environment**
 - 6.3.2
 - OS Windows 10

**Comment by hluk** [comment]
This seems to be problem with how `cmd` interprets the command.

For opening file paths (documents), try using "Open in Browser" predefined command (or basically just `copyq: open(input())`)

**Comment by FreeHarry** [comment]
> This seems to be problem with how `cmd` interprets the command.
> 
> For opening file paths (documents), try using "Open in Browser" predefined command (or basically just `copyq: open(input())`)

The open in browser command works. Thanks.

But I think because of the original problem, it comes not from how `cmd` interprets the command. Because the backslash is inserted mistakenly within `copyq` and given directly to the cmd command.

**Comment by hluk** [comment]
> But I think because of the original problem, it comes not from how `cmd` interprets the command. Because the backslash is inserted mistakenly within `copyq` and given directly to the cmd command.

I checked with a different command and there are no backslashes.
