### ISSUE TITLE
make appimage format

### ISSUE THREAD

**Issue by newyorkthink** [hluk/CopyQ#2231]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hluk** [comment]
I'm probably not going to do that again unless there is a good reason. I tried to create AppImage for CopyQ sometime ago but did not manage to do that. Flatpak was much simpler to set up.

**Comment by hluk** [comment]
AppImage is now available! A development build is here: https://github.com/hluk/CopyQ/actions/runs/24497165958#artifacts
