### ISSUE TITLE
Ditto-like open-and-paste shortcut

### ISSUE THREAD

**Issue by Young-Lord** [hluk/CopyQ#2232]
**Is your feature request related to a problem? Please describe.**
On [Ditto](https://ditto-cp.sourceforge.io/), there is a great shortcut: Hold `Ctrl` and press `` ` ``, the behavior is:
First time: open main page where you can release `Ctrl` and stay here, or press `Enter` to input the first clip (same as CopyQ)
Second time: next clip will be selected. **Release `Ctrl` and the 2nd clip will be pasted**
Third time: same as *Second Time*

**Describe the solution you'd like**
Create a setting to customize the behavior.

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by hluk** [comment]
This feature can be added using [Cycle Items](https://github.com/hluk/copyq-commands/tree/master/Global#cycle-items) (see [README.md](https://github.com/hluk/copyq-commands/blob/master/README.md) for details on how to add the command).
