### ISSUE TITLE
[Wayland] Failed to send all clipoard data to XWayland window

### ISSUE THREAD

**Issue by ToxicMushroom** [hluk/CopyQ#2233]
**Describe the bug**
When trying to paste large images, copyq shows a warning after pasting the first `65536` (2^16) bytes

**To Reproduce**
1. Copy an image larger than +- 66KB
2. Double click the copyq entry to select the entry for pasting
3. Try to paste the image in a program that runs via XWayland (e.g. gimp)

**Expected behavior**
The full image is pasted like when copying straigh from source to the XWayland program.

**Screenshots**
Demonstration.
https://user-images.githubusercontent.com/32853531/212791020-7f8a2788-5937-4cab-98f2-9748a086e9fe.mp4

<details>

  <summary>copyq log</summary>
  
  ```c
  merlijn@arch ~ % copyq
  Warning: [qt.qpa.wayland] QtWarning: Wayland does not support QWindow::requestActivate()
  Warning: [default] QtWarning: Failed to send all clipobard data; sent 65536 bytes out of 1686475
  Warning: [qt.qpa.wayland] QtWarning: Wayland does not support QWindow::requestActivate()
  Warning: [default] QtWarning: Failed to send all clipobard data; sent 65536 bytes out of 1686475
  ```
</details>

<details>

  <summary>env</summary>
  
  ```ini
LOGNAME=merlijn
MAIL=/var/spool/mail/merlijn
MOTD_SHOWN=pam
MOZ_ENABLE_WAYLAND=1
OLDPWD=/home/merlijn/example
PAGER=less
PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-sdk/platform-tools:/home/merlijn/.dotnet/tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
PWD=/home/merlijn
QT_QPA_PLATFORM=wayland
SDL_VIDEODRIVER=wayland
SHELL=/bin/zsh
SHLVL=2
SWAYSOCK=/run/user/1000/sway-ipc.1000.586.sock
SYSTEMD_EXEC_PID=543
TERM=alacritty
USER=merlijn
WAYLAND_DISPLAY=wayland-1
WINDOWID=94412397509648
XCURSOR_SIZE=24
XDG_ACTIVATION_TOKEN=f57c22d4e2e4084ce93c3a7d5e0a162a
XDG_CURRENT_DESKTOP=sway
XDG_RUNTIME_DIR=/run/user/1000
XDG_SEAT=seat0
XDG_SESSION_CLASS=user
XDG_SESSION_DESKTOP=sway
XDG_SESSION_ID=1
XDG_SESSION_TYPE=wayland
XDG_VTNR=1
_=/usr/bin/env
_JAVA_AWT_WM_NONREPARENTING=1
LC_MESSAGES=
  ```
</details>

**Version, OS and Environment**
 - CopyQ Clipboard Manager 6.3.2
 - Qt: 5.15.6
 - KNotifications: 5.98.0
 - Compiler: GCC
 - Arch: x86_64-little_endian-lp64
 - OS: Arch Linux
 - OS [e.g. Windows]
 - DE: sway version 1.8

**Additional context**
This issue does not occur when using QT_QPA_PLATFORM=xbc or when pasting into wayland native programs. 
I tried an online image editor on ungoogled-chromium under XWayland and native to deduce the above.
However due to #2224 using this workaround under wayland is undesirable.

**Comment by hluk** [comment]
Similar problem with Krita. Seem that it could be a problem with XWayland integration. Not sure if I can fix that in CopyQ.

**Comment by hluk** [comment]
All works if I pass the image data to `wl-copy` instead:

```
copyq clipboard image/png | wl-copy --type image/png
```

There is some problem passing the data via pipe (it gets interrupted after 64k is written - buffer size?): https://github.com/hluk/CopyQ/blob/d6c4582ad427cd93651e5acf307e7e8a3932606e/src/platform/x11/systemclipboard/waylandclipboard.cpp#L86

**Comment by hluk** [comment]
I checked the how wl-copy implements sending the data and it seems CopyQ is missing `fcntl(fd, F_SETFL, 0)` for the pipe.
