### ISSUE TITLE
I tell you, why make appimage format

### ISSUE THREAD

**Issue by newyorkthink** [hluk/CopyQ#2235]
first Flatpak is big, it was only download environment, and more package.

two, apt-get and rpm , it was use network

but, appimage file fomat or binary , it can copyq run every.

i share my appimage and binary file, you look , more awesome tool , they have appimage format.

![image](https://user-images.githubusercontent.com/87791643/213330610-96c6a040-6c80-4ddf-998a-df69814946a3.png)

![image](https://user-images.githubusercontent.com/87791643/213330641-08e194c8-9e20-4729-8f40-12031e5eb9a5.png)

**Comment by hluk** [comment]
Please don't open new issues and discuss this in #2231. I'm not planning to add support AppImage but patches are welcome if it won't make current release process more complex.

**Comment by hluk** [comment]
AppImage is now available! A development build is here: https://github.com/hluk/CopyQ/actions/runs/24497165958#artifacts
