### ISSUE TITLE
the 6.4.0 download gives a trojan positive on 360 total security

### ISSUE THREAD

**Issue by boyanmolina** [hluk/CopyQ#2239]
Type:
Win32/Trojan.Generic.HgIAS7AA

Scan Engine:
360 Cloud Scan Engine

File path:
C:\Users\Prensa\Desktop\copyq-6.4.0-setup.exe

File size:
13.87M (14,540,735 Bytes)

File version:
6.4.0               

File description:
CopyQ installer                                             

MD5:
f41ec9261f49be308e99aec439e50c29

Suggestion:
Quarantined files

**Comment by hluk** [comment]
This is most probably a false warning.

The build was grabbed as-is directly from AppVeyor (CI/CD service):
https://ci.appveyor.com/project/hluk/copyq/builds/45983508/artifacts

**Comment by boyanmolina** [comment]
Hi, Defender on Win 10 also gives a warning.

**Comment by hluk** [comment]
Is there anyway to handle these issues? I have no idea what I can do about these reports unless any of them are not false positives - in which case it would be a big problem and it would mean that there was some bad library or tool in CI/CD.

BTW, I got no warnings when uploading the binaries to FossHub. For example (https://virusscan.jotti.org/en-US/filescanjob/zd4vrp6669):

```
(1) Avast! Antivirus 	Clean
(2) BitDefender Antivirus 	Clean
(3) ClamAV 	Clean
(4) Cyren 	Clean
(5) Dr. Web 	Clean
(6) MicroWorld eScan 	Clean
(7) Fortinet 	Clean
(8) F-Secure Anti-Virus 	Clean
(9) G DATA 	Clean
(10) Ikarus 	Clean
(11) K7 AV 	Clean
(12) Kaspersky Anti-Virus 	Clean
(13) Sophos 	Clean
(14) Trend Micro Antivirus 	Clean
(15) VBA32 	Clean
```
