### ISSUE TITLE
CopyQ window size is forced to minimize. (Linux, version 6.3 or later)

### ISSUE THREAD

**Issue by presire** [hluk/CopyQ#2247]
**Describe the bug**
CopyQ (version 6.3 or later) window size is forced to minimize.
Prior to version 6.2, I have never had this problem.

**To Reproduce**
1. Go to the menu bar [File] -> [Preferences...] -> [Shortcuts] -> [Show main window under mouse cursor] and assign some shortcut.  (Ex.  my own setting [Ctrl] + [Shift] + [Down arrow])
2. Press the assigned shortcut to display CopyQ.
3. One out of every few times, the CopyQ window size is minimized.

**CopyQ Version**
6.3 or later.

**My PC environment**
* SUSE Linux Enterprise 15 SP4, and openSUSE Leap 15.4
* KDE Plasma
    5.24.4
* KDE Frameworks
    5.90.0
* Qt version
    5.15.2
* Linux Kernel
    5.14.21
* Graphics Platform
    X11
* GPU
    Radeon RX550  (The GPU driver uses the open source amdgpu)

**note**
This problem occurs both when installing from an rpm file and when building and installing from source code.

**Expected behavior**
When pressing a shortcut key to display the CopyQ screen,
the screen should display normally without being forced to minimize.

**Screenshots**
Shortcut Assignment Settings.
![ksnip_20230128-011140](https://user-images.githubusercontent.com/82971634/215142672-3c864ca6-b298-4fa5-b0d1-0ddc733abdd1.png)

As shown in the image below, One out of every few times, CopyQ window size is forcibly minimized.
![ksnip_20230128-011159](https://user-images.githubusercontent.com/82971634/215143114-ffc6a170-afd9-442f-b72a-70075c3b31d6.png)

**Comment by hluk** [comment]
I don't see any changes in app code since 6.2.0 that could have affected this. Maybe it is caused by some changes in Qt framework or window manager.

**Comment by hluk** [comment]
The **debug logs** should have more information about window geometry if you start the app with `env COPYQ_LOG_LEVEL=DEBUG copyq`.

**Comment by presire** [comment]
Thanks for the reply.

I ran the `env COPYQ_LOG_LEVEL=DEBUG copyq` command,
and then started CopyQ again to see if the screen size would be minimized.  
<br>

The log at that time is shown below.
In this log, there is a section that outputs "`DEBUG: Geometry: Window "MainWindow": Resize window: 50x50`".
This was output when the CopyQ screen was minimized.

```
DEBUG: Server "/home/suse/.config/copyq/.copyq_s" started.
DEBUG: Geometry: Window "MainWindow": Restore geometry "Options/MainWindow_geometry": 645x421,0,0 -> 1481x922,1087,289
DEBUG: Focus window is " ./copyq.sh  ~/I/C/bin — Konsole"
DEBUG: Loading configuration
DEBUG: Configuration loaded
DEBUG: Starting monitor
DEBUG: Executing: copyq --clipboard-access monitorClipboard
DEBUG: Starting callback: onStart
DEBUG: Executing: copyq onStart
DEBUG: Tab "Clipboard(&C)": Loading items from: /home/suse/.config/copyq/copyq_tab_44Kv44Oq44OD44OX44Oc44O844OJKCZDKSAoMSk=.dat
DEBUG: Tab "Clipboard(&C)": 184 items loaded from: /home/suse/.config/copyq/copyq_tab_44Kv44Oq44OD44OX44Oc44O844OJKCZDKSAoMSk=.dat
DEBUG: Executing: copyq eval -- runMenuCommandFilters()
DEBUG: Executing: Command "Show main window under mouse cursor"
DEBUG: Geometry: Window "MainWindow": Geometry blocked until hidden: 1
DEBUG: Geometry: Window "MainWindow": Move window: 2358, 0
DEBUG: Focus window is "~ : fish — Yakuake"
DEBUG: Raising window "CopyQ"
DEBUG: Executing: Command "Show main window under mouse cursor"
DEBUG: Geometry: Window "MainWindow": Geometry blocked until hidden: 1
DEBUG: Geometry: Window "MainWindow": Move to current workspace
DEBUG: Geometry: Window "MainWindow": Geometry blocked until hidden: 0
DEBUG: Geometry: Window "MainWindow": Geometry blocked until hidden: 1
DEBUG: Raising window "CopyQ"
DEBUG: Executing: Command "Show main window under mouse cursor"
DEBUG: Geometry: Window "MainWindow": Geometry blocked until hidden: 1
DEBUG: Geometry: Window "MainWindow": Resize window: 50x50
DEBUG: Geometry: Window "MainWindow": Move to current workspace
DEBUG: Geometry: Window "MainWindow": Geometry blocked until hidden: 0
DEBUG: Geometry: Window "MainWindow": Geometry blocked until hidden: 1
DEBUG: Raising window "CopyQ"
DEBUG: Saving items on application state change (2)
DEBUG: Focus window is " ./copyq.sh  ~/I/C/bin — Konsole"
DEBUG: Auto-hiding unfocused main window
DEBUG: Geometry: Window "MainWindow": Geometry blocked until hidden: 0
DEBUG: Focus window is " ./copyq.sh  ~/I/C/bin — Konsole"
DEBUG: Focus window is " ./copyq.sh  ~/I/C/bin — Konsole"
DEBUG: Focus window is " ./copyq.sh  ~/I/C/bin — Konsole"
DEBUG: Raising window "CopyQ"
DEBUG: Focus window is "Exit? — CopyQ": [QMessageBox] Exit?
DEBUG: Focus window is "Exit? — CopyQ": [QMessageBox] Exit?
DEBUG: Closing server.
DEBUG: Starting callback: onExit
DEBUG: Executing: copyq onExit
DEBUG: Waiting for callback to finish
DEBUG: Callback finished
DEBUG: Monitor finished
```
<br>

I also checked the operation with the default settings after installing openSUSE Leap 15.4,
and the CopyQ screen is still minimized.  
The PC used at this time is an Intel UHD Graphics 620 (iGPU).  (This may not be relevant...)  
<br>

For now, in my environment,  
I can successfully display the CopyQ screen without minimizing it by setting the `window rule` as shown in the image below.  
![ksnip_20230129-222955](https://user-images.githubusercontent.com/82971634/215339208-c30641dd-5461-4fc7-abec-ef38ecf95fe8.png)

**Comment by hluk** [comment]
It looks like a bug in Qt or window manager (or perhaps a problem with the window decorations/theme) because it seems that [frame geometry](https://doc.qt.io/qt-5/qwidget.html#frameGeometry-prop) returns a very small size.

Possible fix in #2248.

**Comment by hluk** [comment]
@presire Any chance you can build and test the fix in #2248?

**Comment by presire** [comment]
Sorry for the delay in responding to you.
<br>
Now, I have built & installed [#2248](https://github.com/hluk/CopyQ/pull/2248),  
and verified that it works and that the CopyQ screen displays properly without minimizing.  

Thank you for the quick response.  
<br>

Just to be sure, I have pasted the log below when it is working properly.  
command: `env COPYQ_LOG_LEVEL=DEBUG copyq`  
<br>

```
DEBUG: Server "/home/suse/.config/copyq/.copyq_s" started.
DEBUG: Geometry: Window "MainWindow": Restore geometry "Options/MainWindow_geometry": 645x421,0,0 -> 1492x953,1532,586
DEBUG: Focus window is " env COPYQ_LOG_LEVEL ~/I/C/bin — Konsole"
DEBUG: Loading configuration
DEBUG: Configuration loaded
DEBUG: Starting monitor
DEBUG: Executing: copyq --clipboard-access monitorClipboard
DEBUG: Starting callback: onStart
DEBUG: Executing: copyq onStart
DEBUG: Tab "Clipboard(&C)": Loading items from: /home/suse/.config/copyq/copyq_tab_44Kv44Oq44OD44OX44Oc44O844OJKCZDKSAoMSk=.dat
DEBUG: Tab "Clipboard(&C)": 198 items loaded from: /home/suse/.config/copyq/copyq_tab_44Kv44Oq44OD44OX44Oc44O844OJKCZDKSAoMSk=.dat
DEBUG: Executing: copyq eval -- runMenuCommandFilters()
DEBUG: Executing: Command "Show main window under mouse cursor"
DEBUG: Geometry: Window "MainWindow": Geometry blocked until hidden: 1
DEBUG: Geometry: Window "MainWindow": Move window: 2347, 963
DEBUG: Focus window is " env COPYQ_LOG_LEVEL ~/I/C/bin — Konsole"
DEBUG: Raising window "CopyQ"
DEBUG: Executing: Command "Show main window under mouse cursor"
DEBUG: Geometry: Window "MainWindow": Geometry blocked until hidden: 1
DEBUG: Geometry: Window "MainWindow": Move to current workspace
DEBUG: Geometry: Window "MainWindow": Geometry blocked until hidden: 0
DEBUG: Geometry: Window "MainWindow": Geometry blocked until hidden: 1
DEBUG: Raising window "CopyQ"
DEBUG: Executing: Command "Show main window under mouse cursor"
DEBUG: Geometry: Window "MainWindow": Geometry blocked until hidden: 1
DEBUG: Geometry: Window "MainWindow": Move to current workspace
DEBUG: Geometry: Window "MainWindow": Geometry blocked until hidden: 0
DEBUG: Geometry: Window "MainWindow": Geometry blocked until hidden: 1
DEBUG: Raising window "CopyQ"
DEBUG: Executing: Command "Show main window under mouse cursor"
DEBUG: Geometry: Window "MainWindow": Geometry blocked until hidden: 1
DEBUG: Geometry: Window "MainWindow": Move to current workspace
DEBUG: Geometry: Window "MainWindow": Geometry blocked until hidden: 0
DEBUG: Geometry: Window "MainWindow": Geometry blocked until hidden: 1
DEBUG: Raising window "CopyQ"
DEBUG: Executing: Command "Show main window under mouse cursor"
DEBUG: Geometry: Window "MainWindow": Geometry blocked until hidden: 1
DEBUG: Geometry: Window "MainWindow": Move to current workspace
DEBUG: Geometry: Window "MainWindow": Geometry blocked until hidden: 0
DEBUG: Geometry: Window "MainWindow": Geometry blocked until hidden: 1
DEBUG: Raising window "CopyQ"
DEBUG: Saving items on application state change (2)
DEBUG: Focus window is " env COPYQ_LOG_LEVEL ~/I/C/bin — Konsole"
DEBUG: Auto-hiding unfocused main window
DEBUG: Geometry: Window "MainWindow": Geometry blocked until hidden: 0
DEBUG: Focus window is " env COPYQ_LOG_LEVEL ~/I/C/bin — Konsole"
^CDEBUG: Terminating application on signal.
DEBUG: Closing server.
DEBUG: Starting callback: onExit
DEBUG: Executing: copyq onExit
DEBUG: Waiting for callback to finish
DEBUG: Callback finished
DEBUG: Monitor finished
```

**Comment by hluk** [comment]
Thanks for testing. The fix will be available in the next release.
