### ISSUE TITLE
Starting CopyQ on start of X without main window launching

### ISSUE THREAD

**Issue by orschiro** [hluk/CopyQ#225]
Hi there,

I have the following line in my `~/.xinitrc`:

```
copyq &
```

The man page states that running copyq without any parameter will launch it as a background process. However, I experience that copyq does open the main window when starting X.

How can I run copyq without having the main window being launched?

Thanks!

**Comment by hluk** [comment]
I'm closing this for now. If you still have this issue please reopen and provide details.

**Comment by sabhisharma-ise** [comment]
Solved the Issue!
(Distro In-use: Linux Mint)

Go to Startup Applications
Select CopyQ and open Edit
Change the command from:
```
copyq --start-server show 
```
to
```
copyq --start-server
```
Works like a Charm!

**Comment by kosail** [comment]
If someone ever comes across this post looking for a solution of starting copyq as a daemon (AKA background service), this might help you.

I run this command in the autostart script of a tiling window manager, but it should work in any environment.
`pgrep copyq || copyq --start-server && copyq hide`

(Sorry for the verbose++ comment, but I just wanna make sure people will be able to find this post easily on web search with words like "copyq daemon" or "tiling window manager")

**Comment by Top-g-hash** [comment]
@kosail  that lit !! worked for me save a hours !!

**Comment by KobeW50** [comment]
> If someone ever comes across this post looking for a solution of starting copyq as a daemon (AKA background service), this might help you.
> 
> I run this command in the autostart script of a tiling window manager, but it should work in any environment. `pgrep copyq || copyq --start-server && copyq hide`

Thank you for this. I had the same issue as this issue's author. BTW you can shorten it a bit by doing 
`pgrep copyq || copyq --start-server hide`

**Comment by j0n4t** [comment]
Workaround for Windows: Use `"C:\Program Files\CopyQ\copyq.exe" --start-server hide` on the target field on startup shortcut properties.

**Comment by aaxper** [comment]
My friend and I have both been having this issue with Niri. Starting it with `copyq --start-server hide` doesn't quite work because the window still briefly opens, meaning the screen flashes every time the server is started (usually when our devices are started).

**Comment by KobeW50** [comment]
@Aaxper Try running `copyq config hide_main_window true`

**Comment by aaxper** [comment]
> [@Aaxper](https://github.com/Aaxper) Try running `copyq config hide_main_window true`

I did. That didn't fix the issue.
