### ISSUE TITLE
UI/UX critiques of Clipboard Storing feature

### ISSUE THREAD

**Issue by redactedscribe** [hluk/CopyQ#2255]
**Describe the bug**
- Clipboard Storing's file/tray context menu option does not show an icon to the left of it after launching CopyQ.
![copyq_no-icon](https://user-images.githubusercontent.com/25013746/216830701-d66580b8-948b-4ec8-bb56-aa27014a7129.png)
- After disabling Clipboard Storing, it confusingly looks like Clipboard Storing is actually _enabled_ due to the tick next to the label.
![copyq_tick-icon](https://user-images.githubusercontent.com/25013746/216830766-fd833044-b2af-4bfa-9b6e-376624f690a0.png)
- After enabling Clipboard Storing, the icon and label combination is less confusing.
![copyq_no-entry-icon](https://user-images.githubusercontent.com/25013746/216830843-8196cd5e-52f4-4771-85b0-2b677c19a00f.png)

**Expected behavior**
Perhaps the Clipboard Storing context menu option should have a static icon? One that represents logging, storage, or monitoring? That way one does not look to a dynamic icon to verify the feature's state, but rather only to locate it in the context menu, and instead rely upon the label's wording to understand state.

Alternatively, a static text of "Enable Clipboard Storing" and _only_ the icon changes between the tick and no-entry (circle-diagonal). This however is probably less obvious as to what the menu entry option will do since the wording always reads "Enable..." and I don't think there's a precedent set in the UI that context CopyQ menu icons reflect state, other than this one menu entry.

**Version, OS and Environment**
- CopyQ 6.4.0
- Windows 11 Pro 10.0.22621

**Comment by hluk** [comment]
> Clipboard Storing's file/tray context menu option does not show an icon to the left of it after launching CopyQ.

That is a definitely a bug.

It would be perhaps easier to fix it with the static icon and static text "Toggle Clipboard Storing".
