### ISSUE TITLE
Images suddenly missing from list.

### ISSUE THREAD

**Issue by Stoner27x** [hluk/CopyQ#2259]
Hi, I'm new to this hub.  I have been using Copy Q successfully for ages. This issue just happened without my intervention. I have read Q&A, been through settings and made sure HTML is ticked.

How do I get images back please?

**Comment by hluk** [comment]
CopyQ won't fetch any remote images or data when showing HTML (and at any other point) - unless you use very old app version in which case it is best to update anyway.

Check if an image item contains an `image/*` format by selecting the item and pressing F4.

Also verify that Images plugin appears before Text plugin in Preferences:

![image](https://user-images.githubusercontent.com/38054/218524368-0c287c73-3cd7-4abd-b9f5-0d808b024237.png)

**Comment by Stoner27x** [comment]
Thanks for responding Lukas.

 

As I said – I have always had images in the list and found this a very good feature.

 

This is what my preferences tab looks like:

  

 

F4 inserts an image (if present) into any active page.

 

Is there any way to get my images back in the list please?

 

Thanks

 

Andrew

**Comment by hluk** [comment]
> This is what my preferences tab looks like:

I cannot see the image. Can you post it in comments on GitHub (instead of via mail)?

> F4 inserts an image (if present) into any active page.

F4 shortcut by default shows data and formats for currently selected item. If it does not work, select "Show Content..." from "Item" menu in menu bar (or context menu).

**Comment by Stoner27x** [comment]
Thanks for responding Lukas.

As I said – I have always had images in the list and found this a very good feature.

This is what my preferences tab looks like:
  
![image](https://user-images.githubusercontent.com/125040467/218977384-1f8ef09e-982f-4020-a39b-d3837db0d5e9.png)


F4 inserts an image (if present) into any active page.

Is there any way to get my images back in the list please?

Thanks

Andrew

**Comment by Stoner27x** [comment]
This is what my list looks like:
![image](https://user-images.githubusercontent.com/125040467/218978586-118134ea-77ac-431e-b7ad-61d99ba32c3d.png)
The thumbnails are so small I cannot identify an image

**Comment by Stoner27x** [comment]
I've got it now, I need to use the down arrow and scroll down thw list then an image pops up ate the bottom of the CQ window if theres room for it.
![image](https://user-images.githubusercontent.com/125040467/218979986-8c6b5a9b-a5e8-4c3f-9fb6-4c5f2a5c3c7f.png)

**Comment by hluk** [comment]
If you want to see bigger images in the list, disable "Show simple items" in preferences:

![image](https://user-images.githubusercontent.com/38054/219935352-87edd90c-31a9-4cec-b15a-9021e49aa4a1.png)

**Comment by Stoner27x** [comment]
Hi Lukas

 

Thanks for that.

 

I can’t reply on GitHub because you’ve closed the thread.

 

I did as instructed and now have images but have lost all but 7 of my entries/list.

 

Please advise

 

Andrew

**Comment by hluk** [comment]
> I can’t reply on GitHub because you’ve closed the thread.

Sorry, this is strange, I was not aware of this. Reopening.

> I did as instructed and now have images but have lost all but 7 of my entries/list.

What exactly do you mean by "lost"? Are there only 7 items in the list now (no other even empty item)?

What is the value of "Maximum number of items in history" in History config tab?

**Comment by Stoner27x** [comment]
Its OK now. Thanks

**Comment by Stoner27x** [comment]
Hi Lukas

 

I tried the edit function to change an entry in the list but cannot get back to the list

If I close this window it comes straight back when I hit the tray icon.

 

Please advise

 

Andrew
