### ISSUE TITLE
bug when copy webm in 6.4.0, but 3.9.0 have not this bug

### ISSUE THREAD

**Issue by kasumiru** [hluk/CopyQ#2264]
Before creating a new issue, see list of [known
issues](https://copyq.readthedocs.io/en/latest/known-issues.html).

**Describe the bug**

**To Reproduce**
1. Go to google, or any another site
2. right click on picture, webm
3. click - "copy"
4. in "show\hide main window" see only empty white square:
![image](https://user-images.githubusercontent.com/25246740/218333124-ec6be9ae-3eb7-4d38-a0c6-dbbf7ccc1905.png)

current latest verstion: 6.4.0, with clear cache, all config files removed for test this reproduce.
Old version 3.9.0 perfectly copied webm photos, this is the saddest. 
I can write mp4 fot STR.

**Comment by hluk** [comment]
Can you check that your installation has `imageformats/qwebp.dll`?

Also verify that the Image plugin is installed, enabled and shows at the top of the list in Items config tab:

![image](https://user-images.githubusercontent.com/38054/219948435-70317045-2233-4535-98dd-5f3e603f09e6.png)

**Comment by hluk** [comment]
BTW, CopyQ by default do not store webp formats (it would need to be enabled by a command).

Can you check if the image item contains the right image format (select the item and press F4)?

**Comment by kasumiru** [comment]
Oh, thanks @hluk for answer! Yes, ofcourse plugin "Images" installed and in top of plugins. File "qwebp.dll" exist. (screenshot). 

> BTW, CopyQ by default do not store webp formats (it would need to be enabled by a command)._

Сopyq version 3.9.0 perfect copying webm withot any issues. but 6.4.0 corrupt buffering webm pictures with any plugin configuring. in cleared installing.

> Can you check if the image item contains the right image format (select the item and press F4)?

In final screenshot i opened F4. All photo - webm, copied from google images.


![image](https://user-images.githubusercontent.com/25246740/221430311-bcb6c054-7f6c-45a0-8ce5-9888c786a110.png)
![image](https://user-images.githubusercontent.com/25246740/221430398-50e5693c-feee-49d1-bfa5-922dc157100d.png)
![image](https://user-images.githubusercontent.com/25246740/221431010-784ae831-86fe-4fc7-aec5-a60869707a80.png)

**Comment by kasumiru** [comment]
Ok. Should I stay on the old version, then all will working?

**Comment by kasumiru** [comment]
This is not internet webm. Its slack images. Please fix this. old copyq normally working with copy images, havent this bug. 
Step To Reproduce: just copy image from Slack! 

![image](https://user-images.githubusercontent.com/25246740/223406414-cbad4d34-6ff0-4aa1-baa0-89f7e52b915f.png)
![image](https://user-images.githubusercontent.com/25246740/223406419-d171c7b1-c374-4815-9b18-13e870bac729.png)

**Comment by hluk** [comment]
I won't be adding advanced HTML rendering to the app - specifically no remote file fetching.

If the source application only provides HTML instead of binary image data, CopyQ won't be able to view it.

Can you also check the clipboard content after copying the image (it is Ctrl+Shift+C from CopyQ main window)?

**Comment by kasumiru** [comment]
I'm uninstall CopyQ 6.4.0, install 3.9.0 and now everything is fine with webm.
 
upd: another trouble in 6.4.0: then copyin picture from telegram desktop (windows 10) and copying text agter then - picture was dropped from copyq. olv version 3.9.0 does not contain this bug. If you want, I can write wideo with all these bugs.
