### ISSUE TITLE
Simple alphabetical sorting in the Edit menu does not work in version 6.4.0 

### ISSUE THREAD

**Issue by nbb1967** [hluk/CopyQ#2267]
In version 6.4.0 the simple alphabetical sorting in the Edit menu (Ctrl+Shift+S) no longer works.
It worked in version 6.3.2

Tested on Windows 10 Pro and Ubuntu 22.04.2 LTS
(New OS installation on VirtualBox + CopyQ)

**Comment by hluk** [comment]
Oops, broken in 2617745f ("Allow using custom sort functions").

Fix with proper tests is in #2269.

Thanks for the report!
