### ISSUE TITLE
Only use command if contents does NOT match regex

### ISSUE THREAD

**Issue by marlarius** [hluk/CopyQ#2273]
The Content field on the Advanced tab is useful for only showing commands that make sense for the given item. Such as only offering to open an url if the contents is actually a web address.

Sometimes the opposite action is needed: That is, only show/use the command if the regex does not match.

An ideal solution would be either having a checkbox to negate the regex or to prefix the regex with eg. an exclamation mark.

However, I think it should be possible with the Filter option, but how?

**Comment by hluk** [comment]
> However, I think it should be possible with the Filter option, but how?

You are right. The value of **Filter** field could be something like:

```js
copyq: if (!/some/.test(str(input()))) fail()
```

**Comment by marlarius** [comment]
It works :)
