### ISSUE TITLE
Script works with Libre office and Word but not with Google docs

### ISSUE THREAD

**Issue by bitdom8** [hluk/CopyQ#2278]
Before creating a new issue, see list of [known
issues](https://copyq.readthedocs.io/en/latest/known-issues.html).

**Describe the bug**

**To Reproduce**
`copyq:
var time = dateString('yyyy-MM-dd hh:mm:ss')
//var texthere = '<a href="###">###' + str(clipboard()).replace("SASA", "hehe") +  '###</a>'
var style = " "
var texthere = '<a href=\"###\">###</a>'
var href ='<html><head><style>span{'
            + style +
            '}</style></head>'
            + texthere +
            '</html>';

copy(mimeText, href, 'text/html', href)
paste()`

**Expected behavior**
HTML output should be enabled.

**Screenshots**
Easily obtainable.

Script should work with google docs but not works

**Comment by bitdom8** [comment]
Ok needed to add https for Gdocs to recognize it as link

 copyq:
var time = dateString('yyyy-MM-dd hh:mm:ss')
//var texthere = '<a href="###">###' + str(clipboard()).replace("SASA", "hehe") +  '###</a>'
var style = " "
var texthere = `<a href=\"https://bitfinicon.com/symbols/` + str(clipboard()) + `\">` + str(clipboard()) + `</a>`
var href ='<html><head><style>span{'
            + style +
            '}</style></head>'
            + texthere +
            '</html>';


copy(mimeText, href, 'text/html', href)
paste()

**Comment by hluk** [comment]
I assume this was resolved. Closing.
