### ISSUE TITLE
tabs ?

### ISSUE THREAD

**Issue by drocsid** [hluk/CopyQ#228]
Hi,

I've been using copyq for 6 months or so. But I've never had the tabs work, or at least I do not understand how they work. Can the tabs toggle to be the active clipboard? For example if I create a tab named jobs, and I select it, will it become the active clipboard, or share with the clipboard (all incomming clipboard entries enter both the clipboard and jobs tab?). Can I easily move clipboard items history from the clipboard across the tabs? With a keyboard shortcut? In my experience using copy q, all I can do is create new items, or paste the active item into the tab. Tabs seem really neutered. Is this a bug, or by design? Maybe I need to fork this thing to get it to behave the way I think it should. Or maybe it's my desktop / distro. I used the archlinux package to install at first, but have just built the most recent version from git and it seems about the same. I am using a tiling wm. - i3

discord@coffee ~/c/b/CopyQ> cmake .
-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - not found
-- Found Qt4: /usr/bin/qmake-qt4 (found version "4.8.6") 
-- Building with Qt 4.
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib64/libX11.so
-- Building for X11 window system.
-- Building with ItemWeb plugin.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/discord/code/build/CopyQ

**Comment by hluk** [comment]
This should be possible to implement using commands now.
