### ISSUE TITLE
Ignore by format does not work for format name "Clipboard Viewer Ignore"

### ISSUE THREAD

**Issue by nbb1967** [hluk/CopyQ#2282]
**Describe the bug**
Ignore by format does not work for format name "Clipboard Viewer Ignore"

**To Reproduce**
I create a command to ignore the clipboard if a format with a specified name is detected on the clipboard (format-flag with instructions for clipboard managers).
 
Command: copyq ignore
Format: format name
Type: Automatic.

**Expected behavior**
If a format with a specified name is found on the clipboard, the clipboard will be ignored.

**Real behavior**
This works fine with Microsoft formats:
"CanIncludeInClipboardHistory"
"CanUploadToCloudClipboard"
"ExcludeClipboardContentFromMonitorProcessing"
[formats description](https://learn.microsoft.com/en-us/windows/win32/dataxchg/clipboard-formats#cloud-clipboard-and-clipboard-history-formats)

But it doesn't work with the format from the ClipMate authors:
"Clipboard Viewer Ignore"
[format description, test tool](http://www.clipboardextender.com/developing-clipboard-aware-programs-for-windows/ignoring-clipboard-updates-with-the-cf_clipboard_viewer_ignore-clipboard-format)

I assumed the cause was spaces in the format name, but this is not confirmed. Ignoring "Rich Text Format" (also contains spaces) - works.

**Version, OS**
 - Application Version [6.4.0]
 - OS [Windows 10]

**Additional context**
These formats are used in Windows by some password managers (KeePass, KeePassXC, Sticky Password, 1Password, NordPass...) and some browsers in private mode (Edge, Firefox...).

**Comment by nbb1967** [comment]
Added: Problem occurs when format size of "Clipboard Viewer Ignore" is 0 bytes.

> Specification
> Format Name: "Clipboard Viewer Ignore".
>
> Clipboard Format Type: Private (must be registered by your program at startup)
>
> Contains: NULL Data.  Optinally, you can include text string up to 80 bytes, identifying originating program. Zero terminated.  But since nothing should ever look at it, you should be able to leave it null.
>

I've tested 3 programs that put "Clipboard Viewer Ignore" format to clipboard:
1. KeePass 2.53 - puts into format its name "KeePass" (format size 16 bytes)
2. Sticky Password 8.6.3.1363 - does not put anything into the format (format size 0 bytes)
3. Clipboard Viewer / Ignore Example 1.0.0 (demo utility from format authors) - does not put anything into format (format size 0 bytes)

CopyQ command (described above) ignores the clipboard from KeePass (as expected).
CopyQ command (described above) does not ignore clipboard from Sticky Password and Clipboard Viewer / Ignore Example

**Comment by hluk** [comment]
I assume that CopyQ does not see such format. You can list the formats in clipboard with Ctrl+Shift+C shortcut from main window.

**Comment by nbb1967** [comment]
![](https://i.imgur.com/dP0EK1B.png)

![](https://i.imgur.com/Ywk15PH.png)

![](https://i.imgur.com/T3sPsML.png)

**Comment by hluk** [comment]
Can you share the command? You must use the complete format name (including the `application/...`).

**Comment by nbb1967** [comment]
```
[Command]
Name=Ignore \"Clipboard Viewer Ignore\"
Command="
    copyq ignore
"
Input=Clipboard Viewer Ignore
Automatic=true
Icon=\xf15b
```
And your variant:
```
[Command]
Name=Ignore \"Clipboard Viewer Ignore\"
Command="
    copyq ignore
"
Input="application/x-qt-windows-mime;value=\"Clipboard Viewer Ignore\""
Automatic=true
Icon=\xf15b
```
Same result: Clipboard from KeePass is ignored. The clipboard from the other two programs - gets into the clipboard history.

**Comment by Chealer** [comment]
Thank you very much @nbb1967 and Lukas

> But it doesn't work with the format from the ClipMate authors:
> "Clipboard Viewer Ignore"
> format description, test tool

For what it's worth, the domain that link points to was hijacked. [The _Ignoring Clipboard Updates with the CF_CLIPBOARD_VIEWER_IGNORE Clipboard Format_ article](https://web.archive.org/web/20200720154713/http://www.clipboardextender.com/developing-clipboard-aware-programs-for-windows/ignoring-clipboard-updates-with-the-cf_clipboard_viewer_ignore-clipboard-format) can now be read from the Wayback machine.

<details>
  <summary>License</summary>
This comment and any other from myself on this ticket is offered under the terms of CC0 1.0.
</details>
