### ISSUE TITLE
Too many and duplicate tag icons on the menu bar

### ISSUE THREAD

**Issue by stardepp** [hluk/CopyQ#2285]
I am very happy with CopyQ, especially with the tabs. But on the menu bar the tag icons are displayed too often and double and triple. Even a complete reset of CopyQ did not change this error. How can I make the tag icons appear only once each?

https://imgur.com/munRxje

**Comment by hluk** [comment]
Can you update to the latest version? I remember this has been problem a long time ago.

After updating, check if there are no duplicate commands/actions in Command dialog (can be opened with F6 from the main window).
