### ISSUE TITLE
Data loss again

### ISSUE THREAD

**Issue by Hossam225** [hluk/CopyQ#2289]
The issue https://github.com/hluk/CopyQ/issues/1935 has occured again.
Fortunately this time I was having Ditto insatlled besides CopyQ, so my clipboard was saved properly in Ditto.
I remember that I faced two incidents within the last 10 days that may have caused in the data corruption with CopyQ:
* The first: The power was cut suddenly from the pc due to a hardware issue.
* The seconed: Windows was stuck (completely freezed) due to driver issue and I needed to force shutting it down as well.

[copyq.log](https://github.com/hluk/CopyQ/files/10898378/copyq.log)

ver 6.1.0

**Update**: I updated to the latest version and the problem shown fixed.

**Comment by barrelltitor** [comment]
I've had this issue in 2023, I still have this issue today. I lose all copyq data due to some .dat corruption I guess. The .dat file is there, but the clipboard shows empty

Are there no automated backups of the dat file? If items are saved on disk why can't they be loaded from disk?
