### ISSUE TITLE
Paste current date and time - with user defined formatting

### ISSUE THREAD

**Issue by francwalter** [hluk/CopyQ#2290]
Hi

I just began to use CopyQ (vs 6.4.0, from Github here) on Ubuntu, I am used to "ClipMate" on Windows (a very old application, not utf8-capable, but still very useful) or Copy'em Paste on MacOS (also very useful).

CopyQ has the great feature to copy current date and time with global keyboard shortcut, but not in a format I ever use.
I use normally date as this: YYYY-MM-DD, e.g. 2023-03-07, the ISO 8601 format, also known in Terminal as `date +%F`
When I need Date **with** time I write: YYYY-MM-DD_HH.mm.ss, e.g. 2023-03-07_10.35.00
But never I use something like: `Dienstag, 7. März 2023 10:39:38 CET` which CopyQ gives me.

I would love to see a feature to set my current date and time format in CopyQ.
A setting for "Date only" (without time) or better: two shortcuts, one for Date, one for Time, both individually formattable.

Maybe it is already possible, but I didnt find it in all settings :(

Thanks, frank

**Comment by Kvcd12** [comment]
See this overview on Commands:

[https://github.com/hluk/copyq-commands](url)

See this example:

[https://github.com/hluk/copyq-commands/blob/master/Global/paste-current-date-time.ini]

**Comment by francwalter** [comment]
Thank. I use autokey-gtk for shortcuts now, works good and reliable.
