### ISSUE TITLE
Linkify not working

### ISSUE THREAD

**Issue by Kmfernan5** [hluk/CopyQ#2293]
Before creating a new issue, see list of [known
issues](https://copyq.readthedocs.io/en/latest/known-issues.html).

**Describe the bug**
 Copy and paste, trying to use linkify. I get the following error in my logs. Nothing happens
.
**To Reproduce**
1. Go to Any website and then copy text then. And then paste using to linkify shortcut
 

**Expected behavior**
Linkify paste

**Screenshots**
![image](https://user-images.githubusercontent.com/98493596/223843692-e5496d19-003b-430f-bfc5-4d00ceed52ae.png)

 Warning [2023-03-08 12:14:22.641] <Server-20716>: [default] QtWarning: DirectWrite: CreateFontFaceFromHDC() failed (Indicates an error in an input file such as a font file.) for QFontDef(Family="Fixedsys", pointsize=8.25, pixelsize=15, styleHint=5, weight=50, stretch=100, hintingPreference=0) LOGFONT("Fixedsys", lfWidth=0, lfHeight=-15) dpi=192
Note [2023-03-08 12:15:16.631] <Client-42684>: Command "Synchronize Clipboard with Other Sessions": Finished in 3270 ms
Note [2023-03-08 12:16:49.078] <Client-18400>: Command "Synchronize Clipboard with Other Sessions": Finished in 3246 ms
Note [2023-03-08 12:17:50.347] <Client-67868>: Command "Synchronize Clipboard with Other Sessions": Finished in 3167 ms
Note [2023-03-08 12:19:39.858] <Client-81432>: Command "Synchronize Clipboard with Other Sessions": Finished in 3310 ms
Note [2023-03-08 12:19:44.992] <Client-63392>: Command "Synchronize Clipboard with Other Sessions": Finished in 3797 ms
Note [2023-03-08 12:20:25.356] <Client-45104>: Command "Synchronize Clipboard with Other Sessions": Finished in 3133 ms
Warning [2023-03-08 12:22:38.586] <Server-20716>: [default] QtWarning: DirectWrite: CreateFontFaceFromHDC() failed (Indicates an error in an input file such as a font file.) for QFontDef(Family="Fixedsys", pointsize=13.5, pixelsize=20, styleHint=5, weight=50, stretch=100, hintingPreference=0) LOGFONT("Fixedsys", lfWidth=0, lfHeight=-20) dpi=192
Warning [2023-03-08 12:22:42.181] <Server-20716>: [default] QtWarning: DirectWrite: CreateFontFaceFromHDC() failed (Indicates an error in an input file such as a font file.) for QFontDef(Family="Fixedsys", pointsize=13.5, pixelsize=20, styleHint=5, weight=50, stretch=100, hintingPreference=0) LOGFONT("Fixedsys", lfWidth=0, lfHeight=-20) dpi=192
Warning [2023-03-08 12:22:42.840] <Server-20716>: [default] QtWarning: DirectWrite: CreateFontFaceFromHDC() failed (Indicates an error in an input file such as a font file.) for QFontDef(Family="Fixedsys", pointsize=13.5, pixelsize=20, styleHint=5, weight=50, stretch=100, hintingPreference=0) LOGFONT("Fixedsys", lfWidth=0, lfHeight=-20) dpi=192
Note [2023-03-08 12:23:19.697] <Client-33388>: Command "Synchronize Clipboard with Other Sessions": Finished in 3143 ms
Warning [2023-03-08 12:24:23.196] <Server-20716>: [default] QtWarning: DirectWrite: CreateFontFaceFromHDC() failed (Indicates an error in an input file such as a font file.) for QFontDef(Family="Fixedsys", pointsize=13.5, pixelsize=20, styleHint=5, weight=50, stretch=100, hintingPreference=0) LOGFONT("Fixedsys", lfWidth=0, lfHeight=-20) dpi=192

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Application Version [e.g. 3.7.2] 6.32
 - OS [e.g. Windows] windows 11
 - Desktop environment, window manager (if applicable)
 - 

**Additional context**

Does this command work?

**Comment by hluk** [comment]
This is meant to be an Automatic command - i.e. works on clipboard when it changes. It won't work if triggered using a shortcut.

**Comment by bonnebulle** [comment]
And, it is a way to do it not automaticly ?
I would like to use the command some time.
Thanks

**Comment by hluk** [comment]
> And, it is a way to do it not automaticly ? I would like to use the command some time. Thanks

You can switch the command from "Automatic" to "In Menu" to trigger it from context menu (after right clicking on an item or with a custom shortcut):

```ini
[Command]
Command="
    copyq:
    const link = str(input());
    const href = `<a href=\"${link}\">${link}</a>`;
    setData('text/html', href);"
Icon=\xf127
InMenu=true
Input=text/plain
Match=^(https?|ftps?|file|mailto)://
Name=Linkify
```

**Comment by bonnebulle** [comment]
Thanks
The problem on URL detection was in the Regex
``^(https?|ftps?|file|mailto):\\/\\/``
I changed into
``^(https?|ftps?|file|mailto):\/\/``

And, in my working flow I prefer data replacement on copy/paste/change
My final command :

```copyq
[Command]
Command="
    copyq:
    var oldText = str(data('text/plain'));
    var linked = '<a href=\"'+oldText+'\">\"'+oldText+'\"</a>';
    setData(mimeText, linked);
    removeData(mimeHtml);
    copy(linked);"
Icon=\xf127
InMenu=true
Input=text/plain
Match=^(https?|ftps?|file|mailto):\/\/
Name=Linkify
```
