### ISSUE TITLE
No Buttons shown at Commands & Preferences @ 13,3" display, 150% size

### ISSUE THREAD

**Issue by greg4b** [hluk/CopyQ#2299]
**Describe the bug**
The dialog boxes for 
* Commands
* Preferences
is too big - the buttons for saving etc. in the bottom cannot be accessed.
Display 13,3", 150%scale, HD Resolution

**To Reproduce**
open Commands or Preferences dialog box.

**Expected behavior**
Buttons in the bottom can be viewed and used.

**Screenshots**
See screenshot

**Version, OS and Environment**
 - Application Version 6.3.2
 - OS Win10

![CopyQ FSDafo](https://user-images.githubusercontent.com/16733586/225419720-1dd5ef2f-5514-4e9c-b821-0f5f99c01453.png)
![grafik](https://user-images.githubusercontent.com/16733586/225419724-6db76bbb-d83b-4837-8e55-12267bf89f16.png)

**Comment by greg4b** [comment]
Furthermore when dragging screenshot from Images tab - a second image is inserted... Advise? Thanks

**Comment by hluk** [comment]
> Furthermore when dragging screenshot from Images tab - a second image is inserted... Advise? Thanks

This has been fixed in 7.0.0 (#2304).

I can look into the size problem. It seems that some widget has some large minimal size configured.

**Comment by greg4b** [comment]
Hello Lukas, 

works fine! See screenshot: 
![CopyQ ehPJEl](https://user-images.githubusercontent.com/16733586/232742263-8b246a80-de0a-4af8-b4ec-f42a60df842f.png)
![grafik](https://user-images.githubusercontent.com/16733586/232742271-c559b79e-ec21-4681-abc1-11124133034f.png)

Tried your development build 7.0.0-19-gfffaa3e1 on W10 (1920x1080) on 13,3" (HP 830G6)

**Comment by hluk** [comment]
Thanks for testing. I will include the fix in the next version.
