### ISSUE TITLE
Moving item on Windows not working

### ISSUE THREAD

**Issue by richboss** [hluk/CopyQ#2304]
**Describe the bug**
According to documentation, an item can be moved from one tab to another by dragging it with the mouse (without pressing any modifier key). This does not work correctly on Windows. On Windows the item gets copied to the destination tab, but it will not be removed from the source tab, hence effectively getting duplicated on the destination tab. On Linux, for comparison, it works as expected.

**To Reproduce**
1. Create an item with arbitrary content on any tab (e.g. the default "Clipboard" tab)
2. Create a second tab
3. Use the mouse to drag the item to the second tab
4. Observe that the item gets copied to the second tab, but at the same time remains on the first tab.

**Expected behavior**
The item should be moved, not copied.

**Version, OS and Environment**
CopyQ Clipboard Manager 6.4.0
Qt: 5.15.2
KNotifications: 5.92.0
Compiler: MSVC
Arch: x86_64-little_endian-llp64
OS: Windows 10 Version 2009

**Comment by hluk** [comment]
This is fixed in #1246, but not yet released.

**Comment by hluk** [comment]
I just released the fix in 7.0.0: https://github.com/hluk/CopyQ/releases/tag/v7.0.0
