### ISSUE TITLE
Sort and reverse for items stopped working

### ISSUE THREAD

**Issue by niksfirefly** [hluk/CopyQ#2309]
Sort and reverse for items stopped working.
When used from menu and also as a shortcut CTRL+SHIFT+R
There is no warnings in DEBUG LOG mode
I disabled scripts with "sort" and still no change.

```
copyq --version
CopyQ Clipboard Manager 6.4.0~focal
Qt: 5.12.8
KNotifications: 5.68.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Ubuntu 20.04.6 LTS
```

**Comment by hluk** [comment]
> Not yet released.

Just released in 7.0.0: https://github.com/hluk/CopyQ/releases/tag/v7.0.0
