### ISSUE TITLE
Commands editor display option will cause the command to be executed continuously

### ISSUE THREAD

**Issue by 7peanuts** [hluk/CopyQ#2311]
**Describe the bug**

Any command, with the display option turned on, will be automatically executed by clicking the mouse.

**To Reproduce**

https://user-images.githubusercontent.com/82173614/229367434-8529604b-cb0c-482e-beff-e83e4d7c1c72.mp4

**Screenshots**
![20230403001444](https://user-images.githubusercontent.com/82173614/229371451-821b2593-d12c-4e83-9a5b-d432882fb8a0.png)
![20230403001541](https://user-images.githubusercontent.com/82173614/229371453-90a1775a-c0d2-420d-8528-800238335b02.png)

**Version, OS, and Environment**
 - Application Version [7.0.0]
 - OS [Windows 11 22621.1485]

**Additional context**

These two screenshot commands are also unavailable.
https://github.com/hluk/copyq-commands/blob/master/Global/screenshot-cutout.ini
https://github.com/hluk/copyq-commands/blob/master/Global/screenshot.ini

**Comment by hluk** [comment]
Display commands are only meant to change item presentation. It is basically just a code that would transform the item data to a form that should be shown by the app (e.g. render markdown). The code should not do any extra actions like changing the stored item itself - this would trigger another round of rendering.

See the documentation: https://copyq.readthedocs.io/en/latest/commands-display.html

See examples: https://github.com/hluk/copyq-commands/tree/master/Display
