### ISSUE TITLE
Screenshot always black on Ubuntu 22.04

### ISSUE THREAD

**Issue by quentin-decre** [hluk/CopyQ#2312]
**Describe the bug**
When I trigger the screenshot shortcut, my screen goes black. I can still select a part of it, but I only get a black square in the copy history.
I did not have this issue before my update to Ubuntu 22

**To Reproduce**
1. Have Ubuntu 22
2. Press the screenshot keyboard shortcut

**Expected behavior**
I expect to have a screenshot of my screen, and being able to select the portion I want to copy

**Screenshots**
![2023-04-04_10-22](https://user-images.githubusercontent.com/1137511/229732491-0778e926-18cf-42d9-b61d-d703c06c30bf.png)

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Application Version : tested on 6.0.1 and 7.0.0
 - OS Ubuntu 22.04

**Comment by hluk** [comment]
Unfortunately, screenshots are not supported on Wayland, unless you use a specialized app for that.
