### ISSUE TITLE
Missing Korean in the installer

### ISSUE THREAD

**Issue by VenusGirl** [hluk/CopyQ#2313]
The copyq.iss contains Korean translation, but Korean is not displayed when installing it.

Isn't it because Korea.iss is missing?

https://github.com/jrsoftware/issrc/blob/main/Files/Languages/Unofficial/Korean.isl
Or 
[INNO Setup - Korean.zip](https://github.com/hluk/CopyQ/files/11150093/INNO.Setup.-.Korean.zip)

![copuq-insta](https://user-images.githubusercontent.com/53147200/229837128-650488c2-c00c-4d89-a053-d4356d25f103.png)

CopyQ 7.0.0
Windows 11 /10

**Comment by hluk** [comment]
Oh, looks like using `MessagesFile` in the config file does not mean the file will be included in installer, just where to find the file - that is pretty useless. :(

https://github.com/hluk/CopyQ/blob/befd8c4bcc7c7a96e007744a11483980fe7e9afd/shared/copyq.iss#L56

**Comment by VenusGirl** [comment]
Name: cz; MessagesFile: "compiler:Languages\Czech.isl"
Name: de; MessagesFile: "compiler:Languages\German.isl"
Name: es; MessagesFile: "compiler:Languages\Spanish.isl"
Name: it; MessagesFile: "compiler:Languages\Italian.isl"
Name: ko; MessagesFile: "compiler:Languages\Korean.isl

Can't I just copy the Korean.isl file into the inno Setup script language directory or folder where the languages of other countries are located?
**c:\Program Files (x86)\Inno Setup 6\Languages\

**Comment by hluk** [comment]
@VenusGirl Thanks for the tip. I tried including the new translation file in Inno Setup installation (#2315) but I still don't see the language when running the installer.

Strangely, I also see two entries for "English" in language selection combo box - same as in the installer for 7.0.0.

You can grab and test the new installer from: https://ci.appveyor.com/project/hluk/copyq/builds/46706467/artifacts

**Comment by VenusGirl** [comment]
Did you copy the Korean.isl file to the c:\Program Files (x86)\Inno Setup 6\Languages\ folder?

58 [CustomMessages]
106 [CustomMessages] section is duplicate and 106 should be deleted.
