### ISSUE TITLE
Navigating Next/Previous tab in main window with Left/Right arrow keys does not work.

### ISSUE THREAD

**Issue by tnilzon** [hluk/CopyQ#2328]
**Describe the bug**
Navigating Next/Previous tab in main window with Left/Right arrow keys does not work.

**To Reproduce**
1. Click on CopyQ tray icon (or use shortcut key) to show the main window (the main window should be configured with more than one tab).
2. Press keyboard Left- or Right arrow key.
3. Result: Nothing happens.

**Expected behavior**
Focused tab should shift in order Next/Previous when pressing Left/Right arrow keyboard keys.

**Screenshots**
N/A

**Version, OS and Environment**
 - Application Version [e.g. 3.7.2]: 6.4.0
 - OS Name: Microsoft Windows 11 Pro, Version10.0.22621 Build 22621

**Additional context**
N/A

**Comment by hluk** [comment]
Can you check if the keys are configured in Preferences?

![image](https://user-images.githubusercontent.com/38054/233697226-c092dc6a-77b6-43a4-bdab-7bebc8657cbd.png)

**Comment by tnilzon** [comment]
You're right, the keys were not configured. Many thanks!
