### ISSUE TITLE
Cannot take screenshots with drawing tablet

### ISSUE THREAD

**Issue by undefynedd** [hluk/CopyQ#2333]
**Describe the bug**
The screenshot feature does not work when using a graphics tablet to drag a box.

**To Reproduce**
1. Set a keyboard shortcut for "Take a Screenshot"
2. Take a screenshot with a drawing tablet
3. Dragging does not render or work, and pressing escape copies the entire screen. It looks as if the cursor is being moved, not dragged.

**Expected behavior**
This did not happen before. Expected behavior is for the drawing tablet to be able to drag a rectangle around area user wants to screenshot.

**Version, OS and Environment**
CopyQ Clipboard Manager 6.2.0
Qt: 5.15.2
KNotifications: 5.78.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Linux Mint 21.1

**Comment by undefynedd** [comment]
It started working after a restart, not sure if this is fixed but I'll close this issue.

**Comment by undefynedd** [comment]
It's not fixed

**Comment by hluk** [comment]
Can you update to a more recent version? 6.2.0 is more than year old.

Also, if you use Wayland (instead of X11) taking screenshots using CopyQ is not supported (and probably won't be).

**Comment by undefynedd** [comment]
> Can you update to a more recent version? 6.2.0 is more than year old.
> 
> Also, if you use Wayland (instead of X11) taking screenshots using CopyQ is not supported (and probably won't be).

I switched to Flameshot, CopyQ is a good clipboard manager.
