### ISSUE TITLE
Ubuntu 23.04 PPA support

### ISSUE THREAD

**Issue by KaKi87** [hluk/CopyQ#2334]
**Is your feature request related to a problem? Please describe.**
Currently, running `apt update` after `add-apt-repository ppa:hluk/copyq` on Ubuntu 23.04 outputs the following :
```
E: The repository 'https://ppa.launchpadcontent.net/hluk/copyq/ubuntu lunar Release' does not have a Release file.
```

**Describe the solution you'd like**
Add PPA support for Ubuntu 23.04

**Describe alternatives you've considered**
None

**Additional context**
None

---
Thanks

**Comment by hluk** [comment]
:+1: It should be there now.
