### ISSUE TITLE
Bell on copying items to clipboard and popup for searching through clipboard

### ISSUE THREAD

**Issue by Marin-Kitagawa** [hluk/CopyQ#2335]
**Describe the solution you'd like**
I have been previously using `Clip Clip` (CC). Whenever I copy things to the clipboard, CC will give a tone of sound. If the content copied is already present in the clipboard (say, for a history of 100 items), the tone will be milder and different. There will also be a bell sound when pasted from the clipboard.

Another feature is to search through the clipboard via popup. `Ctrl+Shift+v` is a shortcut in CC wherein it shows a popup through which I can select the item to be pasted. 

**Describe alternatives you've considered**

**Additional context**
See the below screenshot (some entries have been removed from the image)
![image](https://user-images.githubusercontent.com/49131888/233574548-439123dd-c075-4eab-887f-47033998cf69.png)

**Comment by hluk** [comment]
See: #1328

**Comment by Marin-Kitagawa** [comment]
Ok. What about the little window that allows you to search through clips without going to tray to `Show/Hide CopyQ`?

**Comment by hluk** [comment]
> Ok. What about the little window that allows you to search through clips without going to tray to `Show/Hide CopyQ`?

What would be the difference between this and tray (or even main window)?

**Comment by Chealer** [comment]
@Marin-Kitagawa: Please see [that checklist](https://blog.michael.gr/post/2014-11-bug-reporting-checklist/), in particular sections 8, 9 and 15.

Playing a sound when copying is already tracked in ticket #1865.
