### ISSUE TITLE
How to show the clipboard list by hot key(such as Ctrl+Shift+v) instead of clicking tray icon?

### ISSUE THREAD

**Issue by rmd13** [hluk/CopyQ#2336]
How to show the clipboard list by hotkey (such as Ctrl+Shift+v) instead of clicking tray icon?
I do not want to pin the GUI on the screen all the time, just need to show the list when I need to select one item at that moment.
After click that item once. the GUI could disappear. Move the mouse to the tray is too far on screen.

**Comment by rmd13** [comment]
Solved by adding a shortcut.

**Comment by sintaulsiam** [comment]
> Solved by adding a shortcut.

Doesn't work on wayland
