### ISSUE TITLE
Document for creating sub-menu for commands need to be corrected

### ISSUE THREAD

**Issue by luojunqiang** [hluk/CopyQ#2340]
<https://copyq.readthedocs.io/en/latest/writing-commands-and-adding-functionality.html#name>

> Name of the command. This is used in context menu if “In Menu” check box is enabled. Use / in the name to create sub-menus.

According to code of latest version 7.0, `|` should be used instead of `/` to create sub-menu for command.

**Comment by hluk** [comment]
Fixed, thanks! :+1:
