### ISSUE TITLE
View compounds by most recently added

### ISSUE THREAD

**Issue by taylertot** [hluk/CopyQ#2348]
**Describe the solution you'd like**
I'd like to view compounds in LIMBO by "most recently added". This helps me differentiate when Software has onboarded compounds (from #compound-onboarding channel in Slack), vs me manually onboarding compounds. (i.e., I'll know where to begin because there's a clear visual of the last onboarded compound)

**Comment by Slackadays** [comment]
What's LIMBO?

**Comment by hluk** [comment]
Looks like this is related to a different app not CopyQ (the clipboard manager).
