### ISSUE TITLE
Error message when onboarding a compound

### ISSUE THREAD

**Issue by taylertot** [hluk/CopyQ#2349]
Before creating a new issue, see list of [known
issues](https://copyq.readthedocs.io/en/latest/known-issues.html).

**Describe the bug**
Error message when trying to onboard a compound. When searching for the EXACT same compound to see if it already exists, it results in "no items found."

**To Reproduce**
1. Go to 'https://limbo.aetherbio.com/compounds'
2. Click on 'Add'
3. Input required data: Name, SMILES string, molecular formula, (add CAS Number in Description)
4. See "Error :( Please try again"

**Expected behavior**
To onboard the compound.
<img width="320" alt="Screenshot 2023-05-02 at 4 37 31 PM" src="https://user-images.githubusercontent.com/132326464/235807497-ac17f2de-33b1-4650-b076-2a52cf9b2a3e.png">
<img width="1701" alt="Screenshot 2023-05-02 at 4 38 00 PM" src="https://user-images.githubusercontent.com/132326464/235807545-6a005ee6-4e09-44a0-bd5a-73f9175a8b66.png">

**Screenshots**

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Application Version [e.g. 3.7.2]
 - OS [e.g. Windows]
 - Desktop environment, window manager (if applicable)

**Additional context**

**Comment by Slackadays** [comment]
I can't get into https://limbo.aetherbio.com/compounds, is that supposed to be an internal link?

**Comment by hluk** [comment]
Looks like this is related to a different app not CopyQ (the clipboard manager).
