### ISSUE TITLE
Want to print a CMP ID with Barcode

### ISSUE THREAD

**Issue by taylertot** [hluk/CopyQ#2350]
I have created a compound in [LIMBO](https://limbo.aetherbio.com/compounds). 
I go to print a label in https://devlimbo.aetherbio.com/print-label.
I selected "Bulk Container Label" 
Which option do I choose to print a label with CMP ID and Barcode?
<img width="586" alt="Screenshot 2023-05-02 at 4 50 19 PM" src="https://user-images.githubusercontent.com/132326464/235808984-1757183f-bf8e-46a2-8b23-f8cea1933311.png">

**Comment by Slackadays** [comment]
I don't that's CopyQ in your screenshot.

**Comment by hluk** [comment]
Looks like this is related to a different app not CopyQ (the clipboard manager).
