### ISSUE TITLE
Files-to-items synchronization separates notes from their items

### ISSUE THREAD

**Issue by timtrace** [hluk/CopyQ#2355]
This is CopyQ v7.0.0 on Win10 22H2

I have a "safe" tab that synchronizes to another folder on my local disk. It's also set for "files-to-items" with the extension ".txt" and the item media type "text/plain".

New clipboard items are stored in the "temp" tab.

If I drag an item with a note from temp to safe, the item is split in two, one for the original item and another for the note.

If I choose an item in "safe" which does not have a note, and "Edit Notes," it saves the note as a new item.

The problem is eliminated when I turn off "files-to-items" on my safe tab by removing the extension and type from the synchronization configuration.

Items that are dragged into the safe tab display their notes as expected.  If I add a note to an item using "Edit Notes," it works too. 

Curiously, items that had their notes separated by "files-to-items" are rejoined.

If I then re-enable files-to-items on my safe tab by putting the extension and type back into the synchronization configuration, any items with notes are split in two.

Is this a known problem?

**Comment by hluk** [comment]
Thanks for reporting this. Looking into this.

As workaround, you can remove "text/plain" text next to ".txt" in Synchronize configuration (or remove the whole entry - CopyQ should still handle text items well). Looks like the app forces notes to a separate file due to this configuration.

**Comment by timtrace** [comment]
Thanks! The screenie is my sync config without having made any changes --
![image](https://github.com/hluk/CopyQ/assets/11761953/09c23cd3-f8f3-4974-9498-982df00a906f)

**Comment by timtrace** [comment]
If I may add another symptom - if I tag an item in safe, it creates a duplicate item - one with the tag, one without. It doesn't seem to care if the item is txt or an image.

Your commit may have fixed the issue. I can wait for 7.1.1   :)

**Comment by hluk** [comment]
> If I may add another symptom - if I tag an item in safe, it creates a duplicate item - one with the tag, one without. It doesn't seem to care if the item is txt or an image.

That's a different issue. Fixing here: #2459

Thanks for testing!
