### ISSUE TITLE
Encrypted Tab not working

### ISSUE THREAD

**Issue by francwalter** [hluk/CopyQ#2363]
On Windows 10 (64-Bit) I wanted to create a protected tab.
I had GnuPG already installed, created a key pair in CopyQ and set a password.
Now I added a Tab "Safe" to my list of encrypted tabs and after this I save the preferences and close them.

![grafik](https://github.com/hluk/CopyQ/assets/927269/36f4a388-ce26-4fd5-9cdd-bed60291f006)

Now I create a tab "Safe" and put something in it by drag and drop from the Clipboard tab.

But I only see the circle (Reload-Icon) and if I click, nothing happens.
I cannot input my password, no entry is visible.

![grafik](https://github.com/hluk/CopyQ/assets/927269/db5bc1c2-cbe1-465e-9f07-065b738fa6ad)

I followed the instruction on: https://copyq.readthedocs.io/en/latest/password-protection.html

In my main tab I can encrypt (without password) and decrypt (with my key's password) single items without problem. 

![grafik](https://github.com/hluk/CopyQ/assets/927269/4e939c82-23bb-4e25-a07f-58d74e7b77ba)

But not the "Safe" tab. None of my clips in there are visible.
I tried other names for tabs, no difference.

What could that be?

Thanks.

**Comment by hluk** [comment]
Can you check logs for errors/warning (F12 shortcut from the main window)?

**Comment by francwalter** [comment]
Wow! You came back to me with this issue 😄 Thank! I lost hope a long time ago 😏 

`ERROR [2023-08-22 13:04:15.228] <Server-4840>: Tab “Safe”: Failed to save tab (save items to temporary file), file “C:/Users/f/AppData/Roaming/copyq/copyq_tab_U2FmZQ==.dat”: Writing canceled by application`

This I get, when I move a clip (just some text) to the Safe-Tab.

**Comment by francwalter** [comment]
Wow, yes, now it seems to work!
Thanks!

**Comment by francwalter** [comment]
Maybe I have to redo the whole encryption thing, but how to delete all and restart from scratch?
I already installed gpg4win with chocolatey, now I have gpg 2.4.3 with `Home: C:\Users\f\AppData\Roaming\gnupg` 
I dont know which version I had before.

**Comment by hluk** [comment]
> Maybe I have to redo the whole encryption thing, but how to delete all and restart from scratch? I already installed gpg4win with chocolatey, now I have gpg 2.4.3 with `Home: C:\Users\f\AppData\Roaming\gnupg` I dont know which version I had before.

I haven't tested this myself but you may need an older version for gpg4win 2.0.4. See also: https://github.com/hluk/CopyQ/issues/1208#issuecomment-1648325898

**Comment by francwalter** [comment]
OK, then I wait for that fix in that issue and live without an encrypted folder ;-)
No worries.

**Comment by francwalter** [comment]
Strangely it works when I hibernate my PC and wake up. Now the Crypt-Tab is encrypted and I need my password to make it visible.
But after one minute as I set in History settings ("Unload tab after an interval of minutes" = 1) it is still visible and also after hours.
In effect this is good enough, I think. I dont need it to be encrypted so fast. Hibernate is enough then.
