### ISSUE TITLE
Cycle through clipboard items 

### ISSUE THREAD

**Issue by kingp0dd** [hluk/CopyQ#2366]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Related to this: #729 

Is there way to modify it so that instead of showing toast notifications, it will instead

1. I press Ctrl+Shift+V
2. The regular CopyQ window opens
3. Letting go at this point will paste the text that is highlighted
4. Hitting 'V' instead of letting go will cycle to the next entry in the CopyQ window

This is easier than Ctrl+Shift+V and then using the arrow keys to select the item to paste. With this, you can select an item with just one hand.

**Describe alternatives you've considered**

**Additional context**

**Comment by hluk** [comment]
That's the behavior of the [Cycle Items](https://github.com/hluk/copyq-commands/blob/master/Global/README.md#cycle-items) command (see [README.md](https://github.com/hluk/copyq-commands/blob/master/README.md) for details on how to add the command).

**Comment by kingp0dd** [comment]
Wow I didn't notice that. I'll check it out. Thank you!!

**Comment by kingp0dd** [comment]
When an item is selected and pasted, and then the hotkey is activated again, the highlighted item is the last item pasted. Is there a way to reset the highlighted item to the most recent item (top most entry)?

**Comment by hluk** [comment]
> When an item is selected and pasted, and then the hotkey is activated again, the highlighted item is the last item pasted. Is there a way to reset the highlighted item to the most recent item (top most entry)?

Adding `selectItems(0)` before the line with `show()` should fix this.

I've updated the [Cycle Items](https://github.com/hluk/copyq-commands/blob/master/Global/README.md#cycle-items) command.

**Comment by kingp0dd** [comment]
Perfect, it works! Thanks @hluk!
