### ISSUE TITLE
CopyQ for 32-Bit windows

### ISSUE THREAD

**Issue by nanderer** [hluk/CopyQ#2369]
Hi,

i tried to install copyQ on windows 7 32-bit, it looked like it worked, but after the installation i tried to run it and got an error bout that its not runing on 32-bit systems. Could you make sure that your apparently 32bit installer dose not allow installation of 64-bit software on 32bit systems and provide a 32bit version for systems with low ram like mine?

Thanks in advance

**Comment by hluk** [comment]
I no longer build 32-bit versions on every release, only on demand.

Anyway, here is new 32-bit Windows build: https://ci.appveyor.com/project/hluk/copyq/builds/47369164/artifacts

**Comment by Qussayyon** [comment]
@hluk 
May I get a copy of 32bit for version 8.0 ?

**Comment by hluk** [comment]
New 32-bit Windows build: https://ci.appveyor.com/project/hluk/copyq/builds/49537334/artifacts

It uses older Qt 5 GUI framework since [Qt 6 does not support 32-bit Windows](https://doc.qt.io/qt-6.5/windows.html) anymore.

**Comment by Qussayyon** [comment]
@hluk,
That's good enough.

Thank you very much for your great help.
