### ISSUE TITLE
Scripting errors while performing built-in actions on Debian 10

### ISSUE THREAD

**Issue by elluisian** [hluk/CopyQ#2372]
**Describe the bug**
Basically, when I try to perform some actions on some of the items of a tab, nothing happens.
Not all actions are affected though, the ones that do not work for me are: Pin (Blocca), Add tag (Aggiungi etichetta), New Command (Nuovo comando) and even custom commands made by me do not work properly (but nothing is written on the terminal).

**To Reproduce**
1. Select an item from any tab;
2. Use some of the above mentioned commands on the item;
3. Nothing happens on the GUI but the terminal returns some scripting errors.
Some are TypeError, others are ReferenceError, basically, most of the JS objects are, apparently, set to "undefined";

**Expected behavior**
It should perform the operation I asked for without complaining...

**Screenshots**
![Pin action](https://github.com/hluk/CopyQ/assets/94404541/421fe689-462e-4ae2-9215-0b5b60733de3)

![Add tag action](https://github.com/hluk/CopyQ/assets/94404541/2f69bc91-ec96-4bee-a6b7-c63b9e8779cb)

![New command action](https://github.com/hluk/CopyQ/assets/94404541/c3584f26-efdd-4658-aeeb-82eb5dc68727)

![Terminal errors only](https://github.com/hluk/CopyQ/assets/94404541/70a66caf-0588-4f15-ba6b-3ccd8b212864)

**Version, OS and Environment**
 - CopyQ v7.0.0, v5.0.0, v4.1.0, git version;
 - GNU/Linux Debian 10 (old stable);
 - Xorg, IceWM (desktop environment mode) and some Tint2 panels;
 - `copyq version` output:

```
CopyQ Clipboard Manager v5.0.0
Qt: 5.11.3
KNotifications: 5.54.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Debian GNU/Linux 10 (buster)
``` 

**Additional context**
I compiled (and installed, thanks to GNU stow) all the versions I reported, I even tried to install the Debian 10 .deb file for version 7.0.0... the problem is always there (installed or not).
Up to now, I was always using CopyQ 3.7.3 (installed with apt), which works perfectly, but I want to upgrade, even because I plan to compile this program on an arm64 platform which does not support QSemaphore, but uses Debian 10.
I even tried removing my original user data made with version 3.7.3... same exact thing.

**Comment by hluk** [comment]
The app cannot find plugins. You need to install the app or override the `PLUGIN_INSTALL_PREFIX` cmake option.

**Comment by antoniodanielegialluisi** [comment]
> The app cannot find plugins. You need to install the app or override the `PLUGIN_INSTALL_PREFIX` cmake option.

First of all, thank you for the response.
Sorry for bothering, but unfortunately this isn't working.
Before answering to you again I made other tests, since I didn't know the existence of the `PLUGIN_INSTALL_PREFIX` variable.

Just to be sure I've made everything correctly, I will report the steps I've made, I apologize in advance if I made some stupid mistake.
First of all, I got the repositories and the metadata:

```
git clone <repository-url>
cd CopyQ
git fetch --all --tags
```

I made sure to get all the tags I tested with before, that is, v3.13.0, v4.0.0, v4.1.0, v5.0.0 and v7.0.0, so for each of them, I made `git checkout tags/<version> -B <version>`.

Now, for each local branch, I've compiled using these instructions:

```
git checkout <current-local-branch>
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=<install-prefix> -DPLUGIN_INSTALL_PREFIX=<plugin-install-prefix>
make -j4
sudo make install
```

I tried THREE set of paths for both CMAKE_INSTALL_PREFIX and PLUGIN_INSTALL_PREFIX, these were, respectively:

- /usr and /usr/lib/copyq/plugins
- /usr/local and /usr/local/lib/copyq/plugins
- /usr/local/stow/copyq-test and /usr/local/stow/copyq-test/lib/copyq/plugins


The result is the same as the original bug report, version 3.13.0 works perfectly, all the other ones show the same exact behaviour, no change, no matter the version or the used paths.

From the look of the program GUI below, it seems the pin plugin or whatever it is called is correctly identified (I may be mistaken though).
This is shown in all versions.

![Items section](https://github.com/hluk/CopyQ/assets/94404541/b7ba5e04-c9a0-49e2-bcdc-79f1fd75d9d9)


The only actual "strange" thing I've noticed is during the cmake command, in fact, when I use it on v4.0.0 and superior some warnings are issued, please, have a look.
Version 3.13.0:

```
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building with ItemWeb plugin.
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Building for X11 window system.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/antoniodaniele/Scrivania/CopyQ/build
```


Version 4.0.0 onwards:

```
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.20.1") 
-- Building CopyQ version 7.0.0.
CMake Warning (dev) at /home/antoniodaniele/Lista_Scaffali/Scaffali-common/Programmi_TerzeParti/USR_LOCAL/progs-common/cmake-3.22.2-linux-x86_64/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args`
  (KF5Notifications) does not match the name of the calling package (KF5).
  This can lead to problems in calling code that expects `find_package`
  result variables (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /usr/share/ECM/find-modules/FindKF5.cmake:78 (find_package_handle_standard_args)
  src/notifications.cmake:11 (find_package)
  src/CMakeLists.txt:24 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found KF5Notifications: /usr/lib/x86_64-linux-gnu/cmake/KF5Notifications/KF5NotificationsConfig.cmake (found version "5.54.0") 
-- Found KF5: success (found suitable version "5.54.0", minimum required is "5.18.0") found components: Notifications 
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Building for X11 window system.
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29") 
CMake Warning (dev) at /home/antoniodaniele/Lista_Scaffali/Scaffali-common/Programmi_TerzeParti/USR_LOCAL/progs-common/cmake-3.22.2-linux-x86_64/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args`
  (Wayland_Client) does not match the name of the calling package (Wayland).
  This can lead to problems in calling code that expects `find_package`
  result variables (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /usr/share/ECM/modules/ECMFindModuleHelpers.cmake:248 (find_package_handle_standard_args)
  /usr/share/ECM/find-modules/FindWayland.cmake:101 (ecm_find_package_handle_library_components)
  src/platform/x11/systemclipboard/CMakeLists.txt:2 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found Wayland_Client: /usr/lib/x86_64-linux-gnu/libwayland-client.so (found version "1.16.0") 
-- Found Wayland: /usr/lib/x86_64-linux-gnu/libwayland-client.so (found suitable version "1.16.0", minimum required is "1.15") found components: Client 
-- Found QtWaylandScanner: /usr/lib/qt5/bin/qtwaylandscanner  
-- Configuring done
CMake Warning (dev) in src/platform/x11/systemclipboard/CMakeLists.txt:
  Policy CMP0071 is not set: Let AUTOMOC and AUTOUIC process GENERATED files.
  Run "cmake --help-policy CMP0071" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  For compatibility, CMake is excluding the GENERATED source file(s):

    "/home/antoniodaniele/Scrivania/CopyQ/build/src/platform/x11/systemclipboard/wayland-wlr-data-control-unstable-v1-protocol.c"
    "/home/antoniodaniele/Scrivania/CopyQ/build/src/platform/x11/systemclipboard/qwayland-wlr-data-control-unstable-v1.cpp"
    "/home/antoniodaniele/Scrivania/CopyQ/build/src/platform/x11/systemclipboard/qwayland-wlr-data-control-unstable-v1.h"

  from processing by AUTOMOC.  If any of the files should be processed, set
  CMP0071 to NEW.  If any of the files should not be processed, explicitly
  exclude them by setting the source file property SKIP_AUTOMOC:

    set_property(SOURCE file.h PROPERTY SKIP_AUTOMOC ON)

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /home/antoniodaniele/Scrivania/CopyQ/build
```


I'm not exactly sure what's going on and I don't know if this is related somehow.\
Unfortunately I'm not familiar with cmake nor Qt programming: I just know how to make cmake create the Makefile, I don't know its inner workings.


I hope I'm not bothering too much, but thanks in advance for the response anyway.


PS: If it turns out it IS ME, I'm sorry, no time wasting intended.

**Comment by hluk** [comment]
Hmm, not sure what is happening. The cmake output looks OK - I don't see anything that could break the build.

It is possible that the Qt library on your system is too old (Qt 5.11 is about 5 years old). There is a trick for initializing the `plugins` global variable in scripts but it is unclear in which versions of Qt this can work.

Try to check [debug logs](https://copyq.readthedocs.io/en/latest/faq.html#how-to-enable-logging) if there are any errors/failures during the app start.

You can also try to launch a clean app session to see if any configuration and custom commands in the default session affect the behavior:

```bash
copyq -s test
```

**Comment by elluisian** [comment]
Hi @hluk, I'm sorry for the very late response on this issue, I've been quite busy with university.

You were right (not that I doubted it), the problem is the Qt version.
After many tries, I was capable of compiling Qt 5.12 on Debian Buster.
I tried compiling versions 7, 6, 5 and 4 of CopyQ and they all work correctly now!
In other words, it seems that to run CopyQ 4.0 or higher, you need at MINIMUM Qt 5.12, Qt 5.11 won't work (this is the default with Debian 10).

Now `copyq version` returns:

```
CopyQ Clipboard Manager v4.0.0
Qt: 5.12.0
KNotifications: 5.54.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Debian GNU/Linux 10 (buster)
```

I believe this issue can be declared as "solved".
Sorry for bothering you and thanks for your patience.

**Comment by hluk** [comment]
No problem. Glad all works for you now.
