### ISSUE TITLE
CopyQ ZIP version not digitaly signed

### ISSUE THREAD

**Issue by Dragonminds** [hluk/CopyQ#2378]
Before creating a new issue, see list of [known
issues](https://copyq.readthedocs.io/en/latest/known-issues.html).

**Describe the bug**
When trying to start CopyQ 7.0.0 from ZIP version, Windows 11 shows Windows Defender SmartScreen message: 
App: copyq.exe 
Pubisher: Unknown publisher

**To Reproduce**
1. Download ZIP of CopyQ 7.0.0 from Github repository
2. Extract to a local folder on a Windows 11 system. 
3. Execute the copyq.exe
4. SmartScreen protection message shows. 

**Expected behavior**
SmartScreen warning should not be shown. The executable should be digitaly signed. 

**Screenshots**
![image](https://github.com/hluk/CopyQ/assets/137488895/d8113fab-35e9-48eb-b84f-e8638e0fb53a)

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
Zwischenablageverwaltung
7.0.0

**Additional context**

**Comment by shawnholt** [comment]
I install many windows programs from github but do not see this warning. Virustotal says 2 flags on current version.
