### ISSUE TITLE
Show shortcuts of command on tray icon menu

### ISSUE THREAD

**Issue by GFDGIT** [hluk/CopyQ#2382]
**Describe the solution you'd like**
It would be useful to show shortcuts of command on tray icon menu. Just like what displayed in the right-click menu of the main window.

**Additional context**
![image](https://github.com/hluk/CopyQ/assets/22742500/4ab5b6ef-db26-4598-bd08-50df522ca29c)

**Comment by GFDGIT** [comment]
Sorry to reopen this issue (it came a bit late).

For testing purposes, I have newly installed version 8.0.0 of copyq and created some commands of types `In menu (Ctrl+M)`、`Global Shortcut (Ctrl+G)` and `Menu and Global (Ctrl+Shift+M and Ctrl+Shift+G)`.  And here are the test results: 

1.  In `mian window` context menu, everything works as expected. 
![image](https://github.com/hluk/CopyQ/assets/22742500/7c916ecd-622a-4336-8770-47d1d360e722)

2.  In `tray menu`, the global shortcut key is not displayed.
![image](https://github.com/hluk/CopyQ/assets/22742500/124956aa-063b-4c80-bff3-4d504483d054)

Please take a look into it.

**Comment by hluk** [comment]
Thanks for reporting the problem. I overlooked that my last implementation actually did not update the tray menu.

The fix will be available in the next release.

You can test it with the development builds: https://ci.appveyor.com/project/hluk/copyq/builds/49751820/artifacts

**Comment by GFDGIT** [comment]
> You can test it with the development builds: https://ci.appveyor.com/project/hluk/copyq/builds/49751820/artifacts

Tested and no problem
