### ISSUE TITLE
Is it possible to reuse file paths on Windows?

### ISSUE THREAD

**Issue by eggbean** [hluk/CopyQ#2383]
In the FAQ I see this section which mentions it being possible to reuse file paths:

https://copyq.readthedocs.io/en/latest/faq.html#how-to-reuse-file-paths-copied-from-a-file-manager

Can this be done on Windows as well?

I can see `file://foo` paths in the history, but selecting them doesn't seem to allow repasting the file in Windows Explorer.

Would a script which translates the `file://foo` path to Windows paths like `C:\foo` (as well as other required MIME-type stuff) work?

**Comment by graphixillusion** [comment]
I'm looking exactly for the same thing. Ditto-cp has this feature enable in it.

**Comment by eggbean** [comment]
If you do find a way, please remember to say here.

**Comment by eggbean** [comment]
@graphixillusion 

This post suggests that the same method works on Windows too, but how to you find the MIME types in Windows? Have you tried this?

https://github.com/hluk/CopyQ/issues/1439#issuecomment-658132992

**Comment by graphixillusion** [comment]
@eggbean according to this table:

Windows Format	Equivalent MIME type
CF_UNICODETEXT	text/plain
CF_TEXT	                text/plain
CF_DIB	                image/xyz, where xyz is a Qt image format
CF_HDROP	        text/uri-list
CF_INETURL	        text/uri-list
CF_HTML	                text/html

i've modified the original script into this and it seems to work good:

```
[Command]
Name=Store File Manager Metadata
Command="
    var originalFunction = global.clipboardFormatsToSave
    global.clipboardFormatsToSave = function() {
        return originalFunction().concat([
            mimeUriList,
            'CF_HDROP',
        ])
    }"
IsScript=true
Icon=\xf0c1
```

**Comment by GFDGIT** [comment]
There is a simpler command:
```
[Command]
Name=Copy file on Windows
Input=text/uri-list
Automatic=true
Icon=\xf0c1
```

**Comment by eggbean** [comment]
Excellent. I didn't think that this would end up with a working solution when I asked. Thanks both of you.

**Comment by GFDGIT** [comment]
In fact, the command from FAQ [How to reuse file paths copied from a file manager?](https://copyq.readthedocs.io/en/latest/faq.html#how-to-reuse-file-paths-copied-from-a-file-manager) work on windows and linux, no need to modify it. 

 `mimeUriList ` contain `text/uri-list` which equivalent `CF_HDROP`.
