### ISSUE TITLE
CTRL+1-9 quick select

### ISSUE THREAD

**Issue by black-snow** [hluk/CopyQ#2388]
Perhaps you can already do this and I'm just too blind to see it.

**Is your feature request related to a problem? Please describe.**
My most common use case for a clipboard manager is to have to copy two things. But even with more items on my history I often know in what order they are or it's quick to see. I want to be able to pick the item of choice directly without either having to use the mouse or to navigate down to it using arrow keys.  
Navigating the history is frustrating and I find myself rather copying stuff more often from source again than having to navigate through the clipboard history. There's numbers right next to the entries already - why is that if not for quick access?

**Describe the solution you'd like**
E.g. Ditto has the very handy ctrl+1-9 shortcut to select and insert the 1st-9th item directly. I need to have that in CopyQ as well.

Apparently, ctrl+number is [bound to tab navigation](https://copyq.readthedocs.io/en/latest/keyboard.html). I don't use tabs, and ctrl+number is comfy (small finger vs. thumb). I could live with some alternative meta key, though.

**Describe alternatives you've considered**
Using another clipboard manager.

**Additional context**
-

**Comment by hluk** [comment]
I've added a **new command** [Select Nth Item](https://github.com/hluk/copyq-commands/tree/master/Application#select-nth-item) that works as you describe (see [README.md](https://github.com/hluk/copyq-commands/blob/master/README.md) for details on how to add the command).

**Comment by black-snow** [comment]
Awesome, thanks @hluk!  

I do have some issues with that, though. May or may no be related to wayland/latest Ubuntu. When I hit crtl+\d CopyQ correctly sets the item and it shows up on top, but

* it doesn't insert it (tried FF, sublime text and other apps)
* ctrl+v still inserts the item from before until I hit return on my item of choice

Hence, my workflow atm is to `ctrl+shift+v` and `ctrl+\d` to choose the item, `ctrl+shift+v` to pop CopyQ open again, hit `return`, `ctrl+v` to actually insert the item :/

**Comment by hluk** [comment]
Yeah, unfortunately, pasting in Wayland does not work (even if started with `QT_QPA_PLATFORM=xcb`, CopyQ may not be able to paste into other Wayland apps).

One workaround is to use ydotool to handle it but I have not used it in a while - see [Wayland Support](https://github.com/hluk/copyq-commands/tree/master/Scripts#wayland-support) command ([here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)).

**Comment by black-snow** [comment]
Yikes, do you happen to have a corresponding wayland issue at hand?

I'll close this one. Thanks a lot for your help @hluk ! CopyQ is a real must have and I'm very grateful for it.
