### ISSUE TITLE
MacOS: “CopyQ” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by nZeus** [hluk/CopyQ#2393]
**Describe the bug**
Cannot run CopyQ on MacOS

**To Reproduce**
1. Install copyq using the command `brew install --cask copyq`
2. Try to open the app

**Expected behavior**
The app should run

**Screenshots**
An error is shown
<img width="371" alt="Screenshot 2023-07-10 at 13 17 17" src="https://github.com/hluk/CopyQ/assets/2727326/ffe7aa49-3a83-46d1-ae91-6e4c5ee0b56b">

**Version, OS and Environment**
 - OS Mac OS latest

**Comment by nZeus** [comment]
There is a work-around, it's possible to disable the check for the app by executing this command:
```
sudo xattr -cr /Applications/CopyQ.app
```

**Comment by hluk** [comment]
Looks like the usual behavior on macOS (the app is not signed). Not sure if it might be worth adding to docs (https://copyq.readthedocs.io/en/latest/known-issues.html).

**Comment by nZeus** [comment]
but why not to sign the app? I assume non-tech users won't be able to use the app on Mac
