### ISSUE TITLE
Global shortcut doesn't pass argument?

### ISSUE THREAD

**Issue by reagle** [hluk/CopyQ#240]
I'm new to CopyQ so this is probably a bug in my understanding, but if I assign a global shortcut to the Open URL command, I would expect to be able to do the following:
1. select text/URL; (I have "store text selected using mouse" so the text is at the top of the clipboard history)
2. type global shortcut <alt+ctrl+1>
3. see a browser launched with that URL

Problem: it opens a new _but empty_ browser. However, if I go to the copyq tab, alt+click, and select 'Open URL' it works as expected.

'''
[Command]
Name=Open URL
Match=^(https?|ftps?|file)://
Command=google-chrome %1
Input=text/plain
Output=text/html
InMenu=true
Icon=\xf0c1
GlobalShortcut=Ctrl+Alt+1
'''

**Comment by reagle** [comment]
I'm also trying to use copyq on Mac now, and my commands (below, for example) tend to yield "undefined", I presume because selection doesn't work on OSX either.

```
copyq:
url = 'https://www.google.com/search?q='+str(selection())
open(url)
```

**Comment by hluk** [comment]
You should use `clipboard()` instead, `selection()` is mouse selection which is available only on X11. I don't know is OSX has anything similar but [Qt only supports clipboard on OSX and Windows](http://doc.qt.io/qt-5/qclipboard.html#notes-for-os-x-users).

You can get around it by copying the currently selected text to clipboard. E.g.

```js
copyq:
function selection(args) {
  copy()
  return clipboard.apply(this, arguments)
}

url = 'https://www.google.com/search?q='+str(selection())
open(url)
```

**Comment by hluk** [comment]
Oops, the `copy()` [is not implemented for OSX](https://github.com/hluk/CopyQ/blob/a49969c5118a98838d0c1372175517d69df6c981/src/platform/mac/macplatformwindow.mm#L278).

I cannot implement or test this on OSX. In theory it's trivial to implement since `paste()` already works. The only difference is that `copy()` function should send <kbd>Command</kbd>+<kbd>C</kbd> to the active window.

Can someone implement it?

**Comment by hluk** [comment]
I've created task #450 for that.

**Comment by reagle** [comment]
@hluk, I'm wondering what you were doing with the "(str(selection()) || str(clipboard()))". I thought it might use clipboard() where selection() isn't available, but it still gives me undefined. Does it return clipboard() if selection() exists but is null?

**Comment by hluk** [comment]
@reagle  Oh, my bad, it should actually be `str(selection() || clipboard())`. Calling `selection()` on Windows and OS X [always returns `undefined`](https://github.com/hluk/CopyQ/blob/e11d419a92b288f03d42012063ca20db8e459788/src/scriptable/scriptable.cpp#L536).
