### ISSUE TITLE
The cycle items command behaves incorrectly in v7.0.0

### ISSUE THREAD

**Issue by gerardbosch** [hluk/CopyQ#2411]
**Describe the bug**
A few months ago I noticed the [cycle items command](https://github.com/hluk/copyq-commands/blob/master/Global/cycle-items.ini) originally described [here](https://github.com/hluk/CopyQ/issues/1948), started to behave differently/incorrectly:

* When I release the `Ctrl` key, the window does not close, nor the text is pasted. Now I have to do an extra and hit `Enter` to make it work (I'm using `Ctrl` + `;` as cycle hotkey).

Today I tried to update the command with the [last version](https://github.com/hluk/copyq-commands/commits/master/Global/cycle-items.ini) just in case, as I was still using the first version (I didn't notice there was new versions of the command), but that didn't help. So I decided trying downgrading CopyQ to v6.4.0, which solved the issue.

I'm not sure if the problem is a regression in CopyQ 7.0.0 or the command needs to be updated, so I'm filing it here.

I also noticed that the "Notification for Copied Commands"-command is not working (neither in 6.4.0 nor 7.0.0), but I'm not sure since when, as it's been a long time since last time I installed a command.

**To Reproduce**
Cycle through pasted items and release hotkey.

**Expected behavior**
The text is automatically pasted.

**Version, OS and Environment**
CopyQ v7.0.0
OS: Ubuntu 23.04 / Gnome / X11

**Additional context**
Installed via Nix: `nix profile install nixpkgs#copyq`

**Comment by hluk** [comment]
I haven't tested it on Gnome, but for me both the [Cycle Items](https://github.com/hluk/copyq-commands/blob/master/Global/cycle-items.ini) and [Import Commands after Copied to Clipboard](https://github.com/hluk/copyq-commands/blob/master/Automatic/import-commands-after-copied.ini) work in Fedora 38 with X11 and both kwin and xfwm4 window managers. Not sure what could be the problem.

I don't see any changes between 6.4.0 and 7.0.0 that could affect the behavior.

Could there be some change in the Nix package itself? Maybe a different version of Qt library linked with CopyQ?

**Comment by gerardbosch** [comment]
Thanks for checking this. I tried to browse the Nixpkgs repo as you suggested and apparently it seems there were changes on the QT library, though I'm not familiar at all with any of this.

I found this commit in particular with changes on the QT version, I think from QT5 to QT6. For the date of that commit, could be the source of the issue, as I noticed that started to misbehave long time ago (January/February makes sense to me). Also, it happens to be the immediate commit after CopyQ v6.4.0:

https://github.com/NixOS/nixpkgs/commit/7b61a2bf69212f907ba5e320b9097355090c6e76

Here is the full list of commits on nixpkgs for CopyQ:

https://github.com/NixOS/nixpkgs/commits/044b56eb42730951627bbb7369bc7b2278207dec/pkgs/applications/misc/copyq/default.nix

Do you have any idea on how this could be fixed or what's the root of the problem? Thank you!

**Comment by hluk** [comment]
Oh, looks like there is a problem with the Qt 6 version of the app. Fixing it now.

**Comment by gerardbosch** [comment]
> Oh, looks like there is a problem with the Qt 6 version of the app. Fixing it now.

Great! You're awesome 👏

**Comment by gerardbosch** [comment]
Thanks @hluk! Is the bugfix release going to be published? I'd like to submit a PR to Nixpkg repo and update my installation :)

**Comment by hluk** [comment]
> Is the bugfix release going to be published?

Not yet. But the `master` branch is usually stable.

**Comment by gerardbosch** [comment]
> > Is the bugfix release going to be published?
> 
> Not yet. But the `master` branch is usually stable.

Can we publish the v7.0.1 with this fix or what's the reason for not releasing this? Asking as I'd like to update the Nix package manager with the version that contains this bugfix, then upgrade my installation using Nix. I'm not sure whether I should create a package version that it is not tagged.

Example: https://github.com/NixOS/nixpkgs/commit/d3bfe908177d2aa6dd33a3bdbeb944276fea08e3

**Comment by hluk** [comment]
Unfortunately, the new release is blocked on broken macOS build (due to some external change - missing libs): https://github.com/hluk/CopyQ/actions/runs/6034986679/job/16376461805

**Comment by hluk** [comment]
I've released a new version 7.1.0 (I will have to build the macOS binary after the problems are resolved).
