### ISSUE TITLE
Deleting items does not remove the (now-deleted) uppermost item text from the window title

### ISSUE THREAD

**Issue by dominicpalmer** [hluk/CopyQ#2415]
**Describe the bug**
On deleting all items from a tab, the window title still displays the text from what was the uppermost item.

**To Reproduce**
1. Add an item to a tab.
2. Open the GUI. Delete the item. Close the GUI again.
3. Reopen the GUI.
4. The now-deleted item text is still displayed in the window title. This must be pulled from memory as opposed to disk, because at this point the data is already removed from the `.dat` file.

**Expected behavior**
On deleting all items in a tab, the window title should be `CopyQ` and contain no reference to any deleted items.

![copyq-issue](https://github.com/hluk/CopyQ/assets/32597988/8764206b-ad94-4617-aa47-063516221765)

**Version, OS and Environment**
- CopyQ 7.0.0
- gpg4win-2.0.4.exe
- Windows 10

**Comment by hluk** [comment]
The window title shows the current clipboard content, not a content of an item stored in CopyQ. You can disable this with [No Clipboard in Title and Tool Tip](https://github.com/hluk/copyq-commands/tree/master/Scripts#no-clipboard-in-title-and-tool-tip) command (see [README.md](https://github.com/hluk/copyq-commands/blob/master/README.md) for details on how to add the command).
