### ISSUE TITLE
Automatic switch to move screenshots into a dedicated tab

### ISSUE THREAD

**Issue by abr0011** [hluk/CopyQ#2417]
Would that be possible? So i would have text snippets in the main tab/clip board, and all types of non-text items would go into the designated tab.

**Comment by hluk** [comment]
Here is a command to move any new clipboard item containing `image/png` format to "Images" tab in CopyQ ([here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)):

```ini
[Command]
Automatic=true
Icon=\xf302
Input=image/png
Name=Tab for Images
Remove=true
Tab=Images
```

**Comment by abr0011** [comment]
Sorry, i can't get it to work. Is this right in my screenshot?

[grafik.png]

Sicher versendet mit [Proton Mail](https://proton.me/).

------- Original Message -------
Lukas Holecek ***@***.***> schrieb am Sonntag, 10. September 2023 um 08:37:

**Comment by hluk** [comment]
> Sorry, i can't get it to work. Is this right in my screenshot?

I cannot see the screenshot. Can you share it directly on GitHub (instead of via mail)?

**Comment by abr0011** [comment]
Sure. But something strange happened. I had the code removed from the filter field, and once of a sudden your code works! See also, that the code is present some additional three times! Anyway, it works now! I have also restarted CopyQ to see if it still works, and it does.

By the way, i have no preview popup in the notification area, but that's not a problem at all.
But funny, that it does work, even though all the four fields are now empty. Seems, like CopyQ hat 'integrated' the code anyway.

So, thanks a lot, this is exactly what i was looking for!

https://i.imgur.com/5pHXLge.png

Sicher versendet mit [Proton Mail](https://proton.me/).

------- Original Message -------
Lukas Holecek ***@***.***> schrieb am Sonntag, 10. September 2023 um 14:08:

**Comment by hluk** [comment]
> By the way, i have no preview popup in the notification area, but that's not a problem at all.

I've updated the command in Commands repository (this one shows notifications): https://github.com/hluk/copyq-commands/blob/master/Automatic/move-images-to-other-tab.ini
