### ISSUE TITLE
Command processing and resulting &clipboard item

### ISSUE THREAD

**Issue by reagle** [hluk/CopyQ#242]
I have a command that changes the chase of a selection. As a result, it does place the transformed text as place 0 on the clipboard. However, even though it is at location 0, it is not pasted through ctrl+v or middle-click. I have to actually open the clipboard and select the item. Is there a way so that results are automatically transferred to the systems' clipboards?

```
[Command]
Name=Title Case
Command=bash:\n/home/reagle/bin/fe/change_case.py $(copyq selection)
Output=text/plain
InMenu=true
OutputTab=&clipboard
```

**Comment by reagle** [comment]
Not sure what happened (haven't used this in a bit) but this now results in "true" being added to my clipboard. If I perform the commands manually, this is what I see:

```
urd:~/bin/fe (master)$ text="$(/home/reagle/bin/fe/change_case.py -f "$(copyq selection)")"
urd:~/bin/fe (master)$ echo $text
Lessons I learned on the road as a digital nomad
urd:~/bin/fe (master)$ copyq copy "$text"
true
urd:~/bin/fe (master)$ echo $text
Lessons I learned on the road as a digital nomad
urd:~/bin/fe (master)$ copyq add "$text"

```

**Comment by hluk** [comment]
You probably have "Output" field set for the command in Command dialog [F6]. If you leave the field empty it should work.
