### ISSUE TITLE
How to increase Search font size ?

### ISSUE THREAD

**Issue by luapfr** [hluk/CopyQ#2421]
The font is very small when I start a search. Is there a way to increase this font ?

![CopyQ](https://github.com/hluk/CopyQ/assets/50739062/8adaa77a-02bc-4a2c-9d9f-36bbdaad0ee0)

**Comment by hluk** [comment]
1. Go to Preferences dialog (Ctrl+P).
2. Open Appearance tab.
3. Click Edit Theme button.
4. Find `search_bar` option and add `font-size: 12pt` (or a larger/lower value). The option value could look like this:

```ini
search_bar="
    ;font-size: 12pt
    ;background: ${edit_bg}
    ;color: ${edit_fg}
    ;border: 1px solid ${alt_bg}
    ;margin: 2px"
```
