### ISSUE TITLE
Win+v open windows clipboard instead of use copyq shortkey

### ISSUE THREAD

**Issue by Alexnoj** [hluk/CopyQ#2422]
any idea how to fix it?
clipboard history is off in settings

my script
![image](https://github.com/hluk/CopyQ/assets/30004592/d6f6db63-c5a6-4b73-a86c-41a388d2a93a)

what i get
![image](https://github.com/hluk/CopyQ/assets/30004592/632a0909-278d-487d-b221-2aae658145de)

**Comment by Mattwmaster58** [comment]
I don't know much about the internal mechnisms of global keyboard shortcuts, but looks like the keypress is still being intercepted by windows. I would look for a way to disable the shorcut entirely - may need to edit the registry, GPO, etc  OR use AHK to map meta+v to a seperate obscure key combo, and have that key combo assigned to this command in CopyQ, as AHK's keyboard shortcut robustfulness is second to none IMO. 

In any case, I'm confident this isn't CopyQ's fault

**Comment by Alexnoj** [comment]
hey
thanks for try help.

I forgot update. I solve the problem by block microsoft clipboard in registry. [here ](https://superuser.com/a/1734901/1828561)i found the solution
