### ISSUE TITLE
Case sensitivity doesn't work

### ISSUE THREAD

**Issue by K2M74** [hluk/CopyQ#2428]
**Describe the bug**
As below GIF image, case sensitivity is turned off, but it doesn't work.

**To Reproduce**
![1](https://github.com/hluk/CopyQ/assets/50667472/fe9fe438-7ad4-4bc3-a3d6-0cf8dcc0c2b4)

**Version, OS and Environment**
 - Application Version 7.0.0
 - OS Windows

**Comment by hluk** [comment]
The option is called "Case Insensitive" in English. It looks like the translation is incorrect.

Can you help fix it? It can be changed here: https://hosted.weblate.org/translate/copyq/master/zh_Hans/?q=Case+Insensitive

Thanks for the report!

**Comment by hluk** [comment]
Thanks for the fix. :pray:
