### ISSUE TITLE
Ctrl-C bug in search doesn't work.

### ISSUE THREAD

**Issue by luapfr** [hluk/CopyQ#2440]
I think it's a bug in the latest version.

**Comment by hluk** [comment]
Can you post steps to reproduce the issue?

**Comment by luapfr** [comment]
I do a search and scroll with the keyboard and key "CTRL + C" and it is not copied to the clipboard

see the attached video.
[Bug CopyQ.webm](https://github.com/hluk/CopyQ/assets/50739062/85f26007-45a2-47c5-af52-5f7452815621)

**Comment by luapfr** [comment]
> Hmm, I don't think it ever worked any other way: while the search entry box has focus it processes the copy shortcut even if it does not have a selection.
> 
> But that is annoying - I'm fixing it.



I use the keyboard a lot and the mouse a little

So there is a second bug
When I do a search that shows a search history, I can't automatically scroll to the list, it gets stuck in the search history, it would be interesting if I click on the down arrow to be able to go to the list without needing to use the mouse

[2 Bug CopyQ.webm](https://github.com/hluk/CopyQ/assets/50739062/a9598e16-c5a7-4d26-9cbe-565071d32d66)

**Comment by hluk** [comment]
> So there is a second bug
> When I do a search that shows a search history, I can't automatically scroll to the list, it gets stuck in the search history, it would be interesting if I click on the down arrow to be able to go to the list without needing to use the mouse

That is not a bug. To use Up/Down arrows, disable the "Save Filter History" or use tab first to switch to the item list.

I thing your problems can be related to this change: #1834
