### ISSUE TITLE
Fix Export and Import

### ISSUE THREAD

**Issue by nolimitse** [hluk/CopyQ#2442]
fix 

Export and Import
You can easily export selected tabs and optionally configuration and commands within the application.

Warning

Tabs are always exported unencrypted and if a tab is synchronized with directory on disk the files themselves won’t be exported.

To export the data click “Export…” in “File” menu and select what to export, confirm with OK button and select file to save the stuff to.

To restore the data click “Import…” in “File” menu, select file to import and select what to import.

Note

Import won’t overwrite existing tabs and commands but create new ones.

Alternatively you can use command line for export and import everything (selection dialogs won’t be opened).

copyq exportData {FILE/PATH/TO/EXPORT}
copyq importData {FILE/PATH/TO/IMPORT}

**Comment by hluk** [comment]
Sorry, I don't see what is the problem here.
