### ISSUE TITLE
Number as shortcuts to paste item

### ISSUE THREAD

**Issue by majkinetor** [hluk/CopyQ#246]
Unless I missed existing feature, I find it very unpractical to to j/k the list until I find the item I want. 

It would be awesome if we could use number to paste item on that position, similar to what vim has with `:number<cr>` command.

Currently it starts up search for those numbers and I guess some people might want to have search for numbers available. This could be optional setting or could even require prefix like `:` 

This feature, for example, exists in the best open source windows clipboard manager [clcl](http://www.nakka.com/soft/clcl/index_eng.html)

**Comment by pacid** [comment]
Is this feature still working? I am searching high and low for such a feature as I am doing a lot of copy pasting repetitively and thought it must be somthing like pressing number or ctrl+number or alt+number, I means that't one of the first feature you think about and do it instinctively. I can't seem to find in docs and can't get it to work by just pressing the numbers with the window of CopyQ open. Halp!

**Comment by majkinetor** [comment]
You just press number while copy q windows is shown. Numbers are shown on the left. Number will be typed in search bar, don't that confuse you. So, <number><enter> is all you do

**Comment by pacid** [comment]
Oh yeah figured that it's:
1) Open the CLIPBOARD window
2) Press the number of the stored text you want to paste
3) then ENTER to actually paste it

Thank you majkinetor for the response nonetheless!

How about:
1) Configure the global hotkeys which, in case they are pressed with number key (0-9) just paste the text. So I could have for instance ctrl+shift + (0-9)  for a corresponding text in the clipboard.

My use case here is: I am pasting three different texts over and over, so I'd remember which one is which and it would save some steps. What do you think?

**Comment by pacid** [comment]
![image](https://user-images.githubusercontent.com/1618052/73072721-a3683000-3ead-11ea-886e-db4a83eb258e.png)
Someone described it for another tool.

**Comment by majkinetor** [comment]
That is very nice idea, and it totally fits my workflow. I use a lot first 10 items, but they are not on the main tab. So any hotkey will have to take tab into option.

**Comment by hluk** [comment]
> Configure the global hotkeys which, in case they are pressed with number key (0-9) just paste the text. So I could have for instance ctrl+shift + (0-9) for a corresponding text in the clipboard.

You can make that work with following command ([here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)).

```ini
[Command]
Command="
    copyq:
    var n = str(data(mimeShortcut)).slice(-1)
    select(n)"
GlobalShortcut=ctrl+shift+0, ctrl+shift+1, ctrl+shift+2, ctrl+shift+3, ctrl+shift+4, ctrl+shift+5, ctrl+shift+6, ctrl+shift+7, ctrl+shift+8, ctrl+shift+9
Icon=\xf0cb
IsGlobalShortcut=true
Name=Select Nth Item
```

The behavior depends on current settings in the History config tab in Preferences dialog.

![image](https://user-images.githubusercontent.com/38054/73118046-c0087480-3f4e-11ea-8ba6-830aa5b7bc9c.png)

**Comment by majkinetor** [comment]
CopyQ rocks as always. Thx @hluk

**Comment by pacid** [comment]
Like that? 
![image](https://user-images.githubusercontent.com/1618052/73118315-6140fc00-3f4a-11ea-91db-0cfc9dd02a99.png)
It does not seem to work. I even removed the Icon code since it was giving the syntax error.

**Comment by pacid** [comment]
Awesome, I'd just add to it paste() at the end like that:

`[Command]
Command="
    copyq:
    var n = str(data(mimeShortcut)).slice(-1)
    select(n)
    paste()"
GlobalShortcut=ctrl+shift+0, ctrl+shift+1, ctrl+shift+2, ctrl+shift+3, ctrl+shift+4, ctrl+shift+5, ctrl+shift+6, ctrl+shift+7, ctrl+shift+8, ctrl+shift+9
Icon=\xf0cb
IsGlobalShortcut=true
Name=Select and Paste Nth Item`

**Comment by pacid** [comment]
![image](https://user-images.githubusercontent.com/1618052/73118578-dcf07800-3f4d-11ea-8907-5413c8cf6579.png)

**Comment by majkinetor** [comment]
@DrZanuff , that doesn't make any sense really.

**Comment by majkinetor** [comment]
Ah, ok, sorry :) Thx for sharing indeed :)

**Comment by kayanco** [comment]
Hi,
What command can I add to this code to paste as **plain text**? 

> I have a problem with this code. Pretend I have two itens in clipboard history like that:
> 
>     1. "Hello"
> 
>     2. "World"
> 
> 
> When I press Ctrl+1 it will paste "World", but my item order will change to:
> 
>     1. "World"
> 
>     2. "Hello"
> 
> 
> If I press Ctrl+1 again it will paste now hello. I don't want this behavior, I want it to always mantain the original item order. This is how i fixed for my needs:
> 
> ```
> copyq:
> var n = str(data(mimeShortcut)).slice(-1)
> var item = getitem(n-1)
> copy(item)
> paste()
> ```
