### ISSUE TITLE
MS Defender blocks download?

### ISSUE THREAD

**Issue by Clemens-Ratte-Polle** [hluk/CopyQ#2462]
Microsoft Defender blocks downloading V 7.1.0.
With some work you can download it, but its disgusting.
There is a warning: CopyQ will not be downloaded too often. o_O
I had to declare CQ as secure.
Then i send a feedback to MS that the page is secure.
![2023-09-14_140723 Screenshot](https://github.com/hluk/CopyQ/assets/10136291/4fc61ba2-1f1b-4729-9a1b-106102203f30)
![2023-09-14_140823 Screenshot](https://github.com/hluk/CopyQ/assets/10136291/9ac2fc00-461b-4969-be78-8f7d7e714c5b)
![2023-09-14_140735 Screenshot](https://github.com/hluk/CopyQ/assets/10136291/62f85ed7-b0b2-48b7-a8df-b69a06fcc576)

**Comment by hluk** [comment]
> There is a warning: CopyQ will not be downloaded too often.

Not sure what that means. I assume there is a generic message in the web browser for any `.exe` file.

**Comment by Clemens-Ratte-Polle** [comment]
no, only for CopyQ Download MS Defender warns me.
