### ISSUE TITLE
image display wrong

### ISSUE THREAD

**Issue by Cirn09** [hluk/CopyQ#2466]
**Describe the bug**
here it is:
![image](https://github.com/hluk/CopyQ/assets/25722111/0b0d1bc7-d2e6-4742-94b5-2e9431a4f8e0)

- Red: Image resize failed.
- Orange: No image content

**To Reproduce**
- No image content: Copy image on twitter, Edge browser.
- Resize: copy image from QQ (a Chinese IM software)

**Comment by hluk** [comment]
This is not a bug. CopyQ no longer fetches any remove content and does not make any network requests by default.

CopyQ will only show the images if an image format is available in the item/clipboard.

**Comment by hluk** [comment]
See also: #2084
