### ISSUE TITLE
Program ignore autostart option

### ISSUE THREAD

**Issue by maxtar** [hluk/CopyQ#2468]
**Describe the bug**
Application started when check box clear.

**To Reproduce**
1. Open preferences.
2. Go to `Common` settings.
3. Uncheck `autostart` checkbox.
4. Save settings.
5. Restart system.
6. CopyQ started after reboot.

**Expected behavior**
CopyQ doesn't start.

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Application Version 7.1.0
 - OS Kubuntu 23.04
 - KDE

**Comment by hluk** [comment]
Can you share content of `~/.config/autostart/copyq.desktop` file? Anything in the logs (F12 shortcut from the main window)?

**Comment by maxtar** [comment]
> Can you share content of `~/.config/autostart/copyq.desktop` file? Anything in the logs (F12 shortcut from the main window)?

This file doesn't exist.
Log:
```
Warning [2023-09-17 22:34:22.816] <Server-42704>: Editor command error: execve: No such file or directory
Warning [2023-09-17 22:34:48.915] <Server-42704>: Editor command error: execve: No such file or directory
Warning [2023-09-17 22:34:59.633] <Server-42704>: Editor command error: execve: No such file or directory
Warning [2023-09-17 22:35:57.489] <Server-42704>: Editor command error: execve: No such file or directory
Warning [2023-09-18 19:01:49.129] <Server-2054>: Сервер CopyQ уже запущен.
Warning [2023-09-18 19:01:52.104] <monitorClipboard-2062>: ELAPSED 735 ms accessing "text/plain"
Warning [2023-09-18 19:01:52.107] <monitorClipboard-2062>: ELAPSED 737 ms accessing "UTF8:text/plain"
Warning [2023-09-19 22:32:35.359] <Server-1942>: Server CopyQ already started
Warning [2023-09-19 22:49:24.957] <Server-1925>: Server CopyQ already started
Warning [2023-09-19 22:49:26.810] <monitorClipboard-1932>: ELAPSED 650 ms accessing "imageData"
Warning [2023-09-19 22:51:34.912] <Server-1893>: Server CopyQ already started
Warning [2023-09-19 22:51:36.879] <monitorClipboard-1904>: ELAPSED 673 ms accessing "imageData"
Warning [2023-09-22 23:21:11.856] <Server-1945>: Server CopyQ already started
Warning [2023-09-22 23:27:39.724] <Server-1889>: Server CopyQ already started
```

**Comment by hluk** [comment]
Try disabling the Autostart option clicking Apply button in the Preferences dialog then enable it again, click OK and check the logs. It should contain some error describing why it did not create the file.

**Comment by maxtar** [comment]
> Try disabling the Autostart option clicking Apply button in the Preferences dialog then enable it again, click OK and check the logs. It should contain some error describing why it did not create the file.

Autostart is disabled. But I tried switched it on/off and press Apply button. Log didn't react to these actions.

**Comment by hluk** [comment]
This depends on the current desktop environment and where it stores the autostart scripts.

You can try finding `copyq` in the existing autostart directories:

```
grep -R copyq ~/.config/autostart /etc/xdg/autostart /usr/share/autostart
```

**Comment by hluk** [comment]
BTW, CopyQ only handles autostart via the ` ~/.config/autostart/copyq.desktop` file. Toggling the autostart option would normally create the file and set `Hidden=false` if the autostart is disabled again which means the app should not start by itself.

I think the app could be still stated from other file created from desktop environment settings or from some script.

**Comment by maxtar** [comment]
I'm just used your instruction for ubuntu:

```shell
sudo add-apt-repository ppa:hluk/copyq
sudo apt update
sudo apt install copyq
```

**Comment by hluk** [comment]
After the installation the app should not be autostarted - it still needs to be set in Preferences or in the desktop environment (or by other manual means).

Another idea is that desktop environments can store current **session** and after login/reboot restart the apps running before the last logout. Here is the configuration in KDE/Plasma:
![image](https://github.com/hluk/CopyQ/assets/38054/39b0103e-1186-4f23-a657-9461a97a501f)

You can try putting `copyq` in the "Ignored applications" field.

**Comment by maxtar** [comment]
> After the installation the app should not be autostarted - it still needs to be set in Preferences or in the desktop environment (or by other manual means).
> 
> Another idea is that desktop environments can store current **session** and after login/reboot restart the apps running before the last logout. Here is the configuration in KDE/Plasma: ![image](https://user-images.githubusercontent.com/38054/270745978-39b0103e-1186-4f23-a657-9461a97a501f.png)
> 
> You can try putting `copyq` in the "Ignored applications" field.

Looks like you are right. Problem was in KDE autostart.
