### ISSUE TITLE
copyq stop saving history after huge .dat file in ~/.config/copyq

### ISSUE THREAD

**Issue by trappedinspacetime** [hluk/CopyQ#248]
Hi,

I have been using copyq for a year. Today when I rebooted I noticed that copyq history is empty in notification area. Then I renamed folder in ~/.config/copyq to ~/.config/copyq.old it started working again.
My question now how can open my old history .dat file in  ~/.config/copyq.old?

Regards

Kenn

**Comment by hluk** [comment]
Closing. If you still have issues please reopen and provide details.
