### ISSUE TITLE
Allow configuring shortcuts to past directly one of the last 10 entries

### ISSUE THREAD

**Issue by lepapareil** [hluk/CopyQ#2492]
**Is your feature request related to a problem? Please describe.**
When I want to paste my third copied entry, I have to :

- press shortcut to open the list
- press keys to navigate to the entry
- press enter to paste

**Describe the solution you'd like**
I want to be able to add custom shortcuts like `ctrl+shift+v+3` to paste directly the third entry of my copyq history, or `ctrl+shift+v+10` for the tenth :)

**Comment by hluk** [comment]
See [Select Nth Item](https://github.com/hluk/copyq-commands/blob/master/Global/README.md#select-nth-item) and [Paste Nth Item](https://github.com/hluk/copyq-commands/blob/master/Global/README.md#paste-nth-item) commands (see [README.md](https://github.com/hluk/copyq-commands/blob/master/README.md) for details on how to add the command).

It's probably much easier to Search/Replace the default shortcuts in an editor before pasting the command code into Commands dialog in CopyQ.
