### ISSUE TITLE
'Paste and Forget' not working

### ISSUE THREAD

**Issue by waseemv** [hluk/CopyQ#2493]
Hi,

I just tried the Command "Paste and Forget" from:
https://github.com/hluk/copyq-commands/blob/master/Application/paste-and-forget.ini

But it doesn't work as intended. It pastes the item, but doesn't remove it. The item just moves to the top (as happens for a normal paste). 

**To Reproduce**
1. Add Command from above link
2. Select any item
3. Press Ctrl+Enter, or right-click item and select "Paste and Forget"
4. Item gets pasted, and moves to top (still in clipboard list)

**Expected behavior**
Item should disappear from clipboard after pasting.

**Version, OS and Environment**
Windows 11
CopyQ 7.1.0

**Comment by TigBuh99** [comment]
I have the same issue running CopyQ on MX Linux! After paste the CopyQ title bar states "<EMPTY> - CopyQ", but the entry remains on the clipboard.

**Comment by TigBuh99** [comment]
Thank you for the clarification. It would be nice if the entry was cleared from the clipboard, but this is a feature request!

**Comment by hluk** [comment]
To remove the selected items you can add `remove.apply(this, items)` line to the end of the command (after `copy('')`).

**Comment by waseemv** [comment]
Nice! Thank you! Anything that CopyQ won't do? 🥇 

Btw just curious, what programming language are these commands?

> To remove the selected items you can add `remove.apply(this, items)` line to the end of the command (after `copy('')`).

**Comment by hluk** [comment]
> Btw just curious, what programming language are these commands?

In short, JavaScript. See: https://copyq.readthedocs.io/en/latest/scripting.html
