### ISSUE TITLE
Removed Item Reappears

### ISSUE THREAD

**Issue by PaltryProgrammer** [hluk/CopyQ#2499]
greetings kind regards
please see attached GIF demonstrate removed item reappears upon subsequent insert attempt ,
thank you kindly

Operating System:  Microsoft Windows 10 Professional (x64) Build 19045.3448 (22H2)

￼
CopyQ
Clipboard Manager
6.3.2

![Remved Item Reappears](https://github.com/hluk/CopyQ/assets/48535920/19a29f8d-9b30-460c-bfe8-a92ff87a532a)

**Comment by hluk** [comment]
From your video, this is expected: Paste Items inserts data/items in system clipboard to the item list.
