### ISSUE TITLE
Trying to Create an Automatic Command That Removes Entries That Are a Single Emoji

### ISSUE THREAD

**Issue by andrewcincotta** [hluk/CopyQ#2512]
I use copyq on macOS and have a RayCast extension where I can search for emojis and paste them quickly. The problem is every time I paste an emoji, it copies it into my clipboard, causing unnecessary clutter. I'm looking to make an automatic command that checks newly added clipboard content for entries that contain only one emoji and nothing else (ex: '🧑🏼‍💻').

Can someone assist me in making this command? Thanks!
Pictures below:
<img width="756" alt="image" src="https://github.com/hluk/CopyQ/assets/116472178/d3b40137-d904-4b46-89d9-e743706cab06">
<img width="1206" alt="image" src="https://github.com/hluk/CopyQ/assets/116472178/674d34af-2713-4841-8d82-6331b8b2caa4">

**Comment by hluk** [comment]
The command below uses [a regular expression](https://stackoverflow.com/a/64007175/454171) to figure out if the text is emoji (make sure you use latest version of the app - CopyQ 7.1.0):

```ini
[Command]
Automatic=true
Command="
    copyq:
    // https://stackoverflow.com/a/64007175/454171
    const regex = /(?:[\\u2700-\\u27bf]|(?:\\ud83c[\\udde6-\\uddff]){2}|[\\ud800-\\udbff][\\udc00-\\udfff]|[\\u0023-\\u0039]\\ufe0f?\\u20e3|\\u3299|\\u3297|\\u303d|\\u3030|\\u24c2|\\ud83c[\\udd70-\\udd71]|\\ud83c[\\udd7e-\\udd7f]|\\ud83c\\udd8e|\\ud83c[\\udd91-\\udd9a]|\\ud83c[\\udde6-\\uddff]|\\ud83c[\\ude01-\\ude02]|\\ud83c\\ude1a|\\ud83c\\ude2f|\\ud83c[\\ude32-\\ude3a]|\\ud83c[\\ude50-\\ude51]|\\u203c|\\u2049|[\\u25aa-\\u25ab]|\\u25b6|\\u25c0|[\\u25fb-\\u25fe]|\\u00a9|\\u00ae|\\u2122|\\u2139|\\ud83c\\udc04|[\\u2600-\\u26FF]|\\u2b05|\\u2b06|\\u2b07|\\u2b1b|\\u2b1c|\\u2b50|\\u2b55|\\u231a|\\u231b|\\u2328|\\u23cf|[\\u23e9-\\u23f3]|[\\u23f8-\\u23fa]|\\ud83c\\udccf|\\u2934|\\u2935|[\\u2190-\\u21ff])/g;

    function isEmoji(format) {
        const text = str(data(format));
        const m = text.match(regex);
        return m && m[0].length === text.length;
    }

    if ( isEmoji(mimeText) || isEmoji(mimeTextUtf8) )
        ignore();"
Icon=\xf05e
Name=Avoid Storing Emoji
```

**Comment by andrewcincotta** [comment]
> The command below uses [a regular expression](https://stackoverflow.com/a/64007175/454171) to figure out if the text is emoji (make sure you use latest version of the app - CopyQ 7.1.0):
> 
> ```ini
> [Command]
> Automatic=true
> Command="
>     copyq:
>     // https://stackoverflow.com/a/64007175/454171
>     const regex = /(?:[\\u2700-\\u27bf]|(?:\\ud83c[\\udde6-\\uddff]){2}|[\\ud800-\\udbff][\\udc00-\\udfff]|[\\u0023-\\u0039]\\ufe0f?\\u20e3|\\u3299|\\u3297|\\u303d|\\u3030|\\u24c2|\\ud83c[\\udd70-\\udd71]|\\ud83c[\\udd7e-\\udd7f]|\\ud83c\\udd8e|\\ud83c[\\udd91-\\udd9a]|\\ud83c[\\udde6-\\uddff]|\\ud83c[\\ude01-\\ude02]|\\ud83c\\ude1a|\\ud83c\\ude2f|\\ud83c[\\ude32-\\ude3a]|\\ud83c[\\ude50-\\ude51]|\\u203c|\\u2049|[\\u25aa-\\u25ab]|\\u25b6|\\u25c0|[\\u25fb-\\u25fe]|\\u00a9|\\u00ae|\\u2122|\\u2139|\\ud83c\\udc04|[\\u2600-\\u26FF]|\\u2b05|\\u2b06|\\u2b07|\\u2b1b|\\u2b1c|\\u2b50|\\u2b55|\\u231a|\\u231b|\\u2328|\\u23cf|[\\u23e9-\\u23f3]|[\\u23f8-\\u23fa]|\\ud83c\\udccf|\\u2934|\\u2935|[\\u2190-\\u21ff])/g;
> 
>     function isEmoji(format) {
>         const text = str(data(format));
>         const m = text.match(regex);
>         return m && m[0].length === text.length;
>     }
> 
>     if ( isEmoji(mimeText) || isEmoji(mimeTextUtf8) )
>         ignore();"
> Icon=\xf05e
> Name=Avoid Storing Emoji
> ```

Your command successfully detects "single emoji" entries, but it doesn't remove them properly. Instead, it results in whatever was in index 1 moving to 0 and the emoji being behind. I can watch it delete the entry through copyq where it deletes the entry but it is then replaced. Maybe add a delay before the command runs as I think the error is coming from the raycast extension I am using.

**Comment by hluk** [comment]
The command above only avoids new "emoji" items to be added from the system clipboard. It will not remove existing items from CopyQ.
