### ISSUE TITLE
Autostart is not working with flatpak install 

### ISSUE THREAD

**Issue by rpete3** [hluk/CopyQ#2517]
Autostart is not working with flatpak install 

**To Reproduce**
1. Go to 'Preferences'
2. Click on 'autostart' checkbox
3. reboot
4. CopyQ does not start automatically and ~/.config/autostart does not have an entry for copyq

**Expected behavior**
CopyQ should start automatically.

**Version, OS and Environment**
 - Application Version 6
 - OS Ubuntu 22.04.3 LTS
 - Desktop environment, Gnome shell 42.9

**Comment by hluk** [comment]
Maybe the reason is that I removed `--filesystem=xdg-config/autostart:create` from the flatpak spec (last year). I think it was because the linter complained: https://github.com/flathub/com.github.hluk.copyq/commit/480fb369f3f08ee0d6373ba66824643431877558

**Comment by hluk** [comment]
> Maybe the reason is that I removed `--filesystem=xdg-config/autostart:create` from the flatpak spec (last year). I think it was because the linter complained: [flathub/com.github.hluk.copyq@480fb36](https://github.com/flathub/com.github.hluk.copyq/commit/480fb369f3f08ee0d6373ba66824643431877558)

Yup, that's the reason. All works if I start the flatpak app with the following command:

```
flatpak run --filesystem=xdg-config/autostart:create com.github.hluk.copyq
```

Let me try to revert the change in the spec file.

**Comment by hluk** [comment]
So the linter still doesn't allow me to use this. I think what it means is that it should not be handled by the application itself: https://github.com/flathub/flatpak-builder-lint/issues/87

**Comment by rpete3** [comment]
> So the linter still doesn't allow me to use this. I think what it means is that it should not be handled by the application itself: [flathub/flatpak-builder-lint#87](https://github.com/flathub/flatpak-builder-lint/issues/87)

So you are telling me we can’t use the preferences in CopyQ to activate autostart? The recommended way is to pass the —filesystem option to create it? That’s not very user friendly.

**Comment by hluk** [comment]
> > So the linter still doesn't allow me to use this. I think what it means is that it should not be handled by the application itself: [flathub/flatpak-builder-lint#87](https://github.com/flathub/flatpak-builder-lint/issues/87)
> 
> So you are telling me we can’t use the preferences in CopyQ to activate autostart? The recommended way is to pass the —filesystem option to create it? That’s not very user friendly.

The recommended way seems to be to configure the autostart in your desktop environment (for example: https://code.whatever.social/questions/64444987/how-can-i-set-a-flatpak-application-to-run-on-startup).

I'm not very familiar with all this, but I cannot now configure the flatpak app to access `~/.config/autostart/` anyway due to the linter not accepting the spec with `--filesystem=xdg-config/autostart:create` before building the flatpak.
