### ISSUE TITLE
[Feature request] Images: Save to file

### ISSUE THREAD

**Issue by orschiro** [hluk/CopyQ#252]
Hi there,

I am not sure if this can be achieved with a custom action.

I frequently wish to save images from CopyQ directly to a file.

Could such a feature be added next to the `Move to clipboard` entry in the context menu?

Thanks for your advice!

**Comment by orschiro** [comment]
@hluk 

I would like to come back to what @babakm2 had asked before. Is there any way that CopyQ could recognise the file format of the stored clipboard content automatically?

![image](https://cloud.githubusercontent.com/assets/170947/6437907/634f0514-c0c4-11e4-8c7b-8054a7d7bf53.png)

**Comment by orschiro** [comment]
And another small question. How can I change the default directory to `/tmp`?

I tried the following which does not work:

```
-  currentpath(Dir().homePath())
+ currentpath(Dir().tempPath())
```

**Comment by hluk** [comment]
Nice find! Seems there was little bug in `currentpath()` function (fixed: 77dd8301dca2337607d10950872c5edcf57ae724). Temporarily you can use `currentpath(Dir().tempPath(), 0)` (second parameter of the function is ignored but it's currently required).

I can create function to find file name suffix for given item format (MIME type) but the functionality is available [only in Qt 5](http://doc.qt.io/qt-5/qmimedatabase.html). Official CopyQ releases (except OS X version) still use Qt 4.

I could move fully to Qt 5 but there are still problems with some window managers and environments -- Qt 5.3 has broken drag'n'drop, new KDE can crash tray applications (I use Qt 5 version of CopyQ myself without any other serious issues).

**Comment by orschiro** [comment]
> Nice find! Seems there was little bug in currentpath() function (fixed: 77dd830). Temporarily you can use currentpath(Dir().tempPath(), 0) (second parameter of the function is ignored but it's currently required).

Thanks for the workaround! I just tested it and it is working properly. 

> I can create function to find file name suffix for given item format (MIME type) but the functionality is available only in Qt 5. Official CopyQ releases (except OS X version) still use Qt 4.

Alright. I will patiently wait for the official Linux release then. :)

Regards,

Robert

**Comment by orschiro** [comment]
Sorry to say, but I think I found another bug. :P 

When using `Save Item As` from the tray icon context menu, I only get one mime-type `plain/text` although the content of the clipboard is an image file:

![image](https://cloud.githubusercontent.com/assets/170947/6457428/ebebcd24-c175-11e4-85d1-7fcdc8993eac.png)

**Comment by hluk** [comment]
I didn't consider getting data from clipboard, the command is only applied to selected items in current tab.

[Here is updated version](https://gist.github.com/hluk/64dae8b25cd21e6141dd).

**Comment by orschiro** [comment]
Perfect, works flawlessly!

Maybe also adding your most recent version to https://github.com/hluk/CopyQ/wiki/Command-Examples ?

**Comment by hluk** [comment]
OK, I've added links to other commands to the end of the wiki page.

**Comment by orschiro** [comment]
@hluk 

A quick question: 

Is it possible to make `png` the default format in the `Save item as...` dialog if it is an image file?

Warmly,

Robert

**Comment by hluk** [comment]
Did you try reordering formats in the `suffices` array? I.e.
```js
   ...
    var suffices = {
      'image/png': 'png',
      'image/svg': 'svg',
   ...
```

**Comment by orschiro** [comment]
Yes, I put `png` on the top but it keeps displaying `tiff` as the first option although tiff is not even part of the suffices:

```
var suffices = {
  'image/png': 'png',
  'image/svg': 'svg',
  'image/jpeg': 'jpg',
  'image/jpg': 'jpg',
  'image/bmp': 'bmp',
  'text/html': 'html',
  'text/plain' : 'txt',
}
```

**Comment by hluk** [comment]
The command doesn't convert image formats so if an item contains only `image/tiff` (you can see formats of selected item with F4 shortcut) `image/png` won't be available.

**Comment by orschiro** [comment]
@hluk 

I was referring to screenshots. They don't even come with `image/tiff`. That's why I don't understand why they are even considered by the Save as dialog:

![image](https://cloud.githubusercontent.com/assets/170947/8272141/0f174120-1838-11e5-9948-52eb28334483.png)

**Comment by hluk** [comment]
Do you perhaps have another command interfering with the saving? Try to type `tiff` in search box in Command dialog to filter commands.

**Comment by orschiro** [comment]
No other interfering command. Try to do the following:

1. Create a screenshot and store it in the clipboard
2. Call the `Save as...` function 

You are not presented with `image/tiff` as the first selected/default option?

**Comment by hluk** [comment]
Are you invoking the command with global shortcut? In that case "Save As..." for clipboard is opened.

You can change filter function in the command so it ignores certain formats.

```js
function filterFormats(format)
{
  return /^[a-z]/.test(format) && !/^application\\/x/.test(format) && format !== "image/tiff"
}
```

**Comment by hluk** [comment]
**Note:** If you invoke the command from CopyQ (from menu or with non-global shortcut), dialog for saving currently selected item is opened. With global/system shortcut, dialog for saving clipboard content is opened.

**Comment by orschiro** [comment]
@hluk 

For better clarity of the issue, I prepared the following screencast:

https://youtu.be/M3OgQpn4f5c

Moreover, I changed the `filterFormats` function as you suggested, but then CopyQ fails as follows:

```
Command “copyq eval -- 
var suffices = {
'image/svg': 'svg',
'image/png': 'png',
'image/jpeg': 'jpg',
'image/jpg': 'jpg',
'image/bmp': 'bmp',
'text/html': 'html',
'text/plain' : 'txt',
}

function hasSuffix(fileName)
{
return /\.[0-9a-zA-z]+$/.test(fileName);
}

function addSuffix(fileName, format)
{
var suffix = suffices[format]
return suffix ? fileName + "." + suffix : fileName
}

function filterFormats(format)
{
return /^[a-z]/.test(format) && !/^application\\/x/.test(format) && format !== "image/tiff"
}

if (selectedtab()) tab(selectedtab())
var row = selectedtab() ? currentitem() : -1
var formats = str(read('?', row))
.split('\n')
.filter(filterFormats)

currentpath(Dir().tempPath())
var defaultFileName = 'untitled'

var keyFormat = 'Format'
var keyFileName = 'File'
var defaultFormat = formats[0]

var result = dialog(
'.title', 'Save Item As...',
'.width', 250,
keyFormat, [defaultFormat].concat(formats),
keyFileName, File(defaultFileName)
) || abort()

var fileName = result[keyFileName]
var format = result[keyFormat]

if (!format || !fileName)
abort()

if (!hasSuffix(fileName))
fileName = addSuffix(fileName, format)

var f = File(fileName)
if (!f.open()) {
popup('Failed to open "' + f.fileName() + '"', f.errorString())
abort()
}

f.write(selectedtab() ? getitem(currentitem())[format] : clipboard(format))
popup("Item Saved", 'Item saved as "' + f.fileName() + '".')”
Exit code: 1
CopyQ client ERROR: Error: Eval:-1:-1: syntax error: 

--- backtrace ---
<anonymous>()@:0
--- end backtrace ---
```

**Comment by hluk** [comment]
Ah, sorry I copied the function incorrectly from `ini` file (`\\` should be just `\`).

Can you test again with `image/png` as the first item in `suffices` with the old command? There is an ugly bug in CopyQ 2.4.7 (I'll have to release fixed version soon) -- sometimes changes in commands are not saved. Please save the changes, close the Command dialog and check again if the changes were saved.

**Comment by orschiro** [comment]
@hluk 

It still doesn't show `image/png` as the default entry. I finally found a solution with this workaround:

```
copyq:
var suffices = {
  'image/svg': 'svg',
  'image/png': 'png',
  'image/jpeg': 'jpg',
  'image/jpg': 'jpg',
  'image/bmp': 'bmp',
  'text/html': 'html',
  'text/plain' : 'txt',
}

function hasSuffix(fileName)
{
  return /\.[0-9a-zA-z]+$/.test(fileName);
}

function addSuffix(fileName, format)
{
  var suffix = suffices[format]
  return suffix ? fileName + "." + suffix : fileName
}

function filterFormats(format)
{
  return /^[a-z]/.test(format) && !/^application\/x/.test(format) 
  && format !== "image/tiff" 
  && format !== "image/jpeg"
  && format !== "image/x-MS-bmp"
  && format !== "image/x-bmp"
  && format !== "image/bmp"
}

if (selectedtab()) tab(selectedtab())
var row = selectedtab() ? currentitem() : -1
var formats = str(read('?', row))
  .split('\n')
  .filter(filterFormats)

currentpath(Dir().tempPath())
var defaultFileName = 'untitled'

var keyFormat = 'Format'
var keyFileName = 'File'
var defaultFormat = formats[0]

var result = dialog(
  '.title', 'Save Item As...',
  '.width', 250,
  keyFormat, [defaultFormat].concat(formats),
  keyFileName, File(defaultFileName)
) || abort()

var fileName = result[keyFileName]
var format = result[keyFormat]

if (!format || !fileName)
  abort()

if (!hasSuffix(fileName))
  fileName = addSuffix(fileName, format)

var f = File(fileName)
if (!f.open()) {
  popup('Failed to open "' + f.fileName() + '"', f.errorString())
  abort()
}

f.write(selectedtab() ? getitem(currentitem())[format] : clipboard(format))
popup("Item Saved", 'Item saved as "' + f.fileName() + '".')
```

**Comment by hluk** [comment]
Sorry, I noticed just now that the command disregards the order of items in the `suffices` (that is really only used for getting file suffix).

I've updated the [gist](https://gist.github.com/hluk/64dae8b25cd21e6141dd) so it reorders formats.

**Comment by orschiro** [comment]
The updated gist works perfectly. Thanks very much!

**Comment by orschiro** [comment]
Dear all, 

I would like to place files into `~/Downloads`.

I tried `currentpath(Dir().homePath()).Dir("Downloads")` but didn't succeed. 

Any advice on how to construct this line?

Thankfully,

~Robert

**Comment by orschiro** [comment]
My apologies. I found the error myself. This line of code works:

    currentpath(Dir().homePath() + "/Downloads")

**Comment by itkind** [comment]
Hi, is it possible to save 100 images at once in 100 files with this command?
