### ISSUE TITLE
ScriptError "TypeError Property 'text' Exit code 4"

### ISSUE THREAD

**Issue by iG8R** [hluk/CopyQ#2520]
**Describe the bug**
When I try to execute script the error " TypeError: Property 'text' Exit code: 4" appears.

**To Reproduce**
1. Apply the following script to a clip that contains a note with a URL.
```
[Command]
Command="
    copyq:
    var url = input().text()
    if ( open(url) )
      popup('Opening URL', url)
    else
      popup('Failed to open URL', url)"
HideWindow=true
Icon=\xf0ac
InMenu=true
Input=application/x-copyq-item-notes
Name=Open in &Browser
```
2. See the aforementioned error.

**Expected behavior**
Opening the URL located in the clip note in the browser.

**Screenshots**

[CopyQ-Open-in-Browser-Video_2023-10-27_073333.webm](https://github.com/hluk/CopyQ/assets/11407417/27501586-b34f-413a-9516-0afaacc6d468)

**Version, OS and Environment**
 - CopyQ 7.1.0
 - OS: Microsoft Windows [Version 10.0.19045.2673] 64bit
 - Browser: Firefox 119.0 64bit
 - Browser: Chrome 118.0.5993.90 (Official Build) (64-bit)
 - Browser: Edge 118.0.2088.69 (Official build) (64-bit)

**Comment by iG8R** [comment]
Changed
`var url = input().text()`
to
`var url = input()`

The error also changed:
`Warning [2023-10-29 01:07:17.030] <Server-18540>: [default] QtWarning: ShellExecute 'https://github.com/hluk/CopyQ/issues/2084%00' failed (error 2).`

But if I explicitly insert URL into the code, like this
`var url = 'https://github.com/hluk/CopyQ/issues/2084'`
then this URL opens in the browser without any problems.

**Comment by iG8R** [comment]
Through trial and error, it was found that if the link is opened in this format
`var url = 'https://github.com/hluk/CopyQ/issues/2084'`
then everything works as it should, i.e. the browser page opens with this link.

But in this case
`var url = 'https://github.com/hluk/CopyQ/issues/2084%00'`
gives an error
`Warning [2023-10-29 03:00:10.915] <Server-18540>: [default] QtWarning: ShellExecute 'https://github.com/hluk/CopyQ/issues/2084%00' failed (error 2).`

So, in some incomprehensible way, `%00` is added to the link at the end.

**Comment by iG8R** [comment]
@hluk 
Hi.
I want to clarify the situation from the very beginning.
There are 2 scripts taken from the following topic "Bug or feature ?" #1100
1. **Add URL label & Add URL label (Edge)** https://github.com/hluk/CopyQ/issues/1100#issuecomment-468362174
<details><summary>Add URL label & Add URL label (Edge)  (click to open)</summary>

```
[Commands]
1\Automatic=true
1\Command="
    copyq:
    removeData('text/x-moz-url-priv')
    setData(mimeItemNotes, input())"
1\Icon=\xf15b
1\Input=text/x-moz-url-priv
1\Name=Add URL label
2\Automatic=true
2\Command="
    copyq:
    removeData('application/x-qt-windows-mime;value=\"msSourceUrl\"')
    setData(mimeItemNotes, input())"
2\Icon=\xf15b
2\Input="application/x-qt-windows-mime;value=\"msSourceUrl\""
2\Name=Add URL label (Edge)
size=2
```
</details>

2. **Open in &Browser** https://github.com/hluk/CopyQ/issues/1100#issuecomment-469981581
<details><summary>Open in &Browser (click to open)</summary>

```
[Command]
Command="
    copyq:
    var url = input().text()
    if ( open(url) )
      popup('Opening URL', url)
    else
      popup('Failed to open URL', url)"
HideWindow=true
Icon=\xf0ac
InMenu=true
Input=application/x-copyq-item-notes
Name=Open in &Browser
```
</details>


So, for some unknown reason, the script **Add URL label & Add URL label (Edge)** adds `%00` at the end of the URL when adding it to the mimeItemNotes of the clip.
I found a solution - before saving to mimeItemNotes, use the `chop(1)` command to remove this last character before saving.

```
[Command]
Name=Add URL label
Command="
    copyq:
    removeData('text/x-moz-url-priv')
    var url = input()
    url.chop(1)
    setData(mimeItemNotes, url)"
Input=text/x-moz-url-priv
Automatic=true
Icon=\xf15b
```
But most likely there is some bug in CopyQ, which is causing such behavior. Therefore, it would be better if the error itself is fixed, rather than using such workarounds.

**Comment by hluk** [comment]
> Changed
> `var url = input().text()`
> to
> `var url = input()`

There is no attribute `text` for `ByteArray` (the return type of `input()`). Your fixed code looks OK.

> But in this case `var url = 'https://github.com/hluk/CopyQ/issues/2084%00'` gives an error `Warning [2023-10-29 03:00:10.915] <Server-18540>: [default] QtWarning: ShellExecute 'https://github.com/hluk/CopyQ/issues/2084%00' failed (error 2).`
> 
> So, in some incomprehensible way, `%00` is added to the link at the end.

It looks like the original data contains trailing null character. I can reproduce this from shell:

```bash
# Web browser opens: https://github.com/hluk/CopyQ/issues/2520%00
❯ printf "%s\0" "https://github.com/hluk/CopyQ/issues/2520" | copyq 'open(input())'
true

# ByteArray with null character converted to string still contains the null (bellow is the hexadecimal representation of the string)
❯ printf "HELLO\0" | copyq 'str(input())' | xxd
00000000: 4845 4c4c 4f00 0a                        HELLO..

# Here is the input without null
❯ printf "HELLO" | copyq 'str(input())' | xxd
00000000: 4845 4c4c 4f0a                           HELLO.
```

It seems that the following works well, provided the input is in Latin1 encoding (the standard ISO 8859-1 character set):

```js
var url = input().toLatin1String()
```

The question is why the item note contains the null character. I assume that the clipboard content might have been misinterpreted by CopyQ or the underlying Qt framework (which handles most of the clipboard data transformations/representation).

Which app did you copy the URL from?

**Comment by iG8R** [comment]
I didn't copy the URLs themselves, I copied the texts from the aforementioned Firefox, Edge and Chrome and after that "Add URL label & Add URL label (Edge)" did all the rest of the work on adding URLs to the "Note" fields of the clips.

**Comment by hluk** [comment]
I cannot reproduce the trailing null character when copying from Firefox. I think this could be a problem in the source application. Probably not worth adding a workaround in CopyQ for this.

**Comment by hluk** [comment]
Let me know if you can reproduce it (and how) when copying from the source app. I would prefer to have a proper fix in CopyQ if that will be possible.

**Comment by iG8R** [comment]
Here is the most common process of copying text in Firefox:

[CopyQ-Copying-NULL-Video_2023-10-31_162525.webm](https://github.com/hluk/CopyQ/assets/11407417/55fb3fcf-579e-4133-a4cc-9429f7ec14b8)

**Comment by hluk** [comment]
Oh, the item notes with URL are created automatically with a command. Can you share the command code here with "Copy Selected" button?

BTW, thanks for posting the screencasts - very useful!

**Comment by hluk** [comment]
I mean this process: https://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them

> To share your commands, you can select the commands from command list in “Commands” dialog and press “Copy Selected” button (or just hit Ctrl+C).

And paste the command into a comment in this issue.

**Comment by iG8R** [comment]
Oh, I see.
This is what works in Firefox, but not in Edge and Chrome.
```
[Command]
Name=Add URL label
Command="
    copyq:
    removeData('text/x-moz-url-priv')
    var url = input()
    url.chop(1)
    setData(mimeItemNotes, url)"
Input=text/x-moz-url-priv
Automatic=true
Icon=\xf15b
```

This one, which supposed to work in Edge and Chrome, doesn't work in either of them.
```
[Command]
Name=Add URL label (Edge)
Command="
    copyq:
    removeData('application/x-qt-windows-mime;value=\"msSourceUrl\"')
    setData(mimeItemNotes, input())"
Input="application/x-qt-windows-mime;value=\"msSourceUrl\""
Automatic=true
Icon=\xf15b
```

PS. Please take a look at my screencast on the more troubling issue of not being able to copy images from browsers.
https://github.com/hluk/CopyQ/issues/2084#issuecomment-1782298258

**Comment by iG8R** [comment]
It seems, this command doesn't work in Windows.

![image](https://github.com/hluk/CopyQ/assets/11407417/202edcae-244d-4ed5-8be0-5d70bc522a0a)

Regarding trailing NULL in URLs

![image](https://github.com/hluk/CopyQ/assets/11407417/094d6d9d-59b1-4e18-91f9-dc715950cc0a)

As you can see, the trailing NULL character appears before the URL is recorded into Note. (`application/x-copyq-item-notes`)

PS. I apologize, but I didn't quite understand what was meant by
`You can check the formats by copying from the web browser and opening Clipboard Content dialog in CopyQ (Ctrl+Shift+C).`
I have the following information displayed in this window.

[CopyQ-Clipboard-Contnet-formats-Video_2023-11-01_182429.webm](https://github.com/hluk/CopyQ/assets/11407417/f0345983-be24-41b9-897d-061c86245f47)

**Comment by hluk** [comment]
> It seems, this command doesn't work in Windows.

The console output on Windows does not work for GUI apps unfortunately (#349).

You can use the Action dialog (F5 shortcut) in CopyQ instead with "Store standard output" set to "text/plain" to store the command output to new item.

> PS. I apologize, but I didn't quite understand what was meant by `You can check the formats by copying from the web browser and opening Clipboard Content dialog in CopyQ (Ctrl+Shift+C).`

More specifically: Use the Clipboard Content to figure out the format name containing URL for the current system clipboard content visible by CopyQ. It should list `text/x-moz-url-priv` for stuff copied from web pages in Firefox.

**Comment by iG8R** [comment]
[CopyQ-Notes-issue-Video_2023-11-03_014635_part1.webm](https://github.com/hluk/CopyQ/assets/11407417/e5b1d1ac-f164-4e2c-b283-c8941488847d)

[CopyQ-Notes-issue-Video_2023-11-03_014635_part2.webm](https://github.com/hluk/CopyQ/assets/11407417/db72ca82-a623-433c-8443-a2a3502f6a39)
