### ISSUE TITLE
Add mouse shortcuts besides keyboard ones

### ISSUE THREAD

**Issue by iG8R** [hluk/CopyQ#2522]
**Is your feature request related to a problem? Please describe.**
Please, add a possibility to use mouse buttons as shortcuts, for example, long click on the middle (wheel) button could be used to "Show main window under mouse cursor".

To date, mice are not limited to 3 buttons, there are those that have up to 19 of them, and the number of combinations reaches up to 40. Of course, you can assign a specific keyboard shortcut to certain actions in CopyQ, and then use the mouse software to assign them to its buttons. But through keyboard shortcuts it is impossible to assign the duration of key presses, but the duration of mouse button presses can be registered, and therefore it will be much more convenient when you can assign 2 actions to one mouse button, for example, a long press of the middle button will perform "Show main window under mouse cursor", and a short click will perform "Show/hide main window".

**Comment by hluk** [comment]
This is probably not going to happen. Implementing this for the supported platforms would be hard (probably not possible for the one I use - Linux/Wayland).

**Comment by theorist-complex** [comment]
Any chance this stance has been updated or changed any in the last couple years? 

Moving from Arsclip on w10 to CopyQ on w11 and really missing the mouse options to show main window. 

Thanks!

**Comment by theorist-complex** [comment]
> This is probably not going to happen. Implementing this for the supported platforms would be hard (probably not possible for the one I use - Linux/Wayland).

Any chance this stance has been updated or changed any in the last couple years?

Moving from Arsclip on w10 to CopyQ on w11 and really missing the mouse options to show main window.

Thanks!
