### ISSUE TITLE
Pasting plain text with embedded URLs from the richtext/html format of this text

### ISSUE THREAD

**Issue by iG8R** [hluk/CopyQ#2527]
**Is your feature request related to a problem? Please describe.**
Very often, when we copy texts from web pages and paste them into applications or forms that don't support pasting texts with richtext/html formatting, we encounter a problem of missing a very important part of these texts - URLs, because usually the overwhelming majority of URLs on any web page are hidden under text descriptions and images.

Is there any way to make CopyQ paste texts in plain format that was previously copied from sources in richtext/html format (browsers, Word, etc.), so that they also include URLs (hidden under the text description and images) presented in these copied texts?

**Describe the solution you'd like**
I found a pretty simple UserScript on the internet (https://superuser.com/questions/501603/copy-selected-text-with-links-appended-in-plain-text) that transforms all "hidden" URLs under a text descriptions into an explicit form. It can be used to process any copied texts that contain in addition to plain format also HTML format.

It would be great if:
- besides URLs under texts, CopyQ would also process URLs under images and include them in plain text
- the format of the inserted text:URL pair could be customizable, i.e.` text (URL)`, or `{text | URL}`, or `[image | URL]` , or any other format.

UserScript:
```
// ==UserScript==
// @name        Transform All Links
// @namespace   myscripts
// @description Transforms <a=href>link</a> to { link | <a=href>href</a> }
// @match      *://*/*
// @include    *
// @version     1
// @grant       none
// ==/UserScript==
try{
    transformAnchors();
}catch(err){
    alert("error#" + err.number + " name: " + err.name + "\n"
        + "message: " + err.message + "\n"
        + "description: " + err.description);
    var errmsg = "";
    for (atr in err) {
        errmsg = errmsg + atr + " = " + err[atr] + "<br>\n";
    }
    alert(errmsg);
}

function transformAnchors() {
    //get every anchor node
    var anchornodes = document.getElementsByTagName("A");
    //transform every anchor
    for (var i=0; i<anchornodes.length; ++i){
        //grab the current anchor node
        anchornode = anchornodes[i];
        //ignore erroneous nodes with no parent
        if (anchornode.parentNode == undefined || anchornode.parentNode == null) continue;
        //add text sibling before anchor node : { <a=href>link</a>
//        anchornode.parentNode.insertBefore(document.createTextNode("{ "),anchornode);
//        anchornode.parentNode.insertBefore(document.createTextNode(""),anchornode);
        //create styled anchor node to preserve styling
        styledanchornode = document.createElement("A");
        styledanchornode.setAttribute("class",anchornode.getAttribute("class"));
        styledanchornode.setAttribute("style",anchornode.getAttribute("style"));
        styledanchornode.setAttribute("title",anchornode.getAttribute("title"));
        //put styled anchor node before anchor node
        anchornode.parentNode.insertBefore(styledanchornode,anchornode);
        //move all anchor node children to before anchor node inside styled anchor node : { link <a=href></a>
        while (anchornode.hasChildNodes()){
            styledanchornode.appendChild(anchornode.childNodes[0]);
        }
        //remove styling from anchor node
        anchornode.removeAttribute("style");
        anchornode.removeAttribute("class");
        anchornode.removeAttribute("title");
        //add text sibling before anchor node : { link | <a=href></a>
        anchornode.parentNode.insertBefore(document.createTextNode(" ("),anchornode);
        //add href text child inside anchor node : { link | <a=href>href</a>
        anchornode.appendChild(document.createTextNode(anchornode.href));
        //add text sibling after anchor node : { link | <a=href>href</a> }
        anchornode.parentNode.insertBefore(document.createTextNode(") "),anchornode.nextSibling);
        //increment index to compensate for extra styled anchor node
        ++i
    }
}
```

**Additional context**

[Copy-text-with-links-Video_2023-10-29_210841.webm](https://github.com/hluk/CopyQ/assets/11407417/327ab93b-aa77-4a0e-96a1-4f2af80ad864)

**Comment by hluk** [comment]
This is out of scope for the clipboard manager but it is possible to use another utility (like [Pandoc](https://pandoc.org/)) to convert HTML to a different format.
