### ISSUE TITLE
How to keep the window name of CopyQ unchanged?

### ISSUE THREAD

**Issue by FanNengHu** [hluk/CopyQ#2535]
CopyQ's window name changes with the copied content, such as 'abc-copyQ' or 'bcd-copyq.' 
Is it possible to keep the window name constant? So that the window name always displays 'copyq.' 
I'm not sure if there's an option for that

**Comment by hluk** [comment]
Use [No Clipboard in Title and Tool Tip](https://github.com/hluk/copyq-commands/tree/master/Scripts#no-clipboard-in-title-and-tool-tip) command ([here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)).
