### ISSUE TITLE
J S O N style format for configuration file

### ISSUE THREAD

**Issue by mjoe67886** [hluk/CopyQ#2538]
**Is your feature request related to a problem? Please describe.**
what would be cool is if when I saved my export file if you know it was organized like AJSON to where I could just grab you know those tabs in JSON format and paste it into GPT and say organize all my python snippets and add headers and GPT would organize all my python code based on you know whether it fits you know related to creating file paths or related to you know dictionaries or you know just based on what kind of code it is if you had your export file laid out in JSON format that would give the end user a lot of options as far as you know very quickly with GPT making their making your user interface as far as how they've saved all their tabs and and code snippets look however they want and just like one click....with gpt..... As it is now it looks very dirty and disorganized.... Keeping in mind that i think this is like the greatest creation your software I mean that's ever been created for computers ever.......And I run into needing this so many times in your seriously awesome software which I thank you for but um having the option to right click inside of a tab and choose paste from the context menu would be a major efficiency booster and maybe copy if that's not there...
**Describe the solution you'd like**
The export settings being exported in JSON format and cut copy and paste added to a right click menu for tabs...

**Describe alternatives you've considered**
I'm open to ideas I think mine are good but if you've already implemented a better solution that I'm not aware of please let me know

**Additional context**
As it is the best implementation of a clipboard software that I've ever thought of or could imagine I'm dedicated to supporting it and helping it improve with my feature requests when I discover anywhere it could improve

**Comment by hluk** [comment]
I'm not going to add this to the app itself. The Qt framework that the app uses, supports INI files out-of-the-box.

Commands in CopyQ could probably help exporting and importing the configuration as JSON file (or some app that supports INI to JSON and vice versa conversions).

**Comment by mjoe67886** [comment]
and you said commands in copyQ could probably help exporting and importing the configuration as a J S O N file which commands were you talking about??

**Comment by hluk** [comment]
See the documentation: https://copyq.readthedocs.io/en/latest/writing-commands-and-adding-functionality.html
