### ISSUE TITLE
CopyQ : weird process?

### ISSUE THREAD

**Issue by Clemens-Ratte-Polle** [hluk/CopyQ#2539]
CopyQ 7.1
In Windows Process Manager some additional suspicious CopyQ process wears not its name but of the last copied item.
This happens some time when CopyQ runs wild in RAM usage.
Is this an error?
This irritates too often when sorting all processes for name.
Perhaps its name should always stand at the first position ?
thx

**Comment by hluk** [comment]
Not sure about the naming of the processes on Windows, but CopyQ has couple of [processes](https://copyq.readthedocs.io/en/latest/source-code-overview.html#application-processes) (described below with command line):
- main server `copyq` usually without parameters
- clipboard monitor: `copyq --clipboard-access monitorClipboard`
- context/tray menu command filters: `copyq eval -- runMenuCommandFilters()`
- transforming items data to display (if any "Display" commands are defined): `copyq eval -- runDisplayCommands()`
