### ISSUE TITLE
Causes abnormal playback of videos on web pages

### ISSUE THREAD

**Issue by LeiSangSang** [hluk/CopyQ#2540]
When copyq is running, bilibili's video player will experience abnormalities.
Specifically, you need to click the mouse once in the player area to operate the player normally.
When the player is not "activated", the mouse cursor is also invisible in this area
After closing copyq everything returns to normal
There is no such problem in edge browser.

https://www.bilibili.com

**Version, OS and Environment**
 - Application Version 7.1.0
 - Windows11
 - Chrome 119.0.6045.124

**Comment by hluk** [comment]
I have no idea how CopyQ could affect a media player, unless the player app does something with the system clipboard.

Any errors or warnings in CopyQ logs? To view logs press F12 in main window or select "Show Log" from Help menu.

Do you have any custom commands in Command dialog (F6 shortcut)?

**Comment by LeiSangSang** [comment]
Thank you for your reply. This problem seems to have disappeared after the recent Chrome update.
