### ISSUE TITLE
Paste not working with Hyprland (wayland support script enabled)

### ISSUE THREAD

**Issue by Gufderald** [hluk/CopyQ#2557]
Before creating a new issue, see list of [known
issues](https://copyq.readthedocs.io/en/latest/known-issues.html).
> This issue is in list of known issues; however, I will start an issue here as there may be a workaround for this behaviour

**Describe the bug**
I'm creating this issue to continue discussion in https://github.com/hluk/CopyQ/issues/27, as it's closed.

I'm running Arch with Hyprland compositor. After enabling [wayland support script](https://github.com/hluk/copyq-commands/tree/master/Scripts#wayland-support) everything runs smooth, except paste behavior ONLY in terminal emulators - instead of the clipboard content, it inserts something else. It seems to be related to the paste shortcut, which [wayland support script](https://github.com/hluk/copyq-commands/tree/master/Scripts#wayland-support) sends and which seems to be Shift+Insert. As it is not paste shortcut by default in most terminal emulators - the issue occurs.

**To Reproduce**
1. Use Hyprland and [wayland support script](https://github.com/hluk/copyq-commands/tree/master/Scripts#wayland-support)
2. Try to paste smth from clipboard to your terminal emulator using enter on the copyq window.

**Expected behavior**
Insert selected clipboard entry to the terminal

**Version, OS and Environment**
CopyQ Clipboard Manager 7.1.0
Qt: 5.15.10
KNotifications: 5.110.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Arch Linux
**!** Hyprland, wayland support script enabled

**Comment by Gufderald** [comment]
For now I found a workaround - mapping Shft+Insert chord to a paste action - it works for gnome terminal at least.

**Comment by Gufderald** [comment]
```yaml
  - { key: Insert,         mods: Shift,                           action: Paste            }
```
For alacritty this line should be set instead of `PasteSelection` action

**Comment by Gufderald** [comment]
Created another issue in https://github.com/hluk/copyq-commands; created [MR with edited README for wayland support script.](https://github.com/hluk/copyq-commands/pull/87).

**Comment by gowallasnewpony** [comment]
would this eventually help?:
https://github.com/hluk/CopyQ/issues/633

**Comment by hluk** [comment]
I picked Shift+Insert because it actually is the default shortcut for pasting (clipboard or selection) in most terminal emulators and applications.

You can try modifying the [paste()](https://github.com/hluk/copyq-commands/blob/79286a1b07a7479c73b84f1013d841e4242c05c7/Scripts/wayland-support.ini#L90-L92) function to send Ctrl+Shift+V for pasting:

```js
    global.paste = function() {
        sendShortcut('42:1', '29:1', '47:1', '47:0', '29:0', '42:0')
    }
```

**Comment by Gufderald** [comment]
> would this eventually help?: #633

Thanks, I'll give it a try.

**Comment by Gufderald** [comment]
> I picked Shift+Insert because it actually is the default shortcut for pasting (clipboard or selection) in most terminal emulators and applications.
> 
> You can try modifying the [paste()](https://github.com/hluk/copyq-commands/blob/79286a1b07a7479c73b84f1013d841e4242c05c7/Scripts/wayland-support.ini#L90-L92) function to send Ctrl+Shift+V for pasting:
> 
> ```js
>     global.paste = function() {
>         sendShortcut('42:1', '29:1', '47:1', '47:0', '29:0', '42:0')
>     }
> ```

Thanks! However, changing shortcut to Ctrl+Shift+V will break paste actions for most applications.

**Comment by hluk** [comment]
> However, changing shortcut to Ctrl+Shift+V will break paste actions for most applications.

Yeah, I thought it might be the case (I only tested it in Firefox and kitty terminal emulator).

Alternate solution would be to check the current window title before triggering the paste:

```js
global.paste = function() {
    const window = currentWindowTitle();
    if (window == 'Alacritty') {
        // Shift+Ctrl+V
        sendShortcut('42:1', '29:1', '47:1', '47:0', '29:0', '42:0');
    } else {
        // Shift+Insert
        sendShortcut('42:1', '110:1', '110:0', '42:0');
    }
}
```

**Comment by Gufderald** [comment]
Hi! My mr to docs for scripts was merged, so I suppose this may be closed. I tested sollutions from @gowallasnewpony and @hluk - they both works fine as a workaround too, thanks a lot.
