### ISSUE TITLE
Shift + V get's remembered as shortcut, even after re-installs.

### ISSUE THREAD

**Issue by feikescholtens** [hluk/CopyQ#2559]
Before creating a new issue, see list of [known
issues](https://copyq.readthedocs.io/en/latest/known-issues.html).

**Describe the bug**
Some time ago I configured Shift + V for opening CopyQ. Of course a stupid shortcut, because I do still want to be able to type capital v's. After removing the shortcut however, it still works. I did many reboots, fully reinstalled CopyQ (I also manually deleted every file related to CopyQ inbetween re-installs) but the shortcut STILL works. I also reset my settins via the Preferences window.
After I uninstall CopyQ and press Shift + v, I get the following error: ![PXL_20231129_123531121](https://github.com/hluk/CopyQ/assets/71907413/1259ea42-e69d-4c7c-8133-fc186635625e). Then when I reboot the error doens't show anymore and I can type capital v's again! But everytime I reintall copyQ it picks up this shortcut again :(. So it has something to do with CopyQ re-enabling this shortcut everytime it get's installed. 

**Version, OS and Environment**
CopyQ Clipboard Manager 6.0.1
Qt: 5.15.2
KNotifications: 5.89.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Ubuntu 22.04.3 LTS

**Comment by hluk** [comment]
This is not a bug. Uninstalling or reinstalling apps on Linux distros usually does not remove/reset user configuration.

You can remove all the configuration by removing the config directory from terminal:

```bash
rm -rf ~/.config/copyq
```

Or remove the shortcut from CopyQ itself - either Preferences or Commands dialog (F6 shortcut).
