### ISSUE TITLE
No Icon displayed inSystray

### ISSUE THREAD

**Issue by bungoo33** [hluk/CopyQ#256]
Application works fine but there is just a blank space where the icon should be. 
OS Ubuntu 14.04 using Openbox and tint2.

**Comment by giannino** [comment]
same problem with 19.04
/usr/share/icons/hicolor/scalable/apps/copyq-normal.svg does not exists

**Comment by hluk** [comment]
@giannino It should use `/usr/share/icons/hicolor/scalable/apps/copyq.svg` now. If you use Gnome, try installing [TopIcons Plus](https://extensions.gnome.org/extension/1031/topicons/) extension.

**Comment by giannino** [comment]
The file is there, and the icon also but it's minuscule!

![image](https://user-images.githubusercontent.com/13005325/57274262-081ef880-709b-11e9-81d4-d307a0f680e8.png)

**Comment by hluk** [comment]
@giannino That looks like an issue with a Gnome extension.
