### ISSUE TITLE
Support filtering items based on text and images.

### ISSUE THREAD

**Issue by Achuan-2** [hluk/CopyQ#2572]
Just like the clipboard plugin in utools.
![image](https://github.com/hluk/CopyQ/assets/60436214/88fe6c07-d5d7-4836-9b3d-5815533290de)

![image](https://github.com/hluk/CopyQ/assets/60436214/a01e39c9-56eb-43a0-9338-0ac9f71e3b16)

**Comment by GFDGIT** [comment]
Take a look at [this](https://github.com/GFDGIT/CopyQ_lazy/blob/main/%E5%91%BD%E4%BB%A4%2F%E7%AD%9B%E9%80%89.ini).

**Comment by Achuan-2** [comment]
@GFDGIT 太强了吧，大佬。筛选图片、文件和能够复制文件，真的大大筛选我对CopyQ的认知了，狠狠star了
