### ISSUE TITLE
Copy formatted text from GSuite to Slack (markdown)

### ISSUE THREAD

**Issue by guettli** [hluk/CopyQ#2595]
**Is your feature request related to a problem? Please describe.**

I want to copy and paste formatted text from GSuite (google docs) to Slack (markdown).

**Describe the solution you'd like**

At the moment the formatting gets lost.

I want a magic conversion from html to markdown.

My formatting is not fancy. All I want is a way to copy hyperlinks: `[text](URL)` in markdown.
And maybe headings.

**Describe alternatives you've considered**

I see no alternative at the moment.

---

Thank you for CopyQ, I use it daily on Linux.

**Comment by paragbaxi** [comment]
➕

**Comment by hluk** [comment]
I don't think this is possible unless the app itself provides the data in clipboard (you can check current clipboard formats in CopyQ via menu File - Show Clipboard Content - Ctrl+Shift+C).
