### ISSUE TITLE
capslock...Q?

### ISSUE THREAD

**Issue by anffna** [hluk/CopyQ#2601]
Hi guys! Could anyone provide a script to show notification when capslock is active, keeping the notification visible until capslock becomes inactive again? I switched to Linux recently, and I didn't find any capslock indicator... Anyway, thank you for your attention...

**Comment by hluk** [comment]
Sorry, this is out of scope for clipboard manager.

**Comment by anffna** [comment]
Hi man! Thanks for the answer!  Thanks again!
