### ISSUE TITLE
Suddenly found that all copied images only display links instead of thumbnails.

### ISSUE THREAD

**Issue by 13706021962** [hluk/CopyQ#2611]
Suddenly found that all copied images only display links instead of thumbnails.
![CopyQ aLvtYy](https://github.com/hluk/CopyQ/assets/40297474/a8276912-d847-4b88-b041-8b0c44cc06dc)
![CopyQ ohdqmC](https://github.com/hluk/CopyQ/assets/40297474/50cc7c25-dddf-4d2b-a627-1a6fbc8638bf)

**Comment by hluk** [comment]
This looks like a duplicate of #2084.
