### ISSUE TITLE
is ctrl+D a Shortcut I don't see it listed in the software preferences 

### ISSUE THREAD

**Issue by mjoe67886** [hluk/CopyQ#2612]
Before creating a new issue, see list of [known
issues](https://copyq.readthedocs.io/en/latest/known-issues.html).

**Describe the bug**
I'm pressing the shortcut on my operating system windows 11 and it keeps opening up the software I haven't said any keyboard shortcuts anywhere with any other software and it's not in preferences I just wanted to make sure you knew and just to get confirmation if that's what's going on if you have a hardcoded shortcut a slight feature request if you do have It hard coded is there any way to make that optional..
**To Reproduce**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**
Hopefully make a possibly hard coded shortcut optional 

**Screenshots**

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Application Version [e.g. 3.7.2]
 - OS [e.g. Windows]
 - Desktop environment, window manager (if applicable)

**Additional context**

**Comment by hluk** [comment]
I don't think Ctrl+D is handled by CopyQ itself, if you do not see it set in the Shortcuts tab in the Preferences dialog (Ctrl+P).

If it is set there, click on the button with the shortcut in the Shortcuts tab, press Remove Shortcut button and apply the configuration.

**Comment by mjoe67886** [comment]
I figured it outy in the software there's two sections where you could set
keyboard shortcuts. I had no idea that the control D shortcut was set in
the 2nd section. Thanks For replying by the way
