### ISSUE TITLE
Open under mouse, but CLI

### ISSUE THREAD

**Issue by cdumange** [hluk/CopyQ#2614]
Hey all,

First of all, been using for a long time. Super software !

Now, my little question. A few years ago was added the "Show main window under mouse cursor" possibility but I can't seem to find it with the cli.

I have more and more trouble to have CopyQ shortcuts working as more software are capturing keyboards. Does not work in terminal, firefox, ...

But, if I add it in custom shortcut in my debian, no  problem. So I tried to do it from CLI. Found the show option but nothing more.
Is there a way to open main window under mouse cursor from CLI ?

Have a nice day :)

**Comment by hluk** [comment]
Hi, glad you enjoy the app. :+1: 

For "Show main window under mouse cursor" the command is `copyq showAt`.
