### ISSUE TITLE
Hard-to-read text on clipboard

### ISSUE THREAD

**Issue by juarez-spa3** [hluk/CopyQ#2629]
Before creating a new issue, see list of [known
issues](https://copyq.readthedocs.io/en/latest/known-issues.html).

**Describe the bug**
I don't know exactly how to explain the error and why it occurs. please see screenshot. I copied some text and images to test but I can see the text is copied but the text is not readable.

**To Reproduce**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

<details>
 <summary>Screenshot</summary>

![annotely_image](https://github.com/hluk/CopyQ/assets/153795294/a14274e6-65ce-459d-b108-cd7928e85abb)

</details>

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Application Version: 7.1.0
 - OS: Windows 10 22H2
 - Desktop environment, window manager (if applicable)

**Additional context**

**Comment by hluk** [comment]
See #2398.
