### ISSUE TITLE
Copy Q 8.0.0 M1 version doesn't works.

### ISSUE THREAD

**Issue by ottopic** [hluk/CopyQ#2633]
Unable to start the application because the developer is not recognized. Trying several times and even starting with the right button.

**Comment by yllekz** [comment]
I am getting an error saying the .app is damaged when I download it.

**Comment by ottopic** [comment]
> I am getting an error saying the .app is damaged when I download it.

Yes it is, you are right

**Comment by robertstrom** [comment]
Getting error that the app is damaged also

**Comment by opsmun** [comment]
Same issue.  Not sure how to help further than that.

**Comment by hluk** [comment]
Does [this workaround](https://copyq.readthedocs.io/en/latest/known-issues.html#on-macos-copyq-won-t-paste-after-installation-update) help?

**Comment by robertstrom** [comment]
Those settings are already configured from a previous install.

![image](https://github.com/hluk/CopyQ/assets/3240205/aa716021-a1d8-49c9-b354-ce3c6a906598)

This is what the error looks like when you try to execute the CopyQ.app

![image](https://github.com/hluk/CopyQ/assets/3240205/9b293065-b012-4a7e-8def-41461f2157a3)

**Comment by earthsound** [comment]
Running `codesign -vv /Applications/CopyQ.app` results in 
`/Applications/CopyQ.app: code has no resources but signature indicates they must be present`

ArchiChect shows the same:
`App signature check:
⛔️ spctl error 1
/Applications/CopyQ.app: code has no resources but signature indicates they must be present`

`xattr /Applications/CopyQ.app/` results in:
`com.apple.provenance
com.apple.quarantine`

If you remove those attributes, you can get past this error, but then you hit #2637.

**Comment by hluk** [comment]
Lets move the discussion to #2633.
