### ISSUE TITLE
networkGet(url) failing in "Tab for URLs with Title and Icon" command

### ISSUE THREAD

**Issue by richlux** [hluk/CopyQ#2634]
The "Tab for URLs with Title and Icon" command in the documentation is no longer working.  I've traced it down to the networkGet function.  The networkGet(url) function appears to be failing. It is returning the error "TLS initialization failed".  I also see the following messages in the Server Log:

CopyQ Warning [2024-03-14 11:46:38.144] <Client-67416>: [qt.network.ssl] QtWarning: No TLS backend is available
CopyQ Warning [2024-03-14 11:46:38.144] <Client-67416>: [qt.network.ssl] QtWarning: No functional TLS backend was found
CopyQ Warning [2024-03-14 11:46:38.157] <Client-67416>: [qt.network.ssl] QtWarning: QSslSocket::connectToHostEncrypted: TLS initialization failed

To Reproduce this you can add "serverLog(reply.error) to the "fetchContent" function and then copy a URL.  You will see the error string in the log file.

I'm running the latest version of CopyQ (8.0.0) on Windows 11

This is unrelated, but in case someone else is interested, you can use the old method to get the Icon via API call to "https://s2.googleusercontent.com/s2/favicons?domain_url=", if the method in the current command fails.

Thanks,
Rich

**Comment by hluk** [comment]
The reason is most probably missing plugin in `copyq.exe` installer. Fixing.

Workaround would be to copy the `tls` folder from `copyq.zip` to the installation directory.

**Comment by hluk** [comment]
Fixed installer: https://ci.appveyor.com/project/hluk/copyq/builds/49420809/artifacts

**Comment by richlux** [comment]
Thanks!  This fixed the problem getting the data, but now the Title of the page that is put into the Notes field is wrapping strangely after I copy the URL. If I edit the Clip without even saving it, the formatting is corrected. See the images below.

![image](https://github.com/hluk/CopyQ/assets/25157703/394d7240-4ab7-43e5-b4cb-7dc620ac6b89)

If I edit the clip and the press ESC without making any changes, the Title formats properly and doesn't wrap.

![image](https://github.com/hluk/CopyQ/assets/25157703/fcdb9ca2-05dd-4bf7-a591-f8e74e01ad29)
