### ISSUE TITLE
When installing copyQ_8.0 Microsoft Defender suspects that copyq.exe removing it for the sake of the Trojan

### ISSUE THREAD

**Issue by happysaten** [hluk/CopyQ#2640]
![屏幕截图 2024-03-17 165619](https://github.com/hluk/CopyQ/assets/100853912/26e31dc1-711a-4cb1-93ea-f5ecdef41549)

System version: Win11 Professional Edition 23H2 22631.3296

**Comment by hluk** [comment]
I assume this is another false positive.
