### ISSUE TITLE
control D is what you use to close windows terminal it's used by your software and you can't change that in the hotkey settings 

### ISSUE THREAD

**Issue by mjoe67886** [hluk/CopyQ#2642]
Before creating a new issue, see list of [known
issues](https://copyq.readthedocs.io/en/latest/known-issues.html).

**Describe the bug**
control D is what you use to close windows terminal it's used by your software and you can't change that in the hotkey settings 

**To Reproduce**
Just have windows terminal open and press control D it opens up your software and then go to your settings and try and remove that keyboard shortcut so you could interoperate with Windows terminal and you'll notice there's no option to remove that control D shortcut.

**Expected behavior**
Please make control the optional

**Screenshots**

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Application Version 8
 - OS [e.g. Windows 11]
 - Desktop environment, window manager (if applicable)

**Additional context**

**Comment by hluk** [comment]
To remove the shortcut, click on the shortcut button (for the shortcut you want to remove) and click "Remove Shortcut" button.

**Comment by mjoe67886** [comment]
No the thing is it's inbuilt to your software that's what I've been saying
there's no shortcut named Control D in my shortcuts list I looked like ten
times... I'd appreciate if you could help me get rid of this shortcut maybe
test it on your system and see if when you press control D something
happens.

**Comment by mjoe67886** [comment]
OK that's the weirdest thing I looked everywhere and I just went back to
double check and I instantly noticed the commands window and I thought
that's weird so I looked in there I was looking in the preferences under
the shortcuts there and I could never find it it might be a little
unintuitive having two places but either way I know how to look and again
if I haven't said it before this is absolutely the best thing ever for
productivity..... To summarize the control D shortcut was in there and I
removed it
