### ISSUE TITLE
[CopyQ 8.0.0] Applied Editor foreground color is not respected

### ISSUE THREAD

**Issue by MG240** [hluk/CopyQ#2643]
**Describe the bug**
Applied Editor foreground color is not respected.

**To Reproduce**
1. Go to 'Preferences / Appearances' and apply any of the themes.
2. Edit an item.
3. Bug: Editor foreground color is not respected and always in #000000 regardless of the applied one

**Screenshots**

![20240318_020449685](https://github.com/hluk/CopyQ/assets/128346373/1ed87d19-c308-44d7-b608-eca7d9613f10)

![20240318_020056307](https://github.com/hluk/CopyQ/assets/128346373/8577c38d-982b-4b36-94f6-d861d2199fa0)

**Version, OS and Environment**
 - CopyQ 8.0.0
 - Windows 11 22H2 64bit

**Comment by hluk** [comment]
Fixed. The new Windows zip and installer are available here: https://ci.appveyor.com/project/hluk/copyq/builds/49469682/artifacts
