### ISSUE TITLE
Errormessages after removing copyq 6.4.0

### ISSUE THREAD

**Issue by gituser823** [hluk/CopyQ#2644]
Before creating a new issue, see list of [known
issues](https://copyq.readthedocs.io/en/latest/known-issues.html).

**Describe the bug**
Linut Mint Debian Edition still has version 6.4.0 in the repos,  which I have used until now.
Now I want to update to 8.0 but after removing 6.4.0 I get these errornotifications, how do I get rid of them so I can install version 8 via Flathub?

**To Reproduce**
Remove CopyQ 6.4.0 via package manager.

**Expected behavior**
No errors after removing the package

**Screenshots**
![Selection_011](https://github.com/hluk/CopyQ/assets/32219087/4588f02b-220b-4567-b3bd-b7b3055e6f94)

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Application Version 6.4.0
 - OS Linux Mint Debian Edition 6
 - Desktop environment, window manager Cinnamon

**Additional context**

I also had another bug I could not get rid of with the inapp settings, which was actually why I wanted to update:
When I selected something with the mouse it would always get copied to the clipboard.
I only want text to be copied to the clipboard by clicking Ctrl + C, which settings do I need to set up for that?

For now I have reinstalled version 6.4.0, but I wanna use 8.0

Edit: After installing copyq8.0.0 the errors are gone, maybe you still wanna look into the issue.

**Comment by hluk** [comment]
The app must be closed before being removed from system (or upgraded).
