### ISSUE TITLE
[CopyQ 8.0.0] Theme not applied preferences window and resizing issue in preferences/tab menu

### ISSUE THREAD

**Issue by gituser823** [hluk/CopyQ#2645]
**Describe the bug**
The theme is not applied to preferences, commands and Search windows. And probably other Menu I did not test.

Also in the preferences window the sidebar for "Tabs" can not be properly resized.

**To Reproduce**
Open preferences.
Go to "Tabs".
Resize the middle bar.

**Expected behavior**
The middle bar should be resized so that it stops and resizes to wherever I release mouse1.

**Screenshots**
Heres a gif of the issue:

![copyq_bug](https://github.com/hluk/CopyQ/assets/32219087/830e674f-9b16-410e-88b1-86d2357f3c1f)

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Application Version
 - 8.0.0

 - OS
 - Linux Mint Debian Edition 6

 - Desktop environment, window manager
 - Cinnamon 6.0.4

**Comment by hluk** [comment]
> The theme is not applied to preferences, commands and Search windows.

The app theme should be applied only to the main window not other dialogs (and only if you enable "Set colors for tabs, tool bar and menus" option in Appearance config tab).

> Also in the preferences window the sidebar for "Tabs" can not be properly resized.

That looks like some issue with the current system theme.

I tried various themes and DPI settings and could not reproduce the behavior.

**Comment by gituser823** [comment]
I guess we can close this issue for now as I also no longer can reproduce the resizing bug.
