### ISSUE TITLE
items cannot edit, pin..

### ISSUE THREAD

**Issue by Omoinemie** [hluk/CopyQ#2649]
Before creating a new issue, see list of [known
issues](https://copyq.readthedocs.io/en/latest/known-issues.html).

**Describe the bug**
when setting the synchronize path, all operations on items cannot be run

**Screenshots**
![image](https://github.com/hluk/CopyQ/assets/31991443/9ebef589-9a35-4ddc-890d-897ad0ee97c9)
![image](https://github.com/hluk/CopyQ/assets/31991443/c01e815f-42a4-47b0-8967-2250faffcf75)
![image](https://github.com/hluk/CopyQ/assets/31991443/86cdd3e0-2efc-44c0-86b1-eb16aa6a715b)

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Application Version [e.g. 3.7.2]
 - OS [e.g. Windows]
 - Desktop environment, window manager (if applicable)

**Additional context**
CopyQ Warning [2024-03-21 19:45:27.784] <monitorClipboard-7776>: [qt.qpa.mime] QtWarning: Retrying to obtain clipboard.
CopyQ Warning [2024-03-21 19:49:24.753] <monitorClipboard-7776>: [qt.qpa.mime] QtWarning: Retrying to obtain clipboard.
CopyQ Warning [2024-03-21 19:49:48.924] <monitorClipboard-7776>: [qt.qpa.mime] QtWarning: Retrying to obtain clipboard.
CopyQ Warning [2024-03-21 19:52:18.676] <Server-13672>: [default] QtWarning: QSystemTrayIcon::setVisible: No Icon set
CopyQ Warning [2024-03-21 19:54:26.119] <monitorClipboard-7612>: [qt.qpa.mime] QtWarning: Retrying to obtain clipboard.
CopyQ Warning [2024-03-21 19:54:37.079] <monitorClipboard-7612>: [qt.qpa.mime] QtWarning: Retrying to obtain clipboard.
CopyQ Warning [2024-03-21 19:54:43.785] <monitorClipboard-7612>: [qt.qpa.mime] QtWarning: Retrying to obtain clipboard.
CopyQ Warning [2024-03-21 19:54:53.277] <monitorClipboard-7612>: [qt.qpa.mime] QtWarning: Retrying to obtain clipboard.
CopyQ Warning [2024-03-21 19:55:18.618] <Server-12108>: [default] QtWarning: QSystemTrayIcon::setVisible: No Icon set
CopyQ Warning [2024-03-21 19:55:26.623] <monitorClipboard-4232>: [qt.qpa.mime] QtWarning: Retrying to obtain clipboard.
CopyQ Warning [2024-03-21 19:55:29.679] <monitorClipboard-4232>: [qt.qpa.mime] QtWarning: Retrying to obtain clipboard.
CopyQ ERROR [2024-03-21 19:56:14.048] <monitorClipboard-12460>: 无法连接到服务端！请先启动 CopyQ 服务端。
CopyQ Warning [2024-03-21 19:57:13.569] <Server-6088>: [default] QtWarning: QSystemTrayIcon::setVisible: No Icon set
CopyQ Warning [2024-03-21 20:00:34.703] <Server-27388>: [default] QtWarning: QSystemTrayIcon::setVisible: No Icon set
CopyQ Warning [2024-03-21 20:01:06.274] <monitorClipboard-5212>: [qt.qpa.mime] QtWarning: Retrying to obtain clipboard.
CopyQ Warning [2024-03-21 20:01:30.378] <monitorClipboard-5212>: [qt.qpa.mime] QtWarning: Retrying to obtain clipboard.
CopyQ ERROR [2024-03-21 20:04:36.758] <Server-27388>: Corrupted data: Failed to read MIME type (v1)
CopyQ Note [2024-03-21 20:04:45.058] <Server-27388>: Keeping corrupted tab on user request
CopyQ Warning [2024-03-21 20:05:05.110] <monitorClipboard-26240>: [qt.qpa.mime] QtWarning: Retrying to obtain clipboard.
CopyQ ERROR [2024-03-21 20:06:34.681] <Server-27388>: Corrupted data: Failed to read MIME type (v1)
CopyQ Note [2024-03-21 20:06:38.033] <Server-27388>: Keeping corrupted tab on user request
CopyQ Warning [2024-03-21 20:06:56.649] <monitorClipboard-26240>: [qt.qpa.mime] QtWarning: Retrying to obtain clipboard.
CopyQ Warning [2024-03-21 20:07:39.877] <monitorClipboard-16980>: [qt.qpa.mime] QtWarning: Retrying to obtain clipboard.
CopyQ Warning [2024-03-21 20:09:13.450] <monitorClipboard-23408>: [qt.qpa.mime] QtWarning: Retrying to obtain clipboard.

**Comment by hluk** [comment]
The paths in the configuration should be absolute (starting with drive, for example `C:/`), otherwise a relative folder is used from where the app was started.

I think you may need to use `/` path separator and CopyQ does not recognize the environment variables (like `%LOCALAPPDATA%`).

**Comment by Omoinemie** [comment]
> The paths in the configuration should be absolute (starting with drive, for example `C:/`), otherwise a relative folder is used from where the app was started.
> 
> I think you may need to use `/` path separator and CopyQ does not recognize the environment variables (like `%LOCALAPPDATA%`).

I tried this but it doesn't work, I can't use the edit with the mouse, but it works with the keyboard shortcuts
![image](https://github.com/hluk/CopyQ/assets/31991443/42bcc201-de02-4271-a6f2-6a1323f1512c)
![image](https://github.com/hluk/CopyQ/assets/31991443/942831be-a1f0-4d26-9d70-a4a5f92ca30c)

**Comment by hluk** [comment]
> I can't use the edit with the mouse

Can you post steps to reproduce?

**Comment by Omoinemie** [comment]
> > I can't use the edit with the mouse
> 
> Can you post steps to reproduce?

![PixPin_2024-03-22_19-14-46](https://github.com/hluk/CopyQ/assets/31991443/d418cdf2-4b71-49f7-b436-d778ad017606)

**Comment by madworld567** [comment]
I'm having an identical issue. On MacOS 15 and CopyQ 9.0.0 (arm). I noticed if text I'm trying to import to the synchronized tabs has formats, like the ones copied from any website or online, it'll sabotage the rest of the clipboard. It's so strange, I've been using this for a while without any issue until recently.

Not sure if helps, but I'm currently using Syncthing to sync my clipboard across all my devices.

and yes, the problem does persist even if I remove and create the tab again.

![sample](https://github.com/user-attachments/assets/f6aee141-23e1-4732-aa8c-2f7b3955c1f5)

**Comment by madworld567** [comment]
> I cannot reproduce the behavior with your config, but I'm using Linux.
> 
> I wonder if the following errors in your logs are causing this:
> 
> ```
> CopyQ ERROR [2024-03-21 20:06:34.681] : Corrupted data: Failed to read MIME type (v1)
> CopyQ Note [2024-03-21 20:06:38.033] : Keeping corrupted tab on user request
> ```
> 
> Does the problem persist when you remove and create the tab again?

I'm having an identical issue. On MacOS 15 and CopyQ 9.0.0 (arm). I noticed if text I'm trying to import to the synchronized tabs has formats, like the ones copied from any website or online, it'll sabotage the rest of the clipboard. It's so strange, I've been using this for a while without any issue until recently.

Not sure if helps, but I'm currently using Syncthing to sync my clipboard across all my devices.

and yes, the problem does persist even if I remove and create the tab again.

![sample](https://github.com/user-attachments/assets/f6aee141-23e1-4732-aa8c-2f7b3955c1f5)

**Comment by hluk** [comment]
Thanks for the reproducer!

I can reproduce it, but only if I try triggering the actions from the context menu or menu bar. Using shortcut still works.

Looking into it.
