### ISSUE TITLE
 [Request]: New Windows command "Paste text using keystrokes"

### ISSUE THREAD

**Issue by Morik** [hluk/CopyQ#2655]
**Is your feature request related to a problem? Please describe.**
I'm using Remote Desktops a lot for customer support. Oftentimes, they use long, cryptic (and therefore secure) passphrases, which are hard to type correctly. 

**Describe the solution you'd like**
Basically, the Windows version of [Decrypt and Type](https://github.com/hluk/copyq-commands/tree/master/Application#decrypt-and-type)

**Describe alternatives you've considered**
Currently, I'm using a simple AutoHotkey script to send the current clipboard as keystrokes to the login screen. That's working, but I'm wondering if this could not be solved using a CopyQ command.

**Additional context**
Simmilar to [#1359](https://github.com/hluk/CopyQ/issues/1359)

**Comment by ronindesign** [comment]
This would be great! I'm in the market for a clipboard history manager and use BetterTouchTool on macOS which has this feature and I love it/use it frequently.

**Comment by hluk** [comment]
I would prefer this to be implemented using a custom commands instead. I'm not planning to add this into the app itself - the implementation would be too complex (and would work only on one OS, which I do not use).

I'm not familiar with AutoHotkey itself, but if you can send key presses using a command line, it should be possible to create a custom command in CopyQ to handle it.

**Comment by Morik** [comment]
So i'll created a custom command using only powershell native commands:

```powershell:
Add-Type -AssemblyName System.Windows.Forms

$escMap = @{
    '{' = '{{}'
    '}' = '{}}'
    '+' = '{+}'
    '^' = '{^}'
    '%' = '{%}'
    '~' = '{~}'
    '[' = '{[}'
    ']' = '{]}'
    '(' = '{(}'
    ')' = '{)}'
}

$clip = (& "$env:COPYQ" read 0 | Out-String)

$clip.ToCharArray() | ForEach-Object {
    $c = $_.ToString()
    if ($escMap.ContainsKey($c)) {
        $c = $escMap[$c]
    }

    [System.Windows.Forms.SendKeys]::SendWait($c)
    Start-Sleep -Milliseconds 30
}

[System.Windows.Forms.SendKeys]::SendWait("{ENTER}")
