### ISSUE TITLE
Feature request: Change font size of tabs items count

### ISSUE THREAD

**Issue by elig0n** [hluk/CopyQ#2657]
Under HiDPI 3840x2160 resolution it looks very small and I couldn't find any font setting that can change its size.

![image](https://github.com/hluk/CopyQ/assets/31196036/e17e5f13-43fb-40a1-8404-d6843976a203)

**Comment by hluk** [comment]
Not sure why it does not scale with the DPI. It actually scales for me on my display or even if I change the `QT_SCALE_FACTOR` environment variable to a higher value (e.g. 2 or 3).

Anyway, you can increase the size with the following steps:
1. Open Preferences dialog (Ctrl+P)
2. Open Appearance tab
3. Click Edit Theme button
4. Increase `font-size` value under `tab_bar_item_counter` option (or `tab_tree_item_counter` if you use tab tree instead)
