### ISSUE TITLE
Command/script "Ignore *"Password"* window" stop working on v8.0.0 (but also other commands)

### ISSUE THREAD

**Issue by elbowz** [hluk/CopyQ#2664]
**Describe the bug**
The command/script **"Ignore *"Password"* window"** on version 8.0.0 stop working

**To Reproduce**
1. Enable the command by F6 shortcut
3. Set the correct window title
4. Copy something on the password manger (eg. KeeWeb)

**Expected behavior**
The copied field shouldn't appear in CopyQ

**Version, OS and Environment**
```console 
% copyq version
CopyQ Clipboard Manager 8.0.0
Qt: 5.15.10
KNotifications: 5.110.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Arch Linux
```

```
KDE Plasma Version: 6.0.3
KDE Frameworks Version: 6.0.0
Qt Version: 6.6.3
Kernel Version: 6.8.2-arch2-1 (64-bit)
```

**Additional context**
I have downgrade to CopyQ 7.1.0 and all works like a charm.

I think the problem is spread to others commands/scripts, because they also stop working (eg. Store Window Title, Display Window name, Blocklisted Texts)

Thanks

**Comment by hluk** [comment]
Is there any error/warning in logs?

**Comment by elbowz** [comment]
Sorry, I have completely missed the log, my bad: https://pastebin.com/rZTH2mV7 (following the FAQ about logging)

I have found this line inside: `[qt.qpa.wayland] QtWarning: Wayland does not support QWindow::requestActivate()`

So I have tried to disable the Command [Wayland Support](https://github.com/hluk/copyq-commands/blob/master/Scripts/wayland-support.ini), and the now all it works like a charm :)

if you're wondering, I'm on wayland.

Thanks

**Comment by hluk** [comment]
On Wayland getting window titles won't work - the command uses a workaround for Sway and Hyprland.

More info is here: https://copyq.readthedocs.io/en/latest/known-issues.html#known-issue-wayland

**Comment by elbowz** [comment]
Mhhh...I have kde and hyprland. Anyway, I think a command (taken from the official repo) shouldn't break other ones.

I don't know anything about getting window title on Wayland...only installed the command for a better compatibility.

Thanks!
