### ISSUE TITLE
Move to tab command deletes item if moving to same tab

### ISSUE THREAD

**Issue by CodesAway** [hluk/CopyQ#2669]
**Describe the bug**
`Move to tag` command deletes item if moving to same tab

**To Reproduce**
1. Create **Move to "Tasks" tab** command 
    - Press F6 (to open commands window)
    - Click **Add** and type **move**
    - Select **Move to "Tasks" tab** and click **OK**
    - Click **OK** to close **commands** window
2. Copy some text (appears in default **clipboard** tab)
3. Right click an item and select **Move to "Tasks" tab**
4. This works as expected (creating a **Tasks** tab if one doesn't exist)
5. Switch to the **Tasks** tab
6. Right click item and select **Move to "Tasks" tab** (such as if done by mistake)
7. Item is deleted

**Expected behavior**
No change should be made, since the item is already on the **Tasks** tab

**Screenshots**
![(1) Move to tag tasks success](https://github.com/hluk/CopyQ/assets/13824365/aec7b1f5-60be-48e6-99dd-1c13968b8f9a)
![(2) Select move to same tag](https://github.com/hluk/CopyQ/assets/13824365/dd337027-1d5f-4df9-a84b-76c677890ff0)
![(3) Item is removed (expected no change)](https://github.com/hluk/CopyQ/assets/13824365/7a01e3b0-98ca-44c5-afb6-15ddd70c2fa5)

**Version, OS and Environment**
CopyQ Clipboard Manager 8.0.0
Qt: 6.5.3
KNotifications: 6.0.0
Compiler: MSVC
Arch: x86_64-little_endian-llp64
OS: Windows 11 Version 23H2

**Comment by hluk** [comment]
Fixed in #2684. Thanks for the report!
