### ISSUE TITLE
edit() function to support builtin editor bypass, notes too

### ISSUE THREAD

**Issue by elig0n** [hluk/CopyQ#2672]
it would be useful to be able to force using the non-external editor with edit()
for example with an argument.

Also please consider implementing edit_note() to open an editor with the item note

**Comment by hluk** [comment]
Good idea. Draft for the new API:

```
editItem(row[, mimeType[, data]])

    Edits specific format for the item.

    Opens external editor if set, otherwise opens internal editor.

    If row is -1 (or other negative number) edits clipboard instead and creates new item.
```

For example to edit 3rd item's notes: `editItem(2, mimeItemNotes)`

I'm also changing the current behavior so that the external editor (if set) opens for edit notes instead of the internal one.

**Comment by hluk** [comment]
> I'm also changing the current behavior so that the external editor (if set) opens for edit notes instead of the internal one.

Actually, disregard this. It would be inconsistent with the default edit shortcut (F2).

But it would be possible to assign custom command to edit notes in the external editor.
