### ISSUE TITLE
CopyQ crashes on Ubuntu 

### ISSUE THREAD

**Issue by thoefkens** [hluk/CopyQ#2688]
Before creating a new issue, see list of [known
issues](https://copyq.readthedocs.io/en/latest/known-issues.html).

**Describe the bug**
When I open copyQ's "clipped" screen to select clipboard entries, the screen background is blue.
When I go into the settings of copyQ and click "appearance", copyQ hangs, gets killed and crashes.

![image](https://github.com/hluk/CopyQ/assets/97980582/106ba58b-12e2-4395-a5e1-293aa14016fb)

**To Reproduce**
1. Go to CopyQ - Preferences
2. Click on Appearance
CopyQ crashes.

Attached a screenshot of starting copyQ with debug, then going to appearance.

![image](https://github.com/hluk/CopyQ/assets/97980582/48dc899a-d460-4041-a679-49f2d63d2817)

**Screenshots**

**Version, OS and Environment**
Ubuntu 22.04.4
CopyQ 6.0.1

**Comment by hluk** [comment]
CopyQ 6.0.1 is very old release. Please update to a newer version.

It should be possible to install the latest version from PPA. See: https://copyq.readthedocs.io/en/latest/installation.html
