### ISSUE TITLE
Make images in the tray menu appear larger on mouse over?

### ISSUE THREAD

**Issue by orschiro** [hluk/CopyQ#2699]
Hi all, 

I am wondering if we can improve how images are displayed in the tray menu.

Currently they are very small and often unrecognisable. 

Would it, for example, be possible to make them appear larger on mouse over? 

Thank you!

<img width="358" alt="image" src="https://github.com/hluk/CopyQ/assets/170947/61ac546f-e41f-4d88-b623-5314666f62e7">

**Comment by hluk** [comment]
Unfortunately, I don't think that is supported by Qt GUI framework and in desktop environments (which often override the menu functionality).
