### ISSUE TITLE
Open Main Window Near the Mouse Cursor

### ISSUE THREAD

**Issue by babakm2** [hluk/CopyQ#270]
Hi I have a request:
When I send the global keyboard for show the main windows, I wish to open that near the mouse position. (because I use a  mouse gesture app named [Strokesplus] (http://www.strokesplus.com))

**Comment by JeremyWW** [comment]
As per my issue #315 this would be very useful to me.

**Comment by hluk** [comment]
Implemented. You can find the command to show main window under mouse cursor in Command Dialog (click Add button, select "Show main window under mouse cursor" and select Global Shortcut).

**Comment by JeremyWW** [comment]
Great. When will it be available as a Windows installer?

**Comment by hluk** [comment]
No idea. There is no fixed release cycle for CopyQ.

If you want to test the feature you can download it [here](https://ci.appveyor.com/api/buildjobs/jp65l33wotocwb5y/artifacts/copyq.zip).

**Comment by JeremyWW** [comment]
Thanks. That works well.

**Comment by JeremyWW** [comment]
I have to stop using this build unfortunately. It randomly deletes 'clips' from tabs! Doesn't seem to be any logic / pattern to it.

**Comment by hluk** [comment]
Perhaps the items are not saved. Can you check if the settings are saved in "config" folder in the directory extracted from `copyq.zip`? Application needs to have write access to the "config" folder.

**Comment by JeremyWW** [comment]
No, I give up. Started again with a clean extract but some preferences changes it remembers and some it doesn't no matter how many times I try. I get bizarre messages about '...language will be changed after application restart...' when I haven't changed that, let alone install any languages. Don't know what to do really.

**Comment by marlarius** [comment]
Unfortunately this doesn't seem to work anymore.

I choose "Show main window under mouse cursor" and set my shortcut (Ctrl-Esc).

But it opens at the last position exactly like "Show/hide main window". There is no difference at all.

Copyq 6.0.1 on Linux Mint 21 Cinnamon.

**Comment by hluk** [comment]
@marlarius CopyQ 6.0.1 is an old version, please update if possible.

**Comment by marlarius** [comment]
Thanks. 6.0.1 is the newest version in Ubuntu 22.04's package manager. I will see if I can install from another source.

**Comment by hluk** [comment]
On Ubuntu, you can install latest CopyQ from PPA: https://copyq.readthedocs.io/en/latest/installation.html

**Comment by marlarius** [comment]
Thanks, that worked!
