### ISSUE TITLE
Item content wrapping

### ISSUE THREAD

**Issue by elig0n** [hluk/CopyQ#2709]
Long non-broken lines in the Item content dialog Content pane require horizontal scrolling which can be cumbersome.

This could be implemented i.e. by adding "Toggle wrapping" to context menu inside the Content pane.

**Comment by hluk** [comment]
There is "Wrap long text" option in preferences. But this won't work for some HTML items unless you also disable these under Items configuration tab:
![image](https://github.com/hluk/CopyQ/assets/38054/57be4052-3d81-410c-a153-71ad4b68cd18)
