### ISSUE TITLE
Doesn't log clipboard in Ubuntu 24.04

### ISSUE THREAD

**Issue by rijans** [hluk/CopyQ#2715]
**Describe the bug**
I am using Ubuntu 24.04 and the CopyQ doesn't seem to catch clipboard history. I even tried with reboot OS.

**To Reproduce**
Install CopyQ from Ubuntu store. Try to use it. 

**Version, OS and Environment**
Ubuntu 24.04

- Application Version
CopyQ 7.1.0-1build2

**Comment by hluk** [comment]
See the section about [Wayland in Known Issues](https://copyq.readthedocs.io/en/latest/known-issues.html#known-issue-wayland).
