### ISSUE TITLE
Не работают быстрые клавиши

### ISSUE THREAD

**Issue by Do-fomin** [hluk/CopyQ#2719]
**Version, OS and Environment**
Fedora 40 KDE Plasma 6

- Application Version: 8.0.0-1.fc40
- OS Fedora 40 KDE Plasma 6
- Desktop environment, window manager (if applicable) Fedora 40 KDE Plasma 6

**Additional context**

**Comment by hluk** [comment]
Not enough info. Also, I can accept only english reports.

**Comment by Do-fomin** [comment]
Hotkeys don't work
Application Version: 8.0.0-1.fc40
OS Fedora 40 KDE Plasma 6

**Comment by hluk** [comment]
Global hotkeys are not supported on Wayland (Plasma 6 and other recent desktop environments). See: https://copyq.readthedocs.io/en/latest/known-issues.html#known-issue-wayland
