### ISSUE TITLE
读取图片，将图片转为二进制流，或者，模拟打开图片，打开后将图片直接复制到粘贴板。为什么我没有找到这样的功能，

### ISSUE THREAD

**Issue by GaiaJia** [hluk/CopyQ#2728]

**Comment by hluk** [comment]
Sorry, I can accept only English feature request.

**Comment by hluk** [comment]
BTW, if you want to **copy a text from a screenshot**, try using [Copy Text in Image](https://github.com/hluk/copyq-commands/tree/master/Global#copy-text-in-image) (see [README.md](https://github.com/hluk/copyq-commands/blob/master/README.md) for details on how to add the command).
