### ISSUE TITLE
original window gets unfocused when copyq is open

### ISSUE THREAD

**Issue by Chrysanthemum536** [hluk/CopyQ#2737]
**Describe the bug**
when copyq is activated, the focus is removed from the original window

**To Reproduce**
1. right click on a website, opening the context menu
2. activate copyq. the context menu will close

1. open the start menu
2. activate copyq, the start menu closes

**Expected behavior**
opening the built in windows clipboard, the original window does notice the clipboard selector has been opened

**Version, OS and Environment**

8.0
windows 10

**Comment by hluk** [comment]
Closing as duplicate of #2556.

**Comment by Chealer** [comment]
This is not a duplicate of #2556, but I suggest to discard anyway, since the behavior is now properly described in #3540.
