### ISSUE TITLE
Copyq Hyprland scaling and copy/pasting issues

### ISSUE THREAD

**Issue by cafetestrest** [hluk/CopyQ#2744]
I have issues with copyq menu floating window in hyprland with scaling when searching for something it looks like so for me:
![image](https://github.com/hluk/CopyQ/assets/111571367/6b087bfb-9fcd-45fc-88c5-f1f3bd9722a7)

I'm running Nixos with Hyprland (latest) along with copyq version: 8.0.0.

Unsure if this is copyq bug or hyprland / issue, if so please let me know.

Also I have a weird issue as of lately, copy/pasting does not work as intended for electron apps, when I copy something from Chromium/VSCodium I tend to get <DATA> and sometimes application does not copy stuff properly:
![2](https://github.com/hluk/CopyQ/assets/111571367/f1e6e893-2787-4cdb-a66d-1e4543219060)

**Comment by cafetestrest** [comment]
Also to mention, this is only happening when I start copyq with env QT_QPA_PLATFORM=wayland copyq, when I start it as xcb, it seems to work better but I'm unable to search.

**Comment by hluk** [comment]
I can't fix these issues in the app itself. They are related to Qt GUI framework and the Wayland compositor.

See also: https://copyq.readthedocs.io/en/latest/known-issues.html#known-issue-wayland

Try using the [Wayland Support command](https://github.com/hluk/copyq-commands/tree/master/Scripts#wayland-support) mention in the linked page above.

BTW, for me, the app looks good in Sway Wayland compositor when running with `QT_QPA_PLATFORM=wayland`.
