### ISSUE TITLE
Clearing clipboard after timeout

### ISSUE THREAD

**Issue by Massimo-B** [hluk/CopyQ#2746]
I know you have a scripting API and also a feature to blacklist applications.
But do you support some (default?) API that provides a way for password managers to clear the clipboard after some timeout, as mentioned in 
https://github.com/keepassxreboot/keepassxc/issues/9842
?

**Comment by Cherkah** [comment]
thanks the dev for this app. the klipper's bugs were boring me.

@Massimo-B Good question?
As a keepassxc user how can i use copyq in a secure way with keepassxc?
Should i to use the scripting API?
thanks to clear my questions...

**Comment by hluk** [comment]
There is [Clear Clipboard After Interval](https://github.com/hluk/copyq-commands/blob/master/Scripts/clear-clipboard-after-interval.ini), but it won't work with password managers, because CopyQ in the recent versions completely ignores clipboard content with passwords/secrets.

I will try to modify CopyQ so it lets you react on data from password managers.

**Comment by Massimo-B** [comment]
Thanks, could you provide a short hint how to use this new feature?

**Comment by hluk** [comment]
> Thanks, could you provide a short hint how to use this new feature?

See [README.md](https://github.com/hluk/copyq-commands/blob/master/README.md) for details on how to add the command.

**Comment by hluk** [comment]
Oh, BTW, I did not release the fix for in CopyQ yet. If you are on Windows, you can use development build: https://ci.appveyor.com/project/hluk/copyq/builds/50193991/artifacts

**Comment by Massimo-B** [comment]
I have not idea where to start to get the clipboard manager either ignore passwords from KeepassXC or delete them after a while. It seems that there is some standard to inform the clipboard manager about sensitive passwords.
