### ISSUE TITLE
How to blacklist file Gtk3 FileOpen dialog

### ISSUE THREAD

**Issue by Massimo-B** [hluk/CopyQ#2748]
**Describe the bug**

How can I blacklist a File Open dialog?
Currently using Xfce on Linux. When opening a FileOpen dialog (which should be a Gtk3 dialog by default), and starting to type a path like "/usr/local/bin", every single keystroke gets selected. Selection means adding to PRIMARY. I'm also tracking PRIMARY: 
Preferences->General->[x] (2) Store text selected using mouse
That means the clipboard history in copyq is flooded by all the keystrokes.

How would I blacklist the File Open dialog, similar to
https://copyq.readthedocs.io/en/latest/faq.html#how-to-omit-storing-text-copied-from-specific-windows-like-a-password-manager ?
How can I match a single dialog? I guess the dialog is running on the process like Firefox and I don't want to blacklist the whole Firefox application from copyq.

**Version, OS and Environment**

copyq-8.0.0, Gentoo, Xfce, X11

**Comment by hluk** [comment]
This is not a bug. Unfortunately, a lot of apps mismanage the primary selection buffer (mouse selections).

If you know the window title of the dialog, you can block it using a custom command.

If you do not care about storing the mouse selections, try disabling "Store text selected using mouse" in CopyQ Preferences.

**Comment by Massimo-B** [comment]
The Window Title for the simple Open File dialog is "Open File".
It seems to work after I followed https://copyq.readthedocs.io/en/latest/faq.html#how-to-omit-storing-text-copied-from-specific-windows-like-a-password-manager
Thanks.
