### ISSUE TITLE
Automatically starting the server

### ISSUE THREAD

**Issue by Massimo-B** [hluk/CopyQ#2749]
**Is your feature request related to a problem? Please describe.**

I have a shortcut CTRL+ALT+v for the command `copyq show clipboard` in my window manager (Xfce). Usually copyq server is started with the Autostart of my window manager, but if not for whatever reason, that command should also start the server automatically. What do you think?

**Describe the solution you'd like**

Any remote command that requires the server should try to start the server if it is not running yet.

**Comment by hluk** [comment]
You can use `copyq --start-server show clipboard` to start the server if not yet running and show the tab.
