### ISSUE TITLE
[Feature] Emoji picker + symbols tab

### ISSUE THREAD

**Issue by realgooseman** [hluk/CopyQ#2750]
Hi @hluk and contributors,

Amazing software, great work.
I switched from the Windows native clipboard to CopyQ a few months ago.
CopyQ is more advanced which made me switch but there are two features I miss with the old clipboard.

The emoji picker and symbols tabs.

**Describe the solution you'd like**
Adding new emoji picker and symbol tabs on CopyQ, where you can freely choose and copy from. Natively or as plugin (doesn't matter).

It would work like the Windows clipboard. You have your main clipboard tab and other ones next to it for emojis and symbols. Including a search bar in them to search for specific emojis/symbols.

**Windows Clipboard Example**
![Windows Clipboard](https://github.com/hluk/CopyQ/assets/64812183/5de9cf85-ba91-46b5-b067-7e1a868d46b7)

Quick mockup for CopyQ (Showing new emoji picker + symbols tabs)
![CopyQ Enhanced](https://github.com/hluk/CopyQ/assets/64812183/76130ad5-dd48-49d4-85d2-b033027896cd)

**Comment by RedSnt** [comment]
This would be amazing. Having to pick an emoji first, then super+V (my shortcut for copyQ) then click enter; it's a longer process than it needs to be. I can't straight up ctrl+v the emoji for some reason, I always have to open copyQ first to select it, it's not stored correctly in the buffer or something from emoji selector.  

There's a bug report here about how cumbersome it is in KDE: https://bugs.kde.org/show_bug.cgi?id=434932

**Comment by hluk** [comment]
This is not a thing I would like to have built into CopyQ itself (or as a plugin).

That said, I already have a "Snippets" tab with frequently used emoji symbols. I usually copy a new emoji to the tab and add a note with a couple of labels, so I can search for it later.

![image](https://github.com/user-attachments/assets/3e67d51e-471a-4c99-b0fd-748a1e178307)

It would be possible to generate the tab with a script/command that parses an existing emoji data from some app.

**Comment by RedSnt** [comment]
@hluk A filter that adds emojis to a specific tab upon copy would be real nice. There's already a command that accepts ```text/plain;charset=utf-8``` specifically for emoji, I'm just wondering if there's an easy way to sort it into the snippet/emoji tab automatically.  
This doesn't work for me: 
![image](https://github.com/user-attachments/assets/61f8035a-9033-4a49-8de3-a694bdeec0af)

**Comment by RedSnt** [comment]
Switched to a wayland distro earlier this week, and ran into the problem of CopyQ not being able to detect window titles, anyway, the `QT_QPA_PLATFORM=xcb` environment variable does work (as [described here](https://copyq.readthedocs.io/en/latest/known-issues.html#known-issue-wayland)) when you open the emoji selector manually. But as soon as you open it using a global shortcut, then it inherits Plasma's environment variable (kglobalaccel?) and it goes out the window again. But it's better than nothing I guess, considering it's a limitation of Wayland and not CopyQ.

**Comment by RedSnt** [comment]
<details>
  <summary>1½ year later solution regarding this issue that I've found, depending on ones flavor:  
Using Perl to filter out emojis and sending them to their own tab.  
For my preferences, this will filter out non-emoji text, so it'll only take action on items that doesn't have text or numbers in it. Spaces and linebreaks etc. are fine though.  
</summary>

```
[Command]
Automatic=true
Icon=
Input=text/plain
MatchCommand="
    perl:
    use strict;
    use warnings;

    binmode STDIN, ':encoding(UTF-8)';

    local $/;
    my $text = <STDIN>;

    my $emoji = qr/
        \\p{Extended_Pictographic}
      | [\\x{1F1E6}-\\x{1F1FF}]   # regional indicators used by flags
      | [\\x{1F3FB}-\\x{1F3FF}]   # skin-tone modifiers
      | \\x{FE0F}                # variation selector
      | \\x{200D}                # zero-width joiner
      | \\x{20E3}                # keycap enclosing mark
      | [#*0-9](?=\\x{FE0F}?\\x{20E3}) # keycap bases
    /x;

    exit($text =~ /\\A(?:$emoji|\\s)+\\z/u ? 0 : 1);"
Name=Copy emoji to emoji tab
Remove=true
Tab=E&mojis
```
</details>

EDIT: The icon which doesn't show up here is just a smiling face icon, whatever suits your need of course.
