### ISSUE TITLE
Feature request: Delete all clips

### ISSUE THREAD

**Issue by mrbeeye** [hluk/CopyQ#276]
Please add 'Remove all" to popup menu (menu which appears after clicking on tray icon with right mouse button).

**Comment by scottkosty** [comment]
I'm guessing you already know this but in case you don't: a workaround is to go to "Show/Hide" and to press Ctrl+a, and then the "delete" button.

**Comment by hluk** [comment]
I don't think "Remove All" is needed (seems bit dangerous actually) but you can still prove me wrong and I'll reopen this :) .
