### ISSUE TITLE
v9 and RDP: Remote machine does not see copied items from local machine

### ISSUE THREAD

**Issue by ChrisZ16** [hluk/CopyQ#2761]
From Linux Mint 21.2 (based on Ubuntu 22.04) I RDP to Windows 10 PC. Copyq on the remote machine does not see data copied on the local machine (the other way around it works). Both are running v9.0.0. With v8.0.0 there was no problem.

"Show Log" on remote machine shows repeatedly:
  monitorClipboard-7988: Hiding secret clipboard data
  Server-7816: Hiding secret clipboard data
  monitorClipboard-688: [qt.qpa.mime] QtWarning: Retrying to obtain clipboard.

"Show Log" on the local machine does not show any suspicious messages

I did not configure any hiding of secret clipboard data and the copied text is from normal applications like text editor, browser etc

I do not use Wayland

No difference if I use the copyq-9.0.0.zip or copyq-9.0.0-setup.exe

I went back to v8.0.0 on the remote machine only and it works again

Maybe this has to do with these fixes in v9.0?
- Windows: Detect and ignore secrets from more apps
- Linux: Fixes clipboard synchronization with Qt 6 GUI framework

**Comment by hluk** [comment]
> Maybe this has to do with these fixes in v9.0?
> 
>     * Windows: Detect and ignore secrets from more apps

Can you check what are the formats in the clipboard (with Ctrl+Shift+C)?

It is likely related to this: https://github.com/hluk/CopyQ/issues/2765#issuecomment-2227209429

>     * Linux: Fixes clipboard synchronization with Qt 6 GUI framework

This is Linux thing only: sync between clipboard and primary/selection. Quite likely unrelated.

**Comment by ChrisZ16** [comment]
Formats in the clipoard are (the word "formats" is just the text in the clipoard):

On local machine (CopyQ v9.0, Linux)

![clipboard_formats_v9_local_Linux](https://github.com/user-attachments/assets/1e34cd19-9560-4490-b8be-0c1536ea383f)

Same item on RDP machine (CopyQ v8.0, Win10) - this is v8.0, because v9.0 does not see copied items from local machine

![clipboard_formats_v9_RDP_Win10](https://github.com/user-attachments/assets/2b6212a0-fc82-4bd8-8255-19cc8339056d)

There are formats you mentioned in #2765 (comment) as not stored / not shown

PS: I do not use Wayland

**Comment by hluk** [comment]
Looks like on Windows the clipboard is marked as "secret" or "not to be included in a history". I will be solving this in #2787.
