### ISSUE TITLE
Copyq not working when copying in private browsing (firefox)

### ISSUE THREAD

**Issue by nlfede** [hluk/CopyQ#2762]
**Describe the bug**
After upgrade to Copyq v9.0, every time I copy in a private browsing window, Copyq does not work. 

**To Reproduce**
Open private browsing window in firefox. 
Go to any webpage
Copy something
Check copyq, nothing has been copied, but if you paste with CTRL+V, it works. 

----
I also tried with Microsoft Edge browser, with InPrivate mode, same behaviour. No copy in InPrivate mode, but works well in normal windows. 

**Expected behavior**
It should copy also from private browsing windows. It does in all the previous versions of Copyq. 

I just installed portable copyq v8 and it works. I also installed portable copyq v9, and it doesn't work in that one either, so the problem is in the portable and the installed v9 versions. 

**Version, OS and Environment**
Copyq v9.0 running on Windows 10

- Application Version (for example 7.1.0)
- OS Windows 10

**Comment by ritmation** [comment]
@nlfede The author created a way to process clipboard contents from private/incognito windows in a recent commit. Check issue #2787 for more info.

@hluk I believe that this issue can be closed too.

**Comment by hluk** [comment]
@ritmation Thanks. Closing (solution is [in this comment](https://github.com/hluk/CopyQ/issues/2787#issuecomment-2260800682)).
