### ISSUE TITLE
wl-copy in wsl no longer displays in clipboard history on copyq version 9.0.0

### ISSUE THREAD

**Issue by pbrehm** [hluk/CopyQ#2765]
**Describe the bug**
When I upgraded to copyq 9.0.0 I noticed that copyq was no longer receiving clipboard information that was sent to it via wl-copy.

**To Reproduce**
Install 9.0.0 version of copyq on windows 10. 
Run the command "wl-copy testing123" in the command prompt for wls2 distro.
Note that the string "testing123" is not added to the copy history.
You can still paste it via CTRL-c in windows. But the value cannot be pasted via copyq.
When investigating, I noticed that the clipboard content is labeled as 
```
 <EMPTY>
```
When I downgraded back to 8.0.0 this issue was no longer present.

**Expected behavior**
When I use wl-copy in my wsl distro I expect this value to be added to my clipboard and be present in my history.

**Screenshots**
History at start.
![image](https://github.com/hluk/CopyQ/assets/19656926/118103c0-50ae-483d-8bba-cbbdfdf4b7d0)

Execute wl-copy command
![image](https://github.com/hluk/CopyQ/assets/19656926/c53a99cf-bbec-4f11-bdcc-e4b116eea582)

Observe it is not been added to history.
![image](https://github.com/hluk/CopyQ/assets/19656926/cf011304-c916-4335-befb-b75c321bc608)

**Version, OS and Environment**
copyq version 9.0.0
WSL version: 2.0.1.0
Kernel version: 5.15.123.1-1
WSLg version: 1.0.58
MSRDC version: 1.2.4485
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25880.1000-230602-1350.main
Windows version: 10.0.19045.4291
Ubuntu 22.04.4 LTS
Windows 10 Enterprise Vserion 22H2 build 19045.4291

**Additional context**
N/A

**Comment by hluk** [comment]
I'm not familiar with `wl-copy` thought there is a command with the same name on Linux in Wayland session which works well.

Can you check if CopyQ even see the new clipboard content (using "File - Show Clipboard Content" - Ctrl+Shift+C)?

**Comment by pbrehm** [comment]
Here is the result when run with 9.0.0.
![image](https://github.com/user-attachments/assets/c7cd41b9-9e1f-4129-9c69-aa9a98ac3bae)

Here is the result when run with 8.0.0.
![image](https://github.com/user-attachments/assets/e934e6e5-fe5c-4d47-b0b8-076771c83746)

I am talking about the wayland command. Except In this case it the ws-copy command is being used in the ubuntu WSL2 with [wslg](https://github.com/microsoft/wslg). This shares the clipboard contents from the virtual machine to the windows host machine.

**Comment by hluk** [comment]
CopyQ does not store (and not even shows) the clipboard on Windows if it contains at least one of the following formats (set to specific value):
- `application/x-qt-windows-mime;value="ExcludeClipboardContentFromMonitorProcessing"`
- `application/x-qt-windows-mime;value="CanIncludeInClipboardHistory"`
- `application/x-qt-windows-mime;value="CanUploadToCloudClipboard"`

See details here: https://learn.microsoft.com/en-us/windows/win32/dataxchg/clipboard-formats#cloud-clipboard-and-clipboard-history-formats

From the screenshot, I assume `wl-copy` sets some of these values.

BTW, you can add the copied value to CopyQ with `copyq add TEXT` or even copy it with `copyq copy TEXT`.

**Comment by pbrehm** [comment]
Thanks for the insight @hluk . Sounds like this is by design and explains why it works in 8.0.0 and not 9.0.0.

To elaborate on my use case. I use neovim and have wl-copy setup to share my clipboard from neovim in wsl to my windows clipboard.

Hopefully if anyone else runs into this they can see that they either can downgrade to 8.0.0 or determine some way to configure wl-copy to exclude these formats.

Thanks again for sharing these details!

**Comment by alexbridge** [comment]
IFF anyone struggle: installed latest v16 + applied this fix https://github.com/hluk/CopyQ/issues/2787#issuecomment-2260800682
Now works. Last year had to pin to v8 but now all good. Thank you @hluk
