### ISSUE TITLE
Does not work with Wayland (ok switching to X11)

### ISSUE THREAD

**Issue by rogercreagh** [hluk/CopyQ#2768]
**Describe the bug**
Ubntu 24.04 default new install (which uses Wayland). CopyQ does not get anything from clipboard.

Switching to XOrg/X11 (which is an option when logging in - gear icon bottom right when password box is open) and it works properly (but lots of other things break

**To Reproduce**
Install CopyQ on Ubuntu 24.04

**Expected behavior**
It should work as before when X11 was used (Wayland is still WayToBuggy to be used but is now necessary)

**Version, OS and Environment**
Damn - I've just uninstalled it cos it didn't work. Would have been the latest version installed with `sudo apt install copyq`  three days ago
- OS Ubuntu 24.04LTS
- Gnome 46, Wayland

**Comment by hluk** [comment]
See Known Issues: https://copyq.readthedocs.io/en/latest/known-issues.html#known-issue-wayland
