### ISSUE TITLE
inconsistent search selection

### ISSUE THREAD

**Issue by Chrysanthemum536** [hluk/CopyQ#2770]
**Describe the bug**

after a single digit is entered into the search, it usually selects the item with that index. but rarely it will prioritize selecting an item containing that digit in the content instead.

**To Reproduce**

**Expected behavior**

it should always jump to the item based on the index like this:

![image](https://github.com/hluk/CopyQ/assets/104331720/034908db-996d-472e-8ba5-4aedc7bf721a)

**Screenshots**

**Version, OS and Environment**

- Application Version (for example 7.1.0)
- OS (for example Windows 11, Ubuntu 22.04, macOS Sonoma 14.4)
- Desktop environment, window manager (if applicable)

**Additional context**

**Comment by hluk** [comment]
This is a feature in CopyQ.

You can enable **Search for numbers** option in History configuration tab in Preferences to change the behavior.

**Comment by hluk** [comment]
Oh, sorry, so you mean that _sometimes_ when entering a single digit, the first item containing the digit is selected instead of the item in that row/index.

Looking into it...
