### ISSUE TITLE
Manually editing the contents of the Item Content window

### ISSUE THREAD

**Issue by iG8R** [hluk/CopyQ#2774]
Is there a way to manually edit the contents of the Item Content window, e.g. the content of `application/x-copyq-tags`?

![image](https://github.com/hluk/CopyQ/assets/11407417/3735e067-56b5-4497-8921-846ed8713853)

**Comment by hluk** [comment]
You can use the following command to edit any item format ([here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)):

```ini
[Command]
Command="
    copyq:
    const d = selectedItemData(0);

    const formats = Object.getOwnPropertyNames(d);
    const i = dialog('.list:Format', formats);
    if (i === undefined) abort();

    const content = formats[Number(i)];
    editItem(selectedItems(0), content);
    "
Icon=
InMenu=true
Name=Edit Data
Shortcut=ctrl+f2
```
