### ISSUE TITLE
Wish to optimize multi-device data synchronization

### ISSUE THREAD

**Issue by mxy493** [hluk/CopyQ#2778]
**Is your feature request related to a problem? Please describe.**

I use copyq on multiple devices and synchronize data via onedrive. Conflicts arise when different devices use the same configuration file and datda file.
![image](https://github.com/user-attachments/assets/bcbc5a2f-d83b-4260-b18f-81efe26824b1)

**Describe the solution you'd like**

I want my configurations and data to be automatically synchronized across multiple devices. Can the problem be solved by having a separate data file for each device, writing data to the current device's file, and merging all data from multiple devices for reading data?

**Describe alternatives you've considered**

**Additional context**

**Comment by hluk** [comment]
This won't be possible, only one instance of the app can use the configuration and data files.

For synchronizing a tab, see: https://copyq.readthedocs.io/en/latest/synchronize.html

Full automatic export and import might be possible using some more complex commands. But this is not a goal of this application.
