### ISSUE TITLE
#2679, #2680 break copying from private/incognito windows on Windows

### ISSUE THREAD

**Issue by ritmation** [hluk/CopyQ#2787]
**Describe the bug**
Since the implementation of #2679 (#2680), CopyQ does not store urls/text from incognito windows (Chrome), or private windows (Firefox).
For some reason, Chrome (this includes Edge too) marks **anything** copied from incognito windows as private, this includes the url in the url bar, which then results in CopyQ ignoring clipboard content (which is copied into the clipboard nevertheless, and can be pasted into other applications, for example, text editors).
Firefox is a little bit more relaxed on this, as it does not mark the url in the url bar as secret, only text in the loaded page.

**To Reproduce**
1. Open any web page in incognito/private browsing mode.
2. Select the url in the url bar (by clicking or pressing Ctrl+L) or any text on the loaded page.
3. Press Ctrl+C or select "Copy" from the context menu (right click)

**Expected behavior**
I expect content from incognito windows to be available in CopyQ history.
Current implementation is clearly an overkill, as it does not add any security (content is still available in the clipboard, it is just not displayed/stored by CopyQ, but is available to other applications).
I would like to see an option to disable this behavior, as it does not increase security nor does it add any useful features, it only creates problems that did not exist before.

**Screenshots**
None needed.

**Version, OS and Environment**
CopyQ Clipboard Manager 9.0.0
Qt: 6.5.3
KNotifications: 6.0.0
Compiler: MSVC
Arch: x86_64-little_endian-llp64
OS: Windows 10 Version 22H2

**Additional context**
I understand that this behavior was introduced to prevent displaying/storing passwords from password managers, which is cool, but it has definitely gone too far, as it breaks actually useful things and creates more problems than it solves, if it ever solved anything.
Additional clipboard formats mentioned in #2679 were introduced to prevent clipboard content from 'leaking' into the [cloud clipboard](https://learn.microsoft.com/en-us/windows/win32/dataxchg/clipboard-formats#cloud-clipboard-and-clipboard-history-formats). 
They were introduced to enhance privacy, not security. CopyQ is a local computer application, it does not sync anything to the cloud, therefore it is already private enough.
Any 'unwanted' content can be removed from the history manually, if necessary, and there is already an option to disable/enable clipboard storing if one does not want to store something in the history. If someone is lazy and does not want to do that, that's their problem and their laziness should not affect other users.

Please do not ignore this issue, as it took me a great deal of time to write it in a concise manner, and I think that my arguments are valid and deserve to be considered.

Thank you.

**Comment by hluk** [comment]
> Current implementation is clearly an overkill, as it does not add any security (content is still available in the clipboard, it is just not displayed/stored by CopyQ, but is available to other applications).

This is not overkill. CopyQ must not store nor process passwords or some data which another app decides should be "secret." Sure, clipboard access is usually ungated and that is somewhat broken, I don't want CopyQ to exacerbate this.

> They were introduced to enhance privacy, not security. CopyQ is a local computer application, it does not sync anything to the cloud, therefore it is already private enough.

The new feature prevents leaking secrets to the disk and potentially to a shared volume. The data on the disk (and in memory) are not encrypted by default.

I understand the feature breaks some behavior, but I cannot let CopyQ process and store some secret data in the same manner as other clipboard data.

> Any 'unwanted' content can be removed from the history manually, if necessary, and there is already an option to disable/enable clipboard storing if one does not want to store something in the history. If someone is lazy and does not want to do that, that's their problem and their laziness should not affect other users.

This is not a solution to the problem. Most users won't go through a history or clean it regularly, or even disable it temporarily.

Also, just storing and processing the secret content could cause enough problems.

The only **solution** I could think of (to let you process this data) is to create a separate script function and let you override it (using the Commands dialog). This would avoid storing it and running automatic commands on it by default.

Let me know if the solution above would work for you.

**Comment by ritmation** [comment]
I do not quite understand what do you mean by 'separate script function'.
I'll describe one of my use cases for CopyQ and how the above mentioned changes broke it for me.

Sometimes I do research on various topics and have a bunch of browser instances in incognito mode open.
I use incognito mode because I do not want the all the items to be stored in my history, as it clutters it up and distracts me later when I type something in the URL bar.

After I'm done researching, I need to save some of the URLs along with some text on the page for context in a text file in a separate folder on my drive (or a separate CopyQ tab), so that I can return to it later (which may be weeks/months).

Before I started using CopyQ, I used to copy the data I need, switch to a text editor, paste, then switch back to browser window, close the tab, and repeat the process for the next tab I wanted to save.

CopyQ greatly simplified this process, as I did not need to switch to a text editor anymore, as anything of interest was stored in a CopyQ history tab.
Once I was done, I would simply copy all the items from a CopyQ tab and save them in a text file for later reference.

Changes introduced in CopyQ v9 broke this process.

So far, the only option I have is to switch back to CopyQ v8 (I did), which works perfectly, but I'd love the benefits of new features and bug fixes of future versions.

Basically, I need text/urls copied from incognito windows to be available in CopyQ history tab.

What I initially wanted is an option (which would be off by default) to revert back to v8 behavior, so that I can enable it.
It even does not to be user visible, a command line switch is good enough for me.
I'm an advanced user and understand the risks involved, but I want to be in control of how I do things on my computer and I'm willing to bear the consequences of my own mistakes, if I make any.
It's very annoying and irritating when other people make decisions for you and limit your options.

If a script function can be called automatically on clipboard content which is marked as private and store it in CopyQ's history tab, that would work for me.
That would, possibly, add unnecessary complexity to CopyQ, which was always simple, predictable and consistent application.
It managed the clipboard, did it well and did not interfere.
I'd love it to stay that way.

Thanks.

**Comment by hluk** [comment]
Fixed. In the next release, it will be possible to enable storing (and processing with automatic commands) these "secret" clipboard using the following **Script command** ([here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)):

```ini
[Command]
Command="global.onSecretClipboardChanged = global.onClipboardChanged"
IsScript=true
Name=Store/Process Secrets
```

**Windows builds** with the fix are here: https://ci.appveyor.com/project/hluk/copyq/builds/50320392/artifacts

**Comment by ritmation** [comment]
Awesome. Thank you very much, I really appreciate it.

**Comment by korason7117** [comment]
you could just use a Note taking app like; Obsidian, Notion or Joplin, along with it's respective browser plugins. 
as for dealing with the urlbar's clutter, use firefox and search in `about:config` for `urlbar.suggest` and toggle the ones you need
