### ISSUE TITLE
Popup main window next to cursor

### ISSUE THREAD

**Issue by richlux** [hluk/CopyQ#2793]
Can we have an option to open the CopyQ main window near where the cursor is located when the keyboard hotkey is pressed (Ctr-Q) similar to how Win-v works in Microsoft Windows?  It would be very convenient so you don't have to move your mouse down to the system tray to activate an item in the list.

Rich

**Comment by ZHAOYAWHY** [comment]
同样需要这样的功能

**Comment by hluk** [comment]
There is a "Show main window under mouse cursor" shortcut.
