### ISSUE TITLE
CopyQ not working on Ubuntu-24-04.LTS Wayland but okay on Ubuntu Xorg

### ISSUE THREAD

**Issue by NemCaBong** [hluk/CopyQ#2798]
**Describe the bug**

When using default Ubuntu (Wayland) I cannot copy anything to the clipboard of CopyQ. The "Clipboard Content" is also empty. And whenever I Ctrl + C anything they don't appear in the CopyQ clipboard.
But on Ubuntu Xorg I can still use CopyQ as normal. But I don't quite like Ubuntu Xorg.

**Expected behavior**

I want CopyQ to work as normal in Ubuntu Wayland version 24-04.LTS
**Screenshots**

![image](https://github.com/user-attachments/assets/9b16a592-3716-4af3-8be4-34b5f23791bb)

**Version, OS and Environment**

- CopyQ Clipboard Manager 7.1.0
- Qt: 5.15.12
- KNotifications: 5.115.0
- Compiler: GCC
- Arch: x86_64-little_endian-lp64
- OS: Ubuntu 24.04 LTS

**Additional context**

CopyQ ERROR [2024-07-31 11:58:34.169] <Client-3885>: Connection lost!
CopyQ Warning [2024-07-31 21:56:14.867] <Server-3442>: [default] QtWarning: QVariantMap DBusMenuExporterDBus::getProperties(int, const QStringList&) const: Condition failed: action
CopyQ Warning [2024-07-31 21:56:14.868] <Server-3442>: [default] QtWarning: QVariantMap DBusMenuExporterDBus::getProperties(int, const QStringList&) const: Condition failed: action
CopyQ Warning [2024-07-31 21:56:14.869] <Server-3442>: [default] QtWarning: QVariantMap DBusMenuExporterDBus::getProperties(int, const QStringList&) const: Condition failed: action
CopyQ Warning [2024-07-31 21:56:14.870] <Server-3442>: [default] QtWarning: QVariantMap DBusMenuExporterDBus::getProperties(int, const QStringList&) const: Condition failed: action
CopyQ Warning [2024-07-31 21:56:14.871] <Server-3442>: [default] QtWarning: QVariantMap DBusMenuExporterDBus::getProperties(int, const QStringList&) const: Condition failed: action
CopyQ Warning [2024-08-01 10:50:11.066] <Server-3416>: [default] QtWarning: Activating Wayland clipboard took 5000 ms
CopyQ ERROR [2024-08-01 10:50:11.073] <Server-3416>: [default] QtCritical: Failed to activate Wayland clipboard

**Comment by janvojt** [comment]
To support pasting and other features, use [Wayland Support](https://github.com/hluk/copyq-commands/tree/master/Scripts#wayland-support) commands ([here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)).

**Comment by robertstrom** [comment]
I know that this is marked **closed** and do not know if this will be seen or not but ...

The solution above talks about pasting support in Wayland. I believe that the person specifically said that they cannot copy in Wayland. Neither can I.

Also, if this is suggesting that I need to go through some contortion of applying special commands to each and every copy or paste when in Wayland that is just not a viable or acceptable solution. If that is the case, then that is downright insane ... crazy talk.

If that is not the case then the modifications needed need considerably more documentation and explanation.

**Comment by user211120** [comment]
"I know that this is marked closed and do not know if this will be seen or not but ..." per [robertstrom](https://github.com/robertstrom) ABV:

Just a Note: CopyQ Seems to work with One exception I have found.  Clipboard does not seem to be updating.

Just updated to Ubuntu 24.04.1 lts (Usually WAIT until .2 AND will Next time, My Bad) with GNOME Desktop Manager.

Tnx, Yall
