### ISSUE TITLE
Crash related to inconsistent tab tree structure after drag and drop

### ISSUE THREAD

**Issue by vsiegel** [hluk/CopyQ#280]
I was dragging a node inside the tab tree to rearrange it.Shortly after, maybe a second, copyq got a segfault. 
I restarted a few seconds later, and found that the tree had a different structure than before.
The tree had two levels before the crash, and there was a node on level tree after, so the change was obvious.
I think that the new arrangement did not exist at some earlier time, so that it could be just the state at most recent write before segfault.

The symptoms made me expect it's caused by bad pointers in the tree structure after drag and drop (or only *while* drag and drop) - but that's a guess.

(I am seeing about three or segfaults per day currently; My use of copyq involves many changes of clipboard data per time, and I have 10000 items on clopboard; Otherwise nothing unusual.)

It's Copyq  2.3.0 on Ubuntu 14.04 - I will update to 2.4.1 now.

**Comment by scottkosty** [comment]
bump: vsiegel can you still reproduce this?
