### ISSUE TITLE
CopyQ stores passwords from KeePassXC password manager even if marked secret.

### ISSUE THREAD

**Issue by janvojt** [hluk/CopyQ#2802]
**Describe the bug**

**IMPORTANT**: I am running copyq on Wayland with Wayland support script.

When password manager clears the password from clipboard (with the `x-kde-passwordManagerHint`), copyq stores it.

**To Reproduce**
1. Run Gnome with Wayland
2. Install copyq and setup Wayland scripts.
3. Copy password from KeePassXC
4. Check that password is ignored by copyq
5. Wait 10 seconds, then KeePassXC clears the password

**Expected behavior**
the password is not stored by copyq!

**Version, OS and Environment**
- Linux Debian
- Gnome
- Wayland
- KeePassXC 2.7.9
- copyq 9.0.0

**Additional context**

When password is copied from KeePassXC, there are 3 formats in the clipboard:
```
$ wl-paste -l
text/plain;charset=utf-8
x-kde-passwordManagerHint
text/plain
```
So the hint is there, I am sure of that. When I show the content of the stored password in copyq however, it only shows the `text/plain` format.

What is essentially done by KeePass to clear the cache is the below  (see [here](https://github.com/keepassxreboot/keepassxc/blob/e48ef80e9c81a16ab971ca0e40e0ab4cfb39defb/src/gui/Clipboard.cpp#L90)):

```
auto* clipboard = QApplication::clipboard();
clipboard->clear(QClipboard::Clipboard);
clipboard->clear(QClipboard::Selection);
QProcess::startDetached("wl-copy", {"-c"});
```

If I clear the password using `wl-copy -c` manually, the behaviour is correct (copyq ignores the password).

Therefore I suspect that while clearing the password from the clipboard via `clipboard->clear()`, the `x-kde-passwordManagerHint` format is cleared first, `text/plain` second, but copyq intercepts it in a moment where I have only `text/plain` format in the clipboard, therefore stores it in the clipboard history.

I think once the recent change exposing `onSecretClipboardChanged` is released, I will be able to work around this in some ugly way, e.g. by ignoring clipboard changes few ms after secret is cleared. However I still wanted to post this to see if it would be possible to resolve in a more elegant way.

**Comment by hluk** [comment]
I believe KeePassXC clears clipboard as a whole, otherwise it is a bug on their side or in Gnome. But I haven't seen any issues with using the app myself (though I use Sway window manager, not Gnome).

> Run Gnome with Wayland

AFAIK, CopyQ does not work in this case - same for any other clipboard manager not implemented as a Gnome Shell extension.

Does KeePassXC run in native Wayland mode? You can force it to start in such mode with: `QT_QPA_PLATFORM=wayland keepassxc`

**Comment by janvojt** [comment]
> AFAIK, CopyQ does not work in this case
It does not work out of the box, but works with [Wayland support commands](https://github.com/hluk/copyq-commands/tree/master/Scripts#wayland-support).

> Does KeePassXC run in native Wayland mode?
I think it is running in Wayland mode, because it outputs a lot of logs when I run with `WAYLAND_DEBUG=1`. I also tried your suggestion `QT_QPA_PLATFORM=wayland keepassxc`, however it does not help.

**Comment by hluk** [comment]
> > AFAIK, CopyQ does not work in this case
> 
> It does not work out of the box, but works with [Wayland support commands](https://github.com/hluk/copyq-commands/tree/master/Scripts#wayland-support).

The command does not fix clipboard monitoring (apps in GNOME cannot read clipboard unless they are active), which I assume was not working on newer GNOME releases. Maybe this changed recently. :thinking:
