### ISSUE TITLE
PowerToys run plugin

### ISSUE THREAD

**Issue by pa-0** [hluk/CopyQ#2803]
**Is your feature request related to a problem? Please describe.**

PowerToys has become something of an essential tool in my opinion, as it greatly enhances Windows OS UX.  (Relatively) recently the team has released a framework for creating plugins for the PowerToys Run applet (like Wox Launcher).  There are currently plugins for translations, Everything Search (from voidtools) and even a Clipboard plugin.  

**Describe the solution you'd like**

It would be AWESOME if we could get a CopyQ integration there since Windows clipboard history **<** CopyQ 😄 If I had the requisite ability, I'd create this myself, but unfortnately I do not.

**Comment by hluk** [comment]
I assume this is not something that would be part of CopyQ itself. The app already supports powerful scripting interface that can be used to write add-ons/plugins in other apps.

I don't use PowerToys (nor Windows currently) so I don't have any reason to implement the plugin.
