### ISSUE TITLE
The text and background colors are the same, resulting in unclear display

### ISSUE THREAD

**Issue by 0ran** [hluk/CopyQ#2805]
When copying text, it is often difficult to distinguish the content due to color consistency when copying along with the background
https://i.imgur.com/S1FDlPC.png
https://i.imgur.com/4RHoVCJ.png
https://i.imgur.com/60b2SK9.png

**Comment by hluk** [comment]
I cannot access the images, but I assume this is a problem with copied HTML. See #1464.
