### ISSUE TITLE
command with Win key does not run

### ISSUE THREAD

**Issue by LeonelRFF** [hluk/CopyQ#2807]
I have been using the commands shown on the page [Ejemplos de comandos — Documentación de CopyQ](https://copyq.readthedocs.io/en/latest/command-examples.html#change-copied-text-to-title-case) and they work fine and I tried to create my own as shown below but the shortcut does not work, it keeps and opening the windows default clipboard

[Command]
Name=Show/hide main window
Command=copyq: toggle()
Icon=\xf022
GlobalShortcut=Meta+v

![image](https://github.com/user-attachments/assets/cfe88a86-e9f3-48ea-8dae-cf9ec6fa6eef)

![Clipboard](https://github.com/user-attachments/assets/897628a5-00d9-450d-9294-7201da611e3c)

**Is your feature request related to a problem? Please describe.**

Previously someone already mentioned the proposition of this feature [#1668](https://github.com/hluk/CopyQ/issues/1668) as explained there it is possible to disable that keyboard shortcut or by installing the PowerToys application, in fact I already had it installed but it overwrites another shortcut I already had for other programs including the browser 😥

**Describe the solution you'd like**

still the program is great and it would be good to incorporate it by default, I have seen that in another program [Flow.Launcher.Plugin.WinHotkey/.github/workflows/pr-check.yaml at main · AminSallah/Flow.Launcher.Plugin.WinHotkey](https://github.com/AminSallah/Flow.Launcher.Plugin.WinHotkey/blob/main/.github/workflows/pr-check.yaml) it has been possible to do something similar simply with a plugin

**Comment by hluk** [comment]
Unfortunately, I don't think I can fix this in CopyQ itself if it does not receive the shortcut.

As a workaround, it may be possible to map the shortcuts in the system or in PowerToys instead of CopyQ. See: [Why do global shortcuts not work?](https://copyq.readthedocs.io/en/latest/faq.html#why-do-global-shortcuts-not-work)
