### ISSUE TITLE
Multiple texts cannot be merged

### ISSUE THREAD

**Issue by supply9243** [hluk/CopyQ#2810]
I don't speak English, if anyone submitted this question, please close this question, thank you.

**Describe the bug**
Multiple entries cannot be merged and edited using V9.0.0, which is not a problem with V8.0.0.

**Screenshots**
![2024-08-10_11-16-04](https://github.com/user-attachments/assets/221ad214-6302-4ec6-8148-9230d2aa3a71)

**Version, OS and Environment**
Windows 10

**Additional context**
You just need to download two versions and test them separately. I have repeated this problem in a virtual machine environment.

**Comment by bonnebulle** [comment]
Hum, am facing the same for now

```
Qt: 5.15.15
KNotifications: 5.116.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Manjaro Linux
```

I realy love this feature....


![Image](https://github.com/user-attachments/assets/00dceb7b-e8a7-4903-bca4-f0200eb6e72f)


How to reproduce...
I have 1, 2, 3, etc in my clipboard (copyq <3)
I select 1, 2, 3
I copy (ctrl+C)
Result : list keep the same, no merging

Thanks for all the work and updates
