### ISSUE TITLE
Desktop todo stickies base on clipboard

### ISSUE THREAD

**Issue by adoin** [hluk/CopyQ#2814]
**Is your feature request related to a problem? Please describe.**
Not a problem

**Describe the solution you'd like**
Open copyQ  filter one of the clipboard, marked Item as a desktop stickiy mark.

**Describe alternatives you've considered**
Some times, I have to create todo item through other tool like Stickies. Then get the text from my clipboard.
It will be perfect if I can do this on copyQ

**Comment by hluk** [comment]
Not sure if I understand fully, but you can create an "In Menu" command (using Command dialog - F6 shortcut) that calls a custom external command/utility.

I'm closing this, because I don't want this feature to be built into CopyQ itself.
