### ISSUE TITLE
Custom Notification

### ISSUE THREAD

**Issue by anffna** [hluk/CopyQ#2816]
Hi, Man, it's me one last time, for now...! So, could you make a script available to show notification with icon or image support, which remains visible until the user takes some action?

**Comment by hluk** [comment]
See [notification()](https://copyq.readthedocs.io/en/latest/scripting-api.html#notification) script function. By setting `.time` to `-1` the notification should stay visible until it is clicked. Unfortunately, this is sometimes overridden in desktop environment which set maximum display interval.
