### ISSUE TITLE
Display html without storing it

### ISSUE THREAD

**Issue by Squirreljetpack** [hluk/CopyQ#2817]
Can we only store plain text, but display html?

I tried the https://github.com/hluk/copyq-commands/blob/master/Display/highlight-code.ini plugin, it's great, but it doesn't work if save and display html is turned off.
I turned on only copy plain text option in pref>options for performance reasons (It works amazing on linux desktop but on my m1 the copyq window takes about a second to show up, is that normal?), but I wonder if maybe syntax highlighting would still be possible.

**Comment by hluk** [comment]
Adding the following command would avoid storing the HTML format ([here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)):

```ini
[Command]
Automatic=true
Command="
    copyq:
    removeData(mimeHtml)"
Icon=
Input=text/html
Name=Avoid Storing HTML
```

**Comment by Squirreljetpack** [comment]
perfect, thanks!
