### ISSUE TITLE
Where is the backup settings? 

### ISSUE THREAD

**Issue by subsubsubsubsubsub** [hluk/CopyQ#2821]
Which file is answering? You need to transfer your new version

**Comment by hluk** [comment]
Please clarify the question or ideally post steps to reproduce the problem and expected outcome.

**Comment by subsubsubsubsubsub** [comment]
I had an old version 7. I downloaded 9. How to transfer the backup settings of the old versions?

**Comment by hluk** [comment]
If you use the portable zip and unpack it into a different folder, copy the "config" subfolder from the previous version to the new one.

Alternatively, use Export functionality (under File menu) in the old version and Import in the new one.
