### ISSUE TITLE
Wayland dependencies on Xorg-only

### ISSUE THREAD

**Issue by Massimo-B** [hluk/CopyQ#2830]
copyq-7.1.0

Building copyq on Gentoo still requires to enable USE=wayland because copyq depends on Wayland. Is that really required on Xorg-only installations? Could that be made optional?

**Comment by hluk** [comment]
I'm not planning to change this myself, since every distro is trying to move (or already moved) to Wayland. But feel free to submit patch for this - Wayland stuff would need to be excluded in `src/platform/x11/x11platformclipboard.cpp` and `src/platform/x11/systemclipboard/CMakeLists.txt`.
