### ISSUE TITLE
hide clipboard content 

### ISSUE THREAD

**Issue by ouyang7923** [hluk/CopyQ#2832]
Whether the clipboard content can be hidden? Only remarks are displayed

**Comment by hluk** [comment]
See [No Clipboard in Title and Tool Tip](https://github.com/hluk/copyq-commands/tree/master/Scripts#no-clipboard-in-title-and-tool-tip) (see [README.md](https://github.com/hluk/copyq-commands/blob/master/README.md) for details on how to add the command).
