### ISSUE TITLE
CopyQ doesn't work with firefox

### ISSUE THREAD

**Issue by psquared-dev** [hluk/CopyQ#2836]
I've assigned `Ctrl+`` as shortcut but when I try to use copyQ while using firefox it doesn't open. 
I tried changing shortcut, but it doesn't seem to work.

Kindly help

**Comment by hluk** [comment]
This is likely Wayland problem - global shortcut don't work there (or work only from other app running in X11 compatibility mode (XWayland). See: https://copyq.readthedocs.io/en/latest/known-issues.html#known-issue-wayland

**Comment by hluk** [comment]
I suggest setting a shortcut in the desktop environment. For show/hide the shortcut would be mapped to `copyq toggle`.

See also: https://copyq.readthedocs.io/en/latest/faq.html#why-do-global-shortcuts-not-work

**Comment by psquared-dev** [comment]
Its working now. Thanks

**Comment by psquared-dev** [comment]
One more thing, in firefox when I paste the content of the clipbboard the focus changes to some to some other window.
Why?
