### ISSUE TITLE
Flickering, shaking text, images

### ISSUE THREAD

**Issue by MadRheeza** [hluk/CopyQ#2837]
When i am pressing "show preview", my text or image flickering, if  i sync something he created and delete his dat.file again and again.
![DraftGif_2024-09-08_13 36 03](https://github.com/user-attachments/assets/dfd2cafe-722f-4e64-9d4f-6692ceb20fd6)
![DraftGif_2024-09-08_13 33 14](https://github.com/user-attachments/assets/da46ca7f-c497-436c-a28d-856154c21e6f)
![DraftGif_2024-09-08_13 26 38](https://github.com/user-attachments/assets/fb2a3f49-5204-4481-be5e-103c337a659b)

**Comment by hluk** [comment]
Thanks for the report. Fixing in #2838.

**Comment by MadRheeza** [comment]
thank you, but tell me pls, what i need to download now, where need to extract files and etcc? Sry ia m new in github, an  little confused, i saw "src" folder here in "Avoid modifying data in display commands" but i didnt find in my computer same name folder for extract, i think i am making wrong. I am using Win 11
