### ISSUE TITLE
Ubuntu 24.04 problems

### ISSUE THREAD

**Issue by JohnP888** [hluk/CopyQ#2842]
1.  Ctrl C does not save to CopyQ
2.3.  No longer can paste to active window after clicking on a saved item, although "paste to current window" is selected in history, need Ctrl V.

Ubuntu 24.04.1 LTS  Just "upgraded".

CopyQ 9.0.0 jammy

Great app, love it, thanks, hope it can be fixed!

**Comment by hluk** [comment]
Unfortunately, this is a known problem. See: https://copyq.readthedocs.io/en/latest/known-issues.html#known-issue-wayland

**Comment by JohnP888** [comment]
Thanks for the info
