### ISSUE TITLE
After importing the settings (after an export) my right toolbar repeats all icons three times

### ISSUE THREAD

**Issue by yolinfl** [hluk/CopyQ#2843]
**Describe the bug**
After importing the settings (after an export) my right toolbar repeats all icons three times

**To Reproduce**
Export settings and import it back again

**Expected behavior**
All icons in the toolbar on the right side will appear multiple times

**Screenshots**
https://imgur.com/a/yAGR8gu

**Version, OS and Environment**
W11 all latest version, CopyQ version 9.0

- Application Version (for example 7.1.0)
- OS (for example Windows 11, Ubuntu 22.04, macOS Sonoma 14.4)
- Desktop environment, window manager (if applicable)

**Additional context**
How can I remove these doublures in icons on the right sidebar?

**Comment by hluk** [comment]
This is not a bug. Import does not replace existing commands and tabs, it adds everything from the import file.

After import, you would need to go into the **Commands dialog** (F6 shortcut) and **remove** the old (or new) duplicate commands.
