### ISSUE TITLE
Keep Open, after use

### ISSUE THREAD

**Issue by lauriehowells** [hluk/CopyQ#2844]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lauriehowells** [comment]
Is it possible to implement a "Keep Open Until Closed" feature, it's very annoying having to open Copy Q every time I want to copy/paste... am using both Windows and Linux

**Comment by lkrms** [comment]
Have you tried changing the "Close When Unfocused" setting under Preferences > General?

**Comment by lauriehowells** [comment]
Sure have, but in both Win 11 and Linux Mint, it still closes

**Comment by hluk** [comment]
> Sure have, but in both Win 11 and Linux Mint, it still closes

Do you mean the main window closes even when "Close When Unfocused" option is disabled?

Is the main window only hidden below other windows (e.g. still available in the panel and with alt+tab)? This can be changed by enabling the "Always on Top" option.

**Comment by GhostShadow0316** [comment]
Can I quickly toggle the "Close When Unfocused" setting with a shortcut or something?
because sometimes I want to paste text I copied one after another
but the windows kept closing after I paste one

**Comment by hluk** [comment]
> Can I quickly toggle the "Close When Unfocused" setting with a shortcut or something?

You can use the following command to toggle the option with shortcut or from toolbar/menu ([here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)):
```ini
[Command]
Command="
    copyq:
    const option = 'close_on_unfocus';
    const value = (config(option) == 'true') ? false : true;
    config(option, value);"
Icon=
InMenu=true
Name=Toggle Close When Unfocused
```
