### ISSUE TITLE
Default installation path is Program Files even in current-user mode

### ISSUE THREAD

**Issue by wikeaka** [hluk/CopyQ#2848]
**Describe the bug**

The default installation path is "C:\Program Files," regardless of whether the installer is in all-user mode or current-user mode. The installer cannot modify the Program Files directory when in current-user mode, so I have to manually change the installation path.

"%LocalAppData%\Programs\CopyQ" (or somewhere the installer can modify without the UAC prompt) would be better for current-user mode.

**To Reproduce**

1. Run the installer.
2. Click "Install for me only."
3. Continue installing until the "Select Destination Location" section
4. Notice that the default location is "C:\Program Files."

**Expected behavior**

The default path is "%LocalAppData%\Programs\CopyQ" when in current-user mode.

**Version, OS and Environment**

- Application Version: 9.0.0
- OS: Windows 10

**Additional Context**

The developer mentioned in #1912 that Inno Setup should handle this issue previously, but it seems that a solution is now available.
https://jrsoftware.org/ishelp/index.php?topic=consts ("Auto Constants" section)

**Comment by LinuxOnTheDesktop** [comment]
I think it _is_ worth changing the code. For, first: some users of the program will be thrown, to some extent at least, by the error. I know that I was. Second, and as a general principle: why default to an option that is highly unlikely to work?
