### ISSUE TITLE
Date & Time color

### ISSUE THREAD

**Issue by MadRheeza** [hluk/CopyQ#2849]
![DraftImage_2024-09-30_00 20 02](https://github.com/user-attachments/assets/7f87e0b8-3d54-433c-bfdc-1f0a8ae3e846)
![DraftImage_2024-09-30_00 24 12](https://github.com/user-attachments/assets/4143cab8-ebf0-4dab-87e1-666a45fc6f29)

Help pls, i am using dark bacckground for copyq, how can i change date and time color to white for this command?

`
copyq:
var time = dateString('dd-MM-yyyy  hh:mm:ss')

var tagsMime = 'application/x-copyq-tags'
var tags = str(data(tagsMime)) + time
setData(tagsMime, tags)
`

**Comment by hluk** [comment]
You can set **the color for all the tags** in the Appearance config section by changing the "Foreground" color of the "Number" (tags use the same color as the item numbers by default).

Changing **the color for specific tags** can be done in Items section:
- Go to the Item config section, Tags subsection
- Set Tag Name to `\1`
- Set Match to `(\d{2}-\d{2}-\d{4} \d{2}:\d{2}:\d{2})`
- Set the color

For details, see: https://copyq.readthedocs.io/en/latest/tags.html
