### ISSUE TITLE
Key to open clipboard window can be accidentally disabled

### ISSUE THREAD

**Issue by vsiegel** [hluk/CopyQ#285]
The "Show/hide main menu" hotkey is implemented as a command, not as a normal key mapping. That creates the risk of disabling the most important key. 

 - One way this may happen is that a user experiments with commands, deactivating some he's not currently interested in, without noticing that one of them is special.

 - Another way is to just disable the whole list when debuging something related to hotkeys.
  - In this case, the user is not even aware of the individual items while unckecking the whole list, so it can happen even with the knowledge that the one item is special.

When the second case happened to me, I was pretty sure that something is severely broken - it did not occur to me that I might have disabled the main key myself.

Thre problem could be solved by making "Show/hide main menu" a normal shortcut.

**Comment by SamHasler** [comment]
The "Show/hide main menu" command is not created by default, the user has to add it, so they should know it's there and what it does. As I understand it, commands are system wide, whilst shortcuts only work while the CopyQ window is in focus, so this request doesn't make any sense.

**Comment by SamHasler** [comment]
Which key is that? There wasn't one configured after installation as far as I could tell.

**Comment by vsiegel** [comment]
In the list shown with the menu ``File``->``Commands/Global Shortcuts``, the first entry is ``Show/hide main menu``. 
This command has a global shortcut defined, I'm using Ctrl-Space here. But I do not think that's the default key.
It is possibly undefined by default, (it would prevent conflicts, good) - but I use the program only by this global key.

From the  perspective of a new user, we could assume the desktop setup, configured by someone else, has defined the key - even if undefined by default. (Here, key conflicts can be avoided.)

I noticed that my proposed solution would not work: making "Show/hide main menu" a normal shortcut. is useless, as the show action can only be triggered from a global key (by definition).

Other possible approaches to solve:
Maybe have a special case to define this one key in the Preferences -> General tab.
Or just do not allow to disable that command by unticking in in the list (the key itself can still be set to none). 
Giving a warning when the command gets disabled would not be understandable by the user in this situation, and mostly get ignored, I think.

**Comment by SamHasler** [comment]
That's what I thought. Since it isn't defined by default, the user would have had to set it up themselves, so they should know what it does. I don't see an problem here.

**Comment by vsiegel** [comment]
Hmm... maybe I'm just missing something - but I think it's more that my explanation did not get the message across. It's an important point to look at it from the perspective of an end user.

I'm not saying me or you will see a problem using the software; It's about "end users" - people who use computers only infrequently, without technical background.

Let me give an example case from that perspective:

Asume CopyQ is part of the default Ubuntu configuration used to set up new computers for the employees of a company. 
In this case, some administrator has choosen and configured the global key, taking care to not create conflicts with other parts of the setup. Also, he wrote a documentation, mentioing the global key.
The user knows how to access CopyQ by global key, and in no other way.
I think he can now easily run into the problem described on top, as soon as he starts to access the CopyQ configuration.

**Comment by hluk** [comment]
User should be always able to access CopyQ configuration with mouse to be able to fix any misconfiguration. CopyQ should be accessible via tray or in panel with windows (if tray is not available, main window cannot be hidden and always minimized instead).

Recently I've added button to access command dialog from shortcut configuration -- hopefully that will make it less confusing.
