### ISSUE TITLE
Script not outputting results

### ISSUE THREAD

**Issue by kevjustice** [hluk/CopyQ#2852]
**Describe the bug**
Running a script from the command line does not show any returned data.  However, commands that take action are doing that action (such as adding an item to the clipboard or showing the interface).

**To Reproduce**
Open CMD.exe or powershell (tested in both admin and non-admin).
Run command like copyq --help
No output.

**Expected behavior**
I expect to see the output.

**Screenshots**
![image](https://github.com/user-attachments/assets/6f915078-7450-41f7-bdb7-cd2ccfc2ff1b)

**Version, OS and Environment**
- Application Version: 9.0.0 running from extracted zip version
- OS Win 11 23H2

**Additional context**
Initially I tried to install via chocolatey and it gave me an error that python 3.12.4 was required but I have 3.12.5.  Instead I downloaded the zip file and the app seems to work fine.  I would rather not downgrade python as I do a lot of python coding.

**Comment by hluk** [comment]
Unfortunately, this is a known problem on Windows (I don't see a way to fix this).

See: https://copyq.readthedocs.io/en/latest/known-issues.html#on-windows-copyq-does-not-print-anything-on-console
