### ISSUE TITLE
Feature requests, this is genius!... A paste all at once button so you could copy everything you need from a file and paste the entire data set into gpt at once...

### ISSUE THREAD

**Issue by mjoe67886** [hluk/CopyQ#2860]
Is your feature request related to a problem? Please describe.

I recently encountered a challenge while working on a project that involved managing a large number of code snippets and properties. Specifically, I was working with multiple Python tooltips in a temporary file, and I was looking for a way to quickly copy and paste them all at once using CopyQ. I used GPT models to try to parse a file and find all multi-line tooltips but after a few tries, I decided to manually search for Python separate line characters in the file.

After finding the lines, I cut them out of the file one by one, sometimes in sections, and ended up with 72 items in the CopyQ clipboard. My goal was to paste all these selected items into GPT, but I didn’t want to paste them one by one. I noticed that CopyQ didn't offer a “paste all at once” button in the right-click menu, which would have been incredibly useful for situations like this, where large amounts of code or text are being processed.

Describe the solution you'd like

It would be extremely helpful if CopyQ had a feature allowing users to paste all selected items at once, ideally through a right-click option or a keyboard shortcut (e.g., Control + Shift + Click). This would streamline the process of transferring multiple clipboard entries at once, especially when working with large code bases or when editing in tools like ChatGPT, which is what I was doing in this scenario.

Describe alternatives you've considered

I worked around the issue by right-clicking and selecting “Edit” in CopyQ, where I could see all the copied items at once and then manually pasted them into GPT. However, this process was slower and more cumbersome than it needed to be. A direct “paste all selected items at once” option would greatly simplify this process.

Additional context

In my use case, I had 72 items selected using Shift + Click, and the lack of a “paste all at once” option in the right-click menu or other available buttons made it more difficult to efficiently paste the selected code snippets. Adding this feature would be a perfect addition for users who regularly handle large volumes of code or text, particularly those who work with tools like ChatGPT for editing or debugging code.

Also one little quick note whenever I double click an item in notepad plus plus it never pastes directly in like it does in visual studio code, I have to right click and choose paste.

**Comment by hluk** [comment]
Not sure if understand the request, but currently you can select multiple items (with Shift or Ctrl) and paste them with Enter key if "Paste to current window option is enabled".

**Comment by hluk** [comment]
You can add the following command to CopyQ to add the button to the toolbar or assign a shortcut to it ([here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)):

```ini
[Command]
Command="
    copyq:
    const sel = ItemSelection().selectAll();
    const text = sel.itemsFormat(mimeText).join('\\n\\n');
    hide();
    copy(text);
    paste();"
Icon=
InMenu=true
Name=Select All and Paste
```

**Comment by mjoe67886** [comment]
I appreciate that so you don't think you like that idea in order to add it
I thought it was a pretty good idea for you know the main feet
functionality I'm sure other people would like
