### ISSUE TITLE
be available on Microsoft Store

### ISSUE THREAD

**Issue by cziss** [hluk/CopyQ#2863]
Hi, I love you CopyQ very much. But, in my work, I have been prohibited to use portable apps and IT won't install me this... So, installing form Microsoft Store is way despite I personally hate Microsoft products. 

Are you planning to publish CopyQ on Microsoft Store?

**Comment by hluk** [comment]
> Are you planning to publish CopyQ on Microsoft Store?

Unfortunately, no. See #890.
