### ISSUE TITLE
Some small details of copyq that need to be perfected!

### ISSUE THREAD

**Issue by sr79368142** [hluk/CopyQ#2866]
Dear hluk, CopyQ is really an excellent invention! It has greatly improved efficiency for my work and I can't live without it for a moment!
I have been bothered by some small details of copyq and I don't know how to solve them? I'm giving you my feedback now, maybe you can give me a solution?
The first thing is that the thumbnails of some images don't show up, the images I copy from Firefox have thumbnails, but the ones I copy from cent browser don't see the thumbnails, I'm not sure what's wrong with that. I've tried all the image related scripts from your script library and none of them have been successful in displaying the thumbnails.
Then my system has always enabled dark mode, and if I enable scrollbars in Appearance, white scrollbars appear. In addition to the white scrollbars on windows, the scrollbars on rich text entries are also white, which is very incongruous, and for this reason I have to turn off these settings related to scrollbars. I hope you will improve the settings for dark mode in a future update, thanks!
If I put the copyq window above the taskbar and hide it, and then exit and restart or call out the copyq window with a shortcut key after the next boot, it takes up a part of the taskbar instead of showing above the taskbar, which is a very strange problem. I'm not a programmer and can't do anything about this!
I don't know if other users care much about these details, but I guess I have a bit of a perfectionist tendency and these problems will keep on bothering me if they are not solved, dear hluk, please help me, I will be very grateful to you!!!!

**Comment by hluk** [comment]
Thanks for using the app. I'm glad you like it. :+1: 

> The first thing is that the thumbnails of some images don't show up, the images I copy from Firefox have thumbnails, but the ones I copy from cent browser don't see the thumbnails, I'm not sure what's wrong with that. 

This is a known issue in web browsers. See: #2084

> Then my system has always enabled dark mode, and if I enable scrollbars in Appearance, white scrollbars appear.

Unfortunately, I won't be able to fix these theming issues myself since they are related to various systems, desktop environments, themes and configurations. I suggest you try changing the [style sheets](https://copyq.readthedocs.io/en/latest/theme.html#style-sheets). Here are some example for customizing scroll bars: https://doc.qt.io/qt-6/stylesheet-examples.html#customizing-qscrollbar

BTW, I think the app itself might be able to change appearance of scrollbars only if "Set colors for tabs, tool bar and menus" option is enabled (in Appearance config section). Otherwise, the Qt GUI framework is responsible for the app theme.

> If I put the copyq window above the taskbar and hide it, and then exit and restart or call out the copyq window with a shortcut key after the next boot, it takes up a part of the taskbar instead of showing above the taskbar, which is a very strange problem. 

Not sure if I understand fully, but this sounds like a behavior of the Qt GUI framework and I don't think I can change it.

**Comment by sr79368142** [comment]
> Thanks for using the app. I'm glad you like it. 👍
> 
> > The first thing is that the thumbnails of some images don't show up, the images I copy from Firefox have thumbnails, but the ones I copy from cent browser don't see the thumbnails, I'm not sure what's wrong with that.
> 
> This is a known issue in web browsers. See: #2084
> 
> > Then my system has always enabled dark mode, and if I enable scrollbars in Appearance, white scrollbars appear.
> 
> Unfortunately, I won't be able to fix these theming issues myself since they are related to various systems, desktop environments, themes and configurations. I suggest you try changing the [style sheets](https://copyq.readthedocs.io/en/latest/theme.html#style-sheets). Here are some example for customizing scroll bars: https://doc.qt.io/qt-6/stylesheet-examples.html#customizing-qscrollbar
> 
> BTW, I think the app itself might be able to change appearance of scrollbars only if "Set colors for tabs, tool bar and menus" option is enabled (in Appearance config section). Otherwise, the Qt GUI framework is responsible for the app theme.
> 
> > If I put the copyq window above the taskbar and hide it, and then exit and restart or call out the copyq window with a shortcut key after the next boot, it takes up a part of the taskbar instead of showing above the taskbar, which is a very strange problem.
> 
> Not sure if I understand fully, but this sounds like a behavior of the Qt GUI framework and I don't think I can change it.

Thank you, hluk!!! followed your instructions and I did!
For a user who doesn't know how to program this is a great experience! Maybe I didn't understand the last point, or maybe it's just QT itself, but it doesn't matter, the important thing is that I learned something new, and I think I should seriously watch some instructional videos on programming or something else!
This screenshot is the window of CopyQ that automatically starts when I turn on my computer, and you can see that it's obviously covering part of the taskbar:
![2024-10-22_181216](https://github.com/user-attachments/assets/968814e4-372f-4418-9d20-94ae73700e9e)

This screenshot shows the window position after I manually adjusted it, and as long as I don't quit CopyQ, it stays in this position and doesn't move.
![2024-10-22_181346](https://github.com/user-attachments/assets/9781fd7d-0627-41b6-86b3-37cacc3f1b87)


I'm not sure why CopyQ doesn't automatically memorize the window position?

Translated with [DeepL.com](https://www.deepl.com/?utm_campaign=product&utm_source=web_translator&utm_medium=web&utm_content=copy_free_translation) (free version)

**Comment by sr79368142** [comment]
Thank you, hluk!!! followed your instructions and I did!
For a user who doesn't know how to program this is a great experience! Maybe I didn't understand the last point, or maybe it's just QT itself, but it doesn't matter, the important thing is that I learned something new, and I think I should seriously watch some instructional videos on programming or something else!
This screenshot is the window of CopyQ that automatically starts when I turn on my computer, and you can see that it's obviously covering part of the taskbar:
![2024-10-22_181346](https://github.com/user-attachments/assets/a7829209-64af-4033-bf29-3fb072d94cbf)

This screenshot shows the window position after I manually adjusted it, and as long as I don't quit CopyQ, it stays in this position and doesn't move.
![2024-10-22_181216](https://github.com/user-attachments/assets/b6b04cb8-439a-4b2c-bbd0-4d8e453f06ed)

I'm not sure why CopyQ doesn't automatically memorize the window position?

**Comment by MarGeb1** [comment]
My workaround for this: When positioning CopyQ's window,  make sure to have a space between taskbar and CopyQ's window that matches the height of your taskbar.
