### ISSUE TITLE
Need to power on and start automatically，

### ISSUE THREAD

**Issue by Luayjie** [hluk/CopyQ#2870]
We need to add a startup auto start option, which is not suitable for ordinary people who do not understand the technology and cannot add tasks for auto start

Double click the image to support copying to a text editor (such as Typora)

**Comment by cybermcm** [comment]
@hluk I can't find an Autostart option in Windows version 10.0.0, is it still there?

**Comment by hluk** [comment]
> I can't find an Autostart option in Windows version 10.0.0, is it still there?

It should be available in the installer.

**Comment by cybermcm** [comment]
Thanks for the reply, I used the .zip version to stay portable... no problem, I'll "autostart" it myself with a task.
Great software!
