### ISSUE TITLE
CopyQ Version 9.1.0 not capturing clipboard on Ubuntu 24.04.1 LTS

### ISSUE THREAD

**Issue by smarzism** [hluk/CopyQ#2872]
**Bug**

After upgrading from Ubuntu 22.04 to 24.04.1 LTS, CopyQ no longer captures copied items. The main window and settings open, but no text or images appear in the clipboard history after copying.

```
~$ CopyQ --version
CopyQ Clipboard Manager 9.1.0~noble
Qt: 5.15.13
KNotifications: 5.115.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Ubuntu 24.04.1 LTS
```

**Comment by smarzism** [comment]
I found a solution by switching to the **Xorg session in Ubuntu**, but it would be better to address this issue to ensure compatibility with the default Wayland session.

**Comment by ahmad96hijazi** [comment]
yes me too same situation

**Comment by hluk** [comment]
This is a known issue, see: https://copyq.readthedocs.io/en/latest/known-issues.html#known-issue-wayland
