### ISSUE TITLE
Character Code for Icons Lookup

### ISSUE THREAD

**Issue by pa-0** [hluk/CopyQ#2874]
When writing commands for CopyQ, the command syntax requires a character code is supplied in order to give the command an icon.  Is there an easy way to look up the character codes for each icon?  Maybe a table that shows each icon and corresponding codes we can access when writing new commands?

**Comment by hluk** [comment]
That is not supported, but you can look up the icons here: https://fontawesome.com/search

**Comment by pa-0** [comment]
awesome thank you.
