### ISSUE TITLE
close window when selected on i3wm

### ISSUE THREAD

**Issue by ViniiR** [hluk/CopyQ#2880]
copyq version: both 9.0.0 and 8.0.0
OS: NixOS 24.05
TWM: i3 4.23

on preferences > history > after item is activated:
close main window checkbox

this option above does not work on i3wm
I have tested it on cinnamon DE and it behaves as expected

**Comment by hluk** [comment]
I think this happens because the window manager does not support minimizing windows. Can you also enable "Hide main window" in Layout section in Preferences?
