### ISSUE TITLE
Add option to change number color of selected item

### ISSUE THREAD

**Issue by Nagidrop** [hluk/CopyQ#2887]
**Is your feature request related to a problem? Please describe.**

Number color of selected items for some light themes are almost invisible. 

"simple" (with "Show Number" option ticked) is the most noticable theme (the "1" is almost invisible).
![look_closely](https://github.com/user-attachments/assets/137687a0-e594-4094-b4e5-bffc8889899c)

"green" theme also suffers from it, but to a lesser extent.
![look_closely_2](https://github.com/user-attachments/assets/6888ca63-1c16-4dbf-ba97-f546812fd163)

**Describe the solution you'd like**

I think adding an option to configure for this is best. 

**Describe alternatives you've considered**

Changing default colors is possibly easier to implement, but it might limit user customization.

**Additional context**

None

**Comment by hluk** [comment]
Thanks for the clear report! Fixing in #2893.

**Comment by Nagidrop** [comment]
> Thanks for the clear report! Fixing in #2893.

Glad it helped you fixed the bug :D Thank you for fixing it and also making CopyQ open source :D
