### ISSUE TITLE
Add a "Pinned" tab that aggregates pinned items from all other tabs 

### ISSUE THREAD

**Issue by pa-0** [hluk/CopyQ#2891]
I'm betting a lot of users would find value in having a "Pinned" tab that displays all pinned clipboard items from other tabs.

I've found myself searching through each tab looking for items I previously pinned when I need to use them.  Having to search through my clipboard history for pinned items kinda defeats the purpose.  

I'd create and share a custom command that accomplishes this but I am unfamiliar with the Qt scripting language.

**Comment by hluk** [comment]
The command can be similar to [Search All Tabs](https://github.com/hluk/copyq-commands/tree/master/Application#search-all-tabs). Here is the alternative version ([here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)):

```ini
[Command]
Command="
    copyq:
    // Name for tab for storing matching items.
    var pinTabName = 'Pinned'

    // Clear tab with results.
    try {
      removeTab(pinTabName)
    } catch (e) {}

    // Search all tabs.
    var tabNames = tab()
    for (const tabName of tabNames) {
      tab(tabName)
      const item_count = count()

      // Search all items in tab.
      for (var j = 0; j < item_count; ++j) {
        // Add matching item to tab with results.
        if (plugins.itempinned.isPinned(j)) {
          const item = getItem(j)
          tab(pinTabName)
          setItem(j, item)
          tab(tabName)
        }
      }
    }

    tabIcon(pinTabName, '')
    show(pinTabName)"
Icon=
InMenu=true
Name=Pinned Items Tab
Shortcut=ctrl+shift+f
```

**Comment by pa-0** [comment]
Thank you!
