### ISSUE TITLE
Add Process Name Matching

### ISSUE THREAD

**Issue by supply9243** [hluk/CopyQ#2895]
**Is your feature request related to a problem? Please describe.**

The current window regex matching method may capture unintended processes.
For example, sub-windows in both a.exe and b.exe processes may share the title "重命名,"
but only the "重命名" title in a.exe should match correctly.

**Describe the solution you'd like**

Implement a process detection feature similar to AutoHotkey’s #HotIf WinActive("ahk_exe a"),
where window detection only proceeds if the process meets the expected criteria.

**Describe alternatives you've considered**

**Additional context**

![00](https://github.com/user-attachments/assets/9a1ca6de-7f00-4124-99cd-0b7f34353474)

**Comment by hluk** [comment]
This is likely not going to happen, unless someone else can implement it, because it is very platform specific.

I suggest using the Filter field instead, if you know a utility that can check the process name.
