### ISSUE TITLE
Need advice how to save the file temporarily and offer it to third party program?

### ISSUE THREAD

**Issue by gnusupport** [hluk/CopyQ#2896]
**Is your feature request related to a problem? Please describe.**
I would like to sort pictures, text into the Dynamic Knowledge Repository by using keyboard shortcut. As if I copy with mouse, I would like to decide when to record the picture or text.

**Describe the solution you'd like**
Need guidance to see similar script, how to save file like PNG, JPG, text, then to offer the file to third party script. Or maybe to invoke that file in memory by using some keyboard shortcut.

**Describe alternatives you've considered**
I can accept file on STDIN, though I prefer to save the file first before giving it to third program.

**Comment by hluk** [comment]
This can be done using `TemporaryFile` class. For example, see the following commands:
- https://github.com/hluk/copyq-commands/blob/dca6425160b36e99012784967219b31b9f0dfeb8/Global/show-clipboard.ini#L14
- https://github.com/hluk/copyq-commands/blob/dca6425160b36e99012784967219b31b9f0dfeb8/Global/convert-markdown.ini#L60
- https://github.com/hluk/copyq-commands/blob/dca6425160b36e99012784967219b31b9f0dfeb8/Global/diff-latest-items.ini#L22

**Comment by gnusupport** [comment]
How do I invoke external program on saved image???

**Comment by gnusupport** [comment]
I solved this issue directly with Emacs, thanks
