### ISSUE TITLE
Can i run a script every time the clipboard is changed?

### ISSUE THREAD

**Issue by hollysheep** [hluk/CopyQ#2906]
**Is your feature request related to a problem? Please describe.**
Because it's not possible to sync clipboard from one device to an other machine in the same network i'm trying to sync the clipboard using ssh. For that i want to run a script every time the clipboard is changed and send the new content to a copyq instance running on the other machine using ssh.

**Describe the solution you'd like**
Run a script and copy the new content to an other machine.

**Describe alternatives you've considered**
Nothing.

**Additional context**
No

**Comment by hluk** [comment]
It is possible, see for example: https://github.com/hluk/copyq-commands/blob/master/Automatic/synchronize-clipboard-with-other-sessions.ini (see [README.md](https://github.com/hluk/copyq-commands/blob/master/README.md) for details on how to add the command)

**Comment by hollysheep** [comment]
This works, very nice.

Can i run copyq in daemon mode in background? At the moment i have a icon in system tray in xfce panel.

**Comment by hollysheep** [comment]
Do i need to add the command in both devices? I tried this but it doesn't work. Is there anything to do so that the both instances can "find" each other?

**Comment by hluk** [comment]
> Can i run copyq in daemon mode in background? At the moment i have a icon in system tray in xfce panel.

The GUI app is the server, and it is needed for the app to operate. You can start a new instance of the app and disable tray icon, storing clipboard, notifications etc:

```bash
# Start "nogui" session
copyq --session=nogui --start-server
# setting the following environment variable makes
# the "nogui" session default for the next commands
export COPYQ_SESSION_NAME=nogui
# you can also avoid the above to set a separate session and
# use the default one (just start the app with: copyq --start-server)

# hide tray icon
copyq config disable_tray true

# disable storing clipboard
copyq config clipboard_tab ""

# disable clipboard notifications
copyq config item_popup_interval 0
```

Managing commands can be also done via command line:

```bash
# import a command - shows the Command dialog
cat command.ini | copyq 'addCommands(importCommands(input()))'

# import a command without opening Command dialog
cat command.ini | copyq 'c = commands(); c.unshift(...importCommands(input())); setCommands(c)'

# show all commands
copyq 'exportCommands(commands())'

# show main window
copyq show
```
