### ISSUE TITLE
Linux Mint: CopyQ crashed while setting key binding and now that key-binding is broken. 

### ISSUE THREAD

**Issue by Fffrank** [hluk/CopyQ#2910]
I was trying to configure CopyQ to appear when I pushed Super-V.  While I was configuring this shortcut in the app, the app crashed.  It does not appear when I press Super-V and inside of the app configuration there are no bindings present.  I then realized that I should be binding the app command through the Cinnamon Keyboard/Shortcut manager.  However, when I try to add a custom command in that dialog it does not recognize the key combination.  Other key combos are recognized but when I press Super-V it only puts a single v in the dialog box. 

I uninstalled CopyQ and it did not change anything. 

If I choose Bindings in the Keyboard/Shortcut manager it does recognize the key combo but does not show any matches. 

I've run dconf-editor and recursively reset all folders under org.gnome and org.cinnamon

 I'm assuming CopyQ corrupted a file somewhere -- where else can I look or try to reset?

**Comment by hluk** [comment]
Try checking and removing any shortcut/global commands from the Commands dialog (F6 from main window in CopyQ).

BTW, even if the app configuration is corrupted, the app should not crash. How did you install the app? What is the version? Can you provide output of `copyq version` (from a terminal)?

**Comment by hluk** [comment]
> I am able to assign Meta+V in that dialog but I can't in the Mint keyboard/shortcut config. So weird!

This is strange, it's usually the other way around.

What command do you assign to the shortcut in Mint? For showing the app window, it would be `copyq --start-server toggle` (the `--start-server` argument tells CopyQ to start the main GUI app if it is not running; `toggle` command shows or hides the main window).

**Comment by Fffrank** [comment]
Yes, I was trying to assign `copyq toggle` (but the --start-server flag makes a lot of sense!)

**Comment by hluk** [comment]
Not sure how else can I help.

Try updating CopyQ to the latest version (and other system packages).

BTW, the CopyQ configuration is usually in `~/.config/copyq/copyq.conf` (the paths are printed with `copyq info`).

Can you get the latest crash traceback with `coredump` (perhaps `coredump info copyq`)?

**Comment by Fffrank** [comment]
Thanks for taking the time to respond.  It does feel like a system issue rather than a CopyQ issue.  I'm not finding a traceback for copyq unfortunately.  And nothing mapped that feels out of place within the config file.  I appreciate the help all the same!

**Comment by hluk** [comment]
Let me close this for now, but let me know if you found out any problem with the app.
