### ISSUE TITLE
CopyQ does not work on macOS Sequoia 15.0 

### ISSUE THREAD

**Issue by sakolesnikov** [hluk/CopyQ#2914]
Describe the bug:
Can not run 9.1.0 on MacOS 15.0.

To Reproduce
Unpack and install it, then open it and the app says "CopyQ.app" is damanged and can't be opened. You should move it to the trash.

Version, OS and Environment
CopyQ 9.1.0
macOS Sequoia 15.0

**Comment by hluk** [comment]
Can you check if [this](https://copyq.readthedocs.io/en/latest/known-issues.html#on-macos-copyq-won-t-paste-after-installation-update) solves the issue?

**Comment by hluk** [comment]
Looks like the same issue as in #2652 (closing this as duplicate). Possible solution: https://github.com/hluk/CopyQ/issues/2652#issuecomment-2018283626
