### ISSUE TITLE
Regarding the issue of turning screenshots into paths

### ISSUE THREAD

**Issue by Cyiming** [hluk/CopyQ#2921]
After taking a screenshot, what is shown in the clipboard is the path instead of the picture. However, in the clipboard that comes with Windows, it will be normally displayed as a picture.

![PixPin_2024-12-01_12-59-01](https://github.com/user-attachments/assets/372bdc2c-209f-4656-b893-79cd0feb6556)
![5be2fb978df006f674912e74b43af96](https://github.com/user-attachments/assets/60e1c432-8d02-4880-866c-014f1a3b4d59)

**Comment by hluk** [comment]
This is likely not a bug. It seems that the system clipboard does not contain image data itself, only a path to an image file.

Try using [Preview Image Files](https://github.com/hluk/copyq-commands/tree/master/Display#preview-image-files) command (see [README.md](https://github.com/hluk/copyq-commands/blob/master/README.md) for details on how to add the command).
