### ISSUE TITLE
Task Bar icon not showing up, Program is running but icon does not showup. Linux Mint Mate 22

### ISSUE THREAD

**Issue by biker25159** [hluk/CopyQ#2926]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version, OS and Environment**

- Application Version (for example 7.1.0)
- OS (for example Windows 11, Ubuntu 22.04, macOS Sonoma 14.4)
- Desktop environment, window manager (if applicable)

**Additional context**

**Comment by hluk** [comment]
What is the version of the app? Can you provide output of `copyq version`?

Does this happen when you log in (the app autostarts)? Does the icon show up if you exit the application (`copyq exit`) and launch it again?

**Comment by hluk** [comment]
There seems to be a lot of strange issues in the logs:

> `No plugins loaded`
> `QtWarning: QSystemTrayIcon::setVisible: No Icon set`
> `Error: execve: No such file or directory`

How did you install the app? Official distro repositories?

Can you try installing the latest version of the app (9.1.0)?

You can also try installing the version from Flatpak. See: https://copyq.readthedocs.io/en/latest/installation.html

Also, a workaround could be also to use `COPYQ_DEFAULT_ICON=1` to force the default icon:

```bash
# exit any running instance
copyq exit

# start the app with default icon (not from the icon theme)
env COPYQ_DEFAULT_ICON=1 copyq --start-server
```

**Comment by biker25159** [comment]
Installed newer version 9.1.0
Still have same Problem, but Workaround Works Great
Thank you for your Help
________________________________

**Comment by hluk** [comment]
I think the problem is likely with the current icon theme in your desktop environment, or that the distribution package for copyq is installing icons in a wrong location.
