### ISSUE TITLE
Shortcut to past the second item in the list

### ISSUE THREAD

**Issue by Tortilio** [hluk/CopyQ#2927]
Hi, I believe that a way to paste the content copied before the last one - in a single step - would be a truly "mandatory" addition!
On a personal basis I often find myself needing to alternate two different clipboard contents, and even more often needing to copy something while the previous content will need a one time pasting in a short time. Apart from my personal use, I guess that a quickly accessible second content would prove precious for many users and workflows (as its rather common availability among clipboard software appears to testify).
I compared several clipboard managers in the past and I found CopyQ packed with features and overwhelming nearly all of them in terms of exclusive and sometimes complex operations, so I felt a little surprised in finding out that such not unusual feature was missing.

About how to achieve it, I think that the second content could be either left in its place (that would probably require a temporary shifting to the first position, pasting, and moving it back to the second position) or moved to the first position and pasted. The latter would probably be a preferable solution, allowing for a continuous alternation between the first two items (I found the same request, unproperly flagged with the "bug" label, expressed on issue [#2615](https://github.com/hluk/CopyQ/issues/2615)).

P.S.: Thanks for the great work and piece of software!

**Comment by hluk** [comment]
See #2014.

There are also commands in the copyq-commands repository to help with that: https://github.com/hluk/copyq-commands/tree/master/Global#select-nth-item (see [README.md](https://github.com/hluk/copyq-commands/blob/master/README.md) for details on how to add the command)
