### ISSUE TITLE
how to list/filter  png/screenshot items  in windows？

### ISSUE THREAD

**Issue by alexlandmeow** [hluk/CopyQ#2929]
how to store all image files? my copyq also has text

**Comment by hluk** [comment]
To search for items containing an image in PNG format, search for `image/png`.

If this is about storing images, CopyQ supports this by default, if the Images plugin is installed. See: https://copyq.readthedocs.io/en/latest/images.html

**Comment by alexlandmeow** [comment]
thank you,but i don't know how to install item image plugin,i see the repo has plugin folder,but it seems to need to compile to exe,i don't know how to do that and i don't find the exe file

**Comment by alexlandmeow** [comment]
i remember i choose all the plugins in the copyq installation wizard ,but when i searched image/png it doesn't work.

**Comment by alexlandmeow** [comment]
thank you,i find the way.

**Comment by alexlandmeow** [comment]
but when i select all the png file.it can't drag to the folder,one time only drag one png file
