### ISSUE TITLE
add shortcut to clipboard entries

### ISSUE THREAD

**Issue by horllste** [hluk/CopyQ#2930]
I dont know if this is possible already so this is more of a question than a feature request

Let say i have 2 entries in the clipboard list

entry 1 = Hello, good morning
entry 2 = have a wonderful weekend

so i am thinking of something where i type, for example

"CTRL + shift 1" in my gmail compose and entry 1 will get pasted
"CTRL + shift 2" in my gmail compose and entry 2 will get pasted

Is something like that possible?

**Comment by hluk** [comment]
See #2014.

There are also commands in the copyq-commands repository to help with that:
- https://github.com/hluk/copyq-commands/tree/master/Global#select-nth-item
- https://github.com/hluk/copyq-commands/tree/master/Application#select-nth-item

(See [README.md](https://github.com/hluk/copyq-commands/blob/master/README.md) for details on how to add a command.)
