### ISSUE TITLE
I have closed the flatpack programme: clipboard is empty

### ISSUE THREAD

**Issue by Golddouble** [hluk/CopyQ#2934]
My system: MX-23 Xfce (Debian 12 based)

When I close a flatpack programme, then the clipboard is empty after.

Is there any way, to let the clipboard keep the content of the clipboard when I close the flatpack programme?

How to reproduce:
1. Install the **flatpack** version of FreeTube
2. open Featherpad
3. open FreeTube and select text
4. press Ctrl+C
5. close FreeTube
6. press Ctrl+V
-> Result: It does not bring the text into Featherpad, because the clipboard is empty. 
(Of course it is still in the history, but it's no more in the clipboard)

When I make the same with diodon-clipboard manager, then it's still in the clipboard. (However, diodon has other disadvantages. This is why I don't want to change to diodon.)
Can I get somehow the same also with copyQ?

Thank you.

**Comment by hluk** [comment]
Try using [Reset Empty Clipboard/Selection](https://github.com/hluk/copyq-commands/tree/master/Scripts#reset-empty-clipboardselection) command (see [README.md](https://github.com/hluk/copyq-commands/blob/master/README.md) for details on how to add the command). This sets clipboard to the last known content, after it is cleared (when the source app closes).
