### ISSUE TITLE
Copy `.png` or `.webp` image to clipboard should render a preview, not a file path. Also: `.webp` doesn't render.

### ISSUE THREAD

**Issue by haakonstorm** [hluk/CopyQ#2936]
## **Is your feature request related to a problem? Please describe.**

- Say you have two images (a `image1.png` and `image2.webp`) saved to disk. 
- Select image1, and copy it to clipboard with ctrl+c. Repeat with image2.
- These are rendered as two file paths in CopyQ:

![image](https://github.com/user-attachments/assets/bfd33bdc-cade-4652-8af8-941c636b5842)

## **Describe the solution you'd like**
The expected result was to see these images as image previews, not their file paths, e.g. like this:

![image](https://github.com/user-attachments/assets/3dd916fc-bbcf-48be-b007-8dcf9bd855f1)

## **Alternatives, and `.webp` image previews not supported at all?**
- Also, I've tried right-clicking images on the web in Firefox, and selected "copy image".
If this image is a `.jpg` or `.png`, the image (preview) is rendered correctly (second in list, the "sample" image).
- If this image is a `.webp` image, it is not rendered at all, only a blank "document" type icon (first in list):

![image](https://github.com/user-attachments/assets/68fbe4de-f134-4781-b5c4-03abd34c6a83)

### Example: 
This is the content of the clipboard with a random `.webp` image copied from this [news article](https://www.cnbc.com/2024/12/20/elon-musk-endorses-far-right-alternative-for-germany-party-in-election.html):

![image](https://github.com/user-attachments/assets/1375afcc-cc60-4a17-ad82-8c338bcd2325)

- It appears more than just the `.webp` image is copied on the clipboard, but all other programs accept the contents of the clipboard as an image when pasted with ctrl+v.

## **Additional context**
- Running latest Windows 11, with `CopyQ` installed via `scoop install`.
- on an ASUS RoG Zephyrus M16 laptop (i9, 64gb).
- Latest Firefox.

**Comment by hluk** [comment]
Thanks for the detail description.

Unfortunately, it seems that a usable image data format is not provided by Firefox (or by Qt GUI framework).

See also:  #2084
