### ISSUE TITLE
Issues with Tags

### ISSUE THREAD

**Issue by m4r71n** [hluk/CopyQ#299]
On Windows XP with revision f2aa8d3b4741e596e7c53ce3e9716e0f45533d70 I found some issues with tags:
- There are predefined commands for the tag `Important` but all ten configured tags are empty. If the configuration of the first tag is changed it will affect the default `Important` tag. I would have expected that the first entry in the tags configuration is named `Important`.
- The toolbar icons disappear if an item with tags is highlighted:
![2014-12-01_205149](https://cloud.githubusercontent.com/assets/6043876/5252220/fadfeb16-799b-11e4-8ce3-b08388151ca0.png)
- Assumed there are only two commands for adding tags and an item already has both tags, there is no sub-menu item. Maybe you could grey out the `Tags` context menu item or add a disabled sub-menu item like `No tag action available`:
![2014-12-01_205510](https://cloud.githubusercontent.com/assets/6043876/5252257/6f866148-799c-11e4-9337-fb4ca908cd39.png)

May I ask what the intention for using tags is? Will it be possible to search for tags? Will it be possible to have tabs which dynamically lists items with a tag?

**Comment by pihentagy** [comment]
Hi, using 2.8.0 and still cannot see how can I add/remove arbitrary tag to an item without scripting. The Tags|Add a Tag and Tags|Remove a Tag seems to be broken

**Comment by hluk** [comment]
@pihentagy I've created an issue #593 for this. Thanks for the report.
