### ISSUE TITLE
Global shortcuts should be accessible from preferences

### ISSUE THREAD

**Issue by AndreaCatania** [hluk/CopyQ#306]
Hi, I have installed the new version of copyQ and I can't find the option that allow to activate the history menu pushing the keyboard shortcut.

I'm sure of that in previous version it was available.

If in this version it's available how can I activate it?

Thanks in advance.

**Comment by hluk** [comment]
This can be set in Command dialog ("Commands/Global Shortcuts" [F6] in "File" menu). In the dialog, click "Add" button and select "Show the tray menu" and you should be able to change global shortcuts for this command.

**Comment by AndreaCatania** [comment]
Ohh thanks, it's really hidden for new users... i think that if you insert this section into preference menu will be more simply. I never see the menus offered from "tabs" before now so i've searched alot in the wrong place.
So thanks for support, Bye.

**Comment by hluk** [comment]
You're not the first one to point that out. It's faster to set up commands from the new dialog but for new users it'll be harder to figure this out. I'll try to duplicate the functionality in preferences dialog too.

**Comment by AndreaCatania** [comment]
Hi hluk. I saw that you didn't fix this problem. I think this might be addressed easly you just need to add a button to the tray menu that allow to open directly this menu

**Comment by hluk** [comment]
In configuration dialog, there is button "Custom Actions and Global Shortcuts" under "Shortcuts" tab.

Also there is "Command/Global Shortcuts" just under "Preferences" in "File" menu.

I think tray menu should contain only the frequently used actions.

Any other ideas how to make this easier to find?

**Comment by AndreaCatania** [comment]
Since This is very important thing, you can put it into preference > general.
I'm imagining an input box where the user insert the key combination to open the tray menu.

**Comment by AndreaCatania** [comment]
I always return on this post to read how to enable shortcut to open try menu. I think that is way better if you put this under `preferences > try` otherwise it could be a good idea put this under `preferences > shourtcut `

**Comment by hluk** [comment]
Alright, I admit that currently the shortcut settings are not user-friendly. So I'm redesigning this.

Basically, it will be possible to set any shortcut (even from user defined commands) from the Shortcut configuration tab in preferences. For most users, this also means that they won't have to open the Command dialog at all - unless they need to create custom commands.

Work-in-progress branch is [command-shortcuts-in-preferences](https://github.com/hluk/CopyQ/tree/command-shortcuts-in-preferences).
