### ISSUE TITLE
Clear Clipboard

### ISSUE THREAD

**Issue by JeremyWW** [hluk/CopyQ#308]
HI,

Could we have an option to clear the clipboard content and / or not show the current / last clipboard content on the main window title bar? Just a privacy thing...

Thanks

**Comment by hluk** [comment]
Should be possible with following command.
```
[Command]
Command=copyq copy \"\"\ncopyq selection \"\"
GlobalShortcut=Meta+Alt+X
Icon=\xf070
Name=Clear Clipboard
```
Unfortunately there is bug in v2.4.3 (fixed in git) -- title is not updated when clipboard is changed using command.

**Comment by JeremyWW** [comment]
Thanks but I have no idea what to do with that. I can see there is an option for creating a command but I cannot get the syntax right.

**Comment by hluk** [comment]
Sorry, I usually write "copy/paste or drag'n'drop the code to the command list in Command dialog [F6]" -- I should find simpler way to share commands.

**Comment by JeremyWW** [comment]
Not usable unfortunately - OK initially but after a while it appears to stop working. Is this the title bar bug you referred to? Assuming so, any idea when you'll release a fix?

**Comment by hluk** [comment]
It'll be fixed in next version. The command above currently only clear clipboard (and X11 mouse selection) -- window title is not updated. I'll try to release new version soon, the bug can be pretty annoying.

**Comment by JeremyWW** [comment]
Great. It is pretty annoying! BTW, can I set CopyQ so it only copies text as simple / pure text if I want to? I'm copying names and addresses from a Word document that are in some kind of fancy rich text format but I want to paste into invoices in pure text quickly, one by one. Currently I have to tell Word to only paste in 'Text' with no formatting, for each invoice. Some way around that?

**Comment by hluk** [comment]
If you click "Add" button in Command dialog, you can add "Paste as Plain Text" which overrides Shift+Enter key so it pastes only plain text. Other possibility is to strip the rich text from clipboard on key or do it for any new clipboard content (but that could be unexpected in some cases).

You can also disallow rich text storing (so Shift+Enter pastes plain text out-of-the-box) -- go to preferences, "Items" tab and uncheck "Web" checkbox under "Text" uncheck "HTML" checkbox.

**Comment by m4r71n** [comment]
I've updated the [FAQ](https://github.com/hluk/CopyQ/wiki/FAQ#9). @hluk maybe you should add a `Tip of the Day` help box.

**Comment by hluk** [comment]
Thanks. I personally find these "Tip" popups bit annoying -- I usually click "Don't show again" after seeing it for the first time :). Perhaps this is not the kind of app that can show such dialogs since main window is hidden at start.

But, yeah, some interactive/searchable help dialog would be useful for many users -- perhaps we can have there just the FAQ for now (but it would need to be translatable somehow too).

**Comment by JeremyWW** [comment]
Thanks @hluk - text pasting / storage methods are fine.

**Comment by m4r71n** [comment]
@JeremyWW sorry for being OT
@hluk Instead of the `Tip of the Day` you could add a default tab `FAQ` to CopyQ. Each question from the Wiki-FAQ could be an item in the `FAQ` tab. Of course the `FAQ` tab would only be created at the first start of CopyQ or by an new entry in the `Help` menu.

**Comment by JeremyWW** [comment]
@hluk Any news on the next release? :)

**Comment by hluk** [comment]
I'll try to make the release this weekend (recently I've been fixing some important functionality so I need to test it properly).

**Comment by JeremyWW** [comment]
Great. I can see 2.4.4. is 'on the way'. Looking forward to the Windows installer - I'll check back later.

**Comment by hluk** [comment]
[Released](https://github.com/hluk/CopyQ/releases/tag/v2.4.4). It took me a while to upload all the files (my network is unusually slow today).

**Comment by JeremyWW** [comment]
Got it. Many thanks!

**Comment by JeremyWW** [comment]
This seems to be OK now with the new release, so I've closed the issue. Thanks.

**Comment by akwala** [comment]
I'd like not to show any content, clipboard or tab, while the main window is closed. I can keep tab items out of the tray menu by choosing an empty tab to be shown in the tray menu.

Is it possible to suppress the display of the clipboard content without clearing the content? The clipboard content appears in the main window title, at the top of the system tray menu and upon hovering over the icons in the system tray and the task bar. Can the content be omitted from all of these automatically based on a toggle for something like "Omit clipboard from app title."

**Comment by hluk** [comment]
I don't think this is possible without some scripting.

If you select "File - Disable Clipboard Storing" from menu the clipboard
content shouldn't be visible but also new clipboard won't be stored in the
list of items (alternatively run "copyq disable" to do this).

With scripting you can use following automatic command which ignores
clipboard (omits displaying it in title etc.) when main window is hidden.
The problem can be that following automatic commands are ignored as well,
so I added "write(...)" below to at least store the clipboard content.

[Command]
Automatic=true
Command="
    copyq:
    if (visible())
      abort()

    write(mimeItems, input())

    ignore()"
Icon=\xf070
Input=application/x-copyq-item
Name=Ignore Clipboard When App Is Hidden

Lukas

**Comment by akwala** [comment]
@hluk That works, thanks!

**Comment by akwala** [comment]
Welll... the command doesn't work consistently. During the initial startup, upon login, it fails as shown in the log excerpt below. I have encrypted tabs, including the one for clipboard history, and the errors appear after I submit the password for decryption. If I exit and restart CopyQ after decryption the command works initially but the clipboard content starts appearing when I copy something. 

Not sure if the above has anything to do with this:  A file "is corrupted or some CopyQ plugins are missing!" error has been occurring at initial startup for quite some time, but all my tabs appear normal (upon decryption).

The script errors:
```
Note [2017-12-17 06:01:57.612] Script-3-11694: ScriptError: Exception in command "eval": Invalid tab
Note [2017-12-17 06:01:57.612] Script-3-11694:    
Note [2017-12-17 06:01:57.612] Script-3-11694:    --- backtrace ---
Note [2017-12-17 06:01:57.612] Script-3-11694:    <eval>() at “ ...”:3
Note [2017-12-17 06:01:57.612] Script-3-11694:    --- end backtrace ---
Note [2017-12-17 06:01:57.616] Server-11694: Command “Ignore Clipboard When App Is Hidden”
Note [2017-12-17 06:01:57.616] Server-11694:    Exit code: 4
Note [2017-12-17 06:01:57.616] Server-11694:    
Note [2017-12-17 06:01:57.616] Server-11694:    ScriptError: Invalid tab
Note [2017-12-17 06:01:57.616] Server-11694:    
Note [2017-12-17 06:01:57.616] Server-11694:    --- backtrace ---
Note [2017-12-17 06:01:57.616] Server-11694:    <eval>() at “ ...”:3
Note [2017-12-17 06:01:57.616] Server-11694:    --- end backtrace ---
Note [2017-12-17 06:01:57.616] Server-11694:    
Note [2017-12-17 06:01:57.616] Server-11694:    1. copyq:  
Note [2017-12-17 06:01:57.616] Server-11694:    2.   if (visible()) abort() 
Note [2017-12-17 06:01:57.616] Server-11694:    3.   write(mimeItems, input()) 
Note [2017-12-17 06:01:57.616] Server-11694:    4.   ignore()
Note [2017-12-17 06:02:01.970] Script-5-11694: ScriptError: Exception in command "eval": Invalid tab
Note [2017-12-17 06:02:01.970] Script-5-11694:    
Note [2017-12-17 06:02:01.970] Script-5-11694:    --- backtrace ---
Note [2017-12-17 06:02:01.970] Script-5-11694:    <eval>() at “ ...”:3
Note [2017-12-17 06:02:01.970] Script-5-11694:    --- end backtrace ---
Note [2017-12-17 06:02:01.972] Server-11694: Command “Ignore Clipboard When App Is Hidden”
Note [2017-12-17 06:02:01.972] Server-11694:    Exit code: 4
Note [2017-12-17 06:02:01.972] Server-11694:    
Note [2017-12-17 06:02:01.972] Server-11694:    ScriptError: Invalid tab
Note [2017-12-17 06:02:01.972] Server-11694:    
Note [2017-12-17 06:02:01.972] Server-11694:    --- backtrace ---
Note [2017-12-17 06:02:01.972] Server-11694:    <eval>() at “ ...”:3
Note [2017-12-17 06:02:01.972] Server-11694:    --- end backtrace ---
Note [2017-12-17 06:02:01.972] Server-11694:    
Note [2017-12-17 06:02:01.972] Server-11694:    1. copyq:  
Note [2017-12-17 06:02:01.972] Server-11694:    2.   if (visible()) abort() 
Note [2017-12-17 06:02:01.972] Server-11694:    3.   write(mimeItems, input()) 
Note [2017-12-17 06:02:01.972] Server-11694:    4.   ignore()
```

**Comment by hluk** [comment]
If the clipboard tab is encrypted and you cancel the decryption (password entry) it will lead to those errors. The error messages are really misleading though.

Does the password entry dialog pop up before those errors?

**Comment by akwala** [comment]
LMK if I should create a separate issue for the "corrupted file" message.

Upon initial startup, the password entry does pop up first. If the password entry and decryption happen within a short time, the "corrupted file" error does not occur. The error occurs if the decryption does not happen within that time.

The script errors didn't happen the last few initial startups, but the script doesn't work. The clipboard content display is not suppressed.

**Comment by hluk** [comment]
> LMK if I should create a separate issue for the "corrupted file" message.

@akwala OK, feel free to create new issue for this.

> The script errors didn't happen the last few initial startups, but the script doesn't work. The clipboard content display is not suppressed.

It won't be suppressed if the `ignore()` is not called. It won't be called if the error occurs (i.e. tab is not yet decrypted).

Following command ignores the error.

```ini
[Command]
Automatic=true
Command="
    copyq:
    if (visible())
      abort()
    
    ignore()
    
    try {
      write(mimeItems, input())
    } catch(e) {
    }"
Icon=\xf070
Input=application/x-copyq-item
Name=Ignore Clipboard When App Is Hidden
```

**Comment by akwala** [comment]
Issue #841 created for "corrupted file" error.

**Comment by akwala** [comment]
```
copyq:

    if (visible())
      abort()
    
    ignore()
    
    try {
      write(mimeItems, input())
    } catch(e) {
    }
```
If the clipboard change results from selecting an item from a CopyQ tab then the `ignore()`doesn't seem to happen. This is the case even after removing the `if (visible()) abort()` statement -- I removed this statement also because I don't see the need to ever display the clipboard content.

Selecting and copying an item from a CopyQ tab changes the clipboard but doesn't add it to the clipboard history. Does it trigger an Automatic command like a clipboard change from outside CopyQ does?

**Comment by hluk** [comment]
@akwala I've been working on improving scripting so that would be possible to control what happens when clipboard changes. [1]

E.g. to disable changing window title you could create new command (with newly introduced type "Script") and override `updateTitle()` function.

```js
var updateTitle = function() {}
```

[1] http://copyq.readthedocs.io/en/latest/scripting-api.html#onClipboardChanged

**Comment by akwala** [comment]
So... I don't want to ever display the contents of the clipboard anywhere in the GUI (except in the history the tab when it's decrypted). With the following code in a "Script" command, the clipboard contents do not appear in the window title and in the tool tip of the system tray icon. 

However, the clipboard contents still appear at the top of the system tray menu  -- in the screenshot below, the string in the clipboard, "enabled",  appears at the top of the menu.

In the Tray preferences, I've set the number of items in the tray menu to 0, and the tab shown in the menu is an empty tab.

How can I suppress the clipboard contents in the system tray menu?

```
copyq:
updateTitle = function() {
 print("updateTitle...");
 serverLog("updateTitle...");
 setTitle();
};

onOwnClipboardChanged = function() {
  print("onOwnClipboardChanged...");
  serverLog("onOwnClipboardChanged...");
  updateTitle();
  hideDataNotification();
  setClipboardData();
};
```
![image](https://user-images.githubusercontent.com/1786/57496393-b5af2900-72a0-11e9-949e-be4d41f83bc6.png)

**Comment by hluk** [comment]
I think the best way now is to use following command to stop setting the clipboard labels in GUI.

```ini
[Command]
Command="
    global.updateClipboardData = function() {}"
Icon=\xf070
IsScript=true
Name=Hide Clipboard Content
```
