### ISSUE TITLE
support icon themes

### ISSUE THREAD

**Issue by kosivantsov** [hluk/CopyQ#310]
Would be great if CopyQ supported third party icons in standard locations (/usr/share/icons/theme_name/size/app/; ~/.icons/ etc) or had a way to create and select CopyQ specific icon themes (to be toggled in Preferences -> Appearence). Even with not so bright default icons CopyQ kinda stands out and clashes in gray/monochromatic environments.

**Comment by hluk** [comment]
Icon themes are supported partially (for icons I could find appropriate candidate from [freedesktop icon naming specification](http://standards.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html)). You need to enable "System Icons" in "Appearance" config tab in CopyQ preferences.

Unfortunately such icon themes are specifically Linux/X11 feature so I don't feel very motivated to implement it further for platform-independent applications.

Though it would be definitely nice to have support for custom icon sets so user can use some colorful icons.

**Comment by kosivantsov** [comment]
What was meant is the "main" icon/icons in the systray, not necessarily icons within the window. Currently on Linux the program looks for them /usr/share/icons/hicolor/scalable/apps/copyq*.svg and I guess on Windows it looks for them in a hardcoded location to, but it would be rather nice to be able to substitute the standard ones either by selecting CopyQ color **and icon** theme (which may include only systray icons), or by selecting user's DE icon theme that includes theme-specific CopyQ icons (the latter is probably not very Windows-friendly and rather X11'ish).

**Comment by hluk** [comment]
Implemented.

Unfortunately there is also bug in KDE (https://bugs.kde.org/show_bug.cgi?id=342906) -- if the application is build with Qt 5 and run on KDE, it must be either installed or app icons must be available in current theme so that correct tray and window icons are displayed.
