### ISSUE TITLE
Support chromium/x-bookmark-entries

### ISSUE THREAD

**Issue by SamHasler** [hluk/CopyQ#311]
Copying multiple bookmark entries in Chrome's bookmark manager produces an entry like this in [CLCL](http://www.nakka.com/soft/clcl/index_eng.html):

![image](https://cloud.githubusercontent.com/assets/54277/5855322/e90b8222-a22e-11e4-98dc-5db65c4a4753.png)

It would be very helpful if CopyQ supported this format.

```
00000000: d000 0000 0000 0000 0200 0000 0000 0000  ................
00000010: 0100 0000 1900 0000 6874 7470 3a2f 2f73  ........http://s
00000020: 7461 636b 6f76 6572 666c 6f77 2e63 6f6d  tackoverflow.com
00000030: 2f00 0000 0e00 0000 5300 7400 6100 6300  /.......S.t.a.c.
00000040: 6b00 2000 4f00 7600 6500 7200 6600 6c00  k. .O.v.e.r.f.l.
00000050: 6f00 7700 9247 0000 0000 0000 0000 0000  o.w..G..........
00000060: 0000 0000 0100 0000 2600 0000 6874 7470  ........&...http
00000070: 3a2f 2f73 7461 636b 6f76 6572 666c 6f77  ://stackoverflow
00000080: 2e63 6f6d 2f3f 666f 6f3d 6261 7223 7465  .com/?foo=bar#te
00000090: 7374 0000 1600 0000 4100 6e00 6f00 7400  st......A.n.o.t.
000000a0: 6800 6500 7200 2000 5300 7400 6100 6300  h.e.r. .S.t.a.c.
000000b0: 6b00 2000 4f00 7600 6500 7200 6600 6c00  k. .O.v.e.r.f.l.
000000c0: 6f00 7700 9347 0000 0000 0000 0000 0000  o.w..G..........
000000d0: 0000 0000                                ....
```

**Comment by hluk** [comment]
You can store the format if you add "chromium/x-bookmark-entries" line into "Active Formats" under "Items" configuration tab, "Data" item.

**Comment by SamHasler** [comment]
Nice to be able to keep them in history. I'd prefer if it just kept everything whether it knows how to present it or not the way CLCL does. That setting was hard to find, and without CLCL I wouldn't know what to put in it.

What I'm asking for in the issue is for CopyQ to be able to convert chromium/x-bookmark-entries to text and offer both as paste options. I think the code that encodes the bookmarks in that format is here: https://chromium.googlesource.com/dart/dartium/src/+/44ec9b3b965335d661a144e11894da3cea999bf3/chrome/browser/bookmarks/bookmark_drag_data.cc
if that helps.

**Comment by hluk** [comment]
CopyQ can display the unknown formats specified in the "Data" preferences similarly to CLCL -- i.e. it shows binary blob, but that's hardly readable.

![image](https://cloud.githubusercontent.com/assets/38054/5987159/8d30f644-a91d-11e4-8794-25b9cdb3bb9b.png)
(You can see this if you use `Ctrl+Right Arrow` when the bookmark item is selected in CopyQ, or move "Data" item to the top in preferences.)

Looking at the code in Chromium, it seems that the format is platform-dependent. That's probably OK for storing data temporarily in clipboard, but not for permanent storage or sharing items on multiple machines.

Handling visual representation for this format in CopyQ is not very good idea. It seems to change a lot and for many people it may not be very useful.

There are lot of other formats that applications use internally -- it's nice to be able to save them -- I use few of those. It would be nice to be able to parse it with some automatic commands so it's easier to see what it contains. But I guess I would need to write few more functions for deserialization of some data types.

**Comment by scottkosty** [comment]
> There are lot of other formats that applications use internally -- it's nice to be able to save them -- I
> use few of those.

Is this the reason why In LyX (a document editor), if I go back to a previously saved item (which I copied within LyX), and paste the CopyQ selected item within LyX, it is pasted using plain text and not with LyX's internal format?

**Comment by hluk** [comment]
Yup,  could be. You can inspect the formats in clipboard in the clipboard dialog (ctrl+shift+c) and add formats to the list mentioned above.

**Comment by scottkosty** [comment]
Immediately after I copy, the item has the following formats:
application/x-lyx
text/html
text/plain

If I then select it, it has the following formats:
application/x-copyq-owner
application/x-copyq-owner-window-title
text/html
text/plain

Note that in the first case, paste works as (I) expected, in the second case, the application/x-lyx format is lost. Is that supposed to happen?

Please let me know if I should start a new feature request instead of hijacking this thread.

**Comment by hluk** [comment]
Did you put the new format to configuration as mentioned above ("Data" item in "Item" configuration tab)? You can check the formats stored in an item in history using F4.

**Comment by scottkosty** [comment]
Ah, no I did not. After doing that, everything works great. Thanks for the help. Would a reasonable feature request be to have a preference option that automatically stores all file formats? I see your concern above that some formats might be bad to store if they are not cross-platform. Perhaps a warning could be issued when the preference is checked? I imagine such a feature request would be a bad idea, but wanted to ask just in case.

**Comment by hluk** [comment]
That's really not a good idea and I found out the hard way. CopyQ did this few years back but many applications can provide many different formats which can take a lot of time when asking for data, transferring and storing them. This can really lock up the application for a moment.

So you should always specify which data to store if they are different from the standard ones used by plugins (i.e. images, rich text etc.).

**Comment by scottkosty** [comment]
Makes sense. Thanks for the explanation, Lukáš.
