### ISSUE TITLE
Colours (Appearance) causing history item display problems

### ISSUE THREAD

**Issue by JeremyWW** [hluk/CopyQ#313]
Edited to clarify:

I have Web and Rich Text on (default). In the 'Web page' image you can see the text I'm copying - this is normally my account number but is obscured in this image for privacy's sake, so I've copied the text 'Account Number' which is still white on a blue background. There is no way that I can get that copied text to show up in CopyQ history, whichever theme / adjustment I use, unless I turn off Web and Rich Text - thus the two other images that show the difference.

Any suggestions?

![web page](https://cloud.githubusercontent.com/assets/544340/5915387/38bac4dc-a5fd-11e4-9976-0cdd41bb257a.png)
![web and rich text on](https://cloud.githubusercontent.com/assets/544340/5915391/40c6286a-a5fd-11e4-9785-d05655627576.png)
![web and rich text off](https://cloud.githubusercontent.com/assets/544340/5915394/4a6a4dba-a5fd-11e4-91d6-b008b26cd65d.png)

**Comment by hluk** [comment]
Well, I probably cannot do anything about this if background and foreground colors are incorrectly set in clipboard.

What's the copied HTML? (You can check the HTML by clicking on the item in history, pressing F4 and selecting "text/html".)

**Comment by JeremyWW** [comment]
<span style="color: rgb(255, 255, 255); font-family: Tahoma, Arial, Verdana, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 16.7999992370605px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255);">Account number:</span>

**Comment by JeremyWW** [comment]
How do I paste that here - it gets shortened when I submit the comment!

**Comment by JeremyWW** [comment]
It'll have to be an image...

![2015-01-27_134450](https://cloud.githubusercontent.com/assets/544340/5919316/a97600e2-a62a-11e4-9856-82c8821c1312.png)

**Comment by hluk** [comment]
OK, it seems that in this case the HTML is rendered correctly :) -- style properties `color` and `background-color` are set to white color. So I cannot really do much about this (you could create some kind of command to remove or fix such HTML).

**Comment by JeremyWW** [comment]
Is it not possible to separate the rich text from the HTML? There have been times when I want to copy text and retain the text formatting but I couldn't give a damn about the background or anything else. It's the text I'm interested in. At the moment, the only workable solution is de-select 'Web' and 'Save and display HTML and Rich Text', but that results in plain text only.

**Comment by hluk** [comment]
Here is command that could solve this issue: [Remove Background and Text Colors](https://github.com/hluk/CopyQ/wiki/Command-Examples#remove-background-and-text-colors)

**Comment by JeremyWW** [comment]
Cheers.
