### ISSUE TITLE
Notes 'Tooltip' positioning

### ISSUE THREAD

**Issue by JeremyWW** [hluk/CopyQ#314]
I have a list of 'Favourite' clips with a note attached to each. To save screen 'real estate' I'm using 'Icon only' for the notes with 'Show Tool Tip' checked. This works except that unfortunately the tool tip appears on the extreme right hand side of the CopyQ window which means you don't always spot it - it's outside your normal 'line of sight'. Also, sometimes the note text within the tool tip gets slightly shortened / 'clipped'.

**Comment by hluk** [comment]
The tooltip text clipping seems to be [Qt bug](https://bugreports.qt.io/browse/QTBUG-26576).

What should be the ideal position for this tooltips? It shouldn't cover next item or important parts of current item.

Perhaps I should replace tooltips with something different.

**Comment by JeremyWW** [comment]
Strange: The tool tip will only appear if the item is selected and then it only appears on the far right the first time you hover. If you keep the item selected the tool tip appears just below when you hover for the second and subsequent times. The tool tip should appear as close to the icon as possible but if you give it a time limit, i.e. it disappears after a few seconds, I don't think it would matter what else it covered - perhaps keep it on the same 'line' for the entry if possible.

**Comment by hluk** [comment]
AFAIK, it was not possible to get the size of the tooltip. So perhaps best solution would be to replace tooltip with something different.

The tooltip really shouldn't be too intrusive. I could try to display it on the outside of current item near icon if there is space.

**Comment by JeremyWW** [comment]
OK. Did you see my issue regarding pasting activated items from the tray?
