### ISSUE TITLE
Paste to current window (Tray) does not work

### ISSUE THREAD

**Issue by JeremyWW** [hluk/CopyQ#315]
As issue title. 'Paste activated item to current window' in 'Preferences' - 'Tray' does not work.

**Comment by JeremyWW** [comment]
Not fixed in 2.4.5.

**Comment by hluk** [comment]
I completely forgot about this. I managed to reproduce when trying it out some time ago but it seems to work well now.

What is the OS (and window manager if any)?

Does this work in any apps?

Is the item at least in clipboard after activated from tray?

**Comment by JeremyWW** [comment]
Win 7 Pro x64.

Seems the selected item is in the clipboard after selecting and Ctrl-V will paste. I was expecting it to 'quickpaste' on double click as it does from the main app window. Also, I think to make this really useful you should be able to select the tab from the tray pop-up on the fly.

**Comment by hluk** [comment]
I'll try to reproduce this on my Windows 7.

I think that if you need to do some searching or changing tabs you should open main window instead and "quickpaste" from there.

Anyway, there is [task for tabs in tray menu](https://github.com/hluk/CopyQ/issues/279) but I don't know how to implement that without cluttering the menu too much.

**Comment by JeremyWW** [comment]
Any progress on this? Not working in 2.4.7.

Thanks.

**Comment by hluk** [comment]
I could reproduce it only if the window was not refocused/reactivated after opening tray with mouse. Similar problem is when the window takes to long to reactivate. Is that the case? Unfortunately, I'm not sure if I can do anything about that.

**Comment by JeremyWW** [comment]
What I'm doing (and my expectations based on other clipboard managers I've used) is setting a hot-key to show the tray menu. Then, with a new blank email for example, I'm bringing up the tray menu with the hot-key combination and double clicking on a clipboard item expecting it to paste to the open email window. I know I can achieve this by showing the main window but the beauty of the tray menu is that it appears at the cursor, so all I'm asking for is the exact same 'double click / quick paste' behaviour from the tray menu as you get from the main window. Bringing up the tray menu, double clicking an item and then having to use Ctrl-V defeats the object which, of course, is speed.

**Comment by hluk** [comment]
You shouldn't double-click menu items (if that's really the case) -- after the first mouse button release the menu disappears so that the second click may actually focus some other window.

**Comment by JeremyWW** [comment]
OK, I'm with you. As I said, I was using it the way I've used other clipboard managers - so it's a habit. Any chance of you making the tray 'pop-up' menu work that way?

**Comment by hluk** [comment]
Single click to activate item is standard behavior for menus and you cannot do anything with selected items in menu anyway, so no, I don't plan on changing that.

I would suggest using keys to navigate the menu so you don't have to put hands off the keyboard while typing. If your workflow is different opening main window under mouse may work better -- it's not implemented and there was an issue for this (#270) which I closed as "won't fix" but perhaps I should reconsider.

**Comment by JeremyWW** [comment]
Just had a look at that - yes, that would be very useful.
