### ISSUE TITLE
[defaults] <C-Ins> / <S-Ins> are not handled as copy / paste.

### ISSUE THREAD

**Issue by d-g** [hluk/CopyQ#317]
CopyQ handles `<C-c>` / `<C-v>` as copy / paste key commands for clipboard items but not `<C-Ins>` / `<S-Ins>`. There are several apps that do not support `<C-c>` / `<C-v>` by default, only `<C-Ins>` / `<S-Ins>`; CopyQ is first one, I met, that does the opposite. So that behavior is unexpected.

It could be set on user’s side very easily, of course:

    [Shortcuts]
    paste_selected_items=Ctrl+V, Shift+Ins
    copy_selected_items=Ctrl+C, Ctrl+Ins

Anyway, I believe, it should be in defaults.

**Comment by hluk** [comment]
I don't specify those shortcuts myself, I use the standard shortcuts provided by Qt GUI framework (see "Standard Shortcuts" in [Qt docs](http://doc.qt.io/qt-5/qkeysequence.html)). So should this be a Qt bug?
