### ISSUE TITLE
Bug: Copy previous shortcut is not working

### ISSUE THREAD

**Issue by AjmalVh** [hluk/CopyQ#322]
I am using CopyQ in a Windows 8.1 machine. 'Paste & Copy previous' command is not working, it is pasting the current item in the clipboard, but not copying the previous item. I tried 'Copy previous' command alone as well, but didn't work.  'Paste & Copy next' is working good.  

Attached is the screenshot of my Shortcuts configurations and output of process manager.

![copyq_prev](https://cloud.githubusercontent.com/assets/1432316/6429955/49a54ba6-c019-11e4-81ce-e2e161413d50.JPG)
![copyq_process_manager](https://cloud.githubusercontent.com/assets/1432316/6429956/49a6c5e4-c019-11e4-9c1d-ff40d45466f6.JPG)

**Comment by scottkosty** [comment]
I just wanted to add a note that it works well for me on Ubuntu with CopyQ 2.4.2.

**Comment by hluk** [comment]
Don't mind the "Failed" in the process manager -- it's actually "Finished" -- will be [fixed](https://github.com/hluk/CopyQ/commit/995abc7e2081f777d97cec6fbff81914eff62f97) in next version.

`next()` and `previous()` in those commands should move selection down/up in clipboard tab (or first tab if clipboard tab is unset) and copy that item.

Can you check if selection is changed in that tab if command is executed?

**Comment by AjmalVh** [comment]
Ahh sorry, that was my mistake. I need to select a previous entry in the Clipboard first, then only previous will work. 
![capture](https://cloud.githubusercontent.com/assets/1432316/6572023/a22652c6-c734-11e4-9886-c6ddde75ad52.JPG)
