### ISSUE TITLE
How to use CopyQ as a text snippet manager?

### ISSUE THREAD

**Issue by orschiro** [hluk/CopyQ#323]
Dear all,

Good text snippet managers are very rare on Linux. But fortunately there is CopyQ and I am wondering whether it can be used to manage text snippets. So far I created a new tab that holds all my snippets. I added content as well as a name to each. Now it looks like this:

![image](https://cloud.githubusercontent.com/assets/170947/6431364/fcce9502-c02d-11e4-9793-4244f9769e65.png)

I am wondering what the best way would be to paste text snippets at the current cursor position. At the moment I first have to open the CopyQ interface, select the snippet and move its content to the clipboard. Can this be simplified?

For instance could we think about a keyboard shortcut that triggers a small dialog window asking for the name of the snippet and then pastes it at the current cursor position?

Thankfully,

Robert

**Comment by hluk** [comment]
I think that pasting a snippet from a special dialog would take same amount of keystrokes.

This is how I do it:
- Open CopyQ with Ctrl+\` while writing text in editor
- Search for item to paste
- Press Shift+Enter to paste to editor

Great solution would be just to write text in window an make CopyQ auto-complete it for you. But this seems to be really difficult to do for all platforms.

Here is perhaps one interesting way to paste snippets:
- Create "Snippets" tab
- Add snippets to the tab as normal text items, e.g. `[img]${Image}[/img]` (`${...}` is variable that can be changed later)
- Use [this command](https://gist.github.com/hluk/af37cd2ca650c92ed0fa) to launch snippet dialog

**Comment by orschiro** [comment]
Many thanks @hluk!

> Use this command to launch snippet dialog

This was exactly what I was looking for. I assigned it to `Meta+P` since `CTRL + 1` is often used by other applications, e.g the web browser. One last question: 

Is it possible for the dialog window to search the title of a snippet and not its content? In the below example search for `Test` instead of the content `12345678`.

![image](https://cloud.githubusercontent.com/assets/170947/6650904/63c08c2e-ca2a-11e4-9a96-11b3730df12c.png)

> Add snippets to the tab as normal text items, e.g. [img]${Image}[/img] (${...} is variable that can be changed later)

I don't understand yet how I can replace the variable content. Can you please explain it a little bit more?

**Comment by hluk** [comment]
Do you mean search for item note instead of item text?

I've updated [the command](https://gist.github.com/hluk/af37cd2ca650c92ed0fa) to use item notes if available.

**Comment by orschiro** [comment]
@hluk 

Fantastic work! This makes CopyQ the perfect Snippet manager.

**Comment by orschiro** [comment]
@hluk 

One short question: Can the search algorithm be improved so that it finds a snipped based on the words it contains but irrelevant on the order of the words?

Please see this screencast: http://a.uguu.se/obbotb_copyQSearchSnipped.mp4

I would like CopyQ to find my snippet name by entering `weekend` (although it is the second word in the snippet name). 

Thanks ahead!

Robert

**Comment by hluk** [comment]
I updated the [gist](https://gist.github.com/hluk/af37cd2ca650c92ed0fa). Unfortunately, there is no immediate response whether the expression matches any items.

**Comment by orschiro** [comment]
Cool, it does work! :+1: 

It's technically impossible to have an immediate response?

**Comment by hluk** [comment]
I don't know how to do this with the standard combo box widget provided by Qt (it would be a bit difficult to implement I guess).

Additionally dialog window created by the script is currently not very dynamic (e.g. you cannot tell it what to do when input text changes).

**Comment by orschiro** [comment]
Alright, never mind. Once you know that the search is "intelligent", you don't really have to rely on the suggestions anymore.

**Comment by orschiro** [comment]
I created a short video that explains how to use CopyQ as a text snippet manager. Hopefully it will help to spread the word about this fantastic piece of software. :)

Link: https://vimeo.com/127392443

**Comment by Heart1010** [comment]
@orschiro Thanks for this video! :+1:

**Comment by orschiro** [comment]
@Heart1010 

Welcome. I am glad to support CopyQ in any possible way.

**Comment by ricardoseriani** [comment]
Nice feature \o.
But I have one question.
It's possible to do a search in all sub tabs too ? e.g:  Snippets/Sql, Snippets/Php, Snippets/html, etc ?

Thanks in advance

**Comment by hluk** [comment]
@orschiro  Nice video! Do you know what was the problem with pasting Signature?

Other nice feature of snippets is that you can use placeholders for variable content. E.g. snippet

```
for (var ${var} in ${container})
  ${container}[${var}]
```

asks user to provide text for `var` and `container` before pasting the snippet.

@ricardoseriani I've changed [gist](https://gist.github.com/hluk/af37cd2ca650c92ed0fa) for the command so it takes items from all sub-tabs.

**Comment by ricardoseriani** [comment]
@hluk Thanks, it's awesome

**Comment by orschiro** [comment]
> @orschiro Nice video! Do you know what was the problem with pasting Signature?

I am glad you guys like it! The problem with the signature was actually related to my request to paste images. The snippet I tried to paste was the image and thus was not properly displayed.

**Comment by Chealer** [comment]
@hluk wrote:
> Great solution would be just to write text in window an make CopyQ auto-complete it for you. But this seems to be really difficult to do for all platforms.

If I understand correctly, Lukas is referring to text expansion. [Espanso](https://espanso.org/) is a _text expander_ which reportedly works well enough that one Ditto user reported abandoning Ditto for Espanso (although I can hardly see how a mere text expander would replace a clipboard manager).
 
> * Use [this command](https://gist.github.com/hluk/af37cd2ca650c92ed0fa) to launch snippet dialog

That Gist is now abandoned, since [the command was integrated in `copyq-commands`](https://github.com/hluk/copyq-commands/blob/master/README.md#snippets).

<details>
  <summary>License</summary>
This comment and any other from myself on this ticket is offered under the terms of CC0 1.0.
</details>
