### ISSUE TITLE
sometimes screen does not redraw

### ISSUE THREAD

**Issue by GiorgosK** [hluk/CopyQ#324]
I am a new user of ubuntu and copyq
I am running ubuntu 12.04 with unity (if you want more info you have to tell me how to get them for you) and the latest COPYQ 2.44 version

sometimes the screen keeps an artifact (no cleared pixels) that correspond to the area that would be occupied by the COPY/PASTE tabs that hold the clipboard entries but I have not realized exactly when this happens, doing any screen work on the window underneath will not clear the screen so I have to open up the copy/paste tabs with the shortcut I have set and then close it and then the screen is working properly again

hope the attached screenshot can tell more than what I can describe here 

on the you see what is left from opening the preferences of COPYQ and than closing it 
underneath it there is the not cleared pixels of the same area that the copy/paste tabs window would hold

![not_cleared_pixels_after_closing_preferences](https://cloud.githubusercontent.com/assets/520704/6444251/216d5cf4-c105-11e4-9394-d18d8ba50716.png)

**Comment by hluk** [comment]
This is issue of the graphics driver or some rendering libraries. Here and there I have similar issues with Ubuntu 12.04 and nVidia card. You can try using desktop environment without effects -- you should be able to change that on login screen in Ubuntu (the alternative choices should be "Ubuntu 2D" and "GNOME Classic (No Effects)").
