### ISSUE TITLE
Using Python Script..

### ISSUE THREAD

**Issue by nemonein** [hluk/CopyQ#325]
Hi.
First I have to tell you this. Thank you for developing this program. ;-)
I have read all FAQ, WIKI here, but I could not find out how to do this.

That's what I want to do.

1. Copy a text1. (This must be Copyq selection(1))
2. Copy a text2. (This must be Copyq selection(2))
3. Run a python script which can take text1 and text2 as arguments and make some output with those arguments.
4. The output of a Python script goes to copyq.

How can I do this with CopyQ?

Thanks in advance.

**Comment by hluk** [comment]
Assuming that the copied text is save in CopyQ, following commands can handle running python on the last two stored text items.

Version with external script (copy/paste the following code to command list in Command dialog [F6]):
```
[Command]
Command="
    copyq:
    var result = execute('/home/lukas/script.py', read(0), read(1))
    
    if (result && result.exit_code == 0)
      add(result.stdout)"
GlobalShortcut=Meta+Alt+Z
Icon=\xf016
Name=Apply Script On First Two
```

Inline python:
```
[Command]
Command="
    python:
    import subprocess, os
    
    exe = os.environ['COPYQ']
    
    def copyq(*args):
      return subprocess.Popen([exe] + list(args), stdout=subprocess.PIPE).communicate()[0]
    
    item1 = copyq('read', '0')
    item2 = copyq('read', '1')
    
    copyq('add', item1 + item2)"
GlobalShortcut=Meta+Alt+Z
Icon=\xf016
Name=Apply Script On First Two
```

**Comment by nemonein** [comment]
Thank you Hluk.
I'll try and I'll let you know.

I hope there would be an instruction manual for Copyq..
Wiki is not sufficient for me. (and for other beginners too? ;->)

**Comment by nemonein** [comment]
It works great!
I took the first method you gave me, and it worked very well.
I used to use Autokey for this kind of job, but from now on, Copyq might replace it.

Thank you again, hluk.
