### ISSUE TITLE
"Open windows on current screen" option does not work on Mac OS

### ISSUE THREAD

**Issue by pzawistowski** [hluk/CopyQ#326]
Despite having selected "Open windows on current screen" option, the screen changes when I try to show the CopyQ window. 

My OS: Yosemite 10.10.2 (14C109)

**Comment by dasebasto** [comment]
I'm not sure I have understood the option correctly, but I think it does not work on my PC either (Windows 10, CopyQ v2.8.1).

When my mouse and the current focused window are on my right monitor, I expect CopyQ main window to popup on my right monitor.
Instead, it just pops up on its previous position.

**Comment by hluk** [comment]
@dasebasto Refer to #616.

**Comment by hluk** [comment]
This is fixed in #616.

You can test it with:
- OS X: https://github.com/hluk/CopyQ/releases/download/v2.8.2-beta-2/CopyQ.dmg
- Windows: https://ci.appveyor.com/project/hluk/copyq/build/job/7fl85b5n1nbqqiis/artifacts

Reopen if it's not fixed.
