### ISSUE TITLE
using copyq command on another language

### ISSUE THREAD

**Issue by rachmadaniHaryono** [hluk/CopyQ#331]
how can i use copyq on another language. as example i have this command in python 
`python -c "import urllib as ul;from string import strip; print ul.unquote_plus(strip('''%1'''))"`
and I want to write it down like this
```python
python :
import urllib as ul
from string import strip
print ul.unquote_plus(strip(input()))#here copyq function
```
can it be done or i have to write script and give the content of the clipboard as an argument

**Comment by hluk** [comment]
There is no library for CopyQ. To execute functions you can execute and pass arguments or input to copyq and get the stdout -- see #325.

Actually if need to use `input()` function you can just read stdin in Python.

**Comment by rachmadaniHaryono** [comment]
hi hluk, 
thanks for the reference. i miss that one. I believe you should put that in wiki.
here is the complete script
```ini
[Command]
Name=urldecode
Command="
    python:
    import subprocess, os
    import urllib as ul
    from string import strip
    
    exe = os.environ['COPYQ']
    
    def copyq(*args):
        return subprocess.Popen([exe] + list(args), stdout=subprocess.PIPE).communicate()[0]
    
    print ul.unquote_plus(strip(copyq('read','0')))"
Input=text/plain
Output=text/plain
InMenu=true
Transform=true
```
