### ISSUE TITLE
Graphical glitch when clicking on the tray icon

### ISSUE THREAD

**Issue by orschiro** [hluk/CopyQ#332]
Dear @hluk,

I see the follow graphical glitch (yellow rectangle) when clicking on the tray icon. I am using eOS which is based on Ubuntu 14.04 together with CopyQ v2.4.4.

![image](https://cloud.githubusercontent.com/assets/170947/6798331/501d7c6a-d20c-11e4-9d4b-11da124219b9.png)

Do you have any idea where this glitch is coming from?

Thanks!

Robert

**Comment by hluk** [comment]
No idea. Unity and others started using indicators instead of tray. Qt doesn't support that, instead there are 3rd party libraries which allow to show Qt tray icon as indicator and allow to use tray menu.

Tray should have a tooltip (if you hover mouse over it) -- maybe this is some bug when showing tool tip.

**Comment by orschiro** [comment]
> Tray should have a tooltip (if you hover mouse over it) -- maybe this is some bug when showing tool tip.

Thanks! I will report back ones I have found a solution. I have another Qt indicator - Dropbox - which does not show that glitch.

**Comment by hluk** [comment]
Strange, I've updated my Ubuntu 14.04 installation (in VirtualBox) and I don't see any tool tips.

Is that perhaps Gnome Shell? I have no idea how to display tray icons there.

**Comment by orschiro** [comment]
It is Pantheon shell from elementary OS. Anyway it is nothing terribly annoying. I was just curious what this yellow rectangle is.

**Comment by hluk** [comment]
Oh, OK, I should read the issue text more carefully next time :).

**Comment by orschiro** [comment]
Issue has been resolved by a recent package update of elementary OS!

**Comment by orschiro** [comment]
I finally figured out what is causing the glitch!

It occurs as soon as I add a note to an item. 

Could you please test if you can reproduce the issue with the attached tab?

Thankfully,

Robert



[test.cpq | uploaded via ZenHub](https://files.zenhub.io/56046086c4c3126521f43deb)

**Comment by hluk** [comment]
Tool tip with item note should be displayed when user [hovers over the item](https://github.com/hluk/CopyQ/blob/f1943acecfbb58446e1f418695ed6653060fa7fc/src/gui/traymenu.cpp#L311).

Problem is probably in [the library](https://bugs.launchpad.net/ubuntu/+source/appmenu-qt) handling the Qt 4 tray menu in Ubuntu.

**Comment by hluk** [comment]
I could remove the tool tip and instead show the note as menu item text -- but I'm not sure how since the either the note or the text would be visible only partially. If you have any ideas let me know (I'll leave this task open for now).

**Comment by orschiro** [comment]
Dear @hluk,

I have found a simple workaround by creating the first item without content: 

![image](https://cloud.githubusercontent.com/assets/170947/10121846/42fdc012-6500-11e5-9e27-cc801da3eb98.png)

**Comment by hluk** [comment]
Tool tips are now shown in tray menu as menu item text. So hopefully this is no longer an issue.

**Comment by orschiro** [comment]
@hluk,

Yes, the problem is solved.

Thanks for providing the Ubuntu deb packages in the latest release!

~Robert
