### ISSUE TITLE
Clear Clipboard suddenly broken

### ISSUE THREAD

**Issue by JeremyWW** [hluk/CopyQ#333]
Clear clipboard doesn't work in 2.4.5. Rolling back to 2.4.4 where it's fine.

**Comment by hluk** [comment]
Which "clear clipboard" are you referring to?

**Comment by JeremyWW** [comment]
I have a 'Clear Clipboard.ini' file which I downloaded from here I think, loaded into 'Commands / Global Shortcuts'. We've communicated on this one before - it wasn't working prior to 2.4.4, then you fixed it and now it's broken again.

**Comment by hluk** [comment]
Please post the `ini` file content here so I can test it.

**Comment by JeremyWW** [comment]
[Command]
Command=copyq copy \"\"\ncopyq selection \"\"
GlobalShortcut=Meta+Alt+X
Icon=\xf070
Name=Clear Clipboard

**Comment by scottkosty** [comment]
If Lukas thinks it is a good idea, I would suggest that Jeremy does a "git bisect". Jeremy, first let's see if Lukas thinks that is a good idea, then if you would like some instructions on how to do it, I'd be happy to give them (please contact me by email at skostysh@princeton.edu in case I forget to check back here).

**Comment by hluk** [comment]
No question about git-bisect usefulness -- I just used successfully yesterday in another project :) -- but very few user can do this. I'll first test this out to see if I can reproduce it and let you know. Thanks Scott.

**Comment by scottkosty** [comment]
OK sounds good. Just to be clear, I was offering to give the instructions to Jeremy (I assumed you knew how to do git bisect), in order to save you some time. My opinion is that if a user can compile and install, then it's quite easy to do a git bisect if they know which steps to follow.

**Comment by JeremyWW** [comment]
Thanks but no thanks. I'm really not that kind of user.

**Comment by scottkosty** [comment]
OK, thanks for the reply Jeremy.

**Comment by hluk** [comment]
This happened due to some optimization: CopyQ didn't process new clipboard content if some formats were only removed from clipboard and no new added. Well, I didn't see that this can break window title updates.

**Comment by JeremyWW** [comment]
OK, sure. Does that mean it's otherwise fixed?

**Comment by hluk** [comment]
Yup, fixed. There were lot of bug fixes so I'll try to release next version soon. Thanks for the report.
