### ISSUE TITLE
Add description of a command

### ISSUE THREAD

**Issue by m4r71n** [hluk/CopyQ#336]
The Snippet command https://gist.github.com/hluk/af37cd2ca650c92ed0fa is awesome but you have to know, that it uses a tab called `Snippets`. Sure the tabname is obvious in the script but it is not obvious that the command uses the item note with fallback to the item self for the selection.
I think that a short description of a command could be useful.

**Comment by hluk** [comment]
I think it might be better to ask user to provide custom options when the command is run for the first time.

I did that for some commands in past but the functionality should be simpler to use and it should allow to easily change these options next time the command is run.

Currently it's possible to do something like this:

```js
function option(description, optionKey, defaultValue) {
  var value = settings(optionKey)
  if (value === undefined)
    value = dialog(description, defaultValue)
  if (value === undefined)
    abort()
  settings(optionKey, value)
  return value
}
var snippetsTabName = option("Tab name for snippets", "snippetsTabName", "snippets")
```

But that doesn't allow to modify the options later.

This really should be implemented so users don't have to edit the command manually.

Any ideas how to handle this?

**Comment by m4r71n** [comment]
Don't get me wrong. I don't need this at all. I'm using comments in my commands and for the specific command mentioned above I've also read the corresponding issue #323.
But how would you explain to the user that this command uses the item note with fallback to the item self for the selection?

> I think it might be better to ask user to provide custom options when the command is run for the first time.

Indeed that would be nice but imo not that important.

**Comment by m4r71n** [comment]
Closed due inactivity
