### ISSUE TITLE
Crash when removing command

### ISSUE THREAD

**Issue by JeremyWW** [hluk/CopyQ#337]
More problems I'm afraid. Trying to add / remove global commands / shortcuts is causing CopyQ to crash. It doesn't happen every time but if I add a new command and remove it, then repeat, I get the crash. This doesn't happen in 2.4.4 so I really have no option now but stick to the previous version.

Don't know whether this is in any way related to running on 64 Bit Windows 7.

**Comment by hluk** [comment]
OK, I can reproduce this. This is quite bad - I'll fix it ASAP.

**Comment by JeremyWW** [comment]
Thanks. The thought occurred to me that whatever the problem is with this may also be the reason why the Clear Clipboard script doesn't work??
