### ISSUE TITLE
Add the ability to record 'copy text' and 'copy path' without 'copy file'.

### ISSUE THREAD

**Issue by babam86** [hluk/CopyQ#338]
Add the ability to record 'copy text' and 'copy path' without 'copy file'.

**Comment by hluk** [comment]
Can you be more specific? Do you mean "when doing Ctrl+C in file manager, save only file/directory paths in CopyQ"?

**Comment by babam86** [comment]
Just record the 'copy text' and 'copy path' without record 'copy file'
in File Manager (like Parcellite).

2015-03-28 20:22 GMT+08.00, Lukas Holecek <notifications@github.com>:

**Comment by hluk** [comment]
I don't use Parcellite -- you have to be more specific.

**Comment by babam86** [comment]
Do not record copying files in the File manager.

2015-03-28 21:02 GMT+08.00, Lukas Holecek <notifications@github.com>:

**Comment by hluk** [comment]
Perhaps "Ignore copied files" automatic command is what you need? To add it, open Command dialog [F6], click Add button, select "Ignore copied files" and click OK.

**Comment by bsdelf** [comment]
"Ignore copied files" works, but it will lost the previous selection, therefore it is necessary to add a "copyq select 0" command.
