### ISSUE TITLE
command for importing command

### ISSUE THREAD

**Issue by SamHasler** [hluk/CopyQ#340]
If I go to https://gist.github.com/hluk/af37cd2ca650c92ed0fa and copy the content, is there a way to write a command that would import it into CopyQ?

**Comment by m4r71n** [comment]
Copy the whole command and just paste it in the commands window of CopyQ

**Comment by hluk** [comment]
I can make importing commands easier but I'm afraid it could lead to some security problems -- this could make it too easy to import commands without user consent.

**Comment by SamHasler** [comment]
It was not obvious that pasting into that list was possible. Perhaps add a "copy from clipboard" button next to the up/down buttons to make it more discoverable.

**Comment by hluk** [comment]
Good idea. Buttons to copy and paste commands added to command dialog.
