### ISSUE TITLE
PPA for latest releases

### ISSUE THREAD

**Issue by orschiro** [hluk/CopyQ#341]
Dear all, 

I someone aware of any Ubuntu PPA featuring the latest releases of CopyQ?

Thanks ahead!

Robert

**Comment by hluk** [comment]
It should be possible to use repository at OBS. I build packages there so you'll be the first to get them :).

Here are appropriate bash commands to add repository for Ubuntu:

    ubuntu_version=$(lsb_release -s -r)
    repo_url="http://download.opensuse.org/repositories/home:/lukho:/copyq/xUbuntu_$ubuntu_version"
    sudo add-apt-repository "deb $repo_url ./"
    wget -q -O - "$repo_url/Release.key" | sudo apt-key add -

Details at: https://en.opensuse.org/openSUSE:Build_Service_Debian_builds#Configuring_sources.list

**Comment by orschiro** [comment]
Thanks very much! I am double-prompted with the sudo command which both fail despite the correctly provided password:

```
 sudo add-apt-repository "deb $repo_url ./" wget -q -O - "$repo_url/Release.key" | sudo apt-key add -
[sudo] password for orschiro: [sudo] password for orschiro: 
Sorry, try again.
```

**Comment by hluk** [comment]
Maybe if you try the last two commands separately (without pasting everything to console)?

**Comment by orschiro** [comment]
Yes, that works. My apologises for mixing the two commands while pasting. The only issue remaining is with the verification of the key. This is what I get when running `apt-get update`:

```
W: GPG error: https://download.01.org utopic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A902DDA375E52366
```

**Comment by hluk** [comment]
Whoa, is that even issue with the command above? Can you check content of `/etc/apt/sources.list`? It should contain (among others):

    deb http://download.opensuse.org/repositories/home:/lukho:/copyq/xUbuntu_14.04 ./

except `14.04` should be your version of ubuntu.

**Comment by orschiro** [comment]
Yes, it contains the correct lines:

```
deb http://download.opensuse.org/repositories/home:/lukho:/copyq/xUbuntu_14.04 ./
# deb-src http://download.opensuse.org/repositories/home:/lukho:/copyq/xUbuntu_14.04 ./
```

**Comment by hluk** [comment]
Possibly it was due to some problem with importing the key for repository. This should be handled with command:

    wget -q -O - "http://download.opensuse.org/repositories/home:/lukho:/copyq/xUbuntu_14.04" | sudo apt-key add -

**Comment by orschiro** [comment]
Solved, thanks a bunch! 

Have a great Sunday,

Robert

**Comment by Heart1010** [comment]
Added that repo to my eOS system also...

```$(lsb_release -s -r)``` in elementaryOS gives me 0.2.1 so I had to change that manually to 12.04 and also add that key manually. Working now! Thanks!

**Comment by beruic** [comment]
Since [ppa.orzanna.de](http://ppa.orzanna.de/) does not exist anymore, where should one go for a PPA now?

**Comment by hluk** [comment]
@beruic Can you add repository as described [here](https://github.com/hluk/CopyQ/issues/341)? Alternativaly you can download and install the package manually from [here](http://download.opensuse.org/repositories/home:/lukho:/copyq/).

**Comment by orschiro** [comment]
Dear @beruic,

Indeed just follow the steps from @hluk outlined above [1].

All I did with ppa.orzanna.de was to provide an overview on the line of code you had to use to add a specific repository to your system.

[1] https://github.com/hluk/CopyQ/issues/341#issuecomment-94270268

**Comment by beruic** [comment]
I missed that one. Sorry. Would be nice with an overview page in the style of the [arc-theme](http://software.opensuse.org/download.html?project=home%3AHorst3180&package=arc-theme)

**Comment by beruic** [comment]
...which unfortunately does not work at the moment.

**Comment by beruic** [comment]
The  [arc-theme](http://software.opensuse.org/download.html?project=home%3AHorst3180&package=arc-theme) page works again.
