### ISSUE TITLE
Possible bug with CopyQ and auto-copy in Linux KDE

### ISSUE THREAD

**Issue by tnilzon** [hluk/CopyQ#342]
Items get auto-copied into CopyQ direct upon text selection. Items is not stored in Linux clipboard, just stored in the CopyQ 'Clipboard' tab. This is regardless of the preferences settings under the 'Clipboard Manipulation' and the 'Store text selected using mouse' in CopyQ Configuration. The same behavior happens if the text is selected with keyboard ctrl+shift+back command. CopyQ actually behaves as if the option 'Store text selected using mouse' was ticked, even if it is not ticked. I have only tried this in Linux Mint 17.1 64bit KDE edition.
/Tomas Nilzon, Sweden

**Comment by hluk** [comment]
Is there possibly other clipboard manager running? Klipper (KDE clipboard manager) could be able to synchronize/duplicate selection to clipboard.

**Comment by tnilzon** [comment]
Hi Lukas,

No there is no other application (as I know of) that could be 
interfering with the Linux Clipboard. By default there is 'Klipper' in 
Linux Mint 17.1 64bit KDE edition. But I have un-installed 'Klipper'.

Regards/ Tomas Nilzon, Sweden

**Comment by hluk** [comment]
I cannot reproduce this -- though I'm currently running Xfce.

Perhaps it's feature of KDE or the application where you select the text. Can you check if text is in clipboard after selecting it with mouse? (Also exit CopyQ or disable selection-to-clipboard synchronization.)

**Comment by tnilzon** [comment]
I have tried to selecting some text whiteout CopyQ running, and then 
there is nothing stored in the KDE clipboard. And also, if I have CopyQ 
running and select some text whiteout copying it, and then go strait to 
for example Libreoffice Writer and do ctr+v nothing is pasted, but if I 
then check the 'Clipboard Tab' in CopyQ, the item is there ready to be 
pasted.

/ Tomas

**Comment by hluk** [comment]
Other thing that comes to mind is that automatic commands are also applied on mouse selections. Do you have an automatic command that adds the new selection to the tab? Do you use CopyQ 2.4.6?

**Comment by tnilzon** [comment]
CopyQ version is 2.4.6

It is not only text selected by the mouse. The behavior is exactly the 
same for text selected by the keyboard command ctrl+shift+left

/ Tomas

**Comment by hluk** [comment]
I think that's the same in apps built on Gtk. Gtk doesn't care how user selected text or even if the text was selected automatically, it will go into X11 selection anyway (this has been very annoying behavior for a long time). But that doesn't explain why selection gets stored in CopyQ without your approval :).

**Comment by tnilzon** [comment]
Yes, and this is a rather new issue for me. I have used CopyQ for quite 
a long time without any problem, but this behavior started when I have 
upgraded to Linux Mint 17.1 KDE (built on Kubuntu 14.04.1), and the 
latest builds of CopyQ (downloaded from your git-hub site, and compiled).

/ Tomas

**Comment by hluk** [comment]
I just noticed this behavior with URLs. Quick investigation revealed that selection is added to list because of an automatic command. Can you check if you have some automatic commands with "Copy to tab" option set or that could add items using script?

Because of this I had to fix recent command on gist (https://gist.github.com/hluk/b598ab08e00ce9618b33).

**Comment by tnilzon** [comment]
Hi, yes I had the command 'Move to trash' which have the "Copy to tab" 
option set. I tried to disable this command and closed and restarted 
CopyQ, but unfortunately this made no difference.

:-(


/ Tomas

**Comment by tnilzon** [comment]
Some more information:

I just noticed that items is actually not placed in the 'Clipboard' tab 
(or in the Linux Clipboard) upon selection. It is only showing up in the 
CopyQ notification (as if it were stored). To get the selection actually 
copied, you have to right click 'Copy' (or by ctrl+c) and then the item 
is showing up once more in the CopyQ notification (this time correct 
behavior).

Strange...


/ Tomas

**Comment by hluk** [comment]
The notification (plus window title and tray tooltip change) should pop up only when clipboard changes. I actually had to fixed that when trying to reproduce this issue (4b198821468c566414211305ccfb97652eed6082, 505a3a8617b3661d17e15a2bc4599bca7c1fb390). Though if you have "Paste mouse selection with keyboard" option enabled the popup will still show since the selection is store in clipboard.

**Comment by tnilzon** [comment]
I have now downloaded and compiled the latest CopyQ zip file. The CopyQ 
notification appearance now seems to work as it should. But there is 
still an unwanted behavior from CopyQ upon text selection. I have a 
custom command active (a sound indication when clipboard content is 
changed). This custom command triggers every time a text is selected 
(regardless if it is copied to clipboard or not).

A screen dump is attached showing my CopyQ commands.

/ Tomas

**Comment by hluk** [comment]
Well, yes, as I mentioned before that's because automatic commands are applied on selections too.

If you want to ignore selection completely, you can put following command at the top of your command list.

```ini
[Command]
Automatic=true
Icon=\xf016
Input=application/x-copyq-clipboard-mode
Name=Ignore Selection
Remove=true
```

**Comment by tnilzon** [comment]
Great, that fixed it. Thanks a lot!

/ Tomas
