### ISSUE TITLE
Adding images as snippet

### ISSUE THREAD

**Issue by orschiro** [hluk/CopyQ#343]
Dear @hluk,

In reference to https://github.com/hluk/CopyQ/issues/323, is it possible to add image types to a snippet to be able to paste these (e.g. useful to paste your own scanned-in signature into graphical editors). 

Thanks!

Robert

**Comment by hluk** [comment]
I've updated the [gist for the command](https://gist.github.com/hluk/af37cd2ca650c92ed0fa).

**Comment by orschiro** [comment]
I tried your updated version. But it still fails to paste an image file properly into an item. 

I hope the screencast helps to explain my problem: http://a.pomf.se/hsgynj.mp4

**Comment by hluk** [comment]
Internal editor doesn't support pasting images. It's just for plain text.

**Comment by orschiro** [comment]
I see, this makes it clear now. Thanks!

Do you have any plans to expand support towards images? :)

**Comment by hluk** [comment]
I've created branch [images_in_editor](https://github.com/hluk/CopyQ/tree/images_in_editor) which contains support for pasting and dropping images to editor.

I don't want to use the code as it is now because there are few problems. For example the HTML that is saved contains font description which can be unwanted and annoying when pasting the item. Also it seems difficult to find out if after editing the item needs to be saved as HTML (if it does contain images or possibly other rich text features).

**Comment by orschiro** [comment]
@hluk 

You're doing an amazing job with CopyQ! I am happy to donate a bounty for final release of the image pasting soon. :+1: 

https://www.bountysource.com/transactions/28871?receipt=1

**Comment by orschiro** [comment]
Nice, thank you, Lukas!

**Comment by hluk** [comment]
@orschiro No problem. Please test it and complain before I release it :).

One issue it still has is that HTML will stay in the item even though all images are removed (I haven't find a way to fix this yet).

I plan to extend this and add few buttons to set font formatting -- at least bold, italic, fixed-width.

**Comment by orschiro** [comment]
Sure, I am willing to test it and help!

Do you think you can release an Alpha or Beta as a deb package that I can
easily install?

**Comment by hluk** [comment]
@orschiro I'll try to automate building [beta packages on OBS](https://build.opensuse.org/package/show/home:lukho:copyq/CopyQ-beta) and let you know.

**Comment by hluk** [comment]
@orschiro Done.

Direct links to `copyq_2.7.1.r41.g13d52b5_amd64.deb`:
- [Debian](http://download.opensuse.org/repositories/home:/lukho:/copyq/Debian_8.0/amd64/copyq_2.7.1.r41.g13d52b5_amd64.deb)
- [Ubuntu 16.04](http://download.opensuse.org/repositories/home:/lukho:/copyq/xUbuntu_16.04/amd64/copyq_2.7.1.r41.g13d52b5_amd64.deb)
- [Other distro/architecture](http://download.opensuse.org/repositories/home:/lukho:/copyq/)

**Comment by orschiro** [comment]
I am sorry, I don't understand how to paste an image to the snippets:

![copyq](https://cloud.githubusercontent.com/assets/170947/19212494/7337fb6e-8d52-11e6-80c9-b3eca93327b0.gif)

**Comment by hluk** [comment]
Can you check if an image format is in clipboard? (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>C</kbd> to open clipboard dialog.) You have to copy an image instead of a file.

**Comment by orschiro** [comment]
My bad. It's working perfectly. Thanks a lot!
