### ISSUE TITLE
Search for images in history

### ISSUE THREAD

**Issue by SamHasler** [hluk/CopyQ#345]
It would be useful to have an easy way to search for images in the history.

Perhaps this could be implemented in a general way so that you could search for any particular type of entry.

**Comment by hluk** [comment]
Implemented: MIME types stored in items are searched in addition to item content.

It's easy to use but may return more results than expected -- e.g. searching for `image` returns all images but also items containing text "image" -- with regular expressions you can be more specific with `^image/`.

**Comment by hluk** [comment]
Just heads up: I have to change the behavior for matching formats because it's annoying to search for "text" and it returns all text items (since format is `text/plain`). For more info see #466.
