### ISSUE TITLE
Chocolatey package for Windows

### ISSUE THREAD

**Issue by majkinetor** [hluk/CopyQ#350]
Would you consider automating chocolatey package and push ? This is trivial and would allow people to automate CopyQ installation in a very quick way, especially since by default PowerShell 5 comes with a Chocolatey provider so on newest versions of Windows installation would be one liner.

Here is the code: https://github.com/majkinetor/chocolatey
Here is the repo: https://chocolatey.org/packages/copyq/2.4.6

**Comment by hluk** [comment]
To have a package manager on Windows would really save a lot of time for me.

I'm not sure what can I do to help here. AppVeyor CI automatically builds the app but only newer Qt libraries can be used there and those still contain a lot of unnecessary stuff which makes the application bundle much bigger than the current releases.

I build and upload the release versions for Windows manually and unfortunately it's not trivial process.

**Comment by majkinetor** [comment]
> I'm not sure what can I do to help here

You don't have to do anything particular:

- Clone the repo (or recreate it in a structure you want/like)
- Install chocolatey (10 seconds)
- Open the chocolatey account and get the API key (30 seconds)
- `cinst nuget.commandline` (5s)

After that initialization just replace the [url](https://github.com/majkinetor/chocolatey/blob/master/copyq/tools/chocolateyInstall.ps1#L4) once you release a new version and push it to the chocolatey repo: In the package directory run `..\push.ps1 [API_KEY]`. Once specified API_KEY parameter can be omitted if you use my `push.ps1`.

If you use some automation to upload MSI file to github that could be a part of it. All in all it would require you 10 minutes or so once and later just changing URL.

Now, on chocolatey this needs to get approved to get visible in search and without specifying version but with explicit version it is available immediately. 

I can continue to do this TBH but it is really responsibility of author to do such thing. Windows culture is not ATM like that so the chocolatey work is almost 100% done by volunteers.  

Furthermore, I guess having a choco package would popularize the app far more on WIndows now and the fact is that it totally deserves all the attention it can get.

**Comment by majkinetor** [comment]
Just to let you know, I automated installation of chocolatey package so latest version on github will now be available on Windows in unattended fashion simply by typing `cinst copyq`. You could also install any previous version by appending `--version` option. 

Cheers, and keep up a good work.

**Comment by hluk** [comment]
Thanks for your work!

I didn't have time to see how chocolatey works yet. I currently run Windows in VM and I've been only testing and fixing stuff there the last few days.

Is it possible automate updating one separate package for unstable version of CopyQ from master branch on git? This could help testing the app for some people.

**Comment by hluk** [comment]
I finally managed to try chocolatey -- very convenient -- I'll probably use it on my other Windows machines.

I noticed that the package uses the installer from github so disregard my comment about having package for unstable version.

Thanks again for keeping the package up-to-date.

**Comment by majkinetor** [comment]
Package will always be up to date as the process of package creation is automated. I thought it would be good to put it on your build infrastructure, but I can put it in task scheduler so its not a big difference (as long as I am using it, that is).

As long as you don't remove releases from github you will be able to install any version.

> Is it possible automate updating one separate package for unstable version of CopyQ from master branch on git? This could help testing the app for some people.

I take the link from releases section. In order to get the master one should either a) create new package copyq-pre for instance or b) you also release unstable version and make it part of the version in which case my package will work for that.

Chocolatey allows you the creation of private packages which cant be discovered but you must give the name and full version of the package to other people. This sounds like perfect for testing as, generally, nobody else is aware of the package.

**Comment by hluk** [comment]
Closing.

@majkinetor Let me know if there is anything specific I can help with. Thanks for maintaining the CopyQ package on Chocolatey.
