### ISSUE TITLE
Edit copy buffer

### ISSUE THREAD

**Issue by amerlyq** [hluk/CopyQ#351]
When launching '$ copyq edit -1' from terminal, having editor set up into 'urxvt -e vim %1', always new window opens to edit entry. Is it possible to open vim in same terminal? Of course something simple like 'vim %1' currently don't works. And if it would, you couldn't use it on global shortcut, as you need terminal in first hand. Maybe separate settings? All it's possible with current functionality?

**Comment by hluk** [comment]
CopyQ doesn't know anything about the custom editor (which can be application or a script anyway), it only provides temporary file to edit. User must provide the command to launch the editor.
