### ISSUE TITLE
QtTest4.dll missing from Windows setupVer 2.4.7

### ISSUE THREAD

**Issue by ronenrozner** [hluk/CopyQ#352]
self install .EXE file install successfully,  but when I launch CopyQ 2.4.7 i get an error that QtTest4.dll is missing. Zip file contain the dll and after copying it to the CopyQ install folder the application run correctly.

**Comment by hluk** [comment]
Damn, I forgot to disable tests in release build. Unfortunately, I don't know when I will have time to rebuild it and upload binaries :(.

For now, you can download Qt 5 build from https://ci.appveyor.com/api/buildjobs/nbng0v1jlw8vetur/artifacts/copyq.zip .

**Comment by JeremyWW** [comment]
Qt 5 isn't usable for me - doesn't remember some of it's preferences. I'm also having trouble setting hot-key combinations. Going back to 2.4.6 until you rebuild 2.4.7 - hopefully soon! By the way 'Paste activated item to current window' in 'Preferences' - 'Tray' still isn't working.

**Comment by hluk** [comment]
I've re-uploaded the files.
