### ISSUE TITLE
New Option: Start w/Clipboard storing disabled

### ISSUE THREAD

**Issue by ronenrozner** [hluk/CopyQ#353]
I use CopyQ as a text clip "storage" with pre-defined set of text clips i need for my daily work. I rarely add new clips and would like to have the application start with the Clipboard storing disabled.

thank you !

**Comment by hluk** [comment]
Just clear "Tab for storing clipboard" in "History" config tab.

You can also add new command to ignore clipboard changes completely (don't even show clipboard in window title and tray tool tip).
1. Open Command dialog [F6].
2. Click Add button, select "Ignore copied files" and click OK.
3. Clear "Format" text box (so any clipboard content matches).
4. Click OK.
