### ISSUE TITLE
v2.4.7 no indicator icon shown

### ISSUE THREAD

**Issue by orschiro** [hluk/CopyQ#354]
Dear @hluk,

In the latest version `v2.4.7` the indicator tray icon is no longer shown on my elementaryOS (Ubuntu based) system. Instead it keeps to stay opened as a window that cannot be closed unless I force CopyQ to close (exit).

Can anyone else confirm similar behaviour on a Linux distribution?

Thankfully,

Robert

**Comment by scottkosty** [comment]
I don't have any problems on Ubuntu. Did it work before for you? If so, in bug reports like these it is always useful if you mention such information. For example, does it work for you with 2.4.6?

**Comment by orschiro** [comment]
@scottkosty 

Thanks for your suggestion to downgrade first and test if it resolves the issue. In fact, it doesn't. I suspect an issue with a recent eOS update. I will investigate the problem and report back how I solved it.

**Comment by scottkosty** [comment]
@orschiro , thanks for keeping us updated. Let us know if you find anything else out.

**Comment by orschiro** [comment]
Issue solved thanks to this insightful comment:

https://github.com/synergy/synergy/issues/4774#issuecomment-109512268
