### ISSUE TITLE
Problem with language switching

### ISSUE THREAD

**Issue by online** [hluk/CopyQ#355]
Hello!

When I go to `Preferences` → `General` and choose `Language` → `русский` after this nothing happens. I tried to restart CopyQ, but the language still remains English.

My OS: Windows 8.1, x64.

**Comment by hluk** [comment]
Can you check if the language is set correctly in configuration dialog?

There are currently [lot of untranslated strings](https://hosted.weblate.org/projects/copyq/master/ru/).

I cannot provide translation for most languages. Help needed:
[![Translations](https://hosted.weblate.org/widgets/copyq-287x66-grey.png)](https://hosted.weblate.org/engage/copyq/?utm_source=widget)

**Comment by online** [comment]
@hluk, the language is set correctly in Preferences, I rechecked.

**Comment by online** [comment]
@hluk, may I suggest to add new functions to hot keys?

**Comment by hluk** [comment]
@online No problem, just create new issues if they're unrelated to this one.
