### ISSUE TITLE
CopyQ doesn't start in Ubuntu 15.04 x64

### ISSUE THREAD

**Issue by online** [hluk/CopyQ#356]
Hello!

Please, help solve this problem: when I enter in the terminal `copyq` I see such information:

```
username@Ubuntu-PC:~$ copyq
CopyQ  Loading plugin: /usr/lib/copyq/plugins/libitemdata.so
CopyQ  Loading plugin: /usr/lib/copyq/plugins/libitemencrypted.so
CopyQ  Loading plugin: /usr/lib/copyq/plugins/libitemfakevim.so
CopyQ  Loading plugin: /usr/lib/copyq/plugins/libitemimage.so
CopyQ  Loading plugin: /usr/lib/copyq/plugins/libitemnotes.so
CopyQ  Loading plugin: /usr/lib/copyq/plugins/libitemsync.so
CopyQ  Loading plugin: /usr/lib/copyq/plugins/libitemtags.so
CopyQ  Loading plugin: /usr/lib/copyq/plugins/libitemtext.so
CopyQ  Loading plugin: /usr/lib/copyq/plugins/libitemweb.so
"sni-qt/12017" WARN  11:26:58.423 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE
```

How to start CopyQ? The operating system is newly installed.

**Comment by hluk** [comment]
That seems to be `sni-qt` issue (support for tray for Qt application on Ubuntu). Can you run `copyq show` (to show main window) after `copyq` is started?

**Comment by online** [comment]
@hluk, yes, I do it when I'm near a computer.

**Comment by online** [comment]
@hluk, after execution of `copyq show` I see this:

```
username@Ubuntu-PC:~$ copyq
CopyQ  Loading plugin: /usr/lib/copyq/plugins/libitemdata.so
CopyQ  Loading plugin: /usr/lib/copyq/plugins/libitemencrypted.so
CopyQ  Loading plugin: /usr/lib/copyq/plugins/libitemfakevim.so
CopyQ  Loading plugin: /usr/lib/copyq/plugins/libitemimage.so
CopyQ  Loading plugin: /usr/lib/copyq/plugins/libitemnotes.so
CopyQ  Loading plugin: /usr/lib/copyq/plugins/libitemsync.so
CopyQ  Loading plugin: /usr/lib/copyq/plugins/libitemtags.so
CopyQ  Loading plugin: /usr/lib/copyq/plugins/libitemtext.so
CopyQ  Loading plugin: /usr/lib/copyq/plugins/libitemweb.so
"sni-qt/3710" WARN  19:16:48.410 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
uint DBusMenuExporterDBus::GetLayout(int, int, const QStringList&, DBusMenuLayoutItem&): Condition failed: menu 
uint DBusMenuExporterDBus::GetLayout(int, int, const QStringList&, DBusMenuLayoutItem&): Condition failed: menu 
uint DBusMenuExporterDBus::GetLayout(int, int, const QStringList&, DBusMenuLayoutItem&): Condition failed: menu 
uint DBusMenuExporterDBus::GetLayout(int, int, const QStringList&, DBusMenuLayoutItem&): Condition failed: menu 
uint DBusMenuExporterDBus::GetLayout(int, int, const QStringList&, DBusMenuLayoutItem&): Condition failed: menu 
uint DBusMenuExporterDBus::GetLayout(int, int, const QStringList&, DBusMenuLayoutItem&): Condition failed: menu 
uint DBusMenuExporterDBus::GetLayout(int, int, const QStringList&, DBusMenuLayoutItem&): Condition failed: menu 
uint DBusMenuExporterDBus::GetLayout(int, int, const QStringList&, DBusMenuLayoutItem&): Condition failed: menu 
uint DBusMenuExporterDBus::GetLayout(int, int, const QStringList&, DBusMenuLayoutItem&): Condition failed: menu 
uint DBusMenuExporterDBus::GetLayout(int, int, const QStringList&, DBusMenuLayoutItem&): Condition failed: menu 
uint DBusMenuExporterDBus::GetLayout(int, int, const QStringList&, DBusMenuLayoutItem&): Condition failed: menu
```

What information do I need to provide to solve this problem?

Incidentally, after executing the command `copyq show` the main window of CopyQ was launched.

**Comment by hluk** [comment]
I don't think I can do anything about this. CopyQ seems to be started, just the tray is not visible so it's most probably issue of [sni-qt](https://bugs.launchpad.net/ubuntu/+source/sni-qt). You can disable the tray to keep the icon in the side panel.

**Comment by online** [comment]
@hluk, before reinstalling the operating system it worked fine. What could I do wrong? Tell me anything, please.

**Comment by hluk** [comment]
I don't think you did something wrong. It could be just because the system has different 
versions of some libraries or the tray icons are not supported anymore.

I'm using CopyQ built with newer version of Qt framework and the tray icon doesn't work for me either (I'm using XFCE). But I don't really mind so I disabled the tray altogether and see CopyQ in panel instead (as minimized window).

Tray was never particularly well implemented for all desktop environments. Currently there are issues with many Qt apps because DEs started to use indicators instead of the old tray standard and Qt doesn't support that. KDE provides good implementation for indicators with Qt 5 so I hope we will see some improvements soon.

**Comment by online** [comment]
@hluk, thanks for your reply. I'll use a CopyQ in Windows. I've had enough of experiments with Ubuntu :wink:

It is lacks to insert the contents by pressing Enter in CopyQ window (on Windows OS).

**Comment by hluk** [comment]
Pasting selected items with Enter key ("item activation") is option which is disabled by default -- option "Paste to current window" under "History" config tab.

**Comment by online** [comment]
@hluk, thank you for the tip :wink:
