### ISSUE TITLE
Feature Requests: Play sound when copying to the clipboard

### ISSUE THREAD

**Issue by online** [hluk/CopyQ#357]
Hello!

I could not find this functionality in your wonderful program. Can you add it?

**Comment by hluk** [comment]
See https://github.com/hluk/CopyQ/issues/259#issuecomment-50436597 .

Automatic command looks like this (you can copy it to command list in Command Dialog [F6]):

```
[Command]
Name=Play Sound on Copy
Command="powershell: (New-Object Media.SoundPlayer \"C:\\Users\\copy.wav\").PlaySync()"
Automatic=true
Icon=\xf028
```

(You just need to change the sound file path.)

**Comment by online** [comment]
@hluk, thanks, but I get this error:

```
Command “powershell: (New-Object Media.SoundPlayer E:Downloadssound7.wav ).PlaySync()”
Error: Process failed to start: No such file or directory
```

I use this command:

```
[Command]
Name=Play Sound on Copy
Command="powershell: (New-Object Media.SoundPlayer \"E:\\Downloads\\sound7.wav\").PlaySync()"
Automatic=true
Icon=\xf028
```

File `E:\Downloads\sound7.wav` is in the folder.

**Comment by hluk** [comment]
Enter following in the "Command" field instead.
```
powershell:
(New-Object Media.SoundPlayer "E:\Downloads\sound7.wav").PlaySync()
```
(Not sure why it needs line break now.)

**Comment by online** [comment]
@hluk, Thanks for the help! Now everything is working properly.

**Comment by online** [comment]
@hluk, hi! Tell me, please, what command should be used in Ubuntu instead of this:

```
powershell:
(New-Object Media.SoundPlayer "E:\Downloads\sound7.wav").PlaySync()
```

**Comment by hluk** [comment]
Just use some audio player directly or using bash (to expand paths and variables). Examples:

`cvlc /home/lukas/audio/example.mp3`

`mplayer /home/lukas/audio/example.mp3`

`bash: cvlc ~/audio/example.mp3`

**Comment by online** [comment]
@hluk, this means that in the "Command" field I just need to insert one of these lines?

**Comment by hluk** [comment]
Yes. Just replace the command for Windows with one of the above.

**Comment by online** [comment]
@hluk, thanks for your help! :wink:

**Comment by francwalter** [comment]
I had no luck on Ubuntu with the cvlc command, but when I used mpv <mysoundfile> (without parameter) all worked :)
I had installed mpv with the software installer (not with apt).
Thank! It is an enhancement for ClipQ to play sound (I use a little tic from some clock sound, which I cut with Audacity, just to hear that I have something in Clipboard, because I have set copy on mouse selecting).

**Comment by francwalter** [comment]
> See [#259 (comment)](https://github.com/hluk/CopyQ/issues/259#issuecomment-50436597) .
> 
> Automatic command looks like this (you can copy it to command list in Command Dialog [F6]):
> 
> ```ini
> [Command]
> Name=Play Sound on Copy
> Command="powershell: (New-Object Media.SoundPlayer \"C:\\Users\\copy.wav\").PlaySync()"
> Automatic=true
> Icon=\xf028
> ```
> 

Is there another way to play sound on Windows?
I dont success with that command (yes, changed the path to my sound file: c:\WINDOWS\Media\plopp.wav)
In Powershell (as Non-Administrator) if I do:
`(New-Object Media.SoundPlayer "C:\WINDOWS\Media\plopp.wav").PlaySync()`
The sound is playing!

**Comment by Chealer** [comment]
The much more articulate ticket #1865 tracks the same issue.
