### ISSUE TITLE
Unable to install on Debian Stretch

### ISSUE THREAD

**Issue by rubaboo** [hluk/CopyQ#363]
Any advice? libqt4-gui is not in the "testing" repo for some reason.

```
dpkg -i ./copyq_2.4.7_Debian_8.0_amd64.deb 
(Reading database ... 130226 files and directories currently installed.)
Preparing to unpack .../copyq_2.4.7_Debian_8.0_amd64.deb ...
Unpacking copyq (2.4.7) over (2.4.7) ...
dpkg: dependency problems prevent configuration of copyq:
 copyq depends on libqt4-gui; however:
  Package libqt4-gui is not installed.

dpkg: error processing package copyq (--install):
 dependency problems - leaving unconfigured
Processing triggers for hicolor-icon-theme (0.13-1) ...
Processing triggers for mime-support (3.58) ...
Processing triggers for desktop-file-utils (0.22-1) ...
Errors were encountered while processing:
 copyq
```

**Comment by nameanyone** [comment]
I removed the dependency from the package, and it installed and seems to be working ok. Feel free to close if there is nothing to be done. Thanks.

**Comment by hluk** [comment]
It seems `qt4-x11` is now required instead (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=787737). I'll have to update the build files for Debian somehow.

**Comment by nameanyone** [comment]
`qt4-x11` is a source package. Doesn't that bug report imply you need to switch to qt5? See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=787737#15,
> = Already fixed
>
> >     calibre: libqt4-private-dev
>
> Switched to qt5 some time ago, already in testing.

**Comment by hluk** [comment]
It's possible to use Qt 5 with CopyQ but I'll still have to build with Qt 4 for older distros.

**Comment by scottkosty** [comment]
Now that the package is built with Qt 5 (https://packages.debian.org/sid/utils/copyq), can we close this issue?
