### ISSUE TITLE
After update, special characters are lost with some commands

### ISSUE THREAD

**Issue by Negirno** [hluk/CopyQ#364]
I've updated CopyQ through the PPA provided for Ubuntu 14.04 a couple of hours ago.

However, when I tried the "Join selected items" command available in the Command examples section of your wiki from these two clips:

```
(first clip)
日本語
áéíóú
(second clip)
this is a test
```

I got the following results:
```
???
�����
this is a test
```
CopyQ itself still handles unicode characters correctly, but with commands it converts into ASCII(?) since the update to the current version.

The funny thing is, that a custom script of mine works perfectly, maybe because it doesn't contain special characters itself, but a strange coding of those. This doesn't change the kanji neither in the template, or the kanji which supposed to go in place of %1, even after the update.

Here is the script:
```
[Command]
Name=Kandzsi adatlap sablon
Command="
    copyq add \"\x90e8\x9996\xff1a
    \x66f8\x304d\x9806\xff1a
    {{../../../.img/kanjicafe/%1.png}}
    Vari\xe1nsok: N/A
    K\xe9pjel: \x2026
    KMSZ:
    
    pinyin - 
    \x30aa\x30f3\x30e8\x30df - 
    \x304f\x3093\x3088\x307f - 
    
    ===== Jukugo =====
    
    ===== P\xe9ldamondatok =====\""
Input=text/plain
Output=text/plain
InMenu=true
```

**Comment by hluk** [comment]
Seems to work correctly for me.

What is your CopyQ version? What character encoding does your system use?

**Comment by Negirno** [comment]
I'm using UTF-8.

Program version is v.2.4.7, forgot to mention that I've installed it from [NoobsLab's PPA](https://launchpad.net/~noobslab)

Also. it seems that it only "ruins" the special characters when there is more clips selected in the CopyQ Window. If I select only one item, the characters are left as they are, but if I select multiple items, they would change even in my custom script.

**Comment by hluk** [comment]
Ah, yes sorry I fixed this after 2.4.7 (with commit 463f1bd). I'll try to release new version of CopyQ ASAP.

**Comment by Negirno** [comment]
Thanks.

**Comment by hluk** [comment]
@Negirno Is this fixed for you in 2.4.8?

**Comment by Negirno** [comment]
Currently not having that version, the PPA didn't updated yet.

**Comment by Negirno** [comment]
To be more precise, I've installed CopyQ from [Noobslab's Ubuntu indicators PPA](https://launchpad.net/~noobslab/+archive/ubuntu/indicators). Should I change to another PPA?

**Comment by hluk** [comment]
See #341.

**Comment by Negirno** [comment]
Ok, I've installed the repository.

The new version works, and my issue is resolved. Thanks.

Should I close this issue?

**Comment by hluk** [comment]
Glad to hear it's working. I'm closing this.
