### ISSUE TITLE
scriptable isActiveWindow

### ISSUE THREAD

**Issue by SamHasler** [hluk/CopyQ#367]
I'd like to change the behavior of the show/hide script to always put the clipboard tab in focus:

```
copyq:
if (visible()) {
  hide();
} else {
  show("&clipboard");
}

```

but this will hide the window if it is open but not active.

Could you make `isActiveWindow` scriptable so that I could do this instead:

```
copyq:
if (activeWindow()) {
    hide();
} else {
    show("&clipboard");
}

```

**Comment by hluk** [comment]
In next version, you should be able to do:

```
copyq:
if (focus())
    hide()
else
    show("&clipboard")
```

**Comment by SamHasler** [comment]
Great! When (as in under what circumstances, not necessarily how soon, I'm guessing your spare time is limited) will you release a new version? I don't see a current milestone although I see you used them in the past.

**Comment by hluk** [comment]
Milestones didn't work for me here. I release new version when I have the time, when I'm sure I didn't break anything and there are no critical bugs (could be at the end of this or next week).
