### ISSUE TITLE
Feature request: command line filter/search option!

### ISSUE THREAD

**Issue by sinilill** [hluk/CopyQ#368]
Hi, I think it would be totally awesome if CopyQ had a command line filter/search option!
Example: copyq show Mytab filter "cats" - would show main window, go to tab Mytab and show filtered results for "cats".

Thanks.

**Comment by hluk** [comment]
In next version, you'll be able to show a tab with filtered items with:

```
copyq filter "cats"
copyq show Mytab
```

or

```
copyq -e 'filter("cats"); show("Mytab")'
```

**Comment by SamHasler** [comment]
Will this also allow you to remove the filter? I'd want to clear the filter in my toggle main window script in #367

**Comment by hluk** [comment]
You can use `filter("")` to show all items and hide the filter entry box in main window.
