### ISSUE TITLE
Tray icon on KDE plasma 5

### ISSUE THREAD

**Issue by Heart1010** [hluk/CopyQ#369]
I updated today to openSUSE Tumbleweed with kde plasma 5 desktop and here after kde desktop is loaded I can see the default green/gray scirror CopyQ icon in the tray but this gets "corrupt" a little afterwards and is looking like 

![copyq_tray](https://cloud.githubusercontent.com/assets/1481680/9006247/779e3322-3785-11e5-8da2-44746d1342b5.png)

**Comment by scottkosty** [comment]
How did you install CopyQ? Which version are you using?

**Comment by Heart1010** [comment]
Hmmm, nothing changed (only rebooted after another day in office) and now after spending half day in kde5 the icon still looks good!

![copyq1](https://cloud.githubusercontent.com/assets/1481680/9036953/b228fe9c-39e6-11e5-8a1c-c484bc068f17.png)

So I close this one and will reopen it when the problem occurs again.

Installed CopyQ with the rpm file:
```bash
➜  zypper se -si copyq

S | Name  | Typ       | Version   | Arch   | Repository    
--+-------+-----------+-----------+--------+---------------
i | copyq | Paket     | 2.4.8-8.1 | x86_64 | (Systempakete)
```
