### ISSUE TITLE
feature request: preview pane

### ISSUE THREAD

**Issue by egbertgerber** [hluk/CopyQ#373]
A preview pane (editable for text clips) would make working with larger text clips much easier.
ClipCache Pro has this and it worked quite fine for me, back when I was still using Windows: http://www.xrayz.co.uk/clipcache/screenshots

**Comment by scottkosty** [comment]
For me, the main window of CopyQ does preview. It shows images, and renders HTML for example. What is missing?

**Comment by SamHasler** [comment]
You can already edit clips with the `Item > Edit` menu item (shortcut `F2`). It works well for large text items for me. What are you having difficulty with?

**Comment by hluk** [comment]
I've created [item_preview](https://github.com/hluk/CopyQ/tree/item_preview) branch with initial implementation of item preview dock. The dock can be toggled with F7 and new option in History config tab to show simple items (single line description).

If anyone can tests it, I would really like to hear some feedback.

![image](https://cloud.githubusercontent.com/assets/38054/9836034/54963c02-5a09-11e5-8b6a-f6efb3743f1d.png)

**Comment by SamHasler** [comment]
Does this replace the Item Content (F4) dialog? It seems like duplication.

Why not remove the Item Content dialog and split it into two separate docable panels:

* Formats panel (F4) - show the list of formats and allows switching between them (same as `CTRL+Left` and `CTRL-Right`)
* Preview panel (F7) - As above but add back the "**Size:** *n* bytes"  display at the bottom.
