### ISSUE TITLE
Select multiple clipboard items using only the keyboard

### ISSUE THREAD

**Issue by rolistid** [hluk/CopyQ#374]
Looking for a productive way to use copyq tabs as filterable checklists with discontinuously selected items.
Keep pressing Ctrl while moving focus Up and Down and toggle the selection with Space key doesn't work, as Ctrl + Up / Down moves the items.
I wish that selecting with Shift + Up / Down would be persistent (as in Double|Total Commander) making possible to skip some items pressing only the Up / Down keys, and continue to add more items to the selection with Shift + Up / Down.

**Comment by hluk** [comment]
I've implemented the more-or-less standard behavior for selecting item with Shift and Ctrl (2370d64).

Shortcuts for moving items are now configurable.

**Comment by rolistid** [comment]
Perfect! Thanks a lot!

**Comment by SamHasler** [comment]
is this the "Extended item selection" in the v2.4.9 release?

**Comment by hluk** [comment]
Yes. You may need to update theme to be able to see current-unselected item.
