### ISSUE TITLE
CopyQ list remains empty (Windows 8)

### ISSUE THREAD

**Issue by francois-ferrandis** [hluk/CopyQ#375]
First of all, congrats; CopyQ is hands down my favorite clipboard manager on earth. I have been using it every day for months under Linux and Windows 7, and it worked like a charm.

But today I tried to install it on Windows 8, and faced a bug: **Windows built-in copy-pasting works, but the CopyQ list remains empty.**

I am able to:
- Set custom keyboard shortcuts (to open/close the window, for example)
- Add an entry via File -> New Item (though it won't paste afterwards)

I tried to run CopyQ as Administrator, gave it all authorized scopes in the Security tab, with no luck. I also tried to wipe off user settings / reinstall. I also tried the portable version.

I tried to install Ditto and it works on my system.

How can I help you help me?

**Comment by scottkosty** [comment]
Are you able to build CopyQ? If so, build with debug flags. Then CopyQ will tell you what's wrong when you run it from the terminal (or whatever the Windows equivalent is).

**Comment by hluk** [comment]
You don't have to rebuilt the app. But you have to set environment variable `COPYQ_LOG_LEVEL` to `DEBUG` or `TRACE` to see more detailed console output.

You can also set `COPYQ_LOG_FILE` to path to new log file so the console output will be written there.

Clipboard is automatically saved only if all of the following are true.
1. "Store clipboard" is enabled in settings.
2. "Tab for storing clipboard" is not empty in History configuration tab.
3. commands defined in Command dialog [F6] don't ignore the clipboard content.
4. "Clipboard Storing" is not disabled (toggled with Ctrl+Shift+X).

Note: I test the app on Windows 8 and it does work fine for me.

**Comment by francois-ferrandis** [comment]
Okay, I've set environment variable likewise:
`set COPYQ_LOG_LEVEL=DEBUG`
`set COPYQ_LOG_FILE="C:\Users\François\AppData\Roaming\copyq\out.log"`
but I can't find any log. I have also checked the Windows Log Viewer, but did not find anything CopyQ-related.

Am I doing something wrong?

**Comment by hluk** [comment]
Try to change use different path separator:

    set COPYQ_LOG_FILE="C:/Users/François/AppData/Roaming/copyq/out.log"

or 

    set COPYQ_LOG_FILE="C:\\Users\\François\\AppData\\Roaming\\copyq\\out.log"

**Comment by francois-ferrandis** [comment]
I tried both and still no log file is created.

I don't have the courage to install everything I need to build from source, so unless someone has a debug-enabled compiled version, I'll just forget about it, as no one else seems to have this problem.

**Comment by m4r71n** [comment]
@francois-ferrandis 
Try `Win+R` and execute `"C:\Windows\system32\rundll32.exe" sysdm.cpl,EditEnvironmentVariables`
I've set the following systemvariables: 
![2015-08-17_201911](https://cloud.githubusercontent.com/assets/6043876/9312517/5d4eb140-451d-11e5-9393-733d8845b063.png) 
The `copyq.log` will be created in the same directory as my `copyq.exe`

**Comment by scottkosty** [comment]
@francois-ferrandis do you still have this issue with the most recent CopyQ version?

**Comment by francois-ferrandis** [comment]
@scottkosty I don't have that machine anymore, and no Windows 8 around anymore, so I guess you can close this if you wish. Thank you! :+1:
