### ISSUE TITLE
Build from source fails

### ISSUE THREAD

**Issue by lots0logs** [hluk/CopyQ#377]
Arch Linux
QT 5.5.0
GCC 5.2.0
CMAKE 3.3.1

Build Log: http://build.antergos.com/build/447

Any idea what's causing this?

**Comment by hluk** [comment]
You need to remove following line from `CMakeLists.txt` to build CopyQ with Qt 5.5.0 and up (it's already fixed in master).

    add_definitions( -DQT_RESTRICTED_CAST_FROM_ASCII )

**Comment by lots0logs** [comment]
Okay, thanks!
