### ISSUE TITLE
option to switch mouse buttons for tray icon

### ISSUE THREAD

**Issue by deathtrip** [hluk/CopyQ#378]
Opening dropdown menu with left click, and opening window with the right.
Basically the oposite of what is the default now, as some people might find it more convenient that way.

**Comment by hluk** [comment]
That seems strange to me. I don't know any app that does this. Why is that more convenient?

**Comment by deathtrip** [comment]
On linux KDE, all system icons are opened with a left click. While the right click gives a context menu to change the widget settings etc.

**Comment by hluk** [comment]
Qt GUI framework doesn't directly support the new tray area used by KDE, Unity and others.

KDE developers are the first to properly implement new tray for Qt (there is also `sni-qt` but only for Qt4 and it doesn't work that well).

Since it's currently KDE implementation, it's probably up to them to swap the mouse button behavior. (Note: I don't check whether left or right button was pressed when user clicks the tray icon.)

**Comment by sudhirkhanger** [comment]
This would be a very good addition. KDE, GNOME, Ubuntu, etc. are all moving away from system tray icons having left and right click options. That way users don't have to worry about what functionality belongs to left-click and what belongs to right-click. AFAIK libappindicator protocol used by Ubuntu and KStatusNotifierItems in KDE all advice single-left-click for further options.

**Comment by gbcox** [comment]
If we're talking about the tray area (both xembed - kde4 and libappindicator - kde5) it appears to me that copyq is working exactly as it it suppose to work.  I don't see any difference between it and other apps in the tray area.  As @sudhirkhanger mentioned libappindicator (which is the new method replacing xembed) changed the meaning of right vs. left so everything is standardized.  People may be getting confused between the behavior in xembed and system notifier (libappindicator).

**Comment by sudhirkhanger** [comment]
@gbcox libappindicator is a gtk+ support library based off KDE's KStatusNotifierItems. GNOME design doesn't advocate use of system tray. Basically, the whole of Linux UI is moving towards a consistent left-click-only paradigm.

**Comment by gbcox** [comment]
@sudhirkhanger yes, I understand that... which is why I used the term "tray area" rather than "system tray".

**Comment by syserss** [comment]
I'd appreciate adding this function back into CopyQ.  It had it previously and I rarely use the CopyQ window.  Everything that I typically need to do I can get from the tray menu.  I would highly appreciate if you brought the option back for those that would prefer.  Quite frankly I appreciate apps that give me the option of making it how I want and tend to drop those that make me conform to their approach.

If you are unwilling to make it a documented feature,  Would you at least be willing to share how we could modify it ourselves to achieve the same.  As I mentioned before, switching the default behavior used to be an option.

**Comment by hluk** [comment]
@syserss The option to change the button for opening tray menu **has never been implemented before**.

Since this is somewhat popular issue I've implemented the option but it's not accessible from configuration dialog since it only works on Windows and few desktop environments on Linux. So to enable the option you have to open config file `~/.config/copyq/copyq.config` and add `tray_menu_open_on_left_click=true` under `[Options]` section.

(This will be available in whatever version comes after 2.7.1.)

**Comment by sudhirkhanger** [comment]
@hluk Thank you for making our lives much more easier :).

@gbcox Any plans if we will see this patch before next release of CopyQ in Fedora?

**Comment by gbcox** [comment]
@sudhirkhanger Sure... I'll take a look.

**Comment by gbcox** [comment]
I've opened:  https://bugzilla.redhat.com/show_bug.cgi?id=1359526
I currently have an update in bodhi to fix copyq translations.  I'll stage this one after it gets pushed to updates.  If you want to speed things up, please leave karma.  

I actually like the current way it works... after this patch basically both the left and right key do the same thing - but to each his own.

**Comment by sudhirkhanger** [comment]
@gbcox I don't see any recent copyq package in bodhi. The latest one is copyq-2.7.1-2.fc24 (the translation one).

**Comment by gbcox** [comment]
@sudhirkhanger yes, but it is awaiting karma.  Otherwise I have to wait 7 days before I can push to updates.  This one needs to go first.

**Comment by sudhirkhanger** [comment]
Oh! okay updated and gave the karma to copyq-2.7.1-2.fc24.

**Comment by gbcox** [comment]
Yes, the F24 update for the translation fix has been autopushed - and I just submitted this build for testing.  It could take days however (you know how bodhi can be) so if you don't want to wait, you can get it here from koji:  http://koji.fedoraproject.org/koji/buildinfo?buildID=785247

Whenever it finally gets on bodhi, please leave karma so it gets pushed to updates.

Thanks!

**Comment by mgcarnevali** [comment]
> @syserss The option to change the mouse button for opening tray menu **has never been implemented before**.
> 
> Since this is somewhat popular issue I've implemented the option but it's not accessible from configuration dialog since it only works on Windows and few desktop environments on Linux. So to enable the option you have to open config file `~/.config/copyq/copyq.config` and add `tray_menu_open_on_left_click=true` under `[Options]` section.
> 
> (This will be available in whatever version comes after 2.7.1.)

Hello,

If there any way to open the window with right click?

I can open dropdown menu with left click using this option tray_menu_open_on_left_click=true but I dont know the command option to open the window with right click, both mouse buttons open dropdown menu now.

Many thanks

**Comment by hluk** [comment]
> If there any way to open the window with right click?
> 
> I can open dropdown menu with left click using this option tray_menu_open_on_left_click=true but I dont know the command option to open the window with right click, both mouse buttons open dropdown menu now.

This is not possible in some desktop environments, they handle most of the tray icon behavior themselves.

**Comment by mgcarnevali** [comment]
> > If there any way to open the window with right click?
> > I can open dropdown menu with left click using this option tray_menu_open_on_left_click=true but I dont know the command option to open the window with right click, both mouse buttons open dropdown menu now.
> 
> This is not possible in some desktop environments, they handle most of the tray icon behavior themselves.

Ok, understood.

Is there any way to show entry number beyond numer 9 in system tray?

https://ibb.co/WkLVxGj

Many thanks

**Comment by hluk** [comment]
> Is there any way to show entry number beyond numer 9 in system tray?

No, the numbers are meant to serve as key hints - for example Alt+6 would select the sixth item.
