### ISSUE TITLE
Fuzzy search

### ISSUE THREAD

**Issue by sergei-dyshel** [hluk/CopyQ#382]
When frequently searching through captured snippets, fuzzy search may be very helpful. In terms of regular expressions it is like putting ".*" between all characters of search word and than searching the resulting regex.

Is it hard implement such a feature? I'd even volunteer for this task :smiley:

**Comment by hluk** [comment]
I think that would give unexpected results. Perhaps more useful would be to intersperse non-whitespace (`\S`) characters with `\S*` (or even limit the distance `\S{,10}`).

If you want to implement that, it's relatively easy. Just add new menu action in `FilterLineEdit` class ([here](https://github.com/hluk/CopyQ/blob/97b59c6e8243deea6eb524b4d38eebd8cdbe824d/src/gui/filterlineedit.h#L61)) and transform the search pattern in `FilterLineEdit::filter()`.

Maybe you can just change the behavior when the "Regular Expression" is disabled ([this part](https://github.com/hluk/CopyQ/blob/97b59c6e8243deea6eb524b4d38eebd8cdbe824d/src/gui/filterlineedit.cpp#L88-L92)) without adding new option.

**Comment by olejorgenb** [comment]
It would be great if the search worked more like helm in emacs:

Each word is searched for independently and then the result is ANDed together. So the search word order doesn't matter and they don't have to be consecutive either.

**Comment by hluk** [comment]
@olejorgenb You can give it a shot but I don't think it's possible to implement using QRegExp which is currently used to match items. This might need a bigger change in code.

**Comment by olejorgenb** [comment]
I might do.

Looking at the code it seems like one way would be to change `QRegExp m_re;` in `ItemDelegate` to a list, modify the parser to create on regex per "word" and make `ClipboardBrowser::isFiltered` check all the regexes.

**Comment by amosbird** [comment]
Hmm, has this been implemented? @hluk

**Comment by amosbird** [comment]
I just realized that I can disable `regex search` in the search bar to get the desired filter behavior. However, it then breaks this use case https://github.com/hluk/CopyQ/issues/992 . Is there a way to have the `regex search` toggled in script?

**Comment by hluk** [comment]
> Is there a way to have the `regex search` toggled in script?

Not possible in the latest release. I've just added the feature to change it with `copyq config filter_regular_expression false/true` command or `config('filter_regular_expression', false/true)` from a script (will be available in the next release).

**Comment by amosbird** [comment]
Awesome!
