### ISSUE TITLE
copyq 2.4.6 crashes on FC 21 after update

### ISSUE THREAD

**Issue by trennor** [hluk/CopyQ#383]
updated copyq according to email notification, now it crashes every time I start it up. Backtrace report available but I see no way to include it with this notification. a small paste: 

Thread 2 (Thread 0x7fffdda19700 (LWP 18818)):
#0  0x00007ffff46d7c8d in poll () at /lib64/libc.so.6
#1  0x00007ffff6106570 in qt_safe_poll(pollfd*, int, int, bool) ()
    at /lib64/libQtCore.so.4
#2  0x00007ffff60b5dc8 in QProcessManager::run() () at /lib64/libQtCore.so.4
#3  0x00007ffff5fd03af in QThreadPrivate::start(void*) ()
    at /lib64/libQtCore.so.4
#4  0x00007ffff43ce52a in start_thread () at /lib64/libpthread.so.0
#5  0x00007ffff46e322d in clone () at /lib64/libc.so.6

Thread 1 (Thread 0x7ffff7fb7880 (LWP 18813)):
#0  0x00007ffff6ed7ad2 in QStyleSheetStyle::renderRule(QWidget const*, QStyleOption const*, int) const () at /lib64/libQtGui.so.4
#1  0x00007ffff6eda19b in QStyleSheetStyle::pixelMetric(QStyle::PixelMetric, QStyleOption const*, QWidget const*) const () at /lib64/libQtGui.so.4
#2  0x00007ffff70bc607 in QAbstractItemView::viewOptions() const ()
    at /lib64/libQtGui.so.4
#3  0x00007ffff70eb853 in QListView::viewOptions() const ()
    at /lib64/libQtGui.so.4
#4  0x00007ffff70bd8e7 in QAbstractItemViewPrivate::viewOptionsV4() const ()
    at /lib64/libQtGui.so.4
#5  0x00007ffff70ebb8b in QListView::updateGeometries() ()
    at /lib64/libQtGui.so.4
#6  0x00000000004b1351 in ClipboardBrowser::resizeEvent(QResizeEvent*) ()
#7  0x00007ffff6bed118 in QWidget::event(QEvent*) () at /lib64/libQtGui.so.4
#8  0x00007ffff6fad49e in QFrame::event(QEvent*) () at /lib64/libQtGui.so.4
#9  0x00007ffff70c97b3 in QAbstractItemView::viewportEvent(QEvent*) ()
    at /lib64/libQtGui.so.4
#10 0x00007ffff60da2d6 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () at /lib64/libQtCore.so.4
#11 0x00007ffff6b99edc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib64/libQtGui.so.4
#12 0x00007ffff6ba0958 in QApplication::notify(QObject*, QEvent*) ()
    at /lib64/libQtGui.so.4
#13 0x00007ffff60da16d in QCoreApplication::notifyInternal(QObject*, QEvent*) () at /lib64/libQtCore.so.4
#14 0x00007ffff6c33356 in QWidgetPrivate::setGeometry_sys(int, int, int, int, bool) () at /lib64/libQtGui.so.4
#15 0x00007ffff6be548d in QWidget::setGeometry(QRect const&) ()
    at /lib64/libQtGui.so.4
#16 0x00007ffff702f02b in QAbstractScrollAreaPrivate::layoutChildren() ()
    at /lib64/libQtGui.so.4
#17 0x00007ffff70eba18 in QListView::updateGeometries() ()
    at /lib64/libQtGui.so.4
#18 0x00000000004b1351 in ClipboardBrowser::resizeEvent(QResizeEvent*) ()
#19 0x00007ffff6bed118 in QWidget::event(QEvent*) () at /lib64/libQtGui.so.4
#20 0x00007ffff6fad49e in QFrame::event(QEvent*) () at /lib64/libQtGui.so.4

There are several hundred more  lines in the bt.

**Comment by hluk** [comment]
Can you post the whole backtrace somewhere (perhaps gist)? Looks like some problem with widget size being recursively set.

**Comment by trennor** [comment]
Can you provide a link? It won't upload to fpaste.

**Comment by hluk** [comment]
Link to gist? It's here: https://gist.github.com/

**Comment by trennor** [comment]
link to bt https://gist.github.com/trennor/349132ee2e62d2d1f21f

**Comment by hluk** [comment]
I cannot reproduce it. But the commit hopefully fixes this.
