### ISSUE TITLE
Quick shortcuts

### ISSUE THREAD

**Issue by brannou** [hluk/CopyQ#384]
Would be perfect to have the possibility to paste the nine first elements by simply using shortcut ctrl + v + 1 (keypad) or by customizing this shortcut.

**Comment by hluk** [comment]
It's only possible to map shortcuts which look like `<key modifiers>+<key>`. Workaround is to create command that opens custom dialog on `Ctrl+V` and allows to choose an action.

For example you can use the following to paste multiple items (copy/paste the code below to command list in Command Dialog [F6]).
```ini
[Command]
Command="
    copyq:
    var n = dialog(
      \".title\", \"Paste Multiple Items\",
      \"Number of Items to Paste\", 9
    )
    
    if (!n)
      abort()
    
    var text = str(read(0))
    for (var i = 1; i < n; ++i)
      text += '\\n' + str(read(i))
    
    copy(text)
    paste()"
GlobalShortcut=Ctrl+V
Icon=\xf0c4
Name=Paste N items
```

**Comment by brannou** [comment]
Really interesting thanks i will try it. I was not so clear in my first
post (probably my frenglish 😃 ) i meant ctrl + v + 1, ctrl + v + 2,....
But your code is a good start to elaborate this idea.
Thanks a lot

**Comment by hluk** [comment]
I've added possibility to see which application or global shortcut activated command. See [command example](https://github.com/hluk/CopyQ/wiki/Command-Examples#copy-nth-item).
