### ISSUE TITLE
Inserting today's date?

### ISSUE THREAD

**Issue by orschiro** [hluk/CopyQ#387]
Dear lovely CopyQ team, 

I would like to insert today's date in the form of `YYYY-MM-DD` by using a keyboard shortcut.

Is it possible to tweak CopyQ to this extent?

Thankfully,

Robert

**Comment by hluk** [comment]
Paste following code to command list in Command Dialog [F6] and change the shortcut.
```
[Command]
Command="
    copyq:
    var format = 'yyyy-MM-dd'
    copy(dateString(format))
    paste()"
GlobalShortcut=Meta+Ctrl+D
Icon=\xf073
Name=Paste Current Date/Time
```

**Comment by orschiro** [comment]
Dear @hluk,

That works perfectly. Thank you! ツ

Robert

**Comment by muteboy** [comment]
I've pasted this as a new command verabtim, but when I use the shortcut, I get the CopyQ message "Error: No such file or directory".

**Comment by hluk** [comment]
@muteboy Did you really paste the command into the command list in Command dialog? I.e. copy the command code (starts with `[Command]`), press <kbd>F6</kbd> in CopyQ to open the dialog, click "Paste Commands" button at bottom of the dialog.

**Comment by muteboy** [comment]
I just followed your instructions and it worked great. I didn't know I needed to use the 'Paste Commands' button - I was just pasting the whole code into the box. Thanks for the clarification!

**Comment by hluk** [comment]
You can otherwise paste or drag'n'drop the code to the command list on the left side of the dialog.

**Comment by dbareis** [comment]
I can't find "**dateString**" function documented anywhere (it is mentioned a lot).  Can someone link to the documentation on it's format?
 I've tried "**var T1 = dateString('yyyy-MM-dd HH:MM')** " which works but "SS" is not seconds and in any case I want an AM/PM (12 hour format) time.

**Comment by hluk** [comment]
> I can't find "**dateString**" function documented anywhere (it is mentioned a lot). Can someone link to the documentation on it's format?

It's documented in API reference: https://copyq.readthedocs.io/en/latest/scripting-api.html#dateString

The format is the same as in Qt framework: https://doc.qt.io/qt-5/qdatetime.html#toString

**Comment by hluk** [comment]
> To answer my own question for future googlers, this works for COPYQ:
> **var T1 = dateString('yyyy-MM-dd H:mm:ssap')** //2021-12-09 10:26:15am - https://doc.qt.io/archives/qt-5.7/qml-qtqml-date.html

@dbareis Thanks for sharing this. The description in your link looks clearer than what is linked in the documentation. I will think about updating the docs.

**Comment by dbareis** [comment]
@hluk 
I made a mistake which I worked out in the afternoon, it should be (little 'h'):

var T1 = dateString('yyyy-MM-dd h:mm:ssap')

I was looking everywhere for it but though it was standard Javascript as it was mentioned there.
