### ISSUE TITLE
Using GTK File Chooser Dialog?

### ISSUE THREAD

**Issue by orschiro** [hluk/CopyQ#388]
Dear all, 

I know that CopyQ is using Qt. Yet I would like to know whether it is possible to replace the default file chooser dialog below with the native, more powerful GTK file chooser (in my case on an Ubuntu 15.04 installation).

Thankfully,

Robert

**Default file chooser:**
![image](https://cloud.githubusercontent.com/assets/170947/10094518/04551c16-6361-11e5-9c8b-6b56f31cd77d.png)

**GTK file chooser:**
![image](https://cloud.githubusercontent.com/assets/170947/10094549/4687f0e0-6361-11e5-9b94-85ecbdec2702.png)

**Comment by hluk** [comment]
Hmm, that's strange because the native dialog should be used by default (option [QFileDialog::DontUseNativeDialog](http://doc.qt.io/qt-4.8/qfiledialog.html#Option-enum) can be used to disable that behavior).

Where does the dialog come from? Do Import and Export dialogs look the same?

Perhaps using CopyQ built with Qt 5 will fix that.

**Comment by orschiro** [comment]
Dear @hluk,

I figured the problem. Import and Export both use the native dialog. The non-native shown above is used by [Save as snippet](https://gist.github.com/hluk/64dae8b25cd21e6141dd):

![image](https://cloud.githubusercontent.com/assets/170947/10121835/c8511238-64ff-11e5-83b7-00b4f547c4ee.png)

**Comment by hluk** [comment]
I replaced the dialog with native one (if available on given system).

Problem could be that the dialog could complain in some rare cases since it's specifically for saving to a file.

**Comment by orschiro** [comment]
@hluk 

Nice, thank you!

I will test and report back as soon as there is a new `deb` package released.

Warmly,

Robert

**Comment by orschiro** [comment]
Tested the latest version. Beautiful. 

Thank you!

![image](https://cloud.githubusercontent.com/assets/170947/11163077/f70694fc-8ac2-11e5-8478-f7d5f19eeba2.png)
