### ISSUE TITLE
Window position

### ISSUE THREAD

**Issue by JeremyWW** [hluk/CopyQ#390]
Hi,

Running CopyQ in Windows 10. I'm finding that the main window doesn't remember it's position after a restart / sleep. I position it at bottom right just above the notification area but it reappears further into the main screen area - not by much but enough to be annoying. During the same session it's not a problem, only seems to happen after a restart or wake.

Thanks.

**Comment by hluk** [comment]
Unfortunately I cannot test this.

Do you see this behavior even if you restart just the application?

Is there any difference when you show the main window with command (global shortcut) or clicking on tray icon?

**Comment by JeremyWW** [comment]
Hmm...suddenly I'm having trouble reproducing this myself! I updated the graphics driver a day or two ago...if it happens again I'll let you know.

**Comment by JeremyWW** [comment]
Well it's still happening - randomly. I can't nail it down except that it may possibly be linked to using 'Show main window under mouse cursor' at some point beforehand. I've used both methods of showing the main window today and the next time I bring the main window up by clicking on the notification icon the window has moved in again - evenly on both axis by around 75 pixels.

**Comment by hluk** [comment]
There doesn't seem to be a good way in Qt to check if window was moved by user. Application could receive some move events after moving the window from code and after some unspecified interval.

Anyway, this should be fixed in next version.

**Comment by JeremyWW** [comment]
Great. Thanks.
