### ISSUE TITLE
Upload screenshot to imgur directly?

### ISSUE THREAD

**Issue by orschiro** [hluk/CopyQ#391]
Dear all, 

Does someone use a CopyQ script to directly a screenshot directly to services such as imgur?

I could imagine a context menu entry in the tray indicator or a global keyboard shortcut.

Is it technically possible for CopyQ to interact with external services?

This would be cool. ツ

Thankfully,

Robert

**Comment by rachmadaniHaryono** [comment]
you can install [imgur-uploader](https://github.com/atbaker/imgur-uploader) and set copyq to only enable command when image url is in clipboard
here is an example of command, that i use to download picture
```
[Command]
Name=dl image
Match=^(https?)://.*\\.(jpg|png|jpeg|webm)$
Command="
    wget -P \"/home/q/Downloads/\" --restrict-file-names=nocontrol %1"
Input=text/plain
Output=text/html
InMenu=true
Icon=\xf06e
```
you just have to  change command to `imgur-uploader %1` and the regex to fit your image path

**Comment by orschiro** [comment]
Dear @rachmadaniHaryono,

Thank you!

Something like:

![image](https://cloud.githubusercontent.com/assets/170947/10415854/c11d49f2-6ffc-11e5-9ae9-a353e82e3ebe.png)

However, the command doesn't show up in the menu for some reasons:

![image](https://cloud.githubusercontent.com/assets/170947/10415855/d8613dda-6ffc-11e5-9ff0-24a58552b335.png)

**Comment by rachmadaniHaryono** [comment]
~~i see your clip 0-4 don't have file uri. in your clipboard there is only image but i don't know if it is text or just clip image/png format. can you copy the file and try right click once more.~~

you are try to match regex with clip with format image/png, can you try plain/text format?

**Comment by orschiro** [comment]
You mean changing `Format` to `text/plain`? 

I tried it but it doesn't provide any context menu entry.

**Comment by rachmadaniHaryono** [comment]
```
[Command]
Name=imgurl uploader
Match=^*.\\.png
Command=imgur-uploader %1\n
InMenu=true
```
![screenshot from 2015-10-15 15 43 31](https://cloud.githubusercontent.com/assets/6340878/10507494/6901bdd4-7353-11e5-9b08-70ef9e219ab2.png)

**Comment by orschiro** [comment]
Dear @rachmadaniHaryono,

I appreciate your support! Please tell me if I'm doing anything wrong here. 

I recorded a screencast according to which, I think, it should work as in your example screenshot.


[Untitled Screencast (14).webm | uploaded via ZenHub](https://files.zenhub.io/5620fca46d5b7b202609c69e)

**Comment by rachmadaniHaryono** [comment]
Can you show the content of the clip (press f4 on clip or right click and show content)

**Comment by orschiro** [comment]
This is the content of screenshots that I would like to upload: 

![image](https://cloud.githubusercontent.com/assets/170947/10562885/6d8fd630-7572-11e5-876e-d9211adb767a.png)

**Comment by hluk** [comment]
"Content" field in Command dialog filters text (`text/plain` format) in selected clipboard item. Your image items don't contain text so this won't work, but setting "Format" field is enough in this case.

Also setting the "Format" to "image/png" sends the image data to standard input of the provided command (`%1` is only useful for text items). So depending on what your script can handle you can either pass the data to it directly or create temporary file first. Perhaps one of these would work:

```
imgur-uploader
```
```
imgur-uploader -
```
```
bash:
imgur-uploader <(cat)
```
```
bash:
tmp=/tmp/copy_to_upload.png
cat > "$tmp"
imgur-uploader "$tmp"
```

**Comment by orschiro** [comment]
@hluk 

Thank you! Your solution seems to work in principle. However, it seems that imgur-uploader only supports gif uploads. I will look for another script that supports png uploads.
