### ISSUE TITLE
Blank screen in linux

### ISSUE THREAD

**Issue by rcrath** [hluk/CopyQ#395]
THe main window comes up blank, as do the popups when cycling through clips using shortcuts.  Hovering over menu items in main screen blanks out the other menu items, rest of screen remains blank.  hover popup of systray is fine.  Maybe a borked theme, but I can't see in config to check (2nd image).

Manjaro (Arch-based), CopyQ 2.49

![screenshot from 2015-10-06 22-10-52](https://cloud.githubusercontent.com/assets/944636/10332320/7d514570-6caa-11e5-84d5-845950caea62.png)

![screenshot from 2015-10-07 04-20-18](https://cloud.githubusercontent.com/assets/944636/10332357/c51e82fa-6caa-11e5-8195-a52798dccd25.png)

**Comment by hluk** [comment]
Try setting:
```ini
style_main_window=false
```
in `$HOME/.config/copyq/copyq.conf` -- the option should be already in there and if it's really theme issue it's set to `true`.

You can also try running `copyq` from command line to see if there are any errors.

**Comment by hluk** [comment]
@rcrath Any input on this? Does it work fine? I guess it's issue with graphics driver or Qt in given environment.

**Comment by rcrath** [comment]
@hluk itseems to have cleared up with an update somewhere along the line, so I think you can close.  I'll reopen it if it crops up again and the steps you recommended don't work.  THanks!
