### ISSUE TITLE
Ignore file copy operations?

### ISSUE THREAD

**Issue by paul1149** [hluk/CopyQ#397]
Is it possible to have CopyQ ignore file copy operations? Currently the clipboard record is clogged with filenames, when I'd rather reserve it for text that I work with. Sorry if there's a better place to ask this; I couldn't find it.

Blessings.

**Comment by rachmadaniHaryono** [comment]
this command may help you 

'''
[Command]
Name=Copy file address to other tab
Match=^/
Input=text/plain
Automatic=true
Remove=true
Icon=\xf0c5
Tab=&file
'''
you just have to change the match regex to fit your criteria

**Comment by paul1149** [comment]
Thanks much, but I have no idea how to implement that, and didn't want to dive that deep anyway. I'm confused why unchecking the Data/Text item type, which includes "List of URI (eg copied files)" doesn't do what I want.

**Comment by rachmadaniHaryono** [comment]
> I have no idea how to implement that

try `Match=^\w:\\\\`

> I'm confused why unchecking the Data/Text item type, which includes "List of URI (eg copied files)" doesn't do what I want.

i believe it does remove the type, but you still have other format (ie text/plain and application/x-copyq-owner-windows-title). see content of your clip by pressing F4.

**Comment by paul1149** [comment]
Sorry. Not working and I don't know what I'm doing.

**Comment by hluk** [comment]
See https://github.com/hluk/CopyQ/issues/338#issuecomment-87226938.

**Comment by paul1149** [comment]
Ignore Copied Files does not work. I've also tried added each of the two regexes to the command, with no results. What might help is a general exclusion for the file manager (thunar), but I haven't seen provision for that.

**Comment by hluk** [comment]
What is the content of clipboard (Ctrl+Shift+C) and the new item (F4 on the item) after copying files?

**Comment by paul1149** [comment]
I used ctrl-alt-v (my own shortcut) to bring up the popup, then s to get the program interface. There the clipboard showed: /home/paul/Templates/listing.ott

F4 on that produced 
Formats: text/plain
Content: /home/paul/Templates/listing.ott
Size: 32 bytes

**Comment by hluk** [comment]
Please post the formats in clipboard from CopyQ -- it's the dialog in "File/Show Clipboard Content" (Ctrl+Shift+C) -- surely Thunar uses some special formats apart from plain text.

**Comment by paul1149** [comment]
Yes, thank you, it appears you are correct. There is:
text/plain     /home/paul/Dropbox/Getting Started.rtf
text/uri-list     file:///home/paul/Dropbox/Getting Started.rtf
x-special/gnome-copied-files     copy
file:///home/paul/Dropbox/Getting%20Started.rtf

**Comment by hluk** [comment]
Well, I cannot reproduce this. When I add "Ignore copied files" at the top of the command list in Command dialog, save the dialog and copy some files from file manager (Nemo) the files don't show up in CopyQ (in clipboard tab).

The command basically won't add automatically any clipboard content which contains `text/uri-list` (even with `x-special/gnome-copied-files` it should work -- that's more specific and should allow copying links in other apps).

**Comment by paul1149** [comment]
Strange, then. I moved Ignore copied files to the top of the list, and Applied. It is checked and has been. I also deleted some other commands that I had tried, some which were checked and some not. But nothing works. I'll play with it some more, and if anyone gets another idea that would be great. Appreciate the effort you've put into this.

**Comment by hluk** [comment]
Yes, that's really odd. Are you sure you use the same command as is under "Add" button in Command dialog?

**Comment by paul1149** [comment]
Yes:
Ignore copied files
[x] Automatic
Format: text/url-list
[x] Remove Item

Everything else is blank. I have other rules as well, such as "Move to &files", "files" being a tab, with the same command profile, which do not work either.

**Comment by hluk** [comment]
Just one note: CopyQ won't run any automatic commands under the first one that triggers and has "Remove Item" checkbox enabled (it's noted in tool tip for the checkbox).
