### ISSUE TITLE
Pin items in tray popup

### ISSUE THREAD

**Issue by graceman9** [hluk/CopyQ#398]
Is there is a way to pin some (up to 10) items from list to the top?
It might be useful for some often used passwords, usernames, sql-queries, etc.

In general I'm thinking about two (or more) columns in tray's popup... is it hard to implement? is it OS dependant feature?
The 1st column can be for "pin items", from 2 to 9 can be additional clipboards. It would be comfortable to use different columns, for instance for different types (image, video, link, text, code, filenames...).

Anyone have an idea about how to implement it? is it possible?

**Comment by hluk** [comment]
I don't remember seeing menu with multiple columns (unless it's too big to fit the screen).

Tray menu is intended to be as simple as possible. Isn't it better to open different tab in main window for this?

For example to pop up main window under mouse pointer and open tab "Stuff" you can do following.

    copyq showAt
    copyq show "Stuff"

Or you can open tray menu with given tab.

    copyq config tray_tab "Stuff"
    copyq menu

Or you can open simple dialog to choose a tab first and then show it.

    copyq:
    tab_name = dialog(".title", "Open Tab", "Tab", tab())
    config("tray_tab", tab_name)
    menu()

**Comment by graceman9** [comment]
I'm sorry for the late response.

> Tray menu is intended to be as simple as possible. Isn't it better to open different tab in main window for this?

It's technically proper solution, but I'm looking for the fastest way.
Perhaps I don't understand copyq philosophy, but I'm just want quickly paste predefined items into text/console/web-form field. I didn't get why you suggest me write a such long text commands in.. console? Am I wrong that it is for console?

But thank you a lot, I realized that method proposed by me is not easy to implement. Perhaps someday I'll look closer into copyq docs.

**Comment by hluk** [comment]
Those commands can be used in Command dialog [F6] and can be available from tray menu or executed with a shortcut. That's the way CopyQ functionality can be extended. It's quite advanced but there are some predefined commands if you click on Add button in the dialog.
