### ISSUE TITLE
Global shortcut does not last after reboot

### ISSUE THREAD

**Issue by nartcan** [hluk/CopyQ#400]
I generally use copyq to speed up copy-pasting multiple objects. In order to do it, I use 'paste and copy next' action with 'ctrl+winkey+v'. So I can copy multiple objects and paste them consecutively. 

But, if I reboot my computer, the shortcuts that I set get lost. I appreciate any help or suggestion.

By the way, thank you for this useful software.

**Comment by hluk** [comment]
This could be the same issue as #404. Do you have some command that uses explicitly `settings()`?

**Comment by hluk** [comment]
Closing old issues. Provide more info and reopen if needed.
