### ISSUE TITLE
Edit richtext does not work

### ISSUE THREAD

**Issue by HyperCriSiS** [hluk/CopyQ#402]
Hi,

when I want to edit a rich text Sticky, it does now work, because the opened file is a ".txt" file.
For example, edit with word:
![copyq - word](https://cloud.githubusercontent.com/assets/11708192/10879116/5aa76b5a-8152-11e5-8d8a-3b3c480f96a9.png)

Something wrong in my config?

Thanks in advance.
Hyper

**Comment by HyperCriSiS** [comment]
Also pasting the richtext Sticky is wrong. The format is messed up.

**Comment by hluk** [comment]
CopyQ passes only plain text to external editor -- though it should be possible to write custom command to edit any kind of data in other apps.

What is the application where you copy the rich text? Are you sure that the copied data are correct before it gets to CopyQ?

Can you show content of the item? (You can display item content from main menu "Item/Show Content" [F4].)

**Comment by HyperCriSiS** [comment]
Hi,

sorry for the late answer. At general it would be nice to pass rich text to the external editor.
The issue was when I made a new Item in CopyQ and copied a richtext into it, but I do not need this anymore.

But I have another one :)

When trying to create a Qr-Code CopyQ reports:

Command “./qrencode/qrcode -o - -t PNG -s 6”
Exit code: 1
No input data. 

---
./qrencode/qrcode -o - -t PNG -s 6
---

**Comment by hluk** [comment]
You can pass the rich text data to an editor (this is done with the `qrencode` utility) or create script to save the data in temporary file and then pass the file name.

I don't know what application you use to encode QR codes. The command I provided works with following version.

```
> qrencode --version                                
qrencode version 3.4.4
Copyright (C) 2006-2012 Kentaro Fukuchi
```

**Comment by HyperCriSiS** [comment]
I downloaded exaclty this qrencode version and your latest release.
The provided command is: qrencode -o - -t PNG -s 6

The file list in the qrencode version3.4.4 is:
```
qrcode.exe
qrcodecon.exe
qrcodegui.exe
```

But also if I change command to:
`qrcode -o - -t PNG -s 6`

I get:
```
Exit code: 1
No input data. 
```
Don't know how to pass the clipboard content to this tool. :(

**Comment by hluk** [comment]
If you run the command from CopyQ you need to set correct [format](https://github.com/hluk/CopyQ/wiki/Writing-Commands-and-Adding-Functionality#format) in options for the command. Data of given format will be sent to standard input of the command.
