### ISSUE TITLE
QTScript "settings(key,value)" command wipes out config file

### ISSUE THREAD

**Issue by Xananax** [hluk/CopyQ#404]
Steps:

1 - Create a script that uses `settings` 
Example:
<a href="http://i.imgur.com/rnVdviB.png">
  <img src="http://imgur.com/rnVdviBl.png" />
</a>

Note config file prior to usage:
<a href="http://i.imgur.com/P0oa6cG.png">
  <img src="http://imgur.com/P0oa6cGl.png" />
</a>

2 - Run script:
<a href="http://i.imgur.com/2ZF0iIP.png">
  <img src="http://imgur.com/2ZF0iIPl.png" />
</a>

3 - Open `~/.config/copyq/copyq.conf`:  
file is wiped out.
<a href="http://i.imgur.com/vHumltX.png">
  <img src="http://imgur.com/vHumltXl.png" />
</a>
Commands window is also (arguably consistently) wiped out:
<a href="http://i.imgur.com/W522aoM.png">
  <img src="http://imgur.com/W522aoMl.png" />
</a>

Workaround: Open Config (shows all correct settings), press "cancel", open commands again: they're all restored.
If I instead press "ok", then the new (blank) settings are applied and I loose all my configuration.

The workaround isn't really one, since I cannot make use of whatever I have set through `settings(key,value)` until I open the config window and cancel it.

Note that this also happens with the provided example [Save Texts on Disk](https://gist.github.com/hluk/be4481e6c72ab607c074).

Using Arch Linux, with [this package](https://aur.archlinux.org/packages/copyq/).

**Comment by Xananax** [comment]
Note, I also tried `settings('script/'+key,value)` after reading a bit on how to use QTSettings, but it messed up things even more

**Comment by hluk** [comment]
Wow, that's bad. Thanks for the report and sorry for the trouble.

I use custom class that makes QSetting safe (flushing settings is not atomic operation in Qt 4 -- not sure if it's fixed in Qt 5). Seems this messes things up if the QSettings is accessed in different thread.

I think it would be better to use separate config file for script settings (simpler and faster).

**Comment by hluk** [comment]
This will be fixed in next version. Thanks again for nice report.

**Comment by Xananax** [comment]
You're welcome, thanks for creating one of my favourite apps! A good extensible clipboard manager was thoroughly needed. Thanks also for the extreme quick fix.
