### ISSUE TITLE
Allow to reassign up/down keys in item list

### ISSUE THREAD

**Issue by hluk** [hluk/CopyQ#405]

**Comment by szepeviktor** [comment]
Is it possible not to script:

<kbd>Ctrl + 1</kbd> Item list navigation up
<kbd>Ctrl + 2</kbd> Item list navigation down
<kbd>Ctrl + 3</kbd> Paste current item

Is it "Paste current item"?

```
[Command]
Name=Paste Item
Command=copyq:\ntab(selectedTab())\nselect(currentItem())\nhide()\npaste()
InMenu=true
Icon=\xf0ea
Shortcut=Return
```

**Comment by hluk** [comment]
You can use following three commands but selecting items this way is slower.

[Commands]
1\Name=Up
1\Command=copyq:\nselectItems(currentItem() - 1)
1\InMenu=true
1\Icon=\xf0d8
1\Shortcut=Ctrl+1
2\Name=Down
2\Command=copyq:\nselectItems(currentItem() + 1)
2\InMenu=true
2\Icon=\xf0d7
2\Shortcut=Ctrl+2
3\Name=Paste Item
3\Command=copyq:\nselect(currentItem())\nhide()\npaste()
3\InMenu=true
3\Icon=\xf0ea
3\Shortcut=Ctrl+3
size=3


Lukas

2015-11-09 13:04 GMT+01:00 Viktor Szépe <notifications@github.com>:

**Comment by szepeviktor** [comment]
Thank you!!

```
[Commands]
1\Command=copyq: toggle()
1\GlobalShortcut=Ctrl+Shift+V
1\Icon=\xf022
1\Name=Show/hide main window
2\Command=copyq: selectItems(currentItem() - 1)
2\Name=Up
size=4
2\InMenu=true
2\Shortcut=Ctrl+1
2\Icon=\xf062
3\Command=copyq: selectItems(currentItem() + 1)
3\Icon=\xf063
3\InMenu=true
3\Name=Down
3\Shortcut=Ctrl+2
4\Command="copyq: select(currentItem()); hide(); paste()"
4\Icon=\xf0ea
4\InMenu=true
4\Name=Paste
4\Shortcut=Ctrl+3
```

**Comment by hluk** [comment]
**Commands should be pasted into command list** in Command dialog <kbd>F6</kbd> -- putting this into `copyq.ini` can potentially break things if you're not careful.

BTW: I didn't know you can use `kbd` to format shortcuts on github. Nice.

**Comment by szepeviktor** [comment]
F//Commands dialogue allow me to paste only `copyq: selectItems(currentItem() - 1)`.
Icon, shortcut etc are selectable only by the GUI, no copy-paste.

**Comment by szepeviktor** [comment]
Or is it `Paste Commands` ??

**Comment by szepeviktor** [comment]
GitHub is very advanced: :sunny: :sunny: :sunny:

**Comment by hluk** [comment]
Ahh, yes you can use "Paste Commands" button in the dialog (or just focus the list and paste with <kbd>Ctrl+V</kbd>).
