### ISSUE TITLE
Copy next/previous item and popup clipboard text

### ISSUE THREAD

**Issue by jpsala** [hluk/CopyQ#407]
Hi, I don't know if this is the write place to post a question.
I'm trying to do a script that shows a balloon with the current item when I change it, what I whant is this: when I press a key, for example alt-up the previous item get's selected and it's contents are shown in a balloon, and alt-down to show the next item.
And thanks for copyq, it's wonderfull!

**Comment by hluk** [comment]
I posted previously following commands somewhere.

```ini
[Commands]
1\Name=Copy next item
1\Command="
    copyq: next()
    popup(\"Selected Item\", clipboard())"
1\Icon=\xf063
1\GlobalShortcut=Ctrl+Shift+2
2\Name=Copy previous item
2\Command="
    copyq: previous()
    popup(\"Selected Item\", clipboard())"
2\Icon=\xf062
2\GlobalShortcut=Ctrl+Shift+3
size=2
```

**Comment by jpsala** [comment]
Thanks a lot, I will try it later
