### ISSUE TITLE
Copyq sometimes doesn't copy the whole selection but a part in Chrome.

### ISSUE THREAD

**Issue by sudhirkhanger** [hluk/CopyQ#408]
Chrome has its own unique and weird way of copying things.

| Click | Selection | Copy |
| --- | --- | --- |
| Single (only valid in address bar) | whole | does't copy anything |
| Double | only a part | copies the part |
| Triple | whole | copies whole link |

I have set Copyq to `store text selected using mouse` which should copy any selected text.

If you double click a word in a sentence, it will be copied, and quickly make another click to select the whole sentence, the whole sentence now will not be copied. As if copying requires you to be a little bit slow and diligent.

In the following image you can see I double clicked the word whole and then made another click which selected the whole link but didn't copy the whole selection.

![snapshot21 1](https://cloud.githubusercontent.com/assets/841656/11110460/11b6989e-8922-11e5-8c0e-b8be5d29c4c3.png)

**Comment by hluk** [comment]
Hmm, it works correctly for me (with Copyq 2.4.8 on Chromium 46.0.2490.80).

Can you check is selection is really copied with `copyq selection` command (and perhaps `xclip -o`)?

Can you also post `copyq --version`?

**Comment by sudhirkhanger** [comment]
I am on 2.4.9. This has been a very weird bug for me. I am not if it's KDE related or CopyQ related. I am unable to reproduce it in i3. I am closing it for now until I can reproduce it with much greater confidence.

**Comment by joejoe79** [comment]
sudhirkhanger is right, triple-clicking just a tad slower does the job properly. So the "bug" is there only when one triple-clicks "too quickly". Funny thing, haven't figured that out in months, and most likely never would.

So, not much of a bug there, and not much of problem, obviously. Not sure if I should now remove my replies or leave it be.. OK then, take care!

**Comment by sudhirkhanger** [comment]
@joejoe79 want me to open the report?

**Comment by joejoe79** [comment]
Bah.. No, thank you, I can triple-click a bit less nervously :)

**Comment by Rumbles** [comment]
This just caught me out on Fedora 24, I would appreciate it if it could be opened @sudhirkhanger, I keep shouting at my computer when I copy something quickly and I only get a fragment :)

I can reproduce in terminal and Firefox, but Chrome seems fine. It does appear to be down to how quickly you get the 3rd click in.

I'm running:

copyq --version
CopyQ Clipboard Manager v2.7.1 (hluk@email.cz)
Built with: Qt 5.6.1, LibQxt 0.7.0

**Comment by sudhirkhanger** [comment]
@Rumbles I have reopened it. Let's hope we can find a reliable way to replicate it.

**Comment by gbcox** [comment]
You might give v2.8.0 a try first.  It should be replicated to the testing repo.  If not, you can get it from koji.

**Comment by Rumbles** [comment]
I'm happy to help, let me know what I can do

**Comment by Rumbles** [comment]
I'll have a look at 2.8

**Comment by Rumbles** [comment]
Still seems apparent in 2.8.0, just did:

rpm -Uvh the rpm from koji
Closed copyq and launched it again from the gnome start menu
tried triple clicking on something in gnome terminal and only the word that was selected after the second click went in to copyq

Let me know if there is anything more I can help with

**Comment by hluk** [comment]
Closing - it's quite possible this is fixed in recent versions (a lot of code handling clipboard was changed). If you still have this issue please reopen and provide details.
