### ISSUE TITLE
Spike feature

### ISSUE THREAD

**Issue by svnpenn** [hluk/CopyQ#410]
Microsoft Word has a [spike feature][1], which works like this:

- Ctrl + F3 = add to spike
- Ctrl + Shift + F3 = paste spike, clear spike

I see that CopyQ is similar:

- Ctrl + C = add to spike
- ? = paste spike, clear spike

Does CopyQ have a shortcut to paste all clips, then clear the board?

[1]:http://techadvisory.org/2014/05/the-spike-words-unknown-feature

**Comment by hluk** [comment]
Interesting. Maybe something like following except CopyQ doesn't know how to cut text from other apps (copy/paste the code to command list in Command dialog [F6]).

```ini
[Commands]
1\Name=Add to Spike
1\Command="
    copyq:
    tab(\"Spike\")
    
    copy()
    var text = clipboard()
    
    write(count(), \"text/plain\", text)
    popup(\"Added to Spike\", text)"
1\GlobalShortcut=Ctrl+F3
2\Name=Paste from Spike
2\Command="
    copyq:
    tab(\"Spike\")
    
    var text = \"\"
    while (count() > 0) {
      text = text + str(read(0))
      remove(0)
    }
    copy(text)
    
    paste()"
2\GlobalShortcut=Ctrl+Shift+F3
size=2
```

**Note:** Copying from app could be a bit slow so don't deselect text after <kbd>Ctrl</kbd>+<kbd>F3</kbd> until confirmation popup appears.

**Comment by svnpenn** [comment]
@hluk this might work, but the *Added to Spike* popup shows for too long, about 10 seconds. Can I change it so the popup goes away after 1 second?

**Comment by svnpenn** [comment]
@hluk thank you for the help. I think I will just use the regular Ctrl+C, then I have this command based on your comment:

~~~
[Command]
Name=Paste all
Command="
    copyq:
    var z = ''
    while (count()) {
      z = str(read(0)) + '\\n' + z
      remove(0)
    }
    copy(z)
    paste()"
GlobalShortcut=Ctrl+Shift+V
~~~
