### ISSUE TITLE
activate_pastes / tray_item_paste pastes X selection, not selected item

### ISSUE THREAD

**Issue by blueyed** [hluk/CopyQ#411]
The option `tray_item_paste` does not paste the selected entry, but the last
one from the X selection.

The same seems to be the case for `activate_pastes: true`.

My options:

```
% for i in $(copyq config|grep -P '^\w+'); do printf "$i: "; copyq config $i; done
activate_closes: true
activate_focuses: false
activate_pastes: false
always_on_top: false
autostart: false
check_clipboard: true
check_selection: true
clipboard_notification_lines: 0
clipboard_tab: &clipboard
confirm_exit: true
copy_clipboard: false
copy_selection: false
disable_tray: false
edit_ctrl_return: true
editor: vim-in-term %1
expire_tab: 0
hide_tabs: false
hide_toolbar: false
item_popup_interval: 0
maxitems: 500
move: true
notification_horizontal_offset: 10
notification_maximum_height: 100
notification_maximum_width: 300
notification_position: 3
notification_vertical_offset: 10
open_windows_on_current_screen: true
save_filter_history: true
show_tab_item_count: false
tab_tree: false
text_wrap: true
transparency: 0
transparency_focused: 0
tray_commands: true
tray_images: true
tray_item_paste: true
tray_items: 5
tray_tab: tray_tab_is_current: true
vi: true
```
CopyQ Clipboard Manager v2.4.9 (hluk@email.cz)
Built with: Qt 4.8.7, LibQxt 0.7.0

I have not tried v2.5.0.

**Comment by hluk** [comment]
Option "copy_clipboard" needs to be set for most terminal applications. If the option is enabled, clipboard content is copied to X selection too.

Hmm, but perhaps it's better to set selection disregarding the option ("next" and "previous" commands do this).

**Comment by hluk** [comment]
Fixed (the option will no longer be required to be enabled). Thanks for pointing that out.
