### ISSUE TITLE
Option to Sorting different formats in different tabs

### ISSUE THREAD

**Issue by ZIEXED** [hluk/CopyQ#413]
In the configuration > History
there is an option to select the tab for sorting the clipboard
It will be more great to expand this option by adding the ability to select the sorting tab for every format separately
sorting the images in different tab than texts is very useful :+1: 

**edit:**
I just read the wiki
It's possible from the commands & it's working great now
maybe adding this suggestion as well I think will make it more **simple** for other Ppl
**thank you** ♥

**Comment by hluk** [comment]
I would rather simplify the GUI, remove options, make more things possible through commands and make them easier to use.

**Comment by hluk** [comment]
Closing. If you there is anything specific to do, please provide details.
