### ISSUE TITLE
Fedora 23 - CopyQ

### ISSUE THREAD

**Issue by RobbiNespu** [hluk/CopyQ#414]
Any release for Fedora 23? I saw only Fedora 23 rpm package are available.
Any plans to update it? Thanks very much for your work.

**Comment by scottkosty** [comment]
I've read your question a few times and I don't understand. You suggest that Fedora 23 rpm package is available and then ask if a release for Fedora 23? In any case, this seems like a question for the packager. You might want to ask the Fedora packager of the rpm you're talking about and see if they want to repackage the newer version.

**Comment by RobbiNespu** [comment]
Yes, I suggest that Fedora 23 rpm package is available and then ask if a release for Fedora 23. I checked https://github.com/hluk/CopyQ/releases/tag/v2.5.0 , only Fedora 22 package are available. 

I check the repo.. the latest version are  
```$ sudo dnf info copyq
Last metadata expiration check performed 0:19:46 ago on Mon Nov 23 08:42:38 2015.
Installed Packages
Name        : copyq
Arch        : x86_64
Epoch       : 0
Version     : 2.4.9
Release     : 4.1
Size        : 5.3 M
Repo        : @System
From repo   : @commandline
Summary     : Advanced clipboard manager
URL         : http://sourceforge.net/projects/copyq/
License     : GPL-3.0
Description : CopyQ is advanced clipboard manager with searchable and editable
            : history with support for image formats, command line control and
            : more.```

Just thinking, maybe you can release newest release for Fedora 23 at github,

**Comment by scottkosty** [comment]
I see, thanks for the extra details @RobbiNespu

**Comment by hluk** [comment]
Thanks for the info. I added the packages.
