### ISSUE TITLE
Language option missing

### ISSUE THREAD

**Issue by mcc1** [hluk/CopyQ#418]
There only have one Chinese option in Language.
It will set the program into Simplified Chinese.
Can you Add another Traditional Chinese option?

**Comment by hluk** [comment]
That's strange, I can see it in options on Linux and Windows -- 中文 is one of the options.

![copyq-languages](https://cloud.githubusercontent.com/assets/38054/11496240/deef1f8c-9810-11e5-9d26-c6e7962ede17.png)

The translation is here: https://hosted.weblate.org/projects/copyq/master/zh_TW/

**Comment by hluk** [comment]
I'm probably wrong -- the option I highlighted is the Simplified Chinese, right?

**Comment by mcc1** [comment]
Yes, I have chosen it before. It will changed to simplified Chinese.
Maybe the option should change to
简体中文 for simplified Chinese
2015年12月1日 上午9:52於 "Lukas Holecek" <notifications@github.com>寫道：

**Comment by hluk** [comment]
Not sure why it's not there, I'll try to fix it.

Meanwhile you should be able to set the language by setting `language=zh_TW` in your configuration manually and restarting the app -- it's in `~/.config/copyq/copyq.conf` (Linux) or `config/copyq/copyq.ini` (portable version for Windows) or in `%APPDATA%\copyq`. Unfortunately you will have to change it again when you apply new settings in the app.

**Comment by hluk** [comment]
The some language names in Qt are really same -- I expected them to be unique. I'll have to manually rename the options.
- Traditional Chinese: 繁體中文
- Simplified Chinese: 简体中文

**Comment by mcc1** [comment]
Ok, thanks for your help!
