### ISSUE TITLE
Code to insert today's date?

### ISSUE THREAD

**Issue by muteboy** [hluk/CopyQ#421]
I really like CopyQ, it's the closest thing to Ditto for Windows I've found on Linux. What I would really like is to be able to paste today's date using a hotkey action. I can't figure out the syntax for scripting though. Can anyone help?
If I could use Ctrl+; to paste in the date in ISO 8601 format (YYYY-MM-DD) anywhere, that would be great. It looks like actions and scripts could do it.

**Comment by hluk** [comment]
See #387.
