### ISSUE TITLE
Adding `Ctrl+[` as `Esc`

### ISSUE THREAD

**Issue by amosbird** [hluk/CopyQ#422]
`Ctrl+[` key binding is quite natural for terminal and Vi users. I couldn't find a way to cusmize `CopyQ` to use `Ctrl+[` as escaping, which is a frequent operation when doing `copyq menu`. In fact, the pop up window of `copyq menu` doesn't honor any hot keys copyq has (`ctrl+p` not work).

Env:
ArchLinux
I3 (gap fork , 4.11-404-gfdbe3ce)
CopyQ (v2.5.0)

**Comment by hluk** [comment]
OK, I'll try to implement it for the "Vi style navigation" option.

New shortcuts:
<kbd>Ctrl</kbd> <kbd>[</kbd> -- alias to <kbd>Esc</kbd>
<kbd>Ctrl</kbd> <kbd>n</kbd> -- next item (conflicts with New)
<kbd>Ctrl</kbd> <kbd>p</kbd> -- previous item (conflicts with Preferences)

**Comment by amosbird** [comment]
That's great :smiley: . I think `Ctrl + j -- next item` and `Ctrl + k -- previous item` would be another option.

**Comment by hluk** [comment]
Well, <kbd>j</kbd> and <kbd>k</kbd> already work in Vi mode.

It's actually bit annoying not to be able to search for words starting with these letters in Vi mode without using <kbd>/</kbd>.

**Comment by amosbird** [comment]
@hluk `Ctrl + [` now works in `Copyq show`, but it still doesn't work in `Copyq menu`.

**Comment by hluk** [comment]
Ah, OK, Vi shortcuts never worked in menu (I don't use the tray menu often). I'll fix that in #425.
