### ISSUE TITLE
feature request: show item notes as tooltips on tray dropdown menu

### ISSUE THREAD

**Issue by wseverin** [hluk/CopyQ#423]
The notes feature is really handy, for instance keeping lists of IP addresses and MACs when setting up a network. I can put the host name in the notes for corresponding items. But then from the tray menu I can't tell which item goes with which host without pulling up the CopyQ main window.

So: If CopyQ would display the notes (as a tooltip?) for whatever item the mouse is hovered over in the tray menu, that would be a big timesaver.

**Comment by hluk** [comment]
It actually works that way but tray menu in Ubuntu breaks the functionality (among others).

**Comment by hluk** [comment]
Would it be better to show the tool tip as menu item instead of the content?
