### ISSUE TITLE
Wrong keyboard mapping when assigning global shortcuts in Windows

### ISSUE THREAD

**Issue by tnilzon** [hluk/CopyQ#427]
CopyQ does not recognize local keyboard mapping when assigning global shortcuts. For example if Swedish keyboard is used the wrong keys are mapped if special characters (i.e. < _  etc.) are part of a global shortcut. This bug applies when CopyQ is used under Windows. It appears to work OK when used under Linux.
/Tomas Nilzon, Sweden

**Comment by hluk** [comment]
Is this problem with global shortcuts only or with normal shortcuts too? Can you see incorrect shortcut created or it just doesn't work?

**Comment by hluk** [comment]
Some [key code mappings](https://github.com/hluk/CopyQ/blob/dbe5e3da75467ba5452278f488ce6e4ad175e931/qxt/qxtglobalshortcut_win.cpp#L73) from [Qt](http://doc.qt.io/qt-4.8/qt.html#Key-enum) to [Windows](https://msdn.microsoft.com/en-us/library/windows/desktop/dd375731%28v=vs.85%29.aspx) are missing for many global shortcuts to work.

The existing code was taken from no-longer-maintained [Qxt](https://bitbucket.org/libqxt/libqxt/wiki/Home). I have already added few key mappings and done fixes in the code. I would be glad if anyone can **help me update the code**.

**Comment by tnilzon** [comment]
The incorrect shortcut is created and saved, but then does not work with the keyboard used.

**Comment by hluk** [comment]
Wait, which is it: the shortcut itself is wrong (the shortcut text doesn't match the pressed keys) or it just doesn't work? The former implies that [shortcut setup](https://github.com/hluk/CopyQ/blob/1d64eac2f23b54f5feab3f3ed5b56a68a767e4e4/src/gui/shortcutdialog.cpp#L81) is misbehaving.

**Comment by tnilzon** [comment]
When trying to define a new global shortcut and pressing a key with a special character (i.e. <) another sign shows up (.i.e. \) and sets as shortcut. The shortcut text doesn't match the pressed keys when trying to define a new global shortcut. Every where else in Windows 10 the keyboard mapping is correct (i.e. pressing the < key gives the < sign).

**Comment by hluk** [comment]
It seems to be working well now though I didn't test global shortcuts just the shortcut capture dialog. Please reopen if it doesn't work.

**Comment by tnilzon** [comment]
Where can I download an updated .exe file to install and try this on my Windows machine?

**Comment by hluk** [comment]
You can find Qt 5 version built from last commit [here](https://ci.appveyor.com/project/hluk/copyq/build/artifacts) -- it's zip file though.

**Comment by tnilzon** [comment]
I have now tried the latest CopyQ Windows version. It still behaves the same. Take a look on the attached screendump. I am trying to assign 'Ctrl + <'as a global shortcut to "Show/Hide Main Window" in CopyQ. But it comes up as 'Ctrl + \'. It does not help using 'Shift' either.
This works fine in Linux Mint, but it goes wrong in Windows.

Is the CopyQ configuration file editable in Windows, and what is the file path (I could try to modify the shortcut in the configuration file)?

/Tomas Nilzon

**Comment by hluk** [comment]
I tested it with English and Czech keyboards -- both OK. Tried it now with Swedish keyboard and as you say it's not OK :(.

This seems to be an issue in Qt Creator and with QKeySequenceEdit Qt 5 with too. I think I would require to implement conversion table for Windows virtual keys.

Editing shortcut in config file seems to work. If you installed CopyQ configuration is in registry ("HKEY_CURRENT_USER\Software\copyq") and if you have portable version from zip it's in "config" subdirectory.

**Comment by hluk** [comment]
Should be fixed now. You should be also able to use more global shortcuts.

**Comment by m4r71n** [comment]
@hluk after upgrading from dbe5e3da75467ba5452278f488ce6e4ad175e931 to ac5fcd69c9c350c962204ccf21c01c055d40bf1b my global shortcut for `Show/hide main window` `Ctrl+Shift+V` doesn't work anymore. The shortcut is display correctly and default shorcut `Ctrl+Shift+1` does work.
This happens with my personal Qt 4.8.7 build and also with the [Qt 5 build](https://ci.appveyor.com/api/buildjobs/yt3doiha7f7ppdiy/artifacts/copyq.zip) from AppVeyor.

**Comment by hluk** [comment]
@m4r71n  OK, perhaps [now](7994cf813624a63c9feb07033c16dccc81e79abd).

**Comment by hluk** [comment]
The problem seems that `QKeySequence` messes with the shortcut and getting string and key code gives bad answer.

@m4r71n Can you test it with branch [fix_shortcuts](ae4c8c0821dfcec2c00e15096b1f5f15106985f1)?

**Comment by m4r71n** [comment]
@hluk with 7994cf813624a63c9feb07033c16dccc81e79abd my already defined shortcut `Ctrl+Shift+V` works again. But after removing and readding the `Show/hide main window` command it is not possible to assign `Ctrl+Shift+V`.
ae4c8c0821dfcec2c00e15096b1f5f15106985f1 from https://github.com/hluk/CopyQ/commits/fix_shortcuts behaves identical.

**Comment by hluk** [comment]
Great. If you couldn't assign any global shortcuts in past, it's worth trying now.

**Comment by Chealer** [comment]
~~Thank you for reporting Tomas, but:~~
~~1. Please see [that checklist](https://blog.michael.gr/post/2014-11-bug-reporting-checklist/) when reporting behavioral bugs, in particular sections 8 to 12~~
~~2. Please answer Lukas’s question about normal (non-global) shortcuts~~
~~3. GitHub uses the backslash (\\) as an escape character. Therefore, to show a backslash, you need to type 2.~~

The reporter visibly forgot this ticket and reported again in a much clearer ticket, #2295.

[_License_](https://www.philippecloutier.com/Common+infrastructure+licensing#its)
