### ISSUE TITLE
Strictly separate 'options' and 'cached values'

### ISSUE THREAD

**Issue by amerlyq** [hluk/CopyQ#428]
Year and half ago in #224 I asked you to split config in two.
And now I ask you to do this again, because you enhanced conf and added new dirty options.
I sync `copyq.conf` between many working machines by git, therefore it must be constant and allow changes only on demand -- through preferences.
Therefore:
- `filter_history` must not be inside `copyq.conf`, because I'm tired of resetting `copyq.conf` each time I commit all my system dotfiles.

It's one option which I remember. But there may be more, because I resetted config in other cases also.
I would appreciate it, if you would scan through options list and decided one more time which are options (could be common for several workstations) and which are cached values (actual for concrete local machine only).

P.S. Also I remember sections inside `[Command]` jumps in order by themselves, but seems like you fixed it by adding number before them. Not pretty, but works. However for such nested configs [TOML](https://github.com/toml-lang/toml) seems better for me.

**Comment by hluk** [comment]
OK, I'll move things out of the main config file.

Other config sections which should be saved separately is `[Theme]` (colors, fonts, style sheets) and `[Script]` (custom settings for user commands).

The `[Command]` section is array in standard conf format used by Qt. And yes, it's very ugly:
- The command numbers seem redundant and sorting is bad (1, 10 ... 19, 2, 20 ...).
- Longer strings aren't formatted nicely (contains `\n` instead line breaks).

It would be really nice to use JSON as format for configuration (can be parsed by many tools can parse it and is supported by Qt 5 and perhaps through JavaScript engine in Qt 4).

**Comment by amerlyq** [comment]
Hm, if you are planning to completely replace config format, then JSON isn't that great for config files at all. It's too verbose and strict with all that quotes and braces.
I understand that most of users will never edit configs by any means beside GUI and never look at them directly. But for some guys directly edit is much cleaner way, and them would prefer if format looked nice, robust and readable.
Currently, there are not such many modern options to satisfy that demand -- I could remember only YAML and TOML. Both can be linked statically, therefore no need in dependence on Qt.

As for ```[Theme]``` -- why use JSON, if it's already in css internally? Simply read from ```*.css``` file. Qt allows this. As for scripts -- I don't know if seperating them in one separate file has sense -- then it must be or bunch of small files -- one for each script, or leave them alone in config, as YAML and TOML has nice support for multiline values.

**Comment by hluk** [comment]
I'm not planing on changing config format any time soon -- it's a lot of work and it'll probably break compatibility with older versions.

`[Theme]` section could be `css` but I would need to replace some special IDs/classes with some ugly stuff that Qt requires (styling Qt apps isn't fun anymore) and some theme options are just enabled/disabled values or strings.

`[Scripts]` actually only contain custom configuration for commands (not the commands themselves; e.g. you can set custom options with `copyq settings option_name value` command).

`[Commands]` should be probably elsewhere too -- I have around 50 custom commands (not all active, some for testing) which span over 250 lines in config file.

For now I just moved the `filter_history` option (commit e05501415b7e1750fbea0e78e7abb9494778b048).

**Comment by amerlyq** [comment]
Thanks! I have no concerns with issue then, as it has exceeded primary goal.

By the way, I can't find yours ```copyq.conf``` in ```configs``` repo to peek at your commands/scripts.
I thought about improving my usage experience by that many times, but couldn't find anything of such kind on the web for usecase inspiration. Wiki is even nearly not enough, many examples would be better.
Could you point me out to your config and maybe somewhere else?

**Comment by hluk** [comment]
I post some bigger interesting commands on [gist](https://gist.github.com/hluk) -- most of them are referenced at bottom of [this wiki page](https://github.com/hluk/CopyQ/wiki/Command-Examples).

Many of commands I personally use just send items or clipboard content to another application (but that's usually platform-dependent so I don't post those).

If you have some idea for a command [let me know](mailto:hluk@email.cz)? I usually spend some time trying to implement  new functionality using commands to see if it's possible and how easy it is before updating source code.

**Comment by hluk** [comment]
In recent version some configuration was moved to separate files:

- `[Commands]` to `copyq-commands.ini`
- `[script]` to `copyq-scripts.ini` (custom user settings for commands)
- `collapsed_tabs` and `[TabWidget]` to `copyq_tabs.ini` (collapsed tab for tab tree view)
- `filter_history` to `copyq-filter.ini` (search history)
- geometry for main window and dialogs to `copyq_geometry.ini`
