### ISSUE TITLE
Add support for multiple instances of the application (with the same session)

### ISSUE THREAD

**Issue by blueyed** [hluk/CopyQ#429]
While `-s` / `COPYQ_SESSION_NAME` can be used to have multiple (separate) instances, it could also be useful to have the same instance available on multiple displays, e.g. to share clipboard contents.

I have separate instances (work/private) currently, which is fine and useful in itself.
But from time to time I want to use another private/personal X instance, and it would be nice, if the copyq data could be shared.

From https://github.com/hluk/CopyQ/issues/416#issuecomment-159828708:

> There cannot be two running instances of the application because both would want to write and read the configuration and data. That would require using a system mutex or another server that handles writing/reading exclusively.

**Comment by hluk** [comment]
There should be at most one instance for each session. Using normal files with multiple instances of app is very dangerous (I would need to use database for config and items but that wouldn't solve all problems).

Anyway, I've created [command to synchronize clipboard with other sessions](https://gist.github.com/hluk/b1f69df944335f41242b). Let me know if that works or you have ideas for improvement.

**Comment by blueyed** [comment]
> command to synchronize clipboard with other sessions

Sounds useful, will try this later.

Thanks!

**Comment by blueyed** [comment]
Is there a way to check if copyq is already running with the provided session name?
The return code will be 0 (explained in https://github.com/hluk/CopyQ/issues/416#issuecomment-159828708).

Is it a good idea to just call e.g. `copyq tab` and then check its exit code?

**Comment by hluk** [comment]
Run `copyq eval ""` to check if the main app is running.

**Comment by aurora-of-earth** [comment]
@hluk 
- It would be better to store all copyq data of a session somewhere inside the .copyq folder. so one subfolder for every session.
- add an option to pass the config folder to copyq.

**Comment by hluk** [comment]
> * It would be better to store all copyq data of a session somewhere inside the .copyq folder. so one subfolder for every session.

I probably won't be changing this in near future because the change is complicated and very risky.

BTW, this already works for portable version of the app for Windows (everything is stored under `config\<session_name>\` subfolder).
 
> * add an option to pass the config folder to copyq.

This is already possible if you set environment variable `COPYQ_SETTINGS_PATH`.

**Comment by aurora-of-earth** [comment]
> BTW, this already works for portable version of the app for Windows (everything is stored under config\<session_name>\ subfolder).

I'm not running under Windows.

> This is already possible if you set environment variable COPYQ_SETTINGS_PATH.

Is it available in the documentation?

**Comment by hluk** [comment]
> Is it available in the documentation?

https://copyq.readthedocs.io/en/latest/sessions.html

**Comment by aurora-of-earth** [comment]
@hluk Nice, thanks.
