### ISSUE TITLE
New Command: Copy From PDF

### ISSUE THREAD

**Issue by babakm2** [hluk/CopyQ#432]
When I copy a column from a PDF file to Powerpoint or Word, they paste with a extra 'Enter' Like this:

"Markings begin by drawing the ideal position
for the resultant scar. This is along a line from
the medial epicondyle to the midaxillary line."

and need to this command: ENDkey SPACEkey DELETEkey and DOWNkey for next line and then END>SPACE>DELETE>DOWN... for changing to normal sentences like this:

"Markings begin by drawing the ideal position for the resultant scar. This is along a line from the medial epicondyle to the midaxillary line."

Please show a command for this.

**Comment by hluk** [comment]
You can use following automatic command -- just change the pattern for matching window title if needed (now it matches window titles containing `.pdf`).

```ini
[Command]
Automatic=true
Command="
    copyq:
    text = str(input()).replace(/(\\r\\n|\\n|\\r)/gm, \" \");
    copy(text)
    add(text)"
Icon=\xf039
Input=text/plain
Name=Reformat PDF text
Remove=true
Window=\\.pdf
```

**Comment by babakm2** [comment]
Wow,... Beautiful.
It is very useful... better than my idea.
Thanks a lot...
