### ISSUE TITLE
Write and Copy at the same time?

### ISSUE THREAD

**Issue by Brottweiler** [hluk/CopyQ#433]
I noticed that `copy` literally only copies, not adding to the CopyQ "history". `write` however adds it to the history, but it does **not** copy it. How do I do both at the same time? 

I have a bash script/bound to a key where I want it to `write` a screenshot I am taking but I also want it to `copy` to the clipboard, but right now I have to use `copy` only because `write` does not copy.

**Comment by hluk** [comment]
You can run following to take screenshot, store it in clipboard and the list.

    import png:- | copyq eval 'fmt = "image/png"; copy(fmt, input()); write(fmt, input())'

**Comment by Brottweiler** [comment]
Yep, I replaced my `copyq copy image/png -` with `copyq eval 'fmt = "image/png"; copy(fmt, input()); write(fmt, input())'` and it does what I want. Thanks. :smiley:
