### ISSUE TITLE
Popup accumulation

### ISSUE THREAD

**Issue by jmdsg** [hluk/CopyQ#440]
When i use the following command:

copyq: previous();
seconds = 2;
popup("", clipboard(), seconds \* 1000)

If I execute that command many times (when i am searching for a copy, I have to use this popup, otherwise i am not able to see the current text), eventually the popup windows disappear from the top of my screen, so i think it should be a way of killing the current popup windows when another one is called.

**Comment by hluk** [comment]
You can use newer `notification()` function. If you specify notification ID, existing notification can be reused.

```js
notification('.id', 'clipboard', '.message', clipboard(), '.time', seconds * 1000)
```
