### ISSUE TITLE
Support pasting into VirtualBox guests.

### ISSUE THREAD

**Issue by amosbird** [hluk/CopyQ#442]
I'm currently using ArchLinux as my host machine with CopyQ 2.5. I've set up a Windows guest with capturing keyboard disabled and bidirectional clipboard sharing. When I'm in the guest machine, invoking copyq-menu and paste, it does store the content into guest's clipboard. However I completely lose my keyboard inside guest. I have to wait for about a minute to let my Windows guest react on keyboard input. ![](http://i.imgur.com/oBciLCv.jpg)

I wonder if copyq can achieve seemless copy and paste between host and guest machine.

**Comment by hluk** [comment]
Works for me with:
- ArchLinux (host)
- Windows 8.1 (guest)
- Virtual Box 5.0.14-1 (keyboard capture disabled, bidirectional clipboard sharing enabled)
- CopyQ 2.6.0 (running on host)
- Notepad (target application for pasting on guest)

Could be problem with the target application.

**Comment by amosbird** [comment]
@hluk Does the content get directly inserted into targets?

**Comment by hluk** [comment]
@amosbird Yes, it does and the system is still responsive. But I tried only few apps.

**Comment by amosbird** [comment]
@hluk The only env difference between us are 1. `Windows 7 vs 8.1` and 2. `CopyQ 2.5 vs 2.6`. I've tried notepad, still not working.

**Comment by hluk** [comment]
@amosbird Check if you have latest VirtualBox extensions installed on host (from [AUR](https://aur.archlinux.org/packages/virtualbox-ext-oracle/)) and on guest (from the mounted virtual drive). Also try latest version of CopyQ (not sure if I fixed something related to this).

**Comment by amosbird** [comment]
After upgrading my system it works fine now :smile:

**Comment by amosbird** [comment]
@hluk It only works once a while. And I think I find the cause. I'm using the i3wm, `copyq-menu` fails to refocus on vbox guest window (or may focus in a way vbox doesn't know). Because my mouse is already in the region of the guest window, it fails to active vbox either. However, opening a new tiling window and switch my mouse between these two reactive vbox's keyboard.

**Comment by hluk** [comment]
How do you trigger the `copyq menu` command? Do you set the shortcut in Command dialog in CopyQ?

CopyQ stores ID of currently focused window before opening menu and tries to refocus the window before pasting. But it's possible that triggering the shortcut focuses different window (I think that's the case when using XFCE system shortcuts).

Note: I'm using XFCE with Openbox WM and shortcuts are configured in CopyQ and everything works fine.

**Comment by amosbird** [comment]
I trigger `copyq menu` with i3 config `bindsym Print exec "copyq menu"`. After chatting around in some IRC channels I've got a workable solution, that is to use `VBoxSDL` instead.

**Comment by hluk** [comment]
By default <kbd>Shift</kbd>+<kbd>Insert</kbd> shortcut is used for pasting -- check if it works in the target window. You can set option `paste_with_ctrl_v_windows` in your config file (`~/.config/copyq/copyq.conf`) to match windows titles you want to paste with <kbd>Ctrl</kbd>+<kbd>V</kbd>. For VirtualBox you should have something like following in your config file.

```ini
[General]
paste_with_ctrl_v_windows=VirtualBox
```

I have just changed the behavior a bit so CopyQ waits for user to release the shortcut before sending paste to an application -- seems to work better in some cases.

**Comment by amosbird** [comment]
@hluk <kbd>Shift</kbd>+<kbd>Insert</kbd> works fine. However I mainly use pop-up menu followed with <kbd>Enter</kbd> or <kbd>number</kbd> to insert. In this case `Copyq` still makes `VirtualBox GUI` lose its focus. I've updated to the newest version. It still remains the same.

**Comment by amosbird** [comment]
The root cause of this problem becomes clear now. It's due to the incompatible of `i3wm` and `VirtualBox GUI`. When focusing on the guest machine without capturing keyboard, issuing a `exec` command binded by `i3` will grab the focus to some null space. One way to regain focus without noticing is to execute this command `i3-msg "[class=$(xdotool getmouselocation --shell | awk -F= '/WINDOW/{print $2}' | xargs xprop -id | awk '/WM_CLASS/{print $4}')] focus"` right after the focus lost.

However, `copyq menu` has to gain focus interactively, otherwise it's useless. I have no idea how I can regain focus to `VirtualBox GUI` correctly after `copyq menu` insert its content, since when the time `copyq menu` gets executed, `VirtualBox GUI` has already lost its focus to outer space.

**Comment by hluk** [comment]
Pasting from menu in i3 to VirtualBox still doesn't work for some reason. The correct window seems to have focus after menu item is activated but the shortcut doesn't go through (some keyboard modifiers seems to be still active afterward even though they are not physically pressed).

Pasting from main window works fine.
