### ISSUE TITLE
built-in Alt + n keys to switch between tabs

### ISSUE THREAD

**Issue by scottkosty** [hluk/CopyQ#445]
The ability to set Qt accelerator shortcuts in tab names is great and it is even documented in a user-friendly way at tab creation.

However, I personally find it easier to switch between tabs using the tab number. Perhaps this is because I am used to switching tabs in firefox or chromium. I wonder if other users have a similar reaction or am I alone in this preference?

I almost did not create this request because I tried to use the tab names to set it up how I like. I renamed the "clipboard" tab to "&1 clipboard" and my second tab to "&2 second". This is not ideal because it requires putting the numbers in the tab names, but it is acceptable. However, when I do that a new tab is created by copyQ called "clipboard". I guess that copyQ did not realize that I renamed the built-in "clipboard" tab.

**Comment by hluk** [comment]
Actually Ctrl+1, Ctrl+2 etc. (as in Chromium web browser) is implemented.

For Alt+1 etc. I think it's possible to create command.

**Comment by scottkosty** [comment]
Ah, indeed Ctrl + n work. I will look into creating commands for alt+n. Thanks.

**Comment by hluk** [comment]
Here you go :).

```ini
[Command]
Command="
    copyq:
    var shortcut = str(data(\"application/x-copyq-shortcut\"))
    
    var m = shortcut.match(/[0-9]/)
    var number = m[0] - 1
    
    var tabs = tab()
    if (number == -1)
      number = tabs.length - 1;
    if (number >= tabs.length)
      abort()
    
    var tabName = tabs[number];
    show(tabName)"
Icon=\xf162
InMenu=true
Name=Jump to Tab with Alt+Number
Shortcut=alt+1, alt+2, alt+3, alt+4, alt+5, alt+6, alt+7, alt+8, alt+9, alt+0
```

**Comment by scottkosty** [comment]
Thanks Lukáš for writing that up. I will be testing it.

Let's close this, because of the command you posted, and I imagine that it would not be good to hardcode these in there. The Qt tab widget I guess uses the ctrl shortcuts and maybe has a good reason for not including the duplicate alt shortcuts like chromium and firefox.

**Comment by hluk** [comment]
Note: Qt doesn't implement these shortcuts at all, it's custom code in CopyQ (I implemented it on request).

**Comment by scottkosty** [comment]
Ah good to know. Where in the code is this done?

**Comment by hluk** [comment]
The code is right [here](https://github.com/hluk/CopyQ/blob/ed3d9622d2963434884f44b8328524a947944551/src/gui/mainwindow.cpp#L1384).

Looking at the code more carefully: it tries to use <kbd>Alt</kbd> modifier but it's never triggered -- seems that Qt captures these shortcuts because of key hints like <kbd>Alt</kbd>+<kbd>F</kbd> for File menu.

**Comment by scottkosty** [comment]
Ah, does this mean an event filter would be necessary? (I'm just asking out of curiosity, not suggesting you implement it. Seems too risky to break something else for such a small and debatable improvement.)

**Comment by hluk** [comment]
I don't know where exactly the problem is -- the shortcut seem to be captured in [item list](https://github.com/hluk/CopyQ/blob/ed3d9622d2963434884f44b8328524a947944551/src/gui/clipboardbrowser.cpp#L1329) but it won't propagate to the main window where the tab shortcuts are handled.

**Comment by scottkosty** [comment]
Interesting. Maybe it is an issue with Qt. Thanks for the explanations.

**Comment by qizhihere** [comment]
@hluk @scottkosty Very smart code. I just adjusted your code to toggle Nth tab with global key Alt+N, but i can't get the right result. Do you know why?

```
[Command]
Name=Toggle Nth Tab
Command="
    copyq:
    var shortcut = str(data(\"application/x-copyq-shortcut\"));
    
    var m = shortcut.match(/[0-9]/);
    var number = m[0] - 1;
    
    var tabs = tab();
    if (number == -1) {
      number = tabs.length - 1;
    }
    if (number >= tabs.length) {
      abort();
    }
    
    var tabName = tabs[number];
    if (visible() && selectedTab() == tabName) {
      hide();
    }
    else {
      show(tabName);  
    }"
IsGlobalShortcut=true
Icon=\xf162
Shortcut=alt+1, alt+2, alt+3, alt+4, alt+5, alt+6, alt+7, alt+8, alt+9, alt+0
GlobalShortcut=alt+1, alt+2, alt+3, alt+4, alt+5, alt+6, alt+7, alt+8, alt+9, alt+0
```

**Comment by hluk** [comment]
@qizhihere Can you add `popup(shortcut)` line under the `var shortcut = ...` to see if the command is triggered by a global shortcut? It should show popup notification with the shortcut name when triggered.

**Comment by qizhihere** [comment]
@hluk I added `popup(shortcut)` and it shows `Alt+1` When i press `Alt+1`. But when i add `popup(selectedTab() == "");` below, the result is `true`. It seems `selectedTab()` doesn't work properly?

```
var shortcut = str(data("application/x-copyq-shortcut"));

var m = shortcut.match(/[0-9]/);
var number = m[0] - 1;

var tabs = tab();
if (number == -1) {
  number = tabs.length - 1;
}
if (number >= tabs.length) {
  abort();
}

popup(selectedTab() == "");
var tabName = tabs[number];
if (visible() && selectedTab() == tabName) {
  hide();
}
else {
  show(tabName);  
}
```

**Comment by hluk** [comment]
Ah, yes, `selectedTab()` [works only from commands triggered from menu or using shortcut from main window](https://copyq.readthedocs.io/en/latest/scripting-api.html#selected-items).

**Comment by qizhihere** [comment]
@hluk Okay. is there another way to implement this? i'd like to toggle a specific tab with just a global key. if the window is already visible, just switch to that tab.

**Comment by hluk** [comment]
If you don't need to hide the main window with those shortcuts, you can replace the last part of the command with:

```js
var tabName = tabs[number];
show(tabName);
```

Interestingly, checking which tab is selected is not possible with global shortcuts -- this was intentional because it's strange to change selected tab (and item selection) when main window is not active. Maybe I should change the behavior a bit.

**Comment by qizhihere** [comment]
Ok, thx. Sometimes it's not so convenient to use two different shortcuts to toggle main window and switch tabs. Personally, i think the logic to toggle tab is: If the main window is invisible, then pop it up. If it's already visible(maybe inactive), just simply activate the main window and switch to that tab.

Anyway, when i press the toggle key, i just want that tab activated so i can choose one item from it.
