### ISSUE TITLE
Problem with passing text from CopyQ to Remote Desktop

### ISSUE THREAD

**Issue by Quaturn** [hluk/CopyQ#446]
Hello, I am using windows 7 64-bit and have installed latest version of CopyQ v2.6.0.

The problem is that after I open menu with global shortcut (CTRL+`) and choose the object (text) to be pasted from clipboard to the program running in remote desktop it does not past it there.

It just past it to normal clipboard (CTRL+V) so I need to open the menu pick up an item press ENTER and then pressing CTRL+V to past it to the remote desktop.

It is an issue because Ditto for example can past the selected item directly into app running in remote desktop.

P.S.: The system running in remote desktop is windows 2012

**Comment by hluk** [comment]
Closing (old issue). If it's still a problem, please reopen.

(BTW, CopyQ send Shift+Insert shortcut to target app to paste by default.)

**Comment by Laweena** [comment]
I noticed this behavior too, using version 3.9.3. I was hoping that maybe switching paste method from insert to ctrl-v would help, but it doesn't paste anything and seems to stick the control key in the down state every other time.
