### ISSUE TITLE
Problem with hot keys after updating to v2.6.0

### ISSUE THREAD

**Issue by online** [hluk/CopyQ#447]
Hello, @hluk!

After updating to version 2.6.0 ceased to operate such command:

```
[Command]
Name=Show/hide main window
Command=copyq: toggle()
Icon=\xf022
GlobalShortcut=meta+ctrl+x
```

I use a combination of keys `Windows` + `Ctrl` + `X` but nothing happens. In previous versions this command worked properly. The problem started in version 2.6.0.

Please help me solve this problem.

**Comment by hluk** [comment]
This should be fixed now. I'll try to release version with the fix soon.

**Comment by hluk** [comment]
[CopyQ 2.6.1](https://github.com/hluk/CopyQ/releases/tag/v2.6.1) is released. Reopen if you still have the issue.

**Comment by online** [comment]
@hluk It seems to work fine. Thank you! :+1:

**Comment by online** [comment]
@hluk But I can not assign keyboard shortcuts `Windows` + `Ctrl` + `S`.

**Comment by hluk** [comment]
@online Seems to work on Windows 8 with US keyboard layout.

What keyboard layout do you use?

Did you try to reassign the shortcut in new version of CopyQ?

**Comment by online** [comment]
@hluk I'm using Windows 10 (x64) with [Typography Layout](http://ilyabirman.net/projects/typography-layout/) (English and Russian). In version [v2.5.0](https://github.com/hluk/CopyQ/releases/tag/v2.5.0) shortcuts worked fine.

I installed version [v2.6.1](https://github.com/hluk/CopyQ/releases/tag/v2.6.1), shortcuts `Windows` + `Ctrl` + `X` still don't work.

Screenshot of all commands that I use:

![2016-02-15 00 04 47](https://cloud.githubusercontent.com/assets/722881/13036723/d924539a-d377-11e5-820c-dd902eab416a.png)

And here's `.ini` file with all commands: [All_commands_CopyQ.ini](https://www.dropbox.com/s/h9gpeofgwryt7sk/All_commands_CopyQ.ini?dl=0)

**Comment by hluk** [comment]
Should be fixed now (at least for Russian keyboard layout with those particular shortcuts).

**Comment by online** [comment]
@hluk I'll wait for the new build of CopyQ. Thanks!

**Comment by hluk** [comment]
@online You can test it with automatic build [here](https://ci.appveyor.com/project/hluk/copyq/build/artifacts) (it's Qt 5 version of the app but I assume there won't be too many differences to Qt 4 version which is used for releases).

**Comment by online** [comment]
@hluk It seems work for me (v2.6.1-2-ga49969c), but I don't know how to add a portable version in startup menu of OS.

Sorry for my bad English.

**Comment by hluk** [comment]
@online You should be able to create shortcut in startup menu with:
- right click on startup and select "Open" and
- drag'n'drop "copyq.exe" from unzipped folder with right mouse button and select "Create shortcuts here".

**Comment by online** [comment]
@hluk Thank you, check how it works.

**Comment by online** [comment]
@hluk When I move the main window of the program, I see a small lags (v2.6.1-2-ga49969c).

**Comment by hluk** [comment]
@online That's probably because it uses Qt 5. I'll try to improve performance for next release.
