### ISSUE TITLE
Remapped `Return` key fails in pasting to destination.

### ISSUE THREAD

**Issue by amosbird** [hluk/CopyQ#451]
I've achieved this remapping: `Ctrl-L ===> Return` using `xbindkeys`.

```
"xdotool getwindowfocus key -clearmodifiers --window %@ Return"
  control+ l
```

It works pretty fine. However, neither `Copyq menu` or `Copyq main window` fails in pasting with this remapping.

**Comment by hluk** [comment]
Which version do you use? Did this work in previous versions?

In v2.6.1 I [changed](https://github.com/hluk/CopyQ/commit/4949cfad406e397e089755b96a15e9f5bf583dd1) how <kbd>Ctrl</kbd>+<kbd>V</kbd> shortcut is sent to target application to paste text. I actually found out that it works better now.

It quite possible that `xdotool` clashes with CopyQ (both use X11 libraries to send key presses/releases).

**Comment by amosbird** [comment]
It's v2.6.1. I think it may be `xdotool`'s problem too. How can I directly set this key binding for `copyq menu`?

**Comment by hluk** [comment]
Unfortunately it's not possible to use custom shortcuts in menu.

Perhaps you can get this working by disabling  "Paste activated item to current window" in "Tray" config tab in CopyQ and use following config line for `xbindkeys`.

```
"xdotool getwindowfocus key -clearmodifiers --window %@ Return && copyq paste"
  control+l
```

**Comment by amosbird** [comment]
Oh, that would be an overkill since I only want `ctrl-l` to send `return`. It would be very nice if `copyq menu` can use home row alphabetics or customized one as index rather than numbers.

**Comment by hluk** [comment]
I just tried the `xbindkeys` configuration and for me the <kbd>Return</kbd> key is not even sent to the menu. This is not working in gedit either. It's possibly problem with `xdotool` (or it's not possible to pass the key presses to some windows) so I'm closing this.
