### ISSUE TITLE
CopyQ Line Termination Incorrect for Windows + NotePad = BAD

### ISSUE THREAD

**Issue by dbareis** [hluk/CopyQ#453]
On Windows lines should be terminated with CR & LF and not just LF.

This makes it harder to work with and makes the use of "notepad" as the default external editor a very poor choice as it doesn't recognise the line breaks.

Best would be if CopyQ worked better in Windows however a quick win would be to use "wordpad" instead of "notepad" (however as its not in the path its a little more complicated than that).

**Comment by hluk** [comment]
This is a very old issue. I'm closing this. Please reopen if it is still a problem.
