### ISSUE TITLE
store text selected using mouse (on windows 10)

### ISSUE THREAD

**Issue by Heart1010** [hluk/CopyQ#454]
I switched from Linux to Win10 with one pc. What I really like in Linux is when I select a text with my mouse this text is immediately stored into the clipboard. (without pressing ctrl+c for example)

On Win10 this doesn't work (default).

So is there a setting I missed for that feature?

Thanks

**Comment by hluk** [comment]
Only Linux/X11 supports mouse selections (Qt mentions it [here](https://doc.qt.io/qt-4.8/qclipboard.html#notes-for-windows-and-mac-os-x-users)).
