### ISSUE TITLE
GUI: Gearwheel symbol appears twice. But each symbol has a different function.

### ISSUE THREAD

**Issue by pre55** [hluk/CopyQ#456]
##### Problem:
![CopyQ261_improvement_1_GUI_problem](http://abload.de/img/copyq261_improvement_wgs1g.png)

##### Possible Solution (instead of - "Action F5"):
![Action](http://abload.de/img/actiontesub.png)
_If you need this vector icon, plz msg me. I could provide it to you for free._

PS: Imho "Ausführen" is'nt the right German tranlation for "Action" in this case. 
I recommend using "Aktion" instead.

**Comment by hluk** [comment]
I'm using icons from [Font Awesome](https://fortawesome.github.io/Font-Awesome/cheatsheet/). Seeing circled "play" icon reminds me of video player (and I use the icon in my custom "play" command).

But you're right, the current icon really should be replaced, the problem now is finding the right icon...

I changed the translation, thanks. BTW, you can add or fix German translations [here](https://hosted.weblate.org/projects/copyq/master/de/).
