### ISSUE TITLE
Start CopyQ with deactivated clipboard monitoring

### ISSUE THREAD

**Issue by pre55** [hluk/CopyQ#458]
I have not found a solution to start CopyQ with deactivated clipboard monitoring.
Perhaps you could define a cmd-parameter which makes that possible.

**Comment by hluk** [comment]
To permanently disable clipboard storing, use the "Store clipboard" option in Preferences.

You can map a shortcut to a command that would switch the option on/off ([here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)):

```ini
[Command]
Command="
    copyq:
    const enable = config('check_clipboard') === 'false'
    config(
        'check_clipboard', enable,
        'check_selection', enable,
    )
    iconTagColor('red')
    iconTag(enable ? '' : '\xf05e')"
Icon=\xf05e
InMenu=true
Name=Toggle Clipboard Storing
```
