### ISSUE TITLE
Only copy to PRIMARY (middle-mouse)

### ISSUE THREAD

**Issue by blueyed** [hluk/CopyQ#459]
While there is "Paste clipboard with mouse" option, which makes the copied content also available to be pasted by middle-click (PRIMARY), there's no way to only put it in there, without changing the CLIPBOARD contents, is there?

**Comment by hluk** [comment]
I'm not sure if I understand what you mean. The option "Paste clipboard with mouse" just propagates clipboard to selection buffer, clipboard content doesn't change.

**Comment by blueyed** [comment]
I've meant that when I select an entry from the item list (`copyq: showAt()`), it will be put into both the clipboard (and optionally the selection) clipboard.  But I'd like it to not change the clipboard (but only the selection).  (It's not about CopyQ's input handling, but its output).

**Comment by hluk** [comment]
You can override <kbd>Enter</kbd> key so it copies selected items only to selection.

```ini
[Command]
Command=copyq:\nhide()\ncopySelection(input())
Icon=\xf016
InMenu=true
Input=text/plain
Name=Copy selected items
Shortcut=return, enter
```

Unfortunately it's not possible to do this when using mouse button to activate an item.

**Comment by hluk** [comment]
OK, I've made some changes and the command above will work in next version even when double-clicking on an item (command needs to override shortcut <kbd>Enter</kbd> or <kbd>Return</kbd>).
