### ISSUE TITLE
Improved Tags

### ISSUE THREAD

**Issue by hluk** [hluk/CopyQ#461]
Simplify tags configuration:
- tag preview
- predefined styles
- apply all matching styles from the list (not only first matching)
- format can be defined to handle texts captured in regex

Default style can be simpler -- no border and colors taken from theme if possible, e.g.:
![image](https://cloud.githubusercontent.com/assets/38054/13595341/d7e99c16-e50a-11e5-83d2-52cfaa7587e4.png)

**Comment by PEG71** [comment]
Would be nice to be able to use tags to search/filter.

**Comment by hluk** [comment]
@PEG71 You can search text in tags the same way as any text in items -- just start typing and items with any matching tag with be shown. Did you mean something different?
