### ISSUE TITLE
Could you make Deb Package for Ubuntu 16.04?

### ISSUE THREAD

**Issue by nemonein** [hluk/CopyQ#463]
Hi.
Thank you for your GREAT software.
I tried install CopyQ (for Ubuntu 15.10) in Ubuntu 16.04, but I failed because of libqt4-gui package dependency.
Can you solve the problem?

Thanks in advance!

**Comment by hluk** [comment]
Sorry, unless it's available at [OBS](https://build.opensuse.org) (where the packages are built) I cannot create the package. I'll add it as soon as it's available on OBS.

**Comment by nemonein** [comment]
OK, I see.
Thanks!

**Comment by scottkosty** [comment]
Note that it is quite easy to build from source. Feel free to ask if you want instructions.

**Comment by nemonein** [comment]
@scottkosty 
I really appreciate it if you could teach me how to do it.
I wish I could use 'dpkg-buildpackage -b'.

Thanks in advance.

**Comment by scottkosty** [comment]
OK let's give it a shot. After you paste the following into a terminal, can you copy all of the output from the terminal and paste it here?

```
sudo apt-get install git cmake qttools5-dev libqt5v8-5-dev libqt5svg5-dev qtscript5-dev qttools5-dev-tools libxtst-dev build-essential qtbase5-private-dev &&
git clone "https://github.com/hluk/CopyQ.git" &&
cd "CopyQ" &&
cmake . &&
make &&
sudo make install
```

**Comment by nemonein** [comment]
libqt5v8-5-dev is missing in Ubuntu 16.04 repository.
I excluded it, and ran other commands you wrote.

Everything works fine, and the install was successful.
Thank you so much, scottkosty!

'libqt4-gui' is not needed for CopyQ to run?
I haven't tested well enough, but CopyQ which I compiled, was working without any problem.

And One more thing please.
I would like to make a Deb package, but there are no DEBIAN folder in the source code.
Can you help me with that too?

**Comment by hluk** [comment]
You can use the Debian files from [OBS](https://build.opensuse.org/package/show/home:lukho:copyq/CopyQ).

Package `libqt4-gui` is now needed because the package uses Qt 4 instead of Qt 5. I guess Qt 4 won't be supported by Ubuntu anymore.

**Comment by nemonein** [comment]
I've found another Debian files, http://anonscm.debian.org/cgit/collab-maint/copyq.git.
I don't know about packaging or programming, but I think it uses qt5.
I used it, and there were no errors while building, and CopyQ works fine at least the way I use it.

Here are the dependencies which was generated by building process, using collab-maint's debian files.
`Depends: libc6 (>= 2.14), libgcc1 (>= 1:3.0), libqt5core5a (>= 5.5.0), libqt5gui5 (>= 5.0.2) | libqt5gui5-gles (>= 5.0.2), libqt5network5 (>= 5.0.2), libqt5script5 (>= 5.0.2), libqt5webkit5 (>= 5.0.2), libqt5widgets5 (>= 5.4.0), libstdc++6 (>= 4.1.1), libx11-6, libxtst6`

How do you think about it?
Can I use it?

**Comment by hluk** [comment]
@nemonein Seems OK.

**Comment by nemonein** [comment]
I have found some misbehavior on my build.
If I right click on the icon(app indicator), then click 'show/hide' menu, the icon duplicates.
There happens to be two icons on indicator area. But that's it. Even if I click 'show/hide' again, only two indicators remain, no 3rd icon pops up.

Other than that, I think it works fine.
For anyone who'd like to use CopyQ 2.6.1 on Ubuntu 16.04 until official one is released, I uploaded the Deb package on my blog.
http://nemonein.egloos.com/5294962
It is written in a language most of you don't understand, so just find 'copyq-2.6.1.7z' in the page, then all you have to do is 'Download'.

Thank you @hluk and @scottkosty.
@hluk : You can close this issue.

**Comment by hluk** [comment]
@nemonein Well, indicators doesn't work well in some desktop environments with Qt apps (this is not bug in CopyQ or Qt). It has been broken for a long time and nobody seems to care enough to fix it (this is actually not the case for KDE where developers implemented indicators very nicely). There is unnecessary amount of issues submitted because of that, e.g. #431, and similar to your issue #296 (which was fixed by using a hack).

You can disable tray icon (indicator) in CopyQ settings so that the main window is minimized instead.

Thanks for the package!

**Comment by stefaanverstraeten** [comment]
I succeeded in installing thanks to the instructions (and removing libqt5v8-5-dev) and then I found out that a package is present in https://github.com/hluk/CopyQ/releases (copyq_3.0.0_Ubuntu_16.04_amd64.deb).

**Comment by orschiro** [comment]
@stefaanverstraeten which instructions?

**Comment by stefaanverstraeten** [comment]
@orschiro "scottkosty commented on Mar 12, 2016" in this thread (Could you make Deb Package for Ubuntu 16.04? #463), instructions to clone and install

**Comment by stefaanverstraeten** [comment]
@orschiro Oops, just found that you can link to the comment: https://github.com/hluk/CopyQ/issues/463#issuecomment-195806174

**Comment by orschiro** [comment]
Thinking, should we add these instructions to the README?

**Comment by hluk** [comment]
I've added the [build instructions](https://github.com/hluk/CopyQ/blob/master/README.md#build-from-source-code) and reorganized the sections in README file -- some proofreading is still needed.

**Comment by orschiro** [comment]
There you go: https://github.com/hluk/CopyQ/pull/704

:-)
