### ISSUE TITLE
Searching does not always filter

### ISSUE THREAD

**Issue by nochso** [hluk/CopyQ#466]
This seems fairly random to me. Sometimes when using the search, elements are highlighted but not filtered. If I add to the search term, it does get filtered.

Is this intentional because of performance reasons? If so, is there a setting or way to change this?

For example, I expect to see only entries containing `x`:

![Screenshot](http://i.imgur.com/reCjFJn.png)

**Comment by hluk** [comment]
Ah, yes, it actually filters using format names present in items ("x" matches "text/plain"). But it's quite confusing and I should change the behavior somehow.

**Comment by nochso** [comment]
I see. I didn't find anything in the `edit` menu item. Should have looked at `Show content` instead.

What's interesting, is that it doesn't actually search in the `text/html` content, only the `text/plain` which is exactly what I want.

If you could add a setting to disable searching the format names, that should be enough for me :)

**Comment by hluk** [comment]
I'll change it so you have to be more specific to match formats. You will need to write either the exact format name or match the it whole (e.g. `image/.*` to find all images, `.*/html` to find HTML formatted items).
