### ISSUE TITLE
Command Key lost function( CopyQ 2.6.1 in OSX 10.11.3)

### ISSUE THREAD

**Issue by cewolf2002** [hluk/CopyQ#468]
I installed CopyQ 2.6.1 in OSX 10.11.3.
I tried to create custom command.

Example:
Name : Paste and copy next
Global Shortcut : command + 1
Command : 
copyq: paste(); next()

Then applied.

And I noticed I can not select all by Command + A
Is this a bug?

**Comment by hluk** [comment]
I cannot test this on OS X. The command seem to work on Linux. Can it be that the shortcut is not recognized? Or is the next item in CopyQ selected at least? (Pasting to some windows may not work.)

<kbd>Ctrl</kbd>+<kbd>A</kbd> to select all items work fine for me but I don't think I change the default behavior implemented by Qt.

**Comment by cewolf2002** [comment]
I tried to set another global shortcut including command key.
And will let command + A lose function.

**Comment by hluk** [comment]
I finally got chance to fix OS X issues. I'm on OS X 10.11.6 and cannot reproduce this with CopyQ v2.9.0.

Reopen this if it's still an issue.
