### ISSUE TITLE
Coredump with 2.6.0

### ISSUE THREAD

**Issue by marmotz** [hluk/CopyQ#471]
Hi, on my system (Antergos, an ArchLinux derivated distribution), if I install 2.5.0 (from https://aur.archlinux.org/packages/copyq/), all is working.
But if i install 2.6.0 (from https://github.com/Antergos/antergos-packages/tree/master/copyq), I have a coredump.

I've created an issue on this repo. But @lots0logs advised me to create an issue here.

So, when I launch copyq:
```
$ copyq
[1] 17068 illegal hardware instruction (core dumped) copyq
```
Here is my [coredump.zip](https://github.com/hluk/CopyQ/files/180702/coredump.zip) and its data:
```
$ coredumpctl info 17068
           PID: 17068 (copyq)
           UID: 1000 (marmotz)
           GID: 100 (users)
        Signal: 4 (ILL)
     Timestamp: sam. 2016-03-19 00:33:20 CET (19min ago)
  Command Line: copyq
    Executable: /usr/bin/copyq
 Control Group: /user.slice/user-1000.slice/session-c1.scope
          Unit: session-c1.scope
         Slice: user-1000.slice
       Session: c1
     Owner UID: 1000 (marmotz)
       Boot ID: 7bc85b945d1e4e74bd388f906e66d39b
    Machine ID: dea42d19b1b9458ebebb90fea05ba1dc
      Hostname: xiha
      Coredump: /var/lib/systemd/coredump/core.copyq.1000.7bc85b945d1e4e74bd388f906e66d39b.17068.1458344000000000000000.lz4
       Message: Process 17068 (copyq) of user 1000 dumped core.

                Stack trace of thread 17068:
                #0  0x000000000046aed4 n/a (copyq)
                #1  0x000000000046e220 _ZN15ClipboardServerC1ERiPPcRK7QString (copyq)
                #2  0x00000000004673e6 main (copyq)
                #3  0x00007fc6c4d3d710 __libc_start_main (libc.so.6)
                #4  0x00000000004676a9 _start (copyq)

                Stack trace of thread 17069:
                #0  0x00007fc6c4dfbc3d poll (libc.so.6)
                #1  0x00007fc6c38c2ae2 n/a (libxcb.so.1)
                #2  0x00007fc6c38c4757 xcb_wait_for_event (libxcb.so.1)
                #3  0x00007fc6bdf480a9 n/a (libQt5XcbQpa.so.5)
                #4  0x00007fc6c56fb9ae n/a (libQt5Core.so.5)
                #5  0x00007fc6c4b07424 start_thread (libpthread.so.0)
                #6  0x00007fc6c4e04cbd __clone (libc.so.6)
```

If someone can help me, it will be nice :)

**Comment by hluk** [comment]
Try arch package from [OBS](http://download.opensuse.org/repositories/home:/lukho:/copyq/Arch_Extra/).

**Comment by lots0logs** [comment]
@hluk We are using qt5 for our package. I see your Arch package is using qt4. Could this have anything to do with the issue? Could you take a look at our PKGBUILD and let me know if there's anything its missing? https://github.com/Antergos/antergos-packages/blob/master/copyq/PKGBUILD

**Comment by hluk** [comment]
Both Qt 4 and Qt 5 versions of the app should be stable (I use Qt 5 version without any crashes).

The core dump would be more helpful if you can run the app in debug mode (build with `-DCMAKE_BUILD_TYPE=Debug` switch for `cmake`).

Can you also post ouput of `ldd "$(which copyq)"`?

**Comment by marmotz** [comment]
@hluk it works fine now. @lots0logs have updated something and CopyQ 2.6.1 is working :)

Thanks for your help

**Comment by hluk** [comment]
Glad to hear it works.
