### ISSUE TITLE
How to import ClipXes history clipboard (.clx file) to CopyQ?

### ISSUE THREAD

**Issue by Piter432** [hluk/CopyQ#472]
Hi.

I found your program and looks nice, options also looking useful for me, especially that I'm using ClipX. However, I want to import ClipXes clipboard history (.clx file) to ClipQ. How I can do that? Maybe clipboard history import option, which will also support ClipXes clipboard history file (I haven't tested exporting/saving clipboard history for other clipboard managers so much)?

**Comment by hluk** [comment]
I probably won't ever bother implementing import/export to less known formats. But since CopyQ provides scripting capabilities you might be able to write some importers and exporters yourself (though it would require some experience).
