### ISSUE TITLE
Feature request: allow automatically assign into tabs from specific data types\regex

### ISSUE THREAD

**Issue by royharoush** [hluk/CopyQ#475]
Hi, 
It would be nice to automatically assign into tabs(or an entirely new tag-based assignment), from data types or regex. 
use cases: 
1. auto assign all screenshots into a specific tab based on their data type (e.g, text/bmp).
2. auto assign links, or links to specific web sites, based on the url or the exitance of http\s in the links or note. 

i think this would really help organize the notes kept. 

Thanks, 
Roy

**Comment by hluk** [comment]
Did you check predefined command "Copy URL (web address) to other tab"?

To add the command:
1. open Command dialog <kdb>F6</kdb>,
2. click Add button,
3. select the command from list and click OK,
4. new commands by clicking on OK or Apply button.

When you copy an URL now, it should be added to "web" tab (as well as clipboard tab).

Read more about commands [here](https://github.com/hluk/CopyQ/wiki/Writing-Commands-and-Adding-Functionality).

Some more complicated command are available [here](https://github.com/hluk/CopyQ/wiki/Command-Examples).

Does that help?

**Comment by royharoush** [comment]
you, my friend, is awesome !
