### ISSUE TITLE
Can't hide the main copyq window

### ISSUE THREAD

**Issue by bag-man** [hluk/CopyQ#476]
I'm running Manjaro and Xmonad and I have just updated to copyq 2.6.1. 

Previously I was able to hide copyq from my tray and have no active windows open associated with it. Now however when I launch copyq with `copyq &` in my .xinitrc, I am faced with the main copyq window, and I don't seem to be able to hide or close it in any way. 

Has something related to this changed recently? What information could I help provide you with?

**Comment by hluk** [comment]
See #474 (there will be new option in next version to hide the main window when closed).

**Comment by bag-man** [comment]
Nice one, thanks!
