### ISSUE TITLE
bug: commands  - store copy time

### ISSUE THREAD

**Issue by royharoush** [hluk/CopyQ#477]
Hi,
not sure if you will support global commands, but..
i've tried using the default "store copy time" from both the faq and from the gist. 
both give me the error shown below when copying.

> 
> Command “copyq: var time = dateSt… setData(tagsMime, tags)”
> Exit code: 1
> CopyQ client ERROR: ReferenceError: Can't find variable: setData 
> --- backtrace --- 
> <anonymous>()@:3 
> --- end backtrace --- 

the command code is below. 
> ---
> copyq: 
>     var time = dateString('yyyy-MM-dd hh:mm:ss')
>     setData('application/x-copyq-user-copy-time', time)
> 
>     var tagsMime = 'application/x-copyq-tags'
>     var tags = str(data(tagsMime)) + ', ' + time
>     setData(tagsMime, tags)
> ---

Thanks ! 
Roy

**Comment by hluk** [comment]
It requires version which has not been released yet (mentioned on the wiki: "Requires CopyQ version **greater** than 2.6.1"). Sorry for the confusion.

**Comment by royharoush** [comment]
would it work if i compile from the source code ?

**Comment by hluk** [comment]
Yes. If you are on Windows, you can use automatically build package from [here](https://ci.appveyor.com/project/hluk/copyq/build/artifacts).
