### ISSUE TITLE
How to autostart CopyQ with main window in foreground?

### ISSUE THREAD

**Issue by orschiro** [hluk/CopyQ#483]
Dear all, 

I would like to autostart CopyQ with the main window being opened in the foreground on my Ubuntu 15.10 installation.

Any ideas how to do this?

By main window I refer to the one storing the tabs with the content.

Thankfully,

~Robert

**Comment by hluk** [comment]
There is no simple way to do this now. You can run `copyq show` after the application is started. So you can edit CopyQ's autostart file `~/.config/autostart/copyq.desktop` and edit line starting with `Exec=` to following.

```ini
Exec=sh -c "copyq & sleep 1; copyq show"
```

(You may need to increase the sleep interval in the command.)

**Comment by orschiro** [comment]
Dear @Lukas,

  

Thanks for your workaround!

  

I guess it might actually work to add `copyq show` to the list of startup
applications, correct?

  

Warmly,

  

~Robert

  
Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On Apr 9 2016, at 7:33 am, Lukas Holecek &lt;notifications@github.com&gt;
wrote:  

> There is no simple way to do this now. You can run copyq show after the
application is started. So you can edit CopyQ's autostart file
~/.config/autostart/copyq.desktop and edit line starting with Exec= to
following.

>  
>  
>     Exec=sh -c "copyq & sleep 1; copyq show"

>

> (You may need to increase the sleep interval in the command.)

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on GitHub](https://github.com/hluk/Co
pyQ/issues/483#issuecomment-207713910)![](https://github.com/notifications/bea
con/AAKbwyo_L8NGmxZsSVvV4bdLP0RKfuJ1ks5p1zoWgaJpZM4IA2gC.gif)

**Comment by hluk** [comment]
You actually have to wait few milliseconds after `copyq` command so the "command server" can start. So perhaps you can add `sleep 1; copyq show` to start after the server.

**Comment by orschiro** [comment]
&gt; sleep 1; copyq show to start after the server.  
  
Nice addition. Thanks!

  

~Robert

  

Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On Apr 11 2016, at 5:56 pm, Lukas Holecek &lt;notifications@github.com&gt;
wrote:  

> You actually have to wait few milliseconds after copyq command so the
"command server" can start. So perhaps you can add sleep 1; copyq show to
start after the server.

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on GitHub](https://github.com/hluk/Co
pyQ/issues/483#issuecomment-208419476)![](https://github.com/notifications/bea
con/AAKbw_vH3f8XuIV_fgm8rFoJE8uv8NxDks5p2m8-gaJpZM4IA2gC.gif)

**Comment by orschiro** [comment]
Hi all, 

I was experimenting with the above but it actually doesn't launch the main window. 

Any ideas why this could not be working properly?

Thankfully,

~Robert

![image](https://cloud.githubusercontent.com/assets/170947/14845814/fd10fa02-0c60-11e6-8892-7dcaea1763f4.png)

![image](https://cloud.githubusercontent.com/assets/170947/14845826/081b73a0-0c61-11e6-8216-8eb9afe7c38b.png)

**Comment by hluk** [comment]
Hi Robert,

I think it should work if you set "Command" in "Startup Applications"
dialog as following.

    sh -c "copyq; sleep 2; copyq show"

Lukas

2016-04-27 10:16 GMT+02:00 Robert Orzanna <notifications@github.com>:

**Comment by orschiro** [comment]
Dear Lukas, 

This does work.

Thank you so much! :+1: 

~Robert
