### ISSUE TITLE
How can I get the current user's home directory?

### ISSUE THREAD

**Issue by nemonein** [hluk/CopyQ#484]
Hi.

I need to get the user's home directory(Absolute path), in CopyQ's command.(on Custom Actions)
I've tried this and it works.. (I have little knowledge about Qt scripts.)
```
var homeD = new Dir().homePath()
```
Am I doing OK?
Is there a better way to get the home path?

**Comment by hluk** [comment]
`Dir().homePath()` should be enough.

**Comment by nemonein** [comment]
Thanks!
