### ISSUE TITLE
search all tabs?

### ISSUE THREAD

**Issue by drocsid** [hluk/CopyQ#486]
Hello,

Been using copyQ for about 2 years now, and it kicks ass! I really use it to keep notes on many different things. I use quite a few tabs (maybe about 200) and one thing is that it's sometimes hard to find my content with my own tab index. Then it appears that the search only works on the currently selected tab. To make my life easier it would be nice if I could search all the tabs at once. 

Alternatively I might look into finding a quick way to do this from the terminal.

**Comment by royharoush** [comment]
There's a commnad for that🙏
Look in the hluk's gists

**Comment by royharoush** [comment]
https://gist.github.com/hluk/95889230aeea2388dea5

**Comment by forteller** [comment]
What do I do with this code?

**Comment by royharoush** [comment]
Press f6 and then paste from clipboard, you will have a new command that
will search all tabs when you ctrl alt f

**Comment by drocsid** [comment]
Wow, looks like that creates a new tab with the search results. Not exactly what I was thinking, but it's pretty cool, and works. Then I will close this.

**Comment by royharoush** [comment]
you're welcome ;)

**Comment by drocsid** [comment]
@royharoush: thanks!
