### ISSUE TITLE
Stop to show clips

### ISSUE THREAD

**Issue by didomen** [hluk/CopyQ#487]
Hello,
my copyq stop to save clips and show them in the tab, i tried uninstall it and re-install but it doesn't work.
It star normally and i've it in tray icon but the tab is always empty.
Maybe it's a demo version?
best reguards
![image](https://cloud.githubusercontent.com/assets/18418736/14459931/289730da-00bb-11e6-9606-b5c305bb02d2.png)

**Comment by hluk** [comment]
@didomen I'm afraid that the file with saved items could be corrupted or not-readable. Can you install new version of CopyQ and see log <kbd>F12</kbd>?
