### ISSUE TITLE
Replace/remove a character 

### ISSUE THREAD

**Issue by ZIEXED** [hluk/CopyQ#489]
I want to remove the spaces from `"^ [0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3} $"`
when I copy this I want it to be replaced [in history and in clipboard]
is this possible?
" 8.8.8.8 " > "8.8.8.8"

_btw the current command syntax is very complex and uncomfortable_

**Comment by hluk** [comment]
Following command should help (copy/paste to Command dialog <kbd>F6</kbd>).

I've added some comments for clarity -- for more info see [scripting reference](https://github.com/hluk/CopyQ/blob/master/src/scriptable/README.md).

```ini
[Command]
Automatic=true
Command="
    copyq:
    // Omit running next automatic commands and
    // adding current clipboard to item list.
    ignore()
    
    // Get text from clipboard.
    var oldText = str(data('text/plain'))
    
    // Remove whitespace from start and end of the text.
    var newText = oldText.trim()
    
    // Add new text to item list.
    add(newText)
    
    // Copy new text to clipboard.
    copy(newText)"
Icon=\xf016
Match="^ [0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3} $"
Name=IP - Trim Whitespace
```

> btw the current command syntax is very complex and uncomfortable

If you have any specific ideas I'm all ears.

**Comment by ZIEXED** [comment]
Thanks for your help
I will look at the QT scripting later
For now your command works great
Thanks again ♥

**Comment by elmaure** [comment]
Hi, i need something similar but i can not figure this out.
I work alot with ID numbers, eg. 34.803.198, i need to remove the dots when i copy, to paste the clip without the dots.
Example, of what i need
i select the number "34.803.198"
i press ctrl + c to copy
i pop up copyq with my hotkey (ctrl + shift + v)
i select the item in clipboard and press some hotkey to remove the dots from the string
The result is "34803198" in my copyq clipboard.

I hope you understand my english :D . I already did soemthing similar to remove blank spaces but can not do the same with the dots, i already give up on this, so if something can help me i thank you a lot
