### ISSUE TITLE
Feature idea: Insert element at defined shortcut

### ISSUE THREAD

**Issue by MortenZdk** [hluk/CopyQ#490]
Enable definition of a key combination for an item, whereby the item is inserted when the key combination is typed.

E.g. 

Best regards,
MortenZdk

could be inserted when the combination "BRMZ" was typed.

Inspiration can be found here: www.nch.com.au/fastfox/

Best regards,
MortenZdk

**Comment by hluk** [comment]
I think this feature has been already suggested. It would be great though probably too difficult to implement for all supported platforms (if it's even possible to do everywhere).

What you can do now is to create command which pastes custom text when triggered on global shortcut.

```ini
[Command]
Command="
    copyq:
    var time = dateString('yyyy-MM-dd hh:mm:ss')
    copy(\"Current date/time is \" + time)
    paste()"
GlobalShortcut=meta+alt+t
Icon=\xf017
Name=Paste Current Time
```

Alternatively you can have selection box with some predefined stuff to insert.

```ini
[Command]
Command="
    copyq:
    stuff = [
    'Hello,\\n',
    
    'Time ' + dateString('yyyy-MM-dd hh:mm:ss'),
    
    'Best regards,\\n'
    + (str(env('USER')) || str(env('USERNAME'))),
    ]
    
    var text = dialog('Insert', stuff)
    if (!text)
      abort()
    
    copy(text)
    paste()
    "
GlobalShortcut=meta+alt+i
Icon=\xf040
Name=Insert Stuff
```

**Comment by m4r71n** [comment]
@MortenZdk you could also try the Snippets command: https://gist.github.com/hluk/af37cd2ca650c92ed0fa

**Comment by MortenZdk** [comment]
Thanks for the replies.

I can see that it is possible with some additional scripting, and that is great also for more complex output like the date.

However, the idea was that it should be as easy as simply copying something, and then add a shortcut to the copied item.  For a general phrase to keep, it could then be moved to a defined phrase tab.

Probably not possible to implement on all platforms, but a pity if the lowest common denominator should stop a useful feature to be implemented on some platforms, though re recognize the implementation difficult that may give.

Best regards
MortenZdk
(Written using an AutoHotkey shortcut and instead of a CopyQ shortcut ;-)
