### ISSUE TITLE
Bug: Copying a text that includes a previously copied text overwrites the latter

### ISSUE THREAD

**Issue by forteller** [hluk/CopyQ#491]
This has happened to me quite a lot lately: I copy a URL and paste it into a text I'm writing. Then I copy the whole text I just wrote, including the URL. The next time I want to paste only the URL I open the CopyQ window, just to find that the URL is no longer listed there as a separate item. It's just gone.

I use Ubuntu Gnome 15.10 64 bit.

**Comment by hluk** [comment]
If new item (copied using mouse) contains text of the first item in list (previously copied text), the first item is just replaced. This is used as workaround when some apps constantly update clipboard - e.g. if you mark some text in visual mode in gvim it copies selected text even if the selection is incomplete which spams clipboard tab in CopyQ with incomplete useless items.

(Relevant discussion in #460.)

I'm not sure if I can remove the workaround completely - I think I've only seen the behavior in gvim.
