### ISSUE TITLE
inkscapes format in vector - images broken

### ISSUE THREAD

**Issue by SamHasler** [hluk/CopyQ#492]
In `Preferences > Items > Data` clicking on `Images > Vector Graphics` adds the following to the Data plugin's list of active formats: 
```
image/svg+xml
image/x-inkscape-svg-compressed
```

However, when I copy something in inkscape, I still only see the bmp/jpg/png formats, not the svg.

I'm using Inkscape 0.91 r13725

**Comment by hluk** [comment]
If you enabled `Preferences > Items > Images` it should already store `image/svg+xml` format (which seems to be supported by Inkscape) -- you can check available formats in clipboard by opening Clipboard Content dialog (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>C</kbd>).

![image](https://cloud.githubusercontent.com/assets/38054/14765848/9a6d0300-09f4-11e6-8052-eaa3466029ea.png)

Note: I had to install `python2-lxml` on Arch Linux to be able to copy stuff in Inkscape and perhaps some other libraries are required to store SVG in clipboard.

**Comment by scottkosty** [comment]
By the way, I imagine you use Qt to render the SVG (in the Content frame). Note that Qt does not support all SVG formats. Specifically, it only supports SVG 1.2 Tiny. See here for more information: http://doc.qt.io/qt-5/svgrendering.html .

The only reason I mention this is that it is good to be aware of so you don't think it is a problem with your code. At LyX we are dealing with this issue at http://www.lyx.org/trac/ticket/9778 and we might deal with this issue by using an external converter.

**Comment by hluk** [comment]
Thanks for mentioning that problem @scottkosty.

It's quite possible that an item in CopyQ has SVG format but nothing shows up (I think this can even happen when copying text from Inkscape) or the rendering is not correct (you can inspect item formats using <kbd>F4</kbd>).

[I just fixed this](https://github.com/hluk/CopyQ/commit/3111e12ed925261a9e199da44f0ea6409a218f16) so SVG won't be rendered if some bitmap formats are available.

**Comment by scottkosty** [comment]
Seems like a good idea. Although it would be nice to use the vector format first, I think what you did is a good decision, considering the circumstances.

**Comment by SamHasler** [comment]
Thanks for pointing out the <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>C</kbd> shortcut. Somehow I'd overlooked that. Perhaps it should be on the toolbar.

Inkscape is only putting `image/x-inkscape-svg` on the clipboard, not any of these:
* `image/svg+xml`
* `image/svg+xml-compressed`
* `image/x-inkscape-svg-compressed`


Once I added `image/x-inkscape-svg` copyq stored the SVG format in it's history, which resolves this issue for me, although perhaps you want to add `image/x-inkscape-svg` and `image/svg+xml-compressed` to the vector formats.

However I wasn't able to see the svg "text" itself. What I'd really like is a "raw" view of any image/rendered format so that I can then copy and paste the SVG "text".
