### ISSUE TITLE
Autohide clipboard window when mouse leaves it

### ISSUE THREAD

**Issue by jceb** [hluk/CopyQ#495]
Is there a way to autohide the clipboard window when the mouse leaves it?

**Comment by scottkosty** [comment]
I'm curious, what is the use case for this? There is an option in preferences for "After item is activated (double-click or Enter key), copy it to clipboard and ..." "Close main window". Does that get at the heart of what you want?

**Comment by scottkosty** [comment]
@jceb I just wanted to make sure you saw my reply and questions.

**Comment by jceb** [comment]
@scottkosty I'm sorry that it took so long to come back to this issue.  I consider the clipboard window something temporary that I open to select a previous entry in my clipboard.  Therefore, I'd assume that if I open CopyQ and click on something outside CopyQ or unfocus the window (I use a sloppy mouse focus that advances the focus to the next window if I move the mouse) it should close.

This behaviour I found with other clipboard managers like clipit, parcellite and klipper.

Does this clarify the use case?
