### ISSUE TITLE
"copyq toggle" wil only focus the copyq window

### ISSUE THREAD

**Issue by Johnstone-Tech** [hluk/CopyQ#497]
My use case for copyq was to have it running in the background when my computer starts, then using a shortcut run ~copyq toggle~ to show / hide the application as the docs suggest unless im reading it wrong. Unfortunately after updating i am unable to replicate this workflow, i see thers are having the same issue and have tried suggestions you gave them with no joy.

Currently if i start copyq at boot the window is shown on boot, the only way i can hide the window is to quit copyq. I am running i3 window manager so here is no tray etc, but like i said i had this wrking fine for over 6 months so i doubt its an i3 issue. 

I hope it can be resolved becasue its a great program that was becoming vital to my workflow.

**Comment by hluk** [comment]
See #474 (there will be new option in next version to hide the main window when closed).
