### ISSUE TITLE
Fea: run in multiple X sessions

### ISSUE THREAD

**Issue by amerlyq** [hluk/CopyQ#498]
Currently each next X session can't communicate with already launched copyq, because its window is bounded to very first X.
I don't really know inner structure of copyq, but maybe creating separate sockets for each X server will do to at least allow separate instances of copyq on each X?
Better solution, however, would be running one headless demon server which sync clipboards between all X sessions and open/create actual X windows only when needed for each X server separately.

**Comment by hluk** [comment]
It would be nice to have GUI and server app separated but I'm not sure if it's worth the effort. I think that would be only useful on X11 (and maybe Wayland) but not Windows and OS X.

If you want to run multiple instances of CopyQ you have to use different application sessions. You can start new session by using `copyq --session my_session_2`. Sending commands should work no matter which X session you use (e.g. `copyq --session my_session_2 read`).

BTW, here is useful command to synchronize clipboard with multiple sessions.

```ini
[Command]
Automatic=true
Command="
    copyq:
    // Select session to send data to.
    var sessions = [
      'my_session_2',
      'my_session_3',
      'my_session_4',
    ]
    
    function passInput(session_name, command) {
      execute(
        'copyq', '-s', session_name,
        command, 'application/x-copyq-item', '-',
        null, input())
    }
    
    function syncNewItem(session_name) {
      passInput(session_name, 'write')
    }
    
    function syncClipboard(session_name) {
      passInput(session_name, 'clipboard')
    }
    
    for (var i in sessions) {
      // Set clipboard in each session.
      syncClipboard(sessions[i])
    
      // Add new item in each session.
      syncNewItem(sessions[i])
    }"
Icon=\xf065
Input=application/x-copyq-item
Name=Synchronize Clipboard with Other Sessions
```

**Comment by amerlyq** [comment]
Nice solution. However what it lacks -- it's necessity to specify list of sockets.
I could spawn copyq --session session_${DISPLAY%:} and be content.
But I can't predict those sessions names then. Moreover I don't know if I spawn two or three X.
Therefore explicit list of sessions is bad.
Possible crotch is to check each session 1..9 if existent before sync, but... it's not nice.

**Comment by blueyed** [comment]
For reference: the code is hosted in this Gist: https://gist.github.com/hluk/b1f69df944335f41242b

I came back to this via https://github.com/hluk/CopyQ/issues/429.

What I would like is a non-automatic menu item / action that would copy the current item to another session, and if there are more than two sessions, there would be a selection being offered.

Currently I just copy the contents to a temporary file, and then read it from there in the other session, but this involves spawning a terminal etc.  It could be automated further using the non-CopyQ tools, e.g. xsel etc, but it would be nice to have support in this via CopyQ already.
