### ISSUE TITLE
cmd copyq help doesn't work

### ISSUE THREAD

**Issue by pre55** [hluk/CopyQ#499]
Windows 7 enterprise x64
C:\Windows\System32\cmd.exe

![](http://abload.de/img/copyq_copyq_helpztu50.png)

others work fine,
like `copyq disable`, `copyq enable` and `copyq add "afdf"`.

**Comment by hluk** [comment]
I know about this - see #349 - no idea how to fix it.

You can run `copyq help` from gitbash, from Action dialog in CopyQ <kbd>F5</kbd> ("Store standard output" to "text/plain" to save the help as item) and from powershell (`& 'C:\Program Files (x86)\CopyQ\copyq.exe' help | Write-Output`).
