### ISSUE TITLE
CopyQ cannot be installed on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by AndMunich** [hluk/CopyQ#501]
The *.deb file causes a notice about a not met dependency for one of the Lib-library files.
![selection_416](https://cloud.githubusercontent.com/assets/10129486/14938862/9b7c1d56-0f32-11e6-9181-7fd8b7a7540c.png)

**Comment by hluk** [comment]
Did you get the package for Ubuntu 16.04 from [here](https://github.com/hluk/CopyQ/releases/tag/v2.6.1)?

**Comment by AndMunich** [comment]
No, I had it from SourceForge on Feb. 14th for Ubuntu 15.10 then. Thank you!!!! The copyq_2.6.1_Ubuntu_16.04_amd64.deb from here installs fine, shows up in Dash, but not in the Unity Bar, but obviously it took the settings from the 15.10 installation. I'll keep that in mind, always to go "ad fontes"!! Thanks again, it's a wonderful tool!

**Comment by hluk** [comment]
I'm just releasing new version and uploading all packages on SourceForge - they'll up there any moment. Thanks for using the app!
