### ISSUE TITLE
Feature request: Ability to search history from the tray icon

### ISSUE THREAD

**Issue by orschiro** [hluk/CopyQ#503]
Dear all, 

What do you think of an idea by which the user could invoke a search in the history directly from the tray icon?

Thankfully,

~Robert

![image](https://cloud.githubusercontent.com/assets/170947/15006435/2597ee8e-11d1-11e6-8ac7-3f34269e86a6.png)

**Comment by scottkosty** [comment]
I don't understand how this would work. What happens when you click on your new "Search history..." button? How is it different from clicking on "Show/Hide" and just typing? If you type in the window that pops up with Show/Hide that does a history search.

**Comment by orschiro** [comment]
Hello @scottkosty,

I think this is exactly the workflow I have been looking for. I actually never had thought about using show/hide...

Thank you!

Just a quick question: What is the keyboard shortcut for `Move to clipboard`? 

`Ctrl+c` does not seem to work for me to move the selected entry to the clipboard.

~Robert

**Comment by scottkosty** [comment]
Either double-click or press enter. Does that work?

**Comment by orschiro** [comment]
Yes, both have the expected effect.

However, they both close the main window which I would prefer to keep open. 

Is this possible, too?

~Robert

**Comment by scottkosty** [comment]
Yes, uncheck "Close main window" in the history tab of preferences. I'm curious, why do you want it open after you select something?

**Comment by orschiro** [comment]
Great, thanks @scottkosty!

I don't mind the window being opened since it nicely integrates with its icon into my Unity desktop. 

Moreover, I use it so frequently that I prefer to just keep it open. :smiley: 

~Robert

**Comment by scottkosty** [comment]
I see, makes sense @orschiro . Glad we figured something out that matches your workflow. Do you think we should close this issue now?

**Comment by orschiro** [comment]
Dear @scottkosty,

Yes, I think we are done here. Thank you! :smile: 

~Robert
