### ISSUE TITLE
Delay on Windows

### ISSUE THREAD

**Issue by majkinetor** [hluk/CopyQ#504]
Every now and then.... like once per day or less, on my Windows 7,8,10 systems copyq takes half a minute to respond. How can I troubleshoot this problem ?

**Comment by scottkosty** [comment]
Assuming you are using the latest version, 2.7.0, go to Help > Show Log. If you're not using the latest version, consider updating. Does that give any clues?

**Comment by majkinetor** [comment]
I see only this:

~~~
Note [2016-05-12 17:55:09.456]: Loading plugin: C:/Program Files (x86)/CopyQ/plugins/itemweb.dll
ERROR [2016-05-12 20:12:39.822]: Remote process: Connection timeout!
~~~

**Comment by hluk** [comment]
This probably means that the clipboard monitor (part of CopyQ) doesn't respond because it's trying to fetch clipboard data -- it could be due to misbehaving application from which you copied something to clipboard the last time.

**Tip:** You can set `COPYQ_LOG_LEVEL` environment variable to `DEBUG` to see more detailed log.

**Comment by majkinetor** [comment]
Actually it started to happen quite often. The copyQ seems blocked (for instance icon in tray is frozen in squeezed position). I will set the env var now.

**Comment by majkinetor** [comment]
It now happened when I was looking at the clipboard tab. I was using j/k to go up/down and it blocked for ~15s.

This is the log at that time:

```
DEBUG [2016-05-30 18:12:10.264]: Opened session mutex: copyq_mutex
DEBUG [2016-05-30 18:12:10.265]: Message received with exit code 0.
DEBUG [2016-05-30 18:12:15.168]: Tab "&clipboard": Saving 10000 items
DEBUG [2016-05-30 18:12:22.030]: Tab "&clipboard": Items saved
```

This saving is problematic it seems, it lasts exactly 17s and it blocks copyq. Since it happens on ALL of my systems (5+), its not OS or hardware specific (ofc, on slower machines it lasts way longer). 

Could this be done in another thread ?

**Comment by majkinetor** [comment]
And yeah, I have maximum number of items in history for a reason. :)

**Comment by hluk** [comment]
Is this still an issue with latest version?

**Comment by majkinetor** [comment]
I reduced the history size from 10K to 500 and it doesn't happen any more. Should i return it to test it out ?

**Comment by hluk** [comment]
It's quite possible that saving or loading could take long time when there are large HTML or image items (it should take less data to store images in next version).

You don't have to test this but reopen if the problem returns. I'll try to further improve performance for save/load.

**Comment by majkinetor** [comment]
OK, I will. Thanks.
