### ISSUE TITLE
Cannot run commands in CopyQ

### ISSUE THREAD

**Issue by cam-l** [hluk/CopyQ#506]
As per title.
The command runs but throws a "Process failed to start: No such file or directory" error.
(Also having some issues with commands copied from your list failing to register due to 'illegal characters', not sure if this is related.)

So, is this a bug do you think or user error?

eg..
```
Command “[Command] |Name=Join S…=xf066 |Shortcut=Space”
Error: Process failed to start: No such file or directory
---
[Command]
|Name=Join Selected Items
|Command=copyq add <text edited out here>
|InMenu=true
|Icon=xf066
|Shortcut=Space
---
```
Running Win 7 x64 + CopyQ 2.7
Log Error messages:
- CopyQ ERROR [2016-05-15 16:17:50.266]: Failed to set binary stdin.

**Comment by hluk** [comment]
The commands should be copied to the command list (not the "Command" edit field). I should probably make it more obvious in the application.

**Comment by cam-l** [comment]
Much appreciated. It is actually really easy to use in the application, it was the wording of the wiki that threw me. Great app, thanks.
