### ISSUE TITLE
Keyboard shortcut to access copyq?

### ISSUE THREAD

**Issue by vmiimu** [hluk/CopyQ#508]
As a former ditto user I'm used to using ctrl + ~ to access a small popup window with all the clips.

Presently I'm accessing copyq using the tray icon which isn't as convenient.
Is there a similar shortcut available for copyq? If not, how can one be setup?

**Comment by hluk** [comment]
I've just added new entry to FAQ: [How to open application window or tray menu using shortcut?](https://github.com/hluk/CopyQ/wiki/FAQ#how-to-open-application-window-or-tray-menu-using-shortcut).

**Comment by vmiimu** [comment]
Thanks mate!
Easy to setup and works perfectly.

**Comment by tgott** [comment]
I appreciate the tip. It's working for me as well.
