### ISSUE TITLE
Clipboard has odd behavior with independent spaces on osx and external monitors.

### ISSUE THREAD

**Issue by excetara2** [hluk/CopyQ#509]
If you have two monitors with space 1 and 2 on the first and 3 and 4 on the second. They you pull up copyq on space 3 and then switch to space 4 in an application and want to pull up the menu later to paste. it will switch you back to space 3 which is not desired. This is even with the setting open on active window set.

Also I have tried using show the tray menu but only the mouse seems to work with the tray menu and not the keyboard. It always opens on the current spaces that are being shown. Is there a way to set the behavior of the tray menu opening but for the main window?

Thanks for the help!

**Comment by excetara2** [comment]
I have realized the tray menu item you can navigate with a keyboard like you should be able to but only if the main window is open otherwise you have to move the keyboard to select something to exit out of it or the tray menu item stays on the screen.

I am running on El Capitan.

**Comment by hluk** [comment]
Maybe this is fixed in #703. I couldn't test it on multiple monitors.

**Comment by hluk** [comment]
Please re-open if this is not fixed.

**Comment by excetara2** [comment]
Yes, I don't have external monitor setup for the next couple months so I
will try to replicate it then.
