### ISSUE TITLE
Error with decrypting items

### ISSUE THREAD

**Issue by PEG71** [hluk/CopyQ#513]
Hi,

every time I try to decrypt a previously encrypted item, I get the following error:

```
Commande «copyq: plugins.itemencrypted.decrypt(input())»
code de sortie: 1
CopyQ ERROR [2016-06-06 23:27:54.687]: GPG (exit code 2): gpg: encrypted with 2048-bit RSA key, ID DF80F5BE, created 2016-06-06 
      "copyq" 
gpg: WARNING: encrypted message has been manipulated! 

--- backtrace --- 

--- end backtrace --- 

---
copyq:  plugins.itemencrypted.decrypt(input())

---
```

I'im running Windows 10 with GPG4Win 2.3.1and latest version of copyq.

**Comment by hluk** [comment]
Can you check log (menu item "Help/Show Log" <kbd>F12</kbd>) for any other errors/warnings after CopyQ starts?

**Comment by PEG71** [comment]
No. Just some "Loading plugin" entries.  :/

Is there a recommended version of GPG to install (classic, modern or stable)?

Thanks for your help.

**Comment by hluk** [comment]
I just tried it on Windows 8 with Gpg4Win 2.3.1 and surely it fails sometimes.

I fixed it by setting binary mode for standard output on Windows ([this commit](https://github.com/hluk/CopyQ/commit/46f874fc514e564db3cb3baacfb2e9ddf6bb84f7)). I have no idea why it worked before.

I'm sorry about this, you may have lost your encrypted data.

I'll try to release new version ASAP.

**Comment by PEG71** [comment]
No worries hluk. I am so happy to have found a multi-platform clipboard manager packed with features.

Thanks for this fix and for providing such a great software.
