### ISSUE TITLE
Language Change dialog on every Apply and Ok action

### ISSUE THREAD

**Issue by sudhirkhanger** [hluk/CopyQ#518]
Hi,

Every time I hit Apply or Ok in CopyQ settings I am greeted with following dialog eventhough I am not changing language at all. I am using `copyq-2.7.0-1.fc23.x86_64` on Fedora 23 KDE.
![screenshot_20160618_114116](https://cloud.githubusercontent.com/assets/841656/16169405/b7e59e44-3549-11e6-97e5-b9cfde299f50.png)

**Comment by hluk** [comment]
I'm not entirely sure how this can happen but hopefully the commit fixes it.
