### ISSUE TITLE
Command “copyq: if (monitoring()) {updateFirst()}”

### ISSUE THREAD

**Issue by sudhirkhanger** [hluk/CopyQ#520]
I keep getting the error below.

```
Command “copyq: if (monitoring()) {updateFirst()}”
Error: Process crashed

---
copyq:  if (monitoring()) {updateFirst()}
---
```

Trace generated by ABRT in Fedora can be found [here](https://bugzilla.redhat.com/show_bug.cgi?id=1336133).

**Comment by hluk** [comment]
Should be fixed ([commit](https://github.com/hluk/CopyQ/commit/de2847d3f25ff67e0ee99ad14679030e045d9285)).

**Comment by sudhirkhanger** [comment]
Hi @hluk,

This issue came up again. Please see this bug report. https://bugzilla.redhat.com/show_bug.cgi?id=1359528

**Comment by hluk** [comment]
OK, thanks for the bug report. Refer to #424 -- seems to be same issue.
