### ISSUE TITLE
Hide menu bar and make main window transparent.

### ISSUE THREAD

**Issue by amosbird** [hluk/CopyQ#521]
I found the old issue #135 talking about hiding the menu bar. I've tried the css setting, but it doesn't work. And the transparent settings in Layout tab also don't take effect.

Archlinux
i3wm
CopyQ Clipboard Manager v2.7.1-1-g654ca9d (hluk@email.cz)
Built with: Qt 4.8.7, LibQxt 0.7.0

**Comment by hluk** [comment]
For the menu to be hidden you also need to enable "Set colors for tabs, tool bar and menus" option after changing the style sheet (I've updated [FAQ section](https://github.com/hluk/CopyQ/wiki/FAQ#is-it-possible-to-hide-menu-bar-to-have-even-cleaner-main-window)).

I think you need composite manager window like "xcompmgr" or "compton" to have transparency effects on windows (it should be possible to run it with i3wm).

**Comment by amosbird** [comment]
Menu hiding now works fine. Thanks. However, I've used compton for a long time and other applications' transparency work just fine.

**Comment by hluk** [comment]
I'll take closer look at the issue later -- perhaps it's some issue with Qt 4 and compton.

BTW, did you try Qt 5 version of the app? It's also on [AUR](https://aur.archlinux.org/packages/copyq/), however not yet in most recent version.

**Comment by amosbird** [comment]
@hluk I built the newest version with Qt 5. The transparent setting still doesn't work.

**Comment by hluk** [comment]
@amosbird OK, I'll test it later (it seems to work at least on Windows).

**Comment by hluk** [comment]
Transparency works fine for me on Archlinux with i3 and compton with Qt 5.7.0.

There was [this bug in Qt 5](https://bugreports.qt.io/browse/QTBUG-28477) but it should be already resolved in Qt 5.2.0.

Perhaps there is another application that messes up transparency. Does `compton-trans -o 30` and selecting a window change transparency of a window?

**Comment by amosbird** [comment]
Using `compton-trans -o 30` can make copyq transparent.
