### ISSUE TITLE
Ctrl+Enter shouldn't paste selected items

### ISSUE THREAD

**Issue by hluk** [hluk/CopyQ#523]
When using command:

```ini
[Command]
Name=Select First Tab when Item is Selected
Command="
    copyq:
    select(currentItem())
    
    if (config('activate_closes') == 'true')
      hide()
    
    if (config('activate_pastes') == 'true')
      paste()
    
    // Re-select the first tab.
    tabs = tab()
    setCurrentTab(tabs[0])"
InMenu=true
Icon=\xf022
Shortcut=enter
```

pressing <kbd>Ctrl</kbd>+<kbd>Enter</kbd> and quickly releasing <kbd>Ctrl</kbd> the content is pasted though the shortcut should omit pasting.

**Comment by scottkosty** [comment]
This fixes ctrl+enter for me. Thank you.

For shift+enter, though, in gnome-terminal, it executes a paste of the *previous* item that was copied. In gedit, a paste of the *current* item is executed. Should the behavior be consistent?

**Comment by hluk** [comment]
Works fine for me with gnome-terminal (v3.20.2) and other apps. Can you check if the clipboard and selection really contains the right text to paste (`copyq clipboard && copyq selection`)?

Did it work correctly before this issue was fixed?

The problem could also be that there is bigger delay for the clipboard/selection change to propagate to some apps.

**Comment by scottkosty** [comment]
OK I'll look more into it once I get a chance. What is the expected behavior of shift+enter? Is it the same as enter?

**Comment by hluk** [comment]
I think shift+enter is handled same way as enter (in Qt) -- it should work the same way if not overridden with a custom command (I usually map shift+enter to "paste as plain text").

**Comment by scottkosty** [comment]
The problem seems to be that I had shift+enter mapped to plain text and I had a separate entry for shift+enter that I had copied from here:
https://groups.google.com/forum/#!searchin/copyq/nautilus/copyq/mjcZbevpPaA/UyfHEhU1GQAJ
By removing that entry the shift+enter now works as expected.
