### ISSUE TITLE
Paste pre-defined string.

### ISSUE THREAD

**Issue by amosbird** [hluk/CopyQ#525]
Does copyq support pasting pre-defined strings? I'd like to make a key binding that pastes my email address.

**Comment by hluk** [comment]
It's possible to copy and paste anything from a command. For example you can paste current date and time with following command.

```ini
[Command]
Command="
    copyq:
    var time = dateString('yyyy-MM-dd hh:mm:ss')
    copy('Current date/time is ' + time)
    paste()"
GlobalShortcut=meta+alt+t
Icon=\xf017
Name=Paste Current Time
```

**Comment by amosbird** [comment]
Hmm. This command doesn't work for me. Only the content of current clipboard is pasted. And the golbal shortcut feels a bit uncomfortable. I have to release all the modifiers to get the clipboard pasted.

Archlinux
i3wm
CopyQ Clipboard Manager v2.7.1-7-g1c9b3ec (hluk@email.cz)
Built with: Qt 5.6.1, LibQxt 0.7.0

**Comment by hluk** [comment]
Perhaps the app you're pasting into uses X11 selection instead of clipboard. Does the following help?

```ini
[Command]
Command="
    copyq:
    var time = dateString('yyyy-MM-dd hh:mm:ss')
    var text = 'Current date/time is ' + time
    copy(text)
    copySelection(text)
    paste()"
GlobalShortcut=meta+alt+t
Icon=\xf017
Name=Paste Current Time
```

The app needs to wait for user to release modifiers so it can send shortcut for pasting to current window -- I had some issues on Linux otherwise. BTW it was fixed with [this commit](https://github.com/hluk/CopyQ/commit/4949cfad406e397e089755b96a15e9f5bf583dd1).

Alternatively You can also use [xdotool](https://www.archlinux.org/packages/community/x86_64/xdotool/) for pasting but it doesn't work with all apps when holding some keyboard modifiers.

```ini
[Command]
Command="
    copyq:
    var time = dateString('yyyy-MM-dd hh:mm:ss')
    var text = 'Current date/time is ' + time
    copy(text)
    copySelection(text)
    var result = execute('xdotool', 'key', 'shift+Insert')
    if (result.stderr)
      popup('Pasting failed', result.stderr)"
GlobalShortcut=meta+alt+t
Icon=\xf017
Name=Paste Current Time
```

**Comment by amosbird** [comment]
Thanks. It works fine now. There are still two minor issues. One is the pasting process feels a little bit slow compared to directly pasting with `shift+insert`, and the other is the pollution of the primary selection.

**Comment by hluk** [comment]
What do you mean by "the pollution of the primary selection"?

**Comment by amosbird** [comment]
It shallows the original selection.

**Comment by hluk** [comment]
You can store the previous selection content in a variable and reset the selection after pasting.

```js
var selectionText = selection()
copySelection(...)
paste()
copySelection(selectionText)
```

**Comment by amosbird** [comment]
That's great. I think I should close the issue now. You are very helpful. Thanks!
