### ISSUE TITLE
Pasting into urxvt produces garbage strings.

### ISSUE THREAD

**Issue by amosbird** [hluk/CopyQ#527]
`urxvt -e /path/to/zsh` becomes `{200~urxvt -e /path/to/zsh{201~` when pasted into urxvt.

Archlinux
i3wm
rxvt-unicode (urxvt) v9.22 - released: 2016-01-23
CopyQ Clipboard Manager v2.7.1-1-g654ca9d (hluk@email.cz)
Built with: Qt 5.6.1, LibQxt 0.7.0

**Comment by scottkosty** [comment]
What happens when you exit copyq, copy the string you're trying, and then in urxvt you press shift+insert ?

**Comment by amosbird** [comment]
Hmm, it still produces garbage strings.

**Comment by scottkosty** [comment]
Although I'm not an expert in any of this, I think that's a sign that the root issue is with urxvt. This is not necessarily a bug. Perhaps that behavior is documented somewhere. So the best approach is just to ask the urxvt project if that is the intended behavior of Shift+Insert.

**Comment by amosbird** [comment]
It turns out to be `bracketed paste mode`.

**Comment by scottkosty** [comment]
Good to know. Note that I think you can ask CopyQ to use ctrl+shift+v to paste instead of Shift+Insert to possibly work around the issue. But it sounds like you found a more direct way to solve the problem.
