### ISSUE TITLE
Synchronize clipboard and selection (in X11) for specific windows only

### ISSUE THREAD

**Issue by sergei-dyshel** [hluk/CopyQ#528]
I want this sync to want only for Gnome terminal so that selection with mouse will automatically set clipboard. What auto-command should I write for that?

**Comment by sergei-dyshel** [comment]
Found an answer by myself!
Just use the following auto-command (just change window title from `TERM` to smth more suitable for you):
```
[Command]
Automatic=true
Command=copyq:\ncopy(selection())
Icon=\xf016
Name=Copy selection to clipboard when in Terminal
Window=TERM
```

**Comment by scottkosty** [comment]
Great, thanks for posting the solution that worked for you! By the way, there is a copyq mailing list that can be used to ask questions in the future. It is low traffic but hopefully more users will join.
