### ISSUE TITLE
CopyQ v2.7.1 doesn't launch on OS X 10.11.5: LSOpenURLsWithRole() failed with error

### ISSUE THREAD

**Issue by ujay68** [hluk/CopyQ#529]
When I try to start CopyQ v2.7.1 (build from https://github.com/hluk/CopyQ/releases) on OS X 10.11.5 nothing seems to happen. Starting CopyQ from a terminal says:

```
$ open /Applications/CopyQ.app
LSOpenURLsWithRole() failed with error -10810 for the file /Applications/CopyQ.app.
```

On the same machine, CopyQ v2.7.0 works.

**Comment by scottkosty** [comment]
Are you able to compile CopyQ yourself? On Linux you just need to do

```
cmake .
make
```

I don't know on a mac. If you can compile yourself, then it is easy to do a bisect between 2.7.0 and 2.7.1 and thus figure out the exact commit that caused the problem.

**Comment by alexwforsythe** [comment]
Also on OS X 10.11.5:
```shell
$ /Applications/CopyQ.app/Contents/MacOS/copyq
dyld: Library not loaded: /usr/local/Cellar/qt5/5.6.1/lib/QtWidgets.framework/Versions/5/QtWidgets
  Referenced from: /Applications/CopyQ.app/Contents/Frameworks/QtSvg.framework/Versions/5/QtSvg
  Reason: image not found
```

Seems similar to #386?

**Comment by alexwforsythe** [comment]
v2.7.0 seems to work for me.

**Comment by rafo** [comment]
I have the same problem.

**Comment by jialongl** [comment]
@alexwforsythe   Yes, it is similar to #386 --- a bad build.
After I fixed all the paths of dylibs, I get this error still:

```
$ /Applications/CopyQ.app/Contents/MacOS/copyq
This application failed to start because it could not find or load the Qt platform plugin "cocoa"
in "".

Available platform plugins are: cocoa.

Reinstalling the application may fix this problem.
zsh: abort      /Applications/CopyQ.app/Contents/MacOS/copyq
```

so,,, just have to go back to version 2.7.0 for now.

**Comment by scottkosty** [comment]
Does something need to be reported to homebrew then like for #386?

**Comment by rygwdn** [comment]
Looks like this is caused by https://github.com/Homebrew/homebrew-core/issues/3219

**Comment by hluk** [comment]
Here is [new package for 2.8.1](https://github.com/hluk/CopyQ/releases/download/v2.8.1/CopyQ.dmg). If it doesn't work please refer to #590.

**Comment by ujay68** [comment]
v2.8.1 works for me. Thanks!
