### ISSUE TITLE
Why can't change language on fedora24 use qt5

### ISSUE THREAD

**Issue by ousui** [hluk/CopyQ#530]
the RPM package
https://mirrors.ustc.edu.cn/fedora/linux/updates/24/x86_64/c/copyq-2.7.1-1.fc24.x86_64.rpm
and the source
https://mirrors.ustc.edu.cn/fedora/linux/updates/24/SRPMS/c/copyq-2.7.1-1.fc24.src.rpm

![image](https://cloud.githubusercontent.com/assets/2839512/16895204/2881dca8-4b34-11e6-9594-84371a031553.png)

/usr/share/copyq
![image](https://cloud.githubusercontent.com/assets/2839512/16895206/3c101186-4b34-11e6-938d-db760176e478.png)

**Comment by gbcox** [comment]
I'm sorry, I don't understand what you are talking about or asking.

copyq in fedora uses qt5 - qt4 isn't referenced:
BuildRequires:  kf5-rpm-macros, qt5-qtbase-devel, qt5-qtwebkit-devel, qt5-qtsvg-devel
BuildRequires:  qt5-qttools-devel, qt5-qtscript-devel, qwt-qt5-devel
%build
%{cmake_kf5}    -DCMAKE_SKIP_RPATH=TRUE \
                                -DWITH_QT5=ON \
                                -DWITH_TESTS=TRUE \
                                -DCMAKE_INSTALL_PREFIX=%{_prefix} \
                                -DPLUGIN_INSTALL_PREFIX=%{_libdir}/%{name}/plugins \
                                -DTRANSLATION_INSTALL_PREFIX:PATH=share/%{name}/locale
make %{?_smp_mflags}

**Comment by ousui** [comment]
The spec file has some wrong on paramters *-DTRANSLATION_INSTALL_PREFIX:PATH=share/%{name}/locale*
You must at path `/usr` execute copyq, then you can choese  language.
in other else path you can't chose language.

the paramter may be is `-DTRANSLATION_INSTALL_PREFIX:PATH=%{_prefix}/share/%{name}/locale`

**Comment by gbcox** [comment]
Got it... I'll get it fixed in Fedora.  Will update this report when done.  Should be in a few days.  Thanks for taking the time to report.  I appreciate it.

**Comment by gbcox** [comment]
Fedora bug report:  https://bugzilla.redhat.com/show_bug.cgi?id=1357235

**Comment by ousui** [comment]
Got it. Thank you! Copyq is great!

**Comment by gbcox** [comment]
Please when bodhi allows, leave positive karma.  That will allow the fix to get pushed to production immediately rather than waiting 7 days.
