### ISSUE TITLE
Can copyq export the format "image/png" to a file?

### ISSUE THREAD

**Issue by ousui** [hluk/CopyQ#533]
I want to export image/png(or image/svg, image/gif) to a file.

**Comment by hluk** [comment]
I think [Save Item/Clipboard To a File](https://gist.github.com/hluk/64dae8b25cd21e6141dd) command may come in handy (some others are at [Command Example](https://github.com/hluk/CopyQ/wiki/Command-Examples)).

**Comment by ousui** [comment]
it's very useful, thank you!
