### ISSUE TITLE
make CopyQ delete clipboard entry if externally deleted

### ISSUE THREAD

**Issue by Konfekt** [hluk/CopyQ#534]
Some password managers copy the password to the clipboard and then remove it (a minute) from the clipboard later. At the moment, the entry will then appear doubled in the clipboard history (as is the case with passwordstore) instead of being removed.

**Comment by scottkosty** [comment]
I have no idea how things work, but I'm guessing that the password manager overwrites the clipboard with a blank entry. Thus, CopyQ will only see a string that was copied, then a copy of an empty string. So CopyQ would have to make the assumption that if it receives an empty string, the intention is to remove the previous item from history. Is this what happens? Have you looked at CopyQ's scripting capabilities? You can have an action that might be able to say "if empty, then delete the previous item in history".

**Comment by Konfekt** [comment]
To correct, the clipboard is restored: the clipboard is overwritten with the previous entry.

**Comment by scottkosty** [comment]
I see. So you would want a script that checks whether the current item is equal to the previous previous item. If so, then delete the previous item.

Do you have the option of having the password manager store the password on the PRIMARY selection rather than CLIPBOARD? This way you could just middle-click wherever you need it and you can configure CopyQ to ignore the SELECTION so CopyQ would never even store your password.

**Comment by Konfekt** [comment]
Yep, that's exactly the way I set it up now.

**Comment by hluk** [comment]
Closing.

It's not a good idea to rely on the clipboard to be cleared by password manager. Some other app could change the clipboard before password manager could clear it - in such case, CopyQ would still have the item. Also, if CopyQ is closed before the clipboard is cleared, the password item would be retained.

AFAIK, there is no reliable way to ignore passwords by CopyQ.

**Comment by Konfekt** [comment]
On Windows, [wclip](https://github.com/palortoff/wclip) pastes into the clipboard while circumventing adding an entry to the clipboard history.
