### ISSUE TITLE
Mime type text/html not copied when doing synchronization

### ISSUE THREAD

**Issue by Infinality** [hluk/CopyQ#535]
I am synchronizing between a Linux and Windows system using a common directory.  When I copy something from a browser on Windows, two types are shown on the windows side (text/plain and text/html).  But when I look on the Linux side, only "text/plain" gets brought over to the Linux system.  For what it's worth, images seem to copy fine both ways.

**Comment by hluk** [comment]
Is there `copyq_<row-index>.html` file (next to `copyq_<row-index>.txt`) in your synchronization directory?

**Comment by Infinality** [comment]
Actually, there are no files in the synchronization directory, and I don't recall ever seeing any in there.  I assumed (possibly incorrectly) that the files get removed once the other copyQ picks it up.  Have I set it up incorrectly?

**Comment by Infinality** [comment]
Ah, looks like I had the clipboard name wrong in the sync settings.  It needed to be "&clipboard" not "clipboard".  Might be worth calling that out on that dialog area.  

Thanks for a great clipboard manager!
