### ISSUE TITLE
"Paste to current window" doesn't seem to work

### ISSUE THREAD

**Issue by melarish** [hluk/CopyQ#537]
I have Paste to current window enabled, as well as global shortcut for show/hide. So I'm trying to do: 1) show copyq window 2) move to item 3) press Enter to paste the item. but all it does is move the item to the top and I have to hit ESC to hide copyq and then press ctrl+v to paste. Am I missing some settings or is this broken? Also I have "close main window" enabled but that doesn't close either.

Ubuntu 16.04. Happens in Firefox, Text Editor, everywhere.

**Comment by TarasRoshko** [comment]
1) Set up global hotkey for "Show / hide main window" e.g `Meta + ``

2) Preferences - History - After item is activated, copy it to clipboard and

- [x] Move item to the top
- [x] Close main window
- [x] Focus last window
- [x] Paste to current window

Then doing `Meta + `` and pressing enter on item you want to paste pastes it to last active window and closes copyq

Latrest Win10, couple apps tested (vscode, chrome, etc), all seem to work

I'll check on Ubuntu and let you know

**Comment by melarish** [comment]
I think I had all those settings enabled but it didn't work. Anyway I already uninstalled it and found Diodon works for me, so can't check it anymore. Might help new users if there was a single setting for this though, as it's a default behaviour in most clipboard recorders.

**Comment by hluk** [comment]
You need to enable "Paste to current window" option (under "History" config tab) for pasting to work from main window and "Paste activated item to current window" (under "Tray" config tab) to paste from tray menu.

There still may be window managers or systems where it won't work (usually it won't work if you click on CopyQ icon in tray to show main window or menu before pasting). CopyQ just tries its best to focus last window and send paste shortcut.

If it still doesn't work you can try adding "Paste as Plain Text" command in Command dialog <kbd>F6</kbd> and reassign its shortcut to <kbd>Return</kbd>.

**Comment by arthurcgusmao** [comment]
Depending on your system, `copyq` might be lacking the appropriate permissions. Launching it with `sudo` might be a quick fix.

**Comment by hluk** [comment]
> Depending on your system, `copyq` might be lacking the appropriate permissions. You could try launching it with `sudo`.

This is not a good idea. This app is not meant to be run under root. I would expect that this could actually cause more trouble.

**Comment by tommdq** [comment]
I'm having this same issue using wayland.. I have tried all the solutions mentioned , but I still cannot get the "Paste to current window" feature to work. Any suggestions?
