### ISSUE TITLE
clipboard not saved to the first tab

### ISSUE THREAD

**Issue by mkoura** [hluk/CopyQ#538]
*If any tab is moved in tab bar to the front (in tab tree to the top) it will be used for storing clipboard instead of the former first tab.*

This doesn't work for me. Moving tab to the front doesn't have any effect and CopyQ still saves clipboard to the original tab. I need to change it in preferences ("History" -> "Tab for storing clipboard") to have desired effect.  Version 2.7.1 from Fedora 24.

**Comment by hluk** [comment]
OK, thanks - I've fixed the wiki page.
