### ISSUE TITLE
`copyq menu` not focused, and doesn't auto close when clicked outside

### ISSUE THREAD

**Issue by ghost** [hluk/CopyQ#539]
Hi,

I'm using CopyQ 2.7.1 on Fedora 24, Xfce4 desktop. I found some issues with command line `copyq menu`:
- The menu appears, but not focused. I can't use arrow keys to select items.
- Clicking outside the menu won't close it.
- Once the menu appears, I can press Esc to close it. But if I click outside, then move the mouse inside the menu, pressing Esc again does nothing.

Thank you,

**Comment by hluk** [comment]
I cannot reproduce this on Openbox and xfwm4 window managers (on Xfce4, Arch Linux).

What window manager do you use? Which shortcut and app executes `copyq menu` command?

**Comment by hetraeus** [comment]
I had the same issue. Apparently it was a sxhkd misbehavior for me. "copyq menu" works using openbox shortcuts instead of sxhkd.

**Comment by ousui** [comment]
There no problem on KDE4, Arch Linux, but on **macos**, I had the same issue.

**Comment by hluk** [comment]
I fixed this at least for `sxhkd` app. Hopefully the fix works on OS X too.

Fedora 24: [copyq-2.8.2.beta.1-4.1.i686.rpm](http://download.opensuse.org/repositories/home:/lukho:/copyq/Fedora_24/i686/copyq-2.8.2.beta.1-4.1.i686.rpm)
Arch Linux: [copyq-2.8.2.beta.1-1-i686.pkg.tar.xz](http://download.opensuse.org/repositories/home:/lukho:/copyq/Arch_Extra/i686/copyq-2.8.2.beta.1-1-i686.pkg.tar.xz)
OS X: [CopyQ.dmg](https://github.com/hluk/CopyQ/releases/download/v2.8.2-beta-1/CopyQ.dmg)

**Comment by hetraeus** [comment]
This happens again using v3.0.0, sxhkd keybinds.

**Comment by hluk** [comment]
OK, should be fixed again.
