### ISSUE TITLE
QtWebKit is deprecated

### ISSUE THREAD

**Issue by whitelynx** [hluk/CopyQ#540]
Since `QtWebKit` is [deprecated as of Qt 5.5](http://doc.qt.io/qt-5/whatsnew55.html) and [has been removed from Qt 5.6](http://doc.qt.io/qt-5/whatsnew56.html), the `itemweb` plugin should be [ported to `QtWebEngine`](http://doc.qt.io/qt-5/qtwebenginewidgets-qtwebkitportingguide.html) instead.

**Comment by hluk** [comment]
The webkit support has been remove (web plugin is no longer available).
