### ISSUE TITLE
Icons are broken

### ISSUE THREAD

**Issue by HyperCriSiS** [hluk/CopyQ#544]
Hi,

there are only few Icons shown with version "copyq-windows-2.7.1.zip".
![icons](https://cloud.githubusercontent.com/assets/11708192/17800366/f928450e-65e2-11e6-8cc3-9d29b5811716.png)
Running on Windows 10 x64 Enterprise.

Regards,
Hyper

**Comment by hluk** [comment]
Seems like built-in icon font is not loaded (the few icon you can see are custom icons in SVG format).

Works for me on Windows 8.1; I cannot currently test it on Windows 10 -- I'll try it later.

**Comment by hluk** [comment]
Reopen if this is still an issue. The new versions use new Qt libraries.
