### ISSUE TITLE
Favorites?

### ISSUE THREAD

**Issue by squirrelboot** [hluk/CopyQ#545]
Is there any way we can lock/favorite a paste?

**Comment by scottkosty** [comment]
I don't think there is a way, currently. What i usually do in this case is have a tab called something like "favorites" or "permanent". Note that this issue also came up here:
https://groups.google.com/forum/#!topic/copyq/fafMpP0gNO4

**Comment by MortenZdk** [comment]
A way to save often used items, is to make an additional and copy/move items to this, and then define global shortcuts to paste rows from this tab, for example defining Ctrl+Shift+0 to paste row 0.

The user command for paste from tab 'Quick' is "copyq: tab('Quick'); select(0); paste();".

See the global shortcut window below:

![clipboard01](https://cloud.githubusercontent.com/assets/6162961/18947615/1fa1eea8-8634-11e6-94d4-ec0e33eb3ae1.jpg)

See https://github.com/hluk/CopyQ/issues/549 for a related question.

**Comment by hluk** [comment]
@MortenZdk It's possible to have single command and define multiple shortcuts; the shortcut that invokes the command can then be accessed (see [documentation for application/x-copyq-shortcut](https://github.com/hluk/CopyQ/blob/master/src/scriptable/README.md#applicationx-copyq-shortcut)).

```js
copyq:
tab('Quick')
var shortcut = str(data("application/x-copyq-shortcut"))
// Get last key in shortcut (0..9).
var n = shortcut.split('+')[2]
select(n)
paste()
```

**Comment by MortenZdk** [comment]
@hluk Thanks for you support, and I see that the command could be generic, but I guess I still have to define one entry per global shortcut that I want to define.

**Comment by hluk** [comment]
@MortenZdk The command would work if you assign it multiple shortcuts containing digit key (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>0</kbd>, <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>1</kbd> etc.).

You can also use branching if the shortcuts doesn't contain digit key, e.g.:

```js
var shortcut = str(data('application/x-copyq-shortcut'))
if (shortcut == 'ctrl+shift+a')
  select(0)
else if (shortcut == 'ctrl+shift+b')
  select(1)
else if (shortcut == 'ctrl+shift+c')
  select(2)
//...
```
