### ISSUE TITLE
Animated GIF

### ISSUE THREAD

**Issue by ligockym** [hluk/CopyQ#546]
Hello! 

When I write this simple command `copyq write image/gif - < output.gif && copyq select 0` and I try to paste the image into Slack the gif is not animated. When I upload the output.gif to Slack from file manager everything works. 

Is there any way how to copy animated GIF into clipboard? Or am I doing something wrong?

**Comment by hluk** [comment]
It should be fixed -- I removed automatic conversions to other formats for animated images.

Unfortunately I haven't been able to paste animated GIF using Chromium web browser (Firefox works fine).
