### ISSUE TITLE
No response

### ISSUE THREAD

**Issue by ZIEXED** [hluk/CopyQ#548]
The app was working fine then suddenly stopped working with no response at all

After starting the app I try to open it's window from the tray but no response
also the tray menu doesn't popup when I right click the app icon

this is the only error I see in the logs 
"Failed to set binary stdin." repeated 4 times

I tried to restart and tried to move the configs
Then I tried a fresh extracted version
and I tried the previous portable versions 2.7.0 and 2.6.0 but the problem still exist
I'm using the latest portable version
Win7 64

**Comment by hluk** [comment]
Can you post the log?

You can try to run `copyq show` in terminal. Also check if the application have permission to write to "config" subfolder.

**Comment by ZIEXED** [comment]
unfortunately I don't have any logs
and this error in the logs "Failed to set binary stdin" was the only error
every time I terminate and start CQ I got this error repeated 4 times at every star
I'm very sure the app did had write permissions to all it's folders
I don't have this problem anymore (reinstalled Windows), and I can't reproduce it
u can close this issue, I think its a very rare situation as I'm using CQ from a very long time and that was the first time to face such a problem.

**Comment by ZIEXED** [comment]
The problem occurred again and I was able to know the reason this time
Turn off Switchback compatibility engine from the group policy cause this problem (u must restart)
Administrative templates > Windows Components > Application compatibility

**Comment by hluk** [comment]
I don't see any difference after disabling the option and restarting Windows. I'm using Windows 8.1 and tried this with both installed and portable versions of CopyQ.

Try to open powershell in the CopyQ folder, run following command and post output here.

```powershell
./copyq show 2>&1 | Out-String
```
You can also try portable version from [here](https://ci.appveyor.com/project/hluk/copyq/build/artifacts) (this is even built with some newer versions of libraries, maybe that will help).

**Comment by Urvdmih** [comment]
Win 7 x64 sp1 Pro (russian lang). Not storing buffer in "buffer" tab. In log only this errors:
CopyQ ERROR [2017-01-18 11:44:45.736]: Failed to set binary stdin.
CopyQ ERROR [2017-01-18 11:44:45.739]: Failed to set binary stdin.
I tried both version CopyQ 2.8.2 (installer and portable).

**Comment by hluk** [comment]
@Urvdmih What do you mean by buffer? Is it connected to this issue? If not please create new issue.

**Comment by ZIEXED** [comment]
Sorry I turrned off the compatibility engine and tried again but couldn't reproduce the problem
