### ISSUE TITLE
How to make script command that pastes specific row in user defined tab?

### ISSUE THREAD

**Issue by MortenZdk** [hluk/CopyQ#549]
The "File" => "Commands/Global Shortcuts" (F6) allows use of scripting based on functions defined in [CopyQ Scripting](https://github.com/hluk/CopyQ/blob/master/src/scriptable/README.md).

How to write a command that pastes row 2 from a user tab called "Quick" ?

I tried this command, but it pastes row 2 from default clipboard tab, and not the "Quick" tab:

    copyq: setCurrentTab('Quick'); select(2); paste();

**Comment by hluk** [comment]
The function call to set current tab for script is `tab('Quick')`. The documentation is confusing I'll rephrase that.

**Comment by MortenZdk** [comment]
Hi Lukas, It works great ;-)  Thanks for a super program +1: Best regards Morten
