### ISSUE TITLE
Windows encryption component failure

### ISSUE THREAD

**Issue by vatterspun** [hluk/CopyQ#550]
**Setup**: Win7x86; CopyQ 2.7.1

**Steps**:
1. Download and extract **copyq-windows-2.7.1.zip**
2. Launch _copyq.exe_
3. Right-click on taskbar item and select _Preferences_
4. Select the _Items_ tab and select _Encryption_
5. Click _Generate New Keys_

**Defect**: Error: Process failed to start: No such file or directory
https://i.imgur.com/DIn5QJ0.png

Other notes:

There's a note about encrypting and decrypting under the commands tab but there isn't a commands tab here.  Do I need to download GPG or something?

**Comment by hluk** [comment]
Yes you need GPG app to be installed. Usually if the app is not available **following message** appears and the button to generate keys is disabled.

> To use item encryption, install [GnuPG](http://www.gnupg.org/) application and restart CopyQ.

I think I know where is the problem. I'll try to fix that.

**Comment by vatterspun** [comment]
Thanks for responding.  The only issue is that the GPG installation wouldn't work on every machine I could use this on.  So if installs are disabled or their site is blocked for whatever reason, I couldn't get this.  Even if that's not a restriction, I'd have to configure GPG each time, which is tedious.

Essentially I'm looking for something entirely self-contained so I could run it from a cloud or USB drive as suggested in #11 #92 .

Anyway, let me know if you need me to write that up as a separate feature request.  I wouldn't object to this case being closed since it's working as designed.

**Comment by hluk** [comment]
I would rather implement this so that no external application is required but I haven't found a good way to include this in the application yet.

Would be great to use just Qt ([QSslSocket](http://doc.qt.io/qt-5/qsslsocket.html) and other QSsl* classes) to encrypt/decrypt items -- I tried to do this some time ago but couldn't make it work -- seems that Qt doesn't support data encryption directly.

**Comment by vatterspun** [comment]
Thanks for the consideration.  The closest thing I've found to a clipboard encryption application is the poorly-named Eclipse (http://sector-seven.net/software/eclipse) front-end for MySecret.  It's adequate but outdated and a GPG solution would have a lot more application.

**Comment by vatterspun** [comment]
@hluk What was the resolution on this?

**Comment by hluk** [comment]
Ah, I closed this by mistake - I thought this was resolved bug with GPG.

I still haven't find anything that I could bundle the app. I need some simple library for encryption and some way to handle passwords.

I created a feature-request for this (#641).

**Note:** Currently the app has basically single dependency, which is Qt.

**Comment by vatterspun** [comment]
Understandable.  There's a great, self-contained open source GPG program available that might serve as a model: http://gpg4usb.org

I was mostly looking to CopyQ because GPG4USB doesn't really interact with the clipboard beyond what you manually enter.  I think they were trying to preserve an easy, cross-platform approach but CopyQ was already underway with both of those tasks.

**Comment by hluk** [comment]
Thanks for the suggestion. gpg4usb seems to be using GPGME library which might be ideal but I would need to build the library for Windows. I'll check this out later.

**Comment by vatterspun** [comment]
> I'll check this out later.

Cool, thanks.  I'm not sure how many of your users are really concerned about GPG functionality so I get that your efforts might be better put elsewhere.  Still, it's nice to have.

**Comment by CuriousOctopus** [comment]
Hello! Are there any news on GPG4USB and windows?

**Comment by hluk** [comment]
> Hello! Are there any news on GPG4USB and windows?

No news. The encryption works well for me so I don't have too many reasons to spent time on this.

Using GPGME library would be nice but I couldn't find official binaries for Windows.

**Comment by CuriousOctopus** [comment]
I wasn't able to make encryption work on portable version but installation fixed that.
