### ISSUE TITLE
Does not start after install

### ISSUE THREAD

**Issue by tinca** [hluk/CopyQ#552]
After running the installer on El Capitan app cannot start clicking on its icon.

An attempt to run it from command line gives:

dyld: Library not loaded: /usr/local/Cellar/qt5/5.6.1/lib/QtWidgets.framework/Versions/5/QtWidgets
  Referenced from: /Applications/CopyQ.app/Contents/Frameworks/QtSvg.framework/Versions/5/QtSvg
  Reason: image not found
Trace/BPT trap: 5

**Comment by aga5tya** [comment]
I get this, doesn't open on OSX-Sierra
`LSOpenURLsWithRole()` failed with error -10810 for the file /Applications/CopyQ.app.

**Comment by varra4u** [comment]
I too have the same problem with El Capitan!!

**Comment by aga5tya** [comment]
@varra4u you can use 2.7.0 version. Works for me well.

**Comment by varra4u** [comment]
@aga5tya, thanks for informing, I'll give a try tomorrow.

**Comment by varra4u** [comment]
@aga5tya It worked!! Thanks, it's running fine, but whats the shortcut to open the clip manager to select the copy for pasting!?

**Comment by hluk** [comment]
@varra4u [FAQ: How to open application window or tray menu using shortcut?](https://github.com/hluk/CopyQ/wiki/FAQ#how-to-open-application-window-or-tray-menu-using-shortcut).

**Comment by varra4u** [comment]
@hluk Thanks for pointing to the right doc. Works like a charm!

**Comment by philipbel** [comment]
macOS 10.12 Sierra

```
/Applications/CopyQ.app/Contents/MacOS/copyq
dyld: Library not loaded: /usr/local/Cellar/qt5/5.6.1/lib/QtWidgets.framework/Versions/5/QtWidgets
  Referenced from: /Applications/CopyQ.app/Contents/Frameworks/QtSvg.framework/Versions/5/QtSvg
  Reason: image not found
[1]    78749 abort      /Applications/CopyQ.app/Contents/MacOS/copyq
```

It looks strange to me that the app is referring to my `/usr/local` directory.  Could this bug be caused by a conflict between the bundled Qt and the one installed by Homebrew?

**Comment by tinca** [comment]
Not even homebrew is installed on this box, as far as I can tell.:
MBP:~ zkuti$ homebrew
-bash: homebrew: command not found

Neiter 'whereis' nor 'locate' could find it.

**Comment by briskycat** [comment]
I get the same error with Qt installed from MacPorts:

`$ /Applications/CopyQ.app/Contents/MacOS/copyq 
dyld: Library not loaded: /usr/local/Cellar/qt5/5.6.1/lib/QtWidgets.framework/Versions/5/QtWidgets
  Referenced from: /Applications/CopyQ.app/Contents/Frameworks/QtSvg.framework/Versions/5/QtSvg
  Reason: image not found
Abort trap: 6

$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.12.1
BuildVersion:	16B2555`

**Comment by briskycat** [comment]
So, this is clearly a bug in the application bundle for the 2.7.1 :

```
/Volumes/CopyQ/CopyQ.app/Contents/Frameworks/QtSvg.framework/Versions/5$ otool -L QtSvg 
QtSvg:
	@executable_path/../Frameworks/QtSvg.framework/Versions/5/QtSvg (compatibility version 5.6.0, current version 5.6.1)
	/usr/local/Cellar/qt5/5.6.1/lib/QtWidgets.framework/Versions/5/QtWidgets (compatibility version 5.6.0, current version 5.6.1)
	/usr/local/Cellar/qt5/5.6.1/lib/QtGui.framework/Versions/5/QtGui (compatibility version 5.6.0, current version 5.6.1)
	/usr/local/Cellar/qt5/5.6.1/lib/QtCore.framework/Versions/5/QtCore (compatibility version 5.6.0, current version 5.6.1)
	/System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/AGL.framework/Versions/A/AGL (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
```
Bundled Qt has hardcoded absolute paths to /usr/local/Cellar/qt5/5.6.1/lib.

**Comment by hluk** [comment]
Can anyone check if automatic build scripts for Travis are OK? Particularly:
- [build-osx.sh](https://github.com/hluk/CopyQ/blob/master/utils/build-osx.sh)
- [create_dmg.sh](https://github.com/hluk/CopyQ/blob/master/utils/create_dmg.sh)
- [QMake build file copyq.pro](https://github.com/hluk/CopyQ/blob/master/copyq.pro)

It could be easier to build dmg package with CMake.

**Comment by hluk** [comment]
Here is [new package for 2.8.1](https://github.com/hluk/CopyQ/releases/download/v2.8.1/CopyQ.dmg). If it doesn't work please refer to #590.

**Comment by bogste** [comment]
Could you guys have a look at this again? I am not able to start version `3.1.1` up on Sierra. Installed via Homebrew; it only starts up if I use `sudo copyq &` in a `Terminal` window.

**Comment by hluk** [comment]
Works for me.

What does `copyq version` command print?

Lukas

**Comment by bogste** [comment]
Hello, thanks for coming back to me on this!

There you go:

``` Bash
redactedmachine:~ redacted_user$ copyq --version
CopyQ Clipboard Manager v3.1.1 (hluk@email.cz)
Built with: Qt 5.9.1, LibQxt 0.7.0
```

**Comment by hluk** [comment]
Does `copyq` print any errors? Also check log file, it should be `/Applications/$USER/Library/Application Support/copyq/copyq/copyq.log`.

**Comment by bogste** [comment]
Yes, I already posted the error above:

``` Bash
redactedmachine:~ redacted_user$ copyq
ERROR: Failed to create server: QLocalServer::listen: Permission denied
Warning: CopyQ server is already running.
```

I found 2 log files:

1.) One per `non-sudo user` - where errors are encountered at run
`cat /Users/redacted_user/Library/Application\ Support/CopyQ/copyq/copyq.log`

``` Text
CopyQ ERROR [2017-10-04 12:32:57.564] Server-20334: Failed to create server: QLocalServer::listen: Permission denied
CopyQ Warning [2017-10-04 12:32:57.565] Server-20334: CopyQ server is already running.
CopyQ ERROR [2017-10-04 12:34:45.575] Server-20427: Failed to create server: QLocalServer::listen: Permission denied
CopyQ Warning [2017-10-04 12:34:45.576] Server-20427: CopyQ server is already running.
CopyQ ERROR [2017-10-04 12:35:26.086] Server-20454: Failed to create server: QLocalServer::listen: Permission denied
CopyQ Warning [2017-10-04 12:35:26.088] Server-20454: CopyQ server is already running.
CopyQ ERROR [2017-10-04 12:36:07.104] Server-20486: Failed to create server: QLocalServer::listen: Permission denied
CopyQ Warning [2017-10-04 12:36:07.105] Server-20486: CopyQ server is already running.
CopyQ ERROR [2017-10-04 13:10:23.826] Server-24825: Failed to create server: QLocalServer::listen: Permission denied
CopyQ Warning [2017-10-04 13:10:23.828] Server-24825: CopyQ server is already running.
CopyQ ERROR [2017-10-04 17:27:02.567] Server-3998: Failed to create server: QLocalServer::listen: Permission denied
CopyQ Warning [2017-10-04 17:27:02.569] Server-3998: CopyQ server is already running.
CopyQ ERROR [2017-10-04 17:27:34.258] Server-4046: Failed to create server: QLocalServer::listen: Permission denied
CopyQ Warning [2017-10-04 17:27:34.259] Server-4046: CopyQ server is already running.
CopyQ ERROR [2017-10-04 17:32:19.750] Server-4213: Failed to create server: QLocalServer::listen: Permission denied
CopyQ Warning [2017-10-04 17:32:19.751] Server-4213: CopyQ server is already running.
CopyQ ERROR [2017-10-04 17:33:18.001] Server-4244: Failed to create server: QLocalServer::listen: Permission denied
CopyQ Warning [2017-10-04 17:33:18.002] Server-4244: CopyQ server is already running.
CopyQ ERROR [2017-10-04 20:57:11.390] Server-9820: Failed to create server: QLocalServer::listen: Permission denied
CopyQ Warning [2017-10-04 20:57:11.391] Server-9820: CopyQ server is already running.
CopyQ ERROR [2017-10-04 20:57:31.516] Server-9831: Failed to create server: QLocalServer::listen: Permission denied
CopyQ Warning [2017-10-04 20:57:31.518] Server-9831: CopyQ server is already running.
CopyQ ERROR [2017-10-04 20:58:28.919] Server-9903: Failed to create server: QLocalServer::listen: Permission denied
CopyQ Warning [2017-10-04 20:58:28.920] Server-9903: CopyQ server is already running.
CopyQ ERROR [2017-10-04 20:59:23.027] Server-10026: Failed to create server: QLocalServer::listen: Permission denied
CopyQ Warning [2017-10-04 20:59:23.028] Server-10026: CopyQ server is already running.
CopyQ ERROR [2017-10-04 22:28:04.051] Server-11636: Failed to create server: QLocalServer::listen: Permission denied
CopyQ Warning [2017-10-04 22:28:04.052] Server-11636: CopyQ server is already running.
CopyQ ERROR [2017-10-05 10:39:17.278] Server-525: Failed to create server: QLocalServer::listen: Permission denied
CopyQ Warning [2017-10-05 10:39:17.280] Server-525: CopyQ server is already running.
CopyQ ERROR [2017-10-05 11:01:09.489] Server-1688: Failed to create server: QLocalServer::listen: Permission denied
CopyQ Warning [2017-10-05 11:01:09.490] Server-1688: CopyQ server is already running.
CopyQ ERROR [2017-10-05 11:01:25.369] Server-1718: Failed to create server: QLocalServer::listen: Permission denied
CopyQ Warning [2017-10-05 11:01:25.370] Server-1718: CopyQ server is already running.
CopyQ ERROR [2017-10-05 11:10:53.368] Server-1895: Failed to create server: QLocalServer::listen: Permission denied
CopyQ Warning [2017-10-05 11:10:53.369] Server-1895: CopyQ server is already running.
CopyQ ERROR [2017-10-05 11:11:08.470] Server-2001: Failed to create server: QLocalServer::listen: Permission denied
CopyQ Warning [2017-10-05 11:11:08.472] Server-2001: CopyQ server is already running.
CopyQ ERROR [2017-10-05 11:15:35.124] Server-2189: Failed to create server: QLocalServer::listen: Permission denied
CopyQ Warning [2017-10-05 11:15:35.125] Server-2189: CopyQ server is already running.
```
 
and 2.) one (probably) per `sudo user`, where everything seems nice and smooth)
`cat /Users/redacted_user/Library/Application\ Support/CopyQ/copyq.log`:

``` Text
CopyQ Note [2017-10-04 12:32:57.562] : Ended activity
CopyQ Note [2017-10-04 12:34:45.574] : Ended activity
CopyQ Note [2017-10-04 12:35:26.085] : Ended activity
CopyQ Note [2017-10-04 12:36:07.103] : Ended activity
CopyQ Note [2017-10-04 13:10:23.825] : Ended activity
CopyQ Note [2017-10-04 17:27:02.563] : Ended activity
CopyQ Note [2017-10-04 17:27:34.256] : Ended activity
CopyQ Note [2017-10-04 17:32:19.748] : Ended activity
CopyQ Note [2017-10-04 17:33:17.999] : Ended activity
CopyQ Note [2017-10-04 17:45:26.901] : Ended activity
CopyQ Note [2017-10-04 20:57:11.387] : Ended activity
CopyQ Note [2017-10-04 20:57:31.514] : Ended activity
CopyQ Note [2017-10-04 20:58:28.918] : Ended activity
CopyQ Note [2017-10-04 20:59:23.026] : Ended activity
CopyQ Note [2017-10-04 22:28:04.050] : Ended activity
CopyQ Note [2017-10-05 10:39:17.270] : Ended activity
CopyQ Note [2017-10-05 11:01:09.488] : Ended activity
CopyQ Note [2017-10-05 11:01:25.368] : Ended activity
CopyQ Note [2017-10-05 11:10:53.367] : Ended activity
CopyQ Note [2017-10-05 11:11:08.469] : Ended activity
CopyQ Note [2017-10-05 11:15:35.123] : Ended activity
```

**Comment by hluk** [comment]
Try to run following command.
```
COPYQ_LOG_LEVEL=DEBUG copyq
```

**Comment by bogste** [comment]
I got that the Qt server might be running already? WTH? Checked both Activity Monitor and `htop` and there's no such process active?

Please see output below:

``` Bash
redactedmachine:~ redacted_user$ COPYQ_LOG_LEVEL=DEBUG copyq
Note: Started Background activity for: CopyQ Server
Note: Ended activity
ERROR: Failed to create server: QLocalServer::listen: Permission denied
DEBUG: Server "/Users/redacted_user/.config/copyq/.copyq_s" already running!
Warning: CopyQ server is already running.
```

**Comment by hluk** [comment]
Interesting, thanks for the investigation.

So running `sudo copyq` messes up permissions in the configuration directory of current user (I just tested this too).

I wasn't aware that on OS X this can happen -- I would expect any configuration of a process executed with `sudo` to go into `/Users/root/`.

BTW, `brew` doesn't touch files in user directories.

**Comment by bogste** [comment]
I guess I will need to thank you as well, for your prompt responses, on this. 👍 😄 

Without your input I wouldn't have figured it out. Also, I am wishing that our discussion here will help other people as well.

Unless a bugfix is in order, maybe?

**Comment by hluk** [comment]
> Unless a bugfix is in order, maybe?

@bogste I have no idea how to properly fix this or even if to fix this at all in CopyQ.

Actually, for me it's no problem if permissions change for files in home directory by running `sudo copyq`; user can still remove or modify these files because there seems to be some extended attributes set on them or their home directory that allows user always to "own" the files. But this probably depends on file system.

**Comment by bogste** [comment]
Maybe you could add some permission tests, on config folder in the User's HOME dir? If they do not match somehow, ask for the `sudo` password and just `chgrp`/`chown` using it?

Not sure on how easy this is to implement, however, it is worth a shot if the problem is happening for all users.
