### ISSUE TITLE
Not opening, when I install the new version-2.7.1 in mac pro!

### ISSUE THREAD

**Issue by varra4u** [hluk/CopyQ#553]
I installed the new version today, and found it as not responding when i try to open it after successful installation in MAC!

**Comment by squirrelboot** [comment]
I too am having this issue. I have also tried it with 2.7.0 and the same issue occurs.
I am using an iMac with MacOS Sierra.

**Comment by squirrelboot** [comment]
Update: Ok so I am not one to wait for someone to just fix it. I like to dig deeper.
So varra4u, check out this:  https://github.com/hluk/CopyQ#dependencies

We need to install QT. At least version 5.2. The latest being 5.7 which you can get from here:
https://www.qt.io/download-open-source/

**Comment by nivaca** [comment]
@squirrelboot Wow! That's a 1.6GB download and install just to run this nice app!

**Comment by hluk** [comment]
Here is [new package for 2.8.1](https://github.com/hluk/CopyQ/releases/download/v2.8.1/CopyQ.dmg). If it doesn't work please refer to #590.
