### ISSUE TITLE
Selecting Text causes notifications on Ubuntu 16.04

### ISSUE THREAD

**Issue by jfreak53** [hluk/CopyQ#557]
Before my upgrade to 16.04 copyq was working fine. Now copyq displays the copy notification every time I select text in any window.

![Notification] (http://cdn.microthosting.com/imgs/Screenshot_at_2016-10-18_15-24-48.png)

I have that featured turned off in settings but it still does it:

![Settings] (http://cdn.microthosting.com/imgs/Screenshot_at_2016-10-18_15-26-24.png)

copyq version is:

```
CopyQ Clipboard Manager v2.7.1 (hluk@email.cz)
Built with: Qt 4.8.7, LibQxt 0.7.0
```

And I'm on Ubuntu 16.04.1 x64 fresh install.

**Comment by hluk** [comment]
Are those really notifications from CopyQ?

Did you try it without CopyQ running?

Do you have any commands defined in Command dialog <kbd>F6</kbd>?

You can also check if mouse selections are somehow propagated into clipboard -- you can inspect clipboard content in Clipboard Content dialog <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>C</kbd>.

**Comment by jfreak53** [comment]
`Are those really notifications from CopyQ? Did you try it without CopyQ running?`

Yes, I can confirm they are from CopyQ by closing CopyQ then trying it, it doesn't happen when it's closed.

`Do you have any commands defined in Command dialog F6?`

This is what I have:
http://cdn.microthosting.com/imgs/Screenshot_at_2016-10-24_08-19-07.png

`You can also check if mouse selections are somehow propagated into clipboard -- you can inspect clipboard content in Clipboard Content dialog Ctrl+Shift+C.`

No, when I select something it's not automatically in the clipboard. It shows the notification but it only goes into the clipboard when I actually CTRL+C or Right Click Copy. Selecting only shows the notification not actually put it in.

**Comment by hluk** [comment]
Automatic commands are applied on selection too.

To ignore selection in commands put the following command at the top of the list (copy-paste it to the list in Command dialog).

```ini
[Command]
Automatic=true
Command="
    copyq:
    var mode = str(data('application/x-copyq-clipboard-mode'))
    if (mode == 'selection')
      ignore()"
Icon=\xf05e
Name=Ignore selection in following automatic commands
```

**Comment by jfreak53** [comment]
Perfect! Thanks!
