### ISSUE TITLE
No System Tray Icon

### ISSUE THREAD

**Issue by iomari** [hluk/CopyQ#558]
Greetings,
I'm using cinnamon on opensuse 13.2. I'm using copyq 2.7.1 with no problems except I can't seem to find the system tray icon. It's kind of annoying that I have to execute 'copyq show' everytime I want to use the app.

What am I missing?

iomari

**Comment by hluk** [comment]
What's the desktop environment and window manager you use?

**Comment by iomari** [comment]
Sorry for the late reply. I don't know what I did but it's showing in the tray now. Maybe it was the last system update I did.

**Comment by iomari** [comment]
Cinnamon on opensuse 13.2
