### ISSUE TITLE
Add option for launching the application at OS startup

### ISSUE THREAD

**Issue by hluk** [hluk/CopyQ#56]
This is mainly for Windows but may apply on Ubuntu and others too.

This should be also possible to set in Windows installer.

**Comment by sateshb** [comment]
For windows, add a new string value in the following location and specify the path to copyq.exe

Path: HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run
Value name: CopyQ
Value data: "C:\Program Files (x86)\CopyQ\copyq.exe"

_Value data may vary depending on the specified installation location.__

**Comment by Mintellect310** [comment]
Add apps to run automatically at startup in Windows 10

To add an app to Startup:
1. Select the Start Windows logo Start button button and scroll to find the app you want to run at startup.
2. Right-click the app, select More, and then select Open file location. This opens the location where the shortcut to the app is saved. If there isn’t an option for Open file location, it means the app can’t run at startup.
3. With the file location open, press the Windows logo key Windows logo Start button + R, type shell:startup, then select OK. This opens the Startup folder.
4. Copy and paste the shortcut to the app from the file location to the Startup folder.

**Comment by Adam1544** [comment]
> Add apps to run automatically at startup in Windows 10
> 
> To add an app to Startup:
> 
> 1. Select the Start Windows logo Start button button and scroll to find the app you want to run at startup.
> 2. Right-click the app, select More, and then select Open file location. This opens the location where the shortcut to the app is saved. If there isn’t an option for Open file location, it means the app can’t run at startup.
> 3. With the file location open, press the Windows logo key Windows logo Start button + R, type shell:startup, then select OK. This opens the Startup folder.
> 4. Copy and paste the shortcut to the app from the file location to the Startup folder.

Even if there's no "open file location" one can try to find it with: Win+R and then opening: Shell:AppsFolder
