### ISSUE TITLE
Internal editor converts special characters to question marks in clip when saved.

### ISSUE THREAD

**Issue by Negirno** [hluk/CopyQ#560]
OS: Ubuntu 16.04.1 LTS (with Unity)
CopyQ version: v2.7.1
Language: English, Keyboard: Hungarian

This didn't happened in 14.04. If I edit a clip in CopyQ with the internal editor, and save the changes the non-English characters like gets converted into question marks. Chinese/Japanese characters get converted into a regular '?', while most of the latin extended ones will display as �, except for the hungarian-only characters, 'ő' and 'ű', which gets the regular '?'.

The � converted characters can be "restored" by opening the clip in an external editor (Gedit for me), but if one pastes them regularly into another application, they're also lost. The characters converted to '?'s are permanently lost.

Note: editing and saving the clip in an external editor leaves the characters intact. Also, typing those special characters in the internal editor works, they're only lost when saved.

**Comment by hluk** [comment]
I couldn't reproduce it but I fixed code which probably is the culprit.

Beta package for Ubuntu 16.04 is [here](http://download.opensuse.org/repositories/home:/lukho:/copyq/xUbuntu_16.04/amd64/copyq_2.7.1.r58.gd3a21a9_amd64.deb).

Please reopen if this is not fixed.
