### ISSUE TITLE
[support] How to set ignoring passwords copied from Keepass?

### ISSUE THREAD

**Issue by mnn** [hluk/CopyQ#561]
Is it possible to ignore passwords copied from Keepass? There is *Ignore clipboard copied from some windows or containing some text* in readme, but I am failing to find it anywhere in settings.

**Comment by hluk** [comment]
I've added an entry to FAQ - [How to omit storing text copied from specific windows like a password manager?](https://github.com/hluk/CopyQ/wiki/FAQ#how-to-omit-storing-text-copied-from-specific-windows-like-a-password-manager)

**Comment by mnn** [comment]
Thank you very much :).
