### ISSUE TITLE
Wikipedia

### ISSUE THREAD

**Issue by orschiro** [hluk/CopyQ#563]
Anything else to add?

https://en.wikipedia.org/wiki/CopyQ

:-)

**Comment by hluk** [comment]
Nice job, thanks. Although the article was proposed to be removed because "not notable software." Well, that sucks.

**Comment by orschiro** [comment]
Yes, indeed. And I don't know why. I contested the deletion on the Talk
page.

**Comment by orschiro** [comment]
Sadly, the page has been deleted...

**Comment by hluk** [comment]
There are wiki pages for other clipboard managers, I wonder why CopyQ doesn't deserve to have one too.

It's quite popular on [alternativeTo](http://alternativeto.net/software/copyq/) (most popular clipboard manager for Linux and Mac).

**Comment by orschiro** [comment]
Should we try it again?

**Comment by hluk** [comment]
I don't even know what were the arguments supporting the deletion -- oddly the "Talk" page is empty. Is the discussion available somewhere?

**Comment by orschiro** [comment]
Let's do this: https://en.wikipedia.org/wiki/User_talk:Ronhjones#CopyQ

**Comment by orschiro** [comment]
![image](https://cloud.githubusercontent.com/assets/170947/20110975/cfb0b2b2-a5e6-11e6-88f4-d96aa7cd4a1d.png)

**Comment by orschiro** [comment]
The article page has been restored in Draft mode!

https://en.wikipedia.org/wiki/Draft:CopyQ

Now we need to add more independent and reliable third-party references.

**Comment by hluk** [comment]
Here are few older articles:
- http://lifehacker.com/copyq-runs-commands-and-scripts-on-content-copied-to-th-1561705745
- http://www.linux-magazine.com/Issues/2013/154/CopyQ
- http://www.webupd8.org/2013/02/copyq-interesting-clipboard-manager.html

**Comment by orschiro** [comment]
Thanks!

Added to https://en.wikipedia.org/wiki/Draft:CopyQ
