### ISSUE TITLE
Exclude sensitive processes

### ISSUE THREAD

**Issue by sergeevabc** [hluk/CopyQ#564]
How to exclude [KeePass](http://keepass.info/).exe so sensitive data would not be stored in CopyQ?

**Comment by hluk** [comment]
See FAQ: [How to omit storing text copied from specific windows like a password manager?](https://github.com/hluk/CopyQ/wiki/FAQ#how-to-omit-storing-text-copied-from-specific-windows-like-a-password-manager)

**Comment by sergeevabc** [comment]
Too hard, I’ll stay with Ditto, but thanks.

**Comment by sergeevabc** [comment]
P.S. Let alone following the instructions you provided still DOES NOT exclude KeePass. [Proof](https://ukaz.cz/a/1477925768_58058175b886806f.png).

**Comment by hluk** [comment]
Not sure what could be the problem. The steps in FAQ work for me on Windows 8.1 and Arch Linux.
