### ISSUE TITLE
Getting URL when copying text from a browser

### ISSUE THREAD

**Issue by zygimantus** [hluk/CopyQ#566]
I am wondering if there is a feature for copied text from browsers in this app (similar in OneNote) that when copying the current URL is also saved?

**Comment by hluk** [comment]
I don't know how that would be possible to implement with all main web browsers and supported platforms.

BTW, I use following command that saves window title with copied text (copy/paste the code below to Command list in Command dialog <kbd>F6</kbd>).

```ini
[Command]
Automatic=true
Command="
    copyq:
    var time = dateString('yyyy-MM-dd hh:mm:ss')
    var window = str(data('application/x-copyq-owner-window-title'))
    var tagsMime = 'application/x-copyq-tags'
    var tags = str(data(tagsMime)) + ', ' + window + ', ' + time
    setData(tagsMime, tags)"
Icon=\xf017
Name=Store Copy Time
```

**Comment by zygimantus** [comment]
Thanks, this is actually something very near the solution! By the way, can you give the link where I can find more such commands for your app?

**Comment by hluk** [comment]
Check wiki page [Command Examples](https://github.com/hluk/CopyQ/wiki/Command-Examples). I usually update the page when I find useful new commands.

**Comment by zygimantus** [comment]
Thanks. By the way, I have another question: Is it possible by your given code filter text into tabs (according to applications) which will be created by that command also?

**Comment by hluk** [comment]
Do you mean something like [Copy Clipboard to Window Tabs](https://github.com/hluk/CopyQ/wiki/Command-Examples#copy-clipboard-to-window-tabs)?

BTW, thanks for translations.

**Comment by jcwing01** [comment]
How would you write a command to automatically filter URLs to a tab called URL?

**Comment by hluk** [comment]
> How would you write a command to automatically filter URLs to a tab called URL?

@jcwing01 There is already predefined command for that, you just need to modify it.

1. Open Command dialog (F6),
2. click Add button,
3. select "Copy URL (web address) to other tab" and click OK,
4. enable "Show Advanced",
5. in Advanced tab, change the tab name in "Copy to tab" (default is "web"),
6. click OK to save the new command.

Now when you copy an URL, it will be added to the different tab.

**Comment by jcwing01** [comment]
Thank you Lukas!

Jay

On Wed, Jun 12, 2019 at 9:11 AM Lukas Holecek <notifications@github.com<mailto:notifications@github.com>> wrote:

How would you write a command to automatically filter URLs to a tab called URL?

@jcwing01<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjcwing01&data=02%7C01%7C%7Ca17a47c94b914621e80508d6ef37884b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636959419116458799&sdata=yMTl3Q3uwuQHA4qoD%2BtyznE5sXh7SkgqkyZAcDdVEKA%3D&reserved=0> There is already predefined command for that, you just need to modify it.

  1.  Open Command dialog (F6),
  2.  click Add button,
  3.  select "Copy URL (web address) to other tab" and click OK,
  4.  enable "Show Advanced",
  5.  in Advanced tab, change the tab name in "Copy to tab" (default is "web"),
  6.  click OK to save the new command.

Now when you copy an URL, it will be added to the different tab.

**Comment by jcwing01** [comment]
Thanks Lukas!
Is there any way to also have it automatically copy the URL's Window Title to the Note? 
Cheers

**Comment by jcwing01** [comment]
Hi Lukas,

Thanks for the help!  
I'm trying to do the same thing with File Paths, ie send them to a Tab called 'Files'  I'm using the Linkify command code to convert them to a link:

[Command]
Name=Linkify
Match=file://
Command="
    copyq:
    var link = str(input());
    var href = '<a href=\"###\">###</a>';
    write(
      'text/plain', link,
      'text/html', href.replace(/###/g, link)
    );"
Input=text/plain
Automatic=true
Remove=true

It creates the link, but sends a plain text copy to the destination folder and leaves the html version in the main folder.  Thanks for any help

**Comment by hluk** [comment]
@jcwing01 I think following could help:

```ini
[Command]
Automatic=true
Command="
    copyq:
    var outputTab = 'Files'
    var url = str(input());
    var html = '<a href=\"###\">###</a>'.replace(/###/g, url)
    setData(mimeText, url)
    setData(mimeHtml, html)
    setData(mimeOutputTab, outputTab)"
Enable=false
Input=text/plain
Match=file://
Name=Linkify
```

**Comment by jcwing01** [comment]
fantastic Lukas, you're the best!
One last thing:  would there be any way to copy just the filename itself to the Note?  I was able to do something like this with Windows Titles and URLs, using your advice.  Just wondering.

**Comment by hluk** [comment]
> One last thing: would there be any way to also copy just the filename itself to the Note? 

@jcwing01

```ini
[Command]
Automatic=true
Command="
    copyq:
    var outputTab = 'Files'
    var url = str(input());
    var html = '<a href=\"###\">###</a>'.replace(/###/g, url)
    var note = url.replace(/.*\\//, '')
    setData(mimeText, url)
    setData(mimeHtml, html)
    setData(mimeItemNotes, note)
    setData(mimeOutputTab, outputTab)"
Input=text/plain
Match=file://
Name=Linkify
```
