### ISSUE TITLE
Gaps to the left of menu items in macOS

### ISSUE THREAD

**Issue by briskycat** [hluk/CopyQ#567]
There is ugly free space in menus on macOS Sierra 10.12 (at least) to the left of menu items.
In the main window:
![SS1](https://raw.githubusercontent.com/briskycat/asaws-stuff/master/img/CopyQ/Screen%20Shot%202016-11-03%20at%2017.05.59.png) ![SS1_1](https://raw.githubusercontent.com/briskycat/asaws-stuff/master/img/CopyQ/Screen%20Shot%201.png)
And also in the tray menu:
![SS2](https://raw.githubusercontent.com/briskycat/asaws-stuff/master/img/CopyQ/Screen%20Shot%202016-11-03%20at%2017.07.52.png)
(note how the scissors to the left of the Show/Hide item are distorted too).
Compare how normal Qt menus look on the same macOS:
![SS3](https://raw.githubusercontent.com/briskycat/asaws-stuff/master/img/CopyQ/Screen%20Shot%202016-11-03%20at%2017.09.28.png)
QopyQ assembled from git master branch (732ed8e047be0dd660fc323612a523c534177bff). Qt 5.6.1 from MacPorts.

**Comment by hluk** [comment]
Did you build the app with `cmake`? Are there icons in toolbars or on tabs in Preferences dialog?

Also check if there are any warnings or errors in log (under "Help | Show Log").

**Comment by briskycat** [comment]
I built both ways: the first time I made a release build with qmake, the second time I made a debug build with cmake. There are icons in toolbars and on tabs in the Preferences dialog (but not in menus). There are no errors or warnings in the log. In the release build there are messages like "Note [2016-10-30 20:53:45.965]: Showing main window first to get menu
Note [2016-10-30 23:19:43.819]: Loading plugin: /Applications/CopyQ.app/Contents/Plugins/copyq/libitemdata.dylib".
In the debug build there are additional messages marked with "DEBUG" (but no errors or warnings either).

**Comment by hluk** [comment]
I tried to fix it in branch "osx-menu-icons" -- unfortunately I cannot test it on OS X.

Can you check if the icons are rendered and are smooth?

**Comment by briskycat** [comment]
Yes, in the osx-menu-icons branch there are pretty icons instead of gaps in menus. And the scissors in the tray menu are rendered smoothly.

**Comment by hluk** [comment]
It should be in master branch -- I just generate few icon sizes so hopefully icons will still be smooth. Thanks for testing.
