### ISSUE TITLE
What version works on macOS Sierra 10.12.1?

### ISSUE THREAD

**Issue by pavlelekic** [hluk/CopyQ#569]
I upgraded to Sierra, and downloaded the latest version of copyq, and when I run it nothing happens. There is no interface, no window, nothing. Is there a version that works on Sierra?

**Comment by pavlelekic** [comment]
Actually I found version 2.4.5 to work with Sierra :)

**Comment by hluk** [comment]
2.4.5 is pretty old version.

From issue #567 it seems to work if you build the app yourself.

I should start uploading every package built with [Travis CI](https://travis-ci.org/hluk/CopyQ) so it's possible to test it. Also as I mentioned in #552 the build scripts probably need to be improved.

**Comment by mrjcleaver** [comment]
I tried 2.8.0 on Sierra:
````
Martins-MacBook-Pro:Chef martincleaver$ /Applications/CopyQ.app/Contents/MacOS/copyq 
dyld: Library not loaded: /usr/local/Cellar/qt5/5.7.0/lib/QtWidgets.framework/Versions/5/QtWidgets
  Referenced from: /Applications/CopyQ.app/Contents/Frameworks/QtSvg.framework/Versions/5/QtSvg
  Reason: image not found
Abort trap: 6
````

**Comment by mrjcleaver** [comment]
Moved to https://github.com/hluk/CopyQ/issues/581

**Comment by hluk** [comment]
Here is [new package for 2.8.1](https://github.com/hluk/CopyQ/releases/download/v2.8.1/CopyQ.dmg). If it doesn't work please refer to #590.
