### ISSUE TITLE
Paste plain text keep formated

### ISSUE THREAD

**Issue by guilhas** [hluk/CopyQ#570]
Hello,

Is it possible when pasting as plain text to still keep the formatted in the clipboard?

Regards,
Lino

**Comment by SamHasler** [comment]
A script to split out an item into separate items for each format would be useful, and would fulfill this 
request.

**Comment by hluk** [comment]
Following command should do the trick.

```ini
[Command]
Name=Paste clipboard as plain text
Command="
    copyq: 
    var text = clipboard()
    if (text) {
      hide()
      var html = clipboard('text/html')
      copy(text)
      copySelection(text)
      paste()
      copy('text/plain', text, 'text/html', html)
    }"
Icon=\xf0ea
GlobalShortcut=ctrl+shift+v
```

**Comment by guilhas** [comment]
Thank you. It works.

Best regards,
Lino
