### ISSUE TITLE
Pasting timestamp?

### ISSUE THREAD

**Issue by orschiro** [hluk/CopyQ#572]
Dear all, 

Is it possible to paste a timestamp like `2016/11/08 18:14`?

Thanks!

-Robert

**Comment by orschiro** [comment]
This is how I imagine it:

![image](https://cloud.githubusercontent.com/assets/170947/20115113/5ebcc53a-a5f7-11e6-8e0a-b69dda597335.png)

**Comment by hluk** [comment]
Would [this command](https://github.com/hluk/CopyQ/wiki/Command-Examples#paste-current-date-and-time) help?
