### ISSUE TITLE
Cannot create item with ł

### ISSUE THREAD

**Issue by orschiro** [hluk/CopyQ#573]
`ł`

https://en.wikipedia.org/wiki/%C5%81

It's being changed into `?` upon saving.

**Comment by hluk** [comment]
Is that perhaps font issue? Can you copy and paste the character correctly from CopyQ?

**Comment by orschiro** [comment]
I took the character directly from Wikipedia. 

> Can you copy and paste the character correctly from CopyQ?

What do you mean?

**Comment by hluk** [comment]
If you copy the item with the character, can it be pasted correctly?

BTW, I cannot reproduce this -- the item contains correct character after copying from wiki page.

**Comment by orschiro** [comment]
Clipboard does work well with this character, just not the Snippet function...

![image](https://cloud.githubusercontent.com/assets/170947/20141662/a3abd15a-a691-11e6-85c9-56f31c57b51a.png)

![image](https://cloud.githubusercontent.com/assets/170947/20141669/a9e98580-a691-11e6-9aaa-3dc72fdcf6dd.png)

![image](https://cloud.githubusercontent.com/assets/170947/20141679/b13a4e78-a691-11e6-837a-776b05067722.png)

**Comment by hluk** [comment]
I don't know what you mean by "Snippet function". Is this issue about builtin editor?

[Snippet command](https://gist.github.com/hluk/af37cd2ca650c92ed0fa) works for me when I try to paste snippet with "ł" in builtin editor.

**Comment by orschiro** [comment]
Dear @hluk,

I am sorry that my description of the issue is so vague. Does the following animation help?

![copyq](https://cloud.githubusercontent.com/assets/170947/20147049/be3754b2-a6a6-11e6-8097-fe094bb53803.gif)

**Comment by hluk** [comment]
Can you check what formats the new item contains with <kbd>F4</kbd>?

**Comment by orschiro** [comment]
![image](https://cloud.githubusercontent.com/assets/170947/20147918/7e3837d8-a6aa-11e6-81ed-a215eaa96630.png)

![image](https://cloud.githubusercontent.com/assets/170947/20147925/8262788c-a6aa-11e6-8904-2990c0b1f7e1.png)

**Comment by hluk** [comment]
Hmm, this could be bug in Qt. I'm using Qt 5.7.0 and don't see this issue. Can you post output of `copyq version`?

**Comment by orschiro** [comment]
```
orschiro@x230:~$ copyq version
CopyQ Clipboard Manager v2.7.1 (hluk@email.cz)
Built with: Qt 4.8.7, LibQxt 0.7.0

```

**Comment by hluk** [comment]
Even with that version I cannot reproduce this -- except with Qt 4.8.7 "text/html" is generated. The "text/plain" format for me has 2 bytes for that character.

I'll try to create Qt 5 packages for CopyQ at [OBS](https://build.opensuse.org/package/show/home:lukho:copyq/CopyQ-Qt5) -- hopefully this will work at least the new distros.

**Comment by orschiro** [comment]
Thanks for your efforts!

Can I somehow help?

**Comment by hluk** [comment]
No problem. It already builds successfully on Ubuntu. The difficult part is to figure out which system packages are needed for build and runtime on each distribution.

Grab the newest package for Ubuntu 16.10 from [here](http://download.opensuse.org/repositories/home:/lukho:/copyq/xUbuntu_16.10/amd64/?C=M;O=D).

**Comment by orschiro** [comment]
Installed the new version. Problem is almost fixed! :-)

I can paste it.

The only remaining problem is the following representation:

![image](https://cloud.githubusercontent.com/assets/170947/20150908/5f97c1b4-a6b8-11e6-948c-87cbafa6994a.png)

**Comment by hluk** [comment]
Just open "Item Content" dialog <kbd>F4</kbd> for the item, select "text/html" and press <kbd>Delete</kbd>.

This is because it's sometimes not possible to detect whether to save also rich text (this feature was added with pasting images to builtin editor).

**Comment by orschiro** [comment]
Problem solved.

You are amazing, Lukas! :-)

**Comment by hluk** [comment]
Thanks! 😊
