### ISSUE TITLE
Items paste from main window

### ISSUE THREAD

**Issue by brkerez** [hluk/CopyQ#574]
Hi !
I don't know if that's already possible but I searched through FAQ and Wiki and didn't find anything.

My problem with CopyQ is that is not pasting items I click in main window automatically to current window, it only places it in clipboard. I'm trying to switch from ArsClip to CopyQ but this is blocker for me because this is not the fastest way I can paste items to text Im working with, it requires additional Ctrl+V.

Maybe it is possible with defining action and shortcut for it but that's even more complicated, all I want to do is show main window on some global os shortcut (already configured but I wonder why this is not already predefined as this is I think the most used feature in clipboard history utilities) and then click the item I want to paste it, done. Maybe I'm missing something but I don't see how this can be done right now.

Thanks,
Pavel

**Comment by hluk** [comment]
It's not enabled by default. You need to enable "Paste to current windows" in "History" config tab in Preferences dialog.

**Comment by brkerez** [comment]
Oh I'm sorry I'm blind :)
