### ISSUE TITLE
Clipboard ignores duplicate clips

### ISSUE THREAD

**Issue by BJS1** [hluk/CopyQ#576]
Before adding any clip to the clipboard, CopyQ seems to automatically do a pre-search.  If a matching clip is found, nothing is added to the clipboard.  The identical clip is moved to the top.   There seems to be no way to enable/disable this feature.
The problem is that I am copying a batch of single numbers from one app (some of which are repeated), and moving them as a group to another app.  All identical numbers don't get copied.
Solution?  Thx.

**Comment by hluk** [comment]
You can use following command (copy/paste it to command list in Command dialog <kbd>F6</kbd>).

```ini
[Command]
Name=Add Clipboard to List - Duplicates Included
Command="
    copyq:
    write('application/x-copyq-item', input())"
Input=application/x-copyq-item
Automatic=true
Icon=\xf055
```

It should be last command in the command list.

**Comment by leoalekseyev** [comment]
The proposed solution doesn't work.  First of all, automatic flag means junk gets put into the item list on mouse selection.  Second, when I assigned that command to a shortcut (Ctrl-Shift-C) copying did not work; the item list showed <DATA> and wouldn't paste what was copied.

**Comment by hluk** [comment]
@leoalekseyev  Following command should work a little better and it ignores mouse selections.

```ini
[Command]
Automatic=true
Command="
    copyq:
    if (dataFormats().indexOf(mimeClipboardMode) == -1) {
      write(mimeItems, input())
      removeData(mimeOutputTab)
    }"
Icon=\xf055
Input=application/x-copyq-item
Name=Add Clipboard to List - Duplicates Included
```

Mapping the command to a shortcut won't do anything useful since it works only automatically on changed clipboard data.
