### ISSUE TITLE
Ability to print several selected items

### ISSUE THREAD

**Issue by bigalgeorge** [hluk/CopyQ#579]
Ive been trying to make an action eg in ubuntu:
lpr %1
But its not working can anyone suggest the correct method I want to do away with Ctrl-P action for preferences and add a new Ctrl-P for print dialog of selected items. thanks!

**Comment by hluk** [comment]
You can use a command to print selected items -- following one prints selected items with plain text (copy/paste it to list in command dialog).

```ini
[Command]
Command=lpr
Icon=\xf02f
InMenu=true
Input=text/plain
Name=Print Items
Shortcut=ctrl+p
```

You would need more sophisticated command to print html, images etc. It's better to paste items to an editor like LibreOffice Writer.

I'm not planing to add print support.
