### ISSUE TITLE
LibreOffice Calc freezes when selecting columns when CopyQ "Images" enabled in items tab

### ISSUE THREAD

**Issue by CyberShadow** [hluk/CopyQ#580]
Hi. I noticed the following issue:

If in CopyQ's preferences, on the "Items" tab, "Images" is enabled, when you select a column in LibreOffice Calc (simply select, e.g. click on a column header), Calc freezes for a few dozen seconds.

Looking at Calc's stack trace, it seems to be generating a large PNG file. I'm guessing CopyQ is requesting an image representation of the selection, which can be pretty large in a nearly-infinite spreadsheet.

Note that on the "General" tab, I don't have anything regarding mouse selection checked, so I'm not sure why CopyQ is interested in the current selection in Calc.

For web search engines: for a long time I thought that Calc freezes when I *right-clicked* a column header. However, it is the action of selecting it which is what is causing problems. Once I figured that out, it became easy to identify CopyQ as the cause.

I don't need the "Images" item feature, so this problem has a simple workaround for me, but I figured I should report it anyway.

I'm running CopyQ 2.7.1 and LibreOffice 5.2.3.3 on Arch Linux (x86_64).

**Comment by hluk** [comment]
This is strange: selection shouldn't even contain images. I guess the clipboard have been set by Calc after making the selection.

I don't see this behavior - making selection in Calc doesn't change selection buffer or clipboard. I'm using same system and LibreOffice version, only CopyQ is [recently released version 2.8.0](http://download.opensuse.org/repositories/home:/lukho:/copyq/Arch_Extra/).

Perhaps the behavior can differ depending on options in Calc or desktop environment (mine is Xfce).

Thanks for the report.

**Comment by hluk** [comment]
OK, I was wrong the selection buffer really contains image after making selection in Calc.

**Comment by Coyette** [comment]
Thank you, CyberShadow, you solved my problem with Calc. I had that issue for quite a while, but did not realize that CopyQ was causing this problem in LibreOffice Calc.
