### ISSUE TITLE
Tabs, Items and setting gone after upgrade from 2.7.1 to 2.8.0

### ISSUE THREAD

**Issue by SamHasler** [hluk/CopyQ#583]
I just upgraded to 2.8.0 and all my tabs and settings are gone.

It looks like the files are still there in the install location:
 `C:\Program Files (x86)\_\Environment\CopyQ\config\copyq`
but CopyQ doesn't appear to be reading them any more.

Also, I checked using windows "previous version" feature, and `config\copyq\copyq.ini` has not changed since the upgrade.

**update**: I've downgraded to 2.7.1 and all my settings, items and tabs are back.

**Comment by hluk** [comment]
CopyQ no longer creates `config` subfolder in installation folder on Windows (it won't be possible for multiple users to use the app), this should only happen for portable application.

If you want to use `config` subfolder, move the application to some other location and remove `uninst*.exe` and `uninst*.dat` files.

If you want to use the installed application, move `config\copyq*` to `%APPDATA%\`.

Sorry for the inconvenience.

**Comment by SamHasler** [comment]
That makes sense.

It would have been helpful if the installer had at least warned that it was
going to happen and it was called out prominently in the release notes.

Automatic migration would have been even better.

**Comment by SamHasler** [comment]
@hluk, is it worth adding a note in bold to https://github.com/hluk/CopyQ/releases/tag/v2.8.0 to say that the settings location has changed and descibe how to move it? (basically put what you wrote above into the release notes).

**Comment by hluk** [comment]
OK, I've added the info to the release notes. I'll keep this open for a while too. Thanks.

**Comment by SamHasler** [comment]
That's great.

Do you think modifying the installer to migrate the configuration automatically would be hard?  If you update https://github.com/hluk/CopyQ/wiki/Customize-and-build-the-Windows-installer I'll take a crack at it.

**Comment by hluk** [comment]
I don't know what the installed generator (Inno Setup) can do - probably it won't be that easy or safe to move the folder.

For me the folder was created when using my non-admin account after I installed the application with elevated admin access rights. So in addition to move the folder you probably need to change access rights to all files in the folder.

There are more problems like multiple users using the folder or having already some configuration in `%APPDATA%`. I know it's a mess but currently it may be safer for user to handle this.

If you want to give it a spin anyway: The installation is generated by Appveyor which executes [appveyor-after-build.bat](https://github.com/hluk/CopyQ/blob/master/utils/appveyor-after-build.bat) to generate portable app folder from build files and runs Inno Setup (the last line).

So you basically don't have to build the app. You just need clone of this repo, unzipped portable version and Inno Setup. Open [shared/copyq.iss](https://github.com/hluk/CopyQ/blob/master/shared/copyq.iss) in Inno Setup and add few lines at the beginning of the file.

```
#define AppVersion 2.8.1-beta
#define Source C:\path\to\CopyQ-repository-clone
#define Destination C:\path\to\CopyQ-portable
```

You should now be able to modify the file in Inno Setup and run it easily.

I'll update the old wiki page.
