### ISSUE TITLE
FR: paste one line at a time

### ISSUE THREAD

**Issue by RustemA** [hluk/CopyQ#584]
Could look something like this: Copy a chunk of text consisting of several lines. Invoke "split paste", then paste repeatedly - text is pasted line by line until the last line is pasted.

**Comment by hluk** [comment]
Following command could help (copy/paste to command list in Command dialog <kbd>F6</kbd>).

```ini
[Command]
Name=Paste One Line
Command="
    copyq:
    var text = str(clipboard())
    var n = text.indexOf('\\n') + 1
    var line = n == 0 ? text : text.substr(0, n)
    var rest = n == 0 ? '' : text.substr(n)
    copy(line)
    paste()
    copy(rest)"
Icon=\xf0cb
GlobalShortcut=ctrl+shift+3
```

Unfortunately this could freeze the app for some time if you use the version 2.8.0 (#585 - will be fixed in next version).
