### ISSUE TITLE
Toggle 'Show simple items' setting

### ISSUE THREAD

**Issue by nicpitsch** [hluk/CopyQ#586]
Is there a shortcut or command for toggle the new 'Show simple items' setting (i don't mean F7 Show Preview)?

**Comment by hluk** [comment]
Copy/paste the following code to command list in Command dialog <kbd>F6</kbd> and change the shortcut.

```ini
[Command]
Name=Toggle Simple Items
Command="
    copyq:
    var option = 'show_simple_items'
    var enabled = config(option) == 'true'
    config(option, enabled ? 'false' : 'true')"
InMenu=true
Shortcut=ctrl+1
```

**Comment by nicpitsch** [comment]
Thanks a lot. Very pleased about this new functionality in v2.8.0 and about CopyQ in general!
