### ISSUE TITLE
Ubuntu 16.04: installing from packages won't work, please compile

### ISSUE THREAD

**Issue by omidfi** [hluk/CopyQ#587]
Hello, 
Thanks for the awesome CopyQ! 

I've tried a couple of times to install copyQ from .deb packages, but it doesn't work. An endless struggle with libqt packages was all I got. 

Is it worth it to add a note like that to Readme? 

At least I have this issue here as a note to self, so that next time I don't struggle with QT for too long and go to compiling straight :grinning:

**Comment by hluk** [comment]
CopyQ for newer distros now uses Qt 5 libraries (instead of old Qt 4). All dependencies should be installed with the package. Is there any dependency that is missing?

**Comment by GlebWork** [comment]
It asks qtscripts5 libqt5xml5 libqt5script5. Everything except qtscripts5 can be installed with some difficulties. Also I tried to install qtscripts5-dev - doesn't help.

**Comment by orschiro** [comment]
Same problem with `copyq_2.8.0_Ubuntu_16.10_amd64.deb` on Ubuntu 16.10.

```
libqt5script5 is already the newest version (5.6.1+dfsg-2build1~3).
qtscript5-dev is already the newest version (5.6.1+dfsg-2build1~3).
libqt5scripttools5 is already the newest version (5.6.1+dfsg-2build1~3).

orschiro@x230:~$ sudo dpkg -i Downloads/copyq_2.8.0_Ubuntu_16.10_amd64.deb 
Selecting previously unselected package copyq.
(Reading database ... 412436 files and directories currently installed.)
Preparing to unpack .../copyq_2.8.0_Ubuntu_16.10_amd64.deb ...
Unpacking copyq (2.8.0) ...
dpkg: dependency problems prevent configuration of copyq:
 copyq depends on qtscript5; however:
  Package qtscript5 is not installed.

dpkg: error processing package copyq (--install):
 dependency problems - leaving unconfigured
Processing triggers for bamfdaemon (0.5.3+16.10.20160929-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for gnome-menus (3.13.3-6ubuntu4) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu1) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.15-1) ...
Errors were encountered while processing:
 copyq
```

**Comment by hluk** [comment]
I fixed the dependencies. Try installing the package again.

BTW, you can add package repository to Ubuntu with following commands.

```bash
ubuntu_version=$(lsb_release -s -r)
repo_url="http://download.opensuse.org/repositories/home:/lukho:/copyq/xUbuntu_$ubuntu_version"
sudo add-apt-repository "deb $repo_url ./"
wget -q -O - "$repo_url/Release.key" | sudo apt-key add -

sudo apt update
sudo apt install copyq
```

**Comment by orschiro** [comment]
Worked, thank you. :-)

**Comment by GlebWork** [comment]
Worked for me, thanks!
