### ISSUE TITLE
Double click item paste to current window no longer works

### ISSUE THREAD

**Issue by JeremyWW** [hluk/CopyQ#588]
As per title. This is broken in 2.8.0.

**Comment by hluk** [comment]
Works fine for me. What is the OS? Which package did you install?

**Comment by JeremyWW** [comment]
Windows 10, so just the Windows setup download. Tried it twice now and it 
fails to paste. Rolled back to 2.7.1.

**Comment by hluk** [comment]
I don't have issue with pasting. Do you use any commands that override Enter/Return key?

Did you enable all options in History config tab under "After item is activated..." group?

**Comment by JeremyWW** [comment]
Let me play with it again and get back to you.

**Comment by hluk** [comment]
Thanks, that would help a lot. Please also check if the problem occurs when pasting to other applications.

BTW, new version of CopyQ uses new Qt libraries and is build with different compiler - this all can change some behavior and break some things.

**Comment by hluk** [comment]
OK, I was wrong the selection buffer really contains image after making selection in Calc.

**Comment by JeremyWW** [comment]
I have 'Close main window' and 'Paste to current window' checked. No commands that override Enter/Return. I have a hotkey 'Alt V' to bring up CopyQ at the cursor. I just did a clean install and the first time I double clicked an item it pasted, thereafter nothing will paste. Tried the browser (Chrome), a plain text document, Word document and an email. No joy. Makes no difference if I double click with the mouse or hit Enter/Return. By the way, I don't understand your last reply above.

**Comment by hluk** [comment]
> By the way, I don't understand your last reply above.

Sorry I replied to wrong issue (comment removed).

**Comment by hluk** [comment]
You can try overriding the default action on items (Enter key press and double-click). Following command helped in #562 (copy/paste the code below to command list in Command dialog <kbd>F6</kbd>).

```ini
[Command]
Command="
    copyq:
    hide()
    var text = input()
    copy(text)
    paste()"
Icon=\xf0ea
InMenu=true
Input=text/plain
Name=Paste as Plain Text
Shortcut=enter
```

**Comment by m4r71n** [comment]
After updating to 2.8.0 I've experienced the same issue. All options under `After item is activated...` are enabled. I've no problems with the `Paste as Plain Text` command and the default action on items (Enter key press and double-click) is not overridden.
Pasting to Notepad++ fails almost every time. Pasting to Firefox works better but fails also sometimes.

**Comment by JeremyWW** [comment]
I won't be able to play around with this any more until Monday 
unfortunately. I'll try the code then if no solution comes to light before 
then.

**Comment by hluk** [comment]
I just fixed issue that the old clipboard is pasted - it's currently in "windows-fixes" branch - perhaps this is related.

**Comment by m4r71n** [comment]
@hluk Thank you very much
For me the issue is gone with https://ci.appveyor.com/project/hluk/copyq/build/1.2.512/job/0n0gw0ghxp4fv4vl/artifacts

**Comment by JeremyWW** [comment]
I can't install this. Various dll's missing...

**Comment by hluk** [comment]
I'll try to release v2.8.1 soon.

**Comment by JeremyWW** [comment]
2.8.1 works fine. Issue resolved. Thanks.
