### ISSUE TITLE
system tray icon on gnome

### ISSUE THREAD

**Issue by kimlop** [hluk/CopyQ#589]
![screenshot from 2016-11-26 20-23-38](https://cloud.githubusercontent.com/assets/7025031/20643965/147971c4-b427-11e6-9e83-1e460f8b747e.png)

there is a problem with the system tray icon on gnome, I think that it looks too big

**Comment by Sadi58** [comment]
With so many options in the **Preferences...**, I think, sytem tray icon can also be included in the **Appearance** tab with **mono-dark**, **mono-light**, and **color** options.

**Comment by hluk** [comment]
Icons for tray are installed as `/usr/share/icons/hicolor/scalable/apps/copyq-*.svg`.

It should be possible to create light versions in `/usr/share/icons/ubuntu-mono-light/scalable/apps/` (similarly for dark version).

The original icon is created in Inkscape. Maybe the format is not compatible with whatever the tray uses and it fails to parse the icon size properly.

Does it help if you re-convert the icon using following command?

```sh
convert -background none /usr/share/icons/hicolor/scalable/apps/copyq-normal.svg{,}
```

**Comment by hluk** [comment]
Cau you test this with `copyq-2.8.2-beta` package? Packages are [here](http://download.opensuse.org/repositories/home:/lukho:/copyq/). It should install icons in PNG format too.

**Comment by kimlop** [comment]
thanks, now the icon look perfect on Gnome Ubuntu 16.04 on a 4k screen (standard colored version, not dark).

**Comment by hluk** [comment]
Glad to hear that it's working.

I'm willing to include monochromatic versions of the app icons in official packages. If anyone is up to the job the icons that needs to be modified are:
- https://github.com/hluk/CopyQ/blob/master/src/images/icon.svg
- https://github.com/hluk/CopyQ/blob/master/src/images/icon-running.svg
