### ISSUE TITLE
Keeping items when changing number of items in history

### ISSUE THREAD

**Issue by pihentagy** [hluk/CopyQ#592]
I had 10000 for "maximum number of items in history", and above 4000 items. I thought it is a good idea to limit items to 1000. After setting the new limit, and restarting copyq, I have only 1000 items in the history, but the items are not the most recent 1000. I expected that the most recent items will remain.

using version 2.8.0

**Comment by hluk** [comment]
Oops, sorry if you lost some important data. I've never noticed this could happen. I will fix this ASAP.
