### ISSUE TITLE
Untranslated strings

### ISSUE THREAD

**Issue by Stabb1** [hluk/CopyQ#596]
Just finnished the Norwegian translation a couple of days ago and got the translation implemented in the latest build (2.8.1).  Upon inspecting and correcting typos and making some minor changes I realized that there are some strings that are not open for translation and still appears in English.  I might be pedantic, but to me the translation therefore appears somewhat 'half-done' some places.

Would it be possible to make these strings translatable as well?  Here's the list of the strings I've found:

 - **Clipboard Content** and **Item Content** dialog '_Close_' button and right pane (Content) context menu '_Copy_', '_Select All_' buttons.

- **Commands** dialog '_Ok_', '_Cancel_' and '_Apply_' buttons.
- **Commands** -> **Unsaved Changes** dialog '_Save_', '_Discard_' and '_Cancel_' buttons.
- **Commands** -> syntax-info window '_Close_'-button
- **Commands** -> Command-pane  context menu '_Undo_', '_Redo_', '_Cut_', '_Copy_', '_Paste_', '_Delete_' and '_Select All_' menu-items.

- **Choose Icon** dialog '_Ok_' and '_Cancel_' buttons.
- **New Tab** and **Rename Tab** dialog '_Ok_' and '_Cancel_' buttons.
- **Remove Tab** dialog '_Yes_' and '_No_' buttons.

- **Action** dialog '_Ok_', '_Save_' and '_Cancel_' buttons.
- **Action** dialog -> top and bottom pane context menu '_Undo_', '_Redo_', '_Cut_', '_Copy_', '_Paste_', '_Delete_' and '_Select All_' menu-items.

- **Configuration** -> **Items** -> **Data** Left Pane (Active Formats) context menu '_Undo_', '_Redo_', '_Cut_', '_Copy_', '_Paste_', '_Delete_' and '_Select All_' menu-items.
- **Configuration** -> **Appearance** -> **Select Font** and **Select Color** - _all text_. 
- **Configuration** -> **Shortcuts** -> **New Shortcut** dialog '_Cancel_' button.
- **Confiruration** dialog '_Reset_', '_Ok_', '_Cancel_' and '_Apply_' buttons.

- **About CopyQ** '_Close_' button.
- **CopyQ Log** '_Close_' button.
- **Exit CopyQ** confirmation dialog '_Yes_' and '_No_' buttons

**Comment by hluk** [comment]
Thanks for the translation!

Most of the dialog button and some default actions should have translation provided by Qt library. I may have installed translation incorrectly for the new version of the library.

I'll try to fix that and check what is untranslated. Thanks again.

**Comment by hluk** [comment]
OK, for Windows it should be fixed [here](https://ci.appveyor.com/project/hluk/copyq/build/1.2.553/job/0ajdd1puvju458w5/artifacts) (commit 400dab151f851d512ad986a3f362915d43b6b6bd).

**Comment by Stabb1** [comment]
Thanks Lukas - that was swift :) 👍
