### ISSUE TITLE
Stack push pop functionality?

### ISSUE THREAD

**Issue by BdSherman** [hluk/CopyQ#597]
Hello,

Does CopyQ have the capability to push the clipboard history onto a stack and then pop the most recent with a hotkey and paste that entry into the active field? I have been using software called Qclip which is an older program that no longer works well with windows 10 and I am in desperate need for a replacement which can do this.

Thanks for your time!

**Comment by hluk** [comment]
How about using following commands? Just copy/paste the code below to command list in Command dialog <kbd>F6</kbd> and assign shortcuts for each command -- one copies selected text to stack and other pastes text from stack (this uses special tab "Stack" to store the texts).

```ini
[Commands]
1\Name=Push Item
1\Command="
    copyq:
    tab('Stack')
    copy()
    var text = clipboard()
    add(text)"
1\Icon=\xf078
1\GlobalShortcut=ctrl+shift+c
2\Name=Pop Item
2\Command="
    copyq:
    tab('Stack')
    var text = read(0)
    copy(text)
    paste()
    remove(0)"
2\Icon=\xf077
2\GlobalShortcut=ctrl+shift+v
size=2
```

**Comment by waseemv** [comment]
Hi hluk,

Can we make this work for multiple images (currently only works for text).

> How about using following commands? Just copy/paste the code below to command list in Command dialog F6 and assign shortcuts for each command -- one copies selected text to stack and other pastes text from stack (this uses special tab "Stack" to store the texts).
> 
> ```ini
> [Commands]
> 1\Name=Push Item
> 1\Command="
>     copyq:
>     tab('Stack')
>     copy()
>     var text = clipboard()
>     add(text)"
> 1\Icon=\xf078
> 1\GlobalShortcut=ctrl+shift+c
> 2\Name=Pop Item
> 2\Command="
>     copyq:
>     tab('Stack')
>     var text = read(0)
>     copy(text)
>     paste()
>     remove(0)"
> 2\Icon=\xf077
> 2\GlobalShortcut=ctrl+shift+v
> size=2
> ```

**Comment by hluk** [comment]
I've update the commands to support images (and other formats) and it is now available in the command repository: [Push/Pop Items](https://github.com/hluk/copyq-commands/blob/master/Global/README.md#pushpop-items) (see [README.md](https://github.com/hluk/copyq-commands/blob/master/README.md) for details on how to add the command)

**Comment by DiagonalArg** [comment]
Thanks, @lizyn - very helpful.

This seems to work for me, though is it normal that to paste, I have to use eg. 'ctrl+alt+v' followed by 'ctrl+v'?  Or 'ctrl+alt+shift+v' followed by 'ctrl+v'?  It seems the Pop/Pull commands are somehow "staging" the paste, after which we need to paste; though I don't see the "staged" paste being moved to the "clipboard" tab.
