### ISSUE TITLE
Data items in history

### ISSUE THREAD

**Issue by JeremyWW** [hluk/CopyQ#599]
Even with 'Data' unchecked in 'Items', these are still appearing in history. v2.8.1

**Comment by hluk** [comment]
Can you post which formats these items contain? (Use <kbd>F4</kbd> shortcut to list the formats for selected item.)

**Comment by JeremyWW** [comment]
Screenshot attached:
![2016-12-14_000137](https://cloud.githubusercontent.com/assets/544340/21164423/b2947536-c190-11e6-8f1b-049daf72871e.png)
They all come up as text/plain

**Comment by hluk** [comment]
Usually if you copy files in file manager the path is copied as text (though this may be done by Qt) so that you can paste it in editor or console.

You could ignore those items by adding "Ignore copied files" command in Command dialog <kbd>F6</kbd>.

If that doesn't work, use following modified version (copy/past to command list in Command dialog).

```ini
[Command]
Automatic=true
Icon=\xf06a
Match=^file:///
Name=Ignore copied files
Remove=true
```

**Comment by JeremyWW** [comment]
Thanks. I'll try 'Ignore Copied Files' and see how it goes.

**Comment by JeremyWW** [comment]
The installed 'Ignore copied files' doesn't work. Your modified version did work. Sorry for the delay in confirming.

**Comment by JeremyWW** [comment]
I have to open this again. I do not want copied files appearing in history and currently no solution works - this includes unchecking 'Data' in 'Items' (Preferences) and using 'Ignore Copied Files' as above.

**Comment by hluk** [comment]
Where do you copy the files from and what is the content of the items in CopyQ? (You can inspect the content of selected item with F4 key.)

**Comment by JeremyWW** [comment]
I'm copying a word document from one network location to another. Content is file://diskstation/public/Jem Public/2018/UK INVOICE TEMPLATE.docx (text/plain)

**Comment by hluk** [comment]
I think you can remove one slash character from the Match field from the command above to fix that.

```ini
[Command]
Automatic=true
Icon=\xf06a
Match=^file://
Name=Ignore copied files
Remove=true
```

**Comment by JeremyWW** [comment]
Ah yes. Should have spotted that! Thanks.
