### ISSUE TITLE
The application “CopyQ.app” can’t be opened.

### ISSUE THREAD

**Issue by vitaly-zdanevich** [hluk/CopyQ#602]
![screen shot 2016-12-16 at 10 25 07](https://cloud.githubusercontent.com/assets/3514015/21254959/f92dbc6a-c379-11e6-8667-34a3be89aa7c.png)

Sierra.

**Comment by ousui** [comment]
I can open it~

**Comment by ousui** [comment]
try https://github.com/hluk/CopyQ/releases/download/v2.8.2-beta-1/CopyQ.dmg

**Comment by vitaly-zdanevich** [comment]
thank you, now I started it - but nothing changed - I do not see the new icon - but I see app in ram

**Comment by ousui** [comment]
You can found the log file at `~/Library/Application Support/CopyQ/` and some other files is 
`~/Library/Application Support/copyq.log*`

**Comment by hluk** [comment]
@vitaly-zdanevich Is this still an issue? Can you try to use [these installation instructions](https://github.com/hluk/CopyQ#os-x) instead?
