### ISSUE TITLE
Windows 10: "Paste clipboard as plain text" often fails

### ISSUE THREAD

**Issue by pawelkuras** [hluk/CopyQ#604]
Recently moved to Windows 10 (same issue doesn't exist in Windows 7) and found that a global shortcut for "Paste clipboard as plain text" works occasionally, but often fails with the below error:

Command “copyq: var text = clipboa…pySelection(text) paste()”
Exit code: 1
CopyQ Warning [2016-12-19 12:45:20.329]: Ignoring configuration in "C:/Program Files (x86)/CopyQ/config" (https://github.com/hluk/CopyQ/issues/583). 
CopyQ ERROR [2016-12-19 12:45:40.436]: Error: Failed to set clipboard! 
CopyQ ERROR [2016-12-19 12:45:40.436]:     
CopyQ ERROR [2016-12-19 12:45:40.436]:    --- backtrace --- 
CopyQ ERROR [2016-12-19 12:45:40.436]:    <eval>() at 3 
CopyQ ERROR [2016-12-19 12:45:40.436]:    eval([object Object]) at -1 
CopyQ ERROR [2016-12-19 12:45:40.436]:    <global>() at -1 
CopyQ ERROR [2016-12-19 12:45:40.436]:    --- end backtrace --- 

---
copyq:  
var text = clipboard()
copy(text)
copySelection(text)
paste()
---
---

**Comment by hluk** [comment]
What could work better here is replacing

```js
copy(text)
```

with

```js
execute('clip', undefined, text)
```

in the "Paste clipboard as plain text" command.

**Comment by pawelkuras** [comment]
I am no longer getting the error, but the pasted content is not plain text.

**Comment by hluk** [comment]
Maybe there needs to be a small interval after `clip` so it can properly set clipboard. Or simply it also fails -- you can check exit status with following.

```js
var r = execute('clip', undefined, text)
if (r.exit_code != 0)
  popup("Copy Failed", r.stdout + r.stderr)
```

Another way to handle this is to try to set clipboard few more times (because `copy()` fails if another process sets or blocks clipboard):

```js
var retries = 3;
for (var i = 0; i < retries; ++i) {
  try {
    copy(text)
    break
  } catch(e) {
  }
}
```

**Comment by pawelkuras** [comment]
In the end what resolved this for me was reverting back to version 2.7.1.

**Comment by pawelkuras** [comment]
At first it seemed like 2.7.1 resolved this, but it didn't, it just happened less frequently.  If you paste 2 times one right after the other (using "Paste clipboard as plain text" shortcut), it seems to fail most of the time.

**Comment by hluk** [comment]
Is the issue still `Error: Failed to set clipboard`? What is your workflow? Maybe it would be better to remove any rich text from clipboard automatically with a command.

**Comment by Clemens-Ratte-Polle** [comment]
i have the same problem with this command :(
Workaround: Edit, mark all and Click the "Erase Style" button.
https://github.com/hluk/CopyQ/issues/772#issue-253021543
