### ISSUE TITLE
How do I debug occasional crashes?

### ISSUE THREAD

**Issue by orschiro** [hluk/CopyQ#605]
Dear all, 

The latest version periodically crashes on Ubuntu 16.10.

Often, I don't notice it until I am missing the functionality and then I notice that the tray icon is no longer showing up, which tells me that it had crashed. 

How can I debug why CopyQ is suddenly crashing? 

This did not happen in the past. 

Yours,

-Robert

**Comment by hluk** [comment]
With release version of the app you can probably only get partial info about the crash.

See if there was a recent crash of `copyq` process.

```sh
coredumpctl list
```

Get stack trace of a crash from the list.

```sh
coredumpctl info [PID_FROM_LIST]
```

I recently fixed some critical bugs so you can test this with [latest build](http://download.opensuse.org/repositories/home:/lukho:/copyq/xUbuntu_16.10/amd64/copyq_2.8.1.r10.g4931e708_amd64.deb) (I enabled debugging info for those so it could give better stack trace).

**Comment by orschiro** [comment]
Thanks you for the latest build! :-)

I am currently testing it and it hasn't crashed yet. 

Yours,

-Robert

**Comment by Brottweiler** [comment]
I am getting random periodic crashes aswell today. This happened some time ago, stopped happening, and started happening today. 

The above information made me able to find this coredump from today;

```sh
           PID: 2138 (copyq)
           UID: 1000 (brott)
           GID: 1000 (brott)
        Signal: 11 (SEGV)
     Timestamp: Thu 2017-01-05 11:34:52 CET (3h 5min ago)
  Command Line: copyq
    Executable: /usr/bin/copyq
 Control Group: /user.slice/user-1000.slice/session-c1.scope
          Unit: session-c1.scope
         Slice: user-1000.slice
       Session: c1
     Owner UID: 1000 (brott)
       Boot ID: 5e264106882c4d0eae176bdace782e09
    Machine ID: 6465c58d0fda4d76bca856d45cec1a01
      Hostname: noname
       Storage: /var/lib/systemd/coredump/core.copyq.1000.5e264106882c4d0eae176bdace782e09.2138.1483612492000000000000.lz4
       Message: Process 2138 (copyq) of user 1000 dumped core.
                
                Stack trace of thread 2138:
                #0  0x00007fd2ed1c5250 n/a (n/a)
```

It crashed once, I restarted it. Crashed, I rebuilded it then it crashed again. Then I started it in a terminal to see if there was a error or crash message, it hasn't crashed yet.

I updated my archlinux packages today, if that is relevant:

```sh
[2017-01-05 08:54] [ALPM] upgraded archlinux-keyring (20161201-1 -> 20170104-1)
[...]
[2017-01-05 08:55] [ALPM] upgraded gdk-pixbuf2 (2.36.2-1 -> 2.36.3-1)
[2017-01-05 08:55] [ALPM] upgraded python3-memoizedb (2016.5-1 -> 2017-1)
[2017-01-05 08:55] [ALPM] upgraded python3-xcpf (2016.11-1 -> 2017-1)
[2017-01-05 08:55] [ALPM] transaction completed
[2017-01-05 08:55] [ALPM] running 'gdk-pixbuf-query-loaders.hook'...
```

**Comment by hluk** [comment]
@Brottweiler Does `~/.local/share/copyq/copyq/copyq.log` contain any errors or warnings?

If you can build the app use `cmake -DCMAKE_BUILD_TYPE=Debug ...` so coredump has a readable stack trace.

**Comment by Brottweiler** [comment]
@hluk 

```sh
CopyQ ERROR [2017-01-05 11:34:48.820]: QLocalSocket: Socket operation timed out
CopyQ ERROR [2017-01-05 11:34:52.820]: Failed to read message from client!
```

After I started it in terminal, and it didn't crash, I started it using "rofi" which is the program I use to launch stuff. It hasn't crashed again. Just those few crashes then it stopped.

I will build CopyQ using that cmake option, and I'll get back to you I suppose if it crashes again.
