### ISSUE TITLE
QLocalSocket: Socket operation timed out

### ISSUE THREAD

**Issue by ousui** [hluk/CopyQ#606]
When I have an screenshot with cmd+shift+ctrl, copyq have these exception

```
CopyQ ERROR [2016-12-20 16:51:25.089]: QLocalSocket: Socket operation timed out
CopyQ ERROR [2016-12-20 16:51:25.576]: QLocalSocket: Socket operation timed out
CopyQ ERROR [2016-12-20 16:51:26.064]: QLocalSocket: Socket operation timed out
CopyQ ERROR [2016-12-20 16:51:26.549]: QLocalSocket: Socket operation timed out
......
```

and every application gui blingbling.

The version is 2.8.1, and macos 10.12.2

**Comment by m4r71n** [comment]
@ousui this sounds like #603

**Comment by hluk** [comment]
Yup, should be fixed. You can use [this version](https://github.com/hluk/CopyQ/releases/download/untagged-ecd4b0d73ac9170ef5cf/CopyQ.dmg).

**Comment by ousui** [comment]
Thank you!
