### ISSUE TITLE
Icons in the main window and menus looks strange

### ISSUE THREAD

**Issue by SchweinDeBurg** [hluk/CopyQ#607]
![copyq](https://cloud.githubusercontent.com/assets/2083917/21419481/ec4f144e-c838-11e6-8ee5-bc3b157ce059.png)

**Comment by hluk** [comment]
Can you check log <kbd>F12</kbd> for any warnings or errors? It seems that icon font (FontAwesome) was not loaded correctly.

**Comment by hluk** [comment]
Closing. Need more info.
