### ISSUE TITLE
Can add new option to hide sync-basename? 

### ISSUE THREAD

**Issue by ousui** [hluk/CopyQ#608]
When I use synchronize for a tab, it have some file name like copyq_000* in the title.
Can them hide?

![image](https://cloud.githubusercontent.com/assets/2839512/21419658/e5381ed2-c863-11e6-8620-4c7dd9b25d04.png)

**Comment by hluk** [comment]
The generated names like `copyq_0001` will be hidden in next version.

I also removed some unimportant texts from items which contains notes, tags or synced file name so the some special items not too big.
