### ISSUE TITLE
Drag'n'drop from Copyq doesn't work

### ISSUE THREAD

**Issue by GlebWork** [hluk/CopyQ#610]
Also I can't paste images from clipboard to Skype Alpha

p.s. As far as I remember - it should work

Ubuntu 16.04.1
Copyq 2.8.1 (with last updates)

**Comment by hluk** [comment]
Can you try drag'n'drop while holding <kbd>Ctrl</kbd>?

**Comment by GlebWork** [comment]
No it doesn't work. But now clipboard works (at least CopyQ doesn't crash when I try to save an image)

**Comment by hluk** [comment]
I just found out that some web page text fields in Chromium web browser need images to be stored in files on disk (Firefox doesn't require this) -- same issue with some Dolphin file browser.

I'll try to solve this by storing image in a temporary file and passing path as `text/uri-list` MIME for drag'n'drop.

**Comment by GlebWork** [comment]
Thank you!

**Comment by hluk** [comment]
I didn't test this for Skype (it's fixed for Chromium and Dolphin). Please reopen if the issue is not fixed after new version is released. I'll try to release it soon.

**Comment by GlebWork** [comment]
I've got some update today via repository - it works with Skype via drag'n'drop and from clipboard. Excellent!

**Comment by hluk** [comment]
Great! Thanks for quick feedback.
