### ISSUE TITLE
Text not showing correctly in the internal editor

### ISSUE THREAD

**Issue by et2010** [hluk/CopyQ#612]
When I try to edit an item with the internal editor, the text is not showing correctly. Instead, it looks like this:

![copyq_editor_not_working](https://cloud.githubusercontent.com/assets/11584902/21556226/d0ee8f6e-ce59-11e6-98ba-2757a1bafb6b.png)

The text in the snapshot is actually "text not showing correctly", but ends up like this. Any idea what is causing this? Thanks!

#### system info
Archlinux
copyq 2.8.1-1
copyq-plugin-itemweb 2.8.1-1

**Comment by scottkosty** [comment]
does it show correctly in the tray? What formats does it have (press f4 from the copyQ main window to see).

**Comment by et2010** [comment]
Yes it shows correctly anywhere else, and the format is `text/plain`:

![image](https://cloud.githubusercontent.com/assets/11584902/21568490/19f8a21c-cef0-11e6-9c17-a4f4c5fa351a.png)

**Comment by hluk** [comment]
Can you check if font for editor is a valid one? (It's in "Appearance" config tab in config dialog <kbd>Ctrl</kbd>+<kbd>P</kbd>.)

**Comment by et2010** [comment]
Yes, the default font (in my case, "AkurutiMal1 Normal") for the editor is the culprit. After setting the default font to "Arial", it was fixed. Thanks!

**Comment by hluk** [comment]
Oops, I just noticed that fresh session of CopyQ has this font set as default. I'll fix this.
