### ISSUE TITLE
Show main window under the mouse cursor after holding right mouse button for some time

### ISSUE THREAD

**Issue by Droyk** [hluk/CopyQ#614]
You are about to read some bad English and I am really sorry about it I am not a native English speaker.

Good evening developer @hluk 
First of all I want to thank you for creating a really good clipboard manager but it still fall short on many things but this time I want to talk about a feature that will really come handy to many users 

I want you to implement a feature to show the copyQ window under the mouse cursor when a user click right click mouse button for certain milliseconds (user will decide how much time they want to hold down the right click button for).

thanx for reading it.

**Comment by ZIEXED** [comment]
u mean the context menu list with last x items in the tab? this will be Awesome!

**Comment by hluk** [comment]
This could be probably quite complicated to implement on most platforms.

If there is a software that can map such shortcuts to a custom command you can make it run `copyq menu`.

**Comment by ZIEXED** [comment]
Didn't know about the menu command, thank you :)
(used autohotkey to assign this to shift+v)
it will be great if the list contained only the items without any other option, as the menu is distractingly quite long

**Comment by hluk** [comment]
@ZIEXED Yeah the menu gets huge especially if you have many custom commands. You can remove the command menu items in "Tray" config tab by disabling "Show commands for clipboard content".

I'll try to remove some of the application menu items and keep only the most important.

**Comment by ZIEXED** [comment]
You can remove every thing from the menu when it caled from the command except for the clipboard items
So the menu size would depend only on your config "Number of items in tray menu"
or if u don't want to remove them maybe a "itemsmenu" command or something to do that? (bring only the Citems)

**Comment by hluk** [comment]
I just fixed and improved the `menu()` function so you can specify a tab and number of items. There are no other menu items unless you invoke `menu()` without arguments.

E.g. show menu with 20 items from "clipboard" tab:

```js
menu('clipboard', 20)
```

**Comment by ZIEXED** [comment]
Great! can u compile it :)

**Comment by hluk** [comment]
@ZIEXED [Windows](https://ci.appveyor.com/project/hluk/copyq/build/job/n8lhks3b219j5qjl/artifacts)?

**Comment by ZIEXED** [comment]
Yep, portable :+1:

**Comment by ZIEXED** [comment]
I tested it and it works great :)

**Comment by Droyk** [comment]
Hey sorry for not being active on the discussion guys I want to know what happened to the feature did it got implemented @ZIEXED you tried it what happened will you be able to elaborate it. @hluk

**Comment by ZIEXED** [comment]
@Droyk test [this ](https://ci.appveyor.com/api/buildjobs/xh621veaayinvl30/artifacts/copyq-v2.9.0-15-gd242a926.zip)build 
You can call CopyQ "tabname" "number of items"
_tab name is case sensitive_

**Comment by Droyk** [comment]
@ZIEXED I am talking about the feature I wrote above did it got implemented 
>Implement a shortcut to show CopyQ window under the mouse cursor on holding down rightclick for certain millisecond

**Comment by ZIEXED** [comment]
>  hluk commented 2 days ago
> 
> This could be probably quite complicated to implement on most platforms.
> 
> If there is a software that can map such shortcuts to a custom command you can make it run copyq menu.

**Comment by Droyk** [comment]
@ZIEXED that's sad I really wanted this clipboard manager to get this feature off course I know about autohotkey but I wanted this feature to get implemented 😢

**Comment by hluk** [comment]
@Droyk There is no simple way to implement this. I would need to write code separately for each platform (and I cannot even test it on all platforms).

One of main features of the app is that it can be used from other utilities. If AutoHotkey supports this feature you can simply call `C:\PATH\TO\COPYQ\copyq.exe menu` to show the menu with clipboard.

**Comment by Qwash** [comment]
I noticed in the latest builds the Enable/Disable clipboard sorting removed from the main tray menu
Please let users consider if they want it back from the main app Settings under "Tray" tab

**Comment by hluk** [comment]
@Qwash I've re-added the tray menu item to enable/disable clipboard storing.

**Comment by hluk** [comment]
I'm dropping this. It's not easy to implement for all platforms.
