### ISSUE TITLE
2.8.1, Windows 7: clipboard tab will not load from time to time 

### ISSUE THREAD

**Issue by royharoush** [hluk/CopyQ#619]
hi, 
im using copyq 2.8.1 (release). I'm using the portable version. 
From time to time copyq will stop displaying the content of the clipboard default tab.

it looks like that : 

![image](https://cloud.githubusercontent.com/assets/8113056/21850955/c011ca60-d815-11e6-8133-634c836460c3.png)

any idea what could be causing this ? 

Thanks,
Roy

**Comment by hluk** [comment]
Does this mean that when you restart the application the items are sometimes loaded correctly?

Can you share your log (<kbd>F12</kbd> shortcut)?

**Comment by royharoush** [comment]
Hi,
i can't really explain it, but usually i have to restart my computer (?-_-?) to fix this issue. 
i've reverted back to 2.7.1 for now. 
also, this could be an issue with a policy of my employer, since this is the first time im seeing it, and it's only only on my work computer
see attached. some information was redudcted (username, tab name, etc).
[copyqerrors.txt](https://github.com/hluk/CopyQ/files/701155/copyqerrors.txt)

**Comment by hluk** [comment]
Is the portable folder readable/writable for current user (especially `config\copyq\copyq_tab_*.data` files)?

Moving CopyQ to another location may solve the issue.

It's strange that this works with version 2.7.1 -- maybe the new Qt libraries (used in 2.8.x versions) causes this.

**Comment by royharoush** [comment]
there are no issues with the file permissions on this folder (under my user profile, i can "view" the file's contents outside of copyq). 
i'm using the portable version (not the installer). 
this just happened again, and i restarted, and it was resolved :| 
strange behavior indeed.

**Comment by hluk** [comment]
I've improved save/load functionality and logging. [Here](https://ci.appveyor.com/project/hluk/copyq/build/job/tqltwxbkgyfw47id/artifacts) is Windows build.

Can you test it and see if there are any warnings/errors in log?

**Comment by royharoush** [comment]
This version does seem to fix the issue.
Thanks !
