### ISSUE TITLE
CopyQ window persists on screen, does not toggle

### ISSUE THREAD

**Issue by cvarrick** [hluk/CopyQ#620]
`:~$ copyq -v
CopyQ Clipboard Manager v2.8.1 (hluk@email.cz)
Built with: Qt 5.7.1, LibQxt 0.7.0
`
Fresh install, no modifications to config.

After launch, window is never hidden. selecting an item has no effect.

`copyq hide` returns nothing and has no effect.

`copyq  toggle`  returns 'true' but has no effect.

**Comment by hluk** [comment]
What's the OS and window manager?

Some tiling window managers cannot minimize windows -- show/hide minimizes main window by default when tray is unavailable. There is option to override this behavior and hide the window instead -- enable "Hide main window" in "Layout" config tab.

**Comment by cvarrick** [comment]
This solves the issue.

Window manager is tiling (dwm), I just forget to apply that setting.
Thanks!
