### ISSUE TITLE
Search dialog window for clipboard history?

### ISSUE THREAD

**Issue by orschiro** [hluk/CopyQ#621]
Dear all, 

How would one be able to create a dialog window to search through the entire clipboard history, find an entry based on the item's content and paste it into the current selection?

I imagine a window like this:

![image](https://cloud.githubusercontent.com/assets/170947/21883511/daf2dc26-d8af-11e6-87ba-0b36408bd771.png)

**Comment by hluk** [comment]
Why not use the built-in search?

**Comment by orschiro** [comment]
Maybe I just haven't found it yet. :-)

How do I use it?

Let's say I am inside this composing text box and want to paste something from my clipboard history. 

How would I do that without having to open CopyQ's window?

**Comment by hluk** [comment]
You need to open main window to use the built-in search. Why is that a problem? Why is it better to open simple dialog for searching?

**Comment by hluk** [comment]
Here is the command just to prove it's possible :).

```ini
[Command]
Command="
    copyq:
    // Read search history tab.
    tab('Search')
    var history = ['', '']
    
    for (var i = 0; i < count(); ++i) {
      var text = str(read(i))
      history.push(text)
    }
    
    // Ask user for search expression (case insensitive).
    var what = dialog('.title', 'Search and Paste', 'Search', history)
    if (!what)
      abort()
    
    add(what) // Store new search to history tab.
    
    what = str(what).toLowerCase()
    
    // Tab to search.
    var tab_name = config('clipboard_tab')
    if (!tab_name)
      tab_name = tab()[0]
    tab(tab_name)
    
    // Search and paste if found.
    for (var i = 0; i < count(); ++i) {
      var text = str(read(i)).toLowerCase()
      if (text.indexOf(what) != -1) {
        copy(text)
        paste()
        abort()
      }
    }
    
    popup(
      'Search failed!',
      'Item containing \"' + what + '\" was not found.')"
GlobalShortcut=ctrl+shift+f
Icon=\xf002
Name=Search and Paste
```

**Comment by orschiro** [comment]
Wow, this is great! :-)

Thank you so much.

One question:

Example content from my clipboard history: `{"bonus":60}`

If I run the command and begin to type `bonus`, can it auto-complete to match the content of my history?

This would be useful, for instance, if I have two entries `{"bonus":60}` and `{"bonus":120}`, and want to distinguish which of the two to import.

**Comment by hluk** [comment]
It will autocomplete previously searched text but not an item text. For better search functionality you have to search in main window.

**Comment by orschiro** [comment]
OK! Then I am good for now. Thanks! :-)

**Comment by orschiro** [comment]
I found a problem. 

It pastes all content as lower case. :-(

**Comment by hluk** [comment]
Oops. I fixed the command above.

**Comment by orschiro** [comment]
Works! Oh, this is so great. :-)

**Comment by hluk** [comment]
Hey! Here is improved command that opens selection dialog if search matches multiple items.

```ini
[Command]
Command="
    copyq:
    var title = 'Search and Paste'
    
    // Read search history tab.
    tab('Search')
    var history = ['', '']
    
    for (var i = 0; i < count(); ++i) {
      var text = str(read(i))
      history.push(text)
    }
    
    // Ask user for search expression (case insensitive).
    var what = dialog(
      '.title', title,
      'Search', history)
    if (!what)
      abort()
    
    add(what) // Store new search to history tab.
    
    what = str(what).toLowerCase()
    
    // Tab to search.
    var tab_name = config('clipboard_tab')
    if (!tab_name)
      tab_name = tab()[0]
    tab(tab_name)
    
    // Search items.
    var matches = []
    for (var i = 0; i < count(); ++i) {
      var text = str(read(i))
      if (text.toLowerCase().indexOf(what) != -1)
        matches.push(text)
    }
    
    // Nothing found?
    if (matches.length == 0) {
      popup(
        'Search failed!',
        'Item containing \"' + what + '\" was not found.')
      abort()
    }
    
    var match = matches[0]
    
    // If multiple items matches, show selection dialog.
    if (matches.length > 1) {
      matches.unshift(matches[0])
      match = dialog(
        '.title', title,
        '.label', 'Multiple items were found. Select one to paste.',
        '', matches)
      if (!match)
        abort()
    }
    
    // Paste matched item.
    copy(match)
    paste()"
GlobalShortcut=ctrl+shift+f
Icon=\xf002
Name=Search and Paste
```

**Comment by orschiro** [comment]
![peek 2017-01-14 13-48](https://cloud.githubusercontent.com/assets/170947/21954942/33c09526-da60-11e6-8892-0453ea0d62bd.gif)

**Comment by hluk** [comment]
Can you resize or maximize the second dialog?

BTW, I fixed the dialog size today and added list widget for custom dialogs.

**Comment by orschiro** [comment]
> Can you resize or maximize the second dialog?

No. :-(

> BTW, I fixed the dialog size today and added list widget for custom dialogs.

How do I get this update? You refer to CopyQ or just the command above?

**Comment by hluk** [comment]
New version for Ubuntu 16.04 is available [here](http://download.opensuse.org/repositories/home:/lukho:/copyq/xUbuntu_16.04/amd64/copyq_2.8.2.beta.2.r10.g3f5da98c_amd64.deb).

**Comment by orschiro** [comment]
Wow, that one fixed it and your new selection dropdown menu is just amazing! :-)

**Comment by hluk** [comment]
...and here is version of the command for new beta version with list of multiple matches instead of simple combo box.

```ini
[Command]
Command="
    copyq:
    var title = 'Search and Paste'
    
    // Read search history tab.
    tab('Search')
    var history = ['', '']
    
    for (var i = 0; i < count(); ++i) {
      var text = str(read(i))
      history.push(text)
    }
    
    // Ask user for search expression (case insensitive).
    var what = dialog(
      '.title', title,
      'Search', history)
    if (!what)
      abort()
    
    add(what) // Store new search to history tab.
    
    what = str(what).toLowerCase()
    
    // Tab to search.
    var tab_name = config('clipboard_tab')
    if (!tab_name)
      tab_name = tab()[0]
    tab(tab_name)
    
    // Search items.
    var matches = []
    for (var i = 0; i < count(); ++i) {
      var text = str(read(i))
      if (text.toLowerCase().indexOf(what) != -1)
        matches.push(text)
    }
    
    // Nothing found?
    if (matches.length == 0) {
      popup(
        'Search failed!',
        'Item containing \"' + what + '\" was not found.')
      abort()
    }
    
    var match = matches[0]
    
    // If multiple items matches, show selection dialog.
    if (matches.length > 1) {
      var i = dialog(
        '.title', title,
        '.label', matches.length + ' items were found. Select one to paste.',
        '.style', 'QListWidget{font-family:mono}',
        '.list:', matches)
      if (!i)
        abort()
      match = matches[i]
    }
    
    // Paste matched item.
    copy(match)
    paste()"
GlobalShortcut=ctrl+shift+f
Icon=\xf002
Name=Search and Paste
```

I think typing a text in the list should select the first item starting with the typed text.

**Comment by orschiro** [comment]
Yep, this is perfect! Thanks. :-)

**Comment by hluk** [comment]
Thanks for your support (as always)! :)

I'm glad I finally got to improve the `dialog()` function. I'll try to simplify setting icon for the dialogs too -- right now it can be set only from a file (e.g. '/usr/share/icons/gnome/32x32/actions/search.png').

**Comment by orschiro** [comment]
https://www.youtube.com/watch?v=_9Tc-u6IpJk&feature=youtu.be

That's software worth supporting. :-)

**Comment by hluk** [comment]
Nice! Amazing indeed. :) Thanks!

**Comment by Negirno** [comment]
The script is nice, however for me it pastes the string 'undefined' if there are more than one results.

My version is: 2.7.1.r58

**Comment by hluk** [comment]
@Negirno You need the beta version mentioned above.

**Comment by hluk** [comment]
You can use the command with [CopyQ v2.8.2](https://github.com/hluk/CopyQ/releases/tag/v2.8.2).
