### ISSUE TITLE
Failed to set global shortcut

### ISSUE THREAD

**Issue by ousui** [hluk/CopyQ#622]
The version is  https://github.com/hluk/CopyQ/releases/tag/v2.8.2-beta-2
v2.8.2-beta-1 no problem.
Macos 10.12.2
> Warning [2017-01-11 15:23:04.644]: Failed to set global shortcut "Meta+Ctrl+;" for command "Show ......".

**Comment by ousui** [comment]
Another questions is any other global shortcut is invaild.

**Comment by hluk** [comment]
Thanks for quick heads up.

I don't see any new code that can break this.

The important change is that v2.8.2-beta-1 uses Qt 5.7.0 and v2.8.2-beta-2 uses Qt 5.7.1 (can be seen in build log <sup>1</sup> <sup>2</sup>).

>Another questions is any other global shortcut is invalid.

I think that in this case global shortcut mapping fails if there is no translation to native key code. I don't see any explicit translation from `Qt::Key_Semicolon`. <sup>3</sup>

I'll try to explicitly translate the missing keys and create new beta release.

<sup>1</sup> https://travis-ci.org/hluk/CopyQ/jobs/185695295
<sup>2</sup> https://travis-ci.org/hluk/CopyQ/jobs/189459661
<sup>3</sup> https://github.com/hluk/CopyQ/blob/e159d8ec801ef39f93e943250fe5dc8345330c6b/qxt/qxtglobalshortcut_mac.cpp#L88

**Comment by hluk** [comment]
Here is package with the fix: https://github.com/hluk/CopyQ/releases/download/v2.8.2-beta-osx-global-shortcuts/CopyQ.dmg

**Comment by ousui** [comment]
I used this version copyq, and update  qt5 to 5.7.1_1, then reset the shortcut, problem solving.
