### ISSUE TITLE
Not storing clipboard in "buffer" tab.

### ISSUE THREAD

**Issue by Urvdmih** [hluk/CopyQ#624]
Win 7 x64 sp1 Pro (russian lang). 
Not storing buffer in "buffer" tab. 
In log only this errors:
CopyQ ERROR [2017-01-18 11:44:45.736]: Failed to set binary stdin.
CopyQ ERROR [2017-01-18 11:44:45.739]: Failed to set binary stdin.
I tried both version CopyQ 2.8.2 (installer and portable).
Maybe Kaspersky Antivirus to blame to this? 
I tried add program to trusted, but it did not help.

**Comment by hluk** [comment]
Do you mean that new items in "buffer" tab are not stored? Is the tab empty?

Can you check if permissions for configuration files are read/write? Configuration is in folder `%APPDATA%\copyq` for installed version of the app or `config` folder in unzipped portable version.

**Comment by Urvdmih** [comment]
> Do you mean that new items in "buffer" tab are not stored? Is the tab empty?
Yes. The tab is empty.
>Configuration is in folder %APPDATA%\copyq for installed version of the app or config folder in unzipped portable version.
I tried it and no result. 
> Can you check if permissions for configuration files are read/write? 
Tomorrow at check folder permissions with a portable version of the program. But I'm afraid it's nothing to do with.

**Comment by Urvdmih** [comment]
I checked permissions and they is ok.

**Comment by hluk** [comment]
Do you perhaps have "buffer" in list of tabs to synchronize? (It's in Configuration dialog under "Items" tab and in the first table under "Synchronize".)

If this is not set CopyQ should always log an error if it cannot save or load a tab. If it cannot load a tab there will be a refresh button instead of items like in following image.

![image](https://cloud.githubusercontent.com/assets/38054/22322955/a7d8a7bc-e39f-11e6-8c8d-572f3def3ddc.png)

**Comment by hluk** [comment]
Also check if you have "Maximum number of items in history" in "History" config tab set to a non-zero value.

**Comment by Urvdmih** [comment]
Screenshots:
![copyq_2017-01-26_14-49-05](https://cloud.githubusercontent.com/assets/9265883/22330360/ecb81e76-e3d6-11e6-89a9-09f4764b2abe.png)
![copyq_2017-01-26_14-49-14](https://cloud.githubusercontent.com/assets/9265883/22330365/f38e9072-e3d6-11e6-8eb2-f02ef5b1530c.png)

**Comment by Urvdmih** [comment]
And also I cannot to see any tab in tabs list. It's empty. For example I don't see tab "1". But at home PC (with win10) I also don't see this, but clipboard storing work there. It's strange.

**Comment by hluk** [comment]
Can you add an item manually in the tab? Then if you restart CopyQ is the item still in the tab? By empty tab list do you mean there are no tabs in tab bar when app starts or just in the configuration dialog?

If tab "&буфер" is saved there should be non-empty readable/writable data file `%ADDDATA\copyq\copyq_tab_JtCx0YPRhNC10YA=.dat` (or in `config` folder in portable version).

Can you also share the log?

**Comment by Urvdmih** [comment]
> Can you add an item manually in the tab? Then if you restart CopyQ is the item still in the tab?

I did it. Item still in the tab.

>  By empty tab list do you mean there are no tabs in tab bar when app starts or just in the configuration dialog?

Just in the configuration dialog.

**Comment by hluk** [comment]
There are too many same errors in the log file. The error should be fixed in v2.8.3.

Can you test it with v2.8.3 and check the log again for errors/warning? Also if you can set `COPYQ_LOG_LEVEL` environment variable to `DEBUG`.

(I just fixed the tab names in configuration dialog -- will be in next version.)

**Comment by Urvdmih** [comment]
I tested it with v2.8.3 and the log again with errors.

**Comment by hluk** [comment]
I just double checked and the "Failed to set binary stdin" is not printed with v2.8.3 (the text is not even in the code anymore). Are you sure you run only this version of CopyQ and the log is up to date?

**Comment by Urvdmih** [comment]
I don't understand it. I launched new version of copyq but it created log with errors. And mistakes on 02/01/17. Today 07/02/17.
[config.zip](https://github.com/hluk/CopyQ/files/756704/config.zip)

**Comment by hluk** [comment]
That seems to be an old log file (event modification data is 02/01/17).

Log is not saved in portable/unzipped folder (see bug #551) -- it should be still in `%APPDATA%\copyq`. I'll try to fix the bug soon.

**Comment by Urvdmih** [comment]
I found it. But the clipboard's tab is still empty.
[copyq.zip](https://github.com/hluk/CopyQ/files/757393/copyq.zip)

**Comment by hluk** [comment]
Do you have "Store clipboard" enabled in "General" config tab?

Do you use any automatic commands in Command dialog (<kbd>F6</kbd>)?
