### ISSUE TITLE
Translating to Russian language

### ISSUE THREAD

**Issue by mrkaban** [hluk/CopyQ#627]
Hello! I see that the translation process started the program into Russian. Need help with translation into Russian?

Thank you for your program! She added to my website in Russian and enjoys some popularity! [Link](http://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D1%83%D1%82%D0%B8%D0%BB%D0%B8%D1%82%D1%8B/%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B0/copyq-%D0%BC%D0%B5%D0%BD%D0%B5%D0%B4%D0%B6%D0%B5%D1%80-%D0%B1%D1%83%D1%84%D0%B5%D1%80%D0%B0-%D0%BE%D0%B1%D0%BC%D0%B5%D0%BD%D0%B0.html).

**Comment by hluk** [comment]
Yes, help is always welcome here. You can start translating at [Weblate](https://hosted.weblate.org/projects/copyq/master/ru/).

After a while any new translations get merged to this repository and you should be able to test it by getting [fresh Installer or portable zip](https://ci.appveyor.com/project/hluk/copyq) (you have to click on the first job and the Artifacts to get to download links).

Thanks for your support.
