### ISSUE TITLE
Associates copying to the clipboard with a sound

### ISSUE THREAD

**Issue by wetware05** [hluk/CopyQ#628]
Hi.

You need to add a command that associates copying to the clipboard with a sound. Currently I have a clipboard manager that does it, it's a standard. I would change copyq if I had this option, since it is more elegant and with more options. You are not always sure that you have done a good move with your fingers, when copying something. The associated sound confirms it, and in case it does not sound, you know you have to do it again.

Thanks in advance and congratulations on the program.

**Comment by hluk** [comment]
This was already discussed at #357. Let me know if you need more info.

**Comment by hluk** [comment]
To simplify this I've just created [Play Sound when Copying to Clipboard](https://github.com/hluk/CopyQ/wiki/Command-Examples#play-sound-when-copying-to-clipboard) section on wiki.

**Comment by wetware05** [comment]
Perfect, thank you!!!, I did not know that feature of the commands.

**Comment by Chealer** [comment]
Thank you Lukas

The more articulate ticket #1865 tracks the same issue.
