### ISSUE TITLE
Feature enhancement: "Show Preview" should not be limited and should be scroll able

### ISSUE THREAD

**Issue by royharoush** [hluk/CopyQ#629]
Hi,
The show preview is a pretty awesome feature that takes copyq in a great direction. 
Though, this feature's scroll\size is taken from the note's configuration for scroll\ size. 
see the screenshot:

![image](https://cloud.githubusercontent.com/assets/8113056/22544204/7a844508-e93c-11e6-89cb-dcb5fb48fa72.png)

this configuration is taken from this location: 

![image](https://cloud.githubusercontent.com/assets/8113056/22544250/a405f138-e93c-11e6-8336-646599bee57b.png)

in my view, the preview feature should display the entire content of the note with scrollbar, and not mirror the exact same lines limit of the note. you should also have the ability to mark text and copy it from the preview. 

Thanks ! 
Roy

**Comment by hluk** [comment]
Done. New version for Windows is [here](https://ci.appveyor.com/project/hluk/copyq/build/job/0mtw7s3167fnjl1e/artifacts).

**Comment by royharoush** [comment]
works great, Thanks ! . one thing you left out was the ability to copy from the preview pane :)

**Comment by hluk** [comment]
OK, I just fixed selection for previews. New build for Windows is [here](https://ci.appveyor.com/project/hluk/copyq/build/job/mr7e2y2aq35nl9tj/artifacts).

BTW, selection worked before same as for items in the list -- i.e. to select text in an item you need to hold Shift key so as not to move the item.
