### ISSUE TITLE
Latest version of CopyQ incompatible with Qt 5.8

### ISSUE THREAD

**Issue by ShadowKyogre** [hluk/CopyQ#630]
While I was updating my system, I recompiled copyq against my system copy of the Qt library. The binary is fine, but I'm getting this error:

~~~~
CopyQ ERROR [2017-02-05 16:33:31.038]: QtFatal: Cannot mix incompatible Qt library (version 0x50700) with this library (version 0x50800) (:0, )
~~~~

Any advice for tracking down a more specific error so I can have it back up and running?

System details:

* **Qt5 Version:** 5.8.0
* **Distro:** Arch Linux

**Comment by hluk** [comment]
You can try following:

```bash
# List installed Qt package in version 5.7.x
pacman -Q | grep 'qt.*5\.7'

# Show linked libs.
ldd ./copyq

# Show which Qt libs and plugins are being open when the app starts.
strace ./copyq |& grep 'qt.*\.so'

# Trace library calls.
ltrace -C ./copyq
```

Try to do a clean rebuild.

Same issue: #626

**Comment by ShadowKyogre** [comment]
Yup, it's exactly that same issue! I rebuilt CopyQ, but not the style plugins. Almost forgot about that when cleaning up my system.
