### ISSUE TITLE
Ignore Images size less than given length

### ISSUE THREAD

**Issue by marqqer** [hluk/CopyQ#631]
Dears all:
how can I make an automatic command to omit Image clipboard data less than given length? I have made a test but unable to set the data properly recorded,moreover the way to get length of clipboard data is less effective.
here is my test code:
```ini
[Command]
Name=\x5ffd\x7565\x5927\x5c0f\x5c0f\x4e8e\x32\x35\x36\x42yte\x7684\x56fe\x7247
Command="
    copyq:
    var itemLength = str(input()).length;
    if (itemLength >256 ){
    setItem(0,  clipboard())
    }"
Input=image/png
Automatic=true
Remove=true
Enable=false
Icon=\xf06a
```
thanks a lot.
Yours,

**Comment by hluk** [comment]
You need to use something like following (assuming that you have clipboard storing enabled and save image data).

```js
if (itemLength <= 256)
  ignore()
```

**Comment by marqqer** [comment]
Thanks a lot ! hluk, I got a workable command by set the Remove=false:
`[Command]
Name=Ignore Image Data less than 512Byte
Command="
    copyq:
    //var itemLength = str(input()).length;
    var itemLength = input().length;
    //copy(itemLength);
    if (itemLength <512 ){
        ignore();
    }"
Input=image/png
Automatic=true
Icon=\xf06a

`
but I still want  to know how to save a Image data to CopyQ history:
    if (itemLength >512 ){
           savetohistory();
    }
can you give me some advice how to achieve that?
another question, is there a more effective way to get the size of Image data rather than  input().length;?

**Comment by hluk** [comment]
The "savehistory()" bit should be:

```js
write(0, 'image/png', input());
```

(See [write()](https://github.com/hluk/CopyQ/blob/master/src/scriptable/README.md#writerow-mimetype-data-mimetype-data) API.)

You can also use `input().size()` directly without converting the bytes to string.

**Comment by marqqer** [comment]
Thank a lot  for your prompt reply!
CopyQ is a effective  tool to manipulate clipboard I think I should dig in to make full use of it .
I read through your example  Save As.ini [https://gist.github.com/hluk/64dae8b25cd21e6141dd] and got many questions, where can i find more information of the referenced functions like Dir() / currentpath() /dialog()?

**Comment by hluk** [comment]
API documentation is [here](https://github.com/hluk/CopyQ/blob/master/src/scriptable/README.md). If you have questions just write me an e-mail.

I know the API can use some improvements so if you have any suggestions or anything in API/documentation is unclear and need updating create new bug report.

Thanks!
