### ISSUE TITLE
How to set up a secondary Image editor?

### ISSUE THREAD

**Issue by marqqer** [hluk/CopyQ#632]
Hi dear hluk:
    I have set up the external Image editor and it works fine,mainwhile I want to have a secondary editor for image/png data in the context menu. I made a try to build a command as shown below:  
```
[Command]
Name=Open in MsPaint.exe
Command="
    copyq:
      currentpath(Dir().tempPath())
      var fileName = 'CopyQ-'+dateString('yyMMdd-hhmmss')+'.png'
      var f = File(fileName)
      if (!f.open()) {
        popup('Failed to open \"' + f.fileName() + '\"', f.errorString())
        abort()
      }
      var iReturn=f.write(getitem(currentitem())['image/png'])
      var strFilePath = Dir().tempPath()+ '/' + fileName
      popup('Write to file,Returned:'+iReturn)
      //strFilePath='D:/cards-heart.png'
      strFilePath=strFilePath.replace(/\\//g, '\\\\')
      open(strFilePath)
      var strEditor ='mspaint.exe'
      if (iReturn!=-1){
        execute(strEditor , strFilePath)
      }"
Input=image/png
InMenu=true
HideWindow=true
Icon=\xf296
```
But it  does not work as expected, with an error said "the temp PNG file is not a valid Image format". I have checked the temp folder found that the PNG file will not be successfully written until I close the error prompt dialog,but the iReturn(iReturn=f.write(getitem(currentitem())['image/png']) ) showed that the file writing operated successfully.
And  if I set strFilePath to an exist PNG file(strFilePath='D:/cards-heart.png' ),the execute(strEditor , strFilePath) open the file successfully.
Another question is that the generated temp file will not be deleted after the editor is closed. But use "Image editor command" (set up in "Item" config tab) the temp file will be deleted. How can I achieve this? it seems that my command workflow no one could responsible for the deleting.
Thanks a lot
Yours.

**Comment by hluk** [comment]
To get the file path with native separators with following command.

```js
var strFilePath = Dir().absoluteFilePath(fileName)
strFilePath = Dir().toNativeSeparators(strFilePath)
```

I think you need to close the file to open it in another app -- this also flushes write buffer so all data are safely written to the file.

```js
f.close()
```

Removing the temporary file can be problematic if the `execute()` is not blocked until program finishes.

I guess you could clean up the temporary files before creating new one.

```js
currentpath(Dir().tempPath())

var oldFiles = Dir().entryList(['CopyQ-??????-??????.png'])
for (var i in oldFiles) {
  var f = File(oldFiles[i])
  if ( !f.remove() ) {
    popup('Failed to remove "' + f.fileName() + '": ' + f.errorString())
  }
}
```

**Comment by marqqer** [comment]
Dear hluk,Thanks ,after adding the f.close() ,the editor opened the temp file successfully.
how did the "Image editor command" (set up in "Item" config tab) operated? it seems the OS is responsible for deleting the temporary file ,I noticed the file will be deleted( after closing the editor) even if  CopyQ is quit.

**Comment by hluk** [comment]
CopyQ wait for the editor process to finish and deletes the temporary file.

Maybe from command you can do something like following so that `execute()` waits for editor to finish (I haven't tested this).

```js
execute('call', '/wait', 'mspaint.exe', strFilePath)
if ( f.remove() )
  popup('Removed "' + f.fileName() + '"')
else
  popup('Failed to remove "' + f.fileName() + '": ' + f.errorString())
```

**Comment by marqqer** [comment]
Thank you very much for your extremely helpful and detailed response to my issue,here is my updated workable code:
```
[Command]
Name=Open in FSCapture
Command="
    copyq:
    currentpath(Dir().tempPath())
    currentpath(Dir().tempPath())
    var oldFiles = Dir().entryList(['CopyQ-??????-??????.png'])
    for (var i in oldFiles) {
      var f = File(oldFiles[i])
      if ( !f.remove() ) {
        popup('Failed to remove \"' + f.fileName() + '\": ' + f.errorString())
      }
    }
    var fileName = 'CopyQ-'+dateString('yyMMdd-hhmmss')+'.png'
    var f = File(fileName)
    if (!f.open()) {
      popup('Failed to open \"' + f.fileName() + '\"', f.errorString())
      abort()
    }
    var iReturn=f.write(getitem(currentitem())['image/png'])
    f.close()
    var strFilePath = Dir().absoluteFilePath(fileName)
    strFilePath = Dir().toNativeSeparators(strFilePath)
    var strEditor = 'D:\\\\Applications\\\\SystemEnhance\\\\FastStoneCapture\\\\FSCapture.exe'
    execute(strEditor,strFilePath)"
Input=image/png
InMenu=true
HideWindow=true
Icon=\xf296

```

**Comment by marqqer** [comment]
I have tested your last provided code: 
```
execute('call', 'mspaint.exe', strFilePath)
if ( f.remove() )
  popup('Removed "' + f.fileName() + '"')
else
  popup('Failed to remove "' + f.fileName() + '": ' + f.errorString())
```
but the temporary file was deleted immediately, the editor have got no chance to open it
after i modified
` execute('call', 'mspaint.exe', strFilePath)`
to 
` execute('mspaint.exe', strFilePath)`
the temporary file got deleted after the Editor quit.
but while the editor is running, I can't quit CopyQ, otherwise a prompt "cancel active command and exit",if I chose 'Exit anyway' another error message popup.
another question where can I find more detailed reference of the function CopyQ use ,such as 'toNativeSeparators' and 'absoluteFilePath'

my final code:
```
[Command]
Name=Open in FSCapture
Command="
    copyq:
    currentpath(Dir().tempPath())
    var fileName = 'CopyQ-'+dateString('yyMMdd-hhmmss')+'.png'
    var f = File(fileName)
    if (!f.open()) {
      popup('Failed to open \"' + f.fileName() + '\"', f.errorString())
      abort()
    }
    var iReturn=f.write(getitem(currentitem())['image/png'])
    f.close()
    var strFilePath = Dir().absoluteFilePath(fileName)
    strFilePath = Dir().toNativeSeparators(strFilePath)
    var strEditor = 'D:\\\\Applications\\\\SystemEnhance\\\\FastStoneCapture\\\\FSCapture.exe'
    execute(strEditor, strFilePath)
    if (!f.remove() )
      popup('Failed to remove \"' + f.fileName() + '\": ' + f.errorString())
    
    "
Input=image/png
InMenu=true
HideWindow=true
Icon=\xf296
```

**Comment by hluk** [comment]
The `Dir` object is wrapper for [QDir](http://doc.qt.io/qt-5/qdir.html) (e.g. [QDir::toNativeSeparators](https://doc.qt.io/qt-5/qdir.html#toNativeSeparators)).

If some important methods are missing let me know.
