### ISSUE TITLE
How to change paste() to send ctrl+v?

### ISSUE THREAD

**Issue by marqqer** [hluk/CopyQ#633]
Hi dear hluk:
sorry to bother you again, I found that CopyQ paste selected item to current active window just by sending Shift+Insert,is that right? how can i change it to send ctrl+v? for many Windows  applications don't accept Shift+Insert as pasting.
Thanks and best wishes

**Comment by hluk** [comment]
There is undocumented feature which allows to send <kbd>Ctrl</kbd>+<kbd>V</kbd> instead of the default <kbd>Shift</kbd>+<kbd>Insert</kbd>.

You have to add following to your `copyq.ini` (in portable folder `config\copyq` or `%APPDATA%\copyq`).

```ini
[General]
paste_with_ctrl_v_windows="- IntelliJ IDEA"
```

The string is regular expression matching window titles of the apps where you want use <kbd>Ctrl</kbd>+<kbd>V</kbd> for pasting.

**Comment by marqqer** [comment]
thanks
can you give a example to match any window?

**Comment by hluk** [comment]
I think `paste_with_ctrl_v_windows=".*"` should work.

**Comment by marqqer** [comment]
Thanks a lot , it works, Probably best if we call make it an option can be set.

**Comment by whudwl** [comment]
> There is undocumented feature which allows to send Ctrl+V instead of the default Shift+Insert.
> 
> You have to add following to your `copyq.ini` (in portable folder `config\copyq` or `%APPDATA%\copyq`).
> 
> ```ini
> [General]
> paste_with_ctrl_v_windows="- IntelliJ IDEA"
> ```
> 
> The string is regular expression matching window titles of the apps where you want use Ctrl+V for pasting.

Has the default behaviour changed? It seems to me that now it sends Ctrl+v by default.  
And I've noticed another probably related option `window_paste_with_ctrl_v_regex=` under `Options` section.

**Comment by hluk** [comment]
> Has the default behaviour changed? It seems to me that now it sends Ctrl+v by default.

The app should still send Shift+Insert by default.

> And I've noticed another probably related option `window_paste_with_ctrl_v_regex=` under `Options` section.

Yes, the option is now under `[Options]` group in the config file and can be modified with:

```bash
copyq config window_paste_with_ctrl_v_regex 'SOME REGEXP'
```

**Comment by whudwl** [comment]
> > Has the default behaviour changed? It seems to me that now it sends Ctrl+v by default.
> 
> The app should still send Shift+Insert by default.
> 
> > And I've noticed another probably related option `window_paste_with_ctrl_v_regex=` under `Options` section.
> 
> Yes, the option is now under `[Options]` group in the config file and can be modified with:
> 
> ```shell
> copyq config window_paste_with_ctrl_v_regex 'SOME REGEXP'
> ```

Thank you. Just realized the reason CopyQ didn't work with my Win+Emacs is I ran emacs as admin.
