### ISSUE TITLE
How can I test if current clipboard has an image?

### ISSUE THREAD

**Issue by amosbird** [hluk/CopyQ#634]
I may need to modify scripts basing on that property.

**Comment by hluk** [comment]
Do you want to run an automatic command when an image is copied to clipboard?

**Comment by amosbird** [comment]
No, I have a script that will upload current clipboard content. It need to know the content type to do the right choice of uploading.

**Comment by hluk** [comment]
From command:

```js
var hasPng = str(clipboard('?')).indexOf('image/png')
```

You can list the types currently available in clipboard on command line with:

```bash
copyq clipboard \?
```

**Comment by amosbird** [comment]
cool, thanks.
