### ISSUE TITLE
How to write an action that does an `Move to clipboard` and then close the menu

### ISSUE THREAD

**Issue by amosbird** [hluk/CopyQ#635]
Directly select items other than the first one does not work inside `virtualbox`. So I need to move the item to clipboard first and then do the paste. Can I make the move part auto close the menu?

**Comment by hluk** [comment]
Are you saying you cannot paste selected items (apart from the first one) from tray menu to a guest OS in VirtualBox? Or you cannot even select other menu items? Do you open the menu on host or guest OS (outside or inside VirtualBox)?

**Comment by amosbird** [comment]
Well, the problem is, the old first item gets pasted into vbox. I think it's due to the delay of clipboard sharing.

**Comment by hluk** [comment]
It's possible to write custom item activation command but only when items are activated/pasted from main window. Something like [this](https://github.com/hluk/CopyQ/issues/562#issuecomment-257385689).

**Comment by amosbird** [comment]
Ah, can I make this command also support images?

**Comment by hluk** [comment]
```ini
[Command]
Command="
    copyq:
    hide()
    execute('sleep', '0.1')
    
    copy(mimeItems, input())
    copySelection(mimeItems, input())
    paste()"
Icon=\xf0ea
InMenu=true
Input=application/x-copyq-item
Name=Paste
Shortcut=enter
```

**Comment by amosbird** [comment]
Great! Thank you.

**Comment by amosbird** [comment]
@hluk hmm, can I make this command also move the selected item to the top? Just like `Enter`

**Comment by hluk** [comment]
Interestingly, this is not as simple as it sounds -- there is some scripting I can improve.

For now you can use following code (paste it at the end of your script).

```js
// Move selected items to top.
var selected = selecteditems()
  .sort(function(a, b) { return b - a; });

for (var i = 0; i < selected.length; ++i) {
  var itemData = read(mimeItems, selected[i] + i)
  write(mimeItems, itemData)
  remove(selected[i] + i + 1)
}

// Select moved items.
for (var i = 0; i < selected.length; ++i)
  selected[i] = i
selectItems.apply(this, selected)
```

Did you try pasting items to VirtualBox with CopyQ 2.9.0 (without special command)? I have improved the functionality for some applications so perhaps it works now too.

**Comment by amosbird** [comment]
@hluk Thanks! 2.9.0 can paste text items into vbox directly by `Enter` key, while image items still don't.
