### ISSUE TITLE
Focus problem after pasting to IntelliJ 2016.3.4

### ISSUE THREAD

**Issue by RALGIE** [hluk/CopyQ#637]
Hello,

I've got a problem with focus after pasting an item in IntelliJ, other applications  doesn't have that problem. The selected item is pasted in GEdit, Chromium, etc.. end the focus remains correct. Only IntelliJ has this problem. The selected text is pasted in the editor but doesn't sets the focus to the editor window after the paste. 

System information:
Ubuntu 16.04
 
IntelliJ IDEA 2016.3.4
Build #IU-163.12024.16, built on January 31, 2017
JRE: 1.8.0_121-b13 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

I've got CopyQ version:
CopyQ Clipboard Manager v2.8.2 (hluk@email.cz)
Built with: Qt 5.5.1, LibQxt 0.7.0

This is the command i've configured:
[Command]
Command=copyq: menu()
GlobalShortcut=ctrl+shift+v
Icon=\xf01c
Name=Show the tray menu

I've installed the newer version of CopyQ but this doesn't solve the problem.

Best regards,
Ralph

**Comment by hluk** [comment]
See #562.

The solution is to use [command](https://github.com/hluk/CopyQ/issues/562#issuecomment-257385689) which overrides activating items (<kbd>Enter</kbd>/mouse-double-click) from main window. So unfortunately you have to use `show()` or `showAt()` to show main window instead of `menu()`.

**Comment by RALGIE** [comment]
Unfortunately this is not the solution for this problem. I've changed it and the focus problem remains

**Comment by hluk** [comment]
Should be fixed now. [Here](http://download.opensuse.org/repositories/home:/lukho:/copyq-beta/xUbuntu_16.04/amd64/copyq_2.8.3.r77.ga237f150_amd64.deb) is package with the fix for Ubuntu 16.04.

**Comment by RALGIE** [comment]
After downloading and installing the deb file the issue is gone. CopyQ can paste the text in the IntelliJ IDE. But I get a new issue, when i start CopyQ. It crashes on start from CopyQ. And the commands in the 
![screenshot from 2017-02-14 13-24-52](https://cloud.githubusercontent.com/assets/7306942/22928893/0a5a9314-f2b9-11e6-8974-72c875cac54d.png)

And it start a CopyQ window, with an image from my browser.
![screenshot from 2017-02-14 13-27-12](https://cloud.githubusercontent.com/assets/7306942/22928959/60000a4c-f2b9-11e6-9110-41ce72331c28.png)

**Comment by hluk** [comment]
Can you describe how to crash the app step-by-step?

You can show the commands with new check box "Show Advanced" (it should stay visible after restart). I assume that most users won't touch the advanced settings and only add predefined commands and set shortcuts or name.

**Comment by RALGIE** [comment]
I seach copyq in the Dash
I select copyq and the coppyq window appairs with the background from my open application. 

After I installed the the deb for the first time I got an system error. 
Feb 14 13:08:40 BCT-LT0225a gnome-session[2267]: (gnome-software:2494): As-WARNING **: failed to rescan: Failed to parse /usr/share/applications/copyq.desktop.dpkg-new file: cannot process file of type text/plain
Feb 14 13:08:40 BCT-LT0225a gnome-session[2267]: (gnome-software:2494): As-WARNING **: failed to rescan: Failed to parse /usr/share/applications/copyq.desktop.dpkg-tmp file: cannot process file of type text/plain
Feb 14 13:08:40 BCT-LT0225a gnome-session[2267]: (gnome-software:2494): As-WARNING **: failed to rescan: Failed to parse /usr/share/applications/copyq.desktop file: cannot process file of type application/x-desktop
Feb 14 13:08:40 BCT-LT0225a gnome-session[2267]: (gnome-software:2494): As-WARNING **: failed to rescan: Failed to parse /usr/share/applications/bamf-2.index file: cannot process file of type text/plai


I hope this helps

**Comment by hluk** [comment]
Just tested the package and it seems to work fine for me on Ubuntu 16.04.

I don't understand what you mean by "It crashes on start from CopyQ" -- from the screenshots the application seems to be running.

I think I know what the problem with the second screenshot is -- that is just some dummy window that should be hidden. I'll fix that.

**Comment by hluk** [comment]
[Here](http://download.opensuse.org/repositories/home:/lukho:/copyq-beta/xUbuntu_16.04/amd64/copyq_2.8.3.r83.gadeacff4_amd64.deb) is new package with the empty window removed.

**Comment by RALGIE** [comment]
Thanks for the feedback. 

I need to clear that to you. I main with "It crashes on start from CopyQ" that the Window (you call it the dummy window) is starting with my current background. CopyQ starts and everything seems to work fine. 

The download with the fix doesn't work.

**Comment by hluk** [comment]
Sorry, I just updated the package -- [link to repo](http://download.opensuse.org/repositories/home:/lukho:/copyq-beta/xUbuntu_16.04/amd64/).

**Comment by RALGIE** [comment]
The fix worked. Thanks for fixing this problem
