### ISSUE TITLE
[copyq-git, qt5 build] why menu is soo high?

### ISSUE THREAD

**Issue by FadeMind** [hluk/CopyQ#639]
![screenshot_20170215_183748](https://cloud.githubusercontent.com/assets/9846948/22987121/0ae9feaa-f3ae-11e6-89e3-3f5edc98b3ae.png)

**Comment by hluk** [comment]
I don't see the problem here. Is the position or the height wrong? To fix the height you can try disabling "Set colors for tabs, tool bar, menus" in Configuration dialog under "Appearance" tab.

**Comment by FadeMind** [comment]
Look where Menu show up (TOP right) and TaskBar with Tray icon (BOTTOM right near CLOCK).
Should be like:
OCTOPI tray:
![screenshot_20170216_093420](https://cloud.githubusercontent.com/assets/9846948/23013491/20db8bfc-f42b-11e6-824d-9c5b655c716d.png)

CopyQ tray:
![screenshot_20170216_093529](https://cloud.githubusercontent.com/assets/9846948/23013515/45026366-f42b-11e6-804a-29c76cf542b2.png)

**Comment by hluk** [comment]
So them CopyQ menu is opened by clicking on tray icon? Is that KDE?

**Comment by FadeMind** [comment]
Yep, 

- KDE Plasma 5 5.9.2
- KDE Frameworks 5.31.0
- Manjaro x86_64
```
[fademind@manjaro ~]$ pacman -Q|grep plasma-desktop
plasma-desktop 5.9.2-1
[fademind@manjaro ~]$ pacman -Q|grep khtml
khtml 5.31.0-1
[fademind@manjaro ~]$ lsb_release -a
LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        16.10.3
Codename:       Fringilla
[fademind@manjaro ~]$ 
```

**Comment by hluk** [comment]
OK, should be fixed.

I tested this in Plasma 5.9.2 -- haven't used it in a while -- and the whole system is so unresponsive and slow (something is definitely broken).

I also noticed that global shortcuts don't work at start -- I just fixed that for Cinnamon :(.

**Comment by hluk** [comment]
BTW, global shortcuts should work fine now (982cc09d).

**Comment by FadeMind** [comment]
@hluk thanks for quick fix. Now all is fine. 
Best Regards

**Comment by FadeMind** [comment]
@hluk  since lastest changes in code ISSUE was return.

**Comment by hluk** [comment]
Oh, yeah sorry, I had to revert the workaround (the menu wasn't updated sometimes - 8d147e253f7ddc963358799e9c869b3b6cb65492).

The menu position is bug in KDE - it recreates menu items based on the original Qt tray menu in app.

I'll try to work something out but I don't want any complicated workarounds in code.

**Comment by FadeMind** [comment]
@hluk so should I create new bug about this in KDE bug tracker? :>

**Comment by hluk** [comment]
Perhaps. AFAIK the menu works fine in other desktop environments.

**Comment by FadeMind** [comment]
@hluk done

https://bugs.kde.org/show_bug.cgi?id=377019

**Comment by hluk** [comment]
Workaround in 9c053b889bbd17539f561f989cfd5ec887660e89 seems to work.
