### ISSUE TITLE
Spurious executable permission - traymenu.h

### ISSUE THREAD

**Issue by gbcox** [hluk/CopyQ#640]
Just a FYI... this kicked out by rpmlint during the build.  Something to look at for the next release.

copyq-debuginfo.x86_64: W: spurious-executable-perm /usr/src/debug/CopyQ-2.9.0/src/gui/traymenu.h

**Comment by hluk** [comment]
Damn, I think this is issue with some software running on VirtualBox. Fixed. Thanks for heads-up.
