### ISSUE TITLE
Signed hash sums file for installation packages

### ISSUE THREAD

**Issue by harmancode** [hluk/CopyQ#642]
Could you please provide a signed hash sums file for download files of CopyQ available on Github?
As this is a clipboard manager which may store sensitive data I think its genuineness can be very important.

**Comment by Achaean** [comment]
+1 from me too! :-)

**Comment by hluk** [comment]
I've uploaded `checksums-sha512.txt` and `cosign.bundle` for the latest release (9.1.0).

Below is the command for verifying the checksum file. For details, see: https://docs.sigstore.dev/quickstart/quickstart-cosign

```
cosign verify-blob checksums-sha512.txt --bundle cosign.bundle \
    --certificate-identity=hluk@email.cz \
    --certificate-oidc-issuer=https://github.com/login/oauth
```

Let me know if you have any suggestions.
