### ISSUE TITLE
Tabs contents are empty after updating from 2.8 to 2.9 [Portable]

### ISSUE THREAD

**Issue by ZIEXED** [hluk/CopyQ#643]
all my tabs contents are gone?????????

**Comment by ZIEXED** [comment]
I moved the data to the new location

**Comment by hluk** [comment]
I've been just trying to solve the backup issue #502. Definitely check that out if you have any ideas. Thanks.

**Comment by ZIEXED** [comment]
I don't use backups since I'm using the portable version
but I think the current export|import is good enough
it could be better if its possible to
#Show a list with the tabs to select which tabs to export
#Allow to import multiple tabs at once
so you don't need to repeat this for every tab you have

**Comment by hluk** [comment]
The improved import/export (#42) is almost implemented :).

New import and export options look like this (content depends on the imported file):

![image](https://cloud.githubusercontent.com/assets/38054/23102475/3701069c-f6aa-11e6-9d6a-51106a20cffa.png)
