### ISSUE TITLE
Getting encryption to work

### ISSUE THREAD

**Issue by pablomalo** [hluk/CopyQ#644]
I have a tab I'd like to protect.
I tried following instructions as per https://github.com/hluk/CopyQ/wiki/Password-Protection
GPG4Win is installed; environment is Windows 10 pro.
When I click on "Generate new keys" in CopyQ, I get the following message: "Error: failed to import private keys (see log)".
What am I doing wrong?

Below is the content of C:\Users\user\AppData\Roaming\copyq\copyq\copyq.log

> CopyQ Note [2017-02-19 08:59:29.430]: Loading plugin: C:/Program Files (x86)/CopyQ/plugins/libitemdata.dll
> CopyQ Note [2017-02-19 08:59:29.443]: Loading plugin: C:/Program Files (x86)/CopyQ/plugins/libitemencrypted.dll
> CopyQ Note [2017-02-19 08:59:29.456]: Loading plugin: C:/Program Files (x86)/CopyQ/plugins/libitemfakevim.dll
> CopyQ Note [2017-02-19 08:59:29.468]: Loading plugin: C:/Program Files (x86)/CopyQ/plugins/libitemimage.dll
> CopyQ Note [2017-02-19 08:59:29.487]: Loading plugin: C:/Program Files (x86)/CopyQ/plugins/libitemnotes.dll
> CopyQ Note [2017-02-19 08:59:29.500]: Loading plugin: C:/Program Files (x86)/CopyQ/plugins/libitemsync.dll
> CopyQ Note [2017-02-19 08:59:29.512]: Loading plugin: C:/Program Files (x86)/CopyQ/plugins/libitemtags.dll
> CopyQ Note [2017-02-19 08:59:29.525]: Loading plugin: C:/Program Files (x86)/CopyQ/plugins/libitemtext.dll
> CopyQ ERROR [2017-02-19 08:59:53.272]: ItemEncrypt ERROR: GnuPG stderr:
> CopyQ ERROR [2017-02-19 08:59:53.272]:    gpg: invalid key resource URL `C:\Users\paulg\AppData\Roaming\copyq\copyq.pub'
> CopyQ ERROR [2017-02-19 08:59:53.272]:    gpg: keyblock resource `(null)': general error
> CopyQ ERROR [2017-02-19 08:59:53.272]:    
> CopyQ ERROR [2017-02-19 08:59:55.729]: ItemEncrypt ERROR: GnuPG stderr:
> CopyQ ERROR [2017-02-19 08:59:55.729]:    gpg: invalid key resource URL `C:\Users\paulg\AppData\Roaming\copyq\copyq.pub'
> CopyQ ERROR [2017-02-19 08:59:55.729]:    gpg: keyblock resource `(null)': general error
> CopyQ ERROR [2017-02-19 08:59:55.729]:    
> CopyQ ERROR [2017-02-19 08:59:57.185]: ItemEncrypt ERROR: GnuPG stderr:
> CopyQ ERROR [2017-02-19 08:59:57.185]:    gpg: invalid key resource URL `C:\Users\paulg\AppData\Roaming\copyq\copyq.pub'
> CopyQ ERROR [2017-02-19 08:59:57.185]:    gpg: keyblock resource `(null)': general error
> CopyQ ERROR [2017-02-19 08:59:57.185]:    gpg: key 78D8AA3F: secret key imported
> CopyQ ERROR [2017-02-19 08:59:57.185]:    gpg: no writable keyring found: eof
> CopyQ ERROR [2017-02-19 08:59:57.185]:    gpg: Total number processed: 1
> CopyQ ERROR [2017-02-19 08:59:57.185]:    gpg:       secret keys read: 1
> CopyQ ERROR [2017-02-19 08:59:57.185]:    gpg:   secret keys imported: 1
> CopyQ ERROR [2017-02-19 08:59:57.185]:    
> CopyQ ERROR [2017-02-19 08:59:57.295]: ItemEncrypt ERROR: GnuPG stderr:
> CopyQ ERROR [2017-02-19 08:59:57.295]:    gpg: invalid key resource URL `C:\Users\paulg\AppData\Roaming\copyq\copyq.pub'
> CopyQ ERROR [2017-02-19 08:59:57.295]:    gpg: keyblock resource `(null)': general error
> CopyQ ERROR [2017-02-19 08:59:57.295]:    
>

**Comment by hluk** [comment]
Make sure you are running latest version of CopyQ (v2.9.0).

Can you run `gpg --version` from console? It should print: `gpg (GnuPG) 2.0.30 (Gpg4win 2.3.3)...`

**Comment by hluk** [comment]
Nevermind, it should be **fixed**. It seems the app found and used some old version of `gpg` utility.

You can use download the fixed version for Windows [here](https://ci.appveyor.com/project/hluk/copyq/build/job/9gyr550at2lc6vx9/artifacts).
