### ISSUE TITLE
Any way to restore encrypted clips?

### ISSUE THREAD

**Issue by sajxe** [hluk/CopyQ#649]
Hi, I just upgraded to ubuntu 16.04.01 with a clean new OS install. I installed CopyQ again from scratch  after the upgrade, and copied my configuration settings from my old home folder to my new user account.

CopyQ worked perfectly except that now I cannot open any of the encrypted tabs. I did copy over the old key files.

I'm guessing I made a mistake and should have unencrypted the tabs before I upgraded the OS, to avoid this problem.

Hoping you know a way to get the encrypted data back! If not I guess I will just have to re-enter everything, but there are many tabs and there is a lot to replace, so if there are any workarounds for this I would be very grateful for any help you can give :)

Thanks very much for this great program, I would not be able to get through a day without it! :)

**Comment by sajxe** [comment]
Oh, I forgot to say, I tried to click on "Change password" but nothing happens. There is a very quick flash as though a window tried to pop up, but then it disappears too quickly to see what it says. I am now on 64 bit, and my old OS before the upgrade was 32 bit - I don't know if that makes a difference?

**Comment by hluk** [comment]
Can you provide log (<kbd>F12</kbd> shortcut)?

What does `gpg --version` print on command line?

**Comment by sajxe** [comment]
thanks for the quick reply! I tried to click on an encrypted tab. It showed the reload symbol. I clicked on the reload symbol and the error message "Encryption Failed, Right Click to Show" appeared. If I right click to show, it just pops up another window saying "Encryption Failed!" Here's what I get from F12 after doing all that (there are 3 days in the log but what I just described above is what I just tried now on 2/20 so you can see that in the most recent timestamped lines):

Note [2017-02-18 22:36:07.126]: Loading plugin: /usr/lib/copyq/plugins/libitemdata.so
Note [2017-02-18 22:36:07.127]: Loading plugin: /usr/lib/copyq/plugins/libitemencrypted.so
Note [2017-02-18 22:36:07.128]: Loading plugin: /usr/lib/copyq/plugins/libitemfakevim.so
Note [2017-02-18 22:36:07.128]: Loading plugin: /usr/lib/copyq/plugins/libitemimage.so
Note [2017-02-18 22:36:07.129]: Loading plugin: /usr/lib/copyq/plugins/libitemnotes.so
Note [2017-02-18 22:36:07.129]: Loading plugin: /usr/lib/copyq/plugins/libitemsync.so
Note [2017-02-18 22:36:07.130]: Loading plugin: /usr/lib/copyq/plugins/libitemtags.so
Note [2017-02-18 22:36:07.130]: Loading plugin: /usr/lib/copyq/plugins/libitemtext.so
Note [2017-02-18 22:38:20.334]: Loading plugin: /usr/lib/copyq/plugins/libitemdata.so
Note [2017-02-18 22:38:20.335]: Loading plugin: /usr/lib/copyq/plugins/libitemencrypted.so
Note [2017-02-18 22:38:20.336]: Loading plugin: /usr/lib/copyq/plugins/libitemfakevim.so
Note [2017-02-18 22:38:20.336]: Loading plugin: /usr/lib/copyq/plugins/libitemimage.so
Note [2017-02-18 22:38:20.337]: Loading plugin: /usr/lib/copyq/plugins/libitemnotes.so
Note [2017-02-18 22:38:20.337]: Loading plugin: /usr/lib/copyq/plugins/libitemsync.so
Note [2017-02-18 22:38:20.338]: Loading plugin: /usr/lib/copyq/plugins/libitemtags.so
Note [2017-02-18 22:38:20.338]: Loading plugin: /usr/lib/copyq/plugins/libitemtext.so
Note [2017-02-19 02:44:00.407]: Loading plugin: /usr/lib/copyq/plugins/libitemdata.so
Note [2017-02-19 02:44:00.438]: Loading plugin: /usr/lib/copyq/plugins/libitemencrypted.so
Note [2017-02-19 02:44:00.453]: Loading plugin: /usr/lib/copyq/plugins/libitemfakevim.so
Note [2017-02-19 02:44:00.459]: Loading plugin: /usr/lib/copyq/plugins/libitemimage.so
Note [2017-02-19 02:44:00.469]: Loading plugin: /usr/lib/copyq/plugins/libitemnotes.so
Note [2017-02-19 02:44:00.483]: Loading plugin: /usr/lib/copyq/plugins/libitemsync.so
Note [2017-02-19 02:44:00.485]: Loading plugin: /usr/lib/copyq/plugins/libitemtags.so
Note [2017-02-19 02:44:00.491]: Loading plugin: /usr/lib/copyq/plugins/libitemtext.so
ERROR [2017-02-19 02:44:43.234]: ItemEncrypt ERROR: GnuPG stderr:
ERROR [2017-02-19 02:44:43.234]:    gpg: Sorry, no terminal at all requested - can't get input
ERROR [2017-02-19 02:44:43.234]:    
ERROR [2017-02-19 02:44:43.234]: Tab "%1": Failed to load items
ERROR [2017-02-19 02:44:50.624]: ItemEncrypt ERROR: GnuPG stderr:
ERROR [2017-02-19 02:44:50.624]:    gpg: key 5459CB95: already in secret keyring
ERROR [2017-02-19 02:44:50.624]:    gpg: Total number processed: 1
ERROR [2017-02-19 02:44:50.624]:    gpg:       secret keys read: 1
ERROR [2017-02-19 02:44:50.624]:    gpg:  secret keys unchanged: 1
ERROR [2017-02-19 02:44:50.624]:    
ERROR [2017-02-19 02:44:50.630]: ItemEncrypt ERROR: GnuPG stderr:
ERROR [2017-02-19 02:44:50.630]:    gpg: Sorry, no terminal at all requested - can't get input
ERROR [2017-02-19 02:44:50.630]:    
ERROR [2017-02-19 02:44:50.630]: Tab "%1": Failed to load items
ERROR [2017-02-19 02:44:54.059]: ItemEncrypt ERROR: GnuPG stderr:
ERROR [2017-02-19 02:44:54.059]:    gpg: key 5459CB95: already in secret keyring
ERROR [2017-02-19 02:44:54.059]:    gpg: Total number processed: 1
ERROR [2017-02-19 02:44:54.059]:    gpg:       secret keys read: 1
ERROR [2017-02-19 02:44:54.059]:    gpg:  secret keys unchanged: 1
ERROR [2017-02-19 02:44:54.059]:    
ERROR [2017-02-19 02:44:54.065]: ItemEncrypt ERROR: GnuPG stderr:
ERROR [2017-02-19 02:44:54.065]:    gpg: Sorry, no terminal at all requested - can't get input
ERROR [2017-02-19 02:44:54.065]:    
ERROR [2017-02-19 02:44:54.065]: Tab "%1": Failed to load items
Note [2017-02-19 02:46:18.926]: Loading plugin: /usr/lib/copyq/plugins/libitemdata.so
Note [2017-02-19 02:46:18.927]: Loading plugin: /usr/lib/copyq/plugins/libitemencrypted.so
Note [2017-02-19 02:46:18.927]: Loading plugin: /usr/lib/copyq/plugins/libitemfakevim.so
Note [2017-02-19 02:46:18.928]: Loading plugin: /usr/lib/copyq/plugins/libitemimage.so
Note [2017-02-19 02:46:18.928]: Loading plugin: /usr/lib/copyq/plugins/libitemnotes.so
Note [2017-02-19 02:46:18.929]: Loading plugin: /usr/lib/copyq/plugins/libitemsync.so
Note [2017-02-19 02:46:18.929]: Loading plugin: /usr/lib/copyq/plugins/libitemtags.so
Note [2017-02-19 02:46:18.930]: Loading plugin: /usr/lib/copyq/plugins/libitemtext.so
Note [2017-02-19 05:33:26.233]: Loading plugin: /usr/lib/copyq/plugins/libitemdata.so
Note [2017-02-19 05:33:26.265]: Loading plugin: /usr/lib/copyq/plugins/libitemencrypted.so
Note [2017-02-19 05:33:26.279]: Loading plugin: /usr/lib/copyq/plugins/libitemfakevim.so
Note [2017-02-19 05:33:26.286]: Loading plugin: /usr/lib/copyq/plugins/libitemimage.so
Note [2017-02-19 05:33:26.295]: Loading plugin: /usr/lib/copyq/plugins/libitemnotes.so
Note [2017-02-19 05:33:26.311]: Loading plugin: /usr/lib/copyq/plugins/libitemsync.so
Note [2017-02-19 05:33:26.313]: Loading plugin: /usr/lib/copyq/plugins/libitemtags.so
Note [2017-02-19 05:33:26.314]: Loading plugin: /usr/lib/copyq/plugins/libitemtext.so
ERROR [2017-02-19 05:35:48.376]: ItemEncrypt ERROR: GnuPG stderr:
ERROR [2017-02-19 05:35:48.376]:    gpg: key 5459CB95: already in secret keyring
ERROR [2017-02-19 05:35:48.376]:    gpg: Total number processed: 1
ERROR [2017-02-19 05:35:48.376]:    gpg:       secret keys read: 1
ERROR [2017-02-19 05:35:48.376]:    gpg:  secret keys unchanged: 1
ERROR [2017-02-19 05:35:48.376]:    
ERROR [2017-02-19 05:35:48.386]: ItemEncrypt ERROR: GnuPG stderr:
ERROR [2017-02-19 05:35:48.386]:    gpg: Sorry, no terminal at all requested - can't get input
ERROR [2017-02-19 05:35:48.386]:    
ERROR [2017-02-19 05:35:48.386]: Tab "%1": Failed to load items
ERROR [2017-02-19 05:35:49.934]: ItemEncrypt ERROR: GnuPG stderr:
ERROR [2017-02-19 05:35:49.934]:    gpg: key 5459CB95: already in secret keyring
ERROR [2017-02-19 05:35:49.934]:    gpg: Total number processed: 1
ERROR [2017-02-19 05:35:49.934]:    gpg:       secret keys read: 1
ERROR [2017-02-19 05:35:49.934]:    gpg:  secret keys unchanged: 1
ERROR [2017-02-19 05:35:49.934]:    
ERROR [2017-02-19 05:35:49.947]: ItemEncrypt ERROR: GnuPG stderr:
ERROR [2017-02-19 05:35:49.947]:    gpg: Sorry, no terminal at all requested - can't get input
ERROR [2017-02-19 05:35:49.947]:    
ERROR [2017-02-19 05:35:49.948]: Tab "%1": Failed to load items
ERROR [2017-02-19 05:36:35.556]: Item file “/home/user/.config/copyq/copyq_tab_Y2xlczI=.dat” is corrupted or some CopyQ plugins are missing!
ERROR [2017-02-19 05:36:35.556]: Tab "%1": Failed to load items
Note [2017-02-19 05:52:44.332]: Loading plugin: /usr/lib/copyq/plugins/libitemdata.so
Note [2017-02-19 05:52:44.332]: Loading plugin: /usr/lib/copyq/plugins/libitemencrypted.so
Note [2017-02-19 05:52:44.333]: Loading plugin: /usr/lib/copyq/plugins/libitemfakevim.so
Note [2017-02-19 05:52:44.333]: Loading plugin: /usr/lib/copyq/plugins/libitemimage.so
Note [2017-02-19 05:52:44.334]: Loading plugin: /usr/lib/copyq/plugins/libitemnotes.so
Note [2017-02-19 05:52:44.334]: Loading plugin: /usr/lib/copyq/plugins/libitemsync.so
Note [2017-02-19 05:52:44.335]: Loading plugin: /usr/lib/copyq/plugins/libitemtags.so
Note [2017-02-19 05:52:44.335]: Loading plugin: /usr/lib/copyq/plugins/libitemtext.so
ERROR [2017-02-19 05:54:06.825]: ItemEncrypt ERROR: GnuPG stderr:
ERROR [2017-02-19 05:54:06.825]:    gpg: key 5459CB95: already in secret keyring
ERROR [2017-02-19 05:54:06.825]:    gpg: Total number processed: 1
ERROR [2017-02-19 05:54:06.825]:    gpg:       secret keys read: 1
ERROR [2017-02-19 05:54:06.825]:    gpg:  secret keys unchanged: 1
ERROR [2017-02-19 05:54:06.825]:    
ERROR [2017-02-19 05:54:06.831]: ItemEncrypt ERROR: GnuPG stderr:
ERROR [2017-02-19 05:54:06.831]:    gpg: Sorry, no terminal at all requested - can't get input
ERROR [2017-02-19 05:54:06.831]:    
ERROR [2017-02-19 05:54:06.831]: Tab "%1": Failed to load items
Note [2017-02-19 12:14:04.997]: Loading plugin: /usr/lib/copyq/plugins/libitemdata.so
Note [2017-02-19 12:14:05.378]: Loading plugin: /usr/lib/copyq/plugins/libitemencrypted.so
Note [2017-02-19 12:14:05.681]: Loading plugin: /usr/lib/copyq/plugins/libitemfakevim.so
Note [2017-02-19 12:14:05.840]: Loading plugin: /usr/lib/copyq/plugins/libitemimage.so
Note [2017-02-19 12:14:05.858]: Loading plugin: /usr/lib/copyq/plugins/libitemnotes.so
Note [2017-02-19 12:14:06.030]: Loading plugin: /usr/lib/copyq/plugins/libitemsync.so
Note [2017-02-19 12:14:06.033]: Loading plugin: /usr/lib/copyq/plugins/libitemtags.so
Note [2017-02-19 12:14:06.046]: Loading plugin: /usr/lib/copyq/plugins/libitemtext.so
Note [2017-02-19 17:07:09.096]: Loading plugin: /usr/lib/copyq/plugins/libitemdata.so
Note [2017-02-19 17:07:09.277]: Loading plugin: /usr/lib/copyq/plugins/libitemencrypted.so
Note [2017-02-19 17:07:09.417]: Loading plugin: /usr/lib/copyq/plugins/libitemfakevim.so
Note [2017-02-19 17:07:09.438]: Loading plugin: /usr/lib/copyq/plugins/libitemimage.so
Note [2017-02-19 17:07:09.508]: Loading plugin: /usr/lib/copyq/plugins/libitemnotes.so
Note [2017-02-19 17:07:09.611]: Loading plugin: /usr/lib/copyq/plugins/libitemsync.so
Note [2017-02-19 17:07:09.613]: Loading plugin: /usr/lib/copyq/plugins/libitemtags.so
Note [2017-02-19 17:07:09.613]: Loading plugin: /usr/lib/copyq/plugins/libitemtext.so
Note [2017-02-19 17:22:54.355]: Loading plugin: /usr/lib/copyq/plugins/libitemdata.so
Note [2017-02-19 17:22:54.363]: Loading plugin: /usr/lib/copyq/plugins/libitemencrypted.so
Note [2017-02-19 17:22:54.364]: Loading plugin: /usr/lib/copyq/plugins/libitemfakevim.so
Note [2017-02-19 17:22:54.365]: Loading plugin: /usr/lib/copyq/plugins/libitemimage.so
Note [2017-02-19 17:22:54.365]: Loading plugin: /usr/lib/copyq/plugins/libitemnotes.so
Note [2017-02-19 17:22:54.366]: Loading plugin: /usr/lib/copyq/plugins/libitemsync.so
Note [2017-02-19 17:22:54.366]: Loading plugin: /usr/lib/copyq/plugins/libitemtags.so
Note [2017-02-19 17:22:54.378]: Loading plugin: /usr/lib/copyq/plugins/libitemtext.so
Note [2017-02-19 20:43:57.484]: Loading plugin: /usr/lib/copyq/plugins/libitemdata.so
Note [2017-02-19 20:43:57.850]: Loading plugin: /usr/lib/copyq/plugins/libitemencrypted.so
Note [2017-02-19 20:43:58.063]: Loading plugin: /usr/lib/copyq/plugins/libitemfakevim.so
Note [2017-02-19 20:43:58.094]: Loading plugin: /usr/lib/copyq/plugins/libitemimage.so
Note [2017-02-19 20:43:58.203]: Loading plugin: /usr/lib/copyq/plugins/libitemnotes.so
Note [2017-02-19 20:43:58.284]: Loading plugin: /usr/lib/copyq/plugins/libitemsync.so
Note [2017-02-19 20:43:58.286]: Loading plugin: /usr/lib/copyq/plugins/libitemtags.so
Note [2017-02-19 20:43:58.287]: Loading plugin: /usr/lib/copyq/plugins/libitemtext.so
Note [2017-02-19 21:12:02.868]: Loading plugin: /usr/lib/copyq/plugins/libitemdata.so
Note [2017-02-19 21:12:02.868]: Loading plugin: /usr/lib/copyq/plugins/libitemencrypted.so
Note [2017-02-19 21:12:02.869]: Loading plugin: /usr/lib/copyq/plugins/libitemfakevim.so
Note [2017-02-19 21:12:02.869]: Loading plugin: /usr/lib/copyq/plugins/libitemimage.so
Note [2017-02-19 21:12:02.870]: Loading plugin: /usr/lib/copyq/plugins/libitemnotes.so
Note [2017-02-19 21:12:02.873]: Loading plugin: /usr/lib/copyq/plugins/libitemsync.so
Note [2017-02-19 21:12:02.873]: Loading plugin: /usr/lib/copyq/plugins/libitemtags.so
Note [2017-02-19 21:12:02.874]: Loading plugin: /usr/lib/copyq/plugins/libitemtext.so
Note [2017-02-20 10:43:49.708]: Loading plugin: /usr/lib/copyq/plugins/libitemdata.so
Note [2017-02-20 10:43:50.076]: Loading plugin: /usr/lib/copyq/plugins/libitemencrypted.so
Note [2017-02-20 10:43:50.166]: Loading plugin: /usr/lib/copyq/plugins/libitemfakevim.so
Note [2017-02-20 10:43:50.181]: Loading plugin: /usr/lib/copyq/plugins/libitemimage.so
Note [2017-02-20 10:43:50.207]: Loading plugin: /usr/lib/copyq/plugins/libitemnotes.so
Note [2017-02-20 10:43:50.241]: Loading plugin: /usr/lib/copyq/plugins/libitemsync.so
Note [2017-02-20 10:43:50.251]: Loading plugin: /usr/lib/copyq/plugins/libitemtags.so
Note [2017-02-20 10:43:50.252]: Loading plugin: /usr/lib/copyq/plugins/libitemtext.so
Note [2017-02-20 19:51:40.356]: Loading plugin: /usr/lib/copyq/plugins/libitemdata.so
Note [2017-02-20 19:51:40.715]: Loading plugin: /usr/lib/copyq/plugins/libitemencrypted.so
Note [2017-02-20 19:51:40.955]: Loading plugin: /usr/lib/copyq/plugins/libitemfakevim.so
Note [2017-02-20 19:51:41.036]: Loading plugin: /usr/lib/copyq/plugins/libitemimage.so
Note [2017-02-20 19:51:41.162]: Loading plugin: /usr/lib/copyq/plugins/libitemnotes.so
Note [2017-02-20 19:51:41.187]: Loading plugin: /usr/lib/copyq/plugins/libitemsync.so
Note [2017-02-20 19:51:41.189]: Loading plugin: /usr/lib/copyq/plugins/libitemtags.so
Note [2017-02-20 19:51:41.190]: Loading plugin: /usr/lib/copyq/plugins/libitemtext.so
Note [2017-02-20 20:38:59.328]: Loading plugin: /usr/lib/copyq/plugins/libitemdata.so
Note [2017-02-20 20:39:00.796]: Loading plugin: /usr/lib/copyq/plugins/libitemencrypted.so
Note [2017-02-20 20:39:00.835]: Loading plugin: /usr/lib/copyq/plugins/libitemfakevim.so
Note [2017-02-20 20:39:00.852]: Loading plugin: /usr/lib/copyq/plugins/libitemimage.so
Note [2017-02-20 20:39:00.887]: Loading plugin: /usr/lib/copyq/plugins/libitemnotes.so
Note [2017-02-20 20:39:00.911]: Loading plugin: /usr/lib/copyq/plugins/libitemsync.so
Note [2017-02-20 20:39:00.931]: Loading plugin: /usr/lib/copyq/plugins/libitemtags.so
Note [2017-02-20 20:39:00.932]: Loading plugin: /usr/lib/copyq/plugins/libitemtext.so
ERROR [2017-02-20 21:42:44.108]: ItemEncrypt ERROR: GnuPG stderr:
ERROR [2017-02-20 21:42:44.108]:    gpg: key 5459CB95: already in secret keyring
ERROR [2017-02-20 21:42:44.108]:    gpg: Total number processed: 1
ERROR [2017-02-20 21:42:44.108]:    gpg:       secret keys read: 1
ERROR [2017-02-20 21:42:44.108]:    gpg:  secret keys unchanged: 1
ERROR [2017-02-20 21:42:44.108]:    
ERROR [2017-02-20 21:42:44.114]: ItemEncrypt ERROR: GnuPG stderr:
ERROR [2017-02-20 21:42:44.114]:    gpg: Sorry, no terminal at all requested - can't get input
ERROR [2017-02-20 21:42:44.114]:    
ERROR [2017-02-20 21:42:44.115]: Tab "%1": Failed to load items
ERROR [2017-02-20 21:42:46.341]: ItemEncrypt ERROR: GnuPG stderr:
ERROR [2017-02-20 21:42:46.341]:    gpg: key 5459CB95: already in secret keyring
ERROR [2017-02-20 21:42:46.341]:    gpg: Total number processed: 1
ERROR [2017-02-20 21:42:46.341]:    gpg:       secret keys read: 1
ERROR [2017-02-20 21:42:46.341]:    gpg:  secret keys unchanged: 1
ERROR [2017-02-20 21:42:46.341]:    
ERROR [2017-02-20 21:42:46.347]: ItemEncrypt ERROR: GnuPG stderr:
ERROR [2017-02-20 21:42:46.347]:    gpg: Sorry, no terminal at all requested - can't get input
ERROR [2017-02-20 21:42:46.347]:    
ERROR [2017-02-20 21:42:46.347]: Tab "%1": Failed to load items

**Comment by sajxe** [comment]
This is what I get for your other question:

gpg (GnuPG) 1.4.20
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: ~/.gnupg
Supported algorithms:
Pubkey: RSA, RSA-E, RSA-S, ELG-E, DSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: MD5, SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2

**Comment by sajxe** [comment]
I don't know if the failure to request a terminal has anything to do with what I have installed, but I think I have at least three terminals installed, including the default terminal that comes with Ubuntu, plus Konsole, plus Byobu. If you need a specific other terminal to be called please let me know and I will try installing it! :)

**Comment by hluk** [comment]
That's old version `gpg` incompatible with CopyQ. Just yesterday I fixed the bug so `gpg2` is always used instead.

Beta package for Ubuntu 16.04 is [here](http://download.opensuse.org/repositories/home:/lukho:/copyq-beta/xUbuntu_16.04/amd64/). But it's probably better if you can keep your current CopyQ version and have your `gpg` in `PATH` to refer to `gpg2` (maybe a package provides this).

Sorry for the inconvenience.

**Comment by sajxe** [comment]
Thanks very much hluk! It looks like gpg2 is not yet available for my system. I cannot find a package for it yet and the repository only has the old 1.4.20 version. I found some instructions for installing gpg2 manually but it looks quite complicated and I don't want to mess up my new system accidentally, so I will wait for them to provide an updated package. I've downloaded the beta you kindly provided and will try that if I manage to get gpg2 installed in future. In the meantime I think I will try to work around this by loading 14.04 on a USB drive and decrypting my clips from an older version of CopyQ there, then try to re-import if possible. Thanks very much for all your help!

**Comment by hluk** [comment]
@sajxe `gpg2` is quite ubiquitous and is definitely available on most distros. Did you install package [gnupg2](https://launchpad.net/ubuntu/+source/gnupg2)?

**Comment by sajxe** [comment]
Oops sorry my mistake! I couldn't find it in Synaptic because i looked for gpg2. After searching some more i found it under gnupg2 and you are correct, it is already installed. :) I will try your suggestions - either install the beta version or modify the path. Thanks very much once again!

**Comment by sajxe** [comment]
I installed the beta you provided and everything is now working perfectly again. I was able to decrypt my encrypted tabs with no problems. Thank you very much for all your help! :)
