### ISSUE TITLE
copyq/bash commands on El Capitan

### ISSUE THREAD

**Issue by reagle** [hluk/CopyQ#651]
This is related to #242, but on MacOS. I had hoped that by simply changing the path (s/home/Users/) it would work, but instead I get errors. (Upgraded to 2.9.0 and still present.)

```
Command “bash -c -- text="$…pyq add "$text" --”
Exit code: 127
--: line 1: copyq: command not found
Traceback (most recent call last):
  File "/Users/reagle/bin/fe/change_case.py", line 14, in <module>
    from fe import BORING_WORDS
  File "/Users/reagle/bin/fe/fe.py", line 50, in <module>
    from lxml.etree import parse, Element, SubElement, ElementTree, tostring
ImportError: No module named lxml.etree
--: line 2: copyq: command not found
--: line 3: copyq: command not found

---
bash -c -- 
text="$(/Users/reagle/bin/fe/change_case.py -s "$(copyq clipboard)")"
copyq copy "$text"
copyq add "$text" --
---
```

copyq is available from terminal:

```
hom:~$ which copyq
copyq is hashed (/Applications/CopyQ.app/Contents/MacOS/copyq)
```

Even if I set the copyq path explicitly, I still have trouble. Any ideas?

**Comment by hluk** [comment]
Since the bash in interactive mode can rely on some config files to be sourced (like `/etc/profile`), `copyq` may no be in `PATH` when bash is run with a command (`-c ...`).

The only solution I came up with was adding environment variable (`COPYQ=<absolute_path_to_executable>`) to processes started from CopyQ so you just have to use `"$COPYQ"` instead `copyq`.

Any ideas how to fix this so user can use `copyq` in scripts? BTW, I don't want to modify `PATH` since it could be platform-dependent (different separators on Windows) and it could bring in more unwanted stuff.

**Comment by reagle** [comment]
And my `ImportError` is related to $PYTHONPATH. I can make the path errors going away by running my path script (spun out from .bashrc).

**But** then I end up with every result being `true`. I had this problem before and will have to investigate what it means.

```
bash:
. ~/.setpath.bash
text="$(/Users/reagle/bin/fe/change_case.py "$(copyq clipboard)")"
copyq copy "$text"
copyq add "$text"
```

**Comment by hluk** [comment]
Some script functions return bool and if run from command line without script they just print the bool. E.g.

```bash
> copyq visible
false
```

Not sure if that's what you mean. I'll try to turn the bool to exit code if possible.

**Comment by reagle** [comment]
Yes, I had this problem in #242. There you wrote:

> You probably have "Output" field set for the command in Command dialog [F6]. If you leave the field empty it should work.

I checked and somehow the Output field had been set to text/plain again. When I make it empty/blank, I no longer get "true" but I get nothing/blank preprended to my copyq queue.

**Comment by reagle** [comment]
Never mind, stupid moment on my part but I figured it out. (For the purposes of this bug; setting paths and making sure Output field is blank worked.)
