### ISSUE TITLE
 Autoscroll clibboard after additions

### ISSUE THREAD

**Issue by reagle** [hluk/CopyQ#653]
While debugging #651 I confused myself because as I'm doing copyq commands (add and copy) the display of the queue does not change as items are added to its top. That is, if I have a buffer open, it'd be nice that upon add, it scrolled to the top and showed what the new 0 item is.

**Comment by hluk** [comment]
There is some locking mechanism so that list doesn't scroll elsewhere if items are added to the list.

I had some issues with it too in past. I'll try to remove the feature and see if it gets less confusing.
