### ISSUE TITLE
After switching tabs the activated item will not be pasted

### ISSUE THREAD

**Issue by m4r71n** [hluk/CopyQ#655]
CopyQ 2.9.0 on Windows 10 x64
The options `Move item to top`, `Close main window` , `Focus last window` and `Paste to current window` on the tab `History` are all activated. After opening the main window and switching tabs with `left` or `right` an activated item will not be pasted (only copied to clipboard). Without switching tabs before activating an item it will be pasted.

**Comment by hluk** [comment]
This should be fixed in master branch now.

**Comment by m4r71n** [comment]
It is fixed! Thank you very much
