### ISSUE TITLE
automatic new item from terminal

### ISSUE THREAD

**Issue by matti** [hluk/CopyQ#657]
(in Ubuntu) CopyQ creates a new item automatically in all other apps except in terminal (gnome-terminal / roxterm).

"Store text selected using mouse" works, but I don't want that. How to force always create a new item from the clipboard?

**Comment by hluk** [comment]
You can enable "Store text selected using mouse" option and use following command to filter out uninteresting windows (copy/paste the code to command list in Command dialog <kbd>F6</kbd>). Just change the `terminalWindowTitle` to match the terminal windows.

```ini
[Command]
Automatic=true
Command="
    copyq:
    var terminalWindowTitle = /^Terminal|^xterm/i
    
    var windowTitle = str(data(mimeWindowTitle))
    if ( !windowTitle.match(terminalWindowTitle) )
      removeData(mimeOutputTab)"
Icon=\xf120
Input=application/x-copyq-clipboard-mode
Name=Mouse Selection from Terminals
```

**Comment by matti** [comment]
thanks, this workaround works.

**Comment by matti** [comment]
@hluk so this is not a bug of copyq? that copyq does not detect copy in gnome-terminal?

**Comment by hluk** [comment]
Oh, I think I must've misunderstood the issue before.

Just tested this and with option "Store text selected using mouse" enabled mouse selection from both roxterm and gnome-terminal is stored in CopyQ.

Can you check log for errors (<kbd>F12</kbd> shortcut)?
