### ISSUE TITLE
Pasting in 'GNU Octave' (math software) does not work

### ISSUE THREAD

**Issue by tnilzon** [hluk/CopyQ#658]
When pasting from CopyQ (selecting an item from CopyQ main window, then press enter for pasting) into Command Window of the mathematical software 'GNU Octave', the item is not pasted. Instead a weird sign like this appears: 2~
(pasting with Ctrl+V works as normal)

Versions used:
Ubuntu, version 16.04
GNU Octave, version 4.0.0
CopyQ 2.9.0 (compiled from source 2017-03-05)

/Tomas Nilzon, Sweden

**Comment by hluk** [comment]
To send <kbd>Ctrl</kbd>+<kbd>V</kbd> shortcut to Octave window, add following to your configuration.

```ini
[General]
paste_with_ctrl_v_windows="Octave"
```

Hmm, keyboard control in Octave seems little unusual.

**Comment by tnilzon** [comment]
Thanks, that worked!

/Tomas
