### ISSUE TITLE
Is it possible to display the datetime along with the item number in the copyq clipboard

### ISSUE THREAD

**Issue by v1v3kgithub** [hluk/CopyQ#659]
Is it possible to display the datetime along with the item number in the copyq clipboard

Currently I can only see item number, next to the text/image in the clipboard, but I would also like to the timestamp of when the item was copied into the clipboard.

**Comment by hluk** [comment]
Does using [this command](https://github.com/hluk/CopyQ/wiki/Command-Examples#show-copy-time) do the job? (This will work only for newly copied items.)
