### ISSUE TITLE
Failed to start clipboard monitor

### ISSUE THREAD

**Issue by alxgoncalves** [hluk/CopyQ#660]
Hi,

I've installed CopyQ 2.9.0, Windows 10 64bit, and the clipboard entries are not captured.

The log is attached. How can I fix this?

Thanks.
[copyq.zip](https://github.com/hluk/CopyQ/files/827361/copyq.zip)

**Comment by hluk** [comment]
Can you set `COPYQ_LOG_LEVEL` environment variable to `TRACE` restart the app and share the log again? You can quickly do this from currently running CopyQ session:
- open Action dialog <kbd>F5</kbd>,
- enter following command and click OK,

```batch
cmd /c "set COPYQ_LOG_LEVEL=TRACE && %COPYQ% -s test"
```

- open the new application session from tray (it should be a dark blue icon),
- open Log <kbd>F12</kbd> -- it should now contain lot of `TRACE` and `DEBUG` entries.

**Comment by alxgoncalves** [comment]
Here is the log now:

C:/Users/Alexandre Gonçalves/AppData/Roaming/copyq-test/copyq-test/copyq.log

DEBUG [2017-03-08 11:57:39.552]: Created session mutex: copyq-test_mutex
DEBUG [2017-03-08 11:57:39.556]: Server "copyq-test_Alexandre Gon�alves_s" started.
Note [2017-03-08 11:57:39.562]: Loading plugin: c:/Program Files (x86)/CopyQ/plugins/libitemdata.dll
Note [2017-03-08 11:57:39.568]: Loading plugin: c:/Program Files (x86)/CopyQ/plugins/libitemencrypted.dll
Note [2017-03-08 11:57:39.580]: Loading plugin: c:/Program Files (x86)/CopyQ/plugins/libitemfakevim.dll
Note [2017-03-08 11:57:39.588]: Loading plugin: c:/Program Files (x86)/CopyQ/plugins/libitemimage.dll
Note [2017-03-08 11:57:39.594]: Loading plugin: c:/Program Files (x86)/CopyQ/plugins/libitemnotes.dll
Note [2017-03-08 11:57:39.605]: Loading plugin: c:/Program Files (x86)/CopyQ/plugins/libitemsync.dll
Note [2017-03-08 11:57:39.611]: Loading plugin: c:/Program Files (x86)/CopyQ/plugins/libitemtags.dll
Note [2017-03-08 11:57:39.618]: Loading plugin: c:/Program Files (x86)/CopyQ/plugins/libitemtext.dll
DEBUG [2017-03-08 11:57:39.665]: Loading configuration
DEBUG [2017-03-08 11:57:39.716]: cls: "ConsoleWindowClass"
DEBUG [2017-03-08 11:57:39.718]: Tab "&clipboard": Creating new tab
DEBUG [2017-03-08 11:57:39.719]: Tab "&clipboard": Saving 0 items
DEBUG [2017-03-08 11:57:39.721]: Tab "&clipboard": Items saved
DEBUG [2017-03-08 11:57:39.722]: Tab "&clipboard": 0 items loaded
DEBUG [2017-03-08 11:57:39.736]: Configuration loaded
DEBUG [2017-03-08 11:57:39.738]: Starting monitor.
DEBUG [2017-03-08 11:57:39.740]: Remote process: Starting new remote process "c:/Program Files (x86)/CopyQ/copyq.exe monitor copyq-test_Alexandre Gon�alves_m".
DEBUG [2017-03-08 11:57:50.821]: Window 331264 "CopyQ": Raised
ERROR [2017-03-08 11:57:55.741]: Restarting clipboard monitor (Failed to start)
DEBUG [2017-03-08 11:57:55.748]: Clipboard Monitor: Terminating
DEBUG [2017-03-08 11:57:55.752]: Clipboard Monitor: Terminated
DEBUG [2017-03-08 11:57:55.755]: Starting monitor.
DEBUG [2017-03-08 11:57:55.758]: Remote process: Starting new remote process "c:/Program Files (x86)/CopyQ/copyq.exe monitor copyq-test_Alexandre Gon�alves_m".
DEBUG [2017-03-08 11:57:59.165]: Saved window geometry Options/LogDialog_geometry_global_1920x1080: 676,213 1018x680
DEBUG [2017-03-08 11:57:59.542]: Saved window geometry Options/LogDialog_geometry_global_1920x1080: 676,213 1007x680
DEBUG [2017-03-08 11:58:05.602]: Saved window geometry Options/LogDialog_geometry_global_1920x1080: 676,213 1159x680
ERROR [2017-03-08 11:58:11.757]: Restarting clipboard monitor (Failed to start)
DEBUG [2017-03-08 11:58:11.758]: Clipboard Monitor: Terminating
DEBUG [2017-03-08 11:58:11.758]: Clipboard Monitor: Terminated
DEBUG [2017-03-08 11:58:11.759]: Starting monitor.
DEBUG [2017-03-08 11:58:11.761]: Remote process: Starting new remote process "c:/Program Files (x86)/CopyQ/copyq.exe monitor copyq-test_Alexandre Gon�alves_m".
DEBUG [2017-03-08 11:58:17.699]: Saved window geometry Options/LogDialog_geometry_global_1920x1080: 689,280 1159x680
DEBUG [2017-03-08 11:58:22.217]: Got main window close event.
DEBUG [2017-03-08 11:58:24.343]: Window 331264 "CopyQ": Raised
DEBUG [2017-03-08 11:58:25.915]: Active client threads: 0
DEBUG [2017-03-08 11:58:25.916]: Terminating remaining threads.
DEBUG [2017-03-08 11:58:25.917]: Sockets open: 0
DEBUG [2017-03-08 11:58:25.937]: Closing server.
DEBUG [2017-03-08 11:58:25.953]: Active client threads: 0
DEBUG [2017-03-08 11:58:25.954]: Terminating remaining threads.
DEBUG [2017-03-08 11:58:25.955]: Sockets open: 0
DEBUG [2017-03-08 11:58:29.308]: Created session mutex: copyq-test_mutex
DEBUG [2017-03-08 11:58:29.327]: Server "copyq-test_Alexandre Gon�alves_s" started.
Note [2017-03-08 11:58:29.329]: Loading plugin: c:/Program Files (x86)/CopyQ/plugins/libitemdata.dll
Note [2017-03-08 11:58:29.331]: Loading plugin: c:/Program Files (x86)/CopyQ/plugins/libitemencrypted.dll
Note [2017-03-08 11:58:29.332]: Loading plugin: c:/Program Files (x86)/CopyQ/plugins/libitemfakevim.dll
Note [2017-03-08 11:58:29.335]: Loading plugin: c:/Program Files (x86)/CopyQ/plugins/libitemimage.dll
Note [2017-03-08 11:58:29.339]: Loading plugin: c:/Program Files (x86)/CopyQ/plugins/libitemnotes.dll
Note [2017-03-08 11:58:29.341]: Loading plugin: c:/Program Files (x86)/CopyQ/plugins/libitemsync.dll
Note [2017-03-08 11:58:29.342]: Loading plugin: c:/Program Files (x86)/CopyQ/plugins/libitemtags.dll
Note [2017-03-08 11:58:29.344]: Loading plugin: c:/Program Files (x86)/CopyQ/plugins/libitemtext.dll
DEBUG [2017-03-08 11:58:29.371]: Loading configuration
DEBUG [2017-03-08 11:58:29.394]: cls: "ConsoleWindowClass"
DEBUG [2017-03-08 11:58:29.396]: Tab "&clipboard": Loading items
DEBUG [2017-03-08 11:58:29.397]: Tab "&clipboard": 0 items loaded
DEBUG [2017-03-08 11:58:29.418]: Configuration loaded
DEBUG [2017-03-08 11:58:29.419]: Starting monitor.
DEBUG [2017-03-08 11:58:29.421]: Remote process: Starting new remote process "c:/Program Files (x86)/CopyQ/copyq.exe monitor copyq-test_Alexandre Gon�alves_m".
DEBUG [2017-03-08 11:58:37.393]: Window 724606 "CopyQ": Raised
DEBUG [2017-03-08 11:58:41.040]: Restored window geometry Options/LogDialog_geometry_global_1920x1080: 680,242 1159x680
ERROR [2017-03-08 11:58:45.415]: Restarting clipboard monitor (Failed to start)
DEBUG [2017-03-08 11:58:45.421]: Clipboard Monitor: Terminating
DEBUG [2017-03-08 11:58:45.426]: Clipboard Monitor: Terminated
DEBUG [2017-03-08 11:58:45.430]: Starting monitor.
DEBUG [2017-03-08 11:58:45.435]: Remote process: Starting new remote process "c:/Program Files (x86)/CopyQ/copyq.exe monitor copyq-test_Alexandre Gon�alves_m".
ERROR [2017-03-08 11:59:01.445]: Restarting clipboard monitor (Failed to start)
DEBUG [2017-03-08 11:59:01.449]: Clipboard Monitor: Terminating
DEBUG [2017-03-08 11:59:01.450]: Clipboard Monitor: Terminated
DEBUG [2017-03-08 11:59:01.451]: Starting monitor.
DEBUG [2017-03-08 11:59:01.452]: Remote process: Starting new remote process "c:/Program Files (x86)/CopyQ/copyq.exe monitor copyq-test_Alexandre Gon�alves_m".
ERROR [2017-03-08 11:59:17.448]: Restarting clipboard monitor (Failed to start)
DEBUG [2017-03-08 11:59:17.452]: Clipboard Monitor: Terminating
DEBUG [2017-03-08 11:59:17.453]: Clipboard Monitor: Terminated
DEBUG [2017-03-08 11:59:17.454]: Starting monitor.
DEBUG [2017-03-08 11:59:17.455]: Remote process: Starting new remote process "c:/Program Files (x86)/CopyQ/copyq.exe monitor copyq-test_Alexandre Gon�alves_m".
ERROR [2017-03-08 11:59:33.462]: Restarting clipboard monitor (Failed to start)
DEBUG [2017-03-08 11:59:33.467]: Clipboard Monitor: Terminating
DEBUG [2017-03-08 11:59:33.472]: Clipboard Monitor: Terminated
DEBUG [2017-03-08 11:59:33.476]: Starting monitor.
DEBUG [2017-03-08 11:59:33.481]: Remote process: Starting new remote process "c:/Program Files (x86)/CopyQ/copyq.exe monitor copyq-test_Alexandre Gon�alves_m".
ERROR [2017-03-08 11:59:49.497]: Restarting clipboard monitor (Failed to start)
DEBUG [2017-03-08 11:59:49.501]: Clipboard Monitor: Terminating
DEBUG [2017-03-08 11:59:49.503]: Clipboard Monitor: Terminated
DEBUG [2017-03-08 11:59:49.503]: Starting monitor.
DEBUG [2017-03-08 11:59:49.505]: Remote process: Starting new remote process "c:/Program Files (x86)/CopyQ/copyq.exe monitor copyq-test_Alexandre Gon�alves_m".
ERROR [2017-03-08 12:00:05.510]: Restarting clipboard monitor (Failed to start)
DEBUG [2017-03-08 12:00:05.513]: Clipboard Monitor: Terminating
DEBUG [2017-03-08 12:00:05.514]: Clipboard Monitor: Terminated
DEBUG [2017-03-08 12:00:05.515]: Starting monitor.
DEBUG [2017-03-08 12:00:05.516]: Remote process: Starting new remote process "c:/Program Files (x86)/CopyQ/copyq.exe monitor copyq-test_Alexandre Gon�alves_m".
ERROR [2017-03-08 12:00:21.512]: Restarting clipboard monitor (Failed to start)
DEBUG [2017-03-08 12:00:21.516]: Clipboard Monitor: Terminating
DEBUG [2017-03-08 12:00:21.517]: Clipboard Monitor: Terminated
DEBUG [2017-03-08 12:00:21.518]: Starting monitor.
DEBUG [2017-03-08 12:00:21.519]: Remote process: Starting new remote process "c:/Program Files (x86)/CopyQ/copyq.exe monitor copyq-test_Alexandre Gon�alves_m".
ERROR [2017-03-08 12:00:37.524]: Restarting clipboard monitor (Failed to start)
DEBUG [2017-03-08 12:00:37.528]: Clipboard Monitor: Terminating
DEBUG [2017-03-08 12:00:37.528]: Clipboard Monitor: Terminated
DEBUG [2017-03-08 12:00:37.529]: Starting monitor.
DEBUG [2017-03-08 12:00:37.530]: Remote process: Starting new remote process "c:/Program Files (x86)/CopyQ/copyq.exe monitor copyq-test_Alexandre Gon�alves_m".
ERROR [2017-03-08 12:00:53.522]: Restarting clipboard monitor (Failed to start)
DEBUG [2017-03-08 12:00:53.528]: Clipboard Monitor: Terminating
DEBUG [2017-03-08 12:00:53.533]: Clipboard Monitor: Terminated
DEBUG [2017-03-08 12:00:53.537]: Starting monitor.
DEBUG [2017-03-08 12:00:53.542]: Remote process: Starting new remote process "c:/Program Files (x86)/CopyQ/copyq.exe monitor copyq-test_Alexandre Gon�alves_m".
ERROR [2017-03-08 12:01:09.543]: Restarting clipboard monitor (Failed to start)
DEBUG [2017-03-08 12:01:09.544]: Clipboard Monitor: Terminating
DEBUG [2017-03-08 12:01:09.545]: Clipboard Monitor: Terminated
DEBUG [2017-03-08 12:01:09.546]: Starting monitor.
DEBUG [2017-03-08 12:01:09.548]: Remote process: Starting new remote process "c:/Program Files (x86)/CopyQ/copyq.exe monitor copyq-test_Alexandre Gon�alves_m".
ERROR [2017-03-08 12:01:25.546]: Restarting clipboard monitor (Failed to start)
DEBUG [2017-03-08 12:01:25.550]: Clipboard Monitor: Terminating
DEBUG [2017-03-08 12:01:25.551]: Clipboard Monitor: Terminated
DEBUG [2017-03-08 12:01:25.552]: Starting monitor.
DEBUG [2017-03-08 12:01:25.553]: Remote process: Starting new remote process "c:/Program Files (x86)/CopyQ/copyq.exe monitor copyq-test_Alexandre Gon�alves_m".
ERROR [2017-03-08 12:01:41.564]: Restarting clipboard monitor (Failed to start)
DEBUG [2017-03-08 12:01:41.565]: Clipboard Monitor: Terminating
DEBUG [2017-03-08 12:01:41.566]: Clipboard Monitor: Terminated
DEBUG [2017-03-08 12:01:41.567]: Starting monitor.
DEBUG [2017-03-08 12:01:41.569]: Remote process: Starting new remote process "c:/Program Files (x86)/CopyQ/copyq.exe monitor copyq-test_Alexandre Gon�alves_m".
ERROR [2017-03-08 12:01:57.568]: Restarting clipboard monitor (Failed to start)
DEBUG [2017-03-08 12:01:57.570]: Clipboard Monitor: Terminating
DEBUG [2017-03-08 12:01:57.572]: Clipboard Monitor: Terminated
DEBUG [2017-03-08 12:01:57.574]: Starting monitor.
DEBUG [2017-03-08 12:01:57.577]: Remote process: Starting new remote process "c:/Program Files (x86)/CopyQ/copyq.exe monitor copyq-test_Alexandre Gon�alves_m".
ERROR [2017-03-08 12:02:13.568]: Restarting clipboard monitor (Failed to start)
DEBUG [2017-03-08 12:02:13.569]: Clipboard Monitor: Terminating
DEBUG [2017-03-08 12:02:13.570]: Clipboard Monitor: Terminated
DEBUG [2017-03-08 12:02:13.571]: Starting monitor.
DEBUG [2017-03-08 12:02:13.572]: Remote process: Starting new remote process "c:/Program Files (x86)/CopyQ/copyq.exe monitor copyq-test_Alexandre Gon�alves_m".
ERROR [2017-03-08 12:02:29.582]: Restarting clipboard monitor (Failed to start)
DEBUG [2017-03-08 12:02:29.583]: Clipboard Monitor: Terminating
DEBUG [2017-03-08 12:02:29.585]: Clipboard Monitor: Terminated
DEBUG [2017-03-08 12:02:29.586]: Starting monitor.
DEBUG [2017-03-08 12:02:29.588]: Remote process: Starting new remote process "c:/Program Files (x86)/CopyQ/copyq.exe monitor copyq-test_Alexandre Gon�alves_m".
ERROR [2017-03-08 12:02:45.585]: Restarting clipboard monitor (Failed to start)
DEBUG [2017-03-08 12:02:45.592]: Clipboard Monitor: Terminating
DEBUG [2017-03-08 12:02:45.611]: Clipboard Monitor: Terminated
DEBUG [2017-03-08 12:02:45.613]: Starting monitor.
DEBUG [2017-03-08 12:02:45.618]: Remote process: Starting new remote process "c:/Program Files (x86)/CopyQ/copyq.exe monitor copyq-test_Alexandre Gon�alves_m".
ERROR [2017-03-08 12:03:01.617]: Restarting clipboard monitor (Failed to start)
DEBUG [2017-03-08 12:03:01.620]: Clipboard Monitor: Terminating
DEBUG [2017-03-08 12:03:01.624]: Clipboard Monitor: Terminated
DEBUG [2017-03-08 12:03:01.627]: Starting monitor.
DEBUG [2017-03-08 12:03:01.632]: Remote process: Starting new remote process "c:/Program Files (x86)/CopyQ/copyq.exe monitor copyq-test_Alexandre Gon�alves_m".
DEBUG [2017-03-08 12:03:12.483]: Got main window close event.
ERROR [2017-03-08 12:03:17.633]: Restarting clipboard monitor (Failed to start)
DEBUG [2017-03-08 12:03:17.635]: Clipboard Monitor: Terminating
DEBUG [2017-03-08 12:03:17.637]: Clipboard Monitor: Terminated
DEBUG [2017-03-08 12:03:17.638]: Starting monitor.
DEBUG [2017-03-08 12:03:17.642]: Remote process: Starting new remote process "c:/Program Files (x86)/CopyQ/copyq.exe monitor copyq-test_Alexandre Gon�alves_m".
ERROR [2017-03-08 12:03:33.648]: Restarting clipboard monitor (Failed to start)
DEBUG [2017-03-08 12:03:33.654]: Clipboard Monitor: Terminating
DEBUG [2017-03-08 12:03:33.658]: Clipboard Monitor: Terminated
DEBUG [2017-03-08 12:03:33.662]: Starting monitor.
DEBUG [2017-03-08 12:03:33.666]: Remote process: Starting new remote process "c:/Program Files (x86)/CopyQ/copyq.exe monitor copyq-test_Alexandre Gon�alves_m".
ERROR [2017-03-08 12:03:49.663]: Restarting clipboard monitor (Failed to start)
DEBUG [2017-03-08 12:03:49.668]: Clipboard Monitor: Terminating
DEBUG [2017-03-08 12:03:49.673]: Clipboard Monitor: Terminated
DEBUG [2017-03-08 12:03:49.677]: Starting monitor.
DEBUG [2017-03-08 12:03:49.681]: Remote process: Starting new remote process "c:/Program Files (x86)/CopyQ/copyq.exe monitor copyq-test_Alexandre Gon�alves_m".
ERROR [2017-03-08 12:04:05.681]: Restarting clipboard monitor (Failed to start)
DEBUG [2017-03-08 12:04:05.686]: Clipboard Monitor: Terminating
DEBUG [2017-03-08 12:04:05.691]: Clipboard Monitor: Terminated
DEBUG [2017-03-08 12:04:05.695]: Starting monitor.
DEBUG [2017-03-08 12:04:05.699]: Remote process: Starting new remote process "c:/Program Files (x86)/CopyQ/copyq.exe monitor copyq-test_Alexandre Gon�alves_m".
ERROR [2017-03-08 12:04:21.694]: Restarting clipboard monitor (Failed to start)
DEBUG [2017-03-08 12:04:21.700]: Clipboard Monitor: Terminating
DEBUG [2017-03-08 12:04:21.706]: Clipboard Monitor: Terminated
DEBUG [2017-03-08 12:04:21.710]: Starting monitor.
DEBUG [2017-03-08 12:04:21.715]: Remote process: Starting new remote process "c:/Program Files (x86)/CopyQ/copyq.exe monitor copyq-test_Alexandre Gon�alves_m".
ERROR [2017-03-08 12:04:37.711]: Restarting clipboard monitor (Failed to start)
DEBUG [2017-03-08 12:04:37.716]: Clipboard Monitor: Terminating
DEBUG [2017-03-08 12:04:37.719]: Clipboard Monitor: Terminated
DEBUG [2017-03-08 12:04:37.721]: Starting monitor.
DEBUG [2017-03-08 12:04:37.724]: Remote process: Starting new remote process "c:/Program Files (x86)/CopyQ/copyq.exe monitor copyq-test_Alexandre Gon�alves_m".
ERROR [2017-03-08 12:04:53.733]: Restarting clipboard monitor (Failed to start)
DEBUG [2017-03-08 12:04:53.737]: Clipboard Monitor: Terminating
DEBUG [2017-03-08 12:04:53.742]: Clipboard Monitor: Terminated
DEBUG [2017-03-08 12:04:53.745]: Starting monitor.
DEBUG [2017-03-08 12:04:53.750]: Remote process: Starting new remote process "c:/Program Files (x86)/CopyQ/copyq.exe monitor copyq-test_Alexandre Gon�alves_m".
ERROR [2017-03-08 12:05:09.761]: Restarting clipboard monitor (Failed to start)
DEBUG [2017-03-08 12:05:09.764]: Clipboard Monitor: Terminating
DEBUG [2017-03-08 12:05:09.767]: Clipboard Monitor: Terminated
DEBUG [2017-03-08 12:05:09.770]: Starting monitor.
DEBUG [2017-03-08 12:05:09.776]: Remote process: Starting new remote process "c:/Program Files (x86)/CopyQ/copyq.exe monitor copyq-test_Alexandre Gon�alves_m".
ERROR [2017-03-08 12:05:25.772]: Restarting clipboard monitor (Failed to start)
DEBUG [2017-03-08 12:05:25.777]: Clipboard Monitor: Terminating
DEBUG [2017-03-08 12:05:25.782]: Clipboard Monitor: Terminated
DEBUG [2017-03-08 12:05:25.787]: Starting monitor.
DEBUG [2017-03-08 12:05:25.796]: Remote process: Starting new remote process "c:/Program Files (x86)/CopyQ/copyq.exe monitor copyq-test_Alexandre Gon�alves_m".
ERROR [2017-03-08 12:05:41.809]: Restarting clipboard monitor (Failed to start)
DEBUG [2017-03-08 12:05:41.814]: Clipboard Monitor: Terminating
DEBUG [2017-03-08 12:05:41.819]: Clipboard Monitor: Terminated
DEBUG [2017-03-08 12:05:41.823]: Starting monitor.
DEBUG [2017-03-08 12:05:41.827]: Remote process: Starting new remote process "c:/Program Files (x86)/CopyQ/copyq.exe monitor copyq-test_Alexandre Gon�alves_m".
ERROR [2017-03-08 12:05:57.836]: Restarting clipboard monitor (Failed to start)
DEBUG [2017-03-08 12:05:57.842]: Clipboard Monitor: Terminating
DEBUG [2017-03-08 12:05:57.846]: Clipboard Monitor: Terminated
DEBUG [2017-03-08 12:05:57.850]: Starting monitor.
DEBUG [2017-03-08 12:05:57.855]: Remote process: Starting new remote process "c:/Program Files (x86)/CopyQ/copyq.exe monitor copyq-test_Alexandre Gon�alves_m".
ERROR [2017-03-08 12:06:13.849]: Restarting clipboard monitor (Failed to start)
DEBUG [2017-03-08 12:06:13.850]: Clipboard Monitor: Terminating
DEBUG [2017-03-08 12:06:13.851]: Clipboard Monitor: Terminated
DEBUG [2017-03-08 12:06:13.852]: Starting monitor.
DEBUG [2017-03-08 12:06:13.854]: Remote process: Starting new remote process "c:/Program Files (x86)/CopyQ/copyq.exe monitor copyq-test_Alexandre Gon�alves_m".
ERROR [2017-03-08 12:06:29.851]: Restarting clipboard monitor (Failed to start)
DEBUG [2017-03-08 12:06:29.853]: Clipboard Monitor: Terminating
DEBUG [2017-03-08 12:06:29.856]: Clipboard Monitor: Terminated
DEBUG [2017-03-08 12:06:29.859]: Starting monitor.
DEBUG [2017-03-08 12:06:29.863]: Remote process: Starting new remote process "c:/Program Files (x86)/CopyQ/copyq.exe monitor copyq-test_Alexandre Gon�alves_m".
DEBUG [2017-03-08 12:06:35.917]: Opened session mutex: copyq-test_mutex
DEBUG [2017-03-08 12:06:35.918]: Server "copyq-test_Alexandre Gon�alves_s" already running!
Warning [2017-03-08 12:06:35.919]: O servidor CopyQ já está em execução.
DEBUG [2017-03-08 12:06:40.004]: Window 724606 "CopyQ": Raised
ERROR [2017-03-08 12:06:45.866]: Restarting clipboard monitor (Failed to start)
DEBUG [2017-03-08 12:06:45.867]: Clipboard Monitor: Terminating
DEBUG [2017-03-08 12:06:45.868]: Clipboard Monitor: Terminated
DEBUG [2017-03-08 12:06:45.869]: Starting monitor.
DEBUG [2017-03-08 12:06:45.870]: Remote process: Starting new remote process "c:/Program Files (x86)/CopyQ/copyq.exe monitor copyq-test_Alexandre Gon�alves_m".
DEBUG [2017-03-08 12:06:46.353]: Window 724606 "CopyQ": Raised
DEBUG [2017-03-08 12:06:47.546]: Active client threads: 0
DEBUG [2017-03-08 12:06:47.547]: Terminating remaining threads.
DEBUG [2017-03-08 12:06:47.548]: Sockets open: 0
DEBUG [2017-03-08 12:06:47.574]: Closing server.
DEBUG [2017-03-08 12:06:47.587]: Active client threads: 0
DEBUG [2017-03-08 12:06:47.588]: Terminating remaining threads.
DEBUG [2017-03-08 12:06:47.589]: Sockets open: 0
DEBUG [2017-03-08 12:06:49.772]: Created session mutex: copyq-test_mutex
DEBUG [2017-03-08 12:06:49.776]: Server "copyq-test_Alexandre Gon�alves_s" started.
Note [2017-03-08 12:06:49.778]: Loading plugin: c:/Program Files (x86)/CopyQ/plugins/libitemdata.dll
Note [2017-03-08 12:06:49.779]: Loading plugin: c:/Program Files (x86)/CopyQ/plugins/libitemencrypted.dll
Note [2017-03-08 12:06:49.781]: Loading plugin: c:/Program Files (x86)/CopyQ/plugins/libitemfakevim.dll
Note [2017-03-08 12:06:49.783]: Loading plugin: c:/Program Files (x86)/CopyQ/plugins/libitemimage.dll
Note [2017-03-08 12:06:49.785]: Loading plugin: c:/Program Files (x86)/CopyQ/plugins/libitemnotes.dll
Note [2017-03-08 12:06:49.786]: Loading plugin: c:/Program Files (x86)/CopyQ/plugins/libitemsync.dll
Note [2017-03-08 12:06:49.787]: Loading plugin: c:/Program Files (x86)/CopyQ/plugins/libitemtags.dll
Note [2017-03-08 12:06:49.789]: Loading plugin: c:/Program Files (x86)/CopyQ/plugins/libitemtext.dll
DEBUG [2017-03-08 12:06:49.816]: Loading configuration
DEBUG [2017-03-08 12:06:49.843]: cls: "ConsoleWindowClass"
DEBUG [2017-03-08 12:06:49.846]: Tab "&clipboard": Loading items
DEBUG [2017-03-08 12:06:49.846]: Tab "&clipboard": 0 items loaded
DEBUG [2017-03-08 12:06:49.869]: Configuration loaded
DEBUG [2017-03-08 12:06:49.870]: Starting monitor.
DEBUG [2017-03-08 12:06:49.872]: Remote process: Starting new remote process "c:/Program Files (x86)/CopyQ/copyq.exe monitor copyq-test_Alexandre Gon�alves_m".
DEBUG [2017-03-08 12:06:51.818]: Window 1444962 "CopyQ": Raised


Thanks.

**Comment by hluk** [comment]
Hmm, still not sure what could be wrong, I've never seen this behavior.

Can you test this with [new portable version](https://ci.appveyor.com/project/hluk/copyq/build/job/g63sjgya4pw1bjxl/artifacts)?

**Comment by alxgoncalves** [comment]
I can't download the portable version. Your link goes to a page without any file link....

**Comment by hluk** [comment]
Sorry the content of the page changed. Here is correct [link](https://ci.appveyor.com/project/hluk/copyq/build/1.2.854/job/g63sjgya4pw1bjxl/artifacts).

**Comment by alxgoncalves** [comment]
The portable version works! I replaced the files of the installed version with the files from the portable and everything works.

**Comment by hluk** [comment]
Glad to hear it's fixed. Though I wonder what the problem was -- maybe just some issue with permissions.
