### ISSUE TITLE
Quick access to an item by number

### ISSUE THREAD

**Issue by mleg** [hluk/CopyQ#662]
How can I access an item _by number_ with keyboard?
Not by moving arrows through the list but with just a keystroke.

For example, in a similar Win/OSX app Ditto, **when you press a number key (0-9), it is supposed that you are selecting an item by number rather than performing search**. Which seems natural and very convenient.

One case it's needed for is when one copies few things and then "loops" through them to paste (into another app/place) by pressing the same number key over and over.
Please somebody implement such a feature. I can't CPP.

**Comment by hluk** [comment]
Fixed. This feature was accidentally removed some years ago. No-one complained until now :).

**Comment by mleg** [comment]
Oh thank you very much!
