### ISSUE TITLE
Windows: After changing tabs, paste after pressing enter only works the second time

### ISSUE THREAD

**Issue by ptwentypt** [hluk/CopyQ#665]
Hi,

Thank you for such a great clipboard manager!
Version: 2.9.0, Windows 10

I have Paste to Current Window = ON on History Tab in Preferences.
It works flawless if I'm always in the same Tab.

But if I switch Tabs, the first time I press enter the copyq window goes out of focus and nothing is Pasted in the app I was working on. If I go back to CopyQ and press Enter it will paste OK, and will always work until I change Tabs again.

Is this by design?

I tried to replicate the command as a workaround but I cannot get it to work in case I have multiple items selected. selecteditems() will always return 0,1,2... not the rows selected.

```ini
[Command]
Name=Paste
Command="
    copyq:
    
    tab(selectedtab())
    
    items = selecteditems()
    if (items.length > 1) {
       text=''
        for (i in items) {
            text += str(read(i))
            //popup('Teste',i)
        }
        copy(text)
    } else {
        select(items[0])
    }
    
    hide();
    paste();"
InMenu=true
Icon=\xf0ea
```

Thank you,
Pedro S.

**Comment by hluk** [comment]
It should be already fixed in git master branch (#655). You can try [this version](https://ci.appveyor.com/project/hluk/copyq/build/1.2.876/job/2apemj1k428jc7g6/artifacts).

The command looks OK except the loop should look like this:

```js
for (i in items) {
    row = items[i]
    text += str(read(row))
}
```

(This thing always gets me JavaScript.)

**Comment by ptwentypt** [comment]
Hi @hluk ,

Thanks for such a quick response. I confirm it's solved in master branch #655 . :)

You're right of course... Thank you for clearing that up for me.
Just a quick note about this. In the command examples at the [WIKI](https://github.com/hluk/CopyQ/wiki/Command-Examples), in the Paste And Forget section I guess it sufers from the same evil :)

Thank you again,
Pedro S.

**Comment by hluk** [comment]
@ptwentypt Yes, you're right :). I fixed the command on wiki. Thanks for pointing that out.

**Comment by extrealm** [comment]
Hi, Launchpad ppa does not provide for 14.04 while download section provides .deb, can we update?

 

Best regards,

Austin.

 

Austin Shin | Sr. Staff Engineer, Manager, Wireless Republic Korea | +82-10-8972-5208 | skype:  <mailto:extrealm@gmail.com> extrealm@gmail.com

**Comment by hluk** [comment]
@extrealm What does it have to do with this issue? Maybe you're replying to wrong e-mail.

I need to build version for Ubuntu 14.04 with old Qt 4. This means using different package source files than those in repository. I'll try to upload the package to launchpad but I don't think I can keep the compatibility with old Qt for much longer.

**Comment by extrealm** [comment]
Oh, sorry, I did replied to the [PR-663](https://github.com/hluk/CopyQ/pull/663) email, but it seems updated wrong here.

**Comment by hluk** [comment]
@extrealm The package should be uploaded now. Send me an e-mail directly if there are any issues.
