### ISSUE TITLE
FAQ #9 mentions "paste as plain text" via shift-enter, but feature has disappeared?

### ISSUE THREAD

**Issue by ScottRochford** [hluk/CopyQ#667]
https://github.com/hluk/CopyQ/wiki/FAQ#9

Am I missing something here?  I used to use this feature a lot in 2.5.0, missing in 2.9.0.

**Comment by hluk** [comment]
Did you add the `Paste as Plain Text` command in Command dialog <kbd>F6</kbd>?

**Comment by ScottRochford** [comment]
I did not... maybe I did that in 2.5.0?  Was it there by default?  Just added it now and it works of course.  :-)

I guess that leads me to another question - when I updated from 2.5.0 to 2.9.0, why were all of my settings lost?

**Comment by hluk** [comment]
Whoa, even though version 2.5.0 is really old, losing configuration shouldn't happen. There were lots of changes since then, mainly some different handling of configuration on Windows -- that's probably the culprit. Sorry for the inconvenience.

**Comment by ScottRochford** [comment]
No worries, thanks!
