### ISSUE TITLE
disable tray search bar

### ISSUE THREAD

**Issue by cdpb** [hluk/CopyQ#669]
I am running CopyQ 2.9.0 on Fedora 25.

I don't have a real problem, but I am used to open the tray and press the number of entry that I want to copy - with the latest update, that's not possible anymore because you'll search for the number, rather than selecting anything.

Is it possible to implement a checkbox to disable the tray search bar?

Cheers

**Comment by cdpb** [comment]
Great! Thanks

**Comment by hluk** [comment]
No problem. I didn't add option to disable the search but you should be able to activate items by pressing digit key as before.
