### ISSUE TITLE
Two issues with paste clipboard as plain text

### ISSUE THREAD

**Issue by Kzer-Za** [hluk/CopyQ#670]
1. Whatever the shortcut for this action in menu (then the main window is open), it does not paste plain text, just clears the formatting and puts the text in clipboard, but then I have to manually close the main window and insert the text with Ctrl+V. All the options in History tab in "After item is activated..." section are checked, and with simply selecting the item and pressing Enter (or double clicking) it works, but not when I try to paste something as plain text. And I tried assigning different shortcuts to it.

2. For some reason a global shortcut for this action is not working with Ctrl+Insert combination. Every other combination (out of those that I checked) works, but Ctrl+Insert does nothing - it does not even clear the formatting and put the text in clipboard as with the issue above - simply nothing happens. I checked that no global shortcuts are interfering with Ctrl+Insert. Can't understand what is so special about this combination.

CopyQ version is 2.8.1, system is Linux.

**Comment by hluk** [comment]
I just fixed the issue with Ctrl+Insert.

Can you test the other issue with CopyQ 2.9.0? If you are on Ubuntu you can use [official PPA](https://github.com/hluk/CopyQ#ubuntu) to keep the app up-to-date.

**Comment by Kzer-Za** [comment]
I am on Manjaro, so I installed it from AUR :)

However, the issue with the shortcut in menu stays. Moreover, the issue with Ctrl+Insert on my systems stays too. I've tried uninstalling, deleting ~/.config/copyq directory and reinstalling again, then with clean config adding this action from presets in F6 menu. Even this didn't help.

**Comment by hluk** [comment]
You will need to install `copyq-git` package to get the new fix.

Do you use "Paste as Plain Text" command? There is similar command "Paste clipboard as plain text" but it only pastes what's currently in clipboard -- i.e. it should be triggered without activating main window on tray menu.

**Comment by Kzer-Za** [comment]
> You will need to install copyq-git package to get the new fix.

Thanks, after installing copyq-git the issue with the menu was resolved.

> Do you use "Paste as Plain Text" command?

Yes, that's what I was using - sorry, did not notice that there are two slightly different commands. I just manually ticked in it the checkbox "Global shortcut" and selected a key combination. What's strange is that it _was_ working for all the shortcuts but the Ctrl+Insert! As I understand now, it was kind of unplanned behaviour, now for this command no global shortcut is working (as it, as far as I understand, should be). I added the command "Paste clipboard as plain text" and assigned for it global shortcut Ctrl+Insert - and it's working.

Probably there should be some hint to avoid trying using one of these commands in the role of the other, something that would inform the user that for pasting plain text outside the main CopyQ window he needs one command, and for use in menu, another.

**Comment by hluk** [comment]
This is also why in CopyQ 2.9.0 you need to click on "Show Advanced" in Command dialog to be able to set anything that was unintended for given command -- by default you can only set Shortcut or Global Shortcut (depending on command type).

I should probably rename the command to "Paste **Item** as Plain Text" and "Shortcut" to "Application Shortcut".

**Comment by Kzer-Za** [comment]
I'm sorry for a newbie question, should I close the issue now or do you close it as the repository owner?

**Comment by hluk** [comment]
Sure, you can close the issue if the problems are resolved.

**Comment by Kzer-Za** [comment]
Okay, I'm closing it now. Thanks for fixing it so quickly!
