### ISSUE TITLE
Windows: Incorrect configuration folder for portable version

### ISSUE THREAD

**Issue by royharoush** [hluk/CopyQ#671]
Hi,
When copying my configuration folder into a portable 2.9.0 folder, i get the correct tab structure, just with empty tabs. 
I'm unable to upload the photos, please see links to imgur 

https://i.imgur.com/478PqDL.png
https://i.imgur.com/q73JrwS.png

**Comment by hluk** [comment]
This seems to be an ugly bug.

Configuration folder for version 2.8.3 and earlier is "...\config\copyq\" but for 2.9.0 it's "...\config\copyq\\**copyq\\**".

I'm fixing it. Thanks for the report.
