### ISSUE TITLE
Can't edit rich text copied from MS PowerPoint, LibreOffice Impress etc

### ISSUE THREAD

**Issue by grengray** [hluk/CopyQ#672]
Hello!
CopyQ the best clipboard manager but it can't edit rich text copied from MS PowerPoint, LibreOffice Impress etc.
Fix this bug please.

**Comment by hluk** [comment]
Does this mean that you can only edit plain text?

Can you check if the item has HTML data? (You can do this by selecting the item and opening Content dialog with <kbd>F4</kbd> shortcut -- there should be `text/html` in the list of formats.)
