### ISSUE TITLE
Missing first item in snippet dialog dropdown menu.

### ISSUE THREAD

**Issue by p1tt1** [hluk/CopyQ#675]
If I use your Snippet

```
[Command]
Command="
    copyq:
    stuff = [
    'Hello,\\n',

    'Time ' + dateString('yyyy-MM-dd hh:mm:ss'),

    'Best regards,\\n'
    + (str(env('USER')) || str(env('USERNAME'))),
    ]

    var text = dialog('Insert', stuff)
    if (!text)
      abort()

    copy(text)
    paste()
    "
GlobalShortcut=meta+alt+i
Icon=\xf040
Name=Insert Stuff
```
the fist item `'Hello,\\n',` is missed within the dropdown menu. So I can't select the first item after selecting an other.

**Comment by hluk** [comment]
The first item in array passed to `dialog()` is current text for selection box, rest are items in the selection list. So the command should be:

```ini
[Command]
Command="
    copyq:
    stuff = [
    'Hello,\\n',

    'Time ' + dateString('yyyy-MM-dd hh:mm:ss'),

    'Best regards,\\n'
    + (str(env('USER')) || str(env('USERNAME'))),
    ]

    var text = dialog('Insert', stuff[0].concat(stuff))
    if (!text)
      abort()

    copy(text)
    paste()
    "
GlobalShortcut=meta+alt+i
Icon=\xf040
Name=Insert Stuff
```

**Comment by p1tt1** [comment]
ah... ok.
It works, but isn't intuitive.

**Comment by hluk** [comment]
Yeah, it's not intuitive, I often forgot that the first argument needs to be twice in the list. I'll try to change this -- though it'll probably break current behavior.

**Comment by p1tt1** [comment]
mh...
this workaround create on String with all items...

**Comment by hluk** [comment]
Well, if all items of from the array would be in the selection list you would need to move an item to the front if you want it to be the default one (this is useful for remembering the last selection when the dialog is open again). Currently you only need to prepend the default text to the array.
