### ISSUE TITLE
automatic command stopped working

### ISSUE THREAD

**Issue by m4r71n** [hluk/CopyQ#676]
Hi @hluk,
today I've tried https://ci.appveyor.com/project/hluk/copyq/build/1.2.915 and at least one of my automatic commands is not executed anymore. I can confirm that https://ci.appveyor.com/project/hluk/copyq/build/1.2.910 is working.
The following command transforms copied Jira issue titles
```
[Command]
Name=JIRA \"ISSUE: TITLE\"
Match=^\\s*([A-Z]+\\-[0-9]+)\\s+(.+)$
Window=- Mozilla Firefox
Command="
    copyq:
    var temp = str(input()).trim().replace(/^([A-Z]+\\-[0-9]+)\\s+(.+)$/, '$1: $2')
    add(temp)
    copy(temp)"
Input=text/plain
Automatic=true
InMenu=true
Icon=\xf0c1
```
from this
```
   TEST-123

title of issue
```
to this
```
TEST-123: title of issue
```
I've also noticed that commands with `Type of Action` `In Menu` are not shown in the menu if `Window` is set to a value like `- Mozilla Firefox` under `Match Items`. Maybe for `In Menu` commands this option should be ignored?

**Comment by hluk** [comment]
OK, fixed. Thanks for the heads up.

>Maybe for `In Menu` commands this option should be ignored?

I expected an `In Menu` command to be run only from application window. But since it can be launched from tray menu I guess it shouldn't ignore `Window`. I'll try to refactor the commands a bit more.

**Comment by m4r71n** [comment]
Thank you very much! Confirmed that it is fixed.
I've used the `In Menu` option in addition to the `Automatic` option to easier test my automatic commands. There is only one automatic command for which I've set `Window` to a value. That's why I've noticed this not until now.
