### ISSUE TITLE
Auto convert text encoding to utf-8 when copying

### ISSUE THREAD

**Issue by amosbird** [hluk/CopyQ#679]
When copying from pdf files, non unicode characters are not stored correctly inside copyq. Can I auto convert the encodings to utf8 via command?

**Comment by hluk** [comment]
I don't think it's currently possible. I'll add a function to convert the data to UTF8.

What PDF app do you use? Perhaps CopyQ should detect the encoding automatically.

**Comment by amosbird** [comment]
I don't think it's related to pdf applications. I tried chrome, firefox, sumatra in vbox windows, foxit reader and evince.

**Comment by hluk** [comment]
Can you share the PDF or clipboard content (e.g. with `copyq clipboard | xxd`)?

**Comment by amosbird** [comment]
It's  `00000000: c292 47c3 9fc2 8220 cca7 c295 c3a0 c3a1  ..G.... ........`

**Comment by hluk** [comment]
I've added the encoding conversion functions.

Here are binaries for Windows: https://ci.appveyor.com/project/hluk/copyq/build/1.2.924/job/mga239aihgplip24/artifacts

You can use following command to automatically covert clipboard text data to unicode (copy the code to command list in Command dialog; change the encoding and window title).

```ini
[Command]
Automatic=true
Command="
    copyq:
    var encoding = 'utf16'
    var textData = clipboard()
    var text = toUnicode(textData, encoding)
    setData(mimeText, text)
    copy(text)"
Icon=\xf016
Input=text/plain
Name=Change Encoding
Window=\\.pdf
```

Perhaps you don't even need this if clipboard contains MIME like `text/html;charset=utf-8` (you can list clipboard formats with `copyq clipboard '?'`).

Sometimes it isn't possible to copy a text from some PDFs. In that case you can try OCR with ImageMagick and Tesseract.

```ini
[Command]
Command="
    import png:- | convert png:- -colorspace Gray -depth 8 -resample 200x200 tif:- | tesseract stdin stdout | copyq copy -"
GlobalShortcut=meta+ctrl+s
Icon=\xf016
Name=OCR
```

**Comment by amosbird** [comment]
Thanks! I just used this command in a non-unicode pdf and  I got the following error,
```
Command “copyq: var encoding …xt, text) copy(text)”
Exit code: 1
CopyQ ERROR [2017-03-27 17:44:53.069]: ReferenceError: Can't find variable: toUnicode
CopyQ ERROR [2017-03-27 17:44:53.069]:    --- backtrace ---
CopyQ ERROR [2017-03-27 17:44:53.069]:    <eval>() at 4
CopyQ ERROR [2017-03-27 17:44:53.069]:    eval([object Object]) at -1
CopyQ ERROR [2017-03-27 17:44:53.069]:    <global>() at -1
CopyQ ERROR [2017-03-27 17:44:53.069]:    --- end backtrace ---

---
copyq: 
var encoding = 'utf8'
var textData = clipboard()
var text = toUnicode(textData, encoding)
setData(mimeText, text)
copy(text)
---

```

**Comment by amosbird** [comment]
Well, I grabbed the master copyq from aur. The copied text looks like this `迫莪諨겣`   . It's still mal-encoded.

**Comment by hluk** [comment]
There is `copyq-git` package in AUR which should contain the fix.

**Comment by hluk** [comment]
Did you change the encoding? UTF-8 is the default used by application, you need to change it to the encoding of the original text.

**Comment by amosbird** [comment]
Huh? Which encoding should I change? I did make `utf-16` to `utf-8` and `gbk`, neither work. I was thinking it should automatically recognize the original text's encoding.

**Comment by hluk** [comment]
It's not possible to recognize the encoding automatically (or at least not easy; `enca` fails to do this).

Coverting the text data you provided from `gbk` prints:
```ini
> echo '00000000: c292 47c3 9fc2 8220 cca7 c295 c3a0 c3a1' | xxd -r | copyq 'toUnicode(input(), "gbk")'
聮G脽聜 抬聲脿谩
```

Are you sure that the text copied from PDF is correct -- e.g. can you paste it to an editor which supports unicode.

**Comment by amosbird** [comment]
Um, I'm confused now. Here is the problematic [document](https://paste.wentropy.com/oMw9) .  Can you copy the text correctly from it?

**Comment by hluk** [comment]
No, I cannot copy text from that document (not in Evince, Chromium or Firefox) -- it copies some garbage.

Workaround is to use text recognition with Tesseract. Though this may not be very reliable and may take a while to run. You have to install `imagemagick`, `tesseract` and `tesseract-data-chi_tra`, `tesseract-data-chi_sim` (and possibly other data packages).

Then use command:

```ini
[Command]
Command="
    import png:- | convert png:- -colorspace Gray -depth 8 -resample 200x200 tif:- | copyq:
    var language = 'eng'
    
    var imageData = input()
    var result = execute('tesseract', '--list-langs')
    var languages = str(result.stdout).split('\\n').slice(1)
    
    language = dialog(
      '.title', 'Pick Language',
      '.defaultChoice', language,
      'Language', languages)
    if (!language)
      abort()
    
    result = execute('tesseract', '-l', language, 'stdin', 'stdout', null, imageData)
    add(result.stdout)
    copy(result.stdout)"
GlobalShortcut=meta+ctrl+s
Icon=\xf1ea
Name=Copy Text in Image
```

It doesn't actually be a command in CopyQ:

```bash
import png:- | convert png:- -colorspace Gray -depth 8 -resample 200x200 tif:- | tesseract -l chi_tra stdin stdout | xclip -i -selection CLIPBOARD
```

**Comment by amosbird** [comment]
Ok, so it's not an encoding issue then. Thanks for your kindly help.
