### ISSUE TITLE
Search and Paste: how can I move a searched item back to position 0?

### ISSUE THREAD

**Issue by orschiro** [hluk/CopyQ#680]
Dear all, 

I am using the following command to search and paste from my clipboard history. 

However, when doing so, the pasted entry is not added back to position 0 in the tray icon list. 

How can I change that?

Yours,

Robert

```
copyq:
var title = 'Search and Paste'

// Read search history tab.
tab('Search')
var history = ['', '']

for (var i = 0; i < count(); ++i) {
  var text = str(read(i))
  history.push(text)
}

// Ask user for search expression (case insensitive).
var what = dialog(
  '.title', title,
  'Search', history)
if (!what)
  abort()

add(what) // Store new search to history tab.

what = str(what).toLowerCase()

// Tab to search.
var tab_name = config('clipboard_tab')
if (!tab_name)
  tab_name = tab()[0]
tab(tab_name)

// Search items.
var matches = []
for (var i = 0; i < count(); ++i) {
  var text = str(read(i))
  if (text.toLowerCase().indexOf(what) != -1)
    matches.push(text)
}

// Nothing found?
if (matches.length == 0) {
  popup(
    'Search failed!',
    'Item containing "' + what + '" was not found.')
  abort()
}

var match = matches[0]

// If multiple items matches, show selection dialog.
if (matches.length > 1) {
  var i = dialog(
    '.title', title,
    '.label', matches.length + ' items were found. Select one to paste.',
    '.style', 'QListWidget{font-family:mono}',
    '.list:', matches)
  if (!i)
    abort()
  match = matches[i]
}

// Paste matched item.
copy(match)
paste()
```

![image](https://cloud.githubusercontent.com/assets/170947/24353554/6250cb24-12ee-11e7-9601-2ad5e05ec401.png)

**Comment by hluk** [comment]
If you call `copy()` it won't add new item (or move existing), neither will it execute any automatic commands.

You have to either know the item row and call `select(row)` (which moves item depending on settings) or copy the item using `execute('xclip', '-i', '-selection', 'CLIPBOARD', null, match)` -- this will move an item which matches clipboard content in the tab which is set to store clipboard content.

**Comment by orschiro** [comment]
Thank you! So, basically this?

```
- copy(match)
+ execute('xclip', '-i', '-selection', 'CLIPBOARD', null, match)
```

**Comment by hluk** [comment]
Yes, but if the item contains tags or notes it won't be moved to top because it differs from the clipboard content.

I think this would be much easier if you search items in main window or menu. I do quite often:
- open main window with shortcut ("Show/hide main window" shortcut),
- start typing to search an item,
- select item with enter.

Similarly with menu ("Show tray menu" or command `copyq menu [TABNAME] [ITEMCOUNT]`).

Search history can be enabled with "Save Filter History" in General config tab. But it only works in main window and I never found this very useful, only annoying.

**Comment by orschiro** [comment]
Dear @hluk,

Apologies for my late reply. 

> open main window with shortcut ("Show/hide main window" shortcut),

Can you please clarify this point? I cannot find this shortcut.

![image](https://cloud.githubusercontent.com/assets/170947/24581940/7d8fd2fa-1725-11e7-8205-098a6504340e.png)

**Comment by hluk** [comment]
Global/System shortcuts can be set only in Command dialog -- click "Custom Actions and Global Shortcuts" button in Shortcuts configuration tab or press <kbd>F6</kbd> in main window. In the dialog click Add button, select command and assign shortcut. See also [FAQ](https://github.com/hluk/CopyQ/wiki/FAQ#13).

**Comment by orschiro** [comment]
I found it. 

Thank you so much!

I will see if I can internalise this new habit of using the main window. :-)

Yours,

Robert

**Comment by hluk** [comment]
I should probably make the global shortcut configuration easier to find :).
