### ISSUE TITLE
Issues with Amperstamps in the interface?

### ISSUE THREAD

**Issue by orschiro** [hluk/CopyQ#683]
Dear all,

I am not entirely sure if this is intentional or not. 

![image](https://cloud.githubusercontent.com/assets/170947/24604920/1bb64904-1867-11e7-8f81-3ad6c7f91bf1.png)

**Comment by hluk** [comment]
It's intentional. Though it probably shouldn't be in the name of the command.

Ampersands in tab names are described in [wiki](https://github.com/hluk/CopyQ/wiki/Advanced-Usage#tabs).

**Comment by orschiro** [comment]
I see. Well, good that it is already documented. 

Thank you! :-)
