### ISSUE TITLE
Paste/copy item in order which they are selected

### ISSUE THREAD

**Issue by m4r71n** [hluk/CopyQ#684]
Windows 10 x64 and CopyQ 3.0.0

- Copy `1`, `2` and `3`
- Open main window and select from bottom to top `1`, `2` and `3` and hit enter
- `1`,`3`,`2` will be pasted instead of `1`,`2`,`3`

**Comment by hluk** [comment]
It's implemented so that the order should be `3`,`2`,`1` (from the first selected to last; #517). But it seems the selection model in Qt gives wrong result if I let Qt it handle the key presses -- works OK with mouse.

**Comment by hluk** [comment]
I fixed the selection order (d3c919ddab5eb3d36a1933600c4b929dda464ea7). Though selection is not sorted but in the order you select the items (as in previous versions).

**Comment by m4r71n** [comment]
@hluk incredibly fast fixed! Thank you very much
