### ISSUE TITLE
Can CopyQ use native notifications?

### ISSUE THREAD

**Issue by orschiro** [hluk/CopyQ#688]
Dear all, 

I am wondering whether CopyQ can use native notifications for better desktop integration instead of its custom ones shown below?

![native notifications](https://cloud.githubusercontent.com/assets/170947/25007313/4f199732-2060-11e7-82d4-dbd677540e4c.png)

**Comment by hluk** [comment]
AFAIK, there is no simple way to use native notifications on all platforms.

On Linux you can do use instead of `popup()` or `notification()` the following code.

```js
execute('notify-send', title, message)
```

See `notify-send --help` for more info about arguments.

**Comment by orschiro** [comment]
Thank you, @hluk.

Do I have to compile the code with this modification or is this something I can apply after installing the package?

**Comment by hluk** [comment]
What I meant is: You have to change the commands which use notifications (no need to recompile the source code).

In most cases it should be enough to add following line at start of a command (the second line).

```js
copyq:
function popup(title, message) { execute('notify-send', title, message); }
```

This will override `popup()` function and use native notifications instead.

**Comment by orschiro** [comment]
@hluk, thank you!

I finally understood what you meant and updated my commands to make use of native notifications. :-)

Very cool!

**Comment by hluk** [comment]
Closing; New issues to use native notifications: #1503
