### ISSUE TITLE
v3.0.0 Windows Portable - Tab contents are not being saved when CopyQ is exited gracefully

### ISSUE THREAD

**Issue by carlitorendon** [hluk/CopyQ#689]
Hello CopyQ team,

With v3.0.0, standalone when CopyQ exists gracefully, tab contents are not being saved. 

This is not an issue with the previous standalone version v2.9.0

Let me know if you need logs or something else.

Thanks for the amazing work,
CLR

**Comment by hluk** [comment]
I cannot reproduce this. So definitely share the log (from menu Help - Show Log <kbd>F12</kbd>) and steps to reproduce. Thanks.

**Comment by carlitorendon** [comment]
@hluk Thank you for pointing me to the logs. It seems it that CopyQ lacks access to write:

`Note [2017-04-16 14:18:29.814] Server-15624: Loading plugin: C:/Program Files (x86)/CopyQ/copyq-v3.0.0/plugins/libitemtext.dll
ERROR [2017-04-16 14:18:38.456] Server-15624: Cannot save tab “&clipboard” to “C:/Program Files (x86)/CopyQ/copyq-v3.0.0/config/copyq/copyq_tab_JmNsaXBib2FyZA==.dat” (Access is denied.
ERROR [2017-04-16 14:18:38.456] Server-15624:    )!`

The portable version is inside Program Files (x86); but it is interesting that only v3 is doing this; v2.9 is not.

I guess this is a non-issue
