### ISSUE TITLE
v3.0.0 Windows Portable - Rendering glitch after using "Move to Bottom" keyboard shortcut

### ISSUE THREAD

**Issue by carlitorendon** [hluk/CopyQ#690]
Hello CopyQ team:

1. Remap your "Move to Bottom" action to be CTRL + k (I don't know if this is indispensable but it is part of what i did)
2. Have a tab (it could be the clipboard one) that has at least 3 items.
3. Try to move an item to the bottom
4. Notice how the rendering gets screwed (with some items not displaying their contents). See snapshot below:
![image](https://cloud.githubusercontent.com/assets/14046845/25073987/cf7a85ae-22b7-11e7-9d48-9cf973b54cb1.png)

This doesn't happen if you use the mouse / context menu. 

Also if you do another action (after the rendering is screwed up), the rendering fixes itself;
This was not a problem on v2.9.0

Checked the logs and there's nothing worth pasting here. 

Let me know if you have any questions.

CLR

**Comment by hluk** [comment]
[Fixed version](https://ci.appveyor.com/project/hluk/copyq/build/1.2.965/job/cl2ky96skqhwyhrq/artifacts).
