### ISSUE TITLE
Always copy and past as plain text?

### ISSUE THREAD

**Issue by orschiro** [hluk/CopyQ#692]
Dear all, 

I might have just missed the option or setting, but is there a way to always copy and paste as plain text without any formatting applied?

Yours,

Robert

**Comment by hluk** [comment]
It might be possible to override normal paste shortcut with "Paste clipboard as plain text" command (it's available under Add button in Command dialog <kbd>F6</kbd>).

Perhaps more reliable way is to remove any HTML when copied with following command.

```ini
[Command]
Automatic=true
Command="
    copyq:
    if (dataFormats().indexOf(mimeHtml)) {
      removeData(mimeHtml)
      copy(mimeText, data(mimeText))
    }"
Icon=\xf031
Input=text/plain
Name=Ignore HTML
```

**Comment by orschiro** [comment]
This is really cool. Thank you, @hluk! :-)

**Comment by orschiro** [comment]
@hluk, one last question:

Can the above command also only be applied to items selected from the tray icon?

![image](https://cloud.githubusercontent.com/assets/170947/25386903/39777058-29c9-11e7-8262-e3e30b64f908.png)

**Comment by hluk** [comment]
You have to remove the HTML format before pasting it or paste it from application window with "Paste as  Plain Text" command.

To remove HTML from all items in list:
- open application window,
- select all items with <kbd>Ctrl</kbd>+<kbd>A</kbd>,
- open Action dialog with <kbd>F5</kbd>,
- enter `copyq:removeData(mimeHtml)` in Command field (leave other fields empty),
- and press OK.

**Comment by orschiro** [comment]
Thanks for the addition, @hluk!

I have to do these steps manually, correct?

There is no way to apply this to all items in that tray icon list automatically?

**Comment by hluk** [comment]
The command at the top here creates new clipboard items without the HTML format so you only need to remove it from existing items once.

**Comment by orschiro** [comment]
Thank you again!

I guess that is now all I needed. :-)

**Comment by yisuixinq** [comment]
> It might be possible to override normal paste shortcut with "Paste clipboard as plain text" command (it's available under Add button in Command dialog F6).
> 
> Perhaps more reliable way is to remove any HTML when copied with following command.
> 
> ```ini
> [Command]
> Automatic=true
> Command="
>     copyq:
>     if (dataFormats().indexOf(mimeHtml)) {
>       removeData(mimeHtml)
>       copy(mimeText, data(mimeText))
>     }"
> Icon=\xf031
> Input=text/plain
> Name=Ignore HTML
> ```

when I use this script, sometimes the result is not what is expected.
![copyq](https://user-images.githubusercontent.com/40953718/231446466-fc786e7a-3d48-4c6b-b3ee-078d1a8d8b5c.gif)

**Comment by pirog-x** [comment]
> It might be possible to override normal paste shortcut with "Paste clipboard as plain text" command (it's available under Add button in Command dialog F6).
> 
> Perhaps more reliable way is to remove any HTML when copied with following command.
> 
> ```ini
> [Command]
> Automatic=true
> Command="
>     copyq:
>     if (dataFormats().indexOf(mimeHtml)) {
>       removeData(mimeHtml)
>       copy(mimeText, data(mimeText))
>     }"
> Icon=\xf031
> Input=text/plain
> Name=Ignore HTML
> ```

Where This command is store, I want to backup my system and then import my config files.

**Comment by kudorgyozo** [comment]
> It might be possible to override normal paste shortcut with "Paste clipboard as plain text" command (it's available under Add button in Command dialog F6).
> 
> Perhaps more reliable way is to remove any HTML when copied with following command.
> 
> [Command]
> Automatic=true
> Command="
>     copyq:
>     if (dataFormats().indexOf(mimeHtml)) {
>       removeData(mimeHtml)
>       copy(mimeText, data(mimeText))
>     }"
> Icon=\xf031
> Input=text/plain
> Name=Ignore HTML

Where do I add this? I know I have to press f6 but what do I do after that? Explain to me like i'm 5. How do I add this so it happens automatically every time I copy something?
