### ISSUE TITLE
Exception in custom command 3.0.0~xenial amd64

### ISSUE THREAD

**Issue by jpmoral** [hluk/CopyQ#693]
First of all thanks for a great piece of software!

I have the following automatic action set up to ignore KeePassX:
```
copyq: ignore()
sleep 10;
copyq: copy('')
copyq: select 0
```

It works, but every time I copy a password I get the following errors in popups:
```
Exit code: 4
ScriptError:"ignore()..."2:7: syntax error: Expected `;',`;'
```

I've tried several combinations of removing and adding semi-colons without success.  I can't seem to fint the solution in the [scripting README](https://github.com/hluk/CopyQ/blob/master/src/scriptable/README.md) either.

**Comment by hluk** [comment]
A command is parsed as list of program calls with arguments

```
copyq ignore
sleep 10
copyq copy ''
copyq select 0
```

or passed as script on standard input to an application (in this case CopyQ)

```js
copyq:
ignore()
sleep(10)
copy('')
select(0)
```

Everything after the label `copyq:` is basically parsed as JavaScript.

Other useful labels are `python:`, `bash:` or `powershell:`.

Perhaps it's more clearly described [here](https://github.com/hluk/CopyQ/wiki/Writing-Commands-and-Adding-Functionality#command). I'll try to update the documentation.

**Comment by jpmoral** [comment]
That did it, thanks!
