### ISSUE TITLE
Paste last item in current tab and delete it

### ISSUE THREAD

**Issue by lepalmtree** [hluk/CopyQ#694]
Hi,

I would like to make a command to paste the last entry and delete it from the current tab.
I saw the Paste and Forget example command, but that doesn't do what I'd like.
I've tried
```
copyq:
    tab(selectedtab())
    items = selecteditems()
    select(items[0])
    hide()
    paste()
    remove[items[0])
```
but the `remove()` function expects more than 1 parameter.
How can I achieve this ?

Thank you

**Comment by hluk** [comment]
Function `remove()` [expects at least one argument](https://github.com/hluk/CopyQ/blob/master/src/scriptable/README.md#removerow-) but `select()` [may move the item to the top](https://github.com/hluk/CopyQ/blob/master/src/scriptable/README.md#selectrow) (depends on settings). So you may need to call `remove(0)` instead.

**Comment by lepalmtree** [comment]
It almost works :) it removes the last item in the tab, but keep it in the clipboard.
For example, if I copy "first" and "second". When I paste using the function twice, it will paste "first" two times, and remove "first " and "second" from the main tab. What am I missing ?

**Comment by lepalmtree** [comment]
Sorry I misclicked, I didn't want to close the issue

**Comment by hluk** [comment]
The target application probably still sees the old clipboard content. It could help to put `sleep(50)` (wait in milliseconds) before `paste()`.

Another possibility is that the item was not yet removed by previous command and next command copies it again.

**Comment by lepalmtree** [comment]
I can't make it work like this either. That's too bad. Maybe I'll try again later

**Comment by hluk** [comment]
Closing. If you still have this issue please reopen and provide details.
