### ISSUE TITLE
Select non-first items when search box is active

### ISSUE THREAD

**Issue by amosbird** [hluk/CopyQ#695]
How can I select items using `ctrl-j/k` and `enter` to commit when search box is active?
![](https://paste.wentropy.com/bQ-D.jpg)

**Comment by hluk** [comment]
You have to use <kbd>Tab</kbd> or <kbd>Down</kbd> key to focus the item list first. Alternatively following command maps the shortcuts you need.

```ini
[Command]
Command="
    copyq:
    var shortcut = str(data(mimeShortcut))
    if (shortcut == 'ctrl+j')
      selectItems(currentItem() + 1)
    else
      selectItems(currentItem() - 1)"
Icon=\xf002
InMenu=true
Name=Next/Previous Found Item
Shortcut=ctrl+j, ctrl+k
```

**Comment by amosbird** [comment]
Great!
