### ISSUE TITLE
Absolutely not adapted for hi dpi displays 

### ISSUE THREAD

**Issue by avatsaev** [hluk/CopyQ#696]
![](http://i.imgur.com/zft0TPi.jpg)

**Comment by hluk** [comment]
Works fine for me on 4K monitor.

![image](https://cloud.githubusercontent.com/assets/38054/25564352/e6dae9a0-2db1-11e7-9270-3d05bfa49e95.png)

What's the OS, desktop environment and window manager?

Are you sure you don't set any Qt environment variables that could mess the resolution?

**Comment by avatsaev** [comment]
Ubuntu Gnome 17.04

**Comment by hluk** [comment]
Yup, the rendering is messed up if you set either `QT_SCALE_FACTOR` or `QT_AUTO_SCREEN_SCALE_FACTOR`.

Can you test [new package](http://download.opensuse.org/repositories/home:/lukho:/copyq-beta/xUbuntu_17.04/amd64/)?

**Comment by avatsaev** [comment]
still getting this tiny text: http://imgur.com/a/2R71Y 

can't read anything at a normal distance

**Comment by hluk** [comment]
Try to launch CopyQ from command line with:

```bash
QT_SCALE_FACTOR="" QT_AUTO_SCREEN_SCALE_FACTOR="" QT_SCREEN_SCALE_FACTORS="" copyq
```

**Comment by avatsaev** [comment]
weird, still no changes: http://imgur.com/a/4Erdw

how do i check the version of the app, to ensure that the new packages overwrote the old one?

**Comment by hluk** [comment]
Hmm, how about:

```bash
QT_SCALE_FACTOR=2 copyq
```

Not sure why Qt would choose to ignore those variables.

**Comment by avatsaev** [comment]
yes this one worked, just the tray icon looks pixelated

but looks crisp with this command: QT_SCALE_FACTOR="" QT_AUTO_SCREEN_SCALE_FACTOR="" QT_SCREEN_SCALE_FACTORS="" copyq

**Comment by avatsaev** [comment]
http://i.imgur.com/Mq1i3z9.png

**Comment by hluk** [comment]
Yes, I've noticed the pixelation too, seems like a Qt bug. Though it works for me without any issue if I don't set those variables. Perhaps Qt gets wrong DPI from somewhere else -- there is [quite few places for DPI to be set](https://wiki.archlinux.org/index.php/HiDPI).

**Comment by hluk** [comment]
Oh, I actually needed to set DPI to 162 in XFCE configuration; without it system assumes tiny 96 DPI.

**Comment by avatsaev** [comment]
let me know if you have a new package

**Comment by hluk** [comment]
I'm not sure if I can do anything about that. Can you check if DPI is set correctly in Gnome?

**Comment by avatsaev** [comment]
Unfortunately gnome only allows to modify the scaling factor, and it's an integer value. 

But it's fine, i don't care about the action icons, as long as i can read the text.

Thank you.

**Comment by hluk** [comment]
I guess the one thing that could help is set correct DPI (not sure how it will work with the scaling in Gnome):

```bash
xrandr --dpi 162
# OR
xrandr --dpi 192
# CopyQ needs to be restarted
```
