### ISSUE TITLE
How to match the window name?

### ISSUE THREAD

**Issue by eexpress** [hluk/CopyQ#697]
I want automatic open file that copy from gnome-terminal, so I type  "gnome-terminal" or "*terminal" or such things here, but the command icon disappeared "in Menu", that say the command no match anything if I fit the "window" item.
![copyq-match-window](https://cloud.githubusercontent.com/assets/700793/25566183/d6937ed6-2e06-11e7-9b3c-770698ceb39b.png)

**Comment by eexpress** [comment]
I just want do it like this in perl:
    if(/^\// || /^~\//){s/^~/$ENV{HOME}/;s/\n.*//;if(-e){`xdg-open \"$_\"`;exit;}}

**Comment by hluk** [comment]
"Window" field contains case-sensitive regular expression (uses same format as [QRegExp](http://doc.qt.io/qt-5/qregexp.html#details)) that matches whole window title on Linux/X11.

Perfect match for gnome-terminal would be `^Terminal$`.

![image](https://cloud.githubusercontent.com/assets/38054/25573504/47469bf6-2e46-11e7-9888-47e1438ab244.png)

Unfortunately, this may not work on Wayland yet. You can test if CopyQ sees the window title with following command. It shows notification with the title of current window on <kbd>Ctrl</kbd>+<kbd>Win</kbd>+<kbd>W</kbd> global shortcut.

```ini
[Command]
Command="
    copyq:
    popup('Current Window Title', currentWindowTitle())"
GlobalShortcut=meta+ctrl+w
Icon=\xf009
Name=Test Window Title
```

**Comment by eexpress** [comment]
I got it. the field not need the title but the window classname. OK, I can take it from xwininfo. thanks for help.

```
▶ xwininfo 

xwininfo: Please select the window about which you
          would like information by clicking the
          mouse in that window.

xwininfo: Window id: 0x2200006 "Terminal"
```

**Comment by eexpress** [comment]
Other problem come. I can not understand why `^/\w+/\w+ || ^~/\w+` match my directory name in $HOME.
All double click those directory show in below picture, copyq match it.

![2017-05-05 12-28-05](https://cloud.githubusercontent.com/assets/700793/25733668/5529fc90-318e-11e7-92e4-d8fea62d50c6.png)

**Comment by hluk** [comment]
I think the regex should be `^/\w+/\w+|^~/\w+`. Using `||` in a regex will match anything.

**Comment by eexpress** [comment]
OK, I change the regex to `^~*/\w{3,}`, seems can not use `||` in "Content".

**Comment by hluk** [comment]
The window must match "Window" field even for the menu action. E.g. the terminal needs to have focus so you can access the menu action from tray menu or with `copyq menu` command.

**Comment by eexpress** [comment]
that's no matter. thanks. 
I draw a svg for copyq. https://www.mediawiki.org/wiki/File:CopyQ.svg (seems mediawiki.org mess up)
