### ISSUE TITLE
v3.0.0 MacOS - Focus doesn't return to the running app after summoning CopyQ

### ISSUE THREAD

**Issue by carlitorendon** [hluk/CopyQ#698]
Hello @hluk / CopyQ team, as I mentioned in other issues, I don't use MacOS as much as windows, so I may be misunderstanding something. 

But say that I'm working on Chrome, then I summon CopyQ, do my stuff there and then press ESC to leave it, then the focus doesn't return to the window I was. Chrome would still be the app on the Menu bar but the window I was working before is not selected (no window is selected actually).

**Comment by hluk** [comment]
Should be fixed in [pre-release](https://github.com/hluk/CopyQ/releases/tag/osx-test) (oddly hidden app windows retain focus).

The window behavior is still strange on OS X when main window is open or minimized and other application windows, dialogs and menus are being open and closed.

**Comment by carlitorendon** [comment]
Thanks @hluk, will check and report findings.

**Comment by carlitorendon** [comment]
Hello @hluk, I can confirm that the focus problem is gone. Great work!
