### ISSUE TITLE
Application hangs after displaying window preview using Gnome extension "Dash to panel"

### ISSUE THREAD

**Issue by eexpress** [hluk/CopyQ#700]
![xx](https://cloud.githubusercontent.com/assets/700793/25602525/3fa99b8c-2f27-11e7-8eb1-73295766d201.png)

endless windows, can not exit. Fedora 25.

**Comment by hluk** [comment]
When does it happen? Is that a window, menu or a notification?

**Comment by eexpress** [comment]
It is **window preview** in panel. endless, can not exit. and pgrep can not found those process/windows. Even after pkill copyq, it still here. I only can logout to make it disappear. Maybe copyq is base on Qt, some incompatible with Gnome shell (window manager).

**Comment by hluk** [comment]
Is that an extension? I fail to reproduce it with [TaskBar](https://extensions.gnome.org/extension/584/taskbar/).

Any idea when it happens?

**Comment by eexpress** [comment]
I use gnome shell extension, "Dash to panel". 

I have no idea about how can re-produce it. Maybe It come from some automatic "Command", copyq make an command execute loop? Here has not log file for debug in copyq.

**Comment by eexpress** [comment]
I found automatic command execute twice.

**Comment by hluk** [comment]
Automatic commands are executed only when clipboard or mouse selection changes.

To see executed commands in log, you need to start CopyQ from terminal with `COPYQ_LOG_LEVEL=Debug copyq`.

The log file is usually in `~/.local/share/copyq/copyq/copyq.log` (`copyq info log` prints log file path).

**Comment by hluk** [comment]
@eexpress I still fail to reproduce this with "Dash to Panel" extension. Please reopen this issue if it's still a problem.
