### ISSUE TITLE
[BUG] I pasted the full path of when I enabled sync plugin.

### ISSUE THREAD

**Issue by ousui** [hluk/CopyQ#702]
ENV: 
* macos 10.12.4
* copyq 3.0.0

I setup the synchronize directory for a tab.
Then I copied a string, it create new file on the directory like name "copyq_0133.txt".
But when I use copyq to select the logged item to some Applications like QQ, Wechat, the App will send the file "copyq_0133.txt".
And another App like iTerm, or macos term, copyq will paste the full path for "copyq_0133.txt" 

the gif: https://ww1.sinaimg.cn/large/006tKfTcly1ff94y1bnf4g30bo05okju.gif

![](https://ww1.sinaimg.cn/large/006tKfTcly1ff94y1bnf4g30bo05okju.gif)

**Comment by hluk** [comment]
Hmm, Terminal in OS X seems to prefer to pick from clipboard URI (the full path of synced item) instead of plain text (the synced item content).

CopyQ provides URI for synced items so it's possible to copy or move them out to a file manager.

Not sure if I should remove the URI or how to fix it.

**Comment by hluk** [comment]
You can use "Paste as Plain Text" predefined command so only the text is copied.

**Comment by ousui** [comment]
@hluk  "Paste as Plain Text" can used at QQ, WeChat and Macos term, but not iTerm because CopyQ can't get the iterm focus.
By the way, there's no this bug on version 2.x.

**Comment by hluk** [comment]
@ousui Works for me in iTerm2. Can you test it with new [pre-release](https://github.com/hluk/CopyQ/releases/tag/osx-test)?

**Comment by ousui** [comment]
@hluk 
My iTerm2 enabled hotkey to show and hide menu bar, so It still can't work normally.

![](https://ww4.sinaimg.cn/large/006tNbRwly1ffdq1lxvfvj30rj021mxv.jpg)

This is my command for "Paste as Plain Text": 
```
[Command]
Command="
    copyq: 
    var text = input()
    copy(text)
    copySelection(text)
    paste()"
GlobalShortcut=ctrl+shift+1, DISABLED
HideWindow=true
Icon=\xf0ea
InMenu=true
Input=text/plain
Name=\x6269\x5c55(&X)|\x7c98\x8d34\x4e3a\x7eaf\x6587\x672c
Shortcut=ctrl+return

```

**Comment by hluk** [comment]
Strange, even pasting to iTerm works fine for me with the pre-release, could be due to some configuration or OS X version. Still, iTerm seems to have been unmaintained for a long time.

**Comment by hluk** [comment]
Closing. There were some changes and fixes for URI handling on OS X in recent CopyQ versions. Please reopen if it's still an issue.
