### ISSUE TITLE
v3.0.0 MacOS - Multiple virtual desktops: CopyQ does not play well among them

### ISSUE THREAD

**Issue by carlitorendon** [hluk/CopyQ#703]
Hello @hluk / CopyQ team, 

1) have multiple virtual desktops (say 3)
2) open Chrome on the  1st one, Word on the second one and something else on the 3rd one. 
3) Now you go back to the 1st desktop and the focus is on Chrome. Summon CopyQ, do stuff there and then extinguish it. 
4) Now manually use Mission Control to go to the 2nd virtual desktop where you have Word. Make sure the focus is on Word
5) Summon CopyQ and see how CopyQ is forcing MacOS to travel to virtual desk #1. You do your stuff and then when you extinguish it, it will have MacOS return you to virtual desk #2 where word was. 

This behavior is different from Windows 10 where CopyQ travels with all the virtual desktops.

**Comment by ousui** [comment]
Yes, I found when I use function "hide" to hide the CopyQ window or menu, it will stay that desktop always. 
But when I click "close" button, CopyQ can show at the current desktop.

**Comment by hluk** [comment]
OK, should be fixed. Grab the updated [pre-release](https://github.com/hluk/CopyQ/releases/tag/osx-test).

**Comment by carlitorendon** [comment]
Hello @hluk, will try and share findings

**Comment by carlitorendon** [comment]
Hello @hluk, perfect! Thank you so much. It works great.
