### ISSUE TITLE
Ignoring primary copy sometimes also masks clipboard copy.

### ISSUE THREAD

**Issue by amosbird** [hluk/CopyQ#705]
I use this to prevent copy on selection in qutebrowser
```
[Command]
Automatic=true
Command="
    copyq:
    var clipboardMode = str(input())
    if (clipboardMode == 'selection')
      ignore()"
Icon=\xf05e
Input=application/x-copyq-clipboard-mode
Name=Ignore Selection from qutebrowser
Window=qutebrowser
```

However, sometimes it also makes copy action be masked. I have to press `ctrl-c`  multiple times.

**Comment by hluk** [comment]
Seems like some issue in Qt. When there is lots of selection changes the clipboard change is missed.
