### ISSUE TITLE
Use action to achieve image editing.

### ISSUE THREAD

**Issue by amosbird** [hluk/CopyQ#706]
How can I edit current clipboard's image using external applications just like text editing?

**Comment by hluk** [comment]
Set bitmap and SVG image editor in Configuration:
![image](https://cloud.githubusercontent.com/assets/38054/25791749/acf53e2c-33c2-11e7-8d7e-67a536a24846.png)

Editing an image item (<kbd>Ctrl</kbd>+<kbd>E</kbd>) should open the image editor.

Unfortunately, sometimes an item looks like an image but is an HTML (check available formats in Content dialog <kbd>F4</kbd>).

**Comment by hluk** [comment]
I've added a new [wiki page](https://github.com/hluk/CopyQ/wiki/Images).

**Comment by amosbird** [comment]
@hluk Thanks! Can I make copyq window auto closed when external editor is opened?

**Comment by hluk** [comment]
This is only possible to do using a script, e.g.:

```bash
#!/bin/bash
copyq hide
exec krita "$1"
```

or through command:

```ini
[Command]
Command="
    copyq:
    var app = 'krita'
    var mime = 'image/png'
    var suffix = '.png'
    var fileTemplate = Dir().temp().absoluteFilePath('copyq-XXXXXX' + suffix)
    var item = selectedItemData(0)
    
    var file = TemporaryFile()
    file.setFileTemplate(fileTemplate)
    file.openWriteOnly()
    file.write(input())
    file.close()
    filePath = file.fileName()
    
    hide()
    execute(app, filePath)
    
    var imageFile = File(filePath)
    if ( !imageFile.openReadOnly() )
      abort()
    
    var image = imageFile.readAll()
    if ( image.size() == 0 )
      abort()
    
    for (var format in item) {
      if (format.indexOf('image') != -1)
        delete item[format]
    }
    
    if (selectedItemData(0)) {
      item[mime] = image
      setSelectedItemData(0, item)
    } else {
      setItem(0, item)
    }"
Icon=\xf03e
InMenu=true
Input=image/png
Name=Edit Image
Shortcut=ctrl+e
```

**Comment by amosbird** [comment]
How can I execute the bash script passing current selected item using `ctrl-e` ?

**Comment by hluk** [comment]
Just replace the "Image editor command" in configuration with absolute path to the script (make sure the script is executable).

**Comment by amosbird** [comment]
Um, can I have more than one command defined like this? I need a "Image uploading command" to be specific :smile:

**Comment by hluk** [comment]
Examples for commands:

```bash
bash:
# COPYQ environment variable holds path to executable for CopyQ
"$COPYQ" popup "Hello"
# input can retrieve data for selected item (set Format field)
"$COPYQ" input | "$COPYQ" popup x -
```

```js
copyq:
script='/home/lukas/test.sh'
// Pass data for selected item to a script as argument
execute(script, input())
// or on stdin (null separates script arguments and stdin)
execute(script, null, input())
```

Or you can create temporary file and pass its file name to a script as in the command for image editing in my previous comment.

**Comment by amosbird** [comment]
Thanks!

**Comment by amosbird** [comment]
Um, after using these commands, copyq ends up like this,
![](https://paste.wentropy.com/N1bM.png)

**Comment by hluk** [comment]
Do you use the latest version (3.0.1)?

**Comment by amosbird** [comment]
um, no, I use copyq git version of date 2017-05-07

**Comment by hluk** [comment]
What does `copyq version` print?

**Comment by amosbird** [comment]
```
 ❯ copyq version                                                                                            (7s 154ms)
CopyQ Clipboard Manager v3.0.0-51-g6912f833 (hluk@email.cz)
Built with: Qt 5.8.0, LibQxt 0.7.0
```

**Comment by hluk** [comment]
Hmm, strange. Can you post steps to reproduce?

**Comment by amosbird** [comment]
@hluk This is a one time thing. I cannot reproduce it either. I'll reopen this if I find a way to reproduce. :smiley:

**Comment by hluk** [comment]
@amosbird OK, but create new issue if you manage to reproduce it, thanks.

**Comment by hluk** [comment]
@amosbird I think I fixed the rendering issue (it's in master branch).
