### ISSUE TITLE
Ctrl+Shift+V to paste into Item as plaintext

### ISSUE THREAD

**Issue by KillyMXI** [hluk/CopyQ#707]
Currently, it's only possible to paste text with whatever styles attached to it, and then clear styles with eraser button. But I would like to avoid an extra step. Suggested hotkey is commonly used exactly for that.

**Comment by hluk** [comment]
There are predefined commands "Paste as Plain Text" and "Paste clipboard as plain text", just bind the shortcut you want ([here](https://github.com/hluk/CopyQ/wiki/Keyboard#create-new-shortcut) is how).

**Comment by KillyMXI** [comment]
That means I have to make it global.
I was asking just to extend the capabilities of item editor.

**Comment by KillyMXI** [comment]
I'll workaround it by adjusting the command to "Insert new item as plaintext".

**Comment by hluk** [comment]
Ahh, OK, the command would be something like this:

```ini
[Command]
Command="
    copyq:
    add(clipboard())"
Icon=\xf055
InMenu=true
Name=Insert new item as plaintext
Shortcut=ctrl+shift+v
```

**Comment by LeChatNoir666** [comment]
I would like to have this option as right click context menu too please!
Or as button in the top row?
Or an option to always paste in plain text in the editor?

I'm that crazy to work with 2 Clipboard-Manager (I'm using Ditto too) so my keys for V to insert (like CTRL+Shift+V and Win+V aso..) are limited...

**Comment by Chealer** [comment]
As this is an ITS, each ticket should emphasize the problem, in particular in the title. Please indicate your OS and retitle with a short description of the issue. I suggest:
> No default function to paste as plain text

@LeChatNoir666 wrote:
> I'm that crazy to work with 2 Clipboard-Manager (I'm using Ditto too) so my keys for V to insert (like CTRL+Shift+V and Win+V aso..) are limited...

Ditto natively allows to paste as plain text using <kbd>Shift</kbd>+<kbd>Enter</kbd>. I suggest also using 1 or 2 modifier(s) in combination with Enter.
