### ISSUE TITLE
Allow the customization for the keyboard shortcut that exits the editor

### ISSUE THREAD

**Issue by carlitorendon** [hluk/CopyQ#708]
Hello @hluk / CopyQ team, may I propose a feature? 

For the Windows platform, one can configure CopyQ to allow CTRL+Enter to exit the editor; for MacOS is Command+Enter. However, none of those platforms (and I'm going to venture to guess that neither does Linux) allows such a shortcut to be changed.

For me particularly, the advantage would be the same as with other shortcuts: it would allow me to harmonize my shortcuts across platforms. Whereas now, I have to remember one for Mac and one for Windows.

Let me know what you think.

**Comment by rogerioefonseca** [comment]
Yeah, looks like it is not high prior _ _ , but that is a nice one indeed
