### ISSUE TITLE
There are some problem for global shortcuts for v3.0.1 on macos.

### ISSUE THREAD

**Issue by ousui** [hluk/CopyQ#710]
I had upgrade from pre-release, but when I startup CopyQ, it print these log:
```
Warning [2017-05-10 11:33:50.851] Server-97978: Failed to set global shortcut "Meta+Ctrl+T" for command "...".
Warning [2017-05-10 11:33:50.851] Server-97978: Failed to set global shortcut "Meta+Ctrl+;" for command "...".
Warning [2017-05-10 11:33:50.851] Server-97978: Failed to set global shortcut "Meta+Ctrl+'" for command "...".

```

I can't use "cmd" and another key.
But when I set the shortcut to "F11", it can work.

There's no these issues before v3.0.1.

**Comment by hluk** [comment]
I cannot reproduce this. It's strange that this breaks since there were no changes in the global shortcuts code.

Did you try restarting the app or clearing and resetting the global shortcut again?

**Comment by ousui** [comment]
@hluk 
It's ok now.
I removed /Application/CopyQ.app completely then copy v3.0.1 to /Application.

By the way, where is the config files, I'm try to remove ~/.config/copyq, but when I startup CopyQ, the files created by itself.

**Comment by hluk** [comment]
You can print configuration and other paths with `copyq info` command -- from Action dialog <kbd>F5</kbd> you can run `copyq: add(info())` to create new text item with the paths.

**Comment by ousui** [comment]
Got it.
