### ISSUE TITLE
[BUG] About the popup tip in Action dialog.

### ISSUE THREAD

**Issue by ousui** [hluk/CopyQ#711]
When I checked "Always on top" setup option, the popup tip for script auto completion was covered.

![](http://ww4.sinaimg.cn/large/006tNc79ly1ffgcutjh5qj30i10ce0tq.jpg)

**Comment by hluk** [comment]
Which version do you use (`copyq version`)? I [fixed](https://github.com/hluk/CopyQ/commit/9c814494677076a5ddad090e4156a6814509806f) some completion popup issue just yesterday.

**Comment by ousui** [comment]
v3.0.1

**Comment by hluk** [comment]
I just tested this, seems to be fixed in recent [pre-release](https://github.com/hluk/CopyQ/releases/tag/osx-test).

**Comment by ousui** [comment]
It's fixed. Thank you.
