### ISSUE TITLE
"Tab is full", to optimize the "remove" script

### ISSUE THREAD

**Issue by ousui** [hluk/CopyQ#712]
I enabled synchronize item, and set history limit to 500.
When the copied item Is greater than 500, CopyQ tips me "Tab is full ......".

Then I want to write an auto script, like:
```
copyq: 
var line = size()-1;
remove(line);
```

But it tips me: 
"Removing synchronized items with assigned files from script is not allowed (remove the files instead)";

I found the string at `https://github.com/hluk/CopyQ/blob/master/plugins/itemsync/itemsync.cpp` line 536.

But, when I open CopyQ Browser, click right menu, select delete, it can remove the item and copyq_0xxx.txt/html file.

**Comment by hluk** [comment]
This is intended behavior. Deleting a synchronized item shows confirmation dialog. I wasn't sure if it's a good idea to show the dialog when executing `remove()` from script. Maybe I should really change this.

**Comment by ousui** [comment]
You can add an new method "removeForce()" can delete copyq-item and dependencies.

**Comment by hluk** [comment]
The synced items created by CopyQ can now be removed without confirmation (with `copyq_*` files) -- works the same for non-synchronized tabs.

The confirmation dialog for deleting item only pops up if the underlying files were not created by CopyQ. This is just a safety measure against accidental removal of some important files.

**Comment by hluk** [comment]
BTW, this also means that "Tab is full" message shouldn't popup in most cases.

**Comment by ousui** [comment]
The different platform has different sync path.
Then how can I get the path of the specified sync tab use script on all platform?

**Comment by hluk** [comment]
@ousui It's not possible in v3.0.1 but I just added a fix which allows to do:

```bash
# Print synchronization path for "clipboard" tab.
copyq 'plugins.itemsync.tabPaths["clipboard"]'
```
```bash
# List synchronized tabs.
copyq 'Object.keys(plugins.itemsync.tabPaths)'
```

...and in CopyQ script:

```js
// Iterate synchronized tabs and their paths.
var tabPaths = plugins.itemsync.tabPaths
for (var tabName in tabPaths) {
  var path = tabPaths[tabName]
  // ...
}
```

**Comment by ousui** [comment]
It's very useful!

**Comment by ousui** [comment]
And I want get the history limit count to choice delete the item.
