### ISSUE TITLE
Is CopyQ's tray position configurable?

### ISSUE THREAD

**Issue by icycandy** [hluk/CopyQ#713]
1. Is there a gnome-shell extension, so that CopyQ can appear in the top bar of Fedora?
2. CopyQ's tray position is default in bottom left, is it possible to locate in bottom right?
3. Windows 10 (64-bit) host, Virtualbox 5.1.22, Fedora 25 (64-bit) guest, CopyQ 3.0.0 install on Fedora

global shortcuts working in
   * Firefox 53.0 (64-bit)
   * Chrome 58.0.3029.110 (64-bit)

but not working in
   * gnome-terminal 3.22.1
   * gedit 3.22.0

**Comment by ousui** [comment]
You can add global shortcut command then the menu can show at the cursor.
```
[Command]
Command="
    copyq: menu()"
GlobalShortcut=meta+ctrl+'
Icon=\xf01c
Name=C.\x663e\x793a\x6258\x76d8\x83dc\x5355

```

**Comment by icycandy** [comment]
> global shortcuts working in
>     * Firefox 53.0 (64-bit)
>     * Chrome 58.0.3029.110 (64-bit)
This means that I have already add global shortcuts.
![main window](https://cloud.githubusercontent.com/assets/724257/25980013/894a8cae-36fe-11e7-9794-0bf7b5aa9da6.png)
![tray menu](https://cloud.githubusercontent.com/assets/724257/25980017/8ee8c932-36fe-11e7-90e5-4c5716e3a94c.png)

**Comment by hluk** [comment]
@icycandy If you **disable the tray in configuration** (in configuration dialog, "Tray" tab, "Disable tray" option) the app should be **visible in task bar** (in the list of opened windows).

Not sure why global shortcuts won't work in some apps. Can you check log (<kbd>F12</kbd>) for any errors or warnings?

**Comment by icycandy** [comment]
After I disable the tray, the app did visible in running apps, but I expected the CopyQ icon appear at the right top system tray area.
![1](https://cloud.githubusercontent.com/assets/724257/26005153/cda64d36-376a-11e7-84b3-b9fbb675135a.png)

And I checked the log, there are only 3 warnings, no errors. The full log is list below.
```
Note [2017-05-12 01:28:18.527] Server-3096: Loading plugin: /usr/lib64/copyq/plugins/libitemdata.so
Note [2017-05-12 01:28:18.532] Server-3096: Loading plugin: /usr/lib64/copyq/plugins/libitemencrypted.so
Note [2017-05-12 01:28:18.537] Server-3096: Loading plugin: /usr/lib64/copyq/plugins/libitemfakevim.so
Note [2017-05-12 01:28:18.540] Server-3096: Loading plugin: /usr/lib64/copyq/plugins/libitemimage.so
Note [2017-05-12 01:28:18.543] Server-3096: Loading plugin: /usr/lib64/copyq/plugins/libitemnotes.so
Note [2017-05-12 01:28:18.548] Server-3096: Loading plugin: /usr/lib64/copyq/plugins/libitempinned.so
Note [2017-05-12 01:28:18.556] Server-3096: Loading plugin: /usr/lib64/copyq/plugins/libitemsync.so
Note [2017-05-12 01:28:18.560] Server-3096: Loading plugin: /usr/lib64/copyq/plugins/libitemtags.so
Note [2017-05-12 01:28:18.563] Server-3096: Loading plugin: /usr/lib64/copyq/plugins/libitemtext.so
Note [2017-05-12 01:28:20.307] Server-3096: Loading plugin: /usr/lib64/copyq/plugins/libitemweb.so
Warning [2017-05-12 01:29:17.851] Server-3174: CopyQ server is already running.
Warning [2017-05-12 01:29:33.362] Server-3235: CopyQ server is already running.
Note [2017-05-12 01:40:42.931] Server-1950: Loading plugin: /usr/lib64/copyq/plugins/libitemdata.so
Note [2017-05-12 01:40:43.120] Server-1950: Loading plugin: /usr/lib64/copyq/plugins/libitemencrypted.so
Note [2017-05-12 01:40:43.344] Server-1950: Loading plugin: /usr/lib64/copyq/plugins/libitemfakevim.so
Note [2017-05-12 01:40:43.383] Server-1950: Loading plugin: /usr/lib64/copyq/plugins/libitemimage.so
Note [2017-05-12 01:40:43.419] Server-1950: Loading plugin: /usr/lib64/copyq/plugins/libitemnotes.so
Note [2017-05-12 01:40:43.767] Server-1950: Loading plugin: /usr/lib64/copyq/plugins/libitempinned.so
Note [2017-05-12 01:40:43.886] Server-1950: Loading plugin: /usr/lib64/copyq/plugins/libitemsync.so
Note [2017-05-12 01:40:43.989] Server-1950: Loading plugin: /usr/lib64/copyq/plugins/libitemtags.so
Note [2017-05-12 01:40:44.010] Server-1950: Loading plugin: /usr/lib64/copyq/plugins/libitemtext.so
Warning [2017-05-12 01:40:44.680] Server-2070: CopyQ server is already running.
Note [2017-05-12 01:40:48.961] Server-1950: Loading plugin: /usr/lib64/copyq/plugins/libitemweb.so
Note [2017-05-12 20:11:11.274] Server-1723: Loading plugin: /usr/lib64/copyq/plugins/libitemdata.so
Note [2017-05-12 20:11:11.421] Server-1723: Loading plugin: /usr/lib64/copyq/plugins/libitemencrypted.so
Note [2017-05-12 20:11:11.470] Server-1723: Loading plugin: /usr/lib64/copyq/plugins/libitemfakevim.so
Note [2017-05-12 20:11:11.516] Server-1723: Loading plugin: /usr/lib64/copyq/plugins/libitemimage.so
Note [2017-05-12 20:11:11.579] Server-1723: Loading plugin: /usr/lib64/copyq/plugins/libitemnotes.so
Note [2017-05-12 20:11:11.619] Server-1723: Loading plugin: /usr/lib64/copyq/plugins/libitempinned.so
Note [2017-05-12 20:11:11.748] Server-1723: Loading plugin: /usr/lib64/copyq/plugins/libitemsync.so
Note [2017-05-12 20:11:11.817] Server-1723: Loading plugin: /usr/lib64/copyq/plugins/libitemtags.so
Note [2017-05-12 20:11:11.924] Server-1723: Loading plugin: /usr/lib64/copyq/plugins/libitemtext.so
Note [2017-05-12 20:11:14.410] Server-1723: Loading plugin: /usr/lib64/copyq/plugins/libitemweb.so
```

BTW. If I set exactly same global shortcuts for two different actions, CopyQ seems didn't complain about it.

**Comment by hluk** [comment]
Oh, OK, the top right is the notification area, the tray icon should be visible there if the "Disable tray" option is unchecked, but you may also need to install some other packages on your system.

If CopyQ creates empty space in the notification area, you probably need to install `qt5-qtsvg` and `qt5-qtimageformats`.

> BTW. If I set exactly same global shortcuts for two different actions, CopyQ seems didn't complain about it.

Hmm, seems that the error reporting doesn't work on Linux/X11 -- probably a bug in qxtglobalshortcuts library.

**Comment by icycandy** [comment]
> If CopyQ creates empty space in the notification area, you probably need to install `qt5-qtsvg` and `qt5-qtimageformats`.

I checked that there is no empty space in the notification area, as show in following pictures.
![1](https://cloud.githubusercontent.com/assets/724257/26020259/f5c7ca4e-37ae-11e7-8d14-d6746e63aa1f.png)
![2](https://cloud.githubusercontent.com/assets/724257/26020261/fa962656-37ae-11e7-84db-49c342c73ee7.png)

`qt5-qtsvg` is a dependency of copyq, so it is installed along with copyq. `qt5-qtimageformats` is not a dependency of copyq, so I need to install manully. 
I `dnf install qt5-qtimageformats` and unchecked the "Disable tray" option , and then reboot the Fedora guest. Still no CopyQ icon in notification area.

**Comment by ousui** [comment]
中国人就好办了啊……
我 linux 是直接用快捷键呼出托盘菜单，呼出的地方一般都在光标位置。组合键不行的话，试试单一的 F11 F10 一类的。
qt5 的包好像都要装全了，不然会有问题。
不行把配置文件都删了，然后试一下，我有几次是因为配置文件引起的。

**Comment by icycandy** [comment]
我的主要目的是想在linux终端下快速输入各种机器的密码。你在gnome-terminal下能正常使用全局快捷键吗？
qt5相关的包太多了，全都装的话代价未免太大了点。

-- 
My main aim is to fast input various passwords in linux terminal. Does the global shortcut work well in your gnome-terminal?
There are too many qt5 related packages, it's expensive to install them all.

**Comment by ousui** [comment]
@icycandy 等我回去看一下，我用的发行版是 archlinux，之前装的 kde，终端用的 Yakuake，之前是可以正常用的。最近刚换了 gnome，终端改用 guake，好像还没怎么试。

**Comment by hluk** [comment]
Found a solution for moving the tray icon to top bar: install [TopIcons Plus](https://extensions.gnome.org/extension/1031/topicons/) GNOME Shell extension.

BTW, `qt5-qtimageformats` is only an optional dependency allowing to display images in CopyQ (it may not be required for tray icon).

**Comment by hluk** [comment]
The global shortcut issue might have something to do with the Chinese input method settings. I tried few configurations but couldn't reproduce the issue.

**Comment by ousui** [comment]
@hluk Yes, I found it. I used Baidupinyin input method on mac, when I used it default, I can't use global shortcut, but when I switch English input method, CopyQ can work.

@icycandy 我的 mac 用百度输入法确实会影响全局快捷键的使用，切到英文输入法启动就好了…… 好奇特。。。

**Comment by icycandy** [comment]
@hluk @ousui 
Inspired by the discussion with you two, I think I've found the real reason, not Chinese input method, but virtualbox guest additions.
After uninstalling virtuallbox guest additions (Chinese input method unchanged), CopyQ's global shortcuts worked well.

**Comment by hluk** [comment]
OK, I managed to reproduce this (Arch Linux host, IBus with Pinyin, Fedora 25 guest with VirtualBox additions). Unfortunately after few tries everything starts to work again -- so I cannot properly test it.

Really not sure how to fix it or if I should fix this at all.

As a workaround you can bind the shortcut to show main window (`copyq toggle`) or menu (`copyq menu`) in desktop environment instead of CopyQ.

**Comment by icycandy** [comment]
I tried the system shortcut in fedora,  `Settings` -> `Keyboard` -> `Add Custom Shortcut`
![1](https://cloud.githubusercontent.com/assets/724257/26055729/ad2cdae8-39a4-11e7-9dc9-8d3a2fcd730f.png)

This time, the tray menu will show with <kbd>Ctr</kbd>+<kbd>Shift</kbd>+<kbd>Y</kbd> pressed. But the position of tray menu is not at current cursor, and tray menu will not disappear if i click other area.

Thank you for providing the excellent CopyQ, at least I can use <kbd>Alt</kbd>+<kbd>Tab</kbd> to navigate to CopyQ, then do the copy, and then <kbd>Alt</kbd>+<kbd>Tab</kbd> to navigate back.

**Comment by ousui** [comment]
v3.0.0 在我这里运行正常，右键在左下可以打开托盘菜单，快捷键也可以正常呼出。
以下是我安装的qt5依赖。
```
qt5-3d                qt5-charts            qt5-declarative       qt5-gamepad           qt5-multimedia        qt5-scxml             qt5-serialport        qt5-virtualkeyboard   qt5-webengine         qt5-webview         
qt5-base              qt5-connectivity      qt5-doc               qt5-graphicaleffects  qt5-quickcontrols2    qt5-sensors           qt5-speech            qt5-wayland           qt5-webkit            qt5-x11extras       
qt5-canvas3d          qt5-datavis3d         qt5-examples          qt5-location          qt5-script            qt5-serialbus         qt5-svg               qt5-webchannel        qt5-websockets        qt5-xmlpatterns
```

**Comment by icycandy** [comment]
In the virtualbox Fedora 25 guest, I installed all the qt5 packages, still has the same problem.
There maybe some conflicts in virtualbox guest additions and CopyQ.

**Comment by hluk** [comment]
This could be related to the fact that default GNOME session runs on Wayland. When I set the session to **GNOME on Xorg** I didn't experience any issues.

![image](https://cloud.githubusercontent.com/assets/38054/26194071/83581c72-3bb7-11e7-9356-3faab7de358d.png)

**Comment by icycandy** [comment]
This fix the issue, thanks.
