### ISSUE TITLE
bug with tab switch and paste in 3.0.1 on windows

### ISSUE THREAD

**Issue by CaptainQwark** [hluk/CopyQ#714]
Hi,

After upgrading to 3.0.1 there is an issue that copyq fails to paste on enter after I have switched tabs by either clicking on one or using the left/right arrow keys. Pasting on enter works fine when I don't switch tabs.

I had no issues on 3.0.0.

**Comment by hluk** [comment]
Here is fixed version for Windows: https://ci.appveyor.com/project/hluk/copyq/build/1.2.1011/job/4y36bhbtrnfih56l/artifacts

**Comment by CaptainQwark** [comment]
Wow that was fast! Confirmed as fixed.
Thanks!
