### ISSUE TITLE
Extra tabs with garbled names after restart

### ISSUE THREAD

**Issue by flyinbutrs** [hluk/CopyQ#715]
This is an odd one...  and it might be a bad config file somewhere, but I'm not sure where to look.

Every time I restart CopyQ (3.0.1 on OSX currently, but I've been using many previous versions as well), I have two extra tabs, with weird garbled names:

![image](https://cloud.githubusercontent.com/assets/1248221/26060966/99c3811e-3954-11e7-958c-0af1e08848d9.png)

Any ideas? Let me know if you need any debug info.

**Comment by hluk** [comment]
Can you check if configuration directory `~/.config/copyq` doesn't contain additional `*.dat` files? There should be one data file for each tab (file name is `copyq_tab_<TAB-NAME-IN-BASE64>.dat`).

**Comment by flyinbutrs** [comment]
Ahah, that was it, thanks!
