### ISSUE TITLE
CopyQ in Virtualbox guest sometimes not sync clipboard to host

### ISSUE THREAD

**Issue by icycandy** [hluk/CopyQ#716]
Win10 host, Fedora 25 guest, guest additions installed and `Shared Clipboard` option set to `Bidirectional`

In gnome-terminal or gedit, sometimes I do the copy in guest, but clipboard is not sync to host. While in Firefox or Chrome, everything works fine.

Similar with #713

**Comment by hluk** [comment]
Isn't this bug in VirtualBox? If the clipboard is not propagated from guest to host OS, I cannot do anything about it.

**Comment by icycandy** [comment]
After install CopyQ, only some particular apps have the problem, `gnome-terminal` and `gedit` for example. 
If uninstall CopyQ, clipboard sync is OK in all apps. So I'm not sure which part's bug.

**Comment by hluk** [comment]
And the CopyQ is installed on the guest? Is this still an issue if you disable the last three "Clipboard Manipulation" options in CopyQ's configuration?

![image](https://cloud.githubusercontent.com/assets/38054/26151761/766b951a-3b04-11e7-9699-3b2e6c7ec4ce.png)

**Comment by icycandy** [comment]
Yes, CopyQ is installed on the guest. The last three options is unchecked when I creat this issue.

**Comment by icycandy** [comment]
>  clipboard is not sync to host

I was wrong, the clipboard is sync to host, but very slow.

I have to wait about 5 seconds when I copy in gnome-terminal or gedit; while in firefox the clipboard sync is instantly complete.

**Comment by hluk** [comment]
It could help to set CopyQ (on both guest and host) to synchronize items to a directory in a shared folder set in VirtualBox.

**Comment by hluk** [comment]
It's quite possible that [this workaround](https://github.com/hluk/CopyQ/issues/713#issuecomment-302342308) can help here too.

**Comment by icycandy** [comment]
Yes, it worked. Finally I can work happy with CopyQ.
Thanks much.
