### ISSUE TITLE
L key still sends enter when not using vi-mode 

### ISSUE THREAD

**Issue by amosbird** [hluk/CopyQ#717]
#524 adds `L` key as vim mode's enter key. However it remains active when vi-mode is disabled.

**Comment by hluk** [comment]
I cannot reproduce this.

Did you disable the "Vi style navigation" option (**not** the FakeVim plugin)?

Isn't there by any chance a command overriding <kbd>L</kbd> key?

**Comment by amosbird** [comment]
Ah, there is a command using `L`. Thanks :smile:
