### ISSUE TITLE
When scrolling using mouse wheel the clipboard shown is nearly all empty

### ISSUE THREAD

**Issue by tukanos** [hluk/CopyQ#718]
This applies to CopyQ 3.01 and did not have issues before this version so the regression is probably 3.x bound.  Using it on Windows 7 x64 SP1.

When I'm using mouse wheel to scroll only first 20 items are shown.  All others are just flashing (really annoying) and does not show any text - probably not correctly refreshed.  Note: When keyboard is used either arrow keys or page up/down keys then text is correctly shown.

**Comment by hluk** [comment]
I just released [new version](https://github.com/hluk/CopyQ/releases/tag/v3.0.2) where this should be fixed.

**Comment by tukanos** [comment]
I confirm that this bug has been fixed in 3.02.
