### ISSUE TITLE
Images on macOS

### ISSUE THREAD

**Issue by gibfahn** [hluk/CopyQ#719]
The [images page in the wiki](https://github.com/hluk/CopyQ/wiki/Images) doesn't mention macOS, and there are no items in my preferences to set. Are images supported on macOS?

![image](https://cloud.githubusercontent.com/assets/15943089/26579580/4fd1df0e-452c-11e7-8db4-762f7922b839.png)

**Comment by hluk** [comment]
That's odd. CopyQ should load all plugins (with Image plugin) at start.

How did you install the app?

What does the log say? Log can be displayed using <kbd>F12</kbd> shortcut in main window or from menu "Help - Show Log".

**Comment by gibfahn** [comment]
```
Note [2017-05-28 21:11:56.840] Server-55485: No plugins loaded
Note [2017-05-30 14:26:20.292] Server-2363: No plugins loaded
```

Certainly seems like the issue. I installed with `brew cask install copyq`.

**Comment by hluk** [comment]
I cannot reproduce this. Can you close the app and reinstall (`brew cask reinstall copyq`)?

**Comment by gibfahn** [comment]
Tried that (twice), no luck.

Installed it on a Linux VM and images worked fine.

Not sure what else I can do to debug this.

**Comment by hluk** [comment]
Can you check what's in the plugin directory? You can copy the plugin path to clipboard in CopyQ from Action dialog (F5 shortcut) with command `copyq: copy(info('plugins'))`.

**Comment by gibfahn** [comment]
I think I must be doing something wrong. When I run this command the path should be copied to the clipboard right?

![copyq](https://cloud.githubusercontent.com/assets/15943089/26762833/9ace6fdc-4940-11e7-8aa1-72953e3a746b.gif)

**Comment by hluk** [comment]
The command should only copy the path to clipboard and not add it to the list -- disable "Store standard output" option or use `copyq info plugins` command instead.

BTW, do you have the latest version of CopyQ?

**Comment by gibfahn** [comment]
I'm on macOS Sierra 10.12.5 (the latest), and I should be on the latest copyq ():

```bash
➜  ~ ❯ copyq --version                                                                                                             ~
CopyQ Clipboard Manager v3.0.2 (hluk@email.cz)
Built with: Qt 5.8.0, LibQxt 0.7.0
```

Still not managing to get the output from that command, so I click `Ok` and then I should be able to paste it with `⌘-v` right?

**Comment by hluk** [comment]
If you run `copyq info plugins` from command line, it should print the plugin path.

Alternatively `copyq -e "copy(info('plugins'))"` should copy the path to system clipboard (it prints `true` as a result of the `copy()` function call).

I prefer to use the Action dialog because often `copyq` is not available on command line out of the box -- I think that's the case on OS X and Windows.

How did you install CopyQ?

**Comment by gibfahn** [comment]
I installed with `brew cask`, but I also raised a PR against the cask to symlink the `copyq` binary (https://github.com/caskroom/homebrew-cask/pull/35136).

Interestingly `copyq` fails from the command line, but `copyq --version` works:

```bash
➜  ~ ❯ copyq info plugins                                                                          ~
➜  ~ ❯ copyq                                                                                       ~
ERROR: QtFatal: This application failed to start because it could not find or load the Qt platform plugin "cocoa"
ERROR:    in "".
ERROR:    
ERROR:    Reinstalling the application may fix this problem. (:0, )
libc++abi.dylib: terminating with uncaught exception of type (anonymous namespace)::ExceptionQtFatal: This application failed to start because it could not find or load the Qt platform plugin "cocoa"
in "".

Reinstalling the application may fix this problem. (:0, )
^C^C[1]    29562 abort (core dumped)  copyq
➜  ~ ❯ copyq --version                                                                             ~
CopyQ Clipboard Manager v3.0.2 (hluk@email.cz)
Built with: Qt 5.8.0, LibQxt 0.7.0
```

![image](https://cloud.githubusercontent.com/assets/15943089/26817103/12c366da-4a8d-11e7-8d1e-181c9c504012.png)

**Comment by gibfahn** [comment]
`copyq info plugins` returns no output, which I think means that my plugin path is empty.

**Comment by hluk** [comment]
>I installed with brew cask, but I also raised a PR against the cask to symlink the copyq binary (caskroom/homebrew-cask#35136).

Nice, thanks!

I get same error, though `copyq info plugins` works fine (Sierra 10.12.5).

```
$ copyq
ERROR: QtFatal: This application failed to start because it could not find or load the Qt platform plugin "cocoa"
ERROR:    in "".
ERROR:    
ERROR:    Reinstalling the application may fix this problem. (:0, )
libc++abi.dylib: terminating with uncaught exception of type (anonymous namespace)::ExceptionQtFatal: This application failed to start because it could not find or load the Qt platform plugin "cocoa"
in "".

Reinstalling the application may fix this problem. (:0, )
Abort trap: 6
```

```
$ copyq version
CopyQ Clipboard Manager v3.0.2 (hluk@email.cz)
Built with: Qt 5.8.0, LibQxt 0.7.0
```

```
$ copyq info plugins
/Applications/CopyQ.app/Contents/Plugins/copyq
```

```
$ ls /Applications/CopyQ.app/Contents/Plugins/copyq
libitemdata.dylib	libitemimage.dylib	libitemsync.dylib
libitemencrypted.dylib	libitemnotes.dylib	libitemtags.dylib
libitemfakevim.dylib	libitempinned.dylib	libitemtext.dylib
```

What does `copyq info` print?

**Comment by gibfahn** [comment]
```bash
➜  node git:(pr-13487) ❯ copyq info                                                                                   ~/wrk/com/node
config: /Users/gib/Library/Preferences/com.copyq.copyq.plist
desktop: 
exe: /Applications/CopyQ.app/Contents/MacOS/copyq
has-global-shortcuts: 1
has-mouse-selection: 0
icons: 
log: /Users/gib/Library/Application Support/copyq/copyq/copyq.log
platform: OS X
plugins: 
themes: /Applications/CopyQ.app/Contents/MacOS/../Resources/themes
themes(custom): 
translations: /Applications/CopyQ.app/Contents/MacOS/../Resources/translations
translations(custom): 
```

**Comment by hluk** [comment]
This is probably case-sensitivity issue. The directory CopyQ finds should be "/Applications/CopyQ.app/Contents/**PlugIns**/copyq".

Fixed version is [here](https://github.com/hluk/CopyQ/releases/tag/osx-test).

**Comment by hluk** [comment]
I fail to fix the error when launching `copyq` -- it's possibly some Qt bug. This is only issue when using the symlink. Workaround is to use the real app path 

```
/Applications/CopyQ.app/Contents/MacOS/copyq
```

or 

```
QT_PLUGIN_PATH=/Applications/CopyQ.app/Contents/PlugIns copy
```

**Comment by gibfahn** [comment]
That looks like the fix! When I run by double clicking on the Application the Items are now showing up. 

![image](https://cloud.githubusercontent.com/assets/15943089/26828203/47ac2cb2-4ab8-11e7-99a1-af50f99ed58a.png)

Not sure how you worked that out, but thanks!

**Comment by gibfahn** [comment]
Regarding `QT_PLUGIN_PATH`, from a quick google [it looks like](http://doc.qt.io/qt-5/deployment-plugins.html):

>When the application is run, Qt will first treat the application's executable directory as the base directory for searching for plugins. For example if the application is in C:\Program Files\MyApp and has a style plugin, Qt will look in C:\Program Files\MyApp\styles. (See QCoreApplication::applicationDirPath() for how to find out where the application's executable is.) Qt will also look in the directory specified by QLibraryInfo::location(QLibraryInfo::PluginsPath), which typically is located in QTDIR/plugins (where QTDIR is the directory where Qt is installed). If you want Qt to look in additional places you can add as many paths as you need with calls to QCoreApplication::addLibraryPath(). And if you want to set your own path or paths you can use QCoreApplication::setLibraryPaths(). You can also use a qt.conf file to override the hard-coded paths that are compiled into the Qt library. For more information, see the Using qt.conf documentation. Yet another possibility is to set the QT_PLUGIN_PATH environment variable before running the application. If set, Qt will look for plugins in the paths (separated by the system path separator) specified in the variable.

So it looks like if you use a symlink QT will look in the symlink directory (which seems pretty broken to me). I guess it should be possible to work around this with one of the calls mentioned there. To be honest it's not a huge deal, so if it's a pain to fix documenting and moving on seems reasonable.

**Comment by hluk** [comment]
Hmm, it's bit ugly but [this](https://github.com/caskroom/homebrew-cask/pull/35256/files) works and is used by many other casks.

I'll update the version in cask when new release is available (the fix for plugins is currently only in pre-release for OS X).

Thanks for cooperation! :)
