### ISSUE TITLE
cmake command doesn't catch a missing dep with Qt 5

### ISSUE THREAD

**Issue by scottkosty** [hluk/CopyQ#720]
The cmake command succeeded for me but I got:

````
[ 98%] Building CXX object src/CMakeFiles/copyq.dir/__/qxt/qxtglobalshortcut_x11.cpp.o
[ 99%] Building CXX object src/CMakeFiles/copyq.dir/__/qxt/qxtglobal.cpp.o
/home/scott/IndependentInstalls/CopyQ/qxt/qxtglobalshortcut_x11.cpp:36:45: fatal error: qpa/qplatformnativeinterface.h: No such file or directory
compilation terminated.
src/CMakeFiles/copyq.dir/build.make:2734: recipe for target 'src/CMakeFiles/copyq.dir/__/qxt/qxtglobalshortcut_x11.cpp.o' failed
````
On Ubuntu, the following fixed it for me:

````
sudo apt-get install qtbase5-private-dev
````
Should the cmake command ideally fail because of the missing dependency?

This is with Qt 5.5.1 (the system libs of Ubuntu 16.04).

**Comment by hluk** [comment]
Hmm, not sure if it's possible to easily tell CMake the header is needed. For `qmake` it seem to be enough to say `QT+=gui-private`.

**Comment by scottkosty** [comment]
I see, thanks for the explanation. Since CopyQ has a pretty quick compilation time in my opinion, and the error from make makes the solution pretty obvious, let's not worry about this then.
