### ISSUE TITLE
Command completer popup hangs Ubuntu window manager

### ISSUE THREAD

**Issue by eguendelman** [hluk/CopyQ#722]
I installed latest CopyQ from ppa:hluk/copyq as per instructions, then created a new custom action/command, and when start to type the contents of the command, a completion popup appears.  For some reason, this causes the window manager in Ubuntu (14.04) to completely hang... I still see a moving mouse cursor, but nothing on the screen responds.  Even switching to another tty and killing copyq doesn't free it up.  I have to kill the compiz window manager and let it restart.

My workaround currently is that I compiled copyq from source, and made one modification to comment out the last line of CommandEdit constructor in 
https://github.com/hluk/CopyQ/blob/master/src/gui/commandedit.cpp

Full disclosure: I am actually running Ubuntu in VMWare on OSX host. Not sure if this has anything to do with it... 

If this is not reproducible on your end, could you at least consider adding a settings option to not allow completion popups?

Thanks

**Comment by hluk** [comment]
I cannot reproduce this with VirtualBox, Ubuntu 16.04 guest, Compiz 0.9.12.2 and CopyQ 3.0.2.

This could be some issue in older version of Compiz or some of its plugins.

Can you post backtrace after the window manager gets stuck? E.g build with `cmake -DCMAKE_BUILD_TYPE=Debug ...` and start CopyQ from separate tty `DISPLAY=:0.0 gdb ./copyq` (to print the backtrace press Ctrl+C and type `bt`).

BTW, is there any reason for running Compiz in VM? Seems like it would kill lot of the performance.

In any case, adding an **option to disable auto-completion** is a good idea.

**Comment by eguendelman** [comment]
Thanks for the prompt response.
Regarding debugging it, I was not able to do it using your approach because if I start copyq from a tty screen (and with DISPLAY=:0.0) then I don't get the copyq icon in my toolbar and can't get to a command editor.  The way I tried it is by running copyq from a terminal in the window manager, and ran gdb in a separate tty and attached it to the running copyq process.  I am attaching the backtrace.  Is it helpful?
[gdb.txt](https://github.com/hluk/CopyQ/files/1049574/gdb.txt)
[copyq_log.txt](https://github.com/hluk/CopyQ/files/1049575/copyq_log.txt)

I also had the problem when trying VirtualBox instead of VMWare (I happen to have both set up).  To be clear, I don't know that it's specifically a compiz issue, just that the windows contents are completely frozen but I still have a mouse cursor.  Very strange.  

My compiz is 0.9.11.3

Regarding why using Compiz in VM... mostly because I want my VM to match the environment I use on my work machine which has Ubuntu running natively.

**Comment by eguendelman** [comment]
FYI also happens on my desktop running native Ubuntu, so not related to VM.

**Comment by hluk** [comment]
I've added the option to disable autocompletion (865a37e4) -- "Auto-complete Commands" option in "General" config tab.

Still not sure what's going on -- could be issue with some older libraries (possibly Qt).

**Comment by eguendelman** [comment]
Thanks.  And sorry I forgot to mention that I am using Qt4 (WITH_QT5=OFF).

**Comment by hluk** [comment]
Oh, I completely forgot that official packages for Ubuntu 14.04 are using Qt 4 (I didn't even notice this in backtrace).

Seems like Qt bug: https://bugreports.qt.io/browse/QTBUG-6355

Not sure if I will be able to fix that.

**Comment by hluk** [comment]
OK, I have no idea how to fix this in CopyQ.

I would like to get rid of the old Qt 4 code soon and use only Qt 5 so **this probably won't get fixed**. (The only other supported platform that needs old Qt is openSUSE.)

**Comment by eguendelman** [comment]
Nice to see that you were able to identify the qt bug, and thanks for adding the disable option, it's good enough for my needs.
