### ISSUE TITLE
show what fonts are used for given item

### ISSUE THREAD

**Issue by amosbird** [hluk/CopyQ#725]
This would be a nice feature to debug font issues.

**Comment by hluk** [comment]
This is out of scope for a clipboard manager application.

If the item is plain text the font is directly taken from Appearance settings.

CopyQ uses simpler HTML rendering. The font selected for HTML by CopyQ can differ from the one that would be used by the application you paste the HTML into.

You should be able to use following command to view HTML items in Chrome or Firefox and inspect the fonts and styles there.

```ini
[Command]
Command="
    copyq:
    var app = 'chromium'
    var fileTemplate = Dir().temp().absoluteFilePath('copyq-XXXXXX.html')
    var item = selectedItemData(0)
    
    var file = TemporaryFile()
    file.setFileTemplate(fileTemplate)
    file.openWriteOnly()
    file.write(input())
    file.close()
    var filePath = file.fileName()
    
    hide()
    execute(app, filePath)"
InMenu=true
Input=text/html
Name=Open HTML
```

**Comment by amosbird** [comment]
ok, thanks. BTW, when copying from browser, copyq always generates two items like this ![](https://la.wentropy.com/Rut8.png). Can I make it only generate one?

**Comment by hluk** [comment]
Seems like an item for mouse selection is created and after you press Ctrl+C another item with same text is created.

I just fixed that (0c1b832b74792b49a9c5d5a9885ea1b9f130573b).

Without using the fixed version you can use an automatic command to ignore or remove the old item with same text.

```ini
[Command]
Automatic=true
Command="
    copyq:
    var oldText = str(read(0))
    var newText = str(input())
    
    if (oldText == newText)
      remove(0)"
Icon=\xf05e
Input=text/plain
Name=Omit Duplicate Text
```

**Comment by amosbird** [comment]
thanks!

**Comment by amosbird** [comment]
hmm, this is weird. Copyq shows different glyph than chromium  ![](https://la.wentropy.com/Ajaa.png)

**Comment by amosbird** [comment]
well, I just testes the latest commit, the duplication items are still there.

**Comment by hluk** [comment]
Do you use any automatic commands?

Note: The fix only works for new items (not existing ones).

**Comment by amosbird** [comment]
ah, I see. Thanks!
