### ISSUE TITLE
Right-mouse click to select clip to paste does not paste image

### ISSUE THREAD

**Issue by richlux** [hluk/CopyQ#727]
When using the right-mouse click to select a clip to paste, clicking an image does not paste the image.  It copies the image to the clipboard which can then be pasted via Control-V, but it should paste automatically like the other types of clips.

Rich

**Comment by hluk** [comment]
Pasting images works the same for text so there could be some issue with the target application.

What's the OS, desktop environment and the app you paste images into?

**Comment by richlux** [comment]
I'm running Windows 7 64-bit and pasting into Microsoft Word 2013.  I just restarted exited and restarted CopyQ and it's working now.  I know I did that before I posted the issue. Anyway, sorry for not realizing this sooner.

Rich

**Comment by hluk** [comment]
The pasting from main window and menu still may misbehave since the application only sends Shift+Insert and there is no way to check if the action was successful. Also focusing the target window may fail in some rare cases.
