### ISSUE TITLE
When searching for a string result is blurred.

### ISSUE THREAD

**Issue by tukanos** [hluk/CopyQ#728]
This applies to CopyQ 3.02 and did not have issues before this version so the regression is probably 3.x bound. Using it on Windows 7 x64 SP1.

When I'm searching for a string the searching result becomes blurred and unreadable.

I have prepared a screenshot: 
![Screenshot](https://res.cloudinary.com/morguefile/image/upload/s--Lm5oQXgb--/c_fit,h_1200,q_jpegmini,w_1200/vidz7irtgfdcaoo4cill.jpg)

In case the direct link goes blank here is a link to the  [screenshot](https://mfile.io/323U0H)

**Comment by hluk** [comment]
This was fixed recently. You can use the fixed version from [here](https://ci.appveyor.com/project/hluk/copyq/build/1.2.1043/job/gn86myf80nuc3m2s/artifacts).

Thanks for the report.

**Comment by tukanos** [comment]
I confirm that in the latest linked version this issue is fixed. 

Thank you for the fix.
