### ISSUE TITLE
Two questions about images in clipboard history window

### ISSUE THREAD

**Issue by richlux** [hluk/CopyQ#730]
I have two questions about images in the clipboard history window.

1)  Currently having to specify a Max Image height and Max Image width can cause some images to display cut off in the clipboard history.  Is there a way to specify only one of either the max height or max width and have the other determined automatically by maintaining the aspect ratio?

2) Is there a way to improve the quality of image thumbnails in the history window?  Currently images, especially screenshots, can be quite grainy.  Is there a way to apply anti-aliasing (like how images are displayed in Microsoft Word)?  It would be a nice improvement.  See the two examples of a webpage screen capture below:

Thumbnail in CopyQ:
![copyq](https://user-images.githubusercontent.com/25157703/27202089-378560c8-51ee-11e7-9c59-7640ab6bdbd6.png)

Thumbnail in Microsoft Word:
![word](https://user-images.githubusercontent.com/25157703/27202111-4ab8dbfc-51ee-11e7-8251-42ea752fb534.png)

Thanks,
Rich

**Comment by hluk** [comment]
> Is there a way to specify only one of either the max height or max width and have the other determined automatically by maintaining the aspect ratio?

Aspect ratio for thumbnails is not changed. Set width or height to zero so as not to limit the size (mentioned in tooltips for the configuration fields).

> Is there a way to improve the quality of image thumbnails in the history window?

I just fixed that (9d239ee792640279d623b7f129ca744c059dd889).

You can grab the fixed version for Windows [here](https://ci.appveyor.com/project/hluk/copyq/build/1.2.1044/job/fhrj15qf04ay5ccp/artifacts) (after it's built).

**Comment by richlux** [comment]
Excellent! Thank you. 

Rich
