### ISSUE TITLE
Linux/Ubuntu: CopyQ crasches when deteting a stored item to the Trash Tab

### ISSUE THREAD

**Issue by tnilzon** [hluk/CopyQ#732]
CopyQ crashes when deleting a stored item to the Trash Tab, and CopyQ has to be relaunched.

Since CopyQ version: v3.0.2 CopyQ crashes and needs to be restarted when a stored item in for example the Tab "Clipboard" is deleted. This happens regardless of using keyboard "Delete" or deleting by right click the item with the mouse.

kubuntu version 17.04
CopyQ version: v3.0.2

/Tomas Nilzon

**Comment by hluk** [comment]
Is there anything in the log (F12 shortcut)?

**Comment by tnilzon** [comment]
No, nothing in the Error log. This is a very annoying error since it is impossible to delete any item into the "Trash" tab. The error behavior (and crashing) is very easy to repeat, since it happens every time when trying to delete items.

**Comment by hluk** [comment]
Can you provide `coredumpctl dump` after the app crashes? (The output should start with something like `PID: 25040 (copyq)` if it was caught by system.)

**Comment by tnilzon** [comment]
Hi Lukas, here is the output:

TIME                            PID   UID   GID SIG COREFILE EXE 
Sat 2017-07-01 11:01:07 CEST   6228  1000  1000  11 present  /usr/bin/copyq

**Comment by hluk** [comment]
I don't see the backtrace. Can you try `coredumpctl dump 6228`? Thanks.

**Comment by tnilzon** [comment]
coredumpctl dump 6228
           PID: 6228 (copyq)
           UID: 1000 (tomas)
           GID: 1000 (tomas)
        Signal: 11 (SEGV)
     Timestamp: Sat 2017-07-01 11:01:05 CEST (11min ago)
  Command Line: /usr/bin/copyq
    Executable: /usr/bin/copyq
 Control Group: /user.slice/user-1000.slice/session-3.scope
          Unit: session-3.scope
         Slice: user-1000.slice
       Session: 3
     Owner UID: 1000 (tomas)
       Boot ID: 5fb5f32622dd4a7a8c33433757de7831
    Machine ID: f86b2079ab394f6bbe893efaaaa7890a
      Hostname: tomas-laptop
       Storage: /var/lib/systemd/coredump/core.copyq.1000.5fb5f32622dd4a7a8c33433757de7831.6228.1498899665000000000000.lz4
       Message: Process 6228 (copyq) of user 1000 dumped core.
                
                Stack trace of thread 6228:
                #0  0x000055d5e2080a3d _ZN13CommandAction11onTriggeredEv (/usr/bin/copyq)
Refusing to dump core to tty (use shell redirection or specify --output).

**Comment by hluk** [comment]
I have an idea what's going on. Possible fix is in [copyq-beta Ubuntu package](https://launchpad.net/~hluk/+archive/ubuntu/copyq-beta) and in git repo (27e50ddd65d8eb56bebbf88b8b078a5eb186aae1).

**Comment by hluk** [comment]
CopyQ 3.0.3 with the fix is now available as [copyq Ubuntu package](https://launchpad.net/~hluk/+archive/ubuntu/copyq).

**Comment by hendrik099** [comment]
How I can fix this (Zygote service is not accessible from PID 879, UID 1000) please help me

**Comment by hluk** [comment]
This issue should be fixed so I'm closing it. Please reopen if it doesn't work in CopyQ 3.0.3 and above.

> How I can fix this (Zygote service is not accessible from PID 879, UID 1000) please help me

@hendrik099 I need more info so I can reproduce it. Does it happen when deleting an item? Open new issue if it's not connected to this one.
