### ISSUE TITLE
"Drag" shows in the clipboard history when dragging files from SharePoint (2013)

### ISSUE THREAD

**Issue by richlux** [hluk/CopyQ#734]
When dragging files from a SharePoint 2013 library to my local drive, an entry called "Drag" gets put in the Clipboard history.  Viewing the content, I see two formats:  text/plain which contains "Drag" and text/uri-list, which contains the URL of the file I dragged to my computer.  Is there a way to prevent these from showing up in the clipboard history?

Thanks,
Rich

**Comment by hluk** [comment]
Following command may prevent storing such items.

```ini
[Command]
Automatic=true
Command="
    copyq ignore"
Icon=\xf05e
Input=text/plain
Match=^Drag$
Name=Ignore SharePoint Dragged Files
```

**Comment by richlux** [comment]
Excellent.  Thank you!

Rich
