### ISSUE TITLE
How to determine which tab has active clipboard item

### ISSUE THREAD

**Issue by richlux** [hluk/CopyQ#736]
I have multiple tabs with global commands to move specific copied items, such as images, URLs, etc. into their own tabs (and delete the item from the default clipboard tab). Since Copyq highlights the first item in each tab, there's no easy way to see which item is actually in the windows clipboard. Is there a way that Copyq could bold the text of the tab that contains the current clipboard item? This would make it easy to quickly see which tab had the current clipboard item. 

Thanks, 
Rich

**Comment by hluk** [comment]
Why would it be helpful to see which tab has the current clipboard item? What's the use case?

**Comment by richlux** [comment]
When binary data is stored in the clipboard, there's no way to know what that data is.  I just thought it would be helpful to know by having CopyQ indicate what is in the clipboard somehow, but it's not that important, so you can ignore this request.

Rich

**Comment by hluk** [comment]
There is a [command](https://github.com/hluk/copyq-commands/tree/master/Global#quickly-show-current-clipboard-content) that allows you to map a global shortcut to show popup message with current clipboard text. Perhaps it can be modified to also tell you what type of data clipboard contains.
