### ISSUE TITLE
Italian translation for GUI and installer

### ISSUE THREAD

**Issue by bovirus** [hluk/CopyQ#738]
Hi.

Thanks for your interesting software.

I want to cooperate 

- to finalize Italian translation for GUI. I already download the Italian language in .ts format and I'm working on it) and   

- to localize the installer. 
Could please post the installer script to enable me to translate it into Italian?

Thanks.

**Comment by hluk** [comment]
Installer script is in this repo in [shared/copyq.iss](https://github.com/hluk/CopyQ/blob/master/shared/copyq.iss).

BTW, you can translate GUI texts using [weblate](https://hosted.weblate.org/projects/copyq/master/it/) web service.

Thanks for the help!

**Comment by bovirus** [comment]
I pushed the translation (20% translated) of Italian language

I pushed the copyq.iss modified to add Italian language.

Please check ig it's OK.
