### ISSUE TITLE
Freelance project

### ISSUE THREAD

**Issue by Noizzzy** [hluk/CopyQ#739]
Hello Lukáš Holeček, 

first of all let me say that his is amazing script!

p.s. this is my first post in github so i am not sure if this request should be in the issues or Pull requests. If its in the wrong place, pardon me!

I would like to adapt this script Snippets.ini for answering customers emails that i get a lot. Would you be interested to help me out for agreed budget? If you are ok with that please inform me your day rate and contact me on _evaldas.cesnavicius@gmail.com_

I am sure that would not be anything too difficult for you. If you are busy can you recommend anyone?

looking forward hearing from you!
Eval

**Comment by hluk** [comment]
Sorry, completely forgot about this issue.

If there is anything specific you need to do, just create new issue and I (or others) will try to help. Though I won't be doing this as a second job.
