### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by happysurf** [hluk/CopyQ#743]
I have updated to 3.0.2 to 3.0.3 and now is impossible open CopyQ for this error.

![copyq error](https://user-images.githubusercontent.com/13637587/27903816-f6ff5a60-623a-11e7-9208-780ab632ea3d.png)

After uninstall and reinstall the previous same problem. 

CopyQ 3.0.3 + XP.

**Comment by JohnML1** [comment]
same problem here, try 3.02 or 3.0.1 that will run ok on Win XP. 
I took the *.zip, not the installer!

**Comment by happysurf** [comment]
You are right, my situation is:

**Portable:**
3.0.3 = get error;
3.0.2 = works;
3.0.1 = works:
**Installer:**
3.0.3 = get error;
3.0.2 = get error;
3.0.1 = not tested.

**Comment by hluk** [comment]
The difference is that latest version of CopyQ uses Qt 5.9.

Looks like [this issue](https://bugreports.qt.io/browse/QTBUG-58407) (closed because Qt is no longer supports Window XP).

You can try using the app built with different compiler from [here](https://ci.appveyor.com/project/hluk/copyq/build/1.2.1062/job/mf3xlp7q7erdotvy/artifacts) -- but it may require to install some libraries which cannot be bundled with the app.

**Comment by happysurf** [comment]
Thank you very much for the info, for now I remain with version 3.0.2 waiting to change O.S.

**Comment by hluk** [comment]
Since it's not difficult to build the app again with the older version of Qt, here is [CopyQ 3.0.3 built with Qt 5.7 for Windows XP](https://ci.appveyor.com/project/hluk/copyq/build/job/nw4uy10dngtxaybb/artifacts). This should definitely work.

**Comment by happysurf** [comment]
Thanks, works fine!

**Comment by smaragdus** [comment]
**@hluk**
I am not using _Windows XP_ (_Windows 8_ here) but just asking- have you considered releasing an official _Windows XP_ version of **CopyQ** built with **Qt 5.7**?  Such official _Windows XP_ version would spare time both for the users (opening issues) and for you (responding to issues).

**Comment by hluk** [comment]
@smaragdus I was thinking about that too. AFAIK there are currently no app issues connected to Qt 5.7 on Windows. Currently, the only reason to move to new Qt are that it could solve some issues in future.

**Comment by hluk** [comment]
Closing. If you still have this issue please reopen and provide details.
