### ISSUE TITLE
FakeVim item + text is not aligned correctly in Preferences > Items tab

### ISSUE THREAD

**Issue by scottkosty** [hluk/CopyQ#745]
In the Preferences > Items tab, FakeVim looks to be shifted about one character over to the left, compared to the rest of the items. See the screenshot below:

![screenshot from 2017-07-12 00-48-41](https://user-images.githubusercontent.com/1149353/28102249-13e95d14-669c-11e7-8ec9-d6549941a7fa.png)

This is very minor, so please feel free to close if not worth the time.

**Comment by hluk** [comment]
It's even more apparent on 4K screens.

![image](https://user-images.githubusercontent.com/38054/28489009-2a54d302-6eb8-11e7-8e58-e76b00ce23b8.png)

I think this is problem with all list in the app (tab tree and command list in Command dialog).

Anyway, I've updated the FakeVim icon (Qt Creator has bigger version now) so at least in this case the rendering should be better.
