### ISSUE TITLE
Rendering of unselected item changed

### ISSUE THREAD

**Issue by scottkosty** [hluk/CopyQ#746]
After bf586a1b, the text of an unselected item is more difficult for me to read.

Before:

![before](https://user-images.githubusercontent.com/1149353/28129749-8b7c5582-6702-11e7-8882-424efcae6977.png)

After:

![after](https://user-images.githubusercontent.com/1149353/28129753-8fe45642-6702-11e7-86e4-02c40dcbf107.png)

Was the change intended?

**Comment by hluk** [comment]
Normal text rendering should follow settings in Appearance tab in configuration. If you have set white foreground color for selected items this should be OK.

Unfortunately, it's not quite possible to change color for rich text or HTML items so the text and background stays the same when selected and unselected.

**Comment by scottkosty** [comment]
Changing the selected text to black made it readable for me again. Thanks.
