### ISSUE TITLE
Pinned and protected items

### ISSUE THREAD

**Issue by CarlosTorch** [hluk/CopyQ#747]
How do this feature work on Windows? I really need this function but I just can't find in anywhere in CopyQ

**Comment by royharoush** [comment]
after you enable it in the shortcuts. 

![image](https://user-images.githubusercontent.com/8113056/28312840-41c446b0-6bbd-11e7-8298-07ff0deed3e3.png)






it looks like this 
![image](https://user-images.githubusercontent.com/8113056/28312698-bf9557d8-6bbc-11e7-8802-6483311fd919.png)


![image](https://user-images.githubusercontent.com/8113056/28312794-1ae237a0-6bbd-11e7-8e3b-4bcb087cf477.png)


note: you need to add both pin and unpin.

**Comment by CarlosTorch** [comment]
Weird. i don't have those shortcuts on my list.

![borrar](https://user-images.githubusercontent.com/26047436/28317615-f931b30c-6b84-11e7-82c4-bc6121bd4f4f.JPG)

**Comment by royharoush** [comment]
what version are you using ?

**Comment by CarlosTorch** [comment]
this:

![borrar](https://user-images.githubusercontent.com/26047436/28322547-a07c72d8-6b93-11e7-92de-d2d53c79cf41.JPG)

**Comment by royharoush** [comment]
strange, not sure where i pulled those off from. 
i've exported my commands. 
https://gist.githubusercontent.com/royharoush/1a9f79dc679d38038f92f6789d83e4fd/raw/9fad88b2545ac4d099d48a1e1c44e18bc18d7439/pinCommands.ini

try to load those using the import functions. 
let me know if that worked out for you.

**Comment by CarlosTorch** [comment]
I was able to import it but also getting this error when applied 
![borrar](https://user-images.githubusercontent.com/26047436/28323128-286ff100-6b95-11e7-9f2f-b7d4669a89dd.JPG)

**Comment by royharoush** [comment]
you're using the the portable version ? if so, how did you upgrade to 3.0.3 ?

**Comment by royharoush** [comment]
my bad. go into options and enable this plugin. 

![image](https://user-images.githubusercontent.com/8113056/28323993-05823a88-6be3-11e7-88c2-4d553e59d2c0.png)

**Comment by CarlosTorch** [comment]
Not using portable version.
I've just installed a fresh copy on my friend's laptop (win7, I'm on win10) via teamviewer and the shortcuts aren't there either.

**Comment by royharoush** [comment]
@CarlosTorch making sure you see my comment above.

**Comment by CarlosTorch** [comment]
this is what I have 
![borrar](https://user-images.githubusercontent.com/26047436/28324356-66de25c6-6b98-11e7-8e12-5976a311dde2.JPG)

**Comment by royharoush** [comment]
do you have this file under your copyq installation folder ? 
![image](https://user-images.githubusercontent.com/8113056/28324636-8bd0ec46-6be4-11e7-9f2c-893316959cf1.png)

**Comment by CarlosTorch** [comment]
i'm missing that one
![borrar](https://user-images.githubusercontent.com/26047436/28324936-d527e66a-6b99-11e7-8d61-7905a27b6c19.JPG)

**Comment by royharoush** [comment]
strange, which is probably the reason why its not working. 
you could try the portable version, should work. you could also download it and copy the libitempinned.dll into the folder and it will probably work. (after you restart copyq so the libraries will be reloaded).
@hluk  should probably take a closer look into the build, maybe a flag is missing.

**Comment by CarlosTorch** [comment]
I did so and now it's working great! Thank you so much for your time, sir

**Comment by royharoush** [comment]
@CarlosTorch no problem.

**Comment by hluk** [comment]
Sorry about late reply. The "item pinning" feature was indeed missing from Windows installer.

Fixed installer is [here](https://ci.appveyor.com/project/hluk/copyq/build/1.2.1077/job/e9ithp1elj113nv6/artifacts).

**Comment by hluk** [comment]
I also added documentation: [Pin Items](http://copyq.readthedocs.io/en/latest/pin-items.html)

**Comment by CarlosTorch** [comment]
Thanks hluk. Wonderful and useful software.
