### ISSUE TITLE
Auto-record text inside fields

### ISSUE THREAD

**Issue by MarkoIndaco** [hluk/CopyQ#748]
As title, a usefull tip could be the ability to auto-save the typed text by selectable range time (every xx seconds and/or minutes), or auto-save if the page was accidentally refreshed or something goes wrong (for example error due to a failed login or failed data typed).

**Comment by hluk** [comment]
Do you mean auto-saving text in other applications? That would be quite difficult to implement (if not impossible) for most platforms.

**Comment by MarkoIndaco** [comment]
First of all thank you for reply and many sorry for very late reply... What I mean is, for example when you type in a blank filed (like this) to post a comment in a blog or a site, and you made a refresh (or page refresh itself for some reason), then the ability to "save" the text.

**Comment by hluk** [comment]
Yeah, sorry, this is probably not going to happen. I don't see how this can be implemented.

So I'm closing this even though I would find this feature very useful myself (writing a longer post on a web page I often do Ctrl+A,Ctrl+C to save my work).
