### ISSUE TITLE
"null" in clipboard item list

### ISSUE THREAD

**Issue by richlux** [hluk/CopyQ#749]
I'm not sure what's causing it, but occasionally I will see "null" (without the quotes) in my clipboard list.  Has anyone else seen this or know what the cause is?

Thanks,
Rich

**Comment by hluk** [comment]
Can you check what data the item contains (F4 shortcut)? Also check data in clipboard if it still has the data (Ctrl+Shift+C).

**Comment by richlux** [comment]
They both show a type of text/plain and a contents of "null" (spelled out). When I paste into an editor, it pastes "null", so it really contains that text, but I am definitely not copying that text.

Thanks,
Rich

Richard Luxenberg
Woodbourne Solutions, Inc.
12800 Middlebrook Road
Suite 300
Germantown, MD 20874
phone: 301-428-7620 x116
fax: 301-428-7621
http://www.woodbournesolutions.com

________________________________

**Comment by hluk** [comment]
Do you use any commands that use `copy()` function? You can enter `copy(` in Find field in Command dialog to filter those commands.

**Comment by richlux** [comment]
I don’t have any commands that use copy().  I do have two commands to move images and files to other tabs, but they use the internal “Match Items” and “Copy to tab” options.

Thanks,
Rich

**Comment by hluk** [comment]
Strange, maybe it gets copied by some other app.

Anyway, you can ignore "null" by adding following command.

```ini
[Command]
Automatic=true
Icon=\xf06a
Match=^null$
Name=Ignore \"null\"
Remove=true
```

**Comment by richlux** [comment]
Thanks. I’m going to watch it for a little while to see if I can determine what is causing it.

Thanks,
Rich

Richard Luxenberg
Woodbourne Solutions, Inc.
12800 Middlebrook Road
Suite 300
Germantown, MD 20874
phone: 301-428-7620 x116
fax: 301-428-7621
http://www.woodbournesolutions.com<http://www.woodbournesolutions.com/>
