### ISSUE TITLE
copying from preview copies [space+...]

### ISSUE THREAD

**Issue by royharoush** [hluk/CopyQ#754]
Hi, 
when you copy the last line from preview (not the full preview), the space and 3 dots will also be copied into clipboard. 
i think the problem is with that the UI object of [...] is concatnated into the actual note.string.

version is 3.0.3

![image](https://user-images.githubusercontent.com/8113056/28751964-fa7af0d8-751c-11e7-9435-47fe205fd611.png)

**Comment by hluk** [comment]
I've change it so the ellipsis gets expanded when selecting text near it.

Fixed version for Windows will be available [here](https://ci.appveyor.com/project/hluk/copyq/build/1.2.1097/job/m5a1mlcc33i4v72o/artifacts) (after it's built).
