### ISSUE TITLE
How to open URL in clipboard list

### ISSUE THREAD

**Issue by richlux** [hluk/CopyQ#757]
I'm sure there is a way to do this, but I haven't figured it out.  Is there a way to open a URL that is in the clipboard list (perhaps with a right-mouse click option)?  Sometimes, rather than move the item to the clipboard by double clicking it, I want to just open the URL in the default browser.

Thanks,
Rich

**Comment by hluk** [comment]
There is "Open in &Browser" predefined command - in Command dialog (F6), click Add button, select the command and confirm.

**Comment by richlux** [comment]
That did it. 

Thanks, 
Rich

**Comment by nicolnt** [comment]
Example to open selected text into DeepL translator

```js
copyq:
/* Version : 26-04-2024 */
copy()
var text = str(clipboard())

const DeepLURL = "https://www.deepl.com/translator#en/fr/"

if (text) {
    let requestURL = DeepLURL + encodeURIComponent(text)
    open(requestURL)
}
```
