### ISSUE TITLE
How to add current time to copied content?

### ISSUE THREAD

**Issue by BruceChen2017** [hluk/CopyQ#758]
I mean when you copy something,copyq will contain current time as well as copied content

**Comment by SmileyStiles** [comment]
Look in the help under Command Examples.  There is an example to paste the current date and time and with some modifications I'm sure you could add your copied content.

**Comment by SmileyStiles** [comment]
I was learning JavaScript and if I understand what you want I think this is what you would need.  Copy the following code (ctrl-c) and then start a new command and click the "Paste Commands" button.  Then click OK.  This should have created a new item on your Items menu or mouse right click menu.  For JavaScript programmers there may be a better way of doing this but this was what I could come up with from my one day of learning JavaScript.

Copy the below this line:
[Command]
Name=Paste Date/Time and Selected Text
Command="
    copyq:
    var time = dateString('yyyy-MM-dd hh:mm')
    var text = input()
    copy(time + '  -  ')
    copySelection(time + '  -  ')
    paste()
    copy(text)
    copySelection(text)
    paste()"
Input=text/plain
InMenu=true
HideWindow=true
Icon=\xf0ea

**Comment by BruceChen2017** [comment]
@SmileyStiles Your custom command didn't work for me.Thanks anyway.

**Comment by hluk** [comment]
There's [this command](https://github.com/hluk/copyq-commands/tree/master/Automatic#store-copy-time) (for details, see [README in the same repo](https://github.com/hluk/copyq-commands/blob/master/README.md)).
