### ISSUE TITLE
[Ubuntu 16.04] Crash on select

### ISSUE THREAD

**Issue by koxu1996** [hluk/CopyQ#759]
I am using latest 3.0.3 version from your ppa, but this issue was also in previous ones: sometimes on startup there is crash:
![image](https://user-images.githubusercontent.com/6506780/29059373-891bedf2-7c15-11e7-9b1e-0957668b679a.png)
I tried removing package with `--purge` option, but it did not help.

**Comment by koxu1996** [comment]
There is some problem with Qt libs:
![crash](https://user-images.githubusercontent.com/6506780/29359654-d4b463e6-827f-11e7-8562-2f3fd34188a2.gif)
```
ERROR: QtFatal: Cannot mix incompatible Qt library (version 0x50501) with this library (version 0x50800) (:0, )
terminate called after throwing an instance of '(anonymous namespace)::ExceptionQtFatal'
  what():  Cannot mix incompatible Qt library (version 0x50501) with this library (version 0x50800) (:0, )
Aborted (core dumped)
```

**Comment by hluk** [comment]
If CopyQ is installed from PPA, it must use Qt libraries provided by Ubuntu, i.e. those installed in `/usr/lib*` path.

It could that some different Qt version installed in system has a config file under `/etc/ld.so.conf.d/` or it changes `LD_LIBARY_PATH` env variable.

**Comment by koxu1996** [comment]
Thank you for response. `LD_LIBARY_PATH` was empty, but there was a file `/etc/ld.so.conf.d/qt58.conf` containing: 
```
/opt/qt58/lib
```
I removed it, restarted computer and reinstalled copyq, but I am still getting same error. Output from `ldd`,`strace`,`ltrace` is same as before.

**Comment by hluk** [comment]
Can you just uninstall the old Qt versions instead? Alternatively, you may need to [refresh cache of dynamic linker](https://stackoverflow.com/questions/21758828/purging-and-rebuilding-ldconfig-cache).

**Comment by koxu1996** [comment]
Refreshing cache helped :+1: Thank you very much indeed.
