### ISSUE TITLE
Snippets pasting issue

### ISSUE THREAD

**Issue by Noizzzy** [hluk/CopyQ#760]
Hello guys,

hope you are doing fine!

I am using Snippets.ini template and i am having weird issues:

When i choose a snippet from pop up menu and paste it i get the other snippet that i did not choose. 
In the clipboard everything seems to be normal. Adding screenshot.
Also #5 is for some reason duplicated, but it is not in clipboard - snippets.

I guess it would be easier to reintstall the program and make the snippets again but i am not sure if i wont face the same issue in the future so it would be the best to solve whats cousing it.

If you have any idea please let me know!
thanks!
Eval

![copyq_1](https://user-images.githubusercontent.com/29855540/29061938-5ede7ace-7c28-11e7-9957-47a25b336a13.JPG)

**Comment by hluk** [comment]
Can you try the fixed [snippet command](https://github.com/hluk/copyq-commands/blob/master/Global/snippets.ini)? If you want to use list instead of the combo box search, replace `listSnippets = false` with `listSnippets = true` at the top of the command.
