### ISSUE TITLE
copy plain text instead of rich one

### ISSUE THREAD

**Issue by amosbird** [hluk/CopyQ#761]
Hi, can I make copyq copy text from browser and store it as plain text only? Rich text fails to be pasted into virtualbox.

**Comment by Johnstone-Tech** [comment]
I believe you can toggle rich text in the preferences.

 - Open Preferences (ctrl-p)
 - Under the items Tab select Text and Uncheck "Save and Display HTML and Rich Text"

**Comment by amosbird** [comment]
ah,  thanks!
