### ISSUE TITLE
Double Click Paste stops working when . . .

### ISSUE THREAD

**Issue by SmileyStiles** [hluk/CopyQ#762]
So here's the scenario:   I'm typing in an email, then toggle the CopyQ main program, scroll through the list and double click on the clip that I want.   The CopyQ program closes and then the clip appears in my email where I had left off.   That's perfect and exactly what it should do!

But when I check (turn on) the setting "Show Simple Items" on the History Tab in the Preferences.  Double Clicking no longer does anything.   Hitting the Enter key still works but not the double clicking which is what I got used to doing.  So, I believe this is a bug.  All I did was change the one setting to show the smaller "Simple Item" views in the clip list.

**Comment by trivender** [comment]
> @SmileyStiles says  ...The CopyQ program closes... 

But I don't want program to close(minimize). Please suggest.
