### ISSUE TITLE
Better clipboard editor

### ISSUE THREAD

**Issue by amosbird** [hluk/CopyQ#763]
Hi, how can I make current editor more keyboard centric (with readline hot keys or vim like editing ability) ? Or do we have some kind of external editor support?

**Comment by SmileyStiles** [comment]
I just installed this CopyQ and still learning.  But I think I can answer your question.  Select your clip then F2 to edit or CTRL-E to edit in an external editor.  The external editor can be set from the History Tab in the Preferences Menu.   Now I have a question. What is VIM?  I've been hearing a lot about that since I have been testing these clipboard managers.

**Comment by amosbird** [comment]
hmm, how about we integrating ktexteditor ?

**Comment by hluk** [comment]
Why not use external editor then? Isn't it same as opening pop up window?

Internal editor supports Vim-like editing if you enable FakeVim plugin. Go to Configuration, Items tab, select FakeVim and check "Enable FakeVim for Editing Items".

**Comment by amosbird** [comment]
ah, thanks. Um, `ctrl-enter` doesn't work when FakeVim is enabled. Also, how can I switch to a dark theme for the internal editor ?

**Comment by hluk** [comment]
What should Ctrl+Enter do?

You can change the colors for editor separately in Appearance settings.

**Comment by amosbird** [comment]
itemeditorwidget has a eventfilter for `ctrl-enter`

```
bool ItemEditorWidget::eventFilter(QObject *object, QEvent *event)
{
    if ( object == m_editor && event->type() == QEvent::KeyPress ) {
        QKeyEvent *keyevent = static_cast<QKeyEvent *>(event);
        int k = keyevent->key();

        if (k == Qt::Key_Return || k == Qt::Key_Enter) {
            Qt::KeyboardModifiers mods = keyevent->modifiers();
            if ( (mods & (Qt::ShiftModifier | Qt::AltModifier | Qt::MetaModifier)) == 0 ) {
                bool controlPressed = mods.testFlag(Qt::ControlModifier);
                if (m_saveOnReturnKey && controlPressed ) {
                    keyevent->setModifiers(mods & ~Qt::ControlModifier);
                    return false;
                }
                if ( m_saveOnReturnKey || controlPressed ) {
                    saveAndExit();
                    return true;
                }
            }
        }
    }

    return false;
}
```

it commits current changes and goes back to the main menu.

**Comment by hluk** [comment]
Use `:wq` (`:q!` to exit without saving) or put `noremap <C-Enter> :wq<CR>` in FakeVim's config file.

Alternatively, you can use F2 to save (not sure why this shortcut is not intercepted by FakeVim).

**Comment by amosbird** [comment]
Great! Thank you @hluk
