### ISSUE TITLE
Pasting pinned items distorts the way they are displayed and crashes CopyQ

### ISSUE THREAD

**Issue by Kzer-Za** [hluk/CopyQ#765]
If all items in a tab are pinned, then pasting them messes with the way they are diplayed. I have a tab with 8 items. If I paste any of the 4 lower items, they are getting displayed incorrectly: some (consisting of several lines) overlap with each other, some getting "duplicated" - displayed like, e.g. 4th and 5th item are the same, though when you paste them, they are original items.

Trying to paste the first 4 items just crashes CopyQ if I try to do it immediately after starting CopyQ, but if I first paste at least once from the second 4 items, then next I can paste items from the first half of the list without crashing CopyQ, but if I do that, the items in the list get shuffled seemingly randomly.

I use linux and CopyQ 3.0.3.

**Comment by hluk** [comment]
I fail to reproduce this though I remember similar bug was already fixed in latest version. Can you double-check if the version is really 3.0.3 in About dialog box? (From menu select "Help - About", Shift+F1.)

Do you paste the items with Enter key?

**Comment by Kzer-Za** [comment]
> Can you double-check if the version is really 3.0.3

Yes, I checked it before posting. I updated today because I was using one of the earlier versions, where pinning didn't work. Since you say that a similar bug was fixed, I'm going to uninstall it and install again, maybe it's because I updated. I hope I don't have to purge my config though, reconfiguring all my settings would be a bother.

**Comment by Kzer-Za** [comment]
Nope, uninstalling and installing it again didn't help.

I decided to check if anything is wrong with the commands:
Pinning:
`copyq: plugins.itempinned.pinData()`
Unpinning:
`copyq: plugins.itempinned.unpinData()`

**Comment by hluk** [comment]
Are there any warnings or errors in log? (From menu select "Help - Show Log", F12.)

Can you also post output of `copyq --version`?

**Comment by Kzer-Za** [comment]
`copyq --version
CopyQ Clipboard Manager v3.0.3 (hluk@email.cz)
Built with: Qt 5.9.1, LibQxt 0.7.0`

**Comment by hluk** [comment]
Still haven't noticed this behavior. Do you encrypt the items or the tab? Do you synchronize the tab with a directory on disk? (These are settings in "Items" config tab - default is non-encrypted and not synchronized.)

**Comment by Kzer-Za** [comment]
> Do you encrypt the items or the tab? Do you synchronize the tab with a directory on disk?
No and no. Moreover, after uninstalling and installing CopyQ didn't help, I uninstalled it again and deleted its config folder, so after installing it again I restored its settings manually. There's not much manual settings - a hotkey for opening the main window always on clipboard tab, dark theme, and this tab with often used text strings.

After that, the behavior I wrote about is still there. For now I have come up with a workaround: I do not pin the last item in this tab. As long as at least one item is not pinned, this behavior is not observed. However, this is only a stopgap: if I delete the last item (say, I don't need it anymore) and forget to unpin the next last item, this bug would come up again.

**Comment by hluk** [comment]
It might be worth a shot to try git version of CopyQ. If you are on Arch Linux, try installing `copyq-git` package; if you use Ubuntu, try [copyq-beta from PPA](https://launchpad.net/~hluk/+archive/ubuntu/copyq-beta) (I just updated the package).

**Comment by Kzer-Za** [comment]
> It might be worth a shot to try git version of CopyQ

I gave it a shot just now. In this version pinning isn't working at all. Whether the item is pinned or unpinned, when you select and insert it, it moves to the top of the tab. Even unpinned items get on top of pinned items.

`copyq --version`
`CopyQ Clipboard Manager v3.0.3-66-gd10bcd9b`

**Comment by hluk** [comment]
OK, thanks for the test, I'll fix that. Did the app crash at any point?

**Comment by Kzer-Za** [comment]
> Did the app crash at any point?

No, in that respect it works fine.

**Comment by Kzer-Za** [comment]
Kept forgetting to check whether it's been fixed. Checked it out now in v3.1.2, and everything seems fine.
