### ISSUE TITLE
Divide clip in to smaller clips

### ISSUE THREAD

**Issue by SmileyStiles** [hluk/CopyQ#766]
I was looking for a way to take a clip with a lot of lines of text and separate each line into individual clips.  
I know this could be done manually, but I have a list as an ascii text file that has hundreds of lines that I would like each line to be it's own clip.  To manually clip each one would take awhile.

**Comment by hluk** [comment]
Following command could help ([how to add this to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)).

```ini
[Command]
Command="
    copyq:
    var text = str(input())
    var items = text.split('\\n').reverse()
    add.apply(this, items)"
Icon=\xf0ca
InMenu=true
Input=text/plain
Match=\\n
Name=Split
Shortcut=ctrl+shift+s
```

**Comment by SmileyStiles** [comment]
Could Help!?!   That's exactly what I was looking for!  Thank you!!
I'm new to this JavaScript or is it QTScript?   Do you know of some kind of tutorial for this Scripting language?

**Comment by hluk** [comment]
Yup, it's Qt Script but it's basically the same as JavaScript (only a few functions may not be available).

To dive deeper, definitely check these links:
- [Scripting](http://copyq.readthedocs.io/en/latest/scripting.html)
- [API Reference](http://copyq.readthedocs.io/en/latest/scripting-api.html)
- [Writing Commands](http://copyq.readthedocs.io/en/latest/writing-commands-and-adding-functionality.html)
- [CopyQ Commands repository](https://github.com/hluk/copyq-commands)
