### ISSUE TITLE
Image gets duplicated on Sync tab

### ISSUE THREAD

**Issue by SmileyStiles** [hluk/CopyQ#769]
With an exception of a little annoying duplication of image I would like to say that the Sync is working great now!  I now see what it is supposed to do and can see how this would be powerful for people in the office environment.   I really have no need for syncing but I'm just trying to help you out with some of these bugs.   I think CopyQ has the potential for being the number one clipboard manager out there, even better than Ditto.

So here's the bug.  When I dragged an image over to the Tab that is syncing, it creates two image.  The sync directory looks like this:
**CopyQ.ID9624.png**
copyq_0000.html
copyq_0000.txt
copyq_0001.txt
copyq_0002.txt
**copyq_0003.png**
copyq_0003.uri
copyq_0003_copyq.dat

Notice that there are two PNG files.
I'm using Windows 7 and CopyQ v3.0.3-46-gd7f09f9e

**Comment by hluk** [comment]
Fixed. Thanks for the report!
