### ISSUE TITLE
Add option to store text selection in a seperate tab

### ISSUE THREAD

**Issue by hedning** [hluk/CopyQ#771]
Hi, I enjoy having selections being saved in copyq, but it can become fairly noisy. It would be really nice having an option to store selections in a separate tab. So duplicating the tab storing option for the clipboard:
![image](https://user-images.githubusercontent.com/71978/29722801-66aa0db6-89c2-11e7-9fea-911117e94fad.png)

Having looked at the code I'm guessing what's needed is something like this [here](https://github.com/hluk/CopyQ/blob/master/src/gui/mainwindow.cpp#L2800):
```cpp
    if (storeData) {
      if (isSelection)
        setTextData(&data, m_options.selectionTab, mimeOutputTab);
      else
        setTextData(&data, m_options.clipboardTab, mimeOutputTab);
    }
```
Is this something you're interested in doing (or merging I'm happy to take crack at implementing it)?

**Comment by hluk** [comment]
It can be done with a command. ([See how to add commands to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them))

```ini
[Command]
Automatic=true
Command="
    copyq:
    var tabName = 'Selections'
    setData(mimeOutputTab, tabName)"
Icon=\xf245
MatchCommand="copyq: dataFormats().indexOf(mimeClipboardMode) == -1 && fail()"
Name=Store Mouse Selections in Separate Tab
```

It can be pretty useful for others so [I've added it to command repository](https://github.com/hluk/copyq-commands/tree/master/Automatic#store-mouse-selections-in-separate-tab).

Thanks for the idea.

**Comment by hedning** [comment]
Ah, nice. Thanks 😀
