### ISSUE TITLE
Any way quick to clear formatting from item in clipboard list so it's just plain text?

### ISSUE THREAD

**Issue by richlux** [hluk/CopyQ#772]
Currently to remove formatting from an item in the clipboard list (to make it plain text), I have to right-mouse click the item, select "Edit", Click the "Erase Style" button, and Save the changes.  Is there a way I can make a menu item to quickly clear the formatting?

Thanks,
Rich

**Comment by SmileyStiles** [comment]
Yes, you could set up a command to do that and then you would have that option when you right click on an item, or in your Item menu on the side or on the pull down menu.

This command is already built in so no programming.  Here's how:
On the file menu select "Commands/Global Shortcuts"  or hit F6
Pick the ADD button
Pick from the list "Paste as Plain Text" and hit Ok
Hit Ok to exit the Command window.

Now you should have the new command added to your menus.

**Comment by richlux** [comment]
Thanks, but that's not what I'm trying to do. I know about the command to Paste as Plain Text, but I don't want to paste anything. I also know that I can set it to only copy plain text, but that's not what I want either. I just want a way to convert an item already in the list to plain text. There must be a scripting command to do it, I just don't know what it is. 

Rich

**Comment by SmileyStiles** [comment]
Ahh I see.  There is also another way, hit "Show Content" or F4 and delete what's not Plain Text.  As for a command, I'm just learning JavaScript so this isn't exactly what you want, but it adds a new instance of the selected text to the list.
[Command]
Name=Add to list as Plain Text
Command="
    copyq:
    var text = input()
    copy(text)
    copySelection(text)
    add(text)"
Input=text/plain
InMenu=true
Icon=\xf0ea

**Comment by hluk** [comment]
With following command you can remove HTML formatting of selected item from menu.

```ini
[Command]
Command="
    copyq:
    removeData(mimeHtml)"
Icon=\xf12d
InMenu=true
Input=text/html
Name=Remove HTML
```

**Comment by richlux** [comment]
Exactly what I needed. Thank you! 

Rich

**Comment by erenseymen** [comment]
> With following command you can remove HTML formatting of selected item from menu.
> 
> [Command]
> Command="
>     copyq:
>     removeData(mimeHtml)"
> Icon=\xf12d
> InMenu=true
> Input=text/html
> Name=Remove HTML

If you want to be able to clear HTML styling for multiple selected items, you need to remove the input type field (Input=text/html).

Like this:
```
[Command]
Command="
    copyq:
    removeData(mimeHtml)"
Icon=\xf12d
InMenu=true
Name=Remove HTML
```

Just FYI.
