### ISSUE TITLE
Everything is selected when opening

### ISSUE THREAD

**Issue by SmileyStiles** [hluk/CopyQ#775]
Sometimes when I open Copyq, everything in the tab will be selected.  
It's not that big of a deal, I just select what I want and then that will be the only thing selected and now ready to paste, but I just thought I would let you know.   Also it doesn't happen everytime, only every now and then.
This is with Windows 7 and Copyq v3.0.3-46-gd7f09f9e

**Comment by hluk** [comment]
Is this still an issue?

Do you use any commands with `selectItems`? You can filter the commands in the Command dialog - enter "selectItems" in the "Find" entry field at the top of the dialog.
