### ISSUE TITLE
Some items become huge (empty space) when tagged

### ISSUE THREAD

**Issue by olejorgenb** [hluk/CopyQ#776]
CopyQ 3.0.3 built with webkit support.

I enable eg. https://copyq.readthedocs.io/en/latest/command-examples.html#show-copy-time and copy some text from a browser (tested both Firefox and Chromium) and this is the result: (copied "CopyQ" title from new issue page at github)

![2017-08-31-185451_634x554_scrot](https://user-images.githubusercontent.com/72201/29935089-e7fb5a0e-8e7d-11e7-8d0a-6a328300a0ea.png)

**Comment by hluk** [comment]
Possibly fixed in master branch (93f8653390f80af10d53a1b89ce2e488fb134763).
