### ISSUE TITLE
 Retire the tray/system icon on Linux (Gnome)

### ISSUE THREAD

**Issue by forteller** [hluk/CopyQ#778]
Gnome is [retiring the legacy system tray](http://www.omgubuntu.co.uk/2017/09/will-you-miss-gnome-legacy-tray). Ubuntu removed the same thing a long time ago and is now moving to Gnome. When I first start CopyQ it opens only as a system icon in the tray, and I have to right click on it to get to its UI and preferences – This will soon no longer be possible.

I hope you will be able to switch the new system before Ubuntu 17.10 arrives. Thank you so much!

**Comment by gbcox** [comment]
I believe this has already been covered.  You might want to review:  #378

**Comment by hluk** [comment]
@forteller If CopyQ won't detect tray area the app will be minimized instead of completely hidden, so user should be always able to access the application with just mouse.
