### ISSUE TITLE
Next/previous item hotkey not configurable?

### ISSUE THREAD

**Issue by olejorgenb** [hluk/CopyQ#779]
I'm used to ctrl-n/ctrl-p for and would like to add these bindings to navigate the list.

Looking in the source there seems to be some special handling of the navigation keys embedded in the keyevent handling (keyPressEvent in clipboardbrowser.cpp) so I guess not. Any plans to change this/accept a patch? (or maybe it's hackable using the script language?)

**Comment by hluk** [comment]
Can be changed using following commands ([here is how to add it](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)).

```ini
[Commands]
1\Command="
    copyq:
    selectItems( [currentItem() + 1] )"
1\Icon=\xf063
1\InMenu=true
1\Name=Next
1\Shortcut=ctrl+n
2\Command="
    copyq:
    selectItems( [currentItem() - 1] )"
2\Icon=\xf062
2\InMenu=true
2\Name=Previous
2\Shortcut=ctrl+p
size=2
```

**Comment by olejorgenb** [comment]
Thanks!
