### ISSUE TITLE
Only disable selection copy

### ISSUE THREAD

**Issue by amosbird** [hluk/CopyQ#780]
Hi, how can I only disable selection copy while still let clipboard work (`ctrl-c`) ? Currently I use `copyq disable` which disables both.

**Comment by hluk** [comment]
Do you mean you don't want to store the text selected with mouse in CopyQ?

Does disabling option "Store text selected using mouse" work? (It's in the "General" config tab.)

**Comment by amosbird** [comment]
No, i mean to have a command like `copyq disable selection` and `copyq enable selection` :)

**Comment by hluk** [comment]
OK, but if disabling/enabling the option above works, you can actually do:

```bash
# disable
copyq config check_selection false
# enable
copyq config check_selection true
# toggle
copyq 'config("check_selection", config("check_selection") == "false")'
```

**Comment by amosbird** [comment]
thanks!
