### ISSUE TITLE
CopyQ hangs on show main window 

### ISSUE THREAD

**Issue by wizangzing** [hluk/CopyQ#781]
CopyQ v3.0.3 on macOS Sierra 10.12.5

Sometimes when I press the shortcut (shift F8 on my system) for show/hide main window, the window does not appear and I see the spinning beach ball when I hover over the scissors icon in the status menu.  Activity Monitor shows CopyQ as not responding.

I have left this for hours without it recovering, while the system otherwise performed normally.  This is intermittent and not frequent, but I have seen it happen at least 4 times.  I force quit the app from Activity Monitor to recover.  

I don't see anything in the log.

**Comment by wizangzing** [comment]
found the COPYQ_LOG_LEVEL=DEBUG environment variable.  will update with debug log next time the app hangs.

**Comment by hluk** [comment]
Closing. If you still have this issue please reopen and provide details.
