### ISSUE TITLE
Customize default copyq image storage and apply quick pasting

### ISSUE THREAD

**Issue by amosbird** [hluk/CopyQ#782]
Hi, can I specify the default storage path for copyq's images? I would like to paste images into `Org` file with auto generated `[[filename]]`. How would the command look like?

**Comment by hluk** [comment]
Not sure if I understand. Do you want to store any copied image in a directory on a disk?

**Comment by amosbird** [comment]
yeah, and prefixing them with current timestamp. Hmm, how does copyq store them currently?

**Comment by hluk** [comment]
```ini
[Command]
Automatic=true
Command="
    copyq:
    var imagePath = '/home/user/images/'
    var imageFileName = 'copied-' + dateString('yyyy-MM-dd-HH_mm_ss') + '.png'
    
    if (!Dir().mkpath(imagePath)) {
      popup('Failed to create directory for images')
      abort()
    }
    
    var f = new File(imagePath + '/' + imageFileName)
    if (!f.openWriteOnly()) {
      popup('Failed to save image', f.errorString())
      abort()
    }
    
    f.write(input())
    f.close()"
Icon=\xf03e
Input=image/png
Name=Save Copied Images
```

**Comment by amosbird** [comment]
Cool. But how can I paste the file name as `[[/home/user/images/...]]` while selecting the image item in copyq menu.

**Comment by hluk** [comment]
If the app you paste the image in prefers text instead of images, you can set item text to that file path.

```ini
[Command]
Automatic=true
Command="
    copyq:
    var imageDir = Dir().homePath() + '/Pictures/'
    var imageFileName = 'copied-' + dateString('yyyy-MM-dd-HH_mm_ss') + '.png'
    var imagePath = imageDir + '/' + imageFileName
    
    if (!Dir().mkpath(imageDir)) {
      popup('Failed to create directory for images')
      abort()
    }
    
    var f = new File(imagePath)
    if (!f.openWriteOnly()) {
      popup('Failed to save image', f.errorString())
      abort()
    }
    
    f.write(input())
    f.close()
    
    setData(mimeText, '[[' + imagePath + ']]')"
Icon=\xf03e
Input=image/png
Name=Save Copied Images
```

**Comment by amosbird** [comment]
This doesn't work. the Pictures directory doesn't have the copied image and pasting the image into emacs doesn't generate `[[ imagePath ]]`

**Comment by hluk** [comment]
Can you check the image item formats? (Select item and press F4.) There should be `image/png` with image data and `text/plain` with the path.

NOTE: The command above saves images in `~/Pictures`.

**Comment by amosbird** [comment]
yeah, i've checked that. ![](https://la.wentropy.com/kCWl.png)

**Comment by hluk** [comment]
Seems that something failed while saving the image or the text was removed later by a command.

Were there any error notifications?

Do you use some command to move or add the image to a tab?

**Comment by amosbird** [comment]
No, there isn't a notification or a command dealing with images.

**Comment by hluk** [comment]
Hmm, I tried to remove the old command and add the new one, and after copying an image, it is saved as `~/Pictures/copied-...png` and the image item contains the image path.

Perhaps writing the image data failed, which is unchecked in commands above. Here is update which checks whether the write was OK:

```ini
[Command]
Automatic=true
Command="
    copyq:
    var imageDir = Dir().homePath() + '/Pictures/'
    var imageFileName = 'copied-' + dateString('yyyy-MM-dd-HH_mm_ss') + '.png'
    var imagePath = imageDir + '/' + imageFileName
    
    if (!Dir().mkpath(imageDir)) {
      popup('Failed to create directory for images')
      abort()
    }
    
    var f = new File(imagePath)
    if (!f.openWriteOnly() || f.write(input()) == -1) {
      popup('Failed to save image', f.errorString())
      abort()
    }
    
    f.close()
    
    setData(mimeText, '[[' + imagePath + ']]')"
Icon=\xf03e
Input=image/png
Name=Save Copied Images
```

**Comment by amosbird** [comment]
Weird, there isn't any error popping up, and `~/Pictures` still doesn't have the copied image.

**Comment by hluk** [comment]
Can you try adding few `popup()` lines for debugging the command?

E.g.:
```js
var imageDir = Dir().homePath() + '/Pictures/'
var imageFileName = 'copied-' + dateString('yyyy-MM-dd-HH_mm_ss') + '.png'
var imagePath = imageDir + '/' + imageFileName

popup('imageDir', imageDir)
popup('imagePath', imagePath)

if (!Dir().mkpath(imageDir)) {
  popup('Failed to create directory for images')
  abort()
}

popup('Image directory created')

var f = new File(imagePath)
if (!f.openWriteOnly() || f.write(input()) == -1) {
  popup('Failed to save image', f.errorString())
  abort()
}

popup('Image file created')

f.close()

setData(mimeText, '[[' + imagePath + ']]')
```

**Comment by amosbird** [comment]
hmm, the popups still don't show up.

**Comment by hluk** [comment]
Actually, the command is only applied on newly copied images. It won't work on existing ones.

**Comment by amosbird** [comment]
yeah, i'm aware of that :)

**Comment by hluk** [comment]
OK, just making sure. :)

Is the command at top of command list?

Is "Format" field set to "image/png"?

Is "Automatic" checkbox checked?

**Comment by amosbird** [comment]
yeah, i use `paste command` to generate it. ![](https://la.wentropy.com/9nfb.png)

**Comment by hluk** [comment]
Is there a specific image you try to copy from a web? Perhaps I could try this in Firefox or Chromium.

**Comment by amosbird** [comment]
ah.... i see what's going on. I'm using this `copyq write image/png - < "${filename}"; copyq select 0` to do screenshots, and it fails to activate the auto command. But directly copy image from chrome using right click menu works.

**Comment by hluk** [comment]
If you copy stuff with CopyQ (from commands, or copy items from list), it won't activate the auto commands. This is to avoid executing commands in loop.

**Comment by amosbird** [comment]
oh, so in that case, how can I modify this screenshot command to add mimeText `[[...]]`?

**Comment by hluk** [comment]
How about command that maps a system shortcut to take screenshot? (Though I've been fixing the screenshot functionality in CopyQ recently so if you use v3.0.3 you may have some issues on when using multiple monitors or a hidpi screen.)

```ini
[Command]
Command="
    copyq:
    var imageDir = Dir().homePath() + '/Pictures/'
    var imageFileName = 'copied-' + dateString('yyyy-MM-dd-HH_mm_ss') + '.png'
    var imagePath = imageDir + '/' + imageFileName
    
    var imageData = screenshotSelect();
    
    if (!Dir().mkpath(imageDir)) {
      popup('Failed to create directory for images')
      abort()
    }
    
    var f = new File(imagePath)
    if (!f.openWriteOnly() || f.write(input()) == -1) {
      popup('Failed to save image', f.errorString())
      abort()
    }
    
    f.close()
    
    copy('image/png', imageData)
    write(
      'image/png', imageData,
      mimeText, '[[' + imagePath + ']]'
    )"
GlobalShortcut=print
Icon=\xf03e
Name=Screenshot
```

**Comment by amosbird** [comment]
Oh, I didn't know that copyq can do screenshot by itself. But it seems a bit unstable. I got flickering screen when selecting and the hotkey is kinda limited ( I cannot use Meta- for instance). Can I do
```
    write(
      'image/png', imageData,
      mimeText, '[[' + imagePath + ']]'
    )"
```
in command line?

**Comment by hluk** [comment]
```bash
copyq write image/png - text/plain "[[${filename}]]" < "${filename}"; copyq select 0
```

**Comment by amosbird** [comment]
Ah, that works fine. However, the auto command doesn't set the text part of clipboard correctly. I have to select the item in copyq menu and press Enter to paste the `[[....]]` text. Directly using `Ctrl-v` or `Shift-Insert` doesn't work.

**Comment by hluk** [comment]
If you want to copy only the text you can do following instead of `copyq select 0`.

```bash
copyq copy text/plain "[[${filename}]]"
```

**Comment by amosbird** [comment]
Oh, I meant this command,
```
[Command]
Automatic=true
Command="
    copyq:
    var imageDir = Dir().homePath() + '/Pictures/'
    var imageFileName = 'copied-' + dateString('yyyy-MM-dd-HH_mm_ss') + '.png'
    var imagePath = imageDir + '/' + imageFileName
    
    if (!Dir().mkpath(imageDir)) {
      popup('Failed to create directory for images')
      abort()
    }
    
    var f = new File(imagePath)
    if (!f.openWriteOnly()) {
      popup('Failed to save image', f.errorString())
      abort()
    }
    
    f.write(input())
    f.close()
    
    setData(mimeText, '[[' + imagePath + ']]')"
Icon=\xf03e
Input=image/png
Name=Save Copied Images
```
you gave doesn't set the clipboard with the text.

> If the app you paste the image in prefers text instead of images, you can set item text to that file path.

I can paste the text successfully by selecting the item in copyq menu and press `Enter` in emacs. But it doesn't work if I press `Ctrl-v` or `Shift-Insert`.

**Comment by hluk** [comment]
Yes, it only sets the text to the new item.

To override the clipboard content you need to add following to the command.

```js
copy(
  mimeText, '[[' + imagePath + ']]',
  'image/png', input()
)
```

**Comment by amosbird** [comment]
hmm, that generates a duplicated item ![](https://la.wentropy.com/Xd6u.png)

**Comment by hluk** [comment]
I cannot reproduce that; I see only one image after the command is run. As I said before, copying from CopyQ (in this case `copy()` function call) shouldn't run automatic commands again. Also it shouldn't save the newly copied data.

**Comment by amosbird** [comment]
Hmm, here is the command I used,
```
[Command]
Automatic=true
Command="
    copyq:
    var imageDir = Dir().homePath() + '/Pictures/copyq/'
    var imageFileName = 'copied-' + dateString('yyyy-MM-dd-HH_mm_ss') + '.png'
    var imagePath = imageDir + '/' + imageFileName
    
    if (!Dir().mkpath(imageDir)) {
      popup('Failed to create directory for images')
      abort()
    }
    
    var f = new File(imagePath)
    if (!f.openWriteOnly() || f.write(input()) == -1) {
      popup('Failed to save image', f.errorString())
      abort()
    }
    f.close()
    setData(mimeText, '[[' + imagePath + ']]')
    copy(
      mimeText, '[[' + imagePath + ']]',
      'image/png', input()
    )"
Icon=\xf03e
Input=image/png
Name=Save Copied Images
Tab=&clipboard
```
Is that correct?

**Comment by hluk** [comment]
Unset "Copy to tab" field. :)

This is a UI bug; when you use mouse wheel to scroll the command view and suddenly the mouse is over a combo box, it will start changing the combo box value. Unfortunately, fixing it might be difficult.

**Comment by amosbird** [comment]
Thank you very much @hluk !

**Comment by hluk** [comment]
Glad to help. :) And thanks for quickly responding in issues!

**Comment by amosbird** [comment]
Out of curiousity, where and how does copyq store the copied images?

**Comment by hluk** [comment]
It's stored in `~/.config/copyq/copyq_tab_*.dat` files (one file per tab).

**Comment by amosbird** [comment]
Ok, thanks.

**Comment by amosbird** [comment]
Hi @hluk , I just changed the command to
```
[Command]
Automatic=true
Command="
    copyq:
    var imageDir = Dir().homePath() + '/Pictures/copyq/'
    var imageFileName = 'copied-' + dateString('yyyy-MM-dd-HH_mm_ss') + '.png'
    var imagePath = imageDir + '/' + imageFileName
    
    if (!Dir().mkpath(imageDir)) {
      popup('Failed to create directory for images')
      abort()
    }
    
    var f = new File(imagePath)
    if (!f.openWriteOnly() || f.write(input()) == -1) {
      popup('Failed to save image', f.errorString())
      abort()
    }
    f.close()
    setData(mimeText, '[[file:' + imagePath + ']]')
    copy(
      mimeText, '[[file:' + imagePath + ']]',
      'image/png', input()
    )"
Icon=\xf03e
Input=image/png
Name=Save Copied Images
```

so that it should generates `[[file:/foo/bar.png]]` links. But it doesn't work. Newly created images are still have `[[/foo/bar.png]]` text. I even tried rebooting. So what might be the problem?

**Comment by hluk** [comment]
Is there perhaps duplicate command for setting the text? Try searching for `[[` in the command dialog.

**Comment by amosbird** [comment]
no, there isn't

**Comment by amosbird** [comment]
@hluk Hi, this `mimeText` thing doesn't work when pasting into virtualbox. It always ends up pasting text.

**Comment by hluk** [comment]
I think most apps prefer text and will ignore other formats if text is available. Seems like in this case Qt (framework used by CopyQ) doesn't provide additional images when text is copied.

So perhaps it would be better to store the text separately or in a note or a tag.

**Comment by amosbird** [comment]
Um, what do you mean `Qt (framework used by CopyQ) doesn't provide additional images when text is copied.` ? I can paste the image into another application inside virtualbox, so I guess the image is correctly copied...

> I think most apps prefer text and will ignore other formats if text is available. 

Is there a way to change that behavior?

**Comment by hluk** [comment]
> I can paste the image into another application inside virtualbox, so I guess the image is correctly copied...

Then it looks like it's ignored by the plugin for virtualbox.

Perhaps it can be solved in #793 (which I think is currently bit difficult to handle using CopyQ).

> Is there a way to change that behavior?

Perhaps change `mimeText` in the command to `mimeItemNotes` but you would need to copy the text by selecting the text in the notes or with another command.

**Comment by amosbird** [comment]
Hi @hluk , after half year of using this method, I feel that `So perhaps it would be better to store the text separately or in a note or a tag.` is the right way to do it.

So how can I modify the command to achieve that? i.e. a command to paste the attached text note in selected image.  :)

**Comment by hluk** [comment]
Here are two commands; one for pasting the notes and image when the item is activated (with Enter key or double-click), the second one for storing the image with notes.

```ini
[Commands]
1\Command="
    copyq:
    copy(mimeText, data(mimeItemNotes))
    paste()
    
    copy('image/png', input())
    paste()"
1\HideWindow=true
1\Icon=\xf15c
1\InMenu=true
1\Input=image/png
1\Name=Paste Image with Tag
1\Shortcut=enter
2\Automatic=true
2\Command="
    copyq:
    var imageDir = Dir().homePath() + '/Pictures/copyq/'
    var imageFileName = 'copied-' + dateString('yyyy-MM-dd-HH_mm_ss') + '.png'
    var imagePath = imageDir + '/' + imageFileName
    
    
    if (!Dir().mkpath(imageDir)) {
      popup('Failed to create directory for images')
      abort()
    }
    
    var f = new File(imagePath)
    if (!f.openWriteOnly() || f.write(input()) == -1) {
      popup('Failed to save image', f.errorString())
      abort()
    }
    f.close()
    
    setData(mimeItemNotes, '[[file:' + imagePath + ']]')"
2\Icon=\xf03e
2\Input=image/png
2\Name=Save Copied Images
size=2
```

**Comment by hluk** [comment]
Sure, if for example you have each note on one line.

```ini
[Commands]
1\Command="
    copyq:
    shortcut = str(data(mimeShortcut))
    
    notes = str(data(mimeItemNotes)).split('\\n')
    noteIndex = shortcut.indexOf('shift') == 0 ? 0 : 1
    
    copy(mimeText, notes[noteIndex])
    paste()
    
    copy('image/png', input())
    paste()"
1\HideWindow=true
1\Icon=\xf15c
1\InMenu=true
1\Input=image/png
1\Name=Paste Image with Tag
1\Shortcut=shift+return, ctrl+return
2\Automatic=true
2\Command="
    copyq:
    var imageDir = Dir().homePath() + '/Pictures/copyq/'
    var imageFileName = 'copied-' + dateString('yyyy-MM-dd-HH_mm_ss') + '.png'
    var imagePath = imageDir + '/' + imageFileName
    
    
    if (!Dir().mkpath(imageDir)) {
      popup('Failed to create directory for images')
      abort()
    }
    
    var f = new File(imagePath)
    if (!f.openWriteOnly() || f.write(input()) == -1) {
      popup('Failed to save image', f.errorString())
      abort()
    }
    f.close()
    
    notes = [
      '[[file:' + imagePath + ']]',
      imagePath
    ]
    setData(mimeItemNotes, notes.join('\\n'))"
2\Icon=\xf03e
2\Input=image/png
2\Name=Save Copied Images
size=2
```

**Comment by amosbird** [comment]
Ah, that's hacky but I like it :) . Oh, I missed one thing. How can I write the mimeItemNotes on command line. The old command I used is `copyq write image/png - text/plain text/plain [[file:${img_path}/${filename}]]" < $picture`

**Comment by hluk** [comment]
```bash
copyq write image/png - application/x-copyq-item-notes "[[file:${img_path}/${filename}]]" < "$picture"
```

**Comment by amosbird** [comment]
Hmm, I just played it around for a while. This doesn't work well. If I open copyq menu and directly paste the note (suppose the cursor is on a image), it works. However, if I navigate around to find a image, the note pasting stops working.

**Comment by amosbird** [comment]
And pasting to terminal shell always ends up with `[2;6~`

**Comment by hluk** [comment]
> If I open copyq menu and directly paste the note

Sorry, but shortcuts cannot be overridden in tray menu. You have to open the main window.

> And pasting to terminal shell always ends up with `[2;6~`

It's possible that the terminal accepts different shortcut for pasting than <kbd>Shift</kbd>+<kbd>Insert</kbd> (you can try [this workaround](https://github.com/hluk/CopyQ/issues/633#issuecomment-278326916)).

**Comment by amosbird** [comment]
> Sorry, but shortcuts cannot be overridden in tray menu. You have to open the main window.

Oops, I meant the main window... I haven't used the tray menu for quite a long time.

> It's possible that the terminal accepts different shortcut for pasting than Shift+Insert (you can try this workaround).

Hmm, `Shift` + `Insert` works just fine. In fact, normal text pasting from the main window using `Enter` works fine too in terminal.

**Comment by hluk** [comment]
What the terminal emulator app do you use?

**Comment by hluk** [comment]
Oh, the command is missing an `copySelection()` call. Here are both commands again (just for completeness).

```ini
[Commands]
1\Command="
    copyq:
    shortcut = str(data(mimeShortcut))
    
    notes = str(data(mimeItemNotes)).split('\\n')
    noteIndex = shortcut.indexOf('shift') == 0 ? 0 : 1
    
    copy(mimeText, notes[noteIndex])
    copySelection(mimeText, notes[noteIndex])
    paste()
    
    copy('image/png', input())
    // Clear selection so it's not pasted again in terminal.
    copySelection(mimeText, '\\0')
    paste()"
1\HideWindow=true
1\Icon=\xf15c
1\InMenu=true
1\Input=image/png
1\Name=Paste Image with Tag
1\Shortcut=shift+return, ctrl+return
2\Automatic=true
2\Command="
    copyq:
    var imageDir = Dir().homePath() + '/Pictures/copyq/'
    var imageFileName = 'copied-' + dateString('yyyy-MM-dd-HH_mm_ss') + '.png'
    var imagePath = imageDir + '/' + imageFileName
    
    
    if (!Dir().mkpath(imageDir)) {
      popup('Failed to create directory for images')
      abort()
    }
    
    var f = new File(imagePath)
    if (!f.openWriteOnly() || f.write(input()) == -1) {
      popup('Failed to save image', f.errorString())
      abort()
    }
    f.close()
    
    notes = [
      '[[file:' + imagePath + ']]',
      imagePath
    ]
    setData(mimeItemNotes, notes.join('\\n'))"
2\Icon=\xf03e
2\Input=image/png
2\Name=Save Copied Images
size=2
```

**Comment by amosbird** [comment]
Hmm, it still doesn't work. The same problem.

**Comment by hluk** [comment]
Works nicely for me in `urxvt` with <kbd>Ctrl</kbd>/<kbd>Shift</kbd>+<kbd>Enter</kbd>. No idea what can be the problem.

Make sure you remove the old commands.

**Comment by amosbird** [comment]
@hluk Hello! When having mime picture item in clipboard, gui emacs cannot copy any new text. It yields `Selection owner couldn't convert: STRING` .  This issue seems to be related https://github.com/pvanek/qlipper/issues/35 . Why is there an owner for that mime item?

The related emacs code is `bool there_is_a_selection_owner = XGetSelectionOwner (display, selection_atom) != 0;`
