### ISSUE TITLE
Append to file issues

### ISSUE THREAD

**Issue by endobur** [hluk/CopyQ#784]
I am new to CopyQ, but I am trying to make an action that add a url to a file when it is copied.
(Using copyq 3.0.3 debian 9.0 amd64)

The problem is if I test with writing this line to file:
1234567890
Then I test again with writing this to the file:
abcd
The file will when opened look like this:
abcd567890

---
Action: Automatic
Content: ^https//www.youtube.com/watch.*
copyq:
var format = 'text/plain'
currentpath(Dir().homePath())
var fileName = 'ytFile'
var f = File(fileName)
if (!f.open()){
  popup('Failed to open\"' + f.fileName() + '\"', f.errorString(), 10000)
  abort()
}
f.write(read(format,0))
//f.write(clipboard())
//f.write(selectedtab() ? getitem(currentitem())[format] : clipboard(format))
//f.write(getitem(0)[format])

---
Issue 1: it overwrites the file, doesn't append to it
Issue 2: it triggers on selection, and not only just after I copy
Issue 3: it doesn't write the just copied item, it writes the last copied item prior to it, an item that might not forfil the regex
---

What I look for to be able to copy links, here from youtube, and add them to a textfile for later process.
Before CopyQ I have  had to copy link, alt-tab to text editor, paste link, back to browser, and when it is talk about many many links, it gets slow.
Alternatively I have had to pull all content from ClipIt to a text file using python, and then go and clean the file up afterwards.

**Comment by hluk** [comment]
Use `f.openWriteOnly()` instead of `f.open()` (which opens file in "read/write" mode).

API documentation for `File` seems to be missing this info -- I'll update it.

**Comment by hluk** [comment]
ad Issue 2. To run the command only when clipboard changes (not selection), use:

```js
if (dataFormats().indexOf(mimeClipboardMode) != -1)
  abort()
```

ad Issue 3. Set "Format" field of the command to "text/plain" and then you can access the clipboard text using `input()`.

```js
f.write(input())
```

**Comment by endobur** [comment]
Many thanks for the help, it now seem to be working.
```
[Command]
Automatic=true
Command="
    copyq:
    if (dataFormats().indexOf(mimeClipboardMode) != -1)
      abort()
    currentpath(Dir().homePath())
    var f = new File('ytFile')
    if (!f.openAppend()){
      popup('Failed to open\\\"' + f.fileName() + '\\\"', f.errorString(), 10000)
      abort()
    }
    f.write(input())
    f.write('\\n')
    popup('', input(), 1500)"
Icon=\xf016
Input=text/plain
Match=^https//www.youtube.com/watch.*
Name=TestLinkSave
```
Newline could probably be handled better.
