### ISSUE TITLE
Add to Debian main repository

### ISSUE THREAD

**Issue by yangfl** [hluk/CopyQ#786]
I'd like to suggest to add this package on Debian -- since you're already generating deb packages on PPA, I think it won't be that hard. I can help to pack it properly to meet Debian's criteria.

What's your opinion? :)

**Comment by hluk** [comment]
That definitely would be great. Though I'm not sure what must be done for the package to get into official repos.

BTW, Debian packages are current built on [OBS](https://build.opensuse.org/package/show/home:lukho:copyq/CopyQ-Qt5).

**Comment by Z-Y00** [comment]
qwq, the about page showed there are a lot of co-authors , do we have to write them all into the man page or so? @yangfl

**Comment by yangfl** [comment]
We are now in the main repository https://packages.debian.org/source/sid/copyq . Thank you!

**Comment by hluk** [comment]
Awesome! Thanks!
