### ISSUE TITLE
Searching for pictures via MIME text.

### ISSUE THREAD

**Issue by amosbird** [hluk/CopyQ#789]
This would be a great feature :-)

**Comment by hluk** [comment]
This should by currently possible, just type `image/png` or `^image/.*` (if you use regular expressions).

See also #345.

**Comment by amosbird** [comment]
oh, can I have a key binding for that?

**Comment by hluk** [comment]
> oh, can I have a key binding for that?

Her you go:

```ini
[Command]
Command="
    copyq:
    filter('^image/.*')"
Icon=\xf1c5
InMenu=true
Name=Filter Images
Shortcut=ctrl+i
```
> And the regex searching `^image/.*` doesn't match any images.

Make sure to enable "Regular Expression" when searching.

![image](https://user-images.githubusercontent.com/38054/30284894-9d0cdec6-971c-11e7-91d8-781e90cfce3f.png)

Also sometimes the item with an image doesn't contain image but only `text/html` instead.

**Comment by amosbird** [comment]
Thanks!
