### ISSUE TITLE
Clipboard sharing

### ISSUE THREAD

**Issue by amosbird** [hluk/CopyQ#793]
I'm very frustrated with the virtualbox's clipboard sharing. I tried https://github.com/symless/synergy for a while but it doesn't work well either. I wonder if this feature can be implemented in copyq since it's already cross platform.

**Comment by hluk** [comment]
If you run CopyQ on host and guest machines, maybe you could have an automatic command which synchronizes clipboard on both sides (e.g. over ssh).
