### ISSUE TITLE
Can't find variable session

### ISSUE THREAD

**Issue by orschiro** [hluk/CopyQ#796]
I am getting the following warning on startup of my Ubuntu MATE 17.10 session. 

Does anyone know what that means and how I can resolve it?

![image](https://user-images.githubusercontent.com/170947/30510138-c5b4cb9a-9abe-11e7-910a-f3812f1bfea1.png)

**Comment by hluk** [comment]
Seems like some incorrect command is executed at startup.

You can check log for more info -- search for "ScriptError" and there should be a trace of the command.

**Comment by orschiro** [comment]
Sorry for asking but where can I find the log file?

![image](https://user-images.githubusercontent.com/170947/30518899-513dae18-9b8a-11e7-8d43-67bfc03878e0.png)

**Comment by hluk** [comment]
F12 shortcut or usually `~/.local/share/copyq/copyq/copyq.log`.

**Comment by orschiro** [comment]
Thanks! This is what I got:

```
plugins/libitemdata.so
CopyQ Note [2017-09-16 09:08:03.387] Server-1435: Loading plugin: /usr/lib/copyq/plugins/libitemencrypted.so
CopyQ Note [2017-09-16 09:08:03.413] Server-1435: Loading plugin: /usr/lib/copyq/plugins/libitemfakevim.so
CopyQ Note [2017-09-16 09:08:03.462] Server-1435: Loading plugin: /usr/lib/copyq/plugins/libitemimage.so
CopyQ Note [2017-09-16 09:08:03.471] Server-1435: Loading plugin: /usr/lib/copyq/plugins/libitemnotes.so
CopyQ Note [2017-09-16 09:08:03.483] Server-1435: Loading plugin: /usr/lib/copyq/plugins/libitempinned.so
CopyQ Note [2017-09-16 09:08:03.490] Server-1435: Loading plugin: /usr/lib/copyq/plugins/libitemsync.so
CopyQ Note [2017-09-16 09:08:03.506] Server-1435: Loading plugin: /usr/lib/copyq/plugins/libitemtags.so
CopyQ Note [2017-09-16 09:08:03.513] Server-1435: Loading plugin: /usr/lib/copyq/plugins/libitemtext.so
CopyQ Note [2017-09-16 09:08:04.690] Script-2-1435: ScriptError: Exception in command "-session": ReferenceError: Can't find variable: session
CopyQ Note [2017-09-16 09:08:04.690] Script-2-1435:    
CopyQ Note [2017-09-16 09:08:04.690] Script-2-1435:    --- backtrace ---
CopyQ Note [2017-09-16 09:08:04.690] Script-2-1435:    <global>() at “-session”:1
CopyQ Note [2017-09-16 09:08:04.690] Script-2-1435:    --- end backtrace ---
CopyQ Note [2017-09-16 09:08:04.690] Script-1-1435: ScriptError: Exception in command "-session": ReferenceError: Can't find variable: session
CopyQ Note [2017-09-16 09:08:04.690] Script-1-1435:    
CopyQ Note [2017-09-16 09:08:04.690] Script-1-1435:    --- backtrace ---
CopyQ Note [2017-09-16 09:08:04.690] Script-1-1435:    <global>() at “-session”:1
CopyQ Note [2017-09-16 09:08:04.690] Script-1-1435:    --- end backtrace ---
```

**Comment by hluk** [comment]
Argument `-session` should be either `-s` or `--session`. Perhaps launched from some autostart settings? Check:

```bash
grep -r -- -session ~/.config/autostart
```

**Comment by orschiro** [comment]
Let me check....

```
orschiro@x230:~$ grep -r -- -session ~/.config/autostart
/home/orschiro/.config/autostart/indicator-session.desktop:Exec=/usr/lib/x86_64-linux-gnu/indicator-session/indicator-session-service
```

**Comment by orschiro** [comment]
![image](https://user-images.githubusercontent.com/170947/30518965-bde917fe-9b8b-11e7-8352-0a26e28eb1b9.png)

**Comment by orschiro** [comment]
![image](https://user-images.githubusercontent.com/170947/30518971-ceadb3b0-9b8b-11e7-9ae5-95f9d138741d.png)

**Comment by hluk** [comment]
Is there second entry in autostart configuration for CopyQ? What does following command print?

```bash
grep -r copyq /usr/share/applications/
```

**Comment by orschiro** [comment]
I cannot see a second entry in the startup settings.

```
orschiro@x230:~$ grep -r copyq /usr/share/applications/
/usr/share/applications/bamf-2.index:copyq.desktop	copyq			false
/usr/share/applications/copyq.desktop:Exec=copyq
/usr/share/applications/copyq.desktop:Icon=copyq
```

**Comment by hluk** [comment]
Perhaps the "Automatically remember running application when logging out" option requires apps to handle `-session` argument. I'll try to google that out.

**Comment by orschiro** [comment]
Thanks for your efforts! This feature is actually very handy and I wouldn't want to switch it off.

**Comment by hluk** [comment]
@orschiro I noticed you edited FAQ. I'm trying to move the documentation to separate [web page](http://copyq.readthedocs.io) (Sphinx generated). You should still be able to edit the pages on github, the source code is in [docs directory](https://github.com/hluk/CopyQ/tree/master/docs).

See: [How to enable logging](http://copyq.readthedocs.io/en/latest/faq.html#how-to-enable-logging)

**Comment by orschiro** [comment]
OK. :-)

See this: https://github.com/hluk/CopyQ/pull/797

**Comment by hluk** [comment]
Can you run following?

```bash
grep -ri copyq ~/.config/mate-session/saved-session
```

**Comment by hluk** [comment]
Hmm, I just tested it and it seems Mate's session manager makes an assumption that CopyQ knows `-session` argument. I'll try fix it and to handle the argument.

**Comment by orschiro** [comment]
Still helps?

```
orschiro@x230:~$ grep -r copyq /usr/share/applications/
/usr/share/applications/bamf-2.index:copyq.desktop	copyq			false
/usr/share/applications/copyq.desktop:Exec=copyq
/usr/share/applications/copyq.desktop:Icon=copyq
orschiro@x230:~$ grep -ri copyq ~/.config/mate-session/saved-session
/home/orschiro/.config/mate-session/saved-session/108b8cdb5823e853ae150551203175574300000011610047.desktop:Name=/usr/bin/copyq
/home/orschiro/.config/mate-session/saved-session/108b8cdb5823e853ae150551203175574300000011610047.desktop:Exec=/usr/bin/copyq -session 108b8cdb5823e853ae150551203175574300000011610047_1505514638_87164
/home/orschiro/.config/mate-session/saved-session/108b8cdb5823e853ae150551203288625600000011610048.desktop:Name=/usr/bin/copyq
/home/orschiro/.config/mate-session/saved-session/108b8cdb5823e853ae150551203288625600000011610048.desktop:Exec=/usr/bin/copyq -session 108b8cdb5823e853ae150551203288625600000011610048_1505514638_95792
orschiro@x230:~$ 
```

**Comment by hluk** [comment]
OK, should be fixed now (for next version).

**Comment by orschiro** [comment]
Amazing, thanks! 

El 17 de septiembre de 2017 13:54:15 CEST, Lukas Holecek <notifications@github.com> escribió:
>OK, should be fixed now (for next version).
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/hluk/CopyQ/issues/796#issuecomment-330038649

-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.
