### ISSUE TITLE
image edit command doesn't work

### ISSUE THREAD

**Issue by amosbird** [hluk/CopyQ#798]
Recently update breaks `ctrl-e` for image editing. Copyq doesn't do anything (no log either) after pressing `ctrl-e` on an image.

**Comment by hluk** [comment]
What do you have set as image editors? (In preferences, "Items" tab, under "Images", "command" line edits.)

Or do you override the Ctrl+E shortcut?

**Comment by amosbird** [comment]
Ah, i see. So I should use `edit with editor` command for image editing. I've bound `ctrl-e` to `edit` in order to use fakevim for text. How can I use that binding for image too?

**Comment by hluk** [comment]
OK, I just changed the behavior so that "Edit" action tries to opens image editor if internal text editor cannot be open for the selected item.

**Comment by amosbird** [comment]
great! thank you @hluk
