### ISSUE TITLE
Clipboard filled with single characters ?

### ISSUE THREAD

**Issue by repsorp** [hluk/CopyQ#799]
While typing a message in [Rambox WhatsApp Service](https://github.com/saenzramiro/rambox), CopyQ clipboard is filled with single or double characters of the message i'm currently typing
Don't know if  it's a CopyQ or Rambox issue...

Ubuntu 16.04
CopyQ Clipboard Manager v3.0.3
Rambox 0.5.12

![capture du 2017-09-19 14-28-05](https://user-images.githubusercontent.com/6297032/30596029-40039d5e-9d53-11e7-8ddf-f1bc594edc11.png)

**Comment by hluk** [comment]
Yeah, I noticed that too on WhatsApp. Looks like the bug elsewhere.

To fix WhatsApp (in Firefox) I have to use following automatic command to ignore randomly copied pairs of characters ([here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)).

```ini
[Command]
Automatic=true
Icon=\xf232
Input=text/plain
Match=^..$
Name=Ignore WhatsApp autocopy bug
Remove=true
Window="^WhatsApp - "
```

**Comment by repsorp** [comment]
Perfect !

Just had to replace WhatsApp with Rambox in  Window="^WhatsApp - "

Big thanks

**Comment by DavidParkin** [comment]
I have been getting '[' pasted quite regularly. It seems now to be part of my terminal prompt, [_name@machine_] etc. I have recently changed my prompt. The scenario seems to be copy -> change tab -> paste '[' with the real copied item being second in the list. Hope this helps, I'm not expecting a response.
