### ISSUE TITLE
X11: Reset clipboard if empty

### ISSUE THREAD

**Issue by hluk** [hluk/CopyQ#80]
Reset empty clipboard to last observed content (not all MIME data!) under Linux/X11.

**Comment by dufferzafar** [comment]
@hluk I'm facing this same issue. 

You said: 
> Basic test case is: open a app copy something, close it -- the content should be still available to paste.

This simple case fails on KDE Plasma with all applications!

**Comment by dufferzafar** [comment]
Is it because of this? https://github.com/hluk/CopyQ/commit/5e1a8c930824740628eabfc95a5af161bbce0381 

Can you please make this configurable? I don't use a password manager, but this resetting of clipboard bugs me to no end.

**Comment by hluk** [comment]
@dufferzafar Yes, resetting clipboard/selection was removed because it had some adverse effects.

You can use [Reset Empty Clipboard/Selection command](https://github.com/hluk/copyq-commands/tree/master/Scripts#reset-empty-clipboardselection) (I use this command and it works pretty well). See also #925.
