### ISSUE TITLE
Version 3.1.0~zesty with broken tray icon

### ISSUE THREAD

**Issue by orschiro** [hluk/CopyQ#803]
Just did the update and now got this:

![image](https://user-images.githubusercontent.com/170947/30958878-c0ec554a-a43e-11e7-938e-6ddaf53523b5.png)

**Comment by hluk** [comment]
Damn, that sucks, issues with notification area again.

Just fixed that but I'm not sure how should I fix the just-released packages yet.

Thanks for quick report.

**Comment by orschiro** [comment]
Can you provide a new release under the release tab here on Github that people can manually download?

Thanks for the quick fix!

**Comment by hluk** [comment]
Version 3.1.1 is available in PPA. 😉

**Comment by orschiro** [comment]
Yup, that worked. Thanks! :-)
