### ISSUE TITLE
Performance with large single-lined items

### ISSUE THREAD

**Issue by m4r71n** [hluk/CopyQ#804]
Hi @hluk,
once again thank you very much for your awesome CopyQ. It is such a productivity booster and I cannot live without CopyQ anymore!
But I think there is a performance issue with large single-lined items. To reproduce, copy a big image encoded as DataURI (like [this](https://gist.githubusercontent.com/m4r71n/9e651c2c1c6abc55efba3dfc820ce14c/raw/cf727313b0d71a2de6f3d3cd290a2b544ec28550/datauri) one) into the clipboard and paste the item a few times within CopyQ. Each paste will take about a second and you will immediately notice that the selection of the items via keyboard will slow down and also searching and clearing the search feels unresponsive.

CopyQ 3.1.0 (copyq-v3.1.0.zip) on Windows 10 Pro x64

**Comment by hluk** [comment]
Fixed by cropping long lines.

I'll probably release new version very soon.

**Comment by m4r71n** [comment]
With the latest [build](https://ci.appveyor.com/project/hluk/copyq/build/1.2.1214) CopyQ is much faster. Thank you very much!

**Comment by hluk** [comment]
I added few other fixes to improve performance (e53a8d9d5dec3989ce0d289c79d576af2e814b8e, 03e1954e256b439e9f4179db56a2e97b8abc4524).

Qt classes QTextDocument and QTextEdit can be quite slow when it comes to displaying and editing large amount of text, large lines or lots of nested HTML tags.
