### ISSUE TITLE
Issues with version 3.1

### ISSUE THREAD

**Issue by richlux** [hluk/CopyQ#805]
I just installed version 3.1 on Windows 7 64bit and encountered the following:

1) After double-clicking a a few items in the clipboard list to past and close, the right-mouse context menu appears to stop working, but it actually is popping up hidden or behind the clipboard list.
2) Selecting the ellipses (...) doesn't appear to do anything.  What is supposed to happen?

Thanks,
Rich

**Comment by hluk** [comment]
ad 1. Looks like issue in new Qt. You can get the app with older Qt [here](https://ci.appveyor.com/project/hluk/copyq/build/1.2.1195/job/7j1pqvnr2lh7w8mg/artifacts).

ad 2. You need to hold Shift key to be able to select text and links in the item.

**Comment by hluk** [comment]
I just replaced the Qt versions in https://github.com/hluk/CopyQ/releases/tag/v3.1.0 .

**Comment by richlux** [comment]
Much better.  Thanks!  (FYI, to others who have this issue, I had to completely uninstall the old version of CopyQ for the new version to install the older Qt).  I have two additional questions with regards to #2, 

First, is there a way to collapse the text after I click on the ellipses to expand it?

Second, after I expand the text, I can't click and drag the scrollbar to move up and down in the text because it thinks I want to drag the entire clipboard item to move or paste it.  Similarly, clicking too fast in the scroll bar will cause the double-click action to occur (in my case it's paste and close).  Is there a way to change these behaviors?

Rich

**Comment by hluk** [comment]
> First, is there a way to collapse the text after I click on the ellipses to expand it?

Not possible.

> Second, after I expand the text, I can't click and drag the scrollbar...

I know about this issue. Didn't have time to solve it yet.

I'm closing this one. If you can, please create new issues (one bug or feature request per github issue), it's lot easier to keep track and discuss it that way. Thanks.
