### ISSUE TITLE
Clip Preview not reseting

### ISSUE THREAD

**Issue by SmileyStiles** [hluk/CopyQ#808]
The Clip Preview is not deleting the previous view.  When you select a clip, it adds that to the preview but leaving the old content still in the preview.   I'm using this on Windows 7 PC and CopyQ 3.1.0
![copyq preview](https://user-images.githubusercontent.com/31048485/30996784-37cf62fe-a478-11e7-8a7c-b9116e728d9c.jpg)

**Comment by richtrefz** [comment]
Seeing same problem with CopyQ v3.1.1 on LinuxMint, built from source

**Comment by richtrefz** [comment]
fix works great - thank you

**Comment by hluk** [comment]
Version with the fix for Windows is [here](https://ci.appveyor.com/project/hluk/copyq/build/1.2.1204/job/dckft7pwye4yhx7g/artifacts).

**Comment by SmileyStiles** [comment]
Thank you
