### ISSUE TITLE
bug: for almost every entry in "clipboard" i get a "true" string added. 

### ISSUE THREAD

**Issue by royharoush** [hluk/CopyQ#810]
hi, 

![image](https://user-images.githubusercontent.com/8113056/31127643-3c92033a-a858-11e7-8b4c-b25ca371d204.png)

my version: 
![image](https://user-images.githubusercontent.com/8113056/31127624-2d937706-a858-11e7-9da4-411e799a5a07.png)

my commands(most are generic, some are custom): 

![image](https://user-images.githubusercontent.com/8113056/31127768-7789d26a-a858-11e7-9137-7c6b7cc9dacc.png)

thanks,
roy

**Comment by hluk** [comment]
Can you check if any of your automatic commands (bold in the list) have "Transform" checkbox checked?

**Comment by royharoush** [comment]
None of them has transform checked.

**Comment by hluk** [comment]
Looks like issue in one of the automatic commnads. You can try deactivating bunch of them and see if it fixes the issue.

**Comment by royharoush** [comment]
it was the "store time" command. not sure why, i removed it and pasted it back from the wiki. seems to be the same command.. 
closed.  thanks :)
