### ISSUE TITLE
CopyQ - new Version with Undo deleting?

### ISSUE THREAD

**Issue by Clemens-Ratte-Polle** [hluk/CopyQ#812]
hi
I got version CopyQ 2.4.9 and i am angry about the missing function of undeleting deleted text :(
Does Version 3.1.1 offer the option of undelete, undo?
https://github.com/hluk/CopyQ/releases

thx

**Comment by hluk** [comment]
There are [commands](https://github.com/hluk/copyq-commands/blob/master/Application/undoable-move-to-trash.ini) to move deleted items to trash and back ([here is how to add the commands to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)).

**Comment by Clemens-Ratte-Polle** [comment]
ERROR o_O
"invalid number of arguments"?
-------------------------


Befehl „copyq: trash_tab = "(trash)…e.apply(this, remove_items)“
Exitcode: 1
CopyQ client FEHLER: Error: Ungültige Anzahl an Argumenten! 

--- backtrace --- 
<anonymous>()@:18 
--- end backtrace --- 

---
copyq: 
trash_tab = "(trash)"
tab_mime = "application/x-copyq-user-tab"
index_mime = "application/x-copyq-user-index"
time_mime = "application/x-copyq-user-time"
remove_mime = [tab_mime, index_mime, time_mime]
tab(trash_tab)
item = getitem(0)
time = str(item[time_mime])
select_items = []
remove_items = []
target_tab = str(item[tab_mime])
while (true) {
index = item[index_mime]
for (i in remove_mime)
delete item[remove_mime[i]]
tab(target_tab ? target_tab : selectedtab())
setitem(index, item)
select_items.push(index)
var i = remove_items.length
remove_items.push(i)
tab(trash_tab)
item = getitem(i + 1)
if ( !time || time !== str(item[time_mime]) )
break;
}
if (target_tab)
show(target_tab)
tab(selectedtab())
selectitems.apply(this, select_items)
tab(trash_tab)
remove.apply(this, remove_items)
---

**Comment by hluk** [comment]
Do you use latest CopyQ version?

**Comment by Clemens-Ratte-Polle** [comment]
neo, 2.4.9.
Will i loose my clipboard data when updating?

**Comment by hluk** [comment]
> Will i loose my clipboard data when updating?

If you are concerned about that, [make a backup](http://copyq.readthedocs.io/en/latest/backup.html) before updating.

**Comment by Clemens-Ratte-Polle** [comment]
OK! :)
Everything "funzt" :)
The order of the tabs was confused, but now all in row :)
Undelete works!
THANKS!

**Comment by Clemens-Ratte-Polle** [comment]
ok, not everything went fine :(
The history is cut down after update :(
Better CopyQ would import settings automatically at update by itself...

This fault you notice too late :(

**Comment by Clemens-Ratte-Polle** [comment]
and another error in CopyQ:
When i got the import dialogue window open and then do a text copy, this is not recognized by CopyQ.

**Comment by bshapton** [comment]
I have a problem! I seem to have accidentally deleted everything that was on my clipboard. Is there anything I can do to recover all those clips? I don't know how it happened -  I was just trying to delete one item and everything disappeared. Yikes!

**Comment by Korb** [comment]
> CopyQ - new Version with Undo deleting?

/dup #187?
