### ISSUE TITLE
Append to clipboard?

### ISSUE THREAD

**Issue by SamuelMiller** [hluk/CopyQ#813]
Does Copyq have a simple way to append the current selection to the previous copied item in the clipboard so that when pasted they are concatenated as one item?

**Comment by hluk** [comment]
If you select multiple text items, all the text is concatenated and copied to clipboard (and pasted if it's enabled in configuration). Not sure if that's what you meant.

**Comment by SamuelMiller** [comment]
Can you add to the clipboard sequentially--for example, copy one item, then another, then another and then paste them concatenated?  If so, how do I do that? Thanks, Sam

**Comment by hluk** [comment]
If you copy from item list in the app, you can select more items with Shift or Ctrl and copy more items again.

If you copy stuff outside CopyQ, a custom command could append text to clipboard on a global shortcut. E.g.

```ini
[Command]
Command="
    copyq:
    var text1 = str(clipboard())
    copy()
    var text2 = str(clipboard())
    copy(text1 + '\\n' + text2)"
GlobalShortcut=ctrl+shift+c
Icon=\xf0ea
Name=Copy - Append
```

**Comment by maurelian** [comment]
I cannot get this working for me. 

I'm using this script in the Custom Commands dialogue:

```javascript
copyq:
    var text1 = str(clipboard())
    popup("text1: ", text1, -1) // shows the current clipboard contents
    copy() // updates the current clipboard contents to what I have selected
    var text2 = str(clipboard()) 
    popup("text2: ", text2, -1) // shows the text I have selected
    var finaltext = text1 + '\\n' + text2
    popup("finaltext", finaltext, -1) // shows a string that keeps growing continuously between runs
    copy(finaltext) // doesn't seem to do anything
```

This is on Ubuntu 18.04, with CopyQ v3.2.0.

**Comment by maurelian** [comment]
^ Actually disregard. It does work, ie. when I paste the expected 'finaltext' appears. For whatever reason the CopyQ clipboard tab is updated, but that's fine with me.

**Comment by ijoseph** [comment]
[This](https://github.com/hluk/CopyQ/issues/813#issuecomment-477770824) is nice. A related, debatably within-scope request is to append to a non-text item (and an extension: appending _with_ non-text items).
