### ISSUE TITLE
ui font size; colors

### ISSUE THREAD

**Issue by Lew-Rockwell-Fan** [hluk/CopyQ#814]
I can't adjust the font size of the ui. I pretty much have to lay my eyeballs on the monitor to make them out, so not being able to adjust them makes this a lot harder to figure out and use. I don't mean the font in which the clips are shown - that works - but the font of things like the menu bar menu titles (File, Edit, Items, Tabs, & Help) and items in the menus, etc.

File, Prefs, Appearance-tab settings only affect the pane in which the clips are shown. Nothing I do in Qt Configuration 4.8.7 seems to have any effect.

Copyq was installed with copyq_3.1.1_Ubuntu_16.04-1_amd64.deb using gdebi. This is under plain Openbox (no DE per se) in X in in a  minimalist Ubuntu 16.04 installed from the mini.iso. Maybe I need some qt components that aren't listed as dependencies? It would be nice to adjust the ui colors as well, but font size is crucial. Almost impossible to use otherwise.

Thanks for reading.

**Comment by hluk** [comment]
You can try settings environment variable `QT_DEVICE_PIXEL_RATIO` before launching CopyQ. E.g.

```
QT_DEVICE_PIXEL_RATIO=2 copyq
```

Alternatively, you can override font size for CopyQ:
1. close the app first,
2. edit file `~/.config/copyq/copyq.conf`,
3. under `[Theme]` section there should be `css` and `style_main_window` options, change them to following (use different font size if needed),
```
[Theme]
css="*{font-size: 12pt}"
style_main_window=true
```
4. save the file and start the app.

**Comment by Lew-Rockwell-Fan** [comment]
Thank you very much. The first approach does not work for me, but the second, editing copyq.conf, is perfect. /me bows deeply. This is one cool tool. ;-)
