### ISSUE TITLE
Change Items name or show only(!) notes.

### ISSUE THREAD

**Issue by ipleten** [hluk/CopyQ#815]
I use copyq also for storing passwords in encrypted tab.
Unfortunately, if someone is standing behind me with camera he could record all passwords as they are visible in plain text when I open tab.
Is that possible to change items name or show only notes for them with out showing actual item content?

**Comment by hluk** [comment]
There is [Hide/Show Item Content](https://github.com/hluk/copyq-commands/tree/master/Application#hideshow-item-content) command which hides content of selected items in the list (and when these are copied, only `<HIDDEN>` is shown in window title and notification).

**Comment by ipleten** [comment]
Great, I can used it with notes and that's exactly what I need.
Thank you a lot.
