### ISSUE TITLE
Automatically delete blanks at the end

### ISSUE THREAD

**Issue by u53r55** [hluk/CopyQ#816]
Can **CopyQ** automatically delete a blank space at the end?

**Comment by hluk** [comment]
Do you mean remove empty space from the end of a text copied to clipboard? Following automatic command does that ([here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)).

```ini
[Command]
Automatic=true
Command="
    copyq:
    var text = str(input())
    text = text.replace(/\\s+$/, '')
    if (isClipboard())
      copy(text)
    else
      copySelection(text)
    setData(mimeText, text)"
Icon=\xf016
Input=text/plain
Match=\\s+$
Name=Delete trailing space in clipboard
```
