### ISSUE TITLE
Clip Preview not reseting

### ISSUE THREAD

**Issue by SmileyStiles** [hluk/CopyQ#817]
The Clip Preview is not deleting the previous view. When you select a clip, it adds that to the preview but leaving the old content still in the preview.   I had posted this before with a previous version and it had gotten fixed but now it seems to be doing it again with this version of 3.1.1.  
I'm using this on Windows 7 PC and CopyQ 3.1.1
![copyq preview](https://user-images.githubusercontent.com/31048485/31749273-ca1587e6-b42d-11e7-9620-f4424dee4cac.jpg)

**Comment by hluk** [comment]
It's not fixed in 3.1.1. As pointed in [this comment](https://github.com/hluk/CopyQ/issues/808#issuecomment-333282177), the fixed version for Windows is [here](https://ci.appveyor.com/project/hluk/copyq/build/1.2.1204/job/dckft7pwye4yhx7g/artifacts).

Didn't have time to release new version yet.

**Comment by SmileyStiles** [comment]
Thanks for clearing that up. The version number looked newer to me, so I thought it was a newer version than what you have in your link.

**Comment by hluk** [comment]
> The version number looked newer to me, so I thought it was a newer version than what you have in your link.

Yeah, sorry about that, I think there is still problem with newer builds for Windows - they should show version `3.1.1-...` but instead it's something like `3.1.0-...`. No idea what's going on. I'll try to fix that.
