### ISSUE TITLE
Multi - monitor

### ISSUE THREAD

**Issue by makeshyft-tom-g** [hluk/CopyQ#819]
Please check shortcuts with multi-monitor setups.  The pop-up only displays on the primary window instead of where the mouse is.  I am refering to is the "popup at cursor" option.  Great program, but I have to go back to ditto for now.

**Comment by hluk** [comment]
Do you mean "Open windows on current screen" option? Which OS and desktop environment?

**Comment by wkdhkr** [comment]
Me, too. I am using Windows 10. The CopyQ popup menu does not seem to be able to exist in the minus coordinates.

**Comment by ibeex** [comment]
Same on latest gnome only works in first workspace.

**Comment by hluk** [comment]
Should be fixed (hopefully even for Wayland). To test it, you can get development version for Windows with the fix [here](https://ci.appveyor.com/project/hluk/copyq/build/1.2.1371/job/d42e77v4u0tjkco0/artifacts).
