### ISSUE TITLE
Translation - %1All string

### ISSUE THREAD

**Issue by bovirus** [hluk/CopyQ#820]
@hluk 

I didn't understand if **_%1All_** is reserved word or I can Translate as **_%1 All_** where I can translate the string **_All_** (as someone did for other languages).

I just to translate this string to finalize Italian translation.

**Comment by hluk** [comment]
That's translation for FakeVim module - emulation for Vim editing. The code is from different repo and I would like translators to omit translating those strings altogether - I didn't find a way to do that yet.

So you can keep the test as-is (the %1 is always important though).

Thanks.

**Comment by bovirus** [comment]
@hluk 
As I understood is 

**_%1 (reserved variable) + All (string)_**

and not I understood in the first step 

%1All

as reserved variable. Then I can translate All as string.

**Comment by hluk** [comment]
Just keep it untranslated. I'm trying to drop FakeVim strings from translations...

**Comment by bovirus** [comment]
OK. Thanks.
Please take care that in other language (seems French he translated it).
Please make change in Weblate repository about this string to avoid it as untranslated. 
CopyQ Italian translation is now complete.

I'm finalizing the Weblate software translation.

**Comment by hluk** [comment]
I've removed the FakeVim translations, it will probably take some time for Weblate to fully update the statistics and checks.

Thanks for the translations!
