### ISSUE TITLE
Handle X11 selection for stopped clients

### ISSUE THREAD

**Issue by blueyed** [hluk/CopyQ#821]
If you stop an application where something is selected (using the mouse typically), e.g. a terminal (using the PID from `echo $PPID`) with `kill -STOP $pid`, trying to paste this selection somewhere else will block, until you `kill -CONT` the application with the selection.

Could CopyQ handle this case?

This is related to https://github.com/awesomeWM/awesome-www/pull/111, where I dynamically stop e.g. browsers when they are not focused.

I've tried using `xsel --keep --primary` before the `kill -STOP` to work around this, but it appears to cause issues with Neovim, which uses `xsel` itself for clipboard management.

**Comment by hluk** [comment]
You could copy the selection again in CopyQ before stopping the other application. This way, CopyQ will provide the selection text instead of the other app.

```
copyq 'copySelection(selection())'
```

**Comment by blueyed** [comment]
Thanks, that seems to work well.

Could this be done automatically - e.g. similar to how it is done with killed clients?
Or is CopyQ using X11 events that only happen when a client is killed, but not when it is only stopped?

**Comment by hluk** [comment]
> Could this be done automatically

I don't know how. This is really strange use case - AFAIK, GUI apps are usually not stopped.

CopyQ could automatically take ownership of the X11 selection just after it changes, but some apps deselect text when this happens.

**Comment by blueyed** [comment]
OK.
Thanks for your support.

**Comment by blueyed** [comment]
@hluk 
Is it possible to know who owns the selection? (e.g. PID)
I would then only call this in case it is owned by the process to be stopped - otherwise e.g. `urxvt` unhighlights its selection (like you mentioned before).

**Comment by hluk** [comment]
> Is it possible to know who owns the selection?

I have no idea how to do that (perhaps using [XGetSelectionOwner](https://www.x.org/archive/X11R7.5/doc/man/man3/XConvertSelection.3.html) and somehow getting PID for the window).

**Comment by blueyed** [comment]
Yes, that's what I've found, too.
Then `XGetWindowProperty` could be used, but the code from https://lists.freedesktop.org/archives/xorg/2005-April/007254.html gave me "No properties".. :/

Could you imagine having an API for this in CopyQ, to get the PID of the clipboard or selection owner?

To simplify things for my usecase it would be great to have something along "take ownership of selection/clipboard for $PID".

**Comment by blueyed** [comment]
I think a good workaround is also this:
```
xclip -o -selection clipboard | xclip -verbose -selection clipboard &;
xclip -o -selection selection | xclip -verbose -selection selection &;
```
