### ISSUE TITLE
[Low priority] Oversized settings window

### ISSUE THREAD

**Issue by vatterspun** [hluk/CopyQ#822]
This is a really minor issue because the workaround is fairly simple, but I think users new to copy managers like this might be put off by it.

Setup: Win7x86, 1440x900 monitor

Steps: 
1. Download ZIP version of program (portable)
2. Launch program, select File - Preferences

Defect: setting screen too large.

![2017-10-21 12_57_26-clipboard](https://user-images.githubusercontent.com/1289134/31854475-a68f5c0a-b65f-11e7-8496-cf0b27685fa5.png)

Workaround: Resize the window

**Comment by hluk** [comment]
Is this still an issue? I cannot reproduce this in recent CopyQ version and clean configuration (testing on Linux though). Please, reopen if it shows up again.
