### ISSUE TITLE
Tab with most recently used items from all other tabs

### ISSUE THREAD

**Issue by meekreau** [hluk/CopyQ#824]
If there are items in different tabs that are reused frequently, in order to avoid switching tabs back and forth, it would be helpful to have a special tab where items are copied to upon activation (i.e. when `select()` is called), thus building MRU usage history of items across all tabs. I had a look at scripting to implement this, but as far as I understand, `select()` or `copy()` do not trigger any automatic commands. If there are no other workarounds for this (apart from ripping those items out of the tab tree and storing them in a dedicated tab manually), I would like to suggest this as a feature request.

**Comment by hluk** [comment]
There are commands for [Tab for Frequent Items](https://github.com/hluk/copyq-commands/tree/master/Application#tab-for-frequent-items).

**Comment by meekreau** [comment]
Thank you for the hint. My bad, should have had a closer look at the command repository. Basically, missed the point that *Enter*, which I use most of the time for item activation, can be set as shortcut for a command too.
