### ISSUE TITLE
CopyQ goes mad copying with big Data?

### ISSUE THREAD

**Issue by Clemens-Ratte-Polle** [hluk/CopyQ#825]
When copying over 100 Tabs URL+title with the extension "Copy URL+Title" 

https://chrome.google.com/webstore/detail/copy-url-%2B-title/dgagjmdgbakclelfacghmmbadkdegjjh/reviews

CopyQ goes mad..
It  copies without end! o_O

After over 100 times with CPU horror i killed the app and restarted it, then the madness had an end.
BUT i had to delete all the copied very long items out of CopyQ - hard work... :(

Perhaps CopyQ error, maybe the Chrome extension.

**Comment by hluk** [comment]
I don't have any issues with the extension.

Do you use lates CopyQ? Do you use some automatic commands?

**Comment by Clemens-Ratte-Polle** [comment]
i use "Move to trash" and "Undo Delete"

**Comment by hluk** [comment]
Can you share log (F12 shortcut)?

**Comment by Clemens-Ratte-Polle** [comment]
Note [2017-10-09 15:45:01.716] Server-1132: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/itemdata.dll
ERROR [2017-10-09 15:45:01.750] Server-1132: Failed to extract plugin meta data from 'C:/Program Files (x86)/!Utils/CopyQ/plugins/itemdata.dll'
Note [2017-10-09 15:45:01.873] Server-1132: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/itemencrypted.dll
ERROR [2017-10-09 15:45:01.874] Server-1132: Failed to extract plugin meta data from 'C:/Program Files (x86)/!Utils/CopyQ/plugins/itemencrypted.dll'
Note [2017-10-09 15:45:01.975] Server-1132: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/itemfakevim.dll
ERROR [2017-10-09 15:45:01.976] Server-1132: Failed to extract plugin meta data from 'C:/Program Files (x86)/!Utils/CopyQ/plugins/itemfakevim.dll'
Note [2017-10-09 15:45:02.015] Server-1132: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/itemimage.dll
ERROR [2017-10-09 15:45:02.018] Server-1132: Failed to extract plugin meta data from 'C:/Program Files (x86)/!Utils/CopyQ/plugins/itemimage.dll'
Note [2017-10-09 15:45:02.024] Server-1132: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/itemnotes.dll
ERROR [2017-10-09 15:45:02.026] Server-1132: Failed to extract plugin meta data from 'C:/Program Files (x86)/!Utils/CopyQ/plugins/itemnotes.dll'
Note [2017-10-09 15:45:02.121] Server-1132: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/itemsync.dll
ERROR [2017-10-09 15:45:02.122] Server-1132: Failed to extract plugin meta data from 'C:/Program Files (x86)/!Utils/CopyQ/plugins/itemsync.dll'
Note [2017-10-09 15:45:02.159] Server-1132: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/itemtags.dll
ERROR [2017-10-09 15:45:02.161] Server-1132: Failed to extract plugin meta data from 'C:/Program Files (x86)/!Utils/CopyQ/plugins/itemtags.dll'
Note [2017-10-09 15:45:02.203] Server-1132: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/itemtext.dll
ERROR [2017-10-09 15:45:02.204] Server-1132: Failed to extract plugin meta data from 'C:/Program Files (x86)/!Utils/CopyQ/plugins/itemtext.dll'
Note [2017-10-09 15:45:02.236] Server-1132: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/itemweb.dll
ERROR [2017-10-09 15:45:02.237] Server-1132: Failed to extract plugin meta data from 'C:/Program Files (x86)/!Utils/CopyQ/plugins/itemweb.dll'
Note [2017-10-09 15:45:02.242] Server-1132: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/libitemdata.dll
Note [2017-10-09 15:45:02.247] Server-1132: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/libitemencrypted.dll
Note [2017-10-09 15:45:02.252] Server-1132: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/libitemfakevim.dll
Note [2017-10-09 15:45:02.257] Server-1132: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/libitemimage.dll
Note [2017-10-09 15:45:02.262] Server-1132: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/libitemnotes.dll
Note [2017-10-09 15:45:02.267] Server-1132: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/libitempinned.dll
Note [2017-10-09 15:45:02.272] Server-1132: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/libitemsync.dll
Note [2017-10-09 15:45:02.279] Server-1132: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/libitemtags.dll
Note [2017-10-09 15:45:02.284] Server-1132: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/libitemtext.dll
Note [2017-10-12 16:54:09.503] Server-6896: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/itemdata.dll
ERROR [2017-10-12 16:54:09.582] Server-6896: Failed to extract plugin meta data from 'C:/Program Files (x86)/!Utils/CopyQ/plugins/itemdata.dll'
Note [2017-10-12 16:54:09.660] Server-6896: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/itemencrypted.dll
ERROR [2017-10-12 16:54:09.660] Server-6896: Failed to extract plugin meta data from 'C:/Program Files (x86)/!Utils/CopyQ/plugins/itemencrypted.dll'
Note [2017-10-12 16:54:09.722] Server-6896: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/itemfakevim.dll
ERROR [2017-10-12 16:54:09.738] Server-6896: Failed to extract plugin meta data from 'C:/Program Files (x86)/!Utils/CopyQ/plugins/itemfakevim.dll'
Note [2017-10-12 16:54:09.769] Server-6896: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/itemimage.dll
ERROR [2017-10-12 16:54:09.769] Server-6896: Failed to extract plugin meta data from 'C:/Program Files (x86)/!Utils/CopyQ/plugins/itemimage.dll'
Note [2017-10-12 16:54:09.816] Server-6896: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/itemnotes.dll
ERROR [2017-10-12 16:54:09.816] Server-6896: Failed to extract plugin meta data from 'C:/Program Files (x86)/!Utils/CopyQ/plugins/itemnotes.dll'
Note [2017-10-12 16:54:09.972] Server-6896: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/itemsync.dll
ERROR [2017-10-12 16:54:09.972] Server-6896: Failed to extract plugin meta data from 'C:/Program Files (x86)/!Utils/CopyQ/plugins/itemsync.dll'
Note [2017-10-12 16:54:10.035] Server-6896: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/itemtags.dll
ERROR [2017-10-12 16:54:10.035] Server-6896: Failed to extract plugin meta data from 'C:/Program Files (x86)/!Utils/CopyQ/plugins/itemtags.dll'
Note [2017-10-12 16:54:10.129] Server-6896: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/itemtext.dll
ERROR [2017-10-12 16:54:10.129] Server-6896: Failed to extract plugin meta data from 'C:/Program Files (x86)/!Utils/CopyQ/plugins/itemtext.dll'
Note [2017-10-12 16:54:10.191] Server-6896: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/itemweb.dll
ERROR [2017-10-12 16:54:10.191] Server-6896: Failed to extract plugin meta data from 'C:/Program Files (x86)/!Utils/CopyQ/plugins/itemweb.dll'
Note [2017-10-12 16:54:11.144] Server-6896: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/libitemdata.dll
Note [2017-10-12 16:54:11.425] Server-6896: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/libitemencrypted.dll
Note [2017-10-12 16:54:11.863] Server-6896: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/libitemfakevim.dll
Note [2017-10-12 16:54:13.254] Server-6896: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/libitemimage.dll
Note [2017-10-12 16:54:14.113] Server-6896: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/libitemnotes.dll
Note [2017-10-12 16:54:14.754] Server-6896: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/libitempinned.dll
Note [2017-10-12 16:54:15.379] Server-6896: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/libitemsync.dll
Note [2017-10-12 16:54:15.488] Server-6896: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/libitemtags.dll
Note [2017-10-12 16:54:17.332] Server-6896: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/libitemtext.dll
ERROR [2017-10-15 13:49:07.830] Monitor-5776: QtCritical: QWindowsPipeWriter::write failed. (Kein Prozess ist am anderen Ende der Pipe.) (:0, )
ERROR [2017-10-15 13:49:07.865] Monitor-5776: QtCritical: QWindowsPipeWriter::write failed. (Kein Prozess ist am anderen Ende der Pipe.) (:0, )
ERROR [2017-10-15 13:49:07.866] Monitor-5776: QtCritical: QWindowsPipeWriter::write failed. (Kein Prozess ist am anderen Ende der Pipe.) (:0, )
ERROR [2017-10-15 13:49:07.867] Monitor-5776: QtCritical: QWindowsPipeWriter::write failed. (Kein Prozess ist am anderen Ende der Pipe.) (:0, )
ERROR [2017-10-15 13:49:07.868] Monitor-5776: QtCritical: QWindowsPipeWriter::write failed. (Kein Prozess ist am anderen Ende der Pipe.) (:0, )
ERROR [2017-10-15 13:49:07.869] Monitor-5776: QtCritical: QWindowsPipeWriter::write failed. (Kein Prozess ist am anderen Ende der Pipe.) (:0, )
ERROR [2017-10-15 13:49:07.870] Monitor-5776: QtCritical: QWindowsPipeWriter::write failed. (Kein Prozess ist am anderen Ende der Pipe.) (:0, )
ERROR [2017-10-15 13:49:07.871] Monitor-5776: QtCritical: QWindowsPipeWriter::write failed. (Kein Prozess ist am anderen Ende der Pipe.) (:0, )
ERROR [2017-10-15 13:49:07.872] Monitor-5776: QtCritical: QWindowsPipeWriter::write failed. (Kein Prozess ist am anderen Ende der Pipe.) (:0, )
ERROR [2017-10-15 13:49:07.873] Monitor-5776: QtCritical: QWindowsPipeWriter::write failed. (Kein Prozess ist am anderen Ende der Pipe.) (:0, )
ERROR [2017-10-15 13:49:08.179] Server-6896: Restarting clipboard monitor (Connection timeout)
ERROR [2017-10-15 13:49:24.199] Monitor-17156: QtCritical: QWindowsPipeWriter: asynchronous write failed. (Die Pipe wurde beendet.) (:0, )
ERROR [2017-10-15 13:49:24.202] Monitor-17156: QtCritical: QWindowsPipeWriter::write failed. (Die Pipe wird gerade geschlossen.) (:0, )
ERROR [2017-10-15 13:49:24.214] Server-6896: Restarting clipboard monitor (Failed to start)
ERROR [2017-10-15 13:49:40.209] Monitor-12164: QtCritical: QWindowsPipeWriter: asynchronous write failed. (Die Pipe wurde beendet.) (:0, )
ERROR [2017-10-15 13:49:40.212] Monitor-12164: QtCritical: QWindowsPipeWriter::write failed. (Die Pipe wird gerade geschlossen.) (:0, )
ERROR [2017-10-15 13:49:40.227] Server-6896: Restarting clipboard monitor (Failed to start)
ERROR [2017-10-15 13:49:56.226] Monitor-8496: QtCritical: QWindowsPipeWriter: asynchronous write failed. (Die Pipe wurde beendet.) (:0, )
ERROR [2017-10-15 13:49:56.229] Monitor-8496: QtCritical: QWindowsPipeWriter::write failed. (Die Pipe wird gerade geschlossen.) (:0, )
ERROR [2017-10-15 13:49:56.244] Server-6896: Restarting clipboard monitor (Failed to start)
ERROR [2017-10-15 13:50:12.239] Monitor-232: QtCritical: QWindowsPipeWriter: asynchronous write failed. (Die Pipe wurde beendet.) (:0, )
ERROR [2017-10-15 13:50:12.241] Monitor-232: QtCritical: QWindowsPipeWriter::write failed. (Die Pipe wird gerade geschlossen.) (:0, )
ERROR [2017-10-15 13:50:12.251] Server-6896: Restarting clipboard monitor (Failed to start)
ERROR [2017-10-15 13:50:28.259] Monitor-14928: QtCritical: QWindowsPipeWriter: asynchronous write failed. (Die Pipe wurde beendet.) (:0, )
ERROR [2017-10-15 13:50:28.261] Monitor-14928: QtCritical: QWindowsPipeWriter::write failed. (Die Pipe wird gerade geschlossen.) (:0, )
ERROR [2017-10-15 13:50:28.272] Server-6896: Restarting clipboard monitor (Failed to start)
ERROR [2017-10-15 13:50:44.274] Monitor-7676: QtCritical: QWindowsPipeWriter: asynchronous write failed. (Die Pipe wurde beendet.) (:0, )
ERROR [2017-10-15 13:50:44.276] Monitor-7676: QtCritical: QWindowsPipeWriter::write failed. (Die Pipe wird gerade geschlossen.) (:0, )
ERROR [2017-10-15 13:50:44.286] Server-6896: Restarting clipboard monitor (Failed to start)
ERROR [2017-10-15 13:54:19.383] Server-6896: Restarting clipboard monitor (Connection timeout)
Note [2017-10-18 11:11:01.486] Server-16660: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/itemdata.dll
ERROR [2017-10-18 11:11:01.521] Server-16660: Failed to extract plugin meta data from 'C:/Program Files (x86)/!Utils/CopyQ/plugins/itemdata.dll'
Note [2017-10-18 11:11:01.525] Server-16660: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/itemencrypted.dll
ERROR [2017-10-18 11:11:01.526] Server-16660: Failed to extract plugin meta data from 'C:/Program Files (x86)/!Utils/CopyQ/plugins/itemencrypted.dll'
Note [2017-10-18 11:11:01.567] Server-16660: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/itemfakevim.dll
ERROR [2017-10-18 11:11:01.568] Server-16660: Failed to extract plugin meta data from 'C:/Program Files (x86)/!Utils/CopyQ/plugins/itemfakevim.dll'
Note [2017-10-18 11:11:01.596] Server-16660: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/itemimage.dll
ERROR [2017-10-18 11:11:01.598] Server-16660: Failed to extract plugin meta data from 'C:/Program Files (x86)/!Utils/CopyQ/plugins/itemimage.dll'
Note [2017-10-18 11:11:01.614] Server-16660: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/itemnotes.dll
ERROR [2017-10-18 11:11:01.622] Server-16660: Failed to extract plugin meta data from 'C:/Program Files (x86)/!Utils/CopyQ/plugins/itemnotes.dll'
Note [2017-10-18 11:11:01.662] Server-16660: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/itemsync.dll
ERROR [2017-10-18 11:11:01.663] Server-16660: Failed to extract plugin meta data from 'C:/Program Files (x86)/!Utils/CopyQ/plugins/itemsync.dll'
Note [2017-10-18 11:11:01.676] Server-16660: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/itemtags.dll
ERROR [2017-10-18 11:11:01.678] Server-16660: Failed to extract plugin meta data from 'C:/Program Files (x86)/!Utils/CopyQ/plugins/itemtags.dll'
Note [2017-10-18 11:11:01.681] Server-16660: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/itemtext.dll
ERROR [2017-10-18 11:11:01.682] Server-16660: Failed to extract plugin meta data from 'C:/Program Files (x86)/!Utils/CopyQ/plugins/itemtext.dll'
Note [2017-10-18 11:11:01.685] Server-16660: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/itemweb.dll
ERROR [2017-10-18 11:11:01.686] Server-16660: Failed to extract plugin meta data from 'C:/Program Files (x86)/!Utils/CopyQ/plugins/itemweb.dll'
Note [2017-10-18 11:11:01.849] Server-16660: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/libitemdata.dll
Note [2017-10-18 11:11:01.913] Server-16660: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/libitemencrypted.dll
Note [2017-10-18 11:11:02.006] Server-16660: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/libitemfakevim.dll
Note [2017-10-18 11:11:02.032] Server-16660: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/libitemimage.dll
Note [2017-10-18 11:11:02.076] Server-16660: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/libitemnotes.dll
Note [2017-10-18 11:11:02.247] Server-16660: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/libitempinned.dll
Note [2017-10-18 11:11:02.370] Server-16660: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/libitemsync.dll
Note [2017-10-18 11:11:02.428] Server-16660: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/libitemtags.dll
Note [2017-10-18 11:11:02.494] Server-16660: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/libitemtext.dll
ERROR [2017-10-25 12:21:30.344] Client-18928: Verbindung verloren!
ERROR [2017-10-25 12:21:30.444] Client-8804: QtCritical: QWindowsPipeWriter: asynchronous write failed. (Die Pipe wurde beendet.) (:0, )
ERROR [2017-10-25 12:21:30.512] Client-8804: QtCritical: QWindowsPipeWriter::write failed. (Die Pipe wird gerade geschlossen.) (:0, )
ERROR [2017-10-25 12:21:30.514] Client-8804: Verbindung verloren!
Note [2017-10-25 12:21:44.713] Server-10424: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/itemdata.dll
ERROR [2017-10-25 12:21:44.715] Server-10424: Failed to extract plugin meta data from 'C:/Program Files (x86)/!Utils/CopyQ/plugins/itemdata.dll'
Note [2017-10-25 12:21:44.732] Server-10424: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/itemencrypted.dll
ERROR [2017-10-25 12:21:44.734] Server-10424: Failed to extract plugin meta data from 'C:/Program Files (x86)/!Utils/CopyQ/plugins/itemencrypted.dll'
Note [2017-10-25 12:21:44.782] Server-10424: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/itemfakevim.dll
ERROR [2017-10-25 12:21:44.783] Server-10424: Failed to extract plugin meta data from 'C:/Program Files (x86)/!Utils/CopyQ/plugins/itemfakevim.dll'
Note [2017-10-25 12:21:44.812] Server-10424: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/itemimage.dll
ERROR [2017-10-25 12:21:44.814] Server-10424: Failed to extract plugin meta data from 'C:/Program Files (x86)/!Utils/CopyQ/plugins/itemimage.dll'
Note [2017-10-25 12:21:44.829] Server-10424: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/itemnotes.dll
ERROR [2017-10-25 12:21:44.831] Server-10424: Failed to extract plugin meta data from 'C:/Program Files (x86)/!Utils/CopyQ/plugins/itemnotes.dll'
Note [2017-10-25 12:21:44.856] Server-10424: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/itemsync.dll
ERROR [2017-10-25 12:21:44.857] Server-10424: Failed to extract plugin meta data from 'C:/Program Files (x86)/!Utils/CopyQ/plugins/itemsync.dll'
Note [2017-10-25 12:21:44.870] Server-10424: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/itemtags.dll
ERROR [2017-10-25 12:21:44.871] Server-10424: Failed to extract plugin meta data from 'C:/Program Files (x86)/!Utils/CopyQ/plugins/itemtags.dll'
Note [2017-10-25 12:21:44.873] Server-10424: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/itemtext.dll
ERROR [2017-10-25 12:21:44.874] Server-10424: Failed to extract plugin meta data from 'C:/Program Files (x86)/!Utils/CopyQ/plugins/itemtext.dll'
Note [2017-10-25 12:21:44.877] Server-10424: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/itemweb.dll
ERROR [2017-10-25 12:21:44.878] Server-10424: Failed to extract plugin meta data from 'C:/Program Files (x86)/!Utils/CopyQ/plugins/itemweb.dll'
Note [2017-10-25 12:21:45.048] Server-10424: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/libitemdata.dll
Note [2017-10-25 12:21:45.108] Server-10424: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/libitemencrypted.dll
Note [2017-10-25 12:21:45.196] Server-10424: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/libitemfakevim.dll
Note [2017-10-25 12:21:45.270] Server-10424: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/libitemimage.dll
Note [2017-10-25 12:21:45.321] Server-10424: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/libitemnotes.dll
Note [2017-10-25 12:21:45.385] Server-10424: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/libitempinned.dll
Note [2017-10-25 12:21:45.457] Server-10424: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/libitemsync.dll
Note [2017-10-25 12:21:45.513] Server-10424: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/libitemtags.dll
Note [2017-10-25 12:21:45.612] Server-10424: Lade Plugin: C:/Program Files (x86)/!Utils/CopyQ/plugins/libitemtext.dll

**Comment by hluk** [comment]
There was an issue with installer - it did not remove plugins completely - that's why there are those "Failed to extract plugin meta data" errors. Not sure if that can be the problem, but you can try uninstalling the app, removing any installation files that will be left in the installation folder, and reinstalling.
