### ISSUE TITLE
Print all history ? 

### ISSUE THREAD

**Issue by qoxxxx** [hluk/CopyQ#827]
Is there a way to dump all clipboards in history ? 
Something like
`for i in {0..50}; do copyq read $i; echo -e '\n---'; done`
but more efficient ...

**Comment by hluk** [comment]
Following command is effective (though quite ugly because there is no rage function; I really should add one).

```
copyq 'rows = []; c = count(); for (i = 0; i < c; ++i) { rows.push(i) }; read.apply(this, rows)'
```

**Comment by qoxxxx** [comment]
Thanks !

**Comment by reagle** [comment]
Yes please, was looking today and couldn't believe this didn't exist.
