### ISSUE TITLE
Win key no longer usable as shortcut modifier

### ISSUE THREAD

**Issue by jnki** [hluk/CopyQ#828]
After upgrading to the latest windows 10 creator fall update (1709), the Windows key is no longer usable as a modifier in CopyQ.

I can use it in other software, but in CopyQ, nothing happens.

I used to use the shortcut ctrl + win key + v.

**Comment by hluk** [comment]
Is this still an issue? I don't remember having such issues on Win 10, could be problem that shortcut is misinterpreted by CopyQ (different keyboard layout or some other system settings).

**Comment by jnki** [comment]
Yeah it's still an issue here for me.
If I try to add the shortcut ctrl+win+v, or ctrl+shift+v, it will not recognise them in this window
![image](https://user-images.githubusercontent.com/17442109/45601350-6bbcbe80-ba03-11e8-96bd-d8587f4afce7.png)

I can add ctrl+shift+v in copyq.ini manually to make it work. but i'd rather use ctrl+win+v, like i used to before. My keyboard is UK English qwerty.

**Comment by hluk** [comment]
Thanks for quick response and screenshot.

From the screenshot it looks like one of the dialog buttons is focused. Can you try clicking on the line with `Click here...` to focus the field and then assign a shortcut?

Can you try to assign `meta+ctrl+v` manually instead? (I think `meta` is interpreted as the Win key.)

**Comment by jnki** [comment]
I tried again, clicking in the "click here" box and entering. Still cannot put in ctrl+win+v. 
I can put in other shortcuts like ctrl+f and it accepts that.
Tried manually adding meta+ctrl+v and that also did not work :(

**Comment by hluk** [comment]
Anything in the log? (F12 shortcut)

**Comment by jnki** [comment]
![image](https://user-images.githubusercontent.com/17442109/45640525-daa12280-baaa-11e8-8c1b-9aaf208b9cac.png)

**Comment by hluk** [comment]
Is it possible the it's already used by other application or system?

Can you map for example Ctrl+V or Meta+V?

In case it's not really possible to use a global shortcut, you might be able to set the shortcut in system configuration and assign it to a command (for show/hide it's `copyq toggle`).

**Comment by jnki** [comment]
I can't think of anything that shortcut could be assigned to.

I can map ctrl+v, but I cannot map win+V. Also some other combinations with win key do not work. win+Z, win+C, win+X etc... Sometimes with an extra modifier like they will work.

Like ctrl+win+z will work, but not win+z.

I will look into using the other solution, I'm not sure how to set a system wide shortcut.

**Comment by jnki** [comment]
Hmm same issue with portable it seems.

Yes the issue did appear after the windows update, so likely related to that.

I can use alt+win+v for now, which works nicely for me.

**Comment by Bintux** [comment]
Have the same issue with CopyQ Version v3.9.2 installed and Windows 10 Version 1709

**Comment by monoblaine** [comment]
See https://github.com/hluk/CopyQ/issues/1668#issuecomment-971892924 for a possible workaround.
