### ISSUE TITLE
When synchronizing edit notes creates separate file

### ISSUE THREAD

**Issue by pihentagy** [hluk/CopyQ#830]
* Setup Syncronize Tabs and Directories (I have md, txt and html extensions synced with text/plain, text/plain, text/html mime type respectively)
* Go to that syncronized tab
* Select existing note
* Edit notes
* After some seconds, the note is converted to a separate file (and displayed as a separate item in CopyQ), if the item was `TSP.md`, the note will have `TSP_note.txt` as a name.
* Try to edit the note again and you will presented a blank item. After you type in something and save it, it will overwrite the previous note

**Comment by hluk** [comment]
I cannot reproduce this. Here is how I tested this.

1. I configured synchronization plugin to show `*.md` files as plain text.
![image](https://user-images.githubusercontent.com/38054/32403464-5156a866-c13a-11e7-9bc5-4f598d818efb.png)
2. After creating files in test directory
```bash
> for filename in TSP.{md,txt,html}; do echo TEST > "$filename"; done
> ls
TSP.html  TSP.md  TSP.txt
```
3. it shows up in CopyQ as single item.
![image](https://user-images.githubusercontent.com/38054/32403453-0cba72b4-c13a-11e7-9075-07d3081f0de3.png)
4. I edit note with Shift+F2, type "test" and save.
![image](https://user-images.githubusercontent.com/38054/32403468-77ff7b28-c13a-11e7-8509-3620f0d40ec7.png)
5. Test directory now contains a file ending with `_note.txt`.
```bash
> ls
TSP.html  TSP.md  TSP_note.txt  TSP.txt
```
6. After editing again, only the note and content of the note file changes.
7. After clearing note text, there is no note visible and the note file is removed.

Can you verify if the test is correct?

**Comment by pihentagy** [comment]
Test is right, just I have the following after step 4:


![selection_083](https://user-images.githubusercontent.com/29916/32506621-57cfa262-c3e5-11e7-8114-e08602eb8658.png)

After editing the note of the original TSP.md, editor fires up with blank, and when entering "another", the content of `TSP_note.txt` changed to "another"
![selection_084](https://user-images.githubusercontent.com/29916/32506714-975b1182-c3e5-11e7-8362-1d7f11779186.png)

After clearing note: TSP.html, TSP.txt and TSP.md are all deleted!. TSP_note.txt remained.

CopyQ v3.1.2~xenial on Ubuntu

**Comment by hluk** [comment]
What do you have in synchronization settings?

**Comment by pihentagy** [comment]
![selection_085](https://user-images.githubusercontent.com/29916/32508529-eee71d10-c3ea-11e7-9f32-02193d520357.png)

**Comment by pihentagy** [comment]
How can I delete from the lower list btw?

**Comment by hluk** [comment]
Looks like after adding `txt` to the table, the notes are interpreted as separate item (since it has `txt` suffix too). I'll try to fix that.

Anyway, you can remove the `txt` and `html` lines since some formats are recognized by CopyQ. To delete from the table you need to clear the text (double-click the cell to edit it).

I should make the settings UI for synchronization simpler - I didn't spend much time on it.

Thanks for the report.

**Comment by pihentagy** [comment]
Thanks, it helped. Note, that to delete the row, you also have to clear the Item MIME Type.
