### ISSUE TITLE
Insert item on either side of the selected text

### ISSUE THREAD

**Issue by Kzer-Za** [hluk/CopyQ#831]
Is it possible to implement this feature?

Imagine that you select some text that you want to make a (for example) hyperlink, then select from CopyQ a saved item, something like `<a href="">$SelectedText</a>` and `<a href="">` is inserted before the selected text and `</a>`, after.

It can be used for many tags and bbcodes. Seems to me it can be useful to many people (I read an article praising Charu (a windows clipboard manager) for having this feature).

**Comment by hluk** [comment]
It's possible in CopyQ. Following command copies selected items as a HTML link ([here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)).
```ini
[Command]
Command="
    copyq:
    copy('<a href=\"\">' + str(input()) + '</a>')"
Icon=\xf0c1
InMenu=true
Input=text/plain
Name=Copy as Link
```
