### ISSUE TITLE
MACRO / Shortcut (Move to next item)

### ISSUE THREAD

**Issue by TacKnight** [hluk/CopyQ#832]
Hey,

I cannot for the life of me find or understand how to move to the next item in saved copy history without opening the menu and clicking on it. Is there some sort of support for saying:

Paste item#1 & move to item#2
Paste item#2 & move to item#3
etc etc

**Comment by hluk** [comment]
You can follow [these steps](http://copyq.readthedocs.io/en/latest/faq.html#how-to-open-application-window-or-tray-menu-using-shortcut), but instead of "Show/hide main window", select "Paste and copy next" from the list of predefined commands.
