### ISSUE TITLE
Bind with an Android device's clipboard (ClipSync)

### ISSUE THREAD

**Issue by arjamizo** [hluk/CopyQ#834]
``tl;dr select text on Linux and find it in your Android's clipboard``

I am looking for some alternative for ClipSync, which syncs clipboards between Android and Windows. 

What do you think about this?

New option in options: 
* "Bind with Android"
** Clicking on which opens qrcode with a public key (CopyQ generates its private key only for this session)
** Android device gets MAC (for wifi) or IP (for NAT, but still safety/no 3G nor LTE usage) or (fallback) ngrok alternative
** whenever there's some magic-packet broadcasted via UDP port 3906, CopyQ decrypts this with private key and adds to the history

```bash
    while true; do nc -l 3906 | openssl ... $COPYQ_PRIV_KEY | xclip -selection c; done
```

but this requires additional Android app: 
* Android: 
** qrcode scanner for binding (zlib) + openssl (rsa) for encrypting clipboard content
** hook on every cliboard change + post-hook 
** gnupg for encryption of the cliboard
** (*) optional compression of selected files for super 
** (*) optional share provider for exchanging files

```java
public class ClipBoardCopyQSync extends Service {

    private final String tag = "[[ClipboardWatcherService]] ";  
    private OnPrimaryClipChangedListener listener = new OnPrimaryClipChangedListener() {
        public void onPrimaryClipChanged() {
            performClipboardCheck();
        }
    };

    @Override 
    public void onCreate() {
        ((ClipboardManager) getSystemService(CLIPBOARD_SERVICE)).addPrimaryClipChangedListener(listener);
    }
```
via https://stackoverflow.com/a/22287217

What do you think guys?

**Comment by amosbird** [comment]
I asked for a similar feature https://github.com/hluk/CopyQ/issues/793

**Comment by PaulMEdwards** [comment]
According to #449, Android platform target was dropped...

I'm looking for a replacement for [ClipperSync](https://clippersync.com) which I've been using for many years and is [EOL](https://eol.clippersync.com) as of next month.

**Comment by hluk** [comment]
Closing. I don't have any reason to implement this myself.
