### ISSUE TITLE
System Tray - Windows

### ISSUE THREAD

**Issue by squirrelboot** [hluk/CopyQ#838]
Hello!

I love this program and use it hundreds of times per day. However, I was wondering if there is a way to hide the tray icon by the clock? When I 'disable' tray, it then forces it to minimize to the taskbar, which I don't want either. 

I like having a clean system tray. Since I hotkey and use the window that way, I don't need a taskbar or tray icon. Is there a way to have the program run, but without those two?

Thanks!

**Comment by hluk** [comment]
You need to toggle also the "Hide main window" option in "Layout" configuration tab.

The option is disabled by default because it can be difficult to access the app if tray is not available and main window is not listed in panel at all.
