### ISSUE TITLE
Corrupted tab content displaying

### ISSUE THREAD

**Issue by rparkhunovsky** [hluk/CopyQ#839]
Have an issue with seeing text in the second tab which gets corrupted after editing (by F2) and switching between tabs:
1 - garbage copied from the 1st tab
2 - black rectangle appears
![image](https://user-images.githubusercontent.com/6543422/34043163-1766d65e-e1a0-11e7-8bf5-51e9f8f5b47c.png)

After copyq restart this looks normal as below until the next tab change:
![image](https://user-images.githubusercontent.com/6543422/34043105-dbf6c296-e19f-11e7-8d22-69907100d2f6.png)

Ubuntu 16.04, KDE Neon 5.11, copyq v3.1.2

**Comment by hluk** [comment]
Recently in very rare cases I had same issues on KDE (on Arch Linux).

Hopefully the fix will work for you too.

**Comment by hluk** [comment]
Just found out that this is still an issue.

It can be reproduced when hovering over an item with notes, in which case a tool tip shows over the list, items are then incorrectly rendered when scrolling through the list.

Could be Qt or a graphics driver issue. I'll try to fix that somehow.

**Comment by hluk** [comment]
Should be fixed now (4ec36d5258aa54c538d8c16262f7e1bfe83eb44c).
