### ISSUE TITLE
Error occurs if decryption doesn't happen within a short time.

### ISSUE THREAD

**Issue by akwala** [hluk/CopyQ#841]
If the clipboard is encrypted a dialog pops up to enter the password to decrypt it. If the correct password is not submitted within a short timeout period an error occurs which is logged as "Item file ... is corrupted or some CopyQ plugins are missing!"

No error should occur if a password is not submitted or the dialog to enter it is canceled -- if the dialog is canceled it may be useful to log an INFO message. Only the submission of an incorrect password should trigger an error.

Secondly, the error reporting is misleading. It should report that decryption failed because the password was incorrect.

**Comment by hluk** [comment]
I removed the confusing error message.

In case the password entry times out (which now depends on the pinentry process) or is cancelled, notification "Encryption failed" pops up.

See details in the commit 1fbade4086c37428064f09d6621705f32e2da33a.

**Comment by akwala** [comment]
> In case the password entry times out (which now depends on the pinentry process) or is cancelled, notification "Encryption failed" pops up.
Shouldn't the error be "_Decryption_ failed"?

**Comment by hluk** [comment]
> Shouldn't the error be "Decryption failed"?

Oops, yes. "Encryption failed" only pops up when encrypting or saving encrypted items fails.
