### ISSUE TITLE
Ubuntu 16.04 LTS not supported.

### ISSUE THREAD

**Issue by deragon** [hluk/CopyQ#844]
Following the instructions provided on CopyQ's website, on a Ubuntu 16.04 LTS computer:
```
sudo add-apt-repository ppa:hluk/copyq
sudo apt update
sudo apt install copyq
```
...print out the following errors:
```
# sudo apt install copyq
Reading package lists... Done
Building dependency tree       
Reading state information... Done
copyq is already the newest version (3.1.2-1).
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 copyq : Depends: libqt5core5a (>= 5.7.0) but 5.5.1+dfsg-16ubuntu7.5 is to be installed
         Depends: libqt5gui5 (>= 5.7.0) but 5.5.1+dfsg-16ubuntu7.5 is to be installed
         Depends: libqt5script5 (>= 5.6.0~beta) but 5.5.1+dfsg-2build1 is to be installed
         Depends: libqt5widgets5 (>= 5.6.0~beta) but 5.5.1+dfsg-16ubuntu7.5 is to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
```
The tool should be easy to be installed on an LTS system.  One should not have to compile it or download the dependencies manually and risk problems with other parts of the system.

Maybe a snap or flatpak solution should be considered?

**Comment by hluk** [comment]
I don't see Qt 5.7.0 being supported on Ubuntu 16.04 [1].

If you use Qt from different repos you have to rebuild CopyQ (not sure if there is a simple way with the PPA).

> Maybe a snap or flatpak solution should be considered?

I haven't look into this but pull requests are accepted.

[1] https://packages.ubuntu.com/xenial/libqt5gui5

**Comment by hluk** [comment]
@deragon Just letting you know that CopyQ Flatpak package is on the way (#862).
