### ISSUE TITLE
Question: Snippet placeholders

### ISSUE THREAD

**Issue by glolsh** [hluk/CopyQ#845]
Hello @hluk !
I'm trying to use snippets, but I can't figure out how snippets with placeholders work. (On Ubuntu 16.04.3)
Example text:
`Today is ${Day}`

If I call snippet command - it should show me dialog with snippets, then if selected snippet contains placeholders - ask to insert custom text. Second step never happens.

**Comment by hluk** [comment]
Can you verify you use latest CopyQ (v3.1.2) and up-to-date [Snippets command](https://github.com/hluk/copyq-commands/tree/master/Global#snippets)?

**Comment by glolsh** [comment]
![image](https://user-images.githubusercontent.com/14776737/34549237-d6901e8e-f139-11e7-8e6f-9425acac7f16.png)
`    copyq:
    var snippetsTabName = 'snips'
    // List snippets instead of search combo box?
    var listSnippets = false
    function newVarRe(content) {
      return new RegExp('\\\\${' + content + '}', 'g')
    }
    function getText(item) {
      return str(item[mimeText] || '')
    }
    function assignPlaceholder(snippet, placeholder, value) {
      return snippet.replace(newVarRe(placeholder), value)
    }
    function fuzzyIndexOf(snippetNames, snippetName) {
        var re = new RegExp(snippetName, 'i')
        for (var i in snippetNames) {
          if (snippetNames[i].match(re))
            return i;
        }
        return -1
    }
    function loadSnippets(snippetNames, snippets)
    {
      var tabs = tab()
      for (var i in tabs) {
        var tabName = tabs[i];
        if (tabName != snippetsTabName && tabName.indexOf(snippetsTabName + '/') != 0)
          continue;
        tab(tabName)
        var prefix = tabName.substring(snippetsTabName.length + 1)
        if (prefix)
          prefix += ': '
        for (var j = 0; j < size(); ++j) {
          var snippet = getitem(j)
          var snippetName = str(snippet[mimeItemNotes] || getText(snippet))
          snippetNames.push(prefix + snippetName)
          snippets.push(snippet)
        }
      }
    }
    function askForSnippet(snippetNames, snippets) {
      var list = listSnippets ? '.list:' : ''
      var snippet = dialog(
        '.title', 'Select Snippet',
        list + 'Snippet', snippetNames
      ) || abort()
      if (listSnippets)
          return snippets[snippet]
      var i = snippetNames.indexOf(snippet)
      if (i != -1)
        return snippets[i]
      i = fuzzyIndexOf(snippetNames, snippet)
      if (i != -1)
        return snippets[i]
      popup(
        'Snippet Not Found',
        'No matching snippet found for \"' + snippetName + '\"!'
      )
      abort()
    }
    function getPlaceholders(snippet) {
      var placeholders = []
      var m
      var reVar = newVarRe('(.*?)')
      while ((m = reVar.exec(snippet)) !== null) {
        if (placeholders.indexOf(m[1]) === -1)
          placeholders.push(m[1])
      }
      return placeholders
    }
    function askToAssignPlaceholders(snippet) {
      var placeholders = getPlaceholders(snippet)
      if (placeholders.length == 0)
        return snippet
      var label = escapeHtml(snippet)
        .replace(newVarRe('(.*?)'), '<b>$1</b>')
      var dialogVars = [
        '.title', 'Set Snippet Values',
        '.label', label
      ]
      for (var i in placeholders) {
        var name = placeholders[i]
        dialogVars.push(name)
        dialogVars.push(name)
      }
      var values = dialog.apply(this, dialogVars) || abort()
      if (placeholders.length == 1)
        return assignPlaceholder(snippet, placeholders[0], values)
      for (var i in placeholders) {
        var name = placeholders[i]
        snippet = assignPlaceholder(snippet, name, values[name])
      }
      return snippet
    }
    function pasteSnippet(mime, content) {
      copy(mime, content)
      copySelection(mime, content)
      paste()
    }
    var snippetNames = []
    var snippets = []
    loadSnippets(snippetNames, snippets)
    var snippet = askForSnippet(snippetNames, snippets)
    var textSnippet = getText(snippet)
    if (textSnippet)
      pasteSnippet(mimeText, askToAssignPlaceholders(textSnippet))
    else
      pasteSnippet(mimeItems, pack(snippet))`

**Comment by hluk** [comment]
Not sure whats wrong. Can you try to re-add [the command](https://github.com/hluk/copyq-commands/tree/master/Global#snippets)?

**Comment by glolsh** [comment]
Maybe you can write some step-by-step manual how to use snippets with placeholders? This will help greatly.

**Comment by hluk** [comment]
Not sure what is unclear. Description on how to add commands in CopyQ is in the [copyq-commands repo](https://github.com/hluk/copyq-commands#add-a-command-to-copyq) and in [documentation](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them).

I know that the structure of commands repo and how to add commands to CopyQ may not be easy to grasp. If you have some ideas, I'm accepting pull requests.

**Comment by glolsh** [comment]
Okay, I'll think about it
Should this snippet work?
`*${Weekday} ${Day}th ${Month}*
*Done*
>• merge resolved feature branches
*ToDo*
>• impl product list real data
>• impl product details real data
*Issues*
>• backend documentation is untrue for product details method`

**Comment by hluk** [comment]
Yes, that snippet should work.

![image](https://user-images.githubusercontent.com/38054/34732742-64f2ddd0-f566-11e7-9d22-1b524e87f239.png)

**Comment by glolsh** [comment]
Fixed. As solution: manually importing .ini file worked. Before I was pasting text by hand.

**Comment by glolsh** [comment]
As final question: is there any way to set a range of values for a variable? For example for Weekday there is 5 values - Monday, Tuesday and etc.

**Comment by hluk** [comment]
I've updated the [Snippet command](https://github.com/hluk/copyq-commands/tree/master/Global#snippets). I hope it's clear how to use it from the description.

Your snippet can now look like this.

```
${Weekday:Monday,Tuesday,Wednesday,Thursday,Friday} ${Day:1st,2nd,3rd,4th,5th,6th,7th,8th,9th,10th,11th,12th,13th,14th,15th,16th,17th,18th,19th,20th,21st,22nd,23rd,24th,25th,26th,27th,28th,29th,30th,31st} ${Month:1,2,3,4,5,6,7,8,9,10,11,12}
```

**Comment by glolsh** [comment]
Yep, almost everything works like I need. I hope in future you'll implement "copy final snippet to clipboard" instead of instant pasting to where cursor is.
And multi-line text entering.
![image](https://user-images.githubusercontent.com/14776737/34805127-e642b164-f6ae-11e7-988f-5f896ffa7a18.png)

In any case -  BIG THANK YOU. I'm big fan of your app. It helps me everywhere!

**Comment by hluk** [comment]
> I hope in future you'll implement multi-line text entering

[Done](https://github.com/hluk/copyq-commands/tree/master/Global#snippets) (the custom dialog already supported it) - you can use `${Name:\n}` or `${Name:line1\nline2}`.

> I'm big fan of your app. It helps me everywhere!

It's always great to hear this :). It helps me a lot too - I grew pretty addicted to it.

**Comment by glolsh** [comment]
Thanks you very much) Works like a charm!

**Comment by glolsh** [comment]
@hluk both of them are not working(

**Comment by hluk** [comment]
Just made <kbd>Ctrl</kbd>+<kbd>Enter</kbd> behavior consistent on all platforms. It should work in next version.

**Comment by glolsh** [comment]
Sorry for many requests in one issue. Again - thank you! This one should be quiet for now)

**Comment by hluk** [comment]
:) Glad I can help.
