### ISSUE TITLE
ubuntu package 

### ISSUE THREAD

**Issue by urbandroid** [hluk/CopyQ#847]
$ sudo apt install copyq
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package copyq

https://hluk.github.io/CopyQ/ documentation at the link is not working problems on sudo add-apt-repository ppa:hluk/copyq

**Comment by hluk** [comment]
What's the problem with `sudo add-apt-repository ppa:hluk/copyq`?

**Comment by urbandroid** [comment]
it was public key problem but now after removing repository and trying again to give you error message it worked, interesting. So i'm sorry i can't give you the original message. Also i couldn't find it in any log at /var/log/
