### ISSUE TITLE
Snippets: delay pasting, hide from clipboard?

### ISSUE THREAD

**Issue by paul1149** [hluk/CopyQ#850]
Hi,
I use the Snippets global command a lot. I also have focus follows mouse in effect, and maybe because of that, unless I drag the snippets window over the target application, it often pastes into the wrong application. So I first have to drag the Snippets window over my intended target app.

If I could delay Snippets' pasting by a couple of seconds, it would give the machine time to give focus back to my intended target.

I'm on Linux, Debian 9, MX17.

Also, is there a way to keep Snippets' pastes out of the clipboard? It would be as a security measure. 
Thanks.

**Comment by hluk** [comment]
You can try replacing `pasteSnippet()` function in the Snippet command with following.

```js
function pasteSnippet(mime, content) {
  copy(mime, content)
  copySelection(mime, content)

  // Wait few milliseconds before pasting clipboard.
  sleep(500)
  paste()

  // Clear clipboard after pasted.
  sleep(2000)
  copy('')
  copySelection('')
}
```

**Comment by paul1149** [comment]
Thanks very much. An extra second (1000) gives me the time I need to refocus my target app. For some reason, though, adding this code slows down the initial appearance of the Snippets window, it seems by that same one second amount. I can live with it, but it seems odd.

My apologies on the second request. What I actually meant was to stop Snippets from saving the password in the copyq stack. I'm going to leave the pw in the live clipboard, because sometimes it has to be used more than once. Bbut I'm a bit confused now. Previously I had seen my password in the copyq stack. Maybe I had actually hard-copied it there. Now it doesn't show up, which seems to mean Snippets is already clearing it. But then, up in copyq's title bar, I do see the password. I can live with that too, since it will disappear when the clipboard receives a new string.

Anyway, thanks much for your time and a great utility.

**Comment by hluk** [comment]
> For some reason, though, adding this code slows down the initial appearance of the Snippets window, it seems by that same one second amount.

That's really strange, because the `sleep()` is called only after the Snippets dialogs are closed (just before the paste).

> What I actually meant was to stop Snippets from saving the password in the copyq stack.

Not sure what's your workflow with passwords but Snippets command is intended to be used with templates (e.g. `Today is ${Day}`).

You should be able to paste items directly from CopyQ (depending on your settings).

If you need to store passwords in CopyQ they should be [encrypted](http://copyq.readthedocs.io/en/latest/password-protection.html).

**Comment by paul1149** [comment]
Hluk, sorry, somehow I missed your last post. I don't like the way gmail does threading and look forward to Vivaldi's coming email client.

Yes, I can't figure out why the sleep command would affect the dialog appearance either. But it surely does.

Not sure how Templates, apparently with wildcards, are used. I call up the snippet dialog and, among other things, use it to paste a password.

Nice documentation. Didn't know copyq did encryption. I think it's beyond my needs, but I'll keep it in mind.

Thanks.

**Comment by paul1149** [comment]
My apologies. The delay I was seeing seems to be normal, regardless of the sleep setting at the end. This seems to be a focus bug of Xfce's. When I turn off "focus follows mouse" the problem disappears. I've alerted them but haven't heard back yet.
