### ISSUE TITLE
Tag (like Hashtag #) for more organize and better search

### ISSUE THREAD

**Issue by devlifeX** [hluk/CopyQ#852]
Hey,
I'm using copyq for a while and without doubt it's very handy and straight. 
I have dozens of username and password in my clipboard, it would be very nice if i can set tag or category or what ever you called for it to better search and better copyq user experiences, unfortunately my C++ skill is not good enough to implement this gorgeous feature by myself ;)
thanks in advanced.

**Comment by hluk** [comment]
You can use notes (Shift+F2 to edit note) or [tags](http://copyq.readthedocs.io/en/latest/tags.html).

BTW, I store few passwords in CopyQ as [encrypted items](http://copyq.readthedocs.io/en/latest/password-protection.html) with notes - notes and tags should be visible even if item is encrypted - then I use "Decrypt and Copy" command to copy these items.
