### ISSUE TITLE
Large images aren't copied in copyq

### ISSUE THREAD

**Issue by amosbird** [hluk/CopyQ#855]
Hi, is there somehow a size limit in copyq? When copying a large image inside virtualbox ( > 2MB ), it always fails to show up in copyq.

**Comment by hluk** [comment]
It should work (e.g. [~7MiB image](https://www.nasa.gov/sites/default/files/thumbnails/image/20180041842_goes16-abi-conus-geocolor-2500x1500.jpg)).

Perhaps VirtualBox has some optimizations for this or it's very slow when providing larger amount of clipboard data.

**Comment by amosbird** [comment]
Yeah, it's indeed related to VirtualBox.
