### ISSUE TITLE
Notification of Updates?

### ISSUE THREAD

**Issue by richlux** [hluk/CopyQ#858]
Is there a way to have CopyQ notify the user if there is an update to the program?  Currently, I find myself checking GitHub every once in a while to see if there is an update.  It would be nice if we could be notified automatically somehow.

Rich

**Comment by hluk** [comment]
How about watching [Releases feed](https://github.com/hluk/copyq/releases.atom)?

There is also [mailing list](https://groups.google.com/forum/#!forum/copyq) where I send release announcements.

**Comment by richlux** [comment]
How do I watch the Releases feed?  I know I can watch the conversations on GitHub, but I'm not familiar with how to watch the releases feed.

Rich

**Comment by hluk** [comment]
> How do I watch the Releases feed?

With a [feed reader](https://en.wikipedia.org/wiki/Comparison_of_feed_aggregators). Also some e-mail clients have support for Atom feeds.

**Comment by richlux** [comment]
Thanks.  I didn't realize it was an RSS Feed.  I have a ton of feeds I already watch, so this would probably get lost among the others.  I subscribed to the group instead.

Thanks again,
Rich
