### ISSUE TITLE
[feature] Ability to easy export "text clips" or tabs to a JSON, YAML or CSV format

### ISSUE THREAD

**Issue by TarekJor** [hluk/CopyQ#859]
First, thanks for CopyQ, and the great work it is awesome (and the scripting features are great to integrate with APIs etc)

About the Issue:
## **Ability to easy export "text clips" to a JSON, YAML or CSV format**
I think this is a great and useful feature.

This could be accomplished via command-line particular method but, as it is "trivial" enough, it could be a command to easy export text-tabs: (ignoring captures as MIME /image etc, output only for text "with markup" or "plain text"

Examples:
* note: syntax => {object}, document output (per tab) format (CSV or JSON), or even YAML (lightweight)

syntax:

`copyq {tab} export(yaml) {output-path}`

example:

`copyq clipboard export(yaml) {userData}/../dumps/`

another one:

`copyq queries export(json) ../clips/` => queries.json

Then on ../dumps directory => clipboard.yaml (as document database format with the clip.snippets)

Any other method, via command-line, will be appreciated, as "copyq-commands" already implemented (to make useful things easier)

I don't know what format are the .dat files or .cpq, (noob here on CopyQ)

Notice: I will edit properly this issue, to prevent my spam, or "questions", or if this "feature" is not needed because can be accomplished via "normal" copyq scripting among another programs. (sorry for the inconvenience)

**Comment by hluk** [comment]
There is [Copy and Paste Items in JSON Format](https://github.com/hluk/copyq-commands/tree/master/Application#copy-and-paste-items-in-json-format) command. So saving items in JSON is definitely possible.

In next CopyQ version it'll be possible to add new command line functions, so you will be able to create and `export()` function and run something like `copyq export json`. For now you can execute a script as `cat script.js | copyq -e - arg1 arg2 ...`.

> I don't know what format are the .dat files or .cpq

Those are just binary formats.

**Comment by hluk** [comment]
To export items from a tab to JSON files to given directory you can now use following command. It creates new script function `exportJSON` (for details, see the comment at the top of the command).

```ini
[Command]
Command="
    /*
    
    Exports items from a tab to given directory:
    
      copyq 'exportJSON(\"./exported/\")'
      copyq tab url 'exportJSON(\"./url/\")'
    
    */
    
    function fromData(data)
    {
      var text = str(data)
      if ( data.equals(new ByteArray(text)) ) {
        if (text.indexOf('\\\\n') == -1)
          return text
        return { lines: text.split('\\\\n') }
      }
      return { base64: toBase64(data) }
    }
    
    global.exportJSON = function(path) {
      var indentation = '    '
    
      var dir = new Dir(path)
    
      if ( !dir.mkpath('.') )
        throw 'Failed to create directory: ' + path
    
      for (row = 0; row < count(); ++row) {
        var itemData = getItem(row)
    
        var item = {}
        for (var format in itemData)
          item[format] = fromData(itemData[format])
    
        var file = new File(dir.filePath(row + '.json'))
        if ( !file.openWriteOnly() )
          throw 'Failed to open file: ' + file.fileName()
    
        var json = JSON.stringify(item, null, indentation)
        if ( file.write(json) == -1 )
          throw 'Failed to write file: ' + file.fileName()
      }
    }"
Icon=\xf3b8
IsScript=true
Name=exportJSON()
```

**Comment by TarekJor** [comment]
This is really useful and very appreciated, now it is all faster with that exportJSON function, have a nice day @hluk, and thanks for your help solving this.
