### ISSUE TITLE
Can't paste to JetBrains Rider

### ISSUE THREAD

**Issue by nZeus** [hluk/CopyQ#865]
Hello all!

CopyQ can't paste text into JetBrains Rider. I tried to double-click an item, I tried to press "enter" button. 
The popup disappears but nothing happens:

![copyq](https://user-images.githubusercontent.com/2727326/35518703-904941e8-0512-11e8-9b9e-ce2bb4645254.gif)

I can normally paste text into e.g. notepad, word, excel after a double-click operation.

Thanks!

**Comment by hluk** [comment]
You can try overriding the Enter key with [this command](https://github.com/hluk/CopyQ/issues/562#issuecomment-257385689).

[Here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them).

**Comment by nZeus** [comment]
I did try this command, but it doesn't change anything. Why did you close this issue? This seems to be a 100% bug

**Comment by hluk** [comment]
> Why did you close this issue?

I was recently closing old issues (or issues without any new response).

---

Did you try overriding Enter key with the command I mentioned in the comment above?

Can you paste to the app with <kbd>Shift</kbd>+<kbd>Insert</kbd>?

**Comment by actor20170211030627** [comment]
I meet this bug too, i can't paste into anything focus window, even can't paste at a txt file. (by press `Enter` and double-click item).

**Comment by Chealer** [comment]
@nZeus: Does this persist? If so, please see [that checklist](https://blog.michael.gr/post/2014-11-bug-reporting-checklist/), in particular sections 8 to 13.

@actor20170211030627: Please specify your OS
