### ISSUE TITLE
Share Clips

### ISSUE THREAD

**Issue by JeremyWW** [hluk/CopyQ#866]
Is it possible, in some way that I've missed, to share clips with another user on the same LAN? Or is this a feature request?

**Comment by hluk** [comment]
Did you try exporting tabs? (It's under File - Export; use File - Import to import tabs.)

Another way is to use [synchronize plugin](http://copyq.readthedocs.io/en/latest/synchronize.html).

**Comment by scottkosty** [comment]
Following on the idea to use the synchronize plugin, if you can set up a folder that both computers can access, then I think you can do it. For example, I share a tab on Dropbox and thus have my "favorites" tab synchronized across all of my computers.

**Comment by JeremyWW** [comment]
I'll give it a go. Thanks.

**Comment by JeremyWW** [comment]
This actually works pretty well, although my shared folder is on a mapped drive on a Synology NAS. Instantaneous clip sharing - excellent. So, now I have a feature request! Is it possible to create a pop-up notification banner (standard W10 notifications ideally) when a clip is placed in the Shared tab(s)? This would be brilliant as part of the workflow in our small business.

**Comment by scottkosty** [comment]
Monitoring changes (or creations) in a folder and triggering a command (e.g. a notification/email/anything) is something that is very easy to set up on Linux. If you are using Linux I can tell you how to do this. I'm not sure if "W10" means Windows 10? If so, I imagine there are some programs on Windows that can do the same thing.

As for CopyQ, I think a reasonable feature request would be for CopyQ to notify you if one of the items in your tab has been changed/added externally. Such notifications are common among other programs. However, CopyQ should not in my opinion give a system-wide notification in such a case (I have not seen any other application do that, except Dropbox whose purpose is to manage file and folder changes). It would just be something that you see when you open CopyQ. If you would like to make this request, please open a separate issue.

**Comment by hluk** [comment]
@JeremyWW Can we close this issue?

**Comment by JeremyWW** [comment]
Yep.
