### ISSUE TITLE
CopyQ does not appear in Gnome systray

### ISSUE THREAD

**Issue by Jiehong** [hluk/CopyQ#867]
Hello,

Copyq seems to still be using the old systray on Gnome, and thus doesn't appear with the rest of the top-right systray part.

Would it be possible to re-show it in the tray under Gnome ?

**Comment by hluk** [comment]
Perhaps some Gnome Shell extension can help.

I use Qt GUI framework to create tray icon and I don't want to re-implement the functionality for the few desktop environments that decided to deprecate tray (it still works fine on Windows, OS X and even XFCE and KDE Plasma).
