### ISSUE TITLE
Alt closes main window with default "close_on_unfocus" option

### ISSUE THREAD

**Issue by scottkosty** [hluk/CopyQ#868]
Starting with commit 6eab7d36 (the fix for #495), if I open the main window and press "alt", the window closes. For a use case, I press "alt + e" to open the "Edit" menu or to access a tab (that I use & in the name of to activate the Qt accelerator). Actually, with the option `close_on_unfocus turned` I can't even access File, Edit, etc.

Turning off the option `close_on_unfocus` restores expected behavior for me.

Perhaps this is due to my old Qt version (I use the system default of Ubuntu 16.04)?

    $ copyq --version
    CopyQ Clipboard Manager v3.1.2-212-g7332075 (hluk@email.cz)
    Built with: Qt 5.5.1, LibQxt 0.7.0
    $

**Comment by hluk** [comment]
Should be fixed.

I think there could still be problems with some window managers -- e.g. resizing window in Openbox.

Thanks for the detailed report.

**Comment by scottkosty** [comment]
Tested and works well. Thanks.
