### ISSUE TITLE
Easier way to cycle and paste

### ISSUE THREAD

**Issue by unlocomqx** [hluk/CopyQ#872]
I was using clip diary and it has an option where you can cycle through back and forth then the last item is pasted when you release the global shortcut

I recorded a [video](https://vimeo.com/254948874) containing the described workflow

The problem I encountered while implementing this is that QXT doesn't provide a signal when a hotkey is released (all the keys are released)

Do you have a better idea about potentially implementing this? It's much more convenient that any other method imo

Cheers

**Comment by hluk** [comment]
Did you try "Paste and copy next/previous" commands? They can be added in Command dialog (F6) with Add button.

**Comment by unlocomqx** [comment]
Yes, I tried them but they don't give the same flow
I'll try modifying the qxt lib if I don't find any other solution

Cheers

**Comment by unlocomqx** [comment]
I was able to modify the qxt lib to detect the shortcut release
I set a flag to count the modifiers then count the key up actions
[commit](https://github.com/unlocomqx/CopyQ/commit/2bfe08e727c69c9351343e0417fc4ba1ee923809)
This gave me the same workflow that I got used to, although the solution isn't elegant or very stable
PS: don't mind the enablePasteFlag and the pasteOnRelease, I couldn't use them because I couldn't access the scriptable instance. I have no experience with QT or C++ 
Also sry for the bad code xD, it was more like "fake it till you make it"
