### ISSUE TITLE
double paste issue arch linux

### ISSUE THREAD

**Issue by zeltak** [hluk/CopyQ#874]
Hi

i have been using copyq on arch for last 2 years with no issues

recently in the last few weeks i have been having serious issues when i paste. it seems that copyq pastes once and then after a short delay another paste (unwanted) of the same paste is issued

anyone having these issues?

would love help on how to debug this

best

Z

**Comment by tukanos** [comment]
@zeltak are you using Wayland or Xorg?

**Comment by zeltak** [comment]
Hi

im using up to date arch linux, i3 WM and xorg

best

Z

**Comment by hluk** [comment]
Do you have any commands in Command dialog (F6 shortcut)?

**Comment by zeltak** [comment]
Hi again

no no commands there

would be happy to help in anyway to debug this!

best

Z

**Comment by hluk** [comment]
> would be happy to help in anyway to debug this!

If you can debug this, the method for pasting is [here](https://github.com/hluk/CopyQ/blob/12bf4aac1632e392965c2a40c43b3ffe31f263dd/src/platform/x11/x11platformwindow.cpp#L262). It sends <kbd>Shift</kbd>+<kbd>Insert</kbd> shortcut by default to a target window.

**Comment by scottkosty** [comment]
> i have been using copyq on arch for last 2 years with no issues

Did you update CopyQ recently? If you think it's a CopyQ change that caused the problem, perhaps a git bisect would be useful.
