### ISSUE TITLE
Random large & small blank from clipboard entries 

### ISSUE THREAD

**Issue by mbakstars** [hluk/CopyQ#876]
I am not sure what is causing it, but in my clipboard I have random large and small blank entries. I have actually created a tab with these entries, and have about 40 of them now. I do have errors in my log and can post here upon request.  The major ones that were seen repeatedly are: 

1. ERROR [2018-02-16 10:39:30.032] Server-13680: QtCritical: QWindowsPipeWriter: asynchronous write failed. (The pipe has been ended.) (:0, )
2. ERROR [2018-02-15 17:35:32.026] Monitor-9864: QtCritical: QWindowsPipeWriter::write failed. (No process is on the other end of the pipe.) (:0, )
3. ERROR [2018-02-15 17:35:31.692] Server-20736: Exception: std::bad_alloc

![image](https://user-images.githubusercontent.com/31328113/36336939-8c4a7136-1339-11e8-9a49-acc483037e59.png)

**Comment by hluk** [comment]
What's the app version?

Do you use have any commands in Command dialog (F6 shortcut)?

**Comment by mbakstars** [comment]
Good morning, my apologies I was out of the office over the weekend.  I have quite a few commands; attached zip format. 

W10E64 - App v3.1.2

[backup.zip](https://github.com/hluk/CopyQ/files/1737720/backup.zip)

**Comment by hluk** [comment]
Try to add "Ignore items with no or single character" predefined command -- it's available from Command dialog when you click on "Add" button.

**Comment by hluk** [comment]
Anyway, that's just workaround, empty items (or items with just whitespace) are quite useless and shouldn't be added to the list. I'll do something about that in next release.
