### ISSUE TITLE
Scripting command to see "Inactive Formats"

### ISSUE THREAD

**Issue by SamHasler** [hluk/CopyQ#879]
In [this comment](https://github.com/hluk/CopyQ/issues/311#issuecomment-72268342) I mentioned that I'd prefer if CopyQ just kept everything whether it knows how to present it or not the way CLCL does.

The root issue is that without knowing what formats are stored in the "raw" clipboard data it's impossible to know what to add to "Active Formats", unless you use some other tool to inspect the clipboard.

I noticed this in [release 3.2.0](https://github.com/hluk/CopyQ/releases/tag/v3.2.0):
>  Allow to override clipboard handling with script commands

and from the [updated docs](https://copyq.readthedocs.io/en/latest/scripting-api.html) (Aside: If you could link to updated documentation from the release notes it would be very helpful) there is this new hook:

> ### onClipboardChanged()
> Called when clipboard or X11 selection changes.
> 
> Default implementation is:
> 
> ```
> if (runAutomaticCommands()) {
>     synchronizeSelection();
>     saveData();
>     updateClipboardData();
> } else {
>     clearClipboardData();
> }
> ```

There doesn't appear to be a way to hook into the "Active Formats" here. Could a method be added?

e.g. either, get a list of the "raw" formats on a clipboard item, or have a function that's called for each format to decide whether to show it.

Would either of those be easy to add and do you think that'd make a useful addition?

**Comment by hluk** [comment]
You can override `saveData()`, add additional data to save (with `setData()`) and call the original function (the original removes some helper internal data and saves to clipboard tab).

```ini
[Command]
Command="
    saveData_ = saveData
    saveData = function() {
        // Save all formats in current clipboard (or X11 selection).
        var clipboardFn = isClipboard() ? clipboard : selection
        var allFormats = str(clipboardFn('?')).split('\\n')
        var retrievedFormats = dataFormats()
        for (var i in allFormats) {
            var format = allFormats[i]
            if (format && !(format in retrievedFormats)) {
                var data = clipboardFn(format)
                setData(format, data)
            }
        }
        // Call overridden function.
        return saveData_()
    }"
Icon=\xf0c7
IsScript=true
Name=Save All Formats
```

NOTE: This can lead to some performance issues because it can store a lot of unneeded data - like various image formats (even asking for the data can take a long time).

> Aside: If you could link to updated documentation from the release notes it would be very helpful

Still haven't got the time to update the docs, sorry. The new command types allow to do really interesting things.

**Comment by SamHasler** [comment]
Interesting. It wasn't apparent from the documentation that this was possible.

I'm seeing formats like: `application/x-qt-windows-mime;value="chromium-bookmark-entries"`
Is that a bug in CopyQ or just the script above?

**Comment by hluk** [comment]
> Is that a bug in CopyQ or just the script above?

That's just Qt framework (which provides clipboard access for CopyQ) making some Windows specific clipboard formats available under MIME type.

**Comment by hluk** [comment]
There were some changes for "script" commands in recent CopyQ versions, the command above should be now:

```ini
[Command]
Command="
    var saveData_ = saveData
    global.saveData = function() {
        // Save all formats in current clipboard (or X11 selection).
        var clipboardFn = isClipboard() ? clipboard : selection
        var allFormats = str(clipboardFn('?')).split('\\n')
        var retrievedFormats = dataFormats()
        for (var i in allFormats) {
            var format = allFormats[i]
            if (format && !(format in retrievedFormats)) {
                var data = clipboardFn(format)
                setData(format, data)
            }
        }
        // Call overridden function.
        return saveData_()
    }"
Icon=\xf0c7
IsScript=true
Name=Save All Formats
```
