### ISSUE TITLE
Package for 3.2.0 on OpenSUSE Tumbleweed

### ISSUE THREAD

**Issue by dmarcoux** [hluk/CopyQ#880]
Hi,

I would like to install the latest version `3.2.0` of CopyQ on OpenSUSE Tumbleweed, but unlike previous versions, it doesn't seem to be available in the release. Is it still supported?

Thank you for your work on CopyQ!

**Comment by hluk** [comment]
I used Qt 4 for OpenSUSE Tumbleweed, but I'm deprecating this old Qt version.

Unfortunately, the new spec file that uses Qt 5 fails with some [strange errors](https://build.opensuse.org/package/live_build_log/home:lukho:copyq/CopyQ-Qt5/openSUSE_Tumbleweed/x86_64) (the build commands work fine on Fedora).

If you know how to fix the spec file, it's [here](https://build.opensuse.org/package/view_file/home:lukho:copyq/CopyQ-Qt5/copyq.spec?expand=1).

**Comment by dmarcoux** [comment]
The first potential issue I see is the following:

>[  101s] CMake Warning at src/CMakeLists.txt:49 (find_package):
>[  101s]   By not providing "FindQt5LinguistTools.cmake" in CMAKE_MODULE_PATH this
>[  101s]   project has asked CMake to find a package configuration file provided by
>[  101s]   "Qt5LinguistTools", but CMake did not find one.

I have no idea what Qt5LinguistTools is as I don't know much about Qt5, but it seems like there's a package on OpenSUSE Tumbleweed which is providing this: `libqt5-linguist`.

I tried adding it to the spec files with `BuildRequires:  cmake(libqt5-linguist)` and `BuildRequires: libqt5-linguist` and both don't work.

**Comment by dmarcoux** [comment]
I fixed the CMake warning with `BuildRequires:  libqt5-linguist-devel`. However, it's still not working due to this now:

>[   13s] + -DCMAKE_SKIP_RPATH=TRUE -DWITH_QT5=ON -DWITH_TESTS=TRUE -DCMAKE_INSTALL_PREFIX=/usr -DPLUGIN_INSTALL_PREFIX=/usr/lib64/copyq/plugins -DTRANSLATION_INSTALL_PREFIX:PATH=/usr/share/copyq/locale
[   13s] /var/tmp/rpm-tmp.13L9fZ: line 55: -DCMAKE_SKIP_RPATH=TRUE: command not found
[   13s] error: Bad exit status from /var/tmp/rpm-tmp.13L9fZ (%build)

Do you have an idea on why this is happening?

**Comment by hluk** [comment]
Sorry for late response (somehow lost the notification for your comment in mail).

> My assumption is that the macro cmake_kf5 isn't working on OpenSUSE.

I think that can be fixed by using `%cmake_kf5` instead of `%{cmake_kf5}`. Unfortunately it fails elsewhere after the fix (see [the test project on OBS](https://build.opensuse.org/package/show/home:lukho:branches:home:lukho:copyq/CopyQ-Qt5-opensuse)) -- I'm trying to fixed that.

**Comment by hluk** [comment]
Almost there. Now it complains that `Categories` in desktop file are wrong.

I tried fixing it in spec file but it still fails - not sure what exactly is wrong.

**Comment by dmarcoux** [comment]
I think that I've found why the `Categories` are wrong. Well, at least according to the documentation at https://doc.qt.io/archives/qtextended4.4/desktopfiles.html, it says:

> (...)  you should not attempt to categorize your software as a "Utility", since it is difficult to differentiate this category from the Settings and Applications categories (it falls somewhere in between).

I cannot try it now to see if removing `;Utility` in `Categories` would fix it.

**Comment by hluk** [comment]
Tried `Qt;KDE;Office;TextTools;` and `Qt;KDE;`, without success. Maybe the verification script has issues with parsing the desktop file.

**Comment by hluk** [comment]
Done. Had to change the category to `Qt;KDE;Office;WordProcessor;`.

Package is available at [releases](https://github.com/hluk/CopyQ/releases).

**Comment by dmarcoux** [comment]
Nice one, thank you for taking the time to fix this. It is greatly appreciated.
