### ISSUE TITLE
Last window focus is lost after invoking tray menu with global shortcut

### ISSUE THREAD

**Issue by araujorm** [hluk/CopyQ#883]
When invoking the tray menu with a global shortcut, the focus of the last window is not restored when the tray menu is closed (either by pressing ESC or selecting a clipboard history entry).

For the main window there is an option to do so, which is pretty useful, but right now with the tray, as it is, is a major hindrance.

Can that option be added to restore the focus after closing the tray, or just do it by default? (I think it would make sense to do it by default, like other clipboard managers like clipit or parcellite do)

Thanks and best regards.

**Comment by hluk** [comment]
What's the OS and CopyQ version?

**Comment by araujorm** [comment]
Hi.

Fedora 26, 64 bit.

Happens both with the latest package that comes with fedora (copyq-3.1.2-1.fc26.x86_64) and the release 3.2.0 that is available on https://github.com/hluk/CopyQ/releases for fedora.

Desktop is cinnamon, didn't test with other environments.

As said, if I map the global shortcut to the main window it works correctly when invoked and closed, the problem is if I map the global shortcut to invoke the tray icon menu.

Best regards.

**Comment by araujorm** [comment]
Hi.

This issue still persists in version 3.3.0.

Best regards.

**Comment by hluk** [comment]
Is the focus correctly returned if you press ESC to hide the tray menu?

I think the problem could also be that CopyQ needs to run some focus stealing code so that menu or main window can be correctly focused with global shotcut (this can potentially mess window order used by window manager).

**Comment by araujorm** [comment]
On 03/23/2018 05:21 PM, Lukas Holecek wrote:
>
> Is the focus correctly returned if you press ESC to hide the tray menu?
>
> I think the problem could also be that CopyQ needs to run some focus
> stealing code so that menu or main window can be correctly focused
> with global shotcut (this can potentially mess window order used by
> window manager).
>

No, it's the same thing if one selects an item from the clipboard on the
tray menu, or if one presses ESC.

But this should be trivial to reproduce, or am I the only one having that?

Best regards.

**Comment by araujorm** [comment]
One note:

On 03/23/2018 05:21 PM, Lukas Holecek wrote:
>
> I think the problem could also be that CopyQ needs to run some focus
> stealing code so that menu or main window (...)
>

As I said in the beginning, it works fine if the shortcut is mapped to
open the main window, and the focus is correctly restored. So if I had
to guess, I'd say that the hard part is already implemented, just not
being called for the tray menu case (but I could be wrong, as I didn't
look at the code).

**Comment by hluk** [comment]
> But this should be trivial to reproduce, or am I the only one having that?

I haven't been able to reproduce that. But I think the closest I can now get to your environment is Fedora 25 with Cinnamon (in VirtualBox).

> So if I had to guess, I'd say that the hard part is already implemented, just not being called for the tray menu case (but I could be wrong, as I didn't look at the code).

Window manager should normally be able to focus previous window after menu is closed. I would rather omit running extra code to focus last window (it's bit of a hack and it can break window ordering or return focus to different window or widget anyway).

**Comment by araujorm** [comment]
Hi.

Just tried with MATE, Fedora 26. Same thing, exactly. So I wouldn't say it has to do with cinnamon or fedora.

Please note that the problem does NOT occur when I open the menu with a right-click on the tray icon.

It just happens when opening the tray menu with a keyboard global shortcut (that you must first assign - I like using CTRL-ALT-H but it alwasy happens with every combination I've tried) and you can see in that case that the last window loses focus immediately, whereas with the right click on the tray the last active window never loses focus.

I checked what happens with ClipIt, for instance. When pressing the keyboard shortcut to open the tray menu, the window doesn't lose focus. Also with Parcellite. Hope that helps.

Thanks and best regards.

**Comment by hluk** [comment]
Can you share your configuration (file `~/.config/copyq/copyq.conf`)?

Are you using X11 or Wayland?

**Comment by araujorm** [comment]
Hello.

On 03/27/2018 06:36 AM, Lukas Holecek wrote:
>
> Can you share your configuration (file |~/.config/copyq/copyq.conf|)?
>
Sure, I'm sending it attached.

> Are you using X11 or Wayland?
>
X11.

Thanks and best regards.


[General]
plugin_priority=itemimage, itemencrypted, itemfakevim, itemnotes, itempinned, itemsync, itemtags, itemtext, itemdata

[Command]
Command=copyq: menu()
GlobalShortcut=ctrl+alt+h
Icon=\xf01c
IsGlobalShortcut=true
Name=Show the tray menu

[Options]
action_has_input=false
action_has_output=false
action_output_tab=
action_separator=\\n
activate_closes=true
activate_focuses=true
activate_pastes=false
always_on_top=false
autocompletion=true
autostart=true
check_clipboard=true
check_selection=true
clipboard_notification_lines=0
clipboard_tab=&clipboard
close_on_unfocus=true
command_history_size=100
confirm_exit=true
copy_clipboard=false
copy_selection=false
disable_tray=false
edit_ctrl_return=true
editor=emacs -- %1
expire_tab=0
hide_main_window=false
hide_tabs=false
hide_toolbar=false
hide_toolbar_labels=true
item_popup_interval=0
language=en
maxitems=500
move=true
notification_horizontal_offset=10
notification_maximum_height=100
notification_maximum_width=300
notification_position=3
notification_vertical_offset=10
number_search=true
open_windows_on_current_screen=true
save_filter_history=false
show_advanced_command_settings=false
show_simple_items=false
show_tab_item_count=false
tab_tree=false
tabs=&clipboard
text_wrap=true
transparency=10
transparency_focused=10
tray_commands=true
tray_images=true
tray_item_paste=false
tray_items=30
tray_tab=
tray_tab_is_current=true
vi=false

[Plugins]
itemdata\enabled=true
itemencrypted\enabled=true
itemfakevim\enabled=true
itemfakevim\really_enable=false
itemfakevim\source_file=
itemimage\enabled=true
itemimage\image_editor=
itemimage\max_image_height=240
itemimage\max_image_width=320
itemimage\svg_editor=
itemnotes\enabled=true
itempinned\enabled=true
itemsync\enabled=true
itemtags\enabled=true
itemtext\enabled=true
itemweb\enabled=true

[Shortcuts]
about=shift+f1
change_tab_icon=ctrl+shift+t
commands=f6
copy_selected_items=ctrl+c
delete_item=del
edit=f2
edit_notes=shift+f2
editor=ctrl+e
exit=ctrl+q
export=ctrl+s
find_items=ctrl+g
format-next=ctrl+right
format-previous=ctrl+left
help=f1
import=ctrl+i
move_down=ctrl+down
move_to_bottom=ctrl+end
move_to_clipboard=
move_to_top=ctrl+home
move_up=ctrl+up
new=ctrl+n
new_tab=ctrl+t
next_tab=right
paste_selected_items=ctrl+v
preferences=ctrl+p
previous_tab=left
process_manager=ctrl+shift+z
remove_tab=ctrl+w
rename_tab=ctrl+f2
reverse_selected_items=ctrl+shift+r
show-log=f12
show_clipboard_content=ctrl+shift+c
show_item_content=f4
show_item_preview=f7
sort_selected_items=ctrl+shift+s
system-run=f5
toggle_clipboard_storing=ctrl+shift+x

[Theme]
alt_bg=#f7f5f3
alt_item_css=
bg=#ffffff
css=
cur_item_css="\n    ;border: 0.1em solid ${sel_bg}"
edit_bg=#ffffff
edit_fg=#000000
edit_font=
fg=#000000
find_bg=#ff0
find_fg=#000
find_font=
font=
font_antialiasing=true
item_css=
item_spacing=
menu_bar_css="\n    ;background: ${bg}\n    ;color: ${fg}"
menu_bar_disabled_css="\n    ;color: ${bg - #666}"
menu_bar_selected_css="\n    ;background: ${sel_bg}\n    ;color: ${sel_fg}"
menu_css="\n    ;border-top: 0.08em solid ${bg + #333}\n    ;border-left: 0.08em solid ${bg + #333}\n    ;border-bottom: 0.08em solid ${bg - #333}\n    ;border-right: 0.08em solid ${bg - #333}"
notes_bg=#ffffdc
notes_css=
notes_fg=#000000
notes_font=
notification_bg=#333
notification_fg=#ddd
notification_font=
num_fg=#000000
num_font=
search_bar="\n    ;background: ${edit_bg}\n    ;color: ${edit_fg}\n    ;border: 1px solid ${alt_bg}\n    ;margin: 2px"
search_bar_focused="\n    ;border: 1px solid ${sel_bg}"
sel_bg=#308cc6
sel_fg=#ffffff
sel_item_css=
show_number=false
show_scrollbars=true
style_main_window=false
tab_bar_css="\n    ;background: ${bg - #222}"
tab_bar_item_counter="\n    ;color: ${fg - #044 + #400}\n    ;font-size: 6pt"
tab_bar_scroll_buttons_css="\n    ;background: ${bg - #222}\n    ;color: ${fg}\n    ;border: 0"
tab_bar_sel_item_counter="\n    ;color: ${sel_bg - #044 + #400}"
tab_bar_tab_selected_css="\n    ;padding: 0.5em\n    ;background: ${bg}\n    ;border: 0.05em solid ${bg}\n    ;color: ${fg}"
tab_bar_tab_unselected_css="\n    ;border: 0.05em solid ${bg}\n    ;padding: 0.5em\n    ;background: ${bg - #222}\n    ;color: ${fg - #333}"
tab_tree_css="\n    ;color: ${fg}\n    ;background-color: ${bg}"
tab_tree_item_counter="\n    ;color: ${fg - #044 + #400}\n    ;font-size: 6pt"
tab_tree_sel_item_counter="\n    ;color: ${sel_fg - #044 + #400}"
tab_tree_sel_item_css="\n    ;color: ${sel_fg}\n    ;background-color: ${sel_bg}\n    ;border-radius: 2px"
tool_bar_css="\n    ;color: ${fg}\n    ;background-color: ${bg}\n    ;border: 0"
tool_button_css="\n    ;background-color: transparent"
tool_button_selected_css="\n    ;background: ${sel_bg}\n    ;color: ${sel_fg}"
use_system_icons=false

**Comment by hluk** [comment]
OK, I can reproduce it if I disable "Paste activated item to current window" in Tray tab. Trying to fix that.
