### ISSUE TITLE
macOS cannot respond to hotkey for display under mouse

### ISSUE THREAD

**Issue by RoadToDream** [hluk/CopyQ#885]
cannot respond to hotkey for display under mouse under macOS sometimes when restarted

**Comment by RoadToDream** [comment]
Will not display when auto-started, recover if relaunch manually.

**Comment by hluk** [comment]
Not sure what could be happening here.

I've just implemented better error reporting for global shortcuts, hope that could clear things up.

**Comment by hluk** [comment]
In CopyQ v3.3.0, there should now be now error reporting if a global shortcut fails to be mapped.

**Comment by RoadToDream** [comment]
I don't think it's a conflict...
Seems like it is not activated even if i have applied. Not sure what happened.
I'll try to reproduce that and to find what happened if possible.

**Comment by hluk** [comment]
Is there any error/warning in the log (F12 shortcut in main window)?

You can test mapping a global shortcut to `copyq popup TEST` which should show a popup when the command is run.

**Comment by RoadToDream** [comment]
No, there is nothing related to this bug in the log.
Seems that i must set it in the "Shortcuts tab", but cannot set it in the CopyQ commands window. Or it will not take affects. 
![copyq ortxln](https://user-images.githubusercontent.com/8088354/37901558-211a4ac2-3124-11e8-8fa0-03ffbcaca9f7.png)
Here is an image that after i have changed it in the  CopyQ commands window, but it still maintained in an unchecked state.

**Comment by RoadToDream** [comment]
Not sure what happened, will recover if i killall copyq and restart.

**Comment by hluk** [comment]
Can you test with CopyQ 3.3.1? (It contains [fix for some keyboard layouts](https://github.com/hluk/qxtglobalshortcut/pull/5), thanks to @myhlj.)
