### ISSUE TITLE
Automatic command no longer work

### ISSUE THREAD

**Issue by reagle** [hluk/CopyQ#886]
This problem seemed to start when I moved to 3.2, just like #884, but even after reverting to 3.1.2 my automatic command no longer works. Simply, it looks for a local file URL to a mindmap file (.mm) and opens it in freeplane. The command still works in terminal (MacOS Sierra).

<img width="866" alt="screen shot 2018-02-22 at 2 59 46 pm" src="https://user-images.githubusercontent.com/596814/36561215-18d26f86-17e1-11e8-8f36-f49798f44c8a.png">

**Comment by reagle** [comment]
Ah, this is because those items are no longer checked. Maybe they got unchecked in my move to 3.2 and then back to 3.1.2 ?

**Comment by hluk** [comment]
Not sure what happened but the update by itself shouldn't disable any commands.

**Comment by reagle** [comment]
Yes, weird.... I'll close.
