### ISSUE TITLE
<EMPTY> items showing in copy list with version 3.2.0

### ISSUE THREAD

**Issue by richlux** [hluk/CopyQ#887]
With the latest version, I'm getting items in the copy list with the text `<EMPTY>`.  When I click "Show Content...", the list is completely empty.

Rich

**Comment by hluk** [comment]
Maybe it's related to #876. I just commented on that issue. Do you use "Ignore items with no or single character" command?

**Comment by richlux** [comment]
I'm not using the "Ignore items with no or single character" command, but I am using a command you created for me to Ignore nulls because I was getting a lot of them.  Here's the command:

[Command]
Name=Ignore \"null\"
Match=^null$
Automatic=true
Remove=true
Icon=\xf06a

**Comment by hluk** [comment]
Should be fixed (https://github.com/hluk/CopyQ/commit/37c1791e10984b483490bbdcf80cee72bb34f382).
