### ISSUE TITLE
Publish the app to Microsoft Store

### ISSUE THREAD

**Issue by Kenya-West** [hluk/CopyQ#890]
Microsoft Store is one place for everything in your life, moving your experience to a safe one and making it accessible from many devices that added to your Microsoft account.

Publishing apps to Microsoft Store is benefit both for users and developers + enterprise. Deploying classic apps, that available in Microsoft Store, with safe methods to a verified environments is trusted by enterprises and users. From the other hand, developer can benefit from "In-App Purchase" (paid features of the app), making its own Insider programs, setting up subscriptions and advertisements.

Microsoft corporation has opened a door to developers of classic apps, the way to publish your app to Microsoft Store. UWP brings a second life for your apps: notifications, full power of trusted UWP/WinRT API, easy debug, easy deploy, additional features.

Learn more about that easy process [here](https://developer.microsoft.com/windows/bridges/desktop).

Best regards,
Innokenty Ivanov,
North-Eastern Federal University student (Master degree).
Programmer, web developer, **Microsoft Student Partner**.
My [e-mail](mailto:Kenya-West@outlook.com).

**Comment by hluk** [comment]
There already is task for this (#480).

It requires me to pay some registration fee - I don't want to bother with that now.

Your description reads like you're advertising Microsoft Store.

**Comment by Kenya-West** [comment]
> It requires me to pay some registration fee - I don't want to bother with that now.

Hint: If you are a student, you can get a free Microsoft Developer account, it accesses you to all Microsoft Store, Office Graph, Office 365 API, Microsoft Azure development, Hardware development (and drivers), and development of apps for Cortana and Skype.

**Comment by smaragdus** [comment]
@hluk 
It is none of my business but porting a great program like [CopyQ](https://hluk.github.io/CopyQ/) to UWP is a waste of time, efforts and money. CopyQ is for advanced users while Microsoft Store (a walled garden- more precisely- a walled swamp, full of slime) is for idiots. When I install Windows 8 one of my first job is to remove all 'Store Apps' trash.

**Comment by hluk** [comment]
@smaragdus Thanks for the support. :) I'm definitely not porting to UWP. I'd like for the app to run on as many platforms as possible.

Having Microsoft developer account would at least allow me to sign the app. Otherwise, installation welcomes you with annoying popup that app is unsigned and the button to continue installation is quite well hidden (the same happens on OS X). This is not a priority for me though.

**Comment by vatterspun** [comment]
So @smaragdus already pointed this out in a separate thread but Kenya-West just pastes this exact across [lots of github posts](https://github.com/NickeManarin/ScreenToGif/issues/292#issuecomment-375489673) so ... I don't know if it's exactly spam, but its close.
