### ISSUE TITLE
Not able to past http or https from clipboard

### ISSUE THREAD

**Issue by natashh** [hluk/CopyQ#893]
Anyone habe got a problem with pasting http or https text from the app ?

**Comment by natashh** [comment]
![image](https://user-images.githubusercontent.com/12864518/37228333-88dba8dc-23e0-11e8-98b0-d45405a683cc.png)

**Comment by natashh** [comment]
I see it when I enter is not pasting. What can be wrong?

**Comment by natashh** [comment]
I see the problem only in Chrome. When I am coping from Chrome pasting is not working, from Firefox it is ok.

**Comment by natashh** [comment]
The interesting thing is I am able to copy/paste uri in Chrome, but not able to copy it outside Chrome in example past to notepad.

**Comment by hluk** [comment]
I'm closing this as duplicate of #724. This will be probably fixed in next version.
