### ISSUE TITLE
copyq CLI copy entire file into clipboard Windows

### ISSUE THREAD

**Issue by mokanfar** [hluk/CopyQ#894]
First and foremost thank you very much for this wonderful script. 

I am using windows and I am testing now using CLI by adding copyq.exe to my environment path. 

I try to emulate the copying of a file in windows explorer by selecting it and pressing ctrl+c which shows in copyq GUI as "file:///C:/foo.txt". I press ctrl + v and it copies file into any dir I want it to through file explorer. but what is command to replicate copying entire file (not file contents) into your clipboard through the command line? 

Am I missing something? Documentation does not cover this, only through action dialog...

**Comment by hluk** [comment]
This depends on the file manager you use, it often stores extra data in clipboard (file information, default copy/move etc.).

Basic command could look like this:

```
copyq copy text/uri-list file:///C:/Documents/test.txt
```

But since there could be some extra data required by a file manager, this won't always work.

**Comment by mokanfar** [comment]
@hluk thank you very much, this is exactly what I was looking for.
