### ISSUE TITLE
Title for pinned items

### ISSUE THREAD

**Issue by dalvand** [hluk/CopyQ#897]
Is there any way to set a title for pinned items?

For example, I want to pin several items that each contains a long URL. It is hard to find the right URL when I want to use them unless I can set a title for each, e.g. URL1, URL2, etc. I sill need it to paste the content of URL1 when I enter on it (and not just the text "URL1").

BTW. CopyQ in fantastic piece of software. Keep it up. Thank you very much.

**Comment by hluk** [comment]
Use Shift+F2 to add notes.

You can also use [this command](https://github.com/hluk/copyq-commands/tree/master/Application#hideshow-item-content) to hide the URL. It could make the list bit cleaner.
