### ISSUE TITLE
Past as plain text - is not working

### ISSUE THREAD

**Issue by natashh** [hluk/CopyQ#898]
I am not able to use this function, I see this.
http://prntscr.com/iq8gsl

**Comment by wizangzing** [comment]
+1  Seen on macOS High Sierra 10.13.2 when plain text or rich text was on clipboard.  invoked function with ^V which is bound to "Paste clipboard as plain text" on the shortcuts preferences.  

In addition to the two black popups shown in the original bug report, I sometimes get a blank white window where the title is "<text from clipboard> - CopyQ".  The window has the standard decorations (close/minimize/maximize buttons).  Clicking on this window does not change what macOS considers the current app.  window is dismissed if I open the copyQ window.

**Comment by hluk** [comment]
Looks like culprit is [this commit](2c894df47a4ba6fa7e2753682f73b54757f16b5d). Unfortunately it's big one so it can take a while for me to find out what exactly is going on -- basically the control checksum for clipboard data doesn't get into the system clipboard on OS X (there are some suspicious errors in the log).

**Comment by hluk** [comment]
This should be fixed in new version.
