### ISSUE TITLE
"Unmet dependencies" error message

### ISSUE THREAD

**Issue by repsorp** [hluk/CopyQ#899]
CopyQ 3.3.0
Ubuntu 16.04

The following packages have unmet dependencies:
copyq : Depends: libqt5svg5 (>= 5.6.0~beta) but 5.5.1-2build1 is installed

Depends: libqt5core5a (>= 5.7.0) but 5.5.1+dfsg-16ubuntu7.5 is installed
Depends: libqt5gui5 (>= 5.7.0) but 5.5.1+dfsg-16ubuntu7.5 is installed
Depends: libqt5script5 (>= 5.6.0~beta) but 5.5.1+dfsg-2build1 is installed
Depends: libqt5widgets5 (>= 5.7.0) but 5.5.1+dfsg-16ubuntu7.5 is installed
E: Unmet dependencies. Try using -f.

**Comment by repsorp** [comment]
ooops... sorry, my mistake
works fine with copyq_3.3.0_Debian_8.0-1_amd64.deb

**Comment by hluk** [comment]
Did you install from [PPA](https://launchpad.net/~hluk/+archive/ubuntu/copyq)?

**Comment by repsorp** [comment]
nope, didn't even know there was a ppa for it...
Thanks
