### ISSUE TITLE
paste() doesn't paste

### ISSUE THREAD

**Issue by belisama** [hluk/CopyQ#900]
I installed CopyQ for the LIFO script, which is exactly what I want. For reference:

copyq: 
select(0)
paste()
remove(0)

However, the paste() part of it isn't working. It selects the last item and then deletes it, but never pastes it into the waiting application (Geany text editor). Normal cntl-v pasting works fine. I'm running Linux Mint 18.3 Cinnamon

**Comment by hluk** [comment]
Works nicely for me in clean installation of Geany.

By default, CopyQ sends <kbd>Shift</kbd>+<kbd>Insert</kbd> to paste.

Do you use any plugin or key binding that could interfere?

**Comment by persicathepeachtree** [comment]
During today's testing, it worked intermittently. It would paste for two or three attempts and then stop for several more.

Shift+insert worked fine in multiple applications.

In addition to Geany 1.27, I also tested in LibreOffice 5.4.5.1 and Firefox 58.0.2 with the same results.

I reviewed Cinnamon's key-bindings (I'm only using the default ones), but couldn't find anything for cntl-meta-v.

I have one other custom command in CopyQ (a password vault filter). Disabling it had no affect.

I'm not sure how useful copyq.log would be (it includes nothing from today's testing, for instance), but I went ahead and posted it at https://pastebin.com/axF2X16W just in case.

**Comment by belisama** [comment]
During today's testing, it worked intermittently. It would paste for two or three attempts and then stop for several more.

Shift+insert worked fine in multiple applications.

In addition to Geany 1.27, I also tested in LibreOffice 5.4.5.1 and Firefox 58.0.2 with the same results.

I reviewed Cinnamon's key-bindings (I'm only using the default ones), but couldn't find anything for cntl-meta-v.

I have one other custom command in CopyQ (a password vault filter). Disabling it had no affect.

I'm not sure how useful copyq.log would be (it includes nothing from today's testing, for instance), but I went ahead and posted it at https://pastebin.com/axF2X16W just in case.

**Comment by hluk** [comment]
Did you try it with CopyQ 3.3.0?

One note: CopyQ sends the paste shortcut to currently focused window only after all keyboard modifiers (Shift, Ctrl etc.) are released (it's a workaround for some issues).

**Comment by belisama** [comment]
Okay, it's the key release issue. It's too bad the script continues after a step fails to execute, as that's going to be a dealbreaker. I appreciate your help, though.

**Comment by hluk** [comment]
> Okay, it's the key release issue.

Just tried using `xdotool` to send the shortcut but, again, it looks it doesn't work if you're holding some keys.

If you know an utility that can do the pasting you can replace the builtin `paste()` function with following command (just change the `xdotool` and arguments).

```ini
[Command]
Command="
    paste = function() {
        execute('xdotool', 'key', 'shift+Insert')
    }"
Icon=\xf0ea
IsScript=true
Name=Use xdotool to paste
```

> It's too bad the script continues after a step fails to execute

The problem is that there no way to verify that the stuff was successfully pasted (with `copy()` it's at least possible to determine that clipboard changes).

**Comment by hluk** [comment]
Oh, here is command that works! (You need to install `xdotool`.)

```ini
[Command]
Command="
    paste = function() {
        var x = execute(
            'xdotool',
            'keyup', 'shift',
            'keyup', 'ctrl',
            'keyup', 'meta',
            'keyup', 'super',
            'key', 'shift+Insert')
        if (!x)
            throw 'Failed to run xdotool'
        if (x.stderr)
            throw 'Failed to run xdotool: ' + str(x.stderr)
    }"
Icon=\xf0ea
IsScript=true
Name=Use xdotool to paste
```
