### ISSUE TITLE
Change item order numbering to start with 1 instead of 0

### ISSUE THREAD

**Issue by Hicclub** [hluk/CopyQ#901]
I modified the "Copy Nth item" command script to automatically paste items using global shortcuts. I just find it a little illogical that the first item on the list is item 0...to paste the first item, I hit Ctrl+0, and the problem naturally cascades for the rest of the numbers (the second item is #1, third item is #2, etc).

Can this be changed so that the numbering starts with #1 instead of 0?

**Comment by hluk** [comment]
The reasoning for this is that items are indexed from zero in main window and menu so you can quickly check which item would be copied.
