### ISSUE TITLE
How can I move current selected item to the top, paste it and close copyq window

### ISSUE THREAD

**Issue by amosbird** [hluk/CopyQ#903]
Hi, this is a common workflow that I use everyday. How can I bind it to a key , say `Enter`? Thanks!

**Comment by hluk** [comment]
Actually, that should be the default action for <kbd>Enter</kbd> key.

All the configuration for this is in "History" config tab.

**Comment by amosbird** [comment]
ah..... It is due to a custom command that grabs the `enter` key . thanks!

**Comment by amosbird** [comment]
Oh, I remember why the command exists. It's because the default `Enter` isn't synchronous. The prior top item always gets pasted before the selected item becomes the top one.

**Comment by hluk** [comment]
> The prior top item always gets pasted before the selected item becomes the top one.

This shouldn't be problem anymore. There is a code that verifies that a copy operation succeeded. Though, perhaps the target app still uses the old clipboard content for some reason.

Did you try this in CopyQ 3.3.0? Is there an bug report for this?

**Comment by amosbird** [comment]
Hmm, right. All terminal emulators (urxvt, termite and alacritty) seem to use the old clipboard content. I'm using `CopyQ Clipboard Manager v3.3.0-3-ga345e681 (hluk@email.cz)` and I don't find a bug report for this.

**Comment by hluk** [comment]
Wait a second! I think I'm verifying just the clipboard content, not X11 selection which is usually used by terminal emulator. I'll fix that.

**Comment by hluk** [comment]
Should be fixed now (57e6fa70f77897ec95c99685d7e7a8d1e811d686). I made a mistake which was quite hard to spot.

**Comment by amosbird** [comment]
great!

**Comment by amosbird** [comment]
Hmm, this is now even buggier.

**Comment by hluk** [comment]
I don't have any issues with pasting now.

Do you still have any command overriding <kbd>Enter</kbd> or <kbd>Return</kbd> keys?

What's your settings in "History" config tab?

**Comment by amosbird** [comment]
No, I don't have `Enter` key bound anymore. ![](https://la.wentropy.com/J8xW.png)

This is a bit hard to reproduce though. I'll try to find a consistent way to reproduce it.

**Comment by amosbird** [comment]
It's been something and I don't see this issue happening anymore. I suppose it's fixed somehow :)
