### ISSUE TITLE
Per-tab item limit

### ISSUE THREAD

**Issue by supersaiyansubtlety** [hluk/CopyQ#904]
Hello, 
I would like to see the ability to choose the maximum number of items stored configurable on a per-tab basis.
Also a question: is it possible to copy a file in such a way that it can be pasted on another computer using sync? I currently have sync working but copying files just copies the path which of course doesn't work across computers. I looked into command options and tried "type filename.ext | clip" but couldn't get it to work.

**Comment by hluk** [comment]
> I would like to see the ability to choose the maximum number of items stored configurable on a per-tab basis.

Sorry, probably won't happen, I don't see much use for it.

> is it possible to copy a file in such a way that it can be pasted on another computer using sync?

No sure what you mean. CopyQ is not a file manager.
