### ISSUE TITLE
I cannot launch CopyQ

### ISSUE THREAD

**Issue by clayto2** [hluk/CopyQ#907]
I have tried many times, downloading from different sources, but have not been able to launch. Clicking shortcut icons and even the exe file in the Folder has no effect except I often get a popup saying code execution cannot proceed as Qt5Core.dll not found --- even though that dll is listed in the downloaded Folder
![image](https://user-images.githubusercontent.com/37734167/37862711-66b8c676-2f49-11e8-8c4c-da28b50abf3b.png)
![image](https://user-images.githubusercontent.com/37734167/37862741-defbbc6a-2f49-11e8-8406-8597b6fd13e7.png)

**Comment by hluk** [comment]
Looks like some issue with portable archive.

**Comment by hluk** [comment]
Looks like there were some permission issues when extracting the zip in some temporary "download" folder. Extracting or moving the extracted folder to some other place fixed the issue for me.

Can you check it that works for you too?

**Comment by bawldiggle** [comment]
Extracted to external USB, ran copyq.exe from the USB stick.
No solution, exactly the same alerts as in post #1
:( :(
