### ISSUE TITLE
The package for ArchLinux was updated from v3.1.2 to v3.3.0 and now the application crashes on copy action

### ISSUE THREAD

**Issue by glowingsword** [hluk/CopyQ#909]
```bash
copyq -v
CopyQ Clipboard Manager v3.3.0 (hluk@email.cz)
Built with: Qt 5.10.1, LibQxt 0.7.0
```
```bash
COPYQ_LOG_LEVEL=trace copyq
TRACE: Created session mutex: copyq_mutex
DEBUG: Server "/home/glowingsword/.config/copyq/.copyq_s" started.
DEBUG: Geometry: Window "ProcessManagerDialog": New geometry for "Options/ProcessManagerDialog_geometry_1920x1080"
DEBUG: Geometry: Window "MainWindow": New geometry for "Options/MainWindow_geometry_1920x1080"
TRACE: Loading plugin: /usr/lib/copyq/plugins/libitemdata.so
TRACE: Loading plugin: /usr/lib/copyq/plugins/libitemencrypted.so
TRACE: Loading plugin: /usr/lib/copyq/plugins/libitemfakevim.so
TRACE: Loading plugin: /usr/lib/copyq/plugins/libitemimage.so
TRACE: Loading plugin: /usr/lib/copyq/plugins/libitemnotes.so
TRACE: Loading plugin: /usr/lib/copyq/plugins/libitempinned.so
TRACE: Loading plugin: /usr/lib/copyq/plugins/libitemsync.so
TRACE: Loading plugin: /usr/lib/copyq/plugins/libitemtags.so
TRACE: Loading plugin: /usr/lib/copyq/plugins/libitemtext.so
TRACE: Loading plugin: /usr/lib/copyq/plugins/libitemweb.so
DEBUG: Loading configuration
DEBUG: Tab "&clipboard": Loading items
DEBUG: Tab "&clipboard": 0 items loaded
DEBUG: Configuration loaded
DEBUG: Starting monitor
DEBUG: Executing: copyq monitorClipboard
DEBUG: Got save state request from session manager.
TRACE: Socket 1: Creating socket.
TRACE: Socket 1: Sending message to client (exit code: 9).
TRACE: Write message (13 bytes).
TRACE: Message written.
TRACE: Socket 1: Message sent to client.
TRACE: Socket 1: Sending message to client (exit code: 9).
TRACE: Write message (34 bytes).
TRACE: Message written.
TRACE: Socket 1: Message sent to client.
TRACE: Socket 1: Sending message to client (exit code: 9).
TRACE: Write message (13 bytes).
TRACE: Message written.
TRACE: Socket 1: Message sent to client.
TRACE: Socket 1: Sending message to client (exit code: 9).
TRACE: Write message (34 bytes).
TRACE: Message written.
TRACE: Socket 1: Message sent to client.
TRACE: Getting clipboard data.
TRACE: Got clipboard data.
DEBUG: Executing: copyq provideClipboard
TRACE: Getting clipboard data.
TRACE: Got clipboard data.
TRACE: Socket 2: Creating socket.
TRACE: Socket 2: Sending message to client (exit code: 9).
TRACE: Write message (124 bytes).
TRACE: Message written.
TRACE: Socket 2: Message sent to client.
TRACE: Socket 2: Sending message to client (exit code: 9).
TRACE: Write message (34 bytes).
TRACE: Message written.
TRACE: Socket 2: Message sent to client.
TRACE: Socket 1: Sending message to client (exit code: 9).
TRACE: Write message (13 bytes).
TRACE: Message written.
TRACE: Socket 1: Message sent to client.
TRACE: Getting clipboard data.
TRACE: Got clipboard data.
TRACE: Skipping format: text/plain
TRACE: Skipping format: application/x-copyq-owner
TRACE: Skipping format: TARGETS
TRACE: Skipping format: MULTIPLE
TRACE: Skipping format: TIMESTAMP
TRACE: Skipping format: SAVE_TARGETS
TRACE: Socket 1: Sending message to client (exit code: 9).
TRACE: Write message (23 bytes).
TRACE: Message written.
TRACE: Socket 1: Message sent to client.
TRACE: Socket 1: Sending message to client (exit code: 9).
TRACE: Write message (13 bytes).
TRACE: Message written.
TRACE: Socket 1: Message sent to client.
TRACE: Socket 1: Sending message to client (exit code: 9).
TRACE: Write message (13 bytes).
TRACE: Message written.
TRACE: Socket 1: Message sent to client.
TRACE: Socket 1: Sending message to client (exit code: 9).
TRACE: Write message (13 bytes).
TRACE: Message written.
TRACE: Socket 1: Message sent to client.
TRACE: Socket 1: Sending message to client (exit code: 9).
TRACE: Write message (13 bytes).
TRACE: Message written.
TRACE: Socket 1: Message sent to client.
TRACE: Socket 2: Disconnected from client.
TRACE: Socket 2: Destroying socket.
TRACE: Socket 2: Disconnecting socket.
TRACE: Socket 1: Sending message to client (exit code: 9).
TRACE: Write message (13 bytes).
TRACE: Message written.
TRACE: Socket 1: Message sent to client.
TRACE: Socket 1: Sending message to client (exit code: 9).
TRACE: Write message (34 bytes).
TRACE: Message written.
TRACE: Socket 1: Message sent to client.
TRACE: Getting clipboard data.
TRACE: Got clipboard data.
DEBUG: Executing: copyq provideSelection
TRACE: Getting selection data.
TRACE: Got selection data.
TRACE: Socket 3: Creating socket.
TRACE: Socket 3: Sending message to client (exit code: 9).
TRACE: Write message (736 bytes).
TRACE: Message written.
TRACE: Socket 3: Message sent to client.
TRACE: Socket 3: Sending message to client (exit code: 9).
TRACE: Write message (34 bytes).
TRACE: Message written.
TRACE: Socket 3: Message sent to client.
TRACE: Socket 1: Sending message to client (exit code: 9).
TRACE: Write message (13 bytes).
TRACE: Message written.
TRACE: Socket 1: Message sent to client.
TRACE: Getting selection data.
TRACE: Got selection data.
TRACE: Skipping format: text/html
TRACE: Skipping format: text/plain
TRACE: Skipping format: application/x-copyq-owner
TRACE: Skipping format: TARGETS
TRACE: Skipping format: MULTIPLE
TRACE: Skipping format: TIMESTAMP
TRACE: Skipping format: SAVE_TARGETS
TRACE: Socket 1: Sending message to client (exit code: 9).
TRACE: Write message (22 bytes).
TRACE: Message written.
TRACE: Socket 1: Message sent to client.
DEBUG: New item: Adding
TRACE: Socket 1: Sending message to client (exit code: 9).
TRACE: Write message (13 bytes).
TRACE: Message written.
TRACE: Socket 1: Message sent to client.
Segmentation fault (core dumped)
```
In strace crashed on 
```bash
write(26, "\0\0\0\"\0\0\0\t\0\0\4\0\0\0\0\0\21QVector<Command>\0\0\0\0\0", 38) = 38
write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
recvmsg(6, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(6, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=5, events=POLLIN}, {fd=6, events=POLLIN}, {fd=7, events=POLLIN}, {fd=12, events=POLLIN}, {fd=15, events=POLLIN}, {fd=17, events=POLLIN}, {fd=18, events=POLLIN}, {fd=26, events=POLLIN}, {fd=32, events=POLLIN}], 9, 8884) = 2 ([{fd=5, revents=POLLIN}, {fd=26, revents=POLLIN}])
read(5, "\1\0\0\0\0\0\0\0", 16)         = 8
ioctl(26, FIONREAD, [154])              = 0
read(26, "\0\0\0\226\0\0\0\10\0\0\0\7\0\0\0\n\0\377\377\377\377\0\0\0\f\0\0\0\0\10saveData\0\0\0\2\0\377\377\377\377\0\0\0\1\0\0\0\0\0\n\0\0\0\0\24\0&\0c\0l\0i\0p\0b\0o\0a\0r\0d\0\0\0\1\0\0\0\0\0\10\0\0\0\0\1\0\0\0\24\0t\0e\0x\0t\0/\0p\0l\0a\0i\0n\0\0\0\f\0\0\0\0\30GNOME_DESKTOP_SESSION_ID", 154) = 154
write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
recvmsg(6, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(6, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=5, events=POLLIN}, {fd=6, events=POLLIN}, {fd=7, events=POLLIN}, {fd=12, events=POLLIN}, {fd=15, events=POLLIN}, {fd=17, events=POLLIN}, {fd=18, events=POLLIN}, {fd=26, events=POLLIN|POLLOUT}, {fd=32, events=POLLIN}], 9, 0) = 2 ([{fd=5, revents=POLLIN}, {fd=26, revents=POLLOUT}])
read(5, "\1\0\0\0\0\0\0\0", 16)         = 8
write(26, "\0\0\0\r\0\0\0\t\0\0\0\2\0\377\377\377\377", 17) = 17
write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0xa00000097} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)
```
But then I build the 3.1.2 version of copyq(with same version of Qt and other dependencies) and install it back - it works like at charm.

**Comment by glowingsword** [comment]
Also 

coredumpctl dump --reverse copyq
           PID: 24974 (copyq)
           UID: 1001 (glowingsword)
           GID: 1001 (glowingsword)
        Signal: 11 (SEGV)
     Timestamp: Sat 2018-03-24 15:10:46 EET (2min 9s ago)
  Command Line: copyq
    Executable: /usr/bin/copyq
 Control Group: /user.slice/user-1001.slice/session-c2.scope
          Unit: session-c2.scope
         Slice: user-1001.slice
       Session: c2
     Owner UID: 1001 (glowingsword)
       Boot ID: 77712a08686c4f23a58bc347d96d4920
    Machine ID: e41fabb7773e4d129c06a5b92b051239
      Hostname: arch
       Storage: /var/lib/systemd/coredump/core.copyq.1001.77712a08686c4f23a58bc347d96d4920.24974.1521897046000000.lz4
       Message: Process 24974 (copyq) of user 1001 dumped core.
                
                Stack trace of thread 24974:
                #0  0x00007fa3be871f9d _ZNK13ItemWebLoader6createERK11QModelIndexP7QWidgetb (libitemweb.so)
                #1  0x000055774893f2d6 _ZN11ItemFactory10createItemERKSt10shared_ptrI19ItemLoaderInterfaceERK4QMapI7QString8QVariantEP7QWidgetbbb (copyq)
                #2  0x000055774893f9ba _ZN11ItemFactory10createItemERK4QMapI7QString8QVariantEP7QWidgetbbb (copyq)
                #3  0x0000557748933184 _ZN12ItemDelegate11updateCacheERK11QModelIndexRK4QMapI7QString8QVariantE (copyq)
                #4  0x00005577489321fe _ZN12ItemDelegate5cacheERK11QModelIndex (copyq)
                #5  0x0000557748932b22 _ZN12ItemDelegate20setItemWidgetCurrentERK11QModelIndexb (copyq)
                #6  0x000055774885283b _ZN16ClipboardBrowser13updateCurrentEv (copyq)
                #7  0x00007fa3dc055616 _ZN11QMetaObject8activateEP7QObjectiiPPv (libQt5Core.so.5)
                #8  0x00007fa3dc062508 _ZN6QTimer7timeoutENS_14QPrivateSignalE (libQt5Core.so.5)
                #9  0x00007fa3dc062879 _ZN6QTimer10timerEventEP11QTimerEvent (libQt5Core.so.5)
                #10 0x00007fa3dc05601b _ZN7QObject5eventEP6QEvent (libQt5Core.so.5)
                #11 0x00007fa3dcda2fec _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
                #12 0x00007fa3dcdaa9c6 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
                #13 0x000055774898c61a _ZThn16_N27ApplicationExceptionHandlerI12QApplicationE6notifyEP7QObjectP6QEvent (copyq)
                #14 0x00007fa3dc024cf0 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
                #15 0x00007fa3dc080688 _ZN14QTimerInfoList14activateTimersEv (libQt5Core.so.5)
                #16 0x00007fa3dc080e82 n/a (libQt5Core.so.5)
                #17 0x00007fa3d83d2458 g_main_context_dispatch (libglib-2.0.so.0)
                #18 0x00007fa3d83d26a1 n/a (libglib-2.0.so.0)
                #19 0x00007fa3d83d272e g_main_context_iteration (libglib-2.0.so.0)
                #20 0x00007fa3dc081241 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                #21 0x00007fa3d428a482 n/a (libQt5XcbQpa.so.5)
                #22 0x00007fa3dc02332b _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                #23 0x00007fa3dc02c728 _ZN16QCoreApplication4execEv (libQt5Core.so.5)
                #24 0x00005577487fd556 main (copyq)
                #25 0x00007fa3db107f4a __libc_start_main (libc.so.6)
                #26 0x00005577487fdcba _start (copyq)
                
                Stack trace of thread 24977:
                #0  0x00007fa3db1d297b __poll (libc.so.6)
                #1  0x00007fa3d9f8b180 n/a (libxcb.so.1)
                #2  0x00007fa3d9f8ce4b xcb_wait_for_event (libxcb.so.1)
                #3  0x00007fa3d420282a n/a (libQt5XcbQpa.so.5)
                #4  0x00007fa3dbe37acd n/a (libQt5Core.so.5)
                #5  0x00007fa3daed008c start_thread (libpthread.so.0)
                #6  0x00007fa3db1dce7f __clone (libc.so.6)
                
                Stack trace of thread 24988:
                #0  0x00007fa3daed63bd pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00007fa3dbab45bd __gthread_cond_wait (libstdc++.so.6)
                #2  0x00007fa3b350cd09 n/a (libQt5WebKit.so.5)
                #3  0x00007fa3b350ce59 n/a (libQt5WebKit.so.5)
                #4  0x00007fa3dbabab9f execute_native_thread_routine (libstdc++.so.6)
                #5  0x00007fa3daed008c start_thread (libpthread.so.0)
                #6  0x00007fa3db1dce7f __clone (libc.so.6)
                
                Stack trace of thread 24982:
                #0  0x00007fa3db1d297b __poll (libc.so.6)
                #1  0x00007fa3d83d2613 n/a (libglib-2.0.so.0)
                #2  0x00007fa3d83d272e g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007fa3dc081241 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                #4  0x00007fa3dc02332b _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                #5  0x00007fa3dbe3272e _ZN7QThread4execEv (libQt5Core.so.5)
                #6  0x00007fa3d3d0c416 n/a (libQt5DBus.so.5)
                #7  0x00007fa3dbe37acd n/a (libQt5Core.so.5)
                #8  0x00007fa3daed008c start_thread (libpthread.so.0)
                #9  0x00007fa3db1dce7f __clone (libc.so.6)
                
                Stack trace of thread 24992:
                #0  0x00007fa3daed63bd pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00007fa3acd398ec n/a (radeonsi_dri.so)
                #2  0x00007fa3acd397f8 n/a (radeonsi_dri.so)
                #3  0x00007fa3daed008c start_thread (libpthread.so.0)
                #4  0x00007fa3db1dce7f __clone (libc.so.6)
                
                Stack trace of thread 24993:
                #0  0x00007fa3daed63bd pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00007fa3acd398ec n/a (radeonsi_dri.so)
                #2  0x00007fa3acd397f8 n/a (radeonsi_dri.so)
                #3  0x00007fa3daed008c start_thread (libpthread.so.0)
                #4  0x00007fa3db1dce7f __clone (libc.so.6)
                
                Stack trace of thread 24994:
                #0  0x00007fa3daed63bd pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00007fa3acd398ec n/a (radeonsi_dri.so)
                #2  0x00007fa3acd397f8 n/a (radeonsi_dri.so)
                #3  0x00007fa3daed008c start_thread (libpthread.so.0)
                #4  0x00007fa3db1dce7f __clone (libc.so.6)
                
                Stack trace of thread 24995:
                #0  0x00007fa3daed63bd pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00007fa3acd398ec n/a (radeonsi_dri.so)
                #2  0x00007fa3acd397f8 n/a (radeonsi_dri.so)
                #3  0x00007fa3daed008c start_thread (libpthread.so.0)
                #4  0x00007fa3db1dce7f __clone (libc.so.6)
                
                Stack trace of thread 24989:
                #0  0x00007fa3daed63bd pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00007fa3acd398ec n/a (radeonsi_dri.so)
                #2  0x00007fa3acd397f8 n/a (radeonsi_dri.so)
                #3  0x00007fa3daed008c start_thread (libpthread.so.0)
                #4  0x00007fa3db1dce7f __clone (libc.so.6)
                
                Stack trace of thread 24978:
                #0  0x00007fa3db1d297b __poll (libc.so.6)
                #1  0x00007fa3d83d2613 n/a (libglib-2.0.so.0)
                #2  0x00007fa3d83d272e g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007fa3d83d2782 n/a (libglib-2.0.so.0)
                #4  0x00007fa3d83facea n/a (libglib-2.0.so.0)
                #5  0x00007fa3daed008c start_thread (libpthread.so.0)
                #6  0x00007fa3db1dce7f __clone (libc.so.6)
                
                Stack trace of thread 24979:
                #0  0x00007fa3db1d297b __poll (libc.so.6)
                #1  0x00007fa3d83d2613 n/a (libglib-2.0.so.0)
                #2  0x00007fa3d83d29d2 g_main_loop_run (libglib-2.0.so.0)
                #3  0x00007fa3c9147b78 n/a (libgio-2.0.so.0)
                #4  0x00007fa3d83facea n/a (libglib-2.0.so.0)
                #5  0x00007fa3daed008c start_thread (libpthread.so.0)
                #6  0x00007fa3db1dce7f __clone (libc.so.6)
                
                Stack trace of thread 24991:
                #0  0x00007fa3daed63bd pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00007fa3acd398ec n/a (radeonsi_dri.so)
                #2  0x00007fa3acd397f8 n/a (radeonsi_dri.so)
                #3  0x00007fa3daed008c start_thread (libpthread.so.0)
                #4  0x00007fa3db1dce7f __clone (libc.so.6)
                
                Stack trace of thread 24990:
                #0  0x00007fa3daed63bd pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00007fa3acd398ec n/a (radeonsi_dri.so)
                #2  0x00007fa3acd397f8 n/a (radeonsi_dri.so)
                #3  0x00007fa3daed008c start_thread (libpthread.so.0)
                #4  0x00007fa3db1dce7f __clone (libc.so.6)
Refusing to dump core to tty (use shell redirection or specify --output).

ldd "$(which copyq)"
	linux-vdso.so.1 (0x00007ffe7bdd3000)
	libQt5Network.so.5 => /usr/lib/libQt5Network.so.5 (0x00007f8e0a37d000)
	libQt5Svg.so.5 => /usr/lib/libQt5Svg.so.5 (0x00007f8e0a128000)
	libQt5Script.so.5 => /usr/lib/libQt5Script.so.5 (0x00007f8e09c8d000)
	libXtst.so.6 => /usr/lib/libXtst.so.6 (0x00007f8e09a87000)
	libX11.so.6 => /usr/lib/libX11.so.6 (0x00007f8e09748000)
	libQt5Widgets.so.5 => /usr/lib/libQt5Widgets.so.5 (0x00007f8e08eee000)
	libQt5Gui.so.5 => /usr/lib/libQt5Gui.so.5 (0x00007f8e0872d000)
	libQt5Core.so.5 => /usr/lib/libQt5Core.so.5 (0x00007f8e08025000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f8e07c9e000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f8e07952000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f8e0773b000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f8e07384000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f8e0ac1f000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f8e07166000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007f8e06f4f000)
	libssl.so.1.1 => /usr/lib/libssl.so.1.1 (0x00007f8e06ce5000)
	libcrypto.so.1.1 => /usr/lib/libcrypto.so.1.1 (0x00007f8e06868000)
	libXext.so.6 => /usr/lib/libXext.so.6 (0x00007f8e06656000)
	libXi.so.6 => /usr/lib/libXi.so.6 (0x00007f8e06445000)
	libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007f8e0621c000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f8e06018000)
	libGL.so.1 => /usr/lib/libGL.so.1 (0x00007f8e05d8d000)
	libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007f8e05b57000)
	libharfbuzz.so.0 => /usr/lib/libharfbuzz.so.0 (0x00007f8e058a5000)
	libsystemd.so.0 => /usr/lib/libsystemd.so.0 (0x00007f8e0561e000)
	libicui18n.so.60 => /usr/lib/libicui18n.so.60 (0x00007f8e0517b000)
	libicuuc.so.60 => /usr/lib/libicuuc.so.60 (0x00007f8e04dc2000)
	libpcre2-16.so.0 => /usr/lib/libpcre2-16.so.0 (0x00007f8e04b4b000)
	libdouble-conversion.so.1 => /usr/lib/libdouble-conversion.so.1 (0x00007f8e0493b000)
	libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x00007f8e04623000)
	libXau.so.6 => /usr/lib/libXau.so.6 (0x00007f8e0441f000)
	libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007f8e04219000)
	libGLX.so.0 => /usr/lib/libGLX.so.0 (0x00007f8e03fe8000)
	libGLdispatch.so.0 => /usr/lib/libGLdispatch.so.0 (0x00007f8e03d32000)
	libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007f8e03a69000)
	libgraphite2.so.3 => /usr/lib/libgraphite2.so.3 (0x00007f8e0383d000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007f8e03635000)
	liblzma.so.5 => /usr/lib/liblzma.so.5 (0x00007f8e0340f000)
	liblz4.so.1 => /usr/lib/liblz4.so.1 (0x00007f8e031f8000)
	libgcrypt.so.20 => /usr/lib/libgcrypt.so.20 (0x00007f8e02edc000)
	libicudata.so.60 => /usr/lib/libicudata.so.60 (0x00007f8e01334000)
	libpcre.so.1 => /usr/lib/libpcre.so.1 (0x00007f8e010c1000)
	libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007f8e00eb1000)
	libgpg-error.so.0 => /usr/lib/libgpg-error.so.0 (0x00007f8e00c96000)

**Comment by hluk** [comment]
From backtrace, it looks like some problem with the Web plugin. I assume that it needs to be rebuilt because Qt version was updated.

Can you try reinstalling `copyq-plugin-itemweb` plugin?

**Comment by glowingsword** [comment]
I'm forgot at all about the copyq-plugin-itemweb. Now I update it, and all work good. Thank you very much for your time and your support!
