### ISSUE TITLE
Is it possible to use python3 instead of python(python2)?

### ISSUE THREAD

**Issue by nemonein** [hluk/CopyQ#911]
Hello.

I'm using the latest CopyQ on Kubuntu 17.10. I always thank you for your effort.

You mentioned before how to use python codes(Inline) in CopyQ Commands. (#325)
But it's python2.
I tried **python3:** instead of **python:** but it does not work.

Could there be a way to use inline Python3?

**Comment by hluk** [comment]
`python:` label basically means that `python -c <SCRIPT>` is executed.

You can use `python3 -c:` instead.

(Damn, `python` is still symlink to version 2 in modern distros.)

**Comment by nemonein** [comment]
Thanks!

**Comment by rps007** [comment]
Copyq is really a awesome tool. To use python scripts would make it even better. Unfortunately all my attempts to achieve this have failed so far. 

![Bild1](https://github.com/hluk/CopyQ/assets/86913096/12b178d2-54cd-4f1d-a4d7-fe8d15abcd41)

Can you help me?
