### ISSUE TITLE
CopyQ Autostart Preference Not Working

### ISSUE THREAD

**Issue by dpbaril** [hluk/CopyQ#912]
I am a Linux newbie with a new installation of Linux Mint 18.3 (Cinnamon) on a Dell XPS 8700.  I have installed CopyQ both from the Software Manager and the GitHub download site and encounter the same problem with both.  

In the preferences, I check "Autostart" and then click the Apply or OK buttons but when I re-open the Preference dialog the box is unchecked.  I look in the /.config/autostart/ directory and there is no file for CopyQ.  I've tried uninstalling, reinstalling, rebooting and many searches online for a solution but am unable to find anything.

I realize this may be more of a user support issue than a bug and would happily be redirected to an alternative venue to resolve the issue.

**Comment by dpbaril** [comment]
Doh!  Just found a help video (in German no less!) which explains how to add an app to Autostart.

Sorry for the thrash, although I do think the preference dialogue should work too.

**Comment by hluk** [comment]
Actually other people are having same problem. The "Autostart" option should work by adding the desktop file to `~/.config/autostart/`.

CC @edevil

**Comment by hluk** [comment]
I guess the problem could be that the `~/.config/autostart/` doesn't exist (CopyQ doesn't handle this case).

Also I need to add some error logging for this.

**Comment by dpbaril** [comment]
Once I configured CopyQ with _cinnamon-settings startup_ , it added an entry to ~/.config/autostart/ and CopyQ starts at boot as expected.  

Thanks for responding to this.

**Comment by hluk** [comment]
Will be fixed in next version. The problem was that the app was searching in wrong location for the installed desktop file.

In next version the app won't need the installed desktop file and there will be tests for the autostart feature so it's less likely this will break.

@dpbaril, @edevil, Thanks for the bug reports.
