### ISSUE TITLE
Cannot set shortcut [Mac OS latest]

### ISSUE THREAD

**Issue by Antisunny** [hluk/CopyQ#916]
Seems that `set shortcut` function doesn't work.

- IF there is no default shortcut for a action then you can not set a shortcut to the action anyhow.
- IF a short for a action is deleted, you'll have no way to set a new shortcut after.

**Comment by Antisunny** [comment]
Oh , I finally figure out how to add a shortcut

**Comment by hluk** [comment]
I can change the behavior if the current UI is confusing. Any suggestions? Maybe making the plus button for adding shortcut more visible?
