### ISSUE TITLE
tray menu "Clipboard" content indicator not updated correctly

### ISSUE THREAD

**Issue by araujorm** [hluk/CopyQ#917]
Hello.

When using the tray menu and selecting an existing item, the clipboard content indicator isn't updated (the one that starts with "Clipboard:" ), although the behaviour ends being as expected when you paste the item.

After pasting the item (that meanwhile is actually put in the clipboard), then clipboard indicator updated, but until you paste the item, and if you are only using the tray menu, you can't see what the current clipboard content is (in the main window things seem to work correctly).

Incidentally, other clipboard managers put in bold the current selected item on the tray and it would be nice if copyq also did that. But that's not exactly a problem if the "Clipboard:" indicator works. If anyway you prefer, I can open a separate feature request.

**Comment by hluk** [comment]
The items in tray menu are updated with delay (that's an optimization). I've fixed the "Clipboard:" item so it's updated immediately.

Highlighting the current clipboard item could be a good idea though it may not always work perfectly. I'll try to do something about that.

**Comment by hluk** [comment]
I'm adding an icon to a menu item which is in clipboard (specifically when item text is same as clipboard text - so this won't work for images).
