### ISSUE TITLE
CopyQ Server crash on fully updated ArchLinux

### ISSUE THREAD

**Issue by MRuecker** [hluk/CopyQ#918]
CopyQ always crashes now after updating Arch always when clicking on the tray icon.
When I start manually on command line it crashes too and gives me the following error message:
**Gdk-Message: 09:49:41.689: copyq: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.**

I have this problem on 2 different machines (both Arch) but not on 3rd one...

**Comment by hluk** [comment]
This is probably one of these issues:
- #906
- #909 - note that [copyq-plugin-itemweb](https://aur.archlinux.org/packages/copyq-plugin-itemweb/) AUR package is still out-of-date - better to just remove it for now

**Comment by MRuecker** [comment]
Thanks for the reply.  #906 did solve the problem for me as both machines where it crashes have a 4k display. 
The non crashing machine is a laptop with a 2k display
