### ISSUE TITLE
Wrong Icons in Tabs Menu.

### ISSUE THREAD

**Issue by nemonein** [hluk/CopyQ#922]
CopyQ 3.3.1 on Kubuntu 17.10.
The icons in Tabs menu looks weird.
Please look at the screen shots.

**3.3.0**
![copy-330](https://user-images.githubusercontent.com/5688288/38450560-f7cf93a8-3a5a-11e8-955e-60ef09ea2180.jpg)

**3.3.1**
![copyq-331](https://user-images.githubusercontent.com/5688288/38450565-01ef3532-3a5b-11e8-82fd-f25d906a0ee9.jpg)

**Comment by hluk** [comment]
Haven't noticed this, possibly due to using different version of Qt where the icons are correctly scaled.

This will be fixed in next release.

**Comment by nemonein** [comment]
Thanks!
