### ISSUE TITLE
Application window flashes to show but then disappears

### ISSUE THREAD

**Issue by gbarnabic** [hluk/CopyQ#923]
V. 3.3.1 on Macbook OS 10.13.4.  Installed fine and worked for a few min.  

Now when I try to Show/Hide the application flashed up on the screen then disappears.  I can bring up the preferences dialog and navigate that without issue.  I have reset the preferences.  If I set the preferences to Always on Top and un-check Close when unfocused it will works.

I think the issue is that when I select the top tray icon and select Show/Hide it does not set focus to the dialog when it opens it. So it shows for moment then closes because it doesn't have focus.

**Comment by hluk** [comment]
Thanks for the bug report and workaround description.

The behavior was broken with commit 34317cb3938b3b7d0493308d9614dc2413c15ff5. I will probably remove the code altogether if there are still issues with it.
