### ISSUE TITLE
Add monochrome tray icon

### ISSUE THREAD

**Issue by Ygarr** [hluk/CopyQ#924]
Add ability to choose monochrome tray icon for convenience and universal for any icons and DE theme

**Comment by hluk** [comment]
The icon can be overridden using different icon theme. I think at least one theme overrides the icon with monochrome one - though I don't remember which one.

The icons are installed by default under `/usr/share/icons/hicolor/`.

**Comment by hluk** [comment]
You can also change the color of the default icon with `COPYQ_SESSION_COLOR` environment variable or a command.

Start with different icon color:
```bash
COPYQ_SESSION_COLOR=white copyq
```

Change the icon color while the app is running:
```bash
copyq iconColor white
```

**Comment by Gitoffthelawn** [comment]
@hluk wrote:

> The icon can be overridden using different icon theme. I think at least one theme overrides the icon with monochrome one - though I don't remember which one.
>
> The icons are installed by default under /usr/share/icons/hicolor/

Hi! How does one set up an icon theme?  Also, where are the icons now located (I'm not seeing that folder)?

**Comment by hluk** [comment]
> Hi! How does one set up an icon theme?

That depends on desktop environment, usually in preferences.

> Also, where are the icons now located (I'm not seeing that folder)?

They are usually in "/usr/share/icons/hicolor/" but it could be different on some systems.

Try searching for the icons with following command:

```
find /usr/share/icons/ -name '*copyq*'
```

Anyway, you can now set icon color on app start with following command ([here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)):

```ini
[Command]
Command="
    var onStart_ = global.onStart;
    global.onStart = function() {
        iconColor('white');
        onStart_();
    }"
Icon=\xf53f
IsScript=true
Name=Set Icon Color
```

**Comment by Gitoffthelawn** [comment]
@hluk Thanks! What colors can be used for `iconColor()`?  I tried some HTML colornames and they worked, but I tried rgb() colors and they did not.

**Comment by hluk** [comment]
What colors can be used for `iconColor()`? I tried some HTML colornames and they worked, but I tried rgb() colors and they did not.

Values for `iconColor()` are strings. RGB codes are prefixed with `#`.

Examples: 'orange', '#ffa500', '#09f'

(I've updated the API documentation.)

**Comment by Gitoffthelawn** [comment]
@hluk Thanks!  Is there a way to specify RGB values also as decimals, such as `rgb(255, 255, 0)`?

**Comment by hluk** [comment]
`rgb(...)` is not supported by `iconColor()`.

**Comment by Gitoffthelawn** [comment]
@hluk Thank you. That would explain why I couldn't get it to work! :)

**Comment by emrahoruc** [comment]
I change the command from Startup Applications. 

`sh -c "copyq & copyq iconColor white"`
