### ISSUE TITLE
Clicking on copyq tray icon results in crash - KDE plasma wayland

### ISSUE THREAD

**Issue by FedericoYundt** [hluk/CopyQ#926]
Hello, clicking on copyq tray icon results in crash - often together with whole plasmashell. It works ok with Xorg session.

```
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  3 (X_GetWindowAttributes)
  Resource id in failed request:  0x1
  Serial number of failed request:  8
  Current serial number in output stream:  9
```

```
copyq -v
CopyQ Clipboard Manager v3.3.1
Built with: Qt 5.10.1
```

```
plasmashell -v
plasmashell 5.12.4
```

Tested on Archlinux

**Comment by FedericoYundt** [comment]
This is caused by lack of QtWayland support in copyq combined with `QT_QPA_PLATFORM=wayland` environment variable set by default in KDE plasma session which forces QT apps to use wayland backend. Unsetting it fixes problem.

That variable would be probably [removed](https://phabricator.kde.org/T8077) in next KDE plasma release allowing fallback to X11. Supporting  QtWayland would be a better solution but I don't know if it's planned.

**Comment by hluk** [comment]
I'm fixing the issue.

Since Wayland is supported by Qt, the app should work fine except few features won't be available (global shortcuts, pasting and copying to/from other apps, getting window title).

The Wayland support is tracked by #27.
