### ISSUE TITLE
Show/Hide disappear - CopyQ 3.3.1

### ISSUE THREAD

**Issue by sojuzpl** [hluk/CopyQ#929]
When I try to open Show/Hide from the menu bar window is displayed and quickly disappear. No way to open this window.

CopyQ 3.3.1., macOS HighSierra

**Comment by LeshaRB** [comment]
I also have such problem on mac...
And toolbar in main window without icons..

Later try on Linux

**Comment by hluk** [comment]
This will be fixed in next version (see #923).

For now you can disable the option that closes window when it's unfocused/deactivated:

```
copyq config close_on_unfocus false
```
