### ISSUE TITLE
Double paste when pressing ENTER twice

### ISSUE THREAD

**Issue by raqua** [hluk/CopyQ#930]
Hi. 

I am on Arch Linux and since upgrading to 3.3.x from 3.1.2 copyq became much slower. At least in my default use case, which is open, select (window closes and paste happens) and then enter, to execute the command. I usually press just pressed enter twice, the first one selected the item, second one executed the pasted command. 
When I do that in new version, I get command pasted twice. Please remove this, once command is selected, window should close and not interpret additional enter as second paste selection.

Thanks.

**Comment by hluk** [comment]
> I usually press just pressed enter twice, the first one selected the item, second one executed the pasted command.

Not sure what do you mean by this.

Can you share your configuration (`~/.config/copyq/copyq.conf`)?

**Comment by raqua** [comment]
> Not sure what do you mean by this.

Sorry, I was not clear enough. I am pasting commands to linux terminal. So the first enter selects and pastes the command to my terminal and the second one executes the pasted command. 
I get double paste instead in 3.3.x versions unless I deliberately wait. I do not have to wait too long, but just long enough for it to be seriously slowing me down. And I of course keep forgetting to do so, so I am always double pasting. :/
Configs attached. 
[copyq.conf.zip](https://github.com/hluk/CopyQ/files/1935943/copyq.conf.zip)

**Comment by hluk** [comment]
Thanks for the description.

Looks like while setting clipboard, the target window can be focused (both operations take few milliseconds to finish). This feels much snappier.

**Comment by hluk** [comment]
I'll try to add some timeout so this doesn't happen.

I'm still trying to improve performance because it degraded with recent changes.
