### ISSUE TITLE
URLs included when ignore items with no or single character in CopyQ Commands

### ISSUE THREAD

**Issue by excetara2** [hluk/CopyQ#936]
I want to use this but I can't figure out how to not get it to ignore copied urls. Basically, I just want it to ignore white space or single characters with white space around them. Also, urls are included in this but I can't figure out why. Now I move them to a new tab but would prefer to just remove these items if I could get it working properly.
This was the regex used but I've also tried some other variations with no luck:
`^\s*\S?\s*$`

**Comment by hluk** [comment]
You can try "Ignore copied files" predefined command or modify "Copy URL (web address) to other tab" (clear "Copy to tab" and check "Remove item" instead).

**Comment by excetara2** [comment]
Okay used both of those and got it working just fine. It copies the url over and ignores white space. Thanks.
