### ISSUE TITLE
[Usage]: Shortcut to call menu

### ISSUE THREAD

**Issue by elcolie** [hluk/CopyQ#938]
Thanks to all the men behind the great application. Especially it is an opensource!
```
OSX: 10.13.5
CopyQ Clipboard Manager v3.4.0 (hluk@email.cz)
Built with: Qt 5.10.1
```

Each time I would like to use menu. I have to type `copyq menu` and then select the item from list in the clipboard

**Questions:**
1. How do I define a shortcut to run `copyq menu` in OSX? I had tried automation but it raises command not found
1. When the `menu` does come up. How can I define short cut to hit the item without moving the cursor by arrow keys?

**Comment by hluk** [comment]
> How do I define a shortcut to run copyq menu in OSX? I had tried automation but it raises command not found

Looks like `copyq` is not found in directories listed in `PATH`. Did you install CopyQ using `brew`?

This shouldn't be an issue when launching the command from CopyQ. There is already a predefined command for opening menu and the shortcut can be set in Shortcuts tab in Preferences.

![image](https://user-images.githubusercontent.com/38054/39670438-93c536a8-5105-11e8-8e79-3fc3eb6f47d8.png)

Alternatively, you can define global shortcut for custom command in Command dialog in CopyQ.

> When the menu does come up. How can I define short cut to hit the item without moving the cursor by arrow keys?

You can press a number keys to activate items. Custom shortcuts would work only from main window -- you'll have to use `copyq show` ("Show/hide main window" shortcut) instead and define new shortcut command to activate items.

**Comment by elcolie** [comment]
@hluk Thank you very much for example of the shortcut it works! 
Yes I installed from `brew cask install copyq`
My menu try shortcut is blank. It works when I set `Ctrl+Shift+@` to it
And I add my own `Ctrl+Shift+!`

<img width="660" alt="image" src="https://user-images.githubusercontent.com/18206728/39671006-aa6cebaa-513a-11e8-8dff-1c05108b756f.png">
