### ISSUE TITLE
Moving settings from one computer to another 

### ISSUE THREAD

**Issue by richlux** [hluk/CopyQ#940]
I'm trying to move my settings from one computer to another, but I'm not having any success. I have used the export feature to create a copyq.cpq file, but when I import it, it only shows me the first tab to import. When I exported it, I selected all and looking at the export file with a hex editor, I see all the tabs in there. I also looked in the registry, but I don't see a copyq folder under hkey_local_user/software. On the old computer, I see a "config" folder with a bunch of .ini files under the copyq program folder, but this folder doesn't exist on the new computer. Any idea how I can get my configuration to the new computer? I just want my tabs and commands. 

Rich

**Comment by hluk** [comment]
> I also looked in the registry, but I don't see a copyq folder under hkey_local_user/software.

Registry are no longer used in CopyQ on Windows.

> I see a "config" folder with a bunch of .ini files under the copyq program folder

The config folder is part of portable (unzipped) version, installed program should have all configuration under `%APPDATA%\copyq`. See [Backup](http://copyq.readthedocs.io/en/latest/backup.html) in documentation.

> I have used the export feature to create a copyq.cpq file, but when I import it, it only shows me the first tab to import.

Make sure you use same versions of the app to export and import (even though this shouldn't matter) and select all tabs (by default only the first tab is selected). Can you also see any errors/warnings in log?

**Comment by smaragdus** [comment]
I  think that the portable version is preferable since it is easier to backup and move from one computer to another one. Also, the portable version can be used from external drives with all program data and settings.

**Comment by richlux** [comment]
I've tried with the same version, but I'm not having any luck.  When I do the import, I only see the one tab (Clipboard). The .cpq file appears to have all the tabs in it, but it's a binary file, so I don't know for sure what is in it.  I'm not going to worry about it because I can recreate the tabs, but I had a bunch of commands that are now lost.  Oh well, I can rewrite those also.

Rich

**Comment by hluk** [comment]
Not sure what is going on either. BTW, I'm planing to work on some improvements for import/export (#913) so hopefully I'll be able to fix some bugs.
