### ISSUE TITLE
[Bug]: Extra space in clipboard?

### ISSUE THREAD

**Issue by elcolie** [hluk/CopyQ#941]
My snippet is this
```python
from pprint import pprint
import ipdb; ipdb.set_trace()
```

OSX: 10.13.4
CopyQ Clipboard Manager v3.4.0 (hluk@email.cz)
Built with: Qt 5.10.1

When I paste my snippet from `CopyQ`

I got 1 extra space in front of my snippet
As is
```python
 from pprint import pprint
import ipdb; ipdb.set_trace()
```

**Comment by hluk** [comment]
I suspect that the space was an [UTF-8 BOM](https://en.wikipedia.org/wiki/Byte_order_mark) misinterpreted by CopyQ.

Do you know from which app did you copy it?

What does following command print after you copy the item from CopyQ?

```
copyq clipboard | xxd
```

**Comment by elcolie** [comment]
It is  PyCharm `2018.1.2`
```bash
$ copyq clipboard | xxd
00000000: 6672 6f6d 2070 7072 696e 7420 696d 706f  from pprint impo
00000010: 7274 2070 7072 696e 740a 696d 706f 7274  rt pprint.import
00000020: 2069 7064 623b 2069 7064 622e 7365 745f   ipdb; ipdb.set_
00000030: 7472 6163 6528 29                        trace()
```

**Comment by hluk** [comment]
OK, will be fixed in next release. Thanks for reporting this.
