### ISSUE TITLE
Encountering segfault when starting Copyq

### ISSUE THREAD

**Issue by soupmagnet** [hluk/CopyQ#942]
After a recent update on an Arch Linux system, copyq stopped working entirely.  I reinstalled it several times, and even built and installed from source to see if that made a difference.  Starting copyq from the commend line or the GUI menu, results in a segmentation fault.  I've tried to debug it as much as I can, but unfortunately this is well beyond my knowledge or skillset.  Even if the problem is not directly related to Copyq itself, any help toward understanding why it's failing would be most appreciated.  TIA

`$ ldd copyq`
	`linux-vdso.so.1 (0x00007ffcb75d7000)`
	`libQt5X11Extras.so.5 => /usr/lib/libQt5X11Extras.so.5 (0x00007f69cf56d000)`
	`libQt5Network.so.5 => /usr/lib/libQt5Network.so.5 (0x00007f69cf1e1000)`
	`libQt5Svg.so.5 => /usr/lib/libQt5Svg.so.5 (0x00007f69cef8c000)`
	`libQt5Script.so.5 => /usr/lib/libQt5Script.so.5 (0x00007f69ceaf1000)`
	`libXtst.so.6 => /usr/lib/libXtst.so.6 (0x00007f69ce8eb000)`
	`libX11.so.6 => /usr/lib/libX11.so.6 (0x00007f69ce5ac000)`
	`libQt5Widgets.so.5 => /usr/lib/libQt5Widgets.so.5 (0x00007f69cdd52000)`
	`libQt5Gui.so.5 => /usr/lib/libQt5Gui.so.5 (0x00007f69cd591000)`
	`libQt5Core.so.5 => /usr/lib/libQt5Core.so.5 (0x00007f69cce89000)`
	`libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f69ccb02000)`
	`libm.so.6 => /usr/lib/libm.so.6 (0x00007f69cc76e000)`
	`libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f69cc557000)`
	`libc.so.6 => /usr/lib/libc.so.6 (0x00007f69cc19c000)`
	`/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f69cfc78000)`
	`libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f69cbf7e000)`
	`libz.so.1 => /usr/lib/libz.so.1 (0x00007f69cbd67000)`
	`libssl.so.1.1 => /usr/lib/libssl.so.1.1 (0x00007f69cbafd000)`
	`libcrypto.so.1.1 => /usr/lib/libcrypto.so.1.1 (0x00007f69cb680000)`
	`libXext.so.6 => /usr/lib/libXext.so.6 (0x00007f69cb46e000)`
	`libXi.so.6 => /usr/lib/libXi.so.6 (0x00007f69cb25d000)`
	`libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007f69cb034000)`
	`libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f69cae30000)`
	`libGL.so.1 => /usr/lib/libGL.so.1 (0x00007f69caba5000)`
	`libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007f69ca96f000)`
	`libharfbuzz.so.0 => /usr/lib/libharfbuzz.so.0 (0x00007f69ca6d1000)`
	`libsystemd.so.0 => /usr/lib/libsystemd.so.0 (0x00007f69ca452000)`
	`libicui18n.so.61 => /usr/lib/libicui18n.so.61 (0x00007f69c9fa7000)`
	`libicuuc.so.61 => /usr/lib/libicuuc.so.61 (0x00007f69c9bed000)`
	`libpcre2-16.so.0 => /usr/lib/libpcre2-16.so.0 (0x00007f69c9975000)`
	`libdouble-conversion.so.1 => /usr/lib/libdouble-conversion.so.1 (0x00007f69c9765000)`
	`libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x00007f69c9446000)`
	`libXau.so.6 => /usr/lib/libXau.so.6 (0x00007f69c9242000)`
	`libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007f69c903c000)`
	`libGLX.so.0 => /usr/lib/libGLX.so.0 (0x00007f69c8e0b000)`
	`libGLdispatch.so.0 => /usr/lib/libGLdispatch.so.0 (0x00007f69c8b55000)`
	`libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007f69c888f000)`
	`libgraphite2.so.3 => /usr/lib/libgraphite2.so.3 (0x00007f69c8663000)`
	`libgcrypt.so.20 => /usr/lib/libgcrypt.so.20 (0x00007f69c8347000)`
	`librt.so.1 => /usr/lib/librt.so.1 (0x00007f69c813f000)`
	`liblzma.so.5 => /usr/lib/liblzma.so.5 (0x00007f69c7f19000)`
	`liblz4.so.1 => /usr/lib/liblz4.so.1 (0x00007f69c7d04000)`
	`libicudata.so.61 => /usr/lib/libicudata.so.61 (0x00007f69c615f000)`
	`libpcre.so.1 => /usr/lib/libpcre.so.1 (0x00007f69c5eec000)`
	`libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007f69c5cdc000)`
	`libgpg-error.so.0 => /usr/lib/libgpg-error.so.0 (0x00007f69c5ac7000)`

CORE DUMP

`May 09 13:40:07 magnet kernel: copyq[1435]: segfault at 7ffe38745f48 ip 00007f7c6f8d4fde sp 00007ffe38745f00 error 6 in libc-2.27.so[7f7c6f820000+1b1000]`
`May 09 13:40:07 magnet systemd[1]: File /usr/lib/systemd/system/systemd-coredump@.service:37 configures an IP firewall (IPAddressDeny=any), but the local system does not support BPF/cgroup based firewalling.`
`May 09 13:40:07 magnet systemd[1]: Proceeding WITHOUT firewalling in effect!`
`May 09 13:40:07 magnet systemd[1]: Started Process Core Dump (PID 1437/UID 0).`
`May 09 13:40:07 magnet systemd-coredump[1438]: Process 1435 (copyq) of user 1000 dumped core.`
                                               
                                               `Stack trace of thread 1435:
                                               #0  0x00007f7c6f8d4fde __tzfile_read (libc.so.6)
                                               #1  0x00007f7c6f8d4b89 tzset_internal.part.0 (libc.so.6)
                                               #2  0x00007f7c6f8d4d38 tzset (libc.so.6)
                                               #3  0x00007f7c6f8d3be9 mktime (libc.so.6)
                                               #4  0x00007f7c705f8327 n/a (libQt5Core.so.5)
                                               #5  0x00007f7c705f9219 n/a (libQt5Core.so.5)
                                               #6  0x00007f7c705f94e2 n/a (libQt5Core.so.5)
                                               #7  0x00007f7c705fc39a _ZN9QDateTime18setMSecsSinceEpochEx (libQt5Core.so.5)
                                               #8  0x00007f7c705feb89 _ZN9QDateTime19fromMSecsSinceEpochExN2Qt8TimeSpecEi (libQt5Core.so.5)
                                               #9  0x00007f7c705ff212 _ZN9QDateTime19fromMSecsSinceEpochEx (libQt5Core.so.5)
                                               #10 0x00007f7c706c087f _ZNK9QFileInfo8fileTimeEN11QFileDevice8FileTimeE (libQt5Core.so.5)
                                               #11 0x00007f7c706c0a43 _ZNK9QFileInfo12lastModifiedEv (libQt5Core.so.5)
                                               #12 0x00007f7c7070b06c n/a (libQt5Core.so.5)
                                               #13 0x00007f7c7070b22f n/a (libQt5Core.so.5)
                                               #14 0x00007f7c7070bf42 n/a (libQt5Core.so.5)
                                               #15 0x00007f7c7070c030 _ZN9QSettingsC2ERK7QStringNS_6FormatEP7QObject (libQt5Core.so.5)
                                               #16 0x00007f7c643569f1 _ZN16Qt5CTStylePlugin6createERK7QString (libqt5ct-style.so)
                                               #17 0x00007f7c71599b63 _ZN13QStyleFactory6createERK7QString (libQt5Widgets.so.5)
                                               #18 0x00007f7c715be155 n/a (libQt5Widgets.so.5)
                                               #19 0x00007f7c715bedf5 _ZN11QProxyStyle5eventEP6QEvent (libQt5Widgets.so.5)
                                               #20 0x00007f7c71527fec _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                               #21 0x00007f7c7152f9c6 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                               #22 0x00007f7c707a9ce0 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
                                               #23 0x00007f7c707e14ba _ZN14QObjectPrivate16setParent_helperEP7QObject (libQt5Core.so.5)
                                               #24 0x00007f7c715be118 n/a (libQt5Widgets.so.5)
                                               #25 0x00007f7c715bedf5 _ZN11QProxyStyle5eventEP6QEvent (libQt5Widgets.so.5)
                                               #26 0x00007f7c71527fec _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                               #27 0x00007f7c7152f9c6 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                               #28 0x00007f7c707a9ce0 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
                                               #29 0x00007f7c707e14ba _ZN14QObjectPrivate16setParent_helperEP7QObject (libQt5Core.so.5)
                                               #30 0x00007f7c715be118 n/a (libQt5Widgets.so.5)
                                               #31 0x00007f7c715bedf5 _ZN11QProxyStyle5eventEP6QEvent (libQt5Widgets.so.5)
                                               #32 0x00007f7c71527fec _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                               #33 0x00007f7c7152f9c6 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                               #34 0x00007f7c707a9ce0 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
                                               #35 0x00007f7c707e14ba _ZN14QObjectPrivate16setParent_helperEP7QObject (libQt5Core.so.5)
                                               #36 0x00007f7c715be118 n/a (libQt5Widgets.so.5)
                                               #37 0x00007f7c715bedf5 _ZN11QProxyStyle5eventEP6QEvent (libQt5Widgets.so.5)
                                               #38 0x00007f7c71527fec _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                               #39 0x00007f7c7152f9c6 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                               #40 0x00007f7c707a9ce0 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
                                               #41 0x00007f7c707e14ba _ZN14QObjectPrivate16setParent_helperEP7QObject (libQt5Core.so.5)
                                               #42 0x00007f7c715be118 n/a (libQt5Widgets.so.5)
                                               #43 0x00007f7c715bedf5 _ZN11QProxyStyle5eventEP6QEvent (libQt5Widgets.so.5)
                                               #44 0x00007f7c71527fec _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                               #45 0x00007f7c7152f9c6 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                               #46 0x00007f7c707a9ce0 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
                                               #47 0x00007f7c707e14ba _ZN14QObjectPrivate16setParent_helperEP7QObject (libQt5Core.so.5)
                                               #48 0x00007f7c715be118 n/a (libQt5Widgets.so.5)
                                               #49 0x00007f7c715bedf5 _ZN11QProxyStyle5eventEP6QEvent (libQt5Widgets.so.5)
                                               #50 0x00007f7c71527fec _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                               #51 0x00007f7c7152f9c6 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                               #52 0x00007f7c707a9ce0 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
                                               #53 0x00007f7c707e14ba _ZN14QObjectPrivate16setParent_helperEP7QObject (libQt5Core.so.5)
                                               #54 0x00007f7c715be118 n/a (libQt5Widgets.so.5)
                                               #55 0x00007f7c715bedf5 _ZN11QProxyStyle5eventEP6QEvent (libQt5Widgets.so.5)
                                               #56 0x00007f7c71527fec _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                               #57 0x00007f7c7152f9c6 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                               #58 0x00007f7c707a9ce0 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
                                               #59 0x00007f7c707e14ba _ZN14QObjectPrivate16setParent_helperEP7QObject (libQt5Core.so.5)
                                               #60 0x00007f7c715be118 n/a (libQt5Widgets.so.5)
                                               #61 0x00007f7c715bedf5 _ZN11QProxyStyle5eventEP6QEvent (libQt5Widgets.so.5)
                                               #62 0x00007f7c71527fec _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                               #63 0x00007f7c7152f9c6 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                               
                                               Stack trace of thread 1436:
                                               #0  0x00007f7c6f90ccd9 __poll (libc.so.6)
                                               #1  0x00007f7c6e6cf8e0 n/a (libxcb.so.1)
                                               #2  0x00007f7c6e6d1679 xcb_wait_for_event (libxcb.so.1)
                                               #3  0x00007f7c68c2b82a n/a (libQt5XcbQpa.so.5)
                                               #4  0x00007f7c705bcabd n/a (libQt5Core.so.5)
                                               #5  0x00007f7c6f6090bc start_thread (libpthread.so.0)
                                               #6  0x00007f7c6f9172ff __clone (libc.so.6)`
`

**Comment by hluk** [comment]
Can you share log and configuration?

- Log: `~/.local/share/copyq/copyq/copyq.log`
- Configuration: `~/.config/copyq/copyq.conf`

**Comment by soupmagnet** [comment]
Thanks for the reply,.  The logs revealed that the problem was the result of having some QT libs with mixed versions, which is apparently not allowed...

`...
CopyQ ERROR [2018-05-18 12:56:14.646] Client-3691: QtFatal: Cannot mix incompatible Qt library (version 0x50903) with this library (version 0x50a01) (:0, )
CopyQ ERROR [2018-05-18 12:56:14.889] Client-3698: QtFatal: Cannot mix incompatible Qt library (version 0x50903) with this library (version 0x50a01) (:0, )
CopyQ ERROR [2018-05-18 12:56:15.184] Client-3708: QtFatal: Cannot mix incompatible Qt library (version 0x50903) with this library (version 0x50a01) (:0, )
...`

`$ pacaur -Ss qt | grep -i installed
**extra/qt5-base 5.10.1-8 (qt qt5) [installed]**
extra/qt5-declarative 5.10.1-4 (qt qt5) [installed: 5.9.3-1]
**extra/qt5-location 5.10.1-2 (qt qt5) [installed]**
extra/qt5-multimedia 5.10.1-1 (qt qt5) [installed: 5.9.3-1]
extra/qt5-script 5.10.1-1 (qt qt5) [installed: 5.9.3-1]
extra/qt5-sensors 5.10.1-1 (qt qt5) [installed]
extra/qt5-svg 5.10.1-1 (qt qt5) [installed: 5.9.3-1]
extra/qt5-tools 5.10.1-1 (qt qt5) [installed: 5.9.3-1]
extra/qt5-webchannel 5.10.1-1 (qt qt5) [installed]
extra/qt5-webkit 5.212.0alpha2-14 (qt qt5) [installed]
extra/qt5-x11extras 5.10.1-1 (qt qt5) [installed: 5.9.3-1]
extra/qt5-xmlpatterns 5.10.1-1 (qt qt5) [installed: 5.9.3-1]`

I updated the remaining QT libs to the latest versions and now CopyQ works.  Thanks!
