### ISSUE TITLE
Copying last copied text does not work

### ISSUE THREAD

**Issue by ManuelSchneid3r** [hluk/CopyQ#943]
When I copy a text it appears in copyq list. If I remove the (1st) item from the list the text appears still in the title (fine, clipboard content I guess). When I try to copy the same text "abc" again, it is not added to the list again. I expected it to be added to the list.

**Comment by hluk** [comment]
The item is not added again to the list because the clipboard content (the part that CopyQ checks) didn't change - so you have to re-add it manually (Ctrl+V).

Is there a use case for this? I would find it annoying if the item I removed reappeared.
