### ISSUE TITLE
Cannot add PPA: 'ppa:hluk/copyq'.

### ISSUE THREAD

**Issue by PawarKishori** [hluk/CopyQ#944]
I am not able to add in Ubuntu 14.04. Please help to resolve this issue. Thanks.

**Comment by hluk** [comment]
Please add more details. Did you follow [the documentation](http://copyq.readthedocs.io/en/latest/installation.html)?

**Comment by scottkosty** [comment]
@PawarKishori what command did you use to add and what is the output you get?
