### ISSUE TITLE
Sublime Text

### ISSUE THREAD

**Issue by LeshaRB** [hluk/CopyQ#947]
Add external editor

`/home/lesharb/soft/sublime/sublime_text -- %1`

But text always empty

![image](https://user-images.githubusercontent.com/439337/40103236-6c34815a-58f5-11e8-90f4-9e8b1c5818c8.png)

**Comment by hluk** [comment]
Looks like you'll have to use `--wait` argument, otherwise the command exits immediately (There is same problem with `gvim`). If CopyQ sees that the command exited, it assumes that the editor is no longer running and removes the temporary file with item content.

```bash
sublime_text --wait -- %1
```

I'll add this in FAQ.
