### ISSUE TITLE
Portable [ copyq.exe ] shows 2 alerts, will not run

### ISSUE THREAD

**Issue by bawldiggle** [hluk/CopyQ#950]
Win-7 PRO 64-bit
Downloaded portable [copyq-v3.4.0.zip]  from  ...  https://github.com/hluk/CopyQ/releases
Extracted ZIP ... running copyq.exe ...
At first I get this 
![install error 1](https://user-images.githubusercontent.com/23147509/40278926-b297b89c-5c29-11e8-9162-3c380eb9eded.png)
... followed immediately with ...
![install error msg 2](https://user-images.githubusercontent.com/23147509/40278935-ca18abd4-5c29-11e8-9292-640149a206b9.png)

**Comment by hluk** [comment]
Can you make sure the app is unpacked in a folder where it has read/write access? (All npacked dll files have read permission and the app can create config golder.)

**Comment by bawldiggle** [comment]
Unpacked in folder  C:\DownloadZ\CopyQ-340_p\extracted_p
this folder has 100 plus downloads (installers + portables, they all run without problems

**Comment by bawldiggle** [comment]
Just checked C:\DownloadZ  "Read Only" attribute, was greyed out
Changed Read Only attribute to FALSE ... still the same problem and 2 alerts as in post #1

**Comment by bawldiggle** [comment]
Plugins folder is empty

**Comment by bawldiggle** [comment]
Extracted ZIP to external USB ... ran "copyq.exe ... problem persists
Same alerts (identical msgs
alert #1 "cannot find Qt platform plugin "windows" in "" ... an empty path ??
Where do I find "QT platform plugin for "Windows"  ?

**Comment by smaragdus** [comment]
I am completely satisfied with version [3.0.3](https://github.com/hluk/CopyQ/releases/tag/v3.0.3) so I do not update **CopyQ** any more. Yet I tested version [3.4.0](https://github.com/hluk/CopyQ/releases/tag/v3.4.0) and it worked flawlessly under Windows 8 x64. What archiving program did you use to decompress the archive (**copyq-v3.4.0.zip**)?

**Comment by hluk** [comment]
> What archiving program did you use to extract the archive (copyq-v3.4.0.zip)?

[7-Zip](https://ci.appveyor.com/project/hluk/copyq/build/1.2.1543/job/1tmy9t82c0wvd922#L1089).

For me the windows plugins (file `copyq-v3.4.0/platforms/qwindows.dll`) unzips successfully.

Did you download the archive from [here](https://github.com/hluk/CopyQ/releases)?
