### ISSUE TITLE
Persistent error on file copy operation

### ISSUE THREAD

**Issue by paul1149** [hluk/CopyQ#953]
Hi,
I'm getting an error message whenever I copy files in the file manager. The error doesn't go away until I click it. Here's a shot of the image: https://imgur.com/1LeGrEQ

I have a custom action that prevents file operations from being logged in copyq's DB. I believe it is what is throwing this error. The command is:

```
[Command]
Automatic=true
Command="
    //by pb, 12/2017
    
    //orig command option / output: image/svg+xml"
Icon=\xf06a
Name=Ignore file manager
Output=image/svg+xml
Remove=true
Tab=image/svg+xml
Window=.*File Manager
```
I'd like to either stop the error message, or at least have it automatically dismiss itself after a few seconds, _as all other copyq messages do_. 

I'm on copyq 3.4.0, on MX Linux (debian stretch 9.3) x64.

Thanks!

**Comment by hluk** [comment]
Seems that clipboard monitor crashed. Can you share the log (F12 shortcut in app)?

The automatic command looks very strange. `Output=image/svg+xml` means that (since `Input` is not set) it will try to save text as SVG image to tab `image/svg+xml`. CopyQ also tries to execute the command and lines starting with `//` are not treated as comments.

**Comment by paul1149** [comment]
Ok, I've redone the command, to this:

` [Command]
Automatic=true
Icon=\xf06a
Name=Ignore file manager
Output=text/plain
Remove=true
Tab=files
Window=.*File Manager `

That takes the input and sends it to a new tab I created, then removes it from the clipboard. At least that seems to be what's going on. And no error messages are thrown at all. I don't need the new tab, "files", but if that's what I have to do to get this to work I'll do it this way.

Thanks,
Paul
