### ISSUE TITLE
Build fails when using qt 5.11 - qt5_use_modules is obsolete

### ISSUE THREAD

**Issue by x3rAx** [hluk/CopyQ#954]
I'm on Arch GNU/Linux using qt 5.11

When I try to build CopyQ I'm getting the following error:

```
CMake Error at src/CMakeLists.txt:89 (qt5_use_modules):
  Unknown CMake command "qt5_use_modules".
```

This seems to be because `qt_use_modules` is obsolete ([according to the official Qt documentation](https://doc.qt.io/qt-5/cmake-manual.html#qt5core-macros)) and it seems to have been dropped in 5.11.

I also found these two issues from other projects reporting the same behavior on Arch Linux + qt 5.11:
- https://github.com/MultiMC/MultiMC5/issues/2291
- https://github.com/ubports/libqtdbustest/issues/1

**Comment by hluk** [comment]
@x3rAx I don't have any system with Qt 5.11 available yet, so hope the fix works.

Thanks for the report.

**Comment by x3rAx** [comment]
Hi @hluk, thanks for the fix. I am able to manually build it now :smiley: 

A final request: 

If you'd release a new minor version (v3.4.1) the maintainer of the package in the Arch User Repository could update their package to use the new version so that it can then be installed/updated using the package manager again.

This would be really great because currently I'm always getting an error when updating all packages (and you do that quite often on an Arch Linux :sweat_smile:)
