### ISSUE TITLE
App runs but GUI is not accessible

### ISSUE THREAD

**Issue by Mateusresende** [hluk/CopyQ#956]
You close #951 

How I solve it?

@hluk

The program only runs.
But, it does not open any interface, nothing visual, understand? Only runs background, no function at all.

And from the description given, I could not figure out how to solve it. I already had to search for the files listed all over HD, nothing to find either. I do not know in which directory are also to look manually.

I already removed it, and installed it several times and nothing worked.
It only takes up 300 megabytes of memory.

**Comment by hluk** [comment]
Sorry, I misunderstood your issue. Since you mentioned that "it's running" I assumed that you can still use the app.

As I mentioned the file format for storing items is quite inefficient for large data so it may make the app unresponsive when loading or saving tabs.

Anyway, I need more information.

What app version you use and what OS?

Do you see tray icon after you launch the app?

Does the main window show up with command `copyq show`?

Can you share logs? (Command `copyq info logs` should print the log file path.)

**Comment by gdfox** [comment]
I am having the same problem. I start Copyq, I click on the tray icon, it shows all the clips. I close to the tray, and reopen, all I get is white screen with only the tabs showing. I have to quit and restart to get the clips back. See attached below.

What app version you use and what OS?

Copyq 3.5.0-1
Manjaro KDE Linux

Do you see tray icon after you launch the app?

Yes

Does the main window show up with command copyq show?

![selection_010](https://user-images.githubusercontent.com/341095/42574306-318a910c-84ec-11e8-9b80-362942fb2f7f.png)

Can you share logs? (Command copyq info logs should print the log file path.)

ERROR [2018-01-31 15:07:42.456] Server-3378: Restarting clipboard monitor (Connection timeout)
ERROR [2018-01-31 15:10:43.457] Server-3378: Restarting clipboard monitor (Connection timeout)
ERROR [2018-02-05 11:13:34.956] Server-25282: Restarting clipboard monitor (Connection timeout)
ERROR [2018-02-10 10:27:24.483] Server-669: Restarting clipboard monitor (Connection timeout)
ERROR [2018-03-12 09:31:35.005] Server-19259: Restarting clipboard monitor (Failed to start)
ERROR [2018-03-12 09:31:51.003] Server-19259: Restarting clipboard monitor (Failed to start)
ERROR [2018-03-12 09:32:07.004] Server-19259: Restarting clipboard monitor (Failed to start)
ERROR [2018-03-12 09:32:23.007] Server-19259: Restarting clipboard monitor (Failed to start)
ERROR [2018-03-12 09:32:39.013] Server-19259: Restarting clipboard monitor (Failed to start)
ERROR [2018-03-12 09:32:55.005] Server-19259: Restarting clipboard monitor (Failed to start)
ERROR [2018-03-12 09:40:55.175] Server-1124: Restarting clipboard monitor (Disconnected)
ERROR [2018-03-22 19:32:36.990] Client-18304: Connection lost!
ERROR [2018-04-03 10:51:31.230] Client-1340: Connection lost!
ERROR [2018-04-08 11:52:20.970] Client-13661: Connection lost!
ERROR [2018-04-08 11:52:20.973] Client-32526: Connection lost!
ERROR [2018-04-13 11:48:32.013] Client-1234: Connection lost!
ERROR [2018-04-17 15:21:49.363] Client-2276: Connection lost!
ERROR [2018-05-12 12:14:48.077] Client-6842: Cannot connect to server! Start CopyQ server first.
ERROR [2018-05-12 12:15:07.289] Client-6862: Cannot connect to server! Start CopyQ server first.
ERROR [2018-05-24 06:38:37.185] Client-22873: Connection lost!
ERROR [2018-05-25 06:30:45.769] Client-1261: Connection lost!
ERROR [2018-05-28 08:25:46.941] Client-8532: Connection lost!
ERROR [2018-07-11 08:31:18.811] <Client-10779>: Cannot connect to server! Start CopyQ server first.

**Comment by hluk** [comment]
Is this still an issue with latest version (3.7.1)? I've implemented some fixes for similar issue in recent versions.
