### ISSUE TITLE
Emacs (GUI) cannot copy any text if an image is in clipboard

### ISSUE THREAD

**Issue by hluk** [hluk/CopyQ#957]
Reported by @amosbird.

When having mime picture item in clipboard, gui emacs cannot copy any new text. It yields `Selection owner couldn't convert: STRING` .  This issue seems to be related https://github.com/pvanek/qlipper/issues/35 . Why is there an owner for that mime item?

The related emacs code is `bool there_is_a_selection_owner = XGetSelectionOwner (display, selection_atom) != 0;`

**Comment by hluk** [comment]
@amosbird Can you provide steps to reproduce this? I cannot do that with Emacs 26.1 (image is copied from CopyQ).

What's output of `copyq --version`?

> Why is there an owner for that mime item?

This is probably handled by Qt. CopyQ itself doesn't mess around with the upper case formats.

**Comment by amosbird** [comment]
Ah, this is due to  `(setq save-interprogram-paste-before-kill t)` .

**Comment by hluk** [comment]
> Ah, this is due to (setq save-interprogram-paste-before-kill t) .

Does that mean it's resolved?

**Comment by amosbird** [comment]
well it still remains an issue if that setting is on. However I don't rely on the setting anymore :)  Feel free to close it.

**Comment by hluk** [comment]
Thanks :)
