### ISSUE TITLE
Feature suggestion: option to always show the clipboard tab

### ISSUE THREAD

**Issue by richtrefz** [hluk/CopyQ#960]
I build copyq and run it vs simply using flatpak.  I realized, that at this point, I only make one change to source.  I have a lot of tabs and 98% of the time, when I want to "show main window", I prefer it was on the "clipboard" tab.  If you think others might want the option to do this, this one-liner seems to do the trick.  I'd really prefer to use the flatpak.  Thanks for your consideration.

```
void MainWindow::showWindow()
{
    ...
    QApplication::setActiveWindow(this);

    // ---------------------------------------
    // Change
    ui->tabWidget->setCurrentIndex(0);
    // ---------------------------------------

    stealFocus(*this);
}
```

**Comment by hluk** [comment]
You can use command `copyq show clipboard` to do that or use modified "Show/hide main window" global shortcut command:

```ini
[Command]
Command="
    copyq:
    toggle()
    setCurrentTab('clipboard')"
GlobalShortcut=ctrl+shift+!
Icon=\xf022
IsGlobalShortcut=true
Name=Show/hide main window
```

**Comment by richtrefz** [comment]
**That worked great - thanks for taking the time.**  

Fortunately, with the shortcut, I don't need the tray icon.  New Cinnamon isn't showing it.  Neither when I built it myself or with flatpak.

**Comment by hluk** [comment]
The tray issues happened in past too. The notification area often breaks functionality of tray icons. Perhaps some additional libraries need to be installed for Qt 5 apps to work.
