### ISSUE TITLE
Should be possible to make portable Windows version should store its config non-portably

### ISSUE THREAD

**Issue by tom-seddon** [hluk/CopyQ#961]
(This could apply to other builds as well, but I've only been using the Windows one.)

Suppose you have your favourite tools in version control: the portable version then seems like the one to use, because you're not going to be running the setup program on every PC. But you don't then want it to store its config in the repository, because that's a pain to look after! The config should go in the USERPROFILE folder (even though that isn't portable).

My workaround for this has been to add a 0-byte `unins000.exe` to my repository, so copyq thinks it's the non-portable version, and the working copy doesn't change on each run. But it seems like there ought to be a neater and/or documented way of doing this. Though if nobody's mentioned it so far, maybe not...?

Thanks,

--Tom

**Comment by hluk** [comment]
In next release, it will be possible to add `COPYQ_SETTINGS_PATH` to your environment variable to define custom path for the configuration (see [docs](https://copyq.readthedocs.io/en/latest/sessions.html#configuration-path)).

You can find portable zip with the support [here](https://ci.appveyor.com/project/hluk/copyq/build/1.2.1619/job/yid4qat081i7shaj/artifacts).

Thanks, for the suggestion.
