### ISSUE TITLE
Display all items when searching history

### ISSUE THREAD

**Issue by Clemens-Ratte-Polle** [hluk/CopyQ#962]
Hi.
CopyQ-Search is OK.
But it should give another one. :)

Often you copy 2 and more connected objects, especially in text form.
And when you search for one the other coherent text is NOT displayed, if not remembered: vanished...

So it would be fine to have another search option which displays not only ALL the findings at ONCE.
It should display one finding after another in context to it's history.
Thus you could see all things copied before and after the finding. :) 
Therefore i could see all relating words, objects in relative history.

When pressing another time the special search button the next find position should be displayed with the searched object in the middle of the window.
I hope you understand what i mean :)

thx
Clemens

ps: Yes, this option i also miss in all browser histories!

**Comment by hluk** [comment]
I often need this too. I think this was supported in past in some way -- if you filtered items, the first matching one was selected ---this is same current behavior--- but and pressing <kbd>Esc</kbd> would only cancel the filtering (i.e. show all items) and keep the found item selected.

So I'm bringing the functionality back. Additionally, if you start searching again (e.g. with <kbd>Ctrl</kbd>+<kbd>F</kbd> or <kbd>F3</kbd>) the search will restart with the last searched expression.

If you are on Windows, you can try it out with [this build](https://ci.appveyor.com/project/hluk/copyq/build/job/b40tmq6drbjw3sbk/artifacts) (currently, the new code is in branch `persistent-search`).

**Comment by Clemens-Ratte-Polle** [comment]
so you will bring this functionality back? :)
But it's name "Persistant Search" seems a bit irritating because other projects named alike do it wrong showing only the search hits and NOT chronologically within the "copy history".
e.g.
https://github.com/KieronQuinn/PersistentSearch

Perhaps it should be renamed ?

**Comment by hluk** [comment]
> so you will bring this functionality back? :)

Yes, working on some minor improvements.

> But it's name "Persistant Search" seems a bit irritating

:) Oh, come on, it's only a branch name, it won't show up anywhere in UI and docs, and naming is hard. I call it "persistent" because the last search term is available for next search.

The history of search terms is also available (option "Save Filter History") but I find it more annoying than useful (currently, the search term history popup covers the item list).
