### ISSUE TITLE
Running on Ubuntu 16.04 TLS, kernel: 4.14.13-041413-generic , crashing very often.

### ISSUE THREAD

**Issue by Jagden** [hluk/CopyQ#963]
![image](https://user-images.githubusercontent.com/18083213/41905953-4961f11a-7945-11e8-8ee7-ff707ece4d40.png)

Happens on all versions of copyq including 3.5.0.

Any ideas ?

Running qmake shows:
# qmake -qt=5 --version
QMake version 3.0
Using Qt version 5.5.1 in /usr/lib/x86_64-linux-gnu

**Comment by Jagden** [comment]
# copyq --version
CopyQ Clipboard Manager v3.5.0 (hluk@email.cz)
Built with: Qt 5.3.2

Installed it from here: [https://github.com/hluk/CopyQ/releases](https://github.com/hluk/CopyQ/releases)

But happened since at least 3.1.2 (I didn't test previous versions).

**Comment by hluk** [comment]
Looks like the issue is that the package you installed is built for different distro with different version of Qt and that's why it crashes.

Please install the version from PPA (see [Installation](https://copyq.readthedocs.io/en/latest/installation.html)).

**Comment by Jagden** [comment]
Wow! thanks, will check this out ! thank you very much.
