### ISSUE TITLE
Not responding in Windows7 x64

### ISSUE THREAD

**Issue by snowbound** [hluk/CopyQ#964]
I had 3.4 installed and noticed that as soon as CopyQ starts up if I open the app and scroll down in the captures and then back up again the app shows Not Responding in its title bar and the 2 processes have to be killed off. Any other reports of this type of problem?

Looked at the log file and noticed there is alot of entries similar to 

CopyQ ERROR [2018-06-26 22:33:07.340] <Server-8216>: Failed to extract plugin meta data from 'C:/Program Files (x86)/CopyQ/plugins/itemweb.dll'
CopyQ ERROR [2018-06-26 22:33:07.788] <monitorClipboard-9052>: Failed to extract plugin meta data from 'C:/Program Files (x86)/CopyQ/plugins/itemdata.dll'
CopyQ ERROR [2018-06-26 22:33:07.797] <monitorClipboard-9052>: Failed to extract plugin meta data from 'C:/Program Files (x86)/CopyQ/plugins/itemencrypted.dll'
CopyQ ERROR [2018-06-26 22:33:07.804] <monitorClipboard-9052>: Failed to extract plugin meta data from 'C:/Program Files (x86)/CopyQ/plugins/itemfakevim.dll'
CopyQ ERROR [2018-06-26 22:33:07.811] <monitorClipboard-9052>: Failed to extract plugin meta data from 'C:/Program Files (x86)/CopyQ/plugins/itemimage.dll'
CopyQ ERROR [2018-06-26 22:33:07.818] <monitorClipboard-9052>: Failed to extract plugin meta data from 'C:/Program Files (x86)/CopyQ/plugins/itemnotes.dll'
CopyQ ERROR [2018-06-26 22:33:07.825] <monitorClipboard-9052>: Failed to extract plugin meta data from 'C:/Program Files (x86)/CopyQ/plugins/itemsync.dll'
CopyQ ERROR [2018-06-26 22:33:07.832] <monitorClipboard-9052>: Failed to extract plugin meta data from 'C:/Program Files (x86)/CopyQ/plugins/itemtags.dll'
CopyQ ERROR [2018-06-26 22:33:07.839] <monitorClipboard-9052>: Failed to extract plugin meta data from 'C:/Program Files (x86)/CopyQ/plugins/itemtext.dll'
CopyQ ERROR [2018-06-26 22:33:07.847] <monitorClipboard-9052>: Failed to extract plugin meta data from 'C:/Program Files (x86)/CopyQ/plugins/itemweb.dll'

**Comment by hluk** [comment]
Can you try to uninstall the app and install again? There was an issue with installer not removing old files properly (#959).

**Comment by snowbound** [comment]
What I initially did after discovering the issue was to delete all of the entries under the clipboard tab and that seemed to help fix it. I went to uninstall it just now and discovered that even though the CopyQ was not showing up in the Systray there were 2 CopyQ processes were running. I terminated them and uninstalled CopyQ and reinstalled it into the same directory. Will see how it behaves after this process.

**Comment by snowbound** [comment]
Seems to behaving itself so far no lock ups scrolling up and down

**Comment by hluk** [comment]
Any new errors in the log?

Maybe uninstaller also leaves files behind - in which case you'll have to remove these files manually and re-install.

**Comment by snowbound** [comment]
Note [2018-07-16 01:05:33.435] <Server-4188>: Command “copyq
monitorClipboard”

Note [2018-07-16 01:05:33.435] <Server-4188>: Error: Process crashed

Note [2018-07-16 01:05:33.435] <Server-4188>: 1. copyq monitorClipboard


This is all the logfile shows for today. Those entries are probably after
the machine was booted up after being powered off and the CopyQ Systray
icon was not showing up. Process List on Windows7 showed two CopyQ items
which I terminated. I then run CopyQ again from the Program List entry and
the icon showed up fine.

**Comment by hluk** [comment]
I will close this old issue. Please let me know if this still happens in the latest version.
