### ISSUE TITLE
Being able to keep a default item[FEATURE REQUEST]

### ISSUE THREAD

**Issue by bsucker98** [hluk/CopyQ#965]
would that be possible to add a feature to copy an item on the clipboard by default on startup, plus certain time after(user could decide) copying something, copying the default item back again..& to bookmark needed items, so those will be on the top in the context menu all the time, because would be very useful for frequently used ones..
In my case it's that my "s" key is broken ;)...so I need both capital and simple(not a big deal, a temporary issue, it jst reminded of dis, how useful it really is)
TNX

**Comment by hluk** [comment]
> copy an item on the clipboard by default on startup, plus certain time after(user could decide) copying something, copying the default item back again

Can be solved by adding [Keep Item in Clipboard command](https://github.com/hluk/copyq-commands/tree/master/Scripts#keep-item-in-clipboard). Unfortunately, there is bug in version 3.5.0 so this works only in 3.4.0.

> bookmark needed items, so those will be on the top in the context menu all the time

Set "Pin", "Unpin" shortcuts in preferences (can be the same shortcut).

> In my case it's that my "s" key is broken

Definitely get new keyboard before not using "s" key becomes a habit. :) (I cannot even imagine your suffering.)

**Comment by bsucker98** [comment]
> Definitely get new keyboard before not using "s" key becomes a habit. :) (I cannot even imagine your suffering.)

haha :p
