### ISSUE TITLE
Copy date

### ISSUE THREAD

**Issue by Rocktim53** [hluk/CopyQ#968]
Please provide the date on which the content has been copied.

**Comment by scottkosty** [comment]
Please give more information. It is useful to give some motivation: Why would this feature be useful to you (e.g. give an example)? Where exactly in CopyQ do you suggest that the date be displayed?

**Comment by m4r71n** [comment]
@Rocktim53 there is already a CopyQ command to store the copy date and time. Please See https://github.com/hluk/copyq-commands/blob/master/Automatic/show-copy-time.ini

I've created a PR with instructions to show the copied date and time as a **tag**. Please see: https://github.com/hluk/copyq-commands/pull/5/files

**Comment by Rocktim53** [comment]
m4r71n thanks its work.
