### ISSUE TITLE
Automatically delete the parameter at the end of the link

### ISSUE THREAD

**Issue by altblog** [hluk/CopyQ#970]
Hello! Help me please. I need to when I copy the link (through the right button) in the screenshot on the Google Play Market, after I press Ctrl+V to:
https://lh3.googleusercontent.com/N9P_4H4RwEi6zRZWeIZcw5Pfr0g4cdn6lH1Oyx2mh5d3d779soA9zjJfTLpEFuyNpti6
instead
https://lh3.googleusercontent.com/N9P_4H4RwEi6zRZWeIZcw5Pfr0g4cdn6lH1Oyx2mh5d3d779soA9zjJfTLpEFuyNpti6=w1680-h917-rw
Delete tail after the symbol equals =
This will save me a lot of time. Thank you.

**Comment by hluk** [comment]
Try following automatic command ([here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)).

```ini
[Command]
Automatic=true
Command="
    copyq:
    var url = str(input())
    var i = url.lastIndexOf('=')
    url = url.substring(0, i)
    copy(url)
    setData(mimeText, url)"
Icon=\xf3ab
Input=text/plain
Match="^https://lh3.googleusercontent.com/.*="
Name=Google Play Market: Copy URL Without Parameter
```

**Comment by altblog** [comment]
Thank you so much! Working! Yahoo!
