### ISSUE TITLE
How to set global shortcut to paste second to last clipboard entry (add to FAQ?)

### ISSUE THREAD

**Issue by kiuuik** [hluk/CopyQ#971]
Your software is great.

Until now I have only used the copyq windows. To speed up things today I tried to set a global command that pastes the penultimate element. I fail. I have looked at the options and at the [manual](http://copyq.readthedocs.io/en/latest/) for some time. The problem is with me. I really can't figure out which code I have to put into my newly created command with global shortcut. Any help would be appreciated. 

Maybe I'm not the only one who searches the manual in vain ...

Thanks.

**Comment by hluk** [comment]
Maybe following command will do.

```ini
[Command]
Command="
    copyq:
    var numberOfItems = count()
    if (numberOfItems < 2)
        abort()
    
    var secondToLastRow = numberOfItems - 2
    select(secondToLastRow)
    paste()"
GlobalShortcut=ctrl+shift+!
Icon=\xf46d
IsGlobalShortcut=true
Name=Paste Second to Last Item
```

**Note:** Apart from copying the item, the `select(...)` call will also move the item to the top depending on settings ("Move item to the top" in History configuration tab).

**Comment by kiuuik** [comment]
Thanks for this rapid and exhaustive answer. That's great! I travel at the moment so I can't test it. But it's made by the creator of the software. So I think I can already close the issue. Again: Thank you very much.

**Comment by Garrett-R** [comment]
I think the intention here is probably to copy the second most recent item, not the second oldest item.  

Having a hard getting that working, while also leaving the clipboard unchanged after the operation (i.e. paste the second last item, but then doing CTRL+V will still paste the last item).  This is my attempt but it is failing silently:

```
[Command]
Command="
    copyq:
    var numberOfItems = count()
    if (numberOfItems < 2)
        abort()
    
    next();
    paste();
    previous();"
GlobalShortcut=ctrl+shift+!
Icon=\xf46d
IsGlobalShortcut=true
Name=Paste Second to Last Item
```

Any ideas what I'm doing wrong?

**Comment by hluk** [comment]
@Garrett-R Try adding `sleep(2000)` before `previous()` - this should leave enough time for clipboard to be pasted before it's changed again.

**Comment by Garrett-R** [comment]
Awesome that worked!  (edited my last message to reflect)

**Comment by AnabasisXu** [comment]
> (_edited after @hluk helped me_)
> 
> For anyone who wants to copy the second most recent item from the clipboard (while not change the current thing on clipboard), you can do this:
> 
> ```ini
> [Command]
> Command="
>     copyq:
>     var numberOfItems = count()
>     if (numberOfItems < 2)
>         abort()
>     
>     next();
>     paste();
>     // Allow time for paste to happen
>     sleep(1000);
>     previous();"
> GlobalShortcut=ctrl+shift+!
> Icon=\xf46d
> IsGlobalShortcut=true
> Name=Paste Second to Last Item
> ```
> 
> (for newcomers, this command can be loaded following [these instructions](https://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them))

Thanks! 
>Name=Paste Second to Last Item
I suggest that to avoid confusion, the Name is better changed to 
`Name=Paste The Second Most Recent Item`
