### ISSUE TITLE
Minimize the window

### ISSUE THREAD

**Issue by LinArcX** [hluk/CopyQ#972]
Hi. and thank you for this great application.
I have gnome. and put copyq in: __~/.config/autostart__ for auto start it.
But when i login to system, a windows always appear on desktop. i want to minimize it every time i login to system. any idea?

**Comment by hluk** [comment]
Try using following replacing `Exec` line in the desktop file in autostart directory with following line.

```ini
Exec=sh -c "sleep 5; copyq"
```

Or use workaround:

```ini
Exec=sh -c "(sleep 5; copyq hide) & copyq"
```

**Comment by LinArcX** [comment]
Thank you so much.
