### ISSUE TITLE
Hard to read text items in preview list

### ISSUE THREAD

**Issue by nmat** [hluk/CopyQ#975]
**Description:**
Sometimes text is not visible if you copy text on certain backgrounds.

Example: white text on white background. Black (dark text) on dark background

**Expected:**
Text to be copied as text and not as image in preview item in copyq list. Image and image copy.

**Comment by hluk** [comment]
It's known problem (#194). The colors are part of the copied HTML but it usually has transparent background.

You can disable storing the HTML in configuration:

![image](https://user-images.githubusercontent.com/38054/43356996-e2f1eb0c-927a-11e8-85b5-42510260d776.png)

Alternatively, you can remove the colors with ["Remove Background and Text Colors" command](https://github.com/hluk/copyq-commands/tree/master/Application#remove-background-and-text-colors) (detail on how to add the command are in [README file](https://github.com/hluk/copyq-commands/blob/master/README.md)).

It's also possible to change colors in internal editor (F2 shortcut).
