### ISSUE TITLE
windows 10 - popout position should follow windows standard a bit more

### ISSUE THREAD

**Issue by nmat** [hluk/CopyQ#976]
**Description:**
Right clicking the tray icon makes the popout be very close to window screen so its hard to read and follow the tray popout. Sometimes it even goes out of screen where Exit it hidden below screen area.

**Expected:**
That the popout is a bit further above the icon and follows windows standard a bit more. Not sure if this is a QT thing but the popout really is not easy to follow right now since it is so out of line of the taskbar.

**Comment by hluk** [comment]
It's possible this is due to the menu being created dynamically just before it pops out.

**Comment by nmat** [comment]
Yes that might be it. The right click menu is very dynamic downwards so the exit button just goes outside the screen which feels really strange and hard to read. You have to right click several times to be able to get the window in a good position. :(

**Comment by hluk** [comment]
Interestingly, the positioning of tray menu when you right click tray icon is handled by Qt framework.

I only handle middle click which shows the whole menu on screen.

**Comment by nmat** [comment]
Reproducable here also. Middle click does show the menu on top like right click should. Is this something that can be fixed since Right click kind of is a go to thing for windows users I guess?

**Comment by hluk** [comment]
It's a [Qt bug](https://bugreports.qt.io/browse/QTBUG-63006).

I may be able to implement workaround but the code wouldn't look very good since I need to avoid modifying the tray menu behavior on other platforms. So I would rather wait for fix in Qt.

**Comment by nmat** [comment]
agree, its much better to have it be fixed in QT.

**Comment by hluk** [comment]
Looks like it should fixed in newer versions of Qt.
