### ISSUE TITLE
Shortcut doesn't seem to work

### ISSUE THREAD

**Issue by HeRo002** [hluk/CopyQ#977]
I just installed CopyQ on my Ubuntu 18.04 PC. 
According to CopyQ -> Preferences -> Shortcuts:
"Show Clipboard Content: Ctrl+Shift+C"
But when I open the Text app and press Ctrl+Shift+C nothing happens.

**Comment by hluk** [comment]
"Show Clipboard Content" is not global shortcut, it works only in application.

You can using ["Quickly Show Current Clipboard Content" command](https://github.com/hluk/copyq-commands/tree/master/Global#quickly-show-current-clipboard-content) (details on how to add the command are in [README file](https://github.com/hluk/copyq-commands/blob/master/README.md)).

**Comment by HeRo002** [comment]
Thank you for your answer!
