### ISSUE TITLE
Only starts as root on Ubuntu 18.04

### ISSUE THREAD

**Issue by imajor75** [hluk/CopyQ#978]
When I try to start copyq on Ubuntu 18.04 it gives this error message:

ERROR: Failed to create shared memory: QSharedMemoryPrivate::initKey: unable to set key on lock
Warning: CopyQ server is already running.

The server is not running, if I try copyq toggle I get:
ERROR: Cannot connect to server! Start CopyQ server first.

I can start the server as root without any problems.

**Comment by scottkosty** [comment]
What version of CopyQ do you have? Did you install it from the default Ubuntu repository or a PPA or did you compile it?

**Comment by imajor75** [comment]
I have 3.5.0, I installed it from the Ubuntu Software window.

**Comment by scottkosty** [comment]
Thanks for the quick reply. You might want to wait to see what @hluk says. In the mean time, you might want to removing the version you installed. Then, install from the PPA: https://launchpad.net/~hluk/+archive/ubuntu/copyq I have no idea if that will fix things for you, but it might be worth a try.

**Comment by scottkosty** [comment]
Thanks for that info. That's really strange. I wonder what's going on. We'll have to wait for @hluk to have time. I have not tested CopyQ on Ubuntu 18.04, but I might do so soon in a couple of weeks so I can see if I can reproduce then.

**Comment by imajor75** [comment]
Thank you. Let me know if I can help by testing something or if there is any more info you could fine useful.

**Comment by imajor75** [comment]
Any update on this guys? I think I did something wrong, and run something as root which I'm supposed to run as plain user, and some file has root as the owner. But I'm not sure which one is it. Does copyq have some config files somewhere which I should check?

**Comment by imajor75** [comment]
Thanks for the help guys, this is solved now. But I'm not sure what actually fixed it, probably that I changed the owner of all files in ~ recursively to my user. Now copyq starts automaticaly when I log in, as expected.

Thanks again!
