### ISSUE TITLE
Strange history entries with x-copyq-current-tab that paste two newlines

### ISSUE THREAD

**Issue by blueyed** [hluk/CopyQ#979]
Since recently I am starting to see clipboard entries like the following, where the x-copyq-current-tab entry looks suspicious (what is the meaning of it?

![2018-07-25-000153_979x342_escrotum](https://user-images.githubusercontent.com/9766/43168616-3ea21146-8f9e-11e8-95a2-5deebe2e9a15.png)

When pasting it it results in 2 newlines.

I've only seen it happening when copying it from inside of qutebrowser (likely by right-clicking a link and using the "Copy link address" context menu item).

I've only noticed this with(in) qutebrowser, but I also get the two newlines when pasting to a terminal when it happens.

Often (but not always?) it helps to select the entry from the history menu (using Enter): afterwards it will paste the plain text into a terminal at least, but not inside this qutebrowser textarea still (but two newlines).

CopyQ Clipboard Manager v3.5.0
Built with: Qt 5.11.1

**Comment by hluk** [comment]
[Format `application/x-copyq-current-tab`](http://copyq.readthedocs.io/en/latest/scripting-api.html#mimeCurrentTab) should be only available for commands executed from main window (e.g. application shortcut or from menu).

I cannot reproduce this (the format is not saved and I can paste the link back to qutebrowser). Could be some issue with command mapped to Enter key.

**Comment by blueyed** [comment]
I have "Decrypt and Paste" with "Enter" as shortcut in "CopyQ Commands".
This appears to be a default command, isn't it?

**Comment by blueyed** [comment]
Disabling this (and all other commands) does not help though.

**Comment by blueyed** [comment]
@hluk 
Any more ideas about how to debug this?

I just had the case where nothing would get pasted after "Copy link address" (with the history item looking the same as in the initial comment).
I've then gone to this issue, and for some reason pasting worked fine then in the original tab.
When trying it again, it did not work again, but then pasted the two newlines instead.

**Comment by hluk** [comment]
Does it help to disable all plugins in Item configuration tab? (Just uncheck all items in the list.)

**Comment by blueyed** [comment]
I've just noticed that is behaving strange also with copyq not running - i.e. it looks like a problem with qutebrowser itself.. /cc @TheCompiler
