### ISSUE TITLE
Copyq can't run shell to execute command

### ISSUE THREAD

**Issue by guraga** [hluk/CopyQ#980]
Steps to reproduce:
1. press hot key to open copyq window;
2. press F5 to show "copyq action dialog";
3. write one of the following texts in text area "command":
```bash
true && copyq popup 1 1 || copyq popup 2 2
```
or
```bash
false && copyq popup 1 1 || copyq popup 2 2
```
4. "standard input" is "" (empty string);
5. "store standard output" is "" (empty string);
6. press button "apply".

Actual behavior: in both cases executed command
```bash
copyq popup 2 2
```

Expected behavior: run shell correctly; first command must execute
```bash
copyq popup 1 1
```
and second command must execute
```bash
copyq popup 2 2
```

Copyq v3.5.0-8-g93a1a89.
Qt 5.5.1.
Ubuntu 16.04.

**Comment by hluk** [comment]
CopyQ doesn't support `&&` and `||`. You have to prefix the command with `bash:` to run it in bash interpreter (you can find [details in documentation](http://copyq.readthedocs.io/en/latest/writing-commands-and-adding-functionality.html#command)).
