### ISSUE TITLE
How to launch copyq window from any application

### ISSUE THREAD

**Issue by alexgman** [hluk/CopyQ#983]
Is there a way to define a keyboard shortcut such as ctrl+shift+10, or similar in order to open the copyq window, specifically so that I do not have to go to my taskbar, find copyq, then open it?

**Comment by m4r71n** [comment]
There is an entry in the FAQ https://copyq.readthedocs.io/en/latest/faq.html#how-to-open-application-window-or-tray-menu-using-shortcut
