### ISSUE TITLE
Using CopyQ as a key-value store?

### ISSUE THREAD

**Issue by alexgman** [hluk/CopyQ#984]
I have several hundred non-secure key-value pairs that I need to be able to use in my work. Suppose I have keys/values such as:

```
{
 "alex":"isawesome",
 "myGuid":"d92523e0-504a-43ad-989c-ec0b6eac69ed",
 "someOtherKey":"DAsdasdasd=========2349279348797(*(*(*&$$$$$$$$$)))"
}
```

I will need to use `myGuid` and `someOtherKey` - I would be very grateful for your suggestions on a possible workflow to support being able to easily **find the key that I want, and immediately paste the value.** 

Example use case:

1. I'm using MS-WORD, and need to paste the value of `someOtherKey`
2. later the same day, I am writing an email and I need to send someone the value of `myGuid`
3. etc

The idea I have currently is to simple enter my key,value pairs like so:

![image](https://user-images.githubusercontent.com/4227695/43230907-b425372c-902f-11e8-9147-e095bc646845.png)

The desired behavior would be:
1. type the text `someOtherKey` in some random application like word
2. the the key ( `someOtherKey` ) will immediately be replaced inline with this text: `DAsdasdasd=========2349279348797(*(*(*&$$$$$$$$$)))`

**What are some possible configurations within CopyQ to achieve this?**

**Comment by hluk** [comment]
Capturing typed text is not supported and will be too difficult to implement.

Definitely checkout [Snippets command](https://github.com/hluk/copyq-commands/tree/master/Global#snippets) which tries to work around the limitation (details on how to add the command are in [README file](https://github.com/hluk/copyq-commands/blob/master/README.md)).
