### ISSUE TITLE
rightclick show/hide results in empty History without buttons!

### ISSUE THREAD

**Issue by JohnML1** [hluk/CopyQ#989]
Linux my system Manjaro XFCE

CPU: Quad Core Intel Core i5-6400 (-MCP-) speed/min/max: 800/800/3300 MHz Kernel: 4.17.9-1-MANJARO x86_64 

CopyQ:
v3.5.0-57-g50a89bc1

Logfile:
ERROR [2018-08-01 18:31:15.999] <Client-12683>: Es kann keine Verbindung zum Server hergestellt werden! Bitte zuerst den CopyQ-Server starten.

Is that the reason??

I like this tool ... if it works :-)

The error not allways appear: Start copyq, hide/show several times show perview ... i don't know how to reproduce it, but the Manjaro package Maintainer has this prob too!

**Comment by hluk** [comment]
Do you mean right clicking on the history (item list in main window) and selecting "Show Preview" ("Vorschau anzeigen") can lead to no items in list and no buttons in toolbar?

Is there a link to downstream issue (for the Manjaro package)?

The error in log is unrelated. This just happens if you run a command (e.g. "copyq show") before the main app starts.

**Comment by JohnML1** [comment]
Hi,

.. rightclick on Icon in Taskbar and there in the popup-menue 
"show/hide" that will show as i named it "History".

Do that repeatedly and after some clicks history-window will be empty 
and now buttons at the right or menue at the top.

I attach the last package from Manjaro, that shows this behavior.

Restart copyQ and history is back.

Thanks for CopyQ!!!



Am 05.08.2018 um 13:25 schrieb Lukas Holecek:

**Comment by JohnML1** [comment]
see also:
https://forum.manjaro.org/t/copyq-3-5-0-not-working-well-after-update/52272

no it works ok but we'll see :-)

------------------------------------------------------------------------


Hi,

.. rightclick on Icon in Taskbar and there in the popup-menue 
"show/hide" that will show as i named it "History".

Do that repeatedly and after some clicks history-window will be empty 
and now buttons at the right or menue at the top.

I attach the last package from Manjaro, that shows this behavior.

Restart copyQ and history is back.

Thanks for CopyQ!!!



Am 05.08.2018 um 13:25 schrieb Lukas Holecek:

**Comment by JohnML1** [comment]
Issue appears if you use the close button of history window (the cross 
upper right on XFCE)

use that button several times.

hope you can reproduce it now!

------------------------------------------------------------------------


see also:
https://forum.manjaro.org/t/copyq-3-5-0-not-working-well-after-update/52272

no it works ok but we'll see :-)

------------------------------------------------------------------------


Hi,

.. rightclick on Icon in Taskbar and there in the popup-menue 
"show/hide" that will show as i named it "History".

Do that repeatedly and after some clicks history-window will be empty 
and now buttons at the right or menue at the top.

I attach the last package from Manjaro, that shows this behavior.

Restart copyQ and history is back.

Thanks for CopyQ!!!



Am 05.08.2018 um 13:25 schrieb Lukas Holecek:

**Comment by hluk** [comment]
Whats the window manager (xfwm4, openbox, ...)?

**Comment by JohnML1** [comment]
wikipedia tells me:

  * Xfwm (Standard beiXfce <https://de.wikipedia.org/wiki/Xfce>)


The desktop environment is XFCE.

... i don't know the difference between Desktop Environment and 
window-manager

Hope that gives you the needed information


Am 05.08.2018 um 18:49 schrieb Lukas Holecek:

**Comment by hluk** [comment]
I still cannot reproduce this.

Can you also provide output of `copyq version` and screenshot of the main window when it happens?

**Comment by JohnML1** [comment]
Hi,

here are the needed information:

[john1@manjaro ~]$ copyq version
CopyQ Clipboard Manager v3.5.0
Built with: Qt 5.11.1

The "History" window, but i think you call it the Main Window.


Really strange: the buttons at the right are there now, but the 
Main-Menue is missing as before.

I thought the Window-Close-Button of XFCE caused this issue, but at the 
moment it seems ok.

Can i grep something in journalctl?

These are issues we love?!!

Regards

John

Am 06.08.2018 um 10:31 schrieb Lukas Holecek:

**Comment by JohnML1** [comment]
Hi Lukas,

now its workinf ok, so don't waste too much time.

I can solve this issue just by restarting it, thats fine!

31 Celcius, i think i'm boiled enough :-)



Am 06.08.2018 um 10:31 schrieb Lukas Holecek:

**Comment by hluk** [comment]
Hmm, did you send the screenshots? I don't think github accepts them when sent by e-mail.

I've tested it with Qt 5.10.1, maybe that's why I cannot reproduce it.

Do you have the exact version of Qt 5.11.1 installed (e.g. package `qt5-base`)?

**Comment by hluk** [comment]
> 31 Celcius, i think i'm boiled enough :-)

Oh man, me too, I have about 30 degrees here. :)

**Comment by JohnML1** [comment]
Hi,

yes, screenshot was included.

pastebinit: https://pastebin.com/C7C0YNhB  click the raw button


**********************
13.07.2018 installed: qt5-base  5.11.1-1


... too hot in here, have a walk :-)

Am 06.08.2018 um 13:02 schrieb Lukas Holecek:

**Comment by scottkosty** [comment]
> yes, screenshot was included

It might be a new feature (I don't remember it before), but note that In GitHub you can now drag and drop a picture onto the reply, and it is included. At least for me, it says at the bottom of my reply text area "Attach files by dragging & dropping, selecting them, or pasting from the clipboard".

**Comment by scottkosty** [comment]
> Problem appeared after last update

Last update of what? What is the output from `copyq version`?

**Comment by sispus** [comment]
sorry, last bulk manjaro update which includes copyq

the result of 'copyq version':
CopyQ Clipboard Manager v3.5.0
Built with: Qt 5.11.1

**Comment by hluk** [comment]
I managed to reproduce and fix it with flatpak help (after bumping Qt version to 5.11).

**Comment by JohnML1** [comment]
thanks!

I'll wait for the automtic Manjaro XFCE update!

**Comment by hluk** [comment]
And of course just after I tested this with flatpak, the Qt 5.11 became available in the distro I'm using -- so there was no reason to mess around with flatpak :).
