### ISSUE TITLE
New Snippets script not working

### ISSUE THREAD

**Issue by paul1149** [hluk/CopyQ#990]
I would have posted this as a follow-up at https://github.com/hluk/CopyQ/issues/985, but that issue has been closed.

I'm not getting any action out of the new Snippets script. The hotkey doesn't do anything. I saved the new script to an .ini file, disabled the old one, then Loaded the new one. The Meta + Alt + Q hotkey is still specced, but it isn't doing anything. I'm on Linux. Thanks.

**Comment by hluk** [comment]
Did you copy the `snippets.ini` content and use "Paste Commands" button in Commands dialog?

**Comment by paul1149** [comment]
I copied the code to a new file, `snippets.ini`. Then in CopyQ / Commands... I clicked `Load Commands`, navigated to `snippets.ini`, and the program did the rest. I disabled the older Snippets command so there would be no conflict.

**Comment by hluk** [comment]
Can you reassign the shortcut again? Can you copy the old command here?

**Comment by paul1149** [comment]
Yes, that did it! I guess adding the new version while the old version was still enabled caused shortcut confusion. I respecified the same shortcut, and it immediately worked. Response time is a lot faster than the previous version too. 

When I paste into LibreOffice, the formatting is perfect. When I paste into ebay's listing text box, I get all the formatting, but I get double linefeeds. Wait - I see that only happens in Vivaldi, and not in Slimjet. Doesn't sound like a CopyQ problem.

Thanks much for your help on this new script!

**Comment by hluk** [comment]
> When I paste into ebay's listing text box, I get all the formatting, but I get double linefeeds. Wait - I see that only happens in Vivaldi, and not in Slimjet. Doesn't sound like a CopyQ problem.

Yeah, using HTML formatting in various apps is a mess. I often see it's completely ignored and plain text is pasted instead.
