### ISSUE TITLE
CopyQ only looks for gpg2, and does not find gpg

### ISSUE THREAD

**Issue by scottkosty** [hluk/CopyQ#991]
Installing the package `gpg` on Ubuntu 18.04 provides the binary `gpg`. CopyQ seems to search for the binary `gpg2`, and thus does not find it. If I create a symlink `gpg2` to `gpg`, then CopyQ does detect it.

In the above, what I refer to by "detecting the GPG binary" is the detection shown on CopyQ > Preferences > Items > Encryption.

I don't actually use encryption with CopyQ. I was just testing the feature.

Related to #641.

**Comment by hluk** [comment]
Looks like in `gpg2` is part of [gnupg2 package](https://packages.ubuntu.com/search?searchon=contents&keywords=gpg2&mode=exactfilename&suite=bionic&arch=any). This probably should be mentioned in [docs](http://copyq.readthedocs.io/en/latest/password-protection.html).

**Comment by scottkosty** [comment]
```
$ gpg --version
gpg (GnuPG) 2.2.4
libgcrypt 1.8.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /home/scott/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
$ 

```

Note that `apt-cache show gnupg2` gives the following (after the normal description): `This is a dummy transitional package that provides symlinks from gpg2 to gpg.`

**Comment by hluk** [comment]
In next version, CopyQ will try to use `gpg2` and, if it's not available, fallback to `gpg` (if the `gpg --version` says it's v2).

**Comment by scottkosty** [comment]
@hluk thanks!
