### ISSUE TITLE
toggle image filtering

### ISSUE THREAD

**Issue by amosbird** [hluk/CopyQ#992]
Hello, I have this command for showing image items.

```ini
[Command]
Command="
    copyq:
    filter('^image/.*')"
Icon=\xf1c5
InMenu=true
Name=Filter Images
Shortcut=ctrl+i

```

How can I make it a toggle like command?

**Comment by hluk** [comment]
I think I would need to expand the functionality so that calling `filter()` without arguments returns current filter.

**Comment by hluk** [comment]
In future versions, it will be possible to do:

```js
var filter_ = '^image/.*'
if (filter() == filter_)
  filter('')
else
  filter(filter_)
```

**Comment by amosbird** [comment]
hmm, `In future versions,` does it mean from now on?

**Comment by hluk** [comment]
The feature is currently in master git branch (if you can build the app). Not sure when I'll be able to release new version.
