### ISSUE TITLE
icon snip does not work anymore starting with 9458ffd

### ISSUE THREAD

**Issue by scottkosty** [hluk/CopyQ#993]
Starting with 9458ffdd, icon snip appears to be broken for me. To test, before running CopyQ, I removed the folder `~/.config/copyq`. When I do that and run CopyQ compiled at 9458ffdd, there is no snip on CopyQ startup. Further, if click on the tray icon, go to Preferences, and then click on "OK", there is no snip. In contrast, when I run CopyQ compiled at 01a24331 (the commit before the one above), there is a snip on startup and there is a snip after I click on OK.

Note: I don't actually care about those snips. But the commit also changed the behavior with the snips that I do care about, which is when I copy something to the clipboard. I think I have this preference set in my personal preferences, but when I wanted to reproduce the change of behavior I removed `~/.config/copyq`.

I'm on Ubuntu 18.04 with default GNOME desktop environment.

**Comment by hluk** [comment]
I usually don't notice the icon animation. But with some recent code changes it doesn't snip when clipboard monitor or automatic commands are started.

I changing this so that the icon snips every time a started command/client will communicate with the server. I'm testing this in git branch `tray-icon-snip`.

**Comment by scottkosty** [comment]
Thanks for the update and your work on it. If you need extra testing, let me know. Otherwise I'll wait till it lands in master. The reason why I like the snip on every copy is that it makes me feel more confident that CopyQ indeed grabbed something. In very rare cases, I think I do a copy but later realize that it didn't make it to CopyQ for some reason (e.g., I pressed "ctrl + v" instead of "ctrl + c").

**Comment by scottkosty** [comment]
Tested and works well, except that it snips also on any selection, even though I have the preference "store text selected using mouse" unchecked.

**Comment by hluk** [comment]
> Tested and works well, except that it snips also on any selection, even though I have the preference "store text selected using mouse" unchecked.

Automatic commands are still being executed when X11 selection changes even if the option is unchecked.

I'll try to omit the snips if the action taken by client process is not important, e.g.:
- a client process just starts,
- monitor fetches automatic commands to run,
- display commands set display data,
- filters for menu commands enable/disable menu items,
- some simple non-modifying functions are called.

(Changes are currently in [snip-sometimes branch](https://github.com/hluk/CopyQ/commits/snip-sometimes).)

That fixes the issue with mouse selection, though the icon can still snip if you have "Paste mouse selection with keyboard" enabled or have some automatic commands for the selection.

**Comment by scottkosty** [comment]
@hluk thanks for your work on this! Let me know if you prefer for me to test the branch before/after merge to master.

**Comment by hluk** [comment]
@scottkosty If it's not too difficult for you, feel free to test it now. I usually keep the new stuff in a separate branch for a while to see how it works before merging it to master.

**Comment by scottkosty** [comment]
@hluk just tested and it works well, thanks! I'll keep testing on that branch and let you know if I see a problem.

**Comment by scottkosty** [comment]
> it snips also on any selection

@hluk it seems this issue (quoted above) is back. Bisect leads to aebeb020.

**Comment by hluk** [comment]
OK, fixed again.

I should try to figure out how to create a tests for the snip animation otherwise it will probably break again in future without me noticing.

**Comment by scottkosty** [comment]
> OK, fixed again.

Thanks!

> I should try to figure out how to create a tests for the snip animation otherwise it will probably break again in future without me noticing.

Not a big problem from my perspective for this issue. I'm happy to keep bothering you when it pops up again :)
