### ISSUE TITLE
Feature Suggestion: Enable "show preview" edit mode 

### ISSUE THREAD

**Issue by royharoush** [hluk/CopyQ#994]
Hi, 
Not sure if it was already submitted. 
It would be great if we could have a configuration to be ticked that enables the note to be edited (very plainly, not the entire editor module), from the "show preview" window. 
working with multiple notes simultaneously it sometimes get cumbersome to exit edit mode and move between the different notes, while you need to edit them. 
Thanks ! 
Roy 

p.s
you are a saint !

**Comment by hluk** [comment]
You already requested the feature (#673). Or is that different?

**Comment by royharoush** [comment]
essentially .. the same /going to look for my brain
you can close either of those :)
thanks !

**Comment by hluk** [comment]
> essentially .. the same /going to look for my brain

I'm occasionally getting 404 for my brain also. :)
