### ISSUE TITLE
pasting from main window is slow.

### ISSUE THREAD

**Issue by amosbird** [hluk/CopyQ#995]
When doing paste from main window, it usually takes 1-2 seconds to generate the output.

Here is the setting I use

![img-2018-08-12-152433](https://user-images.githubusercontent.com/5085485/43999655-7a10e71c-9e43-11e8-8aa5-7c1f2d101a36.png)

Is there a way to make `Enter` paste faster?

**Comment by hluk** [comment]
For me it's relatively fast. Probably depends on window manager.

You can try overriding `paste()`:

```ini
[Command]
Command="
    paste = function() {
        var x = execute(
            'xdotool',
            'keyup', 'alt', 'ctrl', 'shift', 'super', 'meta',
            'key', 'shift+Insert')
        if (!x)
            throw 'Failed to run xdotool'
        if (x.stderr)
            throw 'Failed to run xdotool: ' + str(x.stderr)
    }"
Icon=\xf0ea
IsScript=true
Name=Use xdotool to paste
```

Or override <kbd>Enter</kbd> shortcut with a command:

``` ini
[Command]
Command="
    copyq:
    var text = input()
    copy(text)
    copySelection(text)
    paste()"
HideWindow=true
Icon=\xf0ea
InMenu=true
Input=text/plain
Name=Paste Selected Items
Shortcut=enter
```

**Comment by amosbird** [comment]
Yeah, it's indeed related to wm. I've switched to bspwm and it's now much faster. Thanks!
