### ISSUE TITLE
Self replicating URL Issue 

### ISSUE THREAD

**Issue by mbakstars** [hluk/CopyQ#996]
After copy/pasting a URL it seems to continue to create entries (tons) by itself in copyq. It doesn't stop until something else is copied that isn't a URL. INI config and log attached. Using 3.5.0-1

[url issue ini.zip](https://github.com/hluk/CopyQ/files/2315902/url.issue.ini.zip)
[copyq_url issue.txt](https://github.com/hluk/CopyQ/files/2315894/copyq_url.issue.txt)

**Comment by hluk** [comment]
I cannot reproduce it with the commands you provided.

What is the app you copy URL from?

Can you try disabling the automatic commands (the ones with small clipboard icon) to see if one of them is responsible?

**Comment by mbakstars** [comment]
My apologies, I only have access to the computer during weekdays. Using Chrome Beta, and Hangouts chat (in-browser, due to suite EDU edition). I have to run today, but will try tomorrow on the disabling, and provide update.

**Comment by mbakstars** [comment]
I have tried to replicate the issue, with and without those commands triggered with no go. I will try to see if notice it again, and under what conditions. (Apologies on the delay, started school this week - wasn't prepared for the exhaustion/forgetfulness.)

**Comment by mbakstars** [comment]
It happened today. Please see attached image. It looks likes it starts with copy from beta chrome to a window/tab in chrome that is google chat, and possibly bookmarking. Do you need my flags/extension/settings, etc from chrome? It didn't stop until I copied something else (in this case a serial date for excel.)

![image](https://user-images.githubusercontent.com/31328113/45187542-7a260180-b1dd-11e8-9b4e-af0d496bf0ab.png)

**Comment by hluk** [comment]
Seems to happen because Chrome or some web app sets clipboard repeatedly. The duplicate entries are added because item tags are different each time.

What OS are you using? This shouldn't be an issue on Linux because there is some special merging behavior for text. I can fix it by using same behavior for all platforms.

It can be also issue if you use an automatic command where you add the items explicitly.

**Comment by mbakstars** [comment]
I am using Windows 10 Enterprise. Feature 1803; V-10.0.17134-b17134

**Comment by hluk** [comment]
@mbakstars Can you try [this build](https://ci.appveyor.com/project/hluk/copyq/build/1.2.1722/job/e6o6sv3t4p4p47hw/artifacts)?
