### ISSUE TITLE
TOML for configuration and export/import

### ISSUE THREAD

**Issue by mjfs** [hluk/CopyQ#997]
CopyQ uses custom INI format for configuration as well as exporting/importing commands. Switching to [TOML](https://github.com/toml-lang/toml) as a common and standard based format would significantly improve readability and handling of configuration files. What is especially inconvenient with the current INI format is manual editing (e.g. via external text based editor).

**Comment by hluk** [comment]
This is very unlikely to happen unless Qt supports the format -- Qt is basically the only dependency CopyQ requires and I would like to keep it that way.
