### ISSUE TITLE
[Request] Make CopyQ compatible with the Linux Wayland display server.

### ISSUE THREAD

**Issue by tnilzon** [hluk/CopyQ#999]
Linux (Gnome and KDE) are moving from display server Xorg to Wayland. It would be great to have CopyQ to work also under Wayland. I have tried it on Manjaro, Fedora and openSUSE with Wayland, and the present CopyQ version does not work. <https://wayland.freedesktop.org>

**Comment by hluk** [comment]
Closing this as duplicate of #27.

Can you comment in #27 on what doesn't work in Wayland (if it's not yet mentioned)?
